### ISSUE TITLE
Threats from API call not making it to log analytics workspace

### ISSUE THREAD

**Issue by boodoesgh** [Azure/Azure-Sentinel#10000]
**Describe the bug**
The Function (SentinelFuncstionOrchestrator) is able to successfully query the API for detected threats. After that the Function errors out and events are not sent to the log analytics workspace.  

**To Reproduce**
1. Deploy Abnormal data connecter from the content hub and provide Abnormal API key and log analytics workspace workspace ID/key.
2. Let the Function (SentinelFuncstionOrchestrator) run and trigger. 
3. See error

**Expected behavior**
After the API gathers the threat information, it is expected to be populated in the "ABNORMAL_THREAT_MESSAGES_CL" as shown in the data connector.

**Screenshots**
![image](https://github.com/Azure/Azure-Sentinel/assets/84816703/a353cf9b-74fc-460f-9932-087f6094cfac)

**Additional context**
Our account is licensed for various features but not all. Abnormal Support indicated the API permissions error in my screenshot are due to an unpaid feature we are not leveraging. From what I can tell, when the API query is made to "Cases" it returns "None."

**Comment by v-sudkharat** [comment]
Hi @boodoesgh, Thanks for flagging this issue, we will investigate this issue and get back to you with some updates by 27-02-2024. Thanks!

**Comment by v-sudkharat** [comment]
Hi @boodoesgh, We have gone through the solution in which the connector issue has been occurred. The Abnormal Security is a partner supported solution, in which we are not authorized to make any modification into it. So, we kindly request you could you please raise a support case with Abnormal solution support team, so they can check on it and make changes if required.

Sharing the support link - https://abnormalsecurity.com/contact
Thanks!
