### ISSUE TITLE
Auth0 data connector failed to fetch data with error UnboundLocalError: local variable 'token' referenced before assignment Stack

### ISSUE THREAD

**Issue by sandeep5234** [Azure/Azure-Sentinel#10002]
Getting below error, could you please help with this? 

<img width="491" alt="image" src="https://github.com/Azure/Azure-Sentinel/assets/41977495/594d4c27-9ba2-4cce-8bf5-73a5494ff825">

**Comment by v-sudkharat** [comment]
Hi @sandeep5234, Thanks for flagging this issue, we will investigate this issue and get back to you with some updates by 26-02-2024. Thanks!

**Comment by v-muuppugund** [comment]
Hi @sandeep5234 ,COuld you please share more details on this issue with screen shots and detailed replication steps

**Comment by sandeep5234** [comment]
@v-muuppugund and @v-sudkharat   We have customer who wants to bring Auth0 data into sentinel using Auth0 data connector.  Auth0 data connector works with Azure function so we have deployed the Azure function to pull data from Auth0. 

In Auth0 azure function we are getting below error
![image](https://github.com/Azure/Azure-Sentinel/assets/41977495/c946ef40-65ad-4fa9-8f65-8fd62569fd1c)


Please let me know if more information is required.

**Comment by jtcroninopsc** [comment]
My company is having the same issue.

**Comment by digitalarche** [comment]
@sandeep5234  @v-sudkharat @v-muuppugund 

The reason is simple: a basic rule of programming has been broken here.  

Let me explain:  
Since they've moved on to Python 3.8 and especially Runtime 4, the code that used to let things through doesn't do so now.  

In Main.py you have the Auth0Connector class, which is declared and instantiated in the Timer in its init, it declares a self.token to none and then the instantiated object launches the get_log_events method, which by default takes the self.token as the return from the function in the same _get_token() class.  

However, the UnboundErrorLocal in any advanced language specifies that when a function reuses the same variable in Local, it can no longer return global. As the doc says: Python's UnboundLocalError seems very confusing when newcomers to Python experience it for the first time. However, it is quite easy. An UnboundLocalError can occur due to two reasons in Python, one is when you are trying to access the value of a variable before it is assigned, and the second is when Python fails to differentiate between global and local variables.

That's what's happening here: just rename the variable used in the _get_token() accesstoken method and you're back in business.  

I can make the change and do a PR, but I don't know on which branch, given the number of variables, I'll leave it to the people in charge of the repo to make the change as they see fit.  

Don't hesitate to comment if there's a problem, but as far as I'm concerned, everything works.   
Thanks

**Comment by v-muuppugund** [comment]
> @sandeep5234 @v-sudkharat @v-muuppugund
> 
> The reason is simple: a basic rule of programming has been broken here.
> 
> Let me explain: Since they've moved on to Python 3.8 and especially Runtime 4, the code that used to let things through doesn't do so now.
> 
> In Main.py you have the Auth0Connector class, which is declared and instantiated in the Timer in its init, it declares a self.token to none and then the instantiated object launches the get_log_events method, which by default takes the self.token as the return from the function in the same _get_token() class.
> 
> However, the UnboundErrorLocal in any advanced language specifies that when a function reuses the same variable in Local, it can no longer return global. As the doc says: Python's UnboundLocalError seems very confusing when newcomers to Python experience it for the first time. However, it is quite easy. An UnboundLocalError can occur due to two reasons in Python, one is when you are trying to access the value of a variable before it is assigned, and the second is when Python fails to differentiate between global and local variables.
> 
> That's what's happening here: just rename the variable used in the _get_token() accesstoken method and you're back in business.
> 
> I can make the change and do a PR, but I don't know on which branch, given the number of variables, I'll leave it to the people in charge of the repo to make the change as they see fit.
> 
> Don't hesitate to comment if there's a problem, but as far as I'm concerned, everything works. Thanks

Hi @sandeep5234 / @RamAbburi  /' @jtcroninopsc / @digitalarche ,Apologies for the delayed response,will check on it and update you

**Comment by sandeep5234** [comment]
@v-muuppugund  can above recommendation be applied to Auth0 data connector in Sentinel repo? Then we can pick it up in the azure from content hub.

**Comment by v-muuppugund** [comment]
> @v-muuppugund can above recommendation be applied to Auth0 data connector in Sentinel repo? Then we can pick it up in the azure from content hub.

@sandeep5234 ,Sure,will check on it and update you

**Comment by v-muuppugund** [comment]
> > @v-muuppugund can above recommendation be applied to Auth0 data connector in Sentinel repo? Then we can pick it up in the azure from content hub.
> 
> @sandeep5234 ,Sure,will check on it and update you

Hi @sandeep5234 ,Working on it,will update you

**Comment by v-muuppugund** [comment]
Hi @sandeep5234 , Analyzed the issue and we are able to replicate the issue at your end and want to have a debugging session for further trouble shooting, so sharing an email for teams meeting,Could you please share couple of time slots or will discuss in tomorrow call

**Comment by v-muuppugund** [comment]
@sandeep5234  ,as discussed today morning call,the following are updates

- The Auth0 connector are able to replicate the issue and we are unable unable to generate token from Auth0 and working on further analysis ,will update you

**Comment by v-muuppugund** [comment]
@sandeep5234 ,working on work around approach,will update you

**Comment by RamAbburi** [comment]
@v-muuppugund Thanks for the update. Do you have any recommended configuration at Auth0 side to complete this setup.

**Comment by v-muuppugund** [comment]
> @v-muuppugund Thanks for the update. Do you have any recommended configuration at Auth0 side to complete this setup.

Sure ,Will share the configuration steps from Auth0 side

**Comment by v-muuppugund** [comment]
@RamAbburi , Please find below steps need to be done at Auth0 side,

![image](https://github.com/Azure/Azure-Sentinel/assets/139563098/9e3b763a-5d0b-4e2c-9d2c-009741aefd1c)

Step1 : Click on settings of the App and note down the credentials

2.Copy the domain
3.Get the client id value
4.Get the client secret

Step 2: Under Application properties -->select Application type as Machine to Machine
![image](https://github.com/Azure/Azure-Sentinel/assets/139563098/be880c71-820f-4310-8213-bda33bb6c63b)

 

Step 3:  under credentials tab-> Select Client secret (Post),Please find below screen shot for reference,

![image](https://github.com/Azure/Azure-Sentinel/assets/139563098/1d679005-92fa-41d1-8b9d-1316969ddbc1)

Step 4:

Under API tab, Please make sure Authorized to scopes, Please find below screen shot for reference

 
![image](https://github.com/Azure/Azure-Sentinel/assets/139563098/c94ace6c-7014-40eb-9e22-51730c0d811b)
Step 5:

Please make sure the domain value under  settings-->Environment Varaibles, please refer below screen shot for reference and other values are entered from the above step copied values and Domain should be  starts with [https://,then]https://,then click on Apply  and restart function app

![image](https://github.com/Azure/Azure-Sentinel/assets/139563098/08ac35f5-93f5-41fc-a954-85e2a03bf980)

Step 6: After all the above steps,Check in Monitor section function app below up and running
![image](https://github.com/Azure/Azure-Sentinel/assets/139563098/1240aec9-e541-4f73-bb0b-32ae1d64c876)

![image](https://github.com/Azure/Azure-Sentinel/assets/139563098/5abeba6d-3f75-41e5-bf05-62a0baf18e95)

 

Please let me know if you have any questions/ issues,

**Comment by v-sudkharat** [comment]
Hi @sandeep5234, We are waiting for your response on above shared solution. Thanks!

**Comment by sandeep5234** [comment]
@v-sudkharat  We have asked customer to confirm above instructions. Meanwhile would you be able to confirm if Azure function app will cache the token for 24 hours before asking for another token from Oauth or will it renew the token every 5 minutes when Function app executes? Because from Oauth side, customer gets limited set of machine-to-machine token per month and if Azure function app request new token every time, that will deplete customer tokens availability. 

Please confirm.

**Comment by v-muuppugund** [comment]
> @v-sudkharat We have asked customer to confirm above instructions. Meanwhile would you be able to confirm if Azure function app will cache the token for 24 hours before asking for another token from Oauth or will it renew the token every 5 minutes when Function app executes? Because from Oauth side, customer gets limited set of machine-to-machine token per month and if Azure function app request new token every time, that will deplete customer tokens availability.
> 
> Please confirm.

Hi @sandeep5234 ,What is the customer subscription plan in Auth0 based on that tokens will be limited ,Free Maximum M2M tokens is 1000 and based on the subscription plan it will be vary?

**Comment by v-muuppugund** [comment]
> > @v-sudkharat We have asked customer to confirm above instructions. Meanwhile would you be able to confirm if Azure function app will cache the token for 24 hours before asking for another token from Oauth or will it renew the token every 5 minutes when Function app executes? Because from Oauth side, customer gets limited set of machine-to-machine token per month and if Azure function app request new token every time, that will deplete customer tokens availability.
> > Please confirm.
> 
> Hi @sandeep5234 ,It will fetch token from oauth on every function app executes,What is the customer subscription plan in Auth0 based on that tokens will be limited ,Free Maximum M2M tokens is 1000 and based on the subscription plan it will be vary?

Hi @sandeep5234 ,Gentle reminder,,It will fetch token from oauth on every function app executes,What is the customer subscription plan in Auth0 based on that tokens will be limited ,Free Maximum M2M tokens is 1000 and based on the subscription plan it will be vary?

**Comment by v-muuppugund** [comment]
Hi @sandeep5234 ,Since we have not received a response in the last 5 days, we are closing your issue (https://github.com/Azure/Azure-Sentinel/issues/10002) as per our standard operating procedures. If you still need support for 	this issue, feel free to re-open at any time. Thank you for your co-operation!

**Comment by jtcroninopsc** [comment]
I tried redeploying from scratch this morning, but I am still running into errors. Just wanted to verify that the Azure deployment template was updated with the necessary changes.

**Comment by jennylynncone** [comment]
After working with Microsoft third party tech for 2 months, the actual issue is to make sure you have https:// in front of your domain, log errors shows UnboundErrorLocal however further review is a credential issue. In our case it was adding https: to our tenantname.us.auth0.com domain.

<img width="820" alt="Screenshot 2024-07-19 at 7 14 22 AM" src="https://github.com/user-attachments/assets/fd41b342-eb84-4126-9ac4-67dbe8e6f778">

**Comment by bbergstrom** [comment]
Encountered the same error and adding the missing "https://" prefix in the DOMAIN environment variable resolved the issue.
