### ISSUE TITLE
"Excessive number of failed connections from a single source (ASIM Network Session schema)" does not show proper results - watchguard firewall

### ISSUE THREAD

**Issue by jackluz84** [Azure/Azure-Sentinel#10001]
**Describe the bug**
I'm having the same issue identified here: https://github.com/Azure/Azure-Sentinel/issues/7304

But apparently some fix was applied to the Fortigate parser?

In my case, The parser does not correctly work for my Watchguard firewall syslogs. I deployed this ARM template to my workspace because I thought maybe this version was more up to date than what was included when installing from the content hub.

https://github.com/Azure/Azure-Sentinel/tree/master/Parsers/ASimNetworkSession/ARM/ASimNetworkSessionWatchGuardFirewareOS

Then i run a simple query:
ASimNetworkSessionWatchGuardFirewareOS(eventresult='Failure')

But it is not filtering out Success events.

**To Reproduce**
1. Run the built in Analytics rule that comes with "Network Session Essentials" named "Excessive number of failed connections from a single source (ASIM Network Session schema)"
2. run just this query: _Im_NetworkSession(eventresult='Failure')
3. observe too much data is returned, Success is included. This is not expected. only Failure should return.

**Expected behavior**
For the built-in Analytics rules to be effective, the filters have to work correctly. The analytics rule does not serve a purpose if it is returning Success events.

**Screenshots**
![image](https://github.com/Azure/Azure-Sentinel/assets/147873075/472ad8a0-afce-4216-80e1-0b8cf18fe964)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by jackluz84** [comment]
Any update?

**Comment by jackluz84** [comment]
> > Any update?
> > Hi @jackluz84 ,Apologies for the delayed response,Could you please share sample data to email id [i.e.v-muuppugund@microsoft.com](mailto:i.e.v-muuppugund@microsoft.com) and event failure query success events are returning that is the issue and also point me to exact parser, please correct if i miss any point.

Hello,
I sent an email as you requested including this information. I'm pasting the email below for tracking purposes.


I have several scenarios below that should help you narrow down…

I am using this built in query:

let threshold = 5000;
_Im_NetworkSession(eventresult='Failure')
| summarize Count=count() by SrcIpAddr, bin(TimeGenerated,5m)
| where Count > threshold
| extend timestamp = TimeGenerated, threshold


 

For demonstration purposes, I shorten the query to this:


_Im_NetworkSession(eventresult='Failure')

And it returns both success and failure, see screenshot. It should only return failure events.
 

I have the same behavior when NOT using the aggregated parser, and just directly the Watchgaurd parser:
 vimNetworkSessionWatchGuardFirewareOS(eventresult='Failure')

 


I also discovered when filtering using SUCCESS, the inverse of what I want, it seems to work??? So this query correctly filters out all of the failures….
vimNetworkSessionWatchGuardFirewareOS(eventresult='Success')
 



Now here is something interesting. When using NON parameterized parser, this seems to work and will filter out all of the success events….so something seems broken with the parameterized parser?
ASimNetworkSessionWatchGuardFirewareOS
| where EventResult =~ "Failure"
| project TimeGenerated,Dvc,SrcIpAddr,EventResult,EventSeverity
 

And then ultimately the “rewritten” query using ASIM non parameterized works I guess? It says it is consuming excessive resources BTW….
let threshold = 5000;
ASimNetworkSessionWatchGuardFirewareOS
| where EventResult =~ "Failure"
| summarize Count=count() by SrcIpAddr, bin(TimeGenerated,5m)
| where Count > threshold
| extend timestamp = TimeGenerated, threshold

**Comment by v-sudkharat** [comment]
@jackluz84, Noted. Thanks!

**Comment by vakohl** [comment]
Thanks for reporting. Work on this is in progress, will update by next week @jackluz84

**Comment by vakohl** [comment]
The correction is made to the parser. https://github.com/Azure/Azure-Sentinel/blob/master/Parsers/ASimNetworkSession/Parsers/vimNetworkSessionWatchGuardFirewareOS.yaml

Deployment is in progress, will be visible in all workspaces in 2-3 weeks
