### ISSUE TITLE
Cannot save updated analytic rule AccountElevatedtoNewRole

### ISSUE THREAD

**Issue by esschotenw** [Azure/Azure-Sentinel#10021]
**Describe the bug**
After installing the update of the template 'Account Elevated to New Role' from solution 'Business Email Compromise - Financial Fraud', in tab "Set Rule Logic" I encounter the following error: 'evaluate' operator: Failed to resolve column or scalar expression named 'key'
The issue is if there's no data the query will fail because it cannot generate column key that derived from column AdditionalDetails.
The (part of) query:
newlyElevated | project Id, AdditionalDetails
    | mv-expand bagexpansion=array AdditionalDetails
    | evaluate bag_unpack(AdditionalDetails)
    **| evaluate pivot(key, make_set(value))**

Since there's no data that match the query, the update will not be saved.

**To Reproduce**
1. Go to Analytic Rules
2. Click on the rule 'Account Elevated to New Role'
3. Click on the button 'Review and update'
4. Go to tab 'Set Rule Logic'
5. Wait for the error

**Expected behavior**
I can save the update no matter if there's data or not.

**Screenshots**
![image](https://github.com/Azure/Azure-Sentinel/assets/111283564/e80523b0-d247-409b-93c6-8382ef134383)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Edge
 - Version 121.0

**Comment by v-sudkharat** [comment]
Hi @esschotenw, Thanks for flagging this issue, we will investigate this issue and get back to you with some updates by 28-02-2024. Thanks!

**Comment by v-sudkharat** [comment]
Hi @esschotenw, our concern team has made the changes in the Rule and the changes will get reflect in upcoming solution version. 
Meantime, to get unblock you from this issue, please update below shared query with current one while creating the analytic rule and let us know if you still facing same issue. 
Updated query- 
```
    let auditList =
    AuditLogs
    | where TimeGenerated >= ago(14d)
    | where OperationName =~ "Add member to role completed (PIM activation)"
    | where Result =~ "success"
    | extend TargetUserPrincipalName = tostring(TargetResources[2].userPrincipalName)
    | extend displayName = tostring(TargetResources[0].displayName)
    | extend displayName2 = tostring(TargetResources[3].displayName)
    | extend ElevatedRole = iif(displayName =~ "Member", displayName2, displayName)
    ;
    let lookbackList = auditList
    | where TimeGenerated between(ago(14d)..ago(1d))
    ;
    let recentList = auditList
    | where TimeGenerated > ago(1d)
    ;
    let newlyElevated = recentList
    | join kind = leftanti lookbackList on ElevatedRole, TargetUserPrincipalName
    ;
    newlyElevated | project Id, AdditionalDetails
    | mv-expand bagexpansion=array AdditionalDetails
    | evaluate bag_unpack(AdditionalDetails)
    | extend key = column_ifexists("key", ''), value = column_ifexists("value", '')
    | evaluate pivot(key, make_set(value))
    | extend ipaddr = todynamic(column_ifexists("ipaddr", ""))
    | mv-expand ipaddr
    | project Id, InitiatingIPAddress = tostring(ipaddr)
    | join kind=rightouter newlyElevated on Id
    | extend InitiatingAppName = tostring(InitiatedBy.app.displayName)
    | extend InitiatingAppServicePrincipalId = tostring(InitiatedBy.app.servicePrincipalId)
    | extend InitiatingUserPrincipalName = tostring(InitiatedBy.user.userPrincipalName)
    | extend InitiatingAadUserId = tostring(InitiatedBy.user.id)
    | extend InitiatingIPAddress = iff(isnotempty(tostring(InitiatedBy.user.ipAddress)), tostring(InitiatedBy.user.ipAddress), InitiatingIPAddress)
    | extend ElevatedBy = iff(isnotempty(InitiatingUserPrincipalName), InitiatingUserPrincipalName, InitiatingAppName)
    | extend ElevatedUser = TargetUserPrincipalName
    | extend InitiatingAccountName = tostring(split(InitiatingUserPrincipalName, "@")[0]), InitiatingAccountUPNSuffix = tostring(split(InitiatingUserPrincipalName, "@")[1])
    | extend TargetAccountName = tostring(split(TargetUserPrincipalName, "@")[0]), TargetAccountUPNSuffix = tostring(split(TargetUserPrincipalName, "@")[1])
    | project-reorder ElevatedUser, ElevatedRole, ResultReason, ElevatedBy, InitiatingUserPrincipalName, InitiatingAadUserId, InitiatingIPAddress, TargetUserPrincipalName    
```
![image](https://github.com/Azure/Azure-Sentinel/assets/132428394/45d459f4-c97c-48b6-8aa5-7076ae5ea808)

And save the query. 
Please let us know if your issue gets resolved so we can close it from GitHub.
Thanks!

**Comment by esschotenw** [comment]
Hoi @v-sudkharat,

I've tested it and it works!
Thanks, this issue is solved!

**Comment by v-sudkharat** [comment]
@esschotenw, thanks for the update. Closing this issue. If you still need support for this issue, feel free to re-open it any time. Thank you for your co-operation.
