### ISSUE TITLE
Mimecast Secure Email Gateway (using Azure Functions)

### ISSUE THREAD

**Issue by rvluna** [Azure/Azure-Sentinel#10025]
**Is your feature request related to a problem? Please describe.**
yes, partly related to #9377

**Describe the solution you'd like**
After a solution was provided on #9377. We have deployed the solution but this caused a concern, the change made our log retention to 30 days, which is not our default.

**Describe alternatives you've considered**
I have already noted this on our documentation, but it would be helpful to:
- have this documented on the Mimecast Secure Email Gateway (using Azure Functions) connector page, to change the rententionInDays entry under line 236 / 248 (depends on changes) to set it to the desired settings
- have an option to set it without editing the code

**Additional context**
- Affected our own logs, which we lost logs and awaiting help from MS to restore if possible.

**Comment by v-sudkharat** [comment]
Hi @rvluna, This Mimecast solution is partner supported, so we are not authorized to make modification into it. We kindly request you to raise ticket with Mimecast so they can look into it and make require changes. 
Meanwhile, we are sharing steps which helps you to change retention policy of Workspace and Specific table. - 
1. To change the retention policy for workspace you can navigate to below share path and make the change in retention policy - 
![image](https://github.com/Azure/Azure-Sentinel/assets/132428394/4bce3574-3535-4b13-9fbd-da076337aa7b)

![image](https://github.com/Azure/Azure-Sentinel/assets/132428394/f23059ce-68d0-4e4a-9a65-d0b4bb426ff2)

2. To change the retention policy for specific table - Navigate to LAW > Click on Tables and select the specific table for you want to change the retention policy - 
![image](https://github.com/Azure/Azure-Sentinel/assets/132428394/2793d515-c0c7-42b4-9413-d720c4ab0af6)

Regarding the lost logs, could you please raise a Microsoft support request for this? so support team will help you to restore the lost logs.
Closing this issue from GitHub. If you still need support for this issue, feel free to re-open it any time. Thank you for your co-operation.

**Comment by rvluna** [comment]
Hi,

The concern is not about changing log retention, but what the "Mimecast Secure Email Gateway (using Azure Functions)" does when it is deployed on an existing workspace. If a customer deploys this on an existing workspace, which has say for example a log retention of 730 days. Right after you deploy this template, it will change the log retention to 30 days, which MS will automatically will delete all your logs older than 30 days.

The request to update the data connector page to state that this will set the log retention of the new workspace to 30 days, if an existing workspace will be used, state a warning as it hit us on our production.

**Comment by v-sudkharat** [comment]
@rvluna, we understand your concern, but due we are not authorized to make any modification in the solution. so due to that we request you please raise ticket with Mimecast team, so they can look into it and made those changes. Thanks!

**Comment by PCNZ** [comment]
This has been fixed now.
https://github.com/Azure/Azure-Sentinel/commit/d306787ec2b5c5d861769632ea84bc74683f595b
