### ISSUE TITLE
Query incomplete for entity field for ServicePrincipalAssignedPrivilegedRole

### ISSUE THREAD

**Issue by esschotenw** [Azure/Azure-Sentinel#10022]
**Describe the bug**
For 'ServicePrincipalAssignedPrivilegedRole' in Detections/Auditlogs, the entitymappings are filled with columns which don't exists in the kustoquery.
It's about the following:
      - identifier: Name
        columnName: **InitiatingAccountName**
      - identifier: UPNSuffix
        columnName: **InitiatingAccountUPNSuffix**

These two columns didn't exists in the query.

**To Reproduce**
See ServicePrincipalAssignedPrivilegedRole.yaml

**Expected behavior**
The two columns exists in the query

**Comment by v-sudkharat** [comment]
Hi @esschotenw, Thanks for flagging this issue, we will investigate this issue and get back to you with some updates by 28-02-2024 . Thanks!

**Comment by v-sudkharat** [comment]
Hi @esschotenw, Our concern team has made the changes in rule, and it also merged to Master. Please check it from your end and let us know if your issue gets resolved - 
![image](https://github.com/Azure/Azure-Sentinel/assets/132428394/2aad76c4-c82f-4830-83bc-f9c4fc6e6f62)

Thanks!

**Comment by esschotenw** [comment]
Hi @v-sudkharat,

Thank you for your fast response! It's solved now!
Thanks!

**Comment by v-sudkharat** [comment]
@esschotenw, thanks for the update. Closing this issue. If you still need support for this issue, feel free to re-open it any time. Thank you for your co-operation.
