### ISSUE TITLE
Log Analytics Stored function - Cannot save function if  a negative number is set as default value

### ISSUE THREAD

**Issue by JiTmun** [Azure/Azure-Sentinel#10058]
**Describe the bug**
Cannot save a stored function in **Log Analytics** if  a negative number is set as default value.

**To Reproduce**
Steps to reproduce the behavior (cf screenshot also):
1. Go to a Log Analytic Workspace
2. Got to the tile "Logs"
4. Click on "Save as function"
5. Create a parameter with a negative default value
6. The following error occurs:
"Error saving function. Error code: InvalidOperationArgument. Error message: Invalid function parameters string. Encountered possible syntax errors: 'Missing expression (11,11)', 'Expected: ')' (12,14)', 'Expected: '{' (12,14)', 'Expected: '}' (15,17)'. Please see relevant documentation 'https://docs.microsoft.com/en-us/azure/kusto/query/'."

Nota the issue is for any numeric type (int/real/long/decimal).

**Expected behavior**
negative values should be an accepted default value for int/real/decimal/long parameters of a log analytic stored function

**Screenshots**
Edge screenshot:
![image](https://github.com/Azure/Azure-Sentinel/assets/95627331/89e74149-6a07-4592-ba12-91eaa1cbe2af)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser : tested on 
            - Edge Version 121.0.2277.128 (Official build) (64-bit)
            - Firefox 123.0

**Comment by v-sudkharat** [comment]
Hi @JiTmun, Could you please let us know which sentinel solution or rule you are facing this issue. Thanks!

**Comment by JiTmun** [comment]
@v-sudkharat 
I am not sure to understand what you are asking. I updated the issue to be more precise.
The issue is happening in Microsoft Log Analytics.

**Comment by v-muuppugund** [comment]
Hi @JiTmun ,Will check and get back to you on this issue after initial analysis.

**Comment by v-sudkharat** [comment]
Hi @JiTmun, We have checked this issue and this issue require more attention from azure LAW team. We kindly request you to raise a Microsoft support request for this. so, support team can check and assist you on this. We are closing this issue from GitHub. Feel free to re-open this issue in case you have further questions. Thanks!
