### ISSUE TITLE
GCP Pub/Sub Audit Logs unable to Add New Collector

### ISSUE THREAD

**Issue by 18f-rfleming** [Azure/Azure-Sentinel#10051]
GCP Pub/Sub Audit Logs unable to Add New Collector in MS Sentinel.

I have all of the required information to add a new data collector for GCP Audit Logs, however the deployment is failing due to a missing parameter of 'dataCollectionRuleImmutableId'

This parameter isn't asked for during the setup, and I have no idea where to find it.
In fact, it makes little sense because there is technically no Data Collection Rule yet.    This setup process is supposed to be configuring that.

I'm very stuck on this one.

**Comment by v-muuppugund** [comment]
Hi @18f-rfleming ,Could you please share more details on this issue with replication steps and screen shots

**Comment by 18f-rfleming** [comment]
> Hi @18f-rfleming ,Could you please share more details on this issue with replication steps and screen shots

Hello.  I tried the process again this morning, and I'm receiving a different error during the deployment.
I've attached some screenshots.

The new deployment error is as follows:
Connectivity check failed: Status code:GCPB40001, Message: An unknown exception resulted in the failure to authenticate: Google.Apis.Requests.RequestError Permission 'iam.serviceAccounts.getAccessToken' denied on resource (or it may not exist). [403] Errors [ Message[Permission 'iam.serviceAccounts.getAccessToken' denied on resource (or it may not exist).] Location[ - ] Reason[forbidden] Domain[global] ]

Would this be an issue on the GCP side?
![deployment_error](https://github.com/Azure/Azure-Sentinel/assets/161374693/d092d484-0f04-4ae9-8605-a4710bc0b0fc)
![error](https://github.com/Azure/Azure-Sentinel/assets/161374693/0a854277-98b6-4067-ba81-7077ca9a9bc6)

**Comment by v-muuppugund** [comment]
> > Hi @18f-rfleming ,Could you please share more details on this issue with replication steps and screen shots
> 
> Hello. I tried the process again this morning, and I'm receiving a different error during the deployment. I've attached some screenshots.
> 
> The new deployment error is as follows: Connectivity check failed: Status code:GCPB40001, Message: An unknown exception resulted in the failure to authenticate: Google.Apis.Requests.RequestError Permission 'iam.serviceAccounts.getAccessToken' denied on resource (or it may not exist). [403] Errors [ Message[Permission 'iam.serviceAccounts.getAccessToken' denied on resource (or it may not exist).] Location[ - ] Reason[forbidden] Domain[global] ]
> 
> Would this be an issue on the GCP side? ![deployment_error](https://private-user-images.githubusercontent.com/161374693/308184773-d092d484-0f04-4ae9-8605-a4710bc0b0fc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkwNDIzMTksIm5iZiI6MTcwOTA0MjAxOSwicGF0aCI6Ii8xNjEzNzQ2OTMvMzA4MTg0NzczLWQwOTJkNDg0LTBmMDQtNGFlOS04NjA1LWE0NzEwYmMwYjBmYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIyN1QxMzUzMzlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zZDk1M2QwMWU4NDg0MzExZTMxM2UyMzEzYWE5ZWZmZmZhZThlZGMzNTA2MzdmYzZlYWNhOTQzYWRmZmNmN2I0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.rSJtd1QZaoHEFWDpxjHpKlZrebTCcTMvx7C5rwjIE90) ![error](https://private-user-images.githubusercontent.com/161374693/308184792-0a854277-98b6-4067-ba81-7077ca9a9bc6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkwNDIzMTksIm5iZiI6MTcwOTA0MjAxOSwicGF0aCI6Ii8xNjEzNzQ2OTMvMzA4MTg0NzkyLTBhODU0Mjc3LTk4YjYtNDA2Ny1iYTgxLTcwNzdjYTlhOWJjNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIyN1QxMzUzMzlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01MDMzMTVmMWQ3MDUwOTBjMmExMGUyMWFjMjdiZDk3ZDQ1ZDBmZTJhOWI2MmFhOTY4ZGNjZThlNWE0MDQwNTQzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.TuoqMADNfPvj3ETuHOwrvW2CCxtX1fz1OcNHVAgfYtI)

Hi @18f-rfleming ,Its a fresh deployment or redeployment? , if not fresh deployment Could you please do fresh deployment with arm template and let me know if issue still exists

**Comment by 18f-rfleming** [comment]
> Hi @18f-rfleming ,Its a fresh deployment or redeployment? , if not fresh deployment Could you please do fresh deployment with arm template and let me know if issue still exists

This is a fresh deployment.

**Comment by v-muuppugund** [comment]
> > Hi @18f-rfleming ,Its a fresh deployment or redeployment? , if not fresh deployment Could you please do fresh deployment with arm template and let me know if issue still exists
> 
> This is a fresh deployment.

Hi @18f-rfleming ,Will try to replicate the issue from my end and will update you

**Comment by 18f-rfleming** [comment]
@v-muuppugund Is there any documentation you can link to which would describe the GCP permissions that would need to be configured for the GCP service account?    I'm fairly certain that this issue I'm experiencing is on the GCP side.    Our GCP team is asking for documentation.

**Comment by v-muuppugund** [comment]
> @v-muuppugund Is there any documentation you can link to which would describe the GCP permissions that would need to be configured for the GCP service account? I'm fairly certain that this issue I'm experiencing is on the GCP side. Our GCP team is asking for documentation.

@18f-rfleming  Apologies for the delayed response,please find below link for the documenatation
`https://learn.microsoft.com/en-us/azure/sentinel/connect-google-cloud-platform?tabs=terraform%2Cauditlogs`

**Comment by v-muuppugund** [comment]
> > @v-muuppugund Is there any documentation you can link to which would describe the GCP permissions that would need to be configured for the GCP service account? I'm fairly certain that this issue I'm experiencing is on the GCP side. Our GCP team is asking for documentation.
> 
> @18f-rfleming Apologies for the delayed response,please find below link for the documentation `https://learn.microsoft.com/en-us/azure/sentinel/connect-google-cloud-platform?tabs=terraform%2Cauditlogs`

@18f-rfleming ,Gentle reminder,Could you please check documentation link and let me know,
https://learn.microsoft.com/en-us/azure/sentinel/connect-google-cloud-platform?tabs=terraform%2Cauditlogs

**Comment by 18f-rfleming** [comment]
Hello.  Yes, I have found and went through the documentation.
However, there is not enough detail on how to configure the GCP service account and what specific permissions it requires within GCP.
I have a support ticket open with Microsoft to review the configuration.

**Comment by v-muuppugund** [comment]
> Hello. Yes, I have found and went through the documentation. However, there is not enough detail on how to configure the GCP service account and what specific permissions it requires within GCP. I have a support ticket open with Microsoft to review the configuration.

Hi @18f-rfleming AS i am working on other GCP issue i.e. (https://github.com/Azure/Azure-Sentinel/pull/9687) ,will post updates there and its a duplicate issue,we are closing your issue (https://github.com/Azure/Azure-Sentinel/issues/10051) as per our standard operating procedures. If you still need support for 	this issue, feel free to re-open at any time. Thank you for your co-operation
