### ISSUE TITLE
Update connectors to use the AMA agent and "Log Ingestion API"

### ISSUE THREAD

**Issue by o-l-a-v** [Azure/Azure-Sentinel#10067]
### OMSAgent → AMA

The old Log Analytics agent will stop working 31st of August 2024:

* https://azure.microsoft.com/en-ca/updates/were-retiring-the-log-analytics-agent-in-azure-monitor-on-31-august-2024/

Thus, the [Cisco Meraki connector](https://github.com/Azure/Azure-Sentinel/tree/master/Solutions/CiscoMeraki), and probably other connectors in this repo, must be updated.

Example of already updated connectors: 

* [Fortinet FortiGate Next-Generation Firewall connector for Microsoft Sentinel](https://github.com/Azure/Azure-Sentinel/tree/master/Solutions/Fortinet%20FortiGate%20Next-Generation%20Firewall%20connector%20for%20Microsoft%20Sentinel) already has been.

### HTTP Data Collector API → Log Ingestion API

The HTTP Data Collector API will stop working 14th of September 2026:

* <https://learn.microsoft.com/en-us/azure/azure-monitor/logs/data-collector-api>
* <https://learn.microsoft.com/en-us/azure/azure-monitor/logs/custom-logs-migrate>

Example of connectors that must be updated:

* [Cloudflare connector](https://github.com/Azure/Azure-Sentinel/tree/master/Solutions/Cloudflare)

## Describe the solution you'd like

1. Update connectors to use AMA and "Log Ingestion API" long before August 2024 to give us time to migrate.
2. Create a roadmap to keep us updated on the progress for various affected connectors.

## Describe alternatives you've considered

None.

## Additional context

None.

**Comment by v-sudkharat** [comment]
Hi @o-l-a-v, Thanks for flagging this issue, we will investigate this issue and get back to you with some updates by 06-03-2024. Thanks!

**Comment by v-rusraut** [comment]
Hi @o-l-a-v,
We are checking with the respective team, we will provide you an update soon.
Thanks

**Comment by v-rusraut** [comment]
Hi @o-l-a-v,
We got response from respective team. They will be working on these connectors soon, they don't provide any ETA.
If we got any update related to this, we will inform you. currently closing this issue.
Thanks

**Comment by lux209** [comment]
+1 for the meraki connector and also for the VMware one that also only support OMS at the moment

**Comment by InfiniteInsight** [comment]
Any ETA yet? @v-rusraut

**Comment by subhashkrishnan-ai** [comment]
Hey, is there any way we can get this logs from data collector endpoints ? 
MS link- https://learn.microsoft.com/en-us/azure/azure-monitor/logs/custom-logs-migrate

**Comment by JustinGrote** [comment]
Stuck here too, the OMS agent goes EOL in 1 month and there is no solution that has been specified for bringing Cisco Meraki data into Sentinel via the AMA. I guess we'll have to go off the reservation and report back.

**Comment by JustinGrote** [comment]
As an unsupported workaround, I have used logstash with the new DCR based connector to get syslogs into Sentinel. This works on both linux and windows.
https://learn.microsoft.com/en-us/azure/sentinel/connect-logstash-data-connection-rules

**Comment by JustinGrote** [comment]
> @JustinGrote yeah, we’re using Fluent Bit now with `direct` kind DCRs.
> 
> Any chance you’ve tackled ASA logs into CommonSecurityLog without OMS/MMA/OMS? I want to avoid recreating the wheel with whatever black box parsing MS is doing to get them into CEF

Not particularly, I'm mostly making things to match the ASIM schemas to make things easier on our hunters

**Comment by lux209** [comment]
I was informed today that a new collector just came out to support VMware, Meraki and many other log types, check the data connector named "Custom Logs AMA", I did not test it yet but it is looking to be the solution for AMA

**Comment by lux209** [comment]
> > @JustinGrote yeah, we’re using Fluent Bit now with `direct` kind DCRs.
> > Any chance you’ve tackled ASA logs into CommonSecurityLog without OMS/MMA/OMS? I want to avoid recreating the wheel with whatever black box parsing MS is doing to get them into CEF
> 
> Not particularly, I'm mostly making things to match the ASIM schemas to make things easier on our hunters

For ASA you can use the Common Event Format (CEF) via AMA connector as far as I know

**Comment by InfiniteInsight** [comment]
> I was informed today that a new connector just came out to support VMware, Meraki and many other log types, check the data connector named "Custom Logs AMA", I did not test it yet but it is looking to be the solution for AMA

I don't see the "Custom Logs AMA" connector you mentioned. Do you mean the "Common Event Format (CEF) via AMA" connector?

**Comment by o-l-a-v** [comment]
Maybe this one?

* <https://github.com/Azure/Azure-Sentinel/tree/master/Solutions%2FCustomLogsAma>

**Comment by lux209** [comment]
I mean this: https://learn.microsoft.com/en-us/azure/sentinel/unified-connector-custom-device?tabs=rsyslog

I have it on my side on the sentinel content hub named "Custom Logs AMA"

**Comment by JustinGrote** [comment]
Agreed, huge limitation of AMA, it requires Azure Arc to work. Lots of MSSPs have probe VMsfor syslog in other client tenants, and it's not supported to onboard an Azure VM to Arc in another tenant, making it a huge gap (apparently MS assumes noone runs things in Azure, funny enough)

For us, Logstash/Fluent Bit was the only solution to this (Fluent Bit being way less resource intensive)

**Comment by lux209** [comment]
> Agreed, huge limitation of AMA, it requires Azure Arc to work. Lots of MSSPs have probe VMsfor syslog in other client tenants, and it's not supported to onboard an Azure VM to Arc in another tenant, making it a huge gap (apparently MS assumes noone runs things in Azure, funny enough)
> 
> For us, Logstash/Fluent Bit was the only solution to this (Fluent Bit being way less resource intensive). We originally tried "tunneling" client syslogs back to an azure collector on our side using dtlspipe, but the solution was too flaky and didn't allow for onsite log filtering to reduce traffic.

I m also working for a mssp but we are not getting the logs in our own sentinel. Each client has it own instance in their tenant and they grant us the access through an azure app.

For your case I would most likely use rsyslog to forward the logs to your own collector with ama. Rsyslog is pretty reliable, you just need a secure connection for the traffic.

**Comment by JustinGrote** [comment]
" you just need a secure connection for the traffic."

Minor detail there, good luck setting up IPSec tunnels with every MSSP customer. That's why we use Fluent Bit, we just ingest directly into a DCR via HTTPS, no secure connection or overhead required (DCRs are free). You can even make DCRs direct now without a DCE, using kind: direct and the latest API

**Comment by lux209** [comment]
You can use secure syslog using tls

**Comment by JustinGrote** [comment]
> You can use secure syslog using tls
You're still saying a rsyslog vm at the customer site, then tls'd to some public ip of an azure vm on our side, just to then get it into the collector with AMA (which you would need 1 collector per customer and they couldn't run in azure because you couldn't tie it to the customer workspace)

vs.

a single windows/linux vm/container at the customer site that ingests directly to a DCR and can filter locally, minimizing bandwidth to both.

yeah I'll take the second options thanks.

**Comment by lux209** [comment]
But if you finally send the log to the customer workspace why not just use arc and ama in the customer collector hosted in their environment?

Anyway this is not the subject of the thread

**Comment by lux209** [comment]
I can understand, on our side we have nothing to hide on the collectors, they just have the ama agent with full standard configuration.
