### ISSUE TITLE
Issue with parser for CISCO ISE in Sentinel

### ISSUE THREAD

**Issue by sandeep5234** [Azure/Azure-Sentinel#10070]
Cisco ISE Parser in Sentinel not parsing the Values correctly in Log analytics workspace. 

#9746   In this issue there was a parser provided but that doesn't work for the data we have from Cisco ISE devices.

For Example, see this image.
![image](https://github.com/Azure/Azure-Sentinel/assets/41977495/f46f29f1-c039-486d-9a73-58fee2958747)

**Comment by v-sudkharat** [comment]
Hi @sandeep5234, Thanks for flagging this issue, we will investigate this issue and get back to you with some updates by 08-03-2024. 
Please share the sample data with us. it helps us to check on it. 
Thanks!

**Comment by v-sudkharat** [comment]
Hi @sandeep5234, Could you please provide the sample data to us. Thanks!

**Comment by v-sudkharat** [comment]
Hi @sandeep5234, We are waiting for your response, And also could you please check on the configuration which done at Cisco ISE GUI portal which done correctly. 

Thanks!

**Comment by v-sudkharat** [comment]
Hi @sandeep5234, We are waiting for your response. Thanks!

**Comment by sandeep5234** [comment]
@v-sudkharat   sorry for late reply, Customer is still getting back to me with data. I will update soon.

**Comment by sandeep5234** [comment]
Hi @v-sudkharat where should I share the sample data?

**Comment by v-sudkharat** [comment]
Hi @sandeep5234, you can share with us on - v-sudkharat@microsoft.com mail id. Thanks!

**Comment by sandeep5234** [comment]
@v-sudkharat   Data sample shared on provided email. Thank you.

**Comment by v-sudkharat** [comment]
@sandeep5234, Received. Thanks!

**Comment by v-sudkharat** [comment]
Hi @sandeep5234, We have checked your shared sample data. The `SyslogMessage `is not in correct format, and due to that the `Parser` is not parsing the data correctly. 
So, Could you please check the configuration which is done at Cisco ISE GUI portal is done correctly. 
You make check the logging categories with below shared steps- 
![image](https://github.com/Azure/Azure-Sentinel/assets/132428394/66084705-5825-42e2-a4cb-6f9a8ac9baf0)

And if you are not receiving logs then needed to configure the Logging Category with below shared path in Cisco portal- 
` Administration >System >Logging >Logging Categories `

Thanks!

**Comment by v-sudkharat** [comment]
Hii @sandeep5234, Could you please check on above comment and let us know your feedback. Thanks!

**Comment by sandeep5234** [comment]
@v-sudkharat  I will check with customer

**Comment by v-sudkharat** [comment]
@sandeep5234, Sure. Please let us know once it done. Thanks!

**Comment by v-sudkharat** [comment]
Hey @sandeep5234, Any update on CIsco side configuration. Thanks!

**Comment by v-muuppugund** [comment]
Hi @sandeep5234 ,Gentle reminder,Could you please update us on this issue

**Comment by sandeep5234** [comment]
Hi @v-muuppugund  we are still waiting for customer response. As soon as I receive the response I will update here

**Comment by v-sudkharat** [comment]
@sandeep5234, Ok. Please let us know once you get update from customer. Thanks!

**Comment by v-sudkharat** [comment]
Hey @sandeep5234, Any response from customer about configuration?

**Comment by v-sudkharat** [comment]
Hi @sandeep5234, We are waiting for your response on above comment, could you please check with the customer and let us know. 
Thanks!

**Comment by sandeep5234** [comment]
@v-sudkharat apologies for late reply. Customer had made changes. Most of the Field are mapped but below fields are still not mapped correctly.
<img width="459" alt="image" src="https://github.com/Azure/Azure-Sentinel/assets/41977495/5002cd8b-d032-4ff3-b5c7-00f11611d32d">

**Comment by v-sudkharat** [comment]
@sandeep5234, Could you please share the updated parser result with us, so we can check the on this. Thanks!

**Comment by sandeep5234** [comment]
@v-sudkharat will the updated Parser be available in Azure Sentinel Repo? Or where should I grab it from?

**Comment by sandeep5234** [comment]
@v-sudkharat  I have found the updated parser and the results looked better with it. For now it looks ok.

**Comment by v-sudkharat** [comment]
> @v-sudkharat I have found the updated parser and the results looked better with it. For now it looks ok.

@sandeep5234, Noted, so if your issue get resolve, can you please confirm with us so we can close it from GitHub. 

Thanks!

**Comment by v-sudkharat** [comment]
@sandeep5234, Thanks for the confirmation. closing this issue. If you still need support for this issue, feel free to re-open it any time. Thank you for your co-operation.
