### ISSUE TITLE
Customize Sentinel activity template wizard error

### ISSUE THREAD

**Issue by mgijo** [Azure/Azure-Sentinel#10087]
**Describe the bug**
Unable to create few of the out of the box entity activity templates

**To Reproduce**
When creating the entity activity rule I get the below error and it doesn't allow me to continue with the creation:-

**At least one entity identifier must be selected and added to the query.. Input fields "AzureResource_ResourceId" must be part of query input list: StartTimeISO, EndTimeISO, StartTimeUTC, EndTimeUTC, ReferenceTime, Count.**

**Expected behavior**
Expect the activity templates to pass through without any errors

**Screenshots**
<img width="517" alt="image" src="https://github.com/Azure/Azure-Sentinel/assets/83291280/dcf017c4-63be-4bab-98e8-0ad376cec780">

**Additional context**

**Comment by v-sudkharat** [comment]
Hi @mgijo , Thanks for flagging this issue, Could you please share more context about this issue, like which content/solution you are facing this issue. Thanks!

**Comment by mgijo** [comment]
@v-sudkharat , the issue persists within Sentinel **Entity Behavior** blade ---> **Customize Entity page** ---> **Activity templates** section

<img width="672" alt="image" src="https://github.com/Azure/Azure-Sentinel/assets/83291280/c2cc2587-cd20-4c07-b938-c8b36e8971fe">

<img width="609" alt="image" src="https://github.com/Azure/Azure-Sentinel/assets/83291280/3defcdbd-26ee-4d16-aab1-f44092be34b0">

**Comment by v-sudkharat** [comment]
Hi @mgijo, We are waiting for your response on above comment. Thanks!

**Comment by v-sudkharat** [comment]
Hi @mgijo, Gentle Reminder: We are waiting for your response on this issue. If you still need to keep this issue active, please respond to it in the next 2 days. If we don't receive a response by 14-03-2024 date, we will be closing this issue. 		
Thanks!

**Comment by v-sudkharat** [comment]
Hi @mgijo, since we have not received a response in the last 5 days, we are closing your issue #10087 as per our standard operating procedures. If you still need support for this issue, feel free to re-open at any time. Thank you for your co-operation.
