### ISSUE TITLE
Issue with 'Intro to KQL' workbook

### ISSUE THREAD

**Issue by MngEnv455629-Admin** [Azure/Azure-Sentinel#10094]
**Describe the bug**
There is a workbook named 'Intro to KQL' this workbook enables the users to learn KQL by themselves using some exercises. 

Select Section does not work. Followed the Help instructions yet the issue is not resolved by following the instructions. 
<img width="504" alt="Intro to Kql error 2" src="https://github.com/Azure/Azure-Sentinel/assets/155492918/34bc35c4-be4c-4fff-b141-64ffecc506a0">
 

**To Reproduce**
Below are the steps given in the workbook to fix the issue, but we do not see 'mark as trusted'
Fixing the Error
The error you are seeing is due to workbooks in Azure requiring external data sources to be marked as trusted. As this workbook pulls all of its content from GitHub, the repository must be marked as trusted. This is on a user session level and cannot be set within the workbook template. To fix the error:

Go into edit mode.
Under the hidden parameters at the top of the page, click edit.
Check the box next to json.
Click on the edit pencil icon.
Click 'run query'.
Click 'mark as trusted'.
Click save.
Exit edit mode.
The error should be gone and the content will be loaded.

**Expected behavior**
The users should be able to practice KQL exercises. 

**Screenshots**
<img width="1055" alt="Intro to Kql error 1" src="https://github.com/Azure/Azure-Sentinel/assets/155492918/b42ff0e4-f46e-4f5a-af89-0c54ce96533a">

**Comment by v-sudkharat** [comment]
Hi @MngEnv455629-Admin, Thanks for flagging this issue, we will investigate this issue and get back to you with some updates by 08-03-2024. Thanks!

**Comment by v-sudkharat** [comment]
Hi @MngEnv455629-Admin, Sharing the step's to configure the workbook- 

1. Click on edit tab -
![image](https://github.com/Azure/Azure-Sentinel/assets/132428394/6bf50b25-c032-4232-a49b-79d3f4a0d5a5)

2. Select check box of json and click on edit -
![image](https://github.com/Azure/Azure-Sentinel/assets/132428394/b49c86e6-dbc3-436d-ad7c-6f802b71bfd1)

3. Click in check box which is highlighted below and run the query -
![image](https://github.com/Azure/Azure-Sentinel/assets/132428394/e022ce14-3d7a-4094-b1d6-59d1469788c9)

4.
![image](https://github.com/Azure/Azure-Sentinel/assets/132428394/b761308f-f9e7-43f5-bb85-f35c7f0cb6ce)

5. Once the query run, check on save and chick on done editing- 
![image](https://github.com/Azure/Azure-Sentinel/assets/132428394/fada0b5d-befd-4320-86ab-37148d39a59d)

6. 
![image](https://github.com/Azure/Azure-Sentinel/assets/132428394/36b28b37-9188-4f55-906e-0838507d8831)

Please let us know if you still facing the issue. 
Thanks!

**Comment by v-sudkharat** [comment]
Hi @MngEnv455629-Admin, Waiting for your response on above comment. Thanks!

**Comment by v-sudkharat** [comment]
Hi @MngEnv455629-Admin, Gentle Reminder: We are waiting for your response on this issue. If you still need to keep this issue active, please respond to it in the next 2 days. If we don't receive a response by 14-03-2023 date, we will be closing this issue. 		
Thanks!

**Comment by MngEnv455629-Admin** [comment]
Acknowledge the email.

Let me try your solution.

Regards,
________________________________

**Comment by MngEnv455629-Admin** [comment]
This works. Thank you
________________________________

**Comment by v-sudkharat** [comment]
@MngEnv455629-Admin, Welcome. Closing this issue. If you still need support for this issue, feel free to re-open it any time. Thank you for your co-operation.
