### ISSUE TITLE
Deprecated dependencies in S3toSentinel Lambda 

### ISSUE THREAD

**Issue by lmarshman-caci** [Azure/Azure-Sentinel#10101]
Amazon have deprecated the .NET Core 3.1 runtime in AWS, as such we are looking to update to a supported runtime framework in AWS.

It looks as though the provided function has .NET Core 3.1 listed in the dependencies, which is preventing the functon from detecting the updated runtime framework (.NET6) and thus fail. 

I have attempted to manually update the S3toSentinel.deps.json and S3toSentinel.runtimeconfig.json and provide the correct framework, but to no avail. 

For context, here is the error presented by AWS Lambda when testing the function with the .NET6 runtime:
![image](https://github.com/Azure/Azure-Sentinel/assets/115151660/173450bd-7844-4482-b3c5-2f16781cc639)

And here are what I believe to be the offending lines from S3toSentinel.deps.json and S3toSentinel.runtimeconfig.json, respectively:
![image](https://github.com/Azure/Azure-Sentinel/assets/115151660/ee7212bc-4a4a-4a11-a6b2-e075b3853f9d)
![image](https://github.com/Azure/Azure-Sentinel/assets/115151660/6b936cb8-2740-4a6d-8874-f8ed371d3aac)

**Comment by lmarshman-caci** [comment]
Hi @v-rusraut, that's brilliant.
Thanks so much for the swift response!

**Comment by v-rusraut** [comment]
Hi @lmarshman-caci ,
Please provide more details about this issue or provide repro steps.
Thanks

**Comment by lmarshman-caci** [comment]
Hi @v-rusraut, please see screenshots attached to original post for log output from AWS Lambda, along with what I believe to be the lines responsible in the dependencies. 

To reproduce, upgrade the Lambda runtime framework to a newer .NET version within AWS and trigger a test event from the AWS console.
The below output will be returned when running the function on a runtime other than .NET Core 3.1:
![310585898-173450bd-7844-4482-b3c5-2f16781cc639](https://github.com/Azure/Azure-Sentinel/assets/115151660/8e8f01bc-0025-4134-b88a-b28a6f2b94e4)

Please see this page from the AWS documentation around runtime deprecation: https://docs.aws.amazon.com/lambda/latest/dg/lambda-runtimes.html#runtime-deprecation-levels

.NET Core 3.1 was fully deprecated on 03/05/2023, meaning it is no longer possible to deploy the provided Lambda function with the current dependency on this framework. 

Hope this info is of use, please let me know if there's anything else I can provide from my end to assist. 

Cheers,
Leith

**Comment by v-rusraut** [comment]
Hi @lmarshman-caci ,
Thanks for provide more information about issue, we will provide you an update till 22 Mar 2024.

**Comment by v-muuppugund** [comment]
Hi @lmarshman-caci ,Could you please confirm this the data connector i.e. https://github.com/Azure/Azure-Sentinel/tree/master/DataConnectors/S3-Lambda ,so will work further analysis on replicating the issue

**Comment by lmarshman-caci** [comment]
@v-muuppugund Hi there, that's correct - specifically, it's the two aforementioned files from the S3toSentinel.zip

Many thanks!

**Comment by v-muuppugund** [comment]
@lmarshman-caci ,Working on replicating the issue,will update you

**Comment by v-muuppugund** [comment]
Hi @lmarshman-caci ,Working on environment setup,will update you

**Comment by v-muuppugund** [comment]
Hi @lmarshman-caci ,The following is the status
1.Set up done for prerquisites for environment
2.AWS lamda function created
3.Working on next steps for issue replication once done ,will update you and will work on changes for the issue.

**Comment by v-muuppugund** [comment]
> Hi @lmarshman-caci ,The following is the status 1.Set up done for prerequisites for environment 2.AWS lamda function created 3.Working on next steps for issue replication once done ,will update you and will work on changes for the issue.

Hi @lmarshman-caci ,still need some time for completing the environment setup and replicating the issue,will update you

**Comment by lmarshman-caci** [comment]
Hi @v-muuppugund, that's great - thank you for keeping us posted, it is much appreciated!

**Comment by v-muuppugund** [comment]
Hi @lmarshman-caci ,facing an issue while completing the environment setup ,working on it,will update you

**Comment by v-muuppugund** [comment]
Hi @lmarshman-caci ,There is a deprecation of .NET core and unable to repo the issue unable to create lamda functons with .net core3.1 as its nor supported ,so we need to create fresh LaMDA functions with .NET frame work, please find below screen shot for reference

Completed the analysis for this requirement and will be picking up in our queue and will update you once the changes have been completed.

![image](https://github.com/Azure/Azure-Sentinel/assets/139563098/8d1accc1-8af5-4b8e-9004-aa1a61fdba44)

**Comment by lmarshman-caci** [comment]
Hi @v-muuppugund, many thanks for the update. 
Just to confirm, this deprecation was the cause for issue on our end also.

Appreciate you looking into this, I'll keep an eye out for further updates.

**Comment by lmarshman-caci** [comment]
Hi @v-muuppugund, hope you are well.
Just checking to see if there has been any movement on this as the issue appears to have been marked as closed.

Please could you let me know if there have been any updates?

Many thanks in advance!
