### ISSUE TITLE
App Insights Workspace Id in DigitalShadows connector

### ISSUE THREAD

**Issue by devang-metron** [Azure/Azure-Sentinel#10100]
In DigitalShadows Microsoft Sentinel connector, recently one new field is introduced due to changes mentioned [here](https://learn.microsoft.com/en-us/azure/azure-monitor/app/convert-classic-resource).

Can you please elaborate if it is why it is mandatory for new installations?

![image](https://github.com/Azure/Azure-Sentinel/assets/76464285/378d80a3-3a7e-4e1a-8ac8-adbb3f6938d6)

**Comment by v-sudkharat** [comment]
Hi @devang-metron, As Classic Application Insights is retired on 29 February 2024, so you should do your migration from Classic Application Insights to Log Analytic Workspace. To do this, it is mandatory to fill App Insights Workspace Resource ID in new installations. In simple term now onwards, you will be able to see the app inside data into the log analytic workspace going forward. 

Thanks!

**Comment by devang-metron** [comment]
Hey @v-sudkharat ,
What if I don't want to add this?
Shouldn't the app work without it?

Thanks,
Devang

**Comment by v-sudkharat** [comment]
Hi @devang-metron, 
1. When you do the fresh custom deployment using the template and not filled the - App Insights Workspace Resource ID, then the deployment gets failed. 
2. If you have the existing app installed, it will not stop the working, but later on you need to do the configuration it with Manul configuration to use the new features and improvements. 
Sharing the MS-doc for reference - https://learn.microsoft.com/en-us/azure/azure-monitor/app/convert-classic-resource

Thanks!

**Comment by devang-metron** [comment]
Hey @v-sudkharat,

Thanks for the information.

**Comment by v-sudkharat** [comment]
@devang-metron, Welcome.
