### ISSUE TITLE
Security Operations Efficiency is not working or loading

### ISSUE THREAD

**Issue by MAbdelkader99** [Azure/Azure-Sentinel#10119]
**Describe the bug**
Security Operations Efficiency workbook is not working on a specific customer tenant and just stuck on loading state "not even reaching to the state of selecting the workspace , subscription , etc"

**To Reproduce**
Tried different networks "even personal"
tried deleting the template and installing it again
Tried selecting different region 
I have the needed permission "Contributor"
Tried many browsers and other team members machines
it never worked since the start of adopting sentinel
on my test lab it works

Cheers

**Comment by v-sudkharat** [comment]
Hi @MAbdelkader99, Thanks for flagging this issue, we will investigate this issue and get back to you with some updates by 15-03-2024. Thanks!

**Comment by v-sudkharat** [comment]
Hey @MAbdelkader99, Could you please share the failure screenshot with us and also let us know from which solution you have installed this workbook. Thanks!

**Comment by v-sudkharat** [comment]
@MAbdelkader99, Happy to assist you. Closing this issue. If you still need support for this issue, feel free to re-open it any time. Thank you for your co-operation.
