### ISSUE TITLE
Incident active status 

### ISSUE THREAD

**Issue by shipothana** [Azure/Azure-Sentinel#10114]
Hi Team,
May I know if a sentinel incident will trigger in the Sentinel Incident tab any new events matching a particular rule will add the incident or not?
 If not added, how many days will the incident be active on the console?
NRT rules have the capability of adding a new event to the incident?
Kindly let me know if Sentinel has the capability or not?

**Comment by v-sudkharat** [comment]
Hi @shipothana, Thanks for flagging this issue, we will investigate this issue and get back to you with some updates by 14-03-2024 Thanks!

**Comment by v-muuppugund** [comment]
Hi @shipothana ,As discussed yesterday, the following ,will analyze in detail and share an update.

1. Same event update to an incident /alert
2. Incident inactive status

**Comment by shipothana** [comment]
Hi,

Thanks for your update!

Please give me the update as soon as feasible while I wait for your response.

Regards
Siva Pothana
Senior SOC Engineer ,IT Security Service Operations
Alcon Laboratories (India) Private Limited
M: +91-9177313529
***@***.******@***.***>
***@***.***<https://www.alcon.com/>  ***@***.***

**Comment by v-muuppugund** [comment]
Hi @shipothana ,After initial analysis found the following,need some more time to share further outcomes

1. There is no option as of now to update an existing same event update for an incident /alert
2. There is no incident inactive status

**Comment by v-muuppugund** [comment]
Hi @shipothana , Want to discuss as its a enhancement at sentinel,trying to reach over teams on this discussion

**Comment by shipothana** [comment]
Please proceed to close this ticket.

**Comment by v-sudkharat** [comment]
@shipothana, thanks for response. closing this issue. If you still need support for this issue, feel free to re-open it any time. Thank you for your co-operation.
