### ISSUE TITLE
Something wrong while getting the results. Exception error text: Unable to find the server at oauth2.googleapis.com

### ISSUE THREAD

**Issue by zemolino** [Azure/Azure-Sentinel#10113]
Describe the bug:
The bug is occurring within a function named GWorkspaceReports-QueueTrigger. It seems that there's an issue with connecting to the server at **oauth2.googleapis.com** and **admin.googleapis.com** resulting in a TransportError.

The errors: 
Something wrong while getting the results. Exception error text: Unable to find the server at oauth2.googleapis.com Something wrong. Exception error text: Unable to find the server at oauth2.googleapis.com Something wrong while getting the results. Exception error text: Unable to find the server at admin.googleapis.com

Related connector: https://github.com/Azure/Azure-Sentinel/tree/master/Solutions/GoogleWorkspaceReports/Data%20Connectors/GWorkspaceReportsAPISentinelConn

To Reproduce:
This error seems to be happening during the execution of a specific function triggered by a queue. To reproduce the behavior, follow these steps:

Trigger the function associated with the queue.
Monitor the execution of the function.
Observe the error occurring when attempting to connect to oauth2.googleapis.com and admin.googleapis.com.
Expected behavior:
The function should execute without any errors and successfully connect to oauth2.googleapis.com and admin.googleapis.com

This happens sometimes in the code provided.

**Comment by v-muuppugund** [comment]
Hi @zemolino , Could you please share more details of invocation logs and stack traces from app insights to v-muuppugund@microsoft.com

**Comment by v-sudkharat** [comment]
Hi @zemolino, Gentle Reminder: Could you please confirm if you have shared the requested details on above mail id and let us know in the next 2 days. If we don't receive a response by 03-04-2024 date, we will be closing this issue. 		
Thanks!

**Comment by v-muuppugund** [comment]
Hi @zemolino ,Since we have not received a response in the last 5 days, we are closing your issue (https://github.com/Azure/Azure-Sentinel/issues/10113) as per our standard operating procedures. If you still need support for 	this issue, feel free to re-open at any time. Thank you for your co-operation!
