### ISSUE TITLE
Create Report of SecurityAlerts for conversion to CSV

### ISSUE THREAD

**Issue by kay07949** [Azure/Azure-Sentinel#1012]
I am trying to produce a report of security alerts that is to be exported as csv, i have therefore written following query however this fails:

`let Tenant = SigninLogs
| extend Tenant = extract("/(.*?)/(.*?)/",2,ResourceId)
| distinct Tenant;
SecurityAlert
| extend HostName_ = tostring(parse_json(Entities)[0].HostName)
| extend Address_ = tostring(parse_json(Entities)[1].Address)
| extend User_Name_ = tostring(parse_json(ExtendedProperties).["User Name"])
| extend Tenant = Tenant`

it gives me the error:

'extend' operator: Failed to resolve scalar expression named 'Tenant'

If issue persists, please open a support ticket. Request id: 150caf57-89f7-4dde-964a-9478f6129760

i also need to get the Threat Category, is that available in any of the sentinel tables?

**Comment by dicolanl** [comment]
Hi @kay07949 
I am not quite understanding what you are trying to do with Tenant?  in the first part you pulled distinct tenants list.  then the extend wont work cause you need join?  but what is the goal of distinct tenants?

also not securityalerts has the tenant already. you dont need to extract it.
![image](https://user-images.githubusercontent.com/25964057/91202984-68ceac00-e6b7-11ea-8b71-2021300fbd7a.png)

**Comment by kay07949** [comment]
Thanks I didnt realise tenant already exist!

**Comment by kay07949** [comment]
Would you know how I can add another field and get the tenant name?

**Comment by kay07949** [comment]
I also need the threat type , when we create scheduled alerts we specify the tactics

**Comment by dicolanl** [comment]
@kay07949  tactics are not stored in the security alert.  you would need to use a logic app and query the analytic rule for each security alert to get the tactic and add it.  OR have a logic dump your analytics rules to a table in Log A that you could join on.  I see if i can drum a sample of this up, but might take a few weeks.

As for tenant name, again same as above.  although i assume there are small number of tenants.  so it might be better to make a file in a storage account and use externaldata() to pull in the tenantid to tenantname mapping as part of your query.  How many tenants do you have?

**Comment by kay07949** [comment]
we have 8 sentinel workspaces in our environment. tThank you for the suggestion.
