### ISSUE TITLE
Built-in Analytics Rules - Port scan detected (ASIM Network Session schema)

### ISSUE THREAD

**Issue by jeffrywu28** [Azure/Azure-Sentinel#10134]
**Is your feature request related to a problem? Please describe.**
I have Issue hard to investigate from Built-in Alert : Port scan detected (ASIM Network Session schema)
That is I dont know from which Forti because i have a lot of fortinet.

**Describe the solution you'd like**
Please add DeviceExternalID and Computer Hostname that Receive the CommonEventLog to make me easy blocking the IP.

**Describe alternatives you've considered**
Just add another column that not exist "Computer" and "DeviceExternalID"

**Additional context**
<img width="1174" alt="image" src="https://github.com/Azure/Azure-Sentinel/assets/47622164/00faaec4-878b-4887-b11c-9fd29c362ce5">

**Comment by v-sudkharat** [comment]
Hi @jeffrywu28, Thanks for flagging this issue, we will investigate this issue and get back to you with some updates by 18-03-2024. Thanks!

**Comment by v-sudkharat** [comment]
Hi @jeffrywu28, 
As `_Im_NetworkSession` table does not contain your requested columns schema "Computer" and "DeviceExternalID", so to enhance this existing analytic rule, we required the `CommonEventLog `sample data as well. 
So, Please share the data with us on above mentioned mail id, so we can check on this issue. 
Thank!

**Comment by v-sudkharat** [comment]
Hi @jeffrywu28, Gentle Reminder: We are waiting for your response on this issue. If you still need to keep this issue active, please respond to it in the next 2 days. If we don't receive a response by 21-03-2024 date, we will be closing this issue. 		
Thanks!

**Comment by v-sudkharat** [comment]
Hi @jeffrywu28, since we have not received a response in the last 5 days, we are closing your issue as per our standard operating procedures. If you still need support for this issue, feel free to re-open at any time. Thank you for your co-operation.
