### ISSUE TITLE
Deployment of Azure Sentinel Solution for Fortinet Fortigate next generation fails

### ISSUE THREAD

**Issue by roboftheblues** [Azure/Azure-Sentinel#10149]
![image](https://github.com/Azure/Azure-Sentinel/assets/163409015/a1b86da1-adea-43e0-b05c-acd9d1332390)

**Comment by roboftheblues** [comment]
That parameter doesn't exist in the custom template

**Comment by v-muuppugund** [comment]
Hi @roboftheblues , Thanks for flagging this issue, we will investigate this issue and get back to you with some updates by 18Mar24. Thanks!

**Comment by v-sudkharat** [comment]
Hey @roboftheblues, While performing the custom deployment, could you please add the value for - `App Insights Workspace Resource ID` and try to deployment again. 
You can find out the App Insights Workspace Resource ID with below format by replacing with your one- 
`/subscriptions/YoursubscriptionId/resourceGroups/YourresourceGroupName/providers/Microsoft.OperationalInsights/workspaces/YourWorkspaceName`

![image](https://github.com/Azure/Azure-Sentinel/assets/132428394/7ab850ef-e4ec-4ad6-b2da-0dd562647999)

Once the value is added successfully, check the deployment status and let us know if it gets resolved or still facing same issue. 

Thanks!

**Comment by roboftheblues** [comment]
Issue is resolved

**Comment by v-sudkharat** [comment]
@roboftheblues, Thanks for update.
