### ISSUE TITLE
CEF AMA Connector stops logging after 30 minutes

### ISSUE THREAD

**Issue by roboftheblues** [Azure/Azure-Sentinel#10146]
Hi,

Replacing the Legacy Agent connector with the CEF AMA connector but cannot seem to maintain the data stream from the log forwarder (Linux Azure VM).  If we restart the daemons it kicks off log collection again but then seems to stop after approx 30 mins.

![image](https://github.com/Azure/Azure-Sentinel/assets/163409015/399166ce-1780-49b1-a439-75a7b354f2b2)

Grateful for any suggestions

KR

Rob

**Comment by v-sudkharat** [comment]
Hi @roboftheblues, Thanks for flagging this issue, we will investigate this issue and get back to you with some updates by 20-03-2024. Thanks!

**Comment by v-muuppugund** [comment]
Hi @roboftheblues ,working on further trouble shooting of the issue,will update you

**Comment by v-muuppugund** [comment]
Hi @roboftheblues ,Apologies for delayed response and we are working on it,will update you

**Comment by roboftheblues** [comment]
![image](https://github.com/Azure/Azure-Sentinel/assets/163409015/8e29626a-cf70-481e-9c31-b39956f15321)
16 hours ago we deleted the OMSAgent and once again loggin has stopped.  The CEF AMA Connector is not collecting logs

**Comment by roboftheblues** [comment]
Please send any update messages to wayne.kelly@dywidag.com as i am leaving the project

**Comment by askvpb** [comment]
We are also having similar issue like @roboftheblues, our CEF log take 2 hours to arrive the sentinel workspace. Keen to know the fix.

**Comment by askvpb** [comment]
we are using AMA agents

**Comment by roboftheblues** [comment]
Microsoft.Azure.Monitor.AzureMonitorLinuxAgent
Version 1.30.3
Microsoft.EnterpriseCloud.Monitoring.OmsAgentForLinux
Version 1.19.0

They are running side by side, but if you remove the OMS agent Sentinel no longer receives logs

**Comment by v-sudkharat** [comment]
Thanks @roboftheblues / @askvpb for sharing info.

**Comment by v-sudkharat** [comment]
Hey @roboftheblues, Could you please run the below script and let us know the result. Want to check is AMA connector configuration status. Thanks! 
`sudo wget -O Sentinel_AMA_troubleshoot.py https://raw.githubusercontent.com/Azure/Azure-Sentinel/master/DataConnectors/Syslog/Sentinel_AMA_troubleshoot.py&&sudo python3 Sentinel_AMA_troubleshoot.py --cef`

**Comment by v-sudkharat** [comment]
Hey @roboftheblues, We are waiting for your response on above comment. Thanks!

**Comment by roboftheblues** [comment]
Hola, waiting for response from customer

**Comment by v-sudkharat** [comment]
@roboftheblues, Noted. Thanks!

**Comment by roboftheblues** [comment]
----- Starting validation tests for AMA ---------------------------
verify_ama_agent_service_is_running------------> Success
Detected AMA running version- 1.30.3
verify_oms_agent_not_running-------------------> Failure
Detected the OMS Agent running on your machine. If not necessary please remove it to avoid duplicated data in the workspace, which can result in an increase in costs
 
----- Starting validation tests for data collection rules ---------
verify_DCR_exists------------------------------> Success
verify_DCR_content_has_stream------------------> Success
verify_dcr_has_valid_content-------------------> Success
check_multi_homing-----------------------------> Success
 
----- Starting validation tests for the Syslog daemon -------------
verify_Syslog_daemon_listening-----------------> Success
verify_Syslog_daemon_forwarding_configuration--> Success
 
----- Starting validation tests for the operating system ----------
verify_selinux_state---------------------------> Success
verify_iptables_policy_permissive--------------> Success
verify_iptables_rules_permissive_514-----------> Success
verify_iptables_rules_permissive_28330---------> Success
verify_free_disk_space-------------------------> Success
 
----- Starting validation tests for capturing incoming events -----
Attempting to capture events using tcpdump. This could take up to 10 seconds.
listen_to_incoming_events----------------------> Success
Found CEF in stream. Please verify CEF events arrived at your workspace
 
Total amount of failed tests is: 1

**Comment by roboftheblues** [comment]
If we remove the OMS agent log collection stops

**Comment by v-sudkharat** [comment]
Hi @roboftheblues, thanks for sharing result with us, we have reached out to the concern team for this issue, once will get any update from team will update you. Thanks!

**Comment by v-sudkharat** [comment]
Hi @roboftheblues, Our concern team required your Workspace ID, Could you please share it over- v-sudkharat@microsoft.com Thanks!

**Comment by v-sudkharat** [comment]
Hi @roboftheblues, We have received a response from our concerned team; they are investigating the issue and require resource access to check into it. Could you please raise a support ticket with our Azure support team, so they can look into it and connect with you if necessary. Please let us know once you have raised the support ticket, so we can update our concerned team. Thank you!

**Comment by roboftheblues** [comment]
Waiting for the client to respond

**Comment by v-sudkharat** [comment]
@roboftheblues, Noted. Please let us know once it open, so we can close this ticket from GitHub. Thanks!

**Comment by v-sudkharat** [comment]
Hi @roboftheblues, Is there any update on support ticket? Thanks!

**Comment by v-sudkharat** [comment]
Hi @roboftheblues, Gentle Reminder: We are waiting for your response on this issue. If you still need to keep this issue active, please respond to it in the next 2 days. If we don't receive a response by 26-06-2024 date, we will be closing this issue. 		
Thanks!

**Comment by v-sudkharat** [comment]
Hi @roboftheblues, since we have not received a response in the last 5 days, we are closing your issue as per our standard operating procedures. If you still need support for this issue, feel free to re-open at any time. Thank you for your co-operation.
