### ISSUE TITLE
Fortinet-FortiGate-IPEnrichment playbook deployment failed

### ISSUE THREAD

**Issue by roboftheblues** [Azure/Azure-Sentinel#10144]
Hi,

I saw in your archives a similar issue with the Fortinet playbooks.  Our issue with these is it fails with an 'Invalid Location' error.  All of the pre-requisites are complete.  Please see below:

![Screenshot 2024-03-14 114528](https://github.com/Azure/Azure-Sentinel/assets/163409015/51d393b0-8ef9-41dd-9651-45e56207164f)
![Screenshot 2024-03-14 104222](https://github.com/Azure/Azure-Sentinel/assets/163409015/021f28cb-641c-446f-aae4-7e6e7f413ef8)

Looking for help to resolve this issue, other internet resources are not helpful

Kind regards,

Rob

**Comment by v-sudkharat** [comment]
Hi @roboftheblues, Thanks for flagging this issue, we will investigate this issue and get back to you with some updates by 20-03-2024. Thanks!

**Comment by v-sudkharat** [comment]
Hi @roboftheblues, While deployment of playbook, could you please add hard coded value for location with your workspace location and try to deploy it again. 
In below screenshot we have added eastus2 -
![image](https://github.com/Azure/Azure-Sentinel/assets/132428394/95181e76-61ac-49d6-a744-d4cc9512b1ce)

Thanks!

**Comment by roboftheblues** [comment]
![image](https://github.com/Azure/Azure-Sentinel/assets/163409015/54ff1eb3-2a19-4a9f-a84b-9a61cddfe978)
Hard coded westeurope, still fails
But it has created an api connection azuresentinel-Fortinet-FortiGate-IPEnrichment
Doesn't take me to the Logic App designer

**Comment by roboftheblues** [comment]
![image](https://github.com/Azure/Azure-Sentinel/assets/163409015/55e8d46e-8756-4b06-a923-79bc8f6a675a)

**Comment by roboftheblues** [comment]
![image](https://github.com/Azure/Azure-Sentinel/assets/163409015/d70951df-c097-4f37-8545-952786a9fe09)

**Comment by v-muuppugund** [comment]
Hi @roboftheblues ,We will check on the issue and get back to you with an updates

**Comment by roboftheblues** [comment]
Issue resolved

**Comment by v-sudkharat** [comment]
@roboftheblues, thanks for sharing the update with us.
