### ISSUE TITLE
Salesforce Security Cloud connector uses deprecated auth method

### ISSUE THREAD

**Issue by pkozuchowski** [Azure/Azure-Sentinel#10169]
Salesforce Service Cloud connector uses Username + Password flow, which is deemed insecure by Salesforce. It works, but it may be blocked in the future. Right now, it's only disabled on new Salesforce orgs.

Please consider changing to JWT Bearer flow or Client Credentials.
https://help.salesforce.com/s/articleView?id=sf.remoteaccess_disable_username_password_flow.htm&type=5

**Comment by v-muuppugund** [comment]
Hi @pkozuchowski , Thanks for flagging this issue, we will investigate this issue and get back to you with some updates by 25Mar24. Thanks!

**Comment by v-muuppugund** [comment]
Hi @pkozuchowski ,Working on detailed analysis and will update you

**Comment by v-muuppugund** [comment]
Hi @pkozuchowski ,Still need some more time to complete the detailed analysis for the following
1.As-As implementations
2.Changes to be done for existing implemenattion
3.New changes to be integrated
  a. Working on api analysis
  b.Prerequisities
  c. Changes to be done.

**Comment by v-muuppugund** [comment]
Hi @pkozuchowski , Thanks for reach us, we have done the initial analysis for this enhancement and will be picking up in our queue and will update you once the changes have been completed.

**Comment by v-muuppugund** [comment]
> Hi @pkozuchowski , Thanks for reach us, we have done the initial analysis for this enhancement and will be picking up in our queue and will update you once the changes have been completed.

Hi @pkozuchowski ,Could you please share convenient time slots to v-muuppugund@microsoft.com,want to explain the analysis and next steps.
