### ISSUE TITLE
Legacy Fortinet Connector cannot be deleted

### ISSUE THREAD

**Issue by roboftheblues** [Azure/Azure-Sentinel#10166]
Despite the fact that the OMS agent has been removed from the Linux VM, the legacy connector still shows 'Connected' and cannot be deleted.  I understand that this is deprecated in August 2024 but we should be able to disconnect and delete it.  We have already installed the CEF AMA Connector.

**Comment by roboftheblues** [comment]
That doesn't show which connector it is.  We also have the CEF AMA Connector connected to the log forwarder which is collecting logs from the Fortinet Firewall

**Comment by v-sudkharat** [comment]
Hey @roboftheblues, Could you please share more context about the connector or the expected behavior. As per your issue description it's looks you are having below 2 CEF connector is configured but not getting from where the log's get pull. 
![image](https://github.com/Azure/Azure-Sentinel/assets/132428394/edbd7643-9163-4f35-b3dc-1e2947187f3b)

Thanks!

**Comment by v-sudkharat** [comment]
Hi @roboftheblues, Thanks for your response, we will check on the issue and will update you. 
Thanks!

**Comment by v-sudkharat** [comment]
> That doesn't show which connector it is. We also have the CEF AMA Connector connected to the log forwarder which is collecting logs from the Fortinet Firewall

Hey @roboftheblues, Could you please check the "CollectorHostName" column having data into your workspace, If it contains the data for it then your `CEF AMA Connector` is configured. 
You can run below query: - 
```
CommonSecurityLog
|where DeviceVendor =~ 'Fortinet' 
|where DeviceProduct =~ 'Fortigate'   
|extend sent_by_ama = column_ifexists('CollectorHostName','')
| project sent_by_ama
```
Select the timestamp as custom to get the result. and let us know the result for it. 
Thanks!

**Comment by v-sudkharat** [comment]
Hi @roboftheblues, waiting for your response on above comment. Thanks!

**Comment by roboftheblues** [comment]
Hi,

Sorry, I’m on holiday, can’t get back to you until the 8th earliest

Regards,

Rob

Sent from my iPhone

On 2 Apr 2024, at 09:15, v-sudkharat ***@***.***> wrote:

﻿

Hi @roboftheblues<https://github.com/roboftheblues>, waiting for your response on above comment. Thanks!

**Comment by v-sudkharat** [comment]
@roboftheblues, Noted. Please let us know anything need from us. Thanks!

**Comment by v-sudkharat** [comment]
Hi @roboftheblues, Waiting for your response. Thanks!

**Comment by roboftheblues** [comment]
Waiting for you to book a slot in my teams ***@***.***
Sent from my iPhone

On 9 Apr 2024, at 15:41, v-sudkharat ***@***.***> wrote:

﻿

Hi @roboftheblues<https://github.com/roboftheblues>, Waiting for your response. Thanks!

**Comment by v-sudkharat** [comment]
@roboftheblues, Noted.

**Comment by roboftheblues** [comment]
Sorry, didn't realise my email address came out wrong here!
robwood894@hotmail.com

**Comment by roboftheblues** [comment]
Please feel free to add a meeting to my calendar for next week.  I am on CET

**Comment by roboftheblues** [comment]
Waiting for a response from you, i need to discuss the issues with the fortinet connectors and the CEF AMA connector

**Comment by v-sudkharat** [comment]
Hey @roboftheblues, Need some more time to repro this issue :- https://github.com/Azure/Azure-Sentinel/issues/10146 in our environment. 
And regrading this issue :- https://github.com/Azure/Azure-Sentinel/issues/10166, We have shared the query on in this comment (https://github.com/Azure/Azure-Sentinel/issues/10166#issuecomment-2024958690) to know which connector has been configured. 

Thanks!

**Comment by roboftheblues** [comment]
CollectorHostName isn't being sent

**Comment by v-sudkharat** [comment]
@roboftheblues, Noted. Let us check on this and will share update with you. Thanks!

**Comment by v-sudkharat** [comment]
Closing this issue as its addressing over here - https://github.com/Azure/Azure-Sentinel/issues/10146#issuecomment-2127053995
