### ISSUE TITLE
Weird behaviour of boolean with DnsEvents and ipv4_is_private

### ISSUE THREAD

**Issue by ep3p** [Azure/Azure-Sentinel#10168]
This is not an urgent issue.

I opened a support case in Azure for this "behaviour" that does not make sense. But it is something really difficult to explain and understand, so my support case was not successful (but my support engineer made everything he could).

This problem is not from Microsoft Sentinel, this problem is from Log Analytics (KQL).

I have thought of talking directly to Henning Rauch, or Alexander Sloutsky (KQL developers), but **I only need someone from the product team to notice this**.

**Describe the bug**

My company is ingesting logs in "DnsEvents" table, which contains DNS requests.

Sometimes, we receive DNS requests where the "domain requested" contains an IP address (requests made by mistake).

Sometimes, the IP address will appear in the common format, and sometimes, the IP address will appear in this format 001.001.001.001.

![image](https://github.com/Azure/Azure-Sentinel/assets/2527990/773425d1-30bd-419d-bb7c-6d955959945d)

Both formats are valid IP addresses, KQL can parse both formats.

![image](https://github.com/Azure/Azure-Sentinel/assets/2527990/525a42f7-acae-4120-bbbd-1d90c01f453d)

![image](https://github.com/Azure/Azure-Sentinel/assets/2527990/4a254fe5-8db6-4739-a861-a13045e3c4dd)

KQL can check if the IP addresses are private, in both formats.
KQL can parse AND check the IP addresses, at the same time.

![image](https://github.com/Azure/Azure-Sentinel/assets/2527990/68746169-439d-40d4-a0e0-ac97a3006c85)

![image](https://github.com/Azure/Azure-Sentinel/assets/2527990/3c6321e3-7ecd-45e7-a6c6-5917bf69abf1)

If I don't want results where ```Col5``` is ```false```, where the IP address is parsed correctly AND it is private, I only have to add ```| where Col5```

![image](https://github.com/Azure/Azure-Sentinel/assets/2527990/f00a1589-83d4-4928-9149-c2464f698fd5)

The results in the previous image are correct.

**BUT**, if instead of using ```| where Col5```, I use the ```where``` with the same expression used to create ```Col5```:
```| where not(isnotempty(parse_ipv4(QueriedIPAddress)) and ipv4_is_private(QueriedIPAddress))```
**THEN** I don't get the same results.

![image](https://github.com/Azure/Azure-Sentinel/assets/2527990/2a4bd353-c4cd-4cba-bf46-3bdb3a49fc44)

There are results where ```Col5``` is ```false```, **this does not make sense**.

DNS requests with private IP addresses in the format 001.001.001.001 are **NOT removed** (```Col5``` is ```false```).
DNS requests with private IP addresses in the common format **ARE removed** (```Col5``` is ```false```).

**To summarize**

With a ```where``` operator the function ```ipv4_is_private()```, works differently for IP addresses written in the common format ```10.5.6.7``` than for IP addresses written in the extended format ```010.005.006.007```, **which is NOT expected**.

With the ```extend``` and ```project``` operators, the function ```ipv4_is_private()``` works as expected.

**Additional considerations**

I was only able to reproduce this behaviour with "DNSEvents" table, I could not reproduce it using ```datatable``` operator.

The column ```QueriedIPAddress``` is created using the ```extract()``` function, this might also be a critical condition for the behaviour.

Query used to reproduce the behaviour:

```
DnsEvents
| extend QueriedIPAddress = extract(strcat(@"((?:(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.){3}(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?))$"), 1, Name)
| where not(isempty(QueriedIPAddress) or QueriedIPAddress == "127.0.0.1")
| distinct Name, QueriedIPAddress
| project
            Name,
            QueriedIPAddress,
 Col1 =     parse_ipv4(QueriedIPAddress),
 Col2 =     isnotempty(parse_ipv4(QueriedIPAddress)),
 Col3 =     ipv4_is_private(QueriedIPAddress),
 Col4 =     isnotempty(parse_ipv4(QueriedIPAddress)) and ipv4_is_private(QueriedIPAddress),
 Col5 = not(isnotempty(parse_ipv4(QueriedIPAddress)) and ipv4_is_private(QueriedIPAddress))
//| where not(isnotempty(parse_ipv4(QueriedIPAddress)) and ipv4_is_private(QueriedIPAddress))
```

**Comment by v-muuppugund** [comment]
Hi @ep3p ,Thanks for flagging this issue, we will investigate this issue and get back 	to you with some updates by 25Mar24. Thanks!

**Comment by v-muuppugund** [comment]
Hi @ep3p ,Could you please share data to v-muuppugund@microsoft.com ,v-rusraut@microsoft.com as we don't have data in our work spaces.

**Comment by v-muuppugund** [comment]
Hi @ep3p ,The following is the status
1.Data ingestion completed
2.Anlasysed the queries
3.Working on detailed analysis,will update you

Please find below screen shots for reference,
![image](https://github.com/Azure/Azure-Sentinel/assets/139563098/646fe980-3f6c-4b42-83c5-3d7d49a9d5cf)
![image](https://github.com/Azure/Azure-Sentinel/assets/139563098/2f09f766-066b-41c8-88b0-5aed5ad072fe)

**Comment by ep3p** [comment]
thank you @v-muuppugund 

so, it seems the issue could not be replicated with a custom table?

it might depend on my table DnsEvents?

**Comment by ep3p** [comment]
v-muuppugund has diagnosed the issue really happens with parse_ipv4()

```| where isempty(parse_ipv4(QueriedIPAddress))``` does not work as expected

Updated query

```
DnsEvents
| extend QueriedIPAddress = extract(strcat(@"((?:(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.){3}(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?))$"), 1, Name)
| where not(isempty(QueriedIPAddress) or QueriedIPAddress == "127.0.0.1")
| distinct Name, QueriedIPAddress
| project
            Name,
            QueriedIPAddress,
 Col1 =     parse_ipv4(QueriedIPAddress),
 Col2 =     isnotempty(parse_ipv4(QueriedIPAddress)),
 Col3 =     isempty(parse_ipv4(QueriedIPAddress)),
 Auxiliar = gettype(parse_ipv4(QueriedIPAddress))
| where isempty(parse_ipv4(QueriedIPAddress))
```

**Comment by v-muuppugund** [comment]
> v-muuppugund has diagnosed the issue really happens with parse_ipv4()
> 
> `| where isempty(parse_ipv4(QueriedIPAddress))` does not work as expected
> 
> Updated query
> 
> ```
> DnsEvents
> | extend QueriedIPAddress = extract(strcat(@"((?:(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.){3}(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?))$"), 1, Name)
> | where not(isempty(QueriedIPAddress) or QueriedIPAddress == "127.0.0.1")
> | distinct Name, QueriedIPAddress
> | project
>             Name,
>             QueriedIPAddress,
>  Col1 =     parse_ipv4(QueriedIPAddress),
>  Col2 =     isnotempty(parse_ipv4(QueriedIPAddress)),
>  Col3 =     isempty(parse_ipv4(QueriedIPAddress)),
>  Auxiliar = gettype(parse_ipv4(QueriedIPAddress))
> | where isempty(parse_ipv4(QueriedIPAddress))
> ```

Hi @ep3p ,Thank for the detailed trouble shooting session and found the issue is due to Parse_ip4 on direct filter condition,Will do some more analysis about parse_ip4,Will update you and query filters applied well on columns.

**Comment by v-muuppugund** [comment]
Hi @ep3p ,I have done some more analysis parse_ip4 and checked  this conversion from ip to long is not directly supported in KQL ,we can apply filter on column and work around, If you still need support for this issue(https://github.com/Azure/Azure-Sentinel/issues/10168), feel free to re-open at any time. Thank you for your co-operation!
