### ISSUE TITLE
CEF AMA Connector stops logging after DCR update

### ISSUE THREAD

**Issue by roboftheblues** [Azure/Azure-Sentinel#10163]
Hello,

We seem to have an issue with the CEF AMA connector.  If we update or make any changes to the Data Collection Rule the connector stops collecting the logs from the log forwarder.  We have to reboot the log forwarder to enable log collection

**Comment by v-sudkharat** [comment]
Hi @roboftheblues, Thanks for flagging this issue, we will investigate this issue and get back to you with some updates by 21-03-2024. Thanks!

**Comment by v-sudkharat** [comment]
Hey, @roboftheblues, We will address this issue into this one -https://github.com/Azure/Azure-Sentinel/issues/10166, so closing this issue as replicated.
