### ISSUE TITLE
Fortinet-GetEntityDetails

### ISSUE THREAD

**Issue by roboftheblues** [Azure/Azure-Sentinel#10178]
Hello,
Keep getting http 500 errors when the Fortinet playbooks call the function to see if the 'entity' already exists.  The error reads:
2024-03-19T12:04:27.121 [Error] Executed 'Functions.Fortinet-GetEntityDetails' (Failed, Id=985d7eec-dbca-4bb9-b150-1b811393fefb, Duration=8ms)Unexpected character encountered while parsing value: <. Path '', line 0, position 0.

The error is repeated for every IP that has to be checked

**Comment by v-sudkharat** [comment]
Hi @roboftheblues, Thanks for flagging this issue, we will investigate this issue and get back to you with some updates by 28-03-2204. Thanks!

**Comment by roboftheblues** [comment]
This is the response from Co-Pilot AI:

The error message you're seeing, `Unexpected character encountered while parsing value: <. Path '', line 0, position 0`, typically occurs when a JSON parsing operation is attempted on non-JSON data.

In your case, it seems like the `Functions.Fortinet-GetEntityDetails` function is expecting a JSON response from the HTTP request it's making to the `https://[fqdn]/api/v2/cmdb/firewall/addrgrp/[blocklistgroup]/address?filter=start-ip=@167.248.133.164` URL. However, it's receiving a response that starts with `<`, which is not valid JSON.

This could be due to a few reasons:
1. The endpoint might be returning XML or HTML instead of JSON.
2. There might be an issue with the endpoint itself, such as an error page or a redirect.
3. The request might be malformed, causing an unexpected response.

To resolve this issue, you could:
- Check the API documentation to ensure you're making the request correctly.
- Try making a request to the API outside of your function to see what the response looks like.
- Handle non-JSON responses in your function code to prevent this error.

I hope this helps! Let me know if you have any other questions.

**Comment by roboftheblues** [comment]
![image](https://github.com/Azure/Azure-Sentinel/assets/163409015/9c611da0-1a7b-4a42-968f-84882fbaefc6)

**Comment by v-muuppugund** [comment]
Hi @roboftheblues ,Apologies for the delayed response,Could you please share couple of time slots to v-muuppugund@microsoft.com,will share the steps as provided solution to anaother customer and working on PR push

**Comment by v-muuppugund** [comment]
Hi @roboftheblues ,Could you please share convenient time slots for teams meeting to [v-muuppugund@microsoft.com](mailto:v-muuppugund@microsoft.com) as need to update logic app changes along with new package  of function app i.e. https://github.com/Azure/Azure-Sentinel/raw/users/v-muuppugundu/fortinetlogic/Solutions/Fortinet%20FortiGate%20Next-Generation%20Firewall%20connector%20for%20Microsoft%20Sentinel/Data%20Connectors/GetPostPutEntityV3.zip

**Comment by v-muuppugund** [comment]
Hi @roboftheblues ,
Could you please share email id for teams meeting,so will block the calendar for further troubleshooting the issue,

**Comment by roboftheblues** [comment]
***@***.***


Sent from my iPhone

On 10 Apr 2024, at 04:33, Murali Krishna Dev Uppugunduri ***@***.***> wrote:

﻿

Hi @roboftheblues<https://github.com/roboftheblues> ,
Could you please share email id for teams meeting,so will block the calendar for further troubleshooting the issue,

**Comment by v-muuppugund** [comment]
Hi Rob,

Could you please share email id  and am seeing this in the below email
***@***.***

Will block your calendar ,Thanks

Best Regards,
Murali
________________________________

**Comment by roboftheblues** [comment]
Hi Murali,

Can you not see my email address in the 'sender address'?

Rob
________________________________

**Comment by v-muuppugund** [comment]
Hi Rob,

No,I can't see email address,Please find below screen shot i can see from the mail box,
[cid:5d7aa8f0-a67f-4cd0-9d98-7e53480806da]

best Regards,
Murali
________________________________

**Comment by v-muuppugund** [comment]
Hi @roboftheblues ,As discussed over call in detail, this issue has been fixed by doing code changes at your end, we are closing your issue (https://github.com/Azure/Azure-Sentinel/issues/10178) as per our standard operating procedures. If you still need support for this issue, feel free to re-open at any time. Thank you for your co-operation!

**Comment by amrit24-cyber** [comment]
Hi Team,
I am facing similar issue with an internal server error with 500 code. 

Can you please help me with the resolution.

Regards,
Amrit Srivastava
