### ISSUE TITLE
AWS SecurityHub Connector does not ingest GuardDuty and Macie events present in SecurityHub

### ISSUE THREAD

**Issue by CyberHunter7** [Azure/Azure-Sentinel#10180]
**Describe the bug**
AWS SecurityHub Connector does not ingest GuardDuty and Macie events present in SecurityHub events.

**To Reproduce**
1. In Azure: Deploy AWS SecurityHub Connector 
2. In AWS: Generate a High or Critical event in GuardDuty
3. In AWS: Check that SecurityHub ingested the generated GuardDuty event in step 2. 
4. In Azure: Search in Log Analytics AWSSecurityHubFindings_CL table for the SecurityHub event related to GuardDuty

**Expected behavior**
SecurityHub event related to GuardDuty should be present in the Log Analytics.

NB 1 : AWS SecurityHub Connector is functional because we receive  other SecurityHub events in the Log Analytics.

NB 2 : In the function App of the connector -> configurations -> Application settings -> SecurityHubFilters could be set with no filter so all event regardless of severity label are captured

**Comment by v-muuppugund** [comment]
Hi @CyberHunter7 , Thanks for flagging this issue, we will investigate this issue and get back 	to you with some updates by 26Mar24. Thanks!

**Comment by v-muuppugund** [comment]
Hi @CyberHunter7 ,Working on detailed analysis for further changes,will update you

**Comment by CyberHunter7** [comment]
> Hi @CyberHunter7 ,Working on detailed analysis for further replication and changes,will update you

Thank you @v-muuppugund for the update.

**Comment by v-muuppugund** [comment]
Hi @CyberHunter7 ,I am able to replicate the issue and the data is not ingested from guard duty in to AWS Security hub, we have done the complete analysis for this requirement and will be picking up in our queue and will update you once the changes have been completed.Please let me know if you have any questions

**Comment by CyberHunter7** [comment]
> Hi @CyberHunter7 ,I am able to replicate the issue and the data is not ingested from guard duty in to AWS Security hub, we have done the complete analysis for this requirement and will be picking up in our queue and will update you once the changes have been completed.Please let me know if you have any questions we can have a detailed discussion on this requirement.

Hi @v-muuppugund thanks for the update, is there any workaround for the mean time ? is there an estimate when this issue will be resolved ?

**Comment by v-muuppugund** [comment]
> > Hi @CyberHunter7 ,I am able to replicate the issue and the data is not ingested from guard duty in to AWS Security hub, we have done the complete analysis for this requirement and will be picking up in our queue and will update you once the changes have been completed.Please let me know if you have any questions we can have a detailed discussion on this requirement.
> 
> Hi @v-muuppugund thanks for the update, is there any workaround for the mean time ? is there an estimate when this issue will be resolved ?

Hi @CyberHunter7 ,Apologies as of now ,with generated_id from guard duty and no filters the data is not coming up,Please find below screen shot for reference
even gaurd duty is enabled
![image](https://github.com/Azure/Azure-Sentinel/assets/139563098/db526774-49ad-4e04-9519-a77f2c39686f)
Could you please check any logs are present in guard duty  for the region using in AWS security hub connector

**Comment by CyberHunter7** [comment]
> > > Hi @CyberHunter7 ,I am able to replicate the issue and the data is not ingested from guard duty in to AWS Security hub, we have done the complete analysis for this requirement and will be picking up in our queue and will update you once the changes have been completed. Please let me know if you have any questions we can have a detailed discussion on this requirement.
> > 
> > 
> > Hi @v-muuppugund thanks for the update, is there any workaround for the mean time ? is there an estimate when this issue will be resolved ?
> 
> Hi @CyberHunter7 ,Apologies as of now ,with generated_id from guard duty and no filters the data is not coming up,Please find below screen shot for reference even gaurd duty is enabled ![image](https://private-user-images.githubusercontent.com/139563098/322501735-db526774-49ad-4e04-9519-a77f2c39686f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMxOTE0OTAsIm5iZiI6MTcxMzE5MTE5MCwicGF0aCI6Ii8xMzk1NjMwOTgvMzIyNTAxNzM1LWRiNTI2Nzc0LTQ5YWQtNGUwNC05NTE5LWE3N2YyYzM5Njg2Zi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQxNVQxNDI2MzBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04Yjg4NDkwODZkMDVjN2MxN2YzMzJmOTdiODRkOTI4OGM3YzUzNGY0M2I3Njc4OWZjMGU0ZjM0NTI2MTI3NjFmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.JchgfBF1rmvi6c6lqAuJCDwXNmhp3lrF9quHcmqnlqo) Could you please check any logs are present in guard duty for the region using in AWS security hub connector

Hi @v-muuppugund I checked again no logs are present. Do yo understand there is no quick fix for this that can be available ?

**Comment by CyberHunter7** [comment]
> > > > Hi @CyberHunter7 ,I am able to replicate the issue and the data is not ingested from guard duty in to AWS Security hub, we have done the complete analysis for this requirement and will be picking up in our queue and will update you once the changes have been completed. Please let me know if you have any questions we can have a detailed discussion on this requirement.
> > > 
> > > 
> > > Hi @v-muuppugund thanks for the update, is there any workaround for the mean time ? is there an estimate when this issue will be resolved ?
> > 
> > 
> > Hi @CyberHunter7 ,Apologies as of now ,with generated_id from guard duty and no filters the data is not coming up,Please find below screen shot for reference even gaurd duty is enabled ![image](https://private-user-images.githubusercontent.com/139563098/322501735-db526774-49ad-4e04-9519-a77f2c39686f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMxOTE0OTAsIm5iZiI6MTcxMzE5MTE5MCwicGF0aCI6Ii8xMzk1NjMwOTgvMzIyNTAxNzM1LWRiNTI2Nzc0LTQ5YWQtNGUwNC05NTE5LWE3N2YyYzM5Njg2Zi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQxNVQxNDI2MzBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04Yjg4NDkwODZkMDVjN2MxN2YzMzJmOTdiODRkOTI4OGM3YzUzNGY0M2I3Njc4OWZjMGU0ZjM0NTI2MTI3NjFmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.JchgfBF1rmvi6c6lqAuJCDwXNmhp3lrF9quHcmqnlqo) Could you please check any logs are present in guard duty for the region using in AWS security hub connector
> 
> Hi @v-muuppugund I checked again no logs are present. I understand there is no quick fix for this that can be available, is that correct ?

Hello @v-muuppugund any updates ?
