### ISSUE TITLE
Abilty to remove comments from Sentinel Incidents

### ISSUE THREAD

**Issue by robertkitching** [Azure/Azure-Sentinel#1018]
Currently we are unable to remove comments from Sentinel. This would be useful if comments were added in error.
We also use comments to enrich alerts through playbooks etc. If there was an issue with a playbook, we may need to remove comments that were added in error.

If this isn't possible, the ability to hide/dismiss comment would suffice.

If you don't want to expose this functionality in the portal, could it possibly be achieved by an API call? I have looked at the API definition for comments and it does not currently contain a remove method.

**Comment by sarah-yo** [comment]
Comments can now be deleted
