### ISSUE TITLE
GitHub protect using logic app and Azure sentinel 

### ISSUE THREAD

**Issue by Milanthumar** [Azure/Azure-Sentinel#1020]
Dear Team,

As per procedure we could configure logic apps and ingest repologs data to azure sentinel.
Thanks to @9b dicolanl for modification in template. 
https://techcommunity.microsoft.com/t5/azure-sentinel/protecting-your-github-assets-with-azure-sentinel/ba-p/1457721

After monitoring for few days we are observing error for **Get-GitHubAuditEntry** logic app as below and it seems it never worked.

![image](https://user-images.githubusercontent.com/68587784/91701876-3a9a1200-eb78-11ea-8177-85953e45e9a1.png)

![image](https://user-images.githubusercontent.com/68587784/91702426-007d4000-eb79-11ea-8df1-6e3082360231.png)

Regards,
Milan Thumar

**Comment by dicolanl** [comment]
@Milanthumar  can you expand the HTTP and Parse JSON 2 in that failed run?

![image](https://user-images.githubusercontent.com/25964057/91739678-1c77e600-eb67-11ea-829e-012af2c447e4.png)
![image](https://user-images.githubusercontent.com/25964057/91739694-24378a80-eb67-11ea-90b1-48b689834875.png)

I have a feeling the HTTP body is empty thus parse json is empty thus the condition fails.

Also redeploy the logic app.  it looks like you have a previous version and we made a couple updates.  Like I added a delay at the start of the Until loop.

**Comment by sarah-yo** [comment]
Closing as no further questions/activity. Please feel free to raise another issue if the issue persists.
