### ISSUE TITLE
AWS connector script to create a bucket fails on tags on PWSH on macOS

### ISSUE THREAD

**Issue by ShachafGoldstein** [Azure/Azure-Sentinel#10210]
https://github.com/Azure/Azure-Sentinel/blob/a089a4e0d5195c6c8b7ffcc0d8b2b8dd2a85bd02/DataConnectors/AWS-S3/Utils/AwsResourceCreator.ps1#L171

**To Reproduce**

`Azure-Sentinel/DataConnectors/AWS-S3/ConfigAwsConnector.ps1 -AwsLogType CloudTrail -Verbose
give a bucket name that does not exist`

**Expected behavior**
Script to work and create a bucket

Error:
`Error parsing parameter '--tagging': Invalid JSON: Expecting property name enclosed in double quotes: line 1 column 2 (char 1)
JSON received: {\"TagSet\":[{\"Key\": \"Operator\", \"Value\": \"Microsoft_Sentinel_Automation_Script\"}]}`

**Comment by v-muuppugund** [comment]
Hi @ShachafGoldstein ,As discussed yesterday, Blocking your calendar on 10Apr24 at 10am to 11 am Israel time for detailed troubleshooting the issue.

**Comment by v-muuppugund** [comment]
Hi @ShachafGoldstein ,As discussed over call today,the issue has been fixed during debugging session,will be raising the PR for the same and update you.

**Comment by v-muuppugund** [comment]
Hi @ShachafGoldstein , we have raised the PR with the enhancements. The changes will be reflected once the PR is merged.
PR link -
[#10295](https://github.com/Azure/Azure-Sentinel/pull/10295)

Thank you for your cooperation.

**Comment by beanaroo** [comment]
@v-muuppugund We're still experiencing this issue on the latest `master`. It seems that the mentioned PR above was not merged but this issue is closed? Is there another resolution to be aware of?
