### ISSUE TITLE
No hundredth in "authenticationStepDateTime" for "MFA denied; user did not select the correct number" Status

### ISSUE THREAD

**Issue by B-Hard** [Azure/Azure-Sentinel#10230]
**Describe the bug**

**We have more MFA denied Events in the SigninLogs than originally executed.**
For example - type in a wrong MFA Code in the smartphone for 4 times. We have 5 MFA denied events in the Logs.
To investigate I assume there are duplicate MFA denied log entries. Therefore I need hundreth as time value to check and verify.

We already tested this behaviour on 2 seperate Tenants, always generating more or less MFA denied events than originally executed.
Therefore it's not representative to have MFA denied rules for more than 3  failed Login attempts and so forth.

**To Reproduce**
1. Go to Logs
KQL Query to filter for MFA denied Events:

```
SigninLogs
| project
    TimeGenerated,
    AuthenticationRequirement,
    AuthenticationDetails,
    UserPrincipalName,
    CorrelationId,
    ResultType
| where AuthenticationRequirement == "multiFactorAuthentication"
| parse AuthenticationDetails with *'"authenticationStepDateTime":"'AuthStepDateTime"," *
| parse AuthenticationDetails with *'"authenticationStepResultDetail":"'AuthResult ","*
| where AuthResult has "MFA denied; user did not select the correct number"
```

**Expected behavior**
I expect the parsed Column "**AuthStepDateTime**" to have **hundreth as a Time value** like other Events than MFA denied have too.
There are just time values with seconds but no hundreth seconds or more.

**Screenshots**
![MFADenied-notimestamp](https://github.com/Azure/Azure-Sentinel/assets/16137558/1b7d4844-2a59-46b1-9617-371156765aa1)

**Comment by v-sudkharat** [comment]
Hi @B-Hard, Thanks for flagging this issue, we will investigate this issue and get back to you with some updates by 05-04-2024. Thanks!

**Comment by v-sudkharat** [comment]
Hi @B-Hard, Could you please let us know what source you are having to get the data into **SigninLogs**? You can also check the sync for the MFA denied by using the **CreatedDateTime** which holds the millisecond values into it. 

```
SigninLogs
| project
    TimeGenerated,
    CreatedDateTime,
    AuthenticationRequirement,
    AuthenticationDetails,
    UserPrincipalName,
    CorrelationId,
    ResultType
| where AuthenticationRequirement == "multiFactorAuthentication"
| parse AuthenticationDetails with *'"authenticationStepDateTime":"'AuthStepDateTime"," *
| parse AuthenticationDetails with *'"authenticationStepResultDetail":"'AuthResult ","*
| where AuthResult has "MFA denied; user did not select the correct number"
```
As per the [MSDoc,](https://learn.microsoft.com/en-us/azure/azure-monitor/reference/tables/signinlogs) the **CreatedDateTime** is a date and time the sign-in was initiated. So, if logs get pulled in correctly time, the **CreatedDateTime** will shows the correct value into it. 

Thanks!

**Comment by B-Hard** [comment]
@v-sudkharat thanks for your response. I checked the CreatedDateTime and it shows the same value (sec+mill sec) for all my attempts of entering a wrong code. There are defenitely more than one second between each attempt. See here:
![mfadenied-createddatetime](https://github.com/Azure/Azure-Sentinel/assets/16137558/eeed2640-e17a-44aa-9126-77cf3d000d91)

Thanks for your support.

**Comment by v-sudkharat** [comment]
@B-Hard, We will check on the Timestamp for specific Auth result and will update you.

**Comment by B-Hard** [comment]
Any news so far? @v-sudkharat 
Thanks

**Comment by v-sudkharat** [comment]
Hi @B-Hard, Sorry for delay in response. 
Yes, we have checked the logs in `SigninLogs` table, The timestep into the `AuthenticationDetails` is fetch from connector itself. It not only with specific `AuthResult` "MFA denied; user did not select the correct number" you will get it same for few of the below to: -
`MFA successfully completed.`
`Authentication in progress`

![image](https://github.com/Azure/Azure-Sentinel/assets/132428394/6b465fb7-1b6d-4941-8dd0-5ed842505474)

This needs to be check from our backend side configuration, and we are not authorized to check on backend config side. We kindly request you to raise a support case on this issue, so our support team can look into it and if required team will connect with you. 
Thanks!

**Comment by B-Hard** [comment]
Ok thanks for your effort, will open a ticket...

**Comment by v-sudkharat** [comment]
@B-Hard, Welcome. so, closing this issue from GitHub. If you still need support for this issue, feel free to re-open it any time. Thank you for your co-operation.
