### ISSUE TITLE
Forcepoint DLP connector for Microsoft Sentinel - Not working as mentioned in documentation

### ISSUE THREAD

**Issue by Abhishek-Sharan** [Azure/Azure-Sentinel#10234]
**Describe the bug**
Forcepoint DLP connector for Microsoft Sentinel is community supported connector. The steps mentioned in Forcepoint documentation seems dated now. Customers have to ingest the data via Syslog forwarder server. Please have the contents updated to avoid confusion.
https://forcepoint.github.io/docs/dlp_and_azure_sentinel/#forcepoint-data-loss-prevention-and-azure-sentinel
https://learn.microsoft.com/en-us/azure/sentinel/data-connectors/forcepoint-dlp

**To Reproduce**
Not Applicable

**Expected behavior**
Documented steps should be reviewed.

**Screenshots**
Support has confirmed that the given steps content hub will not work:
![image](https://github.com/Azure/Azure-Sentinel/assets/84129078/ff8f8112-c19e-4cc6-822c-2039ba154418)

**Desktop (please complete the following information):**
NA
**Smartphone (please complete the following information):**
 NA
**Additional context**
Please review and update the steps.

**Comment by v-rusraut** [comment]
Hi @Abhishek-Sharan,
As you mentioned steps in Forcepoint documentation seems dated now. Link present in data connector page also redirected to same instruction of Forcepoint documentation. (https://forcepoint.github.io/docs/dlp_and_azure_sentinel/#forcepoint-data-loss-prevention-and-azure-sentinel)
Can you please help us to understand which link of Forcepoint documentation you are referring.
Thanks

**Comment by Abhishek-Sharan** [comment]
Hi @v-rusraut , yes it redirects to the URL you've mentioned. However, as per interaction with support teams it's confirmed that the steps given in the URL won't work. We're looking for assistance to update the URL/document if needed.

**Comment by v-muuppugund** [comment]
Hi @Abhishek-Sharan ,As the document is outdated ,we need to validate from our end and replicate the steps  by going through document,so need some time from us for replication,if needed will have a call with you for detailed discussion.

**Comment by v-muuppugund** [comment]
Hi @Abhishek-Sharan ,As we tried to replicate the issue and don't have forcepoint account credentials,Could you please share couple of time slots for teams meeting to v-muuppugund@microsoft.com

**Comment by v-muuppugund** [comment]
Hi @Abhishek-Sharan , Gentle Reminder,As we tried to replicate the issue and don't have forcepoint account credentials,Could you please share couple of time slots for teams meeting to [v-muuppugund@microsoft.com](mailto:v-muuppugund@microsoft.com) for further discussion on the issue.

**Comment by v-sudkharat** [comment]
Hi @Abhishek-Sharan, since we have not received a response in the last 5 days, we are closing your issue as per our standard operating procedures. If you still need support for this issue, feel free to re-open at any time. Thank you for your co-operation.
