### ISSUE TITLE
Parser's metadata deployment in error when parser already exist for another solution

### ISSUE THREAD

**Issue by nlepagnez** [Azure/Azure-Sentinel#10264]
**Describe the bug**
We have 2 solutions that share multiple same parsers, but a customer can deploy one or the other so the 2 solutions need to deploy the shared parsers. Before Parsers are transformed as YAML objects, we didn't have any problem. Now when we do that we have a metadata conflict during the deployment.

How can we deploy the parser with the solutions without having error ?

**To Reproduce**
1. Go to 'Microsoft Exchange Online Security Solution' in the Content Hub
2. Install the solution
3. Go to 'Microsoft Exchange On-Premises Security Solution' in the Content Hub
4. Install the solution

**Expected behavior**
Installation in success

**Screenshots**
![image](https://github.com/Azure/Azure-Sentinel/assets/2814429/a80e7f15-182a-4643-adfc-1c6d6bde52b6)

**Comment by v-sudkharat** [comment]
Hi @nlepagnez, Thanks for flagging this issue, we will investigate this issue and get back to you with some updates by 16-04-2024. Thanks!

**Comment by v-sudkharat** [comment]
Hey @nlepagnez, We are checking the issue cause for the deployment failure for Parser. Meanwhile, to get unblocked from this issue you can install the solution is another workspace where the solution is not already installed (Older versions). 
This issue occurs only when updating the existing solution to new version. 
Below sol. installed successfully in new workspace :-
![image](https://github.com/Azure/Azure-Sentinel/assets/132428394/992bdae9-1456-43e4-b684-e24b079d9988)

Please let us know if you have any feedback on this. 
Thanks!

**Comment by nlepagnez** [comment]
Hi @v-sudkharat. Exactly If was aware that it works on a new workspace. As we've just updated a major version of the solution, we're concerned about how customers will deploy it. I hope the cause can be found quickly.

Thank you.

**Comment by v-sudkharat** [comment]
@nlepagnez, Sure. we will definitely update you once we get cause or any other info from team. Thanks!

**Comment by nlepagnez** [comment]
### **IMPORTANT**

Hi @v-sudkharat, I see a commit with an autopackage of the solutions : https://github.com/Azure/Azure-Sentinel/commit/a31e95caea0043e0f08ba917ff947eabf45a5952

This brake totally the 2 Microsoft Exchange Security solutions as the Autopackage is not able to keep Default values or parser parameters. You need to stop the package deployment to the content hub and they need to correct : 

- The CreateDefinitionUI with the modified text that is not correct
- The MainTemplate to reinsert parser parameters default values and texts.

**Comment by nlepagnez** [comment]
Hi @v-sudkharat, did the team finished to correct the error ? I see that the team repackaged the solutions, is now good ?

**Comment by v-sudkharat** [comment]
Hey @nlepagnez, still team is working on correction in packaging tool, and regarding publishing the solution there is still having same issue for parser metadata for which team is making changes.

**Comment by nlepagnez** [comment]
Hi @v-sudkharat, As I understand, the team pushed correction to packaging tool and also the solutions. Is it good now ? Is it possible to publish the new versions of the 2 solutions in the Content Hub ?

**Comment by v-sudkharat** [comment]
Hello @nlepagnez, Those solution is already pushed for get available in Content Hub from our end, and currently its pending with content hub team. We will ping you or share update with you over here once those solution is available in content hub with new versions. 
Thanks!

**Comment by nlepagnez** [comment]
Hi, 
I tested the new solutions and the problem doesn't occur again.

Thanks to the team for the resolution.

**Comment by v-sudkharat** [comment]
@nlepagnez, Thanks for closing the issue.
