### ISSUE TITLE
Oracle Cloud Infrastructure and Python 3.8 End of Support

### ISSUE THREAD

**Issue by DavidT8777** [Azure/Azure-Sentinel#10265]
**Describe the bug**
Unable to upgrade the python version for the Oracle Cloud Infrastructure function app. Changing the stack version above Python 3.8 generates errors.

**To Reproduce**
1. Go to the OCI logs function app
2. Under Settings, select Configuration
3. In Configuration, select General Settings
4. Change the Python Version from Python 3.8 to 3.9.
5. Save the configuration
6. See error:
Result: Failure
Exception: ModuleNotFoundError: No module named '_cffi_backend'
Stack:   File "/azure-functions-host/workers/python/3.9/LINUX/X64/azure_functions_worker/dispatcher.py", line 505, in _handle__invocation_request
    call_result = await self._loop.run_in_executor(
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/azure-functions-host/workers/python/3.9/LINUX/X64/azure_functions_worker/dispatcher.py", line 778, in _run_sync_func
    return ExtensionManager.get_sync_invocation_wrapper(context,
  File "/azure-functions-host/workers/python/3.9/LINUX/X64/azure_functions_worker/extension.py", line 215, in _raw_invocation_wrapper
    result = function(**args)
  File "/home/site/wwwroot/AzureFunctionOCILogs/main.py", line 46, in main
    stream_client = oci.streaming.StreamClient(config, service_endpoint=MessageEndpoint)
  File "/home/site/wwwroot/.python_packages/lib/site-packages/oci/streaming/stream_client.py", line 66, in __init__
    signer = Signer(
  File "/home/site/wwwroot/.python_packages/lib/site-packages/oci/signer.py", line 253, in __init__
    self.private_key = load_private_key(private_key_content, pass_phrase)
  File "/home/site/wwwroot/.python_packages/lib/site-packages/oci/signer.py", line 49, in load_private_key
    backend = default_backend()
  File "/home/site/wwwroot/.python_packages/lib/site-packages/cryptography/hazmat/backends/__init__.py", line 14, in default_backend
    from cryptography.hazmat.backends.openssl.backend import backend
  File "/home/site/wwwroot/.python_packages/lib/site-packages/cryptography/hazmat/backends/openssl/__init__.py", line 6, in <module>
    from cryptography.hazmat.backends.openssl.backend import backend
  File "/home/site/wwwroot/.python_packages/lib/site-packages/cryptography/hazmat/backends/openssl/backend.py", line 113, in <module>
    from cryptography.hazmat.bindings.openssl import binding
  File "/home/site/wwwroot/.python_packages/lib/site-packages/cryptography/hazmat/bindings/openssl/binding.py", line 14, in <module>
    from cryptography.hazmat.bindings._openssl import ffi, lib

**Expected behavior**
Function should run without error. Reverting back to Python 3.8 resolves the issue, however, we've received emails from Azure that community support for Python is ending 14-Oct-2024 and to transition to Python 3.9+.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Edge
 - Version: 123.0.2420.81 (Official build) (64-bit)

**Smartphone (please complete the following information):**

**Additional context**

**Comment by v-rusraut** [comment]
Hi @DavidT8777 , Thanks for flagging this issue, we will investigate this issue and get back to you with some updates by 16-04-2024. Thanks!

**Comment by v-rusraut** [comment]
Hi @DavidT8777,
Working on replicating the issue, will update you.
Thanks

**Comment by v-rusraut** [comment]
Hi @DavidT8777,

We tried to replicate the issue,We deployed function app with manual deployement and also through arm template.
After that we changed python version from 3.8 to 3.9 ,but not getting this error - Exception: ModuleNotFoundError: No module named '_cffi_backend'.
Please provide details steps about how to configure function app and also provide python_packages folder.you will get python_packages folder with below steps

1. Go to storage account
2. Search with your functionapp name
3. Data storage -> Containers ->scm-releases
4. download file - scm-latest-functionapp
5. share downloaded file

Thanks

**Comment by DavidT8777** [comment]
This function was originally installed via the Sentinel Content Hub with version 3.0.0. We've upgraded to version 3.0.1 due to issues we reported in #8313. We attempted the upgrade to python 3.9 from the General Settings tab on the function app.  Looking at the scm-releases container in the storage account, it's empty.  

![Screenshot 2024-04-18 113407](https://github.com/Azure/Azure-Sentinel/assets/137198855/41fd7935-5589-4f10-a7c5-b3860a1328b8)

The function app is running and we have current logging from the function.

Thanks!

**Comment by v-rusraut** [comment]
Hi @DavidT8777,
We updated function app packages, please follow below steps for configuration.
1.  Go to Setting section of your function app
<img width="518" alt="image" src="https://github.com/Azure/Azure-Sentinel/assets/126679503/da112535-f9c8-4e35-95c2-7142a4e99a20">

2. Click on Environment variables
<img width="890" alt="image" src="https://github.com/Azure/Azure-Sentinel/assets/126679503/d79950d7-f549-4e46-bec5-1e797ff72b2c">

3. Under the App setting click on WEBSITE_RUN_FROM_PACKAGE
<img width="874" alt="image" src="https://github.com/Azure/Azure-Sentinel/assets/126679503/543a5903-dff1-4b65-a880-b58ae5b8f6b2">

4. Replace the value with below url (Copy existing value and paste it in notepad)

https://github.com/Azure/Azure-Sentinel/raw/vrusraut/OCIDataConnector/Solutions/Oracle%20Cloud%20Infrastructure/Data%20Connectors/OCILogsConn.zip
<img width="940" alt="image" src="https://github.com/Azure/Azure-Sentinel/assets/126679503/5c272ffa-1cc0-467a-8903-5c64dc19579c">

5. Apply changes

6. Go to Configuration section -> General settings
<img width="733" alt="image" src="https://github.com/Azure/Azure-Sentinel/assets/126679503/07e983b1-0671-4e41-a671-155b265de96b">

7. Change python version from 3.8 -> 3.9

8.  Click on Save.

9. Restart function app
<img width="673" alt="image" src="https://github.com/Azure/Azure-Sentinel/assets/126679503/a07cb983-c5ea-4b6c-a369-c020cc63866c">

10. Check log in Monitor Section

**Comment by DavidT8777** [comment]
Hi, @v-rusraut,

I've made the changes you requested to the function app Configuration\Application settings (I don't see an "Environment variables" in the portal) and restarted the app at approximately 10:10am EST.

![image](https://github.com/Azure/Azure-Sentinel/assets/137198855/01ceb77b-7f9d-440b-881c-b4a11e83f871)

![image](https://github.com/Azure/Azure-Sentinel/assets/137198855/b411c047-0244-4920-9c78-d21aab0f8196)

 I'm showing the following error on the Overview page:

![image](https://github.com/Azure/Azure-Sentinel/assets/137198855/92f4501f-5bfb-4b24-8e99-cecc6aedd00a)

![image](https://github.com/Azure/Azure-Sentinel/assets/137198855/2d83c1f4-e4a7-4028-a879-3545df536113)

I've had one invocation of the function since the changes were made and nothing since.

![image](https://github.com/Azure/Azure-Sentinel/assets/137198855/29444dc9-6a6d-45e2-ab26-37eb62cd910c)

I'll revert the changes so that we don't miss any logging.

thanks!
David

**Comment by v-rusraut** [comment]
Hi @DavidT8777,
Please follow above steps again, update below url in WEBSITE_RUN_FROM_PACKAGE and verify.
https://github.com/Azure/Azure-Sentinel/raw/v-rusraut/OCI/Solutions/Oracle%20Cloud%20Infrastructure/Data%20Connectors/OCILogsConn.zip
Thanks

**Comment by v-rusraut** [comment]
Hi @DavidT8777,
For this solution supporting packages will be update before 14 Oct 2024, so till that time you can use python 3.8.
Once packages will update, we will notify you. currently closing this issue.
Thanks

**Comment by v-sudkharat** [comment]
Hey @DavidT8777, could you please check once with below package and let me know if error fixed: 
Select python 3.9 version and then updated below link in path of WEBSITE_RUN_FROM_PACKAGE -

https://github.com/Azure/Azure-Sentinel/raw/82fbb2afd404176623de5dd9133f72bf8d2a828e/Solutions/Oracle%20Cloud%20Infrastructure/Data%20Connectors/OCILogsConn.zip

**Comment by DavidT8777** [comment]
hi @v-sudkharat, aside from one error immediately after implementation, all further invocations of the function have been successful using the provided .zip and the python version set to 3.9.

**Comment by v-sudkharat** [comment]
Hey @DavidT8777, It would be great if you could share that one error screenshot with us. Thanks!

**Comment by DavidT8777** [comment]
@v-sudkharat will do...  I didn't get a screen shot but pulled the information from the logs in the attached .txt file.

[10265-Error After Additional Script and Python 3.9.txt](https://github.com/user-attachments/files/15820978/10265-Error.After.Additional.Script.and.Python.3.9.txt)
[10265-Error After Additional Script and Python 3.9.txt](https://github.com/user-attachments/files/15820978/10265-Error.After.Additional.Script.and.Python.3.9.txt)

**Comment by v-sudkharat** [comment]
Thanks @DavidT8777 for sharing logs, Just want to know one more info from you, After updating 3.9 version in invocation tab its show as status Success right like below screenshot? and also logs are receiving into the workspace correct?- 
![image](https://github.com/Azure/Azure-Sentinel/assets/132428394/89dc984c-2638-4050-92cd-bae204952b31)
