### ISSUE TITLE
Unable to install ZeroFox Marketplace Application from marketplace

### ISSUE THREAD

**Issue by DNRRomero** [Azure/Azure-Sentinel#10287]
**Describe the bug**
On September 18th, 2024, a new Azure Solution was added to this repository named ZeroFox. It is composed of several data connectors, out of which 1 is a codeless connector while the rest are made through Azure Functions.
It was notified to customers that our app was added to Azure and that they were able to install it and use it by looking into our [latest published offer ](https://azuremarketplace.microsoft.com/en-us/marketplace/apps/zerofoxinc1695922129370.f1de974b-f438-4719-b423-8bf704ba2aef?tab=Overview) . However, any customer who tries to access the application, having set up a Resource Group and Workspace, is unable to allocate resources for installing the app. Whenever a Resource Group is selected and the user tries to select an associated workspace, it shows that none exists even though these were already created.
I need help with this issue since customers are waiting to use our application and, due to configuration issues, the application can not be delivered to customers.

**To Reproduce**
1. Go to https://portal.azure.com/#home
2. Search for "ZeroFox Connector" in the Marketplace section
3. Click on the Create button to set up a plan.
4. Select a Resource Group and try to select a workspace matching your selected Resource Group
5. See error

**Expected behavior**
The plan associated with the ZeroFox Connector marketplace offer is created properly and the application can then be used.

**Screenshots**
![image](https://github.com/Azure/Azure-Sentinel/assets/26130667/194bb195-756c-4295-814a-dbd7be85c2a1)

**Comment by v-sudkharat** [comment]
Hi @DNRRomero, Thanks for flagging this issue, we will investigate this issue and get back to you with some updates 18-04-2024. Thanks!

**Comment by v-sudkharat** [comment]
Hey @DNRRomero, We have followed-up with your shared repro steps from this issue description. After selecting the solution from Azure Marketspace, we have selected our Subscription / Resource group, and while selecting the Workspace we are able to see the associated Workspace over there. 
Sharing the screenshot for your reference :- 

![image](https://github.com/Azure/Azure-Sentinel/assets/132428394/897ce1d1-bd97-48da-8031-d988b1b8657f)

Could you please check it once from your end and let us know if still you are having issue. 
Note: It may take 5 to 10 sec delays if your connection is unstable. 

Thanks!

**Comment by DNRRomero** [comment]
Hi @v-sudkharat! I just tried again and checked on my workspace availability 
![image](https://github.com/Azure/Azure-Sentinel/assets/26130667/67c7f09a-7087-46fb-af07-f63e05b3dd96)
As you can see, I have two workspaces set up in the resource group `zf_Test`, namely `workspace_test` and `workspace_test_3`
However when trying to add them to the Solution plan:
![image](https://github.com/Azure/Azure-Sentinel/assets/26130667/15109be9-9bbd-454f-aea7-ddc9c21ddab2)
Even if I try to create a resource group inline, it won't give the option of creating a corresponding workspace
![image](https://github.com/Azure/Azure-Sentinel/assets/26130667/a8b48fbd-f43f-4e60-8c9e-22746b93ca3c)
 I have verified that I am not the only user with this issue, as 2 coworkers and a number of customers have run into it.

**Comment by v-sudkharat** [comment]
Hey @DNRRomero, 
It may due to not having required roles and permission's, so could you please confirm once if you are compliant/having permission to resource group/workspace:- 
https://learn.microsoft.com/en-us/azure/sentinel/roles
 
If still having issue, can we have a call? could you please share your mail ID and couple of Timeslot's for call with us on below mail Id - v-sudkharat@microsoft.com. So we can check it into it. 

Thanks!

**Comment by DNRRomero** [comment]
Hey @v-sudkharat  I have looked into the roles required and did not see anything that may be the cause.
I call with you to get help on this would be great, I've just sent you an email with my appointment schedule

**Comment by v-sudkharat** [comment]
@DNRRomero, We have received your mail. We will schedule a meeting and send invite over mail. Thanks!

**Comment by v-sudkharat** [comment]
Hey @DNRRomero, Just got the issue from your provided screenshot and before schedule the call, I just want to validate the resource you have created.
By observing the workspace icon, based on your provided screenshot it looks you have created **Workspaces** service and not **Sentinel Log Analytic Workspace** in associated Resource Group. To install the sentinel solution from Marketplace, the solution required Log Analytic Workspace linked to its associated Resource Group. 
Correct me if you already created Sentinel LAW and still facing the issue. 
Sharing the steps to create LAW which required to install solution from marketplace: - 
1. Got to Azure Portal HomePage and search for the Microsoft Sentinel : -

![image](https://github.com/Azure/Azure-Sentinel/assets/132428394/4ec5de0e-8e6a-4e32-be28-8b3e74f1ad4e)

2. Click on Create New Workspace and Fill the required details into it : -

![image](https://github.com/Azure/Azure-Sentinel/assets/132428394/441dd2ed-6b29-4900-a5b5-4158c7bfb179)

3. Select the Resource group where you want to create Microsoft Sentinel into it :- 

![image](https://github.com/Azure/Azure-Sentinel/assets/132428394/48e9176e-7795-4a14-a940-1905d7ecc07b)

5. Validate your details once and click on create : -

![image](https://github.com/Azure/Azure-Sentinel/assets/132428394/fc1ae6c9-f537-4c31-8a78-ba99624ece0a)

6. The deployment take few min to create Workspace into Resurce Group.  

7. After deployment, Go to Microsoft Sentinel and click on Create :-

![image](https://github.com/Azure/Azure-Sentinel/assets/132428394/fe0345b5-b1b4-4758-907e-3b8086bf08a6)

8. Enter your created Workspace name into search bar and click on add by selecting it :-

![image](https://github.com/Azure/Azure-Sentinel/assets/132428394/6f456aad-3236-47f8-97d7-04211d04af9a)

9. Once it gets successfully added, you will get below success message: -

![image](https://github.com/Azure/Azure-Sentinel/assets/132428394/2216cd4a-cc32-4c47-93bf-0a0a0988de8f)

10. Now, while you will get the Workspace while creating the solution from Marketplace :- 
 
![image](https://github.com/Azure/Azure-Sentinel/assets/132428394/35dd4a71-bb36-4fd4-9585-0d8ae6914619)

Please confirm the above steps and let me know your feedback. So, we can plan the call accordingly. 

Thanks!

**Comment by DNRRomero** [comment]
Hi @v-sudkharat! you were right, I was not setting up the proper workspace resource. However, after setting it up according to your instructions, I kept running into the same issue:
Here is a list with all resources that I have created
<img width="1589" alt="image" src="https://github.com/Azure/Azure-Sentinel/assets/26130667/e578315b-4596-4a64-8aa3-a641b89900f7">
Here is the Microsoft Sentinel section with the corresponding workspaces, where you can see that` zf-sentinel-worksapce` is listed
<img width="1696" alt="image" src="https://github.com/Azure/Azure-Sentinel/assets/26130667/4ba986fb-6c6a-452f-bcd8-684bf5b500ee">
<img width="443" alt="image" src="https://github.com/Azure/Azure-Sentinel/assets/26130667/1aa1c5f8-5ee0-46ef-9600-5dc4b5c453db">
However, when I try to set up my App, it keeps showing no available workspaces
<img width="813" alt="image" src="https://github.com/Azure/Azure-Sentinel/assets/26130667/63ff2ff4-b510-42f6-84ee-8978e78c22bd">

**Comment by v-sudkharat** [comment]
Hi @DNRRomero, we have sent a meeting invite. Thanks!

**Comment by DNRRomero** [comment]
Hi @v-sudkharat ! When can we expect to see changes in our marketplace solution?
Thank you!

**Comment by v-sudkharat** [comment]
Hey @DNRRomero, I have sent a mail for required few details from your end to update this solution. Could you please check it.  
Thanks!

**Comment by v-sudkharat** [comment]
Hi @DNRRomero, As we fixed the link issue, so can we close this GitHub issue? waiting for you closer confirmation. Thanks!

**Comment by DNRRomero** [comment]
sure thing! Thank you @v-sudkharat
