### ISSUE TITLE
Pricing details from Sentinel Azure monitoring alerts

### ISSUE THREAD

**Issue by shipothana** [Azure/Azure-Sentinel#10283]
Hi Team,
 
Could you please elaborate on how the pricing is calculated from Sentinel when we are planning to create an Azure monitoring use case?
![Create an alert rule](https://github.com/Azure/Azure-Sentinel/assets/127928822/96235cf7-8e7a-40bd-8a79-44322bb3aeae)

**Comment by v-rusraut** [comment]
Hi @shipothana,
Thanks for flagging this issue, we will investigate this issue and get back to you with some updates by 19 Apr 2024. Thanks!

**Comment by v-rusraut** [comment]
Hi @shipothana,
For pricing details please refer below link.
https://azure.microsoft.com/en-us/pricing/details/microsoft-sentinel/
If you still have issue, please let us know.

Thanks

**Comment by v-rusraut** [comment]
Hi @shipothana,
If your issue resolved, please confirm so we can close this issue.
Thanks

**Comment by v-rusraut** [comment]
Hi @shipothana,
since we have not received a response in the last 5 days, we are closing your issue as per our standard operating procedures. If you still need support for this issue, feel free to re-open at any time. Thank you for your co-operation.
