### ISSUE TITLE
Typo in workbook: Azure-Sentinel/Solutions/Microsoft Defender XDR/Workbooks/MicrosoftDefenderForIdentity.json

### ISSUE THREAD

**Issue by SaiRavi55** [Azure/Azure-Sentinel#10305]
**Describe the bug**
MDI workbook has a typo

**To Reproduce**
See Path:- https://github.com/Azure/Azure-Sentinel/blob/master/Solutions/Microsoft%20Defender%20XDR/Workbooks/MicrosoftDefenderForIdentity.json

**Expected behavior**
Line 190, 191, 852 should have the correction as 'DirectoryEvents' instead of 'DircetoryEvents'

**Screenshots**
<img width="511" alt="image" src="https://github.com/Azure/Azure-Sentinel/assets/120112634/84d85422-05ba-4230-b618-aeb1806fd0aa">

![image](https://github.com/Azure/Azure-Sentinel/assets/120112634/703b3c00-5ee8-4ee8-b142-ff2597fc16cc)

**Comment by v-sudkharat** [comment]
Hi @SaiRavi55, Thanks for flagging this issue, we will investigate this issue and get back to you with some updates by 19-04-2024. Thanks!

**Comment by v-sudkharat** [comment]
Hi @SaiRavi55, We are working on adding changes into the solution. Meanwhile could you please follow below steps and confirms that you get the expected result and also there is not any other issue you are facing in a workbook. 
1. Download the below shared workbook json template - 
[UpdatedWorkbook.json](https://github.com/Azure/Azure-Sentinel/files/14996516/UpdatedWorkbook.json)



2. Click on Advance edit option in workbook, which highlighted in below screenshot -
![image](https://github.com/Azure/Azure-Sentinel/assets/132428394/d72fb516-d1cf-43ca-9905-7fd89b2d21a7)
 
3. Now copy the content which you downloaded from step 1. and past over there. Once you past it click on apply - 
![image](https://github.com/Azure/Azure-Sentinel/assets/132428394/e9971e9d-ed82-4a07-bd7f-75bc7ce490d4)

4. Now click on Done editing Option - 
![image](https://github.com/Azure/Azure-Sentinel/assets/132428394/c42be189-6885-4eea-b733-617ff9b01ffc)

Please let us know if you have any feedback for us. 
Thanks!

**Comment by SaiRavi55** [comment]
Hi @v-sudkharat, it looks fine. Thanks for the quick fix.

<img width="593" alt="image" src="https://github.com/Azure/Azure-Sentinel/assets/120112634/3823f23f-6bf4-4ea5-9d49-7cf411134502">

**Comment by v-sudkharat** [comment]
@SaiRavi55, Thank you for confirmation.

**Comment by v-sudkharat** [comment]
Hey @SaiRavi55, We have raised and Merged the PR with the correction. The changes will get reflected into upcoming solution version. 
Closing this issue from GitHub. If you still need support for this issue, feel free to re-open it any time. Thank you for your co-operation.
