### ISSUE TITLE
Impossible to install Microsoft Defender for Cloud connector

### ISSUE THREAD

**Issue by ViktorArnekvist** [Azure/Azure-Sentinel#10306]
**Describe the bug**
When installing the Microsoft Defender for Cloud connector in Sentinel, only the legacy connector installs successfully. The preview one, that Microsoft recommends is not successful.

**To Reproduce**
1. Go to content Hub
2. Search for Microsoft Defender for Cloud
3. Install the connector
4. See error when refreshing the connector page

**Expected behavior**
The preview connector should be installed along with the legacy one without issues.

**Additional context**
Error mesage:
_The following codeless connectors are not valid, and will not be displayed: Connector display name: Tenant-based Microsoft Defender for Cloud (Preview), ConnectorId: /subscriptions/providers/Microsoft.SecurityInsights/dataConnectors/MicrosoftDefenderForCloudTenantBased, ConnectorKind: StaticUI, Error: Error: staticConnectorModel for microsoftdefenderforcloudtenantbased was not found in static connectors list. Try to update the solution, if there is an update available_

**Comment by v-sudkharat** [comment]
Hi @ViktorArnekvist, Thanks for flagging this issue, we will investigate this issue and get back to you with some updates by 19-04-2024. Thanks!

**Comment by liam-stevenson** [comment]
This also occurs when trying to deploy the connector as an ARM template and is not just limited to using the portal.

**Comment by lwardleACE** [comment]
Hi @v-sudkharat I get the error both when using the ARM template method and adding through the portal.

**Comment by v-sudkharat** [comment]
Hi @ViktorArnekvist / @liam-stevenson / @lwardleACE, We have checked on this issue and the fix for this issue will get in upcoming solution version (3.0.2). 
Meanwhile, to get unblock you from this issue could you please custom deploy the Solution MainTemplate and check whether your issue get resolved. 
Sharing the MainTemplate and Custom deployment steps- 

Custom Deployment -  [Custom Deployment of the Solution - Copy.docx](https://github.com/Azure/Azure-Sentinel/files/14342731/Custom.Deployment.of.the.Solution.-.Copy.docx)

Main template: - [mainTemplate.json](https://github.com/Azure/Azure-Sentinel/files/15023766/mainTemplate.json)

Thanks!

**Comment by ViktorArnekvist** [comment]
Hi! @v-sudkharat 
Thanks for the proposed solution. I was successfully able to deploy the resource with the ARM-template. I can see the connector now under **Data Connectors**. I was also able to connect the connector successfully after installation. I have also tested the incident/alert-flow and incidents now show up as intended.

Thanks!

**Comment by BDOMichaelKirstNeshva** [comment]
Hi,
I'm using the code from "All-in-One"
there is a reference to a template with a guid.
What is the new artifact reference?

templateLink": {
                    "uri": "https://catalogartifact.azureedge.net/publicartifacts/azuresentinel.azure-sentinel-solution-microsoftdefenderforcloud-7f61aa4d-8e77-42b6-93f7-e78561b05e98-azure-sentinel-solution-microsoftdefenderforcloud/Artifacts/mainTemplate.json",
                    "contentVersion": "1.0.0.0"
                    
Thanks

**Comment by v-sudkharat** [comment]
@ViktorArnekvist, So as your issue is resolved, can we close this issue from GitHub? 3

**Comment by ViktorArnekvist** [comment]
@v-sudkharat You can close the issue from my side.

**Comment by v-sudkharat** [comment]
@ViktorArnekvist, Thank you for confirmation. Closing this issue. If you still need support for this issue, feel free to re-open it any time. Thank you for your co-operation.

**Comment by kristofdepauw** [comment]
Hello, I just installed Solution 3.0.2 but have the same issue. Can this be checked please?
