### ISSUE TITLE
Have a branch that reflects the currently available content in the Content Hub

### ISSUE THREAD

**Issue by sebovzeoueb** [Azure/Azure-Sentinel#10327]
**Is your feature request related to a problem? Please describe.**
I'm using this repository to automate installation of Content Hub content via an ARM template. If you want a better idea of what we're doing, here's the repo: https://github.com/InfoSecInnovations/Sentinel-Service-Offering. The idea is to be able to 1-click deploy in a repeatable manner a Sentinel enabled Log Analytics Workspace with our recommended set of content enabled.

If there is a better way to do this, please direct me towards that and close this issue!

The problem is that the versions on here can be ahead of what's actually available on the Content Hub, for a concrete example see #10326 in which the newer item has errors, but the current one doesn't.

**Describe the solution you'd like**
Create a branch (and show the name of that branch in the README to avoid getting lost in the massive list of branches) which reflects the currently available versions on the Azure Portal Content Hub.

Or, provide another way to enable Content Hub solutions with an ARM template.

**Comment by v-rusraut** [comment]
Hi @sebovzeoueb,
Thanks for flagging this issue, we will investigate this issue and get back to you with some updates by 26 Apr 2024. Thanks!

**Comment by v-rusraut** [comment]
Hi @sebovzeoueb,
Please refer below link for customize repository deployments.
https://learn.microsoft.com/en-us/azure/sentinel/ci-cd-custom-deploy?tabs=github
If you still have issue, please let us know.
Thanks

**Comment by sebovzeoueb** [comment]
This is not at all what my issue is. I would like to deploy content from this (i.e. Azure/Azure-Sentinel) repository, not custom content, using ARM templates. The goal is to reproduce what the user gets by clicking stuff in the Portal web UI using an ARM template so we can install a set of publicly available Content Hub items in a single deploy on any Azure instance we wish, instead of having to click a bunch of UI every time. This repo is quite a good starting point for grabbing the templates, however the problem is that the main branch is ahead of the versions published on the Content Hub so it's difficult to reproduce 1:1 what the user would get going through the Portal.

My suggestion would be to have a GitHub branch in the Azure/Azure-Sentinel repository that accurately reflects the versions currently available in the Content Hub to avoid issues with version mismatches and errors from installing not yet supported new content.

**Comment by v-rusraut** [comment]
Hi @sebovzeoueb,
The main branch is ahead of the versions published on the Content Hub ,beacuse after merging changes in main branch there is process to publish the content in content hub ,so it taking time to availble that content. 
Currently there is no plan to create branch in Azure/Azure-Sentinel repository
We have noted this and will share this with our respective concern team.
So,currently closing this issue from GitHub. If you still need support for this issue, feel free to re-open it any time. Thank you for your co-operation.
