### ISSUE TITLE
Azure firewall logs not present in ASIM - function is querying wrong tables

### ISSUE THREAD

**Issue by borutlape1** [Azure/Azure-Sentinel#10325]
**Describe the bug**
Azure Firewall logs are not picked up by the builtin function "_ASim_NetworkSession_AzureFirewallV01" because it is querying wrong tables.

These are the queries from the function :

    let AzureFirewallNetworkRuleLogs = 
        AzureDiagnostics
        | where not(disabled)
        | where Category == "AzureFirewallNetworkRule"
        | where isnotempty(msg_s)
        | project msg_s, OperationName, SubscriptionId, ResourceId, TimeGenerated, Type, _ResourceId;
    let AzureFirewallSessionLogs = 
        AzureFirewallNetworkRuleLogs
        | where OperationName in ("AzureFirewallNetworkRuleLog","AzureFirewallThreatIntelLog")

And such Category/Tables do not exist in our setup, the Azure FW logs are present in different tables:

![image](https://github.com/Azure/Azure-Sentinel/assets/72254962/24015d53-2ed2-4b67-a7a7-4e8e8041b69e)

Here is the Diagnostic setting for the FW:

![image](https://github.com/Azure/Azure-Sentinel/assets/72254962/df16c593-241c-464f-9784-52acb85c534a)

Thanks,
Borut

**Comment by vakohl** [comment]
@borutlape1 currently we only support Azure Firewall logs ingested in 'AzureDiagnostics' table as part of _Im_NetworkSession function. Please see https://learn.microsoft.com/en-us/azure/firewall/logs-and-metrics#legacy-azure-diagnostics-logs

What you are using are structured logs, which currently we do not support. We have added this request to our backlog and we will try add support for structured tables too. Sorry but we cannot give any timelines at this point.
