### ISSUE TITLE
certain Analytics Rules using the AzureActivity table expect Resource and ResourceId columns to be present but they aren't always

### ISSUE THREAD

**Issue by sebovzeoueb** [Azure/Azure-Sentinel#10340]
**Describe the bug**
Several rules relating to the AzureActivity table fail to install properly in a clean Log Analytics Workspace because the Resource and ResourceId columns don't always exist. For example "Suspicious granting of permissions to an account". I am deploying an ARM template that creates the Sentinel instance with the Data Connector logs configured, and just after another ARM template with the Analytics Rules. I have however tested this manually through the Portal UI and it can still happen.

**To Reproduce**
- Create a clean Sentinel instance
- Enable AzureActivity Data Connector
- Enable "Suspicious granting of permissions to an account" Analytics Rule
- Sometimes it works, sometimes it errors due to Resource and ResourceId columns missing

**Expected behavior**
Always be able to install Analytics Rules that use AzureActivity logs if I configured the Data Connector, even on a clean instance of Sentinel.

**Additional context**
I suspect this is related to there not having yet been any activity logs relating to a Resource, I believe these columns must get created when a Resource activity happens.

**Comment by Kaloszer** [comment]
@sebovzeoueb The only way we found to at least partially alleviate this is to parse the actual fields within the given workspace and based on that deploy ARs that have those tables/columns. You can also get an issue where the 'table' is a function within a workspace and that also will cause this issue to happen.

**Comment by sebovzeoueb** [comment]
From what I can see, I think that some columns are in a default schema and will be created on connecting logs to the workspace, but Resource and ResourceId are not in this schema for some reason in spite of being listed in the documentation: https://learn.microsoft.com/en-us/azure/azure-monitor/reference/tables/azureactivity.

For example I see the one called _ResourceId is being created every time I run my template.

**Comment by v-rusraut** [comment]
Hi @sebovzeoueb,
Please provide error screen shot which you are getting while creating Analytical Rule.
Thanks

**Comment by sebovzeoueb** [comment]
![image](https://github.com/Azure/Azure-Sentinel/assets/7989595/455fac69-1101-4ae2-8f9f-c768e9d2ebb3)

Here you go!

**Comment by v-rusraut** [comment]
Hi @sebovzeoueb,
Please share the ARM templates which you are using to create Sentinel Instance.
Also create clean Log Analytics Workspace and share the schema of table AzureActivity.
Please refer below screenshot.
<img width="455" alt="image" src="https://github.com/Azure/Azure-Sentinel/assets/126679503/d16d44e3-718e-405a-aad9-47efe7a6adad">

**Comment by sebovzeoueb** [comment]
Well this is annoying, it seems to be an intermittent bug, today I've tried creating multiple workspaces both manually and with my template and it's been fine.

This is the template btw: https://raw.githubusercontent.com/InfoSecInnovations/Sentinel-Service-Offering/restructure/arm-templates/deploy-sentinel.json

But yeah, it's one of those bugs that randomly happens just enough to be annoying, but not enough to solidly reproduce.

**Comment by v-rusraut** [comment]
Hi @sebovzeoueb,
We have noted this and will share this with our respective concern team.
So, currently closing this issue from GitHub. If you still need support for this issue, feel free to re-open it any time. Thank you for your co-operation.
