### ISSUE TITLE
NGINXHTTPServer Parsers doesn't include information about the log source hostname.

### ISSUE THREAD

**Issue by ecIib7L** [Azure/Azure-Sentinel#10349]
[**Is your feature request related to a problem? Please describe.**
NGINXHTTPServer Parsers doesn't include information about the log source hostname.

**Describe the solution you'd like**
Add the log source hostname to the parser for example: extend EventSource = ManagementGroupName

**Describe alternatives you've considered**

**Additional context**
https://github.com/Azure/Azure-Sentinel/blob/master/Solutions/NGINX%20HTTP%20Server/Parsers/NGINXHTTPServer.txt

**Comment by v-sudkharat** [comment]
Hi @ecIib7L, Thanks for flagging this issue, we will investigate this issue and get back to you with some updates by 26-04-2024. Thanks!

**Comment by v-sudkharat** [comment]
Hey @ecIib7L, Could you please check the below updated parser and let us know it resolve your issue? 
Note : The **ManagementGroupName** is having same **hostname** as **Computer**, so you will get the same value for **EventSource**. 
[NGINX.txt](https://github.com/Azure/Azure-Sentinel/files/15147767/NGINX.txt)

Please share the sample data with us if still you are not getting the log source hostname. 
Thanks!

**Comment by ecIib7L** [comment]
Hi @v-sudkharat I saw that the nginx_errorlog_events doesn't have EventSource contigured. Could you please also update this part? I think this will result in errors in the "union....project... EventSource" expression.
Yes this will resolve my issue. I will update this for our directories when this is pushed to the content hub.

**Comment by v-sudkharat** [comment]
@ecIib7L, We have just updated the parser, could you please check it into your available data and let us know if it running correctly? 
[NGINX.txt](https://github.com/Azure/Azure-Sentinel/files/15148168/NGINX.txt)

Please share the parser successfully running result screenshot over here or this mail id - v-sudkharat@microsoft.com
So, we can procced to update this into content hub. Thanks!

**Comment by ecIib7L** [comment]
Hi @v-sudkharat Yes, the parser seems working for both access logs and error logs:
![image](https://github.com/Azure/Azure-Sentinel/assets/167533233/edeff22f-8507-4835-8f90-b18c642b5fee)

**Comment by v-sudkharat** [comment]
@ecIib7L, thanks for the update. we will finalize it and proceed to raise PR. Could you please let us know can we close this issue from GitHub. 
Thanks!

**Comment by ecIib7L** [comment]
@v-sudkharat Sure, you can close this issue. Thanks for your help.

**Comment by v-sudkharat** [comment]
Thanks for confirmation. Closing this issue. If you still need support for this issue, feel free to re-open it any time. Thank you for your co-operation.
