### ISSUE TITLE
Enforce AWS role naming requirements

### ISSUE THREAD

**Issue by jeffb4** [Azure/Azure-Sentinel#10363]
**Is your feature request related to a problem? Please describe.**

For the AWS S3 connector IAM role, it is strictly required that the role be prefixed with `OIDC_` . It will not work if that is not done, but the script does not enforce the naming. This leads to an ambiguous error message in the Sentinel web console.

**Describe the solution you'd like**
I would like the automation script to throw an error if an attempt is made to use an IAM role name that does not begin with `OIDC_`

**Describe alternatives you've considered**

**Additional context**
This requirement is documented in the Sentinel documentation https://learn.microsoft.com/en-us/azure/sentinel/connect-aws?tabs=s3#:~:text=to%20Microsoft%20Sentinel.-,The%20name%20must%20include%20the%20exact%20prefix%20OIDC_%2C%20otherwise%20the%20connector%20will%20not%20function%20properly.,-Use%20the%20values

**Comment by v-sudkharat** [comment]
Hey @jeffb4, Thank you for reporting this issue. we have noted this feature request and will share this with our respective concern team. Currently we can't provide any ETA for this. but once we get any further info from our team will share update to you. 
So, closing this issue from GitHub. If you still need support for this issue, feel free to re-open it any time. Thank you for your co-operation.
