### ISSUE TITLE
Formatting for Syslog integrated logs

### ISSUE THREAD

**Issue by DSharpPro** [Azure/Azure-Sentinel#10360]
Hi All,
We are having some problems with the formatting of the syslog messages coming in from from the server, due to the formatting within Sentinel the characters that would separate the values (to allow it to be formatted) correctly are all removed. Has anyone come across a way to fix this up? 

The problem is that when the log comes in it looks like this:

Time Date Event Event Details etc.

With no symbol included there is no way to split the log in a way that will allow them to be formatted correctly - we can format on length but as all logs are no the same length the formatting becomes quite unreadable to the human eye when reviewing.

Thanks!

**Comment by v-rusraut** [comment]
Hi @DSharpPro,
Thanks for flagging this issue, we will investigate this issue and get back to you with some updates by 01 may 2024. Thanks!

**Comment by v-rusraut** [comment]
Hi @DSharpPro,
Please share more details about the issue.
In which solution you are getting this issue and what is the error?
Thanks

**Comment by v-rusraut** [comment]
Hi @DSharpPro,
Please provide update on above comment.
Thanks

**Comment by v-rusraut** [comment]
Hi @DSharpPro , Gentle Reminder: We are waiting for your response on this issue. If you still need to keep this issue active, please respond to it in the next 2 days. If we don't receive a response by 06-05-2024 date, we will be closing this issue. 		
Thanks!

**Comment by v-rusraut** [comment]
Hi @DSharpPro  , since we have not received a response from you, we are closing this issue as per our standard operating procedures. If you still need support for this issue, feel free to re-open at any time. Thank you for your co-operation.
