### ISSUE TITLE
Can't use Intro to KQL workbook

### ISSUE THREAD

**Issue by piovisqui** [Azure/Azure-Sentinel#10362]
Hello.

When using the Intro to KQL workbook it gets a JSON from this URL: https://[raw.githubusercontent.com/Azure/Azure-Sentinel/master/Tools/IntrotoKQL/all_exercises.json](https://raw.githubusercontent.com/Azure/Azure-Sentinel/master/Tools/IntrotoKQL/all_exercises.json)

However, the GET returns "We could not connect to the server, make sure CORS is enabled in raw.githubusercontent.com".

![image](https://github.com/Azure/Azure-Sentinel/assets/11858817/b9f1d8a9-d903-4a3b-ac00-93d6e8693e43)

How can I make it work? Or is it an error inside the GitHub repo?

**Comment by v-sudkharat** [comment]
Hey @piovisqui, Sharing the step's to configure the workbook- 

1. Click on edit tab -
![image](https://github.com/Azure/Azure-Sentinel/assets/132428394/6bf50b25-c032-4232-a49b-79d3f4a0d5a5)

2. Select check box of json and click on edit -
![image](https://github.com/Azure/Azure-Sentinel/assets/132428394/b49c86e6-dbc3-436d-ad7c-6f802b71bfd1)

3. Click in check box which is highlighted below and run the query -
![image](https://github.com/Azure/Azure-Sentinel/assets/132428394/e022ce14-3d7a-4094-b1d6-59d1469788c9)

4.
![image](https://github.com/Azure/Azure-Sentinel/assets/132428394/b761308f-f9e7-43f5-bb85-f35c7f0cb6ce)

5. Once the query run, check on save and chick on done editing- 
![image](https://github.com/Azure/Azure-Sentinel/assets/132428394/fada0b5d-befd-4320-86ab-37148d39a59d)

6. 
![image](https://github.com/Azure/Azure-Sentinel/assets/132428394/36b28b37-9188-4f55-906e-0838507d8831)

Please let us know if you still facing the issue. 
Thanks!

**Comment by piovisqui** [comment]
Thank you, I missed that.
