### ISSUE TITLE
Dead Letter function in LogStash Plugin

### ISSUE THREAD

**Issue by mitsuo0114** [Azure/Azure-Sentinel#1036]
**Is your feature request related to a problem? Please describe.**
In current implementation at [1], LogStash plugin possibly lose our data before sending data to Azure when the network is unreachable for long time.

[1] https://github.com/Azure/Azure-Sentinel/blob/master/DataConnectors/microsoft-logstash-output-azure-loganalytics/lib/logstash/logAnalyticsClient/logStashAutoResizeBuffer.rb#L90

**Describe the solution you'd like**
I'd like to have Dead Letter Queue function in this plugin. More details are in [2].

With Dead Letter Queue Input plugin [3], we can handle undelivered message as we like if it is adaptable.

As [2] describe, currently this is implemented only in ElasticSearch output plugin but I believe this error handling is suitable way as entire LogStash plugins.

[2] https://www.elastic.co/guide/en/logstash/current/dead-letter-queues.html
[3] https://www.elastic.co/guide/en/logstash/current/plugins-inputs-dead_letter_queue.html

**Describe alternatives you've considered**
More simply, if we can just output undelivered message as file, it should be good.

**Additional context**
Because this plugin output targets only Azure cloud, I believe the down time can be relatively longer than more vicinity systems, that include network error.
Especially in my context, we are transferring Security related information, which should not be loss as much as possible.

**Comment by NoamLandress** [comment]
Thanks for the contribution, we are taking a look and will address the issue.
