### ISSUE TITLE
Intermittent  Entity mapping from Defender Incidents

### ISSUE THREAD

**Issue by ish-rafaeldamiani** [Azure/Azure-Sentinel#10372]
**Describe the bug**
Incidents created in Microsoft Defender will not always have their entities mapped in Sentinel. Entities don't appear on the incident analysis screen or via KQL query.

**To Reproduce**
1. Click on the Incidents menu and select an incident originating from Defender
2. When previewing the incident or clicking View Full Details, entities aren't displayed

**Expected behavior**
The entities (user, ip, host, etc.) will be displayed in all incidents.

**Screenshots**
Prints of incidents without entities and executing the query by clicking on the System Alert ID link

![Suspected brute-force attack attempt involving one user](https://github.com/Azure/Azure-Sentinel/assets/160948785/600a097b-7a0d-41ae-9dac-ebf1a99bef44)
![query security alert](https://github.com/Azure/Azure-Sentinel/assets/160948785/4320a3c6-e6d3-420f-aa63-12bd89a33456)

![Email messages containing malicious file removed after delivery involving one user](https://github.com/Azure/Azure-Sentinel/assets/160948785/00ac4b82-71ed-4c02-91dc-283569b4446f)
![query security alert 2](https://github.com/Azure/Azure-Sentinel/assets/160948785/6e6fe284-1922-416a-824f-5d417522f58c)

**Additional context**
As shown in the prints, some incidents originating from Defender are sent via data connector without the entities. Even running a query searching for the title or system alert id, the information is not found.

**Comment by v-rusraut** [comment]
Hi @ish-rafaeldamiani,
Thanks for flagging this issue, we will investigate this issue and get back to you with some updates by 01 May 2024. Thanks!

**Comment by v-rusraut** [comment]
Hi @ish-rafaeldamiani,

- Please help us to understand from which source you are getting incident - Sentinel or Defender portal
- If from sentinel then which Analytical Rule you are using here and also confirm that in Entity mapping section have you added any entity, please refer below screen shot.
<img width="474" alt="image" src="https://github.com/Azure/Azure-Sentinel/assets/126679503/f8ddf7fb-50e2-493e-86be-081a91116f85">

- If from defender endpoint please check entities are already available in defender portal itself.

Thanks

**Comment by ish-rafaeldamiani** [comment]
Hi, @v-rusraut 

If you look at the first print it has Alert products names: Microsoft Defender for Cloud. This behavior occurs with incidents originating from Defender (for cloud, endpoint, office365).

There is no occurrence with incidents originating from Analytics Rules.

Entities can be located in the Defender portal. But the problem in this case is that some SOC analysts are not allowed access to the Defender portal.

What do I need to know if this behavior of entities is not sent from the Defender portal to Sentinel. Is it normal or possible bug?

**Comment by v-rusraut** [comment]
Hi @ish-rafaeldamiani,
We are working with respective team, we will update you.
Thanks

**Comment by v-rusraut** [comment]
Hi @ish-rafaeldamiani,
We are waiting for response from respective team, we will update you.
Thanks

**Comment by ish-rafaeldamiani** [comment]
Hi, @v-rusraut 

I still awaiting feedback about this issue.

**Comment by v-rusraut** [comment]
Hi @ish-rafaeldamiani,
We are waiting for response from respective team, if we receive any update, we will update you.

**Comment by v-rusraut** [comment]
Hi @ish-rafaeldamiani,
We have received response from receptive team, please use the new Tenant-based Microsoft Defender for Cloud connector, which is in currently PREVIEW state, which allows you to collect Defender for Cloud alerts over your entire tenant, without having to enable each subscription separately. (The connector is highlighted into below screenshot.)
<img width="895" alt="image" src="https://github.com/Azure/Azure-Sentinel/assets/126679503/da6db5d8-4d21-4ad8-bfce-6e9255ab8b6a">

After using above mentioned connector if you still face any issue, kindly raise support ticket in azure portal, so our concern team will check on this and connect with you if required. 

Please let us know once if you raise support ticket case so we can close this issue from GitHub.

Thanks

**Comment by v-sudkharat** [comment]
Hi @ish-rafaeldamiani, Gentle Reminder: We are waiting for your response on this issue. If you still need to keep this issue active, please respond to it in the next 2 days. If we don't receive a response by 05-07-2024 date, we will be closing this issue. 		
Thanks!

**Comment by v-sudkharat** [comment]
Hi @ish-rafaeldamiani, since we have not received a response in the last 5 days, we are closing your issue as per our standard operating procedures. If you still need support for this issue, feel free to re-open at any time. Thank you for your co-operation.
