### ISSUE TITLE
Unable to delete Threat Intelligence Upload Indicators API (Preview) dataconnector

### ISSUE THREAD

**Issue by hakfo** [Azure/Azure-Sentinel#10385]
**Describe the bug**
We are unable to delete the Threat Intelligence Upload Indicators API (Preview) dataconnector
![image](https://github.com/Azure/Azure-Sentinel/assets/43959140/f6a7b532-0baf-4ea9-acc8-538b58b44d83)

It says we need to disconnect the dataconnector, but there is no disconnect button. 

**To Reproduce**
1. Go to the dataconnector
2. Press delete
![image](https://github.com/Azure/Azure-Sentinel/assets/43959140/07bd0ec2-c9bc-4731-8551-aa84f88e742a)

**Comment by v-rusraut** [comment]
Hi @hakfo,
Thanks for flagging this issue, we will investigate this issue and get back to you with some updates by 03-05-2024. Thanks!

**Comment by hakfo** [comment]
@v-rusraut is there any update regarding this issue?

**Comment by v-rusraut** [comment]
Hi @hakfo,
We updated query of connectivityCriterias,So to unblock you from this issue could you please custom deploy the Solution MainTemplate and check whether your issue get resolved.
Sharing the MainTemplate and Custom deployment steps-
Custom Deployment - [CustomDeploymentoftheSolution.docx](https://github.com/Azure/Azure-Sentinel/files/15219712/CustomDeploymentoftheSolution.docx)
Main template: -[mainTemplate.json](https://github.com/Azure/Azure-Sentinel/files/15219718/mainTemplate.json)
After Custom deployement, connector will disconnect, then you can delete this data connector.
Thanks

**Comment by hakfo** [comment]
Hi @v-rusraut.

I tried your solution of deploying the custom deployment. Unfortunately even after waiting several hours (even overnight), it still does not disconnect. Is there another fix we could try?

**Comment by ThePeteStore** [comment]
Doesn't look like the template works either as I get the following error:

{"code":"InvalidTemplate","message":"Deployment template validation failed: 'The template resource '/Microsoft.SecurityInsights/-dc-c6disteyi7k44' for type 'Microsoft.OperationalInsights/workspaces/providers/contentTemplates' at line '455' and column '87' has incorrect segment lengths. A nested resource type must have identical number of segments as its resource name. A root resource type must have segment length one greater than its resource name. Please see https://aka.ms/arm-syntax-resources for usage details.'."}

**Comment by v-rusraut** [comment]
Hi @ThePeteStore,

Please verify that you provided correct value in below places like workspace,Region etc

![image](https://github.com/Azure/Azure-Sentinel/assets/126679503/232e28f6-da7d-418b-8a52-3296cf83e502)

Thanks

**Comment by v-rusraut** [comment]
Hi @hakfo,
Please confirm that still you are continuously getting log from this connector.
Thanks

**Comment by ThePeteStore** [comment]
I can confirm that we are still ingesting data after successfully running the script above

**Comment by v-rusraut** [comment]
> I can confirm that we are still ingesting data after successfully running the script above

Are you able to deploy mainTemplate  now ?

**Comment by v-rusraut** [comment]
> Hi @hakfo, Please confirm that still you are continuously getting log from this connector. Thanks

Please confirm on this.

**Comment by hakfo** [comment]
@v-rusraut I can also confirm that we are still ingesting data. It is still not possible to delete.

**Comment by ThePeteStore** [comment]
@v-rusraut Yes, we deployed the mainTemplate the day of your suggestion and we are still ingesting data.

**Comment by v-rusraut** [comment]
Hi @hakfo,
We are working with respective team, we will update you.

**Comment by hakfo** [comment]
@v-rusraut are there any further updates regarding this issue?

**Comment by v-rusraut** [comment]
Hi @hakfo,
Still we are working with respective team, we will update you.
Thaks

**Comment by v-rusraut** [comment]
Hi @hakfo,
We got response from respective team that, this is known UX bug, and they will fix this issue till end of June, so currently closing this issue, feel free to re-open it any time. Thank you for your co-operation.

**Comment by hakfo** [comment]
Hi @v-rusraut im just checking in to check with you if you have any confirmation from the respective team that this issue has been solved. Have they solved it yet?

**Comment by CJWNom** [comment]
Hi @v-rusraut @v-sudkharat is there any update on this? We are also experiencing the same issue. No logs ingested by this connector in over 3 days, yet it's still 'connected' and unable to be deleted.

**Comment by chritea** [comment]
Got the same issue with one of our customers. Any update on the matter @v-rusraut ?
Thanks in advance

**Comment by Abubaker3030** [comment]
I found the solution. 

-Go into Content Hub, and search for Threat Intelligence. If you dont have the Threat Intelligence hub then install it

-Select Threat Intelligence hub and click on manage. You will a see a list of 5 data connectors in it. 

-Click on Threat Intelligence Upload Indicators API (Preview). Once it opens, click on the 3 dots next to the connector name under updates and select "Delete" or click on "Open Connector Page", then delete from there. 

I couldnt delete it from the data connectors directly, so this Content Hub method worked and the data connector is gone now.
