### ISSUE TITLE
Azure-Sentinel/Tools /Sentinel-All-In-One: Possibility to add tags

### ISSUE THREAD

**Issue by combitech-soc** [Azure/Azure-Sentinel#10388]
We're sorely missing the possibility to add tags to relevant artefacts, specifically to resource groups, when creating a deployment from the template.

**Comment by v-sudkharat** [comment]
Hey @combitech-soc, Thank you for reporting the issue. Could you please provide more context about this issue and if possible please share details with screenshots, so we can check into it. Thanks!

**Comment by combitech-soc** [comment]
Hi.
The context is that many companies has policies requiring tagging when creating certain artefacts, typically resource groups, but basically anything that might have a cost atteched to it. In such cases the otherwise brilliant script won't work, and Sentinel has to be set up manually, which is unwanted.
Also, the script could probably do with a general update, as it appears it doesn't know about Entra ID, only Azure Active Directory. It might be other changes too in the Azure ecosystem that needs to be reflected in the script.

**Comment by v-sudkharat** [comment]
Hey @combitech-soc, Sorry for delay in response. can you please share screenshot with us by steps to repro for this. This will help us to understand more about this issue. 
Thanks!

**Comment by combitech-soc** [comment]
Hi.
I don't see how I can make a screenshot of something that doesn't exist.

//Lasse

**Comment by v-sudkharat** [comment]
@combitech-soc, Noted. We will check with issue with our respective team and will update you. Thanks!

**Comment by v-sudkharat** [comment]
Hey @combitech-soc, We have shared this feature request/enhancement for tool with our respective team, but unable to provide any ETA as of now. Closing this issue. If you still need support for this issue, feel free to re-open it any time. Thank you for your co-operation.
