### ISSUE TITLE
GoogleWorkspaceReports - getting API error, Quota exceeded for quota metric

### ISSUE THREAD

**Issue by dmkolfl** [Azure/Azure-Sentinel#10389]
Hello!

I'm getting the error below for my FunctionApp. The API quota in GCP is standard - 2600 per minute. All settings for the FunctionApp are by default.

Google does not accept my request to increase the quota.

Something wrong while getting the results. Exception error text: <HttpError 403 when requesting https://admin.googleapis.com/admin/reports/v1/activity/users/all/applications/access_transparency?maxResults=1000&startTime=2024-03-11T05%3A20%3A00.000Z&endTime=2024-03-11T05%3A23%3A00.000Z&alt=json returned 'Quota exceeded for quota metric Queries and limit Queries per minute per user of service admin.googleapis.com for consumer project_number:227460265128.'. Details: '[{message: 'Quota exceeded for quota metric Queries and limit Queries per minute per user of service admin.googleapis.com for consumer project_number:227460265128.', domain: usageLimits, reason: rateLimitExceeded}]'>

Why does it request the logs from March 2024 if the current date is April 25, 2024?

**Comment by ingest0x** [comment]
We have started to get this error also suddenly

**Comment by dmkolfl** [comment]
I verified and our account still has required permissions but at first time we got the error about the quota first and then we were flooded by logs for AppInsights.

**Comment by dmkolfl** [comment]
Today I started the app again today, and it did more than 21k requests in a minute and, of course, it started failing because it reached the quota. Why does it generate so many requests?

**Comment by v-sudkharat** [comment]
Hi @dmkolfl, Thanks for flagging this issue, we will investigate this issue and get back to you with some updates by 03-05-2024. Thanks!

**Comment by sc-roberts** [comment]
Keen to hear on this as we ran into the same problem and overnight it logged over 100GB or data into Sentinel through App traces and metrics, and $50 charge for the function app.

**Comment by dmkolfl** [comment]
> Hi @dmkolfl, Thanks for flagging this issue, we will investigate this issue and get back to you with some updates by 03-05-2024. Thanks!

Do you have any updates about this topic?

**Comment by v-sudkharat** [comment]
Hi @ingest0x, We are still checking on this issue, and need more time investigate this issue. We will update you once repro done from our end. Thanks!

**Comment by dmkolfl** [comment]
Hi @v-sudkharat 
I replaced the link for this setting and am monitoring the status. Give me 2-3 days to be able to verify it.

**Comment by v-sudkharat** [comment]
@dmkolfl, Sure. Please let us know once done

**Comment by v-sudkharat** [comment]
@ingest0x, Noted. Please let us know the result. Thanks!

**Comment by v-sudkharat** [comment]
Hey @dmkolfl, Are we good with the connector? waiting for your response.

**Comment by dmkolfl** [comment]
I think we are good for now. Thank you for your support

**Comment by v-sudkharat** [comment]
@dmkolfl, Thanks for the confirmation. So, closing this issue. If you still need support for this issue, feel free to re-open it any time. Thank you for your co-operation.
