### ISSUE TITLE
URI pattern being used is being flagged by ttk

### ISSUE THREAD

**Issue by ashwinvenkatesha** [Azure/Azure-Sentinel#10391]
**Describe the bug**
I am defining a variable called LogAnalyticsURI whose value is a constructed in the below manner.
`"variables" : {
...	
"LogAnaltyicsUri":"[replace(environment().portal, 'https://portal', concat('https://', toLower(parameters('WorkspaceId')), '.ods.opinsights'))]",
...
}`

When I run arm-ttk locally, this complains that
`  [-] URIs Should Be Properly Constructed (17 ms)                                                                
        Function 'concat' found within 'LogAnaltyicsUri' Line: 95, Column: 6                                       
        Function 'concat' found within 'LogAnaltyicsUri' Line: 101, Column: 6                                                
`

Tried changing it to,
`"LogAnaltyicsUri": "[format('https://%s.ods.opinsights.azure.com', parameters('AzureSentinelWorkspaceId'))]",  
`
This fails as well with the below message
`Function 'format' found within 'LogAnaltyicsUri' Line: 95, Column: 6`

**To Reproduce**
1. In mainTemplate.json, create a variable in the below manner
 `"variables" : {
...	
"LogAnaltyicsUri":"[replace(environment().portal, 'https://portal', concat('https://', toLower(parameters('WorkspaceId')), '.ods.opinsights'))]",
...
}`
2. Run arm-ttk test locally to validate.

**Expected behavior**
Since most of the contributors are defining this variable in this manner, this definition of LogAnalyticsURi should be allowed.

**Screenshots**
<img width="756" alt="image" src="https://github.com/Azure/Azure-Sentinel/assets/156476492/dd940a22-f1f6-4af0-b9cf-9bb8f555fc9f">

I am wondering if I submit a pull request, will the same failure occur

**Comment by v-rusraut** [comment]
Hi @ashwinvenkatesha,
Thanks for flagging this issue, we will investigate this issue and get back to you with some updates by 03 May 2024. Thanks!

**Comment by v-sabiraj** [comment]
Hi @ashwinvenkatesha , can we get to know on which maintemplate you are running the Arm-ttk?
Also, can you please let us know what is the file where you have added the variable? 

If we have "uri" or "url" keyword mentioned in variable name, it will fail with above mentioned error.

**Comment by v-sabiraj** [comment]
Hi @ashwinvenkatesha , as per the discussion on call, I think you will not be following the approach to call the function app from the workbook, so are we good to close on this? 
thanks.

**Comment by v-rusraut** [comment]
Hi @ashwinvenkatesha, Gentle Reminder: We are waiting for your response on this issue. If you still need to keep this issue active, please respond to it in the next 2 days. If we don't receive a response by 15-05-2024 date, we will be closing this issue.
Thanks!

**Comment by v-rusraut** [comment]
Hi @ashwinvenkatesha, since we have not received a response from you, we are closing this issue as per our standard operating procedures. If you still need support for this issue, feel free to re-open at any time. Thank you for your co-operation.
