### ISSUE TITLE
Dynatrace Solution missing list of playbooks in Azure Portal on install 

### ISSUE THREAD

**Issue by keyoke** [Azure/Azure-Sentinel#10424]
**Describe the bug**
Dynatrace Solution missing list of playbooks in Azure Portal on install 

**To Reproduce**
1. Go Azure Portal
2. Select the Microsoft Sentinel workspace
3. open content hub
4. Install Dynatrace solution
5. complete the steps in the wizard until you reach Playbooks tab

**Expected behavior**
Present a list of all the playbooks which will be installed

**Screenshots**
![image](https://github.com/Azure/Azure-Sentinel/assets/183547/ee5e78ca-56ad-4e75-b84e-e6fea534605e)

**Comment by v-sudkharat** [comment]
Hi @keyoke, Thanks for flagging this issue, we will investigate this issue and get back to you with some updates by 09-05-2024. Thanks!

**Comment by keyoke** [comment]
Hello @v-sudkharat any news? We are not able to publish the latest package because of this issue.
Many thanks

**Comment by v-sudkharat** [comment]
Hi @keyoke, We have shared this issue to our packaging team, and currently they are checking into it. Meanwhile please use below shared CreateUi file to update with existing issue, in which we have added the generic playbook description. Thanks! 
[createUiDefinition.json](https://github.com/Azure/Azure-Sentinel/files/15345910/createUiDefinition.json)

**Comment by v-sudkharat** [comment]
Hi @keyoke, Waiting for your response. Could you please let us know can we close this issue if your issue gets resolved? 
Thanks!

**Comment by v-sudkharat** [comment]
Hi @keyoke, Gentle Reminder: We are waiting for your response on this issue. If you still need to keep this issue active, please respond to it in the next 2 days. If we don't receive a response by 24-05-2024 date, we will be closing this issue. 		
Thanks!

**Comment by v-sudkharat** [comment]
Hi @keyoke, since we have not received a response in the last 5 days, we are closing your issue as per our standard operating procedures. If you still need support for this issue, feel free to re-open at any time. Thank you for your co-operation.
