### ISSUE TITLE
change analytics rule data source from WAF to key vault 

### ISSUE THREAD

**Issue by Yaniv-Shasha** [Azure/Azure-Sentinel#1043]
The data source of the 3 analytics templates

1. Azure Key Vault access TimeSeries anomaly
2. Mass secret retrieval from Azure Key Vault
3. Sensitive Azure Key Vault operations

is define as WAF but its need to be azure key vault

**Comment by ashwin-patil** [comment]
Bug fix added to #1045  and merged
