### ISSUE TITLE
Missing incident description on Microsoft Defender XDR incidents created by Microsoft Sentinel

### ISSUE THREAD

**Issue by ep3p** [Azure/Azure-Sentinel#10446]
**Is your feature request related to a problem? Please describe.**
Microsoft Defender XDR incidents have NEVER had a description field available in Microsoft Sentinel portal.

When "Incident provider name" is "Azure Sentinel" the incidents HAVE a description.

When "Incident provider name" is "Microsoft Defender XDR" the incidents do NOT have a description (in Microsoft Sentinel portal in Azure).

IF you integrate a Sentinel workspace to Microsoft Defender XDR , ALL the incidents will have now "Microsoft Defender XDR" as "Incident provider name", and ALL the incidents created by Microsoft Sentinel Analytics rules will LOSE their description (in Microsoft Sentinel portal in Azure).

There might be previous playbooks (logic apps) that USED the description field that now is empty, for incidents created by Microsoft Sentinel, and these playbooks now will continuously FAIL.

This is NOT expected, and is not mentioned in Microsoft Docs (https://learn.microsoft.com/en-us/azure/sentinel/microsoft-365-defender-sentinel-integration).

**Describe the solution you'd like**
Microsoft Defender XDR incidents SHOULD have a description in Microsoft Sentinel portal in Azure. They should not have missing attributes compared to incidents created directly by Microsoft Sentinel.

You should NOT LOSE capabilities when integrating Microsoft Sentinel with Microsoft Defender XDR.

![image](https://github.com/Azure/Azure-Sentinel/assets/2527990/d768b027-1b13-41ff-ab8a-169d3f70ee54)

![image](https://github.com/Azure/Azure-Sentinel/assets/2527990/33b5a8e1-10a5-4e1a-ad25-b6fb2aea1549)

**Comment by v-rusraut** [comment]
Hi @ep3p 
Thanks for flagging this issue, we will investigate this issue and get back to you with some updates by 15 May 2024. Thanks!

**Comment by v-rusraut** [comment]
Hi @ep3p,
We are waiting for response from respective team, we will update you.
Thanks

**Comment by v-rusraut** [comment]
Hi @ep3p, Hope you're doing good. As you have raised the support case for this same issue, our support team is working on your ticket. ICM is raised for this issue and so this is duplicate issue that's why closing this issue.
Thanks

**Comment by ep3p** [comment]
@v-rusraut what do you mean?? I have not raised any support case. I have only opened this issue on this GitHub repository.

**Comment by v-rusraut** [comment]
Hi @ep3p,
Actually, our support team shared this issue with us and forwarded this ticket with respective team to work on this, so as other respective was working on this issue so we have closed this issue. but as you mentioned you did not raise any support case let us check with support team and verify once.

**Comment by v-rusraut** [comment]
Hi @ep3p,
We have received the response from respective concern team, The description feature is currently in a private preview as (Enhanced Sync for XDR). so due to that currently it's not visible in incident tab. 

Thanks!

**Comment by ep3p** [comment]
Thank you very much @v-rusraut, understood.

**Comment by SandersAutomation** [comment]
We have this same issue.
We have just integrated XDR with Sentinel and now the Sentinel analytics rule fails to pass the Description through to the automation rule and associated playbook logic app, to send the description in the notification send-basic-email.

**Comment by nvisodriesbuyck** [comment]
Hi,
Is there an update on when a fix will be released globally?

**Comment by tduarte14** [comment]
We are still having this issue in September, 4 months after this issue was reported here. Are there any news??

**Comment by oed-albrinkd** [comment]
The issue is still not fixed - Any updates on that?

**Comment by asimcard** [comment]
was this fixed ever? still happening to me in 2025 @v-rusraut
