### ISSUE TITLE
VMware Carbon Black Cloud (using Function app) data connector not ingesting full three type of logs - Sentinel

### ISSUE THREAD

**Issue by laylavo** [Azure/Azure-Sentinel#10440]
**Describe the bug**

In VMware Carbon Black Cloud data connector, there are three types of logs: CarbonBlackEvents_CL, CarbonBlackAuditLogs_CL, CarbonBlackNotifications_CL

After deploy Azure Function app successfully, only one CarbonBlackAuditLogs_CL appears in LAW:

**To Reproduce**

- Deploy Azure Function App
- In Carbon Black Log Types, I have type: Audit, Events, Alert
- The deployment successful.
- Check the Function Apps details, there is no errors

Please advice!

**Comment by v-sudkharat** [comment]
Hi @laylavo, Thanks for flagging this issue, we will investigate this issue and get back to you with some updates by 15-05-2024. Thanks!

**Comment by laylavo** [comment]
hi @sudkharat, may i know is there any updates ?

**Comment by v-sudkharat** [comment]
Hey @laylavo, We need more time to check and investigate into this issue. Thanks!

**Comment by v-sudkharat** [comment]
Sure, we will share update you by- 23-05-2024. Thanks!

**Comment by v-sudkharat** [comment]
Hi @laylavo, The **CarbonBlackNotifications_CL** is got deprecated as per [Document](https://developer.carbonblack.com/reference/carbon-black-cloud/guides/api-migration/notification-migration/) and there is new Alert API to get Alert information. The API required the **CarbonBlackOrgKey** filed configured in the Environment Variable section of Function App. So kindly check on the below Highlighted parameter screenshot and fetch org_key details screenshot: -

![image](https://github.com/Azure/Azure-Sentinel/assets/132428394/9ed03d26-ae2a-49d5-8637-f7e364b4dd7e)

org_key in console side:- 

![image](https://github.com/Azure/Azure-Sentinel/assets/132428394/3ccfbee7-b6be-4e51-9cdf-a014d73f28c8)

**Comment by v-sudkharat** [comment]
Hey @laylavo, Are we good with above response? please let us know you having any questions or can we close this issue. Thanks!

**Comment by v-sudkharat** [comment]
Hey @laylavo, Could you please ping me on -v-sudkharat@microsoft.com Thanks!
