### ISSUE TITLE
Please help me this parser of Symantec logs

### ISSUE THREAD

**Issue by NellyThai** [Azure/Azure-Sentinel#10454]

**Comment by v-rusraut** [comment]
Hi @NellyThai,
Thanks for flagging this issue, we will investigate this issue and get back to you with some updates by 16 May 2024. Thanks!

**Comment by v-rusraut** [comment]
Hi @NellyThai,
Please help us to understand which Symantec solution you are using and also share error screen shots.
Thanks

**Comment by NellyThai** [comment]
Hi Team,


  *   The solution which is using is: Symantec ProxySG.
  *   Please refer the screenshot as follows:

[A screenshot of a computer  Description automatically generated]

Needless to say, the Computer and the hostname column are all incorrectly parsed, not to mention the actual SyslogMessage.

Thank you so much for your support!

Best Regards,
Nelly Thai
Support Engineer
Azure - Security
Working Hours: 3:00 PM - 12:00 AM (UTC+7, Monday to Friday)
Need help outside of my working hours?
Locate an engineer: ***@***.******@***.***>
Manager: Olivia Li/ ***@***.******@***.***>
***@***.***

**Comment by NellyThai** [comment]
Hi Rusraut,


  *   The solution which is using is: Symantec ProxySG.
  *   Please refer the screenshot as follows:

[A screenshot of a computer  Description automatically generated]

Needless to say, the Computer and the hostname column are all incorrectly parsed, not to mention the actual SyslogMessage.

Thank you so much for your support!

Best Regards,
Nelly Thai
Support Engineer
Azure - Security
Working Hours: 3:00 PM - 12:00 AM (UTC+7, Monday to Friday)
Need help outside of my working hours?
Locate an engineer: ***@***.******@***.***>
Manager: Olivia Li/ ***@***.******@***.***>
***@***.***

**Comment by v-rusraut** [comment]
Hi @NellyThai,
Error screenshot not visible, please provide error screenshot to below email id:
v-rusraut@microsoft.com
Thanks

**Comment by v-rusraut** [comment]
Requested to follow the process.
