### ISSUE TITLE
Sentinel logic-app adding comments containing a HTML table has excessive newlines

### ISSUE THREAD

**Issue by twi252** [Azure/Azure-Sentinel#10459]
**Describe the bug**

In a Logic App, using the Sentinel logic-app connector (Add comment to incident (V3)) in a For Each loop and entering a simple HTML table as the comment causes the table to be prefixed by many `<br>` tags upon presentation inside the browser leading to an unprofessional looking comment.

**To Reproduce**

1. Make a simple logic app that iterates over some sample data in an array via For Each
2. Use the "Add comment to incident (V3)" connector function to post a comment to a sample incident inside the For Each
3. In the comment, add a title describing the table, ie, "This is my test data"
4. Press enter 3 times
6. Make a simple HTML table with 10 or so rows in the table from sample data
7. Execute the logic-app and look at the comments in the Sentinel incident

**Expected behavior**

A comment with a title, a newline, then the table presented graphically (without excessive newlines between title and table)

**Desktop (please complete the following information):**

 - OS: Windows 10
 - Browser Chrome
 - Version Latest

**Additional context**

Using Chromes "inspect" feature to inspect the HTML in the relevant comment, expanding the relevant `<div>`, Sentinel seems to be adding many `<br>` tags (sometimes > 20) leading to a huge amount of space from the title in the comment (line 1) after all the `<br>`'s the table is way down below.

It seems to work normally with other HTML tags, but seems to have a problem with `<table>`'s specifically. I've been trying to remove the excess `<br>` tags but haven't had much luck, so am filing this bug report.

**Comment by v-rusraut** [comment]
Hi @twi252 , Thanks for flagging this issue, we will investigate this issue and get back to you with some updates by 17-05-2024. Thanks!

**Comment by twi252** [comment]
Thanks. Just to add, i tried putting the table into a string-variable and passed the output to "Add comment to incident (V3)" and it does exactly the same thing (i noticed it passes HTML colors across from the `<table>` tag, but it strips it out when the html is put into Add comment to incident (V3) directly.

I've tried trim(variable('mystring')) to ensure there's no leading or trailing whitespace, and see the same.

**Comment by v-rusraut** [comment]
Hi @twi252,
We need more time to check and investigate into this issue. Thanks!

**Comment by twi252** [comment]
Hi, @v-rusraut, no problem, appreciate the help.

**Comment by v-rusraut** [comment]
Hi @twi252,
We have replicated the issue, now we are working with respective team to fix it, we will update you.
Thanks
