### ISSUE TITLE
Improve the Microsoft Entra ID solution workbooks

### ISSUE THREAD

**Issue by MikeP1375** [Azure/Azure-Sentinel#10461]
**Is your feature request related to a problem? Please describe.**
The Entra ID solution workbook has some basic views for looking at the data but more useful workbooks are available in Azure Monitor.

**Describe the solution you'd like**
Request someone review the solution and the following workbook links to see if they can be added to the workbook.

https://learn.microsoft.com/en-us/entra/identity/monitoring-health/workbook-authentication-prompts-analysis
https://learn.microsoft.com/en-us/entra/identity/monitoring-health/workbook-conditional-access-gap-analyzer
https://learn.microsoft.com/en-us/entra/identity/monitoring-health/workbook-cross-tenant-access-activity
https://learn.microsoft.com/en-us/entra/identity/monitoring-health/workbook-mfa-gaps
https://learn.microsoft.com/en-us/entra/identity/monitoring-health/workbook-risk-analysis
https://learn.microsoft.com/en-us/entra/identity/monitoring-health/workbook-sensitive-operations-report
https://learn.microsoft.com/en-us/entra/identity/monitoring-health/workbook-legacy-authentication

Regards

Mike

**Comment by v-sudkharat** [comment]
Hi @MikeP1375, Thanks for highlighting the new features which can be add into the existing Entra ID workbooks, we will check on the doc which you have shared and will also take it up or shared with respective team to add those features in existing ones. 
As this is an enhancement, Closing this issue from GitHub. If you still need support for this issue, feel free to re-open it any time. Thank you for your co-operation.
