### ISSUE TITLE
 Symantec VIP parser not working

### ISSUE THREAD

**Issue by laylavo** [Azure/Azure-Sentinel#10493]
**Describe the bug**

 Symantec VIP parser function not shown any result in Log Analytics Workspace.

**To Reproduce**

1. We have checked the Symantec VIP data connector and syslog Symantec received as normal
2. Query log in LAW, log shown
3. This is the raw log in LAW:
5. Parser function code - Symantec VIP in Sentinel

**Comment by v-sudkharat** [comment]
Hi @laylavo, Thanks for flagging this issue, we will investigate this issue and get back to you with some updates by 28-05-2024. Thanks!

**Comment by v-sudkharat** [comment]
Hi @laylavo, Could you please share the error you're getting while run the parser? and also share in which line the parser getting error message. 
Thanks!

**Comment by laylavo** [comment]
There is no error when we run the VIP parser function. 
When we add the template in Log Analytics Workspace, there is no result found

**Comment by laylavo** [comment]
Hi @Sudarshan Kharat (Tata Consultancy Services ***@***.***>,

There is no error of VIP parser function. When we run the parser, there is no result found.

Best regards,
Layla Vo
Support Engineer
Azure - Security
Working Hours: 7:00 AM - 4:00 PM (UTC+7, Monday to Friday)
Need help outside of my working hours?
Locate an engineer: ***@***.******@***.***>
Manager: Olivia Li/ ***@***.******@***.***>
***@***.***
