### ISSUE TITLE
Create LogAnalytics table for Analytic Rules

### ISSUE THREAD

**Issue by robertkitching** [Azure/Azure-Sentinel#1049]
I would like to report on Analytic Rule changes, creations etc within a set time period.

Currently the only way of getting rule information is via an API call. This is useful but would still require us to create our own snapshot table to be able to report effectively. 

The API response data also doesn't include a 'CreatedDate' for rules just a LastModifiedDate.

If it could work in a similar way to the new 'SecurityIncidents' table  (multi-leg to highlight changes) it would suffice.

**Comment by Ronmarsiano** [comment]
hi @robertkitching, 

first I would like to thank you for the response,
As a first mitigation you are able to pull that information and ingest it into custom logs for monitoring,
or using version control to update your rules (that way you could track all changes ).
We will take your idea into consideration !

thanks,

Ron

**Comment by v-amolpatil** [comment]
Hi @robertkitching, thank you for flagging this. Apologies for the delayed response. If you still need assistance, please reply here within 5 business days.

**Comment by v-amolpatil** [comment]
Hi @robertkitching, Gentle Reminder: We are awaiting for your response on this issue. If you still need to keep this issue active please respond with in next 2 days. If we don't receive response by 9 Feb 2023, we will close this issue.

**Comment by v-amolpatil** [comment]
Since we have not received a response in the last 5 days, we are closing your issue #1049 as per our standard operating procedures. If you still need support for this issue, feel free to re-open at any time. Thank you for your co-operation.
