### ISSUE TITLE
Authentication Methods Changed for Privileged Account - invalid entity mappings

### ISSUE THREAD

**Issue by Kaloszer** [Azure/Azure-Sentinel#10516]
**Describe the bug**
EntityMappings are bound to items that dont exist, even when the query is modified to include them at all times (on query exec) it errors on deployment

**To Reproduce**
1. Try to deploy [`Authentication Methods Changed for Privileged Account`](https://analyticsrules.exchange/analyticrules/694c91ee-d606-4ba9-928e-405a2dd0ff0f/)

[https://github.com/Azure/Azure-Sentinel/blob/master/Solutions/Microsoft Entra ID/Analytic Rules/AuthenticationMethodsChangedforPrivilegedAccount.yaml](https://github.com/Azure/Azure-Sentinel/blob/master/Solutions/Microsoft%20Entra%20ID/Analytic%20Rules/AuthenticationMethodsChangedforPrivilegedAccount.yaml)

2. Get error:
![image](https://github.com/Azure/Azure-Sentinel/assets/62133917/90c51679-5d1a-4aea-b0e2-b2b4ea410ce0)

4. Try to modify the query to set columns as `N/A` when it doesn't have a result

``` kql

let queryperiod = 14d;
let queryfrequency = 2h;
let security_info_actions = dynamic(["User registered security info", "User changed default security info", "User deleted security info", "Admin updated security info", "User reviewed security info", "Admin deleted security info", "Admin registered security info"]);
let VIPUsers = (
    IdentityInfo
    | where TimeGenerated > ago(queryperiod)
    | mv-expand AssignedRoles
    | where AssignedRoles contains 'Admin'
    | summarize by AccountUPN);
AuditLogs
| where TimeGenerated > ago(queryfrequency)
| where Category =~ "UserManagement"
| where ActivityDisplayName in (security_info_actions)
| extend InitiatingAppName = iff(isnotempty(InitiatedBy.app.displayName), tostring(InitiatedBy.app.displayName), "N/A")
| extend InitiatingAppServicePrincipalId = iff(isnotempty(InitiatedBy.app.servicePrincipalId), tostring(InitiatedBy.app.servicePrincipalId), "N/A")
| extend InitiatingUserPrincipalName = iff(isnotempty(InitiatedBy.user.userPrincipalName), tostring(InitiatedBy.user.userPrincipalName), "N/A")
| extend InitiatingAadUserId = iff(isnotempty(InitiatedBy.user.id), tostring(InitiatedBy.user.id), "N/A")
| extend InitiatingIpAddress = iff(isnotempty(InitiatedBy.user.ipAddress) or isnotempty(InitiatedBy.app.ipAddress), tostring(iff(isnotempty(InitiatedBy.user.ipAddress), InitiatedBy.user.ipAddress, InitiatedBy.app.ipAddress)), "N/A")
| mv-apply TargetResource = TargetResources on 
  (
      where TargetResource.type =~ "User"
      | extend TargetUserPrincipalName = iff(isnotempty(TargetResource.userPrincipalName), tostring(TargetResource.userPrincipalName), "N/A")
  )
| where TargetUserPrincipalName in~ (VIPUsers)
| summarize Start=min(TimeGenerated), End=max(TimeGenerated), Actions = make_set(ResultReason, MaxSize=8) by InitiatingAppName, InitiatingAppServicePrincipalId, 
InitiatingUserPrincipalName, InitiatingAadUserId, InitiatingIpAddress, TargetUserPrincipalName, Result
| extend InitiatingAccountName = iff(isnotempty(split(InitiatingUserPrincipalName, "@")[0]), tostring(split(InitiatingUserPrincipalName, "@")[0]), "N/A"), 
InitiatingAccountUPNSuffix = iff(isnotempty(split(InitiatingUserPrincipalName, "@")[1]), tostring(split(InitiatingUserPrincipalName, "@")[1]), "N/A"), 
TargetName = iff(isnotempty(split(TargetUserPrincipalName,'@',0)[0]) and tostring(TargetUserPrincipalName) !has "[", tostring(split(TargetUserPrincipalName,'@',0)[0]), "N/A"), 
TargetUPNSuffix = iff(isnotempty(split(TargetUserPrincipalName,'@',1)[0]) and tostring(TargetUserPrincipalName) !has "[", tostring(split(TargetUserPrincipalName,'@',1)[0]), "N/A")

```

5. Get the same error

**Expected behavior**
Analytic rule is deployed and does not error with entity mappings error

**Additional context**

Not able to deploy in multiple workspaces

**Comment by v-sudkharat** [comment]
Hi @Kaloszer, Thanks for flagging this issue, we will investigate this issue and get back to you with some updates by 31-05-2024. Thanks!

**Comment by v-sudkharat** [comment]
Hey @Kaloszer, The PR has been Merged with the corrections, and now the deployment gets successful. Please redeploy the rule and let us know if your issue gets resolved. Thanks!

**Comment by Kaloszer** [comment]
> Hey @Kaloszer, The PR has been Merged with the corrections, and now the deployment gets successful. Please redeploy the rule and let us know if your issue gets resolved. Thanks! 
> 

Jeez im blind it was case sensitivity after all...
