### ISSUE TITLE
Sophos Endpoint Protection (using REST API) (Preview) - Fails due to table name Custom-SophosEPEvents_CL containing hyphen.

### ISSUE THREAD

**Issue by synapse303** [Azure/Azure-Sentinel#10510]
The deployment tries to create a table called **Custom-SophosEPEvents_CL** which fails due to the inclusion of a hyphen.

```
Connector resource creation failed
Failed to create required resources for data connector InvalidPayload:Data collection rule is invalid, [{"code":"InvalidOutputTable","message":"Table for output stream 'Custom-SophosEPAlerts_CL' is not available for destination 'clv2ws1'.","target":"properties.dataFlows[0]"},{"code":"InvalidOutputTable","message":"Table for output stream 'Custom-SophosEPEvents_CL' is not available for destination 'clv2ws1'.","target":"properties.dataFlows[1]"}]
```

The naming is referenced in the below files and will likely need renaming to **CustomSophosEPEvents_CL**

```
./Data Connectors/SophosEP_ccp/SophosEP_PollingConfig.json:67:                "streamName": "Custom-SophosEPEvents_CL"
./Data Connectors/SophosEP_ccp/SophosEP_DCR.json:70:                "Custom-SophosEPEvents_CL": {
./Data Connectors/SophosEP_ccp/SophosEP_DCR.json:188:                        "Custom-SophosEPEvents_CL"
./Data Connectors/SophosEP_ccp/SophosEP_DCR.json:194:                    "outputStream": "Custom-SophosEPEvents_CL"
./Package/mainTemplate.json:850:                  "Custom-SophosEPEvents_CL": {
./Package/mainTemplate.json:968:                      "Custom-SophosEPEvents_CL"
./Package/mainTemplate.json:974:                    "outputStream": "Custom-SophosEPEvents_CL"
```

Thanks

**Comment by v-sudkharat** [comment]
Hi @synapse303, Thanks for flagging this issue, we will investigate this issue and get back to you with some updates by 30-05-2024. Thanks!

**Comment by v-sudkharat** [comment]
Hey @synapse303, Could you please let us know where exactly this error occurred and if possible, please share the screenshots with us. Thanks!

**Comment by synapse303** [comment]
Hi,

When trying to Add the connector in Content Hub/ Sophos Endpoint Protection/Data Connectors/ Sophos Endpoint Protection (using REST API) (Preview)

<img width="1131" alt="image" src="https://github.com/Azure/Azure-Sentinel/assets/8871752/da506836-8f95-41a5-817b-1d5374b7ae78">

Error:

<img width="427" alt="image" src="https://github.com/Azure/Azure-Sentinel/assets/8871752/b78cfd54-8008-4fe6-a0e1-fc505bd8e4fb">

**Comment by v-sudkharat** [comment]
Hey @synapse303, The error you're getting is only after installing the solution and data connector OR after trying to connect the connector **Sophos Endpoint Protection (using REST API) (Preview)** by entering its credentials? 
And if the error before configuring the connector, then could you please check the same into another different Workspace and let us know the same error you're having. 
If issue still persist, please share your mail ID with us to connect for a call to check on this issue. Thanks!

**Comment by v-sudkharat** [comment]
@synapse303 Thanks for sharing screenshots. will check and get back to you with update.

**Comment by ezrawcdm** [comment]
I can confirm. We are having the same issue in the same place.
![Screenshot 2024-06-05 at 1 10 35 PM](https://github.com/Azure/Azure-Sentinel/assets/149620130/a0c509fd-8054-47c2-bd27-5672469dbe79)

**Comment by ViniMelo** [comment]
We're also having this issue, do we have an update?

**Comment by v-sudkharat** [comment]
Hi @ViniMelo, Our team is still working on investigating on this issue, currently team is facing some challenges on updating the solution. Once changes are done, we will raise the PR with changes and update you. Thanks!

**Comment by TNT-pratik** [comment]
We have the same issue. Any update on this?

**Comment by v-sudkharat** [comment]
Hi @synapse303, 
We have updated the template and will raise PR with the changes. Meantime, could you please custom deploy the Solution **MainTemplate** and check whether your issue get resolved. 

Sharing the **MainTemplate** and Custom deployment steps- 

Custom Deployment -  [Custom Deployment of the Solution - Copy.docx](https://github.com/Azure/Azure-Sentinel/files/14342731/Custom.Deployment.of.the.Solution.-.Copy.docx)

Main template: - [mainTemplate_sophos_new 3 (1).json](https://github.com/user-attachments/files/15967109/mainTemplate_sophos_new.3.1.json)


Thanks!

**Comment by synapse303** [comment]
I deployed via custom solution and it has worked.

thankyou

**Comment by v-sudkharat** [comment]
@synapse303, thank you for response, will update this solution and fix will get available in upcoming solution version. So, closing this issue from GitHub. If you still need support for this issue, feel free to re-open it any time. Thank you for your co-operation.

**Comment by CarlaVallejo** [comment]
@v-sudkharat  perhaps a solution to this error has been found.

**Comment by Sanlues** [comment]
> I deployed via custom solution and it has worked.
> 
> thankyou

Can you let me know the step? I have followed the steps from custom deployment and it has successfully deployed. What are the steps after those, and how do I get the logs? Is there any video that I can follow? 


PS : New to Azure sentinel need help
