### ISSUE TITLE
Microsoft Exchange Logs and Events - [Option 6] Message Tracking of Exchange Servers step is broken

### ISSUE THREAD

**Issue by samet-ibis** [Azure/Azure-Sentinel#10529]
**Describe the bug**
In step 6 of the Microsoft Exchange Logs and Events connector, [Option 6] Message Tracking of Exchange Servers, when selecting the "Data Collection Rules - When Azure Monitor Agent is used" option and proceeding with "Option 2 - Manual Deployment of Azure Automation," a semantic error occurs when trying to add the transform KQL in the "C. Modify the created DCR, Type Custom log" step. For the same reason, the ARM Template option also cannot be deployed.

**To Reproduce**
1. Go to 'Microsoft Exchange Logs and Events connector -> [Option 6] Message Tracking of Exchange Servers -> Option 2 - Manual Deployment of Azure Automation -> Complete step A and B -> Try to C. Modify the created DCR, Type Custom log'
2. Try to 'The 4. step of C.Modify the Created DCR says go to created DCR and In Data Sources, add a Data Source type 'Custom Text logs' and enter 'C:\Program Files\Microsoft\Exchange Server\V15\TransportRoles\Logs\MessageTracking*.log' in file pattern, 'MessageTrackingLog_CL' in Table Name. 6.in Transform field, enter the following KQL request : (enter the given kql in connector) then try to save DCR'
3. And you will see the error after trying to save DCR.

**Expected behavior**
The provided kql must be change. And saving DCR step should be successful.

**Screenshots**
![image](https://github.com/Azure/Azure-Sentinel/assets/100233276/f0c9964d-235a-4d9b-ab73-f0dce391748b)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by v-sudkharat** [comment]
Hi @samet-ibis, Thanks for flagging this issue, we will investigate this issue and get back to you with some updates by 05-06-2024. Thanks!

**Comment by v-rusraut** [comment]
Hi @samet-ibis,
Working on replicating the issue, will update you.
Thanks

**Comment by v-rusraut** [comment]
Hi @samet-ibis,
Please share the kql query which you entered in transform field.
<img width="514" alt="image" src="https://github.com/Azure/Azure-Sentinel/assets/126679503/057874c3-41fe-45dc-95e5-a9b578eefe23">
Thanks

**Comment by v-rusraut** [comment]
Hi @samet-ibis,
Please work on above comment.
Thanks

**Comment by v-rusraut** [comment]
Hi @samet-ibis , Gentle Reminder: We are waiting for your response on this issue. If you still need to keep this issue active, please respond to it in the next 2 days. If we don't receive a response by 24-06-2024 date, we will be closing this issue. 		
Thanks!

**Comment by v-rusraut** [comment]
Hi @samet-ibis, since we have not received a response from you, we are closing this issue as per our standard operating procedures. If you still need support for this issue, feel free to re-open at any time. Thank you for your co-operation.
