### ISSUE TITLE
Azure Firewall ASIM Network Parser | ICMP code and Type parsing

### ISSUE THREAD

**Issue by cgiamp** [Azure/Azure-Sentinel#10532]
Hello,

It appears that there is a small bug on the following line which extracts the ICMP code:
https://github.com/Azure/Azure-Sentinel/blob/a0a2d1d4b3fe5caf51a73963497950af9d18a9c1/Parsers/ASimNetworkSession/Parsers/ASimNetworkSessionAzureFirewall.yaml#L43C11-L43C137
Based on what I see on azure firewall logging and the sample logs here:
https://github.com/Azure/Azure-Sentinel/blob/master/Parsers/AzureFirewall/AzureFirewallNetworkRuleLogs_sample-dataset.kql#L7
the Type keyword has a capital 'T' which causes the regular expression to fail.

I propose changing the regular expression to (not case-sensitive for failsafe):
```
| extend NetworkIcmpCode = iff(NetworkProtocol startswith "ICMP", toint(extract ("(?i)type=(\\d+)", 1, NetworkProtocol)), int(null))
``` 

Also, based on the [documentation](https://learn.microsoft.com/en-us/azure/sentinel/normalization-schema-network#:~:text=to%20NetworkDuration.-,NetworkIcmpType,-Optional) the fields NetworkIcmpType, NetworkIcmpCode should be the corresponding number of the ICMP type and code. On this parser, the NetworkIcmpCode has the value of the ICMP type and the  NetworkIcmpType contains the description of the numeric value of the ICMP Type which is a bit misleading. 
![image](https://github.com/Azure/Azure-Sentinel/assets/22245093/4dba8ac8-87dd-477c-a31c-a909121e96e4)
I think its more appropriate to store the numeric value of the ICMP type on the NetworkIcmpType field.

**Comment by cgiamp** [comment]
Hi,

any update on this one?

**Comment by vakohl** [comment]
Query1:
@cgiamp thanks for reporting this. PR has been created to make the suggested changes. https://github.com/Azure/Azure-Sentinel/pull/10834
 Query2:
NetworkIcmpType should contain the description of the ICMPCode. I think we need make the documentation more clear. Please see description of the ASIM function that extend the NetworkIcmpType field.

"This ASIM function returns ICMP Type name associated with the numerical value provided as a parameter. For example, for 8, the function returns "Echo" (which is the type used by the ping command). "
https://github.com/Azure/Azure-Sentinel/blob/master/ASIM/lib/functions/ASIM_LookupICMPType.yaml

**Comment by vakohl** [comment]
Raised PR for updating documentation as well: https://github.com/MicrosoftDocs/azure-docs/pull/123789
