### ISSUE TITLE
Fortigate AMA issue

### ISSUE THREAD

**Issue by ArmsSec** [Azure/Azure-Sentinel#10544]
If the Fortigate logs in CEF format are coming from the FortiAnalyzer are not parsed correctly by the new connector. Are still matching the old connector.
the issue is with the parsing:
where DeviceProduct =~ 'Fortigate'

This should be changed to something like 
where DeviceProduct has 'Fortigate'
 or
where DeviceProduct startswith 'Fortigate'

 FortiAnalyzer is including the the Fortigate model as a DeviceProduct, like FortiGate-101E

**Comment by v-rusraut** [comment]
Hi @ArmsSec, Thanks for flagging this issue, we will investigate this issue and get back to you with some updates by 07-06-2024. Thanks!

**Comment by v-rusraut** [comment]
Hi @ArmsSec,
We are working with respective team to fix it, we will update you.
Thanks

**Comment by v-rusraut** [comment]
Hi @ArmsSec, We have received a response from our concerned team; they are investigating the issue and require resource access to check into it. Could you please raise a support ticket with our Azure support team, so they can look into it and connect with you if necessary. Please let us know once you have raised the support ticket, so we can update our concerned team. Thank you!

**Comment by v-rusraut** [comment]
Hi @ArmsSec , Gentle Reminder: We are waiting for your response on this issue. If you still need to keep this issue active, please respond to it in the next 2 days. If we don't receive a response by 02-07-2024 date, we will be closing this issue. 		
Thanks!

**Comment by v-sudkharat** [comment]
Hi @ArmsSec, since we have not received a response in the last 5 days, we are closing your issue as per our standard operating procedures. If you still need support for this issue, feel free to re-open at any time. Thank you for your co-operation.
