### ISSUE TITLE
Wrong analytic rule name

### ISSUE THREAD

**Issue by AndreasSkarpelos** [Azure/Azure-Sentinel#10545]
The following analytic rule's name should be "TI Map URL Entity to DeviceNetworkEvents" instead of "TI Map URL Entity to AuditLogs".

https://github.com/Azure/Azure-Sentinel/blob/master/Solutions/Threat%20Intelligence/Analytic%20Rules/URLEntity_DeviceNetworkEvents.yaml

**Comment by v-sudkharat** [comment]
Hi @AndreasSkarpelos, Thanks for flagging this issue, we will investigate this issue and get back to you with some updates by 07-06-2024. Thanks!

**Comment by v-sudkharat** [comment]
Hey @AndreasSkarpelos, PR has been raised and merged with the corrections, the changes will get reflected in upcoming solution version. Thanks!
