### ISSUE TITLE
IdentityInfo table column LastSeenDate is always empty

### ISSUE THREAD

**Issue by Palciny** [Azure/Azure-Sentinel#10558]
**Describe the bug**
This table is populated by Azure Sentinel UEBA with all your users identities information. It can be used to correlate user information and insights with analytics or hunting queries.

LastSeenDate is always empty for this table.

**To Reproduce**
1. Go to 'Sentinel'
2. Click on 'Logs'
3. Run query:

IdentityInfo
| summarize dcount(LastSeenDate), dcount(AccountUPN) by TenantId

4. See that dcount_LastSeenDate = 0

**Expected behavior**
Expecting the same DateTime as then I would query via Microsoft Graph API on the signInActivity  looking for lastSignInDateTime property

https://learn.microsoft.com/en-us/entra/identity/monitoring-health/howto-manage-inactive-user-accounts

**Screenshots**
![image](https://github.com/Azure/Azure-Sentinel/assets/15854440/8f5a4a09-090a-4020-a902-76d7c56a0c03)

**Desktop (please complete the following information):**
 - not applicable

**Smartphone (please complete the following information):**
 - not applicable

**Additional context**
 - not applicable

**Comment by Palciny** [comment]
@shainw, @razmarom can you please check?

**Comment by v-sudkharat** [comment]
Hey @Palciny, we want to know have you raised any support case for this issue? If raised, please let us know, so we can check it with our support team. Thanks!

**Comment by Palciny** [comment]
Hi @v-sudkharat  no I didn't raise the ticket. Should I?

**Comment by v-sudkharat** [comment]
Hi @Palciny, it would you be great if you raise support ticket. So, our team get connect with you for required details and this ticket also get transferred to respective concern team. Please let us know once you open it, so we can close this issue from here. Thanks!

**Comment by Palciny** [comment]
@v-sudkharat 
Support request ID : 406110050003419

**Comment by v-sudkharat** [comment]
Thanks @Palciny. Closing this issue from GitHub. If you still need support for this issue, feel free to re-open it any time. Thank you for your co-operation.
