### ISSUE TITLE
Azure SQL Database solution may be obsolete

### ISSUE THREAD

**Issue by sshockley** [Azure/Azure-Sentinel#10575]
**Describe the bug**
Under the Solutions directory, there's both "Azure SQL Database" and "Azure SQL Database solution for sentinel".  The "Azure SQL Database" one seems to be unmaintained, and Data/Solution_AzureSqlDatabaseTemplateSpec.json refers to files in the Data Connectors directory, which doesn't exist.

**To Reproduce**
See above

**Expected behavior**
Only have one Azure SQL Database solution, unless I'm mistaken and they have different purposes.

**Additional context**
https://github.com/Azure/Azure-Sentinel/tree/master/Solutions/Azure%20SQL%20Database
https://github.com/Azure/Azure-Sentinel/tree/master/Solutions/Azure%20SQL%20Database%20solution%20for%20sentinel

**Comment by v-rusraut** [comment]
Hi @sshockley,Thanks for flagging this issue, we will investigate this issue and get back to you with some updates by 15-06-2024 Thanks!

**Comment by v-rusraut** [comment]
Hi @sshockley,
We have removed the Azure SQL Database solution from Solutions directory, so currently closing this issue. If you still need support for this issue, feel free to re-open at any time. Thank you for your co-operation.
