### ISSUE TITLE
Creating a bug report sends an error via email

### ISSUE THREAD

**Issue by sshockley** [Azure/Azure-Sentinel#10577]
**Describe the bug**
When I create a bug report in this repo, some workflow fails and sends me an email with the details.

**To Reproduce**
Create and save a bug report against Azure/Azure-Sentinel

**Expected behavior**
A message explaining the 5 business day response policy

**Additional context**
The text of the message is:
```
[Azure/Azure-Sentinel] IssueComment workflow run

Repository: Azure/Azure-Sentinel
Workflow: IssueComment
Duration: 11.0 seconds
Finished: 2024-06-03 20:32:27 UTC

View results: https://github.com/Azure/Azure-Sentinel/actions/runs/9356867270

Jobs:
  * commenting failed (1 annotation)

-- 
You are receiving this because you are subscribed to this thread.
Manage your GitHub Actions notifications: https://github.com/settings/notifications
```
The linked action shows the error:
```Error: Unhandled error: HttpError: Resource not accessible by integration```

**Comment by v-rusraut** [comment]
Hi @sshockley ,Thanks for flagging this issue, we will investigate this issue and get back to you with some updates by 15-06-2024 Thanks!

**Comment by v-rusraut** [comment]
Hi @sshockley, We have notified this issue to the respective team and they will work on it, so currently closing this issue. If you still need support for this issue, feel free to re-open at any time. Thank you for your co-operation.
