### ISSUE TITLE
Cannot deploy Windows Fierwall solution on Azure Government

### ISSUE THREAD

**Issue by sshockley** [Azure/Azure-Sentinel#10576]
**Describe the bug**
When trying to deploy the Windows Firewall solution to Sentinel in Azure Government (usgovvirginia) the deployment fails with the error:
"The connecotr 'WindowsFirewallAma' is not supported in this environment"

This happens both when deploying 3.0.1 via the UI or with 3.0.5 using ```az deployment group create```.

**To Reproduce**
Open portal.azure.us
Open Content Hub
Select Windows Firewall, and click Install

Exact error message is:
```json
{
    "status": "Failed",
    "error": {
        "code": "BadRequest",
        "message": "The connecotr 'WindowsFirewallAma' is not supported in this environment"
    }
}
```

**Expected behavior**
Successful deployment without errors
Minor, but correcting the typo of 'connector' would be nice.

The deployment fails completely when using ```az deployment group create```, but when deploying through the portal the solution is partially created with the AMA connector missing.  I believe the first behavior is more correct, if the deployment doesn't completely succeed it should roll back.

**Comment by v-sudkharat** [comment]
Hi @sshockley, Thanks for flagging this issue, we will investigate this issue and get back to you with some updates by 15-06-2024 Thanks!

**Comment by v-sudkharat** [comment]
Hey @sshockley, We have received a response from our concerned team regarding this issue. The Windows Firewall AMA is not supported in government, and the typo fix is underway. So, closing this issue from GitHub. If you still need support for this issue, feel free to re-open it any time. Thank you for your co-operation.
