### ISSUE TITLE
Checking Data Connector manually by installing generated ARM template

### ISSUE THREAD

**Issue by vkorenkov-varonis** [Azure/Azure-Sentinel#10587]
**Describe the bug**
I've created a new Data Connector Solution (Varonis SaaS). And I would like to check how it will look like on the customer side. I took a generated ARM [template for my solution](https://github.com/Azure/Azure-Sentinel/blob/master/Solutions/VaronisSaaS/Package/mainTemplate.json) and see two issues.
- Data Connector page shows that there is not any workbook associated with my connector, but I can find it in workbooks section in Workbook templates 
- Data Connector page shows that there are two Sample Queries associated with the Data Connector, but I can't find them anywhere

Not sure that it's a bug, and will it change after solution will be in Content Hub.

**To Reproduce**
1. Install Data Connector Solution using [mainTemplate.json](https://github.com/Azure/Azure-Sentinel/blob/master/Solutions/VaronisSaaS/Package/mainTemplate.json)
2. Open Data Connector page
3. Check Workbooks amount and Queries amount
4. Open Workbooks section 
5. Open Templates Tab
6. Check that workbook exists
7. Open Log section
8. Open queries and search for "List all Varonis Alerts"
9. There is no query with this name

**Expected behavior**
- Number of workbooks associated with Data Connector should be 1
- Sample Queries associated with Data Connector should be in Log Analytics Queries 

**Screenshots**

![Data Connector](https://github.com/Azure/Azure-Sentinel/assets/99330808/9a584aa5-7c42-44b1-9979-d2a263673702)
![Varonis SaaS Workbook](https://github.com/Azure/Azure-Sentinel/assets/99330808/08e41d4c-aace-455a-9005-6ad6bc30b806)
![Sample Queries](https://github.com/Azure/Azure-Sentinel/assets/99330808/bf61be83-b753-4fb7-b0d0-83adca33a6e5)

**Comment by v-rusraut** [comment]
Hi @vkorenkov-varonis,Thanks for flagging this issue, we will investigate this issue and get back to you with some updates by 15-06-2024 Thanks!

**Comment by v-rusraut** [comment]
Hi @vkorenkov-varonis,
Please refer below points.

- Workbook count not visible on dataconnector page because workbook metadata do not present in WorkbooksMetadata.json file, need to add workbook metadata in it, please raise the PR for same. Once PR merged into master and solution published after that workbook count will be visible.
File Path : https://github.com/Azure/Azure-Sentinel/blob/master/Tools/Create-Azure-Sentinel-Solution/V2/WorkbookMetadata/WorkbooksMetadata.json

- Due to the current design, count of sample queries is showing on data connector page, but these queries not visible anywhere. We have notified this issue to the respective team, and they will work on it.

**Comment by vkorenkov-varonis** [comment]
> * Workbook count not visible on dataconnector page because workbook metadata do not present in WorkbooksMetadata.json file, need to add workbook metadata in it, please raise the PR for same. Once PR merged into master and solution published after that workbook count will be visible.

it's presented.
![image](https://github.com/Azure/Azure-Sentinel/assets/99330808/e642568b-0c43-49d5-aa29-28ae3dbe5fa7)
I've seen that workbook (VaronisSaaS.json) is not presented in global Workbooks folder, where WorkbooksMetadata.json  located. So, I copied it from Solution, then regenerate mainTemplate.json. It hasn't been changed.

**Comment by vkorenkov-varonis** [comment]
> Once PR merged into master and solution published after that workbook count will be visible.
As I understand it will be visible only publishing Solution, am I right?

**Comment by v-rusraut** [comment]
Hi @vkorenkov-varonis,
It is not required to add this workbook into path, remove it from file: https://github.com/Azure/Azure-Sentinel/tree/master/Workbooks
Only add meta data into file: https://github.com/Azure/Azure-Sentinel/blob/master/Tools/Create-Azure-Sentinel-Solution/V2/WorkbookMetadata/WorkbooksMetadata.json
Thanks

**Comment by vkorenkov-varonis** [comment]
Hi @v-rusraut,
I use V3 tool for creating solution and there is no WorkbooksMetadata.json in the tool folder. I'll try version V2, but just for you to know about V3

**Comment by v-rusraut** [comment]
Hi @vkorenkov-varonis,
Please package the solution using V3 tool, no need to add workbook metadata in WorkbooksMetadata.json file.
Thanks

**Comment by vkorenkov-varonis** [comment]
@v-rusraut 
I did what you said, 
![image](https://github.com/Azure/Azure-Sentinel/assets/99330808/f2b97a7d-4eba-48c4-861c-e138dfcde12e)
then package it with v2 tool, and have got the same result:
![image](https://github.com/Azure/Azure-Sentinel/assets/99330808/6b21cced-5415-465d-b124-085f19bc5bcf)

**Comment by v-rusraut** [comment]
Hi @vkorenkov-varonis,
Currently we need to create package using v3 tool only, don't create package using v2.
Create package using v3 and raise the PR, once PR merge, we can publish the solution.
Thanks

**Comment by vkorenkov-varonis** [comment]
@v-rusraut,
What's about queries? Can I see the progress of the bug, or how can I know that it's going to work?

**Comment by piExpr** [comment]
Hey i need pe and afd to ingest data and secure.

What egress and ingress rules needs at afd to work with storage  and function app for varonis saas dat alert?

Microsoft content hub oob single touch deployment but i am in need of all ips to allow. Varonis tam been slow to respond.
