### ISSUE TITLE
Documentation for Microsoft.OperationalInsights/workspaces/providers/contentTemplates resource type

### ISSUE THREAD

**Issue by ws-mpiglas** [Azure/Azure-Sentinel#10583]
Hi,

where I can find documentation for `Microsoft.OperationalInsights/workspaces/providers/contentTemplates` resource type? This resources are used to build `mainTemplate.json` descriptiors.
I want to display in [configuration view](https://github.com/Azure/Azure-Sentinel/blob/d69330667253af3b501db8161d4ce5cf3a341be4/Solutions/WithSecureElementsViaFunction/Package/mainTemplate.json#L256) name of Log Analytics Workspace that is connected to Sentinel solution.

**Comment by v-sudkharat** [comment]
Hi @ws-mpiglas, Thanks for flagging this issue, we will investigate this issue and get back to you with some updates by 13-06-2024. Thanks!

**Comment by v-sudkharat** [comment]
Hey @ws-mpiglas, Are you are looking for this Doc - https://learn.microsoft.com/en-us/rest/api/securityinsights/content-template/get?view=rest-securityinsights-2024-03-01&tabs=HTTP

Please let us know if your issue gets resolved. Thanks!

**Comment by ws-mpiglas** [comment]
HI @v-sudkharat, thanks for that link. It help. 
In connector template I have instruction step

```
{
                      "description": ">**IMPORTANT:** Before deploying the WithSecure Elements connector, have the Workspace Name (can be copied from the following)",
                      "instructions": [
                        {
                          "parameters": {
                            "fillWith": [
                              "workspaceName"
                            ],
                            "label": "Workspace Name"
                          },
                          "type": "CopyableLabel"
                        }
                      ]
                    },
```
I want to show "CopyLabel" that is filled with Log Analytics workspace name. How can I achieve that? Can I define this step like 
below and use `"[parameters('workspace-location')]"` in `fillWith` array?
 
```
{
                      "description": ">**IMPORTANT:** Before deploying the WithSecure Elements connector, have the Workspace Name (can be copied from the following)",
                      "instructions": [
                        {
                          "parameters": {
                            "fillWith": [
                              "[parameters('workspace')]"
                            ],
                            "label": "Workspace Name"
                          },
                          "type": "CopyableLabel"
                        }
                      ]
                    },
```

**Comment by v-sudkharat** [comment]
Hey @ws-mpiglas, Correct me if I'm wrong, What I am trying to understand you want to display the workspace name in connector page in which solution has been deployed/connected: 
Old :- 
![image](https://github.com/Azure/Azure-Sentinel/assets/132428394/b630f607-90cf-402c-9aa7-86242fcefd80)

New :- 
![image](https://github.com/Azure/Azure-Sentinel/assets/132428394/5d6f1dbc-72c1-4bdc-9d21-82146360d3d4)

This can be achieved by define "[parameters('workspace')]" :- 
![image](https://github.com/Azure/Azure-Sentinel/assets/132428394/3bddc8f9-f602-4682-b109-719efca0e7c4)

**Comment by ws-mpiglas** [comment]
Yes, that's what I try to achieve. Thx.
