### ISSUE TITLE
Entra ID Content Hub Analytics Rules Related to Entity Map IP Address

### ISSUE THREAD

**Issue by AntoPorter** [Azure/Azure-Sentinel#10599]
**Describe the bug**
Entra ID Content Hub Analytics Rules Related to the Entity Mapping of IP Address needs manual entry of field.

**To Reproduce**
1. Go to Content Hub > Entra ID
2. Click on Manage
3. Scroll down to an Analytic Rule related to an IP in its Entity
4. View Entity Mapping section.

**Expected behavior**
Automatically map entity on new rule creation, similar to all other content hub entra id analytic 

**Desktop (please complete the following information):**
 - OS: Windows 10 22h2
 - Browser: Edge (latest version)

**Comment by v-sudkharat** [comment]
Hi @AntoPorter, Thanks for flagging this issue, we will investigate this issue and get back to you with some updates by 13-06-2024 . Thanks!

**Comment by v-sudkharat** [comment]
Hi @AntoPorter, we have corrected the Entity mapping and now it's auto map while creating the rule :- 
![image](https://github.com/Azure/Azure-Sentinel/assets/132428394/9deadf73-3598-4560-bd99-97a91cf551d1)

Currently team is working on adding changes into solution and will update you once it done. Thanks!

**Comment by AntoPorter** [comment]
Thankyou!
