### ISSUE TITLE
Azure-Sentinel/Solutions/Azure Activity/Hunting Queries /AnalyticsRulesAdministrativeOperations.yaml needs update in line 18

### ISSUE THREAD

**Issue by TriDru** [Azure/Azure-Sentinel#10603]
Good day, 

the rule "AnalyticsRulesAdministrativeOperations" needs an update in line 18.

  | where Category =~ "Administrative" -> | where CategoryValue =~ "Administrative"

best regards
Tristan

**Comment by v-sudkharat** [comment]
Hi @TriDru, Thanks for highlighting issue with us. We have raised PR with correction and the changes will get reflected in upcoming solution version. Thanks!

**Comment by TriDru** [comment]
Thank you!



Tristan Druben
Consultant Microsoft Security

T:    +49 5251 304 600

Net at Work GmbH | Am Hoppenhof 32 A | 33104 Paderborn
Zentrale: +49 5251 304 600 | Fax: +49 5251 304 650
Handelsregister Paderborn: HRB 2663 | Geschäftsführer: Uwe Ulbrich
Näheres zur Informationspflicht nach Artikel 13 DS-GVO und zu unserer Verarbeitung Ihrer personenbezogenen Daten erfahren Sie unter https://www.netatwork.de/wp-content/uploads/Datenschutzinformation-für-Geschäftspartner_Net-at-Work_final.pdf
www.netatwork.de




Microsoft Copilot Webinar-Reihe
In unserer Webinar-Reihe betrachten wir alle Schlüsselbereiche für die erfolgreiche
Einführung von Künstlicher Intelligenz mit Microsoft Copilot – von der technischen
Vorbereitung und Absicherung Ihrer Cloud bis hin zu den neuen Möglichkeiten zur
Optimierung Ihrer Unternehmensprozesse.
Hier anmelden:https://www.netatwork.de/webcasts/
