### ISSUE TITLE
> @azurekid can we get this alert fine tuned to only alert on unique users within 7days range.

### ISSUE THREAD

**Issue by puteen0001** [Azure/Azure-Sentinel#10618]
> @azurekid can we get this alert fine tuned to only alert on unique users within 7days range. 

Sure, I can work on that 👍
Please open an issue, so I can pick it up

_Originally posted by @azurekid in https://github.com/Azure/Azure-Sentinel/issues/8329#issuecomment-2156028513_
            
```[tasklist]
### Tasks
```

**Comment by v-sudkharat** [comment]
@puteen0001, thank you for flagging this issue. Hi @azurekid, may I know are you planning to pick up this specific request/issue? 

Thanks!

**Comment by azurekid** [comment]
Yup, no problem

**Comment by v-sudkharat** [comment]
Hi @puteen0001/ @azurekid, We are closing this issue on GitHub as per our process. Once you get a chance to look into it, we will reopen this issue and link it to your raised PR. Thanks!
