### ISSUE TITLE
TimeGenerated should be rejected field

### ISSUE THREAD

**Issue by truekonrads** [Azure/Azure-Sentinel#1062]
**Describe the bug**
TimeGenerated,RawData and other reserved fields should be rejected. Otherwise the HTTP Data ingestion endpoint accepts the message but silently discards it.

**Comment by v-amolpatil** [comment]
Hi @truekonrads,
Could you please elaborate more on this issue to proceed further? 
Thanks!

**Comment by v-amolpatil** [comment]
Since we have not received a response in the last 5 days, we are closing your issue #1062 as per our standard operating procedures. If you still need support for this issue, feel free to re-open at any time. Thank you for your co-operation.
