### ISSUE TITLE
MLBehaviorAnalytics Analytic Rules can't be installed multiple times where no changes have been applied

### ISSUE THREAD

**Issue by Kaloszer** [Azure/Azure-Sentinel#10635]
**Describe the bug**
MLBehaviorAnalytics analytic rules are not 'redeployable'

**To Reproduce**
1. Deploy arm template with a MLBehaviorAnalytics kind
```
{
    "$schema": "https://schema.management.azure.com/schemas/2019-04-01/deploymentTemplate.json#",
    "contentVersion": "1.0.0.0",
    "parameters": {
        "workspace": {
            "type": "String"
        }
    },
    "resources": [
        {
            "id": "[concat(resourceId('Microsoft.OperationalInsights/workspaces/providers', parameters('workspace'), 'Microsoft.SecurityInsights'),'/alertRules/fefa22be-4236-4306-b67f-72d598b2577c')]",
            "name": "[concat(parameters('workspace'),'/Microsoft.SecurityInsights/fefa22be-4236-4306-b67f-72d598b2577c')]",
            "type": "Microsoft.OperationalInsights/workspaces/providers/alertRules",
            "kind": "MLBehaviorAnalytics",
            "apiVersion": "2023-12-01-preview",
            "properties": {
                "enabled": true,
                "alertRuleTemplateName": "fa118b98-de46-4e94-87f9-8e6d5060b60b"
            }
        }
    ]
}
```

2. Try to deploy it again
3. Get `Analytics rule template 'fa118b98-de46-4e94-87f9-8e6d5060b60b' is already installed for workspace 'workspaceidd', and cannot be installed more than once. (Code: BadRequest)`

**Expected behavior**
ARM Template should be valid and simply do nothing as the asset is deployed and no changes to it have been made.

**Additional context**
This issue is a problem for IaC solutions where assets are deployed continously.

**Comment by v-sudkharat** [comment]
Hi @Kaloszer, Thanks for flagging this issue, we will investigate this issue and get back to you with some updates by 21-06-2024. Thanks!

**Comment by v-sudkharat** [comment]
Hi @Kaloszer, Are you deploying rule from below path? 
https://github.com/Azure/Azure-Sentinel/tree/f8dabf09b04c2f35b9e4313af31dc394196eb29d/Tools/ARM-Templates/AnalyticsRules/MLBehaviorAnalyticsRule

**Comment by Kaloszer** [comment]
@v-sudkharat Umm, no? It's a template. It's just an ARM export of the `fa118b98-de46-4e94-87f9-8e6d5060b60b` rule.

**Comment by v-sudkharat** [comment]
@Kaloszer, Ok. Will check and get back to you. Thanks!

**Comment by v-sudkharat** [comment]
Hey @Kaloszer, could you please follow below steps and check for the deployment:- 
1. Get the name of deployed rule by using below list api : 
https://learn.microsoft.com/en-us/rest/api/securityinsights/alert-rules/list?view=rest-securityinsights-2024-03-01&tabs=HTTP#code-try-0
Once you get the name copy it (which is highlighted into below screenshot) and use in step 2.
![image](https://github.com/Azure/Azure-Sentinel/assets/132428394/f6c4d1d4-9533-4d6e-88d5-96c0c699b3fc)

2. Now, delete the rule by entering required details in below (In rule ID please enter the name which noted down in step 1) And run it : 
https://learn.microsoft.com/en-us/rest/api/securityinsights/alert-rules/delete?view=rest-securityinsights-2024-03-01&tabs=HTTP#code-try-0

The response should be 200 : 
![image](https://github.com/Azure/Azure-Sentinel/assets/132428394/e2d8761f-311e-4835-89d4-02280bbec0b4)

Once it done, check for the deployment in same W.S :- 
![image](https://github.com/Azure/Azure-Sentinel/assets/132428394/d2eb1075-e71c-4151-b83e-f899f54d8d16)

![image](https://github.com/Azure/Azure-Sentinel/assets/132428394/661f9d9f-97df-4b54-8ef0-104dfa2114fb)

Please let us know if it helps you and resolve your issue. Thanks!

**Comment by Kaloszer** [comment]
> Hey @Kaloszer, could you please follow below steps and check for the deployment:- 
> 1. Get the name of deployed rule by using below list api : 
> https://learn.microsoft.com/en-us/rest/api/securityinsights/alert-rules/list?view=rest-securityinsights-2024-03-01&tabs=HTTP#code-try-0
> Once you get the name copy it (which is highlighted into below screenshot) and use in step 2.
> ![image](https://github.com/Azure/Azure-Sentinel/assets/132428394/f6c4d1d4-9533-4d6e-88d5-96c0c699b3fc)
> 
> 2. Now, delete the rule by entering required details in below (In rule ID please enter the name which noted down in step 1) And run it : 
> https://learn.microsoft.com/en-us/rest/api/securityinsights/alert-rules/delete?view=rest-securityinsights-2024-03-01&tabs=HTTP#code-try-0
> 
> The response should be 200 : 
> ![image](https://github.com/Azure/Azure-Sentinel/assets/132428394/e2d8761f-311e-4835-89d4-02280bbec0b4)
> 
> Once it done, check for the deployment in same W.S :- 
> ![image](https://github.com/Azure/Azure-Sentinel/assets/132428394/d2eb1075-e71c-4151-b83e-f899f54d8d16)
> 
> ![image](https://github.com/Azure/Azure-Sentinel/assets/132428394/661f9d9f-97df-4b54-8ef0-104dfa2114fb)
> 
> Please let us know if it helps you and resolve your issue. Thanks! 
> 

Right but you're asking me to remove the rule and add it back again. That won't work for ARM templates which are used here.

**Comment by v-sudkharat** [comment]
Hi @Kaloszer, Could you please let us know can we close this issue? waiting for your confirmation. Thanks!

**Comment by v-sudkharat** [comment]
Hey @Kaloszer, We are awaiting your feedback on the previous comment. It would be appreciated if you could provide your input, allowing us to share the same with the concerned team. Thank you!

**Comment by Kaloszer** [comment]
@v-sudkharat sorry I have had no time to test this - but this seems to might've been the case. Feel free to close this incident I will re-open if it occurs again.
