### ISSUE TITLE
Cisco Umbrella (using Azure Functions) connector for Microsoft Sentinel incorrect custom table

### ISSUE THREAD

**Issue by shaunyb93** [Azure/Azure-Sentinel#10647]
We have deployed an Azure Sentinel Data Connector for Cisco Umbrella
[https://learn.microsoft.com/en-us/azure/sentinel/data-connectors/cisco-umbrella]

The docs suggest the below Log analytics custom tables are relevant:
Cisco_Umbrella_dns_CL
Cisco_Umbrella_proxy_CL
Cisco_Umbrella_ip_CL
Cisco_Umbrella_cloudfirewall_CL

In our Log Analytics workspace, we are seeing that instead of Cisco_Umbrella_cloudfirewall_CL custom table existing and receiving input from the connector, we have Cisco_Umbrella_firewall_CL:
![image](https://github.com/Azure/Azure-Sentinel/assets/172500478/3608c81a-1678-4271-aec1-ea2dad1675ee)
This causes an issue with the workbooks and analytics rules related to the connector - the connector also shows data source Cisco_Umbrella_cloudfirewall_CL as disconnected.

I have raised a support query with Cisco who have informed me that the solution/data connector is supported by Microsoft. 
I have raised a support query with our Azure subscription reseller who are also unable to help as they are not classing this as a break-fix issue. 

Some further info on the problem:
The logs are being pulled via API from a Cisco-managed S3 bucket with the following containers in existence:
auditlogs
dnslogs
firewalllogs
proxylogs

I am **not** a programmer however I have taken a look inside the code within the Cisco Umbrella (using Azure Functions) connector function app code and I believe there may be an issue with how the data is pulled via API and then pushed into the Log Analytics workspace. I am guessing that because the table in the S3 bucket is called "firewalllogs" that the logic in the Function is pushing the pulled data into Log Analytics table "Cisco_Umbrella_firewall_CL". 

Any further input on resolving this is appreciated.

**Comment by v-rusraut** [comment]
Hi @shaunyb93, Thanks for flagging this issue, we will investigate this issue and get back to you with some updates by 19-06-2024. Thanks!

**Comment by macna** [comment]
Hi, just to add that I am seeing this behaviour also, in two separate deployments.

**Comment by v-rusraut** [comment]
Hi @shaunyb93,
We are working on reproduce the issue, we will update you.
Thanks

**Comment by v-rusraut** [comment]
Hi @shaunyb93,
Please help us to understand which version of Cisco Umbrella you are using currently.
Thanks

**Comment by shaunyb93** [comment]
Hi @v-rusraut 
Cisco Umbrella is a cloud service, there is no specific version information. 
Is there some specific info you were looking for?
Thanks
Shaun

**Comment by shaunyb93** [comment]
Details on the log folders and formats are shown here
https://docs.umbrella.com/umbrella-user-guide/docs/log-format-and-versioning

**Comment by v-rusraut** [comment]
> Details on the log folders and formats are shown here https://docs.umbrella.com/umbrella-user-guide/docs/log-format-and-versioning

Yes , please provide schema version

**Comment by shaunyb93** [comment]
We are using Log Schema v8

**Comment by v-rusraut** [comment]
Hi @shaunyb93,
Please refer link https://learn.microsoft.com/en-us/azure/sentinel/data-connectors/cisco-umbrella it is mentioned This connector has been updated to support [cisco umbrella version 5 and version 6
![5](https://github.com/Azure/Azure-Sentinel/assets/126679503/3dc0b3be-5ceb-41f6-8204-431e46283060)

**Comment by shaunyb93** [comment]
Hi @v-rusraut 
Thanks although we were still having this issue before we upgraded to schema v8
The schema versions have mild difference in fields although I can't see how this would affect which custom table sentinel is writing to? Perhaps you could advise further? Thanks

**Comment by shaunyb93** [comment]
Any update here?
Thanks

**Comment by v-sudkharat** [comment]
@shaunyb93, We are checking the template for this issue, just want to know, do you have any test workspace in your environment? so, if required will share the update template with you. Thanks!

**Comment by shaunyb93** [comment]
Hi @v-sudkharat is there any update on a fix here?

**Comment by v-rusraut** [comment]
Hi @shaunyb93,

According to the Cisco Umbrealla log documentation, they are now stored in "firewalllogs": https://docs.umbrella.com/umbrella-user-guide/docs/log-format-and-versioning

![image](https://github.com/user-attachments/assets/560926af-60ab-424d-bb0b-028b8a927cb8)

We have updated the template and will raise PR with the changes. Meantime, could you please custom deploy the Solution MainTemplate and check whether your issue get resolved.
Sharing the MainTemplate and Custom deployment steps-
Custom Deployment - [CustomDeploymentSteps.docx](https://github.com/user-attachments/files/16782483/CustomDeploymentSteps.docx)
Main template - [mainTemplate.json](https://github.com/user-attachments/files/16782484/mainTemplate.json)

Thanks

**Comment by shaunyb93** [comment]
Hi @v-rusraut Thanks for the reply. 

Cisco advised that these logs have always been stored in firewalllogs rather than cloudfirewalllogs so seems like an oversight in the initial development of this connector/solution. 

Looking at the mainTemplate.json you have provided, cloudfirewalllogs is still referenced in the Workbook (line 775)
Can you advise if this can be corrected?

Will making a custom deployment mean that we need to redeploy the function app again?

Ideally we would like the fix to be applied whereby we can run an update against our existing deployment without the need to redeploy or reconfigure the function app.

Thanks
Shaun

**Comment by v-rusraut** [comment]
Hi @shaunyb93,

If you deploy solution with custom deployment, then you don't need to redeploy function app again.
We need to correct reference of cloudfirewalllogs  in the Workbook, please check EventType column value in Cisco_Umbrella_firewall_CL table, so we can create package again.

Thanks

**Comment by v-rusraut** [comment]
Hi @shaunyb93,
We have updated mainTemplate again, please custom deploy the mainTemplate and check whether your issue get resolved.
Custom Deployment - [CustomDeploymentSteps.docx](https://github.com/user-attachments/files/16782483/CustomDeploymentSteps.docx)
Main template -[mainTemplate.json](https://github.com/user-attachments/files/16799610/mainTemplate.json)
Thanks

**Comment by shaunyb93** [comment]
Hi @v-rusraut 
Cisco_Umbrella_cloudfirewall_CL was still refrerenced on line 822
I changed this manually to Cisco_Umbrella_firewall_CL and ran the custom deployment. 
This does appear to have resolved the issue:
![image](https://github.com/user-attachments/assets/3bd69489-b1dd-4b8e-b361-fb496edabff8)

DataType Cisco_Umbrella_firewall_CL is now showing as connected against the Data connector. 
Thanks
Shaun

**Comment by v-rusraut** [comment]
Hi @shaunyb93,
As table  Cisco_Umbrella_firewall_CL showing as a connected, so closing this issue. As the IPS traffic events not ingested so this is feature request you can raise new Github issue so we can share details with respective team, if you still need support for this issue, feel free to re-open it any time. Thank you for your co-operation.
