### ISSUE TITLE
1Password Solution: Typo in query for "changes to sso configuration" analytics rule

### ISSUE THREAD

**Issue by scottisloud** [Azure/Azure-Sentinel#10650]
**Describe the bug**
The analytics rule for `1Password - Changes to SSO configuration` has a typo. 
Currently:
```
  OnePasswordEventLogs_CL
  | where log_source == "auditevents"
  | where action has_any("enblsso", "disblsso", "chngpsso", "chngasso", "chngdssoo", "addgsso", "delgsso")
  | where object_type == "sso"
  | extend
      ActorUsername = actor_details.email
      , SrcIpAddr = session.ip
```
The arguments passed to `has_any()`, `"changdssoo"`, should be `"changdsso"`

**To Reproduce**
No steps required. 

**Expected behavior**
Query should detect all SSO config changes. 

**Screenshots**
n/a

**Additional context**
I am a 1Password employee and am currently provisionally the technical point of contact for this solution and work in collaboration with @azurekid 

We will address this issue along with others in a future PR.

**Comment by azurekid** [comment]
I will pick this up and do a PR tomorrow to fix the typo

**Comment by v-sudkharat** [comment]
Hi @scottisloud, thanks for flagging this issue. 
@azurekid, please let us know once PR raised, so we can link into this issue. Thanks!

**Comment by v-prasadboke** [comment]
> I will pick this up and do a PR tomorrow to fix the typo

Hello @azurekid, Let me know once you raise the PR. I'll assign it on my name. 

@scottisloud Thanks for pointing this typo error.

**Comment by v-sudkharat** [comment]
Hey @azurekid, Did you get a chance to raised PR for this? please let us know once you raised PR, so we can link this this issue. 
Thanks!

**Comment by azurekid** [comment]
> Hey @azurekid, Did you get a chance to raised PR for this? please let us know once you raised PR, so we can link this this issue. Thanks!

Will do it right now

**Comment by azurekid** [comment]
created PR: #10706
