### ISSUE TITLE
Netskopev2 solution - incorrect deploy buttons

### ISSUE THREAD

**Issue by Wh00T** [Azure/Azure-Sentinel#10657]
**Describe the bug**
The new Netskope v2 solution has incorrect "Deploy to Azure" links in the connector descriptions.

Solution link in Github:
https://github.com/Azure/Azure-Sentinel/tree/master/Solutions/Netskopev2

Netskope Data Connector (using Azure Functions)
https://aka.ms/sentinel-Netskope-azuredeploy
This link will lead you to the deployment template of the v1 version.

Netskope Web Transactions Data Connector (using Azure Functions)
https://aka.ms/sentinel-NetskopeWebTransactions-azuredeploy
This link does not exist and redirects to Bing.

Fyi, not sure if it's on purpose but there is also no documentation on how to manually deploy the Netskope Data Connector, so it can't be deployed from the Azure portal right now ;)

Tagging the solution author @nipun-crestdatasystem for awareness.

**To Reproduce**
Go to 'Content Hub' > 'Netskope' > Install the solution > 'Manage' > 'Netskope Data Connector (using Azure Functions)' > 'Open connector page' > Click on 'Deploy to Azure'

Does not work for the second connector as well:
Go to 'Content Hub' > 'Netskope' > Install the solution > 'Manage' > 'Netskope Web Transactions Data Connector (using Azure Functions)' > 'Open connector page' > Click on 'Deploy to Azure'

**Expected behavior**
Links should bring you to a custom deployment page for the Azure function of the v2 solution.

**Screenshots**
![image](https://github.com/Azure/Azure-Sentinel/assets/1562582/d1a7642a-da23-4ade-9ed0-49cd5b133f75)

**Comment by v-rusraut** [comment]
Hi @Wh00T, Thanks for flagging this issue, we will investigate this issue and get back to you with some updates by 20-06-2024. Thanks!

**Comment by v-rusraut** [comment]
Hi @Wh00T,
We corrected Deploy to Azure links, please verify it so we can close the issue.
Thanks

**Comment by v-rusraut** [comment]
Hi @Wh00T,
We are waiting for response from you.

**Comment by Wh00T** [comment]
Confirm, links have been fixed.

**Comment by v-rusraut** [comment]
@Wh00T, Thanks for the confirmation. So, closing this issue. If you still need support for this issue, feel free to re-open it any time. Thank you for your co-operation.
