### ISSUE TITLE
Extract Entities for incident Creation for AATP/ASC/AADIP.. alerts 

### ISSUE THREAD

**Issue by kay07949** [Azure/Azure-Sentinel#1065]
Hi All, 

i created the scheduled query below for high severity AATP alerts, this is in order to make use of the alert grouping feature which is not currently available for Microsoft Incident Creation rules. What is the best way to extract the entites? Below is the approach I used, is there a better way of doing this?

SecurityAlert
| where ProviderName == "Azure Advanced Threat Protection"
| where AlertSeverity == "High"
| extend Ent = parse_json(Entities) 
| mvexpand Ent
| extend AccountCustomEntity = tostring(Ent.Name)
| extend HostCustomEntity = tostring(Ent.HostName)
| extend IPCustomEntity = tostring(Ent.Address)

thank you in advance.

**Comment by kay07949** [comment]
i want to do the same for other microsoft alerts such as aadip, asc, mdatp, etc.

**Comment by shainw** [comment]
@kay07949 - this is the best way I can find.  Let me check with some others.

**Comment by ashwin-patil** [comment]
Yes, this is the right start however you will have to aggregate the results at the end per Alert and Timestamp so you do not count 4 alerts when there was originally an alert with 4 account entities since we expanded Entities array. 

Here is the extended query you can use for all providers 

```
SecurityAlert
// Converting Entities into dynamic data type and use mv-expand to unpack the array
| extend EntitiesDynamicArray = parse_json(Entities) 
| mv-expand EntitiesDynamicArray
// Parsing relevant entity column extract hostname and IP address
| extend EntityType = tostring(parse_json(EntitiesDynamicArray).Type), EntityAddress = tostring(EntitiesDynamicArray.Address), EntityHostName = tostring(EntitiesDynamicArray.HostName), EntityAccountName = tostring(EntitiesDynamicArray.Name)
| extend HostName = iif(EntityType == 'host', EntityHostName, '')
| extend IPAddress = iif(EntityType == 'ip', EntityAddress, '')
| extend Account = iif(EntityType == 'account', EntityAccountName, '')
| where isnotempty(IPAddress) or isnotempty(Account) or isnotempty(HostName)
// Aggregating by Time and Alert to consolidate all entities per Alert
| summarize AccountList=make_set(Account), IPList = make_set(IPAddress), HostList = make_set(HostName) by TimeGenerated, AlertName
```

**Comment by shainw** [comment]
Closing as this appears to be answered.
