### ISSUE TITLE
Pull request validation error for KQL to YAML conversation

### ISSUE THREAD

**Issue by mattnovitsch** [Azure/Azure-Sentinel#10667]
When trying to commit a pull request for a KQL that I converted to YAML, I get the following error message: 

[Check failure on line 24 in Build log](https://github.com/Azure/Azure-Sentinel/pull/10666/files#annotation_22885235285) 

@azure-pipelines
azure-pipelines
/ Azure.Azure-Sentinel (YamlFileValidation)
Build log #L24
An error occurred, please open an issue
 [Check failure on line 26 in Build log](https://github.com/Azure/Azure-Sentinel/pull/10666/files#annotation_22885235297) 

@azure-pipelines
azure-pipelines
/ Azure.Azure-Sentinel (YamlFileValidation)
Build log #L26
Bash exited with code '255'.

And 

[Check failure on line 73 in Build log](https://github.com/Azure/Azure-Sentinel/pull/10666/files#annotation_22885181137) 

@azure-pipelines
azure-pipelines
/ Azure.Azure-Sentinel (KqlValidations)
Build log #L73
Error: The process '/opt/hostedtoolcache/dotnet/dotnet' failed with exit code 1
 [Check failure on line 78 in Build log](https://github.com/Azure/Azure-Sentinel/pull/10666/files#annotation_22885181149) 

@azure-pipelines
azure-pipelines
/ Azure.Azure-Sentinel (KqlValidations)
Build log #L78
Dotnet command failed with non-zero exit code on the following projects : [
  '/home/vsts/work/1/s/.script/tests/KqlvalidationsTests/Kqlvalidations.Tests.csproj'
]

**Comment by v-sudkharat** [comment]
Hi @mattnovitsch, We have investigated the validation failures, and found that the failure occurred due to indentation error, which we fixed into rule and raised Draft PR - https://github.com/Azure/Azure-Sentinel/pull/10671 
Please refer above draft PR and make changes accordingly. And while committing the updated changes please make sure branch should be updated with Master. 
Thanks!

**Comment by mattnovitsch** [comment]
I refreshed my fork but I still get the same message.

**Comment by v-sudkharat** [comment]
@mattnovitsch, I can see the new files has been into the PR, our review team will check on validations and will help you to fix on it.
