### ISSUE TITLE
Microsoft Purview Insider Risk Management Analytics Rule - Grouping is enabled by Default but has incorrect value associated

### ISSUE THREAD

**Issue by AntoPorter** [Azure/Azure-Sentinel#10677]
**Describe the bug**
Microsoft Purview Insider Risk Management Analytics Rule - Grouping is enabled by Default but has incorrect value associated. This is for all of the Analytics Rules where the grouping of an Alert is based on X number of days, but the days field is set to 0 by default.

**To Reproduce**
1. Go to 'Content Hub'
2. Click on 'Microsoft Purview Insider Risk Management'
3. Scroll down to 'Any Analytics Rule'
4. Create Rule > Run through prompts > Errors on Review due to requirement.

**Expected behavior**
Change 0 Days to 1 Day as Default

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Microsoft Edge
 - Version: Latest

https://github.com/Azure/Azure-Sentinel/tree/master/Solutions/MicrosoftPurviewInsiderRiskManagement/Analytic%20Rules

**Comment by v-sudkharat** [comment]
Hi @AntoPorter, Thanks for flagging this issue, we will investigate this issue and get back to you with some updates by 28-06-2024. Thanks!

**Comment by v-sudkharat** [comment]
Hey @AntoPorter,  In Alert grouping in your end the values are default to 0 day's ? 
![image](https://github.com/Azure/Azure-Sentinel/assets/132428394/e7d1c3aa-614f-4f60-859f-1c33e819c5c9)
want to understand the issue you are facing, while creation of rule what type of error you are getting? It would be great if you could share the error message screenshots with us. 
Thanks!

**Comment by AntoPorter** [comment]
Correct, defaults to 0 days

**Comment by v-sudkharat** [comment]
Hey @AntoPorter, the Alert Grouping time frame is having 3 different durations', which is highlighted below, and while configuring the rule you can set groping time x minutes or hours, if we set default to 1 days then it may affect to other customer too. 
![image](https://github.com/Azure/Azure-Sentinel/assets/132428394/62078549-70c2-4544-b7ec-fff826ce0344)

Hope we answered to your query.

**Comment by AntoPorter** [comment]
Makes perfect sense. Thankyou for looking into it
