### ISSUE TITLE
1Password Solution: App Analytics for Function App defaults to deprecated "classic". 

### ISSUE THREAD

**Issue by scottisloud** [Azure/Azure-Sentinel#10676]
**Describe the bug**
When deployed using the current manifest, the App Insights resources appears to be created as a "classic" resource type. Since this has now been deprecated, new deployments cannot be made to certain regions (e.g., Sweden Central). The App Insights resource should be a Workbook type resource going forward. 

**To Reproduce**
1. Attempt to deploy the solution to a region where Classic app insights have been deprecated. 
2. Function App fails because App Insights resource cannot be created. 

**Expected behavior**
Deployment should succeed. 

**Additional context**
This is something that I (as a 1Password employee) and @azurekid can work on and resolve.

**Comment by v-sudkharat** [comment]
Thanks @scottisloud, for flagging this issue. 
@azurekid, Could you please look into this issue? Thanks!

**Comment by v-sudkharat** [comment]
@azurekid, will link this issue once you raise a PR for this feature request, @scottisloud, As of now closing this from GitHub. Thanks!

**Comment by scottisloud** [comment]
We're seeing some reports from customers attempting to deploy the Solution in some relatively common regions (e.g., canada-central) and failing due to Classic resource mode for Application Insights resources being deprecated in that region. 

Would the Codeless connector currently in PR resolve this? Is there a relatively straightforward way to update the existing solution to use Workspace-based mode?
