### ISSUE TITLE
Error on deploying the data connector

### ISSUE THREAD

**Issue by net-imp** [Azure/Azure-Sentinel#10679]
**Describe the bug**
When clicking to deploy the data connector from Sentinel it gives the following error message: "There was an error downloading the template from URI 'https://github.com/Azure/Azure-Sentinel/blob/master/Solutions/Auth0/Data Connectors/azuredeploy_Auth0_FunctionApp.json'. Ensure that the template is publicly accessible and that the publisher has enabled CORS policy on the endpoint. To deploy this template, download the template manually and paste the contents in the 'Build your own template in the editor' option below. "

**To Reproduce**
1. Go to 'Sentinel > Data Connectors > Auth0 Access Management'
2. Click on 'Deploy to Azure'
3. See error

**Expected behavior**
Expected to install the conector (worked 3 months ago)

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser Edge and Chrome
 - Version 125

**Additional context**

**Comment by v-sudkharat** [comment]
Hi @net-imp, Thanks for flagging this issue, we will investigate this issue and get back to you with some updates by 25-06-2024 . Thanks!

**Comment by v-sudkharat** [comment]
Hey @net-imp, We have fix the link, Kindly check and let us know if your issue resolved. Thanks!

**Comment by net-imp** [comment]
Looking good now! Thank you!

**Comment by net-imp** [comment]
Working as expected again. Closing
