### ISSUE TITLE
DCR - Xpath modification trough GUI overwrite previous ARM  transformKQL and Output Stream

### ISSUE THREAD

**Issue by JiTmun** [Azure/Azure-Sentinel#10678]
**Summary**
Modification of an xpath of a DCR through AZure Monitor overwrite previous dataflows set at DCR creation with an ARM template.

**To Reproduce**
1. Create a DCR from an ARM template with several streams and transformation
ARM details:
    "$schema": "https://schema.management.azure.com/schemas/2019-04-01/deploymentTemplate.json#",
    "contentVersion": "1.0.0.0",
3. deploy to workspace
4. Go to Azure Monitor on the same DCR,
5. modify the XPATH only and save
6. The Output stream is also modified, and dataflows are reset to default

**Expected behavior**
Edit of the Xpath from Azure Monitor should not overwrite dataflows

**Screenshots**
![image](https://github.com/Azure/Azure-Sentinel/assets/95627331/8920733b-ad7b-4a6b-9766-8bcdcc422123)

**Desktop (please complete the following information):**
 - OS: WIn11
 - Browser : Edge 
 - Version :Version 125.0.2535.92 (Official build) (64-bit)

**Comment by v-rusraut** [comment]
Hi @JiTmun ,
Thanks for flagging this issue, we will investigate this issue and get back to you with some updates by 27 June 2024. Thanks!

**Comment by v-sudkharat** [comment]
Hi @JiTmun, This Data collection rule issue needs to be investigated by concern (DCR) team, so we kindly request you to raise a support ticket case in azure portal, so our support team can check into it and connect with you if required. 
Please let us know once you raise a ticket, so we can close this issue from GitHub. Thanks!

**Comment by v-sudkharat** [comment]
@JiTmun, Waiting for your response. Thanks!

**Comment by v-sudkharat** [comment]
Hi @JiTmun, Gentle Reminder: We are waiting for your response on this issue. If you still need to keep this issue active, please respond to it in the next 2 days. If we don't receive a response by 15-07-2024 date, we will be closing this issue. 		
Thanks!

**Comment by v-sudkharat** [comment]
Hi @JiTmun, since we have not received a response in the last 5 days, we are closing your issue as per our standard operating procedures. If you still need support for this issue, feel free to re-open at any time. Thank you for your co-operation.
