### ISSUE TITLE
VMware Carbon Black Cloud Sentinel Data connector not ingesting alerts- Sentinel

### ISSUE THREAD

**Issue by sandeep5234** [Azure/Azure-Sentinel#10680]
We have updated the VMware carbon black data connector to new version. There are 2 functions in it, The audit event function is working ok. But AlertsAPITimer function is not ingesting data. 
We have noticed that ORG KEY ID is a new field required as well because notification_cl is deprecated. We have added the ORK KEY ID into Environmental variables.  But this didn't fix the issue. 

We can see there are no errors as well. But there is no data as well for alerts, We have triggered few test alerts from Carbon black console, but still no data.
This is all the output we see 
![image](https://github.com/Azure/Azure-Sentinel/assets/41977495/eb26391a-caf1-4f0a-8a34-97830c3a9737)

**Comment by v-rusraut** [comment]
Hi @sandeep5234,
Thanks for flagging this issue, we will investigate this issue and get back to you with some updates by 27 June 2024. Thanks!

**Comment by sandeep5234** [comment]
thank you @v-rusraut .

**Comment by v-rusraut** [comment]
Hi @sandeep5234,
We are working on reproduce the issue.
Thanks

**Comment by sandeep5234** [comment]
Thanks for the update @v-rusraut

**Comment by sandeep5234** [comment]
@v-rusraut   Any update on this?

**Comment by v-sudkharat** [comment]
Hey @sandeep5234, While configuring the function app, what value you have added for Log Types? 
Could you please check with below one :- 

![image](https://github.com/Azure/Azure-Sentinel/assets/132428394/95ab967a-814b-4fc4-ac45-a594bc6b0b01)

**Comment by sandeep5234** [comment]
@v-sudkharat I have added above log types and getting below error now.
<img width="418" alt="image" src="https://github.com/Azure/Azure-Sentinel/assets/41977495/1a0cbdfd-4d5b-494c-b766-0b4bf334e4f4">
<img width="407" alt="image" src="https://github.com/Azure/Azure-Sentinel/assets/41977495/e45c61de-624a-4d3a-a71c-b4b0ddfe3f6d">
<img width="412" alt="image" src="https://github.com/Azure/Azure-Sentinel/assets/41977495/d29c54b5-41c7-4321-8a09-964cfa257151">
<img width="407" alt="image" src="https://github.com/Azure/Azure-Sentinel/assets/41977495/e5402ce5-d037-4c84-a12c-12f3c952609f">

**Comment by sandeep5234** [comment]
@v-sudkharat above error coming up on AuditEventAlertsTimer function but the AlertsAPITimer function is still showing same output after adding new log types
<img width="947" alt="image" src="https://github.com/Azure/Azure-Sentinel/assets/41977495/61b5ecd8-6d0d-4525-bf30-a45dda591af4">

**Comment by v-sudkharat** [comment]
> @v-sudkharat I have added above log types and getting below error now. <img alt="image" width="418" src="https://private-user-images.githubusercontent.com/41977495/345268378-1a0cbdfd-4d5b-494c-b766-0b4bf334e4f4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk5OTAyMzMsIm5iZiI6MTcxOTk4OTkzMywicGF0aCI6Ii80MTk3NzQ5NS8zNDUyNjgzNzgtMWEwY2JkZmQtNGQ1Yi00OTRjLWI3NjYtMGI0YmYzMzRlNGY0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzAzVDA2NTg1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdmYmZjOThhNDYwYTlmZWY1MzQwMTdkODdmOTE0M2RlZGM4Yzk2MjU3MTk2Y2NkMjkxMjM0OGJjNWY5YmE3ZmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.NXMMgWV3fX-Wm4jxqEfZGMzblFenx4BdgCVO3-r2XRM"> <img alt="image" width="407" src="https://private-user-images.githubusercontent.com/41977495/345268448-e45c61de-624a-4d3a-a71c-b4b0ddfe3f6d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk5OTAyMzMsIm5iZiI6MTcxOTk4OTkzMywicGF0aCI6Ii80MTk3NzQ5NS8zNDUyNjg0NDgtZTQ1YzYxZGUtNjI0YS00ZDNhLWE3MWMtYjRiMGRkZmUzZjZkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzAzVDA2NTg1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ2YzQyY2I4N2Y4ZjgwMGNlZTM4NDlhOWE3M2Y5NTlhZDNjMmM2YTY5MDFkZGQzMjNmY2JlOGJhNjAxYzU4NmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.pnWwIrjsEbiPemB9djhl0IriV4iEZz6quu9t_gB0ITY"> <img alt="image" width="412" src="https://private-user-images.githubusercontent.com/41977495/345268495-d29c54b5-41c7-4321-8a09-964cfa257151.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk5OTAyMzMsIm5iZiI6MTcxOTk4OTkzMywicGF0aCI6Ii80MTk3NzQ5NS8zNDUyNjg0OTUtZDI5YzU0YjUtNDFjNy00MzIxLThhMDktOTY0Y2ZhMjU3MTUxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzAzVDA2NTg1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVkMjJjNzA3ODQwYzQ5M2ExY2MwOGU3ZjZjYTgxZWVkMWM2NjE4Nzk2ZDJjNzg0YzcxYzljZGUyZDc4MTg5NTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.zY9hzEaZ78f4xmq3MjswnlXLIlBwuAkNQrDbeqgtTbI"> <img alt="image" width="407" src="https://private-user-images.githubusercontent.com/41977495/345268539-e5402ce5-d037-4c84-a12c-12f3c952609f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk5OTAyMzMsIm5iZiI6MTcxOTk4OTkzMywicGF0aCI6Ii80MTk3NzQ5NS8zNDUyNjg1MzktZTU0MDJjZTUtZDAzNy00Yzg0LWExMmMtMTJmM2M5NTI2MDlmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzAzVDA2NTg1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU3OThiNjEwMTBmM2NiNGExYjFkMzJkMDc2OGI3Y2ZlYmY0MmNjOTJkNjA1ZDhkNTllNDRkYzdhNDcwZDc3OGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.jMXE7WYtIkTJB5eCqyANsqif2IClBD0tXjXsvQuD-rA">

@sandeep5234, Check with the log's by updating the PowerShell version to 7.4 in configuration tab : 
![image](https://github.com/Azure/Azure-Sentinel/assets/132428394/a68bbb07-972a-484f-9a7a-545b4ef1edd3)

**Comment by sandeep5234** [comment]
ok checking now @v-sudkharat

**Comment by MBCloudTeck** [comment]
> Hey @sandeep5234, While configuring the function app, what value you have added for Log Types? Could you please check with below one :-
> 
> ![image](https://private-user-images.githubusercontent.com/132428394/345029787-95ab967a-814b-4fc4-ac45-a594bc6b0b01.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAwMjAxNTYsIm5iZiI6MTcyMDAxOTg1NiwicGF0aCI6Ii8xMzI0MjgzOTQvMzQ1MDI5Nzg3LTk1YWI5NjdhLTgxNGItNGZjNC1hYzQ1LWE1OTRiYzZiMGIwMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcwM1QxNTE3MzZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00ZDYwOTIzMjhjNDFmYmQ0Y2RiZWYwMzkyOTJmMWRjNjgxYTI2MzA3ZDhmMmNhMTM0ZjRkY2EzODliNmU0NDYzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.JXAY6Orc0wERP2Vum1vAkQ517LXV8VbHgmUO0HFjW9g)

Hi - Please can you confirm the correct format for this variable is as pictured or the value should be - 

["alert","audit","event","alertSIEMAPI"]

Thanks for your help!

**Comment by MBCloudTeck** [comment]
Further to this, are there any full configuration documents you would recommend. The most helpful we have found is https://simple-security.ca/2023/05/02/cheat-sheet-for-configuring-carbon-black-cloud-edr-for-sentinel/

**Comment by sandeep5234** [comment]
@v-sudkharat We have generated few alerts in Carbon black console but still didn't get notifications in Sentinel workspace. 
What else can we we check?

**Comment by v-sudkharat** [comment]
> > Hey @sandeep5234, While configuring the function app, what value you have added for Log Types? Could you please check with below one :-
> > ![image](https://private-user-images.githubusercontent.com/132428394/345029787-95ab967a-814b-4fc4-ac45-a594bc6b0b01.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAwMjAxNTYsIm5iZiI6MTcyMDAxOTg1NiwicGF0aCI6Ii8xMzI0MjgzOTQvMzQ1MDI5Nzg3LTk1YWI5NjdhLTgxNGItNGZjNC1hYzQ1LWE1OTRiYzZiMGIwMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcwM1QxNTE3MzZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00ZDYwOTIzMjhjNDFmYmQ0Y2RiZWYwMzkyOTJmMWRjNjgxYTI2MzA3ZDhmMmNhMTM0ZjRkY2EzODliNmU0NDYzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.JXAY6Orc0wERP2Vum1vAkQ517LXV8VbHgmUO0HFjW9g)
> 
> Hi - Please can you confirm the correct format for this variable is as pictured or the value should be -
> 
> ["alert","audit","event","alertSIEMAPI"]
> 
> Thanks for your help!

Yes, you add those values.

**Comment by v-sudkharat** [comment]
Hi @sandeep5234, Could you please check the data is ingesting into the table - `CarbonBlackAlerts_CL`, and let us know the result. 
Currently, our team is planning to make this change into solution as well. Thanks!

**Comment by sandeep5234** [comment]
@v-sudkharat looks like that table is not created in the workspace
<img width="320" alt="image" src="https://github.com/Azure/Azure-Sentinel/assets/41977495/01927c70-c536-4ea4-8a18-332503c730d2">
Will we need to create that table manually?

**Comment by MBCloudTeck** [comment]
> @v-sudkharat looks like that table is not created in the workspace <img alt="image" width="320" src="https://private-user-images.githubusercontent.com/41977495/346559720-01927c70-c536-4ea4-8a18-332503c730d2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA0NDI3NTksIm5iZiI6MTcyMDQ0MjQ1OSwicGF0aCI6Ii80MTk3NzQ5NS8zNDY1NTk3MjAtMDE5MjdjNzAtYzUzNi00ZWE0LThhMTgtMzMyNTAzYzczMGQyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA4VDEyNDA1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRhMGYyMDYyYzU3MWI4NmUyNDMyYmI4NjZiZmJjMDFkY2ZkNzhhYmVlODlmOWY1NDk3MjZmNDZmNjUxYTE0ZTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.8h_41rlNX0LiRwJr9MRNNYZCSEdbcgpYBsRzgGW6l1Y"> Will we need to create that table manually?

No the table should self create.

**Comment by MBCloudTeck** [comment]
> > > Hey @sandeep5234, While configuring the function app, what value you have added for Log Types? Could you please check with below one :-
> > > ![image](https://private-user-images.githubusercontent.com/132428394/345029787-95ab967a-814b-4fc4-ac45-a594bc6b0b01.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAwMjAxNTYsIm5iZiI6MTcyMDAxOTg1NiwicGF0aCI6Ii8xMzI0MjgzOTQvMzQ1MDI5Nzg3LTk1YWI5NjdhLTgxNGItNGZjNC1hYzQ1LWE1OTRiYzZiMGIwMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcwM1QxNTE3MzZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00ZDYwOTIzMjhjNDFmYmQ0Y2RiZWYwMzkyOTJmMWRjNjgxYTI2MzA3ZDhmMmNhMTM0ZjRkY2EzODliNmU0NDYzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.JXAY6Orc0wERP2Vum1vAkQ517LXV8VbHgmUO0HFjW9g)
> > 
> > 
> > Hi - Please can you confirm the correct format for this variable is as pictured or the value should be -
> > ["alert","audit","event","alertSIEMAPI"]
> > Thanks for your help!
> 
> Yes, you add those values.

To confirm this only worked using the values seen in the document. NOT the ones I included here. 

alert,audit,event,alertSIEMAPI

Hope this helps. - Also setting the Powershell version back to 7.2 worked for us!

**Comment by sandeep5234** [comment]
@MBCloudTeck applied above settings but not change. My function app is not even creating the table in the workspace. But i can see it says 0 alert . We definitely had some alerts over the weekend. 

<img width="617" alt="image" src="https://github.com/Azure/Azure-Sentinel/assets/41977495/0b0d6266-dbf2-48c8-8e2a-b10485b98c29">

**Comment by sandeep5234** [comment]
@v-sudkharat I have asked customer to generate test alerts. In total 3 alerts were generated and I can see 3 alerts in the function app logs but no data appears in the sentinel workspace.

Please see below

![image](https://github.com/Azure/Azure-Sentinel/assets/41977495/304a90ad-5fff-4926-885b-35927f8ff75a)

**Comment by MBCloudTeck** [comment]
Based on you getting that far, I would now go back to basics and investigate, 

2, Validate the function app access to the Log Analytics Workspace, or better temp "Contributor to the Resource group" the Log analytics sits in, and give it Sentinel Contributor temporally just to be safe. 

1, The format of the logs. Ensuring the exact string above is listed. Use postman to validate the call and response.

**Comment by sandeep5234** [comment]
@v-sudkharat  I have checked the Function app from my side but stuck now. Please let me know the next steps.

**Comment by sandeep5234** [comment]
> Based on you getting that far, I would now go back to basics and investigate,
> 
> 2, Validate the function app access to the Log Analytics Workspace, or better temp "Contributor to the Resource group" the Log analytics sits in, and give it Sentinel Contributor temporally just to be safe.
> 
> 1, The format of the logs. Ensuring the exact string above is listed. Use postman to validate the call and response.

thanks @MBCloudTeck  I think function post request used Workspace ID and Key to post data and I think same ID and key can be used to create authorisation header as well. 

Not sure what else to check.

**Comment by v-sudkharat** [comment]
Hi @sandeep5234, Let's connect via a call, to understand and troubleshoot the issue, could you please send mail id with us on - v-sudkharat@microsoft.com

**Comment by sandeep5234** [comment]
@v-sudkharat I have sent you the email and added my availability as well.

**Comment by v-sudkharat** [comment]
Hi @sandeep5234, Sent an invite via a mail. Thanks!

**Comment by v-sudkharat** [comment]
Hey @sandeep5234, As we are in touch with our support team for this issue, and keeping you updated over mail, so can we close this issue from GitHub? Thanks!

**Comment by sandeep5234** [comment]
@v-sudkharat  yes you can close this case. Thank you.

**Comment by v-sudkharat** [comment]
@sandeep5234, Thank you for confirmation.
