### ISSUE TITLE
Issue with remove_protocol_from_list function

### ISSUE THREAD

**Issue by cgiamp** [Azure/Azure-Sentinel#10695]
Hi,

There seems to be an issue with Fortinet fortigate websession parser on the remove_protocol_from_list function:
https://github.com/Azure/Azure-Sentinel/blob/33961025f93c4ff482a3d89534864ca4cdc164e0/Parsers/ASimWebSession/Parsers/vimWebSessionFortinetFortiGate.yaml#L71

If you pass an argument on url_has_any **without** protocol, the function returns the string trimmed by 1 character:
![image](https://github.com/Azure/Azure-Sentinel/assets/22245093/ed4b1525-93bb-4f8d-b252-6825e7ee916a)

A possible fix is the following:
```
let remove_protocol_from_list = (list: dynamic) {
    print list
        | mv-apply l = print_0 to typeof(string) on
            (extend l = iff( l has "//", substring(l, indexof(l, @'//') + 2), l )) 
        | project l
};
``` 
![image](https://github.com/Azure/Azure-Sentinel/assets/22245093/4e4f9a2e-6f76-459e-ac88-75014d180f70)

Regards,
Christos.

**Comment by cgiamp** [comment]
Hi,
Any update to this one ?

**Comment by vakohl** [comment]
Thankyou for highlighting this @cgiamp . PR has been raised to fix this issue.

https://github.com/Azure/Azure-Sentinel/pull/10836
