### ISSUE TITLE
Microsoft Graph Activity Logs - Suspicious TI-IP Address Detection 

### ISSUE THREAD

**Issue by ibztek** [Azure/Azure-Sentinel#10708]
I'm trying to correlate TI - IP with activities in Graph. Could that be a good detection ? or what is it a better way to protect activites in Microsoft Graph ?

**Comment by v-sudkharat** [comment]
Hi @ibztek, Thanks for flagging this issue, we will investigate this issue and get back to you with some updates by 09-07-2024. Thanks!

**Comment by v-sudkharat** [comment]
@ibztek, sharing a M.S doc that can help you to get answer to your question: - https://learn.microsoft.com/en-us/graph/security-partner-overview
Closing this issue from GitHub. If you still need support for this issue, kindly open a support ticket within Azure portal. so, our support team help you to check and investigate on issue. Thank you for your co-operation.
