### ISSUE TITLE
Detailed descriptions of values required for Microsoft Sentinel Cost Workbook (GBP)

### ISSUE THREAD

**Issue by chris-bristow-maersk** [Azure/Azure-Sentinel#10711]
As per :  Workbooks/MicrosoftSentinelCostGBP.json  (full path: https://github.com/Azure/Azure-Sentinel/blob/master/Workbooks/MicrosoftSentinelCostGBP.json)

There are a number of fields with parameters at the top of the workbook which are needed to be filled out to ensure the  (cost workbook accurately provides a cost for a Log Analytics/Sentinel deployment.
These fields need some detailed help behind them so the output costs are valid.

The fields which need help are:

- Sentinel Price - current help just says 'Enter a value for Sentinel Data cost, default: 4.38'. How is this value calculated?
- Commitment Tier Price - No help / description in the workbook
- Ingestion Price - 'Enter your ingestion price per GB (PAYG or Commitment Tier). You can also refer to Azure Pricing Calculator' Is this Ingestion into Sentinel or Log Analytics or both? 
How many days retention ? - Is this total retention or just Log Analytics retention. What if customer has Archive or Basic enabled or does this not matter? 
Retention price per GB - 'Obtain a value from the Azure Pricing Calculator, default: 0.10' Again more explanation as to how to calculate would be useful.
Total seats (E5/A5/F5/G5) - 'Enter the total number of Microsoft 365 E5, A5, F5, G5 and Microsoft 365 E5, A5, F5, G5 Security licenses in your environment' - Would be useful to know how to find this value, if this is in a MS portal somewhere for example.

If you Edit the Workbook, then an additional field is for 'discountRate' is seen, which is set to 50. Shouldn't this field be shown without having to Edit the workbook first? 

The workbook is really useful, and had some great details, but, without inserting the right values for the above, the total costs and costs per table will be completely wrong. 

For example, can you please add another tab to the workbook which has detailed description of how to enter the appropriate values so the costs are correct. 

Also - why is there only workbook in this format in GBP and EUR, and not one for USD, or is the USD one called something different? 

thanks

**Comment by v-sudkharat** [comment]
Hi @chris-bristow-maersk, Thanks for flagging this issue, we will investigate this issue and get back to you with some updates by 10-07-2024. Thanks!

**Comment by javiersoriano** [comment]
Hi @chris-bristow-maersk, I'm tagging @noodlemctwoodle who created this version of the workbook

Regards

**Comment by v-sudkharat** [comment]
Hi @chris-bristow-maersk, Thank you for being with us. The workbook was created and it is community supported by @noodlemctwoodle. We have attempted to reach out for a point of contact but have not received a response. Therefore, we are closing this issue on GitHub. If we receive any updates from the workbook author, we will inform you. Thank you!

**Comment by noodlemctwoodle** [comment]
I can pick up the issue next week. But I  have limited access to the
internet at the moment.

**Comment by v-sudkharat** [comment]
Thanks @noodlemctwoodle, for the update.

**Comment by noodlemctwoodle** [comment]
@chris-bristow-maersk - Thank you for your feedback. I will work on the updates you have provided and produce an updated version. 

There are some additional changes I have thought about since the initial commit that I would like to add too. 

Stay tuned.

**Comment by noodlemctwoodle** [comment]
just a quick update @chris-bristow-maersk 

I have updated the cost so that it is now automatically calculated based off the selection of the Azure Region and Currency. 
![image](https://github.com/user-attachments/assets/2ef4f84c-2ff7-4f26-823c-02b49a92175c)
![image](https://github.com/user-attachments/assets/599a909c-d8d5-476d-b7a3-0ab018268979)

This is across all ingestion types PAYG, Commitment Tiers, Basic Logs, Auxiliary Logs.

**Comment by noodlemctwoodle** [comment]
@chris-bristow-maersk  https://github.com/Azure/Azure-Sentinel/pull/11003
