### ISSUE TITLE
Sentinel_AMA_troubleshoot.py

### ISSUE THREAD

**Issue by bisskar** [Azure/Azure-Sentinel#10721]
**Describe the bug**
I have 1 linux forwarder, I am forwarding CEF and Syslog messages. to Sentinel. I have 2 DCRs, 1 for Syslog, 1 for CEF. I am filtering CEF from Syslog table on ingestion using Transformation Rule, works fine however I fail 1 check when running TB for syslog (Sentinel_AMA_troubleshoot.py), 

**To Reproduce**
```
sudo python3 Sentinel_AMA_troubleshoot.py --syslog
```
**Expected behavior**
No errors

**Screenshots**
![image (1)](https://github.com/Azure/Azure-Sentinel/assets/65374155/dff41a8c-f299-4be2-a57e-f1d61bea3c12)

**Desktop (please complete the following information):**
 - OS: Debian 11
 - AMA version: 1.31.1

**Additional context**
```
sudo python3 Sentinel_AMA_troubleshoot.py --cef
```
No errors.

Since I am using 2 DCRs, I suspect that once I run --syslog it also checks cef DCR and this is why I see an error. 

DCRs:

[SYSLOG.json](https://github.com/user-attachments/files/16021348/SYSLOG.json)
[CEF.json](https://github.com/user-attachments/files/16021350/CEF.json)

Sentinel_AMA_troubleshoot.py
https://raw.githubusercontent.com/Azure/Azure-Sentinel/master/DataConnectors/Syslog/Sentinel_AMA_troubleshoot.py

Logic:

```
def verify_dcr_has_valid_content(self, dcr_stream):
        """
        Verifying that the CEF DCR on the machine has valid content with all necessary DCR components
        """
        global STREAM_SCENARIO
        command_name = "verify_dcr_has_valid_content"
        command_to_run = "sudo grep -ri \"{}\" /etc/opt/microsoft/azuremonitoragent/config-cache/configchunks/".format(
            self.STREAM_NAME[dcr_stream])
        result_keywords_array = ["stream", "kind", "syslog", "dataSources", "configuration", "facilityNames",
                                 "logLevels", "SecurityInsights", "endpoint", "channels", "sendToChannels", "ods-",
                                 "opinsights.azure", "id"]
        command_object = CommandVerification(command_name, command_to_run, result_keywords_array)
        command_object.run_command(should_decode=False)
        command_object.command_result = command_object.command_result.decode('UTF-8').split('\n')[:-1]
        for dcr in command_object.command_result:
            dcr_path = re.search("(/etc/opt/microsoft/azuremonitoragent/config-cache/configchunks/.*.json)",
                                 str(dcr)).group()
            for key_word in command_object.result_keywords_array:
                if str(key_word) not in str(dcr):
                    command_object.is_command_successful(should_fail=True)
                    print_error(
                        "Found an invalid DCR. It is missing this key-word \'{}\'. It's path is {}".format(key_word,
                                                                                                           dcr_path))
                    return False
        command_object.run_full_verification()
```

**Comment by v-sudkharat** [comment]
Hi @bisskar, Thank you for bringing this connector issue to our attention. For a thorough investigation, we kindly request that you raise a support ticket through the Azure portal. This will enable our support team to check on it and assign it to the respective team. Should further information be needed, they will reach out to you directly.
We are closing this issue from GitHub. If you still need support for this issue, feel free to re-open it any time. Thank you for your co-operation.
