### ISSUE TITLE
Add Entity to existing Incident

### ISSUE THREAD

**Issue by FormindGMO** [Azure/Azure-Sentinel#10728]
**Is your feature request related to a problem? Please describe.**
When investigating an incident, we can find new items related to incident that can be useful to analyse.respond to/pivot against when new incidents will occur.

**Describe the solution you'd like**
* Having a buttun in Entities section of an incident to add new Entity, adding a right pane form asking for entity Type and associated entity
* Having also Logic App action to add it directly with automation.

**Describe alternatives you've considered**
Workaround : 
- Adding new alerts associated with hardcoded Entities and forced linked to this incident. Any ideas could be greatly appreciated.

**Additional context**
None.

**Comment by v-sudkharat** [comment]
Hey @FormindGMO, Could you please provide more details about the issue your facing, it would be great if you could attach screenshots as well. It helps us to investigate on it. Thanks!

**Comment by FormindGMO** [comment]
Hello! thanks for fast reply. It's not an issue but rather a feature request. Let's illustrate w/ an example.
Assuming an incident of a computer having a malware that was run on it. In this incident we can assume that we had FileHash entity pre-positioned, and targeted host.

Analyzing targeted host, we can see that malware reached Command&Control 1.2.3.4. I want to :
* Add for the record this new finding in Sentinel incident with new IP Entity
* Enabling this can maybe leverage other playbooks (like : IP blockage on Firewall)
* And if in the future, other incidents spawns having this IP as Entity, it's linked in Sentinel Investigation tab, which is very useful for historical analysis.

So my feature could be to manually (or *via* Logic Apps) add entity to Incidents.

**Comment by Kaloszer** [comment]
This is a similar requirement for the currently `in preview` create incident feature in sentinel.
What purpose is there to create an incident manually in sentinel where you can't assign entities to it.

During investigation you could also find assets gents that are not 'explicitly' bound by the analytic rule inside of the incident and best case we should be able to add that entity to the incident as it enriches the incident with that particular asset and are relevant to the case.

Similarly as @FormindGMO mentions, this can be utilized alongside existing playbooks that utilize said entities for actions such as:
- bulk reset MFA
- reset auth
- block IP
- block user
- add entities to known threat actors/ add ips to known threat actors

The feature should allow a user within the tenant to at the least - assign entities from the tenant incident is in.

**Comment by v-sudkharat** [comment]
Thanks @FormindGMO / @Kaloszer, sharing information with us, we have reach out to concern team for this issue, Once we get any info from team, will update you.

**Comment by blauwers** [comment]
+1

**Comment by v-sudkharat** [comment]
Hi @FormindGMO, We have received a response from the concerned team. The Sentinel entities linking to an existing incident is not yet supported in the portal. And team has noted down this feature request into their queue, However, Sentinel allows adding entities to an existing incident using the bookmarks feature. For more information, please refer to the following document: https://learn.microsoft.com/en-us/azure/sentinel/bookmarks 
So, closing this issue from GitHub. If you still need support for this issue, feel free to re-open it any time. Thank you for your co-operation.

**Comment by aommm** [comment]
@v-sudkharat , I'm looking to programmatically adding entities to an incident.
Is it possible to add a bookmark to an incident via API?

I've tried the [Bookmarks - Create or Update](https://learn.microsoft.com/en-us/rest/api/securityinsights/bookmarks/create-or-update) endpoint with providing `{"incidentInfo":{"incidentId":"my-incident-id"}}` but it doesn't seem to take effect.
