### ISSUE TITLE
Impossible to install Microsoft Defender for Cloud connector

### ISSUE THREAD

**Issue by kristofdepauw** [Azure/Azure-Sentinel#10737]
**Describe the bug**
Defender for cloud tenantwide connector not found.

Same issue as "Impossible to install Microsoft Defender for Cloud connector #10306" but for 3.0.2 version of solution.

**Comment by v-sudkharat** [comment]
Hey @kristofdepauw, Could you please share the error screenshot with us. And you can also check the connector after reinstalling the solution again.

**Comment by kristofdepauw** [comment]
![image](https://github.com/Azure/Azure-Sentinel/assets/37872919/1bd534ef-1235-40f7-9d32-c0baf78ab537)
![image](https://github.com/Azure/Azure-Sentinel/assets/37872919/1927d1c7-6919-42fb-9e3b-34e0e178676c)

**Comment by v-sudkharat** [comment]
@kristofdepauw, Could you please delete the exiting solution and reinstall into the same workspace, If after reinstalling you're getting same issue, will connect over call and check into it. 
Please share your mail ID with us, so we can connect over call. Thanks!

**Comment by v-sudkharat** [comment]
@kristofdepauw, You can share mail id on in comment itself or mail us on - v-sudkharat@microsoft.com

**Comment by kristofdepauw** [comment]
Hello, I've sent my email id in a separate email. Can you contact me there?

**Comment by kristofdepauw** [comment]
resolved. Thank you.
