### ISSUE TITLE
Enlarge comment input section

### ISSUE THREAD

**Issue by FormindGMO** [Azure/Azure-Sentinel#10733]
**Is your feature request related to a problem? Please describe.**
When big comments (like reports) are input to an incident with "Activity Log" right pane, input window can't be enlarged to see whole lines. 
![image](https://github.com/Azure/Azure-Sentinel/assets/79926595/8328b252-f8d9-4025-a675-ea0e632b7857)

**Describe the solution you'd like**
Adding resize button at the bottom right of the input textbox or a vertical-slidable hrule between input and comment history to enlarge the textbox

**Describe alternatives you've considered**
Workaround is at the moment to copy-paste from notepad, which is unconvenient.

**Additional context**
We use comment section to post analyst reports of the incident for the record. It contains all enrichments, identified risks/assets and so on

**Comment by v-sudkharat** [comment]
Hi @FormindGMO, Thanks for flagging this issue, we will investigate this issue and get back to you with some updates by 11-07-2024. Thanks!

**Comment by v-sudkharat** [comment]
Hi @FormindGMO, We have checked this issue, this issue needs to be investigated by concern team, so we kindly request you to raise a support ticket case in azure portal, so our support team can check into it and connect with you if required.
Please let us know once you raise a ticket, so we can close this issue from GitHub. Thanks!

**Comment by FormindGMO** [comment]
Hello @v-sudkharat, thanks for reply. This is not an issue, it's a feature request. Calling for Support will lead me to bugtracking and (not) fixing elements, which is not what was intended in this feature request.
Ticket is raised anyways...

**Comment by v-sudkharat** [comment]
@FormindGMO, thanks for raising a ticket. With the help of support team this feature request can be assign/forward to respective team. Closing this issue from GitHub. If you still need support for this issue, feel free to re-open it any time. Thank you for your co-operation.
