### ISSUE TITLE
Undefined Tenant ID with the GCP Audit Log Data Connector

### ISSUE THREAD

**Issue by fa-clavis** [Azure/Azure-Sentinel#10756]
**Describe the bug**
Hello team,

I've been trying to connect my lab environment and a client's Sentinel environment GCP Accounts, but it doesn't work.

Even though it shows “undefined”, I tried to run and execute with my tenant ID and workspace ID, but regardless, it doesn't work and possibly because of this error on the Data Connector side.

I tried to delete and reinstall the data connector many times, but it continues to populate “undefined”.

I need to follow with this data connector because of the sink capability where I can send all the audit logs of my client from many projects into Sentinel, similar how it's done with the “Amazon Web Services S3” data connector.

**To Reproduce**

1. Install the “Google Cloud Platform Audit Logs” Data Connector.

**Expected behavior**

I know what is my Tenant ID but within the data connector, it should populate my “Tenant ID” and not “undefined”.

**Screenshots**

![Screenshot 2024-07-09 at 10 57 38](https://github.com/Azure/Azure-Sentinel/assets/166556029/56052bc6-2d43-4a58-b989-c7f645ee1cbc)

![Screenshot 2024-07-09 at 11 00 32](https://github.com/Azure/Azure-Sentinel/assets/166556029/5479dc44-1397-48a0-89e7-ee2d52bf08ab)

**Desktop (please complete the following information):**
 - OS: Mac
 - Browser: Chrome
 - Version: 126.0.6478.115

**Comment by v-sudkharat** [comment]
Hi @fa-clavis, Thanks for flagging this issue, we will investigate this issue and get back to you with some updates by 18-07-2024. Thanks!

**Comment by fa-clavis** [comment]
> Hi @fa-clavis, Thanks for flagging this issue, we will investigate this issue and get back to you with some updates by 18-07-2024. Thanks!

Alright, sounds good.

Thanks!

**Comment by v-sudkharat** [comment]
Hi @fa-clavis The issue has been fixed by concern team, and we are checking with team for release. We will notify you once we get any update/ETA from them. Thanks!

**Comment by fa-clavis** [comment]
Hello team, any feedback?

**Comment by v-sudkharat** [comment]
Hi @fa-clavis, We are following with team and waiting for response about the deployment, once we get any info, will update you. Thanks!

**Comment by v-sudkharat** [comment]
Hey @fa-clavis, Could you please reinstall solution once and check for the tenant ID value :-
![image](https://github.com/user-attachments/assets/dc6d798c-fdd9-4f3b-bd6a-2bb8f119339d)

Thanks!

**Comment by v-sudkharat** [comment]
@fa-clavis, Waiting for your response. Thanks!

**Comment by v-sudkharat** [comment]
Hi @fa-clavis, Gentle Reminder: We are waiting for your response on this issue. If you still need to keep this issue active, please respond to it in the next 2 days. If we don't receive a response by 07-08-2024 date, we will be closing this issue. 		
Thanks!

**Comment by fa-clavis** [comment]
@v-sudkharat Great, I'm gonna test it on the client and I'll return with the results!

**Comment by v-sudkharat** [comment]
@fa-clavis, Sure. Please check and let us know, so we can close this ticket from GitHub. Thanks!

**Comment by v-sudkharat** [comment]
Hey @fa-clavis, Did you get a chance to test connector. Thanks!

**Comment by fa-clavis** [comment]
Hello @v-sudkharat, sorry for the delay but I still haven't had a chance to meet up with them, their agenda has been really tight this week.

**Comment by fa-clavis** [comment]
Hello @v-sudkharat, I have now installed the updated version of the data connector and it's showing the Tenant ID correctly.
Thanks for the support!
