### ISSUE TITLE
Umbrella Data Connector Filtering

### ISSUE THREAD

**Issue by jackbaz** [Azure/Azure-Sentinel#10760]
Hello,

Is there any documented way for Cisco Umbrella Data connector through Azure Functions to only ingest to Sentinel when a block event occurred rather than everything?

Context is we really only want to see blocked events due to Umbrella's classification, not every single request.

Thanks

**Comment by v-sudkharat** [comment]
Hi @jackbaz, Thanks for flagging this issue, we will investigate this issue and get back to you with some updates by 17-07-2024. Thanks!

**Comment by v-sudkharat** [comment]
@jackbaz, are you looking for this one -https://docs.umbrella.com/umbrella-user-guide/docs/view-an-events-details 
Thanks!

**Comment by jackbaz** [comment]
Sorry I dont understand what you mean?

As Umbrella outputs all events to an s3 bucket, I just want to know if we have the ability to filter these events to Sentinel based on the action, not ingest the entire event

**Comment by v-sudkharat** [comment]
Hey @jackbaz, currently we don't have the ingestion filter doc with us, but the ingested logs can be filtered by using Kusto. For more information about query's, you can check for [Query samples](https://learn.microsoft.com/en-us/azure/sentinel/data-connectors/cisco-umbrella-using-azure-functions#query-samples) and [Kusto Query Language.](https://github.com/microsoft/Kusto-Query-Language#kusto-query-language) added into our M.S documentation. 
Thanks!

**Comment by v-sudkharat** [comment]
Hey @jackbaz, Hope we answered your question. So, closing this issue. If you still need support for this issue, feel free to re-open it any time. Thank you for your co-operation.
