### ISSUE TITLE
Excessive results when querying AzureActivity table

### ISSUE THREAD

**Issue by lomgba** [Azure/Azure-Sentinel#10766]
**Describe the bug**
The query returns several identical lines with the same information (05 lines exactly). This disrupts analysis because it seems that it concerns several rules which would have been deleted, whereas it is just one.

**To Reproduce**
Query to reproduce the behavior:

AzureActivity
| where OperationNameValue contains "Microsoft.SecurityInsights/Automationrules/delete"
| extend Resource = tostring(parse_json(Properties).resource)

![img](https://github.com/Azure/Azure-Sentinel/assets/13540681/47c861f0-0be6-4572-85a6-9b77b9834800)

**Expected behavior**
For my use case, I must have one or two lines (results) with ActivityStatusValue equal to “Success” and “start”. Instead of Five same lines with ActivityStatusValue equal to “Success”, and five others Five same lines with ActivityStatusValue equal to “Start”. All with the same informations

**Comment by v-sudkharat** [comment]
Hi @lomgba, Unable to replicate this issue, could you please raise a support case in azure portal, so our support team can check into it and well assign this to respective team for duplication results. 
Kindly let us know once you open the ticket, so we can close this issue.
Thanks!

**Comment by v-sudkharat** [comment]
@lomgba, Waiting for your response on above comment. Thanks!

**Comment by v-sudkharat** [comment]
Hi @lomgba, Gentle Reminder: We are waiting for your response on this issue. If you still need to keep this issue active, please respond to it in the next 2 days. If we don't receive a response by 22-07-2024 date, we will be closing this issue. 		
Thanks!

**Comment by v-sudkharat** [comment]
Hi @lomgba, since we have not received a response in the last 5 days, we are closing your issue as per our standard operating procedures. If you still need support for this issue, feel free to re-open at any time. Thank you for your co-operation.
