### ISSUE TITLE
ENTRA

### ISSUE THREAD

**Issue by smp73** [Azure/Azure-Sentinel#10773]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by v-sudkharat** [comment]
@smp73, Closing this issue as incomplete details provided.

**Comment by smp73** [comment]
12bc6cdb375f9688ba2eff535c36b26dbbaff710

**Comment by smp73** [comment]
12bc6cdb375f9688ba2eff535c36b26dbbaff710
