### ISSUE TITLE
Microsoft Exchange Logs and Events errors when deploying MessageTrackingLog and ExchangeHttpProxy collectors

### ISSUE THREAD

**Issue by micholczyk** [Azure/Azure-Sentinel#10789]
**Describe the bug**
When configuring Microsoft Exchange Logs and Events connector steps regarding _[Option 6] Message Tracking of Exchange Servers_ and _[Option 7] HTTP Proxy of Exchange Servers_ manual deployment fail with errors:
Update Error - Error occurred while compiling query in query: SemanticError:0x00000006 at 1:43 : Undefined symbol: date-time
Update Error - Error occurred while compiling query in query: SemanticError:0x00000006 at 1:43 : Undefined symbol: DateTime

**To Reproduce**
1. Go to Microsoft Sentinel -> Data connectors -> Microsoft Exchange Logs and Events.
2. Scroll down to Configuration -> 2. Deploy log injestion following choosed options -> [Option 6] Message Tracking of Exchange Servers -> Option 2 - Manual Deployment of Azure Automation and follow the instructions there.
3. The error happens in step 4. of _C. Modify the created DCR, Type Custom log_ when configuring a Data Source of Custom Text logs type with the provided KQL.
4. The same applies to [Option 7] HTTP Proxy of Exchange Servers.

**Expected behavior**
The connector should start collecting logs.

**Screenshots**
_[Option 6] Message Tracking of Exchange Servers_
First error shows up after uploading the example file (expected?).
![image](https://github.com/user-attachments/assets/b75ad5a3-d180-4ac8-aca0-a14541aaf24b)
After transformation there is no error.
![image](https://github.com/user-attachments/assets/9c3dd984-8b3f-4b43-8734-498142624f5f)
After performing the steps in _C. Modify the created DCR, Type Custom log_ there is the following error.
![image](https://github.com/user-attachments/assets/b1037429-2d5a-4e99-8d33-82125002c722)
After page refresh the Data sources are gone.
![image](https://github.com/user-attachments/assets/825f56d4-9a30-4fd7-a5bd-67368a778202)

_[Option 7] HTTP Proxy of Exchange Servers_
Again - first error shows up after uploading the example file. Probably expected.
![image](https://github.com/user-attachments/assets/23128fff-6606-4b0c-8a12-34543dcbccdb)
Transformation seems ok.
![image](https://github.com/user-attachments/assets/223b404f-5a25-4eae-84ba-9736d1c7362d)
In step _C. Modify the created DCR, Type Custom log_ same exact error appears.
![image](https://github.com/user-attachments/assets/ed11a9c3-10ca-41ad-bc01-b08e2ff8aef9)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Edge
 - Version: 126.0.2592.87

If I'm doing something wrong, or not understanding something correctly, I'd be glad for your advice. :) Thanks!

**Comment by v-sudkharat** [comment]
Hi @micholczyk, Thanks for flagging this issue, we will investigate this issue and get back to you with some updates by 25-07-2024. Thanks!

**Comment by v-sudkharat** [comment]
Hi @micholczyk, Sorry for delay in response, we need some more time to investigate this issue from our end. Thanks!

**Comment by v-sudkharat** [comment]
Adding, @v-prasadboke

**Comment by matt-traynor** [comment]
@v-prasadboke @v-sudkharat are there any updates on this issue please?

**Comment by saahilverma** [comment]
@v-prasadboke @v-rusraut @v-sudkharat Can we get update on this... Seems like lot of people stuck at transform.

**Comment by nlepagnez** [comment]
Hi, 
There was a bug in how we proposed to implement the DCR manually since "Custom Logs" DCR was out of preview. 
A Pull Request is ongoing #11049

**Comment by v-sudkharat** [comment]
@saahilverma, The PR still is in review state, once it gets merge, the changes will get updated into upcoming solution version. Thanks!
