### ISSUE TITLE
Block-AADUser - Playbook issue

### ISSUE THREAD

**Issue by sunilkhuttan** [Azure/Azure-Sentinel#1079]
"Block-AADUser playbook issue"
I have deployed this playbook to my sentinel instance and triggered it using an analytics rule. The Playbook triggers but there is an action "Alert - Get Account" in Playbook the should return the accounts related to the alert. This action does not return any value. Could you please advise if this is an issue? Is there a solution 

<img width="621" alt="Sentinel-Playbook-Issue" src="https://user-images.githubusercontent.com/12437274/93163327-36feb180-f75a-11ea-942c-13f9dd0af85a.PNG">

**Comment by samikroy** [comment]
@sunilkhuttan - Could you please share the analytics rule and a sample response of the incidents with entity mapping raised by the analytics !

**Comment by sarah-yo** [comment]
@sunilkhuttan per the comment above, please can you share the analytics rule and associated entities, etc.

**Comment by sarah-yo** [comment]
Closing due to lack of response
