### ISSUE TITLE
VMware ESXi AMA migration

### ISSUE THREAD

**Issue by thom2804** [Azure/Azure-Sentinel#10791]
Good day, As you probably know soon in August the Log Analytics agent is being deprecated and will no longer receive support.
Sadly, so far the VMware ESXi data connector has not yet been migrated to the AMA agent, and it doesn't look like it will be receiving this anytime soon.
I currently have an environment which makes use out of the connector and I would like to finish migrating everything to the AMA agent, however the ESXi connector is the only one holding me back now.

I am wondering if there is someone here who has successfully performed this and can give me some more information about.

**Comment by v-sudkharat** [comment]
Hey @thom2804, Thank you for flagging this issue. 
We have forwarded this request to our team and the AMA migration for the connector is currently into their queue. This will get it by end of this month. 
So, closing this issue from GitHub. If you still need support for this issue, feel free to re-open it any time. Thank you for your co-operation. 
Thanks!
