### ISSUE TITLE
RDP Nesting analytic rule miss reporting

### ISSUE THREAD

**Issue by MikeP324** [Azure/Azure-Sentinel#10831]
**Describe the bug**
The analytic rule 'RDP Nesting' (https://github.com/Azure/Azure-Sentinel/blob/master/Detections/SecurityEvent/RDP_Nesting.yaml) has been written to detect an RDP connection from Server A to Server B from a source system using RDP. The problem is the SecurityEvent table provides the IP address of the source making the RDP connection and the hostname for the destination. Without a conversion of destination hostname to IP address you cannot see the connection attempt.

What you will get instead is any alerts where a user source system making an RDP connection is not the same within the set period of 60 mins.

An example could be RDP connection to Server A from a laptop / Desktop then making an RDP connection using Azure Bastion within the timeframe.

**To Reproduce**
1. RDP from Client 1 to Server 1.
2. RDP from Client 2 to Server 2 using the same account used in step 1.

**Expected behavior**
The expectation is to generate an alert when the connection Client 1 -> Server 1 -> Server 2 is made.

**Additional context**
Using template version 1.2.6.

**Comment by v-sudkharat** [comment]
Hi @MikeP324, Could you please share more details about the issue, if possible, kindly provide screenshots as well, so it would be helpful for check into it. 
Thanks!

**Comment by MikeP324** [comment]
Hi @v-sudkharat, is it possible to have a private conversation about the requested information?

**Comment by v-sudkharat** [comment]
Hey @MikeP324, yes, but It would be great if you could provide issue description and expected behavior over comment itself, so if required we can share this issue with our respective concern team with details. Thanks!

**Comment by MikeP324** [comment]
Hi @v-sudkharat,

Sure, here's what I know.

The objective of the analytic rule is to detect a nested RDP session using data from the SecurityEvent or WindowsEvent tables. The table data reports the IP address of the making a successful logon (Event id 4624) as LogonType 10 - RemoteInteractive to the target system in FQDN format. 

At no point does the table data have the IP address of the target device, without the IP address translation from the target  system FQDN where the logon is taking place you cannot make a match to detect a nested connection.

**Comment by v-sudkharat** [comment]
Thanks @MikeP324, for sharing expected behavior with us, will check on this rule and will update you. Thanks!

**Comment by MikeP324** [comment]
@v-sudkharat Maybe these changes coming into Defender AH will help with this issue - https://techcommunity.microsoft.com/t5/microsoft-defender-for-endpoint/detect-compromised-rdp-sessions-with-microsoft-defender-for/ba-p/4201003

**Comment by MikeP324** [comment]
Would like to point two other analytic rules which use similar host-based type of detections.

Rare RDP Connection - https://github.com/Azure/Azure-Sentinel/blob/master/Detections/SecurityEvent/RDP_RareConnection.yaml

Multiple RDP Connections from single system - https://github.com/Azure/Azure-Sentinel/blob/master/Detections/SecurityEvent/RDP_MultipleConnectionsFromSingleSystem.yaml

**Comment by v-sudkharat** [comment]
Hi @MikeP324, Could you please test the below updated query into your environment and share the result with us :- 
File Here-  [Query.txt](https://github.com/user-attachments/files/16655887/Query.txt)

Thanks!

**Comment by MikeP324** [comment]
Hi @v-sudkharat,

Ran the query as requested and got zero results. Also tested opening the timeframe from 8d to 30d and lowered the threshold to 0 to see if I could get any results but still nothing which is great.

Using the old rule I had 132 RDP Nesting rules in the past 30 days.

**Comment by MikeP324** [comment]
@v-sudkharat - Reviewing the rdpConnectionS let function and I think it still have the original error embedded.

        on Account
    // Ensure the first connection is before the second connection
    // Identify only RDP to another computer from within the first RDP connection by only choosing matches where the Computer names do not match
    // Ensure the IPAddresses do not match by excluding connections from the same computers with first hop RDP connections to multiple computers
    | where FirstComputer != SecondComputer
        and FirstIPAddress != SecondIPAddress
        and SecondHop > FirstHop

I think you need to move your resolve logic inside the function.

**Comment by MikeP324** [comment]
@v-sudkharat Thank-you for the update.

I was just starting work on a possible MDE related query but it would only work in Defender as several of the fields are missing in Sentinel.

Here's the untested KQL in case anyone is interested.

(DeviceNetworkEvents 
| where IsInitiatingProcessRemoteSession == "True" and ActionType has "ConnectionSuccess"
| where RemotePort == "389"
| project FirstHop = Timestamp, FirstDeviceName=DeviceName, FirstLocalIP=LocalIP, FirstRemoteURL=RemoteUrl, FirstRemoteIP=RemoteIP, Account=InitiatingProcessAccountName, AccountUPN=InitiatingProcessAccountUpn, FirstRemoteSessionDeviceName=InitiatingProcessRemoteSessionDeviceName, FirstRemoteSessionIP=InitiatingProcessRemoteSessionIP
)
| join kind=inner ( 
DeviceNetworkEvents 
| where IsInitiatingProcessRemoteSession == "True" and ActionType has "ConnectionSuccess"
| where RemotePort == "389"
| project SecondHop = Timestamp, SecondDeviceName=DeviceName, SecondLocalIP=LocalIP, SecondRemoteURL=RemoteUrl, SecondRemoteIP=RemoteIP, Account=InitiatingProcessAccountName, AccountUPN=InitiatingProcessAccountUpn, SecondRemoteSessionDeviceName=InitiatingProcessRemoteSessionDeviceName, SecondRemoteSessionIP=InitiatingProcessRemoteSessionIP
) on Account
| where FirstRemoteSessionDeviceName != SecondRemoteSessionDeviceName
| project-reorder Account, AccountUPN, FirstHop, SecondHop, FirstRemoteSessionDeviceName, FirstRemoteSessionIP, FirstDeviceName, FirstLocalIP, SecondRemoteSessionDeviceName, SecondRemoteSessionIP, SecondDeviceName, SecondLocalIP 
| project-away Account1, AccountUPN1
| where SecondRemoteSessionDeviceName has FirstDeviceName and SecondHop > FirstHop
| where SecondHop <= FirstHop+30m

Also logged issue #11034 for the missing fields in Sentinel.

**Comment by MikeP324** [comment]
Just looked at the yaml file you propose to update, may I ask if you can add additional fields to the entity mappings like the account, hostnames please?

**Comment by MikeP324** [comment]
This issue needs to be reopened, we have tried to implement the code and its triggering.

The code is overly complex for just attempting to detect RDP nesting so I have tried to modify code but I'm no expert so it needs a PR.

 let endtime = 1d;
  // Function to resolve hostname to IP address using DNS logs or a lookup table (example syntax)
  let rdpConnections = 
      (union isfuzzy=true
          (
          SecurityEvent
          | where TimeGenerated >= ago(endtime)
          | where EventID == 4624 and LogonType == 10
          // Labeling the first RDP connection time, computer and ip
          | extend
              FirstHop = bin(TimeGenerated, 1m),
              FirstComputer = toupper(Computer),
              FirstRemoteIPAddress = IpAddress,
              Account = tolower(Account)
          ),
          (
          WindowsEvent
          | where TimeGenerated >= ago(endtime)
          | where EventID == 4624 and EventData has ("10")
          | extend LogonType = tostring(EventData.LogonType)
          | where LogonType == 10 // Labeling the first RDP connection time, computer and ip
          | extend Account = strcat(tostring(EventData.TargetDomainName), "\\", tostring(EventData.TargetUserName))
          | extend IpAddress = tostring(EventData.IpAddress)
          | extend
              FirstHop = bin(TimeGenerated, 1m),
              FirstComputer = toupper(Computer),
              FirstRemoteIPAddress = IpAddress,
              Account = tolower(Account)
          ))
      | join kind=inner (
          (union isfuzzy=true
              (
              SecurityEvent
              | where TimeGenerated >= ago(endtime)
              | where EventID == 4624 and LogonType == 10
              // Labeling the second RDP connection time, computer and ip
              | extend
                  SecondHop = bin(TimeGenerated, 1m),
                  SecondComputer = toupper(Computer),
                  SecondRemoteIPAddress = IpAddress,
                  Account = tolower(Account)
              ),
              (
              WindowsEvent
              | where TimeGenerated >= ago(endtime)
              | where EventID == 4624 and EventData has ("10")
              | extend LogonType = toint(EventData.LogonType)
              | where LogonType == 10 // Labeling the second RDP connection time, computer and ip
              | extend Account = strcat(tostring(EventData.TargetDomainName), "\\", tostring(EventData.TargetUserName))
              | extend IpAddress = tostring(EventData.IpAddress)
              | extend
                  SecondHop = bin(TimeGenerated, 1m),
                  SecondComputer = toupper(Computer),
                  SecondRemoteIPAddress = IpAddress,
                  Account = tolower(Account)
              ))
          )
          on Account
      | distinct
          Account,
          FirstHop,
          FirstComputer,
          FirstRemoteIPAddress,
          SecondHop,
          SecondComputer,
          SecondRemoteIPAddress,
          AccountType,
          Activity,
          LogonTypeName,
          ProcessName;        
  // Resolve hostnames to IP addresses device network Ip's
  let listOfFirstComputer = rdpConnections | distinct FirstComputer;
  let listOfSecondComputer = rdpConnections | distinct SecondComputer;
  let resolvedIPs =  
      DeviceNetworkInfo
      | where TimeGenerated >= ago(endtime)
      | where isnotempty(ConnectedNetworks) and NetworkAdapterStatus == "Up"
      | extend ClientIP = tostring(parse_json(IPAddresses[0]).IPAddress)
      | where isnotempty(ClientIP)
      | where DeviceName in~  (listOfFirstComputer) or DeviceName in~ (listOfSecondComputer)
      | summarize arg_max(TimeGenerated, ClientIP) by Computer= DeviceName
      | project Computer=toupper(Computer), ResolvedIP = ClientIP;
  // Join resolved IPs with the RDP connections
  rdpConnections
  | join kind=inner (resolvedIPs) on $left.FirstComputer == $right.Computer
  | join kind=inner (resolvedIPs) on $left.SecondComputer == $right.Computer
 // | where ResolvedIP != ResolvedIP1
  | distinct
      Account,
      FirstHop,
      FirstComputer,
      FirstComputerIP = ResolvedIP,
      FirstRemoteIPAddress,
      SecondHop,
      SecondComputer,
      SecondComputerIP = ResolvedIP1,
      SecondRemoteIPAddress,
      AccountType,
      Activity,
      LogonTypeName,
      ProcessName
// Ensure the first connection is before the second connection
      // Identify only RDP to another computer from within the first RDP connection by only choosing matches where the Computer names do not match
      // Ensure the IPAddresses do not match by excluding connections from the same computers with first hop RDP connections to multiple computers
      | where FirstComputer != SecondComputer
          and FirstRemoteIPAddress != SecondRemoteIPAddress
          and SecondHop > FirstHop
      // Ensure the second hop occurs within 30 minutes of the first hop
  | where SecondHop <= FirstHop + 30m
  | where SecondRemoteIPAddress == FirstComputerIP
  | summarize FirstHopFirstSeen = min(FirstHop), FirstHopLastSeen = max(FirstHop)
      by
      Account,
      FirstComputer,
      FirstComputerIP,
      FirstRemoteIPAddress,
      SecondHop,
      SecondComputer,
      SecondComputerIP,
      SecondRemoteIPAddress,
      AccountType,
      Activity,
      LogonTypeName,
      ProcessName
  | extend
      AccountName = tostring(split(Account, @"\")[1]),
      AccountNTDomain = tostring(split(Account, @"\")[0])
  | extend
      HostName1 = tostring(split(FirstComputer, ".")[0]),
      DomainIndex = toint(indexof(FirstComputer, '.'))
  | extend HostNameDomain1 = iff(DomainIndex != -1, substring(FirstComputer, DomainIndex + 1), FirstComputer)
  | extend
      HostName2 = tostring(split(SecondComputer, ".")[0]),
      DomainIndex = toint(indexof(SecondComputer, '.'))
  | extend HostNameDomain2 = iff(DomainIndex != -1, substring(SecondComputer, DomainIndex + 1), SecondComputer)
  | project-away DomainIndex

Would like to point out that the IP address information recorded in the table records is the remote IP address of the device making the connection and not the system (Computer). Remember its the system IP address we need to find to allow the match to take place.

Would also look to point out that the query period only needs to be 1 day if you are executing this on frequency of one day.

**Comment by MikeP324** [comment]
@v-sudkharat Forgot to tag you in my last update.
