### ISSUE TITLE
Ubiquiti UniFi AMA migration

### ISSUE THREAD

**Issue by thom2804** [Azure/Azure-Sentinel#10838]
Currently, the Ubiquiti Unifi (using Azure Functions) data connector is still dependent on the legacy Log Analytics agent, with no updates yet to support the new Azure Monitor Agent.
I would like to know if there is someone here who has been able to find a workaround for this to perform the migration to AMA for this connector, since the Legacy agent is being deprecated soon.

**Comment by v-sudkharat** [comment]
Hey @thom2804, Thank you for flagging this issue. 
We have forwarded this request to our team and the AMA migration for the connector is currently into their queue. This will get it by end of this month. 
So, closing this issue from GitHub. If you still need support for this issue, feel free to re-open it any time. Thank you for your co-operation. 
Thanks!

**Comment by thom2804** [comment]
I see that the connector is updated now to the new AMA connector but I am however not receiving any logs through this yet in my environments for Ubiquiti Unifi.
I noticed that the configuration page when opening the dataconnector is still the old description referencing the OMS agent and not the new AMA agent, these steps also dont seem to work for AMA.
Can you look into this and update the configuration steps needed for the AMA connector to work?
