### ISSUE TITLE
Entra ID Protection Solution v3.0.0 not updated with latest analytic rule 'Correlate Unfamiliar sign-in properties & atypical travel alerts' version 1.0.8

### ISSUE THREAD

**Issue by MikeP324** [Azure/Azure-Sentinel#10847]
**Describe the bug**
The Entra ID Protection Solution v3.0.0 has not been updated to v3.0.1 following an update to the analytic rule - Solutions/Microsoft Entra ID Protection/Analytic Rules/CorrelateIPC_Unfamiliar-Atypical.yaml three months ago.

**To Reproduce**
1. Go to Solutions/Microsoft Entra ID Protection/Analytic Rules and note the file CorrelateIPC_Unfamiliar-Atypical.yaml has a template version of 1.0.8.
2. Install the solution Entra ID Protection and check out the template version of 'Correlate Unfamiliar sign-in properties & atypical travel alerts' which is listed as version 1.0.6.

**Expected behavior**
Solution package should of been updated to version 3.0.1 and template version 1.0.8 for 'Correlate Unfamiliar sign-in properties & atypical travel alerts' be available.

**Comment by v-sudkharat** [comment]
Hi @MikeP324, Thanks for flagging this issue, we will investigate this issue and get back to you with some updates by 27-07-2024 . Thanks!

**Comment by v-sudkharat** [comment]
Hey @MikeP324, Thank you for highlighting this issue, we have created the PR with the fix and the change will get updated in upcoming solution version. Thanks!
