### ISSUE TITLE
Request additional entity information for Password spray attack against Microsoft Entra ID application

### ISSUE THREAD

**Issue by MikeP324** [Azure/Azure-Sentinel#10877]
**Is your feature request related to a problem? Please describe.**
Request the analytic rule "Password spray attack against Microsoft Entra ID application" in the solution 'Microsoft Entra ID' be updated with additional entity information other that just IP address.

https://github.com/Azure/Azure-Sentinel/blob/master/Solutions/Microsoft%20Entra%20ID/Analytic%20Rules/SigninPasswordSpray.yaml

**Describe the solution you'd like**
Would like to see the following entity information reported.

- User UPN
- Cloud Client App Name

**Comment by v-sudkharat** [comment]
Hi @MikeP324, Thank you for reporting this feature request with us. We have noted this feature request in our queue and will check on it. If required, we will also share this with our respective concern team. Currently we can't provide any ETA for this. but once we get any further info from our team will share update to you. So, closing this issue from GitHub. If you still need support for this issue, feel free to re-open it any time. Thank you for your co-operation.
