### ISSUE TITLE
Function App for getting Office 365 Management API data - Audit.AzureActiveDirectory

### ISSUE THREAD

**Issue by vanessabruwer** [Azure/Azure-Sentinel#10875]
In the  readme.md file for the Function App for getting Office 365 Management API data - https://github.com/Azure/Azure-Sentinel/tree/master/DataConnectors/O365%20Data - there is reference to the Audit.AzureActiveDirectory logs being ingested by the M365 data connector. This is not correct - this should reference the EntraID data connector instead.

Additionally, this page should be updated to reference the M365 connector instead of O365 connector.

**Comment by v-sudkharat** [comment]
Hi @vanessabruwer, Thanks for flagging this issue, we will investigate this issue and will raise a PR with the fix. Thanks!

**Comment by vanessabruwer** [comment]
The reference to the Audit.AzureActiveDirectory still reads as supported by default O365 connector in the updated readme.
