### ISSUE TITLE
MultipleErrorsReportedForSameDNSQueryStaticThresholdBased.yaml - Alert description invalid starting in version 1.3

### ISSUE THREAD

**Issue by Bievens** [Azure/Azure-Sentinel#10881]
Starting in version 1.3 deployment will result in a validation error

"Column names IPCountthreshold,TotalIPs,SrcIPs do not exist. Please check the query results and try again"

This is due to the addition of the summarization operator that was added on line 38.

**Comment by Bievens** [comment]
commit d431963 introduced the issue.

**Comment by v-sudkharat** [comment]
Hi @Bievens, Thanks for flagging this issue, we will investigate this issue and get back to you with some updates by 15-08-2024. Thanks!

**Comment by v-sudkharat** [comment]
Hi @Bievens, Could you please check with the below shared query and let us know your issue gets resolved : 
```
let lookback=1h;
let threshold = 2;
let errors = dynamic(['NXDOMAIN', 'SERVFAIL', 'REFUSED']); 
_Im_Dns(starttime=ago(lookback)) 
  | where EventResultDetails has_any (errors) 
  | summarize SrcIPs = make_set(SrcIpAddr, 100), Dvcs = make_set(Dvc, 100), ResourceIds = make_set(_ResourceId, 100) by DnsQuery, bin(TimeGenerated, 10min) 
  | where array_length(SrcIPs) >= threshold 
  | extend TotalIPs = array_length(SrcIPs),IPCountthreshold = threshold 
  | extend DomainName = strcat(split(DnsQuery, ".")[1], ".", split(DnsQuery, ".")[2])  
  | mv-expand SrcIPs  
  | extend SrcIP = tostring(SrcIPs)  
  | mv-expand Dvcs  
  | extend Dvc = tostring(Dvcs)  
  | mv-expand ResourceIds  
  | extend ResourceId = tostring(ResourceIds)  
  | extend Dvc = strcat(split(Dvc, ".")[0])
  | summarize Start=min(TimeGenerated), End=max(TimeGenerated), IPCountthreshold = make_set(IPCountthreshold), TotalIPs = make_set(TotalIPs), SrcIPs=make_set(SrcIP) by SrcIP, Dvc, ResourceId, DnsQuery, DomainName
  | extend HostName = tostring(split(Dvc, ".")[0]), DomainIndex = toint(indexof(Dvc, '.'))
  | extend HostNameDomain = iff(DomainIndex != -1, substring(Dvc, DomainIndex + 1), Dvc)

```

Or you can also do the solution custom deployment using below steps:-
Custom Deployment - [CustomDeploymentSteps.docx](https://github.com/user-attachments/files/16782483/CustomDeploymentSteps.docx)
Main template - [mainTemplate.json](https://github.com/user-attachments/files/16864169/mainTemplate.json)

Thanks!

**Comment by Bievens** [comment]
Validation and deployment are successful with the provided query. Thanks for resolving this issue.

**Comment by v-sudkharat** [comment]
@Bievens, Thanks for your response.  closing this issue. If you still need support for this issue, feel free to re-open it any time. Thank you for your co-operation.
