### ISSUE TITLE
Unable to collect ASimNetworkSessionLogs on new Cisco Meraki REST API Data Connector

### ISSUE THREAD

**Issue by tom-1122** [Azure/Azure-Sentinel#10890]
I am trying to migrate away from the old Legacy method of collecting Meraki logs to the Meraki_CL table, and am trying to configure the new Cisco Meraki Rest API data connector.

I've added in my Org ID and API key to the connector and connected successfully, I am successfully receiving logs into the AsimWebSessionLogs & ASimAuditEventLogs table, but I am not seeing any logs in the ASimNetworkSessionLogs table and I can't work out why. 

I've tested with postman and I get a return with logs from the tables I am seeing logs in, but when I try with getOrganizationApplianceSecurityEvents I get a return of []

Any help would be appreciated.

Thanks

**Comment by Masozera** [comment]
Hello @tom-1122, Did you get the solution to this problem?

**Comment by tom-1122** [comment]
> Hello [@tom-1122](https://github.com/tom-1122), Did you get the solution to this problem?

Hello, yeah, these logs are apart of the IDS module in Meraki. Customer didn't have it
