### ISSUE TITLE
Allow only specific users to contribute

### ISSUE THREAD

**Issue by vdobrotskyi-varonis** [Azure/Azure-Sentinel#10906]
Is there way to allow only specific users to contribute to pack that we created for MS Sentinel? We have a concern that someone can check in malicious code without us knowing that. Is there an options to have private github repo for our pack?

**Comment by v-sudkharat** [comment]
Hey @vdobrotskyi-varonis, Currently there is no such feature for this, as this is an open-source repository, and about the code our PR review team will validate that pull request before it get Merged. Thanks!
