### ISSUE TITLE
Only the first line of a Description field is commented out

### ISSUE THREAD

**Issue by tur11ng** [Azure/Azure-Sentinel#10929]
Only the first line of a Description field is commented out in the Advanced Hunting in Azure Microsoft Defender.

https://github.com/Azure/Azure-Sentinel/blob/master/Hunting%20Queries/Microsoft%20365%20Defender/Discovery/MultipleLdaps.yaml

![image](https://github.com/user-attachments/assets/0ec67e81-5118-4551-80af-172bc9920471)

**Comment by v-sudkharat** [comment]
Hi @tur11ng, Just want to check, below one is the rule which you want to highlight for issue? - https://github.com/Azure/Azure-Sentinel/blob/master/Hunting%20Queries/Microsoft%20365%20Defender/Discovery/MultipleSensitiveLdaps.yaml

And could please share the steps to reproduce this issue in Azure portal side. Thanks!

**Comment by tur11ng** [comment]
Just try to view/edit the query inside the Defender in the Advanced Hunting tab. The screenshot I sent you is from there.

**Comment by v-sudkharat** [comment]
Hey @tur11ng, Thanks for your response, raised the PR with changes. Thanks!
