### ISSUE TITLE
Amazon Web Service S3 data connector failure for CloudTrail

### ISSUE THREAD

**Issue by fukayli** [Azure/Azure-Sentinel#10933]
We tried to follow the instruction to run the PowerShell script called "ConfigAwsConnector.ps1" and we have got no error. (the log posted below).

We used the values below to configure the Amazon Web Service S3 data connector in the Azure Sentinel portal.

- Role Arn: arn:aws:iam::<*****>:role/OIDC_datc-role
- Sqs Url: https://sqs.ap-east-1.amazonaws.com/<*****>/datc-sqs
- Destination Table: AWSCloudTrail

**Error found**:
Connectivity check failed: **Status code:S3B40011**, Message: Access to an SQS queue (https://sqs.ap-east-1.amazonaws.com/730477759351/datc-sqs) was denied. Authentication succeeded but authorization failed. Ensure that the SQS has the required permissions listed in its access policy tab.

===== PS execution log ======
PS C:\temp\ConfigAwsComToAzureCom> .\ConfigAwsConnector.ps1

Starting ConfigAwsConnector at: 07/26/2024 04:49:54
  Log created: C:\temp\ConfigAwsComToAzureCom\Logs\AwsS3-07260449.csv

To begin you will choose the AWS logs to configure.

Please enter the AWS log type to configure (VPC, CloudTrail, GuardDuty, CloudWatch, CustomLog): CloudTrail

Checking AWS CLI configuration...

This script creates an Assume Role with minimal permissions to grant Azure Sentinel access to your logs in a designated S3 bucket & SQS of your choice, enable CloudTrail Logs, S3 bucket, SQS Queue, and S3 notifications.

  Notes:
  * You can find more information about the script in https://github.com/Azure/Azure-Sentinel/blob/master/DataConnectors/AWS-S3/README.md
  * If a resource name(like: S3, Sqs, Kms) already exists, the script will use the available one and not create a new resource

Checking existing OIDC provider
  OIDC provider already exists
  Approved client IDs: api://<*****>
  Client ID api://<*****> is already approved

Assume role definition

Please enter role name. If you have already configured an assume role for Azure Sentinel, use the same role name: datc-role
  Using role name: OIDC_datc-role with OIDC prefix because OpenID Connect authentication is being used.

You must specify the the Azure Sentinel Workspace ID. This is found in the Azure Sentinel portal.

Please enter your Azure Sentinel External ID (Workspace ID): <*****>
  Using Azure Sentinel Workspace ID: <*****>
  OIDC_datc-role role created successfully

S3 bucket definition.

Please enter S3 bucket name (between 3 and 63 characters long): datc-bucket
  Using S3 Bucket name: datc-bucket

Bucket doesn't exist or you don't have permission to access it, would you like to create a new bucket ? [y/n]: y
  Creating new bucket: y
  S3 Bucket datc-bucket created successfully

Creating SQS queue:

Please enter Sqs Name: datc-sqs
  Using Sqs name: datc-sqs

Do you want to enable KMS for CloudTrail? [y/n]: n

Updating the SQS policy to allow S3 notifications, and ARN to read/delete/change visibility of SQS messages and get queue url
  Changes S3: SQS SendMessage permission to 'datc-bucket' s3 bucket
  Changes Role ARN: SQS ChangeMessageVisibility, DeleteMessage, ReceiveMessage and GetQueueUrl permissions to 'OIDC_datc-role' rule

Do you want to enable the Trail and CloudTrail S3 Policy for ALL accounts in your organization? [y/n]: y

Updating the S3 policy to allow Sentinel to read the data.
Changes: S3 Get and List permissions to 'OIDC_datc-role' rule
Changes S3: Get CloudTrail notifications

Enabling S3 event notifications (for *.gz file)

Please enter the event notifications name: datc-events
  Using event notification name: datc-events
Event notificaion prefix definition, to Limit the notifications to objects with key starting with specified characters.

The default prefix is 'AWSLogs/<*****>/'.
  Do you want to override the event notification prefix? [y/n]: n

CloudTrail definition

Please enter CloudTrail name: datc-logs
  Using CloudTrail name: datc-logs
  datc-logs trail created successfully

Do you want to enable the CloudTrail data events? [y/n]: n

Do you want the Trail to be multi-region? [y/n]: y

Use the values below to configure the Amazon Web Service S3 data connector in the Azure Sentinel portal.

Role Arn: arn:aws:iam::<*****>:role/OIDC_datc-role
Sqs Url: https://sqs.ap-east-1.amazonaws.com/<*****>/datc-sqs
Destination Table: AWSCloudTrail

Press any key to continue...
===== PS execution log ======

**Comment by v-sudkharat** [comment]
Hi @fukayli, Thanks for flagging this issue, we will investigate this issue and get back to you with some updates. Thanks!

**Comment by fukayli** [comment]
I have enclose the my sqs queue access policy for your information.

{
  "Version": "2012-10-17",
  "Id": "__default_policy_ID",
  "Statement": [
    {
      "Sid": "allow s3 to send notification messages to SQS queue",
      "Effect": "Allow",
      "Principal": {
        "Service": "s3.amazonaws.com"
      },
      "Action": "SQS:SendMessage",
      "Resource": "arn:aws:sqs:ap-east-1:<.....>:datc-sqs",
      "Condition": {
        "ArnLike": {
          "aws:SourceArn": "arn:aws:s3:*:*:datc-bucket"
        }
      }
    },
    {
      "Sid": "allow specific role to read/delete/change visibility of SQS messages and get queue url",
      "Effect": "Allow",
      "Principal": {
        "AWS": "arn:aws:iam::<.....>:role/OIDC_datc-role"
      },
      "Action": [
        "SQS:ChangeMessageVisibility",
        "SQS:DeleteMessage",
        "SQS:ReceiveMessage",
        "SQS:GetQueueUrl"
      ],
      "Resource": "arn:aws:sqs:ap-east-1:<.....>:datc-sqs"
    }
  ]
}

**Comment by fukayli** [comment]
The "ConfigAwsConnector.ps1" script created a role, but when I checked the IAM, I found no "permissions policies" created. I follow the document on manual procedures, I created 5 permission for the OIDC role. However, none of them works.
<img width="1068" alt="Screenshot 2024-08-12 at 9 53 15 PM" src="https://github.com/user-attachments/assets/bf8575ef-f20e-4816-b360-7f689dface80">

**Comment by fukayli** [comment]
Thanks for Microsoft APAC team, the issue resolved. Just Change the region compatibility from “AWS regions enabled by default” to “All AWS Regions”. At AWS Management Console > Account settings > Security Toke Service (STS) > Global endpoint > Change 
![AWS-Change region compatibility](https://github.com/user-attachments/assets/11454671-e9b6-4cef-a45a-0e9b9d203397)
![connected](https://github.com/user-attachments/assets/394264ea-d27b-4e2c-b355-4343d3a91fba)
