### ISSUE TITLE
Trend Micro Vision One (Function App) - latest commit not published to Content Hub

### ISSUE THREAD

**Issue by hgtok** [Azure/Azure-Sentinel#10940]
**Describe the bug**
* the latest commit on 19 July has not been published to Content Hub.
* commit solution is version 3.0.0, but Content Hub remains on version 2.0.1.
* see https://github.com/Azure/Azure-Sentinel/blob/master/Solutions/Trend%20Micro%20Vision%20One/Package/mainTemplate.json

**To Reproduce**
1. Go to 'Content Hub'
2. Scroll down to 'Trend Vision One'
3. See version is 2.0.1

**Expected behavior**
Content Hub to reflect the latest version within a week of the commit.

**Screenshots**
![image](https://github.com/user-attachments/assets/cb837680-2eb4-434e-bd29-d979cd420950)

**Additional context**
#10653 was addressed by Trend, but their commit was not released to Content Hub after waiting several weeks due to this issue.

**Comment by hgtok** [comment]
@v-sudkharat is 'solution author' referring back to Trend? if so, they have responded that publishing to Content Hub is controlled by Microsoft. Hence this issue was created. can I include your email into the support ticket we have opened with Trend to sort this out?

**Comment by v-sudkharat** [comment]
Hi @hgtok, Checking with our team who is in discussion with the Solution Author about publishing the solution. Once we get further update from team, will share with you.
@v-shukore / @v-atulyadav, FYI.
 Thanks!

**Comment by V1ManagedServices** [comment]
> Hi @hgtok, Checking with our team who is in discussion with the Solution Author about publishing the solution. Once we get further update from team, will share with you. @v-shukore / @v-atulyadav, FYI. Thanks!

Hi @v-sudkharat, @v-shukore, @v-atulyadav,
We have replied the issue in this Pull Request: (https://github.com/Azure/Azure-Sentinel/pull/10725#issuecomment-2283088112)

> Hi @v-shukore,
> Thanks for getting back.
> According to the document (https://github.com/Azure/Azure-Sentinel/blob/master/Tools/Create-Azure-Sentinel-Solution/V3/README.md), we've updated the Analytic Rule template version to 1.0.4 and generated the solution package using the createSolutionV3.ps1 script. This created a ZIP file named "3.0.0.zip" under the folder "Solutions/Trend Micro Vision One/Package". The validation for the package was also successful.
> 
> Our question is: Should we delete the older solutions or are there any additional steps required for publishing a solution?
> Thanks.

I've copied my response from the other issue here so we can consolidate all updates in this new ticket. Thank you.

**Comment by v-shukore** [comment]
Hii @V1ManagedServices, as you packaged this solution using V3 tool to 3.0.0 please publish this solution live to partner center. Please refer below steps to publish solution live which is version of 3.0.0.
https://github.com/Azure/Azure-Sentinel/blob/master/Solutions/README.md#step-3--publish-your-solution.
Thanks...!!

**Comment by v-sudkharat** [comment]
Hi @V1ManagedServices, Did you get a chance to check on above comment. Could you please publish the solution to live to get it available in content hub. Thanks!

**Comment by V1ManagedServices** [comment]
> Hi @V1ManagedServices, Did you get a chance to check on above comment. Could you please publish the solution to live to get it available in content hub. Thanks!

Hi @v-sudkharat ,
We have publish the 3.0.0 version in Partner Center.
![圖片](https://github.com/user-attachments/assets/89c02246-365e-4db1-afd0-29d1108bc351)

But we still don't get the newest version of rule template by downloading from Content Hub in Sentinel after the publishing.
When can we expect the updated rule template to be available for download in the production environment?

Thanks.

**Comment by V1ManagedServices** [comment]
> > Hi @V1ManagedServices, Did you get a chance to check on above comment. Could you please publish the solution to live to get it available in content hub. Thanks!
> 
> Hi @v-sudkharat , We have publish the 3.0.0 version in Partner Center. ![圖片](https://private-user-images.githubusercontent.com/128674128/361717517-89c02246-365e-4db1-afd0-29d1108bc351.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ3NDc0OTEsIm5iZiI6MTcyNDc0NzE5MSwicGF0aCI6Ii8xMjg2NzQxMjgvMzYxNzE3NTE3LTg5YzAyMjQ2LTM2NWUtNGRiMS1hZmQwLTI5ZDExMDhiYzM1MS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgyN1QwODI2MzFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lZmFmOWMyYTlmNjgzMzI0YzJhZDgyODNjYzRjM2ZhMzIyNDhjYzUwMWE1NGZjY2JmYmY0NTdlOGE2MzkwNGRjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.jWZ3MXOcLIew24g6-1pC4BoPpkYKZKZaG8Q5W8pstSA)
> 
> But we still don't get the newest version of rule template by downloading from Content Hub in Sentinel after the publishing. When can we expect the updated rule template to be available for download in the production environment?
> 
> Thanks.

Hi @v-sudkharat @hgtok,
The rule template has been updated, please upgrade the package thanks.

![圖片](https://github.com/user-attachments/assets/ee7dcc0a-b400-461c-acab-e907ffe9edfa)

![圖片](https://github.com/user-attachments/assets/4b205090-c693-4a9f-ac8c-5e5491851dd5)

**Comment by v-sudkharat** [comment]
Thanks @V1ManagedServices for the update.

**Comment by v-sudkharat** [comment]
Hi @hgtok, Kindly update the solution and analytic rule to get new changes. Closing this issue. If you still need support for this issue, feel free to re-open it any time. Thank you for your co-operation. 

 Thanks!
