### ISSUE TITLE
AzureFunctionOCILogs: Parsing issue with AzureFunctionOCILogs app for VCN/firewall logs: com.oraclecloud.vcn.flowlogs.DataEvent

### ISSUE THREAD

**Issue by ChandanJainWTW** [Azure/Azure-Sentinel#10957]
**Describe the bug**
AzureFunctionOCILogs: Parsing issue with AzureFunctionOCILogs app for VCN/firewall logs: com.oraclecloud.vcn.flowlogs.DataEvent

events are getting pull from OCI by function app. As we can see the VCN events in attached screen shot.

However, the function would raise an exception / filtering out during the POST if it got a 4xx/5xx 

 
**To Reproduce**
No Logs in Sentinel : KQL

OCI_Logs_CL | where type_s == "com.oraclecloud.vcn.flowlogs.DataEvent"

**Expected behavior**
 Should parse all event to Sentinel
![OCI](https://github.com/user-attachments/assets/5d2cd99e-4663-4f9f-bc66-06084044d56d)
 
<img width="279" alt="KQL for OCI in June" src="https://github.com/user-attachments/assets/fc19c154-a625-40bd-b1f8-f308a835dacf">

Before Function app update 
<img width="279" alt="KQL for OCI in June" src="https://github.com/user-attachments/assets/89aeb953-8bff-4f70-8a48-586935b6082d">

After  Function app update , "com.oraclecloud.vcn.flowlogs.DataEvent" logs were stop 
<img width="263" alt="KQL" src="https://github.com/user-attachments/assets/c78046a9-a2c3-4a86-8527-cce4dde4cc72">

**Screenshots**
Attached 

**Additional context**
Problem has started after recent update in the main.py file - 3 month before

https://github.com/Azure/Azure-Sentinel/tree/master/Solutions/Oracle%20Cloud%20Infrastructure/Data%20Connectors/AzureFunctionOCILogs

**Comment by v-sudkharat** [comment]
Hi @ChandanJainWTW, Thanks for flagging this issue, we will investigate this issue and get back to you with some updates. Thanks!

**Comment by v-sudkharat** [comment]
Hi @ChandanJainWTW, Could you please follow below steps and let us know the result: 

1. Go to Configuration option in your Function App and click on the edit option of WEBSITE_RUN_FROM_PACKAGE and replace the existing Value with below shared one -
https://github.com/Azure/Azure-Sentinel/raw/bfa2464611ef8d21cfe3a87a888d53a3bf900080/Solutions/Oracle%20Cloud%20Infrastructure/Data%20Connectors/OCILogsConn.zip

![image](https://github.com/Azure/Azure-Sentinel/assets/132428394/e3ddedcd-1b8c-4ad2-bbde-49313fb0d58d)

![image](https://github.com/Azure/Azure-Sentinel/assets/132428394/88778a7b-8bca-49b8-8215-a3304ea6119a)
![image](https://github.com/Azure/Azure-Sentinel/assets/132428394/216e0d04-6d68-4999-9463-cf17589d0593)

2. Save the changes and restart the function app - 
![image](https://github.com/Azure/Azure-Sentinel/assets/132428394/af66015d-1fe8-4b23-b343-976f5afdb738)
![image](https://github.com/Azure/Azure-Sentinel/assets/132428394/6c98eb3b-e371-4f19-9f14-905a2b1dee66)

Please let us know the above changes help to resolve the issue. 
Thanks!

**Comment by v-sudkharat** [comment]
> will it be possible to revert the Main.py on previous file .. that was working fine

@ChandanJainWTW, Below is the link for the previous file, please update the same in WEBSITE_RUN_FROM_PACKAGE and restart the function app. - 
https://github.com/Azure/Azure-Sentinel/raw/184d6b21b875526c228671533ed9b959df17122a/Solutions/Oracle%20Cloud%20Infrastructure/Data%20Connectors/OCILogsConn.zip

**Comment by v-sudkharat** [comment]
@ChandanJainWTW, Thanks for the update. sorry but I dont know any such function app which pull historical logs from the Elasticsearch nodes/ OCI block storage, but i will check it with team and update you. 
So, as you issue resolved, closing this issue from github. If you still need support for this issue, feel free to re-open it any time. Thank you for your co-operation.
