### ISSUE TITLE
Instructions for Exchange Admin Audit Log Events Data Connector has incorrect log names (Exchange On-Premises Solution)

### ISSUE THREAD

**Issue by leighcurranTW** [Azure/Azure-Sentinel#10960]
The data connector for the Exchange Admin and Audit Log Events uses 'MS Exchange Management' as the log name when it should be 'MSExchange Management'. For example:  __Click **Add Windows event log** and enter **MS Exchange Management** as log name.__

To reproduce the issue, install the Exchange On-Premises solution and try to configure:

[Option 1] MS Exchange Management Log collection > Data Collection Rules - When the legacy Azure Log Analytics Agent is used > Configure the logs to be collected.

And

[Option 1] MS Exchange Management Log collection > Data Collection Rules - When Azure Monitor Agent is used > Option 2 - Manual Deployment of Azure Automation.

![image](https://github.com/user-attachments/assets/66a00056-e2e3-4d1d-bdb1-60072cf1d9dd)
An example of the event name (Which is used correctly in the parsers etc through the solution already):
![image](https://github.com/user-attachments/assets/1c3abf37-5cd5-4524-84e1-f4094a9cb487)
![image](https://github.com/user-attachments/assets/18bcfea4-f6c3-4f7a-8226-b30732672fd6)

Line 212 and 232 in ESI-ExchangeAdminAuditLogEvents.json

**Comment by v-sudkharat** [comment]
FYI, @v-prasadboke

**Comment by nlepagnez** [comment]
Hi @v-prasadboke , @v-sudkharat, I confirm that the XPath information is not good. The good value is "MSExchange Management!*" So in connector documentation it has to be "MSExchange Management"

**Comment by v-prasadboke** [comment]
Got it @nlepagnez, Working on it

**Comment by nlepagnez** [comment]
Hi @v-prasadboke, the XPath will be corrected in the pull request #11049
