### ISSUE TITLE
TenableIO not showing up in solutions

### ISSUE THREAD

**Issue by leighcurranTW** [Azure/Azure-Sentinel#10962]
I can see that there is a Solution for Tenable.IO in Github: https://github.com/Azure/Azure-Sentinel/tree/master/Solutions/TenableIO but the solution isn't available in Sentinel's content hub. I noticed that there isn't a ReleaseNotes.md like the other solutions (For example the Tenable App Solution):
![image](https://github.com/user-attachments/assets/7cab8f5c-aac5-4054-bdfb-94d812b85a72)
![image](https://github.com/user-attachments/assets/c4aebe2d-7679-42dd-89e6-58f6507d9f14)

Is it supposed to appear as a solution or is it missing some other requirements?

**Comment by v-sudkharat** [comment]
Hey @leighcurranTW, the new release of solution is here- https://github.com/Azure/Azure-Sentinel/tree/master/Solutions/Tenable%20App, So kindly search for the solution name **"Tenable App"** in content hub. 
![image](https://github.com/user-attachments/assets/13da7b5a-695b-4198-b5c0-c2d6217afb5e)

Thanks!

**Comment by leighcurranTW** [comment]
OK thanks for the update.

**Comment by v-sudkharat** [comment]
@leighcurranTW, Welcome. so, closing this issue. If you still need support for this issue, feel free to re-open it any time. Thank you for your co-operation.
