### ISSUE TITLE
`currentGroup_s` Column Missing in New Darktrace Deployments

### ISSUE THREAD

**Issue by Kaloszer** [Azure/Azure-Sentinel#10973]
## Describe the bug
The KQL query in the Darktrace AI Analyst analytic rule includes the `currentGroup_s` column, which is renamed to `DtCGLegacy`. However, this column doesn't always exist in new Darktrace deployments, causing issues such as 'column not found'

## To Reproduce
1. Deploy a new instance of Darktrace
2. Set up the Darktrace connector in Microsoft Sentinel
3. Run the "Darktrace AI Analyst" analytic rule
4. KQL fails to execute/AR deploy due to that the `currentGroup_s` column is missing from the incoming data

## Expected behavior
The analytic rule should work correctly for all Darktrace deployments, regardless of whether the `currentGroup_s` column is present or not.

## Additional context
This issue affects the "Darktrace AI Analyst" analytic rule (ID: `ffa2977f-3077-4bba-b1bf-f3417699cbb0`) in Microsoft Sentinel. The problem lies in the KQL query that assumes the presence of the `currentGroup_s` column.

## Proposed Fix
To address this issue, modify the KQL query to make the `currentGroup_s` column optional.

1. Remove the direct renaming of `currentGroup_s` to `DtCGLegacy` from the `project-rename` operation.
2. Add a new `extend` operation after the existing ones to conditionally include `DtCGLegacy` if it exists.

Here's the modified query:

```kql
darktrace_model_alerts_CL 
| where dtProduct_s =="AI Analyst"
| project-rename  EventStartTime=startTime_s, EventEndTime = endTime_s, NetworkRuleName=title_s, DtCurrentGroup=externalId_g, ThreatCategory=dtProduct_s, ThreatRiskLevel=score_d, SrcHostname=hostname_s, SrcIpAddr=deviceIP_s, DtURL=url_s, DtSummary=summary_s, DtGroupScore=groupScore_d, DtGroupCategory=groupCategory_s, DtSrcDeviceName=bestDeviceName_s, DtIndentifier=identifier_s, ActivityID=activityId_s, DtGroupingID=groupingId_s, DtGroupByActivity=groupByActivity_b, DtSummaryFirstSentence=summaryFirstSentence_s, DtNewEvent=newEvent_b, DtGroupPreviousGroups=groupPreviousGroups_s, DtTime=time_s, DtSeverity=Severity, DtLongitude=longitude_d, DtLatitude=latitude_d  
| extend EventVendor = "Darktrace", EventProduct = "Darktrace DETECT", DtSentinelCategory=DtGroupCategory
| extend DtSentinelCategory = case (DtGroupCategory == "compliance", "Low", 
                                    DtGroupCategory == "suspicious", "Medium",
                                    "High") //compliance -> low, suspcious -> medium, critical -> high
| extend DtCGLegacy = column_ifexists("currentGroup_s", "")

**Comment by v-sudkharat** [comment]
Hi @Kaloszer, We have checked this solution and this solution is a supported with Darktrace, and we are not authorized to make any changes into it. kindly request you to raise an issue ticket with Darktrace's support team. So, they can check on it and raise a PR with those changes. 
Sharing the Darktrace support link -
Link - https://www.darktrace.com/en/contact/
So, closing this issue. If you still need support for this issue, feel free to re-open it any time. Thank you for your co-operation.
Thanks!
