### ISSUE TITLE
"Custom logs via AMA" content does not allow creating a DCR

### ISSUE THREAD

**Issue by ashwinvenkatesha** [Azure/Azure-Sentinel#10979]
**Describe the bug**
"Custom logs via AMA" content does not allow creating a DCR

**To Reproduce**
1. Go to Content Hub -> Custom logs via AMA 
2. Click on 'Create a DCR'
3. See error

**Expected behavior**
User should be able to create a DCR

**Screenshots**
<img width="1578" alt="image" src="https://github.com/user-attachments/assets/14bdd12b-1111-476c-9617-7ebd58b9a302">

**Desktop (please complete the following information):**
 - OS: Mac
 - Browser Chrome
 - Version 127.0.6533.100

**Comment by v-sudkharat** [comment]
Hi @ashwinvenkatesha, Thanks for flagging this issue, we will investigate this issue and get back to you with some updates. Thanks!

**Comment by v-sudkharat** [comment]
Hi @ashwinvenkatesha, to create a DCR workspace requires the below permissions : 
![image](https://github.com/user-attachments/assets/18664729-678b-41d0-be7d-ac4b1be3f77f)

Please enable it from LAW and check for the connector:- 
![image](https://github.com/user-attachments/assets/49ff8c43-f91b-44ca-a382-19e158146d0b)

Please let us know if your issue gets resolved. Thanks!

**Comment by v-sudkharat** [comment]
Hi @ashwinvenkatesha, waiting for your response on above comment. Thanks!

**Comment by v-sudkharat** [comment]
@ashwinvenkatesha, since we have not received a response in the last 5 days, we are closing your issue as per our standard operating procedures. If you still need support for this issue, feel free to re-open at any time. Thank you for your co-operation.
