### ISSUE TITLE
[Deprecated] Aruba ClearPass via AMA

### ISSUE THREAD

**Issue by applefacts** [Azure/Azure-Sentinel#10971]
Is the [Deprecated] Aruba ClearPass via AMA actually deprecated? I see this [commit ](https://github.com/Azure/Azure-Sentinel/commit/b43d92f8a52df6b54dc401639f32022d5c5bea02) but the public doc still shows it being not deprecated: https://learn.microsoft.com/en-us/azure/sentinel/data-connectors/recommended-aruba-clearpass-via-ama

**Comment by v-rusraut** [comment]
Hi @applefacts,
It is correct that data connector - Aruba ClearPass via AMA is deprecated, now it recommends to installation of CEF via AMA Connector to pull the logs. And the public doc will update soon. So, closing this issue. If you still need support for this issue, feel free to re-open it any time. Thank you for your co-operation.
