### ISSUE TITLE
Creating a new custom log (DCR Based) doe not give you the option to specify a data source location

### ISSUE THREAD

**Issue by LiamWBA** [Azure/Azure-Sentinel#10975]
**Describe the bug**
When you want to collect custom logs, you go into the Log Analytics Workspace and you select tables and then you attempt to create a new table (DCR based). The MMA agent is now almost deprecated so really, AMA agent should be the only option I think. When you create the table through this method. It creates a DCR rule but it doesn't allow you to specify the location of the logs. The only option In the data sources section is Edit transformation.

**To Reproduce**
1. Go to Log Analytics Workspace - Tables
2. Create a new table (DCR Based)
3. Go through the wizard - fill in the required fields. Select 'Create a new DCR rule' for the DCR rule section.
4. Once completed - go to the DCR rule
5. Open up the Data Sources section.
6. Try to specify the data source for the collection. Only option is Edit Transformation. 

**Expected behavior**
I would have thought you need to specify a source location for the logs you want the system to collect? How does the DCR rule know where to get the logs from on the resource you specify?

**Comment by v-sudkharat** [comment]
Hi @LiamWBA, Thanks for flagging this issue, we will investigate this issue and get back to you with some updates. Thanks!

**Comment by v-rusraut** [comment]
Hi @LiamWBA,
Please provide details about which custom solution you are using?
For custom based solution new AMA based data connector is available now to pull the logs.
Please check new  solutions - Custom Logs AMA
![image](https://github.com/user-attachments/assets/15a0b742-2d37-4bee-8098-4480c36420c6)

Thanks

**Comment by v-rusraut** [comment]
Hi @LiamWBA,
We are waiting for your response.
Thanks

**Comment by v-rusraut** [comment]
Hi @LiamWBA, Gentle Reminder: We are waiting for your response on this issue. If you still need to keep this issue active, please respond to it in the next 2 days. If we don't receive a response by 13-09-2024 date, we will be closing this issue.
Thanks!

**Comment by v-rusraut** [comment]
Hi @LiamWBA, since we have not received a response, we are closing your issue as per our standard operating procedures. If you still need support for this issue, feel free to re-open at any time. Thank you for your co-operation.
