### ISSUE TITLE
Microsoft Sentinel - JIRA connector not working

### ISSUE THREAD

**Issue by pratikghogre8cap** [Azure/Azure-Sentinel#10983]
**Describe the bug**
The Atlassian Jira Audit (using REST API) (Preview) fails to connect.

**To Reproduce**
1. Go to the Atlassian Jira Audit (using REST API) (Preview) connector in Sentinel.
2. Click on add organization button
3. Fill the required information.

**Expected behavior**
The connection to establish and the data to start flowing.

**Screenshots**
![image](https://github.com/user-attachments/assets/985352d8-997f-4fbb-a3f6-e7b0a3b97cdd)

**Desktop (please complete the following information):**
 - OS: Windows OS 2011
 - Browser: Chrome
 - Version : 127.0.6533.120 (Official Build) (64-bit) (cohort: Stable)

**Additional context**
The user who created the API is a platform admin, and their credential was used to establish this connection.

**Comment by v-sudkharat** [comment]
Hi @pratikghogre8cap, Thanks for flagging this issue, we will investigate this issue and get back to you with some updates. Thanks!

**Comment by Latsis** [comment]
Looks like Sentinel's Content Hub still has the buggy previous version (3.0.2) up, any information when the fixed 3.0.3 will be published there?

**Comment by pratikghogre8cap** [comment]
Tried the new connector manually, worked. 
The connector needs to be updated in Content-Hub. @v-sudkharat

**Comment by v-sudkharat** [comment]
> Looks like Sentinel's Content Hub still has the buggy previous version (3.0.2) up, any information when the fixed 3.0.3 will be published there?

Hi @Latsis, The new 3.0.3 has been published. Thanks!

**Comment by v-sudkharat** [comment]
> Tried the new connector manually, worked. The connector needs to be updated in Content-Hub. @v-sudkharat

Thanks @pratikghogre8cap, for the update. The new 3.0.3 has been published, could you please check and let us know it fixed you issue.

**Comment by TomicaKaniski** [comment]
I'm still getting the 401: Unauthorized, even though I've updated the solution (connector is still v1.0.0). What am I doing wrong?

Cheers,
Tom

**Comment by v-sudkharat** [comment]
> Tried the new connector manually, worked. The connector needs to be updated in Content-Hub. @v-sudkharat

@pratikghogre8cap, could you help us to understand how you configured manually? if possible could you please share screenshots as well.

**Comment by v-sudkharat** [comment]
Hi @TomicaKaniski / @Latsis, 
We will update the template and will raise PR with correct changes. Meantime, could you please custom deploy the Solution MainTemplate and check whether your issue get resolved.
Sharing the MainTemplate and Custom deployment steps-
Custom Deployment - [CustomDeploymentSteps.docx](https://github.com/user-attachments/files/16782483/CustomDeploymentSteps.docx)
Main template - [Fix.txt](https://github.com/user-attachments/files/16798376/Fix.txt)

Thanks!

**Comment by TomicaKaniski** [comment]
Thank you, @v-sudkharat! Removed, deployed the fix, but still having the same issue, unfortunately.

**Comment by v-sudkharat** [comment]
Hi @TomicaKaniski, Coud you please check once by using below file :- 
https://[raw.githubusercontent.com/Azure/Azure-Sentinel/af1e2a30e4d3b8d57c09a1cd7f82825fd6f1c882/Solutions/AtlassianJiraAudit/Package/mainTemplate.json](https://raw.githubusercontent.com/Azure/Azure-Sentinel/af1e2a30e4d3b8d57c09a1cd7f82825fd6f1c882/Solutions/AtlassianJiraAudit/Package/mainTemplate.json)

Maybe the Data connector is not gets overwrite correctly after custom deployment, please check it in different workspace. 
And if you still get same error, We can connect via a call to resolve this issue. Thanks!

**Comment by TomicaKaniski** [comment]
@v-sudkharat, thank you! This one works!

Connected successfully to both - new workspace and an existing one (which was previously failing):
![image](https://github.com/user-attachments/assets/75d16419-9112-4285-8c59-d3192667a807)

Thank you!

Cheers,
Tom

**Comment by v-sudkharat** [comment]
Thanks @TomicaKaniski, for update. This fix will also get updated into upcoming solution version. Thanks! 
So, closing this issue. If you still need support for this issue, feel free to re-open it any time. Thank you for your co-operation.
