### ISSUE TITLE
2 different rules have the same name

### ISSUE THREAD

**Issue by esschotenw** [Azure/Azure-Sentinel#10989]
In folder Azure-Sentinel/Solutions/Microsoft 365/Analytic Rules are two different rules with the same name:

1. sharepoint_file_transfer_above_threshold.yaml
2. sharepoint_file_transfer_folders_above_threshold.yaml

The name for both rules are: Office365 Sharepoint File transfer above threshold

We expected each Analytic Rule has his own name:
1. Office365 Sharepoint File transfer above threshold
2. Office365 Sharepoint File transfer Folders above threshold

![image](https://github.com/user-attachments/assets/2a8492f6-7be9-4697-b548-01dd66677c53)
![image](https://github.com/user-attachments/assets/ec5d9046-4730-4283-9d2a-f8825d75d554)

**Comment by v-sudkharat** [comment]
Hi @esschotenw, Thanks for flagging this issue, we will investigate this issue and get back to you with some updates. Thanks!

**Comment by v-sudkharat** [comment]
Hi @esschotenw, We have raised the PR with correction. Once the raised PR get merged, the changes will get reflected into upcoming solution version. 
Thanks!
