### ISSUE TITLE
Creating OracleWebLogicServer DCR using the Custom AMA Solution reports error "length should be 32 characters or less"

### ISSUE THREAD

**Issue by PCNZ** [Azure/Azure-Sentinel#10993]
**Describe the bug**
Use the new "Custom logs via AMA (Preview)" data connector to create a data collection rule for a device type of OracleWebLogicServer. Always fails with the error "Failed to create rule test, 'Name' length should be 32 characters or less. Specified value has 35 characters.". No matter what name is used.

**To Reproduce**
1. Install the Custom Logs AMA Solution into Sentinel
2. Click on Data Connectors and Open the "Custom logs via AMA (Preview)" data connector page.
3. Click on "Create data collection rule"
4. Enter any rule name, i.e. "test", Click Next
5. Select resources (optional step), Click Next: Collect
6. Choose OracleWebLogicServer from the "Select device type" drop down box.
7. Enter C:\Test\Test.log into the File Pattern field
8. Click Next: Review + create, Click Create
9. Observe error

**Expected behavior**
DCR should be created on completion

**Screenshots**
![image](https://github.com/user-attachments/assets/f1f5a0da-42ae-4d54-bcd7-fadba1e7c89e)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser Chrome or Edge
 - Version latest

**Additional context**
Other data collection rules are able to be created, tested vCenter OK.

**Comment by v-rusraut** [comment]
Hi @PCNZ, Thanks for flagging this issue, we are working with respective team, will update you. Thanks!

**Comment by v-rusraut** [comment]
Hi @PCNZ,
Our respective team is working on to fix this issue, we will update you once issue fixed.
Thanks

**Comment by PCNZ** [comment]
No, getting the same error.
There is also no update in the Content Hub, version 3.0.0 is the latest and the same version I tested with originally.

**Comment by v-rusraut** [comment]
Hi @PCNZ,
Please delete solution and reinstall it again and then check you are able to create the DCR.
Thanks

**Comment by PCNZ** [comment]
> Hi @PCNZ, Please delete solution and reinstall it again and then check you are able to create the DCR. Thanks

Same error unfortunately.

**Comment by v-sudkharat** [comment]
@PCNZ, Could you please verify once :- 
![image](https://github.com/user-attachments/assets/434ca635-41c5-4d3f-a1b9-a4e1ea627076)

We tried from our end and able to create.

**Comment by v-rusraut** [comment]
Hi @PCNZ,
We are waiting for your response.
Thanks

**Comment by PCNZ** [comment]
Just tried again and it is working now.
Thank you.

**Comment by v-rusraut** [comment]
Hi @PCNZ, as you are able to create DCR now, so currently closing this issue. If you still need support for this issue, feel free to re-open at any time. Thank you for your co-operation.
