### ISSUE TITLE
ServiceNow Instructions Need Updating

### ISSUE THREAD

**Issue by SignalDistress** [Azure/Azure-Sentinel#11000]
**Describe the bug**
The instructions here are somewhat out of date:
https://github.com/Azure/Azure-Sentinel/blob/master/Solutions/Servicenow/StoreApp/README.md

**To Reproduce**
Go to the Readme, and then the section Azure: Delegate permissions to the Service Principal.
2 updates are needed.  

First, I believe you need to go to the log analytics workspace for your Sentinel instance and then add the service principal from there.

Secondly, the name of the role itself has changed.  The new name is Microsoft Sentinel Responder instead of Azure Sentinel Responder.

**Comment by v-amolpatil** [comment]
Hi, @SignalDistress,

I have raised a PR for the role text changes. For first point, document first covers all of the configurations from Microsoft Sentinel in Azure portal and then configuration from ServiceNow side. Service Principal details are covered in section "Configure the Service Principals/OAuth Provider credentials".

Thanks!

**Comment by v-amolpatil** [comment]
Closing this issue as PR with the change for role is updated in Readme file.
