### ISSUE TITLE
ServiceNow Sentinel Plugin - Move API URL Feature

### ISSUE THREAD

**Issue by SignalDistress** [Azure/Azure-Sentinel#11001]
We are using this plugin quite successfully and it works really well.
--

<br class="Apple-interchange-newline">

**Is your feature request related to a problem? Please describe.**
While the plugin is setup to manage multiple customers, it cannot be configured for GCC and non-GCC customers.  Since the management URL is set in the system properties it has to be one or the other.  The setting is Azure management API URL to call (must be https://management.usgovcloudapi.net for Gov tenants)

**Describe the solution you'd like**
We'd like the setting to be moved to the workspace configuration table in a new column, Azure Management URL.

**Describe alternatives you've considered**
We are considering building a similar plugin ourselves.

**Additional context**
We will build a new version and help with the development but we are hoping to get this feature included in the code that lives on the ServiceNow Store.  If we create our own version of this we will no longer be able to use the official plugin.

**Comment by v-amolpatil** [comment]
Thank you for reporting this feature request with us. We have noted this feature request in our queue and will check on it. If required, we will also share this with our respective concern team. Currently we can't provide any ETA for this. but once we get any further info from our team will share update to you. So, closing this issue from GitHub. If you still need support for this issue, feel free to re-open it any time. Thank you for your co-operation.
