### ISSUE TITLE
Missing columns from query

### ISSUE THREAD

**Issue by truekonrads** [Azure/Azure-Sentinel#1100]
**Describe the bug**
There are missing output columns - Sentinel/Log Analytics simply omit it.

**To Reproduce**
Consider this query which parses Syslog records that contain a long list of comma delimited values that are broken down into 61 fields:
```
Syslog 
|extend f=extract( @"\d+ [\d.]+ (.+)",1,SyslogMessage)
|extend pafields=split(f,",")
|extend 
receive_time=pafields[1],
serial=pafields[2],
type=tostring(pafields[3])
| where type=="TRAFFIC"
|extend
subtype=tostring(pafields[4+1]),
time_generated=pafields[5+1],
src=pafields[6+1],
dst=pafields[7+1],
natsrc=pafields[8+1],
natdst=pafields[9+1],
...

```

As seen from screenshot, there is a outbound_if column assigned in similar mannger but in the output does not contain the column outbound_if. 

**Expected behavior**
Columns appear in the order they are assigned and do not disappear.

**Screenshots**
![image](https://user-images.githubusercontent.com/1421150/93983361-0996b100-fdb5-11ea-9159-f0aa5d0db467.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 85

**Comment by shainw** [comment]
@truekonrads - I am wondering if you are not seeing them as they are not selected in the Column chooser.   I believe this can happen if they are empty or there are many columns -
![image](https://user-images.githubusercontent.com/45466083/94179197-07823000-fe51-11ea-8790-89adc59207e0.png)

Additionally, you can choose the order of the columns using the [project-reorder operator](https://docs.microsoft.com/en-us/azure/data-explorer/kusto/query/projectreorderoperator)

**Comment by truekonrads** [comment]
Hello,

Thank you for your reply. My description perhaps was inaccurate. It's not that the field doesn't appear in the list of columns - not all are displayed at any given time and your suggestion about enabling it in columns is valid,  but it doesn't appear in the expanded item list:

![image](https://user-images.githubusercontent.com/1421150/94220275-35cc4200-ff1b-11ea-94fe-e651c82e6360.png)


In this example above, there is a field "action_source" between device_name and src_uuid, but it isn't shown on the expanded item.

**Comment by shainw** [comment]
@truekonrads - thanks for the clarification. Can you share the full query that does the parsing so I can test it?  You can attach via a txt file.

**Comment by truekonrads** [comment]
> 
> 
> @truekonrads - thanks for the clarification. Can you share the full query that does the parsing so I can test it? You can attach via a txt file.

[query.kql.txt](https://github.com/Azure/Azure-Sentinel/files/5302933/query.kql.txt)

**Comment by shainw** [comment]
@aprakash13 will have a look at this as I have not had time to test and validate the issue.

**Comment by Lodewyk-Git** [comment]
Hi Konrad,

I had this exact problem when I was parsing data for a custom connector.

In my case the problem was that the column wasn't displaying, because it wasn't populated. I populated the fields using the iff() statement and the row was displayed.

Are you seeing the expected data from SyslogMessage before you parse it?

**Comment by truekonrads** [comment]
Yes I see the expected data. It is genuinely missing
--

Konrads Klints, KPMG Singapore |  Cyber Serenity is possible<https://home.kpmg/sg/en/home/services/cyber-serenity.html>

📱 Mobile +65 9759 9470<tel:+65%209759%209470> | ☎ Direct  +65 6411 8485<tel:+65%206411%208485>

We have access to interesting problems, work for us: careers.kpmg.com.sg<http://careers.kpmg.com.sg/>


________________________________

**Comment by truekonrads** [comment]
Any luck? I have encountered this situation again, mighty annoying

**Comment by shainw** [comment]
@truekonrads - Getting back to stale issues, apologies on the long delay.  Is this still occurring and if so, I think we need to get sample data from you.  What device are you importing data into Syslog from and are you using the default connector?

**Comment by shainw** [comment]
Closing, no response

**Comment by truekonrads** [comment]
@shainw hey, look I'm quite unhappy with what appears to be lazy triaging. The Syslog source has little to nothing to do with it, you could pick any data which has Even if it would, you could easily generate a comparable record. As you can appreciate, sharing firewall log data isn't something people will do.  If I was in your shoes, I would ingest data that has at least sixty fields separated by comma and run the query.
