### ISSUE TITLE
MimecastAudit Data Connector Function App

### ISSUE THREAD

**Issue by katerobson08** [Azure/Azure-Sentinel#11017]
**Describe the bug**
We are trying to move form version 3.8 to 3.9/3.10 or 3.11 for the Mimecast function apps as version 3.8 will no longer be supported from 14th October. You can change the runtime to ~4 and python version 3.8 and it still works .   However, if you try to go to the next version it complains of a missing library **_cffi_backend**  when trying to import  **azure storage blob** module.

**To Reproduce**
1. Go to Mimecast Audit function app
2. Go to settings, Configuration
3. select runtime version **~4**
4. Go to general settings, select python version 3.11

**Expected behavior**
To work as it did before, get mimecast audit events

**Screenshots**

**Function App errror:**
20/08/2024, 15:20:26
Information
Executing 'Functions.GetAuditEvents' (Reason='This function was programmatically called via the host APIs.', 
Id=497dc741-030f-4a30-bb24-a0c151b7ce26)
20/08/2024, 15:20:27
Error
Result: Failure Exception: ModuleNotFoundError: No module named '_cffi_backend'. 
Cannot find module. Please check the requirements.txt file for the missing module. 
For more info, please refer the troubleshooting guide: https://aka.ms/functions-modulenotfound. 
Current sys.path: ['/tmp/functions\\standby\\wwwroot', '/home/site/wwwroot/.python_packages/lib/site-packages', 
'/azure-functions-host/workers/python/3.11/LINUX/X64', '/usr/local/lib/python311.zip', '/usr/local/lib/python3.11', 
'/usr/local/lib/python3.11/lib-dynload', '/usr/local/lib/python3.11/site-packages'] Stack: File 
"/azure-functions-host/workers/python/3.11/LINUX/X64/azure_functions_worker/dispatcher.py", line 479, 
in _handle__function_load_request func = loader.load_function( ^^^^^^^^^^^^^^^^^^^^^ File "/azure-functions-host
/workers/python/3.11/LINUX/X64/azure_functions_worker/utils/wrappers.py", line 49, 
in call raise extend_exception_message(e, message) File "/azure-functions-host/workers/python/3.11/LINUX/X64/
azure_functions_worker/utils/wrappers.py", line 44, in call return func(*args, **kwargs) ^^^^^^^^^^^^^^^^^^^^^ 
File "/azure-functions-host/workers/python/3.11/LINUX/X64/azure_functions_worker/loader.py", 
line 214, in load_function mod = importlib.import_module(fullmodname) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File 
"/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module return _bootstrap._gcd_import(name[level:], 
package, level) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/home/site/wwwroot/GetAuditEvents/__init__.py", 
line 15, in <module> from azure.storage.blob import BlobServiceClient File "/home/site/wwwroot/.python_packages/lib
/site-packages/azure/storage/blob/__init__.py", line 10, in <module> from ._blob_client import BlobClient 
File "/home/site/wwwroot/.python_packages/lib/site-packages/azure/storage/blob/_blob_client.py", 
line 59, in <module> from ._download import StorageStreamDownloader File "/home/site/wwwroot/.python_packages/lib/
site-packages/azure/storage/blob/_download.py", line 20, in <module> from ._encryption import 
( File "/home/site/wwwroot/.python_packages/lib/site-packages/azure/storage/blob/_encryption.py", 
line 22, in <module> from cryptography.hazmat.primitives.ciphers.aead import AESGCM File 
"/home/site/wwwroot/.python_packages/lib/site-packages/cryptography/hazmat/primitives/ciphers/aead.py", 
line 10, in <module> from cryptography.hazmat.backends.openssl import aead File 
"/home/site/wwwroot/.python_packages/lib/site-packages/cryptography/hazmat/backends/openssl/__init__.py", 
line 6, in <module> from cryptography.hazmat.backends.openssl.backend import backend File 
"/home/site/wwwroot/.python_packages/lib/site-packages/cryptography/hazmat/backends/openssl/backend.py", 
line 113, in <module> from cryptography.hazmat.bindings.openssl import binding File 
"/home/site/wwwroot/.python_packages/lib/site-packages/cryptography/hazmat/bindings/openssl/binding.py", 
line 14, in <module> from cryptography.hazmat.bindings._openssl import ffi, lib
20/08/2024, 15:20:27
Error
Executed 'Functions.GetAuditEvents' (Failed, Id=497dc741-030f-4a30-bb24-a0c151b7ce26, Duration=118ms)
20/08/2024, 15:20:27
Error
Result: Failure Exception: ModuleNotFoundError: No module named '_cffi_backend'. Cannot find module. 
Please check the requirements.txt file for the missing module. For more info, please refer the 
troubleshooting guide: https://aka.ms/functions-modulenotfound. Current sys.path: 
['/tmp/functions\\standby\\wwwroot', '/home/site/wwwroot/.python_packages/lib/site-packages', 
'/azure-functions-host/workers/python/3.11/LINUX/X64', '/usr/local/lib/python311.zip', '/usr/local/lib/python3.11', 
'/usr/local/lib/python3.11/lib-dynload', '/usr/local/lib/python3.11/site-packages'] Stack: File 
"/azure-functions-host/workers/python/3.11/LINUX/X64/azure_functions_worker/dispatcher.py", line 479, 
in _handle__function_load_request func = loader.load_function( ^^^^^^^^^^^^^^^^^^^^^ File 
"/azure-functions-host/workers/python/3.11/LINUX/X64/azure_functions_worker/utils/wrappers.py", 
line 49, in call raise extend_exception_message(e, message) File "/azure-functions-host/workers/python/3.11/LINUX/X64
/azure_functions_worker/utils/wrappers.py", line 44, in call return func(*args, **kwargs) ^^^^^^^^^^^^^^^^^^^^^ 
File "/azure-functions-host/workers/python/3.11/LINUX/X64/azure_functions_worker/loader.py", 
line 214, in load_function mod = importlib.import_module(fullmodname) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ 
File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module return 
_bootstrap._gcd_import(name[level:], package, level) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ 
File "/home/site/wwwroot/GetAuditEvents/__init__.py", line 15, in <module> from azure.storage.blob 
import BlobServiceClient File "/home/site/wwwroot/.python_packages/lib/site-packages/azure/storage/blob/__init__.py", 
line 10, in <module> from ._blob_client import BlobClient File "/home/site/wwwroot/.python_packages/lib/site-packages/azure
/storage/blob/_blob_client.py", line 59, in <module> from ._download import StorageStreamDownloader 
File "/home/site/wwwroot/.python_packages/lib/site-packages/azure/storage/blob/_download.py", line 20, 
in <module> from ._encryption import ( File "/home/site/wwwroot/.python_packages/lib/site-packages/azure/
storage/blob/_encryption.py", line 22, in <module> from cryptography.hazmat.primitives.ciphers.aead import AESGCM File 
"/home/site/wwwroot/.python_packages/lib/site-packages/cryptography/hazmat/primitives/ciphers/aead.py", 
line 10, in <module> from cryptography.hazmat.backends.openssl import aead File "/home/site/wwwroot/.python_packages/
lib/site-packages/cryptography/hazmat/backends/openssl/__init__.py", line 6, in <module> 
from cryptography.hazmat.backends.openssl.backend import backend File "/home/site/wwwroot/.python_packages/
lib/site-packages/cryptography/hazmat/backends/openssl/backend.py", line 113, in <module> from 
cryptography.hazmat.bindings.openssl import binding File "/home/site/wwwroot/.python_packages/lib/site-packages/
cryptography/hazmat/bindings/openssl/binding.py", line 14, in <module> from cryptography.hazmat.bindings._openssl import ffi, lib

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by v-sudkharat** [comment]
Hi @katerobson08, Thanks for flagging the issue, we will update the required files and share it with you. Thanks!

**Comment by v-sudkharat** [comment]
Hi @katerobson08, Could you please follow the below steps and let us know your issue resolved:- 


1. Go to Configuration option of you deployed Function App and chick on the edit option of WEBSITE_RUN_FROM_PACKAGE and replace the existing Value with below shared one -

https://github.com/Azure/Azure-Sentinel/raw/b7d990c2c6323102f46e0722c43092b5baec8f95/Solutions/MimecastAudit/Data%20Connectors/MimecastAuditAzureConn.zip

![image](https://github.com/Azure/Azure-Sentinel/assets/132428394/e3ddedcd-1b8c-4ad2-bbde-49313fb0d58d)

![image](https://github.com/Azure/Azure-Sentinel/assets/132428394/88778a7b-8bca-49b8-8215-a3304ea6119a)
![image](https://github.com/Azure/Azure-Sentinel/assets/132428394/216e0d04-6d68-4999-9463-cf17589d0593)

2. Once it gets updated save the changes and restart the function app - 
![image](https://github.com/Azure/Azure-Sentinel/assets/132428394/af66015d-1fe8-4b23-b343-976f5afdb738)

![image](https://github.com/Azure/Azure-Sentinel/assets/132428394/6c98eb3b-e371-4f19-9f14-905a2b1dee66)

Please let us know once your issue gets resolved. 
Thanks!

**Comment by katerobson08** [comment]
Hi,
I've retested but error is still the same. It can't find a library when you change the version from 3.8 to 3.11.
Kate

**Comment by v-sudkharat** [comment]
Hi @katerobson08, After update the above link into the function app configuration and restarting the function app still facing same issue? 
Could you please share the invocation logs with us, to understand what error you're getting. And the function app takes some time to generate new logs after update/restarting it, so wait for some time to generate new logs. Thanks!

**Comment by katerobson08** [comment]
Hi,
Also, I think you will need to update "FUNCTIONS_EXTENSION_VERSION": "~3" to "~4". I don't think 3.11 is available in version 3.
Kate

**Comment by v-sudkharat** [comment]
@katerobson08, Correct, The Extension version should be ~4.  I will make that change as well. Thanks for correcting. So, It our shared zip working?

**Comment by katerobson08** [comment]
Hi,

I've stopped and started the function app this morning and retried, but still getting the same result.

<img width="721" alt="image" src="https://github.com/user-attachments/assets/e368acf8-f49e-44e4-b0ae-85f9ac0e2499">



Error message saying it can't import **_cffi_backend** when trying to import **azure storage blob** module:

27/08/2024, 09:10:00
Information
Executing 'Functions.GetAuditEvents' (Reason='Timer fired at 2024-08-27T08:09:59.9996700+00:00', Id=28ffa5ef-92aa-45dc-8488-232a55fd93d1)
27/08/2024, 09:10:00
Error
Result: Failure Exception: ModuleNotFoundError: No module named '_cffi_backend'. Cannot find module. Please check the requirements.txt file for the missing module. For more info, please refer the troubleshooting guide: https://aka.ms/functions-modulenotfound. Current sys.path: ['/tmp/functions\\standby\\wwwroot', '/home/site/wwwroot/.python_packages/lib/site-packages', '/azure-functions-host/workers/python/3.10/LINUX/X64', '/usr/local/lib/python310.zip', '/usr/local/lib/python3.10', '/usr/local/lib/python3.10/lib-dynload', '/usr/local/lib/python3.10/site-packages'] Stack: File "/azure-functions-host/workers/python/3.10/LINUX/X64/azure_functions_worker/dispatcher.py", line 479, in _handle__function_load_request func = loader.load_function( File "/azure-functions-host/workers/python/3.10/LINUX/X64/azure_functions_worker/utils/wrappers.py", line 49, in call raise extend_exception_message(e, message) File "/azure-functions-host/workers/python/3.10/LINUX/X64/azure_functions_worker/utils/wrappers.py", line 44, in call return func(*args, **kwargs) File "/azure-functions-host/workers/python/3.10/LINUX/X64/azure_functions_worker/loader.py", line 214, in load_function mod = importlib.import_module(fullmodname) File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module return _bootstrap._gcd_import(name[level:], package, level) File "/home/site/wwwroot/GetAuditEvents/__init__.py", line 15, in <module> from azure.storage.blob import BlobServiceClient File "/home/site/wwwroot/.python_packages/lib/site-packages/azure/storage/blob/__init__.py", line 10, in <module> from ._blob_client import BlobClient File "/home/site/wwwroot/.python_packages/lib/site-packages/azure/storage/blob/_blob_client.py", line 59, in <module> from ._download import StorageStreamDownloader File "/home/site/wwwroot/.python_packages/lib/site-packages/azure/storage/blob/_download.py", line 20, in <module> from ._encryption import ( File "/home/site/wwwroot/.python_packages/lib/site-packages/azure/storage/blob/_encryption.py", line 22, in <module> from cryptography.hazmat.primitives.ciphers.aead import AESGCM File "/home/site/wwwroot/.python_packages/lib/site-packages/cryptography/hazmat/primitives/ciphers/aead.py", line 10, in <module> from cryptography.hazmat.backends.openssl import aead File "/home/site/wwwroot/.python_packages/lib/site-packages/cryptography/hazmat/backends/openssl/__init__.py", line 6, in <module> from cryptography.hazmat.backends.openssl.backend import backend File "/home/site/wwwroot/.python_packages/lib/site-packages/cryptography/hazmat/backends/openssl/backend.py", line 113, in <module> from cryptography.hazmat.bindings.openssl import binding File "/home/site/wwwroot/.python_packages/lib/site-packages/cryptography/hazmat/bindings/openssl/binding.py", line 14, in <module> from cryptography.hazmat.bindings._openssl import ffi, lib
27/08/2024, 09:10:00
Error
Executed 'Functions.GetAuditEvents' (Failed, Id=28ffa5ef-92aa-45dc-8488-232a55fd93d1, Duration=43ms)
27/08/2024, 09:10:00
Error
Result: Failure Exception: ModuleNotFoundError: No module named '_cffi_backend'. Cannot find module. Please check the requirements.txt file for the missing module. For more info, please refer the troubleshooting guide: https://aka.ms/functions-modulenotfound. Current sys.path: ['/tmp/functions\\standby\\wwwroot', '/home/site/wwwroot/.python_packages/lib/site-packages', '/azure-functions-host/workers/python/3.10/LINUX/X64', '/usr/local/lib/python310.zip', '/usr/local/lib/python3.10', '/usr/local/lib/python3.10/lib-dynload', '/usr/local/lib/python3.10/site-packages'] Stack: File "/azure-functions-host/workers/python/3.10/LINUX/X64/azure_functions_worker/dispatcher.py", line 479, in _handle__function_load_request func = loader.load_function( File "/azure-functions-host/workers/python/3.10/LINUX/X64/azure_functions_worker/utils/wrappers.py", line 49, in call raise extend_exception_message(e, message) File "/azure-functions-host/workers/python/3.10/LINUX/X64/azure_functions_worker/utils/wrappers.py", line 44, in call return func(*args, **kwargs) File "/azure-functions-host/workers/python/3.10/LINUX/X64/azure_functions_worker/loader.py", line 214, in load_function mod = importlib.import_module(fullmodname) File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module return _bootstrap._gcd_import(name[level:], package, level) File "/home/site/wwwroot/GetAuditEvents/__init__.py", line 15, in <module> from azure.storage.blob import BlobServiceClient File "/home/site/wwwroot/.python_packages/lib/site-packages/azure/storage/blob/__init__.py", line 10, in <module> from ._blob_client import BlobClient File "/home/site/wwwroot/.python_packages/lib/site-packages/azure/storage/blob/_blob_client.py", line 59, in <module> from ._download import StorageStreamDownloader File "/home/site/wwwroot/.python_packages/lib/site-packages/azure/storage/blob/_download.py", line 20, in <module> from ._encryption import ( File "/home/site/wwwroot/.python_packages/lib/site-packages/azure/storage/blob/_encryption.py", line 22, in <module> from cryptography.hazmat.primitives.ciphers.aead import AESGCM File "/home/site/wwwroot/.python_packages/lib/site-packages/cryptography/hazmat/primitives/ciphers/aead.py", line 10, in <module> from cryptography.hazmat.backends.openssl import aead File "/home/site/wwwroot/.python_packages/lib/site-packages/cryptography/hazmat/backends/openssl/__init__.py", line 6, in <module> from cryptography.hazmat.backends.openssl.backend import backend File "/home/site/wwwroot/.python_packages/lib/site-packages/cryptography/hazmat/backends/openssl/backend.py", line 113, in <module> from cryptography.hazmat.bindings.openssl import binding File "/home/site/wwwroot/.python_packages/lib/site-packages/cryptography/hazmat/bindings/openssl/binding.py", line 14, in <module> from cryptography.hazmat.bindings._openssl import ffi, lib

**Comment by v-sudkharat** [comment]
Hi @katerobson08, it due to the python version you have selected into the function app which is Python version 10. Please update it to Python version 11 and check once. I hope this will resolve your issue. 
If you still get issue, we can connect over call and check for it.

Many Thanks!

**Comment by katerobson08** [comment]
Hi,
Got it working now.  I had went back to trying other versions and it was sitting at 3.10, so have changed back to 3.11, when I unzipped the package and seen that it was version 3.11 for the cffi file.

Kate

**Comment by katerobson08** [comment]
haha just seen your comment

**Comment by katerobson08** [comment]
There are 3 other mimecast function apps, I think they will need changed too
MimecastSEG
MimecastTIRegional
MimecastTTP

**Comment by v-sudkharat** [comment]
> There are 3 other mimecast function apps, I think they will need changed too MimecastSEG MimecastTIRegional MimecastTTP

yes, we are activity working on those solutions as well.

**Comment by v-sudkharat** [comment]
> Hi, Got it working now. I had went back to trying other versions and it was sitting at 3.10, so have changed back to 3.11, when I unzipped the package and seen that it was version 3.11 for the cffi file.
> 
> Kate

So, Happy to hear that your issue has been resolved. So, with you confirmation can we close this issue from GitHub?

**Comment by katerobson08** [comment]
Yes thank you for your quick response <3
