### ISSUE TITLE
Unable to open Custom logs via AMA dataconnector

### ISSUE THREAD

**Issue by thom2804** [Azure/Azure-Sentinel#11012]
I just installed the Custom Logs AMA solution in my environment, and I am trying to configure the corresponding data connector however I am getting the following error:
![image](https://github.com/user-attachments/assets/c3e2c402-7cdd-4af8-a233-4a77e512cff2)

Am I missing something? I did no extra steps besides installing the solution.

**Comment by v-sudkharat** [comment]
Hi @thom2804, Thanks for flagging this issue, we will investigate this issue and get back to you with some updates. Thanks!

**Comment by thom2804** [comment]
Update: I tried again today and now it seems to appear correctly in my data connectors and I can also configure an DCR rule without issues, seems like it needed some time to appear...

**Comment by v-sudkharat** [comment]
Thanks for the update @thom2804, So, closing this issue. If you still need support for this issue, feel free to re-open it any time. Thank you for your co-operation.
