### ISSUE TITLE
Azure Sentinel Solution Defender XDR missing fields in table DeviceProcessEvent

### ISSUE THREAD

**Issue by MikeP324** [Azure/Azure-Sentinel#11034]
**Describe the bug**
The Azure Sentinel Solution Defender XDR is missing the following fields in the table DeviceProcessEvent.

- IsInitiatingProcessRemoteSession
- InitiatingProcessRemoteDeviceName
- InitiatingProcessRemoteSessionIP
- InitiatingProcessUnqiueID

**To Reproduce**
1. Using Defender AH, review the schema for table DeviceProcessEvent.
2. Using Sentinel logs view, review the schema for table DeviceProcess event.
3. Note the missing fields.

**Expected behavior**
The fields should be present, having these fields would assist in using Sentinel for searching for RDP sessions.

**Comment by v-rusraut** [comment]
Hi @MikeP324 , Thanks for flagging this issue, we will investigate this issue and get back to you with some updates by 05-09-2024. Thanks!

**Comment by v-rusraut** [comment]
Hi @MikeP324,

Please share the schema definition of table  `DeviceProcessEvents` from both Defender Portal and Sentinel side to below email id.
Email ID : v-rusraut@microsoft.com
Please refer below query to get schema definition

```
DeviceProcessEvents
| getschema 
```

Thanks

**Comment by v-rusraut** [comment]
Hi @MikeP324,
There is no column present with name 'InitiatingProcessRemoteDeviceName' at Defender side.
Are you referring column 'InitiatingProcessRemoteSessionDeviceName' ?

**Comment by MikeP324** [comment]
Hi @v-rusraut, just checked and it was a typo on my part. 

The correct column is 'InitiatingProcessRemoteSessionDeviceName'.

**Comment by v-rusraut** [comment]
Hi @MikeP324, could you please open support case in azure portal, so our support team can check on you issue and if required connect with respective teams. Please let us know, once you open the case, so we close from GitHub.

**Comment by v-rusraut** [comment]
Hi @MikeP324,
Thanks for your response, so currently closing this issue. If you still need support for this issue, feel free to re-open at any time. Thank you for your co-operation.
