### ISSUE TITLE
Logic App failure with "An action failed. No dependent actions succeeded "  and Bad request in Http

### ISSUE THREAD

**Issue by Raj4IBM** [Azure/Azure-Sentinel#11043]
Hi team im getting Logic app failure issue in my Logic app with this error  "An action failed. No dependent actions succeeded "  and Bad request in Http  
<img width="307" alt="image" src="https://github.com/user-attachments/assets/bbaaff20-399a-4d0b-9a82-b48ab3f99cf9">

**Comment by v-sudkharat** [comment]
Hey @Raj4IBM, Could you please share the solution/ playbook name is which your getting issue, and please provide the detailed description to understand the issue.

**Comment by Raj4IBM** [comment]
> v-sudkharat

I dont know about the playbook you are asking .

This issue we are getting when our logic app is sending the alert to one of the API and getting this above error .

**Comment by v-sudkharat** [comment]
Hi @Raj4IBM, Could you please open support case in azure portal, so our support team can check on you issue and if required connect with respective teams.
Please let us know, once you open the case, so we close from GitHub
 Thanks!

**Comment by v-sudkharat** [comment]
Hi @Raj4IBM, Gentle Reminder: We are waiting for your response on this issue. If you still need to keep this issue active, please respond to it in the next 2 days. If we don't receive a response by 04-09-2023 date, we will be closing this issue. 		
Thanks!

**Comment by v-sudkharat** [comment]
Hi @Raj4IBM, since we have not received a response in the last 5 days, we are closing your issue as per our standard operating procedures. If you still need support for this issue, feel free to re-open at any time. Thank you for your co-operation.
