### ISSUE TITLE
Custom logs via AMA (Preview) - DCR rule name length should be 32 characters or less.

### ISSUE THREAD

**Issue by saahilverma** [Azure/Azure-Sentinel#11053]
I have installed the latest Custom logs via AMA, WHILE Creating the DCR It is giving the error of name length to 32 characters max.

I am attaching the error message screenshot here.
You give any length on DCR name it is giving same error message 
![IMG_20240830_105839](https://github.com/user-attachments/assets/d985fcb2-b37b-4a3a-bf31-c95b2574ad64)

![IMG_20240830_111707__01](https://github.com/user-attachments/assets/1eb12726-ce18-42c7-8f54-e3ce35add7df)

**Additional context**

**Comment by v-rusraut** [comment]
Hi @saahilverma,
Our respective team is working on to fix this issue, we will update you once issue fixed.
Thanks

**Comment by v-rusraut** [comment]
Hi @saahilverma,
This length issue is resolved now, please check and let us know that you are able to create DCR.
Thanks

**Comment by v-rusraut** [comment]
Hi @saahilverma , Gentle Reminder: We are waiting for your response on this issue. If you still need to keep this issue active, please respond to it in the next 2 days. If we don't receive a response by 11-09-2024 date, we will be closing this issue.

**Comment by v-sudkharat** [comment]
@saahilverma , Could you please verify once :- 
![image](https://github.com/user-attachments/assets/434ca635-41c5-4d3f-a1b9-a4e1ea627076)

We tried from our end and able to create.

**Comment by saahilverma** [comment]
Do I need to update the app to get the fix? It seems it was v1.0Preview and now its 3.0.

Preview is deleted from store.

Even if I have to update, I gave it a try, reinstalled and uninstall and installed again, it is still pushing 1.0 version from store.

**Comment by v-sudkharat** [comment]
@saahilverma, Yes, please update the existing solution version to 3.0.0 latest one, and try to configure the DCR:-
![image](https://github.com/user-attachments/assets/514ea213-5abc-4406-8a36-744c30d78f91)

Please let us know if you face same issue while creating the DCR. Thanks!

**Comment by saahilverma** [comment]
![IMG_6757](https://github.com/user-attachments/assets/5bcc133c-51ee-4df8-939b-d5f0fec0f9ba)
@v-sudkharat Next problem is app is not getting update. 
![IMG_6756](https://github.com/user-attachments/assets/e4332592-05e7-49bd-89da-92f7f6ae6ce7)


I tried to reinstall, Delete and install from scratch...All possible option. 
Its still loading v1.0 again and again.

**Comment by v-sudkharat** [comment]
@saahilverma, The 3.0.0 version is the correct one, now please try to create the DCR and let us know of you get the same issue. 
OR please share your mail id with us, so we can connect via a call and understand the issue. Thanks!

**Comment by saahilverma** [comment]
@v-sudkharat my email is mentioned in the attachment.


![IMG_6760](https://github.com/user-attachments/assets/3d686211-1898-4d96-8852-55016dd2a13c)

**Comment by v-sudkharat** [comment]
@saahilverma, Thanks!

**Comment by v-rusraut** [comment]
Hi @saahilverma, as discussed over email, are you able to create the DCR, or are you still facing issues?

**Comment by saahilverma** [comment]
Hi,

I was away, tomorrow I am going back to work and will confirm back.



Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by v-rusraut** [comment]
Hi @saahilverma,
We are waiting for response.
Thanks

**Comment by saahilverma** [comment]
Have replied from work email with some new challenge.


Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by v-rusraut** [comment]
Hi @saahilverma, as discussed over email you are able to create DCR, now you are getting issue related to logs not picked up.
To check this issue, need back-end access, please open support case in azure portal, so our support team can check on you issue and if required connect with respective teams. currently closing this issue. If you still need support for this issue, feel free to re-open at any time. Thank you for your co-operation.
