### ISSUE TITLE
Ingestion of CloudWatch Data to Sentinel using Lambda function and S3

### ISSUE THREAD

**Issue by VasDju** [Azure/Azure-Sentinel#11078]
DataConnectors/AWS-S3/CloudWatchLambdaFunction_V2.py and DataConnectors/AWS-S3/CloudWatchLambdaFunction.py issue of ingesting logs. When Lambda code is triggered i receive errors.

More in depth: https://techcommunity.microsoft.com/t5/microsoft-sentinel/ingestion-of-aws-cloudwatch-data-to-microsoft-sentinel-using-s3/m-p/4232203

Error:
 Response {   "errorMessage": "Unable to import module 'lambda_function': Error importing numpy: you should not try to import numpy from\n        its source directory; please exit the numpy source tree, and relaunch\n        your python interpreter from there.",   "errorType": "Runtime.ImportModuleError",   "requestId": "",   "stackTrace": [] }

**Comment by v-sudkharat** [comment]
Hi @VasDju, Thanks for flagging this issue, we will investigate this issue and get back to you with some updates. Thanks!

**Comment by v-sudkharat** [comment]
Hi @VasDju, Could you please try with below steps and let us know if it helps you to resolve this issue: 
1. Click on Layers: 
![image](https://github.com/user-attachments/assets/958d406c-1024-4d70-873a-33b8be8f1191)

2. Click on Add a layer: 
![image](https://github.com/user-attachments/assets/2a70bf60-8a6c-4be9-8c60-581180a172e6)

3. Select below configuration and Add: 
![image](https://github.com/user-attachments/assets/8a2e471c-2097-4580-a044-8425538867af)

And Test your Function again. Thanks!

**Comment by v-sudkharat** [comment]
Hi @VasDju, Waiting for your response on above comment.

**Comment by v-sudkharat** [comment]
Hi @VasDju, Gentle Reminder: We are waiting for your response on this issue. If you still need to keep this issue active, please respond to it in the next 2 days. If we don't receive a response by 02-10-2024 date, we will be closing this issue. 		
Thanks!

**Comment by v-sudkharat** [comment]
Hi @VasDju, since we have not received a response in the last 5 days, we are closing your issue as per our standard operating procedures. If you still need support for this issue, feel free to re-open at any time. Thank you for your co-operation.
