### ISSUE TITLE
GCP Sentinel Audit Log - Org or Project Level

### ISSUE THREAD

**Issue by capcglenn** [Azure/Azure-Sentinel#11091]
**Describe the bug**
We get an authentication error in multiple environments when setting up the connector. We are setting up the account at the project level and we were wondering if it is because we aren't setting it up at the org level.

Connectivity check failed: Status code:GCPB40001, Message: An unknown exception resulted in the failure to authenticate: Google.Apis.Requests.RequestError
Permission 'iam.serviceAccounts.getAccessToken' denied on resource (or it may not exist). [403]
Errors [
	Message[Permission 'iam.serviceAccounts.getAccessToken' denied on resource (or it may not exist).] Location[ - ] Reason[forbidden] Domain[global]
]
 (Code: BadRequest)

**To Reproduce**
Create a new connector to the service account in Google Cloude

**Expected behavior**
Authentication and Authorization.

**Additional context**
We have used TF scripts and manually with similar outcome. We were curious if people have had org policies that conflict.  We have double and tripled checked service account roles, workloadID pool settings and have reviewed our logs:

INFO 2024-09-07T01:07:24.502362498Z [protoPayload.serviceName: sts.googleapis.com] [protoPayload.methodName: google.identity.sts.v1.SecurityTokenService.ExchangeToken] [protoPayload.resourceName: projects/777654301107/locations/global/workloadIdentityPools/0d1e47cc960b457682cce3e94f5e83bf/providers/sentinel-identity-provider] audit_log, method: "google.identity.sts.v1.SecurityTokenService.ExchangeToken", principal_email: ""
  {
    "protoPayload": {
      "@type": "type.googleapis.com/google.cloud.audit.AuditLog",
      "status": {},
      "authenticationInfo": {
        "principalSubject": "776d3614-faed-406c-8b18(SNIP)
      },
      "requestMetadata": {
        "callerIp": "20.15.135.0",
        "callerSuppliedUserAgent": "google-api-dotnet-client/1.56.0.0 (gzip)",
        "requestAttributes": {
          "time": "2024-09-07T01:07:24.510179474Z",
          "auth": {}
        },
        "destinationAttributes": {}
      },
      "serviceName": "sts.googleapis.com",
      "methodName": "google.identity.sts.v1.SecurityTokenService.ExchangeToken",
      "authorizationInfo": [
        {
          "permission": "sts.identityProviders.checkLogging",
          "permissionType": "ADMIN_READ"
        }
      ],
      "resourceName": "projects/777654301107/locations/global/workloadIdentityPools/(SNIP)/providers/sentinel-identity-provider",
      "request": {
        "requestedTokenType": "urn:ietf:params:oauth:token-type:access_token",
        "grantType": "urn:ietf:params:oauth:grant-type:token-exchange",
        "audience": "//iam.googleapis.com/projects/(SNIP)/locations/global/workloadIdentityPools/(SNIP/providers/sentinel-identity-provider",
        "@type": "type.googleapis.com/google.identity.sts.v1.ExchangeTokenRequest",
        "subjectTokenType": "urn:ietf:params:oauth:token-type:jwt"
      },
      "metadata": {
        "mapped_principal": "principal://iam.googleapis.com/projects/777654301107/locations/global/workloadIdentityPools/(SNIPf/subject/(SNIP)",
        "@type": "type.googleapis.com/google.identity.sts.v1.AuditData"
      }
    },
    "insertId": "1accog8d1j7h",
    "resource": {
      "type": "audited_resource",
      "labels": {
        "project_id": "gcp-everest-gemini",
        "method": "google.identity.sts.v1.SecurityTokenService.ExchangeToken",
        "service": "sts.googleapis.com"
      }
    },
    "timestamp": "2024-09-07T01:07:24.502362498Z",
    "severity": "INFO",
    "logName": "projects/gcp-everest-gemini/logs/cloudaudit.googleapis.com%2Fdata_access",
    "receiveTimestamp": "2024-09-07T01:07:24.733036774Z"
  }

**Comment by v-sudkharat** [comment]
Hey @capcglenn, Could you please check with the below steps which shared by our team for the cx which facing same issue's: -https://github.com/Azure/Azure-Sentinel/issues/9687#issuecomment-2063335515

Please let us know if it helps you to resolve this issue. Thanks!

**Comment by v-sudkharat** [comment]
Hi @capcglenn, Could you please check on above comment and let us know your response.

**Comment by capcglenn** [comment]
I didn't see any steps provided. We ended up using a shell script and got it working. Thank you for working on this.
