### ISSUE TITLE
Exchange Admin Audit Logs Parser uses CSV in individual users Github report?

### ISSUE THREAD

**Issue by leighcurranTW** [Azure/Azure-Sentinel#11095]
I'm not sure if this is supposed to be like this but I noticed the parser ExchangeAdminAuditLogs.yaml points to a CSV here: https://raw.githubusercontent.com/nlepagnez/ESI-PublicContent/main/Operations/Watchlists/CmdletWatchlist.csv

![image](https://github.com/user-attachments/assets/268bd8a0-3890-4637-9554-ab53a4bd6d2b)

Should it be moved into the Sentinel repo? What happens if it moves or is deleted from the users repo, does the parse stop working for everyone?

**Comment by v-sudkharat** [comment]
Hi @leighcurranTW, Thanks for raising your query with us. We have shared this issue with Repo author where the RAW link has redirected, and we are checking with him if any plan to move that file into this repository, and we will update you here once it gets done and also link the PR to this issue. 
So, as of now, closing this issue. If you still need support for this issue, feel free to re-open it any time. Thank you for your co-operation.
