### ISSUE TITLE
Minified React error when trying to view a Watchlist

### ISSUE THREAD

**Issue by CG-JuanVG** [Azure/Azure-Sentinel#11104]
**Describe the bug**
When trying to view a watchlist, a Minified React error occurs when rendering the Watchlist view on the Azure Portal.

**To Reproduce**
1. Go to the Sentinel Blade
2. Click on a Workspace that has a Watchlist
3. Scroll down to Watchlist on the left and click on it
4. Click on a Watchlist

**Expected behavior**
I'm expecting the Azure Portal to render the page for this Watchlist correctly, so that I can then press the edit button for example and view the data or make changes.

**Screenshots**
![image](https://github.com/user-attachments/assets/6b333283-f746-41a5-889f-b7a558583f17)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser FireFox
 - Version 130.0 (64-bit

**Smartphone (please complete the following information):**
 - Device: N/A
 - OS: N/A
 - Browser N/A
 - Version N/A

**Additional context**
We had theorized that this issue might occur if you delete a Watchlist, and then create a new one with the same name. This doesn't seem to be the case. All these Watchlists are created via automation. I have a Logic App that creates these watchlists and updates them.
When I use the developer console in FireFox I can see that the Watchlist data is being returned by the Azure Management API, but the Console shows the Minified React error when attempting to render the page. This issue seems to be limited to the Watchlists that are created by my automation.

**Comment by v-rusraut** [comment]
Hi @CG-JuanVG, Thanks for flagging this issue, we will investigate this issue and get back to you with some updates. Thanks!

**Comment by v-rusraut** [comment]
Hi @CG-JuanVG, please open support case in azure portal, so our support team can check on this issue and if required connect with respective teams. so currently closing this issue. If you still need support for this issue, feel free to re-open at any time. Thank you for your co-operation.
