### ISSUE TITLE
EventData is not always parsed

### ISSUE THREAD

**Issue by truekonrads** [Azure/Azure-Sentinel#1110]
**Describe the bug**
The EventData such as IpAddress and Status for events 4678, 4679 isn't always parsed into columns. Data is ingested using stock Windows Sentinel agent.

![image](https://user-images.githubusercontent.com/1421150/94101578-b5e2a100-fe62-11ea-8d3b-8ea3e840a784.png)

**To Reproduce**
```
let d=SecurityEvent
| where 
    EventID in (4768,4769)
| extend oIP=IpAddress,oStatus=Status, eventData=parse_xml(EventData)
| extend 
    IpAddress=iff(IpAddress=='',eventData['EventData']['Data'][6]['#text'],IpAddress),
    Status=iff(Status=='',eventData['EventData']['Data'][8]['#text'],IpAddress)
| project EventID, oStatus,Status,oIP,IpAddress;
d 
| where oStatus=='' or oIP==''|take 5
| union (d |where oStatus!='' or oIP!=''|take 5)
```

**Expected behavior**
EventData is parsed consistently on ingestion

**Comment by ashwin-patil** [comment]
Hi @truekonrads 

The structure of 4768 and 4769 is different hence IpAddress is appearing in different order.

- For 4768 - it will be in `eventData['EventData']['Data'][9]['#text']`
- For 4769 it will be in `eventData['EventData']['Data'][9]['#text']`.

If you need to use both event Ids in single query and extract IpAddress, here is a bit complicated query which does the same. 

It dynamically extracts key vaule pairs and make json object.  You can add additional fields in the final project.

Although this can be computationally expensive if your input data is too big, so **strongly recommended to use with time and Event ID filters** .

```
SecurityEvent
| where TimeGenerated > ago(4h)
| where 
    EventID in (4768,4769)
| limit 500 
| extend EventData = parse_xml(EventData).EventData.Data
| mv-expand bagexpansion=array EventData
| extend EventName=tostring(EventData['@Name']), EventValue=EventData['#text']
| evaluate pivot(EventName, any(EventValue), TimeGenerated, EventID)
| project TimeGenerated, EventID, IpAddress
```

Sample Parsed Output with consistent IpAddress value populated:

![image](https://user-images.githubusercontent.com/11397335/94322738-24e5f580-ff48-11ea-9be5-607b3f86e7e8.png)

**Comment by truekonrads** [comment]
@ashwin-patil  thanks for the work-around; however the bug was that this field should be _consistently_ parsed on ingestion not that it is possible to re-parse it. As you can clearly see from the sample query and data, the IpAddress field does not appear in columns at all for some 4769 messages, beause this field is absent from the entry.

**Comment by ashwin-patil** [comment]
Will update as we hear more on the normalization and updates to Azure monitoring agent. 
For now tagging as enhancement and closing.
