### ISSUE TITLE
Feature/Solution/Alternatives

### ISSUE THREAD

**Issue by Hanzhafiz** [Azure/Azure-Sentinel#11109]
**Feature request for Microsoft Designer related to a problem? My app Microsoft Designer can't not be opened and log-in to soft and fix my problem. Ex. I'm always frustrated when [...] Describe the solution you'd like a clear and concise description of any alternative solutions or features you've considered**

**zhanzhafiz5@gmail.com**

**Comment by Hanzhafiz** [comment]
@Hanzhafiz

**Comment by Hanzhafiz** [comment]
```

```Feature request for Microsoft Designer related to a problem? My app Microsoft Designer can't not be opened and log-in to soft and fix my problem. Ex. I'm always frustrated when [...] Describe the solution you'd like a clear and concise description of any alternative solutions or features you've considered

zhanzhafiz5@gmail.com 
```

**Comment by v-sudkharat** [comment]
Hi @Hanzhafiz, this issue is not related to Microsoft Sentinel. Can you raise a Microsoft support request for this? closing this issue. If you still need support for this issue, feel free to re-open it any time. Thank you for your co-operation.

**Comment by Hanzhafiz** [comment]
> Hi @Hanzhafiz, this issue is not related to Microsoft Sentinel. Can you raise a Microsoft support request for this? closing this issue. If you still need support for this issue, feel free to re-open it any time. Thank you for your co-operation.
