### ISSUE TITLE
The Deployment fails in 3 different environments with different configuration on the same point - enableSolutionAndAlerts - Create-NewSolutionAndRulesFromList.ps1: line 44

### ISSUE THREAD

**Issue by WVDAdminTF** [Azure/Azure-Sentinel#11111]
**Describe the bug**

The resource write operation failed to complete successfully, because it reached terminal provisioning state 'failed'. (Code: ResourceDeploymentFailure)
The provided script failed with the following error:
Microsoft.PowerShell.Commands.HttpResponseException: Response status code does not indicate success: 400 (Bad Request).
   at System.Management.Automation.MshCommandRuntime.ThrowTerminatingError(ErrorRecord errorRecord)
at <ScriptBlock>, /mnt/azscripts/azscriptinput/Create-NewSolutionAndRulesFromList.ps1: line 44
at <ScriptBlock>, <No file>: line 1
at <ScriptBlock>, /mnt/azscripts/azscriptinput/DeploymentScript.ps1: line 310. Please refer to
https://aka.ms/DeploymentScriptsTroubleshoot
for more deployment script information. (Code: DeploymentScriptError)

**To Reproduce**
Simply deploy the Template it WILL fail.

**Expected behavior**
The resource write operation failed to complete successfully, because it reached terminal provisioning state 'failed'. (Code: ResourceDeploymentFailure)
The provided script failed with the following error:
Microsoft.PowerShell.Commands.HttpResponseException: Response status code does not indicate success: 400 (Bad Request).
   at System.Management.Automation.MshCommandRuntime.ThrowTerminatingError(ErrorRecord errorRecord)
at <ScriptBlock>, /mnt/azscripts/azscriptinput/Create-NewSolutionAndRulesFromList.ps1: line 44
at <ScriptBlock>, <No file>: line 1
at <ScriptBlock>, /mnt/azscripts/azscriptinput/DeploymentScript.ps1: line 310. Please refer to
https://aka.ms/DeploymentScriptsTroubleshoot
for more deployment script information. (Code: DeploymentScriptError)

**Please refer the Screenshot,** @pemontto 

**Screenshots**
Environment 1
![image](https://github.com/user-attachments/assets/bd3c8472-5d16-44e7-9681-55f6a0092f2b)

Environment 2
![image](https://github.com/user-attachments/assets/3b2118c7-e552-4650-95d8-366a3e819e8a)

**Desktop (please complete the following information):**
Azure Portal

**Smartphone (please complete the following information):**
-

**Additional context**
-

**Comment by WVDAdminTF** [comment]
Dear @v-rusraut   @v-sudkharat  please can you let me know if there is any update on the same

**Comment by v-sudkharat** [comment]
Hi @WVDAdminTF, Could you please provide more info about the in which sentinel solution or its content the deployment is failing?

**Comment by WVDAdminTF** [comment]
Hi @v-sudkharat could you please be more specific what you would like apart from the information already shared that your repo - https://github.com/Azure/Azure-Sentinel/blob/master/Tools/Sentinel-All-In-One/v2/Scripts/**Create-NewSolutionAndRulesFromList.ps1**

**ps1 file line 44** - is causing the deployment to fail.
![image](https://github.com/user-attachments/assets/d82e9b83-79f8-4b8f-8785-90194fd1907d)

Please can you deploy the template and confirm that it is working with a screenshot.

**Comment by v-sudkharat** [comment]
Hi @WVDAdminTF, Are your deploying below ARM template? - https://portal.azure.com/#create/Microsoft.Template/uri/https%3A%2F%2Fraw.githubusercontent.com%2FAzure%2FAzure-Sentinel%2Fmaster%2FTools%2FSentinel-All-In-One%2Fv2%2Fazuredeploy.json/createUIDefinitionUri/https%3A%2F%2Fraw.githubusercontent.com%2FAzure%2FAzure-Sentinel%2Fmaster%2FTools%2FSentinel-All-In-One%2Fv2%2FcreateUiDefinition.json

For this ARM template we are having authentication error due to some permissions.

**Comment by garybushey** [comment]
This was due to some change so that the Get-AzContext did not return the SubscriptionId.   Changes have been made to fix this as well as add a delay so that the managed identity's permissions get fully distributed.   The changes in the pipeline to get accepted.

**Comment by WVDAdminTF** [comment]
Hi @garybushey,

Thank you for the update.  I will execute the same and let you know if the Deployment completes

**Comment by v-sudkharat** [comment]
@WVDAdminTF, Please let us know once it done. Thanks!

**Comment by v-sudkharat** [comment]
Hi @WVDAdminTF, Did you get a chance to check on above suggestion?

**Comment by v-sudkharat** [comment]
Hi @WVDAdminTF, Gentle Reminder: We are waiting for your response on this issue. If you still need to keep this issue active, please respond to it in the next 2 days. If we don't receive a response by 22-10-2024 date, we will be closing this issue. 		
Thanks!

**Comment by v-sudkharat** [comment]
Hi @WVDAdminTF, since we have not received a response in the last 5 days, we are closing your issue as per our standard operating procedures. If you still need support for this issue, feel free to re-open at any time. Thank you for your co-operation.

**Comment by JelaniB-sec** [comment]
My we reopen this issue? I am failing at the exact same point.

**Comment by JelaniB-sec** [comment]
@v-sudkharat

**Comment by JelaniB-sec** [comment]
My we reopen this issue? I am failing at the exact same point. @v-sudkharat

**Comment by a-balde** [comment]
The fix for this issue has still not been deployed to the Sentinel public repo, and deploying the template to Azure is still failing with this error. To replicate the issue, select 'Azure Activity' as Content Hub Solution and Data connector, leaving all other settings as default. The 'deployRules' resource will fail, and the Azure Activity solution wont be installed. Any update on deploying the changes mentioned by @garybushey ?
