### ISSUE TITLE
I can not open link in HuntingQuery/AWSCloudTrail

### ISSUE THREAD

**Issue by ql3xHd630** [Azure/Azure-Sentinel#11123]
I can not open link in HuntingQuery/AWSCloudTrail

https://github.com/Azure/Azure-Sentinel/blob/master/Solutions/Amazon%Web%Services/Hunting%Queries/AWS_SuspiciousCredentialTokenAccessOfValid_IAM_Roles.yaml
![image](https://github.com/user-attachments/assets/f6bbcd07-254e-49b3-ba25-bf523df4c9ce)

How can i find this?

**Comment by v-sudkharat** [comment]
Hi @ql3xHd630, can you please check with this link -https://github.com/Azure/Azure-Sentinel/blob/master/Solutions/Amazon%20Web%20Services/Hunting%20Queries/AWS_SuspiciousCredentialTokenAccessOfValid_IAM_Roles.yaml

Thanks!

**Comment by ql3xHd630** [comment]
Hi, these link work well. thanks

**Comment by v-sudkharat** [comment]
@ql3xHd630, thanks for the response.
