### ISSUE TITLE
Need Data Connected for Unsupported Log Sources in Azure Sentinel 

### ISSUE THREAD

**Issue by siftain** [Azure/Azure-Sentinel#1114]
Looking for Data Connector or Integration baseline document for below log sources type. Have verified portal and below data connector is missing. Request you to share if any custom data connector available or  baseline document for integrating these log sources in Azure Sentinel SIEM solution. 

1. FireEy log management integration (Sandboxing/NIPS)
2. Attivo (Deception) 
3. Patch management including Ivanti EPM (Patch Management)
4. SAP application interface with Microsoft Sentinel based integrator (SAP Application)
5. Tenable Vulnerable Management (Vulnerability management)

**Comment by preetikr** [comment]
Thanks, @siftain - we'll factor this in our roadmap. I've a few questions.

1. Re Attivo, what specific logs are you looking for from which Attivo products?
2. Re Ivanti, are these logs from Ivanti Unified Endpoint Management? Any specific logs from this?
3. SAP application interface - what are the scenarios for this? Is this SAP logs or some other integration?

Thanks,
Preeti

**Comment by preetikr** [comment]
@siftain Closing this due to no response. Please reactivate once you have responses.
