### ISSUE TITLE
VMware ESXi logs Ingestion into Sentinel

### ISSUE THREAD

**Issue by casecasr** [Azure/Azure-Sentinel#11143]
Hi Folks,

With the VCenter ESXi connector deprecated. Could you kindly provide link to documentation on how ESXi could be integrated into Sentinel?

Thx,
Muid

**Comment by v-rusraut** [comment]
Hi @casecasr,
VMware ESXi solution is dependent on the Syslog solution containing the Syslog via AMA connector to collect the logs.
So now you need to use Syslog via AMA connector.
Please refer solution description of VMWareESXi solution.

![1](https://github.com/user-attachments/assets/67b3e17b-bdd9-49cf-a419-d6153c3c4d59)

Thanks

**Comment by v-rusraut** [comment]
Hi @casecasr,
Please confirm that are you able to integrate VMware ESXi solution.
Thanks

**Comment by v-rusraut** [comment]
Hi @casecasr, Gentle Reminder: We are waiting for your response on this issue. If you still need to keep this issue active, please respond to it in the next 2 days. If we don't receive a response by 27-09-2024 date, we will be closing this issue.
Thanks!

**Comment by casecasr** [comment]
Hi @v-rusraut ,

Apologies for my late response.  I've been away. This is quite helpful.

I have put in a CR and I believe it should be straight forward. 

Thanks for helping out with this.

You may close this case.

**Comment by v-rusraut** [comment]
Hi @casecasr,
Thanks for your response, closing this issue now. If you still need support for this issue, feel free to re-open it any time. Thank you for your co-operation
