### ISSUE TITLE
Armis Activity Data Connector Bug

### ISSUE THREAD

**Issue by DiegoCruzVelorciosgroup** [Azure/Azure-Sentinel#11153]
**Describe the bug**
A problem has been detected when deploying the Armis Activity dataconnector.

The bug was found from the previous version of the connector and the current version of the connector.

**To Reproduce**
1. Deploy the Armis Activity data connector (from sentinel or ARM from the repository is indifferent).
2. Within the deployed resources, look for the Application Insights of the connector with nomenclature activityXXXXXXXXXXXXX
3. If we check the failed requests tab each time the functionapp fails to run.

**Expected behavior**
Data should be stored in the table.

**Possible solution**
After reviewing the error it seems to be found in the __init__.py file of the functionapp code that the connector is downloaded from the sentinel repository.

The error seems to be related to the Armis Api that can process all activities on the platform. 
Line 212 of the script is giving problems.
To solve it we have added a parameter timeFrame with value of “1 Days” avoiding that the api collapses with the request.
![image](https://github.com/user-attachments/assets/a558dc43-e330-45b5-97a3-513a9a79cf03)

` aql_data = '''{} alert:(status:Unhandled,Suppressed,Resolved timeFrame:"1 Days") after:{} '''.format( `

In our repository we leave a version of the zip with the modified code along with the modified arm template to use the code from our repository. 
[Repo](https://github.com/VelorciosGroup/Armis)

**Comment by v-sudkharat** [comment]
Hi @DiegoCruzVelorciosgroup, This Armis solution is partner supported, so we are not authorized to make modification into it. We kindly request you to raise ticket with Armis so they can look into it and make require changes.
Sharing the Mimecast support link -
Link - https://support.armis.com/
And we have also shared this ticket to Armis solution dev, to check on this issue, they will check on it and if required will update here. 
So, closing this issue. If you still need support for this issue, feel free to re-open it any time. Thank you for your co-operation.

**Comment by v-sudkharat** [comment]
Hey @DiegoCruzVelorciosgroup, Sharing an update, the fix has been added into the PR -https://github.com/Azure/Azure-Sentinel/pull/11011
And it will get release in upcoming solution version. Thanks!
