### ISSUE TITLE
Get DataConnectors API Method Issues

### ISSUE THREAD

**Issue by robertkitching** [Azure/Azure-Sentinel#1115]
Hi,

I am trying to pull all data connector metadata from Azure Sentinel using the below API :

[https://github.com/Azure/azure-rest-api-specs/tree/master/specification/securityinsights/resource-manager/Microsoft.SecurityInsights/preview/2019-01-01-preview/examples/dataConnectors](https://github.com/Azure/azure-rest-api-specs/tree/master/specification/securityinsights/resource-manager/Microsoft.SecurityInsights/preview/2019-01-01-preview/examples/dataConnectors)

I receive a response but it seems that not all connectors are included? Examples of missing connectors are Syslog, Firewall etc though these do appear within the Portal.

Can you advise if this is expected or suggest a different endpoint to obtain this data?

Cheers,
Rob

**Comment by treyperrone** [comment]
This is still a large issue now 2 years later. Are there any updates on this front? I can see that many 3rd party connectors might be lagging behind, but even the basic Azure AD data connector isn't something that seems to be triggered with an API call. One would think the MS official DCs would be supported by now.

I am also playing with the newer content hub/solutions method to push out that data connector with API and while i can easily "install" the connector having issues with the enablement portion. the GUI simply links to the normal data connector setup, which really pushes the diagnostics policy over on AAD for any checked boxes. There must some scripted method to push this over.

**Comment by v-amolpatil** [comment]
@robertkitching Please have a look at the updated API Link to [Data Connector -Get](https://learn.microsoft.com/en-us/rest/api/securityinsights/stable/data-connectors/get?tabs=HTTP)

**Comment by v-amolpatil** [comment]
Since we have not received a response in the last 5 days, we are closing your issue #1115 as per our standard operating procedures. If you still need support for this issue, feel free to re-open at any time. Thank you for your co-operation.
