### ISSUE TITLE
Armis Alert Data Connector Bug 

### ISSUE THREAD

**Issue by DiegoCruzVelorciosgroup** [Azure/Azure-Sentinel#11168]
**Describe the bug**
Not all Armis alerts reach Sentinel.

**To Reproduce**
1. Deploy the Armis Alert data connector (from sentinel  (armis solution) or ARM from the repository is indifferent).
2. We perform the following kql query in logs analitic and observe how time jumps are made between alerts.
`ArmisAlerts
| order  by AlertId desc `

![image](https://github.com/user-attachments/assets/3799e1a9-b793-46a2-a5de-c9caf475c353)

**Expected behavior**
Log Analytics receives all the alerts that are on the Armis platform. 

**Additional context**
As far as we know at least persists from the previous version (3.0.3).

We have been looking for a solution to this problem for a couple of weeks, but so far we have not found a solution. We are still investigating.

**Comment by v-sudkharat** [comment]
Hi @DiegoCruzVelorciosgroup, This Armis solution is partner supported, so we are not authorized to make modification into it. We kindly request you to raise ticket with Armis so they can look into it and make require changes.
Sharing the Mimecast support link -
Link - https://support.armis.com/
And we have also shared this ticket to Armis solution dev, to check on this issue, they will check on it and if required will update here. 
So, closing this issue. If you still need support for this issue, feel free to re-open it any time. Thank you for your co-operation.

**Comment by v-sudkharat** [comment]
Hey @DiegoCruzVelorciosgroup, Sharing an update, the fix has been added into the PR -https://github.com/Azure/Azure-Sentinel/pull/11011
And it will get release in upcoming solution version. Thanks!
