### ISSUE TITLE
Duplicate rules

### ISSUE THREAD

**Issue by bittib010** [Azure/Azure-Sentinel#11175]
Duplicate rules in the repo. Find them based on their ID: 
1: 4b11568b-3f5f-4ba1-80c8-7f1dc8390eb7
2: e3d24cfd-b2a1-4ba7-8f80-0360892f9d57

**Comment by bittib010** [comment]
And here are more: 
       3 | c3237d88-fdc4-4dee-8b90-118ded2c507c
       2 | 667e6a70-adc9-49b7-9cf3-f21927c71959
       2 | 67da5c4e-49f2-476d-96ff-2dbe4b855a48
       2 | 85e16874-72aa-4ebe-b36e-e45f8ba50f79
       2 | a6e2afd3-559c-4e88-a693-39c1f6789ef1
       2 | b8508e24-47a6-4f8e-9066-3cc937197e7f
       2 | e7642e6e-cf27-46ec-a4b9-e4475228fead
       2 | ec986fb7-34ed-4528-a5f3-a496e61d8860
       2 | f18c4dfb-4fa6-4a9d-9bd3-f7569d1d685a

**Comment by v-rusraut** [comment]
Hi @bittib010, Thanks for flagging this issue, we will investigate this issue and get back to you with some updates. Thanks!

**Comment by v-rusraut** [comment]
Hi @bittib010,
We have verified all these rules and found that they are not duplicates.

1: 4b11568b-3f5f-4ba1-80c8-7f1dc8390eb7 - This is Analytical Rule
2: e3d24cfd-b2a1-4ba7-8f80-0360892f9d57 - This is Hunting Query

From the list below, one is part of the Solution folder and the other is part of the Hunting folder, and their logic is also different.

3 | c3237d88-fdc4-4dee-8b90-118ded2c507c
2 | 667e6a70-adc9-49b7-9cf3-f21927c71959
2 | 67da5c4e-49f2-476d-96ff-2dbe4b855a48
2 | 85e16874-72aa-4ebe-b36e-e45f8ba50f79
2 | a6e2afd3-559c-4e88-a693-39c1f6789ef1
2 | b8508e24-47a6-4f8e-9066-3cc937197e7f
2 | e7642e6e-cf27-46ec-a4b9-e4475228fead
2 | ec986fb7-34ed-4528-a5f3-a496e61d8860
2 | f18c4dfb-4fa6-4a9d-9bd3-f7569d1d685a

Closing this issue now. If you still need support for this issue, feel free to re-open it any time. Thank you for your co-operation.

**Comment by bittib010** [comment]
I see. Thanks for looking into it. But how about the duplicate guids then? Are they supposed to be the same?
