### ISSUE TITLE
Misplaced query

### ISSUE THREAD

**Issue by bittib010** [Azure/Azure-Sentinel#11170]
**Describe the bug**
This rule is labeled as "kind: Scheduled", is placed inside a Hunting folder and is missing severity. Either it is a scheduled and should have severity set as well as being placed more correctly or it should be changed to a hunting rule. 
Here is the rule: https://github.com/Azure/Azure-Sentinel/blob/534d510ea5d8dc5a853ae3718f8f7188ff2c53a5/Solutions/Windows%20Security%20Events/Hunting%20Queries/ServiceInstallationFromUsersWritableDirectory.yaml#L4

**Comment by v-rusraut** [comment]
Hi @bittib010, Thanks for flagging this issue, we will investigate this issue and get back to you with some updates. Thanks!

**Comment by v-rusraut** [comment]
Hi @bittib010,
There is a mistake in this query. The ‘kind’ field is not required in a hunting query. We have raised a https://github.com/Azure/Azure-Sentinel/pull/11198  PR to remove it.

**Comment by v-rusraut** [comment]
Hi @bittib010,
PR is merged now, closing this issue now. If you still need support for this issue, feel free to re-open it any time. Thank you for your co-operation.
