### ISSUE TITLE
Update isconnected query for Fortinet FortiGate Next-Generation Firewall legacy dataconnector

### ISSUE THREAD

**Issue by thom2804** [Azure/Azure-Sentinel#11178]
Currently, the legacy dataconnector uses the following isconnected query:
```
CommonSecurityLog
| where DeviceVendor == "Fortinet"
| where DeviceProduct startswith "Fortigate"
| summarize LastLogReceived = max(TimeGenerated)
| project IsConnected = LastLogReceived > ago(7d)
```

This query has no filter built in to exclude logs from the AMA connector, so when both dataconnectors are present when creating a connection through the AMA connector where the legacy connector doesn't exist anymore.
I have already created a new query to replace this and filters out results from the AMA agent.

```
let securityLog = 
    CommonSecurityLog
    | where DeviceVendor == "Fortinet"
    | where DeviceProduct startswith "Fortigate"
    | extend ingestion_time = bin(TimeGenerated, 1m)
    | join kind=inner (
        Heartbeat
        | where Category != "Azure Monitor Agent"
        | project TimeGenerated, _ResourceId
        | summarize by _ResourceId, ingestion_time = bin(TimeGenerated, 1m)
    ) on _ResourceId, ingestion_time
    | project-away _ResourceId1, ingestion_time, ingestion_time1
    | summarize LastLogReceived = max(TimeGenerated)
    | project IsConnected = LastLogReceived > ago(7d);
let fallback = datatable(IsConnected: bool)
    [
        false
    ];
securityLog
| union fallback
| summarize IsConnected = max(IsConnected)
```

**Comment by v-sudkharat** [comment]
Hi @thom2804, Thanks for flagging this issue, we will investigate this issue and get back to you with some updates. Thanks!

**Comment by v-sudkharat** [comment]
Hi @thom2804, Is your below query helps you to get disconnect the legacy data connector?  
```
let securityLog = 
    CommonSecurityLog
    | where DeviceVendor == "Fortinet"
    | where DeviceProduct startswith "Fortigate"
    | extend ingestion_time = bin(TimeGenerated, 1m)
    | join kind=inner (
        Heartbeat
        | where Category != "Azure Monitor Agent"
        | project TimeGenerated, _ResourceId
        | summarize by _ResourceId, ingestion_time = bin(TimeGenerated, 1m)
    ) on _ResourceId, ingestion_time
    | project-away _ResourceId1, ingestion_time, ingestion_time1
    | summarize LastLogReceived = max(TimeGenerated)
    | project IsConnected = LastLogReceived > ago(7d);
let fallback = datatable(IsConnected: bool)
    [
        false
    ];
securityLog
| union fallback
| summarize IsConnected = max(IsConnected)
```

**Comment by v-sudkharat** [comment]
Hi @thom2804, I have updated the query in solution template, could you please deploy the below file into your env, and let us know if you're getting expected result : 
Custom Deployment - [CustomDeploymentSteps.docx](https://github.com/user-attachments/files/16782483/CustomDeploymentSteps.docx)
Template file - [mainTemplate.json](https://github.com/user-attachments/files/17256563/mainTemplate.json)

Thanks!

**Comment by v-sudkharat** [comment]
Hi @thom2804, Did you get a chance to deploy the above workaround, waiting for your response. Thanks!

**Comment by v-sudkharat** [comment]
@thom2804, Ok. Thanks!

**Comment by v-sudkharat** [comment]
Hi @thom2804, Thank you for your response. Actually, as of now we can't make this change get available into the content hub as it may affect to other customers who are still using this legacy connector. But we will be noted your point and shared with our respective team on this. 
So, closing this issue. If you still need support for this issue, feel free to re-open it any time. Thank you for your co-operation.
