### ISSUE TITLE
Hunting queries missing version

### ISSUE THREAD

**Issue by bittib010** [Azure/Azure-Sentinel#11174]
As far as my scripting goes for automating IaC rule updates to the ruleset we use, we constantly see the "bug" of missing versioning on a few hunting rules we use. I therefore found all the rules in the repo missing the version and I would love to see them get implemented to the repo, as it makes scripting and auto updating rules based on versioning much easier. A lot of rules has this already set, but most of the hunting rules don't.

I pasted all the rules GUID into this pastebin that are missing version: https://pastebin.com/1STyTcGe

**Comment by v-rusraut** [comment]
Hi @bittib010, Thanks for flagging this issue, we will investigate this issue and get back to you with some updates. Thanks!

**Comment by v-rusraut** [comment]
Hi @bittib010,
Thank you for bringing this to our attention. We have informed the respective team about this request and created a backlog item. We will work on it based on our priority. Currently, there is no ETA associated with it. Currently closing this issue now. If you still need support for this issue, feel free to re-open it any time. Thank you for your co-operation
