### ISSUE TITLE
Subscription Field Fail run Logicapp Get-O365Data

### ISSUE THREAD

**Issue by frigerio-s** [Azure/Azure-Sentinel#1117]
**Describe the bug**
Due to an appdate of logicapp portal it require to update the code .

**Comment by dicolanl** [comment]
Hi @frigerio-s 
Which logic app are you referring too?

**Comment by frigerio-s** [comment]
https://github.com/Azure/Azure-Sentinel/tree/master/Playbooks/Get-O365Data,
i already fixed with a PM
