### ISSUE TITLE
SailPointIdentityNow module import error

### ISSUE THREAD

**Issue by Pathward-MikeM** [Azure/Azure-Sentinel#11179]
**Describe the bug**
The SailPointIdentityNow Connector (https://github.com/Azure/Azure-Sentinel/tree/master/Solutions/SailPointIdentityNow/Data%20Connectors) has a module import error causing the function app to unsuccessfully run. No logs are ingested currently.

**To Reproduce**
Deploy solution, navigate to the function app -> Invocations and review logs of unsuccessful invocations.

**Expected behavior**
All modules import successfully, function app executes and enables log ingestion into Sentinel.

**Additional context**
Full error message:
Result: Failure Exception: ImportError: /home/site/wwwroot/.python_packages/lib/site-packages/cryptography/hazmat/bindings/_rust.abi3.so: undefined symbol: PyInterpreterState_Get. Troubleshooting Guide: https://aka.ms/functions-modulenotfound Stack: File "/azure-functions-host/workers/python/3.8/LINUX/X64/azure_functions_worker/dispatcher.py", line 314, in _handle__function_load_request func = loader.load_function( File "/azure-functions-host/workers/python/3.8/LINUX/X64/azure_functions_worker/utils/wrappers.py", line 42, in call raise extend_exception_message(e, message) File "/azure-functions-host/workers/python/3.8/LINUX/X64/azure_functions_worker/utils/wrappers.py", line 40, in call return func(*args, **kwargs) File "/azure-functions-host/workers/python/3.8/LINUX/X64/azure_functions_worker/loader.py", line 85, in load_function mod = importlib.import_module(fullmodname) File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module return _bootstrap._gcd_import(name[level:], package, level) File "<frozen importlib._bootstrap>", line 1014, in _gcd_import File "<frozen importlib._bootstrap>", line 991, in _find_and_load File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked File "<frozen importlib._bootstrap>", line 671, in _load_unlocked File "<frozen importlib._bootstrap_external>", line 843, in exec_module File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed File "/home/site/wwwroot/SearchEvent/__init__.py", line 14, in <module> from azure.cosmosdb.table.tableservice import TableService File "/home/site/wwwroot/.python_packages/lib/site-packages/azure/cosmosdb/table/__init__.py", line 25, in <module> from azure.cosmosdb.table.tablebatch import TableBatch File "/home/site/wwwroot/.python_packages/lib/site-packages/azure/cosmosdb/table/tablebatch.py", line 20, in <module> from azure.cosmosdb.table._request import ( File "/home/site/wwwroot/.python_packages/lib/site-packages/azure/cosmosdb/table/_request.py", line 27, in <module> from azure.cosmosdb.table._encryption import ( File "/home/site/wwwroot/.python_packages/lib/site-packages/azure/cosmosdb/table/_encryption.py", line 25, in <module> from cryptography.hazmat.primitives.hashes import ( File "/home/site/wwwroot/.python_packages/lib/site-packages/cryptography/hazmat/primitives/hashes.py", line 9, in <module> from cryptography.hazmat.bindings._rust import openssl as rust_openssl

**Comment by v-sudkharat** [comment]
Hi @Pathward-MikeM, The packages are dependent to the python version 3.9, so please update the python version in function app configuration from 3.8 to 3.9 and restart the function app :
![image](https://github.com/user-attachments/assets/7def0402-b3ee-4703-9f76-3cca546111f7)

Please let us know if it helps you to resolve this issue.
