### ISSUE TITLE
Ingest-CanaryTokens: Unable to deploy to Azure, validation failed

### ISSUE THREAD

**Issue by matthwiz** [Azure/Azure-Sentinel#11180]
**Describe the bug**
Unable to add this playbook to Azure. After inputting my information and proceeding to the review tab, I receive an error message and am unable to continue further.

**To Reproduce**
1. Go to code page for Ingest-CanaryTokens playbook (https://github.com/Azure/Azure-Sentinel/tree/master/Playbooks/Ingest-CanaryTokens)
2. Click on Deploy to Azure
3. Sign on as an account with necessary permissions (I use a global administrator)
4. Enter Workspace ID and Workspace Key
5. Click Review + Create
6. See error

**Expected behavior**
Expected no error. Should have been able to click Create and proceed in adding this playbook to Azure

**Screenshots**
![image](https://github.com/user-attachments/assets/41cd20cc-a537-45e4-bfac-17d0dd450804)
![image](https://github.com/user-attachments/assets/8f9f534e-252f-4438-9b78-456548d5cc14)
![image](https://github.com/user-attachments/assets/8ce96a08-4370-4785-8f38-fa4e2b41bab6)

**Desktop (please complete the following information):**
 - OS: Windows 11 23H2
 - Browser: Edge
 - Version: 129.0.2792.52

**Additional context**
The error seems to be indicating a syntax error at or around the "tags" path in the template. After reviewing the source, I was unable to identify the issue.

**Comment by v-rusraut** [comment]
Hi @matthwiz, Thanks for flagging this issue, we will investigate this issue and get back to you with some updates. Thanks!

**Comment by v-rusraut** [comment]
Hi @matthwiz,

We have updated the [azuredeploy.json](https://github.com/user-attachments/files/17189796/azuredeploy.json) file, please refer below steps for deployment:

- Open link - https://github.com/Azure/Azure-Sentinel/tree/master/Playbooks/Ingest-CanaryTokens
- Click on deploy to azure button
![image](https://github.com/user-attachments/assets/676a25e0-f002-4e55-9279-21bf7c6a19f4)

- fill required property value and click on edit template
![image](https://github.com/user-attachments/assets/8b1d3560-d7a4-4721-bde9-e9e209db9433)

- Copy content from attached json file and paste the content and click on save
![image](https://github.com/user-attachments/assets/643c1522-d584-482f-bf52-4e1c9afca21b)

- Check on next button

Please let us know are you able to deploy or not.

**Comment by matthwiz** [comment]
Hello, I was able to deploy successfully with the updated json file. Thanks for you help!

**Comment by v-rusraut** [comment]
Hi @matthwiz, thanks for your response, closing this issue now. If you still need support for this issue, feel free to re-open it any time. Thank you for your co-operation
