### ISSUE TITLE
Send-Teams-adaptive-card-on-incident-creation - Teams Sender Issue

### ISSUE THREAD

**Issue by Guruleenyc** [Azure/Azure-Sentinel#11190]
I got the Send-Teams-adaptive-card-on-incident-creation working with the Playbook and Automation rule, BUT the Logic App is using my account to send to Teams channel. This is NO good since it depends on my account instead of a "service account", anyone in our team that interacts with the Teams channel incident post will be making incident changes on behalf of my account instead of their own, lastly, what happens in the future if my account gets disabled for any reason?

How can we have the Logic App use a managed identity or "service account" so Sentinel incidents in Teams are not bound to a single employees account?

**Comment by Guruleenyc** [comment]
Circling back on this.
Is there any way to have the Sentinel send incidents to a Teams channel without having the Logic App depend on a user account to authenticate to Teams that is a member of the Teams group? We do not want the incidents to appear as though they are being sent by a specific team member in the Teams channel, rather they are being sent by Sentinel.

**Comment by v-rusraut** [comment]
Hi @Guruleenyc, thanks for flagging this issue, we will investigate this issue and get back to you with some updates. Thanks!

**Comment by Guruleenyc** [comment]
Due to the Adaptive Card shortcomings I noted, as a workaround I am now looking into a Playbook / Logic App to use a HTTP action POST with the Teams Webhook URL.
However, the JSON body in the HTTP trigger is difficult to get the format right.
Currently this is my JSON body for the Teams post:

`"HTTP_2": {
                "inputs": {
                    "body": {
                        "attachments": [
                            {
                                "content": {
                                    "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
                                    "body": [
                                        {
                                            "text": "**Creation time**: @{triggerBody()?['object']?['properties']?['createdTimeUtc']}",
                                            "type": "TextBlock"
                                        },
                                        {
                                            "text": "**Title**: @{triggerBody()?['object']?['properties']?['title']}",
                                            "type": "TextBlock"
                                        }
										{
                                            "text": "**ID**: @{triggerBody()?['object']?['properties']?['incidentNumber']}",
                                            "type": "TextBlock"
                                        },
										{
                                            "text": "**Severity**: @{triggerBody()?['object']?['properties']?['severity']}",
                                            "type": "TextBlock"
                                        },
										{
                                            "text": "**Description**: @{triggerBody()?['object']?['properties']?['description']}",
                                            "type": "TextBlock"
                                        },
										{
                                            "text": "**URL**: @{triggerBody()?['object']?['properties']?['incidentUrl']}",
                                            "type": "TextBlock"
                                        },
                                    ],
                                    "type": "AdaptiveCard",
                                    "version": "1.2"
                                },
                                "contentType": "application/vnd.microsoft.card.adaptive",
                                "contentUrl": null
                            }
                        ],
                        "type": "message"
                    },
                    "headers": {
                        "Content-Type": "application/json"
                    },`

**Comment by v-rusraut** [comment]
Hi @Guruleenyc, which issue you are facing now ?

**Comment by v-rusraut** [comment]
Hi @Guruleenyc , Gentle Reminder: We are waiting for your response on this issue. If you still need to keep this issue active, please respond to it in the next 2 days. If we don't receive a response by 18-10-2024 date, we will be closing this issue. 		
Thanks!

**Comment by v-rusraut** [comment]
Hi @Guruleenyc, since we have not received a response in the last 5 days, we are closing your issue as per our standard operating procedures. If you still need support for this issue, feel free to re-open at any time. Thank you for your co-operation.
