### ISSUE TITLE
Typo in Palo Alto Threat dashboard

### ISSUE THREAD

**Issue by tmccamant** [Azure/Azure-Sentinel#112]
**Describe the bug**
There is a typo in the "Threat subtypes sver sime" panel on the Palo Alto Threat dashboard. 

**To Reproduce**
1. View the Palo Alto Threat dashboard
2. See typo

**Comment by shalinoid** [comment]
Thanks @tmccamant we will resolve this shortly

**Comment by shainw** [comment]
Resolved here - https://github.com/Azure/Azure-Sentinel/commit/63b77822c444acb91feb16ecebb6811f9a31062d#diff-9351454191e4fddcffb856ecc821044a
