### ISSUE TITLE
Taxii collectionId is not valid

### ISSUE THREAD

**Issue by FormindMPO** [Azure/Azure-Sentinel#11202]
**Describe the bug**

When adding a new `Threat intelligence - TAXII` connector, i run into a `Taxii collectionId (uuidv4) is not valid.` issue..

![{1D450719-2DB5-4E3B-B58E-A127810672A8}](https://github.com/user-attachments/assets/8d3c2bc5-91f4-43c8-8988-ed74048a0b53)

**To Reproduce**

1. Go to Sentinel > Data connectors > Threat intelligence - TAXII > add
2. Fill in the information
3. 'Add'

**Expected behavior**
I have integrated a lot of connectors.
I even tried to set up the exact same values as i did in previous configurations, that are working today.

**Screenshots**

![image](https://github.com/user-attachments/assets/1001155a-b3ff-4cde-ac03-ed355e4955b7)
New conf
![{1D450719-2DB5-4E3B-B58E-A127810672A8}](https://github.com/user-attachments/assets/8d3c2bc5-91f4-43c8-8988-ed74048a0b53)
Error
![{4756D73F-DFA1-4EE7-B704-50742E1E3BBC}](https://github.com/user-attachments/assets/6faa6d25-08cc-4c36-abcc-4ac90e1655c2)
Working conf

**Desktop (please complete the following information):**
N/A.

**Smartphone (please complete the following information):**
N/A.

**Additional context**
N/A.

**Comment by v-sudkharat** [comment]
Hi @FormindMPO, Thanks for flagging this issue, we will investigate this issue and get back to you with some updates. Thanks!

**Comment by v-sudkharat** [comment]
Hi @FormindMPO, We have checked this issue with our respective data connector team, and to assign this ticket to them we kindly request you to open an Azure support case.
closing this issue from GitHub. If you still need support for this issue, feel free to re-open it any time. Thank you for your co-operation.
