### ISSUE TITLE
Can Sentinel be used to create a Data Invetory

### ISSUE THREAD

**Issue by DonDonDeDon** [Azure/Azure-Sentinel#11205]
More of a query really, can Sentinel be used to create a data inventory? We already have tool that does this but if Sentinel can do the same then I can see a cost saving to be possibly be had.

**Comment by v-rusraut** [comment]
Hi @DonDonDeDon, thanks for flagging this issue, we will investigate this issue and get back to you with some updates. Thanks!

**Comment by v-rusraut** [comment]
Hi @DonDonDeDon, Sentinel cannot be used to create Data inventory, we are closing this issue from GitHub. If you still need support for this issue, feel free to re-open it any time. Thank you for your co-operation.
