### ISSUE TITLE
Sentinel Proofpoint Function App - Warning: ProofpointPOD_message_CL

### ISSUE THREAD

**Issue by justint-mpg** [Azure/Azure-Sentinel#11219]
**Describe the bug**
We are using the Sentinel proofpoint function app, warnings in the Sentinel logs - "The following fields' values msgParts of type ProofpointPOD_message_CL " & "The following fields' values msgParts of type ProofpointPOD_message_CL have been trimmed to the max allowed size, 32766 bytes. Please adjust your input accordingly."

**To Reproduce**
Sentinel Query:
"""
_LogOperation 
| limit 1000
"""

![image](https://github.com/user-attachments/assets/e2c9266c-9689-47ac-bf6c-a70b15cd7e94)

**Comment by v-sudkharat** [comment]
Hi @justint-mpg, We have already got this issue and this consider as feature request for the connector. Our product team will take this request into their queue. We will notify you once the request has been completed. 
So, closing this issue from GitHub. If you still need support for this issue, feel free to re-open it any time. Thank you for your co-operation.
