### ISSUE TITLE
How to contribute to Network Session Essentials/solutions that use ASIM parsers?

### ISSUE THREAD

**Issue by ashwinvenkatesha** [Azure/Azure-Sentinel#11210]
Hi, I am working on adding some new asim parsers under network schema.
Once the PR has been merged, how to go about contributing to existing solutions that already use asim parsers?

**Comment by vakohl** [comment]
You can add your content and raise a PR. Our team will review your content, if approved, content will become part of the solution.

**Comment by vakohl** [comment]
Response to your other question regarding Content using ASim parsers.

you don't need to do anything for having Microsoft Solutions like 'Network Session Essentials' to include your parser. Any content using ASim function like _Im_NetworkSession will call your product specific ASim parser to fetch data.
Once your ASim parser is merged in Github, we have a deployment process that merges new ASim parsers to our Log Analytics Repository. We run this LA deployment on need basis i.e. to deploy new or update existing ASim parsers

**Comment by v-rusraut** [comment]
Hi @ashwinvenkatesha, please provide response on above comment.

**Comment by v-rusraut** [comment]
Hi @ashwinvenkatesha , we are waiting for your response.

**Comment by v-rusraut** [comment]
Hi @ashwinvenkatesha , we are waiting for your response on this issue. If you still need to keep this issue active, please respond to it in the next 2 days. If we don't receive a response by 01-11-2024 date, we will be closing this issue

**Comment by ashwinvenkatesha** [comment]
I spoke with Varun and figured that "Network Session Essentials" needs a UI change only. 
It needs to list our solution "Illumio" along with other vendors.
![Image](https://github.com/user-attachments/assets/fd1501fd-536d-406f-95e9-d4b72e97b5b3)

Change would reside only in yaml file that lists the vendors.

**Comment by ashwinvenkatesha** [comment]
@v-rusraut @v-sudkharat Can you help with this?

**Comment by v-sudkharat** [comment]
Sure @ashwinvenkatesha, 

We will check on it and update you.

**Comment by v-sudkharat** [comment]
@ashwinvenkatesha , Team is working on updating the "`Network Session Essentials`" solution to add your `Illumio` dependent solution, Once PR raised will update you. Thanks!

**Comment by v-sudkharat** [comment]
@ashwinvenkatesha , waiting for your response.

**Comment by ashwinvenkatesha** [comment]
@v-sudkharat 
Please proceed with 'Illumio SaaS'
