### ISSUE TITLE
Unable to enable some Activity templates from Entity Behavior page

### ISSUE THREAD

**Issue by mgijo** [Azure/Azure-Sentinel#11221]
**Describe the bug**
While trying to create some of the out of the box activity templates I get the below common error:-

<img width="612" alt="image" src="https://github.com/user-attachments/assets/7ac0e92b-8570-4dac-9964-9ce87f56e633">

This error seems to be the same for the rest of the below templates

<img width="577" alt="image" src="https://github.com/user-attachments/assets/1882b9bd-cc32-4724-9e52-e4c50f1745f7">

Could you have this reviewed and fixed in Sentinel? Thanks!

**Comment by v-rusraut** [comment]
Hi @mgijo, please raise a support ticket for this issue so our support team can connect with you for the required details. This ticket will also be transferred to the respective team. Therefore, we are closing this issue on GitHub. If you still need support for this issue, feel free to re-open it at any time. Thank you for your cooperation
