### ISSUE TITLE
Defender Advanced Hunt query error

### ISSUE THREAD

**Issue by kseyoss** [Azure/Azure-Sentinel#11235]
It appears the Advanced Hunting queries on the Defender portal are pulled from here. There's an error in the top suggested result... (Shared Queries/Suggested/Microsoft 365 Defender/)

"Downloads" query error:

```
The line: "or (InitiatingProcessFileName =~ "firefox.exe" and (FileName !endswith ".js" or FolderPath !has "profile"))"

Should read: "or (InitiatingProcessFileName =~ "firefox.exe" and (FileName !endswith ".js" and FolderPath !has "profile"))"
```

It doesn't filter as intended with the combination of "or" and !.

**Comment by v-rusraut** [comment]
Hi @kseyoss, Thanks for flagging this issue, we will investigate this issue and get back to you with some updates. Thanks!

**Comment by kseyoss** [comment]
Thank you. There's also another error in the Chrome part... "endswith "crdownload" should be "!endswith "crdownload" or it filters out all the Chrome downloads.

It's a useful query. I've rewritten this quite a bit to filter out automated browser updates (etc), and various other worker file. Feel free to use. :)

// Lists all the files downloaded using popular browsers.
DeviceFileEvents 
| where FolderPath !has "$Recycle.Bin"
| where 
    // Edge
    InitiatingProcessFolderPath endswith @"windows\system32\browser_broker.exe" 
    // Internet Explorer x64
    or InitiatingProcessFolderPath endswith @"program files\internet explorer\iexplore.exe"
    // Internet Explorer x32
    or InitiatingProcessFolderPath endswith @"program files (x86)\internet explorer\iexplore.exe"
    // Chrome
    or (InitiatingProcessFileName =~ "chrome.exe" and FileName !endswith "crdownload" and FolderPath !has "CacheStorage" and FolderPath !has "AppData")
    // Firefox
    or (InitiatingProcessFileName =~ "firefox.exe" and (FileName !endswith ".js" and FolderPath !has "profiles" and FolderPath !has ".xpi" and FolderPath !has "xml" and FolderPath !has "backgroundupdate" and FolderPath !has "MozillaBackgroundTask" and FolderPath !has "AppData"))
| project Timestamp, DeviceName, InitiatingProcessFileName, FileName, FolderPath

**Comment by v-rusraut** [comment]
Hi @kseyoss ,
We are waiting for response.

**Comment by v-rusraut** [comment]
Hi @kseyoss, we are waiting for your response on this issue. If you still need to keep this issue active, please respond to it in the next 2 days. If we don't receive a response by 23-10-2024 date, we will be closing this issue.
Thanks!

**Comment by v-rusraut** [comment]
Hi @kseyoss , since we have not received a response in the last 5 days, we are closing your issue as per our standard operating procedures. If you still need support for this issue, feel free to re-open at any time. Thank you for your co-operation.
