### ISSUE TITLE
failed to run Machine isolate playbook

### ISSUE THREAD

**Issue by soceng** [Azure/Azure-Sentinel#11239]
HI 
i followed the instructions of creating machine isolating playbook, when I tried to run the playbook i get the below error, so i want to know what is the missing permission, and to which resource should be granted (although i executed all steps as mentioned on the page)

<img width="248" alt="image" src="https://github.com/user-attachments/assets/94a125cb-e9fb-48a1-95ff-bf5eb908cb09">

**Comment by soceng** [comment]
the issue was that Microsoft sentinel need to have permission over Resource Group which Logic APP resides.  but when i run it new error appeared as below 
![Image](https://github.com/user-attachments/assets/62b69ddc-2cbd-4258-814c-068ca4f230d8)
![Image](https://github.com/user-attachments/assets/c1fe0131-0589-430e-8293-a83c46ffa52f)

**Comment by v-rusraut** [comment]
Hi @soceng, Thanks for flagging this issue, we will investigate this issue and get back to you with some updates. Thanks!
