### ISSUE TITLE
Proofpoint On demand(POD) Timer too long

### ISSUE THREAD

**Issue by dreamerfuzzy** [Azure/Azure-Sentinel#11243]
**Describe the bug**
In Solutions/Proofpoint On demand(POD) Email Security, the function is now pulling logs every 1 hour, many times the information received is too much and ends with a timeout. 

**To Reproduce**
1. Deploy the function.
2. Wait till the function is executed.
3. If the information received is big, will crash.

**Expected behavior**
If the pulling time is reduced, then this problem will be avoided.

**Additional context**
Suggested time: 10 minutes.

**Comment by v-sudkharat** [comment]
Hi @dreamerfuzzy, Thanks for flagging this issue, we will investigate this issue and get back to you with some updates.Thanks!

**Comment by v-sudkharat** [comment]
Hi @dreamerfuzzy, Did you get a chance to check on above request. Thanks!

**Comment by dreamerfuzzy** [comment]
Hi @v-sudkharat,
Not sure what changes have been made in the package you sent but I do not see any change after applying your patch.

On my end it's still executing every hour 
![Image](https://github.com/user-attachments/assets/21aa9cfb-55af-4e65-8c6f-df04cc62e917)

Thanks.

**Comment by v-sudkharat** [comment]
Hi @dreamerfuzzy, 
Based on the error mentioned into the issue description for function timeout, we have made change in function timeout to 10 min, which help to not crash the app. 
If request is for the run the function app to every 10 min, please update the below URL in we in which we have changes the function execution time which earlier was every `hour `now it set for `every 10 min`: 

https://github.com/Azure/Azure-Sentinel/raw/9b0bbba7d8421a13b8311cba6635280c29112266/Solutions/Proofpoint%20On%20demand(POD)%20Email%20Security/Data%20Connectors/ProofpointSentinelConn.zip

Once update, restart the function app. Thanks!

**Comment by dreamerfuzzy** [comment]
Thanks for your quick response @v-sudkharat,
I've tried but as far I can see, you changed the timer, so it's being execute every 10 minutes but the function is retrieving very time the last 60 minutes, so we're getting duplicate events.
![Image](https://github.com/user-attachments/assets/0de034d0-5431-477a-9e66-e871d17a138f)
![Image](https://github.com/user-attachments/assets/b659c8ad-fd16-499f-8589-bc80a389d082)

Thanks.

**Comment by v-sudkharat** [comment]
> Hi [@dreamerfuzzy](https://github.com/dreamerfuzzy), WEBSITE_RUN_FROM_PACKAGE - https://github.com/Azure/Azure-Sentinel/raw/c32f4c8347e79ed128f76aa76ff099d133997114/Solutions/Proofpoint%20On%20demand(POD)%20Email%20Security/Data%20Connectors/ProofpointSentinelConn.zip
> 
> Update the above shared link in function app WEBSITE_RUN_FROM_PACKAGE: ![Image](https://github.com/user-attachments/assets/fd721f22-2a2d-4986-b4bf-8847b194ba5f)
> 
> Once it updated, save the changes are restart the function app. Please let us know if your issue resolved.
> 
> Thanks!

@dreamerfuzzy, 

> Hi [@dreamerfuzzy](https://github.com/dreamerfuzzy), WEBSITE_RUN_FROM_PACKAGE - https://github.com/Azure/Azure-Sentinel/raw/c32f4c8347e79ed128f76aa76ff099d133997114/Solutions/Proofpoint%20On%20demand(POD)%20Email%20Security/Data%20Connectors/ProofpointSentinelConn.zip
> 
> Update the above shared link in function app WEBSITE_RUN_FROM_PACKAGE: ![Image](https://github.com/user-attachments/assets/fd721f22-2a2d-4986-b4bf-8847b194ba5f)
> 
> Once it updated, save the changes are restart the function app. Please let us know if your issue resolved.
> 
> Thanks!

@dreamerfuzzy , to avoid duplication issue, you can go with this package where the timeout added 10 min, which help to not crash the app 

Thanks!

**Comment by v-sudkharat** [comment]
Hi @dreamerfuzzy, Did you get a chance to check on above comment. Please let us know if it help to resolve your issue. Thanks!

**Comment by v-sudkharat** [comment]
@dreamerfuzzy, Gentle Reminder: We are waiting for your response on this issue. If you still need to keep this issue active, please respond to it in the next 2 days. If we don't receive a response by 06-11-2024 date, we will be closing this issue. 		
Thanks!

**Comment by v-sudkharat** [comment]
Hi @dreamerfuzzy, since we have not received a response in the last 5 days, we are closing your issue as per our standard operating procedures. If you still need support for this issue, feel free to re-open at any time. Thank you for your co-operation.
