### ISSUE TITLE
Crowdstrike Playbooks missing/broken

### ISSUE THREAD

**Issue by Forcky** [Azure/Azure-Sentinel#11258]
Inside the Playbooks folder > Crowdstrike folder ([direct link](https://github.com/Azure/Azure-Sentinel/tree/master/Playbooks/CrowdStrike)) most of the playbooks referenced don't seem to exist. 
For example, the link to the base_playbook lands you on a 404 error with the message "The master branch of Azure-Sentinel does not contain the path Playbooks/CrowdStrike/Playbooks/CrowdStrike_Base."
![Image](https://github.com/user-attachments/assets/1a042d69-4450-4466-8fb2-18e78f84d3b6)

![Image](https://github.com/user-attachments/assets/b4bc4cf8-4819-45fc-aa39-ce250677e7b6)

We beleive we have found the missing 3 here - 
https://github.com/Azure/Azure-Sentinel/tree/master/Solutions/CrowdStrike%20Falcon%20Endpoint%20Protection/Playbooks

Can the links at least be updated, or the playbooks in the playbooks folder be removed?

**Comment by v-sudkharat** [comment]
Hi @Forcky, Thanks for flagging this issue, PR has been raised with corrections. Thanks!
