### ISSUE TITLE
ConvertFrom-Json returning null???

### ISSUE THREAD

**Issue by jasonpanggit** [Azure/Azure-Sentinel#11267]
Hitting empty response when executing ConfigCloudWatchDataConnector.ps1. It seems like everytime we used ConvertFrom-Json, the response is empty. The following is the log generated.

-> AwsResourceCreator.ps1: New-SQSQueue
"10/8/2024 4:40 PM","Creating SQS queue:","Information"
"10/8/2024 4:41 PM","Using Sqs name: aas-azure-sentinel-sqs","Information"
"10/8/2024 4:41 PM","Executing: aws sqs create-queue --queue-name aas-azure-sentinel-sqs --tags {\""Operator\"": \""Microsoft_Sentinel_Automation_Script\""} 2>&1","Verbose"
"10/8/2024 4:41 PM","https://sqs.ap-southeast-1.amazonaws.com/xxxxxxxxxx/aas-azure-sentinel-sqs","Verbose"

-> ConfigCloudWatchDataConnector.ps1
"10/8/2024 4:41 PM","Executing: ((aws sqs get-queue-url --queue-name aas-azure-sentinel-sqs) | ConvertFrom-Json).QueueUrl","Verbose"
--> queue-url variable is empty - need to troubleshoot here
"10/8/2024 4:41 PM","Executing: ((aws sqs get-queue-attributes --queue-url  --attribute-names QueueArn )| ConvertFrom-Json).Attributes.QueueArn","Verbose"
"10/8/2024 4:41 PM","sqsUrl:  sqsArn: ","Verbose"
--> why is sqsUrl and sqsArn emtpy??? - need to troubleshoot here

-> AwsPoliciesUpdate.ps1: Update-SQSPolicy
"10/8/2024 4:41 PM","Updating the SQS policy to allow S3 notifications, and ARN to read/delete/change visibility of SQS messages and get queue url","Information"
"10/8/2024 4:41 PM","Changes S3: SQS SendMessage permission to 'aas-azure-sentinel' s3 bucket","Information"
"10/8/2024 4:41 PM","Changes Role ARN: SQS ChangeMessageVisibility, DeleteMessage, ReceiveMessage and GetQueueUrl permissions to 'OIDC_azure_sentinel_assume_role' rule","Information"
"10/8/2024 4:41 PM","Executing: aws sqs get-queue-attributes --queue-url  --attribute-names Policy","Verbose"
--> queue-url variable is empty
"10/8/2024 4:41 PM","No results returned from: aws sqs get-queue-attributes --queue-url  --attribute-names Policy ","Verbose"

**Comment by v-sudkharat** [comment]
Hi @jasonpanggit, Thanks for flagging this issue, we will investigate this issue and get back to you with some updates. Thanks!

**Comment by v-sudkharat** [comment]
Hi @jasonpanggit, Coud you please share more details about issue, repro steps and if possible, please share the issue screenshots with us. So it will help us to investigate on this issue. Thanks!

**Comment by v-sudkharat** [comment]
Hi @jasonpanggit, Waiting for your response. Thanks!

**Comment by v-sudkharat** [comment]
Hi @jasonpanggit, since we have not received a response in the last 5 days, we are closing your issue as per our standard operating procedures. If you still need support for this issue, feel free to re-open at any time. Thank you for your co-operation.
