### ISSUE TITLE
Invalid Column Name for Entity Mapping

### ISSUE THREAD

**Issue by nicolonsky** [Azure/Azure-Sentinel#11278]
The Analytics Rule Template: Solutions/Threat Intelligence/Analytic Rules/EmailEntity_CloudAppEvents.yaml references an invalid column (case sensitivity issue) in the entity mapping which breaks the Entity mapping configuration when creating the rule from template:
![Image](https://github.com/user-attachments/assets/1da0ac27-e14a-444c-8258-9e8fcc93b13a)

**Comment by v-rusraut** [comment]
Hi @nicolonsky , Thanks for flagging this issue, we will investigate this issue and get back to you with some updates. Thanks!

**Comment by nicolonsky** [comment]
@v-rusraut I already submitted a PR which resolves the mismatch within the template. See #11279

**Comment by v-rusraut** [comment]
Hi @nicolonsky , as you have already raised a PR to fix this, our team is currently reviewing it. Once the PR is merged, we will close this issue

**Comment by v-rusraut** [comment]
Hi @nicolonsky , the changes suggested have been approved, and the PR is now merged. Therefore, we are closing this issue. If you need further support, feel free to re-open it at any time. Thank you for your cooperation.
