### ISSUE TITLE
Unable to view contents of function app's zip files after downloading from SCM_RUN_FROM_PACKAGE link

### ISSUE THREAD

**Issue by ashwinvenkatesha** [Azure/Azure-Sentinel#11281]
Description:
Unable to view contents of function app's zip files after downloading from SCM_RUN_FROM_PACKAGE link

1. Deploy a function app via vscode, ensure functions load in azure console 
2. Go to https://<function_app_name>.scm.azurewebsites.net/api/settings
3. Look for the key: SCM_RUN_FROM_PACKAGE
4. Copy the link and download the zip file
5. Try to open the zip file and this leads to "Unable to expand scm-latest-functionapp.zip, it is in an unsupported format"

**Expected behavior**
Should be able to view contents and resuse in WEBSITE_RUN_FROM_PACKAGE

**Screenshots**
![Image](https://github.com/user-attachments/assets/9b04b000-d352-4912-9aa7-d74d406e1fb0)

**Desktop (please complete the following information):**
 - OS: Mac
 - Browser: Chrome

**Comment by v-sudkharat** [comment]
Hi @ashwinvenkatesha, Thank you for flagging this issue, we will check on it and update you. Thanks!

**Comment by v-sudkharat** [comment]
hey @ashwinvenkatesha, Please let us know which solution function app you have deployed and can you please share the zip with us. thanks!

**Comment by v-sudkharat** [comment]
And is the zip referenced in your raised PR- https://github.com/Azure/Azure-Sentinel/pull/10994/files#diff-95971103b1ceda83854b54c6f329fac170624618ee5faf6c7b8682ec3ab45717

**Comment by v-sudkharat** [comment]
@ashwinvenkatesha, waiting for response

**Comment by ashwinvenkatesha** [comment]
No its not the zip referenced in PR
Like I said in the description, you need to deploy the function app via vscode. So it doesnt use the website_run_from_package setting.
Once deployed, 
Go to https://<function_app_name>.scm.azurewebsites.net/api/settings
Look for the key: SCM_RUN_FROM_PACKAGE
Copy the link and download the zip file
Try to open the zip file and this leads to "Unable to expand scm-latest-functionapp.zip, it is in an unsupported format"

**Comment by v-sudkharat** [comment]
Hi @ashwinvenkatesha, Its a same zip link which referenced in a storage account of a function app : - 
![Image](https://github.com/user-attachments/assets/89f453b7-dd25-4a7b-a4a5-baeeb431e3ba)

So, to open it actually you need a 7-zip extractor software: -https://www.7-zip.org/download.html 
Not sure why default win/mac zip extractor is not supporting the that specific .zip format extension. 

Thanks!

**Comment by v-sudkharat** [comment]
Hi @ashwinvenkatesha, I hope above comment help you to unblock from your issue. Please let us know can we close this issue. Thanks!

**Comment by ashwinvenkatesha** [comment]
![Image](https://github.com/user-attachments/assets/b20e4395-8f66-4bbb-b128-bb30d04799ef)

![Image](https://github.com/user-attachments/assets/146b938c-48a2-48fe-ab45-849a1d8db026)

Trying with multiple apps, still same issue.

**Comment by v-sudkharat** [comment]
@ashwinvenkatesha, Could you please try with this tool - https://www.7-zip.org/download.html and let us know if still facing same issue. 
And please share that zip file with as well, to check if that specific file if have any issues. 

Thanks!

**Comment by ashwinvenkatesha** [comment]
We dont have permission to install that on our systems, I have shown you output of 2 other tools which do the exact same job. 
Il post a link
https://github.com/illumio-shield/Azure-Sentinel/blob/illumio-sentinel-array-bug/Solutions/IllumioSaaS/Data%20Connectors/scm-latest-testIllumioDataConnector02.zip

**Comment by v-sudkharat** [comment]
@ashwinvenkatesha , Updated the zip : 

https://github.com/Azure/Azure-Sentinel/raw/873fb120c32c53696922c8331cc2ca00d91c8971/Solutions/IllumioSaaS/Data%20Connectors/scm-latest-testIllumioDataConnector02.zip

Please download and let me know if still not able to open. Thanks!

**Comment by ashwinvenkatesha** [comment]
This worked, thanks. 
Can you tell me what was the fix pls?

**Comment by v-sudkharat** [comment]
Hi @ashwinvenkatesha, using this tool to extract the zip : -https://www.7-zip.org/download.html

So, closing this issue. If you still need support for this issue, feel free to re-open it any time. Thank you for your co-operation.
