### ISSUE TITLE
Cisco Umbrella playbooks no longer work.  API endpoints v1 appear to have been migrated to v2 with new URI paths

### ISSUE THREAD

**Issue by dimmthewitted** [Azure/Azure-Sentinel#11289]
**Describe the bug**
playbooks in the Cisco Umbrella published in Microsoft Sentinel content hub version 3.0.2 fail with a 403 forbidden.
Please update the solution to the new v2 endpoints and thank you ever so kindly for your efforts.

**To Reproduce**
Run a playbook:
CiscoUmbrella-AddIpToDestinationList
CiscoUmbrella-BlockDomain
CiscoUmbrella-GetDomainInfo
CiscoUmbrella-AssignPolicyToIdentity

**Additional troubleshooting**

Where querying the endpoint with a permissioned API key using postman,
we see that the v1 endpoints:
GET /v1/organizations/{REMOVED_organization_id}/destinationlists

 are showing as forbidden but the v2 endpoint paths downloaded from:
https://github.com/CiscoDevNet/cloud-security/tree/master/Umbrella/PostmanExamples
show success.

GET /policies/v2/destinationlists

as per:
https://developer.cisco.com/docs/cloud-security/overview-of-destination-lists-api/#destination-lists-api-use-cases

Please also see document:
**How to Migrate to the Umbrella API**

regarding:  "_replace the Umbrella v1 API URIs and Reporting v2 API URI with the Umbrella API endpoints._"

https://developer.cisco.com/docs/cloud-security/how-to-migrate-to-the-umbrella-api/#step-2-update-your-client-code

**Screenshots**
![Image](https://github.com/user-attachments/assets/2397f017-be19-4b7c-8439-e3f8cc75550b)

![Image](https://github.com/user-attachments/assets/2d24f01d-d9b6-4780-937d-ffdaa5363b2a)

**Comment by v-rusraut** [comment]
Hi @dimmthewitted , Thanks for flagging this issue, we will investigate this issue and get back to you with some updates. Thanks!

**Comment by v-rusraut** [comment]
Hi @dimmthewitted , we are working with respective team, we will update you.

**Comment by v-rusraut** [comment]
Hi @dimmthewitted, 
We have informed the respective team about this issue and created a backlog item. Our team is working to fix this issue, but there is currently no ETA. We are closing this issue for now. If you need further support, feel free to reopen it at any time. Thank you for your cooperation.
