### ISSUE TITLE
SalesforceSentinelConnector Authentication Parameters, trigger variable, required application setting

### ISSUE THREAD

**Issue by m3lm0re** [Azure/Azure-Sentinel#11288]
**Describe the bug**
There appears to be several issues with the "SalesforceSentinelConnector". 
- The default variable in the trigger "%schedule%" does not point to a value for the function to run out of the box. 
- The current Python code sends authentication parameters in the header, but testing and Salesforce documentation indicate that these parameters should be sent in the body for successful authentication.
-  The python code lists this variable "url = os.environ['SalesforceTokenUri']" but the salesforcetokenURI is not listed in the required application setting or environment variable. in the deployment guidelines.

Steps to Reproduce:
Schedule variable:
Create an Azure Function with a timer trigger.
Set the [schedule](vscode-file://vscode-app/c:/Users/s004231/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-sandbox/workbench/workbench.esm.html) in [function.json](vscode-file://vscode-app/c:/Users/s004231/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-sandbox/workbench/workbench.esm.html) to "0 0 * * * *".
Deploy the function to Azure.
Observe that the function does not trigger every hour.
Expected Behavior: The function should trigger every hour based on the schedule configuration.

Actual Behavior: The function does not trigger every hour.

Authentication:
Replacement authentication snitppit:
def _get_token():
    data = {
        "grant_type": "password",
        "client_id": consumer_key,
        "client_secret": consumer_secret,
        "username": user,
        "password": f'{password}{security_token}'
    }
    headers = {
        'Content-Type': 'application/x-www-form-urlencoded'
    }
    try:
        r = requests.post(url, data=data, headers=headers)
        r.raise_for_status()
        response_json = r.json()
        _token = response_json['access_token']
        _instance_url = response_json['instance_url']
        return _token, _instance_url
    except requests.exceptions.RequestException as err:
        logging.error(f'Token getting failed. Exiting program. {err}')
        exit()
Actual Behavior: The function app does not authenticate.

Environment:

Azure Functions runtime version: Python 3.11
Development environment: Visual Studio Code, Azure Portal

**Additional context**
I think addressing the concerns listed would create a better experience for those customers that need or have to deploy this Data Connector for ingesting log data into Azure Sentinel.

**Comment by v-sudkharat** [comment]
Hi @m3lm0re, Thanks for flagging this issue, we will investigate this issue and get back to you with some updates. Thanks!

**Comment by v-sudkharat** [comment]
Hi @m3lm0re,

For hourly trigger you need to get a license from salesforce which has been already mentioned in the data connector page : 
![Image](https://github.com/user-attachments/assets/3b45e2b9-c2da-4bb3-bb19-ebde4c030a4e)


If you already have that license, please set the **timeInterval** to **hourly** and change the CRON expression accordingly:
![Image](https://github.com/user-attachments/assets/94a3ef92-80eb-4597-84e1-b9432b0877d2)

Thanks!

**Comment by m3lm0re** [comment]
v-sudkharat,

Thanks for the information. But I’m not sure it addresses this issue. Though it does seem it may present another option to work around the default package. Having reference to these environment variables that are required would have made this deployment more streamlined.

The screenshot regarding a license “may” be needed. I’m presuming that if folks need to deploy this function app to collect logs, the license is taking care of. Maybe not. Nonetheless, even if this was the case, I’m not sure how highlighting it here addresses any portion of the issue. Which is the variable in the timer “%schedule% functions.json doesn’t point to a value. I modified this portion of the json to: “"schedule": "0 0 * * * *"”. This triggers the timer every hour.

To your second point below. In place of adding another environment variable—not listed as a requirement. Making two environment variables that would be needed but not listed on the requirements. Adding the environment variable timeintrenval, which is called in the python could also address this. To highlight again, neither of these are mentioned on the data connector page. Having some reference to this, in place of teasing it out may be helpful to others.

--
Michael Elmore

From: v-sudkharat ***@***.***>
Sent: Wednesday, October 23, 2024 4:54 AM
To: Azure/Azure-Sentinel ***@***.***>
Cc: Michael Elmore ***@***.***>; Mention ***@***.***>
Subject: [External] Re: [Azure/Azure-Sentinel] SalesforceSentinelConnector Authentication Parameters, trigger variable, required application setting (Issue #11288)

** This email originated from an external source. If you do not know the sender, please do not reply to the email, click on embedded links or open attachments **
Hi @m3lm0re, For hourly trigger you need to get a license from salesforce which has been already mentioned in the data connector page : image. png (view on web) If you already have that license, please set the timeInterval to hourly and change


Hi @m3lm0re<https://urldefense.com/v3/__https:/github.com/m3lm0re__;!!NsKbedMx-HMD!pPz4G-c0q-K0AyyCuQSH3Zh_P6mjAkx0308nF_l0GLMida5P7dreTuTsvIz971JEYwS45YgFXCTc3Ih-2AGh9sinSUamoQ$>,

For hourly trigger you need to get a license from salesforce which has been already mentioned in the data connector page :
image.png (view on web)<https://urldefense.com/v3/__https:/github.com/user-attachments/assets/3b45e2b9-c2da-4bb3-bb19-ebde4c030a4e__;!!NsKbedMx-HMD!pPz4G-c0q-K0AyyCuQSH3Zh_P6mjAkx0308nF_l0GLMida5P7dreTuTsvIz971JEYwS45YgFXCTc3Ih-2AGh9sh17haFOQ$>

If you already have that license, please set the timeInterval to hourly and change the CRON expression accordingly:
image.png (view on web)<https://urldefense.com/v3/__https:/github.com/user-attachments/assets/94a3ef92-80eb-4597-84e1-b9432b0877d2__;!!NsKbedMx-HMD!pPz4G-c0q-K0AyyCuQSH3Zh_P6mjAkx0308nF_l0GLMida5P7dreTuTsvIz971JEYwS45YgFXCTc3Ih-2AGh9si_atSipA$>

Thanks!

**Comment by v-sudkharat** [comment]
Hi @m3lm0re, Thank you so much for your feedback. 
Actually, the value for “"schedule": "0 0 * * * *"”. which you have hardcoded into the `function.json` file is added into a function app deployment pre-requisite section: 

![Image](https://github.com/user-attachments/assets/af6bb0b3-7b2b-4823-a1ca-40028b1847ba)

The corn expression is depended into the time interval parameter if we set time inter value `hourly `then it will pick this value =` 0 0 * * * *`
and if it set to `daily `to it will pick =` 0 0 0 * * *`

Hoping that we have answered your query. 
Thanks!

**Comment by m3lm0re** [comment]
Interesting. We restrict ARM templates in my organization. We clone the repo, adjust, and deploy with costume pipelines and terraform to manage the infrastructure. This step is not highlighted, that I can identify in the manual deployment guidelines.

  *   Which seems to have been an issue for you, per your initial email. Mentioning a need for a “timeInterval” environment variable. Again, just having some reference to this would be great in the documentation.
***@***.***

I look forward to seeing your response to my other items listed in the issue.

--
Michael Elmore

From: v-sudkharat ***@***.***>
Sent: Thursday, October 24, 2024 1:19 AM
To: Azure/Azure-Sentinel ***@***.***>
Cc: Michael Elmore ***@***.***>; Mention ***@***.***>
Subject: [External] Re: [Azure/Azure-Sentinel] SalesforceSentinelConnector Authentication Parameters, trigger variable, required application setting (Issue #11288)

** This email originated from an external source. If you do not know the sender, please do not reply to the email, click on embedded links or open attachments **
Hi @m3lm0re, Thank you so much for your feedback. Actually, the value for “"schedule": "0 0 * * * *"”. which you have hardcoded into the function. json file is added into a function app deployment pre-requisite section: image. png (view on web)


Hi @m3lm0re<https://urldefense.com/v3/__https:/github.com/m3lm0re__;!!NsKbedMx-HMD!rQaKIp9LRS_Cc2MnIUE1Wsr-Yx70VOFwm0rILtNG8uGhLoI8s4_zJIzfBSPfwwcIiiXqkXsc8m-ZAJXOt5O18I7KuJIliQ$>, Thank you so much for your feedback.
Actually, the value for “"schedule": "0 0 * * * *"”. which you have hardcoded into the function.json file is added into a function app deployment pre-requisite section:

image.png (view on web)<https://urldefense.com/v3/__https:/github.com/user-attachments/assets/af6bb0b3-7b2b-4823-a1ca-40028b1847ba__;!!NsKbedMx-HMD!rQaKIp9LRS_Cc2MnIUE1Wsr-Yx70VOFwm0rILtNG8uGhLoI8s4_zJIzfBSPfwwcIiiXqkXsc8m-ZAJXOt5O18I6RvwziBg$>

The corn expression is depended into the time interval parameter if we set time inter value hourly then it will pick this value = 0 0 * * * *
and if it set to daily to it will pick = 0 0 0 * * *

Hoping that we have answered your query.
Thanks!

**Comment by v-sudkharat** [comment]
@m3lm0re Thanks for your feedback. will keep note of this. 
So, closing this issue. If you still need support for this issue, feel free to re-open it any time. Thank you for your co-operation.
