### ISSUE TITLE
Discrepancy in the Count of the Events - in the Incidents blade and Log Analytics Workspace results

### ISSUE THREAD

**Issue by Ravindra-Am** [Azure/Azure-Sentinel#11302]
Hi Team,

There is a discrepancy between the count of events from the Incident Blade and the output from the Log Analytics Workspace after executing the query. 

For Example:

The number of events from the incidents blade for the Incident Number 1394967 are 2, but when the query was executed, the results getting displayed are only "1".
 
![Image](https://github.com/user-attachments/assets/bc73f08c-c150-46e3-b1dd-fb01418754ed)

![Image](https://github.com/user-attachments/assets/42e2ab0b-bb52-4644-87ea-5d23c23a2246)

Incident Number: 1394532

![Image](https://github.com/user-attachments/assets/04e3b14c-919e-4d9f-99fc-cb3bca8a9504)

![Image](https://github.com/user-attachments/assets/6062fab7-4fa3-4980-aaf4-51461d80e3b7)

Even after deploying the Updated template the results are getting populated the same. 

In the query a Cisco URL link was used, which is getting updated every day.

**ASK: When the data for the past incidents was checked, there is a discrepancy in the output, because of which the SOC team is not willing to investigate the incidents. Need a quick solution for this issue.

**Comment by Ravindra-Am** [comment]
Hi Team, A very good day. Let me know if any data is required from my end.
Thank you

**Comment by v-sudkharat** [comment]
Adding @***@***.***>
________________________________

**Comment by Ravindra-Am** [comment]
Hi Team, a very good day. Any update on the ticket. Let me know if any data is required from my end. 
Thank you

**Comment by v-rusraut** [comment]
Hi @Ravindra-Am , we are working with respective team, we will update you.

**Comment by Ravindra-Am** [comment]
Hi Team, Thank you for your response. any update on the ticket?

**Comment by Ravindra-Am** [comment]
Hi Team, a very good day. Any update on this issue

**Comment by v-visodadasi** [comment]
Hi @Ravindra-Am , Could you please click on this event,
![Image](https://github.com/user-attachments/assets/f5a213ea-0f82-42ee-9c4a-557345611daf)
Copy the query that includes the specific timestamp, and run it in the Log Analytics Workspace to check for the events?
![Image](https://github.com/user-attachments/assets/5732be5b-4159-4fe2-b5e7-ae01a9dcf5a8)

Let me know how many events you are getting after running this query.

**Comment by v-visodadasi** [comment]
HI @Ravindra-Am , Since we have not received a response in the last 5 days, we are closing your issue as per our standard operating procedures. If you still need support for this issue, feel free to re-open at any time.

Thank you for your co-operation.
