### ISSUE TITLE
Trend Micro Vision One - TrendMicro_XDR_WORKBENCH_CL table is not showing any results

### ISSUE THREAD

**Issue by vi-lgtm** [Azure/Azure-Sentinel#11312]
**Describe the bug**
The TrendMicro_XDR_WORKBENCH_CL, TrendMicro_XDR_RCA_Task_CL tables is not showing any results, while table TrendMicro_XDR_OAT_CL seem show some results.

**To Reproduce**
Go to Sentinel > Data connectors > Trend Vision One (using Azure Functions) > Open connector page
Check Data types
Only TrendMicro_XDR_OAT_CL shows green connection icon, other shows grey icon.

Go to Sentinel > Logs > New query
TrendMicro_XDR_OAT_CL shows results.
rendMicro_XDR_WORKBENCH_CL do not show any results.
TrendMicro_XDR_RCA_Task_CL - 'table' operator: Failed to resolve table expression named 'TrendMicro_XDR_RCA_Task_CL'
Request id: 326c8e42-3576-4142-9610-be08ab11227b
TrendMicro_XDR_RCA_Result_CL - 'table' operator: Failed to resolve table expression named 'TrendMicro_XDR_RCA_Result_CL'
Request id: 148180a7-32e3-44dc-b268-a889511f38c8

**Expected behavior**
The TrendMicro_XDR_WORKBENCH_CL, TrendMicro_XDR_RCA_Task_CL, TrendMicro_XDR_RCA_Result_CL tables should display relevant data as per normal operation.![Image](https://github.com/user-attachments/assets/c64fbf95-c18b-463b-9643-60ccf8b87071)

**Comment by v-sudkharat** [comment]
Hi @vi-lgtm, 
We also have checked this solution, this solution is supported with Trend Micro Vision One However, we are not authorized to make any modifications to it. We kindly request that you raise an issue ticket with the Trend Micro Vision One support team. 
Sharing the Trend Micro Vision One support link -
Link - "https://success.trendmicro.com/dcx/s/?language=en_US"
Closing this issue from GitHub. If you still need support for this issue, feel free to re-open it any time. Thank you for your co-operation.
