### ISSUE TITLE
Okta SSO Parser Calling Incorrect Table Name

### ISSUE THREAD

**Issue by JAK1047** [Azure/Azure-Sentinel#11319]
With the new Okta SSO Data Connector using Microsoft Sentinel Codeless Connector Platform Data instead of Azure Functions a backwards compatibility parser function was added:

![Image](https://github.com/user-attachments/assets/38e77592-6303-4d24-84ec-69e377350ce4)

The table called by the parser for the new Data Connector though appears to be incorrect. Calling OktaV2 for the join:

![Image](https://github.com/user-attachments/assets/32d20dbf-9f10-4c45-9b05-94464a63075a)

When the table name generated by the new Data Connector is OktaV2_CL:

![Image](https://github.com/user-attachments/assets/9dadb15f-2cbe-483c-9bbd-3e75b800cdc6)

![Image](https://github.com/user-attachments/assets/30ccd11f-2546-41d6-bf57-bed7ad678fb9)

**Comment by v-sudkharat** [comment]
Hi @JAK1047, Thanks for flagging this issue, we will investigate this issue and get back to you with some updates. Thanks!

**Comment by v-sudkharat** [comment]
Hi @JAK1047, Could you please run below updated parser in your LAW and let us know your issue resolved?: [oktaparser.txt](https://github.com/user-attachments/files/17645809/oktaparser.txt)
 
Thanks!

**Comment by JAK1047** [comment]
That looks good to me! Includes the v2 table and returns all my entries.

**Comment by v-sudkharat** [comment]
@JAK1047, Thanks for the response. the PR has been raised with the changes, and the changes will get reflected into upcoming solution version. 
Closing this issue from GitHub. If you still need support for this issue, feel free to re-open it any time. Thank you for your co-operation.
