### ISSUE TITLE
TimeSeriesAnomaly-MultiVendor_DataExfiltration.yaml

### ISSUE THREAD

**Issue by mbell85** [Azure/Azure-Sentinel#11359]
How can I determine what my baseline threshold should be when utilizing the query 'Time series anomaly for data size transferred to public internet'?

I'm confused about a few things, which is making me unsure. 

Am I correct in understanding that the query is looking at data transfers to the public Internet **_per port_**? 

Am I also correct in seeing the results as being in total bytes out per port versus the baseline, despite any resulting hits stating 'TotalBytesSentinMB'? Comparing to Firewall traffic logs, it appears impossible for the total bytes out to be measuring in MB, otherwise I'd be seeing a lot higher amount of traffic on the firewall.

And does changing the amount of days of history to look up affect the baseline in any manner? 

Anything else I should know about "right-sizing" the query for my tenant? 

Much thanks for any help/input!

**Comment by mbell85** [comment]
Thank you! A very useful query for threat hunting indeed!



--



Mark Bell
[Signature of Mark E. Bell.]
IT Administrator (CompTIA SIS, ITOS, A+, Network+ & Security+ Certified)
Journeys in Community Living
1130 Haley Rd.
Murfreesboro, TN 37129
615-890-4389, ext. 45 (ofc)
615-295-3046 (cell)
www.journeystn.org<http://www.journeystn.org/>
www.fb.com/journeysincommunity<http://www.fb.com/journeysincommunity>
www.twitter.com/journeystn<http://www.twitter.com/journeystn>





________________________________

**Comment by v-visodadasi** [comment]
Hi @mbell85 , Glad you found the query useful! Do you have any further questions or concerns regarding the issue?

**Comment by v-visodadasi** [comment]
Hi @mbell85 , Do you have any further questions or concerns regarding the issue?

**Comment by v-visodadasi** [comment]
Hi @mbell85 , Do you have any further questions or concerns regarding the issue?

**Comment by v-visodadasi** [comment]
Hi @mbell85 , since we have not received a response in the last 5 days, we are closing your issue as per our standard operating procedures. If you still need support for this issue, feel free to re-open at any time. 

Thank you for your co-operation.

**Comment by mbell85** [comment]
No. Thank you!



--



Mark Bell
[Signature of Mark E. Bell.]
IT Administrator (CompTIA SAP, SIS, ITOS, CySA+, Security+, Network+, A+ Certified)
Journeys in Community Living
1130 Haley Rd.
Murfreesboro, TN 37129
615-890-4389, ext. 45 (ofc)
615-295-3046 (cell)
www.journeystn.org<http://www.journeystn.org/>
www.fb.com/journeysincommunity<http://www.fb.com/journeysincommunity>
www.twitter.com/journeystn<http://www.twitter.com/journeystn>





________________________________
