### ISSUE TITLE
Atlassian Jira Audit Function Not Working

### ISSUE THREAD

**Issue by macna** [Azure/Azure-Sentinel#11362]
**Describe the bug**
The "JiraAudit" function included with the Atlassian Jira Audit solution throws the error "'project' operator: Failed to resolve scalar expression named 'EventCreationTime'"

**To Reproduce**
1. Go to Sentinel or Log Analytics
2. Attempt to perform a search using the "JiraAudit" function.
3. See error

**Expected behavior**
Data to be returned using the column names defined in the function.

**Screenshots**
![Image](https://github.com/user-attachments/assets/ba5de6a3-c8e3-43c1-b52c-19d5ed4ccd9b)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser Edge
 - Version 130.0.2849.46

**Comment by v-sudkharat** [comment]
Hi @macna, Thanks for flagging this issue, we will investigate this issue and get back to you with some updates. Thanks!

**Comment by v-sudkharat** [comment]
@macna, can you check for which columns the issue occurred by running the below parser - 
![Image](https://github.com/user-attachments/assets/6014a5e3-81cd-447b-96b0-959d8fc81d3e)

And please check the logs are received into the table `Jira_Audit_CL `and `Jira_Audit_v2_CL ` with the columns. Thanks!

**Comment by v-sudkharat** [comment]
@macna, Did you get a change to check on above comment? Thanks!

**Comment by v-sudkharat** [comment]
Hi @macna, since we have not received a response in the last 5 days, we are closing your issue as per our standard operating procedures. If you still need support for this issue, feel free to re-open at any time. Thank you for your co-operation.

**Comment by macna** [comment]
Hi @v-sudkharat apologies for the delay. The issue related to the EventCreationTime column, which doesn't seem to exist. Please reopen the issue.

**Comment by macna** [comment]
Hi @v-sudkharat - just to reiterate - can this issue be reopened, please?

**Comment by v-sudkharat** [comment]
@macna , reopening the case.

**Comment by v-sudkharat** [comment]
@macna, Please share the logs for - Jira_Audit_CL and Jira_Audit_v2_CL table to understand if the respective column has been created in the tables. 
Mail ID- v-sudkharat@microsoft.com
Thanks!

**Comment by macna** [comment]
Hi @v-sudkharat - we are only populating Jira_Audit_CL. I'll forward you some example rows.

**Comment by macna** [comment]
Hi @v-sudkharat - I have reviewed this issue with my colleagues and have identified a misconfiguration on out part.

Thanks for your help - closing.
