### ISSUE TITLE
Local Admin Group Changes Analytics rule version 1.0.1 is Generating False Positives

### ISSUE THREAD

**Issue by tibikunle01** [Azure/Azure-Sentinel#11364]
Since my customer updated the Local Admin Group Changes Analytics rule from version 1.0.0 to version 1.0.1, they have been getting false positives.

**My customer ran the query in the Local Admin Group Changes Analytics rule version 1.0.1, looking in the past 24 hours and got a results count of 751**
![Image](https://github.com/user-attachments/assets/f4981d3f-ace0-4332-a7fd-f530ecd6abad)

**Got a result count of 751**
![Image](https://github.com/user-attachments/assets/52cb5609-f99f-478d-a0d3-cf123a666691)

**Uncommented the line 21 and got result count of 569**
![Image](https://github.com/user-attachments/assets/f34d4ab1-4fea-41f3-a7f3-6da59f7c99d8)

**Got a result count of 569**
![Image](https://github.com/user-attachments/assets/7f340aa8-ac20-4f05-937d-8e4905398cd0)

**We ran the query in the Local Admin Group Changes Analytics rule version 1.0.0, looking in the past 24 hours and got a result count of 11280**
![Image](https://github.com/user-attachments/assets/2213bf8c-6859-4ae8-88ed-3f6c82960556)

**Got a result count of 11280**
![Image](https://github.com/user-attachments/assets/20a638a9-b377-4224-9594-60de1b8a79ce)

**Uncommented the line 21 and got a result count of 0**
![Image](https://github.com/user-attachments/assets/fc38c4bb-98bd-4842-a8e1-91d11bd8c634)

**Got a result count of 0**
![Image](https://github.com/user-attachments/assets/e70b7d5a-f5b6-449d-a002-65f449efb331)

My customer wants the version 1.0.1 because it has the GroupSid in it compared to version 1.0.0 which doesn't have the GroupSid in it's query.

Help investigate why they are getting false positives when using the Local Admin Group Changes Analytics rule version 1.0.1

**Comment by tibikunle01** [comment]
Hello team, please is there an update on this?

**Comment by v-rusraut** [comment]
Hi @tibikunle01 , Thanks for flagging this issue, we will investigate this issue and get back to you with some updates. Thanks!

**Comment by tibikunle01** [comment]
Hi @v-rusraut, Thank you for your response. Do you have an update yet?

**Comment by tibikunle01** [comment]
Hello @v-rusraut Please do you have an update yet?

**Comment by v-sudkharat** [comment]
@v-visodadasi, look into this issue.

**Comment by v-visodadasi** [comment]
Hi @tibikunle01, Replacing "contains" with "==" helps refine the query to focus on the exact Local Admin Group SID, reducing false positives.

**Comment by tibikunle01** [comment]
Hi @v-visodadasi thank you for your response.  

I replaced "contains" with "==" on line 15 and got a result count of 761

![Image](https://github.com/user-attachments/assets/560d7b9b-7fed-4fcd-af0c-214f050b02ba)

Running the same query with "contains" on line 15, I got a result count of 761.

![Image](https://github.com/user-attachments/assets/a55c5ecd-aff1-47ea-ba4a-33ae5f63bc8a)

Please advise.

**Comment by v-visodadasi** [comment]
Hi @tibikunle01 , I think you had raised an ICM for the same issue, and @v-sabiraj  had reached out to you with a potential solution. Could you please confirm if that's correct? If so, I'll go ahead and close this issue

**Comment by v-visodadasi** [comment]
Hi @tibikunle01 , Could you please confirm?
