### ISSUE TITLE
Malicious Blog URL in Alert

### ISSUE THREAD

**Issue by anomalies324** [Azure/Azure-Sentinel#11379]
the rule "Detecting Macro Invoking ShellBrowserWindow COM Objects" contains a malicious URL posing as a blog subsequent requests to the URL also redirect to a scam advertising site indicating some type of redirection manipulation to try and stop security research. 

Malicious URL - https://blog.menasec.net/2019/02/threat-hunting-doc-with-macro-invoking[.]html 

Alert URL  - https://github.com/Azure/Azure-Sentinel/blob/master/Solutions/Endpoint%20Threat%20Protection%20Essentials/Analytic%20Rules/MacroInvokingShellBrowserWindowCOMObjects.yaml

**Comment by v-rusraut** [comment]
Hi @anomalies324 , Thanks for flagging this issue, we will investigate this issue and get back to you with some updates. Thanks!

**Comment by v-sudkharat** [comment]
@v-visodadasi, look into this issue.
