### ISSUE TITLE
Hello help(question related to microsoft smartscreen)

### ISSUE THREAD

**Issue by PanamaPanamera** [Azure/Azure-Sentinel#11373]
Hello, this is microsoft security community i would likd to report few crypto phishing domains, as that said would be possiboe to flag them for smartscreen?Or maybe you can tell where to report which link as reporting via browser etc doesen't help either for review of site for false positive or marking them as suspicious

http://pehdle-info.com/
https://v2-dexscreener.com/
https://v2-swell-network.com/

**Comment by v-rusraut** [comment]
Hi @PanamaPanamera , Thanks for flagging this issue, we will investigate this issue and get back to you with some updates. Thanks!

**Comment by v-sudkharat** [comment]
Hey @PanamaPanamera, 

Thank you for reaching out to the Microsoft Security Community. To report phishing domains and flag them for SmartScreen, you can use the following link:

Microsoft Report a Phishing Site - https://www.microsoft.com/en-us/wdsi/support/report-unsafe-site

Please provide the necessary details about the suspicious domains, such as http://pehdle-info.com/, on the reporting page. This will help Microsoft review and take appropriate action.

Many Thanks!
