### ISSUE TITLE
The provided script failed with the following error: Microsoft.PowerShell.Commands.HttpResponseException: Response status code does not indicate success: 400 (Bad Request)

### ISSUE THREAD

**Issue by a-balde** [Azure/Azure-Sentinel#11376]
**Describe the bug**
The provided script failed with the following error:\r\nMicrosoft.PowerShell.Commands.HttpResponseException: Response status code does not indicate success: 400 (Bad Request).\n   at System.Management.Automation.MshCommandRuntime.ThrowTerminatingError(ErrorRecord errorRecord)\r\nat <ScriptBlock>, /mnt/azscripts/azscriptinput/Create-NewSolutionAndRulesFromList.ps1: line 44\r\nat <ScriptBlock>, <No file>: line 1\r\nat <ScriptBlock>, /mnt/azscripts/azscriptinput/DeploymentScript.ps1: line 310. Please refer to https://aka.ms/DeploymentScriptsTroubleshoot for more deployment script information.

ARM Template: https://portal.azure.com/#create/Microsoft.Template/uri/https%3A%2F%2Fraw.githubusercontent.com%2FAzure%2FAzure-Sentinel%2Fmaster%2FTools%2FSentinel-All-In-One%2Fv2%2Fazuredeploy.json/createUIDefinitionUri/https%3A%2F%2Fraw.githubusercontent.com%2FAzure%2FAzure-Sentinel%2Fmaster%2FTools%2FSentinel-All-In-One%2Fv2%2FcreateUiDefinition.json

Script: https://github.com/Azure/Azure-Sentinel/blob/master/Tools/Sentinel-All-In-One/v2/Scripts/Create-NewSolutionAndRulesFromList.ps1

**To Reproduce**
To replicate the issue, deploy the ARM template selecting 'Azure Activity' as Content Hub Solution and Data connector, leaving all other settings as default. The 'deployRules' resource will fail, and the Azure Activity solution wont be installed.

**Expected behavior**
There should not be an error on 'deployRules' resource. The Azure Activity Sentinel solution should be installed.

**Screenshots**
![Image](https://github.com/user-attachments/assets/b59b6007-aed2-4463-bcba-0bac7c66c95f)

**Comment by v-rusraut** [comment]
Hi @a-balde , Thanks for flagging this issue, we will investigate this issue and get back to you with some updates. Thanks!

**Comment by a-balde** [comment]
Hi @lussierd16, I replaced **AzureAD** with **Entra ID** in the solutions.json file but that did not resolve the issue.

**Comment by v-sudkharat** [comment]
@a-balde, This issue we are addressing here - https://github.com/Azure/Azure-Sentinel/issues/11329 in which we tagged to respective Author, you can track and also share you response over here.
