### ISSUE TITLE
Imperva WAF solution doesn't have parser although it is in GitHub

### ISSUE THREAD

**Issue by javiersoriano** [Azure/Azure-Sentinel#11382]
**Describe the bug**
Imperva WAF Cloud solution contains [a parser](https://github.com/Azure/Azure-Sentinel/tree/master/Solutions/ImpervaCloudWAF/Parsers), but after installing the solution from content hub, the parser does not show up and it's not available to install. 

![Image](https://github.com/user-attachments/assets/0b6478df-7e89-46e2-9fd5-f7bbda0c58ae)

I believe this is because the Data file for this solution, references "Parsers/ImpervaWAFCloud" but the actual file is ""Parsers/ImpervaWAFCloud.yaml"

**To Reproduce**
Install Imperva WAF Cloud solution

**Expected behavior**
The parser should be available for installation

**Comment by v-sudkharat** [comment]
Hi @javiersoriano, Thanks for flagging this issue, we will investigate this issue and get back to you with some updates. Thanks!

**Comment by v-sudkharat** [comment]
@javiersoriano, Thanks for informing this to us. We have raised the PR with fix, and it's in review state.
Once the PR get merged, the new changes will get reflected into upcoming solution version. Many Thanks!
