### ISSUE TITLE
1Password connector deployment

### ISSUE THREAD

**Issue by abrownsyn** [Azure/Azure-Sentinel#11428]
**Describe the bug**
When following the directions on to set up data connector, I  click on deploy azure enter the required information.The deployment then fails (Code: ParentResourceNotFound) I will also attach a screenshot below. 
 I also found the steps on Medium "https://rogierdijkman.medium.com/1password-microsoft-sentinel-solution-7e77d98957cd"
the link in the that page is not working.

**To Reproduce**
1. Go to [(https://github.com/Azure/Azure-Sentinel/tree/master/Solutions/1Password)
2. Click on '.Deploy to Azure'
3. Once deployment starts, it will error out

**Expected behavior**
After the setup is completed, a summary will be displayed showing the results of the deployed templates.
After some time, Microsoft Sentinel will start receiving data from the 1Password API, and the data connector will show as connected.

**Screenshots**

![Image](https://github.com/user-attachments/assets/0b6a1091-ae70-4552-980b-c192d7eb5962)

**Comment by v-sudkharat** [comment]
Hi @abrownsyn, Thanks for flagging this issue, we will investigate this issue and get back to you with some updates. Thanks!

**Comment by v-sudkharat** [comment]
@abrownsyn, Could you please share the error details with screenshots, and can you check with below steps in solution which have the 1Password connector - 
![Image](https://github.com/user-attachments/assets/6bae27ec-dfdf-407c-a6cb-dc3eed5c573f)

![Image](https://github.com/user-attachments/assets/a7f3c9b3-fb87-4062-9645-f5492499cee1)

![Image](https://github.com/user-attachments/assets/774d4d0b-98cc-4426-a66a-c8285fbb42a7)


Thanks!

**Comment by abrownsyn** [comment]
@v-sudkharat When follow your steps I get back to deploy to azure screen. I'm attaching some screens below, if it's easier we can screen a video conference next week.![Image](https://github.com/user-attachments/assets/3ab0d949-2390-411e-9e8a-557710a3e94c)
![Image](https://github.com/user-attachments/assets/0ef9da5e-bf5a-42fb-b003-aebf8b0eee27)
![Image](https://github.com/user-attachments/assets/8b90a858-04f7-49bc-9ad0-04c350194ea9)

**Comment by v-sudkharat** [comment]
@abrownsyn, Sure. will do. 
I'm see the error which you're having while deployment, its due to the incorrect input filed enter in below for below Workspace Name filed - 

![Image](https://github.com/user-attachments/assets/80711f1d-7601-4e62-86da-6bcaa8d87220)

Please check in your environment, Is the Workspace Name which you have entered are in a same Resource Group. 

Ex - 
![Image](https://github.com/user-attachments/assets/87563b3e-c238-46bc-ac8e-1c3122d1afb8)
 
So, Please validate Workspace Name, Resource Group and Region are correctly added as input filed. 

Thanks!

**Comment by v-sudkharat** [comment]
@abrownsyn, Waiting for your response on above comment. Thanks!

**Comment by abrownsyn** [comment]
@v-sudkharat  sorry for the delay but that fixed it thank you for your help

**Comment by v-sudkharat** [comment]
@abrownsyn, Welcome.
