### ISSUE TITLE
AS-Revoke-Azure-AD-User-Session- Playbooks should use lower  privilege

### ISSUE THREAD

**Issue by jkerai1** [Azure/Azure-Sentinel#11438]
User.ReadWrite.All was previously required but we have User.RevokeSessions.All now which is least privilege option

https://learn.microsoft.com/en-us/graph/api/user-revokesigninsessions?view=graph-rest-1.0&tabs=http

**Comment by jkerai1** [comment]
Affected Playbooks:

AS-Revoke-Azure-AD-User-Session-From-Entity

[AS-Revoke-Azure-AD-User-Session-From-Incident](https://github.com/Azure/Azure-Sentinel/tree/master/Playbooks/AS-Revoke-Azure-AD-User-Session-From-Incident)

**Comment by v-visodadasi** [comment]
Hi @jkerai1 , Could you please provide more details?

**Comment by jkerai1** [comment]
@v-visodadasi 

The app reg here should be using User.RevokeSessions.All not User.ReadWrite.All

See Least Privilege Table here: https://learn.microsoft.com/en-us/graph/api/user-revokesigninsessions?view=graph-rest-1.0&tabs=http#permissions

![Image](https://github.com/user-attachments/assets/2478eff9-5d0e-4ce9-89f5-ffeecffed8f5)
