### ISSUE TITLE
can't connect GCP Pub/Sub Audit Logs Data Connector to MS Sentinel

### ISSUE THREAD

**Issue by odishelidzegio** [Azure/Azure-Sentinel#11453]
**Bug description**
I'm trying to connect GCP Pub/Sub Audit Logs connector to Sentinel, to ingest GCP logs, but after I fill all the required fields it shows this error:
![Image](https://github.com/user-attachments/assets/8c621c30-35e1-4083-80a6-af6477f6b2e2)

This is how it looks like when I'm filling the fields:
![Image](https://github.com/user-attachments/assets/363dec38-8da2-4af6-92f2-dda2a84e1745)

**To Reproduce**
1. Go to 'https://azuremarketplace.microsoft.com/en-us/marketplace/apps/azuresentinel.azure-sentinel-solution-gcpauditlogs-api?tab=Overview'
2. Install it and click manage.
4. Go to installed solution and choose 'GCP Pub/Sub Audit Logs'
5. Click 'Add new collector' and fill out all the required fields.
6. See error: 
 ![Image](https://github.com/user-attachments/assets/ab94e8c7-515d-4204-b086-1c5b640442e3)

**Comment by v-sudkharat** [comment]
@odishelidzegio, Can you please share the full error message screenshot, and is there any support ticket raised for this issue?

**Comment by odishelidzegio** [comment]
Yes, of course, here's the full error message:
![Image](https://github.com/user-attachments/assets/be45ce63-04f7-460b-866d-1ece2ae8e5d7)

Here's Raw message:

{
  "code": "DeploymentFailed",
  "message": "At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-deployment-operations for usage details.",
  "details": [
    {
      "code": "BadRequest",
      "message": "Connectivity check failed. ConnectorId: GCPAuditLogsfa206b6c-a4e9-4dff-a82f-ae6ec19a833a, Status code:GCPB40001, Message:An unknown exception resulted in the failure to authenticate: Google.Apis.Requests.RequestError\r\nPermission 'iam.serviceAccounts.getAccessToken' denied on resource (or it may not exist). [403]\r\nErrors [\r\n\tMessage[Permission 'iam.serviceAccounts.getAccessToken' denied on resource (or it may not exist).] Location[ - ] Reason[forbidden] Domain[global]\r\n]\r\n"
    }
  ]
}

From GCP's side it's completed, yes.

Please also note that the permission "[Permission 'iam.serviceAccounts.getAccessToken" is granted to service account

**Comment by v-sudkharat** [comment]
@odishelidzegio, thanks for sharing it, will check and get back to you.

**Comment by v-sudkharat** [comment]
@odishelidzegio, Based on the error, need to verify the role - iam.serviceAccountTokenCreator is granted to the correct service account. 
You can follow the below step / refer the doc to add it and confirm once it gets from GCP end. 
DOC - https://cloud.google.com/iam/docs/service-account-permissions

1. Go to IAM in GCP Portal and search for you service account name - 
2. Click on the Pencil icon and edit it - 
![Image](https://github.com/user-attachments/assets/d4113362-b6cf-4d35-898d-4c70baba8fe3)

3. Add another role - 
![Image](https://github.com/user-attachments/assets/8f02a247-be80-44c4-a955-70a854f79b36)

4. Search with the role - `iam.serviceAccountTokenCreator` and click on save -
![Image](https://github.com/user-attachments/assets/77c27ab6-cd0d-4a11-83ec-6cae0b5e9b93)

![Image](https://github.com/user-attachments/assets/0275cdca-03e4-4e98-9d74-85b614383e6e)

5. The updated role will get displayed in service account name - 
![Image](https://github.com/user-attachments/assets/853a014a-b54f-46e9-9371-4615742a8adb)

Once it gets updated, reconnect the Data connector and let us know if it still has the issue. 

Thanks!

**Comment by odishelidzegio** [comment]
Hello!
I checked, and the permission was not granted. I granted the permission but still the same error:
![Image](https://github.com/user-attachments/assets/8b36c32f-b579-4f91-b5f4-0ce7db14732e)

Permissions granted:

![Image](https://github.com/user-attachments/assets/42ad3b9f-cf3f-4c17-98bb-9c7d95c7aab6)

**Comment by v-sudkharat** [comment]
@odishelidzegio, Will check with concern team for this case.

**Comment by v-sudkharat** [comment]
@odishelidzegio, Meantime, want to know did you get same error after deployment in different workspace? can you check and let us know it by configure it in different workspace. Thanks!

**Comment by odishelidzegio** [comment]
I think I have not, I'll try it.

**Comment by ulviahmadly99** [comment]
@odishelidzegio , hi mate , did you have any solution for this . I also stucked at this point and no luck to solve it

**Comment by v-sudkharat** [comment]
@ulviahmadly99 / @ulviahmadly99 , Could you please follow the steps mentioned in below Doc -https://learn.microsoft.com/en-us/azure/sentinel/connect-google-cloud-platform?tabs=terraform%2Cauditlogs

And please note that once the configuration has been completed in GCP end, please wait for few minutes before setting it up in Sentinel connector. 

Thanks!

**Comment by odishelidzegio** [comment]
@v-sudkharat any updates?

By the way, I tried it in another workspace and got this error:

Failed to parse input. Error='DataCollectionEndpoint should be in the following format: https://{Data Collection Endpoint name}-{id}-{Region}.ingest.monitor.azure.com (Parameter 'dataCollectionEndpoint')'

@ulviahmadly99 Not yet

**Comment by odishelidzegio** [comment]
@v-sudkharat after many tries, I'm still getting the same error:
![Image](https://github.com/user-attachments/assets/d8a61727-e8fe-49fb-9497-eb0330bd25b6)

I tried to delete everything and recreate it on GCP side but no results.

**Comment by odishelidzegio** [comment]
@v-sudkharat I think I have a problem with this step: https://learn.microsoft.com/en-us/azure/sentinel/connect-google-cloud-platform?tabs=manual%2Cauditlogs#grant-the-identity-pool-access-to-the-service-account

Specifically here: https://cloud.google.com/iam/docs/workload-identity-federation-with-other-clouds#authenticate

I don't understand how to do it. Tried to do the same as in the documentation, but I think I'm not making something correctly here.

**Comment by v-sudkharat** [comment]
@odishelidzegio, no worries, We can have a call to check on this issue. So please can you send the mail id and slots with us - v-sudkharat@microsoft.com

And if you also try this, as it looks your project might be not having the admin access to provide the required access to the services, so you can run below command in terminal before running the terraform scripts- 

```
 gcloud projects add-iam-policy-binding ProjectName \
  --member="user:MailID" \
  --role="roles/iam.roleAdmin"
```
Replace `MailID `as your mail Id - EX - `abcd@gamil.com`

Replace `ProjectName` with your `ProjectName `

Once this get successfully run, you can retry the above-mentioned steps and check for the connector status. And in GCP side the services takes some time to get sync. 
So, wait for some time and then configure the connector.

**Comment by v-sudkharat** [comment]
@odishelidzegio, Did you get a chance to check on it? anything for us?

**Comment by v-sudkharat** [comment]
@odishelidzegio, Ok

**Comment by odishelidzegio** [comment]
Hello @v-sudkharat 

I tried to run the command, and it succeeds, but still got the same error after connecting GCP connector.

**Comment by v-sudkharat** [comment]
@odishelidzegio, let's have the meet, please share the slots in above mail.

**Comment by v-sudkharat** [comment]
@odishelidzegio, Received your mail, I will schedule a call with available time slots and share it via mail. Thanks!

**Comment by odishelidzegio** [comment]
@v-sudkharat thanks for your great support! 

It was a good experience working with you. You assisted me very well, I appreciate.

I'll close this issue now.

Thanks one more time, great assistance!

**Comment by v-sudkharat** [comment]
@odishelidzegio, Thanks for your valuable feedback.
