### ISSUE TITLE
Tenable VM function app 3.0.1 points to invalid URL function app does not run

### ISSUE THREAD

**Issue by PCNZ** [Azure/Azure-Sentinel#11469]
**Describe the bug**
The Tenable App, Tenable Vulnerability Management (using Azure Function) fail to download zip package and does not run

**To Reproduce**
1. Go to 'Content Hub in Sentinel'
2. Click on 'Install Tenable App Solution v3.0.1'
3. Scroll down to 'Data Connectors'
4. Open and Deploy the function app from within the Tenable Vulnerability Management (using Azure Functions)
5. Check the URL used in the Environment variables "WEBSITE_RUN_FROM_PACKAGE"
6. Try to access the URL and find it redirects to a blank page and no zip file is downloaded. https://aka.ms/sentinel-TenableVMAzureSentinelConnector310-functionapp

**Expected behavior**
Previous deployments downloaded a zip file from https://aka.ms/sentinel-TenableIO-functionapp and function app would start and run correctly.

**Screenshots**
Errors in browser when trying to access https://aka.ms/sentinel-TenableVMAzureSentinelConnector310-functionapp
![Image](https://github.com/user-attachments/assets/cf93aa01-5217-47cd-b99b-6729f8b5d0ad)

Deployment of function app shows URL
![Image](https://github.com/user-attachments/assets/c5f623e4-718f-451e-b81c-46fd3bde38cf)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
Please update this URL to direct to a zip file
https://aka.ms/sentinel-TenableVMAzureSentinelConnector310-functionapp
 or change the code on this page to point to a valid URL https://github.com/Azure/Azure-Sentinel/blob/master/Solutions/Tenable%20App/Data%20Connectors/TenableVM/azuredeploy_Connector_TenableVM_AzureFunction.json

**Comment by v-sudkharat** [comment]
Hi @PCNZ, Thanks for flagging this issue, we will investigate this issue and get back to you with some updates. Thanks!

**Comment by v-sudkharat** [comment]
@PCNZ, We have fixed the issue, could you please redeploy / restart the fun app and confirm once. Thanks!

**Comment by v-sudkharat** [comment]
@PCNZ, This issue has been fixed, please let us know/ reopen the case if still it occurred. Many Thanks!

**Comment by PCNZ** [comment]
> [@PCNZ](https://github.com/PCNZ), This issue has been fixed, please let us know/ reopen the case if still it occurred. Many Thanks!

Thanks for the quick action on this @v-sudkharat, yes it's fixed and the package is downloading now on new deployments of the function app.
