### ISSUE TITLE
Get-GitHubRepoLogs fails with "RequestEntityTooLarge" when logging repo comit history

### ISSUE THREAD

**Issue by kirk-spragg** [Azure/Azure-Sentinel#1146]
The Get-GitHubRepoLog logic app fails on our org (seequent) . Send Data 5 fails with an error 'RequestEntityTooLarge. '
![image](https://user-images.githubusercontent.com/26468285/95028311-e5639a00-06fb-11eb-9348-94c8c3eef90a.png)
Unfortunately the repo that causes this failure is private and I am unable to share this outside of my org.

**To Reproduce**
1 - Deploy and configure as per these instructions https://github.com/Azure/Azure-Sentinel/tree/master/DataConnectors/GitHub
2 - Wait for Get-GitHubRepoLog  to run.

**Expected behavior**
Get-GitHubRepoLog  runs without error

**Comment by dicolanl** [comment]
@kirk-spragg I am going to give you a workaround.  this shouldn't normally happen as the Log A api limit is 30MB. which is a lot of JSON!  for some reason your commit log is large.

See Below
![image](https://user-images.githubusercontent.com/25964057/95097719-a83ede00-06e2-11eb-9688-971f6932e60e.png)

You can add a for each loop after For Each 8.  Set the loop to loop on the variable commits.  move send data 5 into the loop and set the data to current item.  This is basically calling the api for each log entry vs batching the logs into 1 submit.  I don't recommend this for all logs in this logic app as its much slower and less efficient.

**Comment by kirk-spragg** [comment]
@dicolanl Given that this playbook currently takes close to 4 hours to run on our org, I don't think that workaround is viable as it will make it take even longer.

It may be simpler to exclude the commit logs completely, what does logging these achieve? 
We have some big repositories with long commit histories, I'm not sure what logging this to an azure sentinel workspace every hour achieves but you may be able to enlighten me on this point.

**Comment by dicolanl** [comment]
@kirk-spragg there are no detections using the commit logs.  but there is a sample hunting query https://github.com/Azure/Azure-Sentinel/blob/master/Hunting%20Queries/GitHub/Suspicious%20Fork%20Activity.yaml 
this kind of sample could be used to look for suspicious activity in the logs.

**Comment by kirk-spragg** [comment]
@dicolanl  I think I've found the root cause of the failure reported in this ticket. The variable that the commit info is appended to is NOT reset between repositories. Thus the contents of "varable 5 "continues to grow with each repo processed (as it is not cleared) and with our large github org with many repos this eventually grows to large to send to our log workspace.

**Comment by dicolanl** [comment]
@kirk-spragg  i saw #1147 .  replied.  

Ok to close this one and work off that one?
