### ISSUE TITLE
Get-GitHubRepoLogs fills the sentinal workspace with numerious duplicate log entries

### ISSUE THREAD

**Issue by kirk-spragg** [Azure/Azure-Sentinel#1147]
**Describe the bug**
https://github.com/Azure/Azure-Sentinel/issues/1146 aside, the Get-GitHubRepoLogs logic app worked for most of our repositories, however one run produces a huge number of what appear to be duplicate log entires in the Azure Sentinal workspace that the logic app is logging to. See this screenshot for an example where it appears that the logic app has logged the same collaborator for a repo repeatedly:

![image](https://user-images.githubusercontent.com/26468285/95029019-87d24c00-0701-11eb-8d8e-24ee6259c6bd.png)

**To Reproduce**
1 - Deploy and configure as per these instructions https://github.com/Azure/Azure-Sentinel/tree/master/DataConnectors/GitHub
2 - Wait for Get-GitHubRepoLog to run.

**Expected behavior**
Log entries would only be entered once, not multiple times in one logic app run.

**Comment by kirk-spragg** [comment]
@dicolanl As per my latest comment in https://github.com/Azure/Azure-Sentinel/issues/1146, the root cause appears to be variables containing repo information (commits, contributors ect) not being cleared between repositories resulting in a steady accumulation of data that is sent to the log workspace with each repo processed.

**Comment by dicolanl** [comment]
@kirk-spragg  got it.  Logic app should clear on each loop, but to make sure it does we will add a variable = null at the end of each loop.

**Comment by dicolanl** [comment]
@kirk-spragg  we updated via #1157 

can we close this issue?

**Comment by kirk-spragg** [comment]
yes
