### ISSUE TITLE
Atlassian Confluence Audit (Preview) connector doesn't work

### ISSUE THREAD

**Issue by odishelidzegio** [Azure/Azure-Sentinel#11475]
**Description**
I'm trying to ingest Atlassian Confluence logs to AZ Sentinel via Atlassian Confluence Audit (Preview) connector. I use auto deploy option. When I'm filling out all the required fields and click deploy, everything is deployed successfully but not a log table is created in the logs analytics and the connector shows disconnected. Tried many times but no success. Deployment is always successful, but the connection status is “disconnected”.

**To Reproduce**
1. From AZ Sentinel content hub, install “Atlassian Confluence Audit (Preview)” connector.
2. Auto-deploy it and see what happens.
3. After successful deployment, check if the connector is connected or not.

**Screenshots**
![Image](https://github.com/user-attachments/assets/bf3bee9e-597a-42f8-bf86-acfc36050aff)

![Image](https://github.com/user-attachments/assets/99c1e9e4-fa3e-4ea5-b755-faf62b5ad3fa)

All deployments are successful:
![Image](https://github.com/user-attachments/assets/c7cc3a21-4f0e-4dcc-b0e2-c54f6cc055ff)

No results after successful deployment:
![Image](https://github.com/user-attachments/assets/d3e40c02-083a-4b6c-b202-83987aba7c1b)

**Comment by v-visodadasi** [comment]
Hi @odishelidzegio , Thanks for flagging this issue, we will investigate this issue and get back to you with some updates. Thanks!!

**Comment by v-sudkharat** [comment]
@odishelidzegio, please do share the function app invocations logs screenshots with us.

**Comment by odishelidzegio** [comment]
@v-sudkharat could you please tell me how exactly do it?

I can only see this:

 ![Image](https://github.com/user-attachments/assets/7e5d61a5-3f66-47e3-bf47-cef722378e1f)

**Comment by v-sudkharat** [comment]
@odishelidzegio 
1. Go to the deployed function app -
![Image](https://github.com/user-attachments/assets/f4d7929e-e17e-4e27-99f6-2c5e08f42955)

2. Go to the invocation tab- 
![Image](https://github.com/user-attachments/assets/e78d2ed8-3522-4b4d-a11e-5f60820b6094)

3. select one of the invocations and send the entire logs message -
![Image](https://github.com/user-attachments/assets/e8b19eb7-37aa-4679-881b-509a0d2952b0)

**Comment by odishelidzegio** [comment]
Thanks for assistance, here's a full log of one of the invocations:

Timestamp	                Log Level	        Message
11/28/2024, 6:20:00 PM	Information	Executing 'Functions.ConfluenceAuditAPISentinelConnector' (Reason='Timer fired at 2024-11- 
                                                                28T14:20:00.0027016+00:00', Id=ca09511b-94c1-47ad-bf19-bc6a9fc8390c)
11/28/2024, 6:20:00 PM	Information	Starting program
11/28/2024, 6:20:00 PM	Information	Request URL: 
                                                                'https://conflauditz3fjcfpooijvs.file.core.windows.net/funcstatemarkershare/funcstatemarkerfile'
11/28/2024, 6:20:00 PM	Information	Request method: 'GET'
11/28/2024, 6:20:00 PM	Information	Request headers:
11/28/2024, 6:20:00 PM	Information	'Accept': 'application/xml'
11/28/2024, 6:20:00 PM	Information	'x-ms-version': 'REDACTED'
11/28/2024, 6:20:00 PM	Information	'x-ms-range': 'REDACTED'
11/28/2024, 6:20:00 PM	Information	'User-Agent': 'azsdk-python-storage-file-share/12.3.0 Python/3.11.10 (Linux-5.10.102.2-microsoft- 
                                                                standard-x86_64-with-glibc2.31)'
11/28/2024, 6:20:00 PM	Information	'x-ms-date': 'REDACTED'
11/28/2024, 6:20:00 PM	Information	Request headers:
11/28/2024, 6:20:00 PM	Information	'x-ms-version': 'REDACTED'
11/28/2024, 6:20:00 PM	Information	'x-ms-content-length': 'REDACTED'
11/28/2024, 6:20:00 PM	Information	'x-ms-type': 'REDACTED'
11/28/2024, 6:20:00 PM	Information	'x-ms-file-permission': 'REDACTED'
11/28/2024, 6:20:00 PM	Information	'x-ms-file-attributes': 'REDACTED'
11/28/2024, 6:20:00 PM	Information	'x-ms-file-creation-time': 'REDACTED'
11/28/2024, 6:20:00 PM	Information	'x-ms-file-last-write-time': 'REDACTED'
11/28/2024, 6:20:00 PM	Information	'User-Agent': 'azsdk-python-storage-file-share/12.3.0 Python/3.11.10 (Linux-5.10.102.2-microsoft- 
                                                                standard-x86_64-with-glibc2.31)'
11/28/2024, 6:20:00 PM	Information	'x-ms-date': 'REDACTED'
11/28/2024, 6:20:00 PM	Information	'x-ms-client-request-id': 'da0765d6-ad93-11ef-ac2f-00155d4b192a'
11/28/2024, 6:20:00 PM	Information	'Authorization': 'REDACTED'
11/28/2024, 6:20:00 PM	Information	No body was attached to the request
11/28/2024, 6:20:00 PM	Information	Response status: 201
11/28/2024, 6:20:00 PM	Information	Response headers:
11/28/2024, 6:20:00 PM	Information	'Content-Length': '0'
11/28/2024, 6:20:00 PM	Information	'Last-Modified': 'Thu, 28 Nov 2024 14:20:00 GMT'
11/28/2024, 6:20:00 PM	Information	'ETag': '"0x8DD0FB7BE3F193F"'
11/28/2024, 6:20:00 PM	Information	'Server': 'Windows-Azure-File/1.0 Microsoft-HTTPAPI/2.0'
11/28/2024, 6:20:00 PM	Information	'x-ms-request-id': '43ed776c-601a-00ab-11a0-419ab0000000'
11/28/2024, 6:20:00 PM	Information	'x-ms-client-request-id': 'da0765d6-ad93-11ef-ac2f-00155d4b192a'
11/28/2024, 6:20:00 PM	Information	'x-ms-version': 'REDACTED'
11/28/2024, 6:20:00 PM	Information	'x-ms-file-change-time': 'REDACTED'
11/28/2024, 6:20:00 PM	Information	'x-ms-file-last-write-time': 'REDACTED'
11/28/2024, 6:20:00 PM	Information	'x-ms-file-creation-time': 'REDACTED'
11/28/2024, 6:20:00 PM	Information	'x-ms-file-permission-key': 'REDACTED'
11/28/2024, 6:20:00 PM	Information	'x-ms-file-attributes': 'REDACTED'
11/28/2024, 6:20:00 PM	Information	'x-ms-file-id': 'REDACTED'
11/28/2024, 6:20:00 PM	Information	'x-ms-file-parent-id': 'REDACTED'
11/28/2024, 6:20:00 PM	Information	'x-ms-request-server-encrypted': 'REDACTED'
11/28/2024, 6:20:00 PM	Information	'Date': 'Thu, 28 Nov 2024 14:19:59 GMT'
11/28/2024, 6:20:00 PM	Information	Request URL: 
                                                                'https://conflauditz3fjcfpooijvs.file.core.windows.net/funcstatemarkershare/funcstatemarkerfile? 
                                                                comp=REDACTED'
11/28/2024, 6:20:00 PM	Information	Request method: 'PUT'
11/28/2024, 6:20:00 PM	Information	Request headers:
11/28/2024, 6:20:00 PM	Information	'Content-Type': 'application/octet-stream'
11/28/2024, 6:20:00 PM	Information	'x-ms-range': 'REDACTED'
11/28/2024, 6:20:00 PM	Information	'x-ms-write': 'REDACTED'
11/28/2024, 6:20:00 PM	Information	'Content-Length': '20'
11/28/2024, 6:20:00 PM	Information	'x-ms-version': 'REDACTED'
11/28/2024, 6:20:00 PM	Information	'User-Agent': 'azsdk-python-storage-file-share/12.3.0 Python/3.11.10 (Linux-5.10.102.2-microsoft- 
                                                                 standard-x86_64-with-glibc2.31)'
11/28/2024, 6:20:00 PM	Information	'x-ms-date': 'REDACTED'
11/28/2024, 6:20:00 PM	Information	'x-ms-client-request-id': 'da0a9e22-ad93-11ef-ac2f-00155d4b192a'
11/28/2024, 6:20:00 PM	Information	'Authorization': 'REDACTED'
11/28/2024, 6:20:00 PM	Information	A body is sent with the request
11/28/2024, 6:20:00 PM	Information	Response status: 201
11/28/2024, 6:20:00 PM	Information	Response headers:
11/28/2024, 6:20:00 PM	Information	'Content-Length': '0'
11/28/2024, 6:20:00 PM	Information	'Content-MD5': 'REDACTED'
11/28/2024, 6:20:00 PM	Information	'Last-Modified': 'Thu, 28 Nov 2024 14:20:00 GMT'
11/28/2024, 6:20:00 PM	Information	'ETag': '"0x8DD0FB7BE4270D1"'
11/28/2024, 6:20:00 PM	Information	'Server': 'Windows-Azure-File/1.0 Microsoft-HTTPAPI/2.0'
11/28/2024, 6:20:00 PM	Information	'x-ms-request-id': '43ed776d-601a-00ab-12a0-419ab0000000'
11/28/2024, 6:20:00 PM	Information	'x-ms-client-request-id': 'da0a9e22-ad93-11ef-ac2f-00155d4b192a'
11/28/2024, 6:20:00 PM	Information	'x-ms-version': 'REDACTED'
11/28/2024, 6:20:00 PM	Information	'x-ms-request-server-encrypted': 'REDACTED'
11/28/2024, 6:20:00 PM	Information	'Date': 'Thu, 28 Nov 2024 14:19:59 GMT'
11/28/2024, 6:20:00 PM	Information	Logs not founded. Time period: from 2024-11-28T14:00:00Z to 2024-11-28T14:10:00Z.
11/28/2024, 6:20:00 PM	Information	Processed 0 events to Azure Sentinel. Time period: from 2024-11-28T14:00:00Z to 2024-11- 
                                                                28T14:10:00Z.
11/28/2024, 6:20:00 PM	Information	Executed 'Functions.ConfluenceAuditAPISentinelConnector' (Succeeded, Id=ca09511b-94c1-47ad- 
                                                                bf19-bc6a9fc8390c, Duration=395ms)

**Comment by v-sudkharat** [comment]
@odishelidzegio, Thanks for sharing the logs. 
As per the shared logs, the logs are not available/ generated in Source itself (Atlassian side), so due to that the correct configured connector has not send any events/ logs in your Sentinel Workspace - 

11/28/2024, 6:20:00 PM Information Logs not founded. Time period: from 2024-11-28T14:00:00Z to 2024-11-28T14:10:00Z.
11/28/2024, 6:20:00 PM Information` Processed 0 events to Azure Sentinel. `Time period: from 2024-11-28T14:00:00Z to 2024-11-
28T14:10:00Z.

If you see in invocation, it mentioned as - `Processed 0 events to Azure Sentinel. `

So, suggestion would be, kindly check the logs are generated/ created in source. Many Thanks!

**Comment by odishelidzegio** [comment]
Yes, I see, and it's strange, because in Confluence I see the Audit Logs.

This is from Confluence's side, and there are so many logs:

![Image](https://github.com/user-attachments/assets/c23f8bc5-5122-4c29-a28f-6dd86717dac3)

**Comment by odishelidzegio** [comment]
@v-sudkharat I don't know how, but the connector has been fixed. I have not made changes to it or to confluence, fixed by itself I guess.

The logs are now ingested, so we can close the issue, I believe.

Thanks for your help!
