### ISSUE TITLE
Unable to run Playbook-ARM-Template-Generator on Mac

### ISSUE THREAD

**Issue by ashwinvenkatesha** [Azure/Azure-Sentinel#11501]
**Describe the bug**
Unable to run Playbook-ARM-Template-Generator on Mac

**To Reproduce**
1. Downloaded zip from https://github.com/Azure/Azure-Sentinel/tree/master/Tools/Playbook-ARM-Template-Generator
2. Opened a pwsh terminal and ran Playbook_ARM_Template_Generator.ps1
3. Tenant id was provided
3. After giving next inputs N and N
Error When trying to connect to tenant : The term 'Out-GridView' is not recognized as a name of a cmdlet, function, script file, or executable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.

**Expected behavior**
Should be able to select the playbooks in the tenant

**Desktop (please complete the following information):**
 - OS: Mac OS

**Comment by v-visodadasi** [comment]
Hi @ashwinvenkatesha  , Thanks for flagging this issue, we will investigate this issue and get back to you with some updates. Thanks!

**Comment by v-sudkharat** [comment]
@ashwinvenkatesha, just tried to replicate the same in PS: 
![Image](https://github.com/user-attachments/assets/d56b17b4-9454-40cd-babd-b5f58ac5f0e6)

After tenant Id, I have set command Y to update the existing PowerShell modules. So, Could you plz try the same in MAC as well and let us know the result.

**Comment by v-sudkharat** [comment]
@ashwinvenkatesha, Closing it.  If you still need support for this issue, feel free to re-open it any time. Thank you for your co-operation.
