### ISSUE TITLE
Unable to package solution using v3 createsolution.ps1

### ISSUE THREAD

**Issue by ashwinvenkatesha** [Azure/Azure-Sentinel#11512]
**Describe the bug**
Unable to package solution using v3 createsolution.ps1

**To Reproduce**
After adding playbook content
1. Am running createSolution.ps1 with data path as input 
 `/Users/<username>/Azure-Sentinel/Solutions/IllumioSaaS/data`

This leads to, 
Generating Playbook using Playbooks/Illumio-Port-Blocking-Switch/azuredeploy.json
Error occured in catch of createSolutionV3 file Error details are Exception calling "Add" with "2" argument(s): "Value cannot be null. (Parameter 'key')"

**Expected behavior**
Solution package should work as expected.

**Comment by v-prasadboke** [comment]
Hello @ashwinvenkatesha, As discussed we will be working on this and try to resolve it from our. 

Will be checking with MS team if needed

**Comment by ashwinvenkatesha** [comment]
Here is the fix which helped unblock me
https://github.com/Azure/Azure-Sentinel/pull/11515/commits/d40340c9ed51e75b6d9186e7fd797c12e15866ba

**Comment by v-visodadasi** [comment]
Hi @ashwinvenkatesha , I wanted to check in and see if the issue has been resolved from your end. Please let me know at your earliest convenience.

**Comment by v-sudkharat** [comment]
> Here is the fix which helped unblock me [d40340c](https://github.com/Azure/Azure-Sentinel/commit/d40340c9ed51e75b6d9186e7fd797c12e15866ba)

@ashwinvenkatesha, As mentioned in above comment, closing this issue.
