### ISSUE TITLE
Get-GitHubRepoLogs fails if you have an empty repo in your github org

### ISSUE THREAD

**Issue by kirk-spragg** [Azure/Azure-Sentinel#1151]
**Describe the bug**
The step "HTTP 6" in the loop "For each" will fail with a http 409 if the repo being processed by the loop happens to be empty.
Found this just due to unfortunate timing, a dev must have created a new repo and the logic app caught it before they had commited anything.
![image](https://user-images.githubusercontent.com/26468285/95272895-18de2a00-089e-11eb-89ac-81b8a3600208.png)

**To Reproduce**
1 - Deploy and configure as per these instructions https://github.com/Azure/Azure-Sentinel/tree/master/DataConnectors/GitHub
2 - Add an empty repository to one of the github orgs monitored by the deployed logic apps.
3 - Run Get-GitHubRepoLogs or wait for the scheduled run and the error should occure as described at the top.

**Expected behavior**
It works without error.

**Comment by dicolanl** [comment]
@kirk-spragg we updated via #1157 
can we close this issue?

**Comment by kirk-spragg** [comment]
@dicolanl  sure!
