### ISSUE TITLE
Device details in the logs from Jumpcloud to sentinel are missing in randam sso event logs

### ISSUE THREAD

**Issue by harishmenti** [Azure/Azure-Sentinel#11535]
Hi Team,

We have integrated Jump Cloud with Sentinel to forward all the logs to Sentinel using the function app with the code found in GitHub. We've been encountering a few logs with missing device details and IP addresses, leading to incident creation ( as we have custom rules to compare IPs against device details). We contacted Jumpcloud, and they stated it was not their responsibility to troubleshoot since the data connector was developed and managed by Azure.. ![Image](https://github.com/user-attachments/assets/3b75c38d-1e9e-4d1d-9797-4da7b4bca182)

**Comment by v-sudkharat** [comment]
Hi @harishmenti, Thanks for flagging this issue, we will investigate this issue and get back to you with some updates. Thanks!

**Comment by v-sudkharat** [comment]
@harishmenti, want to confirm, is this a path for function app -https://github.com/Azure/Azure-Sentinel/tree/5891abc456cd8cceb0b724a9f737b81aae67298a/DataConnectors/JumpCloud%20Single%20Sign%20On which has been configured? 
And could you please share the log's with us, to understand the issue. Thanks!

**Comment by harishmenti** [comment]
Yes, that was the path for the function app that had been configured. I'm attaching the logs and highlighting the events where the device details and IP were not captured. Just a heads up, the device details and IP are missing in the “push_mfa_attempt_failed” events.

Best regards,
Harish Menti.
[signature_1067390269]Permitted by SAMA for Regulatory Sandbox testing and regulated by the CBB and the DFSA as an AISP/PISP.

Harish Menti
Cybersecurity Analyst
Permitted by SAMA for Regulatory Sandbox testing and regulated by the CBB as an AISP/PISP.
From: v-sudkharat ***@***.***>
Date: Thursday, 12 December 2024 at 10:58 AM
To: Azure/Azure-Sentinel ***@***.***>
Cc: Harish Menti ***@***.***>, Mention ***@***.***>
Subject: Re: [Azure/Azure-Sentinel] Device details in the logs from Jumpcloud to sentinel are missing in randam sso event logs (Issue #11535)

CAUTION: This email originated from outside the organization. Do not click links or open attachments unless you recognize the sender and know the content is safe.

@harishmenti<https://github.com/harishmenti>, want to confirm, is this a path for function app -https://github.com/Azure/Azure-Sentinel/tree/5891abc456cd8cceb0b724a9f737b81aae67298a/DataConnectors/JumpCloud%20Single%20Sign%20On which has been configured?
And could you please share the log's with us, to understand the issue. Thanks!

**Comment by harishmenti** [comment]
Please take a look at the logs in the attachments.

Best regards,
Harish Menti.
[signature_1067390269]Permitted by SAMA for Regulatory Sandbox testing and regulated by the CBB and the DFSA as an AISP/PISP.

Harish Menti
Cybersecurity Analyst
Permitted by SAMA for Regulatory Sandbox testing and regulated by the CBB as an AISP/PISP.
From: v-sudkharat ***@***.***>
Date: Thursday, 12 December 2024 at 1:46 PM
To: Azure/Azure-Sentinel ***@***.***>
Cc: Harish Menti ***@***.***>, Mention ***@***.***>
Subject: Re: [Azure/Azure-Sentinel] Device details in the logs from Jumpcloud to sentinel are missing in randam sso event logs (Issue #11535)

CAUTION: This email originated from outside the organization. Do not click links or open attachments unless you recognize the sender and know the content is safe.

@harishmenti<https://github.com/harishmenti>, Not able to see the logs here, can you plz share it on this mail ID - ***@***.******@***.***>

**Comment by v-sudkharat** [comment]
@harishmenti, received the mail, checking on it. Thanks!

**Comment by v-sudkharat** [comment]
@harishmenti, Thank you for sending the logs with us. 
Just want to understand, Is device IP and device details are not get fetched for below specific events only, right?
![Image](https://github.com/user-attachments/assets/a0caa653-4d40-4e51-9d92-11b7c05994c0)

found one JumpCloud doc where some certain details are mentioned about it - 
Doc link -https://jumpcloud.com/support/jumpcloud-protect-for-admins

![Image](https://github.com/user-attachments/assets/6a4c13d8-b9da-48d5-a190-80fa25f08dcc)

the missing device details and IP addresses might be due to authentication failures or incomplete data capture in source itself. If the user's access was initially denied while the authentication process, the corresponding logs and data may not have been generated. As a result, the data connector might not be able to fetch all the necessary fields from **Jump Cloud**, as the authentication attempt didn’t fully complete. 

Many Thanks!

**Comment by MH-CSA** [comment]
Hi @harishmenti i've just deployed the connector and am waiting for data to ingest, i noticed in the function app a banner around upgrading the runtime version, can you advise if you update it or not?

**Comment by harishmenti** [comment]
Hi,

Yes, the IP and device details are missing only in the failed MFA push attempts event logs. Thanks for providing the link and the theoretical explanation makes sense.

In the function app, the runtime version is shown as “Error”. Kindly let me know how to proceed on upgrading. I would want to ensure this action will not affect the current functionality and no interruption in receiving logs. Please, refer to the attachment for the error I was mentioning.

Best regards,
Harish Menti.
[signature_1067390269]Permitted by SAMA for Regulatory Sandbox testing and regulated by the CBB and the DFSA as an AISP/PISP.

Harish Menti
Cybersecurity Analyst
Permitted by SAMA for Regulatory Sandbox testing and regulated by the CBB as an AISP/PISP.
From: MH-CSA ***@***.***>
Date: Tuesday, 17 December 2024 at 7:45 PM
To: Azure/Azure-Sentinel ***@***.***>
Cc: Harish Menti ***@***.***>, Mention ***@***.***>
Subject: Re: [Azure/Azure-Sentinel] Device details in the logs from Jumpcloud to sentinel are missing in randam sso event logs (Issue #11535)

CAUTION: This email originated from outside the organization. Do not click links or open attachments unless you recognize the sender and know the content is safe.

Hi @harishmenti<https://github.com/harishmenti> i've just deployed the connector and am waiting for data to ingest, i noticed in the function app a banner around upgrading the runtime version, can you advise if you update it or not?

**Comment by v-sudkharat** [comment]
@harishmenti / @MH-CSA : 

To address this issue, you can follow below step 1 for existing deployed function app and Step 2 for new deployment:
 
Step 1:

a. Go to deployed function app Environment Variable tab and update the Website Run from Package Like with below shared one and save the changes:

New like - https://aka.ms/sentinel-Jumpcloud-functionapp

![Image](https://github.com/user-attachments/assets/07e3504a-91ec-4094-ae1a-5834263548af)

b. Then go to Configuration tab and change its runtime version to ~4 :

![Image](https://github.com/user-attachments/assets/53c87da4-e365-4646-9e13-f4fc7af51a8b)

c. Then in next step, Upgrade the PowerShell version to 7.4 and save the settings: 

![Image](https://github.com/user-attachments/assets/ca127a64-bbb1-45c7-9b7b-35d5951d47c5)

Once the above steps completed, restart the function app. 

Step 2: 

We have updated the Readme doc with corrections, so just simple re-deploy the function app from it: 
https://github.com/Azure/Azure-Sentinel/blob/4e8f5dc628dbc1a177cd764d1b67e842965df74b/DataConnectors/JumpCloud%20Single%20Sign%20On/Readme.md

Hope the above shared steps help you to resolve the issue. Please confirm once it done so we can mark the issue as close. 

Many Thanks!

**Comment by v-sudkharat** [comment]
@MH-CSA, PR has been merged with the fix. Thanks!
