### ISSUE TITLE
Non Domain Controller Active Directory Replication (Windows Security Events/Analytic Rules/NonDCActiveDirectoryReplication)

### ISSUE THREAD

**Issue by jlextremeiro** [Azure/Azure-Sentinel#11544]
In the Solutions/Windows Security Events/Analytic Rules/NonDCActiveDirectoryReplication.yaml
the condition 
//| where Computer in (DCServersList)
Shouldn't be 
//| where Computer !in (DCServersList).

**Comment by v-visodadasi** [comment]
Hi @jlextremeiro , Thanks for flagging this issue, we will investigate this issue and get back to you with some updates. Thanks!

**Comment by v-visodadasi** [comment]
Hi @jlextremeiro , Can you please provide more details?

**Comment by v-visodadasi** [comment]
Hi @jlextremeiro , Could you please provide clarification on this?

**Comment by v-visodadasi** [comment]
Hi @jlextremeiro , since we have not received a response in the last 5 days, we are closing your issue as per our standard operating procedures. If you still need support for this issue, feel free to re-open at any time.

Thank you for your co-operation.
