### ISSUE TITLE
M365Defender-VulnerabilityManagement - failing deployment every time at Microsoft.Web/sites with ServiceUnavailable error

### ISSUE THREAD

**Issue by SergGu** [Azure/Azure-Sentinel#11540]
**Describe the bug**
We tried deploying https://github.com/Azure/Azure-Sentinel/tree/master/DataConnectors/M365Defender-VulnerabilityManagement multiple times (using several test subscriptions and several admin accounts) and it fails every time at one of the Function App import stages, the error is seems to be related to storage access.
@anders-alex FYI - you seem to be the last person updating the code.

**To Reproduce**
1. Go to https://github.com/Azure/Azure-Sentinel/tree/master/DataConnectors/M365Defender-VulnerabilityManagement
2. Click on 'Deploy to Azure', provide required customisations (e.g. mandatory lint to Log Analytics)
3. Start deployment
4. See error "Storage access failed. Storage volume is currently in R/O mode. Please delete and recreate backup schedule to mitigate."

**Expected behavior**
It is expected that deployment will be finished and the Function App will start.

**Screenshots**
![Image](https://github.com/user-attachments/assets/bf4186c4-8617-47f0-9f1c-159999245a34)

**Desktop (please complete the following information):**
 - OS: Win11/Win10
 - Browser chrome, firefox
 - Version N/A

**Smartphone (please complete the following information):**

**Additional context**
{
    "status": "Failed",
    "error": {
        "code": "ServiceUnavailable",
        "message": "Storage access failed. Storage volume is currently in R/O mode. Please delete and recreate backup schedule to mitigate.",
        "details": [
            {
                "message": "Storage access failed. Storage volume is currently in R/O mode. Please delete and recreate backup schedule to mitigate."
            },
            {
                "code": "ServiceUnavailable"
            },
            {}
        ]
    }
}

**Comment by SergGu** [comment]
This seems to be a region specific Function App issue. The deployment fails in UK East but works fine in other regions.

**Comment by v-sudkharat** [comment]
Hi @SergGu, Thanks for flagging this issue, we will investigate this issue and get back to you with some updates. Thanks!

**Comment by v-sudkharat** [comment]
@SergGu, Yes, it might be due to the R/O mode switched automatically due to the (backups, update) for that specific time period. 
Could you please redeploy it in that region again and let us know if still it has same error.

**Comment by v-sudkharat** [comment]
> This seems to be a region specific Function App issue. The deployment fails in UK East but works fine in other regions.

Ok, Can we close this issue, if its resolve for you?

**Comment by v-sudkharat** [comment]
@SergGu, waiting for the closer confirmation. Thanks!

**Comment by v-sudkharat** [comment]
@SergGu, Thanks for the confirmation.

**Comment by anders-alex** [comment]
@SergGu - I finally got some time to look at this and was able to reproduce. I found the issue and will be pushing a new release to address. Thanks for bringing this to my attention as I bet others are also running into this.
