### ISSUE TITLE
Snowflake Data Connector Authentication to KeyPair Base

### ISSUE THREAD

**Issue by rajj281** [Azure/Azure-Sentinel#11562]
**Is your feature request related to a problem? Please describe.**
Can we switch the snowflake connector from username/password to key pair based authentication or using oauth based.

See announcement made by Snowflake https://www.snowflake.com/en/blog/multi-factor-identification-default/?mkt_tok=MjUyLVJGTy0yMjcAAAGWByH9CYVsuVzPa2Xa6RUowiKSpiTyAyu22UZ3Vv01cBKdXKxzou7Oh8Hrr0AVuwcqoJl3jKOmovqYLRJxY3A7tnWlJVScvf9MDQdywVP24hZudVjBOw

**Comment by v-sudkharat** [comment]
Hi @rajj281, Thanks for flagging this issue, we will investigate this issue and get back to you with some updates. Thanks!

**Comment by v-sudkharat** [comment]
@rajj281, thank you for sharing this feature request with us. We will review it and pass it along to the relevant data connector team for further consideration. While we currently don't have an estimated timeline for this, we will keep you updated and share any progress via GitHub once available.
Closing this issue from GitHub. If you still need support for this issue, feel free to re-open it any time. Thank you for your co-operation.

**Comment by katerobson08** [comment]
Hi @v-sudkharat, are there any updates on when the connector will be amended?

**Comment by v-tsawant** [comment]
Hi @rajj281, we have updated this issue to PM to posterized. While we currently don't have an estimated timeline for this, we will keep you updated and share any progress via GitHub once available.
Closing this issue from GitHub. If you still need support for this issue, feel free to re-open it any time. Thank you for your co-operation.

**Comment by jnawk** [comment]
"Not planned" is not an acceptable position.  The clock is ticking, either you implement the support, or your product stops working with that product.  Closing tickets like this is really not great optics.  Is that really the kind of messaging you want to send to your customers?

**Comment by artisticcheese** [comment]
Legacy_service (which allows username/password) authentication is scheduled to be retired https://docs.snowflake.com/en/user-guide/security-mfa-rollout in Aug 26. Keypair auth is the only solution for reliable connectivity.
