### ISSUE TITLE
Defender XDR - Ingest Defender Vulnerability Management tables to Azure Sentinel/Log Analytics

### ISSUE THREAD

**Issue by aka0** [Azure/Azure-Sentinel#11576]
**Is your feature request related to a problem? Please describe.**

Currently the Defender for XDR data connector does not ingest tables under Defender Vulnerability Management. Specifically, these tables are only available under "Advanced hunting" in the Defender portal and not in Azure Sentinel:

DeviceBaselineComplianceAssessment
DeviceBaselineComplianceAssessmentKB
DeviceBaselineComplianceProfiles
DeviceTvmBrowserExtensions
DeviceTvmBrowserExtensionsKB
DeviceTvmCertificateInfo
DeviceTvmHardwareFirmware
DeviceTvmInfoGathering
DeviceTvmInfoGatheringKB
DeviceTvmSecureConfigurationAssessment
DeviceTvmSecureConfigurationAssessmentKB
DeviceTvmSoftwareEvidenceBeta
DeviceTvmSoftwareInventory
DeviceTvmSoftwareVulnerabilities
DeviceTvmSoftwareVulnerabilitiesKB

**Describe the solution you'd like**

Defender for XDR data connector should ingest the tables noted above, similar to the standard tables such as DeviceFileEvents and DeviceProcessEvents.

Without these tables, Sentinel users are unable to craft analytics rules using data found through these tables.

**Describe alternatives you've considered**

N/A.

**Additional context**
N/A.

**Comment by v-sudkharat** [comment]
Hi @aka0, Thanks for flagging this issue, we will investigate this issue and get back to you with some updates. Thanks!

**Comment by v-sudkharat** [comment]
@aka0, thank you for highlighting this feature request with us. We have taken note of it and will forward it to the respective data connector team. Once we receive any updates on this feature request, we will inform you. Closing this issue for now. If you still need support, feel free to reopen it at any time. Thank you for your cooperation.

**Comment by tgpaysan** [comment]
Any news on this feature request? It would be nice to have those tables available in Defender  xdr connector for data ingestion to sentinel analytics.

**Comment by AmudaPalani** [comment]
@v-sudkharat Can you please confirm if these tables are ingested into Sentinel?
