### ISSUE TITLE
Salesforce connector runs out of memory

### ISSUE THREAD

**Issue by amatasci** [Azure/Azure-Sentinel#11580]
**Describe the bug**
Depending on the amount of events to ingest, the Salesforce Function App can run out of memory and stop ingesting audit events

**To Reproduce**
1. Deploy the Sentinel Salesforce connector
2. Configure it to run daily
3. The function app will run every day and be end in an Error status
4. The error will be something like "Executed 'Functions.SalesforceSentinelConnector' (Failed, Id=4a05cd16-e314-4a2e-ae28-xxxxxxxxx, Duration=84034ms)". After opening a support case (#2412090050003338) it has been confirmed that the issue is related to the function running out of memory

**Expected behavior**
The function app should ingest all events regardless of the number and without running out of memory

**Screenshots**
![Image](https://github.com/user-attachments/assets/d06526ea-a820-42c6-80dd-d0ea3fc57ccd)

**Comment by v-sudkharat** [comment]
Hi @amatasci, Thanks for flagging this issue. Could you please let us know what's your current plan for function app? And to address out of memory issue you can update the function app plan to Premium app service plan. 
Here is a doc which can help to upgrade the plan - https://learn.microsoft.com/en-us/azure/azure-functions/functions-premium-plan?tabs=portal

**Comment by amatasci** [comment]
Hello, we have a Dynamic / Y1 plan, this is the default one created during the deployment of the connector.
How can we modify it to a Premium one?

**Comment by v-sudkharat** [comment]
@amatasci - 
1 :
![Image](https://github.com/user-attachments/assets/296b5e3b-6ff4-41ff-9959-141b0481036f)

2: 
![Image](https://github.com/user-attachments/assets/108b4a34-5bd7-40ed-a3b6-7bd206c74d26)

**Comment by amatasci** [comment]
This possibility isn't available, all options are grayed out

**Comment by v-sudkharat** [comment]
@amatasci, Is the raised support case are still open? Actually, this upgradation for existing app service needs to be check by the function app team.

**Comment by amatasci** [comment]
No, MS support closed it because they said it's not a Function App issue

**Comment by v-sudkharat** [comment]
@amatasci, 
The current existing deployed function app which contains **consumption plan** does not support the upgrade, so creation of new function app with premium plan helps you to get unblocked from this issue. 

You can follow the below shared doc to create a function app manually by selecting the plan according to your requirement:-

- https://learn.microsoft.com/en-us/azure/azure-functions/functions-create-function-app-portal?pivots=programming-language-python

Please go through the below doc for Function App plans with pricing details: - 
https://learn.microsoft.com/en-us/azure/azure-functions/functions-scale?WT.mc_id=AZ-MVP-5003203#overview-of-plans

Additionally, 
We have updated the below ARM template in which the plan has been upgraded to the `PremiumV2` but unable to test it due permission / credentials required.
 If you have any `Testing Environment` (**Not production**), could you please deploy the below shared ARM template by using custom deployment and check for the connector working status - 
ARM template file : - [azuredeploy_Connector_Salesforce_Service_Cloud_AzureFunction.json](https://github.com/user-attachments/files/18253185/azuredeploy_Connector_Salesforce_Service_Cloud_AzureFunction.json)

To custom deploy this template :- 
a. Search Custom deployment in azure home page : 
![Image](https://github.com/user-attachments/assets/eca18827-1f10-4f40-ba58-4284ce1596e2)

b. Select it and past the above ARM template content in custom deployment page :- 
![Image](https://github.com/user-attachments/assets/30918503-c94d-41c1-ad6f-69228db927a6)
c.
 ![Image](https://github.com/user-attachments/assets/b708d95d-f4fd-4ff4-9124-214072f084ad)

Note that, Please do change the function app name while deployment of function in same resource group where old fun app has been already deployed to avoid the existing function override.
 
Once this function app gets deployed successfully, kindly monitor the logs flow and let us know if you get error. 

Many thanks!

**Comment by amatasci** [comment]
Hello, I tested the new ARM template in our Lab.
Using the "daily" schedule the issue is now another one:

![Image](https://github.com/user-attachments/assets/443b8c5e-7214-4579-b605-d73915f8c37f)

Can we increase the timeout in the host.json file from the ARM template?

Many thanks

**Comment by v-sudkharat** [comment]
@amatasci, Sure, we can. 

Updated the **functionTimeout** to 30 min in **Host.json** file and updated it into below shared zip file: 

WEBSITE_RUN_FROM_PACKAGE: - https://github.com/Azure/Azure-Sentinel/raw/c053fb15cc0050720fcb09fe081812cb2fc258d6/Solutions/Salesforce%20Service%20Cloud/Data%20Connectors/SalesforceSentinelConn.zip

You can update the WEBSITE_RUN_FROM_PACKAGE link with above shared link and test for the function app by restart it once. 


![Image](https://github.com/user-attachments/assets/bec54808-38df-41f2-80da-24c7c8367298)

![Image](https://github.com/user-attachments/assets/8e660b8d-e6ba-4e3f-b677-32597e77dfad)

Please kindly let us know if any error occurred. Thanks!

**Comment by amatasci** [comment]
I will test it iin the coming weeks, in the meantime my workoround is to run the function suing an "hourly" schedule

**Comment by v-sudkharat** [comment]
@amatasci, Noted. So, as of now, its ok to close this ticket or do you want to keep it open?

**Comment by amatasci** [comment]
I sit fine to close it for now.
Many thanks

**Comment by v-sudkharat** [comment]
@amatasci, Ok, closing this issue. If you still need support for this issue, feel free to re-open it any time. Thank you for your co-operation.
