### ISSUE TITLE
Okta SSO CCP Issue - Deployment template validation failed

### ISSUE THREAD

**Issue by its-sukhi** [Azure/Azure-Sentinel#11583]
I've just attempted to connect our Okta instance to Sentinel through the Okta SSO Codeless Connector Platform (CCP) data connector instead of the Azure Functions data connector and am getting a 'Deployment template validation failed' error when trying to deploy it using my Domain name and API token.

The following is the JSON error I get from Sentinel:
`
 "correlationId": "8d4661fc-53de-4ce0-9122-07a6cc423aaf",
    "description": "",
    "eventDataId": "dbd8dafa-7189-4dec-bbc4-a6f14535c57f",
    "eventName": {
        "value": "EndRequest",
        "localizedValue": "End request"
    },
    "category": {
        "value": "Administrative",
        "localizedValue": "Administrative"
    },
    "eventTimestamp": "2024-12-18T20:07:16.4020801Z",
    "id": "/subscriptions/xxx/resourcegroups/xxx/providers/Microsoft.Resources/deployments/DataConnector-OktaSSOv2Connections/events/dbd8dafa-7189-4dec-bbc4-a6f14535c57f/ticks/638701492364020801",
    "level": "Error",
    "operationId": "cfc84c10-a519-4589-bbb7-9ecdfb9b1dbe",
    "operationName": {
        "value": "Microsoft.Resources/deployments/write",
        "localizedValue": "Create Deployment"
    },
    "resourceGroupName": "xxx",
    "resourceProviderName": {
        "value": "Microsoft.Resources",
        "localizedValue": "Microsoft Resources"
    },
    "resourceType": {
        "value": "Microsoft.Resources/deployments",
        "localizedValue": "Microsoft.Resources/deployments"
    },
    "resourceId": "/subscriptions/xxx/resourcegroups/xxx/providers/Microsoft.Resources/deployments/DataConnector-OktaSSOv2Connections",
    "status": {
        "value": "Failed",
        "localizedValue": "Failed"
    },
    "subStatus": {
        "value": "BadRequest",
        "localizedValue": "Bad Request (HTTP Status Code: 400)"
    },
    "submissionTimestamp": "2024-12-18T20:08:53Z",
    "subscriptionId": "xxx",
    "tenantId": "xxx",
    "properties": {
        "statusCode": "BadRequest",
        "serviceRequestId": null,
        "statusMessage": "{\"error\":{\"code\":\"InvalidTemplate\",\"message\":\"Deployment template validation failed: 'The template resource 'xxx/Microsoft.SecurityInsights/{{innerWorkspace}}/Microsoft.SecurityInsights/OktaDCV1_{{domainname}}' for type 'Microsoft.OperationalInsights/workspaces/providers/dataConnectors' at line '60' and column '85' has incorrect segment lengths. A nested resource type must have identical number of segments as its resource name. A root resource type must have segment length one greater than its resource name. Please see https://aka.ms/arm-syntax-resources for usage details.'.\",\"additionalInfo\":[{\"type\":\"TemplateViolation\",\"info\":{\"lineNumber\":60,\"linePosition\":85,\"path\":\"properties.template.resources[0].type\"}}]}}",
        "eventCategory": "Administrative",
        "entity": "/subscriptions/xxx/resourcegroups/xxx/providers/Microsoft.Resources/deployments/DataConnector-OktaSSOv2Connections",
        "message": "Microsoft.Resources/deployments/write",
    },
    "relatedEvents": []
`

It seems like the request isn't making it to the Okta side from looking at the last used date/time for the API token. I've tested in two separate Azure accounts with two different Okta repos on each and it's giving me the same error each time.

Any help with this would be appreciated and please let me know if any further information is required.

**Comment by v-sudkharat** [comment]
Hi @its-sukhi, Could you please deploy the updated template into the workspace and let us know if still facing the same issue.

 The custom deployment steps are mentioned into below file : 
Custom Deployment - [CustomDeploymentSteps.docx](https://github.com/user-attachments/files/16782483/CustomDeploymentSteps.docx)
Template File - [mainTemplate.json](https://github.com/user-attachments/files/18193245/mainTemplate.json)

Once the solution is deployed successfully, re-configure the connector. Thanks !

**Comment by its-sukhi** [comment]
Hey @v-sudkharat thank you for the quick reply. I have followed the instructions and can confirm that the connectors now works. Thank you very much!

**Comment by jane152-beep** [comment]
Hi @v-sudkharat I'm having the same issue, but the template you shared on 19/12 doesn't seem to work for me. Do you have any ideas? Thanks!
