### ISSUE TITLE
CiscoISEEvent parser can't interpret multiline syslogs

### ISSUE THREAD

**Issue by DHCW-Operational-Security** [Azure/Azure-Sentinel#11581]
**Describe the bug**
When ISE has logs which are longer than the "Maximum Length" configured in the External Syslog Server, they are sent as multiple syslogs which can be correlated via an ID at the start of each message

**To Reproduce**
Steps to reproduce the behaviour:
1. Configure Cisco ISE to send syslogs to a server which is configured with AMA to send logs into sentinel.
2. Receive logs which are longer than the "Maximum Length" configured in ISE.
3. Use the CiscoISEEvent parser (part of the "Cisco ISE" solution on the content hub).
4. This will parse some logs correctly (the first syslog of each ISE log), but the subsequent syslogs for that ISE log will not be parsed correctly because they start halfway through the log.

**Expected behaviour**
The CiscoISEEvent parser should parse the logs into their respective fields.

**Screenshots**
Here are the raw syslogs as they are ingested into sentinel, you can see there are multiple syslogs for each "ISE log" (I've outlined each "ISE log" for clarity). 
![Image](https://github.com/user-attachments/assets/60caab63-04ad-46a4-a8f2-9e0a9f4b7ab3)

Each syslog starts with the following syntax "[ISE message ID] [number of syslogs for this ISE message] [sequence number]":
![Image](https://github.com/user-attachments/assets/9ed1c0f5-0f8c-4cc6-90f5-4f135948955f)

Because the ISE logs are split over multiple syslogs, it causes the default CiscoISEEvent parser to fail:
![Image](https://github.com/user-attachments/assets/993d4b1d-34ba-4b8e-9d08-ca4ec4373477)

I've added the following 4 lines of KQL between line 4 and 5 in the default parser, this seems to have resolved the issue:
    | parse SyslogMessage with MessageID " " NumberOfSyslogs " " SequenceNo " " RestOfMessage
    | order by MessageID, NumberOfSyslogs, SequenceNo asc 
    | summarize count(), SyslogArray = make_set(RestOfMessage), TimeGenerated = arg_max(TimeGenerated, *) by MessageID
    | extend SyslogMessage = strcat_array(SyslogArray, "")
![Image](https://github.com/user-attachments/assets/dc9e1059-2d8e-4509-926a-89c5f79ae24b)

See the full parser with my updates here:
[Cisco ISE parser - with multiline parsing.txt](https://github.com/user-attachments/files/18186836/Cisco.ISE.parser.-.with.multiline.parsing.txt)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Edge for business
 - Version: Version 131.0.2903.99 (Official build) (64-bit)

**Additional context**

**Comment by v-sudkharat** [comment]
Hi @DHCW-Operational-Security, Thanks for flagging this issue, we will investigate this issue and get back to you with some updates. Thanks!

**Comment by v-sudkharat** [comment]
@DHCW-Operational-Security, Correct. the RAW **syslogmessage** format are splits when it's extended the certain length. 
So, want to understand with your shared scenario, did your shared parser is successfully working for you? And parsing this raw syslog without any fail?
Additionally, you can save that updated parser in parser function with same name for use. 

Thanks!

**Comment by DHCW-Operational-Security** [comment]
The previous "fixed" version couldn't handle non-multiline syslogs, or logs where we've lost one of the packets. Please see the attached v2, it parses single line ISE logs, and drops any logs where we've missed one of the packets for that ISE message (couldn't think of a better way of handling it).

[Cisco ISE parser - with multiline parsing v2.txt](https://github.com/user-attachments/files/18198640/Cisco.ISE.parser.-.with.multiline.parsing.v2.txt)

**Comment by v-sudkharat** [comment]
@DHCW-Operational-Security ,  thank you for presenting this unique scenario and sharing its alternate solutions too. This will undoubtedly help us better understand the syslog raw data patterns, enabling us to enhance the existing parser. We truly appreciate your assistance and coordination on this matter.
As your issue has been fixed, closing this issue from GitHub. If you still need support for this issue, feel free to re-open it any time. Thank you for your co-operation.
