### ISSUE TITLE
Syslog appears to be connected but no data seen from on prem syslog server.  

### ISSUE THREAD

**Issue by jrkingsgate** [Azure/Azure-Sentinel#1171]
**Is your feature request related to a problem? Please describe.**
We noticed that the syslog is showing connected but there's no real way to verify where the disconnect has occurred other than the graph stating there's no data. 

**Describe the solution you'd like**
An easy way to determine if the on premise syslog server is indeed transmitting data from on prem to sentinel and which computers ARE connected.

**Describe alternatives you've considered**
I have verified the data is being ingested by the syslog server, but this only occurred after we reduced the number of items being ingested from informational to notification levels.  SInce then, we can't tell if anything is happened. 

**Additional context**
I have attempted to reinstall the agent, but Sentinel still doesn't show that there is data flowing from this particular syslog. Of note:  Sentinel no longer sees the on prem syslog system, if I ran the Kusto query related to linux computers correctly.  Since we have no way of remove and re-add the agent, then we have no way of knowing where the true issue lies.  So a better troubleshooting tool for connectivity and data flow checking would be great. 

![2020-10-13 16_19_26-Azure Sentinel - Microsoft Azure](https://user-images.githubusercontent.com/50936064/95912107-5e07cd80-0d70-11eb-88ac-35ee210685f5.png)

**Comment by sarah-yo** [comment]
Hello, if this is still a problem as this is related to a production feature rather than the content of Sentinel analytics rules, workbooks, playbooks or hunting queries this needs to be raised as an ticket in the Azure portal, thanks!
