### ISSUE TITLE
Issue with Playbook: IdentityProtection-TeamsBotResponse

### ISSUE THREAD

**Issue by richlilly2004** [Azure/Azure-Sentinel#1172]
@lior-tamir 
When deploying from the template, receive the following when trying to authorize the connection for IDP

Sorry, but we’re having trouble signing you in.

AADSTS50020: User account 'RLilly@test.com' from identity provider 'https://sts.windows.net/f224444-5f00-44e8-babd-133e9cd928d1/' does not exist in tenant 'AmbaWolvesE5' and cannot access the application 'b37216c7-2651-4ee5-9c5d-617a30978148'(AADIP) in that tenant. The account needs to be added as an external user in the tenant first. Sign out and sign in again with a different Azure Active Directory user account.

**Comment by lior-tamir** [comment]
Thanks for the feedback. We are investigating this issue and will update.

**Comment by 54845043589340** [comment]
We have observed the same behavior as well.  It's almost as if the tenantid is hardcoded to use that 'AmbdaWolvesE5' tenant.  Have you been able to reproduce @lior-tamir

**Comment by lior-tamir** [comment]
This bug is still in fix on our side. Will update when fix was uploaded.

**Comment by ihorkyevets** [comment]
Hi!

Any updates on this? 
Thanks!

**Comment by lior-tamir** [comment]
Unfortunately, no updates so far and I don't have timelines for fix due to prioritization issues.
I will update when I have.

**Comment by lior-tamir** [comment]
The bug in AADIP Logic Apps connector has been resolved. Sign in with a user is now supported without this bug. Please let us know if there is still any issue with the playbook. Thanks!

**Comment by sarah-yo** [comment]
Issue has been resolved
