### ISSUE TITLE
Close-SentinelIncident-fromSNOW

### ISSUE THREAD

**Issue by PaulSells** [Azure/Azure-Sentinel#1179]
@Yaniv-Shasha  I noticed a small issue with the Close-SentinelIncident-fromSNOW template

On the Run_query_and_list_results step the KUSTO query refers to IncidentName but is passing IncidentNumber

Line 328

"body": "SecurityIncident\n| where IncidentName == \"@{body('Parse_JSON')?['number']}\"\n

should read 

"body": "SecurityIncident\n| where IncidentNumber == \"@{body('Parse_JSON')?['number']}\"\n

**Comment by Yaniv-Shasha** [comment]
the incident name == to the unique incident id
this is the properties that we are sending back from snow.
![Capture](https://user-images.githubusercontent.com/10268698/123911625-b295bc00-d984-11eb-87b8-72f30332e745.PNG)
indeed the properties name - number can be confusing

**Comment by Yaniv-Shasha** [comment]
no change made, solution tested and work fine
@PaulSells thanks for the feedback and the help to make us better!!
