### ISSUE TITLE
ELK monitoring solution to Azure sentinel

### ISSUE THREAD

**Issue by SivPothana** [Azure/Azure-Sentinel#1187]
Hi Team,
 could you please help me how to get the logs to ELK monitoring solution to Azure sentinel any process& doc could you please share us.

**Comment by preetikr** [comment]
Hi @SivPothana - Logstash would be the way to do this and we have LogStash plug-in docs etc. at https://github.com/Azure/Azure-Sentinel/tree/master/DataConnectors/Logstash-VMSS and https://github.com/Azure/Azure-Sentinel/tree/master/DataConnectors/microsoft-logstash-output-azure-loganalytics

**Comment by SivPothana** [comment]
@preetikr Thanks for your support
