### ISSUE TITLE
Office 365 Connector Fails

### ISSUE THREAD

**Issue by troystrum** [Azure/Azure-Sentinel#119]
**Describe the bug**
Can't connect our Office 365 tenant to Azure Sentinel

**To Reproduce**
1. Go to "Azure Sentinel - Data collection"
2. Click "Configure" under "Office 365"
3. Ensure solution is installed.
4. Select "Connect tenants to Azure Sentinel" then "Add tenant"
5. Enter auth info into popup window. (MFA and Conditional Access is enabled for our admin accounts)
6. Error: "Consent process failed - internal error.  Try again later."

**Expected behavior**
Tenant appears in Azure Sentinel, etc.

**Desktop (please complete the following information):**
 - OS: Windows 10 Enterprise
 - Browser: Chrome and Edge

**Comment by shalinoid** [comment]
@troystrum - thank you for submitting the issue. Can you please send an email to AzureSentinel@microsoft.com with your Log Analytics workspace ID so we can further investigate this issue.

**Comment by troystrum** [comment]
@shalinoid - I did, but:

Your message to asigtp@microsoft.com couldn't be delivered.
The group asigtp only accepts messages from people in its organization or on its allowed senders list, and your   email address isn't on the list.

**Comment by troystrum** [comment]
This appears to have been resolved. I got a 2FA challenge this time (which didn't trigger any time I tried before today) and our Office 365 tenant was on-boarded successfully.

**Comment by shalinoid** [comment]
Thanks for the update. Closing issue
