### ISSUE TITLE
Do we need which to write here the syslog server or the IP address of the Sophos FW device?

### ISSUE THREAD

**Issue by ceritmustafa** [Azure/Azure-Sentinel#1210]
Do we need which to write here the syslog server or the IP address of the Sophos FW device? 

Which one should we write? IP or hostname? @preetikr 

`  For example: | where Computer in **("server1, server2**") and Facility == "local0"`

_Originally posted by @ceritmustafa in https://github.com/Azure/Azure-Sentinel/issues/1008#issuecomment-715312058_

**Comment by v-rbajaj** [comment]
@ceritmustafa Generally, it is the hostname.
Check in log analytics what type of value is generating in computer attribute.

**Comment by v-amolpatil** [comment]
Since we have not received a response in the last 5 days, we are closing your issue #1210 as per our standard operating procedures. If you still need support for this issue, feel free to re-open at any time. Thank you for your co-operation.
