### ISSUE TITLE
TLS encrypted syslog listener

### ISSUE THREAD

**Issue by p-harrison** [Azure/Azure-Sentinel#1237]
**Is your feature request related to a problem? Please describe.**
The default setup for the CEF log collector/forwarder (https://github.com/Azure/Azure-Sentinel/tree/master/DataConnectors/CEF) is to listen for incoming syslog/CEF on an unencrypted TCP port.  Not a MAJOR deal if the forwarder is within your network near the log source, although these days even internally it is not good practice to transmit data unencrypted if it can be avoided.  However it would be great to allow for the forwarder to sit outside the network, say an Azure VM where a VPN is not in-place, but the traffic would absolutely need to be encrypted (as well as IP source filtering setup separately etc)

**Describe the solution you'd like**
Would be great if the installer script (https://github.com/Azure/Azure-Sentinel/blob/master/DataConnectors/CEF/cef_installer.py) could have a switch that would configure syslog-ng to listen on a TLS secured port, either as an alternative to the default or as well as.  If it could issue a self-signed cert even better.

**Describe alternatives you've considered**
I'm sure this could be done manually after the installation has completed, but not ideal to mess around with the agent config I guess.  Obviously we could bring the logs over a VPN and encrypt that way, but this doesn't solve the need to encrypt traffic on the local network, and is not always feasible if collecting logs from a small number of sources that happen to be widely spreadout across networks.

Thanks guys!

**Comment by nishanna** [comment]
I am looking for this enhancement as well. The issue I have is sending syslogs from a cloud service (Trend Deep Security). The only option is to send them over TLS since VPN is not an option with a cloud service. The links provided by Microsoft  [https://docs.microsoft.com/en-us/azure/sentinel/connect-common-event-format](url) on how to set this up direct you to 3rd party websites which isn't particularly helpful.

**Comment by TBSJordanNash** [comment]
I also need TLS ingest. It would be great if Microsoft could offer syslog via a baked-in Azure Function in Sentinel, or at least manage certificates. SentinelOne, for instance, requires a TLS connection and keeps failing the TLS handshake on my syslog forwarder, configured using the provided script. The certificate generation line failed saying the DNS name was too long.

**Comment by a-balde** [comment]
To echo above comments, such a feature will be well received and appreciated.

**Comment by v-amolpatil** [comment]
Hi @p-harrison , thank you for flagging this. Apologies for the delayed response. If you still need assistance, please reply here within 5 business days.

**Comment by v-amolpatil** [comment]
Gentle Reminder: We are awaiting for your response on this issue. If you still need to keep this issue active please respond with in next 2 days. If we don't receive response by 16 Feb 2023, we will close this issue.

**Comment by v-amolpatil** [comment]
Since we have not received a response in the last 5 days, we are closing your issue #1237 as per our standard operating procedures. If you still need support for this issue, feel free to re-open at any time. Thank you for your co-operation.
