### ISSUE TITLE
[Question] Detection Mitre ATT&CK Technique Tagging

### ISSUE THREAD

**Issue by LiamSennitt** [Azure/Azure-Sentinel#124]
Currently the detections are mapped to Mitre ATT&CK Tactics, would you be open to adding technique tagging? Either based on technique id for example with the detection `SecurityEvent/SecurityEventLogCleared.txt`:

```
// Techniques: #T1070
```

or by name:

```
// Techniques: #Indicator Removal on Host
```

I'm happy to go through and add them to the current detections and make a pull request.

**Comment by juliango2100** [comment]
That is a great idea!  Feel free to go through and add this tag to the current detections.  Hunting could also use this tagging as well if you are so inclined.  Thanks!
