### ISSUE TITLE
Barracuda Web Security Gateway

### ISSUE THREAD

**Issue by rnpgithub** [Azure/Azure-Sentinel#1270]
We have a Barracuda Web Security Gateway v14 that we'd like to have the events sent to Sentinel. Our syslog forwarder is already sending the syslogs to Sentinel but there's no connector for the Barracuda Web Security Gateway.

**Comment by preetikr** [comment]
Thanks, for the feedback, @rnpgithub - We have Barracuda Web Application Firewall and Cloudgen Firewall data connectors. We'll plan this one in our roadmap.
