### ISSUE TITLE
Send logs to CommonSecurityLog with the HTTP Data Collector API ?

### ISSUE THREAD

**Issue by irom77** [Azure/Azure-Sentinel#129]
It's possible to send log data to Azure with the HTTP Data Collector API where Log-Type is the name of log which can be seen later under Custom Logs with _CL suffix.

But how to send log to CommonSecurityLog (seen under SecurityInsights) So it can be used in Sentinel Dashboards (without oms agent) ?

**Comment by shalinoid** [comment]
@irom77  - Logs ingested in CEF are shown in CommongSecurityLog. Currently its not possible to use data collector API to send logs to CommonSecurityLog. However, you may still create dashboards with these custom log types. We can also engage with vendor to create a custom connector, datatype and dashboard for their solution in Azure Sentinel.

**Comment by irom77** [comment]
Fair enough, I am using logstash running on Kubernetes to deliver Custom Logs, described [here](https://goo.gl/fKvFQs)

**Comment by shubhanshu02** [comment]
Hi! I wanted to know if the same task, i.e. pushing through Data Collector API to CommonSecurityLog, is possible today. Can someone confirm?
