### ISSUE TITLE
Alerts keep getting triggered even when outside the analysis period

### ISSUE THREAD

**Issue by AdiGri** [Azure/Azure-Sentinel#130]
I created an alert to be triggered when a specific event id (4728 - it indicates when a user is added to Domain Admins) is recorded in the SecurityEvent table. The frequency and the period were both set to 5 minutes. The alert suppression was also set for 5 min. The query was:

```
SecurityEvent
| where EventID == 4728
| project TimeGenerated, Computer, Admin=SubjectAccount,MemberName, TargetAccount, Activity
| extend AccountCustomEntity = TargetAccount
| extend HostCustomEntity = Computer
```

I added a user to Domain Admins and while the alert was triggered, it kept being sent every 5 minutes, even though there were no further events with id 4728.  The alert simulation graph shows the correct data, one single event within the last couple of hours, however the alert (and the corresponding emails and SMS text) kept being raised every 5 minutes. 

My expectation was to receive just one alert, triggered within the 5 minutes of the event 4728 recording.

![logic](https://user-images.githubusercontent.com/10263589/55048180-af7d2a00-501d-11e9-91f4-2839a5febbb2.png)

![notif](https://user-images.githubusercontent.com/10263589/55048294-0daa0d00-501e-11e9-8470-8c5ad14bde1f.png)

**Comment by oshezaf** [comment]
It might be a bug, and I would contact support. During the preview phase, it would be channeled to engineering but will ensure proper follow-up. 

One thing I would try to do would be to add "| where TimeGenerated > ago(5m) ". You are correct that it should not be needed as the period parameter should imply that, but let's see if it solves the issue.

**Comment by shainw** [comment]
Closing as no further activity on this thread in several months.
