### ISSUE TITLE
Triton playbook "Azuredeploy.json" --> "azuredeploy.json"

### ISSUE THREAD

**Issue by lior-tamir** [Azure/Azure-Sentinel#1330]
Triton playbook cannot be deployed - 
Azuredeploy.json should be changed to azuredeploy.json.
Tried to upload a PR for that and name change didn't work.
Possible to change the name of the file?

**Comment by sarah-yo** [comment]
@lior-tamir did you just upload the single file in your PR or did you do the whole folder fresh?

**Comment by lior-tamir** [comment]
I'm using Github desktop, and it seems like it finds the diffs and update only a file that changed - so probably the file.

**Comment by sarah-yo** [comment]
@lior-tamir I changed the name of the file, can you check it works OK now?

**Comment by sarah-yo** [comment]
Fixed with new PR
