### ISSUE TITLE
Playbook - Get-SentinelAlertsEvidence - Fails - Invalid Template

### ISSUE THREAD

**Issue by Springstone** [Azure/Azure-Sentinel#1350]
**Describe the bug**
This used to work, but now we're getting 
InvalidTemplate. Unable to process template language expressions in action 'Parse_JSON' inputs at line '1' and column '3369': 'Required property 'content' expects a value but got null. Path ''.'.
When parsing the Sentinel alert.

**To Reproduce**
On trigger, rule fails on step 2, with above Invalid Template error.

**Expected behavior**
Should run through all steps in the LogicApp without error, assuming all connections correctly configured.

**Screenshots**
![image](https://user-images.githubusercontent.com/2101287/99905179-b96e9900-2ce8-11eb-9e34-99971e0247cb.png)

**Comment by Yaniv-Shasha** [comment]
Hi @Springstone,

just validating it on my side and i seems to be working fine.
im suspecting that you tried to run this playbook on "Microsoft incident creation rule" and not on schedule rules

this logic app only work on rule from product name "azure senitnel"
![image](https://user-images.githubusercontent.com/10268698/99937058-64c13180-2d6d-11eb-97b4-0b4dc3e24fb4.png)

**Comment by dhaferh** [comment]
Hi Yaniv-Shasha,
Im facing the same issue
{"code":"InvalidTemplate","message":"Unable to process template language expressions in action 'Parse_JSON' inputs at line '1' and column '3342': 'Required property 'content' expects a value but got null. Path ''.'."}

The returned data from the 1st step dont have content : 
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "properties": {
    "path": {
      "type": "string"
    },
    "host": {
      "type": "object",
      "properties": {
        "connection": {
          "type": "object",
          "properties": {
            "name": {
              "type": "string"
            }
          },
          "required": [
            "name"
          ]
        }
      },
      "required": [
        "connection"
      ]
    }
  },
  "required": [
    "path",
    "host"
  ]
}

**Comment by Springstone** [comment]
> just validating it on my side and i seems to be working fine.
> im suspecting that you tried to run this playbook on "Microsoft incident creation rule" and not on schedule rules
> 
> this logic app only work on rule from product name "azure senitnel"

I'm not sure I understand. This particular playbook executes against an Azure Sentinel trigger "When a response to an Azure Sentinel alert is triggered (Preview)", not through an analytics rule (scheduled or on incident). 
As I mentioned, this was working previously, but it seems like the content forwarded through the Sentinel trigger has changed format/schema? 

To my understanding you should be able to Run the Trigger directly, and with default configuration, the last 10 alerts will be pushed into a connected EventHub.

**Comment by dhaferh** [comment]
i used another method with graphAPI, and its works
something changed in the parsing with

**Comment by Springstone** [comment]
@Yaniv-Shasha Any ideas on the schema change of the Sentinel incident/alert? It looks like we need to update the first "Parse JSNON" step in the playbook with an updated schema.

**Comment by Yaniv-Shasha** [comment]
@Springstone can you please share with the KQL query that genrate the incident?
i want to reproduce it on my side.

thanks!

**Comment by sarah-yo** [comment]
@Springstone are you able to provide the KQL query? Thanks!

**Comment by Yaniv-Shasha** [comment]
this playbook will be updated soon to handle new feature, if this issue still going on with the new version, share with us example and the analytics rule name and i will check it

**Comment by secuit** [comment]
I have the same issue like @Springstone describes. Does anybody know how to fix the issue?
