### ISSUE TITLE
Cannot deploy Get-MDATPInvestigationPackage playbook

### ISSUE THREAD

**Issue by bananafran** [Azure/Azure-Sentinel#1360]
**Describe the bug**
When clicking "Deploy to Azure" and selecting a MS account, Azure throws the following error:
Error parsing template. Please ensure template is valid JSON. Property name expected at character position 3488. (3 other errors)

**To Reproduce**
1. Go to https://github.com/Azure/Azure-Sentinel/tree/master/Playbooks/Get-MDATPInvestigationPackage
2. Click on "Deploy to Azure"
3. Select an account

**Expected behavior**
This should provide input options for creating the logic app and playbook.

**Screenshot of error**
![Screen Shot 2020-11-24 at 11 05 51 AM](https://user-images.githubusercontent.com/9940403/100119586-0798af00-2e45-11eb-90b5-e32c5b7d811b.png)

**Desktop (please complete the following information):**
 - OS: MacOS Catalina
 - Browser: Google Chrome 87.0.4280.67

**Comment by sarah-yo** [comment]
This has been fixed by PR #1405
