### ISSUE TITLE
Cannot deploy Save-NamedLocations playbook

### ISSUE THREAD

**Issue by bananafran** [Azure/Azure-Sentinel#1361]
**Describe the bug**
When selecting "Deploy to Azure" I'm directed to "https://portal.azure.com/#home" rather than a selection screen for inputs to create the logic app and playbook.

**To Reproduce**
1. Go to https://github.com/Azure/Azure-Sentinel/tree/master/Playbooks/Save-NamedLocations
2. Click on "Deploy to Azure"
3. See the lack of redirect to configuration and creation options for the playbook

**Expected behavior**
This should navigate to a configuration page to create the playbook or provide instructions on creating this if different than the rest of the playbooks in this repo.

**Desktop:**
 - OS: MacOS Catalina
 - Browser: Google Chrome 87.0.4280.67

**Comment by sarah-yo** [comment]
@bananafran have you tried this in different Browsers? It's working fine for me in both Edge and Chrome.

**Comment by bananafran** [comment]
> @bananafran have you tried this in different Browsers? It's working fine for me in both Edge and Chrome.

I hadn't tried in Safari but seems to work there. Thanks.
