### ISSUE TITLE
Variable for account entity not available in 'Suspicious application consent for offline access' rule

### ISSUE THREAD

**Issue by StefC93** [Azure/Azure-Sentinel#1393]
**Describe the bug**
The variable 'GrantInitiatedBy' doesn't show up in the "Map Entities" dropdown boxes. Because of this, it's not possible to map the account.

**To Reproduce**
1. Go to the 'Suspicious application consent for offline access' analytics rule in Azure Sentinel
2. Click on the 'Set rule logic' tab
3. Scroll down to the 'Map Entities' section
4. Click on one of the dropdown boxes that allows you to select a column

**Expected behavior**
The expected behavior is that the GrantInitiatedBy variable shows up in the dropdown list and that you can select this variable to be mapped with the 'Account' entity

**Screenshots**
![image](https://user-images.githubusercontent.com/11227509/100900232-e9752380-34c2-11eb-8afb-467848eeda5d.png)

**Additional context**
This issue causes the Investigate functionality to be unavailable in an incident triggered by this alert because there is no Entity mapped (I only need the user entity).

**Direct GitHub link of the analytic rule**
https://github.com/Azure/Azure-Sentinel/blob/master/Detections/AuditLogs/SuspiciousOAuthApp_OfflineAccess.yaml

**Comment by shainw** [comment]
@StefC93 - Thanks for pointing this out, we are investigating.

**Comment by omerhaimov** [comment]
Yo can only select fields which are in string or datetime format, if you will do tostring(GrantInitiatedBy) it will work

**Comment by shainw** [comment]
@omerhaimov is correct.  Funny, I tested that initially but tested higher in the query and it did not show up.  @StefC93 - By adding it near the end outside the join, allows it to show up - | extend GrantInitiatedBy = tostring(GrantInitiatedBy).  I will fixup the published query, it will take some time to replicate into the product so you will want to do manually in your rule for now.

**Comment by shainw** [comment]
@StefC93 - fixed in #1429, also fixed GrantIpAddress and GrantUserAgent so they are available also in entity mapping.
