### ISSUE TITLE
Looking for a Playbook which can send Teams and SMS notifications on Machine Vulnerabilities, Missing KBs, Alert details, etc

### ISSUE THREAD

**Issue by IshamMohamed** [Azure/Azure-Sentinel#1416]
Hey,

I am looking for a Azure Sentinel playbook that can send Microsoft Teams notification and SMS notification when an alert is generated by Defender for endpoint. Teams notifications should also include data about:
- DataAboutTheEndpoint
- Machine Vulnerabilities
- Missing KBs
- Security Recommendations
- Alerts
- Software Inventory 

Also should be able to perform some actions like:
- App Execution
- Start AV scan

should be performed on machine.

**Comment by kloudynetklassrooms** [comment]
You may checkout the PR https://github.com/Azure/Azure-Sentinel/pull/1422

**Comment by sarah-yo** [comment]
PR has been made for this. Feature request, rather than an Issue.
