### ISSUE TITLE
Can't use union or search in scheduled alert rule

### ISSUE THREAD

**Issue by pemontto** [Azure/Azure-Sentinel#1437]
**Describe the bug**
It seems you're no longer allowed to use `union *` or `search` in scheduled alert rules. This immediately invalidates the recent PR #1425.

`Failed to save analytics rule 'Sentinel table missing logs'. Invalid data model. [Properties.Query: Scheduled alert rule query should not contain 'search' or 'union *']`

**To Reproduce**
Create a scheduled rule with a "union *"

**Expected behavior**
The rule should be able to be created

**Additional context**
We've found the only _reasonable_ way to proactively monitor logging issues across all tables is to use a union, which has previously worked for us. Without Azure Sentinel offering a way to setup this alerting what are the alternatives?

**Comment by shainw** [comment]
@pemontto - thanks for letting us know.  We are investigating this.

**Comment by shainw** [comment]
@pemontto - This is by design.  I will see if I can figure out a reasonable workaround (but it will be a bit before I can look) and I am talking with the engineering team to see if we want to remove this block.  Will keep you posted. 
![image](https://user-images.githubusercontent.com/45466083/102530939-7b9a3180-4056-11eb-8c6b-b9ca6862eee0.png)

**Comment by DeluxeOwl** [comment]
Is there any update on this?

**Comment by Lodewyk-Git** [comment]
Hi @DeluxeOwl, using union * and search takes massive amounts of processing power as they filter through all of the data, why don't you use union fuzzy instead? I believe that union * is better used when you want to manually investigate or find a specific sequence once. 

Example

**Comment by Lodewyk-Git** [comment]
Hi @DeluxeOwl, using union * and search takes massive amounts of processing power as they filter through all of the data, why don't you use union fuzzy instead? I believe that union * is better used when you want to manually investigate or find a specific sequence once. 

*Example*

![image](https://user-images.githubusercontent.com/36856692/122405819-a707c580-cf80-11eb-9af9-b3abd69d28c4.png)

**Comment by Lodewyk-Git** [comment]
Hi @DeluxeOwl, using union * and search takes massive amounts of processing power as they filter through all of the data, why don't you use union fuzzy instead? I believe that union * is better used when you want to manually investigate or find a specific sequence once. 

*Example*

![image](https://user-images.githubusercontent.com/36856692/122405995-cc94cf00-cf80-11eb-84a2-9763ac691e63.png)

**Comment by Lodewyk-Git** [comment]
This way you filter through the tables you want to instead of also querying tables such as Usage, SecurtyAlert, SecurityIncident etc.

**Comment by DeluxeOwl** [comment]
Doesn't really help in my use case, I need union to be able to get a list of the table names from a Log Analytics workspace and create a Analytic Rule based on this query (search doesn't work either)

**Comment by cespinoza01** [comment]
I'm having the same issue. My log stoppage alerts that were working before are not running anymore causing operational issues. I'm using union * to get the list of all the tables in my workspace and determine if any has stopped receiving events.

**Comment by DeluxeOwl** [comment]
@cespinoza01 I'm using the following workaround for my use case:
1. I've created a logic app (that runs periodically) with an app registration that gets the Bearer token to call API's from azure.I used this guide as reference [https://techcommunity.microsoft.com/t5/integrations-on-azure/calling-graph-api-from-azure-logic-apps-using-delegated/ba-p/1997666](https://techcommunity.microsoft.com/t5/integrations-on-azure/calling-graph-api-from-azure-logic-apps-using-delegated/ba-p/1997666)
2. I'm getting the subscription list by making a request to `https://management.azure.com/subscriptions?api-version=2020-01-01` 
3. For each subscription I'm getting a list of workspaces by making a request to `https://management.azure.com/subscriptions/<subscription_id>/providers/Microsoft.OperationalInsights/workspaces?api-version=2020-08-01`
4. I'm running the query on each subscription - resource group - workspace and I'm **manually** creating incidents by making a **PUT** request to this URL `https://management.azure.com/subscriptions/<current_subscription>/resourceGroups/<current_resource_group>/providers/Microsoft.OperationalInsights/workspaces/<current_workspace>/providers/Microsoft.SecurityInsights/incidents/<randomly_generated_uuid>?api-version=2020-01-01`

More info on this API call here: [https://docs.microsoft.com/en-us/rest/api/securityinsights/incidents/create-or-update](https://docs.microsoft.com/en-us/rest/api/securityinsights/incidents/create-or-update)

**Comment by KiranrajPalanisamy** [comment]
Hello all,

Please use the Query like 

union = withsource tablename AzureActivity, Signinlogs,....ETC.. 


And write rest of your query it works as expected
