### ISSUE TITLE
Non-breaking whitespace in detections cause 500 errors with the REST API

### ISSUE THREAD

**Issue by pemontto** [Azure/Azure-Sentinel#1447]
**Describe the bug**
Some of the detections now have non-breaking whitespace in them. Using these raw strings when interacting with the Sentinel API causes vague 500 errors.

```json
{"error":{"code":"InternalServerError","message":"Internal server error"}}
```

Copy pasting the rule into the GUI works OK (on my platform at least MacOS).

**To Reproduce**
1. Take any rule with NBSPs e.g. `Detections/OfficeActivity/MailItemsAccessedTimeSeries.yaml`
2. Create a scheduled rule via the Sentinel API with the raw query string
4. See non-descriptive 500 error

**Expected behavior**

1. The API should return a more descriptive error. At least hinting the problem is in the query field.
1. The repo shouldn't contain detections etc. with NBSPs

**Additional context**
https://github.com/wortell/AZSentinel/issues/158

Files containing NBSPs:
```bash
❯ grep -ril '\xa0' Detections/* 
Detections/AzureDiagnostics/TimeSeriesKeyvaultAccessAnomaly.yaml
Detections/CommonSecurityLog/TimeSeriesAnomaly-MultiVendor_NetworkTraffic.yaml
Detections/MultipleDataSources/NewUserAgentLast24h.yaml
Detections/MultipleDataSources/TimeSeriesAnomaly-MultiVendor_DataExfiltration.yaml
Detections/OfficeActivity/MailItemsAccessedTimeSeries.yaml
Detections/SecurityEvent/TimeSeriesAnomaly-ProcessExecutions.yaml

❯ grep -ril '\xa0' Functions/*       
Functions/CheckifDayLightSavings-US-EU.txt

❯ grep -ril '\xa0' Hunting\ Queries/*
Hunting Queries/LAQueryLogs/CrossWorkspaceQueryAnomolies.yaml
Hunting Queries/LAQueryLogs/NewClientRunningQueries.yaml
Hunting Queries/LAQueryLogs/MultipleLargeQueriesByUser.yaml
Hunting Queries/LAQueryLogs/QueryDataVolumeAnomolies.yaml
Hunting Queries/LAQueryLogs/QueryLookingForSecrets.yaml
Hunting Queries/LAQueryLogs/NewServicePrincipalRunningQueries.yaml
Hunting Queries/LAQueryLogs/NewUserRunningQueries.yaml
Hunting Queries/LAQueryLogs/UserReturningMoreDataThanDailyAverage.yaml
Hunting Queries/LAQueryLogs/UserRunningMultipleQueriesThatFail.yaml
```

**Comment by shainw** [comment]
@pemontto - Thanks and apologies on delay on the PR, reviewing and will complete if no issues right away. ;)
