### ISSUE TITLE
GitHubFunction AuditLog Parser Function Incorrect Logic

### ISSUE THREAD

**Issue by BenMcGarry** [Azure/Azure-Sentinel#1488]
**Describe the bug**

The  latest function update to the GitHubAuditLog parser is not correct and won't run, It returns the following error:

`'project' operator: Failed to resolve scalar expression named 'node'`

**To Reproduce**
1. Go to the parser: https://raw.githubusercontent.com/Azure/Azure-Sentinel/master/Parsers/GitHubFunction/GitHubAuditLog.txt
2. Copy it into the log workplace.
3. Hit run.

**Expected behavior**
Function completed with data parsed

**Screenshots**

![image](https://user-images.githubusercontent.com/9434920/102409226-9765ef00-3fe6-11eb-91ac-1d8cfde30d08.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Edge
 - Version: Version 87.0.664.60

**Additional Information**

https://github.com/Azure/Azure-Sentinel/blob/master/Parsers/GitHubFunction/GitHubAuditLog.txt#L25-L37 are the impacted lines. It looks related to the parse_json(node) area.

**Comment by BenMcGarry** [comment]
Swapping the query to the below resolves, but unsure on the initial use of json parse.

```
GitHub_CL  
| extend AuditEntries = todynamic(parse_json(value_s)) 
| mv-expand AuditEntries 
| evaluate bag_unpack(AuditEntries) 
| project Organization=tostring(node_organizationName_s),
    Action=tostring(node_action_s),
    OperationType=tostring(node_operationType_s),
    Repository=tostring(node_repositoryName_s),
    Actor=tostring(node_actorLogin_s),    
    IPaddress=tostring(node_actorIp_s),
    City=tostring(node_actorLocation_city_s),
    Country=tostring(node_actorLocation_country_s),
    ImpactedUser=tostring(node_userLogin_s),
    ImpactedUserEmail=tostring(node_user_email_s),
    InvitedUserPermission=tostring(node_permission_s),
    Visability=tostring(node_visibility_s),
    TeamName=tostring(node_teamName_s), TimeGenerated
```

**Comment by shainw** [comment]
@BenMcGarry - thanks.  Would you be willing to submit a PR for an update to the Parser?

**Comment by shainw** [comment]
@sreedharande - FYI, maybe your changes had an impact?

**Comment by sreedharande** [comment]
@BenMcGarry - Thanks.

Can you please try the following steps and let me know.
1. Try this query first
`GitHub_CL  
| extend AuditEntries = todynamic(parse_json(value_s)) 
| mv-expand AuditEntries 
| evaluate bag_unpack(AuditEntries)
| where TimeGenerated > ago(30d) 
| project Organization=tostring(parse_json(node).organizationName)`

2. If you are able to see the results, then keep adding all the required columns to the view.

**Comment by BenMcGarry** [comment]
@sreedharande That query returns the below:

`'project' operator: Failed to resolve scalar expression named 'node'`

**Comment by sreedharande** [comment]
@BenMcGarry, Can you please confirm, your GitHub_CL custom log looks like as follows, do you see value_s with different nodes

![image](https://user-images.githubusercontent.com/22670063/102546388-6a5c1f80-406c-11eb-95a7-35e7c2779da0.png)

If you don't mind, send me your GitHub_CL screen shot

**Note:**
These parsers only work with GitHub Azure Function Data connector, not with earlier version using Logic Apps

**Comment by BenMcGarry** [comment]
I'm using the latest function that was pushed to GitHub. I've just ran that and I do not get the breakdown where it splits between value 0/1/2/3 etc etc. Its all under one thing named value_s.

![image](https://user-images.githubusercontent.com/9434920/102547872-bbdacd80-40b1-11eb-8b23-222715e4a81a.png)

**Comment by sreedharande** [comment]
@BenMcGarry - Are you able to see GitHub_CL custom table as follows
![image](https://user-images.githubusercontent.com/22670063/103965279-3ecfd080-5112-11eb-839b-654b255450de.png)

**Comment by BenMcGarry** [comment]
@sreedharande My table shows the same as the screenshot in https://github.com/Azure/Azure-Sentinel/issues/1488#issuecomment-747722873

**Comment by shainw** [comment]
@sreedharande - This looks like it may not be resolved yet?

**Comment by sreedharande** [comment]
@BenMcGarry - Pushed latest changes to the GitHub Azure Function Data connector. Please check it out and let me know your feedback

**Comment by sreedharande** [comment]
@BenMcGarry - Did you get a chance to updated your GitHub Azure Function Data connector with the latest fix?? Please check it out and let me know your feedback

**Comment by BenMcGarry** [comment]
Hey - Sorry forgot to update it. I will report back tomorrow :)

**Comment by BenMcGarry** [comment]
Yep the updated connector resolves it, thanks!
