### ISSUE TITLE
cef_troubleshoot.py failing in RHEL due to TypeError in check_file_read_permissions

### ISSUE THREAD

**Issue by AndyHerb** [Azure/Azure-Sentinel#1498]
**Describe the bug**
When testing/troubleshooting the Sentinel Log Analytics Forwarder on a clean RHEL VM in Azure, 

**To Reproduce**
1. Create a RHEL Marketplace VM in Azure using the following settings:
  Publisher: RedHat
  Offer: RHEL
  SKU: 8.2
2. Follow the [installation guide](https://docs.microsoft.com/en-us/azure/sentinel/connect-cef-agent?tabs=rsyslog) for deploying the Log Forwarder
3. Validate the installation and configuration as per [this guide](https://docs.microsoft.com/en-us/azure/sentinel/connect-cef-verify?tabs=rsyslog#how-to-validate-connectivity)
4. The cef_troubleshoot.py will fail with the following error:

```
Traceback (most recent call last):
File "cef_troubleshoot.py", line 747, in <module> main()
File "cef_troubleshoot.py", line 721, in main omsagent_security_event_conf_validation(workspace_id=workspace_id)
File "cef_troubleshoot.py", line 547, in omsagent_security_event_conf_validation check_file_read_permissions(path, workspace_id)
File "cef_troubleshoot.py", line 466, in  octal_permissions = o.strip("\'\n")
TypeError: a bytes-like object is required, not 'str'
```

**Expected behavior**
Executing cef_troubleshoot.py won't fail

**Desktop (please complete the following information):**
 - OS: RedHat Enterprise Linux
 - Version: Release 8.2 (Ootpa)

**Additional context**
Working around the problem we have simply commented-out line 547 which reads
`check_file_read_permissions(path, workspace_id)`

**Comment by NoamLandress** [comment]
Hi @AndyHerb,
Thanks a lot for bringing this to our attention.
Could you please open a support ticket on this issue so we could assist as soon as possible?
Thanks,
Noam.

**Comment by AndyHerb** [comment]
@NoamLandress - case 120122225004772 raised as requested

**Comment by v-jayakal** [comment]
@NoamLandress - Can we close this issue? Please let us know. Thanks.

**Comment by NoamLandress** [comment]
Yes, @v-jayakal. Closing.
