### ISSUE TITLE
Playbook: ConnectorHealthApp | Sorting Data Table presentation

### ISSUE THREAD

**Issue by swiftsolves-msft** [Azure/Azure-Sentinel#1503]
@iwafula025 Amazing LogicApp I love the anomaly pattern and will try and use this elsewhere. By adding the following KQL lines at the end of heartbeat and anomaly logic app action lookups the data presented may be easier for admins to work through on email \ teams message received. We did something similar for ASC SecureScore data table reports.

| sort by LastHeartbeat asc

| sort by AnomalyScore desc 

![image](https://user-images.githubusercontent.com/30509195/102621765-0e49d780-410e-11eb-93b2-da9111314183.png)

**Comment by iwafula025** [comment]
Thanks @swiftsolves-msft  , great idea. I am collecting feedback over the next month and will update the solution to include value-add suggestions like yours

**Comment by sreedharande** [comment]
Thanks @iwafula025 and @swiftsolves-msft - as it is not fall under issue, added "enhancement" label and closing
