### ISSUE TITLE
RecordType 8 event Operation nuance in Rare Application Consent

### ISSUE THREAD

**Issue by mbrancato** [Azure/Azure-Sentinel#1508]
**Describe the bug**
Most Record Type 8 events have operations that end in a period - so I think the following line can't use an equality operator. You could use `startswith` but I've seen this event with the trailing period as `"Consent to application."`.

https://github.com/Azure/Azure-Sentinel/blob/be0a63cb09ef43a4d625a6c106529d44f5a222db/Detections/AuditLogs/RareApplicationConsent.yaml#L35

**Comment by shainw** [comment]
@mbrancato - thanks, PR #1509 submitted and should be completed today.

**Comment by shainw** [comment]
#1509 approved and merged.
