### ISSUE TITLE
Azure-Sentinel/Hunting Queries/SigninLogs/Signins-From-VPS-Providers.yaml

### ISSUE THREAD

**Issue by guidovbrakel** [Azure/Azure-Sentinel#1517]
I can't get the following hunting query in Sentinel because it has too many characters
Azure-Sentinel/Hunting Queries/SigninLogs/Signins-From-VPS-Providers.yaml

**Comment by shainw** [comment]
@guidovbrakel - Thanks we realized that this may not be able to be saved, but it can be copied and run in the Log Analytics query interface.  We are looking to resolve the issue today.  I will post back the PR that resolves this once available.

**Comment by shainw** [comment]
@guidovbrakel - We just pushed a fix for this - #1519 - thanks for your patience.
