### ISSUE TITLE
Issue with with OMS Agent Install for CEF-VMSS

### ISSUE THREAD

**Issue by happy-jo** [Azure/Azure-Sentinel#1539]
While trying to deploy the CEF-VMSS ARM template, I've found that the VM is unable to install and configure the OMS agent. This error has occurred with the FluentD and CEF VMSS solutions. Error image below.

![image](https://user-images.githubusercontent.com/16526141/103306600-eeeb5e00-49db-11eb-936e-0dc52e0738db.png)

Link to CEF-VMSS repo: https://github.com/Azure/Azure-Sentinel/tree/master/DataConnectors/CEF-VMSS
Link to the FluentD-VMSS repo: https://github.com/Azure/Azure-Sentinel/tree/master/DataConnectors/Fluentd-VMSS

**Comment by dicolanl** [comment]
@happy-jo which os are you using? RH or UB? are you using what is in the template or did you change it?

**Comment by happy-jo** [comment]
I'll need to review this issue since I submitted it so long ago. In the meantime, I'll close the issue. If I send the issue, I'll send a PR.

@dicolanl

**Comment by dicolanl** [comment]
@happy-jo  by the way, see this.  #2739 i did find another issue like this which is resolved now.
