### ISSUE TITLE
Templating YAML Files for Alert Rules

### ISSUE THREAD

**Issue by kay07949** [Azure/Azure-Sentinel#1573]
Hi, 

Please let know if there are any templating tools (Ideal) or a branching strategy to achieve the following:

We have a main template called alert001.yaml with the following KQL Query:

-----------------------------------------------
//MasterTemplate

query: |
  AzureActivity
  | where TimeGenerated between (startofday(ago(starttime)) .. startofday(ago(endtime)))
  | where OperationName in~ (szOperationNames)
  | summarize StartTimeUtc = min(TimeGenerated), EndTimeUtc = max(TimeGenerated), 
 ActivityTimeStamp = makelist(TimeGenerated), ActivityStatus = makelist(ActivityStatus), 

--------------------------
Based on the above template, we need to create customer yaml files, example alert001-customer001.yaml. On the customer YAML file we need to add few additional lines of code on the KQL and this line of code has to be on the specific line and it cannot be and the end of the code, etc. Otherwise KQL will fail.

-------
//Customer YAML Files

AzureActivity
  | where callerIPAddress != "192.168.1.1"
  | where TimeGenerated between (startofday(ago(starttime)) .. startofday(ago(endtime)))
  | where OperationName in~ (szOperationNames)
  | summarize StartTimeUtc = min(TimeGenerated), EndTimeUtc = max(TimeGenerated), 
 ActivityTimeStamp = makelist(TimeGenerated), ActivityStatus = makelist(ActivityStatus)

----------

Whenever we update the main template we will like it to reflect on the alert001-customer001.yaml, alert001-customer002.yaml, alert001-customer003.yaml files. In other words to append these files..

What is the best way to achieve this, should we be pursing a git branching strategy or is there a templating tool similar to Helm that can fulfil this requirement?

**Comment by shainw** [comment]
@kay07949 - For now, git branching is probably the way to go.  @oshezaf, @Ronmarsiano - Thoughts on this from the Azure Sentinel service side?

**Comment by oshezaf** [comment]
Hi @kay07949 : I would like to figure out a solution within Azure Sentinel's rules, rather than by replicating them. To do so, it would be great to better understand the use - do you want to apply the rules in each customer workspace, but make sure that when using the central incident view they have differnt titles? Or apply them in a central workspace using cross-workspace rules, again, with differnt title per customer?

**Comment by kay07949** [comment]
Hi,

@oshezaf apologies for the late response, I just saw this now.

It's a central workspace with cross workspace queries, with different titles per customer. 

My thoughts are using python and jinga2 for templating ? 

Thank you for your help.

Regards,
Kay

**Comment by oshezaf** [comment]
Hi @kay07949 : we have started a private preview for dynamic alert fields, including the title, which may help you achieve what you want without duplicating rules.

**Comment by sarah-yo** [comment]
PrP started to address this issue
