### ISSUE TITLE
Palo Alto DeviceVendor Variation

### ISSUE THREAD

**Issue by richlilly2004** [Azure/Azure-Sentinel#1630]
We are seeing the parser seems to bring in DeviceVendor as not only "Palo Alto Networks", but also "Palo Alto#012Networks".

Not sure if this is a CEF parsing issue or some other problem.

![Screenshot 2021-01-21 111417](https://user-images.githubusercontent.com/16143700/105386311-ddac0080-5bd9-11eb-9d39-a33a982fa23a.png)

**Comment by sarah-yo** [comment]
As this is not Github content related, this should be raised in the Azure support portal if it is still an issue. Thanks!

**Comment by rahulbalan2424** [comment]
@richlilly2004 : did you found the resolution ?

**Comment by FLee565** [comment]
This is caused by a line feed from copying and pasting the CEF formatting from the Palo Alto Docs, make sure your line feeds are not pasted in.
