### ISSUE TITLE
Documentation - Query style guide EntityType enum unreachable

### ISSUE THREAD

**Issue by cyberpion-yotam** [Azure/Azure-Sentinel#1641]
I was trying to view the available entityType or identifiers, and got a 401 when accessing the links in this section.

Section link:
https://github.com/Azure/Azure-Sentinel/wiki/Query-Style-Guide#limitations-and-rules

entityType link:
https://msazure.visualstudio.com/One/_git/ASI-Common?path=%2Fsrc%2FContracts%2FAnalyticsManagementContracts%2FModel%2FEntityType%2FEntityType.cs

Identifiers link:
https://msazure.visualstudio.com/One/_git/ASI-Portal?path=%2Fsrc%2FASIExtension%2FClient%2FData%2FCommon%2FEntities%2FEntities.ts&version=GBdevelop&_a=contents

For me this really inhibits the ability to add detections.

**Comment by shainw** [comment]
@cyberpion-yotam - Thanks for the feedback.  We are looking into it and will come back once we determine the solution.

**Comment by shainw** [comment]
@cyberpion-yotam - We updated with static information for now until the public documentation is finalized - https://github.com/Azure/Azure-Sentinel/wiki/Query-Style-Guide#new-entity-mapping-method
