### ISSUE TITLE
Increase Sentinel comments maximum character limit

### ISSUE THREAD

**Issue by gabrielnecula** [Azure/Azure-Sentinel#1708]
**Is your feature request related to a problem? Please describe.**
The Sentinel comment character limit is making me unable to use enrichment logic apps that need to post more than 3000 characters. 

**Describe the solution you'd like**
I would raise the limit to 40000 or similar.

**Describe alternatives you've considered**
I've considered splitting the comment into multiple parts in the logic app but it is a nightmare from a implementation point of view.

**Additional context**

**Comment by shainw** [comment]
@Ronmarsiano - Can you comment here?  I believe this is coming.

**Comment by Ronmarsiano** [comment]
hi @gabrielnecula ,

thank you for your feedback , we will take it into consideration.

thanks,

Ron

**Comment by NVolcz** [comment]
This limitation is also affecting me and I think this is a weird limitation since I have not seen this in any other similar system :-(

**Comment by meenalluktuke** [comment]
I have the same issue. We are using logic apps to add comments to incidents, it fails because of 3000 characters limitation. Please increase it to at least 10000

**Comment by manojsgh** [comment]
Same situation here

**Comment by shainw** [comment]
Missed posting back here, but the limit has been increased - https://docs.microsoft.com/en-us/azure/sentinel/investigate-cases#comment-on-incidents

**Comment by zrahim-cybermsi** [comment]
This issue is not resolved yet.
