### ISSUE TITLE
DNS lookup requested

### ISSUE THREAD

**Issue by DSharpPro** [Azure/Azure-Sentinel#173]
**Describe the bug**
DNS logs are being received into Sentinel although DNS lookup requests from malicious sources are not being sent.

**Expected behavior**
All DNS logs to be uploaded to Sentinel for consolidation

**Additional context**
Please let us know if you require any further information

**Comment by TheRealEliteOwl** [comment]
Hi! 
Which schema/connector are you referencing?

**Comment by DSharpPro** [comment]
Hi
We are using the DNS connector.

**Comment by TheRealEliteOwl** [comment]
I have tried a few things over the last few days, but none of them have produced different results. I think it would be very helpful if the connector's technical info was offered in greater detail. 

I feel like there is a simple answer here, but we are shooting in the dark without understanding how they work or are coded.

**Comment by oshezaf** [comment]
@DSharpPro: Sorry for the late response and thanks for reporting. We are looking into it. Are those only lookups for malicious sources that are dropped or lookups in general?

**Comment by DSharpPro** [comment]
Hi Oshezaf,
We are not getting any results when running the following query:

DnsEvents
| where SubType == "LookupQuery" 

They are lookups in general.

**Comment by shainw** [comment]
Hey @DSharpPro 
Is this issue still occurring for you?
Thanks,
Shain

**Comment by DSharpPro** [comment]
Hi @Shainw,
Yes this issue is still happening. The DNS events are not being uploaded to Sentinel.
As per my query mentioned above the look up query's for DNS events are not being ingested by sentinel.

**Comment by shainw** [comment]
@DSharpPro - thanks for letting us know.  Let me have a chat with our Connector team and get back to you.

**Comment by oshezaf** [comment]
Hi @DSharpPro and sorry for the very long delay. 

We have checked with the DNS connector team. For DNS look up data, we need to ensure configuration is sent to the agent (in their internal terminology "rule needs a non-null config object which is pushed by the UI". To enforce this, try loading the configuration page once in portal.

Also, in general: for issue not related to the GitHub content, it would be better to use our tech community at: https://techcommunity.microsoft.com/t5/Azure-Sentinel/bd-p/AzureSentinel

~ Ofer

**Comment by DSharpPro** [comment]
Would you be able to elaborate on where the configuration needs to be added please?

**Comment by oshezaf** [comment]
A good question. It is far from obvious. You need the configuration screen for the DNS Analytics solution utilized by Sentinel. 

From the Sentinel page 
1. Select Workspace Settings -> Solutions
2. Select the DNS Analytics solution
3. In the summary pane, "View summary" and then click on the summary to get the solution Dashboard
4. There is a "configure" button at the top.

This is how I know how to get there. Checking with the DNS team if there is a more direct way.

**Comment by oshezaf** [comment]
Just to update: this is the only way to perform this fix, however hopefully it is a one time action.

**Comment by thebluenova** [comment]
To anyone else stuck on this alternate steps:
In Azure Sentinel:
1. Settings
2. Workspace Settings
3. Workspace Summary
4. Click DNS Analytics tile
5. Click Configure
6. If you can read any of the settings change from the dark theme back to the default theme.
