### ISSUE TITLE
Workspace Analytic Rule Template out of sync with GitHub

### ISSUE THREAD

**Issue by mpalumbo7** [Azure/Azure-Sentinel#1772]
**Describe the bug**
The Analytics Rule templates in my Azure Sentinel workspace are not up to date with the templates on GitHub. A bug in a template was fixed on GitHub in 2020-Dec but the template in my workspace was last updated 2020-June. The bug causes malformed alerts to be generated, and since it is published my Microsoft I cannot fix it myself. 

The only course of action is disabling the MS published templates since they are not reliable AND there is no policy stating how/when/if they will be updated.

**To Reproduce**
1. Go to any Azure Sentinel workspace
2. Click on 'Analytics'
3. Click on 'Rule Templates'
4. Search for 'Suspicious application consent for offline access'
    - ID = 6d4cfdf4-2b86-4f12-8a10-49151f23c990
5. Scroll down to `Template last updated' and see June 28, 2020
6. Compare to the GitHub template, which was last updated on Dec 9, 2020
     - [Detections/AuditLogs/SuspiciousOAuthApp_OfflineAccess.yaml](https://github.com/Azure/Azure-Sentinel/blob/master/Detections/AuditLogs/SuspiciousOAuthApp_OfflineAccess.yaml)
     - the bug was fixed on Dec 2, 2020 in https://github.com/Azure/Azure-Sentinel/commit/315d3bfd1435b96dd30dd7713e78c2277ba762d0

**Expected behavior**
The template in my workspace to be kept _reasonably_ up to date. 

**Screenshots**
![image](https://user-images.githubusercontent.com/20686457/107982870-ce2e9600-6f92-11eb-9f71-22f899295b2b.png)

**Additional context**
This template is out of date in all of my Azure Sentinel workspace and it is not the only template that is out of date.

I raised a support ticket and they had the no helpful response other than maybe GitHub is not in sync with the MS Azure Sentinel tenant.

There are rigorous checks for detection syntax & structure...but absolutely no information about how those templates get distributed. 

1. What is Microsoft's plan for pushing updates from GitHub to Sentinel workspaces? 
2. How will rules deployed from a template be updated when the template is updated?

**Comment by Lodewyk-Git** [comment]
Hi Michael,
I share your concern when it comes to the default rule templates. So I went back to when they announced how to use templates: https://techcommunity.microsoft.com/t5/itops-talk-blog/azure-sentinel-using-rule-templates/ba-p/2028427

It does suck that it doesn't get updated as frequently as github does, but the templates are only a start.

Have you considered updating and managing Sentinel manually using automation scripts? Such as described here: https://techcommunity.microsoft.com/t5/azure-sentinel/deploying-and-managing-azure-sentinel-as-code/ba-p/1131928

You could even update your own rules via powershell directly from github.

**Comment by oshezaf** [comment]
Hi @mpalumbo7 and @Lodewyk-Git : we seems to have add an issue with this template. The update should be deployed in a couple of days. We also work to identify the issue and improve our process.
