### ISSUE TITLE
 Rule logic associated with "User account enabled and disabled within 10 mins"

### ISSUE THREAD

**Issue by Lodewyk-Git** [Azure/Azure-Sentinel#1776]
**Rule Description**
Identifies when a user account is enabled and then disabled within 10 minutes. This can be an indication of compromise and an adversary attempting to hide in the noise.

**What the rule does**
This analytical rule joins two events together in Security Events (Windows security events Data Type) when the AccountType ~= "User" for both events.

**Problem**
The problem here is that the Account Type isn't associated with the SubjectAccount nor TargetAccount columns, but is associated with the Account column. 

The Account column is populated based on the Activity. (see example below)

This means that the alert will trigger when a user account enables or disables a TargetAccount that is not a user account.

**Screenshot of Events**
![Example](https://user-images.githubusercontent.com/36856692/108075452-0e654580-7073-11eb-929b-482ed6893b5f.jpg)

**Screenshot of Incident**
![Example2](https://user-images.githubusercontent.com/36856692/108077629-6604b080-7075-11eb-8440-d7804d75d855.jpg)

**Extra**
I do know that there's inconsistencies in the parsing when it comes to Security Events, but this should have an easy work around - such as adding "where TargetAccount !contains '$'" or "where TargetAccount !endswith '$'"

**Comment by shainw** [comment]
@Lodewyk-Git - Agreed there can be some inconsistencies.  Again, happy for you to contribute the fix via PR on this file - https://github.com/Azure/Azure-Sentinel/blob/master/Detections/SecurityEvent/UserAccountEnabledDisabled_10m.yaml.  If not, we will work on fixing in the next 2 weeks.

**Comment by Lodewyk-Git** [comment]
Man, was just going to add this change today, thanks for changing the rule, I'm closing this issue.
