### ISSUE TITLE
"User added to Azure Active Directory Privileged Groups" needs additional parsing

### ISSUE THREAD

**Issue by Lodewyk-Git** [Azure/Azure-Sentinel#1795]
**Rule Description**
This will alert when a user is added to any of the Privileged Groups.

**Problem**
This Analytical rule is parsing from the AuditLogs for one use case only, leaving necessary rows empty.

**Rule KQL**
`let timeframe = 1h;
let OperationList = dynamic(["Add member to role", "Add member to role in PIM requested (permanent)"]);
let PrivilegedGroups = dynamic(["UserAccountAdmins", "PrivilegedRoleAdmins", "TenantAdmins"]);
AuditLogs
| where TimeGenerated >= ago(timeframe)
| where LoggedByService =~ "Core Directory"
| where Category =~ "RoleManagement"
| where OperationName in~ (OperationList)
| mv-expand TargetResources
| extend modifiedProperties = parse_json(TargetResources).modifiedProperties
| mv-expand modifiedProperties
| extend DisplayName = tostring(parse_json(modifiedProperties).displayName), GroupName =  trim(@'"', tostring(parse_json(modifiedProperties).newValue))
| extend AppId = tostring(parse_json(parse_json(InitiatedBy).app).appId), InitiatedByDisplayName = tostring(parse_json(parse_json(InitiatedBy).app).displayName), ServicePrincipalId = tostring(parse_json(parse_json(InitiatedBy).app).servicePrincipalId), ServicePrincipalName = tostring(parse_json(parse_json(InitiatedBy).app).servicePrincipalName)
| where DisplayName =~ "Role.WellKnownObjectName"
| where GroupName in~ (PrivilegedGroups)
// If you want to still alert for operations from PIM, remove below filtering for MS-PIM.
| where InitiatedByDisplayName != "MS-PIM"
| project TimeGenerated, AADOperationType, Category, OperationName, AADTenantId, AppId, InitiatedByDisplayName, ServicePrincipalId, ServicePrincipalName, DisplayName, GroupName
| extend timestamp = TimeGenerated, AccountCustomEntity = ServicePrincipalName`

**Screenshots**
*Event*
![image](https://user-images.githubusercontent.com/36856692/108477799-603ce400-729c-11eb-9a77-ad9482908e0b.png)
*Performed by*
![image](https://user-images.githubusercontent.com/36856692/108479463-7055c300-729e-11eb-843e-2c27bf1092f7.png)

The problem in my specific example is that the "InitatedyDisplayName" query is parsing for an app, but the action was performed by a user. Thus leaving me with no relevant info when opening the event from the Incidents page. (See lines 14-17)

**Example**
InitiatedByDisplayName = tostring(parse_json(parse_json(InitiatedBy).app).displayName) 
vs
InitiatedByDisplayName = tostring(parse_json(parse_json(InitiatedBy).user).displayName)

*also add*
IntiatedBy = tostring(parse_json(parse_json(InitiatedBy).user).userPrincipalName)
TargetName = tostring(TargetResources.userPrincipalName)

By simply changing the .app to .user this query is fixed.

Iff() statements needs to be added to this query for every resource type capable of adding a user to a privileged group.

Different info also gets sent through depending on who performed the action, in the case of a user performing the action the user affected's data is also sent through, this also needs to be added.

**Comment by shainw** [comment]
@Lodewyk-Git - we would be happy for you to contribute any updates and we can review them via PR.  The detection is here - https://github.com/Azure/Azure-Sentinel/blob/master/Detections/AuditLogs/UseraddedtoPrivilgedGroups.yaml.

**Comment by Lodewyk-Git** [comment]
Thanks @shainw for assisting with this. I'm closing this issue as the parsing issue is fixed, now we just need to continue with the clean code methodology.
