### ISSUE TITLE
PulseConnectSecure - Parsing issue

### ISSUE THREAD

**Issue by roie9876** [Azure/Azure-Sentinel#1833]
I'm trying to work with the PulseConnectSecure connector. 
my syslog message look like this:
2021-02-26 21:46:34 - ive - [10.28.55.101] Default Network::user1\demo.local(Users)[] - Authentication failure for AD server 'AD': specified account does not

the query is not working as expected. this fields are empty: 
Node, Source_IP , User ,Realm ,EventID,Messages

**Comment by shainw** [comment]
@acnccd - Can you have a look at this?  I don't have the time right now to investigate.

**Comment by shainw** [comment]
@roie9876 - Apologies on the delay, it looks like the author wasn't able to get back to you yet.  I had a further look and I think this will fix the parser for your event.  Can you please test it -

```
Syslog
| where Computer in ("datasource") and Facility == "local7"
| extend Parser0 = extract_all(@'^(\d{4}\-\d{2}-\d{2})\s(\d{2}\:\d{2}:\d{2})\s(\S+)\s(\S+)\s(\S+)\s\[(\S+)\]\s(\S+)\((.*)?\)\[(.*)\]\s\-\s(.*)',dynamic([1,2,3,4,5,6,7,8,9,10]),SyslogMessage)
| extend Parser =  extract_all(@'^(\d{4}\-\d{2}-\d{2})\s(\d{2}\:\d{2}:\d{2})\s(\S+)\s(\S+)\s(\S+)\s\[(\S+)\]\s(.*)(\()(.*)?\)\[(.*)\]\s\-\s(.*)', SyslogMessage)
| mv-expand Parser
| extend LogTime = todatetime(strcat(tostring(Parser[0]),'T',tostring(Parser[1]))), 
    Node = tostring(Parser[3]), 
    Source_IP = tostring(Parser[5]), 
    User = tostring(Parser[6]), 
    Realm = tostring(Parser[8]), 
    EventID = tostring(Parser[9]), 
    Messages = tostring(Parser[10])
| project-away Parser
```

**Comment by shainw** [comment]
@roie9876 - Checking back before I close this to make sure this resolved your issue?

**Comment by acnccd** [comment]
Apologies, this feel off my radar. If that doesnt work out try this one:

let ServerList = dynamic(["Server1", "Server2"]);
Syslog
| where Computer in~ (ServerList)
// Version 8.0R7 and below using the Standard format
| extend Parser = extract_all(@'(PulseSecure:\s)?(\d{4}\-\d{2}-\d{2})\s(\d{2}\:\d{2}:\d{2})\s(\S+)\s(\S+)\s(\S+)\s\[(\S+)\]\s(\S+)\((.*)?\)\[(.*)\]\s\-\s(.*)',dynamic([1,2,3,4,5,6,7,8,9,10,11]),SyslogMessage)
| mv-expand Parser
| extend LogTime = todatetime(strcat(tostring(Parser[1]),'T',tostring(Parser[1]))), 
    Node = tostring(Parser[4]), 
    SrcIpAddr = tostring(Parser[6]), 
    SrcUserName = tostring(Parser[7]), 
    Realm = tostring(Parser[8]), 
    EventID = tostring(Parser[9]), 
    Messages = tostring(Parser[10])
| project-away Parser
