### ISSUE TITLE
microsoft-logstash-output-azure-loganalytics:  Failed to flush outgoing items

### ISSUE THREAD

**Issue by wstinkens** [Azure/Azure-Sentinel#1843]
When using the LogStash output plugin microsoft-logstash-output-azure-loganalytics v1.0 to ingest Fortinet logs in CEF format (see pipeline below), after a certain period (2-24 hours) I start getting Failed to flush outgoing items errors (see error below).

Because a high volume of logs is being processed (+-4000 events/second) I have tried setting the amount_resizing parameter to false and the max_items parameter to 4000 but I am still receiving the same error.

I am only getting this error for this specific pipeline with the highest volume of logs. My other pipelines on the same LogStash server are working as expected.

Pipeline:
input {
  udp {
    port => 1514
    type => syslog
    codec => cef
  }
}
filter{
}
output {
    microsoft-logstash-output-azure-loganalytics {
        workspace_id => "<workspace_id"
        workspace_key => "<workspace_key>"
        custom_log_table_name => "FortigateSyslog"
        plugin_flush_interval => 5
    }
}

Error:
`[2021-03-02T09:52:42,345][WARN ][logstash.outputs.azureloganalytics][syslog-fortigate-sentinel] Failed to flush outgoing items {:outgoing_count=>597, :exception=>"JSON::GeneratorError", :backtrace=>["jso
n/ext/GeneratorMethods.java:79:in 'to_json'", "/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/microsoft-logstash-output-azure-loganalytics-1.0.0/lib/logstash/logAnalyticsClient/logStashAutoResizeBuff
er.rb:41:in 'flush'", "/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/stud-0.0.23/lib/stud/buffer.rb:219:in 'block in buffer_flush'", "org/jruby/RubyHash.java:1415:in 'each'", "/usr/share/logstash/ve
ndor/bundle/jruby/2.5.0/gems/stud-0.0.23/lib/stud/buffer.rb:216:in 'buffer_flush'", "/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/stud-0.0.23/lib/stud/buffer.rb:112:in 'block in buffer_initialize'"
, "org/jruby/RubyKernel.java:1442:in 'loop'", "/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/stud-0.0.23/lib/stud/buffer.rb:110:in 'block in buffer_initialize'"]}`

**Comment by wstinkens** [comment]
I'm getting a similar error at the moment:
`2021-03-03T08:20:51,964][WARN ][logstash.outputs.azureloganalytics][syslog-fortigate-sentinel][b1d51617926ab2a62a42f6521dc664cc3b9fce7e9c5cb16f51372bd5e4a4c799] Failed to flush outgoing items {:outgoing_count=>2000, :exception=>"JSON::GeneratorError", :backtrace=>["json/ext/GeneratorMethods.java:79:in 'to_json'", "/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/microsoft-logstash-output-azure-loganalytics-1.0.0/lib/logstash/logAnalyticsClient/logStashAutoResizeBuffer.rb:41:in 'flush'", "/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/stud-0.0.23/lib/stud/buffer.rb:219:in 'block in buffer_flush'", "org/jruby/RubyHash.java:1415:in 'each'", "/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/stud-0.0.23/lib/stud/buffer.rb:216:in 'buffer_flush'", "/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/stud-0.0.23/lib/stud/buffer.rb:159:in 'buffer_receive'", "/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/microsoft-logstash-output-azure-loganalytics-1.0.0/lib/logstash/logAnalyticsClient/logStashAutoResizeBuffer.rb:28:in 'add_event_document'", "/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/microsoft-logstash-output-azure-loganalytics-1.0.0/lib/logstash/outputs/microsoft-logstash-output-azure-loganalytics.rb:85:in 'block in multi_receive'", "org/jruby/RubyArray.java:1809:in 'each'", "/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/microsoft-logstash-output-azure-loganalytics-1.0.0/lib/logstash/outputs/microsoft-logstash-output-azure-loganalytics.rb:78:in 'multi_receive'", "org/logstash/config/ir/compiler/OutputStrategyExt.java:143:in 'multi_receive'", "org/logstash/config/ir/compiler/AbstractOutputDelegatorExt.java:121:in 'multi_receive'", "/usr/share/logstash/logstash-core/lib/logstash/java_pipeline.rb:295:in 'block in start_workers'"]}`

**Comment by shainw** [comment]
@preetikr - Not sure if this has been addressed already via another thread.

**Comment by wstinkens** [comment]
Any updates on this issue?

**Comment by wstinkens** [comment]
> 
> 
> @preetikr - Not sure if this has been addressed already via another thread.

Any updates on this issue?

**Comment by preetikr** [comment]
Hi @NoamLandress - Please investigate this / add someone who can help investigate this issue. Thanks.

**Comment by NoamLandress** [comment]
Hi @wstinkens,
Thanks for bringing this to our attention.
Could you please open a support ticket about this so we could continue handling it from there?
Thanks!

**Comment by wstinkens** [comment]
Hi,

I have already created a support ticket (2103250060003229) for this issue 2
weeks ago.

Wouter

**Comment by sarah-yo** [comment]
Being tracked via Azure support

**Comment by jbalmo** [comment]
Hi, I've the same problem. Have you solve it, finally? @wstinkens

**Comment by tdeyle** [comment]
This has been an issue at my site as well. What needs to be done to move this forward to a resolution?
