### ISSUE TITLE
Incident settings (Preview) - Grouping alerts into a single incident if the selected entities match - only first available entity is saved in settings (if selected).

### ISSUE THREAD

**Issue by pgo888** [Azure/Azure-Sentinel#1870]
**Describe the bug**
Scheduled analytic rule is created and "Incident settings (Preview)" - "Grouping alerts into a single incident if the selected entities match:" option is utilized, by choosing more than 1 entity (e.g. Account and URL). Rule is validated and saved. When rule is edited again, it turns out that only setting for the first available entity was saved, other available entities are "unchecked".

**To Reproduce**
1. Go to 'Analytics'
2. Click on 'Create > Scheduled query rule'
3. Create any rule logic with multiple entities, e.g.

`let URL = "https://www.microsoft.com";
AzureActivity
| limit 1
| extend AccountCustomEntity = Caller, IPCustomEntity = CallerIpAddress, URLCustomEntity = URL`

4. Go to 'Incident settings (Preview)'.
5. Enable alert grouping (switch toggle button 'Group related alerts, triggered by this analytics rule, into incidents' to Enabled).
6. Click 'Grouping alerts into a single incident if the selected entities match:'.

Scenario "A":
7A. From drop down list 'Select entities' select first available and at least one additional entity.
8A. Complete process of creating scheduled query rule.
9A. Edit previously created rule and go to 'Incident settings (Preview)'. Only first entity selected in step 7A is selected.

Scenario "B':
7B. From drop down list 'Select entities' select 2nd available and - optionally - at least one additional entity. Do not select 1st available entity.
8B. Complete process of creating scheduled query rule.
9B. Edit previously created rule and go to 'Incident settings (Preview)'. None of the entities selected in step 7B is selected.

**Expected behavior**
It's expected that all selected options (when rule was successfully reviewed and created) are saved. In this specific use case, when multiple enitites are selected, this setting should be saved.

**Screenshots**
Scenario A:
- initial configuration:
![image](https://user-images.githubusercontent.com/80044986/109971434-8a5bc080-7cf6-11eb-8ea1-529ecec0a5ba.png)

- view of the previously saved rule:
![image](https://user-images.githubusercontent.com/80044986/109971737-d73f9700-7cf6-11eb-9a1f-9e4bb7ffff61.png)

Scenario B:
- initial configuration:
![image](https://user-images.githubusercontent.com/80044986/109972049-2dacd580-7cf7-11eb-824a-54863ade8228.png)

- view of the previously saved rule:
![image](https://user-images.githubusercontent.com/80044986/109972222-5cc34700-7cf7-11eb-9054-e81015f9e51b.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: any

**Comment by shainw** [comment]
@pgo888 - Thanks for the response.  The engineering team has been made aware of this, we will track here and get back to you once they have a chance to look at this further.

**Comment by shainw** [comment]
@pgo888 - This should have been fixed around the March 9th timeframe.  Can you confirm you are not seeing the issue still?

**Comment by shainw** [comment]
Closing issue as this appears to be resolved.
