### ISSUE TITLE
AssertionError: no_setter while running access_anomaly.fit(training_df)

### ISSUE THREAD

**Issue by iovex** [Azure/Azure-Sentinel#1896]
https://github.com/Azure/Azure-Sentinel/blob/master/BYOML/Notebooks/AnomalousRASampleData.ipynb

Some bugs in this demos code ,maybe caused by the lib 

Get the error:
model = access_anomaly.fit(training_df)
AssertionError: no_setter

after running below steps:

training_df.describe().show()
(2) Spark Jobs
+-------+----------+---------+-----------------+---------+-----------------+
|summary|      user|      res|       likelihood|tenant_id|           count_|
+-------+----------+---------+-----------------+---------+-----------------+
|  count|      1775|     1775|             1775|     1775|             1775|
|   mean|      null|     null|751.1521126760564|      0.0|6.061971830985915|
| stddev|      null|     null|142.7046344723063|      0.0|2.951618811241105|
|    min|eng_user_0|eng_res_0|            500.0|        0|              1.0|
|    max| hr_user_9| hr_res_9|           1000.0|        0|             11.0|
+-------+----------+---------+-----------------+---------+-----------------+

**Comment by shainw** [comment]
@iovex - I am tracking down the owner for this, will get back to you shortly.

**Comment by anilmsft** [comment]
Are you using Spark 3.0?  
mmlspark_2 has a dependency on Spark 2.4.  It is called out in the readme.md

**Comment by shainw** [comment]
@iovex - Did @anilmsft answer take care of this?

**Comment by iovex** [comment]
@anilmsft @shainw  thanksfor your clarification,  the errors disappeared after changing to Spark 2.4
