### ISSUE TITLE
HAFNIUM hashes update with sha1

### ISSUE THREAD

**Issue by lu-chi** [Azure/Azure-Sentinel#1897]
Would be nice to have sha1 as well, not only sha256 as unfortunately not all the EDRs are that smart.

**Comment by petebryan** [comment]
Hi,

The JSON format of the feed (https://github.com/Azure/Azure-Sentinel/blob/master/Sample%20Data/Feeds/MSTICIoCs-ExchangeServerVulnerabilitiesDisclosedMarch2021.json) contains MD5 and SHA1 hashes under the AdditionMetadata field.
