### ISSUE TITLE
Can we get a partial search function

### ISSUE THREAD

**Issue by Lodewyk-Git** [Azure/Azure-Sentinel#1909]
**Problem**
I always struggle to find values when I've only got a substring.

**Solution**
I'm proposing that there should be partial-search operator that searches for events containing a substring or that a kind gets added where it searches for a substring

**Alternative**
search * |  where * contains "value"

**Screenshots**
![image](https://user-images.githubusercontent.com/36856692/110786329-af12e380-8274-11eb-8439-612265a25204.png)

![image](https://user-images.githubusercontent.com/36856692/110786446-d073cf80-8274-11eb-916a-8f7b7faca6dd.png)

**Comment by shainw** [comment]
@Lodewyk-Git - search already does this, so I think I am missing your use case.  When I do something like:
```search "partial guid"``` it finds the appropriate rows.

**Comment by Lodewyk-Git** [comment]
Hi @shainw
Looks like it was a temporary bug at the same time that the TimeGenerated wasn't working properly a few weeks ago. 

It's working again so I'll close this incident.
