### ISSUE TITLE
SecurityAlert status not updating

### ISSUE THREAD

**Issue by Lodewyk-Git** [Azure/Azure-Sentinel#1911]
**Problem**
The Security Alert table does not always update the status of an alert, especially not for Sentinel.

**Duplicate**
Create an Incident, change the incident status, close the incident. wait for days to see that the status has not changed within The Security Alert table. 

**Example**
![image](https://user-images.githubusercontent.com/36856692/110790343-9c4edd80-8279-11eb-8268-7845cfd37e0c.png)![image](https://user-images.githubusercontent.com/36856692/110790710-0cf5fa00-827a-11eb-9b03-3547c3878995.png)
![image](https://user-images.githubusercontent.com/36856692/110790932-4d557800-827a-11eb-860b-b4bbfd94adc6.png)

**Disclosure**
I'm unsure whether this is supposed to be closed by Product side, but even if it is supposed to be closed product side the sentinel alerts should say dismissed/closed.

**Comment by shainw** [comment]
@oshezaf and @Ronmarsiano - Can you please have a look.

**Comment by oshezaf** [comment]
@Lodewyk-Git : alerts in Sentinel are immutable. Specifically, Sentinel alerts are never closed. The "managed" entity which is assigned or closed is the incident, and you should query the incident table. For details refer to https://docs.microsoft.com/en-us/azure/sentinel/manage-soc-with-incident-metrics

**Comment by Lodewyk-Git** [comment]
@oshezaf Hi Ofer, the problem here is that when you change the properties of an incident it adds duplicate rows to the SecurityIncident table.

*Screenshot*
![SecurityIncidents](https://user-images.githubusercontent.com/36856692/112309735-5d268080-8cac-11eb-9b78-5cc08d8cc6f4.jpg)
