### ISSUE TITLE
detection file containing copy of another detection

### ISSUE THREAD

**Issue by washuu** [Azure/Azure-Sentinel#1916]
please take a look at the files: 
Azure-Sentinel/Detections/CiscoUmbrella/CiscoUmbrellaRequestAllowedHarmfulMaliciousURICategory.yaml
and
Azure-Sentinel/Detections/CiscoUmbrella/CiscoUmbrellaConnectionNon-CorporatePrivateNetwork.yaml

Both files contain the same logic, applicable only to the first detection.

**Comment by shainw** [comment]
@washuu - Thanks for pointing this out.  @vu-socprime - Can you have a look, I assume you meant to have a different query?  @preetikr as FYI.

**Comment by shainw** [comment]
@vu-socprime - Can you have a look at this one?

**Comment by vu-socprime** [comment]
I have created PR for fixing it - https://github.com/Azure/Azure-Sentinel/pull/2005
