### ISSUE TITLE
importAzureSentinelRules.ps1 automatically enables analytic rules even when they are disabled in JSON

### ISSUE THREAD

**Issue by sukster** [Azure/Azure-Sentinel#1919]
**Describe the bug**
When importing the analytic rules with importAzureSentinelRules.ps1 script, I didn't want the rules to be automatically enabled after the import so I edited the Scheduled.json file and set the "Enabled" parameter to false. When I ran the importAzureSentinelRules.ps1 script everything worked fine except the analytic rules have been automatically enabled.

**To Reproduce**
1. Go to the exported Scheduled.json
2. For each or any analytic rule set "Enabled": false
3. Save Scheduled.json
4. Run the importAzureSentinelRules.ps1 script

**Expected behavior**
I would expect that after setting the "Enabled": false, the imported analytic rules would be in a disabled state after the import.

@tianderturpijn or anyone from the Sentinel team, could you please take a look at this?

Thank you, Ludek

**Comment by tianderturpijn** [comment]
@sukster Thanks Ludek, will look into it.

**Comment by tianderturpijn** [comment]
Fixed
