### ISSUE TITLE
importAzureSentinelRules.ps1 script not importing the "Description" field value

### ISSUE THREAD

**Issue by sukster** [Azure/Azure-Sentinel#1921]
**Describe the bug**
When I used the importAzureSentinelRules.ps1 script to import the analytic rules to Sentinel, it did not import the "Description" field value although it was correctly exported and present in the Scheduled.json file.

**To Reproduce**
1. Export the analytic rules (which have Description field populated) with exportAzureSentinelRules.ps1 script
2. Import the exported analytic rules with importAzureSentinelRules.ps1 script
3. See if the Description was imported or not

**Expected behavior**
I would like to the importAzureSentinelRules.ps1 script to import the analytic "Description" value.

@tianderturpijn or anyone from the Sentinel team, could you please try to replicate this and see if you are having the same issue?

Thanks, Ludek

**Comment by tianderturpijn** [comment]
@sukster  Thanks Ludek, going to look into it.

**Comment by tianderturpijn** [comment]
Resolved
