### ISSUE TITLE
data volume cap in workspace 

### ISSUE THREAD

**Issue by SivPothana** [Azure/Azure-Sentinel#1926]
Hello All,

we have data cap limited is only 100 GB  for day but getting more then 100GB data for day in Azure sentinel.

Any way troubleshooting steps in sentinel? if you have any please share us thanks advise.

**Comment by Lodewyk-Git** [comment]
Hi, so what you're saying is that you've got a daily cap limit set, but you're still receiving more than 100GB that are billable per day? Could you provide some additional info? - Screenshots of daily cap and the amount limit being surpassed.

**Comment by SivPothana** [comment]
Hi,
We are getting more than 100 GB data daily bases  but most of the data utilization security events only I have uploaded screenshot as well.
Could you please provide me how to suppress security event data.
If you need any further details please send me a meeting link (sivaramakrishna.p01@infosys.com)

**Comment by Lodewyk-Git** [comment]
Have you tried enabling a data cap found here:
![image](https://user-images.githubusercontent.com/36856692/111447415-1669e100-8716-11eb-9cf2-a6934e437aa7.png)

**Comment by SivPothana** [comment]
thanks for your response I want more concern about hear is  surprise that security event data like.. checkpoint & Palo Alto (common security event tables data )

**Comment by shainw** [comment]
@SivPothana - I recommned you go thru the Ninja training provided in our blogs, this [search](https://techcommunity.microsoft.com/t5/forums/searchpage/tab/message?advanced=false&allow_punctuation=false&q=azure%20sentinel%20ninja) will get you the necessary items.  If that still does not help, I recommend you post to the [techcommunity portal](https://techcommunity.microsoft.com/t5/azure-sentinel/bd-p/AzureSentinel).  Lastly, if you don't get answers there, then you may want to open a [support ticket](https://azure.microsoft.com/en-us/support/options/).
