### ISSUE TITLE
Export-Incidents-With-Comments

### ISSUE THREAD

**Issue by SivPothana** [Azure/Azure-Sentinel#1927]
Hello All,

I need to Export all incidents and comments in an CSV file. 

what is the best way to achieve this? Are there any queries already available for a similar objective?

**Comment by Lodewyk-Git** [comment]
Hi, yes there is a playbook available that does this here: https://github.com/Azure/Azure-Sentinel/tree/master/Playbooks/Export-Incidents-With-Comments 

Please know that asking questions related to specific queries are more likely to be answered here : https://techcommunity.microsoft.com/

**Comment by SivPothana** [comment]
Hi Lodewyk,
Thanks for your response!
I know we have the playbook is available in GitLab, But my sentinel deployment  it dint work this playbook.
that way we are sawing is there any queries already available ?

**Comment by shainw** [comment]
@SivPothana - The [playbook](https://github.com/Azure/Azure-Sentinel/tree/master/Playbooks/Export-Incidents-With-Comments) has a reference to [further details and troubleshooting](https://www.bridewellconsulting.com/automating-azure-sentinel-using-playbooks-to-extract-data).  I recommend you review that information to see the Logic Apps and Requirements for functionality.

**Comment by shainw** [comment]
@SivPothana - if you need further assistance with this feature, I suggest you post to the TechCommunity as @Lodewyk-Git suggested as this may need further troubleshooting.
