### ISSUE TITLE
MCAS Alert mapping incorrect Account

### ISSUE THREAD

**Issue by Lodewyk-Git** [Azure/Azure-Sentinel#1941]
**Describe the bug**
The account entity displayed in the Incident is not related to the actual sign-in attempt in both Activity from an anonymous proxy and Activity from an anonymous proxy. Although it is associated with the Identity. 

**To Reproduce**
1. Go to 'MCAS portal' and enable Activity from an anonymous proxy
2. Fail to sign-in from a VPN connected IP.
3. Wait for the Incident to be created in Sentinel.
4. Scroll down to the Entities associated with the alert, see that it's not the same as the account associated with the sign-in.

**Expected behavior**
Account used to sign-in is displayed as Entity for microsoft related products

**Screenshots**
![image](https://user-images.githubusercontent.com/36856692/111144211-741ff100-858f-11eb-9dd1-2b97e5d5d4cb.png)

![image](https://user-images.githubusercontent.com/36856692/111144600-eee90c00-858f-11eb-941a-88bc38504582.png)

**Additional context**
I've not seen this specific problem occur multiple times. The Principal account associated with Entity behavior was displayed, but the alternate sign in account was the account that performed the action when looking through Sign-in Logs and the principal account is not the same when looking at the sign-in logs.

**Comment by shainw** [comment]
@oshezaf - Can you have a look at this?  Maybe the connector is mapping properly, but in some MCAS alerts the mapping is different?

**Comment by oshezaf** [comment]
@Lodewyk-Git : I would suggest openning a support ticket on this topic. Issues on this GitHub are intended for GitHub content, and not Sentinel issues in general.
