### ISSUE TITLE
Add ability to export Alert Grouping setting in exportAzureSentinelRules.ps1 script

### ISSUE THREAD

**Issue by sukster** [Azure/Azure-Sentinel#1942]
**Is your feature request related to a problem? Please describe.**
I have noticed that currently the exportAzureSentinelRules.ps1 does not export the setting for Alert Grouping. When using the script this needs to be then fixed manually.

**Describe the solution you'd like**
It would be helpful, if the Alert Grouping setting were exported and imported automatically by both scripts.

@tianderturpijn or anyone from the Sentinel team, could you please take a look at this?

Thank you, Ludek

**Comment by tianderturpijn** [comment]
Alert grouping (and automation rules for that matter) or not GA yet. The Az.SecurityInsights PowerShell module is based on GA features. As soon as the features hit GA, we will update the Az.SecurityInsights PowerShell module.

**Comment by tianderturpijn** [comment]
Will release alert grouping support upon GA.
