### ISSUE TITLE
AlertLink field empty in Security Resource Graph KCL queries

### ISSUE THREAD

**Issue by guidovbrakel** [Azure/Azure-Sentinel#1948]
AlertLink missing in Security Resource Graph KCL queries
When we run this query to get the Sentinel Alerts, the AlertLink value is empty.
```
SecurityAlert
| where TimeGenerated >= ago(5m)
| project DisplayName, ProductName, SystemAlertId, AlertLink
```
That field seems to be filled in only for certain alerts. I ran: 
```
SecurityAlert
| where isnotempty(AlertLink ) 
```
 and it only appears to show up for non-Sentinel alerts including ASC, Fusion, and MDATP.

**Comment by shainw** [comment]
@guidovbrakel - the details for Sentinel Alerts are in the Azure Sentinel UX you are currently in whereas the links you are provided are for Alerts that are brought in from other security services via the connector and the link is back to the portal for that security service.

**Comment by shainw** [comment]
@guidovbrakel - closing this, feel free to reopen if you have further questions.
