### ISSUE TITLE
exportAzureSentinelRules.ps1 and importAzureSentinelRules.ps1 supporting Entity Mapping

### ISSUE THREAD

**Issue by sukster** [Azure/Azure-Sentinel#2025]
**Is your feature request related to a problem? Please describe.**
As of now, both scripts do not support export and import of the Entity Mapping in Azure Sentinel. When using these scripts we have to go and add the entity mapping manually. The import of entity mapping is available with the ImportGitHubYAMLrules.ps1 but not in importAzureSentinelRules.ps1. 

**Describe the solution you'd like**
Could you please develop this feature in the importAzureSentinelRules.ps1 and exportAzureSentinelRules.ps1 or alternatively develop a new script to export the analytic rules into the YAML format and we could then use the ImportGitHubYAMLrules.ps1 to import them?

@tianderturpijn or anyone from the Sentinel team, could you please take a look at this?

Thank you, Ludek

**Comment by dicolanl** [comment]
Hi @sukster 
We are aware of this.  The powershell module the script is using is based off the GA version of the API which currently does not expose the entity mapping.  Once that is added we will update the module.
