### ISSUE TITLE
Unable to enable analytical rule

### ISSUE THREAD

**Issue by Lodewyk-Git** [Azure/Azure-Sentinel#2039]
**Describe the bug**
The logic of the query is fine, but it can't be enabled if no data is found. 
This is because The Log analytics query is ran to test out the rule before it is enabled.

**To Reproduce**
1. Go to 'Analytics'
2. Click on 'Templates'
3. Scroll down to 'Exchange OAB Virtual Directory Attribute Containing Potential Webshell'
4. Try to enable this rule
5. See error

**Expected behavior**
Rule should be capabale of being enabled 

**Screenshots**
![image](https://user-images.githubusercontent.com/36856692/113008950-cd834500-9177-11eb-8b63-0bbf32e58616.png)

**Comment by guidovbrakel** [comment]
@Lodewyk-Git Did you added the OABGeneratorLog to Sentinel?
`To onboard the HTTPProxy AOBGeneratorLog, you need to enable (if it’s not already) the Security Events Data Connector in Azure Sentinel and install the Log Analytics agent on the Exchange server. Then go into the Advanced Settings of the Log Analytics Workspace for Azure Sentinel and setup custom log ingestion. Make sure you are connected to the Exchange server through the file system so you can access C:\Program Files\Microsoft\Exchange Server\V15\Logging\OABGeneratorLog to include in the custom log setup wizard. During the wizard, name the new table http_proxy_oab_CL to match the Analytics Rule requirement.`

**Comment by Lodewyk-Git** [comment]
Hi @guidovbrakel 
Thanks for the info, I'll make sure to enable the logging from the exchange server, but the parsing is picking up as faulty, thus preventing me from enabling the rule. 

In the screenshot above I tried to find a roundabout by moving the eventID to after the parsing. Please see the following screenshot:
![image](https://user-images.githubusercontent.com/36856692/113270228-8ca34180-92d9-11eb-9fcd-5616bf28cb89.png)

**Comment by shainw** [comment]
This is fixed in #2191
