### ISSUE TITLE
SymantecProxySG.txt parser update

### ISSUE THREAD

**Issue by appelboom** [Azure/Azure-Sentinel#2042]
Issue Source: Symantec ProxySG (Preview) data connector Kusto Function parser
Reference: https://github.com/Azure/Azure-Sentinel/blob/master/Parsers/SymantecProxySG/SymantecProxySG.txt

The default  BlueCoat ProxySG ELFF log field attribute "date" results in line wrapping issues in rsyslogd/Fluentd parsing to Sentinel Log Analytics workspace. Rather than use a PRoxySG default reuse the MCAS formal below replacing time with localtime

localtime time time-taken c-ip cs-username cs-auth-group x-exception-id sc-filter-result cs-categories cs(Referer) sc-status s-action cs-method rs(Content-Type) cs-uri-scheme cs-host cs-uri-port cs-uri-path cs-uri-query cs-uri-extension cs(User-Agent) s-ip sc-bytes cs-bytes x-virus-id

Some W3C ELFF log entries for cs(Referer) contain whitespace so replacing cs(Referer) with a placeholder attribute like x-virus-id is cleaner.

Reference:
https://techdocs.broadcom.com/content/dam/broadcom/techdocs/symantec-security-software/web-and-network-security/proxysg/common/LogFieldsSubs.pdf

Versions:
SGOS 6.7.4.15
omsagent-1.13.35-0.universal.x64.sh
rsyslogd  8.1911.0-6.el8 (aka 2019.11) compiled with:
        PLATFORM:                               x86_64-redhat-linux-gnu

#################################################
Parser working with updates 
###################################################
Syslog
| where Computer in ("datasource") and Facility == "user"
// Parse 1/3 of SyslogMessage. Seperated due to extract_all() operator limited to 16 regex groups
// BlueCoat ProxySG ELFF Log Format to address time truncation using Log last header
// Custom Log format: localtime time-taken c-ip cs-username cs-auth-group x-exception-id sc-filter-result cs-categories x-virus-id sc-status s-action cs-method rs(Content-Type) cs-uri-scheme cs-host cs-uri-port cs-uri-path cs-uri-query cs-uri-extension cs(User-Agent) s-ip sc-bytes cs-bytes x-virus-id 
| extend Parser = extract_all(@'^(\d{2}:\d{2}:\d{2})\s+(\S+)\]"\s+(\S+)\s+(\S+)\s+(\S+)\s+(\S+)\s+(\S+)\s+(\S+)\s+\"(.*?)"\s+(\S+)\s+(\S+)\s+([\S\s]+)',dynamic([1,2,3,4,5,6,7,8,9,10,11,12]), SyslogMessage)
| mv-expand Parser
| extend logTime = todatetime(strcat(tostring(Parser[0]),'T',tostring(Parser[1]))), 
    time_taken = tolong(Parser[2]), 
    c_ip = tostring(Parser[3]), 
    cs_userdn = tostring(Parser[4]), 
    cs_auth_groups= replace(@"%20",@'',tostring(Parser[5])), 
    exception_id = tostring(Parser[6]), 
    sc_filter_result = tostring(Parser[7]), 
    cs_categories = split(Parser[8],";"), 
    cs_referrer = tostring(Parser[9]), 
    sc_status = tostring(Parser[10]), 
    RemainingString1 = Parser[11] 
// Parse 2/3 of SyslogMessage
| extend Parser2 = extract_all(@'^(\S+)\s+(\S+)\s+(\S+)\s+(\S+)\s+(\S+)\s+(\S+)\s+(\S+)\s+(\S+)\s+(\S+)\s+(\"([\w\s\)\,\.\(\;\:\/\_\-\|\}\{\%\=\+\?\<\>\#\]\[]+)\"|(\S+))\s+(\S+)\s+(\S+)\s+([\S\s]+)',dynamic([1,2,3,4,5,6,7,8,9,10,11,12]), tostring(RemainingString1))
| mv-expand Parser2
// Parse 3/3 of SyslogMessage
| extend s_action = tostring(Parser2[0]), 
    cs_method= tostring(Parser2[1]), 
    content_type = split(replace(@"%20",@'',tostring(Parser2[2])),";"), 
    cs_uri_scheme = tostring(Parser2[3]), 
    cs_host = tostring(Parser2[4]), 
    cs_uri_port = tostring(Parser2[5]), 
    cs_uri_path = tostring(Parser2[6]), 
    cs_uri_query = tostring(Parser2[7]), 
    cs_uri_extension = tostring(Parser2[8]), 
    cs_user_agent = tostring(Parser2[10]), 
    s_ip = tostring(Parser2[12]), 
    sent_bytes =  tolong(Parser2[13]), RemainingString2 = Parser2[14]
| extend Parser3 = extract_all(@'^(\d+)\s+(\S+)\s+\"([\w].+)\"\s+\"([\w].+)\"\s+(\d+)\s+(\S+)\s+(\S+)',dynamic([1,2,3,4,5,6,7]), tostring(RemainingString2))
| mv-expand Parser3
| extend received_bytes = tolong(Parser3[0]), 
    virus_id = tostring(Parser3[1]), 
    app_name = tostring(Parser3[2]), 
    app_operation = tostring(Parser3[3]), 
    src_port = tostring(Parser3[4]), 
    cs_threat_risk = tostring(Parser3[6]),
    country = replace(@"%20",@' ',tostring(Parser3[5]))
| project-away Parser, Parser2, Parser3, RemainingString1, RemainingString2

**Comment by preetikr** [comment]
@v-jayakal - Can you please look into this? Thanks.

**Comment by v-jayakal** [comment]
@appelboom , running the above query is returning error of "ill-formed regular expression".
![IllformedRegEx](https://user-images.githubusercontent.com/73506651/116192672-082ebd80-a6e3-11eb-963e-e5e4fbc1d995.PNG).
Can you please update the parser file here https://github.com/Azure/Azure-Sentinel/blob/master/Parsers/SymantecProxySG/SymantecProxySG.txt as a pull request? It will help in tracking the history.

**Comment by appelboom** [comment]
Regex above parsers correctly however a WARNING to other users wishing to use the Log Analytics function the | mv-expand Parser  
 function massively degrades performance if you have millions of records, so much so the Data connector overview page will display the three blinking dots until | mv-expand Parser is removed (and breaking this parser) YMMV

**Comment by elforb** [comment]
Updated query portion results in error due to extra closing parenthesis at the end of the contained regex.

Corrected Query: `| extend Parser = extract_all(@'^(\d{2}:\d{2}:\d{2})\s+(\S+)]"\s+(\d+)\s+(\S+)\s+(\S+)\s+(\S+)\s+(\S+)\s+(\S+)\s+"([\w\s)(;/_-]+)"\s+(\S+)\s+(\d+)\s+([\S\s]+)',dynamic([1,2,3,4,5,6,7,8,9,10,11,12]), SyslogMessage)`

**Comment by elforb** [comment]
@appelboom We've raised a PR, #2289 , to affect this change. Could you please review?

**Comment by appelboom** [comment]
@elforb Apologies please recheck this. The above does not parse logs (my fault)

`| extend Parser = extract_all(@'^(\d{2}:\d{2}:\d{2})\s+(\S+)\]"\s+(\d+)\s+(\S+)\s+(\S+)\s+(\S+)\s+(\S+)\s+(\S+)\s+\"([\w\s\)\(;\/_-]+)\"\s+(\S+)\s+(\d+)\s+([\S\s]+)',dynamic([1,2,3,4,5,6,7,8,9,10,11,12]), SyslogMessage)`

**Comment by elforb** [comment]
@appelboom The PR, #2289, has been updated with these changes. Please review.

**Comment by v-jayakal** [comment]
@appelboom , Can you please provide us few sample log messages? Tried to find log message format for Symantec ProxySG by following the documentation, but was not successful. Thanks.

**Comment by shainw** [comment]
@v-jayakal - There is an old sample data set in the sample data/syslog folder [here](https://github.com/Azure/Azure-Sentinel/blob/master/Sample%20Data/Syslog/SymantecProxySG.json) - does this suffice?

**Comment by appelboom** [comment]
Hi,

Ended up creating our own parser so don't have any log samples for above.
We found the mv-expand dynamic function is too slow for our event rate.
Use of mv-expand will also slow down the Sentinel datasource UI
The original parser parses many irrelevant fields that just drives up log analytics costs.

Step 1: Set the ProxySG format
We are using localtime here as any other time format results in line wrapping in Sentinel parsed logs and #015 being ignored.

localtime c-ip cs-username sc-status s-action cs-method cs-host cs-uri-port cs-uri-address s-ip cs-threat-risk x-virus-id sc-bytes cs-bytes cs-categories

This will result in the ProxySG logging in below format.

"[14/Jun/2021:18:46:20 +0800]" 192.168.176.220 - 407 TCP_DENIED CONNECT play.googleapis.com 443 142.250.70.202 192.168.49.117 1 - 303 172 "Technology/Internet"
"[14/Jun/2021:18:46:20 +0800]" 192.168.84.61 user3 200 TCP_ACCELERATED CONNECT i.instagram.com 443 157.240.8.52 192.168.49.117 1 - 39 267 "Media Sharing;Social Networking"

However Sentinel logs the following to Syslog table, note truncated timestamp. Not sure  if its sentinel or rsyslog doing this

18:46:49 +0800]" 192.168.171.77 user1 204 TCP_NC_MISS GET www.youtube.com 443 142.250.70.174 192.168.49.117 1 - 536 1546 "Category - Guest SSL Intercept Mixed Content/Potentially Adult Audio/Video Clips" #015
18:46:49 +0800]" 192.168.49.48 - 407 TCP_DENIED CONNECT www.google.com.au 443 142.250.70.195 192.168.49.117 1 - 303 245 "Search Engines/Portals" #015
18:46:49 +0800]" 192.168.49.48 user2 200 TCP_NC_MISS GET www.google.com 443 216.239.38.120 192.168.49.117 1 - 991 1838 "Search Engines/Portals" #015

Step 2:  Update SymantecProxySG function

My regex skills are poor but this seems to do the job quite well.

Syslog
| where Computer in ("proxy1","proxy2")
| extend logTime = extract("(\\S+).(\\S+).(\\S+).(\\S+).(\\S+).(\\S+).(\\S+).(\\S+).(\\S+)",1,SyslogMessage),
c_ip = extract("(\\S+).(\\S+).(\\S+).(\\S+).(\\S+).(\\S+).(\\S+).(\\S+).(\\S+)",3,SyslogMessage),
cs_userdn  = extract("(\\S+).(\\S+).(\\S+).(\\S+).(\\S+).(\\S+).(\\S+).(\\S+).(\\S+)",4,SyslogMessage),
exception_id  = extract("(\\S+).(\\S+).(\\S+).(\\S+).(\\S+).(\\S+).(\\S+).(\\S+).(\\S+)",5,SyslogMessage),
sc_filter_result = extract("(\\S+).(\\S+).(\\S+).(\\S+).(\\S+).(\\S+).(\\S+).(\\S+).(\\S+)",6,SyslogMessage),
sc_status = extract("(\\S+).(\\S+).(\\S+).(\\S+).(\\S+).(\\S+).(\\S+).(\\S+).(\\S+)",7,SyslogMessage),
cs_host = extract("(\\S+).(\\S+).(\\S+).(\\S+).(\\S+).(\\S+).(\\S+).(\\S+).(\\S+)",8,SyslogMessage),
cs_uri_port = extract("(\\S+).(\\S+).(\\S+).(\\S+).(\\S+).(\\S+).(\\S+).(\\S+).(\\S+)",9,SyslogMessage),
cs_uri_address = extract("(\\S+).(\\S+).(\\S+).(\\S+).(\\S+).(\\S+).(\\S+).(\\S+).(\\S+).(\\S+)",10,SyslogMessage),
cs_ip = extract("(\\S+).(\\S+).(\\S+).(\\S+).(\\S+).(\\S+).(\\S+).(\\S+).(\\S+).(\\S+).(\\S+)",11,SyslogMessage),
cs_threat_risk = extract("(\\S+).(\\S+).(\\S+).(\\S+).(\\S+).(\\S+).(\\S+).(\\S+).(\\S+).(\\S+).(\\S+).(\\S+)",12,SyslogMessage),
virus_id = extract("(\\S+).(\\S+).(\\S+).(\\S+).(\\S+).(\\S+).(\\S+).(\\S+).(\\S+).(\\S+).(\\S+).(\\S+).(\\S+)",13,SyslogMessage),
sent_bytes = extract("(\\S+).(\\S+).(\\S+).(\\S+).(\\S+).(\\S+).(\\S+).(\\S+).(\\S+).(\\S+).(\\S+).(\\S+).(\\S+).(\\S+)",14,SyslogMessage),
received_bytes = extract("(\\S+).(\\S+).(\\S+).(\\S+).(\\S+).(\\S+).(\\S+).(\\S+).(\\S+).(\\S+).(\\S+).(\\S+).(\\S+).(\\S+).(\\S+)",15,SyslogMessage),
//cs_categories = extract(@'(\"([\w].+)\")',1,SyslogMessage)
cs_categories = extractall(@'(\"([\w].+)\")',dynamic([1]),SyslogMessage)

Perhaps this will benefit someone else.

Kind regards

**Comment by v-jayakal** [comment]
@appelboom , can you please tell us whether we have to make any version changes as you mentioned above?
Versions you mentioned:
SGOS 6.7.4.15
omsagent-1.13.35-0.universal.x64.sh
rsyslogd 8.1911.0-6.el8 (aka 2019.11) compiled with:
PLATFORM: x86_64-redhat-linux-gnu
As per the above conversation, after version change, do we have to change the date format? 
Please let us know. 
Thanks.

**Comment by appelboom** [comment]
Hi Kal,

Assuming the Symantec ProxySG Data Parser will continue using the original mv-expand function no version changes required but we are suspecting rsyslogd or OMS agent has a bug and is truncating ProxySG logs resulting in random line wrapping / ends.  When localtime attribute is used the wrapping stops and we can match around the issue with the parser update above and below

| extend Parser = extract_all(@'^(\d{2}:\d{2}:\d{2})\s+(\S+)\]"\s+(\d+)\s+(\S+)\s+(\S+)\s+(\S+)\s+(\S+)\s+(\S+)\s+\"([\w\s\)\(;\/_-]+)\"\s+(\S+)\s+(\d+)\s+([\S\s]+)',dynamic([1,2,3,4,5,6,7,8,9,10,11,12]), SyslogMessage)

 We would suggest the default parser recommends a parser log format as Proxy have multiple formats. The parser above expect this formal:  localtime time-taken c-ip cs-username cs-auth-group x-exception-id sc-filter-result cs-categories x-virus-id sc-status s-action cs-method rs(Content-Type) cs-uri-scheme cs-host cs-uri-port cs-uri-path cs-uri-query cs-uri-extension cs(User-Agent) s-ip sc-bytes cs-bytes x-virus-id

If the rsyslog/oms/sentinel internal inability to detect new lines and to truncate randomly is addressed please consider this a workaround

**Comment by v-jayakal** [comment]
@appelboom , ISO - ISO 8601 — Date and time format is expected, then the dates will not be truncated. As per the above data you provided, the datetime at your end does not follow the format.

**Comment by v-jayakal** [comment]
@appelboom , as the time format is different and you have the parser at your end for the format, I am closing this issue.
