### ISSUE TITLE
GitHub Function Hangs on Audit Entry

### ISSUE THREAD

**Issue by BenMcGarry** [Azure/Azure-Sentinel#2092]
**Describe the bug**
When executing the function, it will hang on audit entries. It hits this line then will hang, I raised the time limit to 30 minutes and the function logs receives no trace until timeout.

This line is what it hits. https://github.com/Azure/Azure-Sentinel/blob/master/DataConnectors/GithubFunction/AzureFunctionGitHub/GitHubTimerTrigger/run.ps1#L252

**To Reproduce**
Steps to reproduce the behaviour:
1. Run Function
2. Hit Audit Entries
3. Stall until timeout.

**Expected behaviour**
Function does not stall.

**Screenshots**
![image](https://user-images.githubusercontent.com/9434920/113784958-22056200-972e-11eb-994b-190c1cba53f8.png)

cc @sreedharande

**Comment by sreedharande** [comment]
Thanks @BenMcGarry, From the above screenshot, the organization name was given as "ORGNAME" in ORGS.json file in Storage Account blob container "github-repo-logs". Please verify and confirm

**Comment by BenMcGarry** [comment]
I swapped the text to ORGNAME in the screenshot to not disclose my organisation. In the running system it does display a valid org associated with the PAT.

**Comment by sreedharande** [comment]
@BenMcGarry - Thanks for the update. Will keep you posted with my findings
