### ISSUE TITLE
GithubFunction data connector unclear Post Deployment Steps

### ISSUE THREAD

**Issue by audunsolemdal** [Azure/Azure-Sentinel#2119]
**Describe the bug**

The docs for GithubFunction data connector are unclear or there are missing files

**To Reproduce**
1. Go to 'https://github.com/Azure/Azure-Sentinel/tree/master/DataConnectors/GithubFunction#post-deployment-steps'

`1. There are two json files (ORGS.json and lastrun-Audit.json) in Function Dependencies folder`

I am not sure what is referred to by "Function Dependencies" folder, and I am not able to find any orgs.json or lastrun-audit.json files anywhere.

I tried manually creating the orgs.json file and add it to github-repo-logs, but I am getting some hard to read errors during the function execution and nothing is stored.

**Comment by dicolanl** [comment]
@sreedharande Please review

**Comment by sreedharande** [comment]
@audunsolemdal - Please follow the steps 
1. Navigate to https://github.com/Azure/Azure-Sentinel/tree/master/DataConnectors/GithubFunction
![image](https://user-images.githubusercontent.com/22670063/115900413-c963e380-a414-11eb-846f-f36c337e9cc1.png)
2. Under "Function Dependencies" folder you will find ORGS.json and lastrun-Audit.json
![image](https://user-images.githubusercontent.com/22670063/115900565-ef898380-a414-11eb-95ff-a8708f0d4d89.png)

Please let me know, if you need any additional information

**Comment by sreedharande** [comment]
@audunsolemdal - are you able to resolve this issue??
