### ISSUE TITLE
OneLogin Data Connector fails due to undefined variable and incorrect status code type in output binding

### ISSUE THREAD

**Issue by j-d-harvey** [Azure/Azure-Sentinel#2136]
**Describe the bug**
Connector does not work (see error output). The first error occurs because the $event variable is defined after the Post-LogAnalyticsData function is called. The second error block seems to be occurring because the $writeResult variable is not set anywhere, so no valid StatusCode is being set.

**To Reproduce**
1. Deploy the Data Connector per https://github.com/Azure/Azure-Sentinel/tree/master/DataConnectors/OneLogin
2. Check function execution history

**Expected behavior**
Executes successfully and returns 200 per https://developers.onelogin.com/api-docs/1/events/webhooks

**Screenshots**
Error output:
ERROR: Exception calling "GetBytes" with "1" argument(s): "Array cannot be null. Parameter name: chars" At C:\home\site\wwwroot\OneLogin\run.ps1:73 char:2 + Post-LogAnalyticsData -customerId $customerId -sharedKey $sharedKey ... + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ + CategoryInfo : NotSpecified: (:) [], MethodInvocationException + FullyQualifiedErrorId : ArgumentNullException Script stack trace: at <ScriptBlock>, C:\home\site\wwwroot\OneLogin\run.ps1: line 73 System.Management.Automation.MethodInvocationException: Exception calling "GetBytes" with "1" argument(s): "Array cannot be null. Parameter name: chars" at System.Management.Automation.ExceptionHandlingOps.ConvertToMethodInvocationException(Exception exception, Type typeToThrow, String methodName, Int32 numArgs, MemberInfo memberInfo) at CallSite.Target(Closure , CallSite , Encoding , Object ) at System.Management.Automation.Interpreter.DynamicInstruction`3.Run(InterpretedFrame frame) at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame) Inner exception: System.ArgumentNullException: Array cannot be null. Parameter name: chars at System.Text.Encoding.GetBytes(Char[] chars) at CallSite.Target(Closure , CallSite , Encoding , Object )

ERROR: Cannot create object of type "Microsoft.Azure.Functions.PowerShellWorker.HttpResponseContext". Cannot convert null to type "System.Net.HttpStatusCode" due to enumeration values that are not valid. Specify one of the following enumeration values and try again. The possible enumeration values are "Continue,SwitchingProtocols,Processing,EarlyHints,OK,Created,Accepted,NonAuthoritativeInformation,NoContent,ResetContent,PartialContent,MultiStatus,AlreadyReported,IMUsed,MultipleChoices,Ambiguous,MovedPermanently,Moved,Found,Redirect,SeeOther,RedirectMethod,NotModified,UseProxy,Unused,TemporaryRedirect,RedirectKeepVerb,PermanentRedirect,BadRequest,Unauthorized,PaymentRequired,Forbidden,NotFound,MethodNotAllowed,NotAcceptable,ProxyAuthenticationRequired,RequestTimeout,Conflict,Gone,LengthRequired,PreconditionFailed,RequestEntityTooLarge,RequestUriTooLong,UnsupportedMediaType,RequestedRangeNotSatisfiable,ExpectationFailed,MisdirectedRequest,UnprocessableEntity,Locked,FailedDependency,UpgradeRequired,PreconditionRequired,TooManyRequests,RequestHeaderFieldsTooLarge,UnavailableForLegalReasons,InternalServerError,NotImplemented,BadGateway,ServiceUnavailable,GatewayTimeout,HttpVersionNotSupported,VariantAlsoNegotiates,InsufficientStorage,LoopDetected,NotExtended,NetworkAuthenticationRequired". At C:\home\site\wwwroot\OneLogin\run.ps1:84 char:1 + Push-OutputBinding -Name Response -Value ([HttpResponseContext]@{ + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ + CategoryInfo : InvalidArgument: (:) [], RuntimeException + FullyQualifiedErrorId : ObjectCreationError Script stack trace: at <ScriptBlock>, C:\home\site\wwwroot\OneLogin\run.ps1: line 84 System.Management.Automation.RuntimeException: Cannot create object of type "Microsoft.Azure.Functions.PowerShellWorker.HttpResponseContext". Cannot convert null to type "System.Net.HttpStatusCode" due to enumeration values that are not valid. Specify one of the following enumeration values and try again. The possible enumeration values are "Continue,SwitchingProtocols,Processing,EarlyHints,OK,Created,Accepted,NonAuthoritativeInformation,NoContent,ResetContent,PartialContent,MultiStatus,AlreadyReported,IMUsed,MultipleChoices,Ambiguous,MovedPermanently,Moved,Found,Redirect,SeeOther,RedirectMethod,NotModified,UseProxy,Unused,TemporaryRedirect,RedirectKeepVerb,PermanentRedirect,BadRequest,Unauthorized,PaymentRequired,Forbidden,NotFound,MethodNotAllowed,NotAcceptable,ProxyAuthenticationRequired,RequestTimeout,Conflict,Gone,LengthRequired,PreconditionFailed,RequestEntityTooLarge,RequestUriTooLong,UnsupportedMediaType,RequestedRangeNotSatisfiable,ExpectationFailed,MisdirectedRequest,UnprocessableEntity,Locked,FailedDependency,UpgradeRequired,PreconditionRequired,TooManyRequests,RequestHeaderFieldsTooLarge,UnavailableForLegalReasons,InternalServerError,NotImplemented,BadGateway,ServiceUnavailable,GatewayTimeout,HttpVersionNotSupported,VariantAlsoNegotiates,InsufficientStorage,LoopDetected,NotExtended,NetworkAuthenticationRequired". Inner exception: System.Management.Automation.PSInvalidCastException: Cannot create object of type "Microsoft.Azure.Functions.PowerShellWorker.HttpResponseContext". Cannot convert null to type "System.Net.HttpStatusCode" due to enumeration values that are not valid. Specify one of the following enumeration values and try again. The possible enumeration values are "Continue,SwitchingProtocols,Processing,EarlyHints,OK,Created,Accepted,NonAuthoritativeInformation,NoContent,ResetContent,PartialContent,MultiStatus,AlreadyReported,IMUsed,MultipleChoices,Ambiguous,MovedPermanently,Moved,Found,Redirect,SeeOther,RedirectMethod,NotModified,UseProxy,Unused,TemporaryRedirect,RedirectKeepVerb,PermanentRedirect,BadRequest,Unauthorized,PaymentRequired,Forbidden,NotFound,MethodNotAllowed,NotAcceptable,ProxyAuthenticationRequired,RequestTimeout,Conflict,Gone,LengthRequired,PreconditionFailed,RequestEntityTooLarge,RequestUriTooLong,UnsupportedMediaType,RequestedRangeNotSatisfiable,ExpectationFailed,MisdirectedRequest,UnprocessableEntity,Locked,FailedDependency,UpgradeRequired,PreconditionRequired,TooManyRequests,RequestHeaderFieldsTooLarge,UnavailableForLegalReasons,InternalServerError,NotImplemented,BadGateway,ServiceUnavailable,GatewayTimeout,HttpVersionNotSupported,VariantAlsoNegotiates,InsufficientStorage,LoopDetected,NotExtended,NetworkAuthenticationRequired". at System.Management.Automation.LanguagePrimitives.ConvertViaNoArgumentConstructor.Convert(Object valueToConvert, Type resultType, Boolean recursion, PSObject originalValueToConvert, IFormatProvider formatProvider, TypeTable backupTable, Boolean ignoreUnknownMembers) at System.Management.Automation.LanguagePrimitives.ConvertViaNoArgumentConstructor.Convert(Object valueToConvert, Type resultType, Boolean recursion, PSObject originalValueToConvert, IFormatProvider formatProvider, TypeTable backupTable) at CallSite.Target(Closure , CallSite , Hashtable ) at System.Management.Automation.Interpreter.DynamicInstruction`2.Run(InterpretedFrame frame) at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame) Inner exception: System.Management.Automation.PSInvalidCastException: Cannot convert null to type "System.Net.HttpStatusCode" due to enumeration values that are not valid. Specify one of the following enumeration values and try again. The possible enumeration values are "Continue,SwitchingProtocols,Processing,EarlyHints,OK,Created,Accepted,NonAuthoritativeInformation,NoContent,ResetContent,PartialContent,MultiStatus,AlreadyReported,IMUsed,MultipleChoices,Ambiguous,MovedPermanently,Moved,Found,Redirect,SeeOther,RedirectMethod,NotModified,UseProxy,Unused,TemporaryRedirect,RedirectKeepVerb,PermanentRedirect,BadRequest,Unauthorized,PaymentRequired,Forbidden,NotFound,MethodNotAllowed,NotAcceptable,ProxyAuthenticationRequired,RequestTimeout,Conflict,Gone,LengthRequired,PreconditionFailed,RequestEntityTooLarge,RequestUriTooLong,UnsupportedMediaType,RequestedRangeNotSatisfiable,ExpectationFailed,MisdirectedRequest,UnprocessableEntity,Locked,FailedDependency,UpgradeRequired,PreconditionRequired,TooManyRequests,RequestHeaderFieldsTooLarge,UnavailableForLegalReasons,InternalServerError,NotImplemented,BadGateway,ServiceUnavailable,GatewayTimeout,HttpVersionNotSupported,VariantAlsoNegotiates,InsufficientStorage,LoopDetected,NotExtended,NetworkAuthenticationRequired". at System.Management.Automation.LanguagePrimitives.ThrowInvalidCastException(Object valueToConvert, Type resultType) at System.Management.Automation.LanguagePrimitives.ConvertNoConversion(Object valueToConvert, Type resultType, Boolean recurse, PSObject originalValueToConvert, IFormatProvider formatProvider, TypeTable backupTable) at System.Management.Automation.LanguagePrimitives.ConversionData`1.Invoke(Object valueToConvert, Type resultType, Boolean recurse, PSObject originalValueToConvert, IFormatProvider formatProvider, TypeTable backupTable) at System.Management.Automation.LanguagePrimitives.ConvertTo(Object valueToConvert, Type resultType, Boolean recursion, IFormatProvider formatProvider, TypeTable backupTypeTable) at System.Management.Automation.Adapter.PropertySetAndMethodArgumentConvertTo(Object valueToConvert, Type resultType, IFormatProvider formatProvider) at System.Management.Automation.DotNetAdapter.PropertySet(PSProperty property, Object setValue, Boolean convertIfPossible) at System.Management.Automation.Adapter.BasePropertySet(PSProperty property, Object setValue, Boolean convert)

**Additional context**
Addressed issues in https://github.com/Azure/Azure-Sentinel/pull/2099. Customer is currently using this running the package from their own blob storage.

**Comment by j-d-harvey** [comment]
[https://github.com/Azure/Azure-Sentinel/pull/2099](url)

**Comment by sreedharande** [comment]
@j-d-harvey - Thanks for submitting PR. Your PR got approved.
