### ISSUE TITLE
Query syntax error BehaviorAnalytics'

### ISSUE THREAD

**Issue by AttilioDezzani** [Azure/Azure-Sentinel#2138]
Good morning, some interesting queries made available by azure sentinel give this error, I don't know how to fix.
Query syntax error. 'where' operator: Failed to resolve table or column expression named 'BehaviorAnalytics'.
Example of query 
Anomalous Activity Role Assignment
Anomalous Defensive Mechanism Modification
Anomalous RDP Activity
Thanks for help.

**Comment by shainw** [comment]
@AttilioDezzani - I tested the query and it works.  Do you have the BehaviorAnalytics table? 
![image](https://user-images.githubusercontent.com/45466083/116600884-ad61b580-a8de-11eb-814b-d4a4f1234f1c.png)

**Comment by AttilioDezzani** [comment]
@shainw how can i find this page?

**Comment by shainw** [comment]
@AttilioDezzani - this is in Log Analytics, you should see it in your workspace:
![image](https://user-images.githubusercontent.com/45466083/117342780-74828d00-ae58-11eb-92c9-965bc4779662.png)

**Comment by AttilioDezzani** [comment]
hi,


i see this

[cid:3cc75bd4-4865-4c65-91fd-7c62786ffc48]

________________________________
Da: Shain ***@***.***>
Inviato: giovedì 6 maggio 2021 19:48
A: Azure/Azure-Sentinel ***@***.***>
Cc: Dezzani Attilio ***@***.***>; Mention ***@***.***>
Oggetto: Re: [Azure/Azure-Sentinel] Query syntax error BehaviorAnalytics' (#2138)


This email is from an external Company. Be careful of attachments and links.


@AttilioDezzani<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FAttilioDezzani&data=04%7C01%7Cadezzani%40arcese.com%7Cd451cc1d2ce94587011308d910b72fa7%7Cf99b31d1d1f649f69d6c02e7c477563f%7C0%7C0%7C637559201234946502%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=L5Ny3pUpLNed14jwzNERBEm7bBmkM%2BFu2BIM7irX3ao%3D&reserved=0> - this is in Log Analytics, you should see it in your workspace:
[image]<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F45466083%2F117342780-74828d00-ae58-11eb-92c9-965bc4779662.png&data=04%7C01%7Cadezzani%40arcese.com%7Cd451cc1d2ce94587011308d910b72fa7%7Cf99b31d1d1f649f69d6c02e7c477563f%7C0%7C0%7C637559201234946502%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=9yhGXW5A4wIHZ%2FPksKGz9J2q5ZOJXqZKTVSgSwBjOKE%3D&reserved=0>

**Comment by shainw** [comment]
@AttilioDezzani - The image did not come thru in GitHub, can you post again?  If you don't see the table, then BehaviorAnalytics is not available to you.

https://docs.microsoft.com/en-us/azure/sentinel/enable-entity-behavior-analytics

Some further details - https://docs.microsoft.com/en-us/azure/sentinel/identify-threats-with-entity-behavior-analytics

**Comment by sarah-yo** [comment]
Closing as no response for some time, please raise another issue if this is still a problem, thanks!
