### ISSUE TITLE
Intune Data Connector in Sentinel

### ISSUE THREAD

**Issue by guidovbrakel** [Azure/Azure-Sentinel#2139]
I'm missing/would like to have a data connector for Intune in Sentinel

**Comment by sreedharande** [comment]
@guidovbrakel - If you'd like to request any connector that isn't part of existing connector list, we have this form you can fill in: https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbR-kibZAPJAVBiU46J6wWF_5URDZQSEtOMVlSQTdVTkFPU1BUR0ZWU1FJNC4u

Please follow the steps in this blog to connect your Intune/Endpoint Manager tenant to Azure Sentinel 
https://azurecloudai.blog/2020/07/02/connecting-intune-to-azure-sentinel/
