### ISSUE TITLE
Incorrect input, "ValidationFailed" when JSON parsing

### ISSUE THREAD

**Issue by JakeDerkowski96** [Azure/Azure-Sentinel#2141]
**Describe the bug**
The playbook fails to run becuase the JSON data is not correctly parsed 

**To Reproduce**
1. Deploy to Azure, in the desired workspace.
2. For an Azure Sentinel incident, I ran the playbook
3. "Run failed"
4. See error: ValidationFailed. The schema validation failed.

**Expected behavior**
Input JSON data should be in the same schema as the action of blocking the URL uses

**Screenshots**

![image](https://user-images.githubusercontent.com/45303650/114609169-1d780680-9c64-11eb-8682-3597c2f8f963.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 
 - Browser Edge
 - Version: 89.0.774.75 (Official build) (64-bit)

**Comment by sarah-yo** [comment]
@JakeDerkowski96 which playbook template is this?

**Comment by sarah-yo** [comment]
Closing due to lack of response. Please raise a fresh issue if you are still experiencing an issue with this. Thanks!
