### ISSUE TITLE
microsoft-logstash-azure-loganalytics - Potential memory leak? 

### ISSUE THREAD

**Issue by pbowness** [Azure/Azure-Sentinel#2145]
Running this plugin with Logstash 7.9.3.

The JVM runs out-of-memory. Heap dump shows a number of large byte and character arrays being retained that appear to contain text related to posting failures. Looking at the memory dump, both the byte buffers and char buffers contain:

"Exception in posting data to Azure Loganalytics.[..."

Perhaps there's a leak in how exception text is released? I was running a large configuration with 25 pipelines sending data.

This shows the memory containing the error message and the location at which it was allocated: 
![image](https://user-images.githubusercontent.com/19961065/114724952-11468480-9d0a-11eb-864e-96f25cc1d555.png)

A 45 MB buffer was allocated to contain the error text?

**Comment by NoamLandress** [comment]
Hi @pbowness, thanks for reaching out.
Could you please open a support ticket so we could continue handling this issue there?

Thanks!

**Comment by preetikr** [comment]
closing this as needs to be tracked as a support ticket
