### ISSUE TITLE
Playbook "GetVirusTotalFileInfo "Internal Server Error" on "Entities: Get FileHashes" action

### ISSUE THREAD

**Issue by wbarrett-cnb** [Azure/Azure-Sentinel#2149]
**Describe the bug**
The playbook hangs on the Get Filehashes action. Result code is 500 with a message "internal server error: Bad Gateway"

**To Reproduce**
Deploy Playbook
Select incident in sentinel with a file hash entity
run playbook from alerts tab "view playbooks"
click on playbook title to view progress
Wait for failure

**Expected behavior**
File hashes appear to be passed to the action from the "get entities" action above it, it should be able to parse the file hash from the received JSON and make it available as a file hash value in the File Hash Values array for following steps

**Screenshots**
![image](https://user-images.githubusercontent.com/82614625/114936925-f3ece580-9df1-11eb-9756-ce77c6da5b8d.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version 89

**Comment by dicolanl** [comment]
Hi @wbarrett-cnb 
Are you able to open a Microsoft support ticket?  this seems to be an issues with the Azure Sentinel connector / action.
