### ISSUE TITLE
User added to Azure Active Directory Privileged Groups fails: 

### ISSUE THREAD

**Issue by brohan** [Azure/Azure-Sentinel#2167]
When attempting to enable the included analytic query mentioned in the title one received the following error on the Set rule logic screen:

'where' operator: Failed to resolve column or scalar expression named 'displayName'.

**Comment by shainw** [comment]
@brohan - Thanks for letting us know.  Normally the unpacked values will be there, but the rule wizard appears to be using a short timeframe for validation against the data.  I am adding in a fix, you can fix this by adding in the following after this part.

```| evaluate bag_unpack(modProps)```
Add the following new line below the above
```| extend displayName = column_ifexists("displayName", "NotAvailable"), newValue = column_ifexists("newValue", "NotAvailable")```

The change is already included in PR #2229 and should be available in the UX within a couple weeks.

**Comment by shainw** [comment]
Closing as this is resolved.
