### ISSUE TITLE
Security Center Connector permission error

### ISSUE THREAD

**Issue by bowleg** [Azure/Azure-Sentinel#219]
![git](https://user-images.githubusercontent.com/21582257/62448155-0a0e5b80-b75f-11e9-9588-880efcfc0c2d.PNG)
I am having issues connecting Azure Security Center to the Sentinel solution. I have the correct permission Security Reader set on all my organisations subscriptions, My account has Global Administrator set in Azure AD and Security Admin and Reader set for Azure. In the attached image the only subscription I have permission to add the integration to is the one I am a owner of.

**Comment by shainw** [comment]
@bowleg - apologies for the delay in responding.  Many of us were out at Blackhat or on holiday.  Anyhow, for feature related issues, we would recommend posting to the Azure Sentinel Tech Community discussion as we want to mainly use the Github Issues section for items specific to creation of Dashboards, Detections, Hunting queries and so on, basically the content of Github.  In relation to this issue, this Community discussion may help - https://techcommunity.microsoft.com/t5/Azure-Sentinel/Least-Privilege-Permissions-on-Log-Analytics-Workspace-for-Azure/m-p/787504.  If not, then I would recommend starting a new conversation.
