### ISSUE TITLE
Can't create Analytics template for Exchange OAB Virtual Directory objects

### ISSUE THREAD

**Issue by Carter-ChenC** [Azure/Azure-Sentinel#2200]
**Describe the bug**
When creating the template of Analytics rule for the ExchangeOABVirtualDirectoryAttributeContainingPotentialWebshell, it will show the error message 'extend' operator: Failed to resolve scalar expression named '["@Name"]'.
Probably need an update for this page? (https://github.com/Azure/Azure-Sentinel/blob/master/Detections/SecurityEvent/ExchangeOABVirtualDirectoryAttributeContainingPotentialWebshell.yaml)

**To Reproduce**
1. Go to 'Analytics'
2. Click on 'Rule templates' then find "Exchange OAB Virtual Directory Attribute Containing Potential Webshell", click create rule
3. Direct to the Set rule logic

**Expected behavior**
Successful create this template.

**Screenshots**
At attachment.
![Analytics template](https://user-images.githubusercontent.com/83210873/116056624-96d61700-a6b0-11eb-9b2d-46d255ca0975.png)

Thanks for your help!

**Comment by shainw** [comment]
Fixed in #2191
