### ISSUE TITLE
nil response from RestClient causes 'undefined method `code' for nil:NilClass'

### ISSUE THREAD

**Issue by deepanshumarwah** [Azure/Azure-Sentinel#2214]
https://github.com/Azure/Azure-Sentinel/blob/ed54a0f3abc90326f3a99ec839c2104fd46c5cd8/DataConnectors/microsoft-logstash-output-azure-loganalytics/lib/logstash/logAnalyticsClient/logAnalyticsClient.rb#L25-L27

`response` can be `nil` here, leading to a scenario where the following is logged from the [microsoft-logstash-output-azure-loganalytics](https://github.com/Azure/Azure-Sentinel/blob/ed54a0f3abc90326f3a99ec839c2104fd46c5cd8/DataConnectors/microsoft-logstash-output-azure-loganalytics/lib/logstash/logAnalyticsClient/logStashAutoResizeBuffer.rb#L78-L87) plugin when `is_successfully_posted(response)` is called and [is_successfully_posted](https://github.com/Azure/Azure-Sentinel/blob/ed54a0f3abc90326f3a99ec839c2104fd46c5cd8/DataConnectors/microsoft-logstash-output-azure-loganalytics/lib/logstash/logAnalyticsClient/logStashAutoResizeBuffer.rb#L138-L140) attempts to evaluate `response.code`
from logstash:

```bash
[ERROR][logstash.outputs.azureloganalytics][pipeline-common][pipeline_common_output_azure_log_analytics_ingest] Exception occured in posting to DataCollector API as log type ExampleLogType: 'undefined method `code' for nil:NilClass', data=>[{"original_timestamp":"2021-04-15T10:36:21.315Z","event_uuid":"ede25ed2-0d3e-4898-8c5d-3...
```

There appears to be a related issue logged at rest-client/rest-client#655

**Comment by NoamLandress** [comment]
Hi @deepanshumarwah, thanks for reaching out.
Could you please open a support ticket so we could continue handling this issue there?

Thanks!

**Comment by deepanshumarwah** [comment]
Hi @NoamLandress 
Where can I open the support ticket. Can you please guide me to the portal ?

**Comment by Lodewyk-Git** [comment]
Hi @deepanshumarwah,

https://azure.microsoft.com/en-us/support/create-ticket/

**Comment by deepanshumarwah** [comment]
adding @lukiffer to the issue

**Comment by preetikr** [comment]
Closing this for tracking as support ticket
