### ISSUE TITLE
Error creating rule - User added to Azure Active Directory Privileged Groups

### ISSUE THREAD

**Issue by anfisher1967** [Azure/Azure-Sentinel#2219]
When I try to create the analytics rule in a new Sentinel instance - User added to Azure Active Directory Privileged Groups, there is a red dot over Set rule logic and an error shows up at the bottom of the KQL window that says 'where' operator: Failed to resolve column or scalar expression named 'displayName'

**Comment by shainw** [comment]
@anfisher1967 - please see #2167

**Comment by shainw** [comment]
Fix released, closing.
