### ISSUE TITLE
Error creating rule  - SUNBURST network beacons

### ISSUE THREAD

**Issue by anfisher1967** [Azure/Azure-Sentinel#2220]
When trying to create the rule SUNBURST network beacons, I get an error that says "One or more entity mappings have been defined under the new version of Entity Mappings. These will not appear in the query code. Any entity mappings defined in the query code will be disregarded."

**Comment by shainw** [comment]
@anfisher1967 - Thanks for the feedback.  This has been fixed in #2159 and some others have been fixed in #2226
