### ISSUE TITLE
Azure AD Sign-In logs workbook suddenly doesn't work right.

### ISSUE THREAD

**Issue by anfisher1967** [Azure/Azure-Sentinel#2225]
Usually when you open the AAD sign-in logs workbook,  you click on the box on the left hand side to say which country you want to select which then changes the users in the right hand side to be the users logging in from that country. Now that is not working.

**Comment by shainw** [comment]
@anfisher1967 - Can you share a screenshot of what you are seeing?  I may not be looking at the right thing, but I am not seeing an issue. :)

**Comment by anfisher1967** [comment]
So normally the Location Sign-in details on the right changes depending on what row I pick in Sign-in by location box on the left.

If I pick US, it should show me all the users who sign in from the US in that Location Sign-in details box.

If I pick RU, it should change and show me all the users who tried to sign in from Russia in that Location Sign-in details box.

Now, no matter what I pick the box on the right never changes.

Does that make sense?

[cid:a1e5aa0f-9e78-4398-9eab-d3fc268636b0]

________________________________

**Comment by shainw** [comment]
Ah, so you mean when you select from the table called "Sign-ins by Locations" (with red arrow) and choose a country, it filters the Location Sign-in Details table (blue circle).  I will have to check with the author on this one, I don't have context on what it did before, however, the workbook was updated 10 days ago.  @liatlishams and @Amitbergman - thoughts here?
![image](https://user-images.githubusercontent.com/45466083/116632046-0d6e5100-a90b-11eb-818d-a8a245fde008.png)

**Comment by anfisher1967** [comment]
Exactly! That's the main value of the workbook. They added that drop down that lets you pick between sign in logs and non interactive logs and I think that's when it broke.

On Apr 29, 2021, at 7:54 PM, Shain ***@***.***> wrote:

﻿

Ah, so you mean when you select from the table called "Sign-ins by Locations" (with red arrow) and choose a country, it filters the Location Sign-in Details table (blue circle). I will have to check with the author on this one, I don't have context on what it did before, however, the workbook was updated 10 days ago. @liatlishams<https://github.com/liatlishams> and @Amitbergman<https://github.com/Amitbergman> - thoughts here?
[image]<https://user-images.githubusercontent.com/45466083/116632046-0d6e5100-a90b-11eb-818d-a8a245fde008.png>

**Comment by anfisher1967** [comment]
Shain - did this get fixed? It still doesn't seem to be working right.

On Apr 29, 2021, at 7:54 PM, Shain ***@***.***> wrote:

﻿

Ah, so you mean when you select from the table called "Sign-ins by Locations" (with red arrow) and choose a country, it filters the Location Sign-in Details table (blue circle). I will have to check with the author on this one, I don't have context on what it did before, however, the workbook was updated 10 days ago. @liatlishams<https://github.com/liatlishams> and @Amitbergman<https://github.com/Amitbergman> - thoughts here?
[image]<https://user-images.githubusercontent.com/45466083/116632046-0d6e5100-a90b-11eb-818d-a8a245fde008.png>

**Comment by shainw** [comment]
The fix is in place for this and should be available in Azure Sentinel UX in the next 2 weeks.  Thanks for the feedback.

**Comment by sarah-yo** [comment]
Fix put in place for issue
