### ISSUE TITLE
Microsoft Security Incidents don't show as in use

### ISSUE THREAD

**Issue by anfisher1967** [Azure/Azure-Sentinel#2259]
I enabled the rules entitled "Create incidents based on" Azure AD Identity Protection, MCAS, etc.  They all should show as IN USE (see in use) but they do not for some reason (see enabled rules).

![EnabledRules](https://user-images.githubusercontent.com/33937240/117364817-60f11980-ae8c-11eb-9dfd-94cc1e25e556.JPG)
![InUse](https://user-images.githubusercontent.com/33937240/117364819-6189b000-ae8c-11eb-94a2-c92b2732c025.JPG)

**Comment by Lodewyk-Git** [comment]
Hi @anfisher1967, this sometimes takes a while to display. Is it displaying in use now?

**Comment by anfisher1967** [comment]
I've set up Analytics rules at 50 different customers in the past two months. Perhaps you're right and they take a while to show up but the "Create" rules are the only ones with that behavior and what often happens is that the customer enables the rules multiple times because it doesn't show as In Use. Sometimes they have three of four duplicates of the same rule. I think it's an issue that needs to be fixed.

On May 13, 2021, at 7:59 PM, Lodewyk-Git ***@***.***> wrote:

﻿

Hi @anfisher1967<https://github.com/anfisher1967>, this sometimes takes a while to display. Is it displaying in use now?

**Comment by sarah-yo** [comment]
Hi @anfisher1967, please can you raise a support ticket for this via the Azure Portal, as it appears to be a bug in the Sentinel UI and not with the logic of an analytics rule (we can only deal with the content of analytics rules, workbooks, hunting queries and playbooks). Thanks!
