### ISSUE TITLE
ZScaler CEF logs contain unescaped pipes, breaking Azure log collectors

### ISSUE THREAD

**Issue by DeepMac** [Azure/Azure-Sentinel#2262]
**Describe the bug**
ZScaler NSS Web log entries where a URL contains pipe (|) characters get sent to a Linux-based syslog server. Microsoft's CEF collector mis-interprets these unescaped pipe signs as CEF field delimiters, and does not correctly populate the CommonSecurityLog entry for the event. Fidelity of the events is thus lost.

**To Reproduce**

1. Set-up a Zscaler environment
2. Forward ZScaler NSSWebLog entries to a Linux-based syslog server
3. Install Microsoft CEF collector on the syslog server, forwarding to a Sentinel environment
4. Generate webserver/webbrowser traffic for the ZScaler environment, preferably involving noisy websites with many ads (i.e. Yahoo portals)
5. Observe logs on syslog server for any CEF entries with pipe signs in a URL. Example:
request=nym1-ib.adnxs.com/vevent?an_audit=0&referrer=https://mail.yahoo.com&e=wqT_3QK0DPDtNAYAAAMA1gAFAQjfwMWEBhCh39eUtO-1xxAYr7y36JOhvodaKjYJuL9E8-ew_j8RzJdDviip-T8ZAAAAANejGkAh2tjyuBJr_j8p_-xHisgwAkAxAAAAwMzM9D8w8N7UCTiQW0DDR0gCUOivqX1Y-NOOAWAAaKDCpwF4r6wFgAEBigEDVVNEkgEDVVNEmAGsAqAB-gGoAQGwAQC4AQLAAQXIAQLQAQnYAQDgAQDwAQCKApYBdWYoJ2EnLCAyNTAyNDI4LCAxNjIwMTQwMTI3KTt1ZignaScsIDUyNDE4NTcsIDE2MjAxNDAxMjcpOwEdLGcnLCAxMzU1MzIwMEY7ADBzJywgMjU2ODk3ODQ2Rh8AAHIBHxw2MjgyMTg2NDYfAPCQkgLVBSFFNURsbndpWHV2Y1dFT2l2cVgwWUFDRDQwNDRCTUFBNEFFQUFTTU5IVVBEZTFBbFlBR0RQQW1nQWNBaDR2S0FPZ0FIR0FZZ0JtQmlRQVFHWUFRR2dBUUdvQVFHd0FRQzVBYXFkaWdQSU1BSkF3UUdxbllvRHlEQUNRTWtCQUFBQUFBQUE4RF9aQVFBQQUPdFBBXzRBR0ItTDhDOVFFN2hpRkFtQUlBb0FJQnRRSQUjAHYNCPCGd0FJWXlBS2tHTkFDT3RnQ21CamdBZ0RvQWdENEFnQ0FBd0dZQXdHaUF3NElfOXpwRXhBQkdBSXRBQURnUUtJRERnal8zT2tURUFJWUFpMEFBT0JBb2dNT0NQX2M2Uk1RQ3hnQ0xRQUE0RUM2QXdsT1dVMHlPalEyTURuZ0E3RXI2UU1BQUFBBZRIQVBBRC1FeUFCTmpjLXdXSUJOdgEI8EZRQkFHWUJBR3lCQW9JdnI2WUFSRGZpX0FNc2dRS0NMX0d6d1lRMzR2d0RMSUVDZ2lYb3RRR0VOLUw4QXk2QkNRSW5na1JBQQljDDBEOFoJCgUBAGcFUDxTQ194czhHSUplaTFBYkJCBRsgQUFBTkFfeVFRAQoJARhOZ0VCUEVFCQ0BAVhDSUJZRWtrQVhtOVQyWUJiYm12M3FwQhEzFFBBX3NRVQEpCQEITUVGCQkUQUFIRURKBSgcRUFsajlVXzAuKAAETmsVKMA4RF9nQmJid0RmQUZzSnk3QnZnRm5ONllBWUlHQTFWVFJJZ0dCSkFHQVpnR0FLRUdBEWEoQUNvQmdTeUJpUUoVEwRBQTUICEFBQS4IAQBoAREJATxDNEJnby6aAokBIWxSRDJVOtkCLC1OT09BU0FBS0FBeAkxBQFMNkNVNVpUVEk2TkRZd09VQ3hLMGsFGRRBQUR3UDE9NABGERgMQUFBRxEYDERRUDIdGABIERghKvCkZ0HYAgDgAobXWeoCFmh0dHBzOi8vbWFpbC55YWhvby5jb22AAwCIAwGQA-b1PZgDFKADAaoDAMADrALIAwDYA5yfJOADAOgDAPgDA4AEAJIECS9vcGVucnRiMpgEAKIEDDEzNi41Ni4xMDQuMKgE74IUsgQMCAAQABgAIAAwADgCuAQAwAQAyAQA0gQOOTE1NSNOWU0yOjQ2MDnaBAIIAeAEAPAEgekgiAUBmAUAoAX_EQGoAaoFIDg2ZDU0YzYzYjU0YzQ4NzM5ZDc2MDE0ZDRiNzU4ODViwAUAyQUAAAECFPA_0gUJCQEKAQFo2AUB4AUB8AUL-gUECAAQAJAGAJgGALgGAMEGAR8wAADwP9AGmS_aBhYKEAkRGQFcEAAYAOAGAfIGAggAgAcBiAcAoAcBugcPAUgAGAnWLO8eQADIB6-sBdIHDRV0ATgI2gcGCSc04AcA6gcCCADwB5Xn8gM.&s=10ab3ad0c60c9f44231423bc2b07127b76b9e98b&type=nv&nvt=5&jm=1140|1141|1143|1003&sid=7565120271712493203&vd=ct~0|rr~0&sv=207&tv=view7-1js&ua=chrome5
6. Review CommonSecurityLog events to see if the activity was properly consumed. When the error occurs, events will either be missed, or have incorrect/invalid field values for DeviceVendor, DeviceModel and similar fields.

**Expected behavior**
CEF logs with improper escaping of URL values will be fully parsed as a single field and stored in the CommonEventLog correctly.

Screenshot:
![zss-cef-fail](https://user-images.githubusercontent.com/4560942/117477524-158e4800-af2c-11eb-8cec-c37171d761d3.png)

**Additional context**

**Comment by v-jayakal** [comment]
@DeepMac , can you give entire message (few samples if you can) for analysis please? Thanks.

**Comment by v-jayakal** [comment]
@DeepMac, thank you.

**Comment by v-jayakal** [comment]
Assigning to @NoamLandress for further action. Thanks.

**Comment by sarah-yo** [comment]
Being worked on as an ICM ticket, closing Github issue
