### ISSUE TITLE
Typo in analytic rules

### ISSUE THREAD

**Issue by anfisher1967** [Azure/Azure-Sentinel#2288]
Analytic rule - MFA disabled for a user has a typo

Description
Multi-Factor Authentication (MFA) helps prevent credential compromise. This alert identifies when an attempt has been made to diable MFA for a user

Should be disable no diable

**Comment by Lodewyk-Git** [comment]
Hi @anfisher1967, this problem is fixed, please see https://github.com/Azure/Azure-Sentinel/blob/master/Detections/MultipleDataSources/MFADisable.yaml
