### ISSUE TITLE
In the Infoblox NIOS kusto funtion to parse data, can´t get the data correctly to DNS client resolution

### ISSUE THREAD

**Issue by sorcia25** [Azure/Azure-Sentinel#2296]
I created the Kusto Funtion to parse the Syslog data of my Infoblox, but when I search in the LogAnalytics can´t find any info about the DNS client resolution, no port, no QueryDomainName, no RecordType... nothing.

From Syslog I get this kind of SyslogMesagge: 

![image](https://user-images.githubusercontent.com/50998375/118341771-012aec00-b4e6-11eb-8c7a-868278ed255e.png)

But when I run the Funtion, I got this result (where all the data about the client resolutions is missing:

![image](https://user-images.githubusercontent.com/50998375/118341858-64b51980-b4e6-11eb-909f-3d499d3511ff.png)

What am I doing wrong?

**Comment by Lodewyk-Git** [comment]
Hi @sorcia25, is the data you're trying to display outside of the timerange? I remember ina recent threat hunting webinar the problem had something to do with the data being too old to display. Video [here](https://youtu.be/QaUxdtNfbd8?t=1965).

**Comment by v-jayakal** [comment]
@sorcia25 , Can you give us few sample logs that we can copy and use for the data extraction using parser? Thanks.

**Comment by elforb** [comment]
Hi,

The format of the provided sample data does not match the format expected by the regular expression from the `dnsclient` function you'd shown.
> Ex. See test regexr.com/5tpf8

Why is the log format different than what's expected by the parser here?

**Comment by sorcia25** [comment]
Hi @elforb thats the format that the Infoblox admin send us the data to the Sentinel.

So i'll ned to ask to the Infoblox admin that send the data in what kind of format?... becouse in the funtion comments we just can see a zone transfer event (or some like that), it's don't have a DNS query event...

**Comment by elforb** [comment]
Hi, 

I do not know the exact format, but the pieces missing in the current data are the `View` and `Response` portions.

**Comment by v-jayakal** [comment]
@sorcia25 , as per the documentation provided in connector, https://www.infoblox.com/wp-content/uploads/infoblox-deployment-guide-slog-and-snmp-configuration-for-nios.pdf (Page 23) , message should be in the format as given in the parser with format, example: May 13 12:05:52 10.0.0.0 dhcpd[30174]: DHCPDISCOVER from 0a:0b:0c:0d::0f via eth2 TransID 5daf9374: network 10.0.0.0/24: no free leases.
As per the above message you provided, it seems you have the data, but it is not storing in LA in this format, Can you please confirm that? Thanks.

**Comment by sorcia25** [comment]
Hi @v-jayakal . That's correct, the message that we have in LA isn't in that format... as @elforb says, the message doesn't have the View and Response portions... I'm trying to ask to the Infoblox admin to send the messages in correct format, but I thing that the PDF provided in the documentation connector isn't enought :(

**Comment by v-jayakal** [comment]
@sorcia25 , As you are trying to find the reason for missing view and response portions, can you try and find out why the syslogmessage does not have entire message "May 25 10:24:03 192.168.1.200 named[11464]: client @0x7fc33c4ccec0 192.168.5.20#50884 (api-partner.spotify.com): query: api-partner.spotify.com IN A + (192.168.1.200)"?

**Comment by elforb** [comment]
@sorcia25 We've raised a PR with a potential fix for the DNSClient portion of the parser. Could you check and validate functionality? See #2465

**Comment by elforb** [comment]
@sorcia25 Could you please review the PR posted above and validate that it resolves your issue?

**Comment by v-jayakal** [comment]
@sorcia25 - Any luck? Please let us know, Thanks.

**Comment by v-maudan** [comment]
@sorcia25 , Can you please check and let us know [#2465](https://github.com/Azure/Azure-Sentinel/pull/2465).  Please feel free to reopen this issue.
