### ISSUE TITLE
AAD Audit Logs workbook not parsing the Service Principal ID

### ISSUE THREAD

**Issue by OvidiuCatalan** [Azure/Azure-Sentinel#2314]
**Describe the bug**
https://github.com/Azure/Azure-Sentinel/blob/master/Workbooks/AzureActiveDirectoryAuditLogs.json

AAD workbook is parsing only the User Principal name, however there are many cases where changes are being done by a Service Principal ID. 

The query is checking if the User Principal is not null, otherwise puts "unknown" for everything else. This is causing the workbook to show "unknown" for most of the cases (example below 126 Update User changes, 118 marked as Unknown)

**Expected behavior**
Instead of parsing the SP as unknown, the ID should be displayed.

**Screenshots**
![image](https://user-images.githubusercontent.com/84498946/118941980-f85d6e80-b95a-11eb-9aac-9c4fb07249fe.png)
![image](https://user-images.githubusercontent.com/84498946/118942001-fc898c00-b95a-11eb-95e6-14d4226a0141.png)
![image](https://user-images.githubusercontent.com/84498946/118942009-00b5a980-b95b-11eb-956e-6948326562fa.png)

**Comment by v-amolpatil** [comment]
Hi @OvidiuCatalan, thank you for flagging this. Apologies for the delayed response. If you still need assistance, please reply here within 5 business days.

**Comment by v-amolpatil** [comment]
Hi @OvidiuCatalan, Gentle Reminder: We are awaiting for your response on this issue. If you still need to keep this issue active please respond within next 2 days. If we don't receive response by 8 Feb 2023, we will close this issue.

**Comment by v-amolpatil** [comment]
Since we have not received a response in the last 5 days, we are closing your issue #2314 as per our standard operating procedures. If you still need support for this issue, feel free to re-open at any time. Thank you for your co-operation.
