### ISSUE TITLE
Analytics rule "User added to Azure Active Directory Privileged Groups" not working as intended

### ISSUE THREAD

**Issue by mikoiv** [Azure/Azure-Sentinel#2319]
Analytics rule "User added to Azure Active Directory Privileged Groups": the rule is supposed to alert from a specific list of groups set with the "let PrivilegedGroups" statement in the query. But the actual Where operator that would match the list is commented out, so the rule does not work as intended.

https://github.com/Azure/Azure-Sentinel/blob/master/Detections/AuditLogs/UseraddedtoPrivilgedGroups.yaml

**Comment by Lodewyk-Git** [comment]
Please know that it's commented out, because you have to fill in the let with the privileged groupnames in the org/company that you're monitoring.
