### ISSUE TITLE
Data between Sentinel and Logic App not the same

### ISSUE THREAD

**Issue by Lodewyk-Git** [Azure/Azure-Sentinel#2340]
I was playing around with a Playbook, so I set up an Analytical rule to trigger it every five minutes, before testing it using the automation rule I changed the description of the analytical rule, but in my email the description was unchanged, thus leaving me to believe that the Get Incident flow, or something, is not working correctly.

The automation rule that takes all high severity Incidents and runs the playbook
The email gets the AlertName and Description from the GetIncident flow

### Screenshots
**Email**
![image](https://user-images.githubusercontent.com/36856692/119377694-b23b3e80-bcbd-11eb-82d2-21f13e5671ea.png)
**Sentinel**
![image](https://user-images.githubusercontent.com/36856692/119378009-08a87d00-bcbe-11eb-9da1-b5f43cedf89d.png)
**Logic App**
![image](https://user-images.githubusercontent.com/36856692/119378277-60df7f00-bcbe-11eb-963e-abe9b00082f9.png)

**Comment by Lodewyk-Git** [comment]
Is this the right place to post this or should I open an issue at https://github.com/Azure/logicapps/issues?

**Comment by sreedharande** [comment]
@Lodewyk-Git - This is the correct forum
