### ISSUE TITLE
Carbon Black Connector

### ISSUE THREAD

**Issue by jaroslavkozak** [Azure/Azure-Sentinel#2360]
**Describe the bug**
The events and the notification are not being ingested

**To Reproduce**
The connector was set as described. I can see in Azure that the function is reaching reached out to Carbon Black API. It says connection was successful. No data were retrieved. Carbon Black console also shows the API had successful connection.

However, it is capable to upload only audits logs related to logins to the portal. The events and notifications are not being collected.

**Screenshots**
![image](https://user-images.githubusercontent.com/60477762/119701491-a1034680-be11-11eb-8015-183d35625fa0.png)

![image](https://user-images.githubusercontent.com/60477762/119701741-f0497700-be11-11eb-8446-277c79234eeb.png)

**Comment by v-jayakal** [comment]
@jaroslavkozak , as per the screenshot, there are no events and notifications, hence data is not inserted. Do you have the details of the event and notification URLs for CarbonBlack that returns the data at your end? Can you try to get the data at your end with events and notification URLs using testing tool like Postman? I am also attaching a script that can be used for testing the CarbonBlack API, you can use this to debug and find out the URLs and their return values. Please furnish values for hostname, apiSecretKey, apiId, SIEMapiKey and SIEMapiId to get this running. After run, please let us know the result - if the API is returning the data, and not ingested in the azure function, we can delve further. Thanks.
[TestAPICarbonBlack.ps1.txt](https://github.com/Azure/Azure-Sentinel/files/6559304/TestAPICarbonBlack.ps1.txt)
Note: As the ps1 extension is not supported, it has been converted to txt. Please remove ".txt" extension to turn it into Powershell script for debugging.

**Comment by v-jayakal** [comment]
@jaroslavkozak , were you able to run the script? Are you getting events now? Let us know if you need help. Thanks.

**Comment by jaroslavkozak** [comment]
Hi, I apologize for the delay. The issue turned out to be missing Notification settings for APIs in Carbon Black. Thank you all for your input.
