### ISSUE TITLE
Feed "VPS_Networks.csv" incorrect network

### ISSUE THREAD

**Issue by t0sc4n** [Azure/Azure-Sentinel#2365]
**Describe the bug**
The feed VPS_Networks.csv has an incorrect IPv4 network at the last lines (usually a closed square parenthesis is appended). 
The feed is incorporated in the Sentinel "Signins From VPS Providers" query which try to parse all the networks in the feed, then ignoring the last address.

**To Reproduce**
1. Go to 'https://raw.githubusercontent.com/Azure/Azure-Sentinel/master/Sample%20Data/Feeds/VPS_Networks.csv'
2. Scroll down to the last line

**Expected behavior**
All IPv4 subnets should be valid

**Screenshots**
![feed_error](https://user-images.githubusercontent.com/84924605/119858086-6cc47e80-bf14-11eb-8423-0aca634124c5.png)

**Comment by shainw** [comment]
@petebryan - can you take a look a this.

**Comment by petebryan** [comment]
Thanks @t0sc4n - this is fixed in https://github.com/Azure/Azure-Sentinel/pull/2406
