### ISSUE TITLE
Auto Refresh refreshes when performing actions

### ISSUE THREAD

**Issue by Lodewyk-Git** [Azure/Azure-Sentinel#2372]
**Describe the solution you'd like**
When AutoRefresh is on and I select Incidents it sometimes AutoRefreshes and I lose the incidents that I was working with, so If I decided against applying the actions, I will have to reselect the Incident that I was working with.

**Describe alternatives you've considered**
Incidents should not be auto-refreshed while performing actions on specific data

**To Test**
Go to Incidents
Select a few Incidents 
Click Actions
Wait for the Incidents to AutoRefresh
Click Cancel and notice that no Incidents are selected

**Comment by shainw** [comment]
@Lodewyk-Git - thanks for sharing your experience.  Let me get this info to one of the PMs to look at.

**Comment by shainw** [comment]
@Ronmarsiano - Cleaning up stale issues and wondering if the PM team looked into this.
