### ISSUE TITLE
I want to close all informational incidents 

### ISSUE THREAD

**Issue by nellorelion** [Azure/Azure-Sentinel#2390]
i have thousands of informational incident in new soc and i want to close them all. so concentrate more on high, medium and low one.

can any one can help with logic

**Comment by isurusam** [comment]
@nellorelion Are they still coming? Or you want to close old incidents?

**Comment by sarah-yo** [comment]
@nellorelion you could create an automation rule that would do this, it would be the easiest way to do this:

![image](https://user-images.githubusercontent.com/50611022/123374377-29286780-d5db-11eb-9053-2bffd3274e49.png)
