### ISSUE TITLE
Update required for Azure Sentinel Infoblox NIOS parser?

### ISSUE THREAD

**Issue by oniled** [Azure/Azure-Sentinel#2408]
**Describe the bug**
I can confirm I am receiving Infoblox logs in Azure Log Analytics and Azure Sentinel.  However the parser is not correctly parsing a lot of the logs.  Guessing the parser may need an update?

Others have reported similar issues and the problem is not the format of the data or receiving the data, as both of those have been verified.  I am getting partial/no parsing by the parser is the problem.

**To Reproduce**
1. Setup Syslog server to forward logs to Azure Log Analytics
2. Setup Kusto Function named InfobloxNIOS based on this documentation: https://aka.ms/sentinelgithubparsersinfoblox

**Expected behavior**
Full parsing of the syslogs

**Screenshots**

![image](https://user-images.githubusercontent.com/8421682/120858380-90e91680-c537-11eb-9992-99328f217684.png)

![image](https://user-images.githubusercontent.com/8421682/120858362-89c20880-c537-11eb-92ff-a95afb19c902.png)

**Additional context**

sample syslog that is not being parsed: 

Jun  4 12:20:09 130.191.200.2 dhcpd[7625]: DHCPACK on 10.130.17.107 to b6:57:72:77:93:cc via eth2 relay 10.130.255.254 lease-duration 28727 (RENEW) uid 01:b6:57:72:77:93:cc

**Comment by oniled** [comment]
Records of other having same problem:

https://www.gitmemory.com/issue/Azure/Azure-Sentinel/2296/849183343

**Comment by elforb** [comment]
Hi @oniled,

I have a potential fix for this created at #2547 , could you review and confirm it solves your issue?

**Comment by oniled** [comment]
This looks pretty good for the DHCPAck but maybe need work to correct "r-l-e" and "client"?  Not seeing those parse correctly.  
![image](https://user-images.githubusercontent.com/8421682/124041564-f0fa9d80-d9bb-11eb-8cf2-733857833e5f.png)
![image](https://user-images.githubusercontent.com/8421682/124041575-f821ab80-d9bb-11eb-943e-176e4ea31517.png)

**Comment by v-maudan** [comment]
> This looks pretty good for the DHCPAck but maybe need work to correct "r-l-e" and "client"? Not seeing those parse correctly.
> ![image](https://user-images.githubusercontent.com/8421682/124041564-f0fa9d80-d9bb-11eb-8cf2-733857833e5f.png)
> ![image](https://user-images.githubusercontent.com/8421682/124041575-f821ab80-d9bb-11eb-943e-176e4ea31517.png)

@oniled  Can you paste "r-l-e" and "client" log type sample records. You can remove any sensitive details such as IP, computer name etc. Thanks!

**Comment by oniled** [comment]
sure, sample logs

client

client @0x7fecda73dc30 255.255.255.255#45764 (scontent-lax3-1.cdninstagram.com): query: scontent-lax3-1.cdninstagram.com IN A + (256.256.256.1)

r-l-e

r-l-e:10.130.110.255,Renewed,Tone,22:b4:77:55:f9:b1,1625169071,1625197871,,No Match$default,10.130.0.0,16,10.130.1.1-10.130.254.245

**Comment by v-maudan** [comment]
> sure, sample logs
> 
> client
> 
> client @0x7fecda73dc30 255.255.255.255#45764 (scontent-lax3-1.cdninstagram.com): query: scontent-lax3-1.cdninstagram.com IN A + (256.256.256.1)
> 
> r-l-e
> 
> r-l-e:10.130.110.255,Renewed,Tone,22:b4:77:55:f9:b1,1625169071,1625197871,,No Match$default,10.130.0.0,16,10.130.1.1-10.130.254.245

@oniled ,  Can you please test attached parser and let me know if you still face any issue. Thanks!
[TestInfobloxNIOS.txt](https://github.com/Azure/Azure-Sentinel/files/6791618/TestInfobloxNIOS.txt)

**Comment by v-maudan** [comment]
@oniled , Can you please check provided parser. Thanks!

**Comment by oniled** [comment]
Hi - the r-l-e parser populates the Network field.  

![image](https://user-images.githubusercontent.com/8421682/126022604-86044933-33c9-4ea6-a8a3-617574882cc6.png)

client only populates the Message field

![image](https://user-images.githubusercontent.com/8421682/126022610-fcc2fb09-f85f-4e00-bbd6-41bf9e67bce2.png)

**Comment by v-maudan** [comment]
> Hi - the r-l-e parser populates the Network field.
> 
> ![image](https://user-images.githubusercontent.com/8421682/126022604-86044933-33c9-4ea6-a8a3-617574882cc6.png)
> 
> sample message: r-l-e:146.244.137.240,Renewed,COMPUTERNAME01,e4:b9:7a:ec:69:b9,1626488322,1626488922,113,$default,146.244.137.0,24,146.244.137.1-146.244.137.250
> 
> client only populates the Message field
> 
> ![image](https://user-images.githubusercontent.com/8421682/126022610-fcc2fb09-f85f-4e00-bbd6-41bf9e67bce2.png)
> 
> sample message: client @0x7fa58d1c1130 130.191.170.100#33630 (125.170.191.130.in-addr.arpa): query: 125.170.191.130.in-addr.arpa IN PTR + (130.191.1.1)

@oniled , I verified parser as per given sample data, it is parsing successfully. [PFB screenshot for reference]
can you please check columns specified in parser.  If you still having issue, please let me know. Thanks!

1. r-l-e parser : check columns [Dest_IP,Signature,DNS_Hostname,Dest_MAC_Address,StartTime,EndTime,Network,NetworkRange][PFB screenshot for reference]
![image](https://user-images.githubusercontent.com/75478517/126112659-d9edd923-487d-4cb4-a657-2c5754facd01.png)

2. Client Parser: Check specified columns in parser. [Client_IP,Port ,Protocol ,QueryDomainName ,Message ,Flag ,ResponseCode]
![image](https://user-images.githubusercontent.com/75478517/126114120-d3eeff31-31c4-4e39-be89-8644b69177ed.png)

**Comment by v-maudan** [comment]
@oniled, Can you please check and confirm on this? Thanks!

**Comment by oniled** [comment]
i can confirm its working, thanks for all your help :)
