### ISSUE TITLE
Suggested guidance update

### ISSUE THREAD

**Issue by takhoshi** [Azure/Azure-Sentinel#2425]
**Is your feature request related to a problem? Please describe.**
**CR files get corrupt if they are individually downloaded on browser.** 

**Describe the solution you'd like**
**Update the document to make sure download files in the repo in Zip or with Github Desktop to avoid CR corruptions** 

**Describe alternatives you've considered**

**Additional context**

**Comment by takhoshi** [comment]
https://github.com/Azure/Azure-Sentinel/tree/master/Solutions/SAP/CR

**Comment by v-amolpatil** [comment]
Hi @takhoshi , thank you for flagging this. Apologies for the delayed response. If you still need assistance, please reply here within 5 business days.

**Comment by v-dvedak** [comment]
Since we have not received a response in the last 5 days, we are closing your issue #<2425> as per our standard operating procedures. If you still need support for this issue, feel free to re-open at any time. Thank you for your co-operation.
