### ISSUE TITLE
Ubiquiti Conf Error in OMSAgent Log

### ISSUE THREAD

**Issue by mburrough** [Azure/Azure-Sentinel#2438]
**Describe the bug**
When using the Ubiquiti connector conf with a Linux OMS Agent, the following error is logged in the omsagent.log:
```
[warn]: parameter 'delimiter' in <source>
  type udp
  format none
  port 20514
  bind 0.0.0.0
  delimiter

  tag oms.api.Ubiquiti
</source> is not used.
```

**To Reproduce**
1. Install the OMS Agent on Linux and connect to workspace
2. Install the Ubiquiti.conf file from [](https://raw.githubusercontent.com/Azure/Azure-Sentinel/master/Solutions/Ubiquiti/Data%20Connectors/la_agent_configs/ubiquiti.conf)
3. Update the .conf file per the directions to specify workspace ID
4. Restart omsagent
5. Check omsagent.log and note error

**Expected behavior**
No error occurs

**OMS Host Info:**
 - Device:Linux VM (non-Azure)
 - OS: Debian 10

**Comment by v-amolpatil** [comment]
Hi @mburrough, thank you for flagging this. Apologies for the delayed response. If you still need assistance, please reply here within 5 business days.

**Comment by v-amolpatil** [comment]
Since we have not received a response in the last 5 days, we are closing your issue #2438 as per our standard operating procedures. If you still need support for this issue, feel free to re-open at any time. Thank you for your co-operation.
