### ISSUE TITLE
Error deploying playbook: Incident-Status-Sync-To-WDATP

### ISSUE THREAD

**Issue by genemecija** [Azure/Azure-Sentinel#2463]
**Describe the bug**
An error is encountered after attempting to deploy the "Incident-Status-Sync-To-WDATP" playbook:
> There was an error downloading the template from URI 'https://raw.githubusercontent.com/Azure/Azure-Sentinel/master/Playbooks/Block-AADUser/azuredeploy.json'. Ensure that the template is publicly accessible and that the publisher has enabled CORS policy on the endpoint. To deploy this template, download the template manually and paste the contents in the 'Build your own template in the editor' option below. 

**To Reproduce**
1. Go to https://github.com/Azure/Azure-Sentinel/tree/master/Playbooks/Incident-Status-Sync-To-WDATP
2. Click on "Deploy to Azure"
3. See error

**Expected behavior**
The playbook deploys to Azure Sentinel.

Tagging author: @mahelsay

**Comment by mahelsay** [comment]
HI @genemecija, i have just checked and it surprisingly worked fine! tried to research it and found many others have reported same behaviour in other playbooks as well.
could you please try again ?

**Comment by genemecija** [comment]
Hi @mahelsay,

I've discovered the issue was due to an explicitly defined value within the "location" field of the playbook configuration. I've created Pull Request #2549 to remediate this issue. Once the PR is merged, this issue can be closed.

**Comment by mahelsay** [comment]
Thank you @genemecija  so much for your help on this one!

**Comment by preetikr** [comment]
The PR is merged so closing this issue.
