### ISSUE TITLE
Unable to deploy Custom  sentinel data connector for General and DLP logs https://github.com/Azure/Azure-Sentinel/tree/master/DataConnectors/O365%20Data

### ISSUE THREAD

**Issue by varuntangri03** [Azure/Azure-Sentinel#2474]
Hi,

The deployment template does not seem to work fine, after all the prerequisite completed i am trying to deploy the Azure template solution and it does not create some components. Also i do not see azure function code  and it does not seem to work.

Documentation is not very clear in that detail or something is missing.

**Comment by dicolanl** [comment]
Hi @varuntangri03 
Do you have any errors you can share to help us better understand the issue?  the readme is pretty detailed. do you see steps that are missing?

**Comment by varuntangri03** [comment]
![Azurecustomconnector](https://user-images.githubusercontent.com/67163185/121932277-fcf02980-cd44-11eb-8e70-dcb8c8cd990a.png)

Yes it does not deploy all resources and after deployment i see function app is empty no functions in it. And i do not see the post deployment settings also in Configuration tab in functions app.
![O365Function](https://user-images.githubusercontent.com/67163185/121932580-50627780-cd45-11eb-971b-568f6aa68194.png)

**Comment by dicolanl** [comment]
Thanks @varuntangri03 .  See above I have submitted a PR to fix the issues.
