### ISSUE TITLE
Wrong use of label notation in Office365 workbook

### ISSUE THREAD

**Issue by josephka3** [Azure/Azure-Sentinel#2480]
In the below O365 workbook, in multiple places it is given as, "{Workload:**lable**}"
The spelling of **label** is wrong here, it is given as "**lable**"
https://github.com/Azure/Azure-Sentinel/blob/master/Workbooks/Office365.json

As shown in below doc, it should be, "label"
https://docs.microsoft.com/en-us/azure/azure-monitor/visualize/workbooks-dropdowns#drop-down-parameter-options

It is not detected by the editor either probably because it considers it a string.
Since it is part of the OR condition in the queries, the workbook works.
Kindly rectify this if my understanding of the above is right.

**Comment by v-jayakal** [comment]
Workbook has been modified, changes will be deployed in the next deployment. Please reopen the issue.
