### ISSUE TITLE
Block-AADUser Insufficient Privileges issue

### ISSUE THREAD

**Issue by justmike54** [Azure/Azure-Sentinel#2505]
I'm trying to run the Block-AADUser playbook but keep getting an error regarding insufficient privileges. The account connected to the 'update user' task is a global admin account. I also granted the account the user administrator role also. Can anyone assist?

Error below:

`{
    "statusCode": 403,
    "headers": {
        "Transfer-Encoding": "chunked",
        "Vary": "Accept-Encoding",
        "Strict-Transport-Security": "max-age=31536000",
        "request-id": "d33a71a3-a340-4eef-9a56-ae7019d38afc",
        "client-request-id": "d33a71a3-a340-4eef-9a56-ae7019d38afc",
        "x-ms-ags-diagnostic": "{\"ServerInfo\":{\"DataCenter\":\"UK South\",\"Slice\":\"E\",\"Ring\":\"3\",\"ScaleUnit\":\"000\",\"RoleInstance\":\"LN2PEPF00003B2C\"}}",
        "x-ms-resource-unit": "1",
        "Timing-Allow-Origin": "*",
        "x-ms-apihub-cached-response": "true",
        "Cache-Control": "no-cache",
        "Date": "Thu, 17 Jun 2021 08:15:29 GMT",
        "Content-Type": "application/json",
        "Content-Length": "331"
    },
    "body": {
        "error": {
            "code": "Authorization_RequestDenied",
            "message": "Insufficient privileges to complete the operation.",
            "innerError": {
                "date": "2021-06-17T08:15:30",
                "request-id": "d33a71a3-a340-4eef-9a56-ae7019d38afc",
                "client-request-id": "d33a71a3-a340-4eef-9a56-ae7019d38afc"
            }
        }
    }

> }`

**Comment by dicolanl** [comment]
@justmike54 this seems like an AAD connector issue.  if you authorized that connector with an account that is global admin it should be able to change the user to "disabled".  might mean issue with the connector.  
Could you open a support ticket with Microsoft?

**Comment by justmike54** [comment]
> @justmike54 this seems like an AAD connector issue. if you authorized that connector with an account that is global admin it should be able to change the user to "disabled". might mean issue with the connector.
> Could you open a support ticket with Microsoft?

Thanks, I've raised with Microsoft. Is there anywhere I can check the AAD connector in the meantime? I tried looking under AD connector but not sure where to look.

**Comment by dicolanl** [comment]
@justmike54  on the logic app resource page. there is a blade item called api connections.  go there and you can see which ones the playbook is using.  click the AAD one.  check for status: connected
![image](https://user-images.githubusercontent.com/25964057/122577653-e4636600-d007-11eb-9b4a-7c2fb1513718.png)

you can also click edit api connection and click authorize and go through the sign in process again and try a different user.

**Comment by justmike54** [comment]
> @justmike54 on the logic app resource page. there is a blade item called api connections. go there and you can see which ones the playbook is using. click the AAD one. check for status: connected
> ![image](https://user-images.githubusercontent.com/25964057/122577653-e4636600-d007-11eb-9b4a-7c2fb1513718.png)
> 
> you can also click edit api connection and click authorize and go through the sign in process again and try a different user.

That did the trick! one of the API connections needed to be authorized again for some reason. Thank you!
