### ISSUE TITLE
Azure sentinel doesn't allow to use closure or classification codes other than "Undetermined" when linked incident is closed via Snow

### ISSUE THREAD

**Issue by Ashish-Hingmire** [Azure/Azure-Sentinel#2529]
While using this automated [workflow](https://github.com/Azure/Azure-Sentinel/tree/master/Playbooks/Close-SentinelIncident-fromSNOW) , Azure sentinel doesn't allow to pass classification code other than "Undetermined".
I tried to pass the applicable closure codes but it failed with error message "Bad field" and works only when it has closure code as "Undetermined"
It takes only hard-coded "classification" i.e. "Undetermined". Below are some sample snapshots.
Test 1:
When we passed dynamic Classification code
![image](https://user-images.githubusercontent.com/72780593/122755703-02a0be80-d2b3-11eb-926a-274cdb67ee7d.png)

![image](https://user-images.githubusercontent.com/72780593/122755760-19dfac00-d2b3-11eb-9de9-85ce4a76893b.png)

Test 2:
When we passed hardcoded Classification.
![image](https://user-images.githubusercontent.com/72780593/122755582-cf5e2f80-d2b2-11eb-8902-004a984475c9.png)

Test 3:
When we passed hardcoded Classification as "Undetermined"
![image](https://user-images.githubusercontent.com/72780593/122755921-527f8580-d2b3-11eb-80a8-b0c42da4176f.png)

So it seems Azure sentinel can't understand incoming Classification code from ServiceNow. Please help to close this issue on priority.

**Comment by briandelmsft** [comment]
@Ashish-Hingmire you need to send a classification and classificationReason in the PUT body.  Review https://docs.microsoft.com/en-us/rest/api/securityinsights/incidents/create-or-update#incidentclassification for acceptable classification strings and classificationReason strings
