### ISSUE TITLE
Literal quoting does not work as expected with backslashes

### ISSUE THREAD

**Issue by truekonrads** [Azure/Azure-Sentinel#2557]
**Describe the bug**
The '@' literal quoting doesn't always work, like in this example of strcat

**To Reproduce**
```print x=strcat(@"AB\","USER");```
Error:
```
Failed to parse the query, no additional information is available.
If issue persists, please open a support ticket. Request id: 12eb92a8-1020-41e2-8e49-d04510310790
```
**Expected behavior**
Output "AB\USER".

**Screenshots**
![image](https://user-images.githubusercontent.com/1421150/123196137-f8add400-d4db-11eb-9b86-2ef752d79a84.png)

**Desktop (please complete the following information):**
 - OS: Windows 10, Firefox

**Comment by shainw** [comment]
This seems to work for me if you drop the semi-colon at the end.
![image](https://user-images.githubusercontent.com/45466083/124081866-e3b3d200-da00-11eb-97fb-e070efebeedf.png)

**Comment by truekonrads** [comment]
![image](https://user-images.githubusercontent.com/1421150/124083111-12bd5880-da80-11eb-899b-c06ac1c39daf.png)
Nope

**Comment by shainw** [comment]
@truekonrads - cleaning up stale issues.  In your last screen shot, you are not providing a column name, in my example "x=" needs to be included - print x=strcat(@"AB\","User").
