### ISSUE TITLE
Prompt-User Template Error

### ISSUE THREAD

**Issue by Xebus-Systems** [Azure/Azure-Sentinel#2564]
**Describe the bug**
When deploying Prompt-User into my Azure Tenancy i get the following error

The template validation failed: 'The template action 'Post_a_message_(V3)' at line '1' and column '2285' is not valid: "The template language expression '*sanitized*' is not valid: the value '-' at position '25' cannot be converted to number.".'.

**To Reproduce**

**Expected behavior**
I expected the template to deploy

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by dicolanl** [comment]
Hi @Xebus-Systems 
I just deployed both templates and they worked fine.
![image](https://user-images.githubusercontent.com/25964057/123655630-fc936c00-d7e3-11eb-8742-c61d83011868.png)

Are you entering a number for the team ID and Channel id?  if you dont know them you can just put 123 in the box and update them in the playbook later.

**Comment by Xebus-Systems** [comment]
try deleting out the objects manually and then try and redeploy

Its definitely not working for me

![image](https://user-images.githubusercontent.com/66821277/123674028-40927980-d895-11eb-9ddc-d6ca0c3f313c.png)

**Comment by dicolanl** [comment]
Can you share the details of the bad requst?

**Comment by Xebus-Systems** [comment]
heres the error i get from it

`"{\"error\":{\"code\":\"InvalidTemplate\",\"message\":\"The template validation failed: 'The template action 'Post_a_message_(V3)' at line '1' and column '2777' is not valid: \\\"Unable to parse template language expression '*sanitized*': expected token 'LeftParenthesis' and actual 'Identifier'.\\\".'.\"}}",`

**Comment by dicolanl** [comment]
@Xebus-Systems 
What are you entering for the paramaters?

**Comment by Xebus-Systems** [comment]
![image](https://user-images.githubusercontent.com/66821277/124048441-76d52200-da6a-11eb-8e56-3dd017947318.png)

**Comment by dicolanl** [comment]
@Xebus-Systems You have to enter somehting for teams id and channel id.  just enter 123 for both boxes.  after deployment you can fix the team/channel in the playbook.

**Comment by Xebus-Systems** [comment]
@dicolanl i have no idea why its working now, but its working haha

Cheers for your assistance, i'm scratching my head as to why its now functioning
