### ISSUE TITLE
Run-MDEAntivirus Template error

### ISSUE THREAD

**Issue by Xebus-Systems** [Azure/Azure-Sentinel#2567]
**Describe the bug**
Template error when deploying Run-MDEAntivirus
{
    "status": "Failed",
    "error": {
        "code": "InvalidTemplate",
        "message": "The template validation failed: 'The template action names must be unique: actions 'Add_comment_to_incident_(V3)' are declared multiple times. '."
    }
}

**To Reproduce**
Go to Deploy a custom template
Build your own template editor
Copy code in from github
after adding the details in name e.g Error happens as above

**Expected behavior**
i expect it to deploy the MDEAntivirus integration

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by dicolanl** [comment]
@Xebus-Systems  i just submitted the above PR to fix this.  Once approved the template will be fixed.  Closing issue,
