### ISSUE TITLE
Restrict-MDEIpAddress - Incident Template

### ISSUE THREAD

**Issue by Xebus-Systems** [Azure/Azure-Sentinel#2569]
**Describe the bug**
When deploying the incident template i get the following error

{
  "code": "DeploymentFailed",
  "message": "At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/DeployOperations for usage details.",
  "details": [
    {
      "code": "InvalidRequestContent",
      "message": "The request content is not valid and could not be deserialized: 'Could not find member 'azuresentinel' on object of type 'FlowTemplateParameter'. Path 'properties.parameters.$connections.azuresentinel', line 1, position 2356.'."
    }
  ]
}

**To Reproduce**

Create a custom template
Build your own template in the editor
Copy and paste Code into blank template
Click Save
Enter variables for environment
Click create and get error

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by dicolanl** [comment]
New PR submitted to fix
