### ISSUE TITLE
wrong mapping for computer entity in the "Multiple Password Reset by user" detection 

### ISSUE THREAD

**Issue by Yaniv-Shasha** [Azure/Azure-Sentinel#2570]
**Describe the bug**

the above detection looking for password reset on multiplane data source, my customer spot this issue on the part of the audit logs 

    AuditLogs
        | where TimeGenerated >= ago(timeframe)
        | where OperationName has_any (pWord) and OperationName has_any (action)
        | extend AccountType = tostring(TargetResources[0].type), Account = tostring(TargetResources[0].userPrincipalName), 
            TargetResourceName = tolower(tostring(TargetResources[0].displayName))
        | project TimeGenerated, AccountType, Account, Computer = TargetResourceName, Type),

the part that doing the mapping , in some scenarios return user name and not computer 

 TargetResourceName = tolower(tostring(TargetResources[0].displayName)

**To Reproduce**

run the above query in our internal demo env 

AuditLogs
| extend AccountType = tostring(TargetResources[0].type), Account = tostring(TargetResources[0].userPrincipalName), 
TargetResourceName = tolower(tostring(TargetResources[0].displayName))
| project TimeGenerated, AccountType, Account, Computer = TargetResourceName, Type, TargetResources
| where Computer == "ricky simpson"

![image](https://user-images.githubusercontent.com/10268698/123599187-04f8a080-d7fe-11eb-8850-01c9f9aed9d3.png)

**Expected behavior**
only retrun computer name 

**Screenshots**

**Additional context**

i think we need to add another validator in a sense of the type (user, device) that is part of TargetResourceName  filed

**Comment by ashwin-patil** [comment]
Hi @Yaniv-Shasha , this was recently fixed last week in PR #1834 
Could you try updated template (version: 2.0.0) and let us know if you see any other issues ?

**Comment by ashwin-patil** [comment]
Closing as fix is already checked-in.
