### ISSUE TITLE
I don't believe that event 4657 has a "CommandLine" property

### ISSUE THREAD

**Issue by oshezaf** [Azure/Azure-Sentinel#2575]
https://github.com/Azure/Azure-Sentinel/blob/78dd1dabc6771301fd8a8a672fbaa453b94ce823/Hunting%20Queries/MultipleDataSources/PersistViaIFEORegistryKey.yaml#L26

I don't believe that event 4657 has a "CommandLine" property, which might imply the SecurityEvent part of the query is invalid. See [the documentation](https://docs.microsoft.com/en-us/windows/security/threat-protection/auditing/event-4657).

**Comment by shainw** [comment]
@jannieli - Can you look at this please?

**Comment by oshezaf** [comment]
@jannieli .... reminder.

**Comment by jannieli** [comment]
I think this was fixed with: https://github.com/Azure/Azure-Sentinel/pull/2614
