### ISSUE TITLE
Wrong description/detection title in "Distributed password cracking attempts in Azure AD"

### ISSUE THREAD

**Issue by javiersoriano** [Azure/Azure-Sentinel#2589]
**Describe the bug**
User reported issue via twitter: https://twitter.com/nemesis09/status/1409857824897765384?s=20

"Password cracking is an offline attack. The description here describes password guessing, at best." regarding detection: https://github.com/Azure/Azure-Sentinel/blob/master/Detections/SigninLogs/DistribPassCrackAttempt.yaml

**Comment by shainw** [comment]
@javiersoriano - cleaning up stale issues.  I am not sure this really is accurate.  Password cracking can include a bunch of different types of password attacks.  Opinions are what opinions are and unless there is a real need to change this, I don't see others complaining.  There are a bunch of references, easiest just to point here - https://en.wikipedia.org/wiki/Password_cracking
