### ISSUE TITLE
PaloAltoCustomConnector - Version Not Supported error

### ISSUE THREAD

**Issue by sukster** [Azure/Azure-Sentinel#2597]
**Describe the bug**
When I use the PaloAltoCustomConnector and use action called "Update an address object group", I get an error in the output "Version Not Supported: v10.0". I am using the Palo Alto firewall version 9.1.2. deployed in Azure. What version of Palo Alto Firewall or Panorama have you developed your connector and playbooks on?

**To Reproduce**
1. Create a new playbook for Azure Sentinel
2. Use trigger "When a response to an Azure Sentinel alert is triggered"
3. Use action "Entities - Get IPs"
4. Extract the IPs into an array
5. Add the array under members in "Update an address object group"

**Expected behavior**
I expect the action to dispatch an API call to add the IPs in the array to the Address Group in Palo Alto.

**Screenshots**
![image](https://user-images.githubusercontent.com/67369320/123920117-e3c2bc00-d985-11eb-8d85-9142df02da42.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 Enterprise
 - Browser: Edge (latest)

**Comment by scottbrien01** [comment]
Was there ever an answer to this issue?
