### ISSUE TITLE
functionTimeout error in Github Connector Deployment

### ISSUE THREAD

**Issue by sadewaleBKT** [Azure/Azure-Sentinel#2601]
**Describe the bug**
While attempting to deploy the github connector using the [ARM template](https://github.com/Azure/Azure-Sentinel/tree/master/DataConnectors/GithubFunction), after 10 mins, the function hit a timeout error. 

**To Reproduce**
1. Deploy the ARM template for github connector
2. Perform post deployment steps to add needed files into the storage account
3. Start the function if necessary
4. Monitor the function execution logging, and after 10 mins, you will see error generated for functiontimeout exceeded. 

**Expected behavior**
After running, the function should successfuly complete and the logs should be collected from github api and parsed into azure sentinel log analytics workspace

**Screenshots**
![Screen Shot 2021-06-30 at 11 55 55 AM](https://user-images.githubusercontent.com/77846720/123993549-85540880-d99a-11eb-9a51-3f7ec0afc2ef.png)

**Additional context**

**Comment by sreedharande** [comment]
@sadewaleBKT - GitHub Azure Function app is currently using "Consumption Plan". The Default TimeOut is 5 min and Max is 10 min. In your case, you might have lots of logs coming from your GitHub Organization. Please upgrade to premium plan.
Note: Every premium plan will have at least one active (billed) instance at all times and so this could cost you money

To upgrade Function App from Consumption to Premium, navigate to https://demiliani.com/2020/12/02/moving-azure-functions-from-consumption-to-premium-plans/

**Comment by sadewaleBKT** [comment]
@sreedharande Thanks for the response. I was able to follow the instructions on the link you provided to upgrade to the elastic premium plan, but it seems the timeout value of 10:00 is still being hit. 

Any idea what the best way to change this timeout value is, so the new plan can run for as long as needed to get the job done?

**Comment by sreedharande** [comment]
@sadewaleBKT, are you able to resolve this issue, Please let me know if you need any help

**Comment by sadewaleBKT** [comment]
Hi @sreedharande , i wasnt able to get this working with the upgrade to premium plan. 

I am moving forward to using the logic apps which seems to be working good for me so far. Thanks alot for your response and attempt to assist.
