### ISSUE TITLE
Should one of the make_set be for event_product?

### ISSUE THREAD

**Issue by oshezaf** [Azure/Azure-Sentinel#2621]
https://github.com/Azure/Azure-Sentinel/blob/5f7026dc3bfaa5f131076a347750e71a801da32c/Detections/ASimAuthentication/imAuthSigninsMultipleCountries.yaml#L22

@YaronFruchtmann : Should one of the make_set be for event_product?

**Comment by YaronFruchtmann** [comment]
yes! thanks
