### ISSUE TITLE
Process parser is using HostName instead of Hostname

### ISSUE THREAD

**Issue by YaronFruchtmann** [Azure/Azure-Sentinel#2622]
https://github.com/Azure/Azure-Sentinel/blob/master/Parsers/ASimProcess/ProductParsers/ProcessEventMicrosoftSysmonTerminate.yaml 
Line 38:                         DvcHostName = Computer,
Should:                        DvcHostname = Computer,

Need to check this bug is not found elsewhere, and that detections don't also need a fix

**Comment by oshezaf** [comment]
Thanks. Fixed.
