### ISSUE TITLE
GWorkspace connector may send only some of the events to Sentinel

### ISSUE THREAD

**Issue by oshezaf** [Azure/Azure-Sentinel#2624]
https://github.com/Azure/Azure-Sentinel/blob/954b11d2e4ab99ab65fcaead0eaffae793ed953f/DataConnectors/GoogleWorkspaceReports/GWorkspaceReportsAPISentinelConnector/__init__.py#L130

This looks to me like a bug in the code that throws away many events.

The JSON structure is, simplified for our purpose:
```
...
"items": [
  { // item 1
   ...
   "events": [
    { //event 1
    },
    { //event 2
    },
  { // item 2
...
```

The iterator "event" goes over the JSON array "items", and the iterator "nested" goes over the JSON array "events" array in each item. The function than copies values from each element "events" to the parent "item". As a result the connector keeps an event per element in the "items" array, and does not create an event per an entry in the "events" array.

This is easy to see in the sample data (https://github.com/Azure/Azure-Sentinel/blob/master/Sample%20Data/Custom/GWorkspace_ReportsAPI_drive_CL.json), in which only the last element in the "events" array are expanded to the top JSON element. See line 325

   ```
 "event_name": "add_to_folder",
    "event_type": "access",
    "primary_event": false,
    "billable": true,
    "doc_id": "11fXyLycI_mOzOV0oVlbLfI_KkHy96lN5",
    "doc_type": "unknown",
    "doc_title": "fdaf7afe-7e4d-4359-82bd-f01a9867f535-chunk-161618",
    "visibility": "private",
    "originating_app_id": "962388314550",
    "actor_is_collaborator_account": false,
    "owner": "user2@company.com",
    "owner_is_shared_drive": false,
    "owner_is_team_drive": false,
    "visibility_change": "none",
    "target_user": "user2@company.com",
    "old_value": [
      "owner"
    ],
```

**Comment by oshezaf** [comment]
@preetikr .....

**Comment by averbn** [comment]
@oshezaf 
I checked the connector and made some tests - I didn`t found the issue.
I added counters at the start of the function and at the end (returning part).
![image](https://user-images.githubusercontent.com/72387688/127993365-b4a5c579-9293-4a59-a9e0-b5a96b36f101.png)
As a result, the counters are the same over the same period of time:
![image](https://user-images.githubusercontent.com/72387688/127993472-651eed61-e6c0-4eac-b689-27944e14cacf.png)
Also, I analyzed logs before and after function - enrichment works as properly, do you need examples of logs?

**Comment by oshezaf** [comment]
@averbn : The count is not expected to change. The values to extract from the nested objects into the top objects are the issue. Happy to explain the issue in a chat. That said, I think that the Microsoft team is already fixing this.

**Comment by averbn** [comment]
@oshezaf It seems I understand the issue. I`ll check it in my lab.

**Comment by preetikr** [comment]
@oshezaf - Yes, @averbn is working on a fix for this. Thanks, for the report!

**Comment by v-rucdu** [comment]
@oshezaf  - The issue has been fixed and the PR is merged... Thanks!!!

**Comment by v-maudan** [comment]
@oshezaf , Can we resolve this issue? Thanks!
