### ISSUE TITLE
Multiple workspace query returns unexpected error. (only sometimes)

### ISSUE THREAD

**Issue by DeluxeOwl** [Azure/Azure-Sentinel#2641]
**Describe the bug**
Weird error when trying to run a log analytics query on multiple workspaces.

**To Reproduce**
1. Go to any log analytics workspace
2. Try to run this query (the workspace_name are unique workspaces, I've sanitized them for privacy reasons) 
```sql
let ActivityData = AzureDiagnostics
| union workspace(<workspace_name>).AzureDiagnostics
| union workspace(<workspace_name>).AzureDiagnostics
| union workspace(<workspace_name>).AzureDiagnostics
| union workspace(<workspace_name>).AzureDiagnostics
| union workspace(<workspace_name>).AzureDiagnostics
| union workspace(<workspace_name>).AzureDiagnostics
| union workspace(<workspace_name>).AzureDiagnostics
| union workspace(<workspace_name>).AzureDiagnostics
| union workspace(<workspace_name>).AzureDiagnostics
| union workspace(<workspace_name>).AzureDiagnostics
| union workspace(<workspace_name>).AzureDiagnostics
| union workspace(<workspace_name>).AzureDiagnostics
| union workspace(<workspace_name>).AzureDiagnostics
| union workspace(<workspace_name>).AzureDiagnostics
| union workspace(<workspace_name>).AzureDiagnostics
| union workspace(<workspace_name>).AzureDiagnostics
| union workspace(<workspace_name>).AzureDiagnostics
| union workspace(<workspace_name>).AzureDiagnostics
| union workspace(<workspace_name>).AzureDiagnostics
| union workspace(<workspace_name>).AzureDiagnostics
| union workspace(<workspace_name>).AzureDiagnostics
| union workspace(<workspace_name>).AzureDiagnostics
| union workspace(<workspace_name>).AzureDiagnostics
| union workspace(<workspace_name>).AzureDiagnostics
| union workspace(<workspace_name>).AzureDiagnostics
| union workspace(<workspace_name>).AzureDiagnostics
| union workspace(<workspace_name>).AzureDiagnostics
| union workspace(<workspace_name>).AzureDiagnostics
| union workspace(<workspace_name>).AzureDiagnostics
| union workspace(<workspace_name>).AzureDiagnostics
| union workspace(<workspace_name>).AzureDiagnostics
| union workspace(<workspace_name>).AzureDiagnostics
| union workspace(<workspace_name>).AzureDiagnostics
| union workspace(<workspace_name>).AzureDiagnostics
| union workspace(<workspace_name>).AzureDiagnostics
| union workspace(<workspace_name>).AzureDiagnostics
| union workspace(<workspace_name>).AzureDiagnostics
| union workspace(<workspace_name>).AzureDiagnostics
| union workspace(<workspace_name>).AzureDiagnostics
| union workspace(<workspace_name>).AzureDiagnostics
| union workspace(<workspace_name>).AzureDiagnostics
| union workspace(<workspace_name>).AzureDiagnostics
| union workspace(<workspace_name>).AzureDiagnostics
| where TimeGenerated >= ago(24h)
| where ResourceType == "APPLICATIONGATEWAYS"
| where OperationName == "ApplicationGatewayAccess";
ActivityData
| summarize Count = count() by ["Client IP"] = clientIP_s, Category, ResourceGroup, SubscriptionId, Resource, ResourceType
| order by Count
```

**Expected behavior**
Getting the result from the query.

**Screenshots**
![image](https://user-images.githubusercontent.com/54327698/124906011-4d2e7480-dfef-11eb-80c6-826ca5dc4798.png)

**Additional context**
Sometimes the query works, sometimes it doesn't.
I have permission to run queries on all the workspaces.

We're also encountered this error on different tables, and the same as above, it sometimes works and sometimes doesn't.

**Comment by BenjiSec** [comment]
Do you have the same error message every time, ie. that it's failing to resolve scalar expression "identity_claim_http_schemas_microsoft_com_identity_claims_objectidentifier_g_gsic"? 
I'm trying to reproduce issue using 15 workspaces, but I was always getting the result.

**Comment by DeluxeOwl** [comment]
Yes, it was the same error message every time.

**Comment by BenjiSec** [comment]
to skip errors when you have missing columns or issue with permissions, you should use "isfuzzy=true" with union.
ex. (see bold)
**union withsource=RemoteWorkspaceName isfuzzy=true** 
(workspace('').AzureDiagnostics )
,(workspace('').AzureDiagnostics)
,(workspace('').AzureDiagnostics)
// more workspaces
| where TimeGenerated >= ago(1d)
| where ResourceType == "APPLICATIONGATEWAYS"
| where OperationName == "ApplicationGatewayAccess"
**| parse RemoteWorkspaceName with * "('" RemoteWorkspaceName "')" ***  
| summarize Count = count() by ["Client IP"] = clientIP_s, Category, ResourceGroup, SubscriptionId, Resource, ResourceType, **RemoteWorkspaceName**
| order by Count

Also you can try to use resource-context queries, because you are making enormous query
https://docs.microsoft.com/en-us/azure/azure-monitor/logs/cross-workspace-query
