### ISSUE TITLE
Migrate-LA-to-ADX powershell script fails to recognize the log

### ISSUE THREAD

**Issue by anigan** [Azure/Azure-Sentinel#2652]
This is the output that I get when I run the script:
CommonSecurityLog table is not supported by data export.
DnsEvents table is not supported by data export.
DnsInventory table is not supported by data export.
Heartbeat table is not supported by data export.
Operation table is not supported by data export.
Perf table is not supported by data export.
ProtectionStatus table is not supported by data export.
SecurityAlert table is not supported by data export.
SecurityBaseline table is not supported by data export.
SecurityBaselineSummary table is not supported by data export.
SecurityDetection table is not supported by data export.
SecurityEvent table is not supported by data export.
SecurityIncident table is not supported by data export.
Syslog table is not supported by data export.
Update table is not supported by data export.
UpdateSummary table is not supported by data export.
Usage table is not supported by data export.
W3CIISLog table is not supported by data export.

**Comment by sreedharande** [comment]
@anigan, Operation, Perf, ProtectionStatus , Update, W3CIISLog Tables are not supported by DataExport. Please check supported tables section https://docs.microsoft.com/en-us/azure/azure-monitor/logs/logs-data-export?tabs=portal#supported-tables

**Comment by anigan** [comment]
@sreedharande . It was giving the same error for other tables as well. The output above contains supported as well as unsupported tables. I have fixed this in the PR https://github.com/Azure/Azure-Sentinel/pull/2654 but you're already aware of that.

**Comment by sreedharande** [comment]
@anigan. Thanks for contributing. PR merged
