### ISSUE TITLE
(Preview) TI map Domain entity to DnsEvent

### ISSUE THREAD

**Issue by kelish205** [Azure/Azure-Sentinel#2653]
**Is your feature request related to a problem? Please describe.**
I have turned on my TI map Domain entity to DnsEvent analytic rule. I get duplicate value even after I have investigated IP address. How can I stop receiving the alerts for the IP which I have investigated in past.

**Describe the solution you'd like**
I would like to avoid getting same IP address for investigation every hour when the rule is run.

**Describe alternatives you've considered**
The alternative I have been using is created manual excel sheet of all the IP addresses which have been evaluated. Rather than checking in various tools it is easy to just search for IP address in excel.

**Comment by shussein1530** [comment]
Hello Jeremy Tan, I am trying to implement this query as a rule in our environment, but we do not have DnsEvents data source (table). Is it possible to modify this query using only ThreatIntelligenceIndicator data source and get only top 10 malicious-activity IPs which are not repeated?
