### ISSUE TITLE
Your deployment failed GeoFromIpAndTagIncident

### ISSUE THREAD

**Issue by mastersoho** [Azure/Azure-Sentinel#2673]
When trying to deploy GeoFromIpAndTagIncident I'm getting the following errors. 

See attached

![image](https://user-images.githubusercontent.com/65343387/125599412-410d567f-008d-4006-ac34-225ca706a369.png)

**Comment by dicolanl** [comment]
@mastersoho  could you share the error from linkedtemplate?

**Comment by dicolanl** [comment]
@mastersoho I just submitted the above PR plus #2695 should fix the problems.  closing incident.

**Comment by mastersoho** [comment]
Thanks @dicolanl will test that today

**Comment by mastersoho** [comment]
{"code":"DeploymentFailed","message":"At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/DeployOperations for usage details.","details":[{"code":"ApiNotFound","message":"The API 'IP-API' could not be found."}]}

**Comment by mastersoho** [comment]
{
    "status": "Failed",
    "error": {
        "code": "ApiNotFound",
        "message": "The API 'IP-API' could not be found."
    }
}
