### ISSUE TITLE
Taxii Connector issue

### ISSUE THREAD

**Issue by suhelajjaman** [Azure/Azure-Sentinel#2689]
I had connected threat intelligence feed via Taxii connector, even after deleting the configuration in Taxii connector,the feeds are not stopped it is still being ingested in Log Analytics workspace. The Taxii connector is showing not connected but still logs not stopped.

Please look into before pulling the feeds, it should be looking if the configuration is still there in Taxii data connector

**Comment by BenjiSec** [comment]
Hi, the data is not ingested but by design all TI indicators are refreshed every 14 days so that they stay current. So the feeds aren't the new TI data but refreshed TI data.

**Comment by suhelajjaman** [comment]
But how to stop it from ingesting it, even after deleting Taxii connector configuration

**Comment by BenjiSec** [comment]
Currently, you will have to raise support ticket and they will assist you with the process. More user friendly way will come in the future.
