### ISSUE TITLE
Crowdstrike rules and workbook seem to not relate to the Crowdstrike solution

### ISSUE THREAD

**Issue by oshezaf** [Azure/Azure-Sentinel#2714]
The  [Crowdstrike solution](https://github.com/Azure/Azure-Sentinel/tree/master/Solutions/CrowdStrike%20Falcon%20Endpoint%20Protection)  includes an azure function based connector and the [parser function](https://github.com/Azure/Azure-Sentinel/blob/master/Solutions/CrowdStrike%20Falcon%20Endpoint%20Protection/Parsers/CrowdstrikeReplicator) for it function called CrowdstrikeReplicator. The analytic rules and workbook included in the solution seem to require a function called CrowdStrikeFalconEventStream which is associated with the [older parser based on CEF](https://github.com/Azure/Azure-Sentinel/blob/master/Parsers/CrowdStrikeFalconEventStream/CrowdstrikeFalconEventStream.txt)

**Comment by v-maudan** [comment]
@oshezaf , Moved CrowdStrikeFalconEventStream  parser to solution folder . https://github.com/Azure/Azure-Sentinel/pull/2735
This parser is part of [CrowdStrike Falcon Endpoint Protection Solution ](https://ms.portal.azure.com/#blade/Microsoft_Azure_Marketplace/GalleryItemDetailsBladeNopdl/id/azuresentinel.azure-sentinel-solution-crowdstrikefalconep)which is already published.

**Comment by v-jayakal** [comment]
As parser has moved to solution folder, closing the issue.
