### ISSUE TITLE
DocuSign-SecurityEvents DataConnector error with Azure FunctionApp PowerShell Core

### ISSUE THREAD

**Issue by clhar** [Azure/Azure-Sentinel#2721]
**Describe the bug**
When deploying the DocuSign SecurityEvents DataConnector the function app that is created does not correctly execute, the issue appears to be due to the $rsa = [System.Security.Cryptography.RSA]::Create($rsaParameters) line which produces an error

Exception calling "Create" with "1" argument(s): "The specified RSA parameters are not valid; both Exponent and Modulus are required fields."Data           : System.Collections.ListDictionaryInternalInnerException :Type       : System.Security.Cryptography.CryptographicExceptionTargetSite :Name          : ImportParametersDeclaringType : System.Security.Cryptography.RSAImplementation+RSACng, System.Security.Cryptography.Algorithms, Version=4.3.2.0

This appears to be an issue when running in an Azure Function App on Powershell Core V7

**To Reproduce**
1. Deploy the DocuSign SecurityEvents function app as documented here https://github.com/Azure/Azure-Sentinel/tree/master/DataConnectors/DocuSign-SecurityEvents
2. Review the Function App log
3. Log will show the following output "OUTPUT: Please check you have DerConverter.dll and PemUtils.dll under C:\home\site\wwwroot\Modules" indicating that an error was caught 

**Expected behavior**
The function app should run successfully without any error

**Additional context**
To debug I created another function app and modified the portion of code below as follows to comment out all but the RSA section, this produced more detailed error details

`#try{
	Add-Type -Path "C:\home\site\wwwroot\Modules\DerConverter.dll"
	Add-Type -Path "C:\home\site\wwwroot\Modules\PemUtils.dll"
	$keyStream = [System.IO.File]::OpenRead($privateKeyPath)
	$rsaParameters = [PemUtils.PemReader]::new($keyStream).ReadRsaKey()
	$rsa = [System.Security.Cryptography.RSA]::Create($rsaParameters)
	#$tokenBytes = [System.Text.Encoding]::ASCII.GetBytes($jwtToken)
	#$signedToken = $rsa.SignData(
		#$tokenBytes,
		#[System.Security.Cryptography.HashAlgorithmName]::SHA256,
		#[System.Security.Cryptography.RSASignaturePadding]::Pkcs1)
	#$signedBase64Token = [System.Convert]::ToBase64String($signedToken) -replace '\+', '-' -replace '/', '_' -replace '='
	#$jwtToken = "$encJwtHeader.$encJwtPayLoad.$signedBase64Token"
	#$keyStream.Close()
	#$keyStream.Dispose()
#}
#catch {
	#Write-Output "Please check you have DerConverter.dll and PemUtils.dll under C:\home\site\wwwroot\Modules"
	#$keyStream.Close()
	#$keyStream.Dispose()
#}`

**Comment by Kalakaarboyz1** [comment]
what the fuck i was reported this issue who is this clhar

**Comment by clhar** [comment]
I have now perfromed additional testing and found that there is sensitivity with the [System.Security.Cryptography.RSA]::Create($rsaParameters) code in the function which was not accepting the private key parameters in my case it was the P (prime 1) parameter that was triggering the error.

I extracted the private key parameters and run through my key test code and found that it only failed when running within an Azure function app, the same code running on Windows 10 PowerShell did not error so I can only conclude there is a difference with the Security.Cryptography.RSA  library being used and sensitivity over parameters

In my case I was able to implement a workaround, as the issue only appears to show on certain RSA keys, so I generated new keys which did not trigger the parameter invalid data error.

Original Error with bad key:
![image](https://user-images.githubusercontent.com/87760028/126759724-02c88ca6-d5ad-4d41-b24c-f2eb3e8d9a05.png)

This may be linked with this other reported issue reported on .NET core 3 - https://github.com/dotnet/runtime/issues/30914

**Comment by sreedharande** [comment]
@clhar- did you copy the private_key into the file "DocuSignRSAPrivateKey.key" If you don’t copy them first, your only option will be to delete the RSA key pair and add a new one. Select OK, then select SAVE. Upload previously saved file "DocuSignRSAPrivateKey.key" to "docusign-monitor" container under storage account, named - <<FunctionAppName>><<uniqueid>>

**Comment by clhar** [comment]
@sreedharande yes I had downloaded the key verified it and uploaded to the storage account, and I could read in the key ok, it was an issue with one of the key parameters not being liked by the System.Security.Cryptography.RSA library which meant the line $rsa = [System.Security.Cryptography.RSA]::Create($rsaParameters) was throwing an error but only when running in the Function App

So I can only conclude that either 1) I had a bad RSA private key, or 2) There is a special sensitivity to key parameter padding when running in an Azure Function App like mentioned in the issue I linked above

Also as a further note for anyone else who may have the same issue. I experienced issues with the Function not triggering on the schedule when the WEBSITE_RUN_FROM_PACKAGE was set to the GitHub hosted zip file, so I had to remove this configuration value and upload the package files to the app wwwroot folder so it ran locally rather than from the remote package, but now the code is triggering and working as expected.

**Comment by sreedharande** [comment]
@clhar - only time this will fail when you dont have required DLL's (DerConverter.dll & PemUtils.dll) under the Modules folder in the deployment package. As you uploaded whole package manually to wwwroot folder, now it has access to DerConverter.dll & PemUtils.dll, its working as expected
