### ISSUE TITLE
Make Incident from Alert via API

### ISSUE THREAD

**Issue by Lodewyk-Git** [Azure/Azure-Sentinel#2726]
**Is your feature request related to a problem? Please describe.**
I've been looking at creating Incidents via the API. Then i saw that you can't create the the ExtendedProperties or Entities fields via the API and that an Alert is not created when you create an Incident via the API.

**Describe the solution you'd like**
I'd like to be able to create an Alert and associate it with an Incident via an API request or some other method so that I can create Incidents with prepopulated alert data.

**Describe alternatives you've considered**
I've been considering using a Logic App.

**Additional context**
I want this to work like an MCAS Alert, so that I can send alerts from an IPS or related product with prefilled entities (already existing in environment) without having to rewrite my IPS logic in KQL.

**Comment by BenjiSec** [comment]
Currently you can create Incident but not Alert via API. It would be the best to connect logs to Azure Sentinel and define Analytics in Azure Sentinel for it. If you want to make some additional connection or add additional information, you can use Bookmarks feature and connect Bookmarks to new or existing incident. But this will still need data in Azure Sentinel since Bookmarks are using KQL for hunting.

**Comment by Lodewyk-Git** [comment]
Hi @BenjiSec, when will we be able to create alerts via the API?

**Comment by BenjiSec** [comment]
Currently, there is no info that this is will come as SIEM purpose is not to ingest Alerts but to ingest Events that can be used to create alerts, analyze data, and hunt for more correlated information. You can specify and ingest only specific data to Azure Sentinel, but you would still need to create alert detection in Azure Sentinel.

**Comment by Lodewyk-Git** [comment]
If the purpose is to ingest Events only then why are we receiving alerts from products such as MCAS, Azure Defender and AAD IP and not events? What else can I do if I've got multiple workspaces related to one environment and I want to only view specific Incidents from those different workspaces in one environment?

**Comment by BenjiSec** [comment]
You can utilize Azure Lighthouse for that purpose - [https://docs.microsoft.com/en-us/azure/lighthouse/how-to/manage-sentinel-workspaces](https://docs.microsoft.com/en-us/azure/lighthouse/how-to/manage-sentinel-workspaces).

**Comment by Lodewyk-Git** [comment]
Yes, I'm making use of that feature already...

**Comment by dicolanl** [comment]
@Lodewyk-Git  we dont have an API today to create an alert.  your best bet today would be write your alert to a custom log using the Log A Data Collector API (https://docs.microsoft.com/en-us/rest/api/loganalytics/create-request). Then create an analytic rule in Sentinel that triggers off of your custom log.  The analytic rule would create an alert and if you choose create a matching incident. 

This would be better as well cause your custom log could have additional fields for entities and you could map them in the analytic rule.

**Comment by Lodewyk-Git** [comment]
Thanks @dicolanl, I also ended up with using this method. Will this be the only viable way of accomplishing this task or will the ability to create alerts be possible in the future?

**Comment by dicolanl** [comment]
@Lodewyk-Git  no plans for that at this time.
