### ISSUE TITLE
DependsOn attribute missing from Workspace child resources [Solution Package Generation]

### ISSUE THREAD

**Issue by ericlanteigne-semperis** [Azure/Azure-Sentinel#2729]
**Describe the bug**
Generated a package for a solution and when I verify the resource deployment I encounter an error saying the workspace is not found.
The Resource 'Microsoft.OperationalInsights/workspaces/DSP-Integration-EricsResearch' under resource group 'DSP-Integration' was not found. For more details please go to https://aka.ms/ARMResourceNotFoundFix"

**To Reproduce**
1. Go to 'https://portal.azure.com/?feature.IncidentTriggering=true&feature.investigationrawdata=true&feature.MultiplePlaybooksForRule=true&feature=&EntitiesFromGS=true&feature.mstimatching=true&feature.Dynamics365Connector=true&feature.Solutions=true&feature.EntityMapping=true&feature.AnalyticsEfficiency=true&feature.IncidentTimeline=true&feature.msticonnector=true&feature.mtpconnector=true&feature.BringCustomConnector=true&feature.teamscollaboration=true&feature.AlertDetails=true&feature.ZscalerPrivateAccessConnector=true&SearchKeyFieldMapping=true&feature.WindowsSecurityEventsFeature=true&feature.AdvancedSearch=true&feature.includePreviewTemplates=true&playbooksgallery=true&feature.management=true#create/Microsoft.Template'
2. Click on 'Build your own template in the editor'
3. Paste the content from mainTemplate.json into editor
4. Click on 'Save'
5. Select a Subscription, Resource Group and enter a workspace name.
6. Click on 'Review + Create'
7. Click on 'Create'
8. See error

**Expected behavior**
Expecting resources to wait until parent is available before trying to create. Child resources should have a DependsOn attribute set by package generation.

**Screenshots**
![mainTemplateFirstTry](https://user-images.githubusercontent.com/84532420/126810420-79449320-3d5c-467a-b0a5-c92502a35780.png)

**Additional context**
Source files:
[1.0.1.zip](https://github.com/Azure/Azure-Sentinel/files/6869990/1.0.1.zip)

Package validation:
![templateValidation-1 0 1](https://user-images.githubusercontent.com/84532420/126811513-7b84a515-5815-499b-8f0b-b41a6a97a068.png)

**Comment by v-maudan** [comment]
@ericlanteigne-semperis , Can you please check whether workspace name for Log Analytics where Azure Sentinel is setup.

**Comment by ericlanteigne-semperis** [comment]
I don't understand what I need to check exactly, could you elaborate?

**Comment by v-maudan** [comment]
@ericlanteigne-semperis , We should have Log analytics workspace which is having azure sentinel is setup. It seems 'DSP-Integartion-EricsReserach' workspace is not there in 'DSP-Integration' resource group.
1. Go to Resource Group 'DSP-Integration'
2. Check Log analytics workspace 'DSP-Integartion-EricsReserach' is there or not.If not create the same.[**See Documention**](https://docs.microsoft.com/en-us/azure/azure-monitor/logs/quick-create-workspace)
3. Check these steps to enable azure sentinel for workspace.[**See Documention**](https://docs.microsoft.com/en-us/azure/sentinel/quickstart-onboard#enable-azure-sentinel-)
![image](https://user-images.githubusercontent.com/75478517/127261866-5945f39a-a8a2-4898-b883-fec26e1ef771.png)

**Comment by ericlanteigne-semperis** [comment]
Yes I did confirm the workspace was in fact created. In the screenshot of the failed deployment you can see that it is green and I do see it in the resource group as well. Each test I've done has successfully created the Log analytics workspace. Its only the analytic rules and data connector which it is trying to add to the workspace that fail. 
![image](https://user-images.githubusercontent.com/84532420/127330612-2e72597c-3f57-4b02-a0bf-f9b260620311.png)

**Comment by ericlanteigne-semperis** [comment]
I should add that once I manually added the dependsOn attributes like it mentions in documentation and I got past this issue. I wanted to bring it up though in case it can be incorporated into package generation.

**Comment by v-maudan** [comment]
@ericlanteigne-semperis , We need provide azure sentinel enabled log analytics workspace while testing solution. Can we close this issue or let me know if still need you any help? Thanks!

**Comment by ericlanteigne-semperis** [comment]
@v-maudan Yeah we can close it. If the dependsOn attribute was added it would technically create the workspace for you correctly but it still wouldn't be Sentinel enabled which means it wouldn't work anyways. There may be some additional instruction that could be added to the Readme steps which could help avoid confusion about needing to deploy into an existing Sentinel enabled workspace even though the template will create one if one is not provided. Thanks for the help
