### ISSUE TITLE
Can't deploy CEF-VMSS Ubuntu template due to dpkg in use which brokes OMSAgent installation

### ISSUE THREAD

**Issue by jankeurofins** [Azure/Azure-Sentinel#2739]
**Describe the bug**
I'm trying to run CEF-VMSS template using Ubuntu distro: https://github.com/Azure/Azure-Sentinel/tree/master/DataConnectors/CEF-VMSS
I modified a little ARM template to use existing VirtualNetwork and Internal Load balancer but it doesn't matter here. All ARM resources are deploying without issue. Problem starts when VMSS object is created and VM instance is starting for the first time. It looks like initial VM boot uses dpkg to install some ubuntu packages what interferes with cloud-init data which download omsagent and tries to install it.
No matter how I'm trying to modify custom-data passed to cloud-init I always get error that dpkg is in use, what makes omsagent installation to fail.

Tried adding a loop to cloud-init config but it doesn't help.
`  - while ( fuser /var/lib/dpkg/lock >/dev/null 2>&1 ); do sleep 5; done;`

Thanks.

`

![image](https://user-images.githubusercontent.com/87987326/127007078-573bf1fc-6fbd-4314-bc0b-8491925a28ca.png)
![image](https://user-images.githubusercontent.com/87987326/127007275-f1bd02e9-aebe-4979-8e99-f3fc24624558.png)

**Comment by dicolanl** [comment]
@jankeurofins what happens if you manually install the agent after deployment?

Trying to figure out if this is an Agent Issue or cloudinit problem

**Comment by jankeurofins** [comment]
If I remove cloudinit custom data from the deployment, Azure resources deploy without issue, then logging to VM instance of VM scale set I run all cloud-init commands manually without any problem.

**Comment by dicolanl** [comment]
Seems like a cloudinit issue where its running the commands before dpkg is done.

**Comment by dicolanl** [comment]
btw, just found this https://msftstack.wordpress.com/2016/05/12/extension-sequencing-in-azure-vm-scale-sets/. i think because the template has extensions added and cloudinit is installing the extension its conflicting.  

I just tested removing extensions from the template.  cloud init doesnt have the dpkg error now.  Ill create a new PR and update the templates.

**Comment by dicolanl** [comment]
@jankeurofins Updated with PR above.  I added a loop in the cloudinit to wait for Azure extensions to install.  Tested and it worked.

here is the cloud init log 
138150K .......... .......... .......... .......... .......... 99% 28.5M 0s
138200K .......... .......... .......... .......... .......... 99% 94.6M 0s
138250K .......... .......... .......... .......... .......... 99% 91.3M 0s
138300K .......... .......... .......... .......... .......... 99% 69.5M 0s
138350K .......... .......... .......... .......... .......... 99% 77.4M 0s
138400K .......... .......... .......... .......... .......... 99%  177M 0s
138450K .......... .......... .......... .......... .......... 99% 35.0M 0s
138500K .......... .......... .......... .......... .......... 99% 28.4M 0s
138550K .......... .......... .......... ..........           100% 17.0M=3.5s

2021-07-28 16:34:30 (39.1 MB/s) - ‘omsagent-1.13.35-0.universal.x64.sh’ saved [141916898/141916898]

Checking if Docker is installed...
  Docker not found. Docker agent will not be installed.
--2021-07-28 16:34:52--  https://raw.githubusercontent.com/microsoft/OMS-Agent-for-Linux/master/installer/conf/omsagent.d/security_events.conf
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.109.133, 185.199.111.133, 185.199.108.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.109.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 417 [text/plain]
Saving to: ‘/etc/opt/microsoft/omsagent/workspaceid/conf/omsagent.d/security_events.conf’

     0K                                                       100% 23.5M=0s

2021-07-28 16:34:53 (23.5 MB/s) - ‘/etc/opt/microsoft/omsagent/workspaceid/conf/omsagent.d/security_events.conf’ saved [417/417]

Workspace ID: workspaceid
Primary key: workspacekey
Trying to download the omsagent.
^[[0;30;47mwget https://raw.githubusercontent.com/Microsoft/OMS-Agent-for-Linux/master/installer/scripts/onboard_agent.sh^[[0m
^[[1;32;40mDownloaded omsagent successfully.^[[0m
Installing omsagent
^[[0;30;47msh onboard_agent.sh -w workspaceid -s OkLYuugj1ZOeCtz39zxGSvpbsUo+9B1tDMOtUm/p0imN4963VtIjRCoIssUJlt2uhQd2XnCKPKp/ZeDJ$
^[[1;32;40mInstalled omsagent successfully.^[[0m
Creating omsagent configuration to listen to syslog daemon forwarding port - 25226
Configuration location is - /etc/opt/microsoft/omsagent/workspaceid/conf/omsagent.d/security_events.conf
Download configuration into the correct directory
^[[0;30;47msudo mkdir -p /etc/opt/microsoft/omsagent/workspaceid/conf/omsagent.d/^[[0m
^[[0;30;47msudo wget -O /etc/opt/microsoft/omsagent/workspaceid/conf/omsagent.d/security_events.conf https://raw.githubuserconten$
^[[1;32;40mConfiguration for omsagent downloaded successfully.^[[0m
Trying to change omsagent configuration
^[[1;32;40mOmsagent configuration was changed to fit required protocol - /etc/opt/microsoft/omsagent/workspaceid/conf/omsagent.d/$
^[[1;32;40mFinished changing omsagent configuration^[[0m
Located rsyslog daemon running on the machine

dkpg is no longer locked.

**Comment by jankeurofins** [comment]
Now it's working - no more dpkg lock issue - all cloud-init commands finished with success.
Thank you.

**Comment by dicolanl** [comment]
@jankeurofins AWESOME!  thanks for confirming.
