### ISSUE TITLE
Duplicate playbook

### ISSUE THREAD

**Issue by jonyluke** [Azure/Azure-Sentinel#2751]
The following playbooks are exactly the same.

https://github.com/Azure/Azure-Sentinel/tree/master/Playbooks/Send-IngestionCostAnomalyAlert
https://github.com/Azure/Azure-Sentinel/tree/master/Playbooks/Send-IngestionAnomalyAlert

**Comment by iwafula025** [comment]
@jonyluke  they are not the same, here's the difference: The "Ingestion AnomalyAlert" logic app is complementary to the previously released "Ingestion Cost Alert App" but different in function. The Ingestion Cost Alert App is designed to send you alerts if the budget you define is exceeded. In contrast, the Ingestion Cost Anomaly App is designed to alert you, should there be an unusual spike in the billable data being ingested into the Log Analytics workspace where you have . I am releasing a blog soon to explain in greater detail
