### ISSUE TITLE
The API used in the CarbonBlack connector will be deactivated next month (Sep 2021)

### ISSUE THREAD

**Issue by oshezaf** [Azure/Azure-Sentinel#2776]
https://github.com/Azure/Azure-Sentinel/blob/1c5bafa74ed8f87d26140dba57e17af6aa4e12d7/DataConnectors/VMware%20Carbon%20Black/AzureFunctionVMwareCarbonBlack/run.ps1#L10

Per the [documentation referenced](https://developer.carbonblack.com/reference/carbon-black-cloud/cb-defense/latest/rest-api/)

**Comment by preetikr** [comment]
Thanks, @oshezaf - We're aware of this and plan to update this integration.

**Comment by oshezaf** [comment]
Thanks @preetikr. Can you get me in the loop? I found this out while trying to add EDR normalization to CarbonBlack, and it would if we normalize as we update.

**Comment by v-jayakal** [comment]
@v-rucdu , please add @oshezaf in the vmware update you are working on, Thanks.

**Comment by v-rucdu** [comment]
@oshezaf : I have raised a [PR](https://github.com/Azure/Azure-Sentinel/pull/2871https://github.com/Azure/Azure-Sentinel/pull/2871) for migrating the API
