### ISSUE TITLE
M365-Security-Posture Bug

### ISSUE THREAD

**Issue by Xebus-Systems** [Azure/Azure-Sentinel#2778]
When trying to run the M365 Posture Logic app, im getting the following error in the Output

Auth token does not contain valid permissions or user does not have valid roles.

Have checked my app registration and its permissions based on the documentation provided

Does this need to be updated?

**Comment by BenjiSec** [comment]
@Xebus-Systems - 2 of the MDE API permissions are missing in the instruction.
Can you please follow up the blog on this topic to deploy? All APIs are included here - https://techcommunity.microsoft.com/t5/azure-sentinel/microsoft-defender-security-insights-in-azure-sentinel/ba-p/2359705

Readme will be updated. Thank you.
