### ISSUE TITLE
Office365 see which person shared a file that is downloaded

### ISSUE THREAD

**Issue by jonyluke** [Azure/Azure-Sentinel#2779]
I want to see which person shared a file that is downloaded, in addition to the "FileUpload" operation, could "AddedToSecureLink" or "SecureLinkUpdated" work or are they for something else?

> 
> OfficeActivity
> | where OfficeWorkload == "OneDrive" or OfficeWorkload == "SharePoint" 
> | where Operation == 'FileDownloaded'
> | where TimeGenerated > ago(1h)
> | summarize Count=count() by UserId
> | where Count >= 100
> | join kind=inner(
>  OfficeActivity
> | where OfficeWorkload == "OneDrive" or OfficeWorkload == "SharePoint" 
> | where Operation == 'FileDownloaded'
> | where TimeGenerated > ago(1h)
> | project TimeGenerated, Operation, OfficeWorkload, OfficeObjectId, UserId)
>  on UserId
> | join (
> OfficeActivity
> | where OfficeWorkload == "OneDrive" or OfficeWorkload == "SharePoint" 
> | where Operation == 'FileUploaded'
> | project TimeGenerated, Operation, OfficeWorkload, OfficeObjectId, UserId)
> on OfficeObjectId    
> | project TimeGenerated, Operation, OfficeWorkload, OfficeObjectId, UserId, UserId2

**Comment by ashwin-patil** [comment]
Hey @jonyluke, You can check more operations related to [Sharing and access request activities](https://docs.microsoft.com/en-us/microsoft-365/compliance/search-the-audit-log-in-security-and-compliance?view=o365-worldwide#sharing-and-access-request-activities) on Microsoft  Docs. 

I believe you can extend the query to hunt for additional sharing operations such as  `CompanyLinkCreated` , `AnonymousLinkCreated` , `SharingInvitationCreated` , `SharingInvitationAccepted`  , `SharingSet` , `AnonymousLinkUpdated` , `SharingInvitationUpdated` , this should help tracking origination of sharing and attribute to user.

**Comment by aprakash13** [comment]
@ashwin-patil pointed to doc that can help with extending the query if so required. Closing this out as of now.
