### ISSUE TITLE
Playbooks template "Run-MDEAntivirus" bug

### ISSUE THREAD

**Issue by ityankel** [Azure/Azure-Sentinel#2781]
**Describe the bug**
The template fails to be deployed with an error message about an invalid API connection managed identity. From a look at the template it seems the API connection resource is marked to use managed identity ('alternative' type) but in the playbook parameters the connection isn't marked as a managed identity connection

> {"code":"DeploymentFailed","message":"At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/DeployOperations for usage details.","details":[{"code":"WorkflowManagedIdentityConfigurationInvalid","message":"The workflow connection parameter 'azuresentinel' is not valid. The API connection 'azuresentinel' is configured to support managed identity but the connection parameter is either missing 'authentication' property in connection properties or authentication type is not 'ManagedServiceIdentity'."}]}

**To Reproduce**
Deploy the Run-MDEAntivirus incident trigger playbook

**Screenshots**
![image](https://user-images.githubusercontent.com/47292630/128051786-d8c328f4-27e4-49b1-9dde-6fae6116c76f.png)

**Comment by dicolanl** [comment]
@ityankel just submitted a new PR to fix this. a couple of lines where missing for the connections to use managed identity.
