### ISSUE TITLE
File supports for onedrive

### ISSUE THREAD

**Issue by oshezaf** [Azure/Azure-Sentinel#2787]
https://github.com/Azure/Azure-Sentinel/blob/658935da211bf5ef06a85cc696a55b783358e95a/Parsers/ASimFileEvent/ProductParsers/FileEventMicrosoftSharePoint.yaml#L34

@YaronFruchtmann : we need to update the filter to include OneDrive:
```OfficeActivity | where OfficeWorkload == "OneDrive" or OfficeWorkload == "SharePoint" ```

**Comment by YaronFruchtmann** [comment]
Thanks Sarah. done: https://github.com/Azure/Azure-Sentinel/blob/master/Parsers/ASimFileEvent/ProductParsers/FileEventMicrosoftSharePoint.yaml
