### ISSUE TITLE
Template error regarding "Starting or Stopping HealthService to Avoid Detection"

### ISSUE THREAD

**Issue by Carter-ChenC** [Azure/Azure-Sentinel#2796]
**Describe the bug**
Error message showing: 'extend' operator: Failed to resolve scalar expression named '["@Name"]'.

Doc is here: https://github.com/Azure/Azure-Sentinel/blob/45da87dec250017c0fd45cb55842e6d6cde8f1ee/Detections/SecurityEvent/StartStopHealthService.yaml

**To Reproduce**
![image](https://user-images.githubusercontent.com/83210873/128474687-f2aeff4f-ffa3-4dab-aef3-5d706abcdf61.png)

**Expected behavior**
Can successfully use this Analytics rule.

**Screenshots**
Attached at "To reproduce".

**Comment by Carter-ChenC** [comment]
Hi @aprakash13, is there any updates for this template error? Thanks for your attention!

**Comment by oshvartz** [comment]
this was fixed #3409
