### ISSUE TITLE
Issue w/ Get-MDEInvestigationPackage

### ISSUE THREAD

**Issue by richlilly2004** [Azure/Azure-Sentinel#2802]
Fails to deploy Alert template due to:

{"code":"DeploymentFailed","message":"At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/DeployOperations for usage details.","details":[{"code":"InvalidTemplate","message":"The template validation failed: 'The template action 'Post_a_message_(V3)' at line '1' and column '2906' is not valid: \"The template language expression '*sanitized*' is not valid: the string interpolation segment starting at position '15' is not terminated. Make sure that every '@{' is followed by its '}'.\".'."}]}

**Comment by dicolanl** [comment]
@richlilly2004 did you change the defaults for team id and channel id?  if you leave the default you will get this error.

**Comment by dicolanl** [comment]
@richlilly2004  disregard my previous comment.  i found a type.  new pr submitted with fix.
