### ISSUE TITLE
Sentinel UniFi Solution is not accepted on CSP subscriptions

### ISSUE THREAD

**Issue by s3bast1aan** [Azure/Azure-Sentinel#2824]
**Is your feature request related to a problem? Please describe.**

The Azure Sentinel solution for Ubiquiti UniFi (preview) is not allowing deployments to CSP subscriptions in Azure.

![image](https://user-images.githubusercontent.com/42578716/129197936-0baa2edf-4518-4333-8ba7-347199cbde07.png)

**Describe the solution you'd like**

Allow the Ubiquiti UniFi (preview) solution to be deployed in CSP subscriptions.

![image](https://user-images.githubusercontent.com/42578716/129198219-e87b4885-81e8-4436-8786-948b36efcef4.png)

**External links**

https://www.microsoftpartnercommunity.com/t5/Microsoft-AppSource-and-Azure/Error-This-offer-is-not-available-for-subscriptions-from/m-p/22881
https://docs.microsoft.com/en-us/partner-center/azure-plan-available

**Comment by v-sabiraj** [comment]
@s3bast1aan, we have enabled the csp for this solution, can you please if the issue still persists. Thanks.

**Comment by v-sabiraj** [comment]
@s3bast1aan, please let me know if we can close this issue, thanks.

**Comment by s3bast1aan** [comment]
> @s3bast1aan, please let me know if we can close this issue, thanks.

Hi @v-sabiraj , yes I can confirm that the deployment is working now.
Thank you. :-)
