### ISSUE TITLE
No clear indicator of which account is creating changes against another account - "Multiple Password Reset by User"

### ISSUE THREAD

**Issue by holmbert095** [Azure/Azure-Sentinel#2891]
**Describe the bug**
The query used to show a user account that has had multiple password resets does not clearly indicate which account initiated the password change vs which account had its password changed.

**To Reproduce**
1. When you receive an alert for this analytics rule, copy andn paste the query code into the Logs section of Sentinel.
2. Hit run in the logs area
3. Review the details.

**Expected behavior**
A column that says, "InitiatingAccount" or "AccountMakingChanges" to differentiate between which account and/or device initiated the password changes.

**Screenshots & Query**
Below is the query that the "Multiple Password Reset by User" analytics rule uses: 
`let PerUserThreshold = 5;
let TotalThreshold = 100;
let action = dynamic(["change", "changed", "reset"]);
let pWord = dynamic(["password", "credentials"]);
let PasswordResetMultiDataSource =
(union isfuzzy=true
(//Password reset events
//4723: An attempt was made to change an account's password
//4724: An attempt was made to reset an accounts password
SecurityEvent
| where EventID in ("4723","4724")
| project TimeGenerated, Computer, AccountType, Account, Type),
(//Azure Active Directory Password reset events
AuditLogs
| where OperationName has_any (pWord) and OperationName has_any (action)
| extend AccountType = tostring(TargetResources[0].type), Account = tostring(TargetResources[0].userPrincipalName), 
TargetResourceName = tolower(tostring(TargetResources[0].displayName))
| project TimeGenerated, AccountType, Account, Computer = "", Type),
(//OfficeActive ActiveDirectory Password reset events
OfficeActivity
| where OfficeWorkload == "AzureActiveDirectory" 
| where (ExtendedProperties has_any (pWord) or ModifiedProperties has_any (pWord)) and (ExtendedProperties has_any (action) or ModifiedProperties has_any (action))
| extend AccountType = UserType, Account = OfficeObjectId 
| project TimeGenerated, AccountType, Account, Type, Computer = ""),
(// Unix syslog password reset events
Syslog
| where Facility in ("auth","authpriv")
| where SyslogMessage has_any (pWord) and SyslogMessage has_any (action)
| extend AccountType = iif(SyslogMessage contains "root", "Root", "Non-Root")
| where SyslogMessage matches regex ".*password changed for.*"
| parse SyslogMessage with * "password changed for" Account
| project TimeGenerated, AccountType, Account, Computer = HostName, Type)
);
let pwrmd = PasswordResetMultiDataSource
| project TimeGenerated, Computer, AccountType, Account, Type;
(union isfuzzy=true  
(pwrmd
| summarize StartTimeUtc = min(TimeGenerated), EndTimeUtc = max(TimeGenerated), Computerlist = make_set(Computer, 25), AccountType = make_set(AccountType, 25), Computer = arg_max(Computer , TimeGenerated), Total=count() by Account, Type
| where Total > PerUserThreshold
| extend ResetPivot = "PerUserReset"),  
(pwrmd
| summarize StartTimeUtc = min(TimeGenerated), EndTimeUtc = max(TimeGenerated), ComputerList = make_set(Computer, 25), AccountList = make_set(Account, 25), AccountType = make_set(AccountType, 25), Account = arg_max(Account, TimeGenerated), Computer = arg_max(Computer , TimeGenerated), Total=count() by Type
| where Total > TotalThreshold
| extend ResetPivot = "TotalUserReset")
)
| extend timestamp = StartTimeUtc, AccountCustomEntity = Account, HostCustomEntity = Computer`

![MultiplePwResets8 23 2021](https://user-images.githubusercontent.com/89430397/130554102-2cda2058-3799-46d6-8811-17a93015dc42.jpg)

Is the SamAccountName from #1 the account that made changes on the computer password (#2) in this case?
**OR,** did the SamAccount (#1) have password changes that were made on itself (#3)? 
It would be nice if the fields that are projected in the query can define that, because as an analytics person, it is difficult to tell at first glance of the query.

**Additional context**
By the way, the account in question is a service account. If these are false positives, there needs to be a way to filter those out.
My guess is the account was making changes to other accounts related to account on the device itself.

**Comment by v-amolpatil** [comment]
Hi @holmbert095, thank you for flagging this. Apologies for the delayed response. If you still need assistance, please reply here within 5 business days.

**Comment by v-dvedak** [comment]
Since we have not received a response in the last 5 days, we are closing your issue #<2891> as per our standard operating procedures. If you still need support for this issue, feel free to re-open at any time. Thank you for your co-operation.
