### ISSUE TITLE
The ASIM parser for InfoBlox has an error in line 51

### ISSUE THREAD

**Issue by sorcia25** [Azure/Azure-Sentinel#2895]
The parser for InfoBlox in the ASIM type has an error in line 51:

Actual: NetworkProtocol = iff (EventSubType=='re**a**ponse', tostring(dnsclient[3]),""),   
Mustbe_ NetworkProtocol = iff (EventSubType=='re**s**ponse', tostring(dnsclient[3]),""),

**Comment by oshezaf** [comment]
Thanks @sorcia25! I now fixed the typo.
