### ISSUE TITLE
All-In-One Azure Active Directory data connector doesn't enable Audit or Sign-in Logs

### ISSUE THREAD

**Issue by JonTheNiceGuy** [Azure/Azure-Sentinel#2901]
**Describe the bug**
While the All-in-One ["enables" the Azure Active Directory data connector](https://github.com/Azure/Azure-Sentinel/blob/d1ac91202318ea9fce675439c545f843197af2e0/Tools/Sentinel-All-In-One/ARMTemplates/LinkedTemplates/dataConnectors.json#L148-L163) it doesn't actually enable either of the diagnostics settings ("AuditLogs" or "SignInLogs") to be sent to the LA Workspace.

**To Reproduce**
1. Create custom deployment, using [azuredeploy.json](https://github.com/Azure/Azure-Sentinel/blob/d1ac91202318ea9fce675439c545f843197af2e0/Tools/Sentinel-All-In-One/ARMTemplates/azuredeploy.json)
2. Click into Sentinel -> Data Connectors -> Azure Active Directory
3. Note that it doesn't ever show "Connected"
4. Click into Azure Active Directory connector, and enable "Sign-in Logs" (in a Azure AD P1/P2 enabled environment) or "Audit Logs" (OR, go into Azure Active Directory, select Diagnostic Settings, add new diagnostic setting, and enable "AuditLogs" and "SignInLogs" (again, assuming Azure AD P1/P2) and direct it to your LA Workspace.

**Expected behavior**
I expected that the ARM Template would enable at least Audit Logs when you enabled the Azure AD connector.

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Edge
 - Version: 92.0.902.67

**Comment by javiersoriano** [comment]
HI @JonTheNiceGuy ,

There are two versions of All-in-One, one based on ARM template and one based on powershell script. The one based on powershell does enable Azure AD Audit and SignIn logs, but the one based on ARM doesn't do that.

We tried to make this clear in the documentation posted here: https://github.com/Azure/Azure-Sentinel/tree/master/Tools/Sentinel-All-In-One, but let me know if we should make it more clear.

Regards

**Comment by javiersoriano** [comment]
answered above
