### ISSUE TITLE
Bug - Start-MDEAutomatedInvestigation 

### ISSUE THREAD

**Issue by Xebus-Systems** [Azure/Azure-Sentinel#2937]
When deploying Start-MDEAutomatedInvestigation the package comes up with the following error

Error code

InvalidTemplate
Message
The template validation failed: 'The template action 'Post_a_message_(V3)' at line '1' and column '2137' is not valid: "Unable to parse template language expression '*sanitized*': expected token 'RightParenthesis' and actual 'EndOfData'.".'.

**Comment by dicolanl** [comment]
@Xebus-Systems did you enter a number in the teamsID and ChannelID parameters field?  if you leave them blank it will have an error.

**Comment by Xebus-Systems** [comment]
I put in 123 in each field I was wondering if the json for the comment v3 has been updated or something

**Comment by Xebus-Systems** [comment]
@dicolanl see above :)

**Comment by dicolanl** [comment]
@Xebus-Systems ill have to check this out when im back next week.
