### ISSUE TITLE
Cisco ISE playbook - CiscoISE-FalsePositivesClearPolicies needs update

### ISSUE THREAD

**Issue by v-maudan** [Azure/Azure-Sentinel#2949]
**Describe the bug**

https://github.com/Azure/Azure-Sentinel/blob/master/Solutions/Cisco%20ISE/Playbooks/CiscoISE-FalsePositivesClearPolicies/azuredeploy.json

**WatchlistName , WatchlistFieldName** These variables declared but not used in this playbook.

Getting following error while creating solution.[run arm-ttk cmd]
![image](https://user-images.githubusercontent.com/75478517/131646745-2e7a67fa-fe0e-4da8-8606-12a1e761565e.png)

**Comment by v-maudan** [comment]
@vu-socprime, Can you please check and fix ? Thanks!

**Comment by v-rucdu** [comment]
@socprime : This is blocking us from creating the package for Cisco ISE playbooks. So, could you please let us know when can we expect a fix for this? Thanks!!!!

**Comment by vu-socprime** [comment]
> @socprime : This is blocking us from creating the package for Cisco ISE playbooks. So, could you please let us know when can we expect a fix for this? Thanks!!!!

@v-rucdu Fixed in PR https://github.com/Azure/Azure-Sentinel/pull/2969
