### ISSUE TITLE
MITRE ATT&CK for Azure Sentinel.ipynb

### ISSUE THREAD

**Issue by frenchish** [Azure/Azure-Sentinel#2955]
Hi 

I am trying to make use of the "MITRE ATT&CK for Azure Sentinel.ipynb", but am getting errors on when running the clean_and_process_data() function, I have mode no modifications but it throws the below error.

I thought it might be the empty lists in the data frame so do try skipping those but then get other error, not sure how to fin d the root of the problem so am just raising the error with the default code.

AttributeError: 'float' object has no attribute 'keys'
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-40-88159df04365> in <module>
----> 1 result = clean_and_preprocess_data(df=sentinel_github_df)
      2 
      3 # Append the Fusion dataset to Pre-procesed result
      4 result = result.append(fusion_df, ignore_index=True)
      5 result.head()

<ipython-input-2-e12450333194> in clean_and_preprocess_data(df)
    247         )
    248     # Apply Data wrangling to derive columns from Json response
--> 249     builtin_dataconn_expanded = pd.DataFrame(
    250         builtin_dataconnectors["requiredDataConnectors"].values.tolist()
    251     )

~\anaconda3\envs\pandas_playground\lib\site-packages\pandas\core\frame.py in __init__(self, data, index, columns, dtype, copy)
    568                     if is_named_tuple(data[0]) and columns is None:
    569                         columns = data[0]._fields
--> 570                     arrays, columns = to_arrays(data, columns, dtype=dtype)
    571                     columns = ensure_index(columns)

**Comment by ashwin-patil** [comment]
Bugfixes checked in PR #4221
