### ISSUE TITLE
M365 Defender Data connector CompromisedEntity incorrect value

### ISSUE THREAD

**Issue by Lodewyk-Git** [Azure/Azure-Sentinel#2972]
**Describe the bug**
The CompromisedEntity column is most of the time filled in with the wrong value for alerts coming from MDI

**To Reproduce**
1. Go to 'Sentinel'
2. Click on 'Data conectors'
3. Scroll down to 'M365 Data Connector'
4. Enable ingestion
5. Investigate Alert
6. See error

**Expected behavior**
For the compromised entity to be an actual user/device/entity

**Screenshots**
![image](https://user-images.githubusercontent.com/36856692/132322230-f5ad86e8-8c79-4a7b-a69b-4fa383aaa6af.png)
![image](https://user-images.githubusercontent.com/36856692/132322348-62efb7c7-53b2-4d57-a8e3-83ab045d4a06.png)

**Comment by v-rucdu** [comment]
This is a first party connector, hence forwarding to Shay from Data Collection and Processing team... Thanks!!

**Comment by v-rucdu** [comment]
@Lodewyk-Git : Could you please submit a ticket with Azure Support Team and provide the required details..... If possible please select the owning Team as **Azure Sentinel --> Data Collection and Processing** 
Thanks!!

**Comment by v-rucdu** [comment]
Closing this Issue.. as asked customer to raise the ticket... Thanks!!!
