### ISSUE TITLE
Template regarding "Rare subscription-level operations in Azure" may not useful

### ISSUE THREAD

**Issue by Carter-ChenC** [Azure/Azure-Sentinel#2976]
**Describe the bug**
The script is here: https://github.com/Azure/Azure-Sentinel/blob/2cad1a602c99d6e3f8be2548e31e4ca63ed75c6f/Detections/AzureActivity/RareOperations.yaml

I believe this script will never return any result.

For the value of the ‘OperationNameValue’, it looks like this:
![image](https://user-images.githubusercontent.com/83210873/132457782-c2fd088b-595e-4dce-8d9e-421d91e41f2f.png)

Thus, when we define SensitiveOperationList to "List keys", "List Storage Account Keys", "Register Subscription", "Create or Update Snapshot", "Create or Update Network Security Group", they will never meet the value of ‘OperationNameValue’:
![image](https://user-images.githubusercontent.com/83210873/132457841-8773faf2-178e-4bc3-a132-79a7e496be04.png)

However, when I switch one of those parameters inside the list:
![image](https://user-images.githubusercontent.com/83210873/132457923-78e88e1d-4e0f-485b-a8d5-c38fa6adbacb.png)

Then, there will be some results that can be met.

**Expected behavior**
Reedit the template to make it functional.

**Comment by aprakash13** [comment]
Issue fixed. Closing it now.
