### ISSUE TITLE
Identity Protection mapping incorrect Account Entity

### ISSUE THREAD

**Issue by Lodewyk-Git** [Azure/Azure-Sentinel#2992]
**Describe the bug**
The Account entity is mapping incorrectly from Identity Protection to Sentinel, but under the events the correct account name is displayed.

**To Reproduce**
1. Trigger unfamiliar sign in properties alert
2. Connect AAD IP to Sentinel
3. View Unfamiliar Sign-in Properties Incident

**Expected behavior**
Correct Entity to be mapped

**Screenshots**
![image](https://user-images.githubusercontent.com/36856692/132866588-dbe84d78-7741-4445-a4dd-6479c5f467a6.png)

**Comment by v-mchatla** [comment]
Hi @Lodewyk-Git 
I have tried reproducing the issue with 2.0.1 version of the package by triggering the analytic Rule Correlate Unfamiliar sign-in properties and atypical travel alerts. I don't see any entities. Can you please provide more details in reproducing the issue, if the issue still persists.
![image](https://user-images.githubusercontent.com/108806639/198281077-89351765-bd26-4dcc-97ea-0174c2448130.png)
Thanks

**Comment by Lodewyk-Git** [comment]
Hi @v-mchatla 

I also don't see the wrong account getting mapped after the update. Although I do see that in a lot of cases the only thing being mapped is an IP.
