### ISSUE TITLE
Playbooks template "Restrict-MDEDomain" bug

### ISSUE THREAD

**Issue by ityankel** [Azure/Azure-Sentinel#2996]
**Describe the bug**
When deploying the playbook from the GitHub repo it deploys successfully but opens broken in the LogicApp designer.
I suspect the reason is a naming mismatch - in the $parameters section of the template the Sentinel connection is called 'azuresentinel' but in the trigger and incident comment actions it is referenced as 'azuresentinel_1'

**Screenshots**
![image](https://user-images.githubusercontent.com/47292630/132985668-6317b69f-dbd5-469b-8380-f1292440df0c.png)

**Comment by dicolanl** [comment]
@ityankel good find.  PR submitted above.
