### ISSUE TITLE
DEV-0322 Serv-U related IOCs - July 2021

### ISSUE THREAD

**Issue by anfisher1967** [Azure/Azure-Sentinel#3040]
When you try to enable the DEV-0322 Serv-U related IOCs - July 2021 you get an error in Set Rule Logic. See Screen Shot
![Dev-0322](https://user-images.githubusercontent.com/33937240/133506012-b75e30e7-9466-4cd5-9856-2f6876b8201f.JPG)

**Comment by v-amolpatil** [comment]
Hi @anfisher1967 , thank you for flagging this. Apologies for the delayed response. If you still need assistance, please reply here within 5 business days.

**Comment by v-dvedak** [comment]
Since we have not received a response in the last 5 days, we are closing your issue #<3040> as per our standard operating procedures. If you still need support for this issue, feel free to re-open at any time. Thank you for your co-operation.
