### ISSUE TITLE
SOURGUM Actor IOC - July 2021

### ISSUE THREAD

**Issue by anfisher1967** [Azure/Azure-Sentinel#3041]
*Get an error when creating the SOURGUM Actor IOC - July 2021 analytic rule.  Fails in the Set Rule Logic step
![Sourgum](https://user-images.githubusercontent.com/33937240/133508561-f24a32a8-c985-4095-ae82-c43bc835c36f.JPG)

**Comment by anfisher1967** [comment]
Did this ever get fixed? I'm still getting the same errors in the portal.

**Comment by aprakash13** [comment]
We have some Github validation issues going on currently but we will get this fixed by the end of the week @anfisher1967

**Comment by PawelLiebich** [comment]
Hi, Any update in this case?

**Comment by v-amolpatil** [comment]
Hi @anfisher1967 , thank you for flagging this. Apologies for the delayed response. If you still need assistance, please reply here within 5 business days.

**Comment by v-dvedak** [comment]
Since we have not received a response in the last 5 days, we are closing your issue #<3041> as per our standard operating procedures. If you still need support for this issue, feel free to re-open at any time. Thank you for your co-operation.
