### ISSUE TITLE
Workbook AzureDDOS

### ISSUE THREAD

**Issue by SimoneFrigerio** [Azure/Azure-Sentinel#3046]
https://github.com/Azure/Azure-Sentinel/blob/master/Workbooks/AzDDoSStandardWorkbook.json
this workbook is not working with Azurediagnostic table bigger then 500 Column
Could you please review?

**Comment by ashishsyal** [comment]
@v-rucdu Please review this one.

**Comment by v-maudan** [comment]
@SimoneFrigerio,Could you please verify attached workbook and let us know if you still facing any issue. Thanks!
[AzDDoSStandardWorkbook.txt](https://github.com/Azure/Azure-Sentinel/files/7267999/AzDDoSStandardWorkbook.txt)

**Comment by v-rucdu** [comment]
@SimoneFrigerio : There seems to be multiple issues raised for the same issue... i will close this one as duplicate of the other.., and we can track it from there... Thanks!!!

Duplicate Issue : https://github.com/Azure/Azure-Sentinel/issues/3221
