### ISSUE TITLE
Incident Response Playbooks Crashing

### ISSUE THREAD

**Issue by NRuzickaCyberMSI** [Azure/Azure-Sentinel#3069]
Bug Description
This bug applies to the 3 AAD user response playbooks (block, reset password, and revoke session) and the 2 isolate Azure resource playbooks (isolate VM and isolate storage space). I have spent more than 2 work weeks troubleshooting these playbooks and I still cannot get them to run successfully. They all involve complex incident response actions and as a result crash with a wide variety of error messages. 

How to Reproduce the Issue
I have had multiple other analysts at my company try to run these playbooks using the instructions in the Read Me file, and the playbooks always crash with the same initial errors. The issue can be reproduce by following the instruction in the Read Me for each playbook, they always crash after running regardless of what you do within the bounds of the author's instructions.

Expected Behavior
The status of the playbooks in the run history should be "succeeded" without a crashing error message and get the described task finished. 

Screenshots Explanation
I have added some screenshots of the most recent crashing errors that I am getting from the playbooks. Others that try to use these playbooks out of the box will have to do many other troubleshooting steps before they get to this point. I will leave the solutions to the initial issues that I have discovered in the Additional Context section. The AAD response actions are crashing because they do not recognize the identities associated with a directory where the managed identity is a User Admin. The isolate azure resource playbooks are crashing because they cannot recognize the variable created in the 3rd for each loop.

Desktop Information
 - OS: Windows 10 version 2004
 - Browser: Tried on the most recent versions of both Chrome and Edge

Additional Context
All of these playbooks were made by the same person Nicholas DiCola (username dicolanl). If this user is still around I would greatly appreciate if you could update either your workbooks or instructions so that people using your playbooks can avoid the errors that everyone at my company is running into.

Steps needed for AAD response playbooks: Managed identities are mandatory, the other identity options do not work. Give the managed identity for each playbook User Administrator in AAD and RBAC Sentinel Contributor, the script in the Read Me for the playbooks does not work not matter how much you edit the script based on the error messages and even with global admin activated. 

Steps needed for isolate Azure resource playbooks: Managed identities are also mandatory, the managed identities need to have RBAC Sentinel Contributor, Network Contributor, and their respective resource's Contributor (VM or Storage). If the Azure resource that the playbook wants to isolate cannot be found in the entities of an incident, it will claim the automation succeeded when it did not.

![GitHub_Playbook_Bug_Report_Isolate_Azure_Resource](https://user-images.githubusercontent.com/72464295/133844526-100b7b89-a1bc-4283-8533-eccbe8b6dc3b.PNG)
![GitHub_Playbook_Bug_Report_AAD_IR_2](https://user-images.githubusercontent.com/72464295/133844529-1f2ddfde-c10f-4f68-8caa-033a621aed7b.PNG)
![GitHub_Playbook_Bug_Report_AAD_IR_1](https://user-images.githubusercontent.com/72464295/133844531-42d0407a-3233-4fbe-962b-5869e3a2610a.PNG)

**Comment by sreedharande** [comment]
@NRuzickaCyberMSI - Are you still having issues with those Playbooks

**Comment by v-laanjana** [comment]
@NRuzickaCyberMSI - Are you still having issues with those Playbooks?

**Comment by NRuzickaCyberMSI** [comment]
I submitted this ticket over a year ago, I'm baffled at how dysfunctional playbooks and the support both are. Please close the ticket, it is clear that the Microsoft GitHub team does not care about their Microsoft Partners working with their tools.


Nathaniel Ruzicka

Manager of Security Engineering and Operations, CyberMSI

Email: ***@***.******@***.***>

Mobile/WhatsApp: +1 (847) 922-6283<tel:18479226283>

________________________________
