### ISSUE TITLE
Azure AD Sign-in logs' Sign-ins by Location not working for large amounts of data

### ISSUE THREAD

**Issue by Lodewyk-Git** [Azure/Azure-Sentinel#3086]
**Describe the bug**
The Sign-ins by Location query looks fine to me, it works when I run it separately in a LAW, but for some reason it's not working correctly in the workbook. All other queries are working correctly.

**To Reproduce**
1. Go to 'Azure AD Sign-in logs'
2. Have almost 1M sign-ins
3. Scroll down to 'Sign-ins by Location'

**Expected behavior**
Correct values as shown in LAW

**Screenshots**
![Sign-In Workbook](https://user-images.githubusercontent.com/36856692/134146389-34a4808f-46ad-4049-b834-d09e53fce2ee.png)

**Comment by preetikr** [comment]
@nazang - Is it possible to please look into this? Thanks.

**Comment by Lodewyk-Git** [comment]
Seeing this same problem across multiple (10+) workspaces

![image](https://user-images.githubusercontent.com/36856692/135618854-33ac30cf-83ab-4e81-9eaf-6a27f5962ef4.png)

**Comment by v-laanjana** [comment]
@nazang - Is it possible to please look into this? Thanks.

**Comment by v-amolpatil** [comment]
Hi @Lodewyk-Git , thank you for flagging this. Apologies for the delayed response. If you still need assistance, please reply here within 5 business days.

**Comment by v-amolpatil** [comment]
Gentle Reminder: We are awaiting for your response on this issue. If you still need to keep this issue active please respond within next 2 days. If we don't receive response by 16 Feb 2023, we will close this issue.

**Comment by v-amolpatil** [comment]
Since we have not received a response in the last 5 days, we are closing your issue #3086 as per our standard operating procedures. If you still need support for this issue, feel free to re-open at any time. Thank you for your co-operation.
