### ISSUE TITLE
Compatibility with Cisco Umbrella logs version 6

### ISSUE THREAD

**Issue by piercosta** [Azure/Azure-Sentinel#3100]
**Is your feature request related to a problem? Please describe.**
Cisco Umbrella data connector. 

We are currently unable to switch to Umbrella Logs version 6, because the function app does not parse the new fields. it seems that the funcion app is compatible until version 4.

https://docs.umbrella.com/deployment-umbrella/docs/log-formats-and-versioning

https://github.com/Azure/Azure-Sentinel/blob/master/DataConnectors/CiscoUmbrella/ciscoUmbrellaDataConn/__init__.py

![image](https://user-images.githubusercontent.com/664328/134588564-4e676ef7-2eff-46e2-bd31-e8ada582cce6.png)

![image](https://user-images.githubusercontent.com/664328/134589188-e4a983dc-bffb-4bba-bf40-e89a89cf2dfa.png)

**Describe the solution you'd like**
I would like Cisco Umbrella data connector to parse also the following fields:
Proxy logs:
Identities, Identity Types, Request Method, Certificate Errors, Destination Lists IDs, DLP Status, File Name, Rule ID, and Ruleset ID.

**Describe alternatives you've considered**
Is Microsoft mantaining this data connector or should I contact Cisco to implement the feature?

**Additional context**
I believe this could be considered also a bug, since new Umbrella customer start with version 6 logs and are unable to use the connector. 
That's just a theory, I have not tested it.

**Comment by v-rucdu** [comment]
@piercosta :  We are working on upgrading the Azure Function to support version 5 and 6 log formats.
Meanwhile, if you can share some sample proxy logs from cisco(by masking any PI or security information) with us that would be helpful.

Thanks!!!

**Comment by ashishsyal** [comment]
@piercosta - Can you share some sample proxy logs from cisco(by masking any PI or security information) with us that would be helpful

**Comment by piercosta** [comment]
Hi,
sorry for the delays.I will send you some example of the logs as soon as
possible.
Thanks for your feedback.

Best Regards,
Pier


Il gio 14 ott 2021, 08:18 ashishsyal ***@***.***> ha scritto:

**Comment by v-maudan** [comment]
@piercosta, Did you get chance to test provided package? let me know if any help needed. Thanks!

**Comment by piercosta** [comment]
Hi,
sorry but at the moment I am not able to correctly test the function, since
we don't have a test environment, only production.

Il lun 1 nov 2021, 18:20 v-maudan ***@***.***> ha scritto:

**Comment by v-rucdu** [comment]
@piercosta : We have merged the PR after getting it tested with the help of other customer... Thanks!!!
