### ISSUE TITLE
Playbooks template "AdvancedSNOWTeamsIntegration" bug

### ISSUE THREAD

**Issue by ityankel** [Azure/Azure-Sentinel#3153]
There are several issues with the template:
1. There are 2 resources of type 'Microsoft.Web/connections' for the Azure Sentinel connection - one with managed identity and one without. This prevents the template from being deployed (see screenshot below). The template should contain only 1 deployed connection for Azure Sentinel that uses managed identity (this will require updating the deployed playbooks to use Azure Sentinel with managed identity)
2. The template references in several places a connection with name 'ARMConnectionName' but there is no corresponding resource being deployed with that name
3. The Teams connection resource (with name TeamsConnectionName) uses the display name for the Azure Sentinel connection by mistake
4. The Azure Sentinel connection reference under $connections in the 'ip-checkIPOnVirusTotal' playbook actually uses the name and id of the VirusTotal connection instead of the Azure Sentinel connection

![image](https://user-images.githubusercontent.com/47292630/135748300-cc7910a8-50a6-4a6c-821f-bb8ca4162e18.png)

**Comment by lior-tamir** [comment]
@sreedharande can you please help with solving these bugs? Or ask the author?
Until they are fixed, we will not show it in the Public Preview for playbook templates tab.

**Comment by Lnunovero92** [comment]
@sreedharande please your help, we have the same problem until this date.

Thanks in advance.
