### ISSUE TITLE
CEF Collector in Azure Portal has typo on command block

### ISSUE THREAD

**Issue by AzureAzim** [Azure/Azure-Sentinel#3175]
**Describe the bug**

When you go to configure the CEF Collector, the command block has a typo, causing the command to fail

"sudo wget -O cef_installer.py https://raw.githubusercontent.com/Azure/Azure-Sentinel/master/DataConnectors/CEF/cef_installer.py&&sudo python cef_installer.py WS REDACTED KEY REDACTED"

Should be 

"sudo wget -O cef_installer.py https://raw.githubusercontent.com/Azure/Azure-Sentinel/master/DataConnectors/CEF/cef_installer.py && sudo python cef_installer.py WS REDACTED KEY REDACTED"

**To Reproduce**
1. Go to 'Azure Sentinel CEF Collector page'
2. Click on 'Run the following command to install and apply the CEF collector:'
3. Paste into linux command line
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.111.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 503 first byte timeout
2021-10-05 09:38:20 ERROR 503: first byte timeout.

**Expected behavior**
Downloads, installs, and configures CEF Collector

**Screenshots**
![image](https://user-images.githubusercontent.com/11980156/136036504-96c1c2c5-39cf-44fb-a4ce-dcbdd9f94ffd.png)

**Desktop (please complete the following information):**
 - OS: [Windows 10 21h1
 - Browser Chrome

**Additional context**

**Comment by sarah-yo** [comment]
As this is a UI bug and not related to Github content, please can you raise a ticket to Support via the Azure portal to fix this, thanks!
