### ISSUE TITLE
Netskope Connecter does not work with Rest API v2

### ISSUE THREAD

**Issue by fnifni** [Azure/Azure-Sentinel#3181]
**Describe the bug**
The DESCRIPTION for the Netskope connector states that it should use Netskope's Rest API v2 token.
However, the GetUrl function says to generate a v1 URL.
Netskope's v1 URLs will not accept Rest API v2 tokens.

**To Reproduce**
1. In the configured Netskope Connecter Function App
2. Select "Conigration" on the Netskope Connecter Function App screen you configured.
3. Replace the value of the parameter "apikey" with the Rest API v2 token and save it.
4. Restart the Function App.
5. No new logs will flow into Netskope_CL.

Additional information
Replace the value of the parameter "apikey" with the Rest API v1 token, and new logs will flow into Netskope_CL.

Translated with www.DeepL.com/Translator (free version)

**Expected behavior**
In the Description, please indicate that you want to use the Rest API v1.

**Screenshots**
There is no screenshot because it is a specification error.

**Desktop (please complete the following information):**
Since this is an error in the specification, the desktop environment is irrelevant.

**Smartphone (please complete the following information):**
Since this is an error in the specification, the desktop Smartphone is irrelevant.

**Additional context**
The Netskope connector does not perform any error handling.
If an HTTP request error occurs due to a shaky Internet connection or a temporary malfunction of the Netskope tenant, logging will be aborted.
Also, the Netskope connector does not take rate limits into account.
If a rate limit is violated, an HTTP error (status code 429) will be returned and logging will be aborted without error handling.

For more information on rate limits for v1 and v2, please refer to the following
https://docs.netskope.com/en/rest-api-v1-overview.html
https://docs.netskope.com/en/rest-api-v2-overview.html

**Comment by v-rucdu** [comment]
Hey @fnifni : Thanks for raising this issue. This is more of a new feature request and not an issue. we have created a work item for the same and will be working on it as time permits...  

Thanks
Ruchita

**Comment by anthonysomerset** [comment]
Can i suggest this be re-opened as an issue - if the connector only supports V1 then the documentation needs to reflect that its the V1 API that needs to be configured and the azure sentinel connector page also refers to the v2 api docs with a broken docs link as well
