### ISSUE TITLE
Playbooks template "Send-email-with-formatted-incident-report" bug

### ISSUE THREAD

**Issue by patzak88** [Azure/Azure-Sentinel#3205]
Hello,

I am trying to implement this playbook and when I click Run Playbook, I get the following error at step "Select Entities":

"BadRequest. The 'from' property value in the 'select' action inputs is of type 'Null'. The value must be an array."

I used this playbook in the past as it is, and it worked. Now it doesn`t work anymore. Has something changed ?

Any help would be appreciated. Thank you

![Capture](https://user-images.githubusercontent.com/49722406/136800742-f99e9d5f-81ae-472c-ad4e-e0c169b3208c.PNG)
?

**Comment by BenjiSec** [comment]
Hi @adyp1988  - is this happening on all Incidents or only on specific one? Where it is failing, it looks like there is no Entity field in the incident at all (null value). Even if incident doesn't have entity, Entity field should be there but empty. I re-deployed playbook and tested on 2 incident, with and without entity, and it worked with no issues. 
Did you try re-deploying the playbook?

**Comment by adyp1988** [comment]
Hello @BenjiSec,

thank you for your feedback.
Yes, i have redeployed it several times and I have the same issue. I ran it manually over snd over agsin and still same issue. But in the past worked just fine.
