### ISSUE TITLE
Azure DDOS Workbook Error

### ISSUE THREAD

**Issue by sifriger-msft** [Azure/Azure-Sentinel#3221]
Describe the bug
the AzureDiagnostic schema table is change and the workbook need a refresh
https://github.com/Azure/Azure-Sentinel/blob/master/Workbooks/AzDDoSStandardWorkbook.json

To Reproduce
many query are in error
this is an piece example of the query
|Extend TopAttackVector = tostring(parse_json(AttackVectors_s)[0])
how to fix it adding the new schema field "AdditionalField"
|Extend TopAttackVector = tostring(parse_json(AdditionalFields.AttackVectors_s)[0])
Expected behavior
Screenshots
 
 
![ddos-1](https://user-images.githubusercontent.com/82639336/137270883-c7696c48-7228-4f86-8e45-10cf5e707e14.jpg)

**Comment by SimoneFrigerio** [comment]
Adding cx
@Davide ***@***.***>

**Comment by seb-sudo** [comment]
I am also having this issue

**Comment by v-rucdu** [comment]
Hey.. we are looking into this issue and would get back to you asap... Thanks!!!

**Comment by vmanojreddy** [comment]
@SimoneFrigerio, The issue is not repro for us. Can you Please schedule call to discuss the issue. I'm available on IST timing's. Thanks!!!

**Comment by v-rucdu** [comment]
Hey @SimoneFrigerio : Can you please let us know if the issue still persist for you... can you please share us your availability and email address so that we can schedule a call with you and do some troubleshooting to resolve it... Thanks!!!
