### ISSUE TITLE
Please Provide  Sample Data

### ISSUE THREAD

**Issue by andriykozynets** [Azure/Azure-Sentinel#3225]
Please Provide  Sample Data

_Originally posted by @vmanojreddy in https://github.com/Azure/Azure-Sentinel/issues/3198#issuecomment-943270138_

Hi!

I am not sure how to do that. Let me explain. Our integration is not dealing with log analytics per se. We provide an azure function which creates/updates Sentinel Incidents with REST API calls https://docs.microsoft.com/en-us/rest/api/securityinsights/incidents/create-or-update
We don't analyze logs or events, we don't create incidents based on rules and alerts - we only create Incidents directly with REST API calls.
We do define one data type SYNACK_VULNERABILITY in Synack_API_FunctionApp.json file. But we never use it. The only reason it is there is because the Data Connector page defined by Synack_API_FunctionApp.json reports an error if I try to use an empty array of data types like this "dataTypes": [].
So, in this context, I am not sure how to provide sample data. Our data type SYNACK_VULNERABILITY is a kind of stub. I did check some examples of Sample Data provided by Cisco Umbrella connector (we used it as a reference when working on ours) - these are for the data types. For example https://github.com/Azure/Azure-Sentinel/blob/master/Sample%20Data/Custom/Cisco_Umbrella_ip_CL.json
Unfortunately we cannot provide something like this for our "data type".

We are open to suggestions and can work on some sample data, but need some further guidance on how to do that.

Thank you!

**Comment by vmanojreddy** [comment]
@andriykozynets  : We are closing this issue. The related [pr](https://github.com/Azure/Azure-Sentinel/pull/3198) has been closed. Please feel free to reopen the issue if you need any more details.Thanks!!
