### ISSUE TITLE
Playbooks template "SyncJIRAAssignedUser" bug

### ISSUE THREAD

**Issue by ityankel** [Azure/Azure-Sentinel#3239]
The prerequisite step numbering in the template metadata is incorrect (the number 3. appears twice), which causes the steps to be displayed with incorrect numbers in the Sentinel portal

![image](https://user-images.githubusercontent.com/47292630/137704108-aad638be-4c2e-4500-b653-1d38c2f721da.png)
![image](https://user-images.githubusercontent.com/47292630/137704147-fe89530b-c595-4861-9860-8769699f40ff.png)

**Comment by lior-tamir** [comment]
https://github.com/Azure/Azure-Sentinel/pull/3248
@sreedharande  can you please approve?

**Comment by v-laanjana** [comment]
![image](https://user-images.githubusercontent.com/105694882/197114119-da716c2a-20c1-4a5e-8d9d-c45e5a598b65.png)
