### ISSUE TITLE
Azure Information Protection workbook queries broken

### ISSUE THREAD

**Issue by nfields03** [Azure/Azure-Sentinel#326]
It looks like the table for the Azure Information Protection workbook changed from "InformationProtectionEvents to a custom log source called "InformationProtectionLogs_CL".  The workbook queries the old table name still so all the queries are broken.  No biggie, but hopefully the workbook can get updated soon.

**Comment by orashken** [comment]
Thanks for noticing this issue. 
I've created and merged this [pull request](https://github.com/Azure/Azure-Sentinel/pull/334) to work with the correct table.
It will be updated in Azure portal in next deployment cycle.

**Comment by shainw** [comment]
Closing, this is resolved and the UX should have it.
