### ISSUE TITLE
Juniper SRX parser doesnt work. 

### ISSUE THREAD

**Issue by m-ahmee** [Azure/Azure-Sentinel#3268]
Only a few basic columns are populated. 
![image](https://user-images.githubusercontent.com/54971725/138381080-db59a9a0-2fd0-4067-9884-28623a6c4d22.png)
![image](https://user-images.githubusercontent.com/54971725/138381130-affc3d21-345f-42a8-a2e9-e4a781d50ede.png)

Here is a sample of syslogs that are sent to Sentinel through the collector.  The format appears different from the one shown in the examples in the function.
Oct 22 09:55:42 testnash-vsrx RT_FLOW: RT_FLOW_SESSION_CREATE: session created 192.168.10.30/57380->8.8.8.8/53 0x0 junos-dns-udp 10.20.0.10/18508->8.8.8.8/53 0x0 source rule source-nat-rule N/A N/A 17 AD-permit trust untrust 2983 N/A(N/A) ge-0/0/1.0 UNKNOWN UNKNOWN UNKNOWN N/A N/A -1 N/A N/A N/A Off root
Oct 22 09:55:42 testnash-vsrx RT_FLOW: RT_FLOW_SESSION_CREATE: session created 192.168.10.30/57246->13.70.72.234/443 0x0 junos-https 10.20.0.10/26973->13.70.72.234/443 0x0 source rule source-nat-rule N/A N/A 6 AD-permit trust untrust 2984 N/A(N/A) ge-0/0/1.0 UNKNOWN UNKNOWN UNKNOWN N/A N/A -1 N/A N/A N/A Off root
Oct 22 09:55:44 testnash-vsrx RT_FLOW: RT_FLOW_SESSION_CLOSE: session closed TCP FIN: 192.168.10.30/57246->13.70.72.234/443 0x0 junos-https 10.20.0.10/26973->13.70.72.234/443 0x0 source rule source-nat-rule N/A N/A 6 AD-permit trust untrust 2984 10(3737) 13(4971) 2 UNKNOWN UNKNOWN N/A(N/A) ge-0/0/1.0 UNKNOWN N/A N/A -1 N/A NA 0 0.0.0.0/0->0.0.0.0/0 NA NA N/A N/A Off root 0
Oct 22 09:55:46 testnash-vsrx RT_FLOW: RT_FLOW_SESSION_CLOSE: session closed Closed by junos-alg: 192.168.10.30/57380->8.8.8.8/53 0x0 junos-dns-udp 10.20.0.10/18508->8.8.8.8/53 0x0 source rule source-nat-rule N/A N/A 17 AD-permit trust untrust 2983 1(71) 1(87) 4 UNKNOWN UNKNOWN N/A(N/A) ge-0/0/1.0 No N/A N/A -1 N/A NA 0 0.0.0.0/0->0.0.0.0/0 NA NA N/A N/A Off root 0

**Comment by v-rucdu** [comment]
Hey.. we are looking into this issue and would get back to you asap... Thanks!!!

**Comment by v-jayakal** [comment]
@m-ahmee - As you mentioned there is a format difference between the sample data used for creation of this parser (reference here: https://github.com/Azure/Azure-Sentinel/blob/master/Sample%20Data/Syslog/JuniperSRX.json) and the format you mentioned above. Recently in such a scenario for a customer, we created a different version of Juniper Parser
[JuniperSRXTest5-Latest.txt](https://github.com/Azure/Azure-Sentinel/files/7811093/JuniperSRXTest5-Latest.txt)
Can you please create this as a test function by name "JuniperSRXTest" and check with your data and let us know whether this works or not?  Thanks.

**Comment by ritika-msft** [comment]
Hi,

We have made few changes to the parser to help improve the parser performance Juniper SRX Parser update for perf improvement by ritika-msft · Pull Request #3847 · Azure/Azure-Sentinel (github.com). Can you please follow below steps and save the function with a different name and update us if you see any improvement in parser performance?

1.	Open Log Analytics Workspace
2.	Open new Query window
3.	Copy and paste the updated query from the JuniperSRX.txt file provided in the PR Juniper SRX Parser update for perf improvement by ritika-msft · Pull Request #3847 · Azure/Azure-Sentinel (github.com).
4.	In the query window, on the second line of the query, enter the hostname(s) of your Juniper SRX device(s) and any other unique identifiers for the logstream. 
5.	For example: | where Computer in ("server1", "server2")
6.	Click on Save button and select as Function from drop down by specifying function name and alias as JuniperSRX_Test.
7.	Run the query to validate data is being received and parsed, and if there are any performance improvements?

Let us know if the query works fine. Thanks.

**Comment by m-ahmee** [comment]
Hi Team,
I have tried the new function and it working fine with RT logs. I havent tested with other type of security logs like UTM yet.
I have to use simple syslog format for the function to work. Is there a similar function that works with structured logs as well?
Thanks

**Comment by ritika-msft** [comment]
Hi @m-ahmee,
Can you provide us sample logs( structured logs) that you have mentioned in your comment above. Once we have the logs, we will test the changes and update you. Thanks!!

**Comment by v-jayakal** [comment]
@m-ahmee - Closing this issue as there is no response on this for more than a month. Please re-open or create a new one if the issue persists and needs help. Thanks.
