### ISSUE TITLE
Need consitent Permissions on the Github Playbooks

### ISSUE THREAD

**Issue by bobsyourmom** [Azure/Azure-Sentinel#3298]
Problem: Using the Sentinel Playbooks requires serious preparation related to permissions. These permissions are inconsistent from one playbook to another.

Solution: Use Managed identities and a powershell script wherever possible. Many of the playbooks already have these, but others recommend app registrations or very broad permissions like resource contributor.

eg: Get-MDEFileActivityWithin30Mins
add a powershell script for managed identities rather than use an app registration. eg:

$MIGuid = "[ enter managed identity ]"
$MI = Get-AzureADServicePrincipal -ObjectId $MIGuid
$MDEAppId = "fc780465-2017-40d4-a0c5-307022471b92"
$PermissionName = "Machine.ReadWrite.All" 
$MDEServicePrincipal = Get-AzureADServicePrincipal -Filter "appId eq '$MDEAppId'"
$AppRole = $MDEServicePrincipal.AppRoles | Where-Object {$_.Value -eq $PermissionName -and $_.AllowedMemberTypes -contains "Application"}
New-AzureAdServiceAppRoleAssignment -ObjectId $MI.ObjectId -PrincipalId $MI.ObjectId -ResourceId $MDEServicePrincipal.ObjectId -Id $AppRole.Id

**Comment by v-laanjana** [comment]
@lior-tamir  are you still having permission  issue ?

**Comment by v-amolpatil** [comment]
Hi @bobsyourmom , thank you for flagging this. Apologies for the delayed response. If you still need assistance, please reply here within 5 business days.

**Comment by v-amolpatil** [comment]
Gentle Reminder: We are awaiting for your response on this issue. If you still need to keep this issue active please respond within next 2 days. If we don't receive response by 16 Feb 2023, we will close this issue.

**Comment by v-amolpatil** [comment]
Since we have not received a response in the last 5 days, we are closing your issue #3298 as per our standard operating procedures. If you still need support for this issue, feel free to re-open at any time. Thank you for your co-operation.
