### ISSUE TITLE
Trigger an alert for each event should't have number of alerts generated capped at 20

### ISSUE THREAD

**Issue by shikhin-metron** [Azure/Azure-Sentinel#3365]
I am creating a new custom connector for azure sentinel integration. The platform I am integrating with has their own statuses and severity, so when I ingest that data into the logs and promote it to azure sentinel incidents, it has status and severity as New and Medium(severity according to what I have set in analytic rules). I am syncing the status and severity using a playbook where it reads the description of alert(using analytic rule I have added status and severity info of other platform to description of incident) and then updates accordingly. If I get multiple events grouped into single alert, it will be impossible to update status or severity, or even keep track of and analyse those individual events as a threat analyst.

Please increase the cap to a much, much larger number so that it will not create problems for historical poll, or even better, don't keep a cap at all.

**Comment by sarah-yo** [comment]
Hello @shikhin-metron, please raise this as a feature request in Sentinel user voice, thanks!

https://feedback.azure.com/d365community/forum/37638d17-0625-ec11-b6e6-000d3a4f07b8?WT.mc_id=m365-0000-rotrent
