### ISSUE TITLE
Alert - Get incident does not work correctly all the time in logic app

### ISSUE THREAD

**Issue by shikhin-metron** [Azure/Azure-Sentinel#3366]
Running a logic app with alert trigger followed by Alert - Get incident action. It doesn't always run, and fails with error 404. The raw output is as follows:

```
{
    "statusCode": 404,
    "headers": {
        "Pragma": "no-cache",
        "x-ms-request-id": "5f988537-3544-4eb7-9ac3-fa4f1d2f3761",
        "Strict-Transport-Security": "max-age=31536000; includeSubDomains",
        "X-Content-Type-Options": "nosniff",
        "X-Frame-Options": "DENY",
        "Cache-Control": "no-store, no-cache",
        "Set-Cookie": "ARRAffinity=6dc3181dbc497137c79e4967b18e393ce974784d3b5dd4189dd87ea066e7fe9c;Path=/;HttpOnly;Secure;Domain=azuresentinel-uks.logic-ase-uksouth.p.azurewebsites.net,ARRAffinitySameSite=6dc3181dbc497137c79e4967b18e393ce974784d3b5dd4189dd87ea066e7fe9c;Path=/;HttpOnly;SameSite=None;Secure;Domain=azuresentinel-uks.logic-ase-uksouth.p.azurewebsites.net",
        "Timing-Allow-Origin": "*",
        "x-ms-apihub-cached-response": "false",
        "Date": "Tue, 02 Nov 2021 07:27:54 GMT",
        "Content-Length": "311",
        "Content-Type": "application/json",
        "Expires": "-1"
    },
    "body": {
        "error": {
            "code": 404,
            "source": "logic-apis-uksouth.azure-apim.net",
            "clientRequestId": "5f988537-3544-4eb7-9ac3-fa4f1d2f3761",
            "message": "The response is not in a JSON format.",
            "innerError": "Failed to run playbook - no incident found with the properties you provided"
        }
    }
}
```

If the alert trigger is running successfully, this problem should not arise.

**Comment by laglergruener** [comment]
Hi, any updates on that issue. I’ve the same problem on existing and new environments!

**Comment by shikhin-metron** [comment]
> Hi, any updates on that issue. I’ve the same problem on existing and new environments!

I have noticed that it doesn't happen when I put a delay of couple of seconds before Alert - Get incident action. It might be happening because multiple places that incident is getting accessed at the same time.

**Comment by laglergruener** [comment]
Awesome, thanks for your reply, you made my day! But that issue wasn't in the past available, because I always created the playbook without a delay. I'll test it thanks.

**Comment by dicolanl** [comment]
@lior-tamir to look into this.

**Comment by v-laanjana** [comment]
@lior-tamir any update on this?

**Comment by v-amolpatil** [comment]
Gentle Reminder: We are awaiting for your response on this issue. If you still need to keep this issue active please respond within next 2 days. If we don't receive response by 16 Feb 2023, we will close this issue.

**Comment by shikhin-metron** [comment]
No, I will not require further assistance, thanks. Closing the issue.

**Comment by winner19678** [comment]
Hi I am seeing the same issue here. The delay addition does not help.

I have been advised by Microsoft to do the following

'Switch your trigger from the Microsoft Sentinel alert trigger to the Microsoft Sentinel incident trigger. It will not fire until the incident is created and all the incident information (or at least most of it) will already be loaded'

Does this article need to be updated?

**Comment by pergyz** [comment]
Regarding the "Alert - Get Incident" action failing intermittently, I suggest implementing a "do until" loop with a 1-minute delay per iteration. Personally, I have set the loop to run for 60 iterations, but this might need adjustment based on other factors, such as playbook execution time.

<img width="815" alt="Screenshot 2024-08-14 095026-0" src="https://github.com/user-attachments/assets/50ba2b5a-be69-4b9b-b827-ab61cab20f77">
