### ISSUE TITLE
AzurePortalSigninfromanotherAzureTenant.yaml - Persistent storage path does not exist.

### ISSUE THREAD

**Issue by RyanStandbridge-QC** [Azure/Azure-Sentinel#3367]
**Describe the bug**
In line 3 of the analytic AzurePortalSigninfromanotherAzureTenant.yaml a hard coded URL path used within the analytic is no longer live. 

**To Reproduce**
1. Go to 'https://github.com/Azure/Azure-Sentinel/blob/master/Detections/SigninLogs/AzurePortalSigninfromanotherAzureTenant.yaml'
2. Scroll down to 'line 23'
3. See error

**Expected behavior**
Either a live link or a call to a list of IOCs expected for this analytic.

**Comment by aprakash13** [comment]
This has been fixed now. Closing this out.
