### ISSUE TITLE
Pulse secure parser for Azure Sentinel

### ISSUE THREAD

**Issue by annanra** [Azure/Azure-Sentinel#3370]
For standard log format with syslog type as below, the regex used in the pulseconnectsecure(function developed by @shainw and @acnccd) parser is not matching
'2021-11-03 01:20:46 - ive - [1.2.3.4] Jane, Mitchel(Employee)[] - Received OCSP response from '1.1.1.1' with url 'http://abc.com', user: 'Jane, Mitchel'  serial number: 'D8:DB:12:8A:DE:00:00:00:04:B1:8D''

Current regex :  (\d{4}\-\d{2}-\d{2})\s(\d{2}\:\d{2}:\d{2})\s(\S+)\s(\S+)\s(\S+)\s\[(\S+)\]\s(\S+,)\s(\S+)\((.*)?\)\[(.*)\]\s\-\s(.*)

Can someone help me with a regex which matches for all the below syslog messages

'2021-11-03 01:20:46 - ive - [1.2.3.4] Jane, Mitchel(Employee)[] - Received OCSP response from '1.1.1.1' with url 'http://abc.com', user: 'Jane, Mitchel'  serial number: 'D8:DB:12:8A:DE:00:00:00:04:B1:8D''

2020-05-01 05:36:14 - ive - [10.0.0.0] user100(ABC Realm)[Personal_PC No RDP] - WebRequest ok : Host: sample.abc.com, Request: GET /Citrix/XDSWeb/dample/js/ctxs.webui.min_0204820BD028.js HTTP/1.1

2020-05-01 00:07:21 - ive - [127.0.0.1] System()[] - User Accounts modified. Removed username ABC\user34 from authentication server ABC Active Directory.

**Comment by v-rucdu** [comment]
Hey.. we are looking into this issue and would get back to you asap... Thanks!!!

**Comment by ritika-msft** [comment]
Hi @annanra ,

We have updated the regex of the parser to match the syslog messages shared by you. https://github.com/Azure/Azure-Sentinel/pull/3887. Can you please follow below steps and save the function with a different name and update us if the parser is working fine now?

1. Open Log Analytics Workspace
2. Open new Query window
3. Copy and Paste the updated query from the PulseConnectSecure.txt file provided in the https://github.com/Azure/Azure-Sentinel/pull/3887/files.
4. In the query window, on the second line of the query, enter the hostname(s) of your Pulse Connect Secure device(s) and any other unique identifiers for the logstream. 
//    For example: | where Computer in ("server1, server2") and Facility == "local7"
5. Click on Save button and select as Function from drop down by specifying function name and alias as PulseConnectSecure_Test.

Run the query to validate data is being received and parsed.

Let us know, if the query works fine. Thanks!!

**Comment by ritika-msft** [comment]
Hi @annanra, Closing this issue as there is no response on this for more than a month. Please re-open or create a new one, if the issue persists and needs help. Thanks.
