### ISSUE TITLE
Unclear filters in CredentialAddedAfterAdminConsent.yaml

### ISSUE THREAD

**Issue by zino-sgh** [Azure/Azure-Sentinel#3376]
In Detections/AuditLogs/CredentialAddedAfterAdminConsent.yaml the detection explanation says that the event triggers if there is admin consent before the credential addition. In the code itself the filter uses "where TimeConsent > TimeCred" which looks like it will trigger if the consent is after the credential. Furthermore, there is no filter on the isAdminConsent field but I'm not sure if there should (the explanation says admin consent is relevant).

**Comment by v-amolpatil** [comment]
Hi @zino-sgh , thank you for flagging this. Apologies for the delayed response. If you still need assistance, please reply here within 5 business days.

**Comment by v-dvedak** [comment]
Since we have not received a response in the last 5 days, we are closing your issue #<3376> as per our standard operating procedures. If you still need support for this issue, feel free to re-open at any time. Thank you for your co-operation.
