### ISSUE TITLE
AD4IoT - Triton Attack Playbook 'Deploy to Azure' link not working

### ISSUE THREAD

**Issue by jpr2016git** [Azure/Azure-Sentinel#3377]
I've also tried pasting the raw code but getting the below error when saving it. It would be nice to have more detailed instructions describing the required components needed to be in place before deployment, if applicable.

Error:
Failed to save logic app IoT-Triton-Attack. The request content is not valid and could not be deserialized: 'Could not find member 'defaultValue' on object of type 'FlowTemplateParameter'. Path 'properties.parameters.PlaybookName.defaultValue', line 1, position 1297.'.

**Comment by sarah-yo** [comment]
Fixed
