### ISSUE TITLE
Connecting ITSM with Sentinel Incidents

### ISSUE THREAD

**Issue by john-joyner** [Azure/Azure-Sentinel#340]
We are standardizing on Azure Monitor Alerts that call ITSM workflows. Is there a way to automatically create Azure Monitor Alerts from Sentinel Incidents? That is, are Sentinel Incidents exposed to Log Analytics? If that is not the case, I am seeing that Playbooks are the Sentinel solution to export Incident data to ITSM workflows, is that correct? What if we don't use one of the listed ITSM products at https://github.com/Azure/Azure-Sentinel/tree/master/Playbooks (JIRA, SNOW, or ZenDesk?)...(we use AutoTask) what development track should we take to create our own playbook, that is, one that creates AutoTask tickets when Sentinel Incidents are created. (FYI if I can surface Incidents in Log Analytics I already have an AutoTask connection solution there.) Thanks, John

**Comment by dicolanl** [comment]
Hi
You are correct.  Today Azure Sentinel does not expose incidents in Log A so you cant use Azure monitor alerts for ITSM.  Playbooks is the way to go.

I dont believe there is a Logic App connector for Autotask.  I would encourage you to have the vendor create one. 
in the mean time, it looks like they have an API https://ww4.autotask.net/help/Content/LinkedDOCUMENTS/WSAPI/T_WebServicesAPIv1_5.pdf so you could use the HTTP action in Logic Apps to connect to their API.

**Comment by john-joyner** [comment]
That is extremely helpful and just what I was looking for. Thank you!
