### ISSUE TITLE
Solution is not available in CSP Subscriptions

### ISSUE THREAD

**Issue by vikaskumawat80** [Azure/Azure-Sentinel#3400]
I am trying to use CrowdStrike Falcon Endpoint Protection Solution (Preview) solutions in Azure CSP Subscriptions but it seems it is not available for CSP yet.

I tried the same in a Visual Studio Subscription and it worked. I am getting the below error:

_**This offer is not available for subscription from Microsoft Azure Cloud Solution Providers**_

**Comment by v-jayakal** [comment]
Not yet supported for CSP Subscription, Need the go-ahead from @preetikr. Closing this for now as no action to be done on this.

**Comment by gokulbala** [comment]
> Not yet supported for CSP Subscription, Need the go-ahead from @preetikr. Closing this for now as no action to be done on this.

Dear Team, we have a customer who wishes to use the Content Hub enhancement features and wants to know a **date** of release for CSP subscriptions.  Could @v-jayakal and @preetikr  please confirm on the same? Would much appreciate this. thanks.
