### ISSUE TITLE
Include Category AzureFirewallNetworkRule on Detection Analytics Rules

### ISSUE THREAD

**Issue by ep3p** [Azure/Azure-Sentinel#3416]
Some APT Detection Rules query many tables, among them "AzureDiagnostics", with ResourceType "AZUREFIREWALLS". Most of these rules only consider when Category is "AzureFirewallApplicationRule".

In Azure Firewall, Application Rules are the last to be checked when allowing or denying a communication, they previously check "Network Rules".

I think some Microsoft clients might have a poor implementation of Azure Firewall. Unfortunately they might be using only "Network Rules", and some might have "any to any" rules, and **NOT use "Application Rules" AT ALL**...

I have identified some rules that do not use the Category "AzureFirewallNetworkRule" in their queries.

**Detection Rules that query only "AzureFirewallApplicationRule":**

DEV-0322 Serv-U related IOCs - July 2021
Known CERIUM domains and hashes
Known GALLIUM domains and hashes
Known Phosphorus group domains/IP
Known STRONTIUM group domains - July 2019
Known ZINC Comebacker and Klackring malware hashes
Solorigate Network Beacon
SOURGUM Actor IOC - July 2021
THALLIUM domains included in DCU takedown
Alert for  IOCs related to Windows/ELF malware - IP, Hash IOCs - September 2021
Chia_Crypto_Mining - Domain, Process, Hash and IP IOCs - June 2021
NOBELIUM - Domain and IP IOCs - March 2021
NOBELIUM - Domain, Hash and IP IOCs - May 2021

**Detection Rules that already query both "AzureFirewallApplicationRule" and "AzureFirewallNetworkRule" :**

Known IRIDIUM IP
Several deny actions registered

Would you change the condition to 
```yaml
| where Category in ("AzureFirewallApplicationRule", "AzureFirewallNetworkRule")
```
in some of these queries?

**Comment by shainw** [comment]
@ep3p - Thanks we will take a look.

**Comment by shainw** [comment]
@aprakash13 - We have done this recently in https://github.com/Azure/Azure-Sentinel/blob/master/Detections/MultipleDataSources/Log4J_IPIOC_Dec112021.yaml and are looking to modify all of these queries to improve perf - please look at adding in AzureFirewallNetworkRule matching where it makes sense.

**Comment by cloudsecure2022** [comment]
How to tweak the "Several deny actions registered" alert. The fine turning will help to reduce some less critical incidents.

**Comment by NikTripathi** [comment]
Hi @ep3p Can you please confirm if you are still facing the issue?
Thanks.

**Comment by ep3p** [comment]
@NikTripathi please, consider this solved. Thank you very much for your time.

**Comment by v-amolpatil** [comment]
Closing this issue as this is resolved.
