### ISSUE TITLE
Carbon Black rules

### ISSUE THREAD

**Issue by decoderdude143** [Azure/Azure-Sentinel#3429]
**Describe the bug**
 Carbon Black Rules  are not correct , rules doesn't work when correctly , where Threathunterinfor is not a column in the CB event table its the Threatinfo, below is the correct rule that i have created and may require change in repo.

let threshold = 8;
CarbonBlackNotifications_CL
| where threatInfo_score_d >= threshold
| extend eventTime = datetime(1970-01-01) + tolong(threatInfo_time_d / 1000) * 1sec
| summarize StartTime = min(TimeGenerated), EndTime = max(TimeGenerated), count()
by
eventTime,
Threat_Name = threatInfo_summary_s,
Device_Name = deviceInfo_deviceName_s,
Internal_IP = deviceInfo_internalIpAddress_s,
External_IP = deviceInfo_externalIpAddress_s,
Threat_Score = threatInfo_score_d
| project-away count_
| extend
timestamp = StartTime,
HostCustomEntity = Device_Name,
IPCustomEntity = Internal_IP

**Comment by shainw** [comment]
@decoderdude143 - Thanks for sharing.  Can you submit an update directly as a PR please? We will review that way.

**Comment by decoderdude143** [comment]
thanks have send through the PR please confirm if the PR process is correct

**Comment by shainw** [comment]
Associating PR #3447

**Comment by shainw** [comment]
@decoderdude143 - when you get a chance, please review the comments in #3447

**Comment by shainw** [comment]
Closing for now as no response in 45 days.
