### ISSUE TITLE
Confirm-AADRiskyUser - not mapping in domain to username

### ISSUE THREAD

**Issue by bobsyourmom** [Azure/Azure-Sentinel#3433]
**Describe the bug**
Playbook:
https://github.com/Azure/Azure-Sentinel/tree/master/Playbooks/Confirm-AADRiskyUser

Will not map the domain to the user, so when the logicapp performs "Entities - Get Accounts" the result is <username>@ but the output should be <username>@<domain>

The reason appears to be that the function should map to ntDomain and not UPNSuffix.

eg. 
this doesn't work:
concat(items('For_each')?['Name'], '@', items('For_each')?['UPNSuffix'])

this works:
concat(items('For_each')?['Name'], '@', items('For_each')?['ntDomain'])

**To Reproduce**
1. run the playbook, it should fail
2. view the audit log results
3. open the "Entities - Get Accounts" operator and observe the output shows <username>@ with the domain missing.

**Expected behavior**
1. run the playbook, it should succeed
2. view the audit log results
3. open the "Entities - Get Accounts" operator and observe the output shows <username>@<domain>

**Comment by dicolanl** [comment]
Hi @bobsyourmom 
I think there are entities that have upnsuffix and some that have ntdomain depending on source product. 

We can add an if statement to use one or the other depending on availability.

**Comment by dicolanl** [comment]
@bobsyourmom  do you have an alert/incident with an entity where NTDomain is something.com?  I looked at a few we have and NTDomain seems to be consistently "NETBIOS" name of the domain and not a FQDN of domain.

The alerts from AAD always have UPN Suffix.

**Comment by sarah-yo** [comment]
Closing due to lack of response
