### ISSUE TITLE
Rule error Chia_Crypto_Mining - Domain, Process, Hash and IP IOCs - June 2021

### ISSUE THREAD

**Issue by anfisher1967** [Azure/Azure-Sentinel#3455]
Rule creation fails with Set rule logic step.

**Comment by anfisher1967** [comment]
![Chia](https://user-images.githubusercontent.com/33937240/142067859-9da6f92a-3a3a-44e1-a5b8-d1751b461feb.jpg)

**Comment by shainw** [comment]
@anfisher1967 - test out the query in this PR, ProcessId was never really there, it should be File and FilePath.  These are not part of the automap, so you will need to add them specifically, but they are now easily found - FileCustomEntity and FilePathCustomEntity columns.  You will still need to add in the Value mapping for File Hash as this is not automapped either.  You will map it to the FileHashCustomEntity column.
