### ISSUE TITLE
Azure Defender User Name displaying incorrect value

### ISSUE THREAD

**Issue by Lodewyk-Git** [Azure/Azure-Sentinel#3461]
**Describe the bug**
An Alert from Azure Defender got triggered. The value for the user was not the same as the value found on the actual machine. The machine that got affected is a Linux Redhat server.

**To Reproduce**
1. Go to Redhat
2. Access SSH keys 
3. See alert in Azure Sentinel

**Expected behavior**
Alert to map the correct User Name - UPN - Account - etc.

**Screenshots**
![image](https://user-images.githubusercontent.com/36856692/142209557-a2b091a3-2d8b-458f-ad98-2dc84837959c.png)

**Additional context**
When looking at the logs in Linux I could see that the User Name was not unknown user

**Comment by aprakash13** [comment]
@gitj121 Jessen can you please look at the query and see if we need to change the template. Thanks.

**Comment by gitj121** [comment]
@Lodewyk-Git Could you please share the name of the alert that triggered this hit?

**Comment by Lodewyk-Git** [comment]
The Incident display name is:
Process seen accessing the SSH authorized keys file in an unusual way

AlertType:
VM_SshKeyAccess

You can PM me for more details

**Comment by Lodewyk-Git** [comment]
Hey @gitj121, any update on this? I'm seeing it a lot less, but it does still occur for some M365D alerts from time to time.

**Comment by v-amolpatil** [comment]
Hi @Lodewyk-Git , thank you for flagging this. Apologies for the delayed response. If you still need assistance, please reply here within 5 business days.

**Comment by v-amolpatil** [comment]
Gentle Reminder: We are awaiting for your response on this issue. If you still need to keep this issue active please respond within next 2 days. If we don't receive response by 16 Feb 2023, we will close this issue.

**Comment by v-amolpatil** [comment]
Since we have not received a response in the last 5 days, we are closing your issue #3461 as per our standard operating procedures. If you still need support for this issue, feel free to re-open at any time. Thank you for your co-operation.
