### ISSUE TITLE
Error in remediation steps for Defender's "Traffic detected from IP addresses recommended for blocking" incident

### ISSUE THREAD

**Issue by garybusheyWork** [Azure/Azure-Sentinel#3463]
When an incident is created from Microsoft Defender (AKA Azure Defender) for the alert "Traffic detected from IP addresses recommended for blocking", the remediation steps come through as JSON rather than a readable string.   The other incidents from this connection seem to work just fine. 

The JSON looks like (subscription ID removed):

{"kind":"openBlade","displayValue":"Enforce rule","extension":"Microsoft_Azure_Security_R3","detailBlade":"AdaptiveNetworkControlsResourceBlade","detailBladeInputs":"protectedResourceId=/subscriptions/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxx/resourcegroups/adtest/providers/microsoft.compute/virtualmachines/activedirectorytest"}

**Comment by v-amolpatil** [comment]
Hi @garybusheyWork , thank you for flagging this. Apologies for the delayed response. If you still need assistance, please reply here within 5 business days.

**Comment by v-amolpatil** [comment]
Gentle Reminder: We are awaiting for your response on this issue. If you still need to keep this issue active please respond within next 2 days. If we don't receive response by 16 Feb 2023, we will close this issue.

**Comment by v-amolpatil** [comment]
Since we have not received a response in the last 5 days, we are closing your issue #3463 as per our standard operating procedures. If you still need support for this issue, feel free to re-open at any time. Thank you for your co-operation.
