### ISSUE TITLE
Markdown in the incident's description not showing in the incident detail pane

### ISSUE THREAD

**Issue by garybusheyWork** [Azure/Azure-Sentinel#3464]
The markdown text is not being interpreted in the incident detail pane.  It is showing as straight text making it hard to read and not what is expected.   It was showing just fine until a week or two ago.

**Comment by garybusheyWork** [comment]
It appears to be working again.  Not sure when it was resolved ( had last 4 days off) but I noticed it this morning.

**Comment by v-laanjana** [comment]
closing as its not happening
