### ISSUE TITLE
Threat intelligence create a new indicator rejects domains with hyphens

### ISSUE THREAD

**Issue by loganberriescartload** [Azure/Azure-Sentinel#3470]
**Describe the bug**
When trying to add a new domain-name indicator with a hyphen to the threat intelligence page the error: "is not a valid domain name' is returned

**To Reproduce**
1. Go to the threat intelligence page.
2. Click add new
3. Select Domain-name as the indicator type
4. Input a domain with a hypen in it, for example goo-gle.com 

**Expected behavior**
A domain name with a hyphen is a valid domain, which should not be rejected and should be allowed to be added to the threat intelligence table 

**Screenshots**
![image](https://user-images.githubusercontent.com/94572731/142290302-3e2b41c9-a508-4a9e-8a4c-9db4a238da7f.png)

**Desktop (please complete the following information):**
 - Windows 10
 - Edge
 - 95.0.1020.53

**Comment by azsec** [comment]
The API version `2021-04-01` still accepts hyphen in the domain. 

<img width="588" alt="hyphen-domain-ti-azsentinel" src="https://user-images.githubusercontent.com/58447315/145627957-1f4c0dbb-d397-49d7-a4cb-48b976ce47ea.PNG">

You can test with this script https://github.com/azsec/azure-sentinel-tools/blob/master/scripts/threat-intelligence/New-AzThreatIntelligenceIndicator.ps1

Below is my Sentinel when retrieving from API with [this script[(https://github.com/azsec/azure-sentinel-tools/blob/master/scripts/threat-intelligence/Get-AzThreatIntelligenceIndicatorById.ps1):

```
{
  "id": "/subscriptions/xxxxx-xxxxx-xxxxx/resourceGroups/azsec-corporate-rg/providers/Microsoft.OperationalInsights/workspaces/azsec-shared-workspace/providers/Microsoft.SecurityInsights/threatIntelligence/bb95edaa-f73f-e5c6-cd45-4857d3233e7f",
  "name": "bb95edaa-f73f-e5c6-cd45-4857d3233e7f",
  "etag": "\"0a00221a-0000-0200-0000-61b3a3fa0000\"",
  "type": "Microsoft.SecurityInsights/threatIntelligence",
  "kind": "indicator",
  "properties": {
    "confidence": 80,
    "created": "2021-12-10T19:01:13.6518912Z",
    "createdByRef": "Azsec",
    "externalId": "indicator--71b06697-8d1a-45b8-8e94-325fdf86481c",
    "lastUpdatedTimeUtc": "2021-12-10T19:01:13.7448993Z",
    "revoked": false,
    "source": "Azure Sentinel",
    "displayName": "sample-domain-name",
    "description": "Just a domain",
    "threatTypes": [
      "attribution"
    ],
    "parsedPattern": [
      {
        "patternTypeKey": "domain-name",
        "patternTypeValues": [
          {
            "valueType": "domain-name",
            "value": "abc-xyz.com"
          }
        ]
      }
    ],
    "pattern": "[domain-name:value = \u0027abc-xyz.com\u0027]",
    "patternType": "domain",
    "validFrom": "2021-11-27T00:00:00Z",
    "validUntil": "2022-11-27T00:00:00Z"
  }
}
```

**Comment by loganberriescartload** [comment]
I attempted to re-create this bug and it appears that the issue was fixed at some point.
