### ISSUE TITLE
Run-MDEAntivirus fails

### ISSUE THREAD

**Issue by bobsyourmom** [Azure/Azure-Sentinel#3475]
**Describe the bug**
scan fails since machineID is missing
it seems the 'get hosts from entities' may have used to provide the machine ID but it doesn't anymore?
But if you add the Defender: Get Hostname operator you can pull the machine ID by using the workstation hostname from the get entities output.

**To Reproduce**
run the playbook: https://github.com/Azure/Azure-Sentinel/tree/master/Playbooks/Run-MDEAntivirus

**Expected behavior**
successful av scan

**Additional context**
my email if you have questions: dbroggy@trustwave.com

**Comment by dicolanl** [comment]
Hey @bobsyourmom 
What is the source product from alert/incident that you used to call?

if the alert comes from MDE it will have the DeviceID in a property (MdatpDeviceId).

**Comment by rjaakke** [comment]
Hi @dicolanl,

This is what I get as output from the 'Entities - GetHosts', as you can see this is not flattened

[
  {
    "dnsDomain": "contoso.local",
    "hostName": "host1",
    "osFamily": "Windows",
    "osVersion": "21H1",
    "additionalData": {
      "MdatpDeviceId": "xxxxxxxxxxxxxxx",
      "FQDN": "host1.contoso.local",
      "AadDeviceId": "xxxxxxxxxxxxxxx",
      "RiskScore": "Low",
      "HealthStatus": "Active",
      "LastSeen": "2021-11-30T09:29:08.0111267Z",
      "LastExternalIpAddress": "0.0.0.0",
      "LastIpAddress": "0.0.0.0",
      "AvStatus": "Updated",
      "OnboardingStatus": "Onboarded"
    },
    "friendlyName": "host1",
    "Type": "host"
  }
]

**Comment by dicolanl** [comment]
@rjaakke My output is the same as yours. :). [ opens an array of items.  { opens the item.  so MDATPdeviceId is at the base level of the Item.

**Comment by dicolanl** [comment]
@rjaakke Well thats interesting.   Tagging @lior-tamir  for awareness.

What is the source of your alert, MDE?  
What trigger are you using?  i used the alert trigger (although it shouldnt matter)

Can you copy the code of the logic app for the get hosts action?  like this?
"Entities_-_Get_Hosts": {
                            "inputs": {
                                "body": "@triggerBody()?['Entities']",
                                "host": {
                                    "connection": {
                                        "name": "@parameters('$connections')['azuresentinel']['connectionId']"
                                    }
                                },
                                "method": "post",
                                "path": "/entities/host"
                            },
                            "runAfter": {
                                "Alert_-_Get_incident": [
                                    "Succeeded"
                                ]
                            },
                            "type": "ApiConnection"
                        }

**Comment by rjaakke** [comment]
@dicolanl The source is MDE and de playbook is trigger via an automation rule that calls the incident trigger

We used the template from Sentinel but if I look at https://github.com/Azure/Azure-Sentinel/tree/master/Playbooks/Run-MDEAntivirus/alert-trigger you can see in both azuredeploy JSON's that the condition 'is not equal to null' is missing a value.

"expression": {
                                        "and": [
                                            {
                                                "not": {
                                                    "equals": [
                                                        "",
                                                        "@null"
                                                    ]                                                }                                            }                                        ]                                    },

Here's the code of the Get Hosts action:
"Entities_-_Get_Hosts": {
                "inputs": {
                    "body": "@triggerBody()?['object']?['properties']?['relatedEntities']",
                    "host": {
                        "connection": {
                            "name": "@parameters('$connections')['azuresentinel']['connectionId']"
                        }
                    },
                    "method": "post",
                    "path": "/entities/host"
                },
                "runAfter": {},
                "type": "ApiConnection"
            },

**Comment by v-mchatla** [comment]
Hi
Entities - Get Hosts step is not rendering the correct host details. 
![image](https://user-images.githubusercontent.com/108806639/201033127-4d76f587-ca99-4191-826d-e3ccd381e51f.png)

![image](https://user-images.githubusercontent.com/108806639/201031191-ecb8c09c-9cfe-46ec-94fe-47e0215396c6.png)
@manishkumar1991 - Can you please analyze and provide possible fix for this.
Thanks

**Comment by v-amolpatil** [comment]
Hi @bobsyourmom , thank you for flagging this. Apologies for the delayed response. If you still need assistance, please reply here within 5 business days.

**Comment by v-amolpatil** [comment]
Gentle Reminder: We are awaiting for your response on this issue. If you still need to keep this issue active please respond with in next 2 days. If we don't receive response by 16 Feb 2023, we will close this issue.

**Comment by v-amolpatil** [comment]
Since we have not received a response in the last 5 days, we are closing your issue #3475 as per our standard operating procedures. If you still need support for this issue, feel free to re-open at any time. Thank you for your co-operation.
