### ISSUE TITLE
[Playbooks/Prompt-User] deployment failing

### ISSUE THREAD

**Issue by juju4** [Azure/Azure-Sentinel#3488]
**Describe the bug**
When deploying this playbook from deploy button on github, deployment is failing with below error

**To Reproduce**
1. Go to https://github.com/Azure/Azure-Sentinel/tree/master/Playbooks/Prompt-User
2. Click on Deploy to Azure
3. Input your target, deploy

**Expected behavior**
Deployment should succeed without errors.

**Screenshots**

Deploy to Azure button
```
{"code":"DeploymentFailed","message":"At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/DeployOperations for usage details.","details":[{"code":"InvalidTemplate","message":"The template validation failed: 'The template action 'Post_a_message_(V3)' at line '1' and column '2285' is not valid: \"Unable to parse template language expression '*sanitized*': expected token 'LeftParenthesis' and actual 'Identifier'.\".'."}]}
```

**Desktop (please complete the following information):**
N/A

**Smartphone (please complete the following information):**
N/A

**Comment by sreedharande** [comment]
Fixed
