### ISSUE TITLE
Sentinel Content Management > Repositories (preview): deployment failing

### ISSUE THREAD

**Issue by juju4** [Azure/Azure-Sentinel#3491]
**Describe the bug**
My understanding of "repositories (preview)" is to be leveraged as continuous integration/deployment pipeline. If not correct, please say.
I mirrored this repository in Azure DevOps, added a branch for my environment, and configured it in Sentinel repositories.
The resulting pipeline fails first because of local href error (#3490) and after on powershell script execution below which is not expected.

Side note, deployment is only asking target sentinel where I would expect other input, typically target resource group for playbooks/logicapp.

**To Reproduce**
1. Clone repository in Azure Devops
2. Add it to Sentinel repositories
3. Check Pipeline results in Azure Devops

**Expected behavior**

If CI/CD, this should result in corresponding content to be deployed to matching Sentinel and be operational without errors.

**Screenshots**

```
Starting: AzurePowerShell
==============================================================================
Task         : Azure PowerShell
Description  : Run a PowerShell script within an Azure environment
Version      : 5.185.0
Author       : Microsoft Corporation
Help         : https://aka.ms/azurepowershelltroubleshooting
==============================================================================
Generating script.
========================== Starting Command Output ===========================
"C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe" -NoLogo -NoProfile -NonInteractive -ExecutionPolicy Unrestricted -Command ". 'D:\a\_temp\[GUID].ps1'"
Import-Module -Name C:\Modules\az_6.5.0\Az.Accounts\2.6.1\Az.Accounts.psd1 -Global
WARNING: Both Az and AzureRM modules were detected on this machine. Az and AzureRM modules cannot be imported in the 
same session or used in the same script or runbook. If you are running PowerShell in an environment you control you can
 use the 'Uninstall-AzureRm' cmdlet to remove all AzureRm modules from your machine. If you are running in Azure 
Automation, take care that none of your runbooks import both Az and AzureRM modules. More information can be found 
here: https://aka.ms/azps-migration-guide
Clear-AzContext -Scope CurrentUser -Force -ErrorAction SilentlyContinue
Clear-AzContext -Scope Process
Connect-AzAccount -ServicePrincipal -Tenant *** -Credential System.Management.Automation.PSCredential -Environment AzureCloud @processScope
 Set-AzContext -SubscriptionId [GUID] -TenantId ***
Starting Deployment for Files in path: D:\a\1\s
##[error]You cannot call a method on a null-valued expression.
##[error]PowerShell exited with code '1'.
Finishing: AzurePowerShell
```

**Desktop (please complete the following information):**
N/A

**Smartphone (please complete the following information):**
 N/A

**Comment by h0ffayyy** [comment]
I'm seeing the same thing. From GitHub actions log:

```
Initializing Az Module
"C:\Program Files\PowerShell\7\pwsh.exe" -NoLogo -NoProfile -NonInteractive -Command "try ***
            $ErrorActionPreference = \"Stop\"
            $WarningPreference = \"SilentlyContinue\"
            $output = @***
            $data = Get-Module -Name Az -ListAvailable | Sort-Object Version -Descending | Select-Object -First 1
            $output['AzVersion'] = $data.Version.ToString()
            $output['Success'] = \"true\"
        ***
        catch ***
            $output['Error'] = $_.exception.Message
        ***
        return ConvertTo-Json $output"
"C:\Program Files\PowerShell\7\pwsh.exe" -NoLogo -NoProfile -NonInteractive -Command Test-Path (Join-Path C:\Modules az_*)
True
***
  "AzVersion": "6.5.0",
  "Success": "true"
***
Initializing Az Module Complete
Running Az PowerShell Script
"C:\Program Files\PowerShell\7\pwsh.exe" -NoLogo -NoProfile -NonInteractive -Command D:\a\_temp\[GUID].ps1
Starting Deployment for Files in path: D:\a\sentinel-playbooks\sentinel-playbooks
ForEach-Object: D:\a\_temp\[GUID].ps1:107
Line |
 107 |      $template.resources | ForEach-Object ***
     |                            ~~~~~~~~~~~~~~~~
     | You cannot call a method on a null-valued expression.

Error: Error: The process 'C:\Program Files\PowerShell\7\pwsh.exe' failed with exit code 1
```

**Comment by shainw** [comment]
@preetikr - please have a look

**Comment by juju4** [comment]
From recent testing, this seems to be partially working.
After merging with current upstream/master, deleting sentinel repository creation, adding again, it attempts to deploy targeted scope (playbooks for now) and does some partially.

Still need to find
- how to give general or individual playbooks input parameters. Else most playbooks end with broken API connection
- why some playbooks deployed without managed identity even when their json has it
- exact permissions required (least privileged ideally) and where

**Comment by pelsebubb** [comment]
Is this working now, last time i checked it just failed.

**Comment by v-laanjana** [comment]
@juju4 are you still facing same issue ?

**Comment by juju4** [comment]
That's mostly addressed with sentinel-deployment.config

Updated relevant docs
https://learn.microsoft.com/en-us/azure/sentinel/ci-cd?tabs=github
https://learn.microsoft.com/en-us/azure/sentinel/ci-cd-custom-deploy?tabs=github
