### ISSUE TITLE
Sentinel Play Books : Issue with action 'Alert - Get Incident'

### ISSUE THREAD

**Issue by maheshmarthi** [Azure/Azure-Sentinel#3507]
**Describe the bug**
Issue with action 'Alert - Get Incident'

**To Reproduce**
1. Create a playbook with Azure Sentinel Alert Trigger.
2. Make sure that the alert is associated with more than one incident
3. Fire the playbook from one of the incidents -> alerts => playbooks
4. Go to run history to see the error

**Expected behavior**
The action should output an array of incidents

**Screenshots**
![image](https://user-images.githubusercontent.com/15907487/142848998-c85d6a6b-2764-43e4-a491-4b6ff0183a51.png)

**Comment by shainw** [comment]
@sreedharande - Can you have a look?  not sure who implemented this.

**Comment by v-amolpatil** [comment]
Hi @maheshmarthi , thank you for flagging this. Apologies for the delayed response. If you still need assistance, please reply here within 5 business days.

**Comment by v-dvedak** [comment]
Since we have not received a response in the last 5 days, we are closing your issue #<3507> as per our standard operating procedures. If you still need support for this issue, feel free to re-open at any time. Thank you for your co-operation.
