### ISSUE TITLE
Duplicated Detections about MFA Rejection/Deny

### ISSUE THREAD

**Issue by ep3p** [Azure/Azure-Sentinel#3516]
There are two detections for basically the same. Clients might be confused.

https://github.com/Azure/Azure-Sentinel/blob/master/Detections/SigninLogs/ExplicitMFADeny.yaml
https://github.com/Azure/Azure-Sentinel/blob/master/Detections/SigninLogs/MFARejectedbyUser.yaml

**Comment by shainw** [comment]
@ep3p - Thanks, I think we got a bit excited about adding detections covering the fundamentals documentation - https://docs.microsoft.com/azure/active-directory/fundamentals/security-operations-user-accounts. :)

We will look at merging...

@petebryan and @ashwin-patil - Let's look at how we want to merge these.  The ExplicitMFADeny has been around much longer and covers multiple data types.  We may want to just update that one.

**Comment by v-amolpatil** [comment]
Hi @ep3p , thank you for flagging this. Apologies for the delayed response. If you still need assistance, please reply here within 5 business days.

**Comment by ep3p** [comment]
Personally I just wanted Microsoft to note this, personally I don't need this issue to be open, thank you for your time.

**Comment by v-dvedak** [comment]
Thank you @ep3p! In that case, we are closing your issue #<3516> as per our standard operating procedures. If you still need support for this issue, feel free to re-open at any time. Thank you for your co-operation.

**Comment by roniegh** [comment]
@shainw @petebryan @ashwin-patil @ep3p could you please merge these redundant rules or at least add a deprecation warning to the legacy one?
