### ISSUE TITLE
Azure Playbook [BlockAADUser-Alert]

### ISSUE THREAD

**Issue by DevMickeal** [Azure/Azure-Sentinel#3522]
**Describe the bug**
I clone the BlockAADUser-Alert template and attached it to the automation rules of one of my analytics rule.
I expected the playbook to block user every time the alert is triggered, however, I received a comment from the playbook saying:

![image](https://user-images.githubusercontent.com/62293658/143002037-45a69a57-d1f2-443a-a5e4-8a1bcdc9fb28.png)

**Expected behavior**
It's expected to block the user but it is not and the connection is a global admin account

**Screenshots**
Is this connection right:
![image](https://user-images.githubusercontent.com/62293658/143003032-2efa2dd9-cea4-48f7-a177-6c2641fef6b7.png)
 
or this: 

![image](https://user-images.githubusercontent.com/62293658/143003153-c91eeb40-0ea4-4950-b90e-0a12f1388856.png)

**Comment by dicolanl** [comment]
Hi @DevMickeal 
did you authorize the AAD connection?  if so, the user that you used does it have permissions to update the user?

**Comment by DevMickeal** [comment]
Thanks for checking @dicolanl, the user is a GA and I did authorize the AAD connection.

As shared in the screenshot, which is the right connection, I believe it should be Azure AD

**Comment by dicolanl** [comment]
the template will use the azuread-Block-AADUser.  but in reality, it doesnt matter which connection you use as long as the connection is authorized and the user that authorized has the needed permissions.

**Comment by DevMickeal** [comment]
The connection was authorized by a GA, so it definitely has the right permission and how do I know if the connection has been authorized.

**Comment by dicolanl** [comment]
could you look at previous runs and screen shot the failed run?

**Comment by DevMickeal** [comment]
![image](https://user-images.githubusercontent.com/62293658/143187493-f3ab53f2-266d-491a-971d-1a0f7161a41f.png)

@dicolanl and see below forbidden on the successful run

![image](https://user-images.githubusercontent.com/62293658/143187707-7aa82276-c496-4ae2-a7bc-1bc86f6b45a6.png)

**Comment by lior-tamir** [comment]
Hi @DevMickeal, so the **user authenticated** to the connector is a global administrator on the tenant? I'm asking since the actual user which the connector was authenticated with must have 
Group.ReadWrite.All
User.ReadWrite.All
Directory.ReadWrite.All

Can you please share the error message as well?

**Comment by BenjiSec** [comment]
to update - API needs special permission to be able to block admin user (reference - https://docs.microsoft.com/en-us/graph/api/user-update?view=graph-rest-beta&tabs=http#request-body). We are working on updating current readme to state that, and creating additional playbook with higher permissions to be able to block admin users.

**Comment by BenjiSec** [comment]
Readme for playbook Block-AADUser is updated with info that it doesn't support  block of admin users. Template updated to have notification to manager, if manager available.

Additional playbook created that supports block of admin users as well - Block-AADUserOrAdmin.

**Comment by DevMickeal** [comment]
That's great...thank you Benjamin..thank you SecuritJedi😊
