### ISSUE TITLE
MS Sentinel - FileHash Enrichment - Virus Total playbook - Data sent to LogAnalytic dropped

### ISSUE THREAD

**Issue by mx-oss** [Azure/Azure-Sentinel#3536]
**Describe the bug**
Data sent to LogAnalytic to VTFileReport_CL was dropped: The number of custom fields 501 is above the limit of 500 fields per data type.

**To Reproduce**
This playbook will take each File Hash entity and query VirusTotal for File Report (https://developers.virustotal.com/v3.0/reference#file-info). It will write the results to Log Analytics and add a comment to the incident.
When running the logic-app, the VT API returning more than 500 fields for a file hash analysis causing an error with the Log analystics when the data is send to the VTFileReport_CL table

**Expected behavior**
Be able to reduce the number of custom fields created by the logic-app in order to avoid to get an error from Log Analytics due to the custom fields limit (max : 500 custom fields)

**Screenshots**
![image](https://user-images.githubusercontent.com/15915198/143250869-d1ed6c87-8f0e-4673-bc76-85ecc8ba6a75.png)

**Comment by shainw** [comment]
@mx-oss - For clarity, this playbook? https://github.com/Azure/Azure-Sentinel/tree/master/Playbooks/Get-VirusTotalFileInfo.

@dicolanl, @sarah-yo and @sreedharande - can one of you have a look?

**Comment by mx-oss** [comment]
Yes, it is correct. 

Sent from my phone

Maxime
