### ISSUE TITLE
security log trough WEF

### ISSUE THREAD

**Issue by miki-alkalay** [Azure/Azure-Sentinel#354]
forward security event will not include the whole fields that are originally withing the security event.
regular security event log fields:

TenantId | ff632c0c-8a76-4ec2-a668-e155d2babcd1
-- | --
  | TimeGenerated [UTC] | 2019-10-20T08:18:41.3Z
  | SourceSystem | OpsManager
  | Account | CYBERPROOF\AAD_53070ababab9
  | AccountType | User
  | Computer | AD-02.cyberproof.io
  | EventSourceName | Microsoft-Windows-Security-Auditing
  | Channel | Security
  | Task | 12544
  | Level | 8
  | EventID | 4648
  | Activity | 4648 - A logon was attempted using explicit credentials.
  | IpAddress | -
  | IpPort | -
  | LogonGuid | e1f33118-1ad6-d77f-8adf-9c8461ed1d2d
  | Process | miiserver.exe
  | ProcessId | 0x884
  | ProcessName | C:\Program Files\Microsoft Azure AD Sync\Bin\miiserver.exe
  | SubjectAccount | CYBERPROOF\AAD_53070ababab9
  | SubjectDomainName | CYBERPROOF
  | SubjectLogonId | 0x227e0
  | SubjectUserName | AAD_53070ababab9
  | SubjectUserSid | S-1-5-21-1358865192-1755961342-2118700785-2285
  | TargetAccount | CYBERPROOF.IO\MSOL_53070ababab9
  | TargetDomainName | CYBERPROOF.IO
  | TargetInfo | ldap/AD-02.cyberproof.io/cyberproof.io
  | TargetLogonGuid | 00000000-0000-0000-0000-000000000000
  | TargetServerName | AD-02.cyberproof.io
  | TargetUserName | MSOL_53070ababab9
  | SourceComputerId | 0a9eb353-db20-4ba9-bf96-fb3c664a9273
  | EventOriginId | f643600a-7483-4f21-9468-0efe4c801fd4
  | MG | 00000000-0000-0000-0000-000000000001
  | TimeCollected [UTC] | 2019-10-20T08:40:02.266Z
  | ManagementGroupName | AOI-ff632c0c-8a76-4ec2-a668-e155d2babcd1
  | Type | SecurityEvent

event that are coming from WEF:

AuthenticationPackageName | Negotiate
-- | --
  | FailureReason | %%2313
  | IpAddress | -
  | IpPort | -
  | KeyLength | 0
  | LmPackageName | -
  | LogonProcessName | Advapi
  | LogonType | 4
  | ProcessId | 0x28c
  | ProcessName | C:\Windows\System32\svchost.exe
  | Status | 0xc000006d
  | SubStatus | 0xc000006a
  | SubjectDomainName | POLF_NT
  | SubjectLogonId | 0x3e7
  | SubjectUserName | POL-ATL-RMT$
  | SubjectUserSid | S-1-5-18
  | TargetDomainName | POLF_NT
  | TargetUserName | sdooma
  | TargetUserSid | S-1-0-0
  | TransmittedServices | -
  | WorkstationName | POL-ATL-RMT

pl

**Comment by shainw** [comment]
Hi, not every event has all available entities or values in it.  Do you have a specific event or events where you see certain values in the Event Log but not in the Event when it comes into Log Analytics?  As this is not specific to the GitHub queries and related to data ingestion into Log Analytics, you may need to call in to our support team - https://docs.microsoft.com/en-us/azure/azure-supportability/how-to-create-azure-support-request
