### ISSUE TITLE
Incident-Email-Notification playbook does not send email notification

### ISSUE THREAD

**Issue by Emilyen777** [Azure/Azure-Sentinel#3547]
Hi There,

I am new in Microsoft Sentinel.  I am using an Incident-Email-Notification playbook but I will not get email updates when a new Incident is created. It works when pushing the button Run Trigger. I will appreciate any help. Thanks a lot

**Comment by Emilyen777** [comment]
> Hi There,
> 
> I am new in Microsoft Sentinel. I am using an Incident-Email-Notification playbook but I will not get email updates when a new Incident is created. It works when pushing the button Run Trigger. I will appreciate any help. Thanks a lot

![IncEma](https://user-images.githubusercontent.com/92591624/143591096-a8b45664-d851-4f2e-af82-1bee8225fed7.png)

 I have initiated brute force attack, I see succeeded status but did not get email notification

**Comment by Lodewyk-Git** [comment]
Hi @Emilyen777, you most likely have to set up an automation rule to run the playbook when a new Incident is created. (Automatically)

To understand what the trigger does see https://docs.microsoft.com/en-us/azure/sentinel/playbook-triggers-actions#microsoft-sentinel-triggers-summary

To know more about automation rules see (setting up etc): https://docs.microsoft.com/en-us/azure/sentinel/tutorial-respond-threats-playbook#automate-threat-responses
