### ISSUE TITLE
Gov-cloud compatibility

### ISSUE THREAD

**Issue by rolandpg** [Azure/Azure-Sentinel#3585]
**Is your feature request related to a problem? Please describe.**
I would like to use this connector in a GCC-high environment.

**Describe the solution you'd like**
A GCC-connector or option to change the ods.opinsights.azure.com to ods.opinsights.azure.us

**Describe alternatives you've considered**
a separate cef forwarder instead of the azure connector.

**Additional context**

**Comment by rolandpg** [comment]
> Thank you for submitting an Issue to the Azure Sentinel GitHub repo! You should expect an initial response to your Issue from the team within 5 business days. Note that this response may be delayed during holiday periods. For urgent, production-affecting issues please raise a support ticket via the Azure Portal.

No response on this yet

**Comment by v-jayakal** [comment]
@rolandpg - Can you please give more details? What is the connector mentioned in this Issue? Thanks.

**Comment by rolandpg** [comment]
https://github.com/Azure/Azure-Sentinel/tree/master/DataConnectors/microsoft-logstash-output-azure-loganalytics/
is the connector.  trying to sent input from logstash to AZ-sentinel ina GCC high environment.

**Comment by benatsb** [comment]
@rolandpg , you need to specify the endpoint in the plugin output configuration. See [microsoft-logstash-output-azure-loganalytics/#configuration](https://github.com/Azure/Azure-Sentinel/tree/master/DataConnectors/microsoft-logstash-output-azure-loganalytics/#configuration)

> **endpoint** – Optional field by default set as log analytics endpoint.

Add the following to your output configuration:
`
...

endpoint => "ods.opinsights.azure.us"

...
`

If you're not familiar with Azure Government and the differences from Azure Commercial, I recommend this as a reference for AzGov services: 
https://docs.microsoft.com/en-us/azure/azure-government/compare-azure-government-global-azure

**Comment by NikTripathi** [comment]
Hi @rolandpg Can you please confirm if you issue resolved.

Thanks.

**Comment by v-amolpatil** [comment]
Hi @rolandpg, thank you for flagging this. Apologies for the delayed response. If you still need assistance, please reply here within 5 business days.

**Comment by v-amolpatil** [comment]
Gentle Reminder: We are awaiting for your response on this issue. If you still need to keep this issue active please respond with in next 2 days. If we don't receive response by 16 Feb 2023, we will close this issue.

**Comment by v-amolpatil** [comment]
Since we have not received a response in the last 5 days, we are closing your issue #3585 as per our standard operating procedures. If you still need support for this issue, feel free to re-open at any time. Thank you for your co-operation.
