### ISSUE TITLE
Analytic Rule Template Doesn't show entities information - ThreatIntelligenceIndicator/DomainEntity_SecurityAlert.yaml

### ISSUE THREAD

**Issue by v-danielgal** [Azure/Azure-Sentinel#3587]
**Describe the bug**
The query that come inside the analytic rule template doesn't print the information needed to trigger the security alert or sometimes shows empty information even if the information is contained inside the query parsed information

**To Reproduce**

- Go to analytic rule template "TI map Domain entity to SecurityAlert" and copy all the query, 
- Paste the query in Log Analytics Workspace after verifying you have all the data sources connected.
- You will see the results without information of the entity mapping (Host, IP, URL)

**Expected behavior**

Expectation of  this alert  is to bring in entities for both the domain that was alerted on, and the host/IP of where the alert originated.

**Screenshots**

![1](https://user-images.githubusercontent.com/95255583/145885776-af9f171d-672b-4f9b-a9ff-29719646b3f3.jpg)

![2](https://user-images.githubusercontent.com/95255583/145885804-6c6b9483-93e2-4c2e-8aeb-2e2f6bee1162.jpg)
 
![3](https://user-images.githubusercontent.com/95255583/145885844-149eb6bb-350b-4a89-b4db-5650e718f207.jpg)

**Additional context**
This is an issue reported to Microsoft Defender for cloud pod.

**Comment by v-danielgal** [comment]
Hi team, will you have news about this issue?

thanks!

**Comment by shainw** [comment]
@aprakash13 - Can you have a look at this please?

**Comment by v-danielgal** [comment]
Customer provided his own solution for this
