### ISSUE TITLE
Data Connector - Salesforce Service Cloud - header ingestion

### ISSUE THREAD

**Issue by nickselvaggio** [Azure/Azure-Sentinel#3594]
**Describe the bug**
The Salesforce Service Cloud data connector (https://github.com/Azure/Azure-Sentinel/tree/master/DataConnectors/SalesforceServiceCloud) ingests header data that Salesforce includes in every downloaded log file. This results in header data (with the column titles) being ingested into Log Analytics.

**To Reproduce**
1. Execute the function app
2. Run a query in Log Analytics for the SalesforceServiceCloud_CL table sorted by TimeGenerated
3. There will be several log entries that contain only header information from the CSV files downloaded from the Salesforce API (see screenshot for example of a record that only contains CSV header data). This can be seen on the first log entry after the function executes, but there may be others inside the table dependent on the amount of CSV files downloaded and ingested into Log Analytics.

**Expected behavior**
The header information is not ingested - only the actual data after the 1st line of each downloaded file.

**Screenshots**
![Header](https://user-images.githubusercontent.com/28307087/144254592-5393515f-dff0-44b6-bc65-e4a985149cdd.png)

**Comment by preetikr** [comment]
@ashishsyal / @v-jayakal - Please investigate this. Thanks.

**Comment by v-jayakal** [comment]
@nickselvaggio - Modified the connector exclude header values for data ingestion. lease find the attached document containing instructions for updating the package to the temporary package https://github.com/Azure/Azure-Sentinel/blob/SalesForceExcludeHeader/DataConnectors/SalesforceServiceCloud/SalesforceSentinelConn.zip?raw=true. Please update and let us know the result. 
Instruction Guide:
[TSG - How to - Update Azure Function and Restore-SalesForce.docx](https://github.com/Azure/Azure-Sentinel/files/7683461/TSG.-.How.to.-.Update.Azure.Function.and.Restore-SalesForce.docx)

**Comment by nickselvaggio** [comment]
@v-jayakal Deployed the new function and tested it - the header lines are no longer being sent to Log Analytics - thank you!

**Comment by v-jayakal** [comment]
@nickselvaggio - Please restore the original package path and restart the function. If you haven't noted the path, 'https://aka.ms/sentinel-SalesforceServiceCloud-functionapp' is the original value for WEBSITE_RUN_FROM_PACKAGE. The temporary path will be deleted, hence you need to move to the master version of the path. Please let us know if you need any help. Thanks.
