### ISSUE TITLE
Problem in Validation Pipeline

### ISSUE THREAD

**Issue by cmaneiro** [Azure/Azure-Sentinel#3620]
**Describe the bug**
Automatic validation fail for valid YAML file in NPM installation step

**Screenshots**
always file in this non YAML related activity due to invalid credentials
![image](https://user-images.githubusercontent.com/22166946/144705335-d6abe436-dadb-482f-a8d2-348f1078d570.png)

**Comment by shainw** [comment]
@samikroy and @cmaneiro - The issue is being worked and only critical bug fixes are going thru right now.  Will update as soon as the team has a solution, then we will re-run validations.

**Comment by cmaneiro** [comment]
> @samikroy and @cmaneiro - The issue is being worked and only critical bug fixes are going thru right now. Will update as soon as the team has a solution, then we will re-run validations.

great @shainw, so this could be related with validation failing??? I have a PR #3601 failing and is not clear why.

will the validation run again automatically???

regards

**Comment by shainw** [comment]
@cmaneiro - some of the validations are truly failing.  You can tell if it is the NPM failure or not by looking at the validation outputs.  If you see this, then it is NPM, otherwise, please check the error and fix the failure.
![image](https://user-images.githubusercontent.com/45466083/144908229-10492286-a2c6-4b0b-9411-bbedb6fba175.png)

You have some additional errors that should be looked at:
![image](https://user-images.githubusercontent.com/45466083/144908317-12c8e619-5c3e-4dec-95aa-ee88777d6974.png)

![image](https://user-images.githubusercontent.com/45466083/144908380-d63324cd-f393-4351-a319-fffd3e7ea3c1.png)

**Comment by cmaneiro** [comment]
> @cmaneiro - some of the validations are truly failing. You can tell if it is the NPM failure or not by looking at the validation outputs. If you see this, then it is NPM, otherwise, please check the error and fix the failure. ![image](https://user-images.githubusercontent.com/45466083/144908229-10492286-a2c6-4b0b-9411-bbedb6fba175.png)
> 
> You have some additional errors that should be looked at: ![image](https://user-images.githubusercontent.com/45466083/144908317-12c8e619-5c3e-4dec-95aa-ee88777d6974.png)
> 
> ![image](https://user-images.githubusercontent.com/45466083/144908380-d63324cd-f393-4351-a319-fffd3e7ea3c1.png)

Hi @shainw ,

Mostly error are NPM related, I can see the two failed steps you share, but honestly have no clue what is failing, it's a hunting rule, the query is working properly, YAML structure has been validated, I have compared with existing Hunting rule files.

Would you mind take a look to the YAML to see if I'm missing something? 

Thanks!!!

**Comment by samikroy** [comment]
> @cmaneiro - some of the validations are truly failing. You can tell if it is the NPM failure or not by looking at the validation outputs. If you see this, then it is NPM, otherwise, please check the error and fix the failure. ![image](https://user-images.githubusercontent.com/45466083/144908229-10492286-a2c6-4b0b-9411-bbedb6fba175.png)
> 
> You have some additional errors that should be looked at: ![image](https://user-images.githubusercontent.com/45466083/144908317-12c8e619-5c3e-4dec-95aa-ee88777d6974.png)
> 
> ![image](https://user-images.githubusercontent.com/45466083/144908380-d63324cd-f393-4351-a319-fffd3e7ea3c1.png)

Thank you for sharing this @shainw.

@cmaneiro - have created #3634 where we only have npm failure and have updated the file to pass other validation. Please have a look.

**Comment by cmaneiro** [comment]
thanks @samikroy really a life saver here!!! 

@shainw I have implemented @samikroy proposal in PR #3601 and all validations are passed except NPM related.

now we have two pull requests #3601 and #3634 

Regards

**Comment by samikroy** [comment]
> thanks @samikroy really a life saver here!!!
> 
> @shainw I have implemented @samikroy proposal in PR #3601 and all validations are passed except NPM related.
> 
> now we have two pull requests #3601 and #3634
> 
> Regards

Thank you @v-sabiraj , 
@shainw &  @cmaneiro - The build error is fixed now. Could you please help approving this PR.

**Comment by cmaneiro** [comment]
The Validation process seems to be working properly now, I can close this issue

Thanks
