### ISSUE TITLE
Onborad ADS servers to our azure sentinel

### ISSUE THREAD

**Issue by SivPothana** [Azure/Azure-Sentinel#3671]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by shainw** [comment]
@SivPothana - There is no description of the issue, just the template.

**Comment by shainw** [comment]
Closing as no response and no action.
