### ISSUE TITLE
Add new TI map rule for CommonSecurityLog table

### ISSUE THREAD

**Issue by javiersoriano** [Azure/Azure-Sentinel#3675]
**Describe the solution you'd like**
There are many rules that correlate IOCs in the ThreatIntelligenceIndicator table wit multiple data types, but there is not a single rule that correlates IOCs with CommonSecurityLog (CEF) table.

@shainw @petebryan

**Comment by ep3p** [comment]
https://github.com/Azure/Azure-Sentinel/blob/master/Detections/ThreatIntelligenceIndicator/DomainEntity_CommonSecurityLog.yaml

https://github.com/Azure/Azure-Sentinel/blob/master/Detections/ThreatIntelligenceIndicator/FileHashEntity_CommonSecurityLog.yaml

https://github.com/Azure/Azure-Sentinel/blob/master/Detections/ThreatIntelligenceIndicator/FileHashEntity_Covid19_CommonSecurityLog.yaml

**Comment by javiersoriano** [comment]
Great, thanks!

**Comment by javiersoriano** [comment]
Actually, I was referring to detections that look for IPs in CommonSecurityLog.

The detections posted above look at domain and file hash entities, but there's not one for IPs

**Comment by shainw** [comment]
@javiersoriano - you are correct and not sure why we do not have it except that it might be related to the number of different columns in CommonSecurityLog where an IP resides depending on the vendor.  We will look into it.  @aprakash13 - Can you look into an IPEntity_CommonSecurityLog query?  We should also look at an ASIM query at the same time so we can be ready when it is integrated.

**Comment by aprakash13** [comment]
Thanks @javiersoriano. Have created one now.
https://github.com/Azure/Azure-Sentinel/pull/3801
