### ISSUE TITLE
Table IdentityInfo renews every 21 days, but Detection Rules have a 14 day limit

### ISSUE THREAD

**Issue by ep3p** [Azure/Azure-Sentinel#3679]
Some Detection Rules have started using the table IdentityInfo.

https://github.com/Azure/Azure-Sentinel/blob/27dfdca9a382b1b65abb4a6256a51d7e22b9ac0d/Detections/MultipleDataSources/PrivilegedAccountsSigninFailureSpikes.yaml

https://github.com/Azure/Azure-Sentinel/blob/6746bec52043c39b29e13d9348df8bae043d7988/Detections/MultipleDataSources/AuthenticationMethodsChangedforPrivilegedAccount.yaml

I think this table is useful, it can be used in many use cases.

I think IdentiytInfo resynchronizes **fully** every **21 days**. I might be wrong on this, this claim should be checked.

The problem is that Scheduled Analytics Rules (Detection rules) have a limit (queryperiod) of 14 day data, and I have encountered some cases where a user did not have a IdentityInfo event for more than 14 days but in the past 18 days, and thus, a detection rule might trigger or not wrongly because of this, because it didn't have the last available data of an active user.

I don't think Detection Rules should extend its QueryPeriod. But **maybe IdentityInfo could resynchronize every 14 days**, to force its data to be available and updated for Detection Rules, OR alternatively, be treated as Watchlist events, that are in a different cache, updated, etc.

**Comment by shainw** [comment]
@ep3p - Thanks for the feedback.  We will have a look here.  On a side not, you can change the query period to 21 days in your repo to meet your needs.

**Comment by razmarom** [comment]
Hi, in the past 2 weeks we updated the period of full sync of the Identity-Info to be 14 days, as we were aware of this problem.
It is deployed already, so you should no longer have this problem.
For any concern please feel free to reply.
Thank,
Raz

**Comment by ep3p** [comment]
Thank you very very much for this to you both.
