### ISSUE TITLE
Not yet supported for CSP Subscription, Need the go-ahead from @preetikr

### ISSUE THREAD

**Issue by gokulbala** [Azure/Azure-Sentinel#3688]
Not yet supported for CSP Subscription, Need the go-ahead from @preetikr. Closing this for now as no action to be done on this.

_Originally posted by @v-jayakal in https://github.com/Azure/Azure-Sentinel/issues/3400#issuecomment-978795853_

Query: Dear Team, we have a customer who wishes to use the Content Hub enhancement features and wants to know a date of release for CSP subscriptions. Could @v-jayakal and @preetikr please confirm on the same? Would much appreciate this. thanks.

**Comment by v-jayakal** [comment]
@preetikr - This is an ask for CSP enablement for Crowdstrike Falcon. Earlier issue raised for this is https://github.com/Azure/Azure-Sentinel/issues/3688. Can you please check this and let us know. Thanks.

**Comment by v-jayakal** [comment]
@gokulbala  - Please check in marketplace, Crowdstrike has been CSP enabled.

**Comment by gokulbala** [comment]
Thanks a lot @v-jayakal , much appreciate this.  We've informed our customer to check the same, will get back to you incase of any issues faced by them.  Thanks again.

**Comment by v-jayakal** [comment]
Since Crowdstrike has CSP enabled, closing this issue.
