### ISSUE TITLE
Query error for Analytics Rule 'A potentially malicious web request was executed against a web server'

### ISSUE THREAD

**Issue by v-miketang** [Azure/Azure-Sentinel#3694]
**Describe the bug**
When trying to create the analytics rule 'A potentially malicious web request was executed against a web server' in Microsoft Sentinel, there are parameters in the query not able to resolve column or scalar expression

Github link: https://github.com/Azure/Azure-Sentinel/blob/master/Detections/AzureDiagnostics/MaliciousWAFSessions.yaml

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to 'Microsoft Sentinel'
2. Click on 'Analytics '
3. Choose 'Rule templates'
4. Search for 'A potentially malicious web request was executed against a web server'
5. Click on 'Create rule'
6. See the error on 'Set rule logic' tab

**Expected behaviour**
The query in the rule logic should contain no errors and be able to save and create the analytics rule.

**Screenshots**
![image](https://user-images.githubusercontent.com/96047595/145780815-88ac765a-f92c-44e9-8915-c4995913d010.png)

Checked in the AzureDiagnostics table, could not find those parameters causing errors:
![image](https://user-images.githubusercontent.com/96047595/145781092-2ef3ac69-e3f2-4de6-a78b-d074d0149cc8.png)

**Comment by azsec** [comment]
@v-miketang have you configured Diagnostics for your application gateway? You need to collect `ApplicationGatewayAccessLog` as the query needs it

<img width="448" alt="app_gateway_diag" src="https://user-images.githubusercontent.com/58447315/145914415-c8d1f0be-4d3b-4160-bb95-608b2848ad03.PNG">

References:

- [Resource logs for Azure Web Application Firewall](https://docs.microsoft.com/en-us/azure/web-application-firewall/ag/web-application-firewall-logs)
- [Back-end health and diagnostic logs for Application Gateway](https://docs.microsoft.com/en-us/azure/application-gateway/application-gateway-diagnostics)

**Comment by azsec** [comment]
@v-miketang Have you configured to collect `ApplicationGatewayAccessLog` data for your Application Gateway? The query needs it.

<img width="389" alt="app_gateway_diag" src="https://user-images.githubusercontent.com/58447315/145914626-4d3cbad6-fba0-42b4-bc49-10b34653aef2.PNG">

Reference:
- [Resource logs for Azure Web Application Firewall](https://docs.microsoft.com/en-us/azure/web-application-firewall/ag/web-application-firewall-logs)
- [Back-end health and diagnostic logs for Application Gateway](https://docs.microsoft.com/en-us/azure/application-gateway/application-gateway-diagnostics)

**Comment by shainw** [comment]
@v-miketang - Did @azsec provide you what you were looking for here?

**Comment by shainw** [comment]
@v-miketang - Closing the issue for now, if you did not get the answer you needed, please re-open.
