### ISSUE TITLE
Windows Firewall Logging

### ISSUE THREAD

**Issue by YulelogPagoda** [Azure/Azure-Sentinel#370]
Been through all the issue reports and guides, had the Windows Firewall Logging working until this morning, but it died. I've been through removing the data connector and putting it back in, reset the MMA agents, and so on.... has something else changed here?

**Comment by shainw** [comment]
Apologies for the delay in responding.  Would you be able to give a call into our support team, they are best suited to help you there - https://docs.microsoft.com/en-us/azure/azure-supportability/how-to-create-azure-support-request
