### ISSUE TITLE
Packaging Fails

### ISSUE THREAD

**Issue by rons4** [Azure/Azure-Sentinel#3719]
**Describe the bug**
Packaging for the Pull Request "SIGNL4 Solution Packaging #3665" fails. It mentions to create an issue.

**To Reproduce**
1. Go to the Pull request "SIGNL4 Solution Packaging #3665" and see the errors there.

**Expected behavior**
The Pull Request should succeed.

**Desktop (please complete the following information):**
 - GitHub

**Smartphone (please complete the following information):**
 - N/A

**Additional context**
I am sorry, if I miss something here and I appreciate your assistance.

**Comment by v-jayakal** [comment]
@rons4 - Validations were failing as there were some packaging issues earlier. Rebase from master resolved the failures. Since no errors, closing this issue.
