### ISSUE TITLE
Clone by URL failed

### ISSUE THREAD

**Issue by digitalarche** [Azure/Azure-Sentinel#3737]
**Describe the bug**

Clone repository https://github.com/Azure/Azure-Sentinel.git into D:\GitDrive\Azure-Sentinel: could not remove directory 'D:/GitDrive/Azure-Sentinel/.git/refs/remotes/origin/dev/normalization/DEV-0322_SolarWinds_Serv-U_IOC': parent is not directory: Specified path is not found.

It is perhaps all the same to be taken into account even if normal git works?

**To Reproduce**
But only with Gitkraken 8.2.0 

**Additional context**
With Git Bash this error not appear

**Comment by v-laanjana** [comment]
@digitalarche could you please try with 8.10.1 (latest) .we have tested at our end cloning is working fine.

I am closing issue as it working fine.
