### ISSUE TITLE
Unable to use Content Hub with CSP Subscription

### ISSUE THREAD

**Issue by Shobogan** [Azure/Azure-Sentinel#3746]
**Describe the bug**
Trying Multiple Content hub and Keep getting told unable to use with CSP

**To Reproduce**
Have a CSP subscription and try to assign any content hub options

![Content_Hub_Error](https://user-images.githubusercontent.com/96302873/146565249-c12ceb35-1f32-4c5b-b719-d5e9bce68f87.jpg)

**Comment by v-jayakal** [comment]
@Shobogan  - Can you please tell me which solution you are trying for? We have enabled CSP for few solutions.

**Comment by v-jayakal** [comment]
@Shobogan - CSP enablement for ContentHub solutions are done for few solutions (Log4j, Training solution, RiskIQ, Crowdstrike , Palo Alto Prisma, Imperva Cloud WAF, CMMC, Sophos EP). Road map for rest of the solutions is February 2022. Hence closing this issue. If required, please approach @preetikr with ask about CSP. Thanks.
