### ISSUE TITLE
Sentinel lab playbook does not work

### ISSUE THREAD

**Issue by poortom1004** [Azure/Azure-Sentinel#3757]
**Describe the bug**
On Exercise 3, Step 3 on https://github.com/Azure/Azure-Sentinel/blob/master/Solutions/Training/Azure-Sentinel-Training-Lab/Modules/Module-1-Setting-up-the-environment.md#exercise-3-configure-microsoft-sentinel-playbook

Step with text: "Click on Edi API connection under General."

Receiving an error "Resource ID is not available" when editing the API connection

**To Reproduce**
1. Deploy the provided solution
2. Go to the Get-GeoFromIpAndTagInciden logic app
2. Click on API connections
3. Click on azuresentinel-Get-GeoFromIpAndTagIncident
4. Click on Edit API connection

**Expected behavior**
Expecting to be able to authorize the connection with my credentials

**Screenshots**
![image](https://user-images.githubusercontent.com/31856350/146691341-dd5a761b-9982-4591-82c9-173296c2fb92.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 (19044.1415)
 - Browser: Edge Chromium
 - Version: 96.0.1054.62

**Additional context**
Waited 2 hours after deploying the solution and still receive the error

**Comment by rajeshcom** [comment]
poortom1004 - have hit the same issue - Receiving an error "Resource ID is not available" when editing the API connection

Did you get a response/fix for yours ?

**Comment by v-rucdu** [comment]
Hey.. we are looking into this issue and would get back to you asap... Thanks!!!

**Comment by rajeshcom** [comment]
Appreciate that. 
Can't proceed with the labs as the API might have a bearing going forward. 
Thanks

**Comment by rajeshcom** [comment]
@v-rucdu
Happy New Year
Any leads on the issue ?
Thanks

**Comment by v-jayakal** [comment]
@javiersoriano - Can you please help on the issue? Thanks.

**Comment by v-jayakal** [comment]
@poortom1004  & @rajeshcom - This is actually an issue that is platform wide, not specifically related to Training Lab. It happens to all playbooks we have in Sentinel unfortunately and is reported to engineering team.

**Comment by v-rucdu** [comment]
@poortom1004 & @rajeshcom - Looks like a fix for the mentioned issue is available. Can you please check once again and confirm if it is resolved?
Thanks!!!
