### ISSUE TITLE
Azure AD Identity Protection sync alerts with sentinel

### ISSUE THREAD

**Issue by aquiros17** [Azure/Azure-Sentinel#3766]
**Describe the bug**
Azure AD Identity Protection connector at Microsoft sentinel is not working as expected. When the user has an identity protection risk alert (sign in or user risk at identity protection), this generates an alert on Microsoft Sentinel. In some cases (random), the identity protection alerts doesn't appears at Sentinel (1st problem)
Furthermore, when I close the incident on identity protection, this change is not syncing to sentinel, so I have to close the incident in two sides (identity protection and sentinel). On the other side, when I close the identity protection incident on sentinel, this change is not syncing to identity protection alert (This problems always appear and we have been waiting for a solution from Microsoft and the solution never appears)
This is a big problem because, we are a Microsoft CSP partner and we have a lot of customers that we have deployed Microsoft Sentinel and with this situation, the customers are thinking to change to other solution as IBM QRADAR, Splunk or similar.
I have opened a Microsoft support ticket and they answer me that the syncronization between Azure AD Identity protection and Microsoft sentinel is not supported. So, I have the following questions:
1. When will this sync issue between identity protection and sentinel be fixed to work like microsoft 365 defender or microsoft defender for cloud?
2. Why don't all the azure ad identity protection alerts appear in sentinel?

**To Reproduce**
1. Go to 'Microsoft Sentinel' > 'Data connectors'
2. Enable Azure AD identity protection connector 
3. Simulate Azure AD Identity protection alerts and close this alerts from Identity protection or sentinel

**Comment by Lodewyk-Git** [comment]
Hi, I've had this happen before, might it be that the alert does exist in the SecurityAlert table, but that no Incidents are created from it?

**Comment by aquiros17** [comment]
The alerts doesn't exist in the SecurityAlert table. Only visible in AAD Identity Protection but this is not generating incident/alert on Sentinel. We have another alerts on AAD Identity Protection that is generating incident/alerts on sentinel. What's happen?
I don't understand anything :(

**Comment by schen1880** [comment]
I have run into similar issue where alerts in Identity Protect do not create alerts in Sentinel. Connector has been disconnected and reconnected and everything has been deleted and recreated and they still do not appear. The risk logs are able to be queried in the log analytics workspace. Has there been any update?

**Comment by v-laanjana** [comment]
@aquiros17  we are looking into issue.

**Comment by schen1880** [comment]
Azure Identity Protection alerts are one of the main alerts customers need. WIthout there is little chance of adoption, and those already on it are looking to leave. Is this actually connector actually supported?

**Comment by v-amolpatil** [comment]
Hi @aquiros17 , thank you for flagging this. Apologies for the delayed response. If you still need assistance, please reply here within 5 business days.

**Comment by v-dvedak** [comment]
Since we have not received a response in the last 5 days, we are closing your issue #<3766> as per our standard operating procedures. If you still need support for this issue, feel free to re-open at any time. Thank you for your co-operation.
