### ISSUE TITLE
Validation of Palo Alto Solution Template fails with InvalidResourceLocation if resource group location differs from Sentinel log analytics workspace location

### ISSUE THREAD

**Issue by vmhenard** [Azure/Azure-Sentinel#3769]
**Describe the bug**
If the Sentinel Log Analytics workspace and its resource group have different locations, some solutions can’t be deployed.
The template fails to find a log analytics workspace in the resource group location, so it tries to create a new log analytics workspace in the resource group location. This fails as the existing log analytics workspace having the same name prevents it from being created.
The Palo-Alto solutions (CDL and Prisma) are concerned.

**To Reproduce**
1. Create a resource group in location A in one of your subscriptions
2. Create a log analytics workspace in location B (B different than A) in that resource group
3. Add a Sentinel workspace to the log analytics workspace previously created
2. Go to the newly deployed Sentinel workspace
3. On the left, scroll down and select "Content hub (Preview)" under Content Management
4. Search for Palo Alto in the search bar
5. Select "Palo Alto Networks Cortex Data Lake" or "Palo Alto Prisma"
6. Click Install
7. Click Create
8. Select your subscription, the resource group and the workspace previously created
9. Click Review+Create
10. See Validation failed error message : 
```
{
  "code": "InvalidResourceLocation",
  "message": "The resource 'myWorkspaceName' already exists in location 'B' in resource group 'myResourceGroupName'. A resource with the same name cannot be created in location 'A'. Please select a new resource name."
}
```

**Expected behavior**
The template should not assume the location of the log analytics workspace, and either asks for it or checks all locations before trying to deploy, hence validation succeeds and the solution can be deployed.

**Screenshots**
I can add some if needed

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser : Microsoft Edge
 - Version 96.0.1054.62 (Official build) (64-bit)

**Comment by elforb** [comment]
Hi @vmhenard ,

Thanks for bringing this up, I've made update to the mentioned solutions in Github (#3890) and the Azure Marketplace.

Will post here once more when the solution updates are live in the marketplace.

**Comment by elforb** [comment]
Hi @vmhenard ,

The two solution updates are now live in the marketplace.

Please let us know if the issue still persists.
