### ISSUE TITLE
cef_troubleshoot.py error with Python3

### ISSUE THREAD

**Issue by fsnengineering** [Azure/Azure-Sentinel#377]
**Describe the bug**
In the cef_troubleshoot.py we saw errors with variable 'line' from line 277. Result of tcp_dump.stdout.readline() is a byte type, not a str. Cannot compare with str "CEF" or "ASA" later in script. Was able to modify my copy of the script to add:
line = line.decode("utf-8") 
this fixed the error.

1. New VM with Fedora, RHEL, or CentOS
2. Update Python.
3. Install cef_installer.py
4. Run cef_troubleshoot.py
5. errors:
Validating CEF\ASA into rsyslog daemon - port 514
This will take 60 seconds.
sudo tcpdump -A -ni any port 514 -vv
Traceback (most recent call last):
  File "cef_troubleshoot2.py", line 633, in <module>
    main()
  File "cef_troubleshoot2.py", line 619, in main
    handle_rsyslog(workspace_id)
  File "cef_troubleshoot2.py", line 589, in handle_rsyslog
    "Received CEF\\ASA message in daemon incoming port.[" + daemon_port + "]", mock_message=False)
  File "cef_troubleshoot2.py", line 279, in incoming_logs_validations
    if handle_tcpdump_line(line, incoming_port, ok_message):
  File "cef_troubleshoot2.py", line 238, in handle_tcpdump_line
    if "CEF" in line or "ASA" in line:
TypeError: a bytes-like object is required, not 'str'

 - OS: Fedora 31

**Comment by shainw** [comment]
Not sure you have seen this post - https://social.msdn.microsoft.com/Forums/officeocs/en-US/caae8973-5794-4fbc-93ed-b318e7cff3f2/troubleshooting-syslog-connection-to-sentinellog-analytics?forum=opinsights

If that does not address your issue, as suggested in the response here, please open a support ticket so we can troubleshoot this with you - https://docs.microsoft.com/en-us/azure/azure-supportability/how-to-create-azure-support-request
