### ISSUE TITLE
Azure Active Directory tables with different type columns

### ISSUE THREAD

**Issue by ep3p** [Azure/Azure-Sentinel#3772]
I think I might have not configured something properly.

The Azure Active Directory tables SigninLogs and AADNonInteractiveUserSignInLogs refer to very similar activity, they have similar columns.

In my tenant both tables have some columns with the same name, but different type, they are:

Status
MfaDetail
LocationDetails
DeviceDetail
ConditionalAccessPolicies

These columns in the table SigninLogs are of type dynamic, in the table AADNonInteractiveUserSignInLogs of type string. If I try to union both tables, complications arise.

Please, could I know if this is intended or is a particular misconfiguration by my tenant?

**Comment by ep3p** [comment]
I see it is intended by the specification:

https://docs.microsoft.com/es-es/azure/azure-monitor/reference/tables/signinlogs
https://docs.microsoft.com/es-es/azure/azure-monitor/reference/tables/aadnoninteractiveusersigninlogs

Please, is there any possibility in the future they will be of the same type?

**Comment by shainw** [comment]
@ep3p - Thanks for the feedback.  I will share with the Azure Monitor team to understand why this may be.  In the meantime, I am sure you realize this can be handled by changing the type with tostring().

**Comment by v-amolpatil** [comment]
Hi @ep3p , thank you for flagging this. Apologies for the delayed response. If you still need assistance, please reply here within 5 business days.

**Comment by ep3p** [comment]
Thank you, I do not need assistance, I just wanted to point something that does not make much sense.
