### ISSUE TITLE
Unable to import YAML rules into Sentinel Analytics

### ISSUE THREAD

**Issue by Danilow** [Azure/Azure-Sentinel#3786]
Hi, 

We are currently unable to import the " Detections " Directory into our Sentinel application.
We are using a DevOps pipeline to automatically deploy our code base to Sentinel. 
There are multiple modules on the internet to push yaml to Sentinel.  
But these modules seem to lose the " tactics " and/or "techniques" fields which are important to us. 
Do you maybe have some kind of translation tool or a guide on how to use these rules in Azure Sentinel.
Or can someone maybe assist me on this topic? 

Kind regards, 
LD

**Comment by shainw** [comment]
@Danilow - Wondering if you are following the guidance here - https://techcommunity.microsoft.com/t5/microsoft-sentinel-blog/deploying-and-managing-microsoft-sentinel-as-code/ba-p/1131928.

**Comment by Danilow** [comment]
Hi @shainw, I did stumble upon this guide. 
Excuse me if I'm incorrect but this does not explain how to import the YAML detection rules from https://github.com/Azure/Azure-Sentinel/tree/master/Detections . It says they need to be in JSON format. 
Kind regards, 
LD

**Comment by Danilow** [comment]
I am able to import the yaml rules into sentinel. The "tactics" and "techniques" fields remain empty after importing these rules. 
While these fields are added in the YAML rules. It is vital information to us to be able to see tactics and techniques.

**Comment by shainw** [comment]
@Danilow - @rod-trent is one of our great contributors for items like this.  He has a pointer on one of his blogs - https://azurecloudai.blog/2021/03/22/how-to-import-one-or-multiple-analytics-rules-into-azure-sentinel/ - to this solution which appears to be what you are looking for - https://emptydc.com/2021/03/19/alertrule-from-github-to-azure-sentinel/

**Comment by shainw** [comment]
@Danilow - did you get the answers you needed in the blogs I shared?

**Comment by shainw** [comment]
Closing, no response
