### ISSUE TITLE
Cisco ASA Parser for Syslog

### ISSUE THREAD

**Issue by ZLT-ops** [Azure/Azure-Sentinel#3789]
**Is your feature request related to a problem? Please describe.**
Currently didn't found any parsers that will match the Cisco ASA Syslog

**Describe the solution you'd like**
A Query that will parse all the fields

**Describe alternatives you've considered**
Tried to start to write on my self but got stuck trying to see all the possible fields

**Comment by kochavis** [comment]
Hi, thank you for submitting this issue.
The Cisco ASA connector is quite limited and based on several pre-built regexes that require an exact match for full parsing to happen. Currently fully support Is available for a small number of events. This event seems to be of ID 4-106100 while we only support 6-106100.
We are currently working on a new connector for the Cisco ASA with a new Workflow supporting more events, We'll make sure to add this one to the list considered for parsing.

**Comment by guarismo** [comment]
Cisco ASA logs should go to CommonSecurityLog table via the CEF connector, they are parsed correctly this way unless the Cisco ASA device has the "logging emblem" setup.

**Comment by v-dvedak** [comment]
Hi @ZLT-ops , thank you for flagging this. Apologies for the delayed response. If you still need assistance, please reply here within 5 business days.

**Comment by v-dvedak** [comment]
Since we have not received a response in the last 5 days, we are closing your issue #3789 as per our standard operating procedures. If you still need support for this issue, feel free to re-open at any time. Thank you for your co-operation.
