### ISSUE TITLE
IpRep and GeoIP Playbooks giving null value error

### ISSUE THREAD

**Issue by WhatsTheFreqKenneth** [Azure/Azure-Sentinel#379]
After importing both Get-IPReputation and Get-GeoFromIpAndTagIncident from the git and running against an incident both playbooks report the following error at the "For each 2" loop:

ExpressionEvaluationFailed. The execution of template action 'For_each_2' failed: the result of the evaluation of 'foreach' expression '@body('Alert_-_Get_incidents')?['value']' is of type 'Null'. The result must be a valid array.

screen shot from Get-IPReputation
![image](https://user-images.githubusercontent.com/38758896/68703431-a57e4c00-0558-11ea-836b-c20c098a3b91.png)

screen shot from Get-GeoFromIpAndTagIncident
![image](https://user-images.githubusercontent.com/38758896/68703524-d6f71780-0558-11ea-8a34-8025071b51b9.png)

**Comment by dicolanl** [comment]
There was an update to the azure sentinel logic app connector. I will update the templates this week and publish a new pull request.
