### ISSUE TITLE
Issue injesting data from Cisco FTD

### ISSUE THREAD

**Issue by DSharpPro** [Azure/Azure-Sentinel#383]
**Describe the bug**
When sending syslog messages from Cisco FTD they are now collected correctly in Sentinel. This causes the data not to be translated correctly, so events (incidents + playbooks) don't work correctly

**Additional context**
https://techcommunity.microsoft.com/t5/Azure-Sentinel/Azure-Sentinel-The-Syslog-and-CEF-source-configuration-grand/ba-p/803891

It appears that CEF will structure the data correctly, but wanted to confirm if there is a resolution to importing the syslog messages so they can be used in Sentinel?

Thank you

**Comment by shainw** [comment]
@DSharpPro - Apologies for missing the Issue back in November.  If you have not resolved this, I think it best to open a support ticket to see what may be occurring - https://docs.microsoft.com/en-us/azure/azure-supportability/how-to-create-azure-support-request
