### ISSUE TITLE
Cisco Meraki Instructions

### ISSUE THREAD

**Issue by DeanGross** [Azure/Azure-Sentinel#3832]
**Describe the bug**
The instructions tell us to click the Edit API and this is not an option.

**To Reproduce**
1. download the json file from git hub
2. deploy the template using the custom deployment option 
3. View the MerakiConnector after the deployment is complete

**Expected behavior**
I'm expecting the instructions to describe what we should do accurately.

**Screenshots**
This is what I do see 
![image](https://user-images.githubusercontent.com/4058555/148114963-36911d8e-668a-4d3c-8517-db2962db1745.png)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by v-laanjana** [comment]
v-jayakal , can you please have look and update?

**Comment by v-amolpatil** [comment]
Hi @DeanGross, thank you for flagging this. Apologies for the delayed response. If you still need assistance, please reply here within 5 business days.

**Comment by v-amolpatil** [comment]
Gentle Reminder: We are awaiting for your response on this issue. If you still need to keep this issue active please respond within next 2 days. If we don't receive response by 16 Feb 2023, we will close this issue.

**Comment by v-amolpatil** [comment]
Since we have not received a response in the last 5 days, we are closing your issue #3832 as per our standard operating procedures. If you still need support for this issue, feel free to re-open at any time. Thank you for your co-operation.
