### ISSUE TITLE
multiple password reset by user - incorrect rule logic 

### ISSUE THREAD

**Issue by 82BBB00** [Azure/Azure-Sentinel#3837]
**Describe the bug**
Analytic Rule "[multiple password reset by user](https://github.com/Azure/Azure-Sentinel/blob/ee97399b426a21878776c4c7b4835efc04b47393/Detections/MultipleDataSources/MultiplePasswordresetsbyUser.yaml)" may have issues with Self-Service password reset service when a match is found in AuditLogs.

**To Reproduce**
1. Make this rule trigger for AuditLogs by using the Self-Service password reset service and you will find this in the Evidence>events:
See screenshot 1
2. Open Evidence> events and check the Total password resets
See screenshot 2
3. Open Azure AD > navigate to the concerned user > open AuditLogs
See screenshot 3
4. Here (screenshot 3) you find the actions seen as password reset by the Analytic Rule
*note: Screenshots are from different cases, that explains the time difference, so ignore that ;) 

**Expected behavior**
I would like to see that there is some way in the analytic rule that only checks for a real password reset in the audit logs and considers the status reason (steps) that could be part of a password change process, in this case the Self-Service password reset service

**Screenshots**
Screenshot 1:
<img width="240" alt="image" src="https://user-images.githubusercontent.com/96875510/148219378-0cd8ed7a-2d74-4f6c-8053-c6e0ccf3c7a4.png">

Screenshot 2: 
<img width="644" alt="image" src="https://user-images.githubusercontent.com/96875510/148222766-80556fe2-61bf-4c45-bc41-eaf6178a937a.png">

Screenshot 3:
<img width="544" alt="image" src="https://user-images.githubusercontent.com/96875510/148222922-038ed1b2-a8dd-43eb-b24f-f3227139ebb9.png">

**Comment by princemathew** [comment]
Best option is to avoid records where OperationName "Self-service password reset flow activity progress" is success. I have modified query as below.

`AuditLogs
| extend User = tostring(TargetResources[0].userPrincipalName), IPAddress = tostring(InitiatedBy.user.ipAddress)
| where LoggedByService == "Core Directory" and (OperationName contains "Reset user password" or OperationName contains "Change user password") or LoggedByService == "Self-service Password Management"
| summarize StartTimeUtc = min(TimeGenerated), EndTimeUtc = max(TimeGenerated),ActionCount  = countif((OperationName=="Self-service password reset flow activity progress" and Result=="success")==0),IPAddress=make_set_if(IPAddress,isnotempty(IPAddress)) by User,OperationName`
