### ISSUE TITLE
https://github.com/Azure/Azure-Sentinel#resources   has an invalid link

### ISSUE THREAD

**Issue by CliveWatsonQC** [Azure/Azure-Sentinel#3839]
Link #2 in the list on this page is invalid, source: https://github.com/Azure/Azure-Sentinel#resources 

**Product specific feature requests - Upvote or post new on Microsoft Sentinel feedback forums**

See image:![image](https://user-images.githubusercontent.com/96070044/148234631-171072a7-2fa9-453f-b1fd-8180ee521e19.png)

I think the new link should point to https://feedback.azure.com/d365community/forum/37638d17-0625-ec11-b6e6-000d3a4f07b8#

**Comment by samikroy** [comment]
@CliveWatsonQC - This is updated now. Please have a check.

**Comment by CliveWatsonQC** [comment]
Thank you – that works 😉



​--
​
Clive Watson
Solutions Director
***@***.***
Quorum Cyber Security Limited
​Registered Office: Suite 2, Ground Floor, Orchard Brae House, 30 Queensferry Road, Edinburgh, EH4 2HS
​Registered Number: SC510322. Registered in Scotland
 
From: Samik Roy ***@***.***>
Sent: 07 January 2022 04:13
To: Azure/Azure-Sentinel ***@***.***>
Cc: Clive Watson ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] - Re: [Azure/Azure-Sentinel] https://github.com/Azure/Azure-Sentinel#resources has an invalid link (Issue #3839)


@CliveWatsonQC<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FCliveWatsonQC&data=04%7C01%7Cclive.watson%40quorumcyber.com%7C22041a22fcbc4138082708d9d193fcf4%7C4bd2cd737c3248aa8a02646c8bc0d343%7C1%7C0%7C637771255831229348%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=QEpGCvJvYyYWWbjqqi5tuTm2DnYY1sicmdbd%2FZS7RIA%3D&reserved=0> - This is updated now. Please have a check.

—
Reply to this email directly, view it on GitHub<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FAzure%2FAzure-Sentinel%2Fissues%2F3839%23issuecomment-1007126985&data=04%7C01%7Cclive.watson%40quorumcyber.com%7C22041a22fcbc4138082708d9d193fcf4%7C4bd2cd737c3248aa8a02646c8bc0d343%7C1%7C0%7C637771255831229348%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=%2BEYHSk%2B5jCe2S77mDw7a340JKkD6cRylv3D8%2BN1slKA%3D&reserved=0>, or unsubscribe<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAW46THECEGL3KY3ZRO3CKFTUUZR4TANCNFSM5LKBYS6A&data=04%7C01%7Cclive.watson%40quorumcyber.com%7C22041a22fcbc4138082708d9d193fcf4%7C4bd2cd737c3248aa8a02646c8bc0d343%7C1%7C0%7C637771255831229348%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=N1X%2FcB8tvLngzRIqTvZfeNJeOE%2Fdekum5OUb0DkUyyc%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Cclive.watson%40quorumcyber.com%7C22041a22fcbc4138082708d9d193fcf4%7C4bd2cd737c3248aa8a02646c8bc0d343%7C1%7C0%7C637771255831229348%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=00iFzfn04kemOXeNZH1iBJnhq6wJ2lqcd456FpcHYy0%3D&reserved=0> or Android<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Cclive.watson%40quorumcyber.com%7C22041a22fcbc4138082708d9d193fcf4%7C4bd2cd737c3248aa8a02646c8bc0d343%7C1%7C0%7C637771255831229348%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=z0Njv4Sf06ozungQxh5qa1ZVAaSQopqLw%2FACIA0sUu4%3D&reserved=0>.

**Comment by aprakash13** [comment]
Issue seems to be resolved. Closing this now. Thanks @samikroy for making the changes and @CliveWatsonQC for bringing this up.
