### ISSUE TITLE
Allow Variables in Logstash Output Plugin "custom_log_table_name" param

### ISSUE THREAD

**Issue by benatsb** [Azure/Azure-Sentinel#3881]
Hello, 
This is a feature request/change regarding the Logstash output plugin to Log Analytics. I'm attempting to reference a metadata field with the table name for the "custom_log_table_name".  I think this would be a welcome addition to the plugin. 

I do not know Ruby all that well, but I've linked a line below that is checking the value of the "custom log name" parameter. In comparison, the secretID and workspaceID are able to use a key store value with the syntax of "${secretvalue}" within the parameter. This same syntax I would like to use in referencing a metadata field. However, the "custom table name" is performing regex matche and not allowing the value to be parsed or a look up performed. 

Adding this feature would be great for a more dynamic processing capability in Logstash outputting to Log Analytics.

https://github.com/Azure/Azure-Sentinel/blob/60484322d19b86c5a83bba3518bc2601c8807fb7/DataConnectors/microsoft-logstash-output-azure-loganalytics/lib/logstash/logAnalyticsClient/logstashLoganalyticsConfiguration.rb#L31

**Comment by sarah-yo** [comment]
Hi @benatsb, thanks for your feedback! For feature requests, please add them here, thanks!

https://feedback.azure.com/d365community/forum/37638d17-0625-ec11-b6e6-000d3a4f07b8
