### ISSUE TITLE
AD account with Don't Expire Password  - incorrect rule logic

### ISSUE THREAD

**Issue by 82BBB00** [Azure/Azure-Sentinel#3940]
**Describe the bug**
Analytics Rule [AD account with Don't Expire Password](https://github.com/Azure/Azure-Sentinel/blob/08a8d2b9c5c9083e341be447773a34b56b205dee/Detections/SecurityEvent/password_never_expires.yaml) is False Positive sensitive because the Analytics Rule need some additional query.

**To Reproduce**
1. Make this alert trigger
2. Open Evidence > logs
See screenshot 1
3. Here you see that 'Don't Expire Password' - Enabled is enabled (%%2089)
4. However, if you search for all the events with the following query:
// start query 
SecurityEvent
| where Account contains "Name of account"
| where TargetUserName contains "Name of account"
// end of query

You see that Don't Expire Password' - Enabled has been disabled a little bit later (%%2057)
See screenshot 2

**Expected behavior**
I would like to see that there is some way in the analytics rule that it waits with a trigger and check first if the UserAccountControl did not change to %%2057 let's with a timeframe of 30 minutes later.

**Screenshots**
Screenshot 1:
<img width="535" alt="image" src="https://user-images.githubusercontent.com/96875510/149950553-9564f2f3-d307-47b6-829e-58e65f996b24.png">

Screenshot 2:
<img width="766" alt="image" src="https://user-images.githubusercontent.com/96875510/149951436-4822f1f9-972a-411b-9747-5aead94c857c.png">

**Comment by v-amolpatil** [comment]
Hi @82BBB00, thank you for flagging this. Apologies for the delayed response. If you still need assistance, please reply here within 5 business days.

**Comment by v-dvedak** [comment]
Since we have not received a response in the last 5 days, we are closing your issue #<3940> as per our standard operating procedures. If you still need support for this issue, feel free to re-open at any time. Thank you for your co-operation.
