### ISSUE TITLE
Parquet flow log format support for AWS S3 Connector

### ISSUE THREAD

**Issue by JPvRiel** [Azure/Azure-Sentinel#3952]
**Is your feature request related to a problem? Please describe.**

As per https://github.com/Azure/Azure-Sentinel/blob/3c28104fa7a83dfeb7d4132fcf726e818e5b6324/DataConnectors/AWS-S3/ConfigVpcFlowDataConnector.ps1#L25, it appears the default plaintext format for AWS VPC flog logs is assumed.

There does not appear to be any explicit support for using the Parquet format choice.

Neither is there any mention of Parquet support with the [Configure an AWS service to export logs to an S3 bucket](https://docs.microsoft.com/en-us/azure/sentinel/connect-aws?tabs=s3#configure-an-aws-service-to-export-logs-to-an-s3-bucket) reference in the Microsoft docs for the connector.

**Describe the solution you'd like**

As per [Amazon VPC Flow Logs now supports Apache Parquet, Hive-compatible prefixes and Hourly partitioned files](https://aws.amazon.com/about-aws/whats-new/2021/10/amazon-vpc-flow-logs-parquet-hive-prefixes-partitioned-files/) and the "Log file format" description at [Publish flow logs to Amazon S3](https://docs.aws.amazon.com/vpc/latest/userguide/flow-logs-s3.html#flow-logs-s3-create-flow-log), using the Parquet format can avoid 20% storage cost and is far more performant when queried via AWS Athena, etc - it's a better optimized format choice.

**Describe alternatives you've considered**

Using the plaintext format. However, for a large organization, the additional cost overhead of this sub-optimal format choice will impact cloud budget and possibly preclude use of VPC flow logging at scale. 

**Additional context**

Parquet is also a popular format for large volume data science use-cases and can be used in Jupyter notebooks and imported into pandas data-frames, so the format seems to be gaining wider popularity. E..g scalable python libraries like dask favor using optimized parquet data files to partition workloads for on-storage processing and avoiding memory overhead.

**Comment by v-jayakal** [comment]
@Danielohfeld - Can you please check this issue? Assigning this to you as you last worked on this connector, let us know if this does not belong to you. Thanks.

**Comment by danielohfeld** [comment]
I'm checking this issue with the relevant product manager

**Comment by danielohfeld** [comment]
The feature is supported under the private preview of AWS custom logs. Closing issue

**Comment by v-amolpatil** [comment]
Closing this issue based on previous comment here.
