### ISSUE TITLE
Playbooks template "Prompt-User" bug

### ISSUE THREAD

**Issue by ms-yaronsahar** [Azure/Azure-Sentinel#3963]
**Describe the bug**
Can't deploy this template. getting :

{  "code": "DeploymentFailed",  "message": "At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/DeployOperations for usage details.",  "details": [    {      "code": "InvalidTemplate",      "message": "The template validation failed: 'The template action 'Post_a_message_(V3)' at line '1' and column '2285' is not valid: \"Unable to parse template language expression '*sanitized*': expected token 'LeftParenthesis' and actual 'Identifier'.\".'."    }  ]}

**To Reproduce**
Try to deploy this template, it will failed eventually, tried with several WS and it's also failing on customer's env..

**Expected behavior**
Template is able to by deployed

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by dicolanl** [comment]
hi @ms-yaronsahar 
did you enter a teams id and teams channel id?  if you leave the default values it will fail.
