### ISSUE TITLE
SQLParser - Statement gets truncated

### ISSUE THREAD

**Issue by guarismo** [Azure/Azure-Sentinel#3968]
This is not capturing the whole statement, it gets truncated.
https://github.com/Azure/Azure-Sentinel/blob/28c966e6bf7f6987c03dc20db9ff72568049b256/Parsers/SQLSever/SQLServer_Parser.txt#L31

To fix I added the next field extraction below it:

```
| parse RenderedDescription with * "database_name:" DatabaseName:string
"schema_name:" Temp:string
"object_name:" ObjectName:string
"statement:" Statement:string
"additional_information:" AdditionalInfo:string
"." *
```

**Comment by aprakash13** [comment]
Fixed by the PR 3977 by @samikroy
