### ISSUE TITLE
ID duplicate

### ISSUE THREAD

**Issue by GKGAB-BenedictSchmieder** [Azure/Azure-Sentinel#3990]
The id "34c5aff9-a8c2-4601-9654-c7e46342d03b" can be found in two .yaml templates:
- Hunting Queries/SigninLogs/UserAccountsMeasurableincreaseofsuccessfulsignins.yaml
- Detections/MultipleDataSources/PrivilegedAccountsSigninFailureSpikes.yaml

**Comment by aprakash13** [comment]
The changes made by @samikroy have been merged now to update the Id.
