### ISSUE TITLE
https://github.com/Azure/Azure-Sentinel/pull/3957

### ISSUE THREAD

**Issue by CliveWatsonQC** [Azure/Azure-Sentinel#4002]
Hello, I'm not sure what the error is with the JSON file - the error text isn't helpful and the code looks ok

1 files changed in current PR after filter. File Type Filter: .json, File path Filter: Workbooks, File Kind Filter: Modified
WorkbooksMetadata Validation Failed. File path: Workbooks/WorkbooksMetadata.json. Error message: Cannot read properties of undefined (reading 'startsWith')

Please see https://github.com/Azure/Azure-Sentinel/pull/3957

![Screenshot 2022-01-25 095825](https://user-images.githubusercontent.com/96070044/150954793-e4079cd5-59d3-453a-947b-8178547990f9.png)

**Comment by CliveWatsonQC** [comment]
Any updates on this please?

**Comment by ritika-msft** [comment]
Closing the issue. As the check failure for workbook is resolved in another new PR #4089 and the PR #3957 is no more required.
