### ISSUE TITLE
Error creating new analytic rule

### ISSUE THREAD

**Issue by anfisher1967** [Azure/Azure-Sentinel#4007]
Trying to turn on Authentication Methods Changed for Privileged Account. It errors out in Set rule logic. "where operator:Failed to resolve table of column expressions named IdentityInfo
![authmeth](https://user-images.githubusercontent.com/33937240/151039339-42769237-20e4-40ba-bce0-68e5a8fdbe9f.JPG)
"

**Comment by samikroy** [comment]
@anfisher1967 - Could you please have a look if UBEA is configured in the mentioned workspace.
This should enable IdentityInfo table in the workspace.
Reference - 
https://docs.microsoft.com/en-us/azure/sentinel/enable-entity-behavior-analytics#:~:text=From%20the%20Microsoft%20Sentinel%20navigation,enable%20UEBA%2C%20then%20select%20Apply.

https://techcommunity.microsoft.com/t5/microsoft-sentinel-blog/what-s-new-identityinfo-table-is-now-in-public-preview/ba-p/2571037#:~:text=If%20already%20have%20UEBA%20enabled,Sentinel%20UEBA'%20group%20in%20LA.&text=The%20Identity%20info%20table%20contains,roles%20assigned%20and%20UEBA%20enrichments.

**Comment by samikroy** [comment]
@anfisher1967 - Could you please confirm this !

**Comment by v-amolpatil** [comment]
Hi @anfisher1967, Gentle Reminder: We are awaiting for your response on this issue. If you still need to keep this issue active please respond within next 2 days. If we don't receive response by 10 Feb 2023, we will close this issue.

**Comment by v-mchatla** [comment]
Hi @anfisher1967 - Since we have not received response from last 7 days, we are closing your issue as per our standard operating procedures. If you still need support for this issue you can re-open it at any time.
If you do re-open, we simply request that you ensure the issue has response to the last request. Thank you for your cooperation.
