### ISSUE TITLE
Scaleable SYSLOG CEF Collection using VMSS - Deploy to Azure not working

### ISSUE THREAD

**Issue by jpr2016git** [Azure/Azure-Sentinel#4011]
**Describe the bug**
The 'deploy to azure' button on 'Scaleable SYSLOG CEF Collection using VMSS' doesn't work.

**To Reproduce**
1. Go to https://github.com/Azure/Azure-Sentinel/tree/master/DataConnectors/CEF-VMSS 
2. Click on 'Deploy to Azure'

**Expected behavior**
NA

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by samikroy** [comment]
Updated the fix #4012

**Comment by samikroy** [comment]
@jpr2016git - please have a check now.
This should be fixed after the merge now.
