### ISSUE TITLE
Trouble finding data connector names ("kind" parameter) for Sentinel All-in-one deployment script 

### ISSUE THREAD

**Issue by garretlayel** [Azure/Azure-Sentinel#4019]
I am currently looking into incorporating the Sentinel all-in-one deployment script as an alternative method for the company I am currently with; however, I am having issues regarding the true connector names that are included within the connectors.json file. I was browsing the code and noticed that the name ("kind" parameter)  is different than that of the connector when actually browsing in Sentinel. My question is how can I find the coded and correct name for each connector? I want to possibly add or subtract different connectors to the provided script, but I first need the coded names to do so. I will paste some screen shots to visually show this issue. You can see that the connectors are labelled differently as they may have been renamed. 
![Screenshot 2022-01-26 193724](https://user-images.githubusercontent.com/96433807/151282051-7facd731-fb30-4c2a-95e3-84fdd2bb760c.png)
![Screenshot 2022-01-26 193743](https://user-images.githubusercontent.com/96433807/151282057-6d6d40a5-9bde-4119-b08f-76781fe219ec.png)
![Screenshot 2022-01-26 193756](https://user-images.githubusercontent.com/96433807/151282058-44fc3ebf-3872-4374-9bd0-d80c0c98ffb7.png)
![Screenshot 2022-01-26 193806](https://user-images.githubusercontent.com/96433807/151282061-2563402e-5537-4ebf-8be1-92517b69ffb6.png)
Thank you in advance for any help you can provide!

**Comment by Lodewyk-Git** [comment]
Hi, yes I've also noticed that all of the old names are still being used in the API, we get around it with variables. Here's some documentation on the [kind values:](https://docs.microsoft.com/en-us/rest/api/securityinsights/stable/data-connectors/create-or-update) 

You'll have to play around with it, we couldn't find documentation for a lot of features so it wasn't easy to set up our all-in-one deployment. 


Also consider using [bicep](https://docs.microsoft.com/en-us/azure/azure-resource-manager/bicep/) 
We've switched over to this almost 100% (Where we can of course) and it's much easier to read and maintain. [Bicep git](https://github.com/Azure/bicep) 

Best of luck!

**Comment by garretlayel** [comment]
Thank you so much @Lodewyk-Git I will give those a try!

**Comment by garretlayel** [comment]
@Lodewyk-Git I am curious if you can share how your deployment went. Was it successful? Did you have to change any of the scripts from the provided templates?

**Comment by javiersoriano** [comment]
As @Lodewyk-Git explained, the mapping between the actual names and the ones used by API are captured here: https://docs.microsoft.com/en-us/rest/api/securityinsights/stable/data-connectors/create-or-update
