### ISSUE TITLE
[DataConnectors/AWS-SecurityHubFindings]

### ISSUE THREAD

**Issue by sreekumarpg** [Azure/Azure-Sentinel#4031]
Hello All,

I have deployed the AWS SecurityHub Data connector from the template and provided the value in the ARM template.

While monitoring the AzFunAWSSecurityHubIngestion, I can see program is starting and fetching the SecurityHubFilters but issue is that after the fetch there is a error in the log
[Error]   4 events have not been sent

How can we troubleshoot this issue and find what is the root cause for this as I have provide the workspace ID as the Log Analytics workspace ID and for  Workspace Key provided Primary key under Agents management.

Someone help me to resolve this issue please
![image](https://user-images.githubusercontent.com/22677711/151528950-0a9c34d1-6681-4943-9a4a-95d08144c00f.png)

**Comment by sreedharande** [comment]
@sreekumarpg - As per our discussion, this issue has been resolved
