### ISSUE TITLE
Azure-Sentinel .yaml format description?

### ISSUE THREAD

**Issue by adulau** [Azure/Azure-Sentinel#404]
**Is your feature request related to a problem? Please describe.**

We are maintaining [MISP](https://github.com/MISP/MISP) and we have seen people sharing specific rule-sets like Sigma. Is the format .yaml format in Azure-Sentinel related to [Sigma](https://github.com/Neo23x0/sigma)? or is it a specific format? If yes, do you have a schema description available. We would like to make a specific parser to extract the data and feed it into MISP format.

**Comment by shainw** [comment]
I believe this covers what you are looking for, but if not, please let me know - https://github.com/Azure/Azure-Sentinel/wiki/Query-Style-Guide.

Thanks,
Shain

**Comment by shainw** [comment]
Closing, assuming the previous response answered your question.

**Comment by adulau** [comment]
It was perfect, thank you. By the way, [MISP](https://www.misp-project.org/) now includes a new attribute type called [kusto-query](https://github.com/MISP/MISP/commit/7a82a9f8d73e3565b8b880476bffccfe08afb57d) to share query within MISP events.
