### ISSUE TITLE
GitHub parser doesn't fits to new data connector (solution) for GitHub Enterprise

### ISSUE THREAD

**Issue by Cloud-Architekt** [Azure/Azure-Sentinel#4042]
**Describe the bug**
The new Continuous Threat Monitoring for GitHub solution includes a data connector for polling GitHub audit log data to Sentinel natively. Previously a [custom solution for collecting GitHub data](https://techcommunity.microsoft.com/t5/microsoft-sentinel-blog/protecting-your-github-assets-with-azure-sentinel/ba-p/1457721) with Logic Apps (and Azure Function) was the only available solution. The new solution from the content hub includes the same parser as the previous solution. But the data connectors ingest data to another table (GitHubAuditLogPolling_CL instead of GitHub_CL). Data fields are also not matching between the two solutions.

**To Reproduce**
1. Install the Continuous Threat Monitoring for GitHub from the content hub
2. Load the function of the parser to the workspace and run the query
3. Scroll down to "Failed to resolve table or column expression named 'GitHub_CL'"

**Expected behavior**
Deployed parser in content hub solution should fits to the data connector.

**Screenshots**
![Parser](https://user-images.githubusercontent.com/47817884/151664047-7c1fa123-e80f-4865-b74a-3c0be6d92aaf.png)

**Additional context**
Data fields (columns) also not fits to the ingested data.
Many relevant data fields are not ingested from GitHub audit log (such as IP address).

**Comment by dicolanl** [comment]
@kobymymon could you look at this?

**Comment by kobymymon** [comment]
Hi @Cloud-Architekt,
We're fixing this issue in the solution itself, the bug is with the table name.
please change it to - GitHubAuditLogPolling_CL
and let me know if it works now (it should).
thanks for sharing this!
Koby

**Comment by corpca-Admin** [comment]
Hi @kobymymon,

changing the table wouldn't help. The column names in the parser are wrong and don't match to the connector from the solution. ![image](https://user-images.githubusercontent.com/97869526/152141665-d07e9380-28f0-4638-8eb4-6e9a8c94a8f3.png)

I've already tried to match the columns to the names in the table. But a high number of columns are not exists and will be not ingested by the data connector (node_actorLocation_city_s, node_user_email_s, node_actorIp_s).

Thomas

**Comment by Cloud-Architekt** [comment]
Hi @kobymymon,

changing the table wouldn't help. The column names in the parser are wrong and don't match to the connector from the solution.
![image](https://user-images.githubusercontent.com/47817884/152142025-acd81308-d8e1-4d1e-a9d4-47e2d94b955e.png)


I've already tried to match the columns to the names in the table. But a high number of columns are not exists and will be not ingested by the data connector (node_actorLocation_city_s, node_user_email_s, node_actorIp_s).

Thomas

**Comment by kobymymon** [comment]
Hi @Cloud-Architekt,
can you run this query - 

```
GitHubAuditLogPolling_CL
| project TimeGenerated=TimeGenerated,
    Organization=columnifexists('node_organizationName_s', ""),
    Action=action_s,
    OperationType=Type,
    Repository=columnifexists('node_repositoryName_s',""),
    Actor=columnifexists('node_actorLogin_s', ""),
    IPaddress=columnifexists('node_actorIp_s', ""),
    City=columnifexists('node_actorLocation_city_s', ""),
    Country=columnifexists('node_actorLocation_country_s', ""),
    ImpactedUser=columnifexists('node_userLogin_s', ""),
    ImpactedUserEmail=columnifexists('node_user_email_s', ""),
    InvitedUserPermission=columnifexists('node_permission_s', ""),
    Visability=columnifexists('node_visibility_s', ""),
    OauthApplication=columnifexists('node_oauthApplicationName_s', ""),
    OauthApplicationUrl=columnifexists('node_applicationUrl_s', ""),
    OauthApplicationState=columnifexists('node_state_s', ""),
    UserCanInviteCollaborators=columnifexists('node_canInviteOutsideCollaboratorsToRepositories_b', ""),
    MembershipType=columnifexists('node_membershipTypes_s', ""),
    CurrentPermission=columnifexists('node_permission_s', ""),
    PreviousPermission=columnifexists('node_permissionWas_s', ""),
    TeamName=columnifexists('node_teamName_s', ""),
    Reason=columnifexists('node_reason_s', ""),
    BlockedUser=columnifexists('node_blockedUserName_s', ""),
    CanCreateRepositories=columnifexists('canCreateRepositories_b', "")
```

when i run it, i get these results:
<img width="670" alt="Screen Shot 2022-02-02 at 13 20 20" src="https://user-images.githubusercontent.com/74963647/152144429-d7306f8f-f40e-4c37-83a2-bbef5e09a3bc.png">

**Comment by Cloud-Architekt** [comment]
The query can be executed. Nevertheless the mapping is still wrong because of the different table names between the data connector from the content hub solution and the previous data connector from the GitHub repo.

For example:
CurrentPermission / PreviousPermission is not listed because node_permission_s/node_permissionWas_s doesn't exist:
![image](https://user-images.githubusercontent.com/47817884/152165347-b171f77a-c377-4bca-a3f9-555ae8c1d1f7.png)

Correct column name should be old_permission_s and permission_s:
![image](https://user-images.githubusercontent.com/47817884/152165805-b13c0b3d-4a59-47c7-841d-d535a3768dfd.png)

As far as I can see, the parser must be re-written for the schema of the data connector.

**Comment by kobymymon** [comment]
@Cloud-Architekt 
Thanks Thomas.
We'll fix that and release the new version by tomorrow. I'll keep you update.
thanks for the feedback!
