### ISSUE TITLE
Is the intention here to search for the IPaddresses in the process name (maybe it should be the command line)?

### ISSUE THREAD

**Issue by oshezaf** [Azure/Azure-Sentinel#4054]
https://github.com/Azure/Azure-Sentinel/blob/1a1d450126eb3c8eb13055ac9709070ecab1b8d0/Detections/MultipleDataSources/WSLMalwareCorrelation.yaml#L119

@shainw

**Comment by aprakash13** [comment]
Thanks @oshezaf / @samikroy for handling this.
