### ISSUE TITLE
Failed to get HTTP response because of invalid input (DRAFT, queryData) in Run query and list results 2 of Get_sentinelAlertsEvidence

### ISSUE THREAD

**Issue by smaheux21** [Azure/Azure-Sentinel#4055]
**Describe the bug**
We are adding the Get-SentinelAlertsEvidence and when I run it from a Sentinel indicent I have the Failed to get HTTP response because of invalid input (DRAFT, queryData). Bad request input. Please Check user input parameters (query syntax, chart type or other resource input)\r\nclientRequestId: 

**To Reproduce**
1. Go to 'Sentinel Incident  - View full details - Alerts - View Playbook'
2. Click on RUN
3. Go Back to automation, Active Playbook and in overview we can see last execution failed
4. See error in Run details

**Expected behavior**
Suppose to have a copy of the incident and the related entities in Event Hub

**Screenshots**
![image](https://user-images.githubusercontent.com/98770056/151862858-160383c6-29d8-4380-a948-abdcefef38c3.png).

**Comment by simonkudla** [comment]
Hi, I am also experiencing the same issue with my workflow.

Did you happen to find a solution to this?

**Comment by samikroy** [comment]
@smaheux21 - Could you please share a screenshot of the run failure similar to this 
Was able to get the data from log analytics
![image](https://user-images.githubusercontent.com/20562985/152733230-7a63df89-957f-419d-a394-a5b9c9ea570f.png)

**Comment by smaheux21** [comment]
![image](https://user-images.githubusercontent.com/98770056/152786357-9baa603f-b09b-4487-98f9-70a241a80cff.png)

{
  "ResultStatus": "BadRequest",
  "Content": {
    "error": {
      "message": "The request had some invalid properties",
      "code": "BadArgumentError",
      "correlationId": "c8cf97ee-635a-403f-969e-09f3e5c14709",
      "innererror": {
        "code": "SyntaxError",
        "message": "A recognition error occurred in the query.",
        "innererror": {
          "code": "SYN0002",
          "message": "Query could not be parsed at 'datetime()' on line [2,42]",
          "line": 2,
          "pos": 42,
          "token": "datetime()"
        }
      }
    }
  },
  "Message": "Failed to get HTTP response because of invalid input (DRAFT, queryData). Bad request input. Please Check user input parameters (query syntax, chart type or other resource input)\r\nclientRequestId: e3079328-0ae1-4c0b-901f-02bbea52a741"
}

**Comment by samikroy** [comment]
@smaheux21 - 
Seems like you might need to authenticate the Log Analytics Connection
![image](https://user-images.githubusercontent.com/20562985/152839721-4ded60c8-2bbc-4c1e-802d-d387f0749fbb.png)

And then you should be able to see the query 

![image](https://user-images.githubusercontent.com/20562985/152839872-d56cb31c-1d18-42ef-824b-ba558298189a.png)

please give this a try and let me know

**Comment by samikroy** [comment]
@smaheux21 - Could you please have a look if this is resolved.

**Comment by smaheux21** [comment]
Yes it is resolved

**Comment by keeshulsbos** [comment]
I have tried to Implement the Playbook according to the information published on the GitHub url: https://github.com/Azure/Azure-Sentinel/tree/master/Playbooks/Get-SentinelAlertsEvidence. I'm stuck with an error in the Logic app. The error message is: 

InvalidTemplate. Unable to process template language expressions in action 'Parse_JSON' inputs at line '0' and column '0': 'Required property 'content' expects a value but got null. Path ''.'.

I would like to have the Alerts created within Sentinel to be uploaded to the EventHub.

The strange thing is that it occurs on two different Microsoft Tenants. Same installation process but I'm not able to resolve this. 
![GitHub-Sentinel Playbook Logic App error](https://user-images.githubusercontent.com/43389013/199704922-a1e9ecfc-4b82-4178-88eb-983e44953ac6.png)
I can't find anything useful on the Internet and I'm new to Microsoft Sentinel so learning every day.
