### ISSUE TITLE
Playbooks cannot be saved. The request content is not valid and could not be deserialized: 'Could not find member 'defaultValue' on object of type 'FlowTemplateParameter'.

### ISSUE THREAD

**Issue by Pagni** [Azure/Azure-Sentinel#408]
Logic Apps cannot be created from the json files available in the Playbooks folder.

**To Reproduce**
1. Go to 'https://raw.githubusercontent.com/Azure/Azure-Sentinel/master/Playbooks/Block-AADUser.json' and copy the content.
2. Paste into a new logic app.
3. Click save.
4. See error:
*Failed to save logic app 'APPNAMEHERE'. The request content is not valid and could not be deserialized: 'Could not find member 'defaultValue' on object of type 'FlowTemplateParameter'. Path 'properties.parameters.PlaybookName.defaultValue', line 1, position 968.'.*

![image](https://user-images.githubusercontent.com/58553718/70995210-e9b8bb00-20c7-11ea-80eb-ff59843a66b8.png)

**Expected behavior**
Successful save.

**Desktop (please complete the following information):**
 - OS: Win10
 - Browser: Chrome
 - Version:  Up to date.

**Comment by petebryan** [comment]
Thanks for raising @Pagni  - this Playbook was created by @dicolanl - perhaps he can shed some light on this issue.

**Comment by Pagni** [comment]
Hi @petebryan,
Thanks for following up.

This is user error by me. I thought I could simply create a blank logic app from inside Sentinel and use the code.
Should have paid more attention to the Playbooks README.

Closing off.
