### ISSUE TITLE
Virus Total URL Enrichment API Error

### ISSUE THREAD

**Issue by Dan156478** [Azure/Azure-Sentinel#4082]
**Describe the bug**
API error when attempting to use URL enrichment playbooks
-URL Enrichment - Virus Total domain report
-URL Enrichment - Virus Total report

**To Reproduce**
1. Enable & Configure Playbook
2. Open Logic App Designer
3. Expand 'Get Domain report' or 'Get URL Report'
4. See error: "Operation not found under connector '/subscriptions/<subscription>/providers/Microsoft.Web/locations/<location>/managedApis/virustotal'
5. After execution, step will show error output: 
"{
  "statusCode": 404,
  "message": "Resource not found"
}"

**Expected behavior**
No error and playbook execution completion

**Screenshots**
![image](https://user-images.githubusercontent.com/35740405/152231852-422ce3cc-b9bb-411e-9603-db80a22a4744.png)

**Desktop (please complete the following information):**
 - OS: Win 11
 - Browser Chromium Edge
 - Version 97

**Additional context**
No issues running other VirusTotal Enrichment Playbooks, such as File Hash or IP.

**Comment by dicolanl** [comment]
@Dan156478  seems like the connection didnt deploy.  if you click on API Connections do you see the connection resource?  like this:
![image](https://user-images.githubusercontent.com/25964057/152382253-58b7de8d-8475-4a8c-ab28-48afc7b2900d.png)

**Comment by Dan156478** [comment]
Hi @dicolanl, Looks to be be deployed & connected. I've tried using an existing connection that we are successfully using for the VirusTotal FileHash & IP playbooks, and also tried creating a new connection, both result in the same error.
![image](https://user-images.githubusercontent.com/35740405/152384288-09a129ac-59b2-4bf3-93c6-fc0fd15bc08e.png)

**Comment by dicolanl** [comment]
@Dan156478  found the issue that get url report action doesnt exist anymore and has been replaced.  i updated the logic app and submitted a new PR.

**Comment by Dan156478** [comment]
@dicolanl Perfect, thank you!

**Comment by mirek-elk** [comment]
Hi, the same happens for me with Get IP report (same error, and it worked until last week)
