### ISSUE TITLE
UserAgent log4j

### ISSUE THREAD

**Issue by yaronMSFT** [Azure/Azure-Sentinel#4093]
**Describe the bug**
- User Agent Regex can be improved to be more robust and comprehensive
- The Regex does not identify the literal attack vectors given in UserAgentString
-  The regex searches for url-encoded chars, such as  encoding of { as "%7B". This will miss "%7b". I suggest using the [url_decode function](https://docs.microsoft.com/en-us/azure/data-explorer/kusto/query/urldecodefunction)
- Also, using tolower prior to regex matching could make the regex expression much simpler.

**To Reproduce**
Run the following query - the UA regex misses the known simple vectors: 

`let GithubUARegex = @'(\\$|%24)(\\{|%7B)([^jJ]*[jJ])([^nN]*[nN])([^dD]*[dD])([^iI]*[iI])(:|%3A|\\$|%24|}|%7D)';
 let ProposedRegex = @'(\$|%24)(\{|%7B)([^jJ]*[jJ])([^nN]*[nN])([^dD]*[dD])([^iI]*[iI])(:|%3A|\$|%24|}|%7D)';
 let UA=datatable(UserAgent:string)["${jndi:ldap:/"
   , "${jndi:rmi:/"
   , "${jndi:ldaps:/"
   , "${jndi:dns:/"
   , "${jndi:iiop:/"
   ,"${jndi:"
    ,"${jndi:nds:/"
    ,"${jndi:corba/"
    ,"%24%257bjNdi:rmi%3A"];
    UA 
    | extend 
      RevisedRegex=UserAgent matches regex ProposedRegex
    , GHRegex       =UserAgent matches regex GithubUARegex 
   , RevisedRegexOverUrlDecoded = tolower(url_decode(url_decode(UserAgent))) matches regex ProposedRegex
  , decodedUA = tolower(url_decode(url_decode(UserAgent))) `

**Comment by yaronMSFT** [comment]
You are welcome x 3, github bot. 
Sorry for the code formatting, it did not transmit well

**Comment by v-amolpatil** [comment]
Since we have not received a response in the last 5 days, we are closing your issue #4093 as per our standard operating procedures. If you still need support for this issue, feel free to re-open at any time. Thank you for your co-operation.
