### ISSUE TITLE
CrowdstrikeFalconAPISentinelConnector is ignoring secondary events

### ISSUE THREAD

**Issue by ZLT-ops** [Azure/Azure-Sentinel#4126]
**Describe the bug**
CrowdstrikeFalconAPISentinelConnector is ignoring the secondary events that it pulls from the SQS URL

**To Reproduce**
1. Enable the integration between CrowdStrike and Sentinel using the ContentHub
2. Input all the necessary fields
3. Go to the function app in Azure
4. See the Monitor 

**Expected behavior**
All the Events should be in Sentinel not just the raw events from the data file

**Screenshots**
<img width="1399" alt="Screen Shot 2022-02-08 at 10 24 10 AM" src="https://user-images.githubusercontent.com/96545016/153051736-e9412300-643b-475e-9743-cabf476e73fa.png">

<img width="901" alt="image" src="https://user-images.githubusercontent.com/96545016/153052352-82f9d417-5e8a-421e-82cc-e55c5694bdd2.png">

<img width="976" alt="image" src="https://user-images.githubusercontent.com/96545016/153052397-035e691f-ff5d-4e0e-ac47-7403c2f919f4.png">

<img width="856" alt="image" src="https://user-images.githubusercontent.com/96545016/153052600-3d2c4988-35a4-4753-a23c-85814b05044e.png">

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Chrome

**Comment by ZLT-ops** [comment]
Maybe it's because the Logsource has more than 500 properties, that is just a speculation

**Comment by v-rucdu** [comment]
@ZLT-ops : This seems to be a very old problem, and this connector may have already had numerous updates, can you please check if your problem has been solved? Thanks!!

**Comment by v-amolpatil** [comment]
@ZLT-ops As per previous comment closing this issue. Feel free to reopen the issue if you need more assistance. Thanks!
