### ISSUE TITLE
Microsoft Sentinel & Cisco Umbrella Data Connector

### ISSUE THREAD

**Issue by djkered** [Azure/Azure-Sentinel#4131]
I have tried connecting the Cisco Umbrella Data Connecter, but it is not pulling any data. I have followed the steps and I still get these 3 failed connections.

![image](https://user-images.githubusercontent.com/60485104/153072966-9c22fb34-454d-4e1a-ae96-b51d0d9c155b.png)

Anyone have a how to or possibly a fix for this?

**Comment by ritika-msft** [comment]
Hi @djkered , can you please confirm if dns, proxy , ip and firewall settings are correctly configured for your Cisco Umbrella account? https://docs.umbrella.com/deployment-umbrella/docs/log-formats-and-versioning
	https://docs.umbrella.com/deployment-umbrella/docs/manage-intelligent-proxy
	https://docs.umbrella.com/deployment-umbrella/docs/point-your-dns-to-cisco

And do you see logs getting pushed daily in all the below shown folders for your AWS S3 bucket?
![image](https://user-images.githubusercontent.com/53035464/157853855-345a1f35-393c-4769-8987-5a63f1a1d61a.png)

**Comment by ashishsyal** [comment]
@djkered - Please share an update.

**Comment by ashishsyal** [comment]
@djkered  - Was it resolved for you?

**Comment by ashishsyal** [comment]
Please share if that is still not working for you.

**Comment by ashishsyal** [comment]
In case of no response, we will close the issue in next 2 working days. Please feel free to raise another one in case of any issues.

**Comment by vmanojreddy** [comment]
we are closing this issue as we did not hear back from you. Please feel free to reopen the issue with more details if the issue still persist... Thanks!!!

**Comment by warpedbubble** [comment]
@djkered Did you ever find a solution to this? We are experiencing the same thing.

@vmanojreddy @ashishsyal , I do see files/data in the events, proxylogs and auditlogs folders but only seeing the DNS connector as green in Sentinel
