### ISSUE TITLE
RiskIQ Solution not authorizing during deployment

### ISSUE THREAD

**Issue by ml58158** [Azure/Azure-Sentinel#4132]
**Describe the bug**
When the RiskIQ solution is deployed to Sentinel , the API Connection does not automatically authorize which causes the playbooks to fail when ran. 

**To Reproduce**
1. Deploy the RiskIQ solution from the ContentHub blade.
2. Once fully deployed, run a riskiq playbook against an alert or incident with external facing data. 
3. Notice that the RiskIQ data does not populate in the comments section of the incident. 
4. Click on the logic app run results and look at the run details.
5. Notice that connections fails with error: 401 unauthorized .

Next,
1. Navigate to the Logic Apps section on Azure.
2. Select one of the RiskIQ logic apps.
3. Click on Api-Connections and select the api-connection named after the playbook.
4. Click on Edit API connection
5. Click on the blue Authorize button and authenticate .
6. Click Save.
7. Go back to the incident and rerun the playbook .
8. Notice the playbook now runs successfully and comments the data in the incident. 
(Note this has to be for all 28 playbooks)

**Expected behavior**
The expected behavior is the solution deploys and the playbooks run successfully .
![2022-02-08 15_57_03-azuresentinel-RiskIQ-Intel-Summary-Domain-Alert-Trigger - Microsoft Azure - Work](https://user-images.githubusercontent.com/11156002/153074385-488909ce-f024-4117-8ff2-9803370ea854.png)

**Comment by v-rucdu** [comment]
@ml58158 : This seems to be a very old problem, and this solution may have already had numerous updates... Can you please check if this scenario is still valid? Thanks!!

**Comment by v-mchatla** [comment]
Hi @ml58158,
We have added this information part of post deployment steps in our later releases. Hope this could fixed the issue. Let us know if you need any other details or suggestions.
![image](https://user-images.githubusercontent.com/108806639/211774204-ea6ee538-12c3-420a-9b62-49bbc174b1d5.png)
Thanks
