### ISSUE TITLE
Trim function not parsing correctly 

### ISSUE THREAD

**Issue by Lodewyk-Git** [Azure/Azure-Sentinel#4138]
**Describe the bug**
When I use the trim function it struggles to remove values such as '"' and ',' - I can't get these values out. When testing this on an online regex  - like [regexr](https://regexr.com/ ) - it removes the quotations
To get around this I am using the mv-expand method

**To Reproduce**
Try the following trim:
`SecurityIncident
| extend Tactics = trim(@'[["\]]+',tostring(AdditionalData.tactics))`

**Expected behavior**
No unexpected quotes

**Screenshots**
Expected:
![image](https://user-images.githubusercontent.com/36856692/153202365-de52423a-d96f-4e07-a497-4af92fafd33f.png)
Actual result:
![image](https://user-images.githubusercontent.com/36856692/153202406-07cb28a3-f44b-4628-8b49-7dc6b342248e.png)

**Additional context**
To get around this I'm using the following method of parsing:
`SecurityIncident
| mv-expand AdditionalData
| extend ProductName = parse_json(tostring(AdditionalData.alertProductNames))
| mv-expand ProductName
| extend tactics = parse_json(tostring(AdditionalData.tactics))
| mv-expand tactics`

I'd like to get unique values using the trim method.

**Comment by tvuylsteke** [comment]
Hey @Lodewyk-Git, not really an answer as to why trim isn't removing the double quotes. But I believe I've found a possible workaround using the strcat_array function

SecurityIncident | extend Tactics = strcat_array(AdditionalData.tactics,",")

The result is a Tactics columns with no ",[ or ] in it.

**Comment by Lodewyk-Git** [comment]
Thank you @tvuylsteke! This is a very helpful function.

**Comment by shainw** [comment]
@Lodewyk-Git - I don't think Trim will do what you are asking and isn't designed for it based on documentation.  Trim operates only on the start and end of the string, which is what it appears to be doing in your testing - https://docs.microsoft.com/en-us/azure/data-explorer/kusto/query/trimfunction.

I think that replace_regex() does what you want - https://docs.microsoft.com/en-us/azure/data-explorer/kusto/query/replace-regex-function

```
SecurityIncident
| project Title, AdditionalData
| where AdditionalData.tactics != '[]'
| where array_length( AdditionalData.tactics) > 1 //just here to test with more than one tactic, remove
| extend tactics = AdditionalData.tactics
| extend lngth = array_length(AdditionalData.tactics)
| project Title, tactics
| extend Tactics_replace = replace_regex(tostring(tactics), @'[["\]]+', '')
```
