### ISSUE TITLE
Unable to deploy ARM Template for Zero Trust Workbook

### ISSUE THREAD

**Issue by lisamurphy-msft** [Azure/Azure-Sentinel#4146]
**Describe the bug**

Unable to deploy the ARM template provided at: 
https://raw.githubusercontent.com/Azure/Azure-Sentinel/master/Solutions/ZeroTrust(TIC3.0)/Package/mainTemplate.json

**To Reproduce**
```
az deployment group create \
--name $deploymentName \ 
--resource-group $resourceGroupName \
 --template-uri https://raw.githubusercontent.com/Azure/Azure-Sentinel/master/Solutions/ZeroTrust\(TIC3.0\)/Package/main
Template.json
```
This will fail to deploy with the following output: 
```
{'code': 'InvalidTemplate', 'message': "Deployment template validation failed: 'The template resource '/Microsoft.SecurityInsights/e9610775-45d1-46d0-a945-8a4d653b5e7e' for type 'Microsoft.OperationalInsights/workspaces/providers/alertRules' at line '224' and column '77' has incorrect segment lengths. A nested resource type must have identical number of segments as its resource name. A root resource type must have segment length one greater than its resource name. Please see https://aka.ms/arm-template/#resources for usage details.'.", 'additionalInfo': [{'type': 'TemplateViolation', 'info': {'lineNumber': 224, 'linePosition': 77, 'path': 'resources[1].type'}}]}
```

**Expected behavior**
I expect it to deploy as expected. 

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] N/A Azure CLI
 - Browser [e.g. chrome, safari] N/A
 - Version [e.g. 22] 2.32.0

**Additional context**

**Comment by vmanojreddy** [comment]
We updated latest package can you please go through that. Please provide more details if the issue still persist. thanks!!!

**Comment by vmanojreddy** [comment]
@lisamurphy-msft We updated latest package can you please go through that. Please provide more details if the issue still persist. thanks!!!

**Comment by vmanojreddy** [comment]
@lisamurphy-msft We updated latest package can you please go through that. Please provide more details if the issue still persist. thanks!!!

**Comment by lisamurphy-msft** [comment]
@vmanojreddy Thank you for responding; this can be resolved; the issue was missing a required parameter in the CLI interface. 
Adding `--parameters workspace=<workspace_name>` fixed this for me.

**Comment by vmanojreddy** [comment]
@lisamurphy-msft Thank you for update and sorry for late reply. We check the main template and deploy the solution at time deploying we got error property is missing so we have update package and published the package. 
We are closing this issue it be resolved. thanks!!!
