### ISSUE TITLE
Multi-incident Investigate

### ISSUE THREAD

**Issue by Lodewyk-Git** [Azure/Azure-Sentinel#4152]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
I'd like to be able to select Incidents from the Incidents overview and then bulk Investigate, this should have two features:

1. Everything has it's entities associated with all alerts in the Investigation graph, similar to fusion alerts, with associations made where entities match.
2. All of the alerts should be grouped and should be accessible in Sentinel when Investigating like this
3. This should be especially relevant for all Incidents of the same type
4. This should not create a new event in The SecurityIncident table, unless configured as related

**Describe alternatives you've considered**
I've written a custom query that allows me to filter through the securityalert and securityincident tables that matches based on systemalertID so that I can investigate seemingly relevant data together

**Additional context**
I was looking at 6 Incidents of the exact same type and really just wanted to view them in a similar way to how I can view mult-stage Incidents, without having to do what I normally do, which is using KQL to get the data that I want.

**Comment by samikroy** [comment]
@Lodewyk-Git - This is great use case, did you come across this alert grouping for any incident. This might be helpful in your case
https://techcommunity.microsoft.com/t5/microsoft-sentinel-blog/what-s-new-reduce-alert-noise-with-incident-settings-and-alert/ba-p/1187940

**Comment by samikroy** [comment]
@Lodewyk-Git - The query looks good.
For this feature to be a part of the product please share your feedback to 
https://feedback.azure.com/d365community/forum/37638d17-0625-ec11-b6e6-000d3a4f07b8
