### ISSUE TITLE
Two detection rules should add IdentityInfo as required data type

### ISSUE THREAD

**Issue by javiersoriano** [Azure/Azure-Sentinel#4197]
Affected detection rules:

- Privileged Accounts - Sign in Failure Spikes: https://github.com/Azure/Azure-Sentinel/blob/27dfdca9a382b1b65abb4a6256a51d7e22b9ac0d/Detections/MultipleDataSources/PrivilegedAccountsSigninFailureSpikes.yaml
- Authentication Methods Changed for Privileged Account: https://github.com/Azure/Azure-Sentinel/blob/6746bec52043c39b29e13d9348df8bae043d7988/Detections/MultipleDataSources/AuthenticationMethodsChangedforPrivilegedAccount.yaml 

Please add IdentityInfo as required dataType. Right now it makes customers think UEBA would not be needed, which is untrue.

**Comment by Lodewyk-Git** [comment]
Hey @javiersoriano, I believe that data type isn't released to Sentinel yet.
M365 Defender:
![image](https://user-images.githubusercontent.com/36856692/154639422-bf952a93-ceac-469c-8176-94c862525a9e.png)

Sentinel:
![image](https://user-images.githubusercontent.com/36856692/154639453-dfdda264-e29a-48b3-a429-cc7ebdda37cd.png)


So not sure what the overarching connectorId will be as it seems the previous connectorIds are related to the solutions name like.

MDE:
![image](https://user-images.githubusercontent.com/36856692/154639621-16bd12d5-f2ad-43fa-87ee-26ba8272d3e5.png)

MDO: 
![image](https://user-images.githubusercontent.com/36856692/154640039-d33eb41a-9974-4285-9a8d-29381a32344f.png)

So IdentityInfo might be under MCAS? 🤷‍♂️

**Comment by javiersoriano** [comment]
IdentityInfo is not a table attached to any data connector. It is a table created by UEBA engine that contains a snapshot of Azure AD users. We need to find a way to capture that UEBA is required to make this rule work, because right now customers think that the rule will just work with SigninLogs

**Comment by Lodewyk-Git** [comment]
I see your point, I should have looked harder:
![image](https://user-images.githubusercontent.com/36856692/154799085-3e64f518-4c96-4848-be54-6709d2ad0dbb.png)

Are you saying a check has to occur that makes sure that UEBA is enabled for Identities?

Is there a way to test from ARM templates? I've not seen a section for the required types before from your All-in-one solution (Be it because I wasn't looking hard enough or another reason)

**Comment by javiersoriano** [comment]
It doesn't need to check it, but just show that UEBA is required or else the detection won't work.

**Comment by oshezaf** [comment]
@javiersoriano : the list of connectors does not imply require. It implies used. In most if not all cases, the list is the list of tables that can be used but none is required. I understand the challenge, but I am not sure this is the solution. Maybe a feature request about the issue will let Ron work on a solution.
