### ISSUE TITLE
ASimNetworkSession error when used as a string

### ISSUE THREAD

**Issue by puijjar** [Azure/Azure-Sentinel#4215]
**Describe the bug**
Sentinel appears to replace string "ASimNetworkSession" with the contents of the function.

**To Reproduce**
Query:
print "ASimNetworkSession"

Error:
Query could not be parsed at 'SrcProcessId' on line [715,20]

**Expected behavior**
Prints ASimNetworkSession into results.

**Additional context**
The error which displays the bug is caused by a typo in the current version of ASimNetworkSessionMicrosoftWindowsEventFirewall. How does this pass your test pipelines? The debugging process was a miserable experience.

Network ASIM is currently not working at all due to using the string described in the bug.

**Comment by tvuylsteke** [comment]
Hey @puijjar, I believe this has to to with an issue in how kusto parsers the queries. Shortly after you experienced this I've also escalated this and for now the workspace deployed parser has been updated and should not run into this issue any more.

I believe updating the ASimNetworkSession parser with the latest on the repo should make your issue go away.

The change I'm referring to is on this line: https://github.com/Azure/Azure-Sentinel/blob/2dc5f99ab7bfa20f003ac10c87b392c3226a2230/Parsers/ASimNetworkSession/Parsers/ASimNetworkSession.yaml#L31

@oshezaf just for your information.

**Comment by oshezaf** [comment]
So @tvuylsteke , @puijjar is correct :-(. While LA does not actually replaces function name in strings with the content of the function, it verifies it.

This is a known and hard to fix LA bug. It also happens in comments by the way. We fixed this specific one by fixing the underlying function, so the latest from the repo should indeed help. More generally, we are replacing the function names in strings which we use today with a different string to bump into the issue less.
