### ISSUE TITLE
Inaccurate listing of Active Products - M365 Defender Connector

### ISSUE THREAD

**Issue by clivewatson** [Azure/Azure-Sentinel#4229]
**Describe the bug**
Only MDE is listed as an **Active** Product

**To Reproduce**
1. In Sentinel, open Data Connectors blade
2. select "Microsoft 365 Defender (Preview)"
3. Open Connector Page

**Expected behavior**
All products that are active to be listed.  You can see in the screenshot, MDE and MDO are enabled, but only MDE shows in the list.

**Screenshots**
![image](https://user-images.githubusercontent.com/19288031/154966005-b08b91c8-6a6f-4169-a532-8f547e8559b5.png)

**Comment by sarah-yo** [comment]
@clivewatson can you raise this as a bug and in a support ticket through the portal, please? :)
