### ISSUE TITLE
SharePoint and Onedrive Workbook Parameter UserID Lookup Fix 

### ISSUE THREAD

**Issue by benatsb** [Azure/Azure-Sentinel#4245]
**Describe the bug**
Link to workbook:
https://github.com/Azure/Azure-Sentinel/blob/master/Workbooks/SharePointAndOneDrive.json

The "SharePoint and OneDrive workbook" parameter "Users" does not work when "All" operations are selected. 

It appears the intended functionality is to perform a unique user ID lookup based on the operations selected via dropdown. However, when the option "all" is selected for operations the only option available for Users is "all". This is not desirable when you want to filter on a specific user ID when using "all" operations.

The KQL statement for the Users list is looking for a dynamic/array in variable "operations", but if the operations drop down is selected as "all" there are no results returned as the queries throughout the workbook use a "where all or checkbox items" logic and label for the parameter. This means the Users lookup is matching on a null variable lookup from "operations" and no user IDs are returned.

The solution I used was to check the Operations parameter for "all" and if so return a list of all users IDs.

Link to the specific line:
https://github.com/Azure/Azure-Sentinel/blob/2b422a934b0eb518bc4d9da1f7c93ba27d1e5440/Workbooks/SharePointAndOneDrive.json#L104

**To Reproduce**
1. The workbook in your environment.
2. Click a time range with sufficient data.
3. Select "all" in Operations. 
4. Select the drop down for Users. You will only have "all" as an option for the users. 
5. Edit the workbook paste in the JSON line below under the parameter section for "users".
6. Repeat step 3, and on step 4 you can select from any user id.

**Expected behavior**
The expected behavior is to be able to filter by user ID even when "all" operations are selected. 

**Screenshots**
don't have any

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Edge
 - Version: ?

**Additional context**

Solution: 

I have tested the below and used the addition of ```where '{Operations:lable}'=='All'``` to get a populated user ID list even when the operations parameter is "all". 

KQL expanded:
```
OfficeActivity
| where OfficeWorkload in ('OneDrive', 'SharePoint')
| where '{Operations:lable}'=='All' or Operation in ({Operations})
| summarize Count = count() by UserId
| order by Count desc, UserId asc
| project Value = UserId, Label = strcat(UserId, ' - ', Count)
```
JSON line:
```
OfficeActivity\r\n| where OfficeWorkload in ('OneDrive', 'SharePoint')\r\n| where '{Operations:lable}'=='All' or Operation in ({Operations})\r\n| summarize Count = count() by UserId\r\n| order by Count desc, UserId asc\r\n| project Value = UserId, Label = strcat(UserId, ' - ', Count)
```

**Comment by benatsb** [comment]
Related, I do not know why throughout the workbook this is used "Operations:lable" instead of "Operations:label". All the queries have the "lable" typo. 

This workbook is otherwise un-editing or customized apart from the users parameter fix.

**Comment by samikroy** [comment]
> [benatsb](/benatsb)

@benatsb - Could you please try the above version.

And the possible reason is earlier workbook  has "Operations:**lable**" as a parameter but is updated as "Operations:**label**" from a product standpoint. 

However both the keywords works.

![image](https://user-images.githubusercontent.com/20562985/155879284-21d59c21-0cbd-4ce2-8b3f-41ea1ff6ca9e.png)
