### ISSUE TITLE
[Feature Request] Support hex encoded conversion to ASCII

### ISSUE THREAD

**Issue by azsec** [Azure/Azure-Sentinel#425]
**PROBLEM STATEMENT**

Linux audit log is fed to Log Analytics workspace following standard format. The PROCTILE field records full command-line of the command that was used to invoke the process (with syscall normally). This field is encoded in hexadeximal notation. 

Currently when doing analysis against this type of log, we normally need to convert hex to ASCII. There is not any built-in function to help analyst to convert from hex to ascii using Kusto Query Language.

**SOLUTION PROPOSAL**

There are the following options:
- Provide built-in function to support converting hex to ascii via KQL. A boilerplate code would be:
```
LinuxAuditLog_CL
| where RecordType == "PROCTITLE"
| extend decodedCmd == toascii(proctitle)
```
Function name would be `fromHex()` too.

- Provide a function in msticpy to help analyst as well as to group records by Audit ID.
```
# This command is used to extract set of events that match audit ID number 
and display decoded command line.
.\sectools\unhexlify.py --audit-id 123455
```
or 
```
# This command is used to find a keyword from encoded command line
.\sectools\unhexlify.py --search '/usr/bin/'
```
**WORKAROUND**

A workaround would be to build a utility to invoke **ausearch** with `--interpret` and feed logs to Log Analytics workspace. However this way would lead to a lot of efforts, and would be counter to built-in agent's function.

**Comment by ashwin-patil** [comment]
Thanks azsec for submitting request. 

For KQL - yes, there is no built-in support for hex to ascii as you mentioned. You can submit a request on uservoice for this feature on [Azure Sentinel Uservoice](https://feedback.azure.com/forums/920458-azure-sentinel). 

Alternatively, I found within msticpy, @ianhelle has already implemented it as part of auditextract module.

Check the example code in the Sample Notebook from Azure-Sentinel-Notebooks github-  
Example - Step-by-Step Linux-Windows-Office Investigation.ipynb - [nbviewer](https://nbviewer.jupyter.org/github/Azure/Azure-Sentinel-Notebooks/blob/master/Sample-Notebooks/Example%20-%20Step-by-Step%20Linux-Windows-Office%20Investigation.ipynb) .

Navigate to Cell - 61 where sample auditextract usage is given.  
ReadTheDocs - [msticpy.sectools.auditdextract](https://msticpy.readthedocs.io/en/stable/msticpy.sectools.html#module-msticpy.sectools.auditdextract)
```
# We still have some work to do using the auditdextract module from msticpy
# This will do
# - spliting the key=value string
# - the hex decoding of any encoded strings
# - type conversion for int fields
# - for SYSCALL/EXECVE rows we'll do some extract processing to identify the executable that ran
# and re-assemble the commandline arguments
# - extracting the real timestamp and replacing the original TimeGenerated columns (since this was
# just the log import time, not the event time, which is what we are after)
from msticpy.sectools.auditdextract import extract_events_to_df, get_event_subset
linux_events_all = extract_events_to_df(linux_events_df, verbose=True)
```
in the cell output you can see decoded command lines for Proctitle with command line.

**Comment by azsec** [comment]
Thank you @ashwin-patil . The auditextract does exactly what I need. That is awesome!

**Comment by shainw** [comment]
Closing as answered.

**Comment by johnmccash** [comment]
I have a better/simpler solution to this:

AuditD_CL |where proctitle_CF != ""|extend proctitle_decoded = url_decode(replace("[0-9a-fA-F]{2}","%\\0",proctitle_CF))

Enjoy!
     John

**Comment by johnmccash** [comment]
Actually, some Linux versions don't encode the PROCTITLE data. Also, the command arguments in hex-encoded PROCTITLE strings seem to be separated by nulls (%00) The following conversion is therefore superior:

AuditD_CL |where proctitle_CF != ""|extend proctitle_decoded = iif(proctitle_CF matches regex "^([0-9a-fA-F]{2})+$",url_decode(replace("%00","%20",replace("[0-9a-fA-F]{2}","%\\0",proctitle_CF))),proctitle_CF)
