### ISSUE TITLE
Watchlist Names (not Alias) do not accept spaces

### ISSUE THREAD

**Issue by ep3p** [Azure/Azure-Sentinel#4301]
**Describe the bug**
When creating a Watchlist, the Name of the Watchlist (not the Watchlist Alias) does not accept spaces anymore.

![image](https://user-images.githubusercontent.com/2527990/156346796-1cbd8661-55ef-4603-8b37-0c0835d02f89.png)

**To Reproduce**
1. Go to 'Watchlist'
2. Click on 'Add new'

**Expected behavior**
Is this change expected? Because you had some deployments in this Github where the created Watchlist Name has spaces.

![image](https://user-images.githubusercontent.com/2527990/156347161-f1f129d2-110c-4288-b603-0044cb44c5ca.png)

**Comment by teachjing** [comment]
I just confirmed that this is expected behavior. This is the new validation and spaces will not be allowed going forward. Underscores and hyphens will still be allowed.
