### ISSUE TITLE
Tenable.io Function App not ingesting Vulnerabilities

### ISSUE THREAD

**Issue by philfy20** [Azure/Azure-Sentinel#4322]
**Describe the bug**
The Tenable.io solution provides a function app that pulls Asset and Vulnerability data from Tenable.io and ingests them into a set log analytics workspace. Assets are ingested fine however no vulnerabilities are being ingested and are failing. The tenable.io environment I am connecting to has around 11,000 assets and around 60,000 open Vulnerabilities. Looking at the logs of the function app I am getting 413 error when the app trys to post the Vulnerabilities log analytics workspace. And also the 137 python error See below screen shots

**To Reproduce**
Deployed the Tenable.io solution from the conent hub. Then deploy the function app by following the instructions via the tenable.io data connector. Also looking at the reviews of the solution in Sentinel I am not the only one having this issue.

**Expected behavior**
Vulnerability data from Tenable.io is ingested into the set log analytics workspace. 

**Screenshots**
![image](https://user-images.githubusercontent.com/91515482/156674082-f6931d49-fdaf-4ec2-bc98-6a4568d87461.png)
![image](https://user-images.githubusercontent.com/91515482/156674183-2af1a071-d9e1-4b8d-a0c1-f111694e4de3.png)
![image](https://user-images.githubusercontent.com/91515482/156674243-64811a5e-a98d-4c26-a175-a2cbbb18cb58.png)
![image](https://user-images.githubusercontent.com/91515482/156674451-fae4f0f8-5bcd-4d03-a7a8-50310f699330.png)

**Additional context**

**Comment by ashishsyal** [comment]
We are looking into this

**Comment by philfy20** [comment]
Update tenable have update code and have a pull request pending https://github.com/Azure/Azure-Sentinel/pull/4654. Hopefully once approved we can test the new code and advise if issue is resovled

**Comment by philfy20** [comment]
Issue has been resolve with new code from Tenable https://github.com/Azure/Azure-Sentinel/pull/4654

**Comment by philfy20** [comment]
issue has been resolved with the following code from vendor https://github.com/Azure/Azure-Sentinel/pull/4654
