### ISSUE TITLE
TimeSeriesAnomaly-ProcessExecutions.yaml is constantly triggering Anomaly Alerts for the Microsoft Monitoring Agent

### ISSUE THREAD

**Issue by wingcomm** [Azure/Azure-Sentinel#4334]
**Describe the bug**
We're finding that this analytic in Sentinel is constantly triggering for the Microsoft Monitoring Agent.https://github.com/Azure/Azure-Sentinel/blob/master/Detections/SecurityEvent/TimeSeriesAnomaly-ProcessExecutions.yaml

The alerts logs are filled with so many noisy log entries for MMA, it renders the analytics practically unusable.

**To Reproduce**
Install Microsoft Azure Monitoring agent
Enable "Process execution frequency anomaly"
Review log entries associated with alerts.

**Examples of noisy logs**

"C:\Windows\system32\cmd.exe" /c "C:\Program Files\Microsoft Monitoring Agent\Agent\Health Service State\Monitoring Host Temporary Files 1377\19569\Main.cmd" (numbers change at random)

**Comment by ashwin-patil** [comment]
Queryfrequency Fix was deployed in PR #4336
