### ISSUE TITLE
Isolate-MDEMachine Bug

### ISSUE THREAD

**Issue by SimoneFrigerio** [Azure/Azure-Sentinel#4341]
The Playbook "Isolate-MDEMachine" has a bug
probably is changed the schema from MDATP Alert JSON

MdatpDeviceId is not available by default into host anymore, you ll find it under additional data

![immagine](https://user-images.githubusercontent.com/82639336/157240561-bc1b1848-7a80-452f-a49c-4b63ccad8e2f.png)

![immagine](https://user-images.githubusercontent.com/82639336/157243465-914cdb43-ab44-4399-9bac-2530f8bb44b3.png)

Could you please update all the Playbook that are using this MdatpDeviceId?
many thanks

**Comment by BenjiSec** [comment]
Hi @SimoneFrigerio - can you ping me so that we can troubleshoot? I just deployed both - incident trigger and alert trigger and both works with no issues.

**Comment by TimGjerlufsen** [comment]
It seems that the issue with the missing MdatpDeviceId has reappeared. Others that has same problem?
