### ISSUE TITLE
Netskope Data Connector does not work out of box with ARM template - incorrect powershell version

### ISSUE THREAD

**Issue by anthonysomerset** [Azure/Azure-Sentinel#4342]
**Describe the bug**
When deploying the Netskope Data Connector function via the linked arm template in azure sentinel it fails to run out of the box with errors such as:

```
WARNING: This version of Az.Accounts is only supported on Windows PowerShell 5.1 and PowerShell 7.0.6 or greater, open https://aka.ms/install-powershell to learn how to upgrade. For further information, go to https://aka.ms/azpslifecycle.
```

**To Reproduce**
1. Go to Azure Sentinel instance and Data Connectors page
2. Find the Netskope connector Click on 'Open Connector Page'
3. Scroll down to 'Option 1'
4. Click Deploy on Azure
5. go through the deployment steps, inserting correct credentials
6. wait - view application traces
7. see errors

**Expected behavior**
Data Connector should work with no further interaction

**Screenshots**

**Additional context**
Problem is fixed by editing function configuration to specify powershell core 7.0 as the power shell core version - it was showing as blank for me when i first loaded this page:

![image](https://user-images.githubusercontent.com/340584/157242071-90266968-86a9-4336-9dec-b48e29bac509.png)

I suspect the Arm template just needs updating to specify the correct version

**Comment by v-rucdu** [comment]
@anthonysomerset : Thanks for raising the issue. A fix for this has been checked-in to master (https://github.com/Azure/Azure-Sentinel/pull/4433), closing this issue. Please feel free to reopen in case you face any issues... Thanks!!
