### ISSUE TITLE
Documentation Bug: Netskope Connecter does not work with Rest API v2 and docs link broken

### ISSUE THREAD

**Issue by anthonysomerset** [Azure/Azure-Sentinel#4343]
**Describe the bug**
The documentation within Azure Sentinel connector page stats that the connector uses Netskope's v2 REST API, but the code only talks to  v1 REST API which is also deprecated on netskope side

This causes confusion as users go and configure V2 API keys and it fails to authenticate against the V1 API

Documentation should be updated to refer to the V1 API support to avoid confusion, the actual documentation link is also broken in this regard - its specific to a single customer of Netskope and not the generic docs pages:

V1 API - https://docs.netskope.com/en/rest-api-v1-overview.html
V2 API - https://docs.netskope.com/en/rest-api-v2-overview-312207.html

Relates to https://github.com/Azure/Azure-Sentinel/issues/3181

I understand it would be a feature request to update the connector to use the V2 API instead of V1 and am aware as per the issue this is already in the system for looking at but in the immediate term, documentation and links should be updated to refer to the correct API to avoid confusion/errors

**Comment by vmanojreddy** [comment]
We are closing this issue. The Netskope Connecter Rest API v2 doc url is resolved and deployed. Please feel free to reopen the issue with more details if the issue still persist... Thanks!!!
