### ISSUE TITLE
AzureActivity inconsistent schema?

### ISSUE THREAD

**Issue by ko-sharon** [Azure/Azure-Sentinel#4350]
**Describe the bug**
For KQL queries referencing AzureActivity, there seems to be inconsistency in the schema.

*To Reproduce**
1. Take the Hunting Query 'Anomalous Listing of Storage Keys' as an example: https://github.com/Azure/Azure-Sentinel/blob/master/Hunting%20Queries/AzureActivity/Anomalous_Listing_Of_Storage_Keys.yaml

2. If we just run the first 3 lines of the query:
```
AzureActivity
  | where OperationNameValue == "microsoft.storage/storageaccounts/listkeys/action"
  | where ActivityStatusValue == "Succeeded" 
```

3. If instead we run:
```
AzureActivity
  | where OperationNameValue =~ "microsoft.storage/storageaccounts/listkeys/action"
  | distinct ActivityStatusValue
```

4. You'll notice more entries appearing and also ActivityStatusValue includes "Succeeded" and also "Success"

**Expected behavior**
Unsure if this is the expected behaviour? It looks like the difference is in that OperationNameValue can exist in 2 forms:
microsoft.storage/storageaccounts/listkeys/action
MICROSOFT.STORAGE/STORAGEACCOUNTS/LISTKEYS/ACTION

And if it's in the all caps form, the ActivityStatusValue is different (ie. Success, not Succeeded). Are they duplicates?

**Screenshots**
![image](https://user-images.githubusercontent.com/57211088/157374296-dc685765-9243-4ef5-a9d8-f3bce9acecd8.png)

**Comment by sarah-yo** [comment]
Tracking in ICM
