### ISSUE TITLE
GitHub Enterprise Audit Log (Preview)

### ISSUE THREAD

**Issue by mastersoho** [Azure/Azure-Sentinel#4363]
We've recently deployed the GitHub Enterprise Audit Log (Preview) connector using the following link
https://azuremarketplace.microsoft.com/en-us/marketplace/apps/microsoftcorporation1622712991604.sentinel4github?tab=overview
We then set up a personal token key graning it admin:org permissions. The configuration connected fine and the status says "connected" but two hours later and we still have no logs received. Any ideas?

Thanks

**Comment by sarah-yo** [comment]
Hi @mastersoho are you still not getting logs?

**Comment by mastersoho** [comment]
Hi Sarah.
I recreated the PAT and now we are getting logs. However, the second time I added the following permissions;
admin:org + admin:org_hook
Either a) admin:org scope was not adequate or b) we just got lucky the second time around and admin:org_hook is not necessary 
Thanks
