### ISSUE TITLE
AWS S3 Microsoft Sentinel Connector - Consider create a CloudFormation and Stacksets

### ISSUE THREAD

**Issue by dneto82** [Azure/Azure-Sentinel#4398]
**Is your feature request related to a problem? Please describe.**
Make easier to security teams enroll accounts and extract value from you AWS Logs. Seems not feasible to require Ops or Devs teams to "run PowerShell" with a lot of options for each account.

**Describe the solution you'd like**
We hope a lot of customers have more than 1 AWS accounts. A common scenario also with Organization. 
Request to OpsTeams to run a pwsh with aws seems a little silly. You can consider use CloudFormation and Stackset for provision ARN with proper privileges and generate changes required to Sentinel always get proper information.

**Describe alternatives you've considered**
Benefit from automated way.

**Additional context**
N/A.

**Comment by sreedharande** [comment]
@dneto82 - We are in the process of adding CloudFormation Templates, Stay tuned
