### ISSUE TITLE
Error during deployment of Prompt-User Playbook

### ISSUE THREAD

**Issue by tijan2018** [Azure/Azure-Sentinel#4415]
**Describe the bug**
I am receiving the errors as indicated in the attached screenshots when deploying the Prompt User playbook in Azure. 
![Prompt_User_Playbook_Error_1](https://user-images.githubusercontent.com/45381747/158420606-e002a6b9-c109-4553-875c-7eccff38378c.png)
![Prompt_User_Playbook_Error_2](https://user-images.githubusercontent.com/45381747/158420610-c85bcf8a-df47-4cda-a303-9ea45213436a.png)
![Prompt_User_Playbook_Error_3](https://user-images.githubusercontent.com/45381747/158420616-c253e3d0-0d22-4e18-9826-4ebefc4f3dd8.png)
cise description of what the bug is.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by BenjiSec** [comment]
@tijan2018  - playbook is updated to support new MS Teams action. Please confirm if it's working so that we can close the issue.
