### ISSUE TITLE
Adding new field to sentinel record

### ISSUE THREAD

**Issue by secure0** [Azure/Azure-Sentinel#442]
Check [CONTRIBUTING guideline](https://github.com/fluent/fluentd/blob/master/CONTRIBUTING.md) first and here is the list to help us investigate the problem.

**Describe the bug**
I am trying to add new field to Fluentd record,with two filter sections for the same source section, but the new record doesn't seem to be added.

**To Reproduce**

**Expected behavior**

**Your Environment**

- Fluentd0.12.40
- NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"

- Kernel version: 3.10.0-1062.el7.x86_64
<source>
  type syslog
  port 25226
  bind 127.0.0.1
  protocol_type udp
  tag oms.syslog
</source>

<filter oms.syslog.**>
  type record_transformer
  <record>
    myownfield "ABCDE"
  </record>
</filter>

<filter oms.syslog.**>
  type filter_syslog
</filter>

No related errors.

**Comment by oshezaf** [comment]
Hi @secure0 : I assume that you are trying to modify FluentD as part of the Log Analytics agent with the goal of having additional fields in the Log Analytics workspace. You will not be able to add fields to the Syslog table in Log Analytics. You can use the Log Analytics agent to ingest into custom tables which will enable you to control the fields in the custom table created. See more info [here](https://docs.microsoft.com/bs-latn-ba/azure/azure-monitor/platform/data-sources-json).

**Comment by secure0** [comment]
> 
> 
> Hi @secure0 : I assume that you are trying to modify FluentD as part of the Log Analytics agent with the goal of having additional fields in the Log Analytics workspace. You will not be able to add fields to the Syslog table in Log Analytics. You can use the Log Analytics agent to ingest into custom tables which will enable you to control the fields in the custom table created. See more info [here](https://docs.microsoft.com/bs-latn-ba/azure/azure-monitor/platform/data-sources-json).

Hi @oshezaf , correct, that is what i want. Even if i manipulate the FluentD plugins responsible for processing syslog ? what is the reason of not being able to add fields to the Syslog table in Log Analytics ?

**Comment by oshezaf** [comment]
With Log Analytics native tables have a fixed schema. Only custom tables can have custom fields. One thing to keep in mind is that this is only physical fields. You can always have view functions that present a logical view of a table and includes additional fields: parsed, calculated or enriched from other sources.
