### ISSUE TITLE
CrowdStrike Solution - Data Replicator Connector no longer ingesting logs

### ISSUE THREAD

**Issue by cfbv** [Azure/Azure-Sentinel#4422]
The Crowdstrike Falcon Data Replicator connector within the Crowdstrike Falcon solution is no longer ingesting logs properly since recent changes. The function app logs do not show any errors but also no longer picks up any data from the S3 bucket. 

To temporarily resolve this connector issue, I configured the 'WEBSITE_RUN_FROM_PACKAGE' to use an older version of CrowdstrikeFalconAPISentinelConn.zip in this repository.

**Comment by xyzzykdj** [comment]
We are having the same issue...

**Comment by andreakano** [comment]
Same problem here

**Comment by ZLT-ops** [comment]
The bug is fixed when you change the package to:

https://github.com/Azure/Azure-Sentinel/blob/v-ntripathi/CrowdstrikeFalconICMFix349173681/Solutions/CrowdStrike%20Falcon%20Endpoint%20Protection/Data%20Connectors/CrowdstrikeReplicator/CrowdstrikeFalconAPISentinelConn.zip?raw=true

**Comment by NikTripathi** [comment]
Closing the issue as it has been confirmed that it got resolved. Having internal discussion to make the same changes public.
