### ISSUE TITLE
Sentinel Training Lab Solution - Module 1, Exercise 2- Ingestevents deployment; Conflict with runPowerShellInline

### ISSUE THREAD

**Issue by InfamousParrot** [Azure/Azure-Sentinel#4446]
When creating the workbook within Sentinel, I receive this error for the ingestEvents deployment
{
    "status": "failed",
    "error": {
        "code": "DeploymentScriptOperationFailed",
        "message": "The received access token is not valid: at least one of the claims 'puid' or 'altsecid' or 'oid' should be present. If you are accessing as application please make sure service principal is properly created in the tenant."
    }
}

This issue is occurring within a dev environment running the workbook as owner of subscription and resource group containing the log analytic workspace for Sentinel.
![Picture1_LI](https://user-images.githubusercontent.com/54108222/159083268-e3845fb1-ead3-462b-89a8-f459d7f9dbfc.jpg)

**Comment by javiersoriano** [comment]
Hi @InfamousParrot , I cannot reproduce the issue on my end. Could you try again in a different region?

Thanks

**Comment by lloydcarnie1** [comment]
I had the same issue and looks like spinning the solution up in East US fixed the issue.

**Comment by wupatric** [comment]
having same issue here, region "East US"
