### ISSUE TITLE
CLose-MCAS not able to link with automation

### ISSUE THREAD

**Issue by atech-soc** [Azure/Azure-Sentinel#4459]
**Describe the bug**
under azure sentinel > automation unable to link logic app "Close-Incident-MCAS" it doesn't populate in the list

**To Reproduce**
Deploy "Close-Incident-MCAS" logic App
go to sentinel
automation
create automation rule
put require condition
under action select run playbook
you won't find this logic App there

**Expected behavior**
logic App should list under run playbook option of automation rule

**Desktop (please complete the following information):**

 - Browser : Edge
 - Version 99.0.1150.39 (Official build) (64-bit)

**Comment by BenjiSec** [comment]
Hi @atech-soc - this playbook is using alert trigger. Automation rules are not supporting alert triggers yet. Automation rules are supporting only Incident trigger.
I would suggest use of Microsoft 365 Defender connector which supports bi-directional sync between MS Sentinel and Microsoft 365 Defender (including MCAS/MD for Cloud Apps).

**Comment by BenjiSec** [comment]
Hi,

Here it is - https://docs.microsoft.com/en-us/azure/sentinel/connect-microsoft-365-defender?tabs=MDE
