### ISSUE TITLE
ASIM Links for ASim Windows Event template Point to the wrong location

### ISSUE THREAD

**Issue by Cyb3rWard0g** [Azure/Azure-Sentinel#4471]
**Describe the bug**
ASIM parsers in this template give 404 error

https://github.com/Azure/Azure-Sentinel/blob/master/Parsers/ASim%20WindowsEvent/ARM/MicrosoftWindowsEventFullDeployment.json

For example, ASIM registry in that template: https://github.com/Azure/Azure-Sentinel/blob/master/Parsers/ASim%20WindowsEvent/ARM/MicrosoftWindowsEventFullDeployment.json#L21

Should point to https://github.com/Azure/Azure-Sentinel/blob/master/Parsers/ASimRegistryEvent/ARM/FullDeploymentRegistryEvent.json it looks like. 

I am not sure if that is the way to update the ASim WindowsEvent template. We use those parsers for project SimuLand.

**Comment by Cyb3rWard0g** [comment]
https://github.com/Azure/SimuLand/issues/28

**Comment by Cyb3rWard0g** [comment]
Bad one:
https://raw.githubusercontent.com/Azure/Azure-Sentinel/master/Parsers/ASimRegistry/ARM/vimRegistryEventMicrosoftWindowsEvent/vimRegistryEventMicrosoftWindowsEvent.json

Good one: 
https://raw.githubusercontent.com/Azure/Azure-Sentinel/master/Parsers/ASimRegistryEvent/ARM/vimRegistryEventMicrosoftWindowsEvent/vimRegistryEventMicrosoftWindowsEvent.json

**Comment by oshezaf** [comment]
Hopefully solved. Can you recheck @Cyb3rWard0g ?

**Comment by Cyb3rWard0g** [comment]
It works now :) Thank you @oshezaf !
