### ISSUE TITLE
Please add apiuser to Solutions/LastPass/Data Connectors/LastPassAPIConnector.json

### ISSUE THREAD

**Issue by ianssoftcom** [Azure/Azure-Sentinel#4484]
**Is your feature request related to a problem? Please describe.**
When viewing Event Reports, regular polling by Sentinel is not commented, and cannot be distinguished from potential malicious activity.

```
      "Data": "(initiated by API)"
      "Data": "(initiated by API)"
      "Data": "(initiated by API)"
```

**Describe the solution you'd like**
LastPass supports the `apiuser` declaration, comment the requests as Sentinel or something descriptive so that events can be distinguished from potential attacks using the LastPass API.

`{ "apiuser": "Sentinel" }`

**Comment by ThijsLecomte** [comment]
That's a good point @ianssoftcom , is this just an additional parameter which needs to be added?
Do you have a link to the documentation stating this by any chance?

**Comment by ianssoftcom** [comment]
Here is the curl command I used for testing
```
curl -s -H 'Content-Type: application/json' -d "{
\"cid\": \"99999999\",
\"provhash\": \"$(lpass show --password 'Business/lastpass hash')\",
\"apiuser\": \"Ian\",
\"cmd\": \"reporting\",
\"data\": {}
}" https://lastpass.com/enterpriseapi.php | jq -r
```
I found the option here:
https://admin.lastpass.com/advanced/enterpriseApi
