### ISSUE TITLE
[Feature request] Request for building the playbook (Microsoft Logic app to help to query the Akamai Netstorage SCP/SFTP for downloading file (trafficlog-13-01-12-3PM.txt) hourly

### ISSUE THREAD

**Issue by williamtwar** [Azure/Azure-Sentinel#4490]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I struggle to build the playbook for pulling the file (trafficlog-13-01-12-3PM.txt) from Akamai Netstorage SCP/SFTP

**Describe the solution you'd like**
I would like to have a template playbook o help to query the Akamai Netstorage SCP/SFTP for downloading files (trafficlog-13-01-12-3PM.txt) hourly

The following file as below
trafficlog-13-01-12-3PM.txt
trafficlog-13-01-12-4PM.txt
trafficlog-13-01-12-5PM.txt

**Describe alternatives you've considered**
Currently, there are no other ways

**Additional context**

Documentation
https://techdocs.akamai.com/netstorage/docs/use-secure-copy#secure-copy-scp-connection-options

**Comment by BenjiSec** [comment]
Hi @williamtwar - does Akamai Netstorage has API from where we can grab those traffic logs? If yes, then you need to use HTTP Logic App connector and collect data from that API per Akamai instructions. After you get the data, you'll need to send that data to Sentinel using Azure Log Analytics Data Collector connector (Send Data action in Logic App). 
If Akamai doesn't have an API, then you cannot use Logic App for it.

**Comment by williamtwar** [comment]
Hi,

Akamai Netstorage has its own HTTP API. It's totally different from REST API.

**Comment by williamtwar** [comment]
Would you mind advising whether there is an example playbook that uses the SCP/SFTP/FTP to pull the logs hourly?
If so, would you please provide the link for me to redesign the Azure logic app playbook to fit my needs?

**Comment by BenjiSec** [comment]
Hi, there is no playbook available currently for your use case in Microsoft Sentinel official repo.

If you create the same, you can submit PR with the template of the playbook for the wider community.
