### ISSUE TITLE
Add Licensing requirements/Dependencies

### ISSUE THREAD

**Issue by DeanGross** [Azure/Azure-Sentinel#4503]
**Is your feature request related to a problem? Please describe.**
I can't tell if playbooks will violate licenses or have dependencies on them. Specifically AAD P1 or P2. 

**Describe the solution you'd like**
The documentation should state the licensing requirements for the connectors/events used in a Playbook/logic app, i.e. will the Confirm Risky AAD User playbook work for users that don't have AAD P2? will it violate the license if it does work and the account doesn't have this license?   

**Describe alternatives you've considered**
Providing some information in the playbook description would eliminate this uncertainty.

**Additional context**
There may be other playbooks that have similar issues, but the ones that deal with risky users are the most obvious to me

**Comment by BenjiSec** [comment]
@DeanGross - Identity Protection is part of Azure AD Premium 2 and, if you are using this functionality, user should be licensed for it.
