### ISSUE TITLE
Two detections have SecurityEvent as data source but they actually use Event

### ISSUE THREAD

**Issue by javiersoriano** [Azure/Azure-Sentinel#4516]
These two rules:

https://github.com/Azure/Azure-Sentinel/blob/master/Detections/SecurityEvent/CredentialDumpingToolsFileArtifacts.yaml
https://github.com/Azure/Azure-Sentinel/blob/master/Detections/SecurityEvent/CredentialDumpingServiceInstallation.yaml

Have under requiredDataConnectors the SecurityEvent table, but they don't actually use that table, they use Event table.

Could we correct this?

Thanks

**Comment by aprakash13** [comment]
This is addressed under https://github.com/Azure/Azure-Sentinel/pull/4525 by Samik Roy. Closing this for now.
