### ISSUE TITLE
Virus Total IP Enrichment Playbook - 403 Forbidden Error

### ISSUE THREAD

**Issue by Gary-S-ingh** [Azure/Azure-Sentinel#4549]
The Playbook Status is "Failed" and getting stuck in “For each” – “Condition” – “True” – “Output” – “Status Code: 403” 

Sample Message Body:

{
  "StatusCode": "Forbidden",
  "ReasonPhrase": "Forbidden",
  "Content": "{\"error\":{\"code\":\"AuthorizationFailed\",\"message\":\"The client 'XXXXXX' with object id 'XXXXXX’ does not have authorization to perform action 'Microsoft.SecurityInsights/incidents/comments/write' over scope '/subscriptions/XXXXX/resourceGroups/brev-sandbox-sentinel/providers/Microsoft.OperationalInsights/workspaces/brev-sandbox-loganalytics/providers/Microsoft.SecurityInsights/incidents/XXXXX/comments/XXXX' or the scope is invalid. If access was recently granted, please refresh your credentials.\"}}",
  "Headers": {
    "Pragma": [
      "no-cache"
    ],
    "x-ms-failure-cause": [
      "gateway"
    ],
    "x-ms-request-id": [
      "XXXX"
    ],
    "x-ms-correlation-request-id": [
      "XXXX"
    ],
    "x-ms-routing-request-id": [
      "XXXX
    ],
    "Strict-Transport-Security": [
      "max-age=31536000; includeSubDomains"
    ],
    "X-Content-Type-Options": [
      "nosniff"
    ],
    "Connection": [
      "close"
    ],
    "Cache-Control": [
      "no-cache"
    ],
    "Date": [
      "Thu, 31 Mar 2022 21:49:20 GMT"
    ],
    "Content-Length": [
      "655"
    ],
    "Content-Type": [
      "application/json; charset=utf-8"
    ],
    "Expires": [
      "-1"
    ]
  },
  "debugInfo": "clientRequestId: XXXXX"
}

Configured a Custom Role with the specific write permissions and assigned at the Sentinel Resource Group level (Scoped to this Logic App only) but still having issues. 

The Connector we are using under “Condition – True – Add comment to incident (V3)” is a service principal account. Considering the least privileged principle how can we fix the error and where should the custom role to be assigned? Thanks

**Comment by BenjiSec** [comment]
Hi @Gary-S-ingh , did you try to assign Microsoft Sentinel Responder role? Responder role can write a comment in Sentinel. We would suggest using system assigned Managed Identity so that only that specific playbook has a permission.

**Comment by Gary-S-ingh** [comment]
Hello, @BenjiSec Good day. Considering the least privilege principle I created a custom role with the specific permission “Microsoft.SecurityInsights/incidents/comments – Write: Create Incident Comments” scoped at RG level and then assigned to the service account used in the Logic App Connector and that fixed the issue yesterday. 
Is it best practice to use system assigned role i.e.Microsoft Sentinel Responder role instead of the custom role I’ve created? I can try assigning the default Responder Role to that Service Account and see if that works
Many thanks

**Comment by BenjiSec** [comment]
Hi @Gary-S-ingh - it is always best to use least privilege if possible. From existing roles, Microsoft Sentinel Responder has least privilege to perform the action and that is why I had suggested it. If you want to do it more granular and create custom roles that will do only that specific task, you can do it. It will be just a bit more of managing from your side, since you'll have more custom roles.

**Comment by Jim1Ud** [comment]
> Hi @Gary-S-ingh , did you try to assign Microsoft Sentinel Responder role? Responder role can write a comment in Sentinel. We would suggest using system assigned Managed Identity so that only that specific playbook has a permission.

Hi Gary, did you have to assign the role to the Resource Group where the App lives?
