### ISSUE TITLE
Unisolate-MDE-Machine playbook OOB deployment error

### ISSUE THREAD

**Issue by mgijo** [Azure/Azure-Sentinel#4556]
While trying to deploy the **Unisolate-MDE-Machine** playbook out-of-the-box from Microsoft Sentinel - the name of the playbook is set to "**Isolate-MDEMachine**" , where instead it should be"**Unisolate-MDEMachine**" Also, if we already have "**Isolate-MDEMachine**" playbook deployed this causes the wizard to prompt us with an error such as "_name of the playbook already exists..._"

![image](https://user-images.githubusercontent.com/83291280/161340840-ef45ad1b-d09e-4a30-b0ce-078c5bb1523f.png)

Could you review and change the name of the playbook during initial deployment from "**Isolate-MDEMachine**" to "**Unisolate-MDEMachine**" ?

Thanks!

**Comment by sreedharande** [comment]
fixed #4587
