### ISSUE TITLE
Error - Microsoft Threat Protection - API Dashboard.pbit 

### ISSUE THREAD

**Issue by askvpb** [Azure/Azure-Sentinel#4558]
[](url)**Describe the bug**
[Microsoft Threat Protection - API Dashboard.pbit](https://github.com/Azure/Azure-Sentinel/blob/master/Tools/M365-PowerBi%20Dashboard/Microsoft%20Threat%20Protection%20-%20API%20Dashboard.pbit)
I'm having issues connecting the provided powerbi template to my tenant. I'm receiving error on the data refresh page as shown in the screenshot. 

"Software
Column 'name' in Table 'Software' contains a duplicate value 'Microsoft_.net_sdk_5.0.212_(x64)' and this is not allowed for columns on the one side of a many-to-one relationship or for columns that are used as the primary key of a [table.]

Can some help me?
![Screenshot 2022-04-04 132629](https://user-images.githubusercontent.com/86829647/161459484-6e9387a1-9c7a-4d5d-89b7-59030069f04e.png)

**Comment by sarah-yo** [comment]
Hello @askvpb, this would be better raised as a support issue for PowerBi rather than in the Sentinel Github, thanks!
