### ISSUE TITLE
UserSearchingForVIPUserActivity unable to detect LAQuery logs that do not have AADEmail

### ISSUE THREAD

**Issue by TheCat1989** [Azure/Azure-Sentinel#4575]
Hi community folks

we have encountered an issue that UserSearchingForVIPUserActivity analytic rules are not able to detect LAQuery logs that do not have AADEmail.

The AADEmail are just an attribute that will be recorded for LAQuery logs. however, in the following cases, the AADEmail is not presented. 

1. the query is called from API, 
2. some query with 401 status code 
3. some query queried by the workbook 

would it be better if we monitor the AAD object ID instead to have a better coverage?

![image](https://user-images.githubusercontent.com/35518480/161664645-dde99211-af2b-473a-99cb-fec0dfc324cc.png)

**Comment by v-dvedak** [comment]
Hi @TheCat1989, thank you for flagging this. Apologies for the delayed response. If you still need assistance, please reply here within 5 business days.

**Comment by v-dvedak** [comment]
Since we have not received a response in the last 5 days, we are closing your issue #<4575> as per our standard operating procedures. If you still need support for this issue, feel free to re-open at any time. Thank you for your co-operation.
