### ISSUE TITLE
Fortigate ip blocking Playbook

### ISSUE THREAD

**Issue by raj009970** [Azure/Azure-Sentinel#4598]
**Is your feature request related to a problem? Please describe.**

I want to build a playbook that will automatically block an ip address in the FortiGate firewall. i am using the below link. 
https://github.com/Azure/Azure-Sentinel/tree/master/Playbooks/Fortinet-FortiGate

Question: -So my question is, what are the primary criteria to build connectivity between Microsoft sentinel and FortiGate. and how we can test that we have connectivity between sentinel and FortiGate.
how I am establishing the connectivity: -
I have asked my FortiGate Admin to Create an API user and an API key. user has admin rights and with the least privilege.
and i have asked them to put the below ip address in trust list that connector will use to communicate with the fortigate firewall
40.71.249.139, 40.71.249.205, 40.114.40.132, 40.71.11.80/28, 40.71.15.160/27, 52.188.157.160, 20.88.153.176/28, 20.88.153.192/27, 52.151.221.184, 52.151.221.119
I have also asked to create an address object too. 

when i go to the function and go to monitor then it is showing success count is zero

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by BenjiSec** [comment]
Hi @raj009970 - we are using API to make connection. To test connection, please try to execute any of the playbooks that we already have created. First you need to deploy Fortinet FortiGate Logic App connector and then to deploy the playbook. Did you tried any of the playbooks that come in Fortinet FortiGate solution in Content Hub?

**Comment by sarah-yo** [comment]
No response, please reopen if further assistance is required.

**Comment by raj009970** [comment]
Thanks for your reply.
I have created a api key and a user in fortigate firewall. How I can verify that connectivity has been established between azure sentinel and fortigate firewall. Basically I want this playbook to block an ip address automatically. So how I can bind this playbook in rule.

**Comment by BenjiSec** [comment]
Hi, you can try any of the playbooks available in the Content Hub solution for Fortinet FortiGate

![image](https://user-images.githubusercontent.com/61513156/166493037-bee5b169-4313-4ece-aa32-d45951f37a8c.png)

**Comment by raj009970** [comment]
hi BenjiSec

Thank you for your reply. 

 could someone please let me know how we can test the API is working or not? actually, i am using below information.

Rest API ADMIN- A user created in Fortigate firewall and API key.
Fortinet service end point i am using https://x.x.x.x:444/api OR should i use only https://x.x.x.x:444/ OR http://x.x.x.x:444/api/v2/cmdb/firewall/address?access_token=xxxxxxxxxxxxxxxxxxxxxxxx.
i need to know what exact configuration we have to do for function app.
do we have to open any port in firewall to run this playbook.
we have three playbook in Github. i want only IP blocking playbook. so do i have to bind only ip blocking playbook in log analytic rule?
is there any way to test the connectivity between firewall and logic app. if we have,, how we can verify that connectivity has been established. now we just need to configure the playbook.
if there is any other prerequisites then please let me know.
