### ISSUE TITLE
Azure Sentinel Oracle Cloud Infra. Data Connector errors

### ISSUE THREAD

**Issue by happy-jo** [Azure/Azure-Sentinel#4603]
**Issue description:**
After deploying the OCI solution and the associated Function App, we observed OCI API errors relating to "ToManyRequest". We are unsure of why this is or how to resolve this issue. Should the Function code be modified with a sleep interval?
We have posted an image of the error below.

**Link to solution:** https://github.com/Azure/Azure-Sentinel/tree/master/Solutions/OCILogs/Data%20Connectors

**Image of issue:**
![OCI issue](https://user-images.githubusercontent.com/16526141/162492028-d7525c11-48a6-4fb8-8c09-a0269786198d.png)

**Comment by happy-jo** [comment]
@v-atulyadav , @ashwin-patil 

There seems to be two issues with this solutions.

1. If there are multiple Partitions assigned to the Consumer Group and one of the cursors outside of the retention period, this will lead to an error. This seems to be address in the following link:  [Troubleshooting Streams](https://docs.oracle.com/en-us/iaas/Content/Streaming/Reference/troubleshootingstreaming.htm#:~:text=Consumers%20receive%20a%20%22The%20cursor,message%20and%20a%20400%20error&text=This%20error%20means%20that%20the,fallen%20behind%20the%20trim%20horizon.)
2. In some instances, there can be a lot of data returned (e.g. if netflow logs are being sent to the stream) which could lead to the Log Analytics POST payload to exceed the max allowed. You should consider a payload size calculator and split the payload up into smaller, more manageable chunks.

**Comment by NikTripathi** [comment]
Hi @happy-jo We have modified the function app and tested it at our end. It is executing fine.
Please use below URL to deploy the azure function and let us know the output. During deployment please select partition cursor in the cursor type.
Azure Deploy :- https://portal.azure.com/#create/Microsoft.Template/uri/https%3A%2F%2Fraw.githubusercontent.com%2FAzure%2FAzure-Sentinel%2Fv-ntripathi%2FOCIColumnLimitFixForIcM352779411%2FSolutions%2FOracle%2520Cloud%2520Infrastructure%2FData%2520Connectors%2Fazuredeploy_OCI_logs_API_FunctionApp.json
Thanks.

**Comment by v-amolpatil** [comment]
Since we have not received a response in the last 5 days, we are closing your issue #4603 as per our standard operating procedures. If you still need support for this issue, feel free to re-open at any time. Thank you for your co-operation.
