### ISSUE TITLE
Preview images missing from workbook template

### ISSUE THREAD

**Issue by mariavaladas** [Azure/Azure-Sentinel#4633]
**Describe the bug**

**To Reproduce**
1. Go to Microsoft Sentinel
2. Workbooks
3. Templates
4. Find Log Sources & Analytics rules coverage

**Expected behavior**
There should be a preview image, but instead there is text

**Screenshots**
![image](https://user-images.githubusercontent.com/69897891/163186061-2f65541f-cd6b-4d1c-8ea7-f98cc7976375.png)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Edge

**Additional context**
The screenshots are uploaded to https://github.com/Azure/Azure-Sentinel/tree/master/Workbooks/Images/Preview as expected

**Comment by elforb** [comment]
Hi @mariavaladas, thank you for raising this issue.

The problem appears to be arising from the files containing a special character, `&` in the name.

Will be applying a fix for this shortly, and deployment will occur in the weekly workbook sync.
