### ISSUE TITLE
Restrict-MDEIPAddress

### ISSUE THREAD

**Issue by poojithanagesh** [Azure/Azure-Sentinel#4638]
Trying to run this playbook on an incident received 10-12 days back
1)	We see an error as follows while trying to run this playbook on an incident received a couple of weeks ago 
        It says ‘TimeGenerated’ parameter is not available.

![Playbook error](https://user-images.githubusercontent.com/103599447/163267968-30cdd79f-b259-44f1-8147-f4a547645c8a.PNG)

2)	We see a few incidents from Defender for Cloud saying, ‘Network communication with malicious IP’ and the entities lists 2 IP Addresses - for source IP & Destination IP
If we have this playbook run on these incidents, I guess it would block both the source & destination IP address here, which would not meet the requirement since we do not want to block the source IP address.
And since the incidents are from Defender for Cloud, we are not able to customize the entities listed here.

![Playbook_error](https://user-images.githubusercontent.com/103599447/163268183-4ffd4277-7744-4532-9c7d-0658a75408c0.PNG)

Thanks in advance for your inputs !

**Comment by BenjiSec** [comment]
Hi TimeGenerated is available in alert trigger but not in incident trigger. I'll replace it to use "createdTimeUtc". Update will be ready in the next 24 hours in GitHub. In Playbook Template tab it will be available in couple of days.
