### ISSUE TITLE
TimeSeriesKeyvaultAccessAnomaly.yaml not showing results

### ISSUE THREAD

**Issue by poojithanagesh** [Azure/Azure-Sentinel#4651]
Trying to run this KQL and see no results returned, but while using the previous query we see results returned with HourlyCount =1.
There is a keyvault with HourlyCount =1, and check being made with every hour frequency.

We commented '//let baselinethreshold = 5'; and also tried 'let baselinethreshold = 0' so that we could see results for resources with HourlyCount =1. But they are not yielding any results.

Attached the previous TimeSeriesKeyvaultAccessAnomaly query 
[OldTimeSeriesKeyvaultAccessAnomalyQuery.txt](https://github.com/Azure/Azure-Sentinel/files/8492229/OldTimeSeriesKeyvaultAccessAnomalyQuery.txt)

**Comment by v-amolpatil** [comment]
Hi @poojithanagesh, if you still need assistance, please reply here within 5 business days.

**Comment by v-amolpatil** [comment]
Gentle Reminder: We are awaiting for your response on this issue. If you still need to keep this issue active please respond within next 2 days. If we don't receive response by 21 Feb 2023, we will close this issue.

**Comment by v-amolpatil** [comment]
Since we have not received a response in the last 5 days, we are closing your issue #4651 as per our standard operating procedures. If you still need support for this issue, feel free to re-open at any time. Thank you for your co-operation.
