### ISSUE TITLE
Plans for Python 3.7+ support for BOX connector

### ISSUE THREAD

**Issue by dcbrown16** [Azure/Azure-Sentinel#4672]
We have a customer inquiry through CSS about the BOX connector.
According to the info here, Python 3.6 is required.
"Choose Python 3.6 (note that other versions of python are not supported for this function)"
https://github.com/Azure/Azure-Sentinel/blob/master/Solutions/Box/Data%20Connectors/Box_API_FunctionApp.json
Support for 3.6 ended in December 2021. Do you plan to support higher versions of Python with this connector soon?
https://endoflife.date/python

You can contact me internally at v-dibr if more info is needed.

**Comment by sarah-yo** [comment]
Please raise through internal channels
