### ISSUE TITLE
Custom details visible when clicked on the incident

### ISSUE THREAD

**Issue by shikhin-metron** [Azure/Azure-Sentinel#4705]
If the custom details are defined in analytic rules, they are visible now on incident, below the comments without clicking on `View full details` button. Is this a new UI feature? Can we disable it?

To reproduce: 
    1. Have some custom details in analytic rule
                       2. Create an incident using analytic rule
                       3. Click on the incident
                       4. All custom details will be visible below the comments section.(As shown in the screenshot below)

![Screenshot from 2022-04-25 17-35-39](https://user-images.githubusercontent.com/88835344/165085928-106f07c4-e39d-4bc5-b14f-a686e2206ca3.png)

**Comment by tatecksi** [comment]
@shikhin-metron , this is a new capability to provide better visibility for the details mapped in the analytic rules. With this addition, users will no longer need to go into the full incident view in order to find custom details.

Note: Closing this for now as it's not a product issue.

**Comment by shikhin-metron** [comment]
> @shikhin-metron , this is a new capability to provide better visibility for the details mapped in the analytic rules. With this addition, users will no longer need to go into the full incident view in order to find custom details.
> 
> Note: Closing this for now as it's not a product issue.

alright thanks. Was not sure if it was a new feature since could not find it anywhere on the microsoft documents on internet.
