### ISSUE TITLE
dataConnectorValidator.ts missing AzureDevOpsAuditing datatype

### ISSUE THREAD

**Issue by azurekid** [Azure/Azure-Sentinel#4731]
**Describe the bug**
An error occurs on the pull request because Native Microsoft tables are not understood by the script.

**To Reproduce**
See links: 
[Pull Request](https://github.com/Azure/Azure-Sentinel/pull/4729/checks?check_run_id=6193248986)
[Pipeline error](https://dev.azure.com/azure/Azure-Sentinel/_build/results?buildId=40413&view=logs&j=a23680af-8687-50ef-83c8-8f4f16dc3bd5&t=483ed120-0434-59e0-b202-e39922d1f55a)

**Expected behavior**
Default table, ehich is not a custom table in Log Analytics should be accepted.

**Screenshots**
![image](https://user-images.githubusercontent.com/40334679/165519511-c8ad0512-5bde-46ee-854b-2d1243abb502.png)
![image](https://user-images.githubusercontent.com/40334679/165519809-dc00c78f-ce81-421c-96c9-5cd2f8cbde12.png)
![image](https://user-images.githubusercontent.com/40334679/165519602-2880acd8-9c36-42c9-acd1-07a089cff075.png)

**Comment by azurekid** [comment]
I've created a [Pull Request](https://github.com/Azure/Azure-Sentinel/pull/4738) for this issue with ID: #4738

**Comment by ashishsyal** [comment]
We are looking into this.

**Comment by v-dvedak** [comment]
Closing the issue since PR for this (https://github.com/Azure/Azure-Sentinel/pull/4738) is merged
