### ISSUE TITLE
Setting up a new custom connector for security solution

### ISSUE THREAD

**Issue by utsavpatel51** [Azure/Azure-Sentinel#474]
I am developing a new connector on top of a built-in connector(Common Event Format(CEF)) just like Checkpoint,CISCO ASA, for which a security solution is yet to develop.I am not getting proper guidelines/documentation on how to add setup/add a new vendor (as a security solution) to configure with my custom connector(in-built CEF connector in my case).We can create workbook and PR it but if we want to create new data connector for new security solution which has CEF format data how can we create data connector for that?

**Comment by shainw** [comment]
@utsavpatel51 - Does this help you - https://techcommunity.microsoft.com/t5/azure-sentinel/azure-sentinel-creating-custom-connectors/ba-p/864060

**Comment by utsavpatel51** [comment]
@shainw - currently azure sentinel have 33 data connector
![image](https://user-images.githubusercontent.com/26016485/74417226-5f44cb80-4e6c-11ea-8545-ddbe3bcee05a.png)
how can I add my own security vendor connector?
I have created logic app connector but how can i publish it to azure so everyone can use it?

**Comment by oshezaf** [comment]
Hi @utsavpatel51 : at this point to be included in the connector gallery, you will have to work with our technical partnership team. Contact me privately so I can put you in contact with them.

**Comment by utsavpatel51** [comment]
Are you taking about Contributor License Agreement (CLA) or another thing?

**Comment by shainw** [comment]
@utsavpatel51 - were you able to connect up with Ofer?

**Comment by oshezaf** [comment]
@utsavpatel51 : I am not referring to the CLA. The technical partnership team would be able to guide you as to the requirements for inclusion.

**Comment by utsavpatel51** [comment]
> Hi @utsavpatel51 : at this point to be included in the connector gallery, you will have to work with our technical partnership team. Contact me privately so I can put you in contact with them.

Can you share your contact details please or if you can connect me directly to the technical partnership team, anything would be a great help!

**Comment by oshezaf** [comment]
> Hi @oshezaf : Can you share your contact details please or if you can connect me directly to the technical partnership team, anything would be a great help!

Send me an e-mail to ofer dot shezaf at microsoft dot com

**Comment by dicolanl** [comment]
@oshezaf  can we close this since it was taken offline?

**Comment by shainw** [comment]
I say so, closing for now and we can re-open if needed. :)

**Comment by shikhin-metron** [comment]
Hi, I also want to add my own connector in the connectors gallery. My question is, is there any way we can test the solution, how it would work in the gallery before actually getting it into connector gallery? I am using log analytics api with azure functions.

**Comment by shikhin-metron** [comment]
> Hi, I also want to add my own connector in the connectors gallery. My question is, is there any way we can test the solution by connecting, how it would work in the gallery before actually getting it into connector gallery? I am using log analytics api with azure functions.

@oshezaf @shainw can you guys help me with this?

**Comment by oshezaf** [comment]
We are in private preview for such a feature. Are you a member of the Azure Security private preview ring?
