### ISSUE TITLE
MDO Alert Policy not mapping Entities

### ISSUE THREAD

**Issue by Lodewyk-Git** [Azure/Azure-Sentinel#4781]
**Describe the bug**
One of our medium sized clients have been receiving Unusual external user file activity alerts. These have not been mapping any entities in either M365 Defender or Sentinel

**Expected behavior**
Entities to be mapped

**Screenshots**
![image](https://user-images.githubusercontent.com/36856692/166639762-df64da68-beb4-4452-b7b7-24d84caeb468.png)

**Additional context**
This same Incident has been created like this over 200 times a day. The raw data is associated correctly in M365 D, but that's where it ends. There's also no toggle for this policy other than the daily limit.

![image](https://user-images.githubusercontent.com/36856692/166640004-e0b9cc60-1c10-42b0-801e-467ccc7743fe.png)
![image](https://user-images.githubusercontent.com/36856692/166640020-a49c3dae-a6e7-46b0-9233-711de6ce9591.png)

**Comment by sarah-yo** [comment]
Hi @Lodewyk-Git 

Looks like the entities are not being passed through from MDO - can you please raise this issue with the MDO side of the house so they can look at what's going on? Thanks!
