### ISSUE TITLE
Unconsidered case in Authentication Methods Changed for Privileged Account detection

### ISSUE THREAD

**Issue by ep3p** [Azure/Azure-Sentinel#4786]
**Is your feature request related to a problem? Please describe.**
Detection [Authentication Methods Changed for Privileged Account](https://github.com/Azure/Azure-Sentinel/blob/master/Detections/MultipleDataSources/AuthenticationMethodsChangedforPrivilegedAccount.yaml) was recently  merged from different branches.

On 12th April this PR was merged (https://github.com/Azure/Azure-Sentinel/pull/4294).

On 13th April this PR was merged (https://github.com/Azure/Azure-Sentinel/pull/4569).

I don't have any objection about these changes, those branches come from different needs, and https://github.com/Azure/Azure-Sentinel/pull/4294 was prefered to be completely substituted by https://github.com/Azure/Azure-Sentinel/pull/4569.

I just want to point https://github.com/Azure/Azure-Sentinel/pull/4569 does not consider a special case:

There are some tenants where a telephone number is enough to configure the MFA of an account. When this MFA is configured, in AuditLogs table appears an event "Update user" where one of the modified properties is "StrongAuthenticationMethod", **AND there isn't any other event in AuditLogs regarding the security info of the account**, like the ones contemplated by https://github.com/Azure/Azure-Sentinel/pull/4569, thus effectively https://github.com/Azure/Azure-Sentinel/pull/4569 would not detect that change, that special case.

I prefer not to open another PR or mess with the most recent commit again. I just think some Microsoft customers might complain again in the future, just wanted to warn.

**Describe the solution you'd like**
Maybe this is not a problem about the detection, but the logging of AuditLogs. Maybe, for this special case, a "security info" event should be generated along the "Update user" event.

Last time I checked **every "security info" event is accompanied by a "Update user" event with "StrongAuthentication\*" field**. But **not every "Update user" event with "StrongAuthenticationMethod" field is accompanied by a "security info" event**. I checked this last March, maybe something has changed and it does not occur anymore. This was the reason for https://github.com/Azure/Azure-Sentinel/pull/4294 .

If you want me to append a concrete example of this event with info about the StrongAuthenticationMethod change, let me know.

Changes in MethodType 5 only generate "Update user" events.
![image](https://user-images.githubusercontent.com/2527990/166829997-6b5ff7cf-84bd-440a-8ad9-4b728154a523.png)

**Comment by v-dvedak** [comment]
Hi @ep3p, thank you for flagging this. Apologies for the delayed response. If you still need assistance, please reply here within 5 business days.

**Comment by v-dvedak** [comment]
Thanks @ep3p, closing the issue. If you still need support for this issue, feel free to re-open at any time. Thank you for your co-operation.
