### ISSUE TITLE
Missing users in IdentityInfo table compare to AzureAD

### ISSUE THREAD

**Issue by JiTmun** [Azure/Azure-Sentinel#4812]
**Describe the bug**
According to the [documentation](https://docs.microsoft.com/en-us/azure/azure-monitor/reference/tables/identityinfo) and [IdentityInfo release blog post](https://techcommunity.microsoft.com/t5/microsoft-sentinel-blog/what-s-new-identityinfo-table-is-now-in-public-preview/ba-p/2571037)
Identityinfo table is populated by Azure Sentinel UEBA with all the users identities information from the AzureAD
That's not what we observe in practice.

We had a user who launched a powershell script on a computer with his own account from its own user directory, but we didn't had any entry in the IdentityInfo table for this user during the past week. When we check in the AzureAD, at least this account has some recent SignIn, and exist since a year.
This is even general, as we know that to get info on a user we need to get data from IdentityInfo at least on  the past 3 days to be sure that this user will be in the query results targerting IdentityInfo Table.

**To Reproduce**
No steps identified, is general to Sentinel

**Expected behavior**
IdentityInfo should have at least an entry for every user in the UserAD, as this in the ground truth for users

**Comment by Lodewyk-Git** [comment]
Hey @JiTmun, did you see the user sign-in in any of the Azure Active Directory Data Types? (SignInLogs, AuditLogs, NonInteractiveSignInLogs etc.)
