### ISSUE TITLE
Azure FrontDoor Premium is not recognized

### ISSUE THREAD

**Issue by Jeremyp87** [Azure/Azure-Sentinel#4825]
Resource = AZUREFRONTDOOR with FD Premium, none of the queries work with Azure FrontDoor Premium deployment.

**Comment by sarah-yo** [comment]
Hi @Jeremyp87 

Please can you be more specific about which queries aren't working and provide some screenshots of the issue? Thanks!

**Comment by Jeremyp87** [comment]
Hi Sarah,

The Sentinel Workbooks for WAF seem incomplatible with Azure Frontdoor Premium as it uses different Collum names. See example below, there is no "ResourceType == "FRONTDOORS", the Category doesn't match up either. This issue is for all the 4 WAF Sentinel workbooks and for the Analytic queries as well.

FrontDoor Log:
![image](https://user-images.githubusercontent.com/104898983/167768620-7e444e3b-51e7-43ef-b653-f013d42a1ae8.png)


Query:
let FakeData = (datatable (
    Message: string,
    ruleName_s: string,
    clientIp_s: string,
    clientIP_s: string,
    action_s: string,
    transactionId_s: string,
    trackingReference_s: string
) [
    "", "", "", "", "", "", ""
]);
FakeData
| union AzureDiagnostics
| where (ResourceType == "APPLICATIONGATEWAYS" or ResourceType == "FRONTDOORS" or ResourceType == "CDNWEBAPPLICATIONFIREWALLPOLICIES")
    and ("{WAFType:label}" == "All" or (ResourceType == "APPLICATIONGATEWAYS" and "{WAFType:label}" contains "application gateway") or (ResourceType == "FRONTDOORS" and "{WAFType:label}" contains "azure front door") or (ResourceType == "CDNWEBAPPLICATIONFIREWALLPOLICIES" and "{WAFType:label}" contains "cdn"))
    and ("{WAF:label}" == "All" or Resource in ({WAF}))
| where Category == "FrontdoorWebApplicationFirewallLog"
    or OperationName == "ApplicationGatewayFirewall"
    or Category == "WebApplicationFirewallLogs"
| extend Action = iif(action_s == "Blocked", Action = "Block", action_s)
| extend Action = iif(Action == "Detected", Action = "Log", Action)
| where '*' == Action or '*' == "*"
| where '*' == requestUri_s or '*' == "*"
| extend Rule = strcat(ruleName_s, Message), ClientIP = strcat(clientIp_s, clientIP_s)
| where '*' == Rule or '*' == "*"
| summarize count() by Rule, bin(TimeGenerated, 1h)

Thanks,
Regards,
Jeremy

**Comment by tobystic** [comment]
Please close this issue. This has been updated in the workbooks with resourcetype : PROFILE
