### ISSUE TITLE
Playbooks/Send-basic-email deployment with DevOps Repo

### ISSUE THREAD

**Issue by Jeremyp87** [Azure/Azure-Sentinel#4826]
It is unclear to me with the provided documentation how to deploy a Playbook using Microsoft Sentinel | Repositories (Preview). Analytics rules work fine, but Playbooks are not exportable..

**Comment by BenjiSec** [comment]
To create template that you can use in Repositories, you can utilize Playbook ARM Template Generator - https://github.com/Azure/Azure-Sentinel/tree/master/Tools/Playbook-ARM-Template-Generator

More about the tool - https://techcommunity.microsoft.com/t5/microsoft-sentinel-blog/export-microsoft-sentinel-playbooks-or-azure-logic-apps-with/ba-p/3275898

**Comment by Jeremyp87** [comment]
I exported the template but after adding it to my repo, it doesn't seem to be deployed while analytic rules work fine..

**Comment by Jeremyp87** [comment]
That's working great! Thanks!
