### ISSUE TITLE
The workbook "ForcepointNGFWAdvanced.json" is not showing as a template in Sentinel workbooks

### ISSUE THREAD

**Issue by RaGerges** [Azure/Azure-Sentinel#4828]
**Describe the bug**
The workbook "ForcepointNGFWAdvanced.json" is not showing as a template in Sentinel Workbooks, after 20 days of being approved.

**Expected behavior**
The workbook "ForcepointNGFWAdvanced.json" should show up in sentinel workbooks after 2 weeks (14 days).

**Comment by alexkarabas** [comment]
This has been pushed to Production, apologies for the delay
