### ISSUE TITLE
Restrict-MDEDomain playbook readme.md file is missing

### ISSUE THREAD

**Issue by chomiy67** [Azure/Azure-Sentinel#4875]
**Describe the bug**
[Azure-Sentinel](https://github.com/Azure/Azure-Sentinel)/[Playbooks](https://github.com/Azure/Azure-Sentinel/tree/master/Playbooks)/Restrict-MDEDomain playbook readme.md file is missing

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by BenjiSec** [comment]
Hi, it is updated. As soon as PR is approved, it will be updated in the repo.
PR link - https://github.com/Azure/Azure-Sentinel/pull/4921

**Comment by sarah-yo** [comment]
Fixed
