### ISSUE TITLE
ubiquiti.conf "[warn]: parameter 'delimiter' in <source></source> is not used."

### ISSUE THREAD

**Issue by mvaneijken** [Azure/Azure-Sentinel#4899]
**Describe the bug**
When configuring the ubiquiti connector on linux the configuration could not be used:

```
2022-05-12 07:35:44 +0000 [warn]: parameter 'delimiter' in <source>
  type udp
  format none
  port 22022
  bind 0.0.0.0
  delimiter 

  tag oms.api.Ubiquiti
</source> is not used.
```
The configuration file is sourced from: https://github.com/Azure/Azure-Sentinel/blob/83c6d8c7f65a5f209f39f3e06eb2f7374fd8439c/Solutions/Ubiquiti/Data%20Connectors/la_agent_configs/ubiquiti.conf

Used configuration (workspace_id is masked):
```
<source>
  type udp
  format none
  port 22022
  bind 0.0.0.0
  delimiter "\n"
  tag oms.api.Ubiquiti
</source>

<match oms.api.Ubiquiti>
  type out_oms_api
  log_level info
  num_threads 5
  omsadmin_conf_path /etc/opt/microsoft/omsagent/<workspace_id>/conf/omsadmin.conf
  cert_path /etc/opt/microsoft/omsagent/<workspace_id>/certs/oms.crt
  key_path /etc/opt/microsoft/omsagent/<workspace_id>/certs/oms.key
  buffer_chunk_limit 10m
  buffer_type file
  buffer_path /var/opt/microsoft/omsagent/<workspace_id>/state/out_oms_api_ubiquiti*.buffer
  buffer_queue_limit 10
  buffer_queue_full_action drop_oldest_chunk
  flush_interval 30s
  retry_limit 10
  retry_wait 30s
  max_retry_wait 9m
</match>
```

**To Reproduce**
1. Configure Syslog on Unifi USG
2. Install the Linux Oms Agent (version omsagent-1.14.12-0)
3. Install and configure the "Ubiquiti UniFi (Preview)" data connector as described on the connector page in Sentinel
4. Download and set the workspace_id in the ubiquiti.conf file 
5. Restart the OmsAgent
6. `cat /var/opt/microsoft/omsagent/log/omsagent.log` shows the error above.

**Expected behavior**
It is expected that the agent would start including the ubiquiti.conf configuration.

**Desktop (please complete the following information):**
 - OS: Ubuntu Ubuntu 21.10
 - rsyslogd: version 8.2102.0
 - Ubiquiti Unifi USG3 v4.4.56
 - Ubiquiti Unifi Controller v7.1.61

**Comment by v-rucdu** [comment]
@mvaneijken : This seems to be a very old problem, and this connector may have already had numerous updates, can you please check and confirm if your problem has been solved? Thanks!!

**Comment by v-rucdu** [comment]
@mvaneijken : We are archiving this issue, please feel free to reopen incase the problem persist.. Thanks!!!
