### ISSUE TITLE
Suggestion for "results" field in Anomaly events

### ISSUE THREAD

**Issue by ep3p** [Azure/Azure-Sentinel#4905]
**Is your feature request related to a problem?**
No.

**Describe the solution you'd like**
Anomalies events have a query in ```ExtendedLinks[0].DetailBladeInputs```, if executed, that query would return the events that are considered the actual "anomaly".

Apart from these queries not being always "ready" to be copypasted and run (some of them contain errors), I would like another field with the results of this query being compressed in a format like:

```// might contain sensitive data
let alertedEvent = datatable(compressedRec: string)
['xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx==']
| extend raw = todynamic(zlib_decompress_from_base64_string(compressedRec)) | evaluate bag_unpack(raw) | project-away compressedRec;
alertedEvent
```

**Why?**

This field already exists for SecurityAlert events generated by a scheduled rule, specifically for the rules configured so that each event in the results is treated as a security alert.

It is found in ```ExtendedProperties.Query```, and a ```ExtendedProperties.OriginalQuery``` field is also generated. This is what allows an analyst clicking the event of an incident, and getting only a certain specific event from a query that returned several different events in its execution.

![image](https://user-images.githubusercontent.com/2527990/168041740-327e7a41-3fe0-400d-857a-3b4b2fadce81.png)

If this is implemented, then it would be easy to configure queries and rules that simply return the actual "anomaly" events, when a certain Anomaly event of interest happens. Instead of an analyst getting an Anomaly event, looking for the query field, copying this query, executing it in a new tab, and waiting for the results to load (when previously Microsoft has already done all of that to compute the Anomaly events).

If this is implemented, the only part left for the client would be to look for the "```['xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx==']``` values" in the Anomaly event, parse and decompress this value, and the actual anomaly events would be projected. The Anomaly event would be transparent for the analyst.

**Comment by sarah-yo** [comment]
Hi @ep3p, please can you raise this in the Azure Ideas platform. Thanks!

https://feedback.azure.com/d365community/forum/37638d17-0625-ec11-b6e6-000d3a4f07b8

**Comment by ep3p** [comment]
Done, thank you https://feedback.azure.com/d365community/idea/4d4bd0ea-59de-ec11-a81b-0022484ee92d

**Comment by abdallaamohamed** [comment]
I agree with ep3p, here is how to do it 

Table
| extend Compressed = extract(@"\['([^;]+)']",1,<CompressedTextQuery>)
| extend raw = todynamic(zlib_decompress_from_base64_string(Compressed))
