### ISSUE TITLE
Analytic Rule under security events folder missing query data frequency parameters

### ISSUE THREAD

**Issue by sandeep5234** [Azure/Azure-Sentinel#4929]
Trigger operators missing from rules "NRT_base64_encoded_pefile.yaml" and "NRT_execute_base64_decodedpayload.yaml"
These analytics rules will be found under Detections/securityevent folder. 

To reproduce:
run below command to deploy above 2 rules
  Import-AzSentinelAlertRule -SubscriptionId "subID" -WorkspaceName "workspacename" -SettingsFile "filepathtoabove2files"

**Screenshots**
![image](https://user-images.githubusercontent.com/41977495/168429090-8f26f46b-d8f3-4536-98ae-c19fb2bf2a57.png)

**Desktop (please complete the following information):**
 - OS:Windows 11
 - Powershell- 7

**Comment by v-mchatla** [comment]
HI @sandeep5234,
Sorry for the delay in response. Not sure how this rule is defined earlier but currently it's having a Kind as NRT. Query data frequency parameter is Required for Scheduled Detections only as it is of kind NRT we no need to specify. 
Hope this helps.
Closing this incident as rules are working as expected. Please feel free to reopen if you need any further clarification.
Thanks
