### ISSUE TITLE
CEF connector dropping Cisco ASA message ID

### ISSUE THREAD

**Issue by mblume1** [Azure/Azure-Sentinel#493]
I noticed that the CEF connector pulls in Cisco ASA logs to the Cisco ASA connector, but the OMS Agent is dropping the message ID at the front of the log. The workspace in Sentinel uses these Message IDs to parse the logs. For example:

When fed into the syslog connector the logs have the message ID:
%ASA-3-722035: Group <> User <> IP <> Received large packet ().

When fed into the Cisco ASA connector it gets dropped:
%ASA: end configuration: OK

If the workspace queries are built on parsing logs based on message ID, how can we get this ID into the Cisco ASA connector?

**Comment by oshezaf** [comment]
Hi @mblume1 : When configured to use the Cisco ASA (CEF) connector, the message is parsed to CEF. The data should reside in other fields and not in the message field. When sending as Syslog you get the data in raw format. If you are note getting the messages parsed into CEF, I suggest opening a support ticket.

**Comment by mblume1** [comment]
Ok that makes sense. I will open a support ticket with Azure Sentinel.
