### ISSUE TITLE
Some went wrong deploying CEF-VMSS

### ISSUE THREAD

**Issue by MauRiEEZZZ** [Azure/Azure-Sentinel#498]
**Describe the bug**
I clicked the deploy to Azure button at the page described below and the deployment wizard deployed a website...

**To Reproduce**
1. Go to 'https://github.com/Azure/Azure-Sentinel/tree/master/DataConnectors/CEF-VMSS#deploy-unbuntu-vmss', (Deploy Unbuntu VMSS) 
2. Click on 'Deploy to Azure'
3. Page 1 will appear, accept whatever default or change what you like.
3. Page 2 appears to show what it will deploy:
![image](https://user-images.githubusercontent.com/9781801/75013379-75621580-5484-11ea-86ec-61deacdd12d5.png)
4. Only Website???
5. After deployment:
![image](https://user-images.githubusercontent.com/9781801/75013481-ae9a8580-5484-11ea-9c45-c83b57c807af.png)

**Expected behavior**
It should deploy other resources than this, like as described in
https://github.com/Azure/Azure-Sentinel/tree/master/DataConnectors/CEF-VMSS 

**Screenshots**

**Desktop (please complete the following information):**
 - OS: macOs Mojave
 - Browser safari
 - Version 13.0

**Comment by dicolanl** [comment]
Researching

**Comment by dicolanl** [comment]
@MauRiEEZZZ Please try now.  I had the wrong deploy URL.  Updated the readme

**Comment by dicolanl** [comment]
Closing as the URLS were updated.
