### ISSUE TITLE
Playbook-ARM-Template-Generator not sanitizing data

### ISSUE THREAD

**Issue by Glenn408** [Azure/Azure-Sentinel#4990]
We've been trying to use the Playbook-ARM-Template-Generator to export our SNOW playbooks. After several tests we've found that little to none of the JSON has not been sanitized of the organisational information such as subscription and tenant IDs. The only parts that were successfully sanitized were the business logo and name. As a result, the rest of the parameters are not being asked when uploading the ARM template on the new tenant and the exports are failing. 

We've tried using different versions of Powershell (5.1 & 7) without any errors but get the same results. Also, tried on Visual studio code which stalls after entering the tenant ID and gives the following problem - 

"The cmdlet 'Confirmation-Dlg' uses an unapproved verb."

Any help/advice would be appreciated.

Tool - https://github.com/Azure/Azure-Sentinel/tree/master/Tools/Playbook-ARM-Template-Generator

**Comment by sreedharande** [comment]
@Glenn408 - How are you defining subscription and tenant ID in your playbook as a Variable or Parameter? You need to create Parameters within the logic app - then tool will add them to ARM Template

**Comment by Glenn408** [comment]
@sreedharande that was the issue. Thanks for the help! 

I had one final query. When we convert the playbook to the arm template using the script, the following section is added without being sanitized (I've made bold and italic the manually sanitized parts) -

    "resources":  [
        {
            "properties":  {
                "provisioningState":  "Succeeded",
                "state":  "Enabled",
                "integrationAccount":  {
                    "name":  "**_account_**",
                    "id":  "/subscriptions/**_subscriptionID_**/resourceGroups/**_ResourceGroup_**/providers/Microsoft.Logic/integrationAccounts/**_account_**",
                    "type":  "Microsoft.Logic/integrationAccounts"


This part isn't in the code before it is converted. Is there a reason this is added and a way we can sanitize?

**Comment by v-amolpatil** [comment]
Gentle Reminder: We are awaiting for your response on this issue. If you still need to keep this issue active please respond within next 2 days. If we don't receive response by 10 March, we will close this issue.

**Comment by v-dvedak** [comment]
Since we have not received a response in the last 5 days, we are closing your issue #4990 as per our standard operating procedures. If you still need support for this issue, feel free to re-open at any time. Thank you for your co-operation.
