### ISSUE TITLE
Cannot find "Validate the connector UX" - build your own connector

### ISSUE THREAD

**Issue by nancyparekh** [Azure/Azure-Sentinel#504]
Hello,
I am trying to build my own data connector according to the guidelines mentioned in [https://github.com/Azure/Azure-Sentinel/blob/master/DataConnectors/ReadMe.md#build-the-connector](https://github.com/Azure/Azure-Sentinel/blob/master/DataConnectors/ReadMe.md#build-the-connector). In the 3rd step i.e. "**Validate the Connector UX**", I am supposed to upload my connector JSON file using the "**Import**" option, but I cannot find such option on my portal.

As mentioned in the document I tried to access the utility using the [ https://ms.portal.azure.com/?feature.BringYourOwnConnector=true](https://ms.portal.azure.com/?feature.BringYourOwnConnector=true) but I was redirected to [https://portal.azure.com/?feature.BringYourOwnConnector=true#home](https://portal.azure.com/?feature.BringYourOwnConnector=true#home).
Can anyone let me know if this feature is still in beta version or do I need to update my subscription or any other issue?

**Comment by shainw** [comment]
@nancyparekh - the link will take you to the location to select the workspace associated with Azure Sentinel.  Once in Azure Sentinel, choose Data Connectors and you will see the "Import" button at the top.

![image](https://user-images.githubusercontent.com/45466083/75380705-5d2b3580-588c-11ea-9e3e-b817c7d93e14.png)

Let us know if that helps and I will see about updating the documentation.

Thanks,
Shain

**Comment by nancyparekh** [comment]
> @nancyparekh - the link will take you to the location to select the workspace associated with Azure Sentinel. Once in Azure Sentinel, choose Data Connectors and you will see the "Import" button at the top.
> 
> ![image](https://user-images.githubusercontent.com/45466083/75380705-5d2b3580-588c-11ea-9e3e-b817c7d93e14.png)
> 
> Let us know if that helps and I will see about updating the documentation.
> 
> Thanks,
> Shain

Hi Shain,
Thanks for the solution, it worked for me indeed!

**Comment by shainw** [comment]
Instructions updated.
