### ISSUE TITLE
GitHub Data Connector issue with KQL query for table GitHubAuditLogPolling CL

### ISSUE THREAD

**Issue by anthfuller** [Azure/Azure-Sentinel#5077]
**Upon installing GitHub Data Connector**
The Sentinel Workbook errors and KQL queries looking for a table: **"GitHubAuditLogPolling_CL"**, that is missing.

**To Reproduce**
1. Go to 'Sentinel Content hub'
2. Click on 'Search for GitHub
3. Scroll down to 'Create GitHub data Connector' and configure personal access token (making sure to add Admin.org on the access token for permissions). Once the GitHub content hub has been created, configure the repo organizational name, and add in access token. Refer to these instructions: https://techcommunity.microsoft.com/t5/microsoft-sentinel-blog/microsoft-sentinel-continuous-threat-monitoring-for-github/ba-p/3037154
4. See error, once you try and run a KQL query when opening the GitHub/Sentinel Data connector

**Expected behavior**
Audit logs can be pulled by running a Sentinel query using the Log Analytic KQL query, also the Sentinel Workbook for GitHub should work and not error out.

**Screenshots**
Adding two screenshots to show the error and what looks like a missing table. I also found out that **Dicolani** is no longer with the Security CXE and was the author for this GitHub data connector in the content hub. Please, help, thank you!

**Desktop (please complete the following information):**
 - OS: [Windows 11]
 - Browser [Edge
 - Version [21H2]
![GitHubError](https://user-images.githubusercontent.com/38588965/170032153-0ffad2d0-9eaf-406d-847f-f7744a4b8da1.png)
![GitHubError_workbook](https://user-images.githubusercontent.com/38588965/170032154-8e06833c-6e4c-44bf-88c7-7c9c6c9336de.png)

**Additional context**

**Comment by sarah-yo** [comment]
Looks to me like you don’t have GitHub data being ingested and thus those tables don’t exist in log analytics, hence why the queries and workbook will throw out errors. 

Based on the screenshots can you confirm that the following tables exist in your log analytics workspace?

Github_CL
Githubauditpolling_CL
