### ISSUE TITLE
Owner, Status, Severity Dropdown Not Working (Combined Workspaces)

### ISSUE THREAD

**Issue by nxraven** [Azure/Azure-Sentinel#5121]
**Describe the bug**
When selecting an alert, the right-hand preview of the incident's action buttons (Owner, Status, Severity) are greyed out and unresponsive. This appears to only happen when multiple workspaces are selected into one view. Individual workspaces function as expected. First seen May 22, 2022.

**To Reproduce**
1. Go to Azure Lighthouse and select multiple workspaces.
2. Click on "View Incidents."
3. Scroll down to an alert and click the alert, previewing the incident on the right-hand side.
4. See error where the Owner, Status, Severity dropdowns are greyed out.

**Expected behavior**
It is expected for the dropdown menus to toggle Owner, Status, and Severity.

**Screenshots**
![Screenshot 2022-05-25 084821](https://user-images.githubusercontent.com/87076634/170304098-c96d3762-29d6-450f-92a8-0078043e0f1b.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro 21H2
 - Browser Google Chrome
 - Version 101.0.4951.67 (Official Build) (64-bit)

**Smartphone (please complete the following information):**
Not Tested

**Additional Testing**
Cleared browser cookies and cache, affecting all users, users are in multiple countries

**Comment by sarah-yo** [comment]
Hi @nxraven, I couldn't replicate this so please could you raise this with Azure Support so they can look into your specific tenant. Thanks!
