### ISSUE TITLE
Uses a preview feature without warning

### ISSUE THREAD

**Issue by rukasakurai** [Azure/Azure-Sentinel#5143]
The code below uses the Azure Monitor HTTP Data Collector API feature which is currently in preview 
https://github.com/Azure/Azure-Sentinel/blob/1fed5a8f2c06f413d407bc32490119c7eb3f3d76/DataConnectors/O365%20Data/O365APItoAS-Template/TimerTrigger/run.ps1#L17

Recommendation to explictly mention in the comments that a preview feature is being used.

**Comment by sarah-yo** [comment]
Hi @rukasakurai, this is called out in the linked documentation:

![image](https://user-images.githubusercontent.com/50611022/170811439-fa4c61a8-3013-47a6-beb2-62a590b3875a.png)
