### ISSUE TITLE
Incomplete Instructions for Playbook Attributes

### ISSUE THREAD

**Issue by DeanGross** [Azure/Azure-Sentinel#5150]
**Describe the bug**
During the NIST 800-53 solution installation, we are prompted to enter the TeamsChannelID and the TeamsgroupID, but there is not any information about the type of data that is expected. where do we get these values from? These attributes are not used in the Teams user interface, so I'm not sure what to enter

**Screenshots**
![image](https://user-images.githubusercontent.com/4058555/170707952-04311954-03ed-409a-9e3b-f3e6a704bf40.png)

**Comment by thbanasi** [comment]
Here's an article which provides a quick overview on how to obtain this data which is sourced through the "Get a link to the Team" option in the ellipses next to the team name. https://www.c-sharpcorner.com/blogs/how-to-fetch-the-teams-id-and-channel-id-for-microsoft-teams#:~:text=To%20fetch%20the%20teams%20and%20channel%20id%20we,be%20used%20in%20graph%20API%20as%20mentioned%20below

**Comment by DeanGross** [comment]
Thanks, it would be helpful to included those instructions in the workbook as a tooltip or something

**Comment by thbanasi** [comment]
Will do and thanks for your feedback!
