### ISSUE TITLE
NIST SP 800-53 Workbook

### ISSUE THREAD

**Issue by DeanGross** [Azure/Azure-Sentinel#5151]
**Is your feature request related to a problem? Please describe.**
There is the ability to add an assessment note, but it does not document who actually did the assessment, 
**Describe the solution you'd like**
it would be useful to have an Assessor Name field.

**Comment by sarah-yo** [comment]
Hi @DeanGross, please can you raise this in the Azure Ideas platform. Thanks!

https://feedback.azure.com/d365community/forum/37638d17-0625-ec11-b6e6-000d3a4f07b8
