### ISSUE TITLE
404 on aka.ms link for Facebook Workplace template

### ISSUE THREAD

**Issue by dneto82** [Azure/Azure-Sentinel#5166]
https://github.com/Azure/Azure-Sentinel/blob/851627ca832539221511becf1a36c5d839ff7b21/Solutions/Workplace%20from%20Facebook/Data%20Connectors/WorkplaceFacebook/azuredeploy_Connector_FacebookWorkplaceWebhooks_AzureFunction.json#L158

**Comment by dneto82** [comment]
Actual Link - https://aka.ms/sentinel-WorkplaceFacebook-functionapp
Wrong Path:
`https://github.com/Azure/Azure-Sentinel/blob/master/DataConnectors/WorkplaceFacebook/WorkplaceFacebookWebhooksSentinelConn.zip?raw=true`

Correct Path:
`https://github.com/Azure/Azure-Sentinel/blob/master/Solutions/Workplace%20from%20Facebook/Data%20Connectors/WorkplaceFacebook/WorkplaceFacebookWebhooksSentinelConn.zip?raw=true`

**Comment by NikTripathi** [comment]
Hi @dneto82  Thanks for letting us know. Links has been updated and issue must have been resolved.
Sorry for the inconvenience.
Thanks.

**Comment by NikTripathi** [comment]
We has an ICM for the same. [Incident 338301888](https://portal.microsofticm.com/imp/v3/incidents/details/338301888/home) : [S500] [CRI] 2209220030001625 - workplace from facebook connector ERROR
