### ISSUE TITLE
Workbook gets corrupted on Solution deploy

### ISSUE THREAD

**Issue by johannesh-recordedfuture** [Azure/Azure-Sentinel#5167]
**Describe the bug**
The [Recorded Future solution](https://github.com/Azure/Azure-Sentinel/tree/master/Solutions/Recorded%20Future) contains two workbooks which for some reason break when you deploy the full solution. If you manually deploy the workbooks individually there is no problem. Specifically it is a query in each of the playbooks that are modified into a breaking state during the solution deploy. The queries go from `| project Risk=ConfidenceScore, DomainName, ThreatType` (part of the working query) to `|projectRisk=ConfidenceScore, DomainName, ThreatType` (part of the broken query). 

**EDIT:** [Link to query in GitHub solution repo ](https://github.com/Azure/Azure-Sentinel/blob/223f77cf0d881e6bfe70196041162569c7de8bd2/Solutions/Recorded%20Future/Workbooks/Recorded%20Future%20-%20%20C%26C%20DNS%20Name%20to%20DNS%20Events%20-%20Correlation%26Threat%20Hunting.json#L158)

I have no idea what could cause this.

**To Reproduce**
1. In an Azure environment, go to Solutions
2. Create a new **Recorded Future Sentinel Solution** from the Store
3. Go to one of the included workbooks
4. See error in Query

**Expected behavior**
The workbook is deployed with the query and the query is kept intact to how it is on GitHub.

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04
 - Browser: Chrome
 - Version: 101.0.4951.64 (Official Build) (64-bit)

**Comment by johannesh-recordedfuture** [comment]
Is it possible to get someone to look into this issue?

**Comment by NikTripathi** [comment]
@johannesh-recordedfuture Sorry for responding late. New solution with the fix has been live. Can you please test it and confirm.
Thanks

**Comment by v-laanjana** [comment]
@johannesh-recordedfuture Sorry for responding late. New solution with the fix has been live. Can you please test it and confirm.
Thanks

**Comment by RecordedFutureOskbo** [comment]
I have tested this from Recorded Future and the KQL now looks good and works as expected.

**Comment by v-laanjana** [comment]
@RecordedFutureOskbo  Thank for update .
