### ISSUE TITLE
could not receive logs after configuring Tenable.io Vulnerability Management (Preview)

### ISSUE THREAD

**Issue by IDCheryl** [Azure/Azure-Sentinel#5174]
**Describe the bug**
After creating Tenableio in Content hub, then deployed ARM for Data connector: Tenable.io Vulnerability Management (Preview)
waiting more than 48hours, no data could be received

**To Reproduce**
1. Go to 'Content hub' >> search Tenable, create Tenable solution
2. Click on 'Data connector' >> search "Tenable.io Vulnerability Management (Preview)" >> choose Azure Resource Manager (ARM) Template to deploy function app with workspace ID& key and TenableAccessKey and TenableSecretKey 
3. After waiting 48hours, go to logs and query "Tenable_IO_Assets_CL"
5. 
![image](https://user-images.githubusercontent.com/105334881/171202330-5f7d18e5-8211-4bcb-bb94-2662f1e852cb.png)

**Expected behavior**
Logs should be received after configuring data connector

**Screenshots**
![image](https://user-images.githubusercontent.com/105334881/171202651-400cc2a7-ecfd-453f-8a15-59d06fbab3f5.png)

**Comment by dneto82** [comment]
@IDCheryl did you ran [parser](Solutions/TenableIO/Parsers/TenableIOAssets.txt) after deployed solution?

**Comment by IDCheryl** [comment]
Hello @dneto82 , 
I have not yet ran parser.
I'm trying to query Tenable_IO_Assets_CL this original data type, no data returned.
Below is the error message I found, could you please suggest what the problem and how can i address it?
![error](https://user-images.githubusercontent.com/105334881/171760528-879f84d4-7044-4f9f-91c9-2520bf461e12.png)

**Comment by IDCheryl** [comment]
Hello @dneto82 

Tenant permission has been updated to administrator now, and i could observe the Tenable_IO_Assets_CL logs now.

However I could still not observe any Tenable_IO_Vulns_CL logs. 
I have checked the function app. Success timestamp already exists.

Error message attached.
![error-vul](https://user-images.githubusercontent.com/105334881/171778409-25c41d52-7a2f-4cae-a3f8-59dc1bb370d1.png)

and I've seen someone commented for this solution as well, I've encounter just the same issue here.
![comments](https://user-images.githubusercontent.com/105334881/171778825-e9b44fc4-7d21-479a-af7f-3a7e493b1e5c.png)

i could see the assest data ingested but no vuln data. Please kindly help fix

**Comment by v-amolpatil** [comment]
Hi @IDCheryl, thank you for flagging this. Apologies for the delayed response. If you still need assistance, please reply here within 5 business days.

**Comment by v-amolpatil** [comment]
Since we have not received a response in the last 5 days, we are closing your issue #5174 as per our standard operating procedures. If you still need support for this issue, feel free to re-open at any time. Thank you for your co-operation.
