### ISSUE TITLE
Validation check is incorrectly flagging dynamic variable as a resourceId property

### ISSUE THREAD

**Issue by rc-iwoodley** [Azure/Azure-Sentinel#5175]
[This](https://github.com/redcanaryco/Azure-Sentinel/tree/MSFT-421/Solutions/Red%20Canary) is the branch with our Solution files.

**Describe the bug**

RE [mainTemplate.json](https://github.com/redcanaryco/Azure-Sentinel/blob/MSFT-421/Solutions/Red%20Canary/Package/mainTemplate.json): validation is failing with the following error and suggested fix:

<img width="358" alt="sentinel-error" src="https://user-images.githubusercontent.com/80064276/171201193-a4617746-86b1-4b33-ba02-6837cdd56cb0.png">

The suggested fix is to create a variable under the **variables** section of `mainTemplate.json`. This does not make sense, as **detection_id** is simply referencing the **detection_id_s** column from our custom table; it is not a hardcoded value or a **resourceId.** **detection_id** is used in our analytics rule [here](https://github.com/redcanaryco/Azure-Sentinel/blob/MSFT-421/Solutions/Red%20Canary/Analytic%20Rules/RedCanaryThreatDetection.yaml#L121-L122) to group alerts.

The associated CI run showing the validation failure is available [here](https://partner.microsoft.com/dashboard/windows/api/certweb/report/certReport/39e67fe0-26cb-43da-b5c8-0ea190f4b3ab).

**To Reproduce**
1. Run validation against [our branch](https://github.com/redcanaryco/Azure-Sentinel/tree/MSFT-421/Solutions/Red%20Canary).

**Expected behavior**
Validation should pass.

**Comment by NikTripathi** [comment]
Hello @rc-iwoodley , We are already working on this error. We are listing out all the values which are referencing to a column from a custom table. We will add exception for all those values in one go. Sorry for inconvenience caused. Issue will be resolved soon.
Thanks.

**Comment by AshfordTC** [comment]
@NikTripathi Thanks for the input.  We have been waiting to get resolution on this for months.  Can you post here when the exceptions for the given values have been added?  We will then immediately resubmit.

**Comment by ashishsyal** [comment]
We are working on this and will share an update shortly.
