### ISSUE TITLE
PostMessageToTeams Playbook throwing an error 

### ISSUE THREAD

**Issue by tijan2018** [Azure/Azure-Sentinel#5177]
**Describe the bug**
I have deployed the playbook but getting a licensed related error whenever I try to run the playbook with an incident even though the Teams channel is licensed. 

**To Reproduce**
1. Go to Sentinel Incidents
2. Click on any Incident and attach the playbook

**Expected behavior**
A notification to be sent to the team's channel created for incident notifications

**Screenshots**
![image](https://user-images.githubusercontent.com/45381747/171262763-802a31bf-e7d5-4c01-952e-7397ec81efbc.png)

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 11]
 - Browser [Edge]
 - Version [101.0.1210.53]

**Additional context**
No other context to add

**Comment by sarah-yo** [comment]
Hi @tijan2018, can you confirm that the user account that you have used to access Teams via the Playbook is properly licensed for Teams? It's not the channel that needs to be licensed its the user.

**Comment by tijan2018** [comment]
Hi Sarah, yes, the user is licensed for Teams. I am working with a customer on this and the user who created the Teams channel is definitely licensed for Teams. Has this playbook been tested recently? Is there any chance that a similar issue has been reported before?

**Comment by tijan2018** [comment]
Any update on this issue?

**Comment by v-laanjana** [comment]
Hi @tijan2018 Could you please confirm above comments ?

**Comment by BenjiSec** [comment]
@sreedharande  - there is no update on this, so you can close the issue.
