### ISSUE TITLE
Cisco Umbrella function app - Reference Bundle requires updating. 

### ISSUE THREAD

**Issue by jeremymk-msft** [Azure/Azure-Sentinel#5179]
**Describe the bug**
Cisco Umbrella Data Connector function app deployment will generate an error message with the following when attempting to run.

Microsoft.Azure.WebJobs.Script: Referenced bundle Microsoft.Azure.Functions.ExtensionBundle of version 1.8.1 does not meet the required minimum version of 2.6.1. Update your extension bundle reference in host.json

**To Reproduce**
Deploy the function app as is within the repo. 

**Expected behavior**
The function app trigger should run on it's timer basis.  Once upgraded to 2.* of the reference bundle,  the application will work as intended. 

**Additional context**

Testing and validating updating the function to the 2.* reference bundle will resolve it and allow the function to trigger.

**Comment by v-laanjana** [comment]
@ teachjing  any update?

**Comment by v-laanjana** [comment]
@jeremymk-msft the above issue has been fixed please try to deploy again .
