### ISSUE TITLE
Analytics Rule Issue : DEV-0586 Actor IOC - January 2022

### ISSUE THREAD

**Issue by hisashin0728** [Azure/Azure-Sentinel#5187]
**Describe the bug**
Some IoC rules aren't imported to Microsoft Sentinel.
- DEV-0586 Actor IOC - January 2022
- ACTINIUM Actor IOCs - Feb 2022
- SOURGUM Actor IOC - July 2021

**To Reproduce**
1. Go to Analytics Rules, and select Rule Templates.
2. Click on the following template rules.

1. DEV-0586 Actor IOC - January 2022
2. ACTINIUM Actor IOCs - Feb 2022
3. SOURGUM Actor IOC - July 2021

4. The error detects when the template rules are enabled.
5. See error

**Expected behavior**

**Screenshots**
<img width="680" alt="image" src="https://user-images.githubusercontent.com/55295601/171530361-cb711307-eb18-485e-b8dc-fe6980e03100.png">

<img width="652" alt="image" src="https://user-images.githubusercontent.com/55295601/171530395-e4c548a0-a052-4ce6-95c1-7d07341aab82.png">

**Desktop (please complete the following information):**
**Smartphone (please complete the following information):**
**Additional context**

**Comment by v-vdixit** [comment]
Hi @hisashin0728 we have updated the package for the solution, please check and confirm if you are still facing this issue, thanks

**Comment by v-vdixit** [comment]
@hisashin0728 Gentle Reminder: We are awaiting for your response on this issue. If you still need to keep this issue active please respond on it in the next 2 days. If we don't receive response by given date we will close this issue as per our standard procedure

**Comment by v-vdixit** [comment]
Hi @hisashin0728 Since we have not received a response in the last 5 days, we are closing your issue #5187 as per our standard operating procedures. If you still need support for this issue, feel free to re-open at any time. Thank you for your co-operation.
