### ISSUE TITLE
Playbook – Create a list of discovered vulnerabilities pertaining to a machine/host 

### ISSUE THREAD

**Issue by preetikr** [Azure/Azure-Sentinel#520]
**Requirements**

- Create an Azure Logic Apps playbook for Azure Sentinel that includes the following workflow:
   * Triggers on an Azure Sentinel alert. 
   * If the alert has hosts, find list of vulnerabilities pertaining to each host/machine. Include name, description, severity, CVE at a minimum. 
   * Feed that into a document and post the document onto a SharePoint site.
   * Update the Azure Sentinel incident with the link to the vulnerability report.
- Validate the playbook works as expected per the functional requirement mentioned above. 
- Submit the playbook as a GitHub Pull Request per the playbook contribution guidance.
- Attach a screenshot of the working playbook with your submission. 
- Attach a screenshot of the final output with the vulnerability data. 
- Provide a readme with the steps with your submission to document any prerequisite steps required before running this playbook.

The first submission that meets the requirements gets the reward. Rewards are subject to [Microsoft terms and conditions](https://aka.ms/sentinelrewardsterms). 
 
**Hints** 

- Connect with any product (API) of your choice that provides vulnerability list. Few examples are [Qualys](https://www.qualys.com/documentation/), [Microsoft Defender ATP](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/get-discovered-vulnerabilities), etc.
- Feel free to leverage HTTP Connector for Azure Logic Apps as needed.

**Helpful resources**
- [Azure Sentinel Playbook documentation](https://docs.microsoft.com/azure/sentinel/tutorial-respond-threats-playbook)
- [Playbook contribution guidance](https://aka.ms/sentinelgithubplaybooks)
- [Create Azure Logic Apps Playbook](https://docs.microsoft.com/azure/logic-apps/quickstart-create-first-logic-app-workflow)
- [SharePoint Logic Apps connector](https://docs.microsoft.com/en-us/connectors/sharepointonline/)

**Comment by sysgoblin** [comment]
Any preference or stipulation on the document type you want to hold the vulnerability data? (csv, word doc, txt etc?)

**Comment by shainw** [comment]
Answering both parts I think the audience is slightly different for each file type.  I think maybe the way to go is provide both a CSV and a summary Word/PDF Document.  The CSV is probably more useful for the threat hunter/security analyst who is going to look further into the the security issue, whereas, the Word DOC/PDF is probably more useful for building out a larger report that goes to management on current threats in the environment.  That said, we shouldn't require you to provide both as that is not specified, so going with the language in the post using the term "document", I think a Word DOC or PDF would be appropriate.  Thanks much for your interest, looking forward to your submission.  Shain

**Comment by WayneJLee** [comment]
Hey @preetikr just checking on the status of the review.

**Comment by preetikr** [comment]
Hi @WayneJLee - Congratulations! We've reviewed and merged your submission.
Thanks, for your contribution.
We'll reach out to you to figure the next steps on Rewards for this contribution.
Thanks,
Preeti
