### ISSUE TITLE
Cisco Meraki Solution data connector errors

### ISSUE THREAD

**Issue by sjbradbury** [Azure/Azure-Sentinel#5202]
After deploying this solution on May 26 - https://github.com/Azure/Azure-Sentinel/tree/master/Solutions/CiscoMeraki 

We have errors on the Sentinel data connectors page: "Unexpected error An error occurred while we were working on this page. Please try again later. If you continue to receive this error message, contact Microsoft support."

Deleting the solution does not resolve the problem

**Comment by marcjacquard** [comment]
Look at your functions and load the CiscoMeraki function code. See if you get an error about a duplicate function. I had the same issue and when I loaded the function code it showed I had a duplicate. I deleted the function code and then the error went away. It also instantly re-added the newer function code.

**Comment by sjbradbury** [comment]
> Look at your functions and load the CiscoMeraki function code. See if you get an error about a duplicate function. I had the same issue and when I loaded the function code it showed I had a duplicate. I deleted the function code and then the error went away. It also instantly re-added the newer function code.

Yeah that absolutely fixed it, I remember seeing the error about a duplicate function but never deleted anything. I deleted the CiscoMeraki function, which never disappeared it just refreshed with different code and now the data connectors page loads fine.

Thank you!
