### ISSUE TITLE
Workbook – Monitor data using any firewall logs with other data logs of your choice

### ISSUE THREAD

**Issue by preetikr** [Azure/Azure-Sentinel#522]
**Requirements**

- Create an Azure Monitor workbook for Azure Sentinel that includes the following:
  * Mash up of Windows Firewall data in Azure Sentinel and at least 3 data types
  * Workbook includes at least four charts / visuals that includes one trend chart
  * Correlate entities across the different data types    
  * Workbook description should include a note on how the workbook demonstrates usefulness to an enterprise, for example by streamlining security operations, reducing threat detection and response times, or improving the effectiveness of existing security tools.   
- Validate the workbook works as expected per the functional requirement mentioned above. 
- Submit the workbook as a GitHub Pull Request per the workbook contribution guidance.

 
The first submission that meets the requirements gets the reward. Rewards are subject to [Microsoft terms and conditions](https://aka.ms/sentinelrewardsterms). 
  
**Helpful resources**

- [Azure Sentinel Workbook documentation](https://docs.microsoft.com/azure/sentinel/tutorial-monitor-your-data)
- [Workbook contribution guidance](https://aka.ms/sentinelgithubworkbooks)
- [Create Azure Monitor Workbooks](https://docs.microsoft.com/azure/azure-monitor/app/usage-workbooks)

**Comment by shainw** [comment]
@TheAwesem - Thanks again for the submission.  I reviewed  your submission and provided recommended changes.  Apologies for the delay in getting back to you with these suggestions.

**Comment by preetikr** [comment]
@TheAwesem - Congratulations! We've reviewed and merged your submission.
Thanks, for your contribution.
We'll reach out to you to figure the next steps on Rewards for this contribution.
Thanks,
Preeti
