### ISSUE TITLE
MS Sentinel-GitHub Data Connector RES40005 Transient Exception Error

### ISSUE THREAD

**Issue by anthfuller** [Azure/Azure-Sentinel#5232]
**When installing NEW UPDATED SENT/GitHub data connector from content hub**

**To Reproduce**
1. Sentinel Content hub
2. Locate GitHub data connector.
3. Install, after install attempt to connect GitHub Repo. Create Personal access token with admin.org permissions
4. Add in GitHub ENT organization name and access token, hit connect. Received "res40005 hit transient exception" error. 

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by dneto82** [comment]
Same problem here

**Comment by v-rucdu** [comment]
@anthfuller : Based on your discussion with Prathibha, GitHub audit polling solution is installed successfully and now we see the dataconnector is connected and pulling the details from GitHub API. And also the analytical queries and workbooks also enabled and connected. Hence we are closing this issue. Please reach out to us in case any open queries.
