### ISSUE TITLE
"TI map URL entity" detection rules are checking a single URL

### ISSUE THREAD

**Issue by ep3p** [Azure/Azure-Sentinel#5270]
**Describe the bug**

"TI map URL entity" detection rules are checking a single URL through a regex, instead of the multiple URLs that could happen.

For example, in (https://github.com/Azure/Azure-Sentinel/blob/master/Detections/ThreatIntelligenceIndicator/URLEntity_SecurityAlerts.yaml),
the operator that extracts the URL just returns one URL, when in fact there could be more than one URL in the Entities of a SecurityAlert.

```| extend Url = extract("(http[s]?://(?:[a-zA-Z]|[0-9]|[$-_@.&+]|[!*\\(\\),]|(?:%[0-9a-fA-F][0-9a-fA-F]))+)", 1,Entities)```

I propose you could use something like:

```
| extend Url = todynamic(dynamic_to_json(extract_all(URLRegex, dynamic([1]), Entities)))
| mv-expand Url
| extend Url = tostring(Url[0])
| where isnotempty(Url)
```

The ```todynamic(dynamic_to_json(``` part is needed because sometimes ```extract_all()```, for the same source string, returns:
```["example.com","example2.com"]```
and other times returns:
```[["example.com"],["example2.com"]]```
It is a weird behaviour, but I don't know the reason.

For the URLRegex you could use something like:

```((https?|ftp|ldap|wss?|file):\/\/(([\:\%\w\_\-]+(\.|@))*((xn--)?[a-zA-Z0-9\-]+\.)+(xn--[a-z0-9]+|[A-Za-z]+)|\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{0,3})[.,:\w@?^=%&\/~+#-]*[\w@?^=%&\/~+#-])```

Thank you for attending me.

**Comment by Jukeking86** [comment]
// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

using Azure.Core;
using Azure.Core.TestFramework;
using Azure.ResourceManager.Resources;
using Azure.ResourceManager.TestFramework;
using NUnit.Framework;
using System.Threading.Tasks;

namespace Azure.ResourceManager.AppPlatform.Tests
{
    public class AppPlatformManagementTestBase : ManagementRecordedTestBase<AppPlatformManagementTestEnvironment>
    {
        protected ArmClient Client { get; private set; }

        protected AppPlatformManagementTestBase(bool isAsync, RecordedTestMode mode)
        : base(isAsync, mode)
        {
        }

        protected AppPlatformManagementTestBase(bool isAsync)
            : base(isAsync)
        {
        }

        [SetUp]
        public void CreateCommonClient()
        {
            Client = GetArmClient();
        }

        protected async Task<ResourceGroupResource> CreateResourceGroup(SubscriptionResource subscription, string rgNamePrefix, AzureLocation location)
        {
            string rgName = Recording.GenerateAssetName(rgNamePrefix);
            ResourceGroupData input = new ResourceGroupData(location);
            var lro = await subscription.GetResourceGroups().CreateOrUpdateAsync(WaitUntil.Completed, rgName, input);
            return lro.Value;
        }
    }
}

**Comment by ep3p** [comment]
@Jukeking86 please, review your recent activity, they seem like malformed automatic actions.

**Comment by v-vdixit** [comment]
Hi @ep3p we are looking into this, will test and update the query shortly, thanks!

**Comment by v-vdixit** [comment]
Hi @aprakash13 / @devikamehra please take a look at this and provide feedback, thanks!

**Comment by v-vdixit** [comment]
Hi @ep3p we are testing the suggested changes, will update shortly, thanks!
