### ISSUE TITLE
Unable to install CEF collector on Linux machine using web proxy

### ISSUE THREAD

**Issue by jgallucci32** [Azure/Azure-Sentinel#528]
**Describe the bug**
When installing the Linux Syslog agent to collect Common Event Format (CEF) Syslog messages, the install errors out when the system using a web proxy (such as Squid) to forward requests to the internet.

**To Reproduce**
1. Login to Linux machine to install the CEF collector
2. Configure proxy settings
```
cat << EOF > /etc/profile.d/proxy.sh
export http_proxy=http://myproxy:3128/
export https_proxy=https://myproxy:3128/
export no_proxy="127.0.0.1, localhost"
EOF
```
2. Re-login to system to ensure proxy settings persist
3. Run the following command to install and apply the CEF collector
```
sudo wget https://raw.githubusercontent.com/Azure/Azure-Sentinel/master/DataConnectors/CEF/cef_installer.py&&sudo python cef_installer.py <hash value>
```
```
--2020-03-16 14:50:45--  https://raw.githubusercontent.com/Azure/Azure-Sentinel/master/DataConnectors/CEF/cef_installer.py
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... failed: Name or service not known.
wget: unable to resolve host address ‘raw.githubusercontent.com’
```

**Expected behavior**
Log agent installed successfully

**Server Info**
Red Hat Enterprise Linux 7.7

**Comment by oshezaf** [comment]
Per the Log Analytics agent documentation [here](https://docs.microsoft.com/en-us/azure/azure-monitor/platform/log-analytics-agent) and [here](https://docs.microsoft.com/en-us/azure/azure-monitor/platform/agent-manage#linux-agent-1), you set up a proxy by modifying the proxy.conf.

**Comment by jgallucci32** [comment]
Thanks @oshezaf this is pointing me in the right direction. It looks like the python wrapper script written for Azure Sentinel does not have support yet for an http proxy. I'll see if I can modify the script and issue a pull request.

**Comment by jgallucci32** [comment]
Created pull request https://github.com/Azure/Azure-Sentinel/pull/531

There were two parts to the issue. The first part is with the `cef_installer.py` script which is in the pull request. The second issue was with sudo not passing the `https_proxy` environment variable.

To fix the second issue you need to modify `/etc/suoders` or add the file `/etc/sudoers.d/proxykeep` to pass the environment variables for http proxy settings
```
Defaults env_keep += "http_proxy https_proxy no_proxy"
```

With sudo passing the `https_proxy` environment variable and the `cef_installer.py` script modified to detect and add the argument to the omsagent install script, the CEF collector can be installed fully with proxy settings and no post-modifications required.

**Comment by Ronmarsiano** [comment]
Thanks for the contribution, we are taking a look and will address the issue

**Comment by laughingman42** [comment]
We were able to work around this problem by updating /etc/wgetrc to add the proxy variables http_proxy and https_proxy and enable it using use_proxy = on. We also added check_certificate = off to prevent issues with SSL. This ensures any instance of wget being called by scripts or nested scripts will always pickup the proxy configuration. Ref ([link](https://www.gnu.org/software/wget/manual/html_node/Sample-Wgetrc.html))

**Comment by preetikr** [comment]
Closing as this has been work-arounded
