### ISSUE TITLE
Include Alert Generating Platform Alert Link in Sentinel Alerts

### ISSUE THREAD

**Issue by kylemiller061** [Azure/Azure-Sentinel#530]
**Is your feature request related to a problem? Please describe.**
I would like similar functionality to the Microsoft365 Security Portal in Sentinel where you can directly pivot into the appropriate security product portal from a specific alert. I have to manually navigate into for example the MDATP portal and find the corresponding alert to action on it.

**Describe the solution you'd like**
For a MDATP alert in Sentinel, include a link to the alert in Sentinel that directs you to appropriate the MDATP portal alert.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by preetikr** [comment]
@kylemiller061 - This information is available in Azure Sentinel alerts. Alerts are exposed via incidents in Azure Sentinel, clicking on which gets you to the Azure Sentinel's SecurityAlerts table. The source link to the product alert is available in the **ExtendedProperties** field for MDATP alerts -> **Drill into Windows Defender ATP link** and access value. We will look into your feedback of exposing this as a direct clickable link in the incident itself. 
There's another way to access the direct link to Azure Sentinel and other product alerts. This is via [Microsoft Graph Security API](https://aka.ms/graphsecuritydocs) that provides Azure Sentinel, MDATP and other alerts in a structured format - field **sourceMaterials** has the link.

**Comment by kylemiller061** [comment]
I understand that the data is available via ExtendedProperties in LogAnalytics, but this is not optimal for an analyst investigative workflow. Directly exposing the data from, or opening the appropriate web pages for the alert, machine, user, etc. Would make the end users experience allot smoother.

**Comment by preetikr** [comment]
@kylemiller061 - Yes, I agree. The Log Analytics part is more of a workaround for now. We are working on a feature to show the link to the product portal for Microsoft alerts and should land in the next couple months. Stay tuned. Thanks, for your feedback.
