### ISSUE TITLE
Detection rule 'Failed login attempts to Azure Portal' incorrect IPCustomEntity

### ISSUE THREAD

**Issue by wadstromdev** [Azure/Azure-Sentinel#536]
**Describe the bug**
The IPCustomEntity in the detection rule 'Failed login attempts to Azure Portal' is a list of IP adresses which causes incorrect view of entities in the Sentinel incident.

**To Reproduce**
1. Trigger a failed logon attempt incident
2. Compare the entities list to the query results

**Expected behavior**
I believe the query should result in one row per failed login, with one IP per row, instead of aggregating all failures to one row per account.

**Screenshots**
![image](https://user-images.githubusercontent.com/36885853/77047876-cacb0d00-69c5-11ea-9011-37e09da03df6.png)
![image](https://user-images.githubusercontent.com/36885853/77047952-eb936280-69c5-11ea-92e8-7eb7d2115591.png)

**Desktop (please complete the following information):**
 - OS: N/A
 - Browser N/A
 - Version N/A

**Smartphone (please complete the following information):**

**Additional context**

**Comment by shainw** [comment]
@wadstromdev - Thanks, let me have a look and I will get back to you.

**Comment by shainw** [comment]
@wadstromdev - I did some review and there is room for improvement in general on this, including bringing the IP thru properly.  I am working on it and will post here once I push the fix into the repo.

**Comment by shainw** [comment]
I have submitted a PR to fix the IPAddress issue and improvements in general - https://github.com/Azure/Azure-Sentinel/pull/539
