### ISSUE TITLE
Azure Sentinel Suppression alert issue 

### ISSUE THREAD

**Issue by Ziy-sws** [Azure/Azure-Sentinel#538]
Good Day 

I am having an issue where a certain user's MFA has been disabled, and it should be that way for a few days. I have the analytics rule alert enabled but it keeps querying and opening a new alert. (I want it to query for at least 1 hour) . I have set the suppression to 5 hours after an alert is generated, although when testing no new alarms are coming through, e.g. another user disabling MFA.

Is there anyway to set the suppression for only one specific alert? 

![image](https://user-images.githubusercontent.com/52692970/77163773-7dc76380-6ab7-11ea-924b-97055d8932be.png)

**Comment by shainw** [comment]
@Ziy-sws - I am not sure this is currently possible, but the idea is sound.  Alert suppression based on AlertId or UserId or HostName and so on seems to make sense.  I will have one of the PMs review the issue and comment.  Thanks for the question.

**Comment by Ziy-sws** [comment]
Thank you!

**Comment by preetikr** [comment]
@Ziy-sws - Thanks, for the feedback. Complete alert suppression based on properties is in our plans. 
In the interim, you can leverage the new Alert Grouping feature, that's in Public Preview for your use case.
