### ISSUE TITLE
Timechart Renders Incorrectly In Workbook but Correctly In Log Analytics Query Editor

### ISSUE THREAD

**Issue by melatonein5** [Azure/Azure-Sentinel#5397]
## Summary

I recently wrote a query to render a timechart which queries the incidents table, finds new incidents, and groups them based on 15 minute intervals. I also added the functionality to group by day, with the idea the graph can be used for resource management (the idea is that the number of incidents peaks on certain days). Here is the query:

```let TimeRange = now(-28d);
let Interval = 15m;
let Days = dynamic({"00:00:00":"1_Sun", "1.00:00:00":"2_Mon", "2.00:00:00":"3_Tue", "3.00:00:00":"4_Wed", "4.00:00:00":"5_Thu", "5.00:00:00":"6_Fri", "6.00:00:00": "7_Sat"}); 
SecurityIncident
| where TimeGenerated > TimeRange
| where Status == "New"
| summarize arg_min(TimeGenerated, *) by IncidentName
| project format_datetime(bin(TimeGenerated, Interval), "HH:mm"), Day=tostring(Days[tostring(dayofweek(TimeGenerated))])
| summarize Count = count() by TimeGenerated, Day
| sort by TimeGenerated asc 
| render timechart 
```

It works perfectly in the Log Analytics Query Editor.

![image](https://user-images.githubusercontent.com/58752351/174793473-1beba464-ee04-44eb-b6a1-5b0b59c2abf2.png)

When I try to add it to a workbook, the graph is unreadable. I believe this is because the render function works slightly differently when in a work book. The lines are a mess.

![image](https://user-images.githubusercontent.com/58752351/174793705-83187417-f548-4fe8-9b00-1a9d45cc3921.png)

## To Reproduce

1. Go to Sentinel
2. Click On "Logs" in the side bar of the main menu page
3. Paste the above query, it will produce the correct output
4.  Navigate to workbooks on the side menu.
5. Create a new workbook
6. Add a query
7. Paste the above query

_Note: The query I ran had 335 results, with an range of data points. I believe it is the number of X axis datapoints is the main culprit, so any reproduction needs to have a similar data set. I have attached a data export._

## Expected behavior
The graph in the workbook should look the graph in the Log Analytics query editor.

## Screenshots

It works perfectly in the Log Analytics Query Editor.

![image](https://user-images.githubusercontent.com/58752351/174793473-1beba464-ee04-44eb-b6a1-5b0b59c2abf2.png)

When I try to add it to a workbook, the graph is unreadable. I believe this is because the render function works slightly differently when in a work book. The lines are a mess.

![image](https://user-images.githubusercontent.com/58752351/174793705-83187417-f548-4fe8-9b00-1a9d45cc3921.png)

Screenshot of the chart settings. Changing the grouping results results in a single line, rather than 7, so is not an option:

![image](https://user-images.githubusercontent.com/58752351/174795926-564cf9fd-4200-465d-b13c-0ff7a5eeaf89.png)

## Desktop (please complete the following information):
 - OS: Windows 10 Enterprise
 - Browser: Edge
 - Version: 102.0.1245.44 (Official build) (64-bit)
 
## Additional context
[query_data (3).csv](https://github.com/Azure/Azure-Sentinel/files/8948678/query_data.3.csv)

**Comment by v-rbajaj** [comment]
Gentle Reminder: We are awaiting for your response on this issue. If you still need to keep this issue active please respond on it in the next 2 days.. If we don't receive response, we will be close this issue.

**Comment by v-rbajaj** [comment]
Since we have not received a response in the last 5 days, we are closing your issue https://github.com/Azure/Azure-Sentinel/issues/5397 as per our standard operating procedures. If you still need support for this issue, feel free to re-open at any time. Thank you for your co-operation.
