### ISSUE TITLE
Get-MDATPInvestigationPackage - issue with retrieving package download URI due to POST instead of GET 

### ISSUE THREAD

**Issue by alexverboon** [Azure/Azure-Sentinel#540]
Hello, 
I am having issues with running the Get-investigation package download URI step in the Get-MDATPInvestigationPackage playbook and I am pretty sure that the issue is related to that the logic app step submits a POST instead of a GET, i was able to reproduce the issue in the MDATP API explorer. 

The following error appears:
{
  "error": {
    "code": "NotFound",
    "message": "No HTTP resource was found that matches the request URI 'https://api.securitycenter.windows.com/api/machineactions/ea098113-c6ed-44ed-bb04-f1e3f160eff4/getPackageUri'.",
    "target": "693228c8-f7d5-463a-8945-872d217253a2"
  }
}

When running the same command with GET, the URL is correctly returned. 

however when i change the logic app code to 
   "method": "get",
                                    "path": "/api/machineactions/@{encodeURIComponent(body('Actions_-_Get_single_machine_action')?['id'])}/getPackageUri"

i get completely other errors.

**Comment by alexverboon** [comment]
hmm, nevermind, changed the code , and will try again, i was too long in visual edit mode that i simply forgot that i can switch to code view :-)

**Comment by dicolanl** [comment]
@alexverboon great catch.  https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/get-package-sas-uri  looks like its a GET.  But this playbook is using the native connector.  Ill take it with the MDATP team.

**Comment by alexverboon** [comment]
Hi NIcholas, thanks for confirming, i was already banging my head against a wall the other night :-). By the way I noticed some other issues with the current playbook, that i fixed, it's around timing, it takes a little bit from submitting from Azure sentinel playbook (logicapp) till the API in defender, so i added a little dealy to the flow. Please let me know when the GET/POST issue is solved , then i will try again and when fixed, submit my playbook to the repo.

**Comment by dicolanl** [comment]
@alexverboon sent to MDATP team.  They said should be fixed in like 3 weeks.  We will leave this open and check back then.

**Comment by alexverboon** [comment]
Okay, great thanks for the feedack, really appreciated, I add this task to my backlog then to implement later.

**Comment by alexverboon** [comment]
Let me know when this is resolved, happy to test and provide feedback

**Comment by dicolanl** [comment]
@alexverboon  This Fix should be deployed this week.

**Comment by a-balde** [comment]
Was a fix deployed for retrieving this download URI ?
