### ISSUE TITLE
Doubt about using Codeless with Session authType

### ISSUE THREAD

**Issue by cupello** [Azure/Azure-Sentinel#5405]
Hello people!

I need to login in an application and get the session id cookie to work with their API (yes... not good). I was trying to do something like this:

"pollingConfig": {
    ...
    "auth": {
        "authType": "Session",
        "IsPostPayloadJson": true,
        "SessionLoginRequestUri": "https://{{placeHolder1}}:443/login.html",
        "QueryParameters": "{'username': '{{placeHolder2}}', 'password': '{{placeHolder3}}'}",
        "SessionIdName": "SESSIONID"
    }

But no success yet... Could anyone tell me if this is possible and provide some examples?

Thanks in advance.

**Comment by v-rbajaj** [comment]
To log in to an application and obtain the session ID cookie, you will typically need to follow these steps:

1. Open the login page of the application in your web browser.
2. Enter your login credentials (e.g., username and password).
3. Submit the login form.
4. Check if the application returns a session ID cookie in the HTTP response headers.
If the application returns a session ID cookie, you can extract the value of the cookie and use it in your subsequent API requests.
Example:
import requests

# Set up the login data
login_data = {
    'username': 'your_username',
    'password': 'your_password'
}

# Send the login request
login_url = 'https://example.com/login'
response = requests.post(login_url, data=login_data)

# Check if the session ID cookie was returned
if 'sessionid' in response.cookies:
    # Extract the value of the session ID cookie
    session_id = response.cookies['sessionid']
    print(f'Session ID: {session_id}')
else:
    print('Login failed')

**Comment by v-rbajaj** [comment]
Since we have not received a response in the last 5 days, we are closing your issue https://github.com/Azure/Azure-Sentinel/issues/5405 as per our standard operating procedures. If you still need support for this issue, feel free to re-open at any time. Thank you for your co-operation.
