### ISSUE TITLE
Events not populating in Incident/Alert

### ISSUE THREAD

**Issue by Ziy-sws** [Azure/Azure-Sentinel#545]
![image](https://user-images.githubusercontent.com/52692970/77397807-f592d800-6dae-11ea-9b73-c0bf9a59a46d.png)

Good Day

My alarms are appearing in this manner this morning, is there anything i can do to fix it?

**Comment by preetikr** [comment]
@Ziy-sws - Please file a support ticket with detailed repro for getting this issue fixed. Refer to https://azure.microsoft.com/en-us/support/options/ for filing a support ticket.

**Comment by Ziy-sws** [comment]
Hi

Its resolved now, running the query manually showed the results and the next day events populated as normal
