### ISSUE TITLE
$null is no longer accepted to mean "make no change"

### ISSUE THREAD

**Issue by YSSecurity** [Azure/Azure-Sentinel#5456]
**Describe the bug**
Line 284: $null value is no longer accepted to mean "keep current values" and API call throws an error. Script returns to the Continue or exit prompt.

**To Reproduce**
1. Run current script as is selecting at least one table
2. Provide a total storage time in days
3. PowerShell will throw an error 
4. The script will continue to the Continue or Exit prompt and when selected continue and table data is returned, no change was done to the table selected previously.

**Expected behavior**
No error in the API call resulting in updated table properties.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10.0.19043.1237

**Additional context**
Replacing $null in the code with the hardcoded value allows the script to run successfully. Ideally a variable shall be used.
Sorry, did not have enough time to identify appropriate variable.
Thanks for the script! Very handy!

**Comment by YSSecurity** [comment]
Just used the most recent version again and looks like the problem is still there (https://github.com/Azure/Azure-Sentinel/blob/master/Tools/Archive-Log-Tool/ArchiveLogsTool-PowerShell/Configure-Long-Term-Retention.ps1) line 292.
Script fails as is, but works if '$null' is replaced by '90'.

**Comment by v-rbajaj** [comment]
We wanted to check on the status of Issue https://github.com/Azure/Azure-Sentinel/issues/5456. The issue is pending for more than expected days. Please let us know if you need any assistance to review this Issue. As per our standard operating procedures if no response is received in the next 7 business days, we will close this Issue. Thank you for your cooperation.

**Comment by v-vdixit** [comment]
Since we have not received a response in the last 7 days, we are closing your issue as per our standard operating procedures. If you still need support for this issue, feel free to re-open at any time. Thank you for your co-operation.
