### ISSUE TITLE
Failed to create alert rule Azure Portal Signin from another Azure Tenant

### ISSUE THREAD

**Issue by Rahulg485** [Azure/Azure-Sentinel#5483]
Hello Team,

I am facing below while creating the Analytic rule in Microsoft Sentinel. I have tried in multiple Log Analytics Workspace and regions still facing the same issue. Can someone please help me on this. Thanks in advance.

Below is the error screenshot for reference.

![image](https://user-images.githubusercontent.com/108336794/176159792-1edff11e-0124-4f9d-b28f-564d14b4b8b1.png)

**Comment by tatecksi** [comment]
Hi @Rahulg485,

Looks like your file name is not valid anymore. The latest one should be ServiceTags_Public_20220627.json.
Please try again with the updated URL (it worked on my end).

Thanks

**Comment by Rahulg485** [comment]
Hi Jeremy,

Thanks for the quick help, I have modified the same in KQL query in my test lab which worked 😊.  Will reach you in case any help needed.

Regards,
Rahul Gattadi
Consultant | Microsoft Services
***@***.******@***.***>

[A close up of a logo  Description automatically generated]

**Comment by Rahulg485** [comment]
Hi Jeremy,

We are trying to create the rule in Prod, however we see storage path doesn’t exist even after changing it to ServiceTags_Public_20220627.json. Coud you please check and provide us the updated storage link?

***@***.***

Regards,
Rahul Gattadi
Consultant | Microsoft Services
***@***.******@***.***>

[A close up of a logo  Description automatically generated]

From: RAHUL GATTADI
Sent: Friday, July 1, 2022 3:25 PM
To: Azure/Azure-Sentinel ***@***.***>; Azure/Azure-Sentinel ***@***.***>
Cc: Mention ***@***.***>; Sanchu Sankar ***@***.***>; Vinayak Latthe ***@***.***>; Benjamin Kovacevic ***@***.***>
Subject: RE: [Azure/Azure-Sentinel] Failed to create alert rule Azure Portal Signin from another Azure Tenant (Issue #5483)

Hi Jeremy,

Thanks for the quick help, I have modified the same in KQL query in my test lab which worked 😊.  Will reach you in case any help needed.

Regards,
Rahul Gattadi
Consultant | Microsoft Services
***@***.******@***.***>

[A close up of a logo  Description automatically generated]

**Comment by Rahulg485** [comment]
Hi Jeremy and Team,

Could you please help us on this? We need to enable the rule on client Production.


Regards,
Rahul Gattadi
Consultant | Microsoft Services
***@***.******@***.***>

[A close up of a logo  Description automatically generated]

From: RAHUL GATTADI
Sent: Saturday, September 3, 2022 3:49 AM
To: 'Azure/Azure-Sentinel' ***@***.***>; 'Azure/Azure-Sentinel' ***@***.***>
Cc: 'Mention' ***@***.***>; Sanchu Sankar ***@***.***>; Vinayak Latthe ***@***.***>; Benjamin Kovacevic ***@***.***>; Madhur Shukla ***@***.***>
Subject: RE: [Azure/Azure-Sentinel] Failed to create alert rule Azure Portal Signin from another Azure Tenant (Issue #5483)

Hi Jeremy,

We are trying to create the rule in Prod, however we see storage path doesn’t exist even after changing it to ServiceTags_Public_20220627.json. Coud you please check and provide us the updated storage link?

***@***.***

Regards,
Rahul Gattadi
Consultant | Microsoft Services
***@***.******@***.***>

[A close up of a logo  Description automatically generated]

From: RAHUL GATTADI
Sent: Friday, July 1, 2022 3:25 PM
To: Azure/Azure-Sentinel ***@***.******@***.***>>; Azure/Azure-Sentinel ***@***.******@***.***>>
Cc: Mention ***@***.******@***.***>>; Sanchu Sankar ***@***.******@***.***>>; Vinayak Latthe ***@***.******@***.***>>; Benjamin Kovacevic ***@***.******@***.***>>
Subject: RE: [Azure/Azure-Sentinel] Failed to create alert rule Azure Portal Signin from another Azure Tenant (Issue #5483)

Hi Jeremy,

Thanks for the quick help, I have modified the same in KQL query in my test lab which worked 😊.  Will reach you in case any help needed.

Regards,
Rahul Gattadi
Consultant | Microsoft Services
***@***.******@***.***>

[A close up of a logo  Description automatically generated]

**Comment by raldponsua** [comment]
> Hi Jeremy and Team, Could you please help us on this? We need to enable the rule on client Production. Regards, Rahul Gattadi Consultant | Microsoft Services ***@***.******@***.***> [A close up of a logo Description automatically generated] From: RAHUL GATTADI Sent: Saturday, September 3, 2022 3:49 AM To: 'Azure/Azure-Sentinel' ***@***.***>; 'Azure/Azure-Sentinel' ***@***.***> Cc: 'Mention' ***@***.***>; Sanchu Sankar ***@***.***>; Vinayak Latthe ***@***.***>; Benjamin Kovacevic ***@***.***>; Madhur Shukla ***@***.***> Subject: RE: [Azure/Azure-Sentinel] Failed to create alert rule Azure Portal Signin from another Azure Tenant (Issue #5483) Hi Jeremy, We are trying to create the rule in Prod, however we see storage path doesn’t exist even after changing it to ServiceTags_Public_20220627.json. Coud you please check and provide us the updated storage link? ***@***.*** Regards, Rahul Gattadi Consultant | Microsoft Services ***@***.******@***.***> [A close up of a logo Description automatically generated] From: RAHUL GATTADI Sent: Friday, July 1, 2022 3:25 PM To: Azure/Azure-Sentinel ***@***.******@***.***>>; Azure/Azure-Sentinel ***@***.******@***.***>> Cc: Mention ***@***.******@***.***>>; Sanchu Sankar ***@***.******@***.***>>; Vinayak Latthe ***@***.******@***.***>>; Benjamin Kovacevic ***@***.******@***.***>> Subject: RE: [Azure/Azure-Sentinel] Failed to create alert rule Azure Portal Signin from another Azure Tenant (Issue #5483) Hi Jeremy, Thanks for the quick help, I have modified the same in KQL query in my test lab which worked 😊. Will reach you in case any help needed. Regards, Rahul Gattadi Consultant | Microsoft Services ***@***.******@***.***> [A close up of a logo Description automatically generated] From: Jeremy Tan ***@***.******@***.***>> Sent: Friday, July 1, 2022 2:27 PM To: Azure/Azure-Sentinel ***@***.******@***.***>> Cc: RAHUL GATTADI ***@***.******@***.***>>; Mention ***@***.******@***.***>> Subject: Re: [Azure/Azure-Sentinel] Failed to create alert rule Azure Portal Signin from another Azure Tenant (Issue #5483) Hi @Rahulg485<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FRahulg485&data=05%7C01%7Crahulgattadi%40microsoft.com%7Ceff4ef85c4be4e4a6c6108da5b3fb9be%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637922626545592449%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=dZkigewDgwl9QPvNZQhhFSoGXXgDp0y84H6obwykirM%3D&reserved=0>, Looks like your file name is not valid anymore. The latest one should be ServiceTags_Public_20220627.json. Please try again with the updated URL (it worked on my end). Thanks — Reply to this email directly, view it on GitHub<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FAzure%2FAzure-Sentinel%2Fissues%2F5483%23issuecomment-1172109504&data=05%7C01%7Crahulgattadi%40microsoft.com%7Ceff4ef85c4be4e4a6c6108da5b3fb9be%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637922626545592449%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=GMdXbw%2F0fhe12rZ9eLHXyrBpBv4QmoB9tF9mPIKqQvg%3D&reserved=0>, or unsubscribe<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAZ2RNGUIQVPSZGMCWBYN3G3VR2XHRANCNFSM52BWDSDQ&data=05%7C01%7Crahulgattadi%40microsoft.com%7Ceff4ef85c4be4e4a6c6108da5b3fb9be%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637922626545592449%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=Vc0C%2FsyLzo402tX3Z96zJgGpgRmXGeAgKXeKKcDpWhs%3D&reserved=0>. You are receiving this because you were mentioned.Message ID: ***@***.******@***.***>>

@Rahulg485 this should be the updated one ServiceTags_Public_20220905.json 
From this link: https://azservicetags.azurewebsites.net/
