### ISSUE TITLE
OfficeActivity NRT rule not possible to filter by column Operation

### ISSUE THREAD

**Issue by ep3p** [Azure/Azure-Sentinel#5490]
**Describe the bug**
It is not possible to make a NRT rule that filters the column ```Operation``` of table ```OfficeActivity```.

**To Reproduce**
1. Create a new NRT rule.
2. Go to "Set rule logic".
3. Paste ```OfficeActivity
| where Operation == "FileDownloaded"```
4. Error ```NRT queries cannot use joins or unions, or query more than one table.``` appears.

**Expected behavior**
Filtering on ```Operation``` column does not seem to indicate we are querying more than one table, other columns may be fine to filter. I think Samik Roy has encountered the same error when trying to create NRT versions of scheduled rules (detections).

**Screenshots**
![image](https://user-images.githubusercontent.com/2527990/176246806-0fd92d17-daae-4b4a-8e60-1a69b7e31097.png)

I am trying to create a NRT that specifically filters "FileDownloaded" events, please, do you know if there is a previous filter or something so this query works as NRT?

Thank you for attending me.

**Comment by tatecksi** [comment]
Hi @ep3p,

This will be fixed in the future. In the mean time, kindly use the below query as workaround:

```
OfficeActivity
| where * == "FileDownloaded"
```

**Comment by ep3p** [comment]
Thank you very much @tatecksi

I will wait, I need to use Operation column with ```has_any``` ```in``` operators.

**Comment by c-zuc** [comment]
Hi everyone,
seems that the bug is not limited to any particular table or column, writing the word `Operation` anywhere in an NRT query will result in the error. I found out that the same thing happens with the word `Event` too:

![image](https://user-images.githubusercontent.com/107475442/190999338-dde89d88-da80-4225-8f98-902611800be2.png)

**Comment by ep3p** [comment]
Thank you very much @c-zuc . I didn't realize the parser just checked for strings.

I think currently we can circumvent this problem using:
```
OfficeActivity
| distinct ['Oper''ation']
```

![image](https://user-images.githubusercontent.com/2527990/192501141-1a8cd12a-dc7d-49fd-9ec6-eefef086c3d2.png)
