### ISSUE TITLE
Azure Sentinel Learning - Module 2 Data Connectors

### ISSUE THREAD

**Issue by cwoods1482** [Azure/Azure-Sentinel#5493]
I am following this guide. https://github.com/Azure/Azure-Sentinel/blob/master/Solutions/Training/Azure-Sentinel-Training-Lab/Modules/Module-2-Data-Connectors.md

When selecting the Parameters of the Primary Log Analytics Workspace I get this error "The resource type 'workspaces' could not be found in the namespace 'Microsoft.OperationalInsights' for api version '2022-09-01-privatepreview'. The supported api-versions are '2015-03-20,2015-11-01-preview,2017-01-01-preview,2017-03-03-preview,2017-03-15-preview,2017-04-26-preview,2020-03-01-preview,2020-08-01,2020-10-01,2021-06-01,2021-03-01-privatepreview,2021-12-01-preview'."

![image](https://user-images.githubusercontent.com/108353634/176402870-04f75197-9536-449e-88ce-80d99f0833e9.png)

**Comment by prathi5** [comment]
I am also having same issue..
The resource type 'workspaces' could not be found in the namespace 'Microsoft.OperationalInsights' for api version '2022-09-01-privatepreview'. The supported api-versions are '2015-03-20,2015-11-01-preview,2017-01-01-preview,2017-03-03-preview,2017-03-15-preview,2017-04-26-preview,2020-03-01-preview,2020-08-01,2020-10-01,2021-06-01,2021-03-01-privatepreview,2021-12-01-preview'.

**Comment by prathi5** [comment]
I haev tested again, seems the issue is fixed 👍 :-)
Thanks @javiersoriano

**Comment by cwoods1482** [comment]
Thanks very much. All resolved.
