### ISSUE TITLE
Azure Sentinel Workbook Displays Old Data Maybe Due To Caching

### ISSUE THREAD

**Issue by utsavpatel51** [Azure/Azure-Sentinel#550]
I have created a KQL and using that plotted a Tile view in the workbook. The data in the Tile is supposed to change based on the Timerange filter I have added. This is working fine unless new events are received. So let's say I have selected "Last 24 hours" at 12 PM and the count in tile is "2". Now I keep the session idle for a few minutes and at 12:10 PM, a new event arrives. Thereafter when I change the Timerange filter to "Last 5 minutes", I see the new event, but when I again change the Timerange filter to "Last 24 hours", the count still will be "2" instead of "3". 

However, when I refresh the entire web page, the count will be updated. Is there any way to overcome this? I think the results are being cached by Azure and reused, but is there a way to disable this?

**Comment by shainw** [comment]
@utsavpatel51 - Thanks for letting us know and the detailed explanation of what is occurring.  Let me bring it back to some of the PM's on the team and we will see what we can track down.  Thanks, Shain

**Comment by BharathNimmala-MSFT** [comment]
Thanks to John Gardner to help answer this query on [MSDN](https://social.msdn.microsoft.com/Forums/en-US/e1bb873b-089d-4da8-b322-6a4599b88a3e/azure-sentinel-workbook-displays-old-data-due-to-caching?forum=opinsights). 

@utsavpatel51 please review it and circle back for any further queries. 

@shainw FYI

**Comment by utsavpatel51** [comment]
Thanks, I have to refresh the page manually or re-run the query but it seems when I use the [tabs ](https://user-images.githubusercontent.com/26016485/78633865-40891100-78c0-11ea-952f-2bc66b799820.png)refresh button is not working for me.

**Comment by morshabi** [comment]
Hi, thank you for your feedback.
I see that you have also asked this question via MSDN: https://social.msdn.microsoft.com/Forums/en-US/e1bb873b-089d-4da8-b322-6a4599b88a3e/azure-sentinel-workbook-displays-old-data-due-to-caching?forum=opinsights
please let us know if you have any further questions.
