### ISSUE TITLE
Detection IDs are different in repo to those in Sentinel

### ISSUE THREAD

**Issue by LiamCloudGuard** [Azure/Azure-Sentinel#5512]
**Describe the bug**
Within the detections folder in this repository, each yaml file has an ID. This ID is different to the ID assigned when you deploy the alert through Sentinel.

This makes using the Repository (Preview) function for content management very difficult. If you deploy the alert through Sentinel, it will show when a version update is available. However, if you create the alert with the ID in the yaml files, it will not show when an update is available.

**To Reproduce**
1. Deploy 'Authentication Methods Changed for Privileged Account' alert through Sentinel. 
2. The ID assigned when deployed is '24436335-bd9f-452a-9382-f6152049f29f'
3. Go to the part of the repo where this alert is stored: 
https://github.com/Azure/Azure-Sentinel/blob/a02403e37dbecb4f2eb8f67817f62fd17a13bf50/Detections/MultipleDataSources/AuthenticationMethodsChangedforPrivilegedAccount.yaml
4. The ID within the yaml file is '694c91ee-d606-4ba9-928e-405a2dd0ff0f'

NOTE: This is one example, all alerts have the same issue

**Expected behavior**
The IDs should be the same for easy management of version control for each alert within Sentinel

**Comment by kevincaballerox15** [comment]
Hi @LiamCloudGuard, the yaml ID is mapped to the alertRuleTemplateName property of the resource. You can find this when you export the rule and view the json file. The ID you see in the GUI is the reference to the resourceId of the rule in your Sentinel deployment.

I suspect you are using some tool to deploy directly from GitHub or a YAML to JSON converter and it might be stripping the alertRuleTemplateName as that was the case for me.

For your reference, you can't just add the values to the alertRuleTemplateName property if you have already deployed it without the value (yaml template ID). It will error out saying something like "This is an existing resource and was not deployed using a template". Therefore, you will have to re-deploy the resource and make sure it's there.

**Comment by LiamCloudGuard** [comment]
Hi @kevincaballerox15,

I created a script that would pull the alerts from the Azure-Sentinel repo, and convert the yaml files to JSON/ARM templates. Then using the repositories (preview), I connect Sentinel to the new repository containing the new JSON files.

I want the alerts to act as if they were deployed from the GUI as seen in the screenshot below. I assumed this was because the id of the alert was different. 

What steps do I need to take to ensure the alert acts the same as if it was deployed from the GUI?

Many Thank!


<img width="647" alt="Screenshot 2022-10-04 114813" src="https://user-images.githubusercontent.com/90031013/193800672-e45842e3-42e9-41b4-b8cf-b909b72fa513.png">

**Comment by kevincaballerox15** [comment]
@LiamCloudGuard, I would inspect the output of your script that converts yaml to ARM/JSON templates and make sure it doesn't strip out the **alertRuleTemplateName** property in the template. 

A quick way to check this to export a rule that is generated by your yaml to json converter and another for one that is deployed from the GUI.

I suspect that the yaml to JSON converter is stripping out the **alertRuleTemplateName** or having the value as "null"

See example secreenshot for what I mean.

2. is what you need in your JSON template to associate your rule as if it was deployed from the GUI. If it doesn't exist, you need to update your templates to include it to achieve what you want.

<img width="956" alt="image" src="https://user-images.githubusercontent.com/97994670/193815931-7a8d02e1-c815-49b3-8e03-63dc45e2fc5f.png">


If you have already deployed the rule in a sentinel workspace without the **alertRuleTemplateName** defined in the JSON, you would need to delete the rule from the GUI and re-deploy it.

Hope that helps!

**Comment by LiamCloudGuard** [comment]
@kevincaballerox15 

Thank you, that clears things up for me. I appreciate you taking the time to help me with this.
