### ISSUE TITLE
Unisolate MDE playbooks for Alerts and Incidents faulty condition 

### ISSUE THREAD

**Issue by pt0x** [Azure/Azure-Sentinel#5526]
**Describe the bug**
The condition for the unisolate MDE playbooks (alert and incident) is faulty in logic app code.
Details are provided below.

**To Reproduce**
0. Connect MDE to Sentinel
1. Implement (both) playbooks from: https://github.com/Azure/Azure-Sentinel/tree/master/Playbooks/Isolate-MDEMachine
2. Implement (both) playbooks from: https://github.com/Azure/Azure-Sentinel/tree/master/Playbooks/Unisolate-MDEMachine
3. Follow prerequisites after deploying to azure as described
4. Create automation rule - 
5. Trigger: when incident is created -  
6. Conditions: Contains + Create incidents based on MDE and MDC - 
7. And: File Hash Equals = the hashes from https://en.wikipedia.org/wiki/EICAR_test_file
8. Actions: Run Playbook Isolate-MDEMachine-Incident
9. Trigger automation by downloading the EICAR test files on a MDE managed host and wait until Sentinel incident is created and the host is isolated (~15 min).
10. Go to the Sentinel incident and select Actions - Run Playbook - select Unisolate-MDEMachine-incident
11. This will not unisolate the machine.

**Expected behavior**
When running the playbook (step 10) is should unisolate the machine (step 11) :)

**Additional context**

I had to troubleshoot this at a customer. It seems there is an error in the unisolate playbooks (alert and incident). 
When following the steps above, the logic app for unisolating succesfully runs. 

When looking at the logic app runs you see that this is due to the condition being "false". So the logic app simply adds a comment that the device you want to unisolate doesn't have a MDEDeviceID (or MdatpDeviceId). That why the logic app / playbook succeeds, but the machine is still isolated.

The condition looks for the existence of the MdatpDeviceId in found entities that belong to the incident. 
Tue = unisolate + write comment
False = write comment

**Solution**

> This example describes the Incident playbook, the same applies to Alert playbooks though.

- **Isolate-MDEMachine-incident | Working**
line 35
"path": "/api/machines/@{encodeURIComponent(items('For_each')?['additionalData']?['MdatpDeviceId'])}/isolate"
line 88
"@items('For_each')?['additionalData']?['MdatpDeviceId']",

- **Unisolate-MDEMachine-incident | Not Working**
line 34
"path": "/api/machines/@{encodeURIComponent(items('For_each')?['MdatpDeviceId'])}/unisolate"
line 87
"@items('For_each')?['MdatpDeviceId']",      

As you can see, the ['additionalData'] is missing, adding this to the unisolate logic apps fixes the issue.

**Comment by BenjiSec** [comment]
Hi, thanks for raising the issue. Now it is fixed, and PR is submitted. 

https://github.com/Azure/Azure-Sentinel/pull/5541
