### ISSUE TITLE
Get-GeoFromIpAndTagIncident playbook run failure

### ISSUE THREAD

**Issue by sonnyakhere** [Azure/Azure-Sentinel#5544]
The Get-GeoFromIpAndTagIncident playbook keeps returning failure.

After clicking Actions>Run playbook, the playbook doesn't pop up despite linking.
![mod4a](https://user-images.githubusercontent.com/67973894/177214521-b33b3098-aa6f-4af1-9c57-0f4177542188.PNG)

When I view playbook of each alert in the incident, it is visible. However when I run it, it triggers and returns failure.
![mod4b](https://user-images.githubusercontent.com/67973894/177214661-07abab83-b935-4dfe-9553-df67e3d387d4.PNG)

From the screenshot you can see it is enabled, triggers but returns failure.
![mod4c](https://user-images.githubusercontent.com/67973894/177215341-29d5ac67-fb58-484f-82e6-56879f82e1d8.PNG)

I would assistance with resolution or proper troubleshooting steps. Thank you.

**Comment by jing-microsoft** [comment]
Could you go into the specific action that failed in the playbook and provide the error message you get when running this playbook ?

**Comment by sonnyakhere** [comment]
> Could you go into the specific action that failed in the playbook and provide the error message you get when running this playbook ?

This is the error message:
![error code](https://user-images.githubusercontent.com/67973894/178350091-9bc007aa-8713-490e-8805-39cf38e30982.PNG)

**Comment by v-amolpatil** [comment]
Hi @jing-microsoft,Could you please try if you are still getting the same error? 
Also try to click on the "Refresh" icon as shown in below screenshot? 
![image](https://user-images.githubusercontent.com/107389644/218325699-84d8a0fc-d800-448e-9574-de83da6ecb77.png)
Below is the success log:
![image](https://user-images.githubusercontent.com/107389644/218325742-024961ec-3863-4a17-b630-6cdadb6ea8bc.png)

Let us know if you still need assistance on it or we can close the issue if issue doesnt persist.

**Comment by tamer-fpga** [comment]
Hello there, I am actually still having this issue of running "Get-GeoFromIpAndTagIncident" Playbook. It returns failed (Bad Request). When I click on "View run" to troubleshoot the issue, I get a red exclamation mark on the alert - get incident. I click on it and it shows the 400 bad request response code.

**Comment by v-amolpatil** [comment]
@tamer-fpga @sonnyakhere, We have provided a fix few weeks ago and this is now working correctly and also provided the same comment on your another issue #7435. So closing this issue. Feel free to reopen this issue if you still need assistance.

**Comment by Jimnar** [comment]
I'm having the exact same issue as described above. Is the fix in the Microsoft Sentinel Graining Lab Solution at https://azuremarketplace.microsoft.com/en-us/marketplace/apps/azuresentinel.azure-sentinel-solution-azuretraininglab?
