### ISSUE TITLE
Sysmon Parser - 'extend' operator: Failed to resolve scalar expression named '["@Name"]'. 

### ISSUE THREAD

**Issue by ETMRidge** [Azure/Azure-Sentinel#5556]
**Describe the bug**
Using the Sysmon Parser(https://github.com/Azure/Azure-Sentinel/blob/master/Parsers/Sysmon/Sysmon-AllVersions_Parser.txt) to create an analytics rule.  You are presented with the error:
'extend' operator: Failed to resolve scalar expression named '["@Name"]'. 

**To Reproduce**
1. Create the following query in Azure Sentinel as an scheduled analytics rule:
![image](https://user-images.githubusercontent.com/92232253/177513301-574aa094-3ebd-46f5-a72f-02130b9a6277.png)
2.  This will present the error.

**Expected behavior**
No error should occur.

**Screenshots**
![image](https://user-images.githubusercontent.com/92232253/177513600-4befc87b-f52c-4308-b404-fa6bcffc563f.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Firefox
 - Version 102.0

**Additional context**

**Comment by ETMRidge** [comment]
Just to link a similar issue I found raised last year:
https://github.com/Azure/Azure-Sentinel/issues/2200

**Comment by v-spadarthi** [comment]
@WoodellJ : We merged the [PR](#5717)  Could you please let us know still you are facing the issue ?

**Comment by v-spadarthi** [comment]
@WoodellJ : We merged the [PR](https://github.com/Azure/Azure-Sentinel/issues/5556#5717) Could you please let us know still you are facing the issue  or issue got resolved ?

**Comment by v-mchatla** [comment]
Hi @WoodellJ,
We are closing this issue as its already addressed and we are not seeing this issue anymore. Please find the below screenshot for your reference. Please feel free to reopen if you need any further assistance on this.
![image](https://user-images.githubusercontent.com/108806639/211250637-e4241cf8-7ba1-4b63-9aaf-c6c4524689f9.png)
Thanks
