### ISSUE TITLE
createSolution.ps1 doesnt handle custom connector

### ISSUE THREAD

**Issue by dicolanl** [Azure/Azure-Sentinel#5562]
When running createSolution.ps1 to create a solution, it leaves a null field in the createUiDefintion.json if the playbook is not a playbook but is a custom connector.

On line 312, it uses $playbookName for the label.  $playbookName comes from line 270 which gets the name from the template if it has a "PlaybookName" or "Playbook Name" parameter.  A custom connector would not have a playbook name parameter in the ARM template.

**To Reproduce**
1. run createSolution.ps1 on a solution that has a custom connector in the Playbooks folder in the solution.

**Comment by dicolanl** [comment]
Hi @v-rbajaj 
No one ever fixed this, its still an issue.

**Comment by v-vdixit** [comment]
Hi @dicolanl can you please confirm if you have a parameter with alias '"CustomConnectorName" in azuredeploy file of custom connector and same should be present in associated playbooks' parameters too, the script works fine if these requirements are met, please let us know if you're looking for something else, thanks!

**Comment by v-vdixit** [comment]
Gentle Reminder: We are waiting for your response on this issue. If you still need to keep this issue active, please respond on it in the next 2 days. If we don't receive response, we will be closing this issue as per our standard procedures, thanks!

**Comment by v-vdixit** [comment]
Since we have not received a response in the last 5 days, we are closing your issue as per our standard operating procedures. If you still need support for this issue, feel free to re-open at any time. Thank you for your co-operation
