### ISSUE TITLE
UpdateCloudIPs

### ISSUE THREAD

**Issue by gmccauley** [Azure/Azure-Sentinel#5574]
**Describe the bug**
The Update Cloud IPs Watchlist Function is failing for AzureIPs and does not create the watchlist.

**Error Message**
`2022-07-07T20:25:52.229 [Error] ERROR: Response status code does not indicate success: 400 (Bad Request).Exception             :Type       : Microsoft.PowerShell.Commands.HttpResponseExceptionResponse   : StatusCode: 400, ReasonPhrase: 'Bad Request', Version: 1.1, Content: System.Net.Http.HttpConnectionResponseContent, Headers:{Cache-Control: no-cachePragma: no-cacheServer: Kestrelx-ms-ratelimit-remaining-subscription-writes: 1199x-ms-request-id: 74775aaf-c5dd-482d-8326-cb7ad3a41948x-ms-correlation-request-id: 74775aaf-c5dd-482d-8326-cb7ad3a41948x-ms-routing-request-id: SOUTHCENTRALUS:20220707T202552Z:74775aaf-c5dd-482d-8326-cb7ad3a41948Strict-Transport-Security: max-age=31536000; includeSubDomainsX-Content-Type-Options: nosniffDate: Thu, 07 Jul 2022 20:25:51 GMTContent-Length: 142Content-Type: application/json; charset=utf-8Expires: -1}TargetSite :Name          : ThrowTerminatingErrorDeclaringType : System.Management.Automation.MshCommandRuntime, System.Management.Automation, Version=7.0.9.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35MemberType    : MethodModule        : System.Management.Automation.dllStackTrace :at System.Management.Automation.MshCommandRuntime.ThrowTerminatingError(ErrorRecord errorRecord)Message    : Response status code does not indicate success: 400 (Bad Request).Source     : System.Management.AutomationHResult    : -2146233088TargetObject          : Method: PUT, RequestUri: 'https://management.azure.com//subscriptions/8a46f981-c864-48b6-8ef6-a114eddadf34/resourceGroups/sentinel/providers/Microsoft.OperationalInsights/workspaces/Sentinel/providers/Microsoft.SecurityInsights/watchlists/AzureIPRanges?api-version=2021-03-01-preview', Version: 1.1, Content: System.Net.Http.ByteArrayContent, Headers:{Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsIng1dCI6IjJaUXBKM1VwYmpBWVhZR2FYRUpsOGxWMFRPSSIsImtpZCI6IjJaUXBKM1VwYmpBWVhZR2FYRUpsOGxWMFRPSSJ9.eyJhdWQiOiJodHRwczovL21hbmFnZW1lbnQuYXp1cmUuY29tLyIsImlzcyI6Imh0dHBzOi8vc3RzLndpbmRvd3MubmV0LzEzZWVkYWRlLTcyMDItNGNhZS04YmRlLTA5YjRiMzBiOGE2Yy8iLCJpYXQiOjE2NTcyMjQ2NjksIm5iZiI6MTY1NzIyNDY2OSwiZXhwIjoxNjU3MzExMzY5LCJhaW8iOiJFMlpnWU5EYktYMlI5L0oyWm5WdGMzblBUTFYwQUE9PSIsImFwcGlkIjoiOTkzNWIyNjItYmE5Zi00NmJmLWE1MTItMjBhZTcyMGMwNzhmIiwiYXBwaWRhY3IiOiIyIiwiaWRwIjoiaHR0cHM6Ly9zdHMud2luZG93cy5uZXQvMTNlZWRhZGUtNzIwMi00Y2FlLThiZGUtMDliNGIzMGI4YTZjLyIsImlkdHlwIjoiYXBwIiwib2lkIjoiMGRkOGJmODctMjU1OS00Nzc2LWJmY2EtZTg5N2NiNDc0ZDEwIiwicmgiOiIwLkFTa0EzdHJ1RXdKeXJreUwzZ20wc3d1S2JFWklmM2tBdXRkUHVrUGF3ZmoyTUJNcEFBQS4iLCJzdWIiOiIwZGQ4YmY4Ny0yNTU5LTQ3NzYtYmZjYS1lODk3Y2I0NzRkMTAiLCJ0aWQiOiIxM2VlZGFkZS03MjAyLTRjYWUtOGJkZS0wOWI0YjMwYjhhNmMiLCJ1dGkiOiJXSmc4NDg0MHhFT0NXaXN5RDNxakFBIiwidmVyIjoiMS4wIiwieG1zX21pcmlkIjoiL3N1YnNjcmlwdGlvbnMvOGE0NmY5ODEtYzg2NC00OGI2LThlZjYtYTExNGVkZGFkZjM0L3Jlc291cmNlZ3JvdXBzL1NlbnRpbmVsL3Byb3ZpZGVycy9NaWNyb3NvZnQuV2ViL3NpdGVzL3VwZGF0ZWNsb3VkaXBzN2JxNHVjNHZ2NHE2eSIsInhtc190Y2R0IjoiMTQ5NTQ5NzE0OSJ9.Dip66aO9596qTIvS4eoLX2RlW7mHXFlMsDwzYzILEBKQ1W0ywj7vMzJFAwi_KswV0E7Yvmae_qTmCedsDeqSHe7awX5o7MqYP0HZ87yDE6s1WMNMIPav77MBcbOS9Py3PHbUxp7UzOpNgKoWDlw1yRPVPcfNcDFWjdXSvZ_V4x4UmI9ZOuxC_NyJ3wtaWCsOe-et5GQWzkYmltgNYVEoU7ljCOswY9hitglsI7lpQeeOUh8GyzLe0bCtpiuME51bESj2YAbNMh9y8xIUzuB37Zfzknf5ML5C_cLleq9OUNGsl8v7HlldVzrUH-K_wJIe3bvW_DmR2D0KEpacm2BVHwUser-Agent: Mozilla/5.0User-Agent: (Windows NT 10.0; Microsoft Windows 10.0.14393; en-US)User-Agent: PowerShell/7.0.9Content-Length: 329Content-Type: application/json}CategoryInfo          : InvalidOperation: (Method: PUT, Reques…application/json}:HttpRequestMessage) [Invoke-RestMethod], HttpResponseExceptionFullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeRestMethodCommandErrorDetails          : {"error":{"code":"400","message":"Invalid csv content : no watchlist items found in the provided rawContent !"}}InvocationInfo        :MyCommand        : Invoke-RestMethodScriptLineNumber : 482OffsetInLine     : 21HistoryId        : 1ScriptName       : C:\home\site\wwwroot\UpdateCloudIPs\run.ps1Line             : $response = Invoke-RestMethod -Method Put -Headers $requestHeaders -Uri $Uri -Body $bodyPositionMessage  : At C:\home\site\wwwroot\UpdateCloudIPs\run.ps1:482 char:21+ … $response = Invoke-RestMethod -Method Put -Headers $requestHeaders -U …+               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~PSScriptRoot     : C:\home\site\wwwroot\UpdateCloudIPsPSCommandPath    : C:\home\site\wwwroot\UpdateCloudIPs\run.ps1InvocationName   : Invoke-RestMethodCommandOrigin    : InternalScriptStackTrace      : at <ScriptBlock>, C:\home\site\wwwroot\UpdateCloudIPs\run.ps1: line 482Microsoft.Azure.WebJobs.Script.Workers.Rpc.RpcException : Result: ERROR: Response status code does not indicate success: 400 (Bad Request).Exception             :Type       : Microsoft.PowerShell.Commands.HttpResponseExceptionResponse   : StatusCode: 400, ReasonPhrase: 'Bad Request', Version: 1.1, Content: System.Net.Http.HttpConnectionResponseContent, Headers:{Cache-Control: no-cachePragma: no-cacheServer: Kestrelx-ms-ratelimit-remaining-subscription-writes: 1199x-ms-request-id: 74775aaf-c5dd-482d-8326-cb7ad3a41948x-ms-correlation-request-id: 74775aaf-c5dd-482d-8326-cb7ad3a41948x-ms-routing-request-id: SOUTHCENTRALUS:20220707T202552Z:74775aaf-c5dd-482d-8326-cb7ad3a41948Strict-Transport-Security: max-age=31536000; includeSubDomainsX-Content-Type-Options: nosniffDate: Thu, 07 Jul 2022 20:25:51 GMTContent-Length: 142Content-Type: application/json; charset=utf-8Expires: -1}TargetSite :Name          : ThrowTerminatingErrorDeclaringType : System.Management.Automation.MshCommandRuntime, System.Management.Automation, Version=7.0.9.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35MemberType    : MethodModule        : System.Management.Automation.dllStackTrace :at System.Management.Automation.MshCommandRuntime.ThrowTerminatingError(ErrorRecord errorRecord)Message    : Response status code does not indicate success: 400 (Bad Request).Source     : System.Management.AutomationHResult    : -2146233088TargetObject          : Method: PUT, RequestUri: 'https://management.azure.com//subscriptions/8a46f981-c864-48b6-8ef6-a114eddadf34/resourceGroups/sentinel/providers/Microsoft.OperationalInsights/workspaces/Sentinel/providers/Microsoft.SecurityInsights/watchlists/AzureIPRanges?api-version=2021-03-01-preview', Version: 1.1, Content: System.Net.Http.ByteArrayContent, Headers:{Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsIng1dCI6IjJaUXBKM1VwYmpBWVhZR2FYRUpsOGxWMFRPSSIsImtpZCI6IjJaUXBKM1VwYmpBWVhZR2FYRUpsOGxWMFRPSSJ9.eyJhdWQiOiJodHRwczovL21hbmFnZW1lbnQuYXp1cmUuY29tLyIsImlzcyI6Imh0dHBzOi8vc3RzLndpbmRvd3MubmV0LzEzZWVkYWRlLTcyMDItNGNhZS04YmRlLTA5YjRiMzBiOGE2Yy8iLCJpYXQiOjE2NTcyMjQ2NjksIm5iZiI6MTY1NzIyNDY2OSwiZXhwIjoxNjU3MzExMzY5LCJhaW8iOiJFMlpnWU5EYktYMlI5L0oyWm5WdGMzblBUTFYwQUE9PSIsImFwcGlkIjoiOTkzNWIyNjItYmE5Zi00NmJmLWE1MTItMjBhZTcyMGMwNzhmIiwiYXBwaWRhY3IiOiIyIiwiaWRwIjoiaHR0cHM6Ly9zdHMud2luZG93cy5uZXQvMTNlZWRhZGUtNzIwMi00Y2FlLThiZGUtMDliNGIzMGI4YTZjLyIsImlkdHlwIjoiYXBwIiwib2lkIjoiMGRkOGJmODctMjU1OS00Nzc2LWJmY2EtZTg5N2NiNDc0ZDEwIiwicmgiOiIwLkFTa0EzdHJ1RXdKeXJreUwzZ20wc3d1S2JFWklmM2tBdXRkUHVrUGF3ZmoyTUJNcEFBQS4iLCJzdWIiOiIwZGQ4YmY4Ny0yNTU5LTQ3NzYtYmZjYS1lODk3Y2I0NzRkMTAiLCJ0aWQiOiIxM2VlZGFkZS03MjAyLTRjYWUtOGJkZS0wOWI0YjMwYjhhNmMiLCJ1dGkiOiJXSmc4NDg0MHhFT0NXaXN5RDNxakFBIiwidmVyIjoiMS4wIiwieG1zX21pcmlkIjoiL3N1YnNjcmlwdGlvbnMvOGE0NmY5ODEtYzg2NC00OGI2LThlZjYtYTExNGVkZGFkZjM0L3Jlc291cmNlZ3JvdXBzL1NlbnRpbmVsL3Byb3ZpZGVycy9NaWNyb3NvZnQuV2ViL3NpdGVzL3VwZGF0ZWNsb3VkaXBzN2JxNHVjNHZ2NHE2eSIsInhtc190Y2R0IjoiMTQ5NTQ5NzE0OSJ9.Dip66aO9596qTIvS4eoLX2RlW7mHXFlMsDwzYzILEBKQ1W0ywj7vMzJFAwi_KswV0E7Yvmae_qTmCedsDeqSHe7awX5o7MqYP0HZ87yDE6s1WMNMIPav77MBcbOS9Py3PHbUxp7UzOpNgKoWDlw1yRPVPcfNcDFWjdXSvZ_V4x4UmI9ZOuxC_NyJ3wtaWCsOe-et5GQWzkYmltgNYVEoU7ljCOswY9hitglsI7lpQeeOUh8GyzLe0bCtpiuME51bESj2YAbNMh9y8xIUzuB37Zfzknf5ML5C_cLleq9OUNGsl8v7HlldVzrUH-K_wJIe3bvW_DmR2D0KEpacm2BVHwUser-Agent: Mozilla/5.0User-Agent: (Windows NT 10.0; Microsoft Windows 10.0.14393; en-US)User-Agent: PowerShell/7.0.9Content-Length: 329Content-Type: application/json}CategoryInfo          : InvalidOperation: (Method: PUT, Reques…application/json}:HttpRequestMessage) [Invoke-RestMethod], HttpResponseExceptionFullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeRestMethodCommandErrorDetails          : {"error":{"code":"400","message":"Invalid csv content : no watchlist items found in the provided rawContent !"}}InvocationInfo        :MyCommand        : Invoke-RestMethodScriptLineNumber : 482OffsetInLine     : 21HistoryId        : 1ScriptName       : C:\home\site\wwwroot\UpdateCloudIPs\run.ps1Line             : $response = Invoke-RestMethod -Method Put -Headers $requestHeaders -Uri $Uri -Body $bodyPositionMessage  : At C:\home\site\wwwroot\UpdateCloudIPs\run.ps1:482 char:21+ … $response = Invoke-RestMethod -Method Put -Headers $requestHeaders -U …+               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~PSScriptRoot     : C:\home\site\wwwroot\UpdateCloudIPsPSCommandPath    : C:\home\site\wwwroot\UpdateCloudIPs\run.ps1InvocationName   : Invoke-RestMethodCommandOrigin    : InternalScriptStackTrace      : at <ScriptBlock>, C:\home\site\wwwroot\UpdateCloudIPs\run.ps1: line 482Exception: Response status code does not indicate success: 400 (Bad Request).Stack:    at System.Management.Automation.MshCommandRuntime.ThrowTerminatingError(ErrorRecord errorRecord)`

**Comment by jing-microsoft** [comment]
Could you please provide a bit more context so I can try to replicate the issue. A 400 response indicates a bad request and I want to see what the request has.

**Comment by gmccauley** [comment]
> Could you please provide a bit more context so I can try to replicate the issue. A 400 response indicates a bad request and I want to see what the request has.

Not sure what context you want....
The Function App was installed from here (https://github.com/Azure/Azure-Sentinel/tree/master/Watchlists/UpdateCloudIPs).
AWS and Azure were selected during deployment.  AWS works, Azure does not.

When looking at the Invocation Details in "Monitor", the below error is displayed.  When trying to manually run from "Code + Test", the original error is displayed.

![image](https://user-images.githubusercontent.com/11580087/178780888-72acdb52-ec56-4674-92fd-cf42f4c2df90.png)

**Comment by v-rbajaj** [comment]
Hi @gmccauley, looking at the provided screenshot of the error message it looks there is a configuration issue as it a Bad request. 
I hope you have followed the readme file and there aren't any trailing whitespaces while providing the details. 
![image](https://user-images.githubusercontent.com/120547590/237017869-85c51ce1-02ec-4355-ac06-e9839aeb45ed.png)

Because we tried deploying the function app on our local and it was working fine.

**Comment by v-rbajaj** [comment]
Gentle Reminder: We are awaiting for your response on this issue. If you still need to keep this issue active please respond on it in the next 2 days .If we don't receive response, we will be close this issue.

**Comment by v-rbajaj** [comment]
Since we have not received a response in the last 5 days, we are closing your issue https://github.com/Azure/Azure-Sentinel/issues/5574 as per our standard operating procedures. If you still need support for this issue, feel free to re-open at any time. Thank you for your co-operation.
