### ISSUE TITLE
Sentinel Incident comment function need to support @-mentions

### ISSUE THREAD

**Issue by dani3lheidemann** [Azure/Azure-Sentinel#5578]
**Describe the solution you'd like**
The comment function within incidents is great, but I would like to be able to address employees directly via "@"-Mentions (like in teams).

![image](https://user-images.githubusercontent.com/40823696/177956691-4d543297-4944-4d00-b8ad-94b697ff6a02.png)

**Describe alternatives you've considered**
An alternative is to create a Microsoft Teams team via Sentinel and discuss it there. But this is a bit to much for me, especially because it would create a team for every incident, which is way to much for us. We would like to have all conversation about the incident directly attached to the issue (like in Azure DevOps User Stories / Tasks).

**Comment by jing-microsoft** [comment]
All comments under an incident will fall under the incident. 

What did you want an @mention to do specifically ? Message the user or add him to an existing teams conversation that was generated by the incident?

**Comment by dani3lheidemann** [comment]
Hi @jing-microsoft,
thank you for your answer! With the @-mention, I mean something comparable to Azure DevOps discussions within user stories / tasks. In Azure DevOps, I'm able to discuss the work to do right in the user story / task and can mention my colleagues right in the discussion panel. When I mention some of my colleagues, they will be notified via email they were mentioned in the task. This is really helpful to keep all conversation/discussion about the task within the task object (see picture below).

![image](https://user-images.githubusercontent.com/40823696/178419291-b38fddc3-3384-41de-b24f-32a1f30c3455.png)

**Comment by v-vdixit** [comment]
Hi @dani3lheidemann we are discussing with the concerned team will update you once we hear back from them, thanks!

**Comment by v-rbajaj** [comment]
Hi @dani3lheidemann, this feature request is a good suggestion and is noted down by the respective team. It will be taken up and will be worked upon in future. However, this will not happen in the coming planning cycle. 
We are closing this issue, feel free to re open in case you have any questions.
