### ISSUE TITLE
Codeless Connector nextPageUrl paging type fails

### ISSUE THREAD

**Issue by panovattack** [Azure/Azure-Sentinel#5611]
``When using the Codeless Cloud Connector for odata REST APIs, the connector fails with error "RES40002 - Invalid Config."  For example:

` "paging": { 
		"pagingType":"NextPageUrl",
		"nextPageUrl":"@odata.nextLink"
},`

This prevents the CCP from pulling data sources from the MSFT graph or M365 Defender APIs when the results are paged. 

When paging type is set to "None" the first page downloads and ingests into Sentinel correctly.

**Comment by panovattack** [comment]
Also tried

`"paging": { 
						"pagingType":"NextPageUrl",
						"nextPageParaName":"@odata.nextLink"
					}`

same result.

**Comment by panovattack** [comment]
Anyone?

**Comment by VulcanPower** [comment]
Same issue here. 
"NextPageUrl" doesn't seem to work at all with @odata.nextlink.

Tried these variations but still doesnt work.
`"nextPageUrl":"$.'@odata.nextLink'"`
`"nextPageUrl":"$.['@odata.nextLink']'"`
`"nextPageUrl":"$.[``@odata.nextLink]'"`

**Comment by panovattack** [comment]
We also tried: 

`"paging": { 
   "pagingType":"NextPageUrl",
   "nextPageParaName":"%40odata.nextLink"
}`

Same result.

**Comment by davi-cruz** [comment]
Hello everyone!

While creating content for demonstration purposes I also started receiving the `RES40002 - Invalid Config` error. 

The API I've built replies with a NextLink as the OData standard, to which I'm also stuck while creating the CCP connector for Microsoft Sentinel.

Initially I thought that the error could be related to my configuration but when I found this issue I also noticed that no connector exists in this repository using the paging style **NextPageUrl**.

Is this a known issue we're looking into @sreedharande @NikTripathi?

Below some details from my testing environment:
- Request received from Sentinel:

```plaintext
2022-09-19T19:43:14Z   [Verbose]   Posting invocation id:50644988-5bfb-4837-9b02-c297479c0f8e on workerId:c0fbebc5-cbfd-4d73-ac94-2813cf450963
2022-09-19T19:43:14Z   [Information]   INFORMATION: Request: {
  "Body": null,
  "Headers": {
    "accept": "application/json",
    "connection": "keep-alive",
    "host": "<redacted>.azurewebsites.net",
    "user-agent": "Scuba",
    "accept-encoding": "gzip, deflate",
    "max-forwards": "9",
    "x-functions-key": "<redacted>",
    "x-arr-log-id": "32b83717-509f-42b9-9238-f3ff0bedf4ec",
    "client-ip": "10.0.0.23:22241",
    "x-site-deployment-id": "<redacted>",
    "was-default-hostname": "<redacted>.azurewebsites.net",
    "x-forwarded-proto": "https",
    "x-appservice-proto": "https",
    "x-arr-ssl": "2048|256|CN=Microsoft Azure TLS Issuing CA 01, O=Microsoft Corporation, C=US|CN=*.azurewebsites.net, O=Microsoft Corporation, L=Redmond, S=WA, C=US",
    "x-forwarded-tlsversion": "1.2",
    "x-forwarded-for": "52.154.254.182:11200",
    "x-original-url": "/api/SampleDataSourceAPIKey",
    "x-waws-unencoded-url": "/api/SampleDataSourceAPIKey",
    "disguised-host": "<redacted>.azurewebsites.net"
  },
  "Method": "GET",
  "Url": "https://<redacted>.azurewebsites.net/api/SampleDataSourceAPIKey",
  "Params": {},
  "Query": {},
  "RawBody": null
}
2022-09-19T19:43:14Z   [Information]   Executed 'Functions.SampleDataSourceAPIKey' (Succeeded, Id=50644988-5bfb-4837-9b02-c297479c0f8e, Duration=82ms)
```

- Response: 
```json
{
  "nextPageLink": "https://<redacted>.azurewebsites.net/api/SampleDataSourceAPIKey?PageNumber=2",
  "hasNextPage": true,
  "status": "OK",
  "messages": [
    {
      "TimeGenerated": "2022-09-19T19:49:00.8897896+00:00",
      "Message": "This sample data was obtained using Codeless Connector Platform in Microsoft Sentinel using APIKey Authentication",
      "Component": "SampleDataSourceAPIKey",
      "TransactionNumber": "aE5xZGNldVN2Zg=="
    },
    {
      "TimeGenerated": "2022-09-19T19:49:00.8924095+00:00",
      "Message": "This sample data was obtained using Codeless Connector Platform in Microsoft Sentinel using APIKey Authentication - Another from the same transaction",
      "Component": "SampleDataSourceAPIKey",
      "TransactionNumber": "QUllRlZtU1B0aQ=="
    }
  ]
}
```

**Comment by v-mchatla** [comment]
Hi @panovattack, 
Thank you for flagging this. Apologies for the delayed response. 
If you still need assistance, please reply here within 5 business days.
Thanks

**Comment by v-dvedak** [comment]
Since we have not received a response in the last 5 days, we are closing your issue #5611 as per our standard operating procedures. If you still need support for this issue, feel free to re-open at any time. Thank you for your co-operation.
