### ISSUE TITLE
Issues with installing & running CEF collector on Linux machine

### ISSUE THREAD

**Issue by lancepreston** [Azure/Azure-Sentinel#563]
**Describe the bug**
Installation is semi-successful, in that many packages are installed, but receive several errors indicating "no such file" or "permission denied".  Installation completes with "_Omsagent restarted successfully_" and "_Installation completed_", and returns a successful return code of 0 (zero).

**To Reproduce**

1. execute installation command:
`# wget https://raw.githubusercontent.com/Azure/Azure-Sentinel/master/DataConnectors/CEF/cef_installer.py&&sudo python cef_installer.py <workspace id> <secret key>`

2.  errors produced
![image](https://user-images.githubusercontent.com/63064363/78279614-676ccf00-74dd-11ea-9f67-4a0da81450e7.png)

3. yet those directories are created with appropriate ownership and permissions:
![image](https://user-images.githubusercontent.com/63064363/78279726-98e59a80-74dd-11ea-93b1-18c72b11d4ea.png)

4. services do not start successfully following install
![image](https://user-images.githubusercontent.com/63064363/78280443-b6ffca80-74de-11ea-84b2-606ce6207934.png)

**Expected behavior**
Log agent installed successfully & sending syslog messages to Azure

**Additional context**
Red Hat Enterprise Linux Server release 7.7
have applied CIS benchmark: CIS_Red_Hat_Enterprise_Linux_7_v2.1.0 (level 1)

*See attached text file containing full installation output and errors
[CEF Installer errors.txt](https://github.com/Azure/Azure-Sentinel/files/4422615/CEF.Installer.errors.txt)

**Comment by preetikr** [comment]
@lancepreston - Please file a support ticket with the repro you have for getting unblocked on this issue. Refer to https://azure.microsoft.com/en-us/support/options/ for filing a support ticket.

**Comment by lancepreston** [comment]
Support ticket #120032424003253 was opened on 3/24/20

**Comment by preetikr** [comment]
Thanks @lancepreston - We'll investigate this and get back.

**Comment by morshabi** [comment]
Hi, this issue was answered via direct ICM to the Azure Sentinel team. To summarize the response, OMSAgent doesn't support hardening with CIS. We are working on fixing the issue with CIS but we don't have ETA.
