### ISSUE TITLE
GreyNoise-IP-CommunityEnrichment Playbook broken

### ISSUE THREAD

**Issue by ml58158** [Azure/Azure-Sentinel#5645]
**Describe the bug**
In the GreyNoise-IP-CommunityEnrichment Playbook, 
The Filter IPs Only step is broken as it doesn't accept the "Entities" dynamic variable.
It gives the error, "The value must be of type array."

**Expected behavior**
Playbook should save.

**Screenshots**
![image](https://user-images.githubusercontent.com/11156002/179238361-ad18cbf1-6034-4fc1-8f11-5bef78112fc7.png)

*

**Comment by BenjiSec** [comment]
@ml58158 - can you please remove Entities and then from Expression add "array(triggerBody()?['object']?['properties']?['relatedEntities'])". Please confirm if issue is solved.

![image](https://user-images.githubusercontent.com/61513156/179753639-abcb0bef-bb85-4255-8908-7629712944fd.png)

**Comment by Lodewyk-Git** [comment]
I implemented this change to both playbooks. It seems like it works as It has added tags to my Incidents.

**Comment by BenjiSec** [comment]
Thanks! Entities is read as Object and that is why it didn't be able to filter array. You can use array() in expression or to initialize variable, type array, and as value add Entities from dynamic content. Then in filter array action, you can call that variable that will be array.

Thanks for confirmation and making PR.
