### ISSUE TITLE
By using Validate the Connector UX "Import button" is not visible on Data connectors configuration tab

### ISSUE THREAD

**Issue by jayeshprajapaticrest** [Azure/Azure-Sentinel#5648]
**Describe the bug**
We need to manually deploy the Data connector and for that we have referred below github link and follow the step no 3 to Validate the Connector UX, But we are unable to see Import button currently.

https://github.com/Azure/Azure-Sentinel/blob/master/DataConnectors/ReadMe.md

**To Reproduce**
Same steps followed in above mentioned github link.

**Expected behavior**
Import button should be visible.

**Screenshots**
Expected result
<img width="700" alt="image" src="https://user-images.githubusercontent.com/98145046/179473521-68ba055a-ac59-4a66-b046-e2ff8dd5eaf5.png">

Current result
<img width="958" alt="image" src="https://user-images.githubusercontent.com/98145046/179473394-a8809a5f-105b-477a-b975-fda815bb2030.png">

**Desktop (please complete the following information):**
 - OS: [Windows 11]
 - Browser : [chrome, Edge]
 - Version [Latest]

**Additional context**
Till last week Import button is visible in portal and we are able to perform Validate the Connector UX task.
But from last Friday we are unable to see Import button in portal.

**Comment by samikroy** [comment]
@jayeshprajapaticrest  - Could you please try this in the preview portal 

https://preview.portal.azure.com/?feature.BringYourOwnConnector=true

The preview image loads here.

![image](https://user-images.githubusercontent.com/20562985/180637678-bdb0e9fb-7c54-4dbd-8f81-52a0581032cf.png)

**Comment by v-spadarthi** [comment]
@jayeshprajapaticrest : We are closing this issue. Now we are able to see the Import functionality by using below link 
https://preview.portal.azure.com/?feature.BringYourOwnConnector=true and modified the data connector readme.md file by "samikroy" as well. Please feel free to reopen the issue with more details if the issue still persists... Thanks!!!
