### ISSUE TITLE
Graph API to list data connectors Sentinel

### ISSUE THREAD

**Issue by guidovbrakel** [Azure/Azure-Sentinel#5654]
Because the data connectors in Sentinel change from time to time, it would be great to have an graph api to list all the api's and use them in Bicep or ARM. For example the defender connector has still the mdatp name which can cause a lot confusion. If I would able to query a list of the data connectors using an api that would be really help.

**Comment by v-mchatla** [comment]
Hi @guidovbrakel,
Hope @jing-microsoft answered to your question and closing this issue as addressed. Please feel free to reopen this issue if you need any further information on this.
Thanks
