### ISSUE TITLE
Cisco Firepower eStreamer Solution Issues with encore.sh script

### ISSUE THREAD

**Issue by thinkdreams** [Azure/Azure-Sentinel#5694]
**Describe the issue**
I'm working on integration of the Cisco eNcore python script, following instructions here:

[https://www.cisco.com/c/en/us/td/docs/security/firepower/670/api/eStreamer_enCore/eStreamereNcoreSentinelOperationsGuide_409.html]

I've got everything installed and working on an already existing OMS server and connected to Azure Log Analytics. The script (encore.sh) is failing during the test run (./encore.sh foreground) with a python error.

When I run the ./encore.sh test - it completes successfully, ensuring that the TLS connection is made correctly.

When I run the ./encore.sh foreground command, the script starts, and then fails on the cef.py python section with an error: NameError: name 'basestring' is not defined.

The worker process then stops the monitor and returns to the command line.

**Expected behavior**
At this point in the installation, it is expected that the encore.sh process should start receiving CEF based logs from our FMC/FTD implementation via the eStreamer integration component.

**Version Information**
Azure OMS server (up to date) running python 3.8.10 on Linux
Cisco FMC/FTD running 7.0.1 code (also current recommended version by Cisco)

**Additional context**
I have an open case with Cisco TAC - but they are stalling on the ticket during research. It looks like based on the python code comments that they wrote the cef.py module - but I'm not sure how far they'll be able to assist on the encore.sh script as they haven't been very forthcoming as to their support for this solution - even though it's a recommended integration component to send log data via CEF to a SIEM

Any help or suggestions would be GREATLY appreciated. No modifications have been made to the python scripts/modules/components of this script - it's all stock based on the aforementioned instructions. Any additional information that is needed I'll be happy to provide.

**Comment by v-mchatla** [comment]
Hi @thinkdreams, 
Thank you for flagging this. Apologies for the delayed response. 
If you still need assistance on this, please reply here within 5 business days.
Thanks

**Comment by v-dvedak** [comment]
Since we have not received a response in the last 5 days, we are closing your issue #5694 as per our standard operating procedures. If you still need support for this issue, feel free to re-open at any time. Thank you for your co-operation.
