### ISSUE TITLE
Create-AnalyticsRulesFromTemplates powershell script executing with errors

### ISSUE THREAD

**Issue by mgijo** [Azure/Azure-Sentinel#5748]
I have been observing multiple errors while trying to execute this PowerShell script - https://github.com/Azure/Azure-Sentinel/blob/master/Tools/PowerShell/Create-AnalyticsRulesFromTemplates/Create-AnalyticsRulesFromTemplates.ps1

During execution it does enable some of the Sentinel Analytic rules and not all for the connected data connectors. Part of the problem could be that on line 41, 42 and 155 of the PowerShell script - the API version seems to be **api-version=2019-01-01-preview** instead of the newly published **api-version=2021-10-01**  as per this documentation https://docs.microsoft.com/en-us/rest/api/securityinsights/stable/alert-rules/create-or-update?tabs=HTTP

Below screenshot with errors during execution:-

![image](https://user-images.githubusercontent.com/83291280/181545151-8cb1ad3a-80a2-46f4-b3bb-cfd9f0c708f8.png)

![image](https://user-images.githubusercontent.com/83291280/181546556-4d767262-5396-4edb-9198-fc42e672c1b0.png)

After execution there are still many analytic rules that isn't enabled. In my scenario I have SecurityEvents and Azure Activity data connector connected. But below screenshot shows some analytic rules not enabled:-

![image](https://user-images.githubusercontent.com/83291280/181548334-d9610ce9-93ea-4efa-922b-06e8a8787e42.png)

**Comment by jing-microsoft** [comment]
I think you may be right and may be a problem with the powershell module not referencing the right api version which is embedded in the powershell module.

**Comment by jing-microsoft** [comment]
> I have been observing multiple errors while trying to execute this PowerShell script - https://github.com/Azure/Azure-Sentinel/blob/master/Tools/PowerShell/Create-AnalyticsRulesFromTemplates/Create-AnalyticsRulesFromTemplates.ps1
> 
> During execution it does enable some of the Sentinel Analytic rules and not all for the connected data connectors. Part of the problem could be that on line 41, 42 and 155 of the PowerShell script - the API version seems to be **api-version=2019-01-01-preview** instead of the newly published **api-version=2021-10-01** as per this documentation https://docs.microsoft.com/en-us/rest/api/securityinsights/stable/alert-rules/create-or-update?tabs=HTTP
> 
> Below screenshot with errors during execution:-
> 
> ![image](https://user-images.githubusercontent.com/83291280/181545151-8cb1ad3a-80a2-46f4-b3bb-cfd9f0c708f8.png)
> 
> ![image](https://user-images.githubusercontent.com/83291280/181546556-4d767262-5396-4edb-9198-fc42e672c1b0.png)
> 
> After execution there are still many analytic rules that isn't enabled. In my scenario I have SecurityEvents and Azure Activity data connector connected. But below screenshot shows some analytic rules not enabled:-
> 
> ![image](https://user-images.githubusercontent.com/83291280/181548334-d9610ce9-93ea-4efa-922b-06e8a8787e42.png)

Could you try changing the URL versions and also removing the EnumasString on like 158 and seeing if this resolves it those errored ones.

**Comment by mgijo** [comment]
Unfortunately, the issue seems to still persists. Thanks for trying to perform few modifications. Below screenshot of the error during execution of the script:-

<img width="933" alt="image" src="https://user-images.githubusercontent.com/83291280/182689169-a6b16762-af7d-485f-8b32-564d05ad2c27.png">

It says there's something wrong with line 178. Which is also called in line 175. Not sure if the variable mentioned here is causing the issue in the script.

<img width="563" alt="image" src="https://user-images.githubusercontent.com/83291280/182689551-a7a56a05-77d4-43a2-afa6-4ac413c9fddf.png">

**Comment by garybushey** [comment]
It appears that those errors are because there is an error in the template's KQL code.  If you look at the templates in question, they will show an error in the KQL code.  The PowerShell script appears to be working correctly, it just cannot create the rules due to the errors in the KQL code.

**Comment by v-amolpatil** [comment]
Hi @mgijo, if you still need assistance, please reply here within 5 business days.
