### ISSUE TITLE
Retrieve data from data warehouse 

### ISSUE THREAD

**Issue by weabey** [Azure/Azure-Sentinel#577]
I am implementing a azure playbook(using logic apps) for incident response. For that, i need to retrieve data from internal data warehouse at some-point of playbook work flow. 
For an instance, retrieve info such as asset owner, hostname, regards to specific IP from internal data warehouse
any-idea on how to connect data-warehouse and query info from there to achieve this in logic apps ?

**Comment by shainw** [comment]
@weabey - I think this may be what you are looking for - https://docs.microsoft.com/en-us/azure/logic-apps/logic-apps-gateway-connection

**Comment by shainw** [comment]
@weabey - going to close this, but if you have further questions please post them.
