### ISSUE TITLE
Unautherized to apply changes - License is invalid error while connecting Office 365 to Sentinel

### ISSUE THREAD

**Issue by fivefq** [Azure/Azure-Sentinel#579]
**Describe the bug**
I am getting "Unautherized to apply changes - License is invalid " error while connecting Office 365 to Sentinel. I have Global Admin access on the tenant and read write/access on the log analytics workspace.

To reproduce:
Go to Azure --> Sentinel Workspace --> Configuration--> Data Connectors --> Office 365 --> Open Connector Page-->  Configruration (Check Exchange and Sharepoint) --> Apply Changes.

![image](https://user-images.githubusercontent.com/23518260/78593148-37178e80-7857-11ea-96bd-fb70c65328cf.png)

**Comment by shainw** [comment]
Thanks for reporting, we are aware of the issue and working on a resolution.  Thanks for your patience.

**Comment by fivefq** [comment]
Looks like it is working now.
