### ISSUE TITLE
SecurityEvents - do both columns Process/ProcessName map to NewProcessName in eventxml

### ISSUE THREAD

**Issue by baselsalam** [Azure/Azure-Sentinel#582]
Can you please clarify if this is indeed the case (both Process/NewProcess columns map to the same NewProcessName field in EventXML),   
or if the column 'Process' maps to something else?     
I don't need you to fix this, I just want to know if I can use these interchangeably.

Why this question:
In TimeSeriesAnomaly-ProcessExecutions, the column 'Process' seems to have the value of 'NewProcessName' from the Event XML   
In malware_in_recyclebin, the column 'NewProcessName' seems to have the value of 'NewProcessName' from the Event XML

In addition, is there a code here where the mapping from EventXML to kusto columns is present?

**Comment by shainw** [comment]
Yes, Process is derived from NewProcessName.  Usage depends on the goal of the query.  I thought we had the schema available publicly, need to check on it.  Thanks for the questions.

**Comment by shainw** [comment]
Closing this, answer is the same in https://github.com/Azure/Azure-Sentinel/issues/587
