### ISSUE TITLE
Typo in "Port scan detected (ASIM Network Session schema)"

### ISSUE THREAD

**Issue by wingcomm** [Azure/Azure-Sentinel#5822]
**Describe the bug**
Typo on https://github.com/Azure/Azure-Sentinel/blob/master/Detections/ASimNetworkSession/PortScan.yaml line 8

**To Reproduce**
View incident

**Expected behavior**
Line 8 should have "ports" not "pots"

**Comment by oshezaf** [comment]
Fixed
