### ISSUE TITLE
Google Workspace Connector ARM template error

### ISSUE THREAD

**Issue by q-andrikoshundi** [Azure/Azure-Sentinel#5849]
When I use the "Deploy to Azure" option to create the Google Workspace (G Suite) connector using an ARM template I get an error stating:
There was an error downloading the template from URI 'https://raw.githubusercontent.com/Azure/Azure-Sentinel/master/DataConnectors/GoogleWorkspaceReports/azuredeploy_Connector_GWorkspaceReportsAPI_AzureFunction.json'.

Steps to reproduce the behaviour:
Go to any Microsoft Sentinel Instance
Go to Data Connectors
Choose the Google Workspace (G Suite) connector and Open Connector Page
Click the Deploy to Azure Button

![image](https://user-images.githubusercontent.com/90905744/183401265-9ee64a21-c72d-4ca7-a22c-4ea766582703.png)

**Comment by v-marimanda** [comment]
We are closing this issue. The Deploy to Azure and function app short link  is updated. Please feel free to reopen the issue with more details if the issue still persist... Thanks!!!
