### ISSUE TITLE
Azure Sentinel Data Connector for VMware Carbon Black missing requirements

### ISSUE THREAD

**Issue by dwlfrth** [Azure/Azure-Sentinel#5866]
When trying to use the VMware Carbon Black Data Connector for Azure Sentinel, either through an Azure Deployment or manuel deployment, I get the following error while running.

`[Error]   EXCEPTION: The script 'run.ps1' cannot be run because the following modules that are specified by the "#requires" statements of the script are missing: AWS.Tools.Common.
`

**To Reproduce**
Simply try to run the Data Connector.

**Comment by v-laanjana** [comment]
@dwlfrth can you please elaborate more how to reproduce  issue?
