### ISSUE TITLE
SecurityEvents - do both Account and TargetAccount map to EventData.TargetUserName ?

### ISSUE THREAD

**Issue by baselsalam** [Azure/Azure-Sentinel#587]
I'm trying to understand the fields used by these 2 SecurityEvent detections:
Detections/gte_6_FailedLogons_10m.yaml - this one refers to both Account and TargetAccount.

Inside of EventXML, these 2 fields don't exist, so they're obviously being mapped from somewhere else. Can you please which fields in EventXML/EventData these 2 columns are derived from.

**Comment by shainw** [comment]
It depends on the Event.  In a 4624/4625 event, the mapping of Account comes from TargetAccount, which further comes from concatenation of TargetDomainName\TargetUserName.  Other events are populated similarly, but it depends on AccountType and the context of the event for what the Account and TargetAccount get populated by.  You can get an idea of what is fields populate Account and TargetAccount by running the below query.  In general, if you are unsure, it is best to go with TargetDomainName+TargetUsername or SubjectDomainName+SubjectUserName depending on the context of the event and what you are attempting to key on.

  let timeframe = 15d;
  SecurityEvent
  | where TimeGenerated >= ago(timeframe)
  //| where EventID !in (4624, 4625, 4688)
  | summarize by EventID, Activity, Account, TargetAccount, AccountType, TargetDomainName, TargetUserName, SubjectDomainName, SubjectUserName

**Comment by baselsalam** [comment]
Thank you so much!

In order to improve RCA/debuggability with the raw event logs, could you please post the mapping logic you use? 
This way when we have a Sentinel detection, we can construct raw debugging queries showing exactly the fields that are relevant.

**Comment by shainw** [comment]
@baselsalam - I discussed this further with some of the PM team.  We have a solution that is in the works, but is not ready to be published at this point as it does not just include SecurityEvents.  I don't have a timeframe for when this will be available as the owner is out on holiday, but will post back once we have some further information.  If you have further specific items, post a new issue on it and we will get you an answer.

**Comment by shainw** [comment]
Still in progress on determining timing, will update once we have more details.

**Comment by shainw** [comment]
@baselsalam - It's been a while on this one and I forgot to update the thread.  We now handle the issue with what is called ASIM, you can read more about it here - https://docs.microsoft.com/en-us/azure/sentinel/authentication-normalization-schema.
