### ISSUE TITLE
Inquiries about "Synchronization Tool for Sentinel and JIRA"

### ISSUE THREAD

**Issue by stormech77** [Azure/Azure-Sentinel#5872]
Hello

By referring to the url below, the status synchronization of jira and sentinel is in progress.
I have handled all the contents of the guide, but the following problem is occurring during sync operation

When I checked, I found a lot of customfield_100XX in the app designer code part that are not listed in the guide document.
Could you please check the error below?
We ask you what additional work you need to do.

- URL : https://github.com/Azure/Azure-Sentinel/tree/master/Playbooks/Sync-IncidentsWithJIRA

![image](https://user-images.githubusercontent.com/53404278/183846467-ea8ac573-3254-4d8f-aa8e-b5dbb7ac9074.png)

ExpressionEvaluationFailed. The execution of template action 'Switch' failed: The result of the evaluation of 'scope' action expression '@triggerBody()?['fields']?['customfield_10010']?['currentStatus']?['statusCategory']' is not valid. It is of type 'Null' but is expected to be a value of type 'String, Integer'.

Best Regards

**Comment by macleee** [comment]
Hello!

I have exactly same issue as @stormech77. Any updates related to this issue?

BR

**Comment by stormech77** [comment]
Hello macleee
I found a solution
Change the format of automation rule in jira
(web request body - automation format)
Then it will be processed

Best Regards

**Comment by macleee** [comment]
Actually I got it working with my modification! Thank you very much @stormech77 !

**Comment by stormech77** [comment]
Good Job  @macleee 
Always be happy!
Best Regards

**Comment by macleee** [comment]
Hello @james-stapp !

I fix it by changing automation rule in JIRA to "web request body - automation format". But after that You need to check where the switch is pointing to. At least in my case I didn't have customfield_10010 so I needed to change it. Try to check your RAW output and find the field where is the status.

Hope this helps you.

**Comment by stormech77** [comment]
@james-stapp 
As a side note, please put the "request type field" in the screen of your project and add a value and then try it.

**Comment by stormech77** [comment]
@macleee Hello
The url below doesn't seem to work anymore
- https://github.com/Azure/Azure-Sentinel/tree/master/Playbooks/Sync-IncidentsWithJIRA
Perhaps the jira incident item is missing from the playbook list.
Do you have a related JSON file by any chance?

Best Regards

**Comment by macleee** [comment]
Hello @stormech77 !

MS is moving stuff under "solutions". Here is the link for the playbooks: https://github.com/Azure/Azure-Sentinel/tree/master/Solutions/AtlassianJiraAudit/Playbooks
