### ISSUE TITLE
Port Scan Analytic Rule not Populating Entities list in Incident

### ISSUE THREAD

**Issue by wingcomm** [Azure/Azure-Sentinel#5877]
**Describe the bug**
When the the [Port scan detected (ASIM Network Session schema)]  analytic rule triggers an incident, it does not populate the SrcIPAddr columns into the Entities list with an IP address even though its configured as part of the rule. This prevents us from creating playbooks for expected behavior related to this detection.

**To Reproduce**
1. Enable the rule
2. Ensure that ScrIPAddr is mapped to "IP Address"
<img width="1952" alt="Screen Shot 2022-08-10 at 11 05 26 AM" src="https://user-images.githubusercontent.com/9159510/183939483-1b83db0f-7f98-4e92-8470-b4c1682e5a05.png">
3. View incident generated by rule and see that "Entities" list is empty.
<img width="455" alt="Screen Shot 2022-08-10 at 11 06 17 AM" src="https://user-images.githubusercontent.com/9159510/183939804-4af5b9bf-2a21-4e2a-ba2e-ca04a9a4a1e7.png">
4. Review Events to confirm the SrcIPAddr column is populating:
<img width="983" alt="Screen Shot 2022-08-10 at 11 06 34 AM" src="https://user-images.githubusercontent.com/9159510/183940035-ad132982-a728-45c9-8d0c-336a9482f599.png">

**Expected behavior**
We should see all of the SrcIPAddr rows listed in the Entities field so that we can create playbooks to auto-close expected detections from certain IP Addresses.

**Screenshots**
Included inline above.

**Comment by wingcomm** [comment]
Any updates on this issue?

**Comment by tatecksi** [comment]
Hi @wingcomm, kindly open a support ticket for this.

**Comment by v-vdixit** [comment]
Hi @wingcomm hope this issue has been resolved, if you're still facing this issue please let us know, thanks!

**Comment by v-vdixit** [comment]
Hi @wingcomm Gentle Reminder: We are waiting for your response on this issue. If you still need to keep this issue active, please respond on it in the next 2 days. If we don't receive response, we will be closing this issue as per our standard procedures, thanks!

**Comment by v-vdixit** [comment]
Hi @wingcomm Since we have not received a response in the last 5 days, we are closing your issue #5877 as per our standard operating procedures. If you still need support for this issue, feel free to re-open at any time. Thank you for your co-operation.
