### ISSUE TITLE
Connector for GCP Pub/Sub

### ISSUE THREAD

**Issue by q-andrikoshundi** [Azure/Azure-Sentinel#5889]
https://techcommunity.microsoft.com/t5/microsoft-sentinel-blog/the-codeless-connector-platform/ba-p/3095455

![image](https://user-images.githubusercontent.com/90905744/184106626-892778db-dc8f-478b-a77e-711a2aab780c.png)

![image](https://user-images.githubusercontent.com/90905744/184106709-35057729-c47f-4d78-85eb-75ad3f76c765.png)

**Comment by v-dvedak** [comment]
Hi @q-andrikoshundi, Pub/Sub model is already being used by GCP Audit Logs connector. We will develop more connectors that use the same model. So, closing this issue. If you still need support for this issue, feel free to re-open at any time. Thank you for your co-operation.
