### ISSUE TITLE
Salesforce connector - Azure Function Select query from Salesforce env is not working

### ISSUE THREAD

**Issue by inbalsilis** [Azure/Azure-Sentinel#5909]
**Describe the bug**
TimerInterval set by default as hourly, 
The Azure Function have condition:
if interval == 'hourly':
        query = "/services/data/v44.0/query?q=SELECT+Id+,+EventType+,+**Interval**+,+LogDate+,+LogFile+,+LogFileLength" + \
        "+FROM+EventLogFile" + \
        f"+WHERE+Interval+=+'Hourly'+and+CreatedDate+>+{past_time}"

    elif interval == 'daily':
        query = "/services/data/v44.0/query?q=SELECT+Id+,+CreatedDate+,+EventType+,+LogDate+,+LogFile+,+LogFileLength" + \
                "+FROM+EventLogFile" + \
                f"+WHERE+LogDate+>+{past_time}"

The salesforce env doesnt have Interval, so the Select with the interval==hourly not working and we get error back.
When we changed the TimerInterval to daily, the select worked, and the Azure Function return success.
Please note, the same connector with Salesforce Dev env, and hourly interval: worked.
Please note, the same connector with Salesforce Enterprise/Prod env, and hourly interval: didnt worked.

**To Reproduce**
1. Go to Sentinel -> Connectors -> Salesforce and install Salesforce connector (remain with default setup)
2. Go to Azure Functions-> Functions -> SalesforceSentinelConnector -> Monitor -> and check the status of the calls
3. If error 400 exits, with sytext: File list getting failed
5. Go to Function->Configuration-> Application Settings-> check the status of timeIntervl

**Expected behavior**
The Function will connect without errors

**Screenshots**
![a7117f42-28bb-477f-8fb4-43ee1bdc834b](https://user-images.githubusercontent.com/100754734/184856243-2fbff419-a6df-463f-a046-3f56401e2e0b.jpg)

![b3dea169-bcd9-4cc8-b66b-3492ecae5be3](https://user-images.githubusercontent.com/100754734/184856300-5f52f3c3-2931-452e-9b28-a652b4779833.jpg)

**Additional context**
![e7ec9c6e-274f-4db6-82e4-570d4bbba36b](https://user-images.githubusercontent.com/100754734/184857139-30c77e55-3c95-4a10-b297-fa14f1ebac1f.jpg)
![4c3d91e8-e92b-42bc-962d-57cec611003d](https://user-images.githubusercontent.com/100754734/184857452-a550f61f-889d-4ae0-a738-ca7cd974bdae.png)

**Comment by v-vdixit** [comment]
Hi @inbalsilis are you still facing this issue, please let us know if you still need assistance with this issue, thanks!

**Comment by inbalsilis** [comment]
No, thanks.

**Comment by v-vdixit** [comment]
Thanks for confirmation, closing this issue.
