### ISSUE TITLE
Analytic Update SigninLogs/BypassCondAccessRule

### ISSUE THREAD

**Issue by clogmeister** [Azure/Azure-Sentinel#5955]
**Describe the bug**
In the analytic query, the Status variable is incorrectly extracted from DeviceDetail, it should be extracted from Status

**To Reproduce**
Change line 39 from:
  | extend DeviceDetail = todynamic(DeviceDetail), Status = todynamic(DeviceDetail), LocationDetails = todynamic(LocationDetails)
  
to:
  | extend DeviceDetail = todynamic(DeviceDetail), Status = todynamic(Status), LocationDetails = todynamic(LocationDetails)

**Expected behavior**
The status code should visible in the Status column in the output.

**Screenshots**
Output using current query:
![image](https://user-images.githubusercontent.com/52942359/185841991-b069dced-1ef1-4a4a-9b11-3c128c598a6e.png)

Output using updated query:
![image](https://user-images.githubusercontent.com/52942359/185842031-c9220e44-1eb2-483d-85e2-331207185a86.png)

**Desktop (please complete the following information):**
N/A

**Smartphone (please complete the following information):**
N/A

**Additional context**
N/A

**Comment by sreedharande** [comment]
@clogmeister - Thanks for bringing this to our attention. Can you raise PR with the fix

**Comment by tatecksi** [comment]
PR has been raised to fix the issue
