### ISSUE TITLE
Get-AlertEntitiesEnrichment - Error when deploying

### ISSUE THREAD

**Issue by Xebus-Systems** [Azure/Azure-Sentinel#5964]
Hi All,

Just wondering if anyone else is getting the same error

When deploying this playbook into my sentinel im getting the following error

{"code":"DeploymentFailed","message":"At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/DeployOperations for usage details.","details":[{"code":"WorkflowTriggerNotFound","message":"The workflow 'GetAlertEntitiesEnrichment' trigger 'When_a_response_to_an_Azure_Sentinel_alert_is_triggered' could not be found."}]}

The first part deployed fine with App registration etc, its the Get-AlertEntitiesEnrichment section

I'm running my Sentinel in one Resource Group and have adding a second resource group for SOAR components, unsure if anyone else runs it in this manner and has had success with this

Can someone advise?

Regards
Xebus

**Comment by piaudonn** [comment]
If you change the line 583 of [Get-AlertEntitiesEnrichment.json](https://github.com/Azure/Azure-Sentinel/blob/592d819593806be524ac32c90397ca5dfd04b969/Playbooks/Get-AlertEntitiesEnrichment/Get-AlertEntitiesEnrichment.json) from:
`"value": "[listCallbackURL(concat(resourceId('Microsoft.Logic/workflows/', parameters('logicAppName')), '/triggers/When_a_response_to_an_Azure_Sentinel_alert_is_triggered'), '2016-06-01').value]"`
to
`"value": "[listCallbackURL(concat(resourceId('Microsoft.Logic/workflows/', parameters('logicAppName')), '/triggers/Microsoft_Sentinel_alert'), '2016-06-01').value]"` your deployment will go through.

Shameless plug, you might give a try to this if you are looking at enrichment: https://aka.ms/mstat 🤖

**Comment by Xebus-Systems** [comment]
cheers found it, and is now working properly :) cheers @piaudonn
