### ISSUE TITLE
Incident link is not available in Logic App trigger

### ISSUE THREAD

**Issue by devblackops** [Azure/Azure-Sentinel#597]
Is it possible to get the **Incident link** from the Logic App trigger? I'd like to include a deep link directly to the Sentinel incident in notifications such as Slack or email but this information doesn't appear to be available anywhere.

**Comment by dicolanl** [comment]
We are planning to add this.  For feature changes, please use https://feedback.azure.com/forums/920458-azure-sentinel which is our uservoice.
