### ISSUE TITLE
Incident description set by the first Alert description

### ISSUE THREAD

**Issue by Lodewyk-Git** [Azure/Azure-Sentinel#5985]
**Is your feature request related to a problem? Please describe.**
I'd like to have a unique Incident description that's not a part of the alert description.

**Describe the solution you'd like**

I'm using it for some firewall Incidents I made

But the Incident description seems to be overwritten by the first alert's description, even when there's multiple alerts with different  descriptions
*The alert description*
![image](https://user-images.githubusercontent.com/36856692/186420115-e9668652-4c46-4603-be39-e739c076e0ae.png)

*My default Incident description*
![image](https://user-images.githubusercontent.com/36856692/186420191-e7478401-88bb-403f-a9ef-62b9c4050266.png)

**Additional context**
Once the Incident is created, it will have the fist Alert's description, even when multiple alerts form the Incident

**Comment by v-vdixit** [comment]
Hi @Lodewyk-Git are you still facing this issue? Please confirm, thanks!

**Comment by v-vdixit** [comment]
Hi @Lodewyk-Git Gentle Reminder: We are waiting for your response on this issue. If you still need to keep this issue active, please respond on it in the next 2 days. If we don't receive response, we will be closing this issue as per our standard procedures, thanks!

**Comment by v-rbajaj** [comment]
Hi @Lodewyk-Git, currently this isn't supported. One of our respective team has added it as FR.
