### ISSUE TITLE
URGENT: Cisco Umbrella Folder Missing in Azure Sentinel DataConnectors 

### ISSUE THREAD

**Issue by alakijaD** [Azure/Azure-Sentinel#5995]
**Describe the bug**
CiscoUmbrella has been moved or deleted. Our Sentinel Function App unable to pull umbrella logs as there is no effectively no WEBSITE_RUN_FROM_PACKAGE.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to Azure Sentinel - > Function Apps -> your Umbrella Function App name
2. Click on Application Insights -> your Umbrella resource -> transaction search
3. Set to 'Last 24 hours'
4. Last request 7:53 AM 25/08/2022

**Expected behavior**
Function app expected to make requests every 10 minutes

**Additional context**
Missing Folder in this repository - will affect several organisations worldwide that rely on these logs 
Effectively blind on Sentinel till remediated.

**Comment by antoniolch** [comment]
In order to temporarily solve the issue, waiting Microsoft to fix it, use as value of the variable WEBSITE_RUN_FROM_PACKAGE a .zip file present in a previous commit (e.g. https://github.com/Azure/Azure-Sentinel/blob/0f534907ce1f19b6d22f77b75b5b4b4763b92d9e/DataConnectors/CiscoUmbrella/CiscoUmbrellaConn.zip?raw=true)

**Comment by Lsvingen** [comment]
When installing this connector again in a new Sentinel instance it points to a new link for the app source.
It is no longer using Github, but is pointing to the aka.ms link below..

https://aka.ms/sentinel-CiscoUmbrellaConn-functionapp

After changing to use the source from the previous commit and restarting the app the connector works again naturally, great tip @antoniolch 😃

**Comment by zackoch** [comment]
Do the maintainers know the sentinel connectors portal 'auto deployment' process relies on the location of these files to remain static?

This is like the third connector where the maintainers swizzled around the paths and broke the deployment for everyone using it 🤕

Thanks for the short URL @Lsvingen

**Comment by thinkdreams** [comment]
This worked for us as well. Also note that Python 3.8 is now the supported version to move to, so if you haven't yet - make the modifications to Python using this guide:

https://docs.microsoft.com/en-us/azure/azure-functions/functions-reference-python?tabs=asgi%2Capplication-level&tryIt=true&source=docs#code-try-26

**Comment by thinkdreams** [comment]
Note the instructions are not super clear, so make sure you enclose the python|3.8 in double quotes in the command line syntax.
