### ISSUE TITLE
Wrong ParserName in vimAuthenticationPostgreSQL.yaml

### ISSUE THREAD

**Issue by puijjar** [Azure/Azure-Sentinel#6030]
File: Parsers/ASimAuthentication/Parsers/vimAuthenticationPostgreSQL.yaml

Property ParserName should be vimAuthenticationPostgreSQL instead of ASimAuthenticationPostgreSQL.

**Comment by oshezaf** [comment]
Thanks @puijjar . Fixed now.

**Comment by puijjar** [comment]
Wrong functions are also refered in Parsers/ASimAuthentication/ARM/vimAuthenticationPostgreSQL/vimAuthenticationPostgreSQL.json.

**Comment by oshezaf** [comment]
Hopefully fixed this one as well now. Thanks!

**Comment by oshezaf** [comment]
Hopefully fixed this one as well now. Thanks!
