### ISSUE TITLE
GCP IAM Function | "Request exceeds maximum number of resource_names or project_ids"

### ISSUE THREAD

**Issue by dneto82** [Azure/Azure-Sentinel#6042]
**Describe the bug**
Function for GCP IAM seems to have a limit on resources request by Google API.

**To Reproduce**
1. Deploy ARM Template
2. Fill RESOURCE_NAMES with all your organization, projects
3. Wait Function trigger
4. Get error 400 (Bad Request) from google API.

`Result: Failure Exception: BadRequest: 400 POST https://logging.googleapis.com/v2/entries:list?prettyPrint=false: Request exceeds the maximum number of resource_names or project_ids....`

**Expected behavior**
Function proposed must treat values and split requests based on limits of queried resources id/names. Especially when you have ton of projects on your organization

**Screenshots**
<img width="1034" alt="image" src="https://user-images.githubusercontent.com/1860114/187384958-5e46382c-7072-4bf5-88a9-095c75e29b1e.png">

**Additional context**
Reference:
[Function](https://github.com/Azure/Azure-Sentinel/blob/a23ff174f5fb6343ac558ab88103e4327a6f6326/Solutions/GoogleCloudPlatformIAM/Data%20Connectors/azuredeploy_GCP_IAM_API_FunctionApp.json#L11)
[Google Cloud Docs](https://cloud.google.com/logging/docs/reference/v2/rest/v2/LogEntry)
`[LOG_ID] must be less than 512 characters long and can only include the following characters: upper and lower case alphanumeric characters, forward-slash, underscore, hyphen, and period.`

**Comment by cupello** [comment]
Hello! Any news?

**Comment by v-vdixit** [comment]
Hi @dneto82 @cupello Are you still facing this issue, please confirm

**Comment by v-vdixit** [comment]
Hi @dneto82 ,Gentle Reminder: We are waiting for your response on this issue. If you still need to keep this issue active, please respond on it in the next 2 days. If we don't receive response, we will be closing this issue as per our standard procedures, thanks!

**Comment by v-vdixit** [comment]
Hi @dneto82 Since we have not received a response in the last 5 days, we are closing your issue #6042 as per our standard operating procedures. If you still need support for this issue, feel free to re-open at any time. Thank you for your co-operation.
