### ISSUE TITLE
Playbook Deployment Error

### ISSUE THREAD

**Issue by tspizzirri** [Azure/Azure-Sentinel#6049]
**Describe the bug**
When deploying the Reset-AADPassword playbook, I receive the attached error.
**To Reproduce**
1. Go to ['...'](https://github.com/Azure/Azure-Sentinel/tree/master/Solutions/Azure%20Active%20Directory/Playbooks/Reset-AADUserPassword)
2. Deploy the playbook. Both incident and alert version produce the same error.
3. See error (attached screenshot)

**Expected behavior**
Playbook deploys

**Screenshots**
Attached

**Additional context**
![Snag_1839dac](https://user-images.githubusercontent.com/62339920/187761463-d968b58f-bb13-47ac-bcf4-1b74fdc53717.png)

**Comment by v-mchatla** [comment]
Hi @tspizzirri,
Thanks for bringing to our attention. We have fixed the issue in the readme file and raised the [PR](https://github.com/Azure/Azure-Sentinel/pull/7061). We will keep you posted on the progress.
Thanks

**Comment by v-mchatla** [comment]
Hi @tspizzirri,
We are closing this issue as its fixed and we are not seeing this issue anymore. Please feel free to reopen if you need any further assistance on this.
Thanks
