### ISSUE TITLE
Google Workspace Function | "Result: Failure Exception: RefreshError: The credentials do not contain the necessary fields need to refresh the access token."

### ISSUE THREAD

**Issue by boodoesgh** [Azure/Azure-Sentinel#6057]
**Describe the bug**
Function for Google Workspace does not seem to refresh the auth token.

**To Reproduce**
1. Deploy ARM template
2. Fill RESOURCE_NAMES with all your organization, projects
3. Wait function trigger
4. The function will successfully trigger 3-4 times before encountering refresh auth errors on every subsequent trigger.

**Expected behavior**
The auth token to automatically refresh.

**Screenshots**
![image](https://user-images.githubusercontent.com/84816703/187943981-ed83336f-b600-462d-a567-86b1ba494b42.png)

**Comment by bzuffi** [comment]
+1 Has there been any fixes for this issue? It still remains in the connector.

**Comment by matheusquei** [comment]
+1 !!! same problem since 2022... plis help! Exact the same error

**Comment by bzuffi** [comment]
I spent an inordinate amount of time working on this and eventually got it working. Make sure you are following the instructions to the letter. FWIW, three things that tripped me up were:

1. Pickling apparently needs to be done on a Windows system.
2. Make sure you use a Google Domain Admin to execute the pickling process
3. I don't think this in the instructions but you need to enable Domain-Wide Delegation for the API client and the Google Reports APIs. 

References
- https://learn.microsoft.com/en-us/azure/sentinel/data-connectors/google-workspace-g-suite-using-azure-function
- https://support.google.com/a/answer/162106?hl=en

**Comment by v-vdixit** [comment]
Hi @boodoesgh Are you still facing this issue, please confirm

**Comment by v-vdixit** [comment]
Thanks for confirmation, closing this.
