### ISSUE TITLE
Analytic rule validation failure - Privileged User Logon from new ASN

### ISSUE THREAD

**Issue by mgijo** [Azure/Azure-Sentinel#6097]
**Describe the bug**
The analytic rule named **Privileged User Logon from new ASN**  does not validate due to misconfiguration in the default settings of Sentinel. Due to this administrators are unable to enable this rule out-of-the-box. 

Below are few screenshots of this analytic template with error details:-

![Screenshot 2022-09-06 180537](https://user-images.githubusercontent.com/83291280/188749354-793041c6-9ca0-4640-999e-31531d7f2925.jpg)

![Screenshot 2022-09-06 180633](https://user-images.githubusercontent.com/83291280/188749368-3f2c0ab9-3333-4c3e-b613-9697fdd0b558.jpg)

**Expected behavior**
I would suggest to rename the  last line of the KQL logic from **IpAddress** to **IPAddress** to fix the first issue. Screenshot below of expected result:-

![image](https://user-images.githubusercontent.com/83291280/188749734-5e6742a6-1c2b-4d6c-8a8d-c4251ac46a5d.png)

Also, to fix the second issue - I would suggest to set the mapping with the following configuration below:-

![image](https://user-images.githubusercontent.com/83291280/188749861-f4ed51e2-79ee-43ed-b44a-47424b5b884c.png)

Thanks!

**Comment by sreedharande** [comment]
Thanks for bringing this to our attention, can you please create PR with this Fix.

**Comment by tatecksi** [comment]
PR has been raised to fix the issue
