### ISSUE TITLE
8 Entity Activity templates with issues during out-of-the-box deployment

### ISSUE THREAD

**Issue by mgijo** [Azure/Azure-Sentinel#6119]
**Describe the bug**
Unable to enable 8 of the activity templates available from the Entity Settings page under the Entity Behavior blade in Sentinel. Below is a screenshot of the 8 activity templates we are unable to enable out of the box.

![image](https://user-images.githubusercontent.com/83291280/189018462-b17ba662-6b94-4ead-a64e-28e479bc3bc4.png)

**To Reproduce**
You can select any one of the highlighted activity templates from the screenshot provided earlier and try to enable them. But it fails with the below error (screenshot below):-

![image](https://user-images.githubusercontent.com/83291280/189018566-21f9fadb-c0b9-41c2-91de-4d480a0259c2.png)

**Suggested fix*
I would suggest to change the KQL query under each of the affected entity activity template since there is a minor issue.

![image](https://user-images.githubusercontent.com/83291280/189018821-14bd8340-e20e-4f9e-9c7c-0840a9413f22.png)

The issue is if the **{{Account_SID}}** specified under each of these affected could be changed to **{{Account_Sid}}**. This minor change should fix issues if implemented on 8 of the affected activity templates.

![image](https://user-images.githubusercontent.com/83291280/189018831-4ea1f1d9-df14-4e97-a700-d9a442918eb9.png)

**Comment by Lodewyk-Git** [comment]
![image](https://user-images.githubusercontent.com/36856692/190985129-b1b9265a-79e8-4858-b5cd-a952aac9390b.png)

**Comment by sreedharande** [comment]
@mgijo - Thanks for bringing this our attention. Can you please raise PR with this Fix

**Comment by mgijo** [comment]
> @mgijo - Thanks for bringing this our attention. Can you please raise PR with this Fix

sure @sreedharande . Could you guide me how to raise a PR in Github?

**Comment by tatecksi** [comment]
@mgijo , I believe this has been fixed. Proceed to close.
