### ISSUE TITLE
Spelling error

### ISSUE THREAD

**Issue by anfisher1967** [Azure/Azure-Sentinel#6140]
Not sure it anyone cares but malicious is spelled wrong in these two queries

[detect-malcious-use-of-msiexec (1).yaml](https://github.com/Azure/Azure-Sentinel/blob/master/Hunting%20Queries/Microsoft%20365%20Defender/Execution/detect-malcious-use-of-msiexec%20(1).yaml)

[detect-malcious-use-of-msiexec (2).yaml](https://github.com/Azure/Azure-Sentinel/blob/master/Hunting%20Queries/Microsoft%20365%20Defender/Execution/detect-malcious-use-of-msiexec%20(1).yaml)

**Comment by sreedharande** [comment]
@anfisher1967 @Lodewyk-Git - Thanks
