### ISSUE TITLE
V2 Solution build tooling requires that workbook metadata is already on the master branch

### ISSUE THREAD

**Issue by sdball** [Azure/Azure-Sentinel#6141]
When building a solution using the V2 tooling workbook builds will error because the v2 powershell build script has a [hardcoded lookup to the master branch](https://github.com/Azure/Azure-Sentinel/blob/a79c1637e8acb6a5c750f0ec4fae45d7a087fdcf/Tools/Create-Azure-Sentinel-Solution/V2/createSolutionV2.ps1#L154).

```
$workbookMetadataPath = "https://raw.githubusercontent.com/Azure/Azure-Sentinel/master/"
```

Example of failure from build

```
  Parameters Without Default Must Exist In CreateUIDefinition
    [-] Parameters Without Default Must Exist In CreateUIDefinition (2 ms)
        workbook1-name does not have a default value, and is not defined in
CreateUIDefinition.outputs
```

**Expected behavior**
Solution builds with workbooks should be allowed to provide a local WorkbooksMetadata.json file.

**Comment by colindomoney-42crunch** [comment]
I have also encountered this issue. I noticed a _WorkbookMetadata_ folder in the /V2 root and assumed it would use this location but adding my metadata to this file still gave the same error as above until I hardcoded the path in my PS1 script.

**Comment by sdball** [comment]
That's exactly what I had do as well. I had a small patch to temporarily change the hardcoded location to our own fork's feature branch so the build would work and avoided committing that as part of our PR.

**Comment by v-rucdu** [comment]
Thanks @keyoke for the fix... PR has been merged to the master... @sdball as the fix is merged to master, we are closing this issue please feel free to reopen in case the issue persist... Thanks!!!
