### ISSUE TITLE
Post to Teams does not seem to work

### ISSUE THREAD

**Issue by akefallonitis** [Azure/Azure-Sentinel#617]
Hi

 I am trying to add the playbook https://github.com/Azure/Azure-Sentinel/tree/master/Playbooks/Post-Message-Teams to post in a Teams Channel for every new incident.
 Although i deploy the playbook successfully when i **run trigger**  it always fail on the **Alert - Get incident** step with **404 resource not found** are there any special permissions needed ?
What am i missing?  Any info from someone that already deploy it ?

Thanks in Advanced

**Comment by akefallonitis** [comment]
One addition when i try to run the playbook in the incident i get this error message:

ExpressionEvaluationFailed. The execution of template action 'For_each' failed: the result of the evaluation of 'foreach' expression '@body('Alert_-_Get_incident')?['value']' is of type 'Null'. The result must be a valid array.

**Comment by dicolanl** [comment]
Hi @akefallonitis  are you triggering the playbook from the logic app resource? or from Azure Sentinel?  

ExpressionEvaluationFailed. The execution of template action 'For_each' failed: the result of the evaluation of 'foreach' expression '@Body('Alert_-_Get_incident')?['value']' is of type 'Null'. The result must be a valid array.

this implies the get incident returned null, which would happen if the sentinel trigger is null.  you can not trigger these playbooks from logic apps as they wouldnt have any data from the sentinel trigger.  you need to do it from azure sentinel in one of your incidents.

**Comment by akefallonitis** [comment]
Hi @dicolanl and thanks for your answer

I have tried both triggering from Sentinel and Logic app.

It only work from sentinel when i remove the for each statement

**Comment by dicolanl** [comment]
ahh ok.  Let me look at it and we can update by removing the loop.

**Comment by akefallonitis** [comment]
So the loop is not needed ?

**Comment by dicolanl** [comment]
Nope.. ;)
