### ISSUE TITLE
Incident rule using bag_unpack not defining columnname in scheduled rule

### ISSUE THREAD

**Issue by Lodewyk-Git** [Azure/Azure-Sentinel#6175]
**Describe the bug**
When trying to create a rule that uses bag_unpack it does not registered one of the unpacked values as a column and thus won't create. 

**To Reproduce**
Create  the rule "User account created without expected attributes defined"

Default Rule:
![image](https://user-images.githubusercontent.com/36856692/190980962-4a0f38aa-16c4-47c6-be30-248d16b6e1f1.png)

Without bag_unpack:
![image](https://user-images.githubusercontent.com/36856692/190981158-6f05e068-15fd-437b-bef4-3baff9cd1543.png)

**Expected behavior**
Query to work with bag_unpack

**Comment by tatecksi** [comment]
Hi @Lodewyk-Git, did you get the latest version of this rule?
It should have the highlighted line to prevent the error.

![image](https://user-images.githubusercontent.com/25794051/195495269-d54850a5-ec2b-4eed-9d76-e0823fef71e7.png)
