### ISSUE TITLE
No tabular expression statement found - NewResourceGroupsDeployedTo.yaml - Suspicious Resource deployment

### ISSUE THREAD

**Issue by rweirtbg** [Azure/Azure-Sentinel#6194]
**Describe the bug**
We are unable to view events for "Suspicious Resource deployment" The event search has errors:
No tabular expression statement found

**To Reproduce**
1. Trigger alert
2. Attempt to view Events on triggered incident
3. See error

**Expected behavior**
See results

**Screenshots**
Screenshot error attached.

<img width="2055" alt="Screen Shot 2022-09-21 at 2 09 00 AM" src="https://user-images.githubusercontent.com/111534841/191427784-3ae2c2d6-c232-4577-b3d7-0de36698c591.png">

**Comment by tatecksi** [comment]
@rweirtbg, quick fix would be to remove the first empty line in the rule's query and you won't see the error anymore for subsequent alerts.

![image](https://user-images.githubusercontent.com/25794051/194866794-0833e7d8-70f5-4a1f-8eee-1e818d99d838.png)
