### ISSUE TITLE
Cannot Create Rule for "Threat Essentials - Multiple admin membership removals from newly created admin."

### ISSUE THREAD

**Issue by rweirtbg** [Azure/Azure-Sentinel#6196]
**Describe the bug**
Cannot Create Rule for "Threat Essentials - Multiple admin membership removals from newly created admin." Attempting to do this causes a Sentinel Error: 
`this.sectionParameters.alertEnrichmentConfiquration.entitiesMapping.filterisnotafunction`

**To Reproduce**
1. Go to 'Analytic Rules'
2. Click on 'Rule Templates'
3. Scroll down to 'Threat Essentials - Multiple admin membership removals from newly created admin'
4. Select 'Create rule'
5. See error

**Expected behavior**
No Error

**Screenshots**

<img width="461" alt="Screen Shot 2022-09-21 at 2 59 21 AM" src="https://user-images.githubusercontent.com/111534841/191436594-aca48e05-a8c7-4a24-a032-923175bd1eb2.png">

<img width="1036" alt="Screen Shot 2022-09-21 at 2 58 45 AM" src="https://user-images.githubusercontent.com/111534841/191436729-5e331d05-5742-4b51-8a18-737e77039730.png">

**Comment by tatecksi** [comment]
Hi @rweirtbg, I have tried creating the rule and was able to create it successfully. Can you please try again?
Otherwise, kindly raise a support ticket as it might be due to your environment and not the rule template.
