### ISSUE TITLE
Data fetch failed (Invalid Config.) with Solutions/LastPass

### ISSUE THREAD

**Issue by ChristopheDMTL** [Azure/Azure-Sentinel#6202]
Hello,

I think there is a problem with the solution, after deploying the solution from the content hub, I was able to go into the connector and configure the connection to LastPass, but the table never created.

And I have these two alerts that keep repeating:
![Screenshot at 2022-09-21 16-33-50](https://user-images.githubusercontent.com/98554355/191604959-49c6c616-280e-4468-bdb1-4635cf9c5678.png)

![Screenshot at 2022-09-21 16-37-16](https://user-images.githubusercontent.com/98554355/191605527-ff873e3c-ed38-46cc-bf77-5af9e4935c83.png)

Thanks

**Comment by ashishsyal** [comment]
Hi - Are you still facing the issue?

**Comment by ChristopheDMTL** [comment]
Hello,

Thank you for your feedback, but I couldn't wait for the resolution.
We finally built our own solution.

Thanks

**Comment by v-rbajaj** [comment]
@ChristopheDMTL, Thanks for the confirmation, we are closing this issue.
