### ISSUE TITLE
Have MS maintain a list of know data centers etc

### ISSUE THREAD

**Issue by KjaAkademiker** [Azure/Azure-Sentinel#6205]
**Describe the bug**
For the https://github.com/Azure/Azure-Sentinel/blob/4ad195f4fe6fdbc66fb8469120381e8277ebed81/Detections/SigninLogs/AuthenticationAttemptfromNewCountry.yaml

I get daily alerts/incidents in Sentinel, where 95% of the detections are from MS Datacenters

**Screenshots**
See attaced screenshot

**Additional context**
I would love if MS would maintain a list of datacenters that can excluded/whitelisted, to avoid false positives. Is there anyone that knows of such a list?

Regards
Kim

![Skærmbillede 2022-09-22 105808](https://user-images.githubusercontent.com/102727656/191704804-834c14ab-d9ec-409f-be96-25d1fa2034de.png)

**Comment by v-rbajaj** [comment]
Hi @KjaAkademiker, yes, we do have a list of Microsoft Service IPs including Azure VM external IP ranges. Its accessible here - https://www.microsoft.com/en-us/download/details.aspx?id=56519

If you want to use this data in a query to filter out Azure IPs you can use a formatted set we keep in GitHub for easier access with the externaldata KQL operator -https://github.com/microsoft/mstic/blob/master/PublicFeeds/MSFTIPRanges/MSFT_PublicIPs.csv

**Comment by v-rbajaj** [comment]
Reminder: We are awaiting for your response on this issue. If you still need to keep this issue active please respond on it in the next 2 days. If we don't receive response by given date we will be close this issue.

**Comment by v-rbajaj** [comment]
Since we have not received a response in the last 5 days, we are closing your issue https://github.com/Azure/Azure-Sentinel/issues/6205 as per our standard operating procedures. If you still need support for this issue, feel free to re-open at any time. Thank you for your co-operation."
