### ISSUE TITLE
Bad URL in Tenable.io content solution manifest and package (documentation)

### ISSUE THREAD

**Issue by ktb-jcm** [Azure/Azure-Sentinel#6209]
**Describe the bug**
The Tenable.io Solution for Microsoft Sentinel's template has a bad URL in the documentation. The bad URL is:

- https://docs.tenable.com/tenableio/vulnerabilitymanagement/Content/Settings/GenerateAPIKey.htm

The **correct** URL is:

- https://docs.tenable.com/tenableio/Content/Platform/Settings/MyAccount/GenerateAPIKey.htm

Please correct this in the package manifest and all relevant documentation. This apples to the Microsoft Sentinel Content Hub as well.

**To Reproduce**
Navigate to the URLs documented in the description, and observe the 404 error versus the appropriate data.

**Expected behavior**
URL's should be correct.

**Screenshots**
You shouldn't need screenshots, ;)

**Desktop (please complete the following information):**
**Smartphone (please complete the following information):**
These are not relevant, a bad URL is universally inaccessible on all platforms and permutations.

**Comment by v-dvedak** [comment]
Closing the issue since the URL if fixed in [PR](https://github.com/Azure/Azure-Sentinel/pull/6334) and PR is merged.
