### ISSUE TITLE
Abnormal Security solution does not include steps on identifying required IP addresses

### ISSUE THREAD

**Issue by ktb-jcm** [Azure/Azure-Sentinel#6211]
**Describe the bug**
In the Abnormal Security solution for Microsoft Sentinel, references are made to enabling the Abnormal API key, however it fails to mention that this requires specifying IP address(es) that will be making the API calls. Abnormal Security **requires** specifying one or more IP addresses/ranges before the API can be enabled. Those IP addresses must be where the API calls will be made from.

**To Reproduce**

1. Start the solution install
2. Navigate to an Abnormal Security portal and click the API integration option
3. Observe that the "Save" button is grayed out unless one or more source IP ranges/addresses are given

NOTE: This requires having an Abnormal Security license, which may be why it escaped someone's notice.

**Expected behavior**
The documentation and installation should include steps to:

- Describe the need for specifying the source IPs when enabling and getting the Abnormal API key
- How to look-up the IP addresses the function app will use
- Remediate the catch-22 of needing the function app installed to know the IP addresses required to create the API key needed to create the function app. :/

**Screenshots**

**Desktop (please complete the following information):**
N/A

**Smartphone (please complete the following information):**
N/A

**Additional context**
Likely this solution will need to be modified to create the function app first, obtain its IP address and then direct user to process docs on how to get their API key.

Some reference to this page is needed, at the least - https://learn.microsoft.com/en-us/azure/azure-functions/ip-addresses?tabs=portal

**Comment by v-vdixit** [comment]
Hi @ktb-jcm are you still facing this issue, please confirm, thanks!

**Comment by v-vdixit** [comment]
Hi @ktb-jcm Gentle Reminder: We are waiting for your response on this issue. If you still need to keep this issue active, please respond on it in the next 2 days. If we don't receive response, we will be closing this issue as per our standard procedures, thanks!

**Comment by v-vdixit** [comment]
Hi @ktb-jcm Since we have not received a response in the last 5 days, we are closing your issue # 6211 as per our standard operating procedures. If you still need support for this issue, feel free to re-open at any time. Thank you for your co-operation.
