### ISSUE TITLE
Limo Anomali feed is end-of-life on August 14th, 2022.

### ISSUE THREAD

**Issue by mattu0119** [Azure/Azure-Sentinel#6212]
**Is your feature request related to a problem? Please describe.**
Limo Anomali free feed ended its service on August 14th 2022. We unable to add Threat Intelligence connector from the feed on Sentinel Training Lab Module2.
https://github.com/Azure/Azure-Sentinel/blob/master/Solutions/Training/Azure-Sentinel-Training-Lab/Modules/Module-2-Data-Connectors.md#exercise-3-enable-threat-intelligence-taxii-data-connector

I don't know any other free feed. It is very helpful if the other free feed is provided on the module.

**Comment by paisleyborg** [comment]
Hi, just following up on this request, as I have numerous new staff members that are trying to work through this lab. Thank you

**Comment by elasticsec** [comment]
> **Is your feature request related to a problem? Please describe.** Limo Anomali free feed ended its service on August 14th 2022. We unable to add Threat Intelligence connector from the feed on Sentinel Training Lab Module2. https://github.com/Azure/Azure-Sentinel/blob/master/Solutions/Training/Azure-Sentinel-Training-Lab/Modules/Module-2-Data-Connectors.md#exercise-3-enable-threat-intelligence-taxii-data-connector
> 
> I don't know any other free feed. It is very helpful if the other free feed is provided on the module.

Try using AlienVault OTX

**Comment by v-vdixit** [comment]
Since we have not received a response in the last 7 days, we are closing your issue as per our standard operating procedures. If you still need support for this issue, feel free to re-open at any time. Thank you for your co-operation.
