### ISSUE TITLE
Add "Create Alert" to LogicApp Integration

### ISSUE THREAD

**Issue by ETMRidge** [Azure/Azure-Sentinel#6243]
**Is your feature request related to a problem? Please describe.**
N/A

**Describe the solution you'd like**
An addition to the Azure Sentinel Logic App Integration options to include "Create Alert".
This would be useful to add, as if a logic app was triggered and detected an artefact through an open source Threat Intelligence platform(AbuseIPDB, Greynoise, Virustotal), it would display in the timeline of the incident investigation.

**Describe alternatives you've considered**
Using the "add comment" integration.  However, this does not display the information as I would like it to do so.

**Additional context**

**Comment by BenjiSec** [comment]
Hi @ETMRidge - thank you for the feedback and idea for additional action in Microsoft Sentinel Logic App connector.
Tagging @lior-tamir for visibility. 
Is there a reason why not to add this as a bookmark once detected?

**Comment by v-amolpatil** [comment]
Hi @ETMRidge, Closing this issue and there is no update. Feel free to reopen if you need assistance on this issue.
