### ISSUE TITLE
NXLog FIM Solution v2.0.0

### ISSUE THREAD

**Issue by techwriter-dev** [Azure/Azure-Sentinel#6263]
This issue shall replace [NXLog FIM Solution v1.0.0 #5904](https://github.com/Azure/Azure-Sentinel/pull/5904) since its creator is no longer tasked with this issue.

A new PR will be created that shall include the original work completed in [Pull Request #5904](https://github.com/Azure/Azure-Sentinel/pull/5904) as well as resolve some of the discussions that are still open.

### Change(s):

    Initial submission for NXLog FIM Solution

### Version Updated:

    This will change the version from 1.0.0 to 2.0.0 as @v-atulyadav [requested in this discussion](https://github.com/Azure/Azure-Sentinel/pull/5904#discussion_r969267995).

### Testing Completed:

    Yes (according to the previous owner)

Checked that the validations are passing and have addressed any issues that are present:

    Yes

**Comment by sreedharande** [comment]
PR under review #6264
