### ISSUE TITLE
cloudinit-rh.txt failing on rhel

### ISSUE THREAD

**Issue by tjav** [Azure/Azure-Sentinel#627]
The ```CEF-VMSS-RH-Templatev2.json``` deployment is not working for me. the ***troubleshoot.py*** shows that rsyslog in not working. On a standalone machine running the troubleshoot twice works. When I try to manually run ``cloudinit-rh.txt`` on an instance. I receive the following 

```bash
sudo sed -i -e 's@*.*;auth,authpriv.none@syslog.*;auth,authpriv.none@g' /etc/rsyslog.d/50-default.conf
sed: can't read /etc/rsyslog.d/50-default.conf: No such file or directory
```

other commands seems to work.

**edit** same for the ubuntu vmss

**Comment by preetikr** [comment]
@tjav -  Please file a support ticket with the repro you have for getting unblocked on this issue. Refer to https://azure.microsoft.com/support/options/ for filing a support ticket.
