### ISSUE TITLE
Sentinel's _ASim_DnsBuiltIn Function/Parser has a bug 

### ISSUE THREAD

**Issue by LaraibKhan555** [Azure/Azure-Sentinel#6306]
let DisabledParsers=materialize(_GetWatchlist('ASimDisabledParsers') 
| where SearchKey in ('Any', 'Exclude_ASim_Dns') 
| extend SourceSpecificParser=column_ifexists('SourceSpecificParser','') 
| where isnotempty(SourceSpecificParser) 
| distinct SourceSpecificParser);
let builtInDisabled=toscalar(toscalar(DisabledParsers) has_any ('Exclude_ASim_DnsBuiltIn', 'Exclude_ASim_Dns', 'Any')); // this particular expression is not correct.

The Correct expression to use here is:

let builtInDisabled=toscalar('Exclude_ASim_Dns' in (DisabledParsers) or 'Any' in (DisabledParsers)); 

The rest of the Parser is fine, exclusion works fine when this particular expression is corrected. Let me know if someone has any feedback!

**Comment by oshezaf** [comment]
Hi @LaraibKhan555 . I am not sure I fully understand what's wrong with the original. It works for me. Is there a query error anywhere, or exclusion just does not work? Something else? Can you share what were the values in your Watchlist when things did not work?

thanks!
 ~ Ofer

**Comment by LaraibKhan555** [comment]
Hi, @oshezaf we try to exclude all vendor parsers but CiscoUmbrella the query won't show any data when this expression is used.
**let builtInDisabled=toscalar(toscalar(DisabledParsers) has_any ('Exclude_ASim_DnsBuiltIn', 'Exclude_ASim_Dns', 'Any'));**

We then tried the below expression to exclude all but CiscoUmbrella, the logs from Cisco Umbrella start populating in the log viewer.
**let builtInDisabled=toscalar('Exclude_ASim_Dns' in (DisabledParsers) or 'Any' in (DisabledParsers));**

**Comment by oshezaf** [comment]
Few questions and comments:
- First, we don't have an option of "exclude all but X", and therefore I think that the original works as expected. 
- I do wonder why your version works. Can you share the content of the Watchlist?
- Lastly, what is the use case for excluding all others? Do you have the sources but don't want them to be parsed? If you don't have the sources, you don't need to exclude.

**Comment by LaraibKhan555** [comment]
- I do wonder why your version works. Can you share the content of the Watchlist?
![image-20220930-150149](https://user-images.githubusercontent.com/24682607/196920730-c4ed1883-5b68-407e-a9ee-669ff304ea8c.png)

- Lastly, what is the use case for excluding all others? Do you have the sources but don't want them to be parsed? If you don't have the sources, you don't need to exclude.
**Usecase to excluding all other than CiscoUmbrella is we don't have integration for those sources and exclusion was necessary to improve query processing time.**

Query time before exclusion:
![image-20220930-142808](https://user-images.githubusercontent.com/24682607/196921208-3150b342-9863-4972-ba6b-4398d6322037.png)

Query time after exclusion:
![image-20220930-150525](https://user-images.githubusercontent.com/24682607/196921333-b72e3d79-cfaa-4ac0-b58d-0b688d2800d6.png)

**Comment by oshezaf** [comment]
Let me try to replicate why my version does not work. 

Also, I want to try to nail the root cause as to why the query is slow for sources you don't have. Can you help me by checking which of the parsers is slow? Better even, I would be glad to meet and test things on your system if this is OK with you. I am at ofer.shezaf@microsoft.com

**Comment by oshezaf** [comment]
OK. Obviously we have a bug. I was misguided as I thought you used "Any" to exclude all. We will fix. Still @LaraibKhan555, I would like to investigate why without exclusion it takes so much. Can you help me there? See my asks above.

**Comment by LaraibKhan555** [comment]
Ok, I'm sharing MS Teams invite with you shortly.

**Comment by oshezaf** [comment]
Resolved a while ago.
