### ISSUE TITLE
VMware Carbon Black Cloud - Failing due to processing speed, Function app time out duration

### ISSUE THREAD

**Issue by cfbv** [Azure/Azure-Sentinel#6308]
**Describe the bug**
With larger carbon black environments where carbon black events are being brought in from S3, the function app will fail due events being generated in larger quantities than the function can handle. This results in not all events being processed before the function time out are hit (Default 5 minutes)

Increasing the function time out further than the interval will allow the function app to complete but creates an issue of other missed logs since the interval and timeout do not match. 

Increasing the function app ASP to a premium plan does not fix the issue. 

To fix the issue, there needs to be a way to have the function run faster, this may be a limitation with using PowerShell, and need to unzip all the files from S3. 

I looked at seeing if we could implement some type of parallel processing loop for this function app but was unable to get it to work. 

**To Reproduce**
1. Try to use the function app to bring in all events from a mid size environment (2000+ seats)

**Comment by v-rucdu** [comment]
@cfbv : This seems to be an old problem, and this connector may have already had numerous updates, can you please confirm if your problem has been solved? Thanks!!

**Comment by v-amolpatil** [comment]
hi @cfbv, based on previous comment closing this issue. Feel free to reopen issue if you still need assistance.  Thanks!
