### ISSUE TITLE
SensorId should be used instead of DeviceId

### ISSUE THREAD

**Issue by guarismo** [Azure/Azure-Sentinel#6332]
DeviceId adds the number ID of the device to the SensorId, it's better to use SensorId instead.
This happens on all the Analytic Rules for MDIoT

https://github.com/Azure/Azure-Sentinel/blob/ad9c873613a51da9a5f404addfe4359ace1200d4/Solutions/IoTOTThreatMonitoringwithDefenderforIoT/Analytic%20Rules/IoTNetworkScanning.yaml#L24
https://github.com/Azure/Azure-Sentinel/blob/ad9c873613a51da9a5f404addfe4359ace1200d4/Solutions/IoTOTThreatMonitoringwithDefenderforIoT/Analytic%20Rules/IoTNetworkScanning.yaml#L32
https://github.com/Azure/Azure-Sentinel/blob/ad9c873613a51da9a5f404addfe4359ace1200d4/Solutions/IoTOTThreatMonitoringwithDefenderforIoT/Analytic%20Rules/IoTNetworkScanning.yaml#L53

**Comment by v-vdixit** [comment]
@devikamehra, Can you please take a look at this, thanks!

**Comment by v-vdixit** [comment]
Since we have not received a response in the last 7 days, we are closing your issue as per our standard operating procedures. If you still need support for this issue, feel free to re-open at any time. Thank you for your co-operation.
