### ISSUE TITLE
O365API Logging Logic App errors

### ISSUE THREAD

**Issue by thetootall** [Azure/Azure-Sentinel#634]
I followed the configuration process to setup and install the logic app to feed data into the custom O365API Log Analytics logging source and read that when there is no data the "Parse JSON" step will fail with":

InvalidTemplate. Unable to process template language expressions in action 'Parse_JSON' inputs at line '1' and column '2868': 'The template language expression 'body('HTTP')[0]' cannot be evaluated because array index '0' cannot be selected from empty array. Please see https://aka.ms/logicexpressions for usage details.'.

It's super annoying because that means a majority of the runs will come back with a failure code.

However the times when there is data and gets to the "Send Data" step I'm finding that these inputs come back with the following as part of my raw OUTPUT:

"body": {
        "error": {
            "code": 400,
            "message": "A value for subdomain must be specified in token:username.",
            "source": "logic-apis-eastus.azure-apim.net",
            "path": "",
            "clientRequestId": xxxxxx
        }

When I look thru my raw INPUT i get the following:

{
    "method": "post",
    "headers": {
        "Log-Type": "O365API",
        "time-generated-field": "CreationTime"
    },
    "path": "/api/logs",
    "host": {
        "connection": {
            "name": "/subscriptions/xxxxxxxxxxxxxxxxxxxxxxx/resourceGroups/xxxxxxxxxx/providers/Microsoft.Web/connections/azureloganalyticsdatacollector-Get-O365Data"
        }
    },
  
Along with a large blob of data, so I know that its connecting to my tenant but its failing with the 400 error message.

Please advise

**Comment by dicolanl** [comment]
Hi @thetootall 
I think we have a bug.  Let me take it with @petebryan

**Comment by petebryan** [comment]
Thanks @thetootall we heard the feedback on the failure situation when there is no Teams data to parse, we will look at updating the logic app so that it has a conditional flow where if no data is returned it just ends the execution rather than failing.

With the "Send Data" step issue the input you are seeing is the correct format. Looking at the [API documentation](https://docs.microsoft.com/en-us/azure/azure-monitor/platform/data-collector-api) the most common cause of the 400 response is an issue with the content or the workspace. 
To help with this can you please check that the Send Data Step is correctly connected to the Workspace you have, also can you please confirm if the blob of data you are seeing being sent appears to be json data (it should be). In addition could you let us know what setting you have set of the Send Data step.

Its worth noting that the Send Data action is still in preview and we may just be seeing an issue with the action. One thing you could try is removing this step in the Logic App designer and re-adding it.

**Comment by thetootall** [comment]
@petebryan I checked in Designer view within the Logic App and it had a warning symbol,

![image](https://user-images.githubusercontent.com/19433966/80778557-6d7ebb80-8b2e-11ea-8f51-148f2ac4a512.png)

so I checked code view to cross reference:

    "parameters": {
        "$connections": {
            "value": {
                "azureloganalyticsdatacollector": {
                    "connectionId": "/subscriptions/**<subscriptionID>**/resourceGroups/**<resourceGroup>**/providers/Microsoft.Web/connections/azureloganalyticsdatacollector-Get-O365Data",
                    "connectionName": "azuresentinel-Get-O365Data",
                    "id": "/subscriptions/f**<subscriptionID>**/providers/Microsoft.Web/locations/**<location>**/managedApis/azureloganalyticsdatacollector"
                }
            }
        }
    }

Looking at the my Subscription ID, Resource Group name, and Location all of them look accurate.

So edited the step and here it was prompted to provide my workspace ID and workspace key in a new connection

![image](https://user-images.githubusercontent.com/19433966/80779670-fb0fda80-8b31-11ea-8a54-69ac7c84daa8.png)

After i saved the changes and generated some activity in Teams, I was able to see the logic app fire with Succeeded however then back to the known error with no data.

![image](https://user-images.githubusercontent.com/19433966/80779748-31e5f080-8b32-11ea-9b90-3483711ddd75.png)

One thing of note: I was not prompted for the workspace key when I deployed the Logic App Template at the bottom of this page - only the AAD App Client Id / App Secret / Tenant ID
https://github.com/Azure/Azure-Sentinel/tree/master/Playbooks/Get-O365Data

The Template did seem to do a good job of getting everything else setup - maybe adding additional info to specify the workspace info in a future version?

Thanks again for the help!

**Comment by dicolanl** [comment]
@thetootall got it.  I'm researching this now, 
 {
      "type": "Microsoft.Web/connections",
      "apiVersion": "2016-06-01",
      "location": "[parameters('logicAppLocation')]",
      "name": "[parameters('azureloganalyticsdatacollector-2_name')]",
      "properties": {
        "api": {
          "id": "[concat('/subscriptions/',subscription().subscriptionId,'/providers/Microsoft.Web/locations/',parameters('logicAppLocation'),'/managedApis/azureloganalyticsdatacollector')]"
        },
        "displayName": "[parameters('azureloganalyticsdatacollector-2_displayName')]",
        "parameterValues": {
          "username": "[parameters('azureloganalyticsdatacollector-2_username')]",
          "password": "[parameters('azureloganalyticsdatacollector-2_password')]"
        }
      }
    }

it appears i can provide workspace id and key as username and password parameters!

Im asking making many improvements to handle things like when no data is returned

**Comment by dicolanl** [comment]
@thetootall FYI.  Just submitted PR #639 
Note, i tried the above and it allowed me to pass the workspace id but not key.  so after deployment, as usual, you need to authorize the connections by going to the resource, click edit api connection.  click authorize or for log a enter the workspace key and click save.
which we shared here.
https://github.com/Azure/Azure-Sentinel/tree/master/Playbooks#each-folder-contains-a-security-playbook-arm-template-that-uses-microsoft-azure-sentinel-trigger
