### ISSUE TITLE
Create SNOW/JIRA tickets possibly broken

### ISSUE THREAD

**Issue by ArbalaSecurity** [Azure/Azure-Sentinel#638]
I was revisiting the deployment of the playbooks and it appears that it might be broken. The second step of the Playbooks (Alert - Get Incident) are showing [Operation not found under connector]

It seems that maybe that has been removed and its replacement is (Alert - Get Incident (Preview))

Trying to clean it up and make it work again doesn't seem to return the same results, however.  
The line [ "foreach": "@body('Alert_-_Get_incident')?['value']",] doesn't seen to be valid with the Get Incident - Preview.

I hope I am not just missing something obvious. I tried 2 totally separate instances.

Error
![image](https://user-images.githubusercontent.com/62150467/80771593-934d9580-8b19-11ea-9c64-30422dafd489.png)

Newer fields I can fill in
![image](https://user-images.githubusercontent.com/62150467/80769929-5c28b580-8b14-11ea-9b8f-3839db78c3f2.png)

For each Control "value" is not a valid option in dynamic content selection. Manually setting this makes it fail.
![image](https://user-images.githubusercontent.com/62150467/80770612-5af88800-8b16-11ea-9200-f8c9d34714a7.png)

**Comment by dicolanl** [comment]
Hi @ArbalaSecurity 
Did you authorize the connections first?  https://github.com/Azure/Azure-Sentinel/tree/master/Playbooks#each-folder-contains-a-security-playbook-arm-template-that-uses-microsoft-azure-sentinel-trigger

I just looked in our demo env and even thought he designer shows preview the code shows Alert_-_Get_incident

**Comment by ArbalaSecurity** [comment]
Yes, the APIs are authorized and connected. Do existing deployments still work and maybe not new ones? Thank you for the help. I can't find the object with out preview - is it possible that was deprecated?

**Comment by dicolanl** [comment]
Ill have to try and delete and re-deploy to confirm
