### ISSUE TITLE
Anomaly "Suspicious volume of AWS write API calls from a user account" title has a trailing space

### ISSUE THREAD

**Issue by ep3p** [Azure/Azure-Sentinel#6451]
**Describe the bug**
In ```Anomalies``` table, the events of the rule "Suspicious volume of AWS write API calls from a user account" in the column ```RuleName``` have a trailing space.

**To Reproduce**
1. Go to a LogAnalytics workspace with the Anomalies table, and some generated events of the Anomaly rule "Suspicious volume of AWS write API calls from a user account"
2. Run
```
Anomalies
| where RuleName endswith "Suspicious volume of AWS write API calls from a user account "
```
3. Observe the returned events of the mentioned rule.
4. Run
```
Anomalies
| where RuleName endswith "Suspicious volume of AWS write API calls from a user account"
```
5. Observe the previous events do not appear.

**Expected behavior**
The second query with no events should return events.

**Screenshots**
![image](https://user-images.githubusercontent.com/2527990/196868316-49923937-ae41-4268-b79b-480ebd7766c7.png)
![image](https://user-images.githubusercontent.com/2527990/196868442-4b018f4f-6955-401f-8342-d24ebc6ff795.png)

**Comment by ep3p** [comment]
Moreover, please, if you are going to contact the developer, tell them the query in ExtendedLinks[0]["DetailBladeInputs"] does not work.

They need to substitute the part:
```reverse(split(reverse(tostring(UserIdentityArn)),"/",0))```
by
```split(UserIdentityArn,"/",0)[-1]```.

**Comment by v-vdixit** [comment]
Hi @ep3p are you still facing this issue?

**Comment by ep3p** [comment]
Sorry @v-dixit I can't diagnose if this issue is still happening, because I have not received any event of this Anomaly type for a long time. The only way to know if this issue was resolved, would be to question the Anomaly team at Sentinel. This issue should be something that has happened in every Sentinel workspace.

**Comment by v-vdixit** [comment]
@ep3p thanks for your update we will connect with the Anomaly team and update you, thanks!

**Comment by v-vdixit** [comment]
Hi @ep3p we are discussing on this will update you shortly, thanks for your patience.

**Comment by v-vdixit** [comment]
Hi @ep3p we are working on this, will provide you update by end of this week, thanks!

**Comment by v-vdixit** [comment]
Hi @ep3p we are working with concerned team, will update you before end of this week, thanks!

**Comment by v-vdixit** [comment]
Hi @ep3p we are unable to find an instance where the rule name has trailing space, can you please confirm if this issue can be closed, we will keep an eye out for this error, thanks!

**Comment by ep3p** [comment]
Thank you very much to everyone.
