### ISSUE TITLE
AWS: Logon without MFA: incorrectly flags on SSO logon

### ISSUE THREAD

**Issue by hazcod** [Azure/Azure-Sentinel#6456]
**Describe the bug**

We currently have SSO enabled for logging onto our AWS acccounts.
Since this logon is federated to our identity provider, AWS does not see MFA authentication.
This results in having a lot of triggered 'Logon with MFA' (both realtime and scheduled) incidents.

**To Reproduce**
1. Create AWS accounts
2. Federate them to an identity provider
3. Setup AWS sentinel integration and enable 'Console logon without MFA' rules

**Expected behavior**
Rule not being triggered when SSO is being used.

**Comment by dneto82** [comment]
Hi @hazcod , seems in this case you can adjust your query rule to reflect this condition, like this:

`
| where SessionIssuerUserName !contains "AWSReservedSSO"
`

**Comment by hazcod** [comment]
@dneto82 thank you! Ill open a PR to get this fixed upstream.
