### ISSUE TITLE
MicrosoftInsiderRiskManagement. Microsoft Sentinel Analytics issue 

### ISSUE THREAD

**Issue by CliveWatsonQC** [Azure/Azure-Sentinel#6470]
**Describe the bug**

Source: https://github.com/Azure/Azure-Sentinel/tree/ee97399b426a21878776c4c7b4835efc04b47393/Solutions/MicrosoftInsiderRiskManagement/Analytic%20Rules

4 of the Analytic provided have the **Limit** operator (which is an alias of **Take**) 
https://learn.microsoft.com/en-us/azure/data-explorer/kusto/query/takeoperator
"**There is no guarantee which records are returned, unless the source data is sorted.**"

**To Reproduce**
1. Open any of these Analytics from the link above

**Expected behavior**
This code works today, only if data **less** that the limit of rows is returned but will provided false results if more than the limit of rows are returned.  
**Limit** is often used in testing, maybe the **top** operator would be a better choice: https://learn.microsoft.com/en-us/azure/data-explorer/kusto/query/topoperator

### Example, 
- If the rule detects 1 result and the limit is 10 then this is ok.

- However, if the rule detects 100 rows of data, and the limit is set to 25, 75% of the data will be ignored - as the order isn't _guaranteed_ this could mean some real issues are missed, and the next time a different set of 25 rows is returned.

**Screenshots**
![image](https://user-images.githubusercontent.com/96070044/197225859-dcd0bd06-c29c-4f56-b5bc-a110812cb96e.png)

![image](https://user-images.githubusercontent.com/96070044/197226801-3cc679e6-6c0e-4743-a55e-ceda85de4806.png)

**Comment by v-vdixit** [comment]
Hi @CliveWatsonQC are you still facing this issue, please confirm, thanks!

**Comment by clivewatson** [comment]
Yes, issue is still in the source code.  This was reported 5mths ago  +

![image](https://user-images.githubusercontent.com/19288031/236410164-3911e894-4e2b-4c04-998f-0dd9f36194b0.png)

**Comment by v-vdixit** [comment]
Hi @clivewatson we are working on updating the queries with grouping alerts, we will update you shortly, thanks for you patience and understanding.

**Comment by v-vdixit** [comment]
Hi @clivewatson we are working with the concerned team, will update you once we hear back from them, thanks!

**Comment by v-vdixit** [comment]
Hi @clivewatson we are working on updating the queries, will update you once the package is updated, thanks!

**Comment by v-vdixit** [comment]
Hi @clivewatson we are still working on changes, will update you by end of this week, thanks!

**Comment by v-vdixit** [comment]
Hi @clivewatson we have received suggestion from team that we should remove limit and group the alerts instead, the query will be summarized by incident number along with other parameters, we cannot use the top operator as it will still return the first N records sorted by the specified columns. Please check and confirm for us if your expected solution is inline with the grouping of alerts in these queries, thanks!

**Comment by v-vdixit** [comment]
Gentle Reminder: We are waiting for your response on this issue. If you still need to keep this issue active, please respond on it in the next 2 days. If we don't receive response, we will be closing this issue as per our standard procedures, thanks!

**Comment by CliveWatsonQC** [comment]
Yes confirmed, that's a sensible solution

**Comment by v-vdixit** [comment]
Thanks for confirming @clivewatson we will work on making these changes in all rules.

**Comment by v-vdixit** [comment]
Hi @clivewatson we are working on updating the queries with grouping alerts, we will update you shortly, thanks for your patience and understanding.

**Comment by v-vdixit** [comment]
Hi @clivewatson we are working on updating the queries with grouping alerts, we will update you shortly, thanks for your patience and understanding.

**Comment by v-vdixit** [comment]
Hi @clivewatson we have raised the PR with updated analytic rules, it is under review and the updates will be published once PR is merged, thanks!
