### ISSUE TITLE
Oracle Database Audit Event data naming mismatch 

### ISSUE THREAD

**Issue by TheCat1989** [Azure/Azure-Sentinel#6475]
Hi Team 

Since the update of the Oracle database audit parser change, the data types in the logs seems to be changed.
The change of the parser will make the old analytic rule and hunting query unusable.

for example in the parser, the SrcUserName is renamed as CURUSE
![image](https://user-images.githubusercontent.com/35518480/197493586-55e37983-6322-45ed-9843-cdcb325eb023.png)

however, in the analytic rules the attribute remained unchanged.

![image](https://user-images.githubusercontent.com/35518480/197494725-3f0329b5-751e-4e7c-917c-6ca34c0a0588.png)

**Comment by v-mchatla** [comment]
Hi @TheCat1989,
My team is working on fixing this issue. 
@NikTripathi - Can you please provide update once the Parser changes are live.
Thanks

**Comment by v-mchatla** [comment]
Hi @TheCat1989,
The parser is optimized and currently pending with certification process. We will share you the update once it's pushed to live. Meanwhile you can review the parser from this [link](https://github.com/Azure/Azure-Sentinel/blob/master/Solutions/OracleDatabaseAudit/Parsers/OracleDatabaseAuditEvent.txt).
Thanks

**Comment by v-mchatla** [comment]
Hi @TheCat1989,
Closing this incident as fixed. Please feel free to reopen the issue if you still need any further assistance on this.
Thanks
