### ISSUE TITLE
Add Host/IP/etc. To Watchlist - Incident Trigger issue

### ISSUE THREAD

**Issue by mbell85** [Azure/Azure-Sentinel#6487]
**Describe the bug**
I've been attempting to use these Playbook templates that are available in Sentinel/Automation to help keep track of users, ip addresses, hosts, etc via watch lists. The only requirement noted is that the playbook's managed identity must be granted the role of Microsoft Sentinel Contributor, which I've done. However, I'm finding that the logic apps are failing at the step where the watch list that doesn't exist yet is to be created. The errors received are:

{
  "error": {
    "code": 500,
    "source": "logic-apis-southcentralus.azure-apim.net",
    "clientRequestId": "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
    "message": "BadGateway",
    "innerError": {
      "status": 500,
      "message": "The given key was not present in the dictionary.\r\nclientRequestId: XXXXXXXXXXXXXXXXXXXXXXXXXXX",
      "error": {
        "message": "The given key was not present in the dictionary."
      },
      "source": "azuresentinel-scus.azconn-scus-001.p.azurewebsites.net"
    }
  }
}

**To Reproduce**
1. Go to 'any of the logic apps that are set up to create watch lists or add to existing watch lists.'
2. Click on 'any of the last failed jobs and select one, then resubmit the job. Wait for the job to complete.'
3. Select the failed job after completed and scroll down to the step called "Watchlists - Create a new watchlist with data.." and expand the output.
4. See error mentioned above.

**Expected behavior**
For a non-existent watchlist to be created with the data intact from the logic app.

**Comment by mbell85** [comment]
I found the solution in another user's past question here: https://github.com/Azure/Azure-Sentinel/issues/5040#issuecomment-1152247689

Basically the JSON needed a little tweaking compared to what was provided out of the box in the Azure Sentinel -> Automation -> Playbook Templates page.

This is what got it to work:

[Graphical user interface, text, application, Teams  Description automatically generated]

--

Mark Bell
IT Administrator
Journeys in Community Living
1130 Haley Rd.
Murfreesboro, TN 37129
615-890-4389, ext. 45 (ofc)
615-295-3046 (cell)
www.journeystn.org<http://www.journeystn.org/>
www.fb.com/journeysincommunity<http://www.fb.com/journeysincommunity>
www.twitter.com/journeystn<http://www.twitter.com/journeystn>

NOTICE: This email may contain confidential (including but not limited to) HIPAA-protected and/or privileged information intended only for specific, predetermined recipients. If you are not the intended recipient, you are hereby notified that any review, further dissemination, distribution or duplication of this communication is STRICTLY FORBIDDEN. Please delete and/or destroy all copies of this message after notifying Mark Bell of the error by reply email or calling 615-295-3046.

**Comment by v-vdixit** [comment]
Hi @mbell85 as per your last comment, we hope your issue has been resolved, we are closing this issue as completed, if you are still facing this issue, feel free to reopen, thanks!
