### ISSUE TITLE
Unclarity around Azure Information Protection dataconnector

### ISSUE THREAD

**Issue by hazcod** [Azure/Azure-Sentinel#6489]
**Describe the bug**

The dataconnector page for Azure Information Protection (Preview) mentions it's going to be replaced by the [Microsoft 365 auditing solution](https://docs.microsoft.com/microsoft-365/compliance/auditing-solutions-overview?WT.mc_id=Portal-fx), but there is no mention of Sentinel integration there.

This is since March 18, 2022, which makes me believe the dataconnector has been broken since then.

![image](https://user-images.githubusercontent.com/5222512/198099834-f80901ca-2a59-46b2-8afe-a0ad1743f81b.png)

**Comment by hazcod** [comment]
@NikTripathi FYI would be interesting if you could chime in here since you merged https://github.com/Azure/Azure-Sentinel/pull/4994.

**Comment by v-rbajaj** [comment]
Hi @hazcod, we raised a PR for deprecating Azure Information Protection, once the PR is merged, will let you know. 
I hope that solves your concern. 
Please let us know if in case you have further questions.

**Comment by hazcod** [comment]
What is the replacement dataconnector @v-rbajaj ?

**Comment by v-rbajaj** [comment]
Hi @hazcod, The replacement is Microsoft Information Protection.

**Comment by v-rbajaj** [comment]
Hi @hazcod, PR https://github.com/Azure/Azure-Sentinel/pull/7866 has been merged. Closing this issue.
