### ISSUE TITLE
Cisco Umbrella Data Connector - Add function to fetch Admin Audit events

### ISSUE THREAD

**Issue by rraj1996** [Azure/Azure-Sentinel#6501]
Hi Folks,

Thank you in advance .

We've Cisco Umbrella admin audit logs written to S3 bucket but I guess the Azure function doesn't fetch it though.

Can anyone help me with the changes in the code that I am supposed to do to get the same in Sentinel.

Regards.

**Comment by v-rbajaj** [comment]
Hi @rraj1996, are you still facing this issue?

**Comment by v-rbajaj** [comment]
Gentle Reminder: We are awaiting for your response on this issue. If you still need to keep this issue active please respond on it in the next 2 days. If we don't receive response, we will be close this issue.

**Comment by v-rbajaj** [comment]
Since we have not received a response in the last 5 days, we are closing your issue https://github.com/Azure/Azure-Sentinel/issues/6501 as per our standard operating procedures. If you still need support for this issue, feel free to re-open at any time. Thank you for your co-operation.
