### ISSUE TITLE
Azure Devops Pull Request Bypass does not mention pull request

### ISSUE THREAD

**Issue by hazcod** [Azure/Azure-Sentinel#6502]
**Is your feature request related to a problem? Please describe.**

The current rule that triggers an incident in Sentinel when Microsoft Azure DevOps audit log mentions a pull request bypass does not mention the pull request itself in the entities list, only the user.

**Describe the solution you'd like**
The pull request URL to be mentioned in the entities.

**Comment by v-prasadboke** [comment]
Hello hazcod 
Can you please elaborate this issue you are facing

**Comment by hazcod** [comment]
The incident created for this rule does not have the actual link to the pull request in the entities.

**Comment by v-amolpatil** [comment]
@hazcod Could you please specify which analytic rule you are taking about? Also could you please provide us an screenshot of error if available so that it will help us to investigate more.
Thanks!

**Comment by hazcod** [comment]
@v-amolpatil : `Azure DevOps Pull Request Policy Bypassing`.
This rule detection never mentions the pull request title as an entity.

**Comment by v-amolpatil** [comment]
Hi @hazcod, We have deployed latest version with change and is available in Marketplace. Hence closing the issue. Feel free to reopen if you need any assistance.
