### ISSUE TITLE
Could not add this repo to Sentinel

### ISSUE THREAD

**Issue by TheCat1989** [Azure/Azure-Sentinel#6514]
Steps to reproduce
Fork this Sentinel github repo into my repository

click on the "+Add new" option and create a connection in the repo tab 

![image](https://user-images.githubusercontent.com/35518480/198952233-e36d1302-5351-410e-8992-d9079dccc405.png)

Select the content type as analytic rules

![image](https://user-images.githubusercontent.com/35518480/198952167-dae4bada-3ec8-49ab-a585-5bd54c879b9d.png)

Hit deploy and returns the following error

![image](https://user-images.githubusercontent.com/35518480/198952260-50fa0a24-249a-4718-b9fd-0969fbb6e22b.png)

from the github's perspective.

![image](https://user-images.githubusercontent.com/35518480/198952337-43c98507-4263-4ea0-867f-b9295e74a811.png)

more interestingly, if we create a new repo only contains the analytic rule template, the deployment would be success,

BUT the no analytic rules was deployed to the workspace

Expected behavior
it should sync the content from the github repo to the sentinel workspace.

Actual behavior
Deployment failed

**Comment by v-rbajaj** [comment]
Hi @TheCat1989, Thanks for flagging this. Are you still facing this issue?

**Comment by v-rbajaj** [comment]
Gentle Reminder: We are awaiting for your response on this issue. If you still need to keep this issue active please respond on it in the next 2 days .If we don't receive response, we will be close this issue.

**Comment by v-rbajaj** [comment]
Since we have not received a response in the last 5 days, we are closing your issue https://github.com/Azure/Azure-Sentinel/issues/6514 as per our standard operating procedures. If you still need support for this issue, feel free to re-open at any time. Thank you for your co-operation.
