### ISSUE TITLE
Create Solution Tool: Add support for inputfile as a parameter

### ISSUE THREAD

**Issue by dicolanl** [Azure/Azure-Sentinel#6549]
Today, when running the createSoluiton.ps1 the input file must be in \Tools\Create-Azure-Sentinel-Solution\input.  Recommend adding a parameter to the script -inputfile where the user can specify the location of the input file.  Input files can then be stored in the Solutions\<solution> folder.  They can easily be updated by the solution owner for preparing a package.

**Comment by v-mchatla** [comment]
Hi @dicolanl,
Thanks for reaching out to us. I will check with team on feasibility and respond back.
Thanks

**Comment by v-vdixit** [comment]
Hi @dicolanl We wanted to check on the status of Issue #6549. The issue is pending for more than expected days. Please let us know if you need any assistance to review this Issue. As per our standard operating procedures if no response is received in the next 7 business days, we will close this Issue. Thank you for your cooperation.

**Comment by dicolanl** [comment]
hi @v-vdixit no progress has been made.  @v-mchatla  was going to check with the team but never responded.

**Comment by v-vdixit** [comment]
Hi @dicolanl we are working on this with the concerned team will update you shortly, thanks for your patience.

**Comment by v-rbajaj** [comment]
Hi @dicolanl, respective team has made necessary changes in the script which will be live in next upcoming weeks which will solve this issue.

**Comment by dicolanl** [comment]
Great!!!

**Comment by v-rbajaj** [comment]
Hi @dicolanl, The changes have been pushed to master, the input file is passed as a parameter now. 
Feel free to reopen the issue in case of further questions.
