### ISSUE TITLE
ProofPoint POD

### ISSUE THREAD

**Issue by sunchippss** [Azure/Azure-Sentinel#6564]
We installed the ProofPoint POD preview solution last week.

Since then we've been having a issues with our LAW stating:

The following fields' values msgParts of type ProofpointPOD_message have been trimmed to the max allowed size, 32766 bytes. Please adjust your input accordingly. (1)

![workspaceError](https://user-images.githubusercontent.com/97361654/200008892-4a073fc5-5017-47c4-83dd-61a55e6f50bb.PNG)

**Comment by funzel1** [comment]
same issue

**Comment by sunchippss** [comment]
Still having the same issue.

**Comment by NikTripathi** [comment]
Hi @sunchippss We have created a Bug Item to track this issue [Bug 16217592](https://msazure.visualstudio.com/One/_workitems/edit/16217592): ProofPoint POD preview solution.

You can track this on the above provided URL. @manishkumar1991 Is already working on this.

Thanks.

**Comment by funzel1** [comment]
We have the same issue, looks like the count of activity definitions is too high, so we have splitted the api in several parallel solutions for example one for Forms only.

**Comment by manishkumar1991** [comment]
@sunchippss :
Can you please share the raw logs of Proofpoint here , so that we can investigate and check that at which point the message is getting trimmed .

**Comment by v-rbajaj** [comment]
Hi @sunchippss, Gentle Reminder: We are awaiting for your response on this issue. If you still need to keep this issue active please respond on it in the next 2 days. If we don't receive response by given date we will be close this issue.

**Comment by v-rbajaj** [comment]
Hi @sunchippss, Since we have not received a response in the last 5 days, we are closing your issue https://github.com/Azure/Azure-Sentinel/issues/6564 as per our standard operating procedures. If you still need support for this issue, feel free to re-open at any time. Thank you for your co-operation.
