### ISSUE TITLE
Raise version on data connector for SentinelOne from ~3 to ~4 

### ISSUE THREAD

**Issue by infernuxmonster** [Azure/Azure-Sentinel#6567]
**Is your feature request related to a problem? Please describe.**
The current SentinelOne data connector is deployed as a version 3 app, which should be upgraded by dec 3rd. Doing a raw update in place (change ~3 to ~4) does not work as it will throw errors with low versions of dependencies.

**Describe the solution you'd like**
Upgrade the package and files for the data connector in the official Azure repo.

**Describe alternatives you've considered**
Download the files and upgrade it myself, then self-publish to my own github-repo and point to that in the website run from package var.

**Additional context**

**Comment by v-mchatla** [comment]
Hi @infernuxmonster,
Thanks for raising the concern. We will be adding it to our backlog item and provide you the update once we are done with the changes.
Thanks

**Comment by v-mchatla** [comment]
Hi @infernuxmonster,
Our team has completed the requested change as part of this [PR](https://github.com/Azure/Azure-Sentinel/pull/6592). So, we are closing this ticket, please feel free to reopen the issue, if you still need any support.
Thanks
