### ISSUE TITLE
Trend Micro parser function missing -space- with DeviceVendor

### ISSUE THREAD

**Issue by ryangto** [Azure/Azure-Sentinel#658]
**Describe the bug**
Trend Micro connector set up at step 2.5 to perform a save of the function has a typo at DeviceVendor == "TrendMicro".  It should be DeviceVendor=="Trend Micro" and then ingested Trend Micro logs will associate correctly with the connector.  Not sure if it's based on the version or not but with our version the column for Device Vendor has a space.

**To Reproduce**
1. Go to Connector --> Trend Micro --> Step 2.5 Make sure to save the TrendMicroDeepSecurity function so that it queries the Trend Micro data properly.
2. Try running the function and receive 0 results (screenshot below)

**Expected behavior**
Modified the function by adding a -space- between Trend Micro and associated logs with the new function work as expected.

**Screenshots**
![image](https://user-images.githubusercontent.com/36899116/81171599-a1ad0e80-8f6a-11ea-9c3a-21742455e31c.png)

![image](https://user-images.githubusercontent.com/36899116/81173620-5c8adb80-8f6e-11ea-8c6c-bb94ee6f5a67.png)

![image](https://user-images.githubusercontent.com/36899116/81173977-f5215b80-8f6e-11ea-9c54-3bb6ff469e82.png)

**Comment by shainw** [comment]
@ryangto - thanks for the feedback. I will have to test, but think to have backward compat, we may just add this - | where DeviceVendor has_any ("TrendMicro", "Trend Micro").  We will test and confirm.

**Comment by shainw** [comment]
Associated PR - https://github.com/Azure/Azure-Sentinel/pull/665
