### ISSUE TITLE
Defender for Office connector creates streaming API without AlertInfo

### ISSUE THREAD

**Issue by hazcod** [Azure/Azure-Sentinel#6616]
**Describe the bug**

Using the native (codeless) Defender for Office in Sentinel creates a Defender for Office streaming API without AlertInfo.
I believe this will make us miss important alerts.

![image](https://user-images.githubusercontent.com/5222512/201624351-d3006cab-5257-48bd-81ec-10e3e8f464a6.png)

**To Reproduce**
1. Enable `Defender for Office` Dataconnector in Sentinel.
2. Got to https://security.microsoft.com/settings/mtp_settings/raw_data_export
3. Notice `AlertInfo` not being enabled.

**Expected behavior**
AlertInfo enabled.

**Comment by v-vdixit** [comment]
Hi @hazcod are you still facing this issue, please confirm, thanks!

**Comment by hazcod** [comment]
Yes, nothing changed about the connector.

**Comment by v-vdixit** [comment]
Hi @hazcod thanks for your patience and understanding, we are discussing with the author of the connector regarding this issue, will update you shortly.

**Comment by v-vdixit** [comment]
Hi @hazcod we are working with the concerned team, will update you once we hear back from them, thanks!

**Comment by v-vdixit** [comment]
Hi @hazcod to use the Defender for Office streaming API with AlertInfo, please ensure that you have followed all steps mentioned in the documentation and that all pre requisites are met, please check the documentation here - [Microsoft Defender for Office 365 connector for Microsoft Sentinel](https://github.com/MicrosoftDocs/azure-docs/blob/main/articles/sentinel/data-connectors/microsoft-defender-for-office-365.md), thanks!

**Comment by v-vdixit** [comment]
Gentle Reminder: We are waiting for your response on this issue. If you still need to keep this issue active, please respond on it in the next 2 days. If we don't receive response, we will be closing this issue as per our standard procedures, thanks!

**Comment by v-vdixit** [comment]
Since we have not received a response in the last 5 days, we are closing your issue as per our standard operating procedures. If you still need support for this issue, feel free to re-open at any time. Thank you for your co-operation

**Comment by DevSecNinja** [comment]
If anyone else runs into this, make sure that under the Defender XDR data connector in Sentinel, "AlertInfo" is selected under "Microsoft Defender Alerts".
