### ISSUE TITLE
PBI Dashboard appears broken

### ISSUE THREAD

**Issue by kraken8585** [Azure/Azure-Sentinel#6644]
**Describe the bug**
Launching the pbit file returns an 404 error for the aadusers and recommendation table.

**To Reproduce**
Download PBIT file and launch it with Power BI

**Expected behavior**
All dashboard should load correctly without an error in retrieving the data from Defender API

**Screenshots**

**Desktop (please complete the following information):**
PowerBI for desktop

**Additional context**
**GitHub reference 
https://github.com/Azure/Azure-Sentinel/tree/master/Tools/M365-PowerBi%20Dashboard

Sample error when trying to connect to the ODATA feed

Microsoft.Mashup.Engine1.Library.Resources.HttpResource: Request failed: OData Version: 3 and 4, Error: The remote server returned an error: (404) Not Found. (Not Found) OData Version: 4, Error: The remote server returned an error: (404) Not Found. (Not Found) OData Version: 3, Error: The remote server returned an error: (404) Not Found. (Not Found)

**Comment by v-rbajaj** [comment]
Hi @kraken8585, are you still facing this issue? I have checked the link in the additional context of the issue - the file is no longer present.

**Comment by v-rbajaj** [comment]
Hi @kraken8585, Gentle Reminder: We are awaiting for your response on this issue. If you still need to keep this issue active please respond on it in the next 2 days. If we don't receive response by given date we will be close this issue.

**Comment by v-rbajaj** [comment]
Hi @kraken8585, Since we have not received a response in the last 5 days, we are closing your issue https://github.com/Azure/Azure-Sentinel/issues/6644 as per our standard operating procedures. If you still need support for this issue, feel free to re-open at any time. Thank you for your co-operation.
