### ISSUE TITLE
The O365 Connector does not include auditlogs from Teams & Skype for Business

### ISSUE THREAD

**Issue by JeroenMvS** [Azure/Azure-Sentinel#666]
All documentation indicates that you are able to select whatever O365 activity you want to send to Sentinel, but in my environment and all demo's I have seen I can only select Exchange & SharePoint and no data from Teams etc.
Can anyone please confirm if only Exchange & SharePoint are supported?
If thats the case, does anyone know when all O365 audit logs, in particular Teams, will be available?

**Comment by dicolanl** [comment]
Hi @JeroenMvS 
Thats correct.  today we only get Ex+SP via the office connector.  We are working on native connectors for other services like teams.

In the short term, we have solutions you can use
https://github.com/Azure/Azure-Sentinel/tree/master/Playbooks/Get-O365Data - Logic App Playbook to get O365 Data.
https://github.com/Azure/Azure-Sentinel/tree/master/DataConnectors/O365%20Data - Azure Function to get O365 Data

**Comment by JeroenMvS** [comment]
Thanks for the quick and useful reply!
