### ISSUE TITLE
Cisco DUO Connector function app - Reference Bundle requires updating

### ISSUE THREAD

**Issue by chanster** [Azure/Azure-Sentinel#6664]
**Describe the bug**
CiscoDuo Connector does not deploy correctly

```
Microsoft.Azure.WebJobs.Script: Referenced bundle Microsoft.Azure.Functions.ExtensionBundle of version 1.8.1 does not meet the required minimum version of 2.6.1. Update your extension bundle reference in host.json to reference 2.6.1 or later. For more information see https://aka.ms/func-min-bundle-versions.
```

**To Reproduce**
1. Go to your Function Apps
2. Click on CiscoDuo app that was deployed
3. View the Overview Page

**Expected behavior**
After deploying connector, logs should begin ingesting from DUO.

**Screenshots**
![image](https://user-images.githubusercontent.com/232767/202288823-70e0e3b4-1025-481c-b9ff-dffa70f6b678.png)

**Desktop (please complete the following information):**
 - OS: MacOS 12.5.2
 - Browser: Chrome
 - Version: `107.0.5304.110`

**Additional context**
Previous deployment is working, but stating to upgrade before Dec 3.
<img width="570" alt="image" src="https://user-images.githubusercontent.com/232767/202289151-538e90ef-1069-46de-ab3e-151c35d0331a.png">

**Comment by v-mchatla** [comment]
Hi @chanster,
Thanks for contacting us. Our team is currently working on the bulk update for all the solutions. We will let you know once the changes are live.
Thanks

**Comment by v-mchatla** [comment]
Hi @chanster,
This is fixed and the function app is running without any issue. Closing the issue as its fixed please feel free to reopen it if you need any further assistance.
![image](https://user-images.githubusercontent.com/108806639/207566938-38edbdac-2722-4dcb-92ec-9553da39a508.png)

Thanks
