### ISSUE TITLE
Granting_Permissions_To_Account_detection error

### ISSUE THREAD

**Issue by noapocalypse** [Azure/Azure-Sentinel#6681]
ON deploying the above rule in sentinel via the gui.
![image](https://user-images.githubusercontent.com/6807001/202667171-283dcae4-e410-4a22-ac4b-9348ab944928.png)
'summarize' operator: Failed to resolve table or column expression named 'IdentityInfo'.
This error is returned on the set rule logic tab.

Whilst i assume the error is due to not having UEBA turned on the rule exists within the templates for the Azure Activity connector - it may be worth adding a note with regards pre-requisites for this specific template. Previous versions of the template did not call to this table (i've only identified it when attempting to update to the latest).

Apologies if this is just user error

**Comment by v-vdixit** [comment]
Hi @noapocalypse we have checked if we have data available for 'Identity Info' in the workspace we are creating the rule in, the query will work as expected, we would take up your suggestion and add pre- requisites note for this case in our next package update, most likely, thanks!

**Comment by v-vdixit** [comment]
Gentle Reminder: We are awaiting for your response on this issue. If you still need to keep this issue active please respond on it in the next 2 days. If we don't receive response by given date we will close this issue as per our standard procedure, thanks!

**Comment by noapocalypse** [comment]
Ah yeah, that's cool adding it to the pre-reqs is a good shout. If you can get that to pop up in the Review and update section on Sentinel that'll be great - Ideally having rules like this flagged with something different than update available would be useful as well - or having them flag with update available but with a keyed colour to represent that something is missing in the environment  so as such it's as update as it can be for the given env. would also be great.

**Comment by v-vdixit** [comment]
Hi @noapocalypse thanks for these suggestions we will keep a note of these for our next solution updates, as your issue has been resolved I am closing this, feel free to reopen if you have any further queries, thanks!
