### ISSUE TITLE
Dataconnector: Cisco Stealthwatch 

### ISSUE THREAD

**Issue by patrickboeck** [Azure/Azure-Sentinel#6703]
**Describe the bug**
There is an issue/typo in the current Cisco Stealthwatch Connector from the Content Hub.
Into the Connector Instructions there is the Template for the custom logformat which must be configured on the Applicane. But into the template there is a missing **"t"**
Wrong:
_argetHG={target_host_group_names}_

Correct:
_**t**argetHG={target_host_group_names}_

**To Reproduce**
1. Go to 'Data connectors \ Cisco Stealthwatch
2. Click on 'Instructions'
3. Scroll down to '2. Configure Cisco Stealthwatch event forwarding'

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/47869600/203294824-0d08f0d1-7440-40df-9e47-489ab72a514e.png)

**Additional context**

**Comment by v-vdixit** [comment]
Hi @patrickboeck please install the latest version of the solution and close the issue if it is resolved. Thanks!

**Comment by v-vdixit** [comment]
The issue has been fixed. That is why it is closed. Thanks!
