### ISSUE TITLE
ASIM NetworkSession for Windows sysmon parser

### ISSUE THREAD

**Issue by Gareze** [Azure/Azure-Sentinel#6705]
Currently there seems to be only a Linux parser for network session for sysmon (ASimNetworkSessionMicrosoftLinuxSysmon.yaml) which seems odd as Windows sysmon has been around for much longer than Linux.

Under the section "ASIM parsers for Sysmon for Windows" you also list the linux version ( vimNetworkSessionLinuxSysmon) of the parser which should be corrected as this is clearly looking for syslog data.

Could you please advise if the ASIM NetworkSession for windows sysmon is in the pipeline and when it will be released?

Thanks

**Comment by devikamehra** [comment]
@Gareze Thank you so much for raising this issue in the documentation. It should be fixed now.

For the Windows Sysmon ASIM Parser, our team is already on it and should be available in near future.

**Comment by v-amolpatil** [comment]
Closing this issue as this is already resolved.
