### ISSUE TITLE
Arista NDR: Grouping  is not applicable in analytic rules

### ISSUE THREAD

**Issue by adarshb20** [Azure/Azure-Sentinel#6708]
**Describe the bug**
Unable to see the `Grouping logic` and `Grouping period` in analytic rules for the Arista NDR (formerly Arista Networks Awake Security) solution.

**To Reproduce**
1. Add Arista NDR solution to Microsoft Sentinel
2. Go to Analytic Rules
3. Select any rules added by the solution (starts with "Awake Security")
4. The rules won't show the `Grouping logic` and `Grouping period`.

**Expected behavior**
`Grouping logic` and `Grouping period` must be applicable once we add the solution.

**Screenshots**
<img width="364" alt="With Grouping" src="https://user-images.githubusercontent.com/18482538/203370362-dfe31e99-5d16-4822-adb2-6fa5d8b82e95.png">
<img width="353" alt="Solution imported" src="https://user-images.githubusercontent.com/18482538/203370466-d1d332f8-df13-4d90-96ea-3c631c4944d1.png">

**Desktop (please complete the following information):**
 - OS: Mac OS 12
 - Browser: Chrome
 - Version: 107

**Smartphone (please complete the following information):**
 - Device: NA
 - OS: NA
 - Browser: NA
 - Version: NA

**Additional context**
The analytic rules are available [here](https://github.com/Azure/Azure-Sentinel/tree/master/Solutions/AristaAwakeSecurity/Analytic%20Rules).
We have the grouping configuration in the yaml file but it is not working as expected.

**Comment by yew011** [comment]
Kindly raise this issue.  Would like to get answer asap.  Thx in advance.

**Comment by v-vdixit** [comment]
Hi @adarshb20, are you still facing this issue?

**Comment by adarshb20** [comment]
Yes, just confirmed it is not grouping.
it would be very helpful, if you could help us validate the [analytic rules](https://github.com/Azure/Azure-Sentinel/tree/master/Solutions/AristaAwakeSecurity/Analytic%20Rules) to know if there's a configuration mismatch.

**Comment by v-vdixit** [comment]
Hi @adarshb20 Can you please check if while creating the rule you have enabled the rule in basics tab and then further enabled grouping in Incident settings tab, thanks!
![image](https://github.com/Azure/Azure-Sentinel/assets/115772287/0358c0d2-cbad-49b0-9b1d-789c10e4c0e8)

**Comment by adarshb20** [comment]
1. Can't we enable that with the use of yaml in the solution
2. even if it is enabled, the configuration for grouping logic and period has default values and not the one as specified in the yaml

**Comment by v-vdixit** [comment]
Hi @adarshb20 we are checking with the concerned team, will provide you details once we hear back from them, thanks!

**Comment by v-vdixit** [comment]
Hi @adarshb20 can you try deploying the query with the Azure Rest API and check if the grouping shows enabled in that case?

**Comment by v-vdixit** [comment]
Gentle Reminder: We are waiting for your response on this issue. If you still need to keep this issue active, please respond on it in the next 2 days. If we don't receive response, we will be closing this issue as per our standard procedures, thanks!

**Comment by adarshb20** [comment]
It works via REST API

**Comment by v-vdixit** [comment]
Thanks for confirming, we will check for the error in deployment with solution, thanks!

**Comment by v-vdixit** [comment]
Hi @adarshb20 we are working with the team internally on packaging tool and comparing the code of analytic rules for Rest API and template to trace the cause of error, will update you by next week, thanks for your patience.

**Comment by v-vdixit** [comment]
Hi @adarshb20 we are still working on packaging updates with the team, will update you once done, thanks!

**Comment by adarshb20** [comment]
thanks for the update @v-vdixit

**Comment by v-vdixit** [comment]
Hi @adarshb20 we are working on this solution packaging with latest updates in our packaging tool, the changes will be updated shortly, thanks!

**Comment by v-vdixit** [comment]
We are working on this solution packaging with latest updates in our packaging tool, the changes will be updated shortly, thanks!

**Comment by v-vdixit** [comment]
Hi @adarshb20 there have been some changes in our packaging tools and UI and as I can see the grouping is enabled now for queries after creation, adding screenshot for your reference, thanks! 

![image](https://github.com/Azure/Azure-Sentinel/assets/115772287/e25d76a7-efb7-4f62-9018-4f8f805c077c)

We are closing this issue as this has been resolved, feel free to reopen if you still face this issue.

**Comment by adarshb20** [comment]
@v-vdixit, I just tried to verify by redeploying our solution, although in the template the grouping does show enabled but it fails while we create the rule with the template with incorrect lookback duration error as below 
<img width="609" alt="image" src="https://github.com/Azure/Azure-Sentinel/assets/18482538/100a0c56-67f8-426e-b99b-4d928e86b99d">

We do have  lookback duration set as 3d in all rules, e.g. here https://github.com/Azure/Azure-Sentinel/blob/a26f467de06ed6d4199edde188afec85a7e6bdf9/Solutions/AristaAwakeSecurity/Analytic%20Rules/HighMatchCountsByDevice.yaml#L58C23-L58C25

**Comment by v-vdixit** [comment]
Hi @adarshb20 the new UI allows you to adjust lookback duration manually, it's as per the user's choice to add lookback duration even if it's different from what is entered in the rule, thanks!

**Comment by adarshb20** [comment]
I see, looking good then, thanks for all the help! @v-vdixit
