### ISSUE TITLE
Get-IPReputation

### ISSUE THREAD

**Issue by akefallonitis** [Azure/Azure-Sentinel#671]
Trying to use the Get-IPReputation playbook and although deployed successfully and added connections i get error when i try to run it on the Alert - Get incident part (Not found - response 404)

When i am trying to update the connections i get this error:

Failed to save logic app Get-IPReputation. Some of the connections are not authorized yet. If you just created a workflow from a template, please add the authorized connections to your workflow before saving.

And i am not allowed to save.

Am i missing something ?

**Comment by akefallonitis** [comment]
Guessing its related to this step:

![image](https://user-images.githubusercontent.com/24274227/81688962-97a37800-9462-11ea-83dc-c27a3bab5ae9.png)

So what parameters needed to be added there ?

**Comment by dicolanl** [comment]
@akefallonitis https://github.com/Azure/Azure-Sentinel/tree/master/Playbooks#each-folder-contains-a-security-playbook-arm-template-that-uses-microsoft-azure-sentinel-trigger

you must authorize connections after deployment.  see the readme link above.  there is no way to do this via ARM so it has to be done manually.

**Comment by akefallonitis** [comment]
Ty @dicolanl as for the step in the screenshot why it it needed ?

**Comment by dicolanl** [comment]
@akefallonitis when you go authorize the step you will need to add the workspace key.  this step is used to save the results of the virus total query back to log analytics.
