### ISSUE TITLE
Block-AADUser

### ISSUE THREAD

**Issue by akefallonitis** [Azure/Azure-Sentinel#674]
Hey,

I am trying to implement the Block-AADUser logic app but i get an error on the Alert - Get incident step :

 

 

{
  "error": {
    "code": 400,
    "source": "logic-apis-northeurope.azure-apim.net",
    "clientRequestId": "adc961ce-781a-406b-9f24-f02580e7f386",
    "message": "The response is not in a JSON format.",
    "innerError": "Invalid subscription id or resource group"
  }
}

 

As i validated all the parameters and permissions seem correct i don't know what i am doing wrong.

Anyone had any similar issue ? Any fix ?

**Comment by dicolanl** [comment]
@akefallonitis  could you share a screen shot of the error?

**Comment by preetikr** [comment]
Closing owing to no-activity. @akefallonitis - Please reactivate once you have the screenshot of the error for further action on this. Thanks.
