### ISSUE TITLE
Cisco Umbrella Connector broken since #6675

### ISSUE THREAD

**Issue by dev-sec7** [Azure/Azure-Sentinel#6781]
**Describe the bug**
The Cisco Umbrella (Preview) Data Connector deployment in Microsoft Sentinel results in error "Azure Functions runtime is unreachable" when deployed from the latest master ARM template within Azure Portal

**To Reproduce**
1. Deploy Cisco Umbrella (Preview) Data Connector from within Microsoft Sentinel

**Expected behavior**
The data connector should deploy and run successfully.

**Screenshots**
![image](https://user-images.githubusercontent.com/105065107/205131644-33d5e23f-f7a9-409b-bc97-2488037d33fd.png)

**Additional context**
This issue was caused by updates to the function runtime version to ~4
https://github.com/Azure/Azure-Sentinel/pull/6675

**Comment by willheineman** [comment]
I bet this is the same issue as https://github.com/Azure/Azure-Sentinel/issues/6786 and https://github.com/Azure/Azure-Sentinel/issues/6785

This function refers to a .zip file in GitHub, but someone reorganized the repo and moved that file! Line 160 in the deployment script shows this: https://github.com/Azure/Azure-Sentinel/blob/a5c6a759146d06e4be39b549b1b19c0e3ec985fe/Solutions/CiscoUmbrella/Data%20Connectors/azuredeploy_CiscoUmbrella_API_FunctionApp.json#L160

I suspect you can fix this by doing 2 things
1. Editing your function app to change the Function Runtime Version back to `~3` 
2. Change the value of `WEBSITE_RUN_FROM_PACKAGE` to `https://github.com/Azure/Azure-Sentinel/blob/master/Solutions/CiscoUmbrella/Data%20Connectors/CiscoUmbrellaConn.zip?raw=true`

**Comment by ashishsyal** [comment]
We are looking into this.

**Comment by ashishsyal** [comment]
@dev-sec7 - Please update if you already resolved with steps shared by @willheineman . We will also take a look as it is on our radar.

**Comment by dev-sec7** [comment]
> @dev-sec7 - Please update if you already resolved with steps shared by @willheineman . We will also take a look as it is on our radar.

@ashishsyal  The change that broke the Cisco Umbrella connector function app was the update to the Function Runtime Version to ~4.  This is a needed change since version ~3 will not be supported after December 3rd 2022.  

Issue #6786 was created as a duplicate of this just a few hours later
issue #6785 is referencing a different Data Connector with a similar issue to #5995 which has been closed

Changing the function runtime back to version ~3 will allow the function to execute but it is not a supportable resolution.  

I didn't find any need to change the value of WEBSITE_RUN_FROM_PACKAGE as the value https://aka.ms/sentinel-CiscoUmbrellaConn-functionapp in the latest version seems to be working just fine.

**Comment by v-rucdu** [comment]
@dev-sec7  : the PR containing the fix has been merged. In order to make it work please reinstall the function from the Connector Page.

Apologies for the inconvenience caused... Thanks!!!
