### ISSUE TITLE
'Incorrect header check' error in Imperva Cloud WAF Azure Function App

### ISSUE THREAD

**Issue by rcegan** [Azure/Azure-Sentinel#6784]
The Imperva Cloud WAF Azure Function is no longer functional. The function deploys and runs okay, however even with correct API configuration no logs are brought into the log analytics workspace. I can see errors in the `traces` logs in application insights for the function app: (partially redacted logs)

```
12/1/2022, 11:20:22.741 PM Downloading file 10x_3513xxx.log
12/1/2022, 11:20:23.181 PM Successfully downloaded file: 10x_3513xxx.log
12/1/2022, 11:20:24.346 PM Unpacking and decrypting file 10x_3513xxx.log
12/1/2022, 11:20:24.357 PM Something wrong. Exception error text: Error -3 while decompressing data: incorrect header check
```

**To Reproduce**
1. Go to Data Connectors > Imperva Cloud WAF (Using Azure Function)
2. Follow the connector instructions to deploy the function app and enter the configuration details
3. Observe error in application insights

**Expected behavior**
Expecting this to run successfully without error and for logs to appear in the Sentinel log analytics workspace. 

**Azure Function App details**
Azure Functions SDK Version: 3.17.0.0

**Desktop:**
 - OS: Windows 10 & 11
 - Browser: Microsoft Edge, Chrome
 - Version: Latest on both

**Comment by v-dvedak** [comment]
We need logs under Monitor in Function. You can get the logs by using below steps:
- Go to the Function
- Click on function name
- Click on Monitor
- Click on the date and share the logs

**Comment by v-dvedak** [comment]
Hi @rcegan , if you still need assistance, please reply here within 5 business days.

**Comment by v-dvedak** [comment]
Since we have not received a response in the last 5 days, we are closing your issue #6784 as per our standard operating procedures. If you still need support for this issue, feel free to re-open at any time. Thank you for your co-operation.
