### ISSUE TITLE
Proofpoint POD Connector References a GitHub file which was moved

### ISSUE THREAD

**Issue by willheineman** [Azure/Azure-Sentinel#6785]
https://github.com/Azure/Azure-Sentinel/blob/a5c6a759146d06e4be39b549b1b19c0e3ec985fe/Solutions/ProofPointPOD/Data%20Connectors/azuredeploy_Connector_Proofpoint_AzureFunction.json#L154

The ProofPointPOD Sentinel Connector references a zip file in the Azure Function App which was moved. Line 154 has a configuration value called "WEBSITE_RUN_FROM_PACKAGE", which points to a zip file in GitHub.

The current location of this file is: https://github.com/Azure/Azure-Sentinel/blob/master/Solutions/ProofPointPOD/Data%20Connectors/ProofpointSentinelConn.zip?raw=true

But the connector was updated to use a permalink, which is now broken since the files were moved: https://aka.ms/sentinel-ProofpointSentinelConn-functionapp

This permalink is a reference to the old file location: https://github.com/Azure/Azure-Sentinel/blob/master/DataConnectors/ProofpointPOD/ProofpointSentinelConn.zip?raw=true

**Comment by ashishsyal** [comment]
We are looking into this

**Comment by v-rucdu** [comment]
Apologies for the inconvenience caused the links has been updated... Please feel free to open this if issue persists... Thanks!!
