### ISSUE TITLE
ProofpointPOD Connector will not run with runtime version 4

### ISSUE THREAD

**Issue by willheineman** [Azure/Azure-Sentinel#6786]
https://github.com/Azure/Azure-Sentinel/blob/a5c6a759146d06e4be39b549b1b19c0e3ec985fe/Solutions/ProofPointPOD/Data%20Connectors/azuredeploy_Connector_Proofpoint_AzureFunction.json#L144

A recent pull request changed this function app to use runtime version `~4`, which is breaking the function app. When the runtime version is set to `~4`, the function stops running, and you can no longer view the function in the FunctionApp/Functions . You just receive an error.

If I revert it back to version ~3, the function starts again.

I do not know enough about the runtime version to know why this version change is breaking the function, but I believe that support for ~3.x will end on December 3rd.

Steps to replicate
1. Deploy connector (fix the WEBSITE_RUN_FROM_PACKAGE as noted in issue #6785 )
2. Monitor app and you will see that it will not run

Steps to fix
1. Navigate to Function App / Settings / Configuration
2. Click on "Function Runtime Settings"
3. Change Runtime Version to `~3`
4. Restart function app

**Comment by willheineman** [comment]
After further research, the ithe Function app would not run with Runtime 4.x because it was set to use Python 3.6, which is not supported in Runtime 4.x. 

Breaking Change from 3.x to 4.x: [Drop old language versions support in Functions v4 · Issue #1999 · Azure/Azure-Functions (github.com)](https://github.com/Azure/Azure-Functions/issues/1999)

Using this guide, we were able to identify the current python version that the Function App was using, and then update it to the latest (PYTHON|3.9): [How to target Azure Functions runtime versions | Microsoft Learn](https://learn.microsoft.com/en-us/azure/azure-functions/set-runtime-version?tabs=portal#manual-version-updates-on-linux)


1. Query the Function App to check the current Python version

```
az functionapp config show --name <function_app> \
--resource-group <my_resource_group> --query 'linuxFxVersion' -o tsv
```
2. Update the function App to Python|3.9

```
az functionapp config set --name <FUNCTION_APP> \
--resource-group <RESOURCE_GROUP> \
--linux-fx-version <"PYTHON|3.9"
```

3. Update the Function App to use the Runtime 4.x

**Comment by v-rucdu** [comment]
@willheineman : the PR containing the fix has been merged. In order to make it work please reinstall the function from the Connector Page.

Apologies for the inconvenience caused... Thanks!!!
