### ISSUE TITLE
Issue with alert custom details format in SecurityAlerts table

### ISSUE THREAD

**Issue by puijjar** [Azure/Azure-Sentinel#6796]
**Describe the bug**
Alert custom details are saved in the SecurityAlerts table using CRLF line breaks and are **not** recognized by Kusto JSON parser as valid JSON.

So this doesn't work:

```
SecurityAlert
| where ExtendedProperties has "Custom Details"
| project CustomDetails = todynamic(ExtendedProperties)["Custom Details"]
// Access the whatever properties and do whatever..
| project CustomDetails.ioc
```

To work around this we have to replace "\r\n" with "":

```
SecurityAlert
| where ExtendedProperties has "Custom Details"
| project CustomDetails = todynamic(ExtendedProperties)["Custom Details"]
| extend CustomDetails = todynamic(replace("\r\n", "", tostring(CustomDetails)))
// Access the whatever properties and do whatever..
| project CustomDetails.ioc
```

Please consider changing the format to have no unnecessary additional line break characters.

**Comment by v-vdixit** [comment]
Hi @puijjar are you still facing this issue, please confirm, thanks!

**Comment by v-vdixit** [comment]
Hi @puijjar since we have not received a response in the last 7 days, we are closing your issue as per our standard operating procedures. If you still need support for this issue, feel free to re-open at any time. Thank you for your co-operation.
