### ISSUE TITLE
Comments are executed in Log Analytics

### ISSUE THREAD

**Issue by azurekid** [Azure/Azure-Sentinel#6797]
**Describe the bug**
When the name of an available function is written in the comments, this function is being executed.
I've noticed this because I had a workspace function with an error in it.
When writing some comments in query mentioning this (broken) function, I got an error when running the code. [image 1]

![image](https://user-images.githubusercontent.com/40334679/205325448-c4e1356c-14d1-40c2-88c6-88aecc4bd3e2.png)

**To Reproduce**
1. Go to 'Log Analytics'
2. 'Create a new query'
3. Add a comment that contains the name of a broken workspace function
4. Select All code, incl. comments
5. Run the code

**Expected behavior**
I would expect that everything that is written in a comments block is not being executed by Log Analytics.
This behavior can cause a major performance impact if the code contains multiple workspace function names.

**Screenshots**
### Running when _all_ code (incl. comment) is selected
![image](https://user-images.githubusercontent.com/40334679/205325448-c4e1356c-14d1-40c2-88c6-88aecc4bd3e2.png)

### Running code with _only query_ selected
![image](https://user-images.githubusercontent.com/40334679/205326658-43cf192c-73cc-42bd-bc28-01de3645850a.png)

### Running code with _only comments_ selected
![image](https://user-images.githubusercontent.com/40334679/205326923-0d8947bb-031d-40c3-8a2d-eed02e18a336.png)

### Screenshot of mentioned broken function (line 123 is causing the error)
![image](https://user-images.githubusercontent.com/40334679/205327080-f57db01f-e14f-4afa-8506-aee1af2eadfd.png)

## Performance
When running this against a very small dataset the quickest response when comments are selected in 649ms
![image](https://user-images.githubusercontent.com/40334679/205329365-826b58ba-b622-4bbf-9750-1ebc2688327b.png)

When running against the same dataset with **no** comments selected the quickest response in 477ms
![image](https://user-images.githubusercontent.com/40334679/205330062-4d3fbe66-17b8-4b97-8e7d-363ec87af606.png)

**Comment by puijjar** [comment]
This sounds familiar: https://github.com/Azure/Azure-Sentinel/issues/4215.

**Comment by v-amolpatil** [comment]
While LA does not actually replaces function name in strings with the content of the function, it verifies it.

This is a known and hard to fix LA bug. It also happens in comments by the way. We fixed this specific one by fixing the underlying function, so the latest from the repo should indeed help. More generally, we are replacing the function names in strings which we use today with a different string to bump into the issue less.

**Comment by v-dvedak** [comment]
Closing this issue since we are investigating internally.
