### ISSUE TITLE
MultiplePasswordresetsbyUser Rule requires additional tuning for SSPR

### ISSUE THREAD

**Issue by best-geek** [Azure/Azure-Sentinel#6799]
This rule causes excessive noise by including SSPR and Password flow interrupt events. Customers are regularly requesting this rule to be tuned or turned off because of this. 

### Rule link

[MultiplePasswordresetsbyUser](https://github.com/Azure/Azure-Sentinel/blob/ee97399b426a21878776c4c7b4835efc04b47393/Detections/MultipleDataSources/MultiplePasswordresetsbyUser.yaml)

### Fix
This rule looks across multiple data points but when evaluating the audit logs some exclusions already exist. In the union for the Audit logs, the following exclusions under `new additions` should also be included 

```
        AuditLogs
        | where OperationName has_any (pWord) and OperationName has_any (action)
        | where ResultDescription !contains "User submitted a new password"
        | where ResultDescription <> "User started the mobile SMS verification option"
        | where ResultDescription <> "User submitted their user ID"
        | where ResultDescription <> "User was presented with verification options"
        | where ResultDescription <> "User completed the email verification option"
        | where ResultDescription <> "User completed all verification steps required to reset their password"
        | where ResultDescription <> "Successfully completed reset."
        | where ResultDescription <> "User completed the mobile SMS verification option"    
        | where ResultDescription <> "User started the email verification option"
        // new additions
        | where OperationName <> "Self-service password reset flow activity progress"
        | where OperationName <> "Change password (self-service)"
        | where OperationName <> "Reset password (self-service)"
```

## Justification
- `Self-service password reset flow activity progress` is typically caused by a password policy which requires users to rotate passwords. This operation already implies the user has signed in successfully and therefore the password reset is non-malicious. 
- *self-service* password resets should not be included because the user is required to verify some piece of MFA information for the SPPR request to authenticate. Therefore this password change can be deemed as non-malicious.

**Comment by v-vdixit** [comment]
Hi @best-geek we have tuned this rule for the details that you highlighted hope, it's working fine now, feel free to reopen the issue if it persists, thanks!
