### ISSUE TITLE
Feature: alert on shared mailbox accounts which have login enabled

### ISSUE THREAD

**Issue by hazcod** [Azure/Azure-Sentinel#6833]
**Is your feature request related to a problem? Please describe.**

Shared mailboxes on Exchange exist as regular user accounts in Azure AD, which serves no use since delegate access should be used to access these. I believe Sentinel should issue an alert if an Azure AD account is set to *Enabled* while a shared mailbox account exists for it in Exchange, since this should never be the case.

**Describe the solution you'd like**
An alert that fires periodically if an AAD account is set to `enabled` while a shared mailbox exists for it.

**Describe alternatives you've considered**
None

**Additional context**
Additional login credentials for a shared mailbox only serve as an additional security risk to the company.

**Comment by v-dvedak** [comment]
We are discussing on this request internally and so closing this.

**Comment by hazcod** [comment]
Can we at least keep this open until a conclusion has been reached @v-dvedak ?
Just closing it without resolution feels untransparent.
