### ISSUE TITLE
Bug: Inconsistent parameter when getting entity Host info (MdatpDeviceId vs MdeDeviceId)

### ISSUE THREAD

**Issue by brolifen** [Azure/Azure-Sentinel#6839]
**Describe the bug**
When using the "Isolate endpoint - MDE" playbook template some inconsistent data is being sent to the logic app. The data references a parameter which seems to change depending on how the playbook was ran (triggered vs manually).

**To Reproduce**
1. Use the "Isolate endpoint - MDE" playbook template to create a playbook
2. Setup all the appropriate permissions for the logic app to isolate a device and write comments to the incident
3. Create an Automation rule with Trigger: "When incident is created" and choose the newly created playbook
4. Trigger an incident in MDE, wait until it streams to Sentinel.
5. Notice that the playbook fails because logic app references the "MdatpDeviceId" value which does not exist, instead "MdeDeviceId" was being given in the input.
6. Now go back to the **Incident --> Actions --> Run playbook** and choose the same playbook that was triggered automatically
7. Notice that it now succeeded to run the logic app as now the Entity host info contains "MdatpDeviceId" and no longer "MdeDeviceId".

**Expected behavior**
The deviceId parameter should be either be MdeDeviceId or MdatpDeviceId all the time not change depending on circumstances of running the playbook. It would seem there is some sort of naming migration going on in the backend which breaks this playbook template.

**Screenshots**
![SentinelBug](https://user-images.githubusercontent.com/20615514/206213883-9b257a96-8b54-4751-af14-2aeadc970af5.jpg)

**Additional context**
M365 E5 License

**Comment by v-mchatla** [comment]
Hi @brolifen,
Thanks for flagging this. There is an open PR with the fix, you can track the status [here](https://github.com/Azure/Azure-Sentinel/pull/7125) for the same.
Thanks

**Comment by v-amolpatil** [comment]
The PR for this fix is merged in master so closing this issue.
