### ISSUE TITLE
Issue with Tenable IO Solution Parser - TenableIOVulnerabilities.txt

### ISSUE THREAD

**Issue by NoMad-Actual** [Azure/Azure-Sentinel#6844]
**Describe the bug**

Repeatedly getting an error that there are multiple functions - "Detected multiple functions with the same name: 'TenableIOVulnerabilities'. Resolve the conflict to allow these functions to be used in a query. If the issue persists, please open a support ticket."

This was resolved by renaming the function in the KQL comment.

Solution file here: https://github.com/Azure/Azure-Sentinel/blob/74645a0f96ccfc8a89d6241d5bd7874078a378c2/Solutions/TenableIO/Parsers/TenableIOVulnerabilities.txt

**To Reproduce**
1. Deploy the Tenable App from the Content Hub
2. Deploy the connector and the function parsers
3. Go to "Logs"
4. Attempt to call the function: TenableIOVulnerabilities 

**Expected behavior**
The function should be called appropriately without errors after a clean solution deployment.

**Screenshots**

![CleanShot 2022-12-07 at 15 36 36@2x](https://user-images.githubusercontent.com/112786403/206301725-16d2f303-ff1b-45b1-86f3-a71c62f7cf83.png)

![CleanShot 2022-12-07 at 15 40 38@2x](https://user-images.githubusercontent.com/112786403/206301747-50042dfa-f15d-4f83-b1f1-6e3b30e6e50a.png)

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: Edge
 - Version 108.0.1462.41 

**Smartphone (please complete the following information):**
N/A

**Additional context**
N/A

**Comment by v-laanjana** [comment]
@NoMad-Actual Please delete function "TenableIOVulnerabilities" from logs>functions>Workspace functions> search and delete.

**Comment by kenperkins-difenda** [comment]
> @NoMad-Actual Please delete function "TenableIOVulnerabilities" from logs>functions>Workspace functions> search and delete.

@v-laanjana - thank you for reaching out. What are the steps after deleting the function?

**Comment by NoMad-Actual** [comment]
> @NoMad-Actual Please delete function "TenableIOVulnerabilities" from logs>functions>Workspace functions> search and delete.

@v-laanjana - thank you for the reply. What are the steps after deleting the function?

**Comment by v-laanjana** [comment]
please install from content hub  steps  sentinel>content hub> search solution >reinstall

**Comment by v-laanjana** [comment]
@NoMad-Actual could you please acknowledge if your issue fixed?

**Comment by NoMad-Actual** [comment]
Hello, I'm working with a client to get this tested.

Thank you!

**Comment by v-laanjana** [comment]
NoMad-Actual please updates us .

**Comment by NoMad-Actual** [comment]
This solved the issue.  Thank you for your support!

From: v-laanjana ***@***.***>
Date: Monday, December 19, 2022 at 05:40
To: Azure/Azure-Sentinel ***@***.***>
Cc: Ken Perkins ***@***.***>, Mention ***@***.***>
Subject: Re: [Azure/Azure-Sentinel] Issue with Tenable IO Solution Parser - TenableIOVulnerabilities.txt (Issue #6844)

NoMad-Actual please updates us .

**Comment by v-dvedak** [comment]
Closing the issue as it is resolved.
