### ISSUE TITLE
Issue ingesting demo data from Azure Sentinel Training Lab (solution)

### ISSUE THREAD

**Issue by xxxdebug** [Azure/Azure-Sentinel#6855]
Installed a fresh Sentinel + LA workspace. After importing the Training Lab Solution from MS, I get errors, specific at the stage of ingesting data into my workspace. Permissions related? 

Any idea what could cause this? 

`{
    "status": "failed",
    "error": {
        "code": "DeploymentScriptOperationFailed",
        "message": "The received access token is not valid: at least one of the claims 'puid' or 'altsecid' or 'oid' should be present. If you are accessing as application please make sure service principal is properly created in the tenant."
    }
}`

**Comment by v-mchatla** [comment]
Hi @xxxdebug,
Can you please try installing by creating new workspace.
I have tried installing it from Content hub. It got installed successfully. 
![image](https://user-images.githubusercontent.com/108806639/207029680-6f530edf-4a25-49a3-9351-2f86253bac09.png)
Let us know if you are still facing any issue. Please ensure you have latest version (1.0.6) installed.
Thanks

**Comment by xxxdebug** [comment]
Hi @v-mchatla, indeed, I re-created the workspace and it's working now. Weird, I didnt do anything wrong to be honest. But it's deployed now. Thanks so much.
