### ISSUE TITLE
LastPass Data Connector Not Polling at all

### ISSUE THREAD

**Issue by asterictnl-lvdw** [Azure/Azure-Sentinel#6875]
**Describe the bug**
The LastPass Data Connector seems not to be working and ingesting data into Microsoft Sentinel at all. Can this please be fixed?

The following problems:
- Logs are not ingested
- Query does not work, because tables and the database seems not being initialized

**To Reproduce**
1. Install and configure the LastPass Connector
2. Customer ID and API-Key
3. Simply Connecto the Connector and wait for logs to be ingested.
4. Use the Query onto the Connector Page to test if the logs are ingested

**Expected behavior**
When running the query results should be expected

**Screenshots**
![image](https://user-images.githubusercontent.com/99249102/206996474-c7f1e21f-e6a3-4272-af6b-321d6b889624.png)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser Edge (Latest)

**Additional context**
Please let me know if this will be fixed at all.

Thanks in advance.

**Comment by asterictnl-lvdw** [comment]
@v-dvedak 

The error in the log seems to be: Data fetch failed (Invalid Config.)
Errorcode: RES40002
{"ConnectorDataType":"ApiPolling","DestinationTable":"LastPassNativePoller_CL"}

Please let me know if you need more info.

~LvdW

**Comment by asterictnl-lvdw** [comment]
@v-dvedak @ThijsLecomte @ThijsLecomte-TC

I have looked at the template and I found an issue there what might cause the problem and making the LastPass connector not work at all:

According to documentation of LastPass there is no such thing as API authentication since the authentication is done in the body. You provide each request with the authentication CID and Provisioning Hash.  There is no such thing as API-Key authentication here since this is done in the request itself.

This is the actual request you send in the body. This includes the CIS and ProvisionHash that needs to be filled in by userInput:
`
{
    "cid": "{{CID}}",
    "provhash": "{{ProvisionHash}}",
    "cmd": "reporting",
    "data": {
        "from": "2022-01-01 00:00:00",
        "to": "2022-01-31 23:59:59"
    }
}
`

Since I only saw the options basic, oauth and apikey I wonder it if is possible at all.

According to the lines in [mainTemplate.json](https://github.com/Azure/Azure-Sentinel/blob/master/Solutions/LastPass/Package/mainTemplate.json) something tries to authenticate with a non-existing API-key. 

Line 1215
`"type": "APIKey"`
Line 1224
`"authType": "APIKey"`

This might also get a little problematic since I did not saw the option to add multiple textboxes to fill in details. Alternatively what could be done is deploying it by a Azure ARM Template or using a Azure Function App to mitigate the problem.

**Comment by ThijsLecomte** [comment]
Hi all

I have been investigating this, the API calls look fine, it might be an issue for the CCP connector for which I need to create a support case myself.

I understand the confusion about the authentication, but this is expected as this is the auth configuration:

`"auth": {
            "authType": "APIKey",
            "APIKeyName": "provhash",
            "IsAPIKeyInPostPayload": true
          },`


So it adds the authmethod to the body

**Comment by NikTripathi** [comment]
Hi @ThijsLecomte Can you please test the below custom template and let us know the output.

Please deploy the custom template available on the below URL. It will update your solution and then please test the connector.

URL:- https://raw.githubusercontent.com/Azure/Azure-Sentinel/f3ad344e225e348e2d946f1dcf4ec696ebb3e8c7/Solutions/LastPass/Package/mainTemplate.json

Steps:- 
1: Go to Portal and search for deploy a custom template.
![image](https://user-images.githubusercontent.com/87809732/209349690-39e3d802-2e0c-4a8d-b5ba-667ff5d20ba3.png)
2: Click on build your own template in editor.
![image](https://user-images.githubusercontent.com/87809732/209349902-12d559d7-7667-4b5f-b4dd-6cca2fc576a7.png)
3: Remove the content and paste the content which is available on the above URL and click on save.
![image](https://user-images.githubusercontent.com/87809732/209350012-ce5cc030-98a4-4a03-a2c9-4875beecd5a5.png)
4: Select Resource group and workspace and then click on review + Create.
![image](https://user-images.githubusercontent.com/87809732/209350112-0c843a29-fd04-4768-975e-27feb0a489bb.png)
5: Once deployment is done please test the data connector and let us know the output. 

Thanks.

**Comment by ashishsyal** [comment]
Seems Thijs is on vacation till 2nd Jan, waiting for the confirmation.

**Comment by ThijsLecomte** [comment]
Hi @ashishsyal , I provided feedback on the other issue =>https://github.com/Azure/Azure-Sentinel/issues/6244#issuecomment-1363989631

**Comment by v-dvedak** [comment]
Closing this issue since it is fixed as per confirmation from Thijs.
