### ISSUE TITLE
Log4j solution no longer deploys in Azure Government

### ISSUE THREAD

**Issue by KenBenjamin** [Azure/Azure-Sentinel#6880]
Previously, we were able to deploy this solution successfully, but a recent update now throws the following error:

`{"code":"DeploymentFailed","message":"At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/DeployOperations for usage details.","details":[{"code":"NoRegisteredProviderFound","message":"No registered resource provider found for location 'usgovvirginia' and API version '2021-03-01-preview' for type 'Watchlists'. The supported api-versions are '2021-09-01-preview, 2021-10-01-preview, 2022-01-01-preview, 2022-04-01-preview, 2022-05-01-preview, 2022-06-01-preview, 2022-07-01-preview, 2022-08-01-preview, 2022-09-01-preview, 2022-10-01-preview, 2022-11-01-preview, 2022-12-01-preview, 2021-04-01, 2021-10-01, 2022-08-01, 2022-11-01'. The supported locations are 'usgovvirginia, usgovarizona'."}]}`

Please update the API version used for Watchlists to a valid version.

**Comment by v-rucdu** [comment]
@KenBenjamin thanks for reporting the issue.. we are looking into it and will provide you with an update soon... Thanks!!!

**Comment by v-rucdu** [comment]
@KenBenjamin, the issue has been fixed and the package is also updated. Please try installing the latest package from content hub... Thanks!!

**Comment by v-rucdu** [comment]
@KenBenjamin: Closing this issue, please feel free to re-open it in case the issue persists... Thanks!!!
