### ISSUE TITLE
Bad username / password issue in the Qualys connector with correct username and password

### ISSUE THREAD

**Issue by tokesr** [Azure/Azure-Sentinel#6886]
**Describe the bug**
Issue in the Qualys connector for Sentinel.
During execution the built-in Qualys connector function app throws a Bad username/password error message.
When I try authenticate on the Qualys API through postman the authentication works just fine, but for some reason not through the Function App from Azure.

**To Reproduce**
1. Deploy the Qualys connector for Sentinel
2. Configure the proper username and password (and other values)
3. Execute the code
4. Check the upcoming error messages for details

**Expected behavior**
I would expect the correct username and password to work just fine.

**Desktop (please complete the following information):**
 -Not applicable I think, the issues is in the Function App or config not in the OS/browser

**Additional context**
Me and my colleagues deployed this connector recently in multiple environments and we encountered the same error in all of them (so not a unique issue, and it is not related to me directly)

Details of the error message:
Invoke-WebRequest : <Date> 2010 Bad Login/Password 
Invoke-WebRequest -Headers $hdrs -Uri "$($base)/session/" -Method ... +
Response status code does not indicate success: 403 (Forbidden).

**Comment by v-mchatla** [comment]
Hi @tokesr,
Thanks for reporting the issue. Our team is working on it, will keep you posted.
Thanks

**Comment by tokesr** [comment]
Hi team,
Is there any update regarding this case? Could you reproduce this issue or were you already familiar with it?
If any additional information is needed please let me know.

**Comment by NikTripathi** [comment]
Hi @tokesr , I would suggest to test your credentials using CURL or Portman. 
From the information provided by you it seems more like an authorization failure. In the past we have seen similar issues and to resolve them we just followed below steps.
1:- Login to the Qualys portal by using the same credentials that you are using the connector.
2:- Complete the whole registration process by completing the profile.

Le me know if you face any issue.
Thanks.

**Comment by tokesr** [comment]
hi @NikTripathi 
As the original issue states the authentication works without any issue when I do it through Postman. So, the credentials are definitely not the problem.
Since opening the ticket I also put together a small code to test whether any logs can be read from Qualys (the eliminate authZ issues) and with my custom code I could read the logs.
Still, the Sentinel connector is failing with the above-mentioned error messages.

**Comment by v-amolpatil** [comment]
@tokesr This issue is related to **Authorization** and Not **Authentication**, so could you please complete the steps given by Nikhil in previous comments. Adding steps from previous comment as:
1:- Login to the Qualys portal by using the same credentials that you are using the connector.
2:- Complete the whole registration process by completing the profile.

Please let us know if you face any issue.
Thanks!

**Comment by v-amolpatil** [comment]
Hi @tokesr, as per previous comments issue is with authorization and can be fixed by completing all the steps provided earlier. Closing this issue for now, feel free to reopen if you need more assistance. Thanks!
