### ISSUE TITLE
EventOutcome field and value do not appear in CommonSecurityLog table

### ISSUE THREAD

**Issue by LaraibKhan555** [Azure/Azure-Sentinel#6896]
Microsoft CEF event mapping documentation says the **Outcome** field is mapped in the **CommonSecurityLog** table.

![image](https://user-images.githubusercontent.com/24682607/207341975-51b44084-dcb1-4788-9761-07b1a70d3f84.png)

However, there's no **Outcome** field in the **CommonSecurityLog** schema.
But there's one field called **EventOutcome** as shown in MS Sentinel below.

![image](https://user-images.githubusercontent.com/24682607/207342423-d58467ac-51eb-4099-8352-11f4e7f60762.png)

Although once a CEF event arrived in the Sentinel. The outcome value does not appear in the correct field, despite the outcome being set in the raw event.
![image](https://user-images.githubusercontent.com/24682607/207343113-337d8980-3435-40cd-b55a-e5053ca0fa32.png)

outcome value appears in **AdditonalExtensions**

### Issue
The document version of **CommonSecurityEvent** schema mapping and MS Sentinel version of **CommonSecurityEvent** schema should be homogenous.

### Bug-1
Raw events contain outcome values (success or failure) that appear in **AdditionalExtension** and not in the **EventOutcome** field.

### Bug-2
Once the Raw event has the **EventOutcome** field, it completely disappears from the CommonSecurityEvent table.

**Comment by v-amolpatil** [comment]
@LaraibKhan555 The documentation for the schema change has been updated. Please refer the documentation links below: 
https://learn.microsoft.com/en-us/azure/sentinel/cef-name-mapping
https://learn.microsoft.com/en-us/azure/azure-monitor/reference/tables/commonsecuritylog
Closing the issue as this is fixed.
