### ISSUE TITLE
Migrate-LA-to-ADX.ps1 only migrated 7 Sentinel tables

### ISSUE THREAD

**Issue by mtittle52** [Azure/Azure-Sentinel#6900]
Hi, 

We just ran the script Migrate-LA-to-ADX.ps1 to setup ingestion from Sentinel to ADX.  Upon completion of the script it only setup the export for 7 Sentinel tables and created 7 event hubs (all in one namespace) and only created two data connections on the ADX DB.  We ran the script to setup export of all the LA tables, so I'm not sure why it only setup the export for 7 tables.   If I had to draw any correlation, it's that it seems like the script only setup the export for tables that actually have data.  Is this expected behavior?  How can I get the script to setup the export of all the LA tables?

Thanks,

Mike

**Comment by mtittle52** [comment]
Hi, just a follow-up to my original post.  As we continue testing this script, it seems it does work best with Sentinel/Log Analytics tables that have data and are actively ingesting data.  We've been trying to use this script to pre-stage all the Sentinel table exports to ADX as part of our code-based deployment, but at that stage none of the source tables have any data, so it doesn't really seem well suited for this purpose.

**Comment by sreedharande** [comment]
@mtittle52 - Yes you are correct, Script will create EventHub Topics for the tables that are actively ingesting data. Its #bydesign to create Data Export Rules at LA.

If you are creating these tables in ADX for Long term data retention - We have new Sentinel native feature called "Archive Tier"

**Comment by v-amolpatil** [comment]
Thanks for the response @sreedharande.
Hi @mtittle52, 
Thanks for flagging this. Hope Sreedhar comment answers your query. Please let us know if we can close the issue or need any more assistance.
Thanks!

**Comment by mtittle52** [comment]
Thank you.  You may close the issue.
________________________________
