### ISSUE TITLE
ArchiveLogTools-PowerShell Script returns an Invalid Input error 

### ISSUE THREAD

**Issue by adampowellscc** [Azure/Azure-Sentinel#6904]
When leveraging the ArchvieLogTools script I can successfully authenticate, select the required analytics tables however after providing a value to set for total retention it errors.

Update-TablesRetention {"error":{"code":"InvalidInput","message":"One or more validation errors occurred","target":"property","details":[{"code":"InvalidParameter","message":"Unexpected character encountered while parsing value: ,. Path 'properties.retentionInDays', line 3, position 25.","target":"properties.retentionInDays"}]}}

**To Reproduce**
1. Run the script
2. provide tenant id
3. successfully authenticate
4. select required workspace
5. select analytics 
6. select table
7. provide value for retention 
8. returns error 

Update-TablesRetention {"error":{"code":"InvalidInput","message":"One or more validation errors occurred","target":"property","details":[{"code":"InvalidParameter","message":"Unexpected character encountered while parsing value: ,. Path 'properties.retentionInDays', line 3, position 25.","target":"properties.retentionInDays"}]}}

After providing the value, retention settings should be updated on the table 

![Screenshot 2022-12-14 100553](https://user-images.githubusercontent.com/120561453/207566591-c9076b5c-17f8-4742-8b50-1b554fbef7e0.png)

**Additional context**
https://github.com/Azure/Azure-Sentinel/tree/master/Tools/Archive-Log-Tool/ArchiveLogsTool-PowerShell

**Comment by v-mchatla** [comment]
Hi @adampowellscc,
Closing this issue as fixed. Please feel free to reopen the issue if the issue persists.
Thanks
