### ISSUE TITLE
In operator not case-sensitive

### ISSUE THREAD

**Issue by Lodewyk-Git** [Azure/Azure-Sentinel#6934]
**Describe the bug**
One Rule triggered where in operated like in~

**Expected behavior**
in operator to be case-sensitive as described in documentation. 

**Screenshots**
![image](https://user-images.githubusercontent.com/36856692/208664398-73b7984c-e6f7-41a2-93e9-38c0fba695cb.png)

**Additional context**

**Comment by v-mchatla** [comment]
Hi @Lodewyk-Git,
Can you share the complete query to understand the issue better.
Thanks

**Comment by Lodewyk-Git** [comment]
Sure, it this one https://github.com/Azure/Azure-Sentinel/blob/master/Solutions/Azure%20Active%20Directory/Analytic%20Rules/AuthenticationMethodsChangedforPrivilegedAccount.yaml

**Comment by v-mchatla** [comment]
Hi @Lodewyk-Git Hi @Lodewyk-Git,
Sorry for the delay in response. We don't have required sample data to test this rule at our end. Can you please share sample data if possible.
Thanks

**Comment by Lodewyk-Git** [comment]
Thanks @briandelmsft, you're completely right, for some reason I thought that the ActivityDisplayName was being made into a set.
