### ISSUE TITLE
Why are tables like AzureActivity not supported?

### ISSUE THREAD

**Issue by MiguelElGallo** [Azure/Azure-Sentinel#6941]
Hello,
Is it possible to add support for other tables like AzureActivity not supported?
Thanks!

**Comment by oshezaf** [comment]
@MiguelElGallo : supported in what manner? There is an AzureActiivy solution in the Sentinel Content Hub. Its source on GitHub can be found [here](https://github.com/Azure/Azure-Sentinel/tree/master/Solutions/Azure%20Activity)

**Comment by v-amolpatil** [comment]
Hi @MiguelElGallo, Please refer previous comment added by oshezaf. Let us know if you still need assistance in 5 business days.

**Comment by v-amolpatil** [comment]
Since we have not received a response in the last 5 days, we are closing your issue #6941 as per our standard operating procedures. If you still need support for this issue, feel free to re-open at any time. Thank you for your co-operation.
