### ISSUE TITLE
M365D alerts coming through to Sentinel as New Incidents months after Closure

### ISSUE THREAD

**Issue by Lodewyk-Git** [Azure/Azure-Sentinel#6945]
**Describe the bug**
Just had an Alert in Defender from the 1st of August come through and create an Incident in Sentinel. Almost got a heart attack until I saw the date and time on the Alert itself.

**Expected behavior**
Alerts to be Sent through within a reasonable time frame and not afterwards. 
Incident times to be accurate to alert times.

**Screenshots**
![image](https://user-images.githubusercontent.com/36856692/208923788-bad85c07-2ae0-401d-b10f-8bca18c865d7.png)

**Additional context**
This had already been assigned to myself via Sentinel in august, but was unassigned in the new creation where it was set to active and then resolved again by the m365d back end.

**Comment by v-amolpatil** [comment]
Hi @Lodewyk-Git,
Does it appear for other issues as well or is it only 1 problem getting that. Could you please also send us the custom rule created for this using the export rule.
Thanks,

**Comment by Lodewyk-Git** [comment]
Hi @v-amolpatil,

It's based on the old Microsoft rule for MDE. 

```
{
    "$schema": "https://schema.management.azure.com/schemas/2019-04-01/deploymentTemplate.json#",
    "contentVersion": "1.0.0.0",
    "parameters": {
        "workspace": {
            "type": "String"
        }
    },
    "resources": [
        {
            "id": "[concat(resourceId('Microsoft.OperationalInsights/workspaces/providers', parameters('workspace'), 'Microsoft.SecurityInsights'),'/alertRules/ae95b2bf-28f3-427e-aa12-2d18145e7d91')]",
            "name": "[concat(parameters('workspace'),'/Microsoft.SecurityInsights/WorkspaceID')]",
            "type": "Microsoft.OperationalInsights/workspaces/providers/alertRules",
            "kind": "MicrosoftSecurityIncidentCreation",
            "apiVersion": "2022-09-01-preview",
            "properties": {
                "displayName": "Create incidents based on Microsoft Defender for Endpoint alerts",
                "description": null,
                "enabled": true,
                "productFilter": "Microsoft Defender Advanced Threat Protection",
                "severitiesFilter": null,
                "displayNamesFilter": null,
                "displayNamesExcludeFilter": null,
                "alertRuleTemplateName": null
            }
        }
    ]
}
```

I see the last template update was 24 Oct 2019, but the one that I am using wasn't linked with the Gallery content. It pulled in all of the old data when the rule was created, hasn't happened since. 

What is the look back period on enablement for the current MS rules?

**Comment by v-vdixit** [comment]
Hi @Lodewyk-Git are you still facing this issue, please confirm, thanks!

**Comment by v-vdixit** [comment]
Hi @Lodewyk-Git Gentle Reminder: We are waiting for your response on this issue. If you still need to keep this issue active, please respond on it in the next 2 days. If we don't receive response, we will be closing this issue as per our standard procedures, thanks!
