### ISSUE TITLE
Azure Monitor Agent not installing on Red Hat Linux 7

### ISSUE THREAD

**Issue by Lodewyk-Git** [Azure/Azure-Sentinel#6952]
**Describe the bug**
Azure Monitor Agent not installing on Red Hat Linux

**To Reproduce**
Create a custom text log via DCR
increase filesystem size for /opt /var /etc to bigger than 500 mb  (as specified in waagent python script)
Associate Azure Arc on-boarded device with data collection  
Go to Azure Arc and verify that the Agent was installed on the Virtual machine
Run Heartbeat query

**Expected behavior**
Hearbeat table to return results

**Screenshots**
![image](https://user-images.githubusercontent.com/36856692/209134036-cc5ed2dc-334b-4ab1-b9f6-c14f5d80428c.png)

**Additional context**
Had this issue arise when we tried to install the agent on RHEL. Got error 52. Found a file called agent.py - /var/lib/waagent/Microsoft.Azure.Monitor.AzureMonitorLinuxAgent-1.24.2/agent.py -that checks for space. Increased the space according to the file. Shows success, but still no data ingested in log analytics.

**Comment by v-vdixit** [comment]
Hi @Lodewyk-Git are you still facing this issue, please confirm, thanks!

**Comment by v-vdixit** [comment]
Hi @Lodewyk-Git Gentle Reminder: We are waiting for your response on this issue. If you still need to keep this issue active, please respond on it in the next 2 days. If we don't receive response, we will be closing this issue as per our standard procedures, thanks!

**Comment by v-vdixit** [comment]
Hi @Lodewyk-Git Since we have not received a response in the last 5 days, we are closing your issue #6952 as per our standard operating procedures. If you still need support for this issue, feel free to re-open at any time. Thank you for your co-operation
