### ISSUE TITLE
Feature: alert on device code logon

### ISSUE THREAD

**Issue by hazcod** [Azure/Azure-Sentinel#6957]
**Is your feature request related to a problem? Please describe.**
Ref https://www.inversecos.com/2022/12/how-to-detect-malicious-oauth-device.html

**Describe the solution you'd like**
An analytics rule that triggers on `Authentication Protocol: Device Code` and `Authentication Requirement: Single-factor authentication` to warn for device code phishing.

**Describe alternatives you've considered**
none

**Additional context**
Device code phishing is an upcoming attack vector for office365 phishing.

**Comment by v-amolpatil** [comment]
@hazcod We have taken a note of this request. Closing the issue.

**Comment by hazcod** [comment]
@v-amolpatil Shouldn't we keep this open until .. you know .. it's implemented?
Moving this request to somewhere invisible doesn't feel right.

**Comment by kolitsasg** [comment]
@v-amolpatil Totally agree with @hazcod. This security mechanism should be in place as soon as this feature (device code) was released. Currently it is a blind spot to user compromise and there is no way to be automatically alerted when device code authenication is used. In addition, the sign in details (Device info) show incorect information (the device is shown as managed, compliant, Azure AD joined) making the detection even more difficult.
