### ISSUE TITLE
Rule Template RDP_RareConnection.yaml giving false positives

### ISSUE THREAD

**Issue by luke-isopro** [Azure/Azure-Sentinel#700]
**Describe the bug**
Rule is returning non "rare" rdp connections from template query.
Appears the starttime and endtime variables are back to front.
Causing 
- the outer join to go back 14 days instead of 1
- the leftanti join to always return zero records

**To Reproduce**
1. Creating rule from 'Rare RDP Connections' template in Azure Sentinal

**Expected behavior**
Rule should return connections seen today, which haven't been seen in the last 14 days

**Screenshots**

**Desktop (please complete the following information):**
 - OS: N/A
 - Browser N/A
 - Version N/A

**Smartphone (please complete the following information):**
 - Device: N/A
 - OS: N/A
 - Browser N/A
 - Version N/A

**Additional context**

**Comment by shainw** [comment]
@luke-isopro - Thanks for the feedback, will have a look.

**Comment by shainw** [comment]
@luke-isopro - This was already fixed here - https://github.com/Azure/Azure-Sentinel/commit/cafb7a6d0d72c5f9d9176df91bc64a9d93943bd3#diff-c15387d343804caa22848d3976f3d713

But looks like the backend bringing it into the templates did not update it.  I will check on it.  In the mean time, you can use the version in GitHub - https://github.com/Azure/Azure-Sentinel/blob/master/Detections/SecurityEvent/RDP_RareConnection.yaml

**Comment by shainw** [comment]
@luke-isopro - we have some holds on bringing changes in over the last month, the plan is to have this updated, along with others in the next week.  Thanks, Shain.

**Comment by luke-isopro** [comment]
thanks for the updates @shainw

**Comment by shainw** [comment]
@luke-isopro - the Rule Template should now be updated with the same version as GitHub.  I have confirmed in my test environment, please verify.

**Comment by luke-isopro** [comment]
thanks @shainw I can confirm it's picking up the new template in the Azure console

**Comment by shainw** [comment]
@luke-isopro - thanks for verification and keep the feedback coming. :)
