### ISSUE TITLE
White List Azure IPs

### ISSUE THREAD

**Issue by kay07949** [Azure/Azure-Sentinel#701]
We are using the Key Vault use cases and it is generating a lot of incidents, especially from Azure backup IP range.  We therefore need a strategy whitelist these addresses.

•	13.69.65.32/27- (13.69.65.58) AzureBackup
•	13.67.12.0/24 – (13.67.12.0) AzureBackup.SoutheastAsia
•	40.71.12.0/25- (40.71.12.21) AzureBackup

The complete list is available on:

https://www.microsoft.com/en-us/download/confirmation.aspx?id=56519 

What is the best way to whitelist these IPs? My thougths were to create an Azure function that pulls in the IP range from the file and then create a custom table that syncs with the updated files on a weekly basis, we can then filter the KQL...

Please let me know your thoughts.

**Comment by oshezaf** [comment]
Probably right. I thought that the externaldata operator will save you from the import, but it seems to fail with the format of this specific file. To match the ranges you will need to try things outlined here: [Approximate, partial and combined lookups in Azure Sentinel](https://techcommunity.microsoft.com/t5/azure-sentinel/approximate-partial-and-combined-lookups-in-azure-sentinel/ba-p/1393795)

**Comment by ashwin-patil** [comment]
I am working on a solution for a similar request from other customer this week. As Ofer said, externaldata can not be used as the actual download link to json is not static.  However you can script and retrieve the download URL from HTTP response to that page.

Here is the sample oneliner PowerShell that will get you started to retrieve the download URL if you want to script it. 

```powershell 
Invoke-WebRequest -Uri "https://www.microsoft.com/en-us/download/confirmation.aspx?id=56519" -UseBasicParsing | Foreach {$_.Links } | Where-Object {$_.href -like "*json"} | Get-Unique | % href`
```

As you mentioned the best way to automate is via Azure Function to download this weekly and automatically upload to blob storage.

Once the URL is known, you could use something similar to below KQL query to create the table. URL will be replaced your blob storage uri once automation is in place.

```
let AzureIPRangesPublicCloud = (externaldata(changeNumber:string, cloud:string, values: dynamic)
[@"https://download.microsoft.com/download/7/1/D/71D86715-5596-4529-9B13-DA13A5DE5B63/ServiceTags_Public_20200518.json"]
with (format="multijson"));
let AzureSubnetRangeWhitelist = AzureIPRangesPublicCloud
| mvexpand values
| extend platform = parse_json(parse_json(values).properties).platform, 
    systemservice = parse_json(parse_json(values).properties).systemService, 
    region = parse_json(parse_json(values).properties).region, 
    addressPrefixes = parse_json(parse_json(values).properties).addressPrefixes
| mvexpand addressPrefixes
| project platform, systemservice, region, addressPrefixes;
AzureSubnetRangeWhitelist 
```

**Comment by kay07949** [comment]
Hi Ashwin, 

This is great query, however it returns the cidr, e.g 20.46.152.128/28. and this wouldnt filter out the query, e.g | where CallerIPAddress == "40.71.12.21/32"

**Comment by oshezaf** [comment]
If a single value, use [ipv4_is_match()](https://docs.microsoft.com/en-us/azure/data-explorer/kusto/query/ipv4-is-matchfunction). If a list, see how to use mv-apply with ipv4_is_match in the article I referenced above ([Approximate, partial and combined lookups in Azure Sentinel](https://techcommunity.microsoft.com/t5/azure-sentinel/approximate-partial-and-combined-lookups-in-azure-sentinel/ba-p/1393795))

**Comment by ashwin-patil** [comment]
Here is a sample query for CommonSecurityLog as Ofer suggested with **_ip4_is_match()_** and 
**_mv-apply_**.
You can replicate it to other tables based on IP field to match. I would strongly recommend to run this at smaller and frequent intervals depending on the volume of records the original table has.

```
let AzureIPRangesPublicCloud = (externaldata(changeNumber:string, cloud:string, values: dynamic)
[@"https://download.microsoft.com/download/7/1/D/71D86715-5596-4529-9B13-DA13A5DE5B63/ServiceTags_Public_20200518.json"]
with (format="multijson"));
let AzureSubnetRangeWhitelist = AzureIPRangesPublicCloud
| mvexpand values
| extend addressPrefixes = parse_json(parse_json(values).properties).addressPrefixes
| project addressPrefixes; 
let lookup = toscalar(AzureSubnetRangeWhitelist | summarize l=make_set(addressPrefixes));
  let starttime = 4h;
  let endtime = 1h;
  let PrivateIPregex = @'^127\.|^10\.|^172\.1[6-9]\.|^172\.2[0-9]\.|^172\.3[0-1]\.|^192\.168\.';
  let AllDestIP = materialize(
  CommonSecurityLog 
  | where TimeGenerated between (startofday(ago(starttime))..startofday(ago(endtime)))
  | where isnotempty(DestinationIP) and isnotempty(SourceIP)
  | extend DestinationIpType = iff(DestinationIP matches regex PrivateIPregex,"private" ,"public" )
  | where DestinationIpType == "public"
  | distinct DestinationIP
  );
  let AzureSubnetMatchedIPs=AllDestIP
  | mv-apply l=lookup to typeof(string) on
  (
   where ipv4_is_match (DestinationIP, l)
  )
  | project-away l;
  CommonSecurityLog 
  | where TimeGenerated between (startofday(ago(starttime))..startofday(ago(endtime)))
  | where isnotempty(DestinationIP) and isnotempty(SourceIP)
  | where DestinationIP !in ((AzureSubnetMatchedIPs))
```

**Comment by kay07949** [comment]
Thanks all much appreciated.

**Comment by kay07949** [comment]
i am have a simlar task, which is to whitelist all Qualysis IPs, i have written the code below:

`let lookup=toscalar(datatable(ip_range:string) ["64.39.96.0/20"] | summarize l=make_set(ip_range));
let AllSourceIps = materialize(
CommonSecurityLog
| where TimeGenerated > ago(1hr)
| where DeviceVendor == "Palo Alto Networks"
| where Activity == "THREAT"  and ( DeviceEventClassID != "file"  and DeviceEventClassID != "virus") 
| distinct SourceIP
);
let MatchedIps = AllSourceIps
| mv-apply l=lookup to typeof(string) on
(
   where ipv4_is_match (SourceIP, l)
);
CommonSecurityLog
| where TimeGenerated > ago(1hr)
| where DeviceVendor == "Palo Alto Networks"
| where Activity == "THREAT"  and ( DeviceEventClassID != "file"  and DeviceEventClassID != "virus") 
| where DestinationIP !in ((MatchedIps))

`

However this dont seem to be whitelisting as expected. Any idea what could be going wrong here?

**Comment by ashwin-patil** [comment]
Closing the issue - sample query provided per requirements.

**Comment by kay07949** [comment]
i have the url in a custom table, how do i extract the IP into the required URL field?

let url = TestKay_CL 
| project PublishedData_s;
let AzureIPBackupRanges = (externaldata(changeNumber:string, cloud:string, values: dynamic)
[@"url"]

The above do not work it gives me an error.
