### ISSUE TITLE
Palo-Alto Block IP Playbook not connecting with Panorama

### ISSUE THREAD

**Issue by PrashaliShinde** [Azure/Azure-Sentinel#7036]
Hi team,

We are trying to configure PaloAlto-PAN-OS-BlockIP playbook and the sentinel steps are running successfully but while going for panorama steps ("List Address Objects") it is not connecting with Panorama instance, we have provided the API key and location. 

Following error, we are receiving when trying to execute any panorama step
"error": {
    "code": "InternalServerError",
    "message": "A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."
  }

Please let us know if we are missing anything.

**Comment by manishkumar1991** [comment]
@PrashaliShinde , Can you please check/run below curl call, this is same which will list all the address objects.


curl -X GET 'https://<your pan os server ip>/restapi/v9.1/Objects/Addresses?location=vsys&vsys=vsys1' -H 'X-PAN-KEY: <pankey>'

and share the result with us

**Comment by manishkumar1991** [comment]
@PrashaliShinde , did you get a chance to look over my comment

**Comment by v-amolpatil** [comment]
Hi @PrashaliShinde, thank you for flagging this. Could you please refer previous comments from Manish and let us know if you still need assistance, please reply here within 5 business days.

**Comment by v-amolpatil** [comment]
Gentle Reminder: We are awaiting for your response on this issue. If you still need to keep this issue active please respond within next 2 days. If we don't receive response by 15 Feb 2023, we will close this issue.
