### ISSUE TITLE
UDP/TCP messages contain ICMP codes

### ISSUE THREAD

**Issue by cgiampoulakis** [Azure/Azure-Sentinel#7038]
https://github.com/Azure/Azure-Sentinel/blob/799dc67acda591fd4ef44fe701e3bf9110cbbf1a/Parsers/ASimNetworkSession/Parsers/ASimNetworkSessionAzureFirewall.yaml#L61

There seems to be a logic issue related to the above iff() function: If the msg does not start with ICMP, the NetworkIcmpCode will always be echo-reply. So we will have UDP/TCP events with echo-reply ICMP codes which is misleading.

**Comment by oshezaf** [comment]
Thanks @cgiampoulakis to identifying the issue. I have fixed the parsers. The fix is available in the GitHub version. It will be available in the built-in parsers in the near future.
