### ISSUE TITLE
Ownerless group  events missing in Sentinel Audit log query

### ISSUE THREAD

**Issue by funzel1** [Azure/Azure-Sentinel#7050]
**Describe the bug**

**To Reproduce**
1. Make a Microsoft Group ownerless (delete the account)
2. 3 types of notifications visible in the audit log (notificaction,response and unattended group)
3. Sentil log query against audit log has only operations "Response" as result, other both missing

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by funzel1** [comment]
Hello @v-amolpatil 


1. Enable new solution 
https://learn.microsoft.com/en-us/microsoft-365/admin/create-groups/ownerless-groups-teams?view=o365-worldwide


2.First delete user in Azure AD permanent who is an owner of a Microsoft Group

3.most active user on the group should get offer to accept to be the new owner
In the audit log is the activity Ownerless group notify

If somebody accepts the offer, you will see in in the audit log activity "Ownerless group response"
If nobody accepts the offer you will see in the audit log daily entry "Ownerless group unattended"
All the activities in the audit log have identity "Group Configuration Processor"

In Sentinel query against the audit log you will find only activity Response, notify and unattended missing

Audit log filter:
![image](https://user-images.githubusercontent.com/34111090/211558268-7b2b18a0-6bfa-4ab5-8916-4116e7cd7e61.png)
Sentinel query
![image](https://user-images.githubusercontent.com/34111090/211558464-68295245-a7ee-4c1c-bbc8-e8ed4e94920d.png)

**Comment by v-vdixit** [comment]
Hi @funzel1 are you still facing this issue, please confirm, thanks!

**Comment by v-vdixit** [comment]
Gentle Reminder: We are waiting for your response on this issue. If you still need to keep this issue active, please respond on it in the next 2 days. If we don't receive response, we will be closing this issue as per our standard procedures, thanks!

**Comment by v-vdixit** [comment]
Hi @funzel1 Since we have not received a response in the last 5 days, we are closing your issue as per our standard operating procedures. If you still need support for this issue, feel free to re-open at any time. Thank you for your co-operation
