### ISSUE TITLE
Playbooks template "Block-AADUser_alert" bug

### ISSUE THREAD

**Issue by tabarik** [Azure/Azure-Sentinel#7051]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by v-mchatla** [comment]
Hi @tabarik,
Thanks for notifying us. Can you please elaborate the issue and share the data which helps in reproducing it.
Thanks
