### ISSUE TITLE
Function App to pull logs from Cisco Secure Endpoint (AMP) (Preview) Failure 

### ISSUE THREAD

**Issue by az-mikhail** [Azure/Azure-Sentinel#7053]
**Describe the bug**

**To Reproduce**
1. Deploy Cisco Secure Endpoint (AMP) (Preview) data connector
2. Deploy Azure Function to pull logs via Cisco API from Cisco Secure Endpoint (AMP) solution

**Expected behavior**
It is expected that logs from Cisco SE will be ingested into Sentinel

**Additional context**
There are a few errors in the Function app.

`Result: Failure Exception: Exception: Error while calling Cisco API. Response code: 401 Stack: File "/azure-functions-host/workers/python/3.8/LINUX/X64/azure_functions_worker/dispatcher.py", line 458, in _handle__invocation_request call_result = await self._loop.run_in_executor( File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run result = self.fn(*self.args, **self.kwargs) File "/azure-functions-host/workers/python/3.8/LINUX/X64/azure_functions_worker/dispatcher.py", line 701, in _run_sync_func return ExtensionManager.get_sync_invocation_wrapper(context, File "/azure-functions-host/workers/python/3.8/LINUX/X64/azure_functions_worker/extension.py", line 215, in _raw_invocation_wrapper result = function(**args) File "/home/site/wwwroot/AzureFunctionCiscoSecureEndpoint/main.py", line 51, in main for events in cli.get_audit_logs(audit_logs_last_ts): File "/home/site/wwwroot/AzureFunctionCiscoSecureEndpoint/main.py", line 102, in get_audit_logs raise Exception(f'Error while calling Cisco API. Response code: {res.status_code}')`

`Executed 'Functions.AzureFunctionCiscoSecureEndpoint' (Failed, Id=32136e66-f85c-4399-885d-c103421c4c8f, Duration=183ms)
`

**Comment by az-mikhail** [comment]
The issue can be closed.
The reason for this error was incorrectly configured API HOst.
Pay attention that for the Cisco tenants configured in the EU, the host API should be api.eu.amp.cisco.com.
For the tenants in North America: api.amp.cisco.com

**Comment by v-mchatla** [comment]
Hi @az-mikhail,
Thanks for the update. We will be closing it as fixed.
Thanks
