### ISSUE TITLE
Removal of deprecated workflows?

### ISSUE THREAD

**Issue by juju4** [Azure/Azure-Sentinel#7054]
**Describe the bug**
when forking repo, some deprecated workflows are still present and creating unnecessary errors.
aka
* .github/workflows/convertKqlFuncYamlToArmTemplate.yaml
* .github/workflows/runAsimTesters.yaml
resulting in
```
 Error: .github#L1
No event triggers defined in `on`
```

See for example https://github.com/juju4/Azure-Sentinel/actions

Above file are empty and replaced by
https://github.com/Azure/Azure-Sentinel/blob/master/.github/workflows/convertKqlFunctionYamlToArmTemplate.yaml
https://github.com/Azure/Azure-Sentinel/blob/master/.github/workflows/runAsimSchemaAndDataTesters.yaml
since 2 months it seems.

**To Reproduce**
1. Fork repo
2. Run actions

**Expected behavior**
Get same actions state than parent

**Comment by v-vdixit** [comment]
Hi @juju4 are you still facing this issue, please confirm, thanks!

**Comment by v-rbajaj** [comment]
Hi @juju4, Gentle Reminder: We are awaiting for your response on this issue. If you still need to keep this issue active please respond on it in the next 2 days. If we don't receive response, we will be close this issue.

**Comment by juju4** [comment]
This issue won't be fixed without any change.

That's polluting any fork of the repo.
Example with mine: https://github.com/juju4/Azure-Sentinel/actions as shared previously

**Comment by v-vdixit** [comment]
Hi @juju4 thanks for confirming we will work with the team on this and update you shortly.

**Comment by v-rbajaj** [comment]
Hi @juju4, we are waiting for response from the respective team, we will provide you an update.
