### ISSUE TITLE
Please provide samples for COVID-19 IOC list

### ISSUE THREAD

**Issue by King-Konsto** [Azure/Azure-Sentinel#710]
**Is your feature request related to a problem? Please describe.**
It would be really great if one could find the samples from the open-source COVID-19 indicator list (https://github.com/Azure/Azure-Sentinel/blob/1e5c7d84db69f9072a6fc332875b9f873f07f9c9/Sample%20Data/Feeds/Microsoft.Covid19.Indicators.csv) in a malware sharing platform (VT, MalwareBazaar, etc.) or if they would be available for download directly via Microsoft. I'm always frustrated if I find a list of IOCs tagged as malware/phish without any context and without the possibility to analyse the malware.

**Describe the solution you'd like**
Please provide also samples together with the hashes via a malware sharing platform or directly via MS.

**Describe alternatives you've considered**
Please provide at least more information about the malware/phish (e.g. which kind of malware?) instead of just publishing the hash and calling it malware/phish.

**Comment by shainw** [comment]
@King-Konsto - Thanks for the posting.  I am chatting with the folks that own these indicators and will post back once we have a response.  Thanks much, Shain

**Comment by jdallman** [comment]
@King-Konsto,  sorry for the delay. Although we understand the value of sharing more information related to these campaigns, Microsoft will not be sharing full samples for these hashes. You might want to check out this Jupyter Notebook that lets you identify how many of the hashes are on VT and emits a Yara rule. John and others will be iterating on it over time. (https://hub.gke.mybinder.org/user/johnlatwc-shared-gdl0bms5/notebooks/notebooks/COVID19-v.14.ipynb)

I will share your request for more information on malware (e.g. which kind) with the team so we can explore what we might do to improve analyst/RE scenarios.

**Comment by shainw** [comment]
Closing, re-open if needed.

**Comment by King-Konsto** [comment]
Thanks for the detailed response. I understand that it is not easy to share more data.
