### ISSUE TITLE
Updated Reset AAD Password Playbook using Graph API Beta

### ISSUE THREAD

**Issue by laughingman42** [Azure/Azure-Sentinel#713]
**Is your feature request related to a problem? Please describe.**
As documented here ([link](https://docs.microsoft.com/en-us/azure/active-directory/authentication/concept-sspr-writeback#unsupported-writeback-operations)), for tenants with SSPR (Self Service Password Reset) active and password writeback enabled, the password reset using Graph API v1 is not supported. Thus this playbook would not run correctly since it is using Graph API v1 for the resetPassword method 

**Describe the solution you'd like**
The same link notes that Graph API beta is supported for password writeback to tenant. This would require the use of passwordAuthenticationMethod: resetPassword ([link](https://docs.microsoft.com/en-us/graph/api/passwordauthenticationmethod-resetpassword?view=graph-rest-beta&tabs=http))

**Describe alternatives you've considered**
Unfortunately, with the changes to Graph API in beta, and the fact that SSPR with Password writeback has effectively blocked the usage of Graph API v1 for password reset, there doesn't seem to be any alternatives

**Additional context**

**Comment by dicolanl** [comment]
@laughingman42 good catch. 

Do you know if graph has a way to check if SSPR and writeback is enabled?  I could add a check in the playbook and use the Beta API.

**Comment by laughingman42** [comment]
@dicolanl - Unfortunately I could not find an attribute that indicates this. It maybe some sort of direct check between ADConnect and Azure. 
However, since the access model has changed for the new API, it would be great if you could create a new playbook for this. The new API requires generating an authorization bearer token with the right roles and permissions ([link](https://docs.microsoft.com/en-us/graph/api/passwordauthenticationmethod-resetpassword?view=graph-rest-beta&tabs=http#permissions)).

I have been unsuccessful to get this to work in my environment. Per the doc, you cannot do this using Application permission. So you need to use the Delegated permissions and generate a authorization bearer token using the credentials of an account with Authentication Admin role. After getting the token I am am unable to use the resetPassword method as it errors out with "The method is not supported for this URL." (using POST /users/{id}/authentication/passwordMethods/{id}/resetPassword)

**Comment by dicolanl** [comment]
@laughingman42 i cant seem to find a way to check for writeback being enabled. :(  what do you think about just changing this playbook to always use this api? https://docs.microsoft.com/en-us/graph/api/passwordauthenticationmethod-resetpassword?view=graph-rest-beta&tabs=http
