### ISSUE TITLE
Enrich-Incident-Alienvault-OTX - Template issue

### ISSUE THREAD

**Issue by qbcc-damianwheatley** [Azure/Azure-Sentinel#7130]
When the logic ap runs, it throws up this error.

InvalidTemplate. The execution of template action 'Filter_array_-_DNS_Entities' failed: The evaluation of 'query' action 'where' expression '@equals(item()['kind'], 'DnsResolution')' failed: 'The template language expression 'equals(item()['kind'], 'DnsResolution')' cannot be evaluated because property 'kind' cannot be selected.

**Comment by qbcc-damianwheatley** [comment]
Hi, Team any movement on this issue?

**Comment by v-amolpatil** [comment]
@qbcc-damianwheatley We have identified the fix and we will update you soon on this. Thanks!

**Comment by v-amolpatil** [comment]
Hi @qbcc-damianwheatley, We have fixed the issue as part of Pull request 7313 and hence closing the issue. Feel free to reopen if you need any assistance.
