### ISSUE TITLE
Azure Active Directory Connector not working

### ISSUE THREAD

**Issue by rod-trent** [Azure/Azure-Sentinel#7140]
**Describe the bug**
The Azure Active Directory Connector has stopped working. It seems to have been broken for at least a week (maybe more). 

**To Reproduce**
1. Open the Data Connector (either through the Data Connector blade or through the Content Hub solution)
2. Select the logs to collect.
3. Click the "Apply Changes" button.
4. Give an error message (see Screenshot below)

**Screenshots**
![failed](https://user-images.githubusercontent.com/56966432/214178904-c94ebb6d-db86-4b23-9ced-c210331cc31e.jpg)

**Additional context**
Many others are reporting this. Seems to be system wide.

**Comment by skjivert** [comment]
Just chiming in to say I'm also seeing this in my tenant.

**Comment by samikroy** [comment]
This seems to be working & resolved now 

![image](https://user-images.githubusercontent.com/20562985/225416708-f1b1b248-39ab-43bd-a1f5-1dc0d7ff6561.png)

@skjivert , @rod-trent  - Could you please confirm.

**Comment by v-vdixit** [comment]
Hi @rod-trent the issue has been resolved from our end so closing this, if you're still facing this issue please update here, thanks!
