### ISSUE TITLE
Cosmetic: change $(GetDate) to $($TimeStamp) 

### ISSUE THREAD

**Issue by andrePKI** [Azure/Azure-Sentinel#7162]
https://github.com/Azure/Azure-Sentinel/blob/8d9ef4e9e762c191d115d2d16df995bbd50fbd25/Tools/AzureDataExplorer/CreateTables_ADX/Create-LA-Tables-ADX.ps1#L327

Suggest to change `$(Get-Date)` to `$($TimeStamp)`  to show the same date/time as the log file name

**Comment by sreedharande** [comment]
@andrePKI - Good one, can you pls raise PR with this change

**Comment by v-rbajaj** [comment]
Since we have not received a response in the last 5 days, we are closing your issue https://github.com/Azure/Azure-Sentinel/issues/7162 as per our standard operating procedures. If you still need support for this issue, feel free to re-open at any time. Thank you for your co-operation.
