### ISSUE TITLE
Azure-Sentinel/Tools/AzureDataExplorer/Migrate-LA-to-ADX.ps1

### ISSUE THREAD

**Issue by andrePKI** [Azure/Azure-Sentinel#7166]
**Describe the bug**
The code is only selecting between datatypes `string` and `datetime`, but other datatypes exist, like `dynamic, real, int, long, bool`
These should be defined correctly in the ADX schema too 

**To Reproduce**
N/A

**Expected behavior**
correct transformation from Sentinel datatype to ADX datatype

**Comment by v-vdixit** [comment]
Hi @andrePKI are you still facing this issue, please confirm, thanks!

**Comment by v-vdixit** [comment]
Hi @andrePKI since we have not received a response in the last 7 days, we are closing your issue as per our standard operating procedures. If you still need support for this issue, feel free to re-open at any time. Thank you for your co-operation.
