### ISSUE TITLE
Azure-Sentinel/Tools/AzureDataExplorer/: specify subscription/resourcegroup for Event Hub namespace and Event Hubs

### ISSUE THREAD

**Issue by andrePKI** [Azure/Azure-Sentinel#7168]
**Is your feature request related to a problem? Please describe.**
The script currently creates event hubs in the same resource group as the existing Log Analytics workspace, as specified in the script parameter `LogAnalyticsResourceGroup`. That is not logical in bigger environments like ours - we need a separate resourcegroup.

**Describe the solution you'd like**
Therefore it is requested to have an extra script parameter to specify the (subscription and) resourcegroup for the eventhub namespace and event hubs.

**Describe alternatives you've considered**
none. Permissions won't let me or my security principal to create resources in the Sentinel/Log Analytics resource group

**Additional context**
Add the script parameter `EventHubResourceGroup` as an optional parameter, and if present use it in the code from line 418.
Set the default value if not specifed to `LogAnalyticsResourceGroup`.

**Comment by sreedharande** [comment]
@andrePKI - As this script is a community contribution, you are welcome to download it and make modifications that suit your environment. However, I am unable to endorse your specific changes to the script at this time. It is widely utilized within the community, and I have not yet encountered a need for additional parameters.
