### ISSUE TITLE
MS Sentinel > Data Connector > Sophos XG Firewall (Preview) > Function Parser link 404

### ISSUE THREAD

**Issue by vmonge** [Azure/Azure-Sentinel#7178]
**Issue Description:**
Sophos XG Firewall (Preview) Kusto Function parser link returning 404: 
https://raw.githubusercontent.com/Azure/Azure-Sentinel/master/Parsers/SophosXGFirewall/SophosXGFirewall.txt
showing 404 directly from Microsoft Sentinel Data Connector Sophos XG Firewall. 

**Repro Steps:** 
Azure> Microsoft Sentinel > Data Connector > Sophos XG Firewall (Preview) > 
Next Steps > Kusto Function parser Link "_Follow these steps to get this Kusto Functions_" > "**404: Not Found**" 
At : 
https://raw.githubusercontent.com/Azure/Azure-Sentinel/master/Parsers/SophosXGFirewall/SophosXGFirewall.txt

InHouse repro : Yes.

**Expected behavior**
Show Kusto Function Parser for Sophos XG Firewall logs in Syslog Table. 

**Presumably to route to this link instead:** 
https://github.com/Azure/Azure-Sentinel/blob/master/Solutions/Sophos%20XG%20Firewall/Parsers/SophosXGFirewall.txt

**Screenshots**

![image](https://user-images.githubusercontent.com/28789477/215534881-fbc97234-a04e-44c7-b885-f3b03a9627b6.png)

**Desktop (please complete the following information):**
 - OS: Windows11
 - Browser chrome/firefox/edge

**Comment by v-mchatla** [comment]
Hi @vmonge,
Thanks for notifying us. We have fixed this issue and closing the ticket.
Please feel free to reopen if you are still experiencing this problem or need any further assistance.
Thanks

**Comment by vmonge** [comment]
Hi @v-mchatla  
Is it ok to reopen this Issue again ?
I have noticed another one broken hyperlinks for Kusto parsers in MSSentinel : 

- SalesForce Hyperlink in Sentinel : 
https://raw.githubusercontent.com/Azure/Azure-Sentinel/master/Solutions/Salesforce%20Service%20Cloud/Parsers/SalesforceServiceCloud
(New one has the ".txt" at the end.)

![image](https://user-images.githubusercontent.com/28789477/218149664-8e7ea2d0-5814-454d-84a3-e634526be3d6.png)


Thanks in advance.
