### ISSUE TITLE
Confirm-AADRiskyUser Parse JSON Schema is invalid

### ISSUE THREAD

**Issue by richlilly2004** [Azure/Azure-Sentinel#718]
The parse JSON fails, the schema likely changed and needs to be updated to:

{
    "properties": {
        "@@odata.context": {
            "type": "string"
        },
        "accountEnabled": {
            "type": "boolean"
        },
        "ageGroup": {},
        "assignedLicenses": {
            "items": {
                "properties": {
                    "disabledPlans": {
                        "type": "array"
                    },
                    "skuId": {
                        "type": "string"
                    }
                },
                "required": [
                    "disabledPlans",
                    "skuId"
                ],
                "type": "object"
            },
            "type": "array"
        },
        "assignedPlans": {
            "items": {
                "properties": {
                    "assignedDateTime": {
                        "type": "string"
                    },
                    "capabilityStatus": {
                        "type": "string"
                    },
                    "service": {
                        "type": "string"
                    },
                    "servicePlanId": {
                        "type": "string"
                    }
                },
                "required": [
                    "assignedDateTime",
                    "capabilityStatus",
                    "service",
                    "servicePlanId"
                ],
                "type": "object"
            },
            "type": "array"
        },
        "businessPhones": {
            "items": {
                "type": "string"
            },
            "type": "array"
        },
        "city": {},
        "companyName": {
            "type": "string"
        },
        "consentProvidedForMinor": {},
        "country": {},
        "createdDateTime": {
            "type": "string"
        },
        "creationType": {},
        "deletedDateTime": {},
        "department": {
            "type": "string"
        },
        "deviceKeys": {
            "type": "array"
        },
        "displayName": {
            "type": "string"
        },
        "employeeId": {},
        "extension_63f00f8ae3bb4135affd4f2f5cf41ceb_CustomAttribute1": {
            "type": "string"
        },
        "extension_daa2389c9c1e4e38ae913edbf56e7c2f_division": {
            "type": "string"
        },
        "externalUserState": {},
        "externalUserStateChangeDateTime": {},
        "faxNumber": {
            "type": "string"
        },
        "givenName": {
            "type": "string"
        },
        "id": {
            "type": "string"
        },
        "identities": {
            "items": {
                "properties": {
                    "issuer": {
                        "type": "string"
                    },
                    "issuerAssignedId": {
                        "type": "string"
                    },
                    "signInType": {
                        "type": "string"
                    }
                },
                "required": [
                    "signInType",
                    "issuer",
                    "issuerAssignedId"
                ],
                "type": "object"
            },
            "type": "array"
        },
        "imAddresses": {
            "items": {
                "type": "string"
            },
            "type": "array"
        },
        "infoCatalogs": {
            "type": "array"
        },
        "isResourceAccount": {},
        "jobTitle": {
            "type": "string"
        },
        "legalAgeGroupClassification": {},
        "mail": {
            "type": "string"
        },
        "mailNickname": {
            "type": "string"
        },
        "mobilePhone": {
            "type": "string"
        },
        "officeLocation": {
            "type": "string"
        },
        "onPremisesDistinguishedName": {
            "type": "string"
        },
        "onPremisesDomainName": {
            "type": "string"
        },
        "onPremisesExtensionAttributes": {
            "properties": {
                "extensionAttribute1": {
                    "type": "string"
                },
                "extensionAttribute10": {},
                "extensionAttribute11": {},
                "extensionAttribute12": {},
                "extensionAttribute13": {},
                "extensionAttribute14": {},
                "extensionAttribute15": {},
                "extensionAttribute2": {},
                "extensionAttribute3": {},
                "extensionAttribute4": {},
                "extensionAttribute5": {},
                "extensionAttribute6": {},
                "extensionAttribute7": {},
                "extensionAttribute8": {},
                "extensionAttribute9": {}
            },
            "type": "object"
        },
        "onPremisesImmutableId": {
            "type": "string"
        },
        "onPremisesLastSyncDateTime": {
            "type": "string"
        },
        "onPremisesProvisioningErrors": {
            "type": "array"
        },
        "onPremisesSamAccountName": {
            "type": "string"
        },
        "onPremisesSecurityIdentifier": {
            "type": "string"
        },
        "onPremisesSyncEnabled": {
            "type": "boolean"
        },
        "onPremisesUserPrincipalName": {
            "type": "string"
        },
        "otherMails": {
            "type": "array"
        },
        "passwordPolicies": {
            "type": "string"
        },
        "passwordProfile": {},
        "postalCode": {},
        "preferredDataLocation": {},
        "preferredLanguage": {},
        "provisionedPlans": {
            "items": {
                "properties": {
                    "capabilityStatus": {
                        "type": "string"
                    },
                    "provisioningStatus": {
                        "type": "string"
                    },
                    "service": {
                        "type": "string"
                    }
                },
                "required": [
                    "capabilityStatus",
                    "provisioningStatus",
                    "service"
                ],
                "type": "object"
            },
            "type": "array"
        },
        "proxyAddresses": {
            "items": {
                "type": "string"
            },
            "type": "array"
        },
        "refreshTokensValidFromDateTime": {
            "type": "string"
        },
        "showInAddressList": {},
        "signInSessionsValidFromDateTime": {
            "type": "string"
        },
        "state": {},
        "streetAddress": {},
        "surname": {
            "type": "string"
        },
        "usageLocation": {
            "type": "string"
        },
        "userPrincipalName": {
            "type": "string"
        },
        "userType": {
            "type": "string"
        }
    },
    "type": "object"
}

**Comment by dicolanl** [comment]
PR #749 merged to fix this
