### ISSUE TITLE
AWS-SecurityHubFindings zip file is out of sync with host.json file

### ISSUE THREAD

**Issue by rcscoggin** [Azure/Azure-Sentinel#7190]
**Describe the bug**
Currently getting the error:  Result: Failure Exception: ModuleNotFoundError: No module named '_cffi_backend'. Please check the requirements.txt file for the missing module.

this has happened since the function restarted on Jan 2nd and pulled the Dec 30th zip file.

**To Reproduce**
Download the zip and compare to the current baseline for that file, should check others to ensure. Thanks!

https://github.com/Azure/Azure-Sentinel/blob/master/DataConnectors/AWS-SecurityHubFindings/AzFunAWSSecurityHubIngestion.zip?raw=true

**Comment by rcscoggin** [comment]
@sreedharande any ETA on when you might be able to look at this issue?  We've been unable to resolve the problem on our side.  It appears to be a missing module.  Please, advise.  Thanks!

**Comment by rcscoggin** [comment]
@v-amolpatil any ETA on when you might be able to look at this issue? We've been unable to resolve the problem on our side. It appears to be a missing module. Please, advise. Thanks!

**Comment by sreedharande** [comment]
@rcscoggin Thanks Rodger, Can you pls raise PR with the missing module

**Comment by rcscoggin** [comment]
@sreedharande  I cannot raise a PR as I am only reporting the error.  Our Azure function stopped working around Jan 2 and the error was "Result: Failure Exception: ModuleNotFoundError: No module named '_cffi_backend'"  I do not have a development environment to fix the code and test, only a production environment with error.  Does this error not happen when you run this in your test environment?  Is there more information about our Azure function that would help?  We did not change anything, it just stopped working after the commits on Dec 30, 2022 and subsequent automated fetch from this repo by the Azure function on a restart.

**Comment by rcscoggin** [comment]
@sreedharande  Any update on this? I'm not sure what you want me to do to try and fix this, a module is missing.

**Comment by v-vdixit** [comment]
Hi @rcscoggin we are discussing this with team, will update you shortly, thanks!

**Comment by v-vdixit** [comment]
Hi @rcscoggin we are still working with the team will update you shortly, thanks!

**Comment by v-vdixit** [comment]
Hi @rcscoggin Can you please provide a screenshot of Execution logs, so that we can work on tracing the root cause of this, thanks!

**Comment by rcscoggin** [comment]
@v-vdixit  I wiped away the logic app entirely and re-installed, it is now working with the current master branch.  Unfortunately, in doing so the only information I have is:

Result: Failure Exception: ModuleNotFoundError: No module named '_cffi_backend'. Please check the requirements.txt file for the missing module.

this happened when the function restarted on Jan 2nd and pulled the Dec 30th zip file.  

We can close this issue unless others have reported similar.

Thanks!

**Comment by v-vdixit** [comment]
Hi @rcscoggin thanks for your update, please ensure you are using the latest path for function app zip file and the correct python version, as this usually happening with python 3.9 and not with python 3.8. if you have made any customizations in deployment, please update accordingly, for consumption plan we don't have option from UI to change. I would suggest redeploying the function app and update version.
If you are using premium function app plan, then you can navigate to Configuration --> General Settings and choose version.

**Comment by v-vdixit** [comment]
Gentle Reminder: We are waiting for your response on this issue. If you still need to keep this issue active, please respond on it in the next 2 days. If we don't receive response, we will be closing this issue as per our standard procedures, thanks!

**Comment by v-vdixit** [comment]
Since we have not received a response in the last 5 days, we are closing your issue as per our standard operating procedures. If you still need support for this issue, feel free to re-open at any time. Thank you for your co-operation
