### ISSUE TITLE
CEF Install script has SELinux failure on EL 8

### ISSUE THREAD

**Issue by dsmorse** [Azure/Azure-Sentinel#7212]
**Describe the bug**
When deploying the CEF installer script based on the instructions in Azure Sentinel. the script fails on Rocky Linux 8 due to an issue with SELInux. 
 When I follow the CEF install steps from Azure Sentinel it has you wget the file:
  https://raw.githubusercontent.com/Azure/Azure-Sentinel/master/DataConnectors/CEF/cef_installer.py 
and executing it via python. 
When I run this it fails to restart the rsyslog service.  Looking at the logs, the services fails because the script writes the conf file with the wrong SELinux context.  
As a workaround I have to manually run the command:
`sudo chcon -t syslog_conf_t /etc/rsyslog.conf`

Side Note: it fails on Rocky Linux 9 too in other ways, but I noticed that RHEL/Rocky Linux 9 is not listed as supported in the script, which would be nice to tell the user in the connector deployment page. 

**To Reproduce**
1. Go to Azure Sentinel and get the install command from the "Data Connectors" page
2. From an Enterprise Linux 8 host with SELinux enabled execute the command
3. Verify in the script output if rsyslog service restarts successfully or if a failure warning is posted. 
4. See workaround to set the SELinux context and manually restart the service. 

**Expected behavior**
script should write the file with the correct SELinux settings so that the script is able to restart the service successfully

**Desktop (please complete the following information):**
 - OS: Rocky Linux 8

**Comment by v-vdixit** [comment]
Hi @dsmorse are you still facing this issue?

**Comment by v-vdixit** [comment]
Since we have not received a response in the last 5 days, we are closing your issue as per our standard operating procedures. If you still need support for this issue, feel free to re-open at any time. Thank you for your co-operation
