### ISSUE TITLE
Rsyslogd fails to start (Segmentation Fault)

### ISSUE THREAD

**Issue by MathiasVandePol** [Azure/Azure-Sentinel#724]
**Describe the bug**
After installing the CEF collector with the cef-installer.py script, rsyslogd service fails to start and throws an error: "Segmentation Fault".

**To Reproduce**
1. Install the Cef collector with ```sudo wget https://raw.githubusercontent.com/Azure/Azure-Sentinel/master/DataConnectors/CEF/cef_installer.py&&sudo python cef_installer.py [WorkspaceID] [Workspace Primary Key]```
2. run sudo rsyslogd, notice it saying "Segmentation Fault"

**Possible Culprit**
 I noticed after removing the ~ symbol in security-config-omsagent.conf that it started working again so I guess it fails parsing that line. Looks like tilde is legacy and replaced with `stop`
https://www.rsyslog.com/doc/master/configuration/actions.html#discard-stop 

**Additional context**
Running on  CentOS Linux release 7.8.2003 (Core)

```
rsyslogd 8.24.0-52.el7, compiled with:
        PLATFORM:                               x86_64-redhat-linux-gnu
        PLATFORM (lsb_release -d):
        FEATURE_REGEXP:                         Yes
        GSSAPI Kerberos 5 support:              Yes
        FEATURE_DEBUG (debug build, slow code): No
        32bit Atomic operations supported:      Yes
        64bit Atomic operations supported:      Yes
        memory allocator:                       system default
        Runtime Instrumentation (slow code):    No
        uuid support:                           Yes
        Number of Bits in RainerScript integers: 64

```

**Comment by NoamLandress** [comment]
Hi, thanks for your contribution. 
We have updated the "security-config-omsagent.conf" file content. 
You can run the "cef_troubleshoot.py" script and it will guide you through how to update it.
Thanks.

**Comment by preetikr** [comment]
This is now resolved, hence closing.
