### ISSUE TITLE
CEF troubleshoot firewall warning does not go away after adding rule

### ISSUE THREAD

**Issue by MathiasVandePol** [Azure/Azure-Sentinel#725]
**Describe the bug**
cef_troubleshoot.py keeps outputting that there was no exception found for the omsagent.

> Warning: no exception found for omsagent in the firewall
You can add exception for the agent port[25226] by using the following commands:
Add exception:
sudo firewall-cmd --direct --add-rule ipv4 filter INPUT 0 -p tcp --dport 25226  -j ACCEPT
Validate the exception was added in the configuration:
sudo firewall-cmd --direct --get-rules ipv4 filter INPUT
Reload the firewall:
sudo firewall-cmd --reload
You can disable your firewall by using this command - not recommended:
sudo systemctl stop firewalld

**To Reproduce**
1. Run `cef_troubleshoot.py`
2. Add the rule with the command cef_troubleshoot.py proposes (`sudo firewall-cmd --direct --add-rule ipv4 filter INPUT 0 -p tcp --dport 25226  -j ACCEPT`)
3. Validate the rule was added: ```sudo firewall-cmd --direct --get-rules ipv4 filter INPUT```
which outputs:``` 0 -p tcp --dport 25226 -j ACCEPT```
4. Reload the firewall with ```sudo firewall-cmd --reload```
4. Rerun `cef_troubleshoot.py` and get the same messages

This is because the rule is added to the direct iptables ruleset, not the public.xml as the check requires you to do. (see https://github.com/Azure/Azure-Sentinel/blob/master/DataConnectors/CEF/cef_troubleshoot.py#L42)

**Possible Solution**
Change the command to something in the line of
`sudo firewall-cmd --permanent --zone=public --add-rich-rule='rule family=ipv4 protocol=tcp to-port=25226'`

**Expected behavior**
The Warning should disappear after adding the rule.

**Comment by Castaldio86** [comment]
During the install of the OMS agent on 20.04 I found that netstat was missing.

Could you try verify if netstat is installed.

If not, could you run:

apt-get install python net-tools

**Comment by NoamLandress** [comment]
Thanks for the contribution, we are taking a look and will address this issue soon.

**Comment by v-laanjana** [comment]
@MathiasVandePol are you still facing same issue ??

**Comment by v-laanjana** [comment]
@NoamLandress is this issue fixed ??

**Comment by NoamLandress** [comment]
Hi, Yes. Please share if the issue still persists.
