### ISSUE TITLE
AbuseIPDB-EnrichIncidentByIPInfo

### ISSUE THREAD

**Issue by martie5858** [Azure/Azure-Sentinel#7306]
**Describe the bug**
When pulling the IP data from AbuseIPDB the countryName returns NULL

**To Reproduce**
1. Edit the Playbook in Logic Apps Designer
2. Open Append Results to Results List
3. Add the following value:   "Country": @{body('AuseIPDB_CHECK_Endpoint')?['data']?['countryName']},
4. Run Playbook
5. Under Run history - Open Run
6. Result
{
  "Country": null,
  "abuseConfidenceScore": 0,
  "hostnames": [
    "220-253-27-156.tpgi.com.au"
  ],
  "ipAddress": "220.253.27.156",
  "ipVersion": 4,
  "isPublic": true,
  "isWhitelisted": null,
  "isp": "iiNET Limited",
  "lastReportedAt": null,
  "numDistinctUsers": 0,
  "totalReports": 0,
  "usageType": null
}

**Expected behavior**
Country should be Australia in this example.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome

**Smartphone (please complete the following information):**
n/a

**Additional context**
Testing the use and functionality of the playbook

**Comment by v-amolpatil** [comment]
Hi @martie5858, Could you please try using below  code `"Country": "@body('AuseIPDB_CHECK_Endpoint')?['data']?['countryName']",`
and let us know if it works?

**Comment by martie5858** [comment]
Thank you.

**Comment by v-amolpatil** [comment]
Hi @martie5858, Is the provided code working?

**Comment by martie5858** [comment]
I needed to add some additional flags to allow verbose responses. This
solved this issue.

**Comment by v-amolpatil** [comment]
Closing issue as this is now resolved.
