### ISSUE TITLE
Outdated Mitre Attack Workbook

### ISSUE THREAD

**Issue by kraken8585** [Azure/Azure-Sentinel#7309]
**Is your feature request related to a problem? Please describe.**
The current workbook is in reference to mitre attack v11 - Would recommend updating this to v12 to stay relevant
https://github.com/Azure/Azure-Sentinel/blob/master/Workbooks/MITREAttack.json

**Describe the solution you'd like**
Latest version -> https://attack.mitre.org/versions/v12/

**Comment by ashwin-patil** [comment]
I will take a look at it and update the code with latest MITRE ATT&CK version.

**Comment by v-rbajaj** [comment]
Hi @kraken8585, according to respective team, this is in their backlog and they will soon update it in sometime.
