### ISSUE TITLE
PickupSTIX not accepting new requests for this feed at this time.

### ISSUE THREAD

**Issue by RemyDePoorter** [Azure/Azure-Sentinel#7317]
**Describe the bug**
PickupSTIX not accepting new requests for this feed at this time.

**To Reproduce**
Go to https://www.celerium.com/pickupstix

**Comment by v-rbajaj** [comment]
Hi @RemyDePoorter,
It isn't accepting new requests feed. 
You can reach out to them on support@celerium.com via mail.

**Comment by v-rbajaj** [comment]
Gentle Reminder: We are awaiting for your response on this issue. If you still need to keep this issue active please respond on it in the next 2 days. If we don't receive response, we will be close this issue.

**Comment by v-rbajaj** [comment]
Since we have not received a response in the last 5 days, we are closing your issue https://github.com/Azure/Azure-Sentinel/issues/7317 as per our standard operating procedures. If you still need support for this issue, feel free to re-open at any time. Thank you for your co-operation.
