### ISSUE TITLE
Private Connection Sentinel S3 bucket.

### ISSUE THREAD

**Issue by CarlosAugustoDeSouzaJunior** [Azure/Azure-Sentinel#7320]
**Is your feature request related to a problem? Please describe.**

All our S3 and SQS queue in production are private, so we cannot use the connector. We need also have more information about  how Sentiennel AWS account works in the backend and were the connectors runs.

**Describe the solution you'd like**

We would like to have V-Net Integration for sentienl and the connector using this integration to comunicate with AWS S3 and queues.

**Describe alternatives you've considered**

We do not have as per  regulamentations requiriments.

**Additional context**

**Comment by v-vdixit** [comment]
Hi @CarlosAugustoDeSouzaJunior are you still facing this issue, please confirm, thanks!

**Comment by v-vdixit** [comment]
Since we have not received a response in the last 7 days, we are closing your issue as per our standard operating procedures. If you still need support for this issue, feel free to re-open at any time. Thank you for your co-operation.
