### ISSUE TITLE
Playbook - Get-SentinelAlertsEvidence - Fails 

### ISSUE THREAD

**Issue by sphtd** [Azure/Azure-Sentinel#7331]
**Describe the bug**
This used to work, but now we're getting
Unable to process template language expressions in action 'Parse_JSON' inputs at line '0' and column '0': 'Required property 'content' expects a value but got null. Path ''.'.
When parsing the Sentinel alert.

**To Reproduce**
On trigger, rule fails on step 2, with above Invalid Template error.

**Expected behavior**
Should run through all steps in the LogicApp without error, assuming all connections correctly configured.

**Screenshots**
![image](https://user-images.githubusercontent.com/22845822/218483068-1e44882e-a37a-41a8-97ae-5dcdc4371e21.png)

**Additional context**

**Comment by v-vdixit** [comment]
Hi @sphtd thanks for flagging this, we are working with the team on fixing this, will update you shortly.

**Comment by v-vdixit** [comment]
Hi @sphtd we have worked on testing this with the team, but we are not getting this error at our end, can you please provide us a screenshot of the output of the step that is executed right before the step for which the playbook is failing for you, thanks!

**Comment by v-vdixit** [comment]
Hi @sphtd Gentle Reminder: We are waiting for your response on this issue. If you still need to keep this issue active, please respond on it in the next 2 days. If we don't receive response, we will be closing this issue as per our standard procedures, thanks!

**Comment by v-vdixit** [comment]
Since we have not received a response in the last 5 days, we are closing your issue as per our standard operating procedures. If you still need support for this issue, feel free to re-open at any time. Thank you for your co-operation.
