### ISSUE TITLE
Sentinel Analytics rule "Conditional Access Policy Modified by New User"

### ISSUE THREAD

**Issue by MarianHHristov** [Azure/Azure-Sentinel#7332]
The rule is called “Conditional Access Policy Modified by New User” and according to its description: _Detects a Conditional Access Policy being modified by a user who has not modified a policy **in the last 14 days.**_

That statement is confirmed by the KQL query:
let known_users = (AuditLogs
  | where TimeGenerated between**(ago(14d)..ago(1d))**
  | where OperationName has "conditional access policy"
  | where Result =~ "success"
  | extend userPrincipalName = tostring(parse_json(tostring(InitiatedBy.user)).userPrincipalName)
  | summarize by userPrincipalName);
  AuditLogs
  | where TimeGenerated > ago(1d)
  | where OperationName has "conditional access policy"
  | where Result =~ "success"
  | extend userPrincipalName = tostring(parse_json(tostring(InitiatedBy.user)).userPrincipalName)
  | extend CAPolicyName = tostring(TargetResources[0].displayName)
  | extend ipAddress = tostring(parse_json(tostring(InitiatedBy.user)).ipAddress)
  | where userPrincipalName !in (known_users)
  | extend NewPolicyValues = TargetResources[0].modifiedProperties[0].newValue
  | extend OldPolicyValues = TargetResources[0].modifiedProperties[0].oldValue
  | project-reorder TimeGenerated, OperationName, CAPolicyName, userPrincipalName, ipAddress, NewPolicyValues, OldPolicyValues

However, looking into the “Query scheduling”, I noticed that the “Lookup data from the last” is not 14 days.
Notably, it is just 7 days.

![image](https://user-images.githubusercontent.com/125347633/218672539-f2fa8f78-d6fe-427b-b08a-40f6dcb381fb.png)

**Comment by v-amolpatil** [comment]
@MarianHHristov We have fixed the issue, it will take some days or 1 week to reflect.

**Comment by v-amolpatil** [comment]
Hi @MarianHHristov, This is now reflecting in Gallary content as shown in below screenshot, so closing the issue as fixed. Feel free to reopen if you need any assistance.

![image](https://user-images.githubusercontent.com/107389644/222378797-84cfe61e-b980-4cb8-91d0-d1d8f79eee1c.png)
