### ISSUE TITLE
Playbooks template "Isolate-MDEMachine" bug

### ISSUE THREAD

**Issue by nmohammed94** [Azure/Azure-Sentinel#7335]
The template in MS Sentinel doesn't point to an existing GItHub directory.

There's no way to check the pre-requites from the Sentinel portal

**Comment by nmohammed94** [comment]
When you click here:
[Graphical user interface, application  Description automatically generated]

You get a 404 page:
[Graphical user interface, website  Description automatically generated]

The pre-requisites are documented on GitHub not Sentinel. So it makes it difficult to show them to the customer.

Kind Regards,
Naser Mohammed
Support Engineer
Azure Security, Identity & Management
Microsoft Customer Service & Support
Office: +962 (6) 550 9419
***@***.******@***.***>
Working hours: Sun-Thu 9 AM-6 PM UTC+3

***@***.***

Team Manager | O. Militao ***@***.******@***.***>)

**Comment by v-amolpatil** [comment]
Hi @nmohammed94, Could you please try to install the solution "Microsoft Defender For Endpoint" from the content hub?

**Comment by v-amolpatil** [comment]
Reminder: We are awaiting for your response on this issue. If you still need to keep this issue active please respond on it in the next 2 days 5 April.. If we don't receive response by given date we will be close this issue.

**Comment by v-amolpatil** [comment]
Since we have not received a response in the last 5 days, we are closing your issue #7335 as per our standard operating procedures. If you still need support for this issue, feel free to re-open at any time. 
Thank you for your co-operation.
