### ISSUE TITLE
workbook image validation is failing on a valid guid input 

### ISSUE THREAD

**Issue by aviatam** [Azure/Azure-Sentinel#7379]
**Describe the bug**
Unable to add SVG icon to workbook due to validation , even when entering valid GUID exception returned indicating 
GUID is invalid see error --> https://dev.azure.com/azure/Azure-Sentinel/_build/results?buildId=54782&view=logs&j=5c2f387a-8476-5c61-1167-a0d2a5b79536&t=5297d577-9e13-555d-6285-d2eda31e9542&l=21

Notice: validation is not mandatory but blocks the pr 

**To Reproduce**
view this file https://github.com/Azure/Azure-Sentinel/pull/7378/files#diff-35d78a044eba49bf5d858da2fdb84b869fdd2545f16bacbf691d16d6b05e8ef3 and rerun the pull request 
please review this pr --> https://github.com/Azure/Azure-Sentinel/pull/7378

**Expected behavior**
validation should pass

**Comment by v-sabiraj** [comment]
@aviatam, please change the highlighted guid as it is not in correct format.
![image](https://user-images.githubusercontent.com/94349919/220172253-d1c7f66e-ed33-437e-add2-9f6c24c8d13b.png)

**Comment by v-sabiraj** [comment]
Closing this as the validations are now passing in PR. Thanks.
