### ISSUE TITLE
Deception honey tokens solution throws python error

### ISSUE THREAD

**Issue by KociaQuePasa** [Azure/Azure-Sentinel#7383]
**Describe the bug**
After deployment of the solution, when I try to deploy tokens at scale I get a Python error displayed:

*"NewConnectionError('<urllib3. connection.HTTPSConnection obiect at 0x71373831c0>: Failed to establish a new connection: (Errno -2] Name or service not known')), «class 'requests. exceptions.ConnectionError'>, init .Dv, 392"*

**To Reproduce**
1. Install Solution in MS Sentinel
2. Configure all the permissions
3. Go to Sentinel Workbooks and find SOCHTManagement workbook (default naming)
4. Go to Keyvaults and click deploy at scale
5. Admire the beautiful error

**Expected behavior**
Tokens get deployed according to what was configured and I dont get python error..

**Screenshots**
Exact error text pasted in description

**Desktop (please complete the following information):**
- Done via Azure Portal (MacOS, Firefox)

**Comment by v-vdixit** [comment]
Hi @KociaQuePasa, The error message you received suggests that the Python script is unable to establish a new HTTPS connection to the target server due to a DNS resolution issue. This can happen for several reasons, such as a misconfigured DNS server, a network connectivity issue, or a firewall blocking the connection.
You can try to resolve this issue by using any of the following: -
1) Check the target server hostname and IP address: Make sure that you have correctly entered the hostname or IP address of the target server in the Python script. You can try to ping the target server from the machine where the Python script is running to ensure that it is reachable.
2) Check the DNS server configuration: If the target server hostname cannot be resolved to an IP address, check your DNS server configuration. Make sure that the DNS server is configured correctly and is accessible from the machine where the Python script is running.
3) Check the network connectivity: If the target server is located on a different network, check the network connectivity between the machine where the Python script is running and the target server. Make sure that there are no network connectivity issues or firewall rules blocking the connection.
4) Check the proxy server configuration: If you are using a proxy server to connect to the Internet, make sure that the Python script is configured to use the proxy server. You can set the http_proxy and https_proxy environment variables in the script to specify the proxy server.
I hope this helps your issue, if none of these work for you please let me know, thanks

**Comment by v-vdixit** [comment]
Hi @KociaQuePasa are you still facing this issue?

**Comment by v-vdixit** [comment]
Hi @KociaQuePasa in that case you just make sure that all the necessary dependencies required for the solution to work properly are installed and updated, we will test the function app Code with changes and update you on this, thanks

**Comment by KociaQuePasa** [comment]
I have went through the whole procedure with the MS Support, step by step.
AND still the same issue occured.
I had a hypothesis that in the error output, at the end the number 392 corresponds to the line of code that has thrown an error, but I'm no Python guy so that's just my wild guess.

Anyway, I'll be waiting for your update.

**Comment by v-vdixit** [comment]
Hi @KociaQuePasa If you still need to keep this issue active please respond on it in the next 2 days <date>.. If we don't receive response by given date we will be close this issue. Thanks!

**Comment by KociaQuePasa** [comment]
Hi, I still need a little more time.
If that's ok I'd like to keep that Issue hanging.
Once I confirm that the error has been resolved and the solution works as intended I'll provide an update.
Is that ok?

**Comment by v-vdixit** [comment]
Hi @KociaQuePasa, please provide update on this, thanks!

**Comment by KociaQuePasa** [comment]
Today we're redeploying whole solution so I'll see where it goes.
IF (Stuff works) then I'll update and close.
Else: I'll keep on ranting about the non-working solution :)

**Comment by KociaQuePasa** [comment]
And nothing.
We've reinstalled everything.
All I got when I clicked "Deploy at scale" was the url with a blank page:
"https:// <funcname>.azurewebsites.net/.auth/login/aad/callback".

And nothing else.

**Comment by v-vdixit** [comment]
Hi @KociaQuePasa can you please provide some elaboration on this, it will be helpful for us in tracing this error and resolving, thanks!

**Comment by KociaQuePasa** [comment]
Hi, yes:
Generally we have reinstalled the whole solution from scratch, recreated all resources that take part in the process, created new SP and so on.
As I already had full permissions on the KV access policy I went straight to "deploy at scale" from the Sentinel workbook for the solution.
And instead of deployment of the honeysecret I got blank page with the URL above.

Nothing more.

**Comment by KociaQuePasa** [comment]
[Pika-what](https://www.startpage.com/av/proxy-image?piurl=http%3A%2F%2Fpictures.fanart-central.net%2Fs%2FShido%2F848672%2FShido-848672-Pikachu.png&sp=1683714911Te8a63e05b0960839d2379f89b7b16277155d35aa976fe1ffd21da3fbaecc95d1)

**Comment by KociaQuePasa** [comment]
[Pika-what](http://www.fanart-central.net/pictures/user/Shido/848672/Pikachu)

**Comment by v-vdixit** [comment]
Hi @KociaQuePasa, thanks for the update, we are discussing with the team, will update you shortly.

**Comment by v-vdixit** [comment]
Hi @KociaQuePasa we are working with the solution owners for this, will update you once we hear back from them, thanks!

**Comment by v-vdixit** [comment]
Hi @KociaQuePasa we are still waiting to hear back from the concerned team, apologies for the inconvenience, we will update you once we hear back from the team, thanks!

**Comment by v-vdixit** [comment]
Hi @KociaQuePasa thanks for your patience please ensure you have admin access to install and use this solution and refer to this documentation - [Honey Tokens Solution](https://github.com/Azure/Azure-Sentinel/blob/master/Solutions/HoneyTokens/README.md) to troubleshoot from your end, we are working on with the team will update you shortly, thanks!

**Comment by v-vdixit** [comment]
Hi @KociaQuePasa we are waiting for your update with confirmation about access level, please respond in the next 2 days else we will have to close this issue as per our standard procedure, thanks!

**Comment by KociaQuePasa** [comment]
Hi, I still need a little more time for this installation to take place. I'll update You once I can get it moving.
Thank You for all the efforts <3

**Comment by v-vdixit** [comment]
Hi @KociaQuePasa we are waiting for your update, thanks!

**Comment by KociaQuePasa** [comment]
Hi,
After 6 times of reinstalling the solution, as every time we had to purge manually whole deployment, we have managed to install the solution.
But then we got another error in the welcome tab of the workbook for the solution in sentinel:
![image](https://github.com/Azure/Azure-Sentinel/assets/34538439/d0b73ab6-d1cf-40bc-bd79-c680c1051ede)

So.. that's how it went.

**Comment by v-vdixit** [comment]
Hi @KociaQuePasa for 'no response' error one possible cause is that the workbook is not properly configured. You can check the configuration of the workbook and ensure that all the required parameters are set correctly. Another possible cause is that there is a connectivity issue between the workbook and the data source. You can check the connectivity between the workbook and the data source and ensure that the data source is accessible. If the issue persists, you can collect logs manually to troubleshoot the issue, thanks!

**Comment by v-vdixit** [comment]
Gentle Reminder: We are waiting for your response on this issue. If you still need to keep this issue active, please respond on it in the next 2 days. If we don't receive response, we will be closing this issue as per our standard procedures, thanks!

**Comment by v-vdixit** [comment]
Since we have not received a response in the last 5 days, we are closing your issue as per our standard operating procedures. If you still need support for this issue, feel free to re-open at any time. Thank you for your co-operation.
