### ISSUE TITLE
Get-GeoFromIpAndTagIncident playbook run failed

### ISSUE THREAD

**Issue by tamer-fpga** [Azure/Azure-Sentinel#7435]
Hello there, I am actually still having this issue of running "Get-GeoFromIpAndTagIncident" Playbook. It returns failed (Bad Request). When I click on "View run" to troubleshoot the issue, I get a red exclamation mark on the alert - get incident. I click on it and it shows the 400 bad request response code.

{
  "error": {
    "code": 400,
    "source": "logic-apis-eastus.azure-apim.net",
    "clientRequestId": "efe7-k05-03a5-abce-2b9c4ca08eb",
    "message": "The response is not in a JSON format.",
    "innerError": "Invalid subscription id or resource group or API connection"
  }
}

**Comment by v-mchatla** [comment]
Hi @tamer-fpga,
Thanks for reaching out to us. We are not able to repro the issue but its clear that there is some issue with one of these - subscriptionid, resourcegroup, and API Connection. If your subscription and resourcegroup details are correct. Please try authorizing the API Connection.
![image](https://user-images.githubusercontent.com/108806639/221564886-8652d0a6-d56a-4cae-9717-fe356e67fd51.png)
Let us know if you are still facing the issue.

**Comment by tamer-fpga** [comment]
> Hi @tamer-fpga, Thanks for reaching out to us. We are not able to repro the issue but its clear that there is some issue with one of these - subscriptionid, resourcegroup, and API Connection. If your subscription and resourcegroup details are correct. Please try authorizing the API Connection. ![image](https://user-images.githubusercontent.com/108806639/221564886-8652d0a6-d56a-4cae-9717-fe356e67fd51.png) Let us know if you are still facing the issue.

I authorized it again. All info there are correct as well. However, the issue still persists.

**Comment by v-amolpatil** [comment]
Hi @tamer-fpga, When we try at our end we are getting below error 403 error which is failing as we dont have key. Could you please share the api key? As the key is only available in Pro(page link https://members.ip-api.com/#pricing)
{
  "status": "fail",
  "message": "SSL unavailable for this endpoint, order a key at https://members.ip-api.com/"
}

**Comment by tamer-fpga** [comment]
> 
where can I find it at my end?

**Comment by v-amolpatil** [comment]
FYI, @tamer-fpga we have provided a fix for this and its changes will reflect in few days.

**Comment by tamer-fpga** [comment]
> FYI, @tamer-fpga we have provided a fix for this and its changes will reflect in few days.

Thanks a lot for the efforts. I will verify and get back to you in a few days.

**Comment by tamer-fpga** [comment]
The playbook still fails. I have tested it today.

**Comment by v-amolpatil** [comment]
Hi @tamer-fpga, I tested and is working. Could you please try to redeploy by refering below link? Make sure to deploy custom connector which is also provided in the link below:
https://github.com/Azure/Azure-Sentinel/tree/master/Playbooks/Get-GeoFromIpAndTagIncident
Let me know your feedback.

**Comment by v-amolpatil** [comment]
Gentle Reminder: We are awaiting for your response on this issue. If you still need to keep this issue active please respond on it in the next 2 days by 30 March.. If we don't receive the response by given date we will be close this issue.

**Comment by v-amolpatil** [comment]
Since we have not received a response in the last 5 days, we are closing your issue #7435 as per our standard operating procedures. If you still need support for this issue, feel free to re-open at any time. 
Thank you for your co-operation.

**Comment by deaningraham** [comment]
This solution did not work.
