### ISSUE TITLE
TAXII 2.0 Intelligence Feed not available anymore

### ISSUE THREAD

**Issue by tamer-fpga** [Azure/Azure-Sentinel#7460]
Hello There,
Regarding module 2, Exercise 3, The Intelligence feeds are not available anymore (https://www.celerium.com/pickupstix) by celerium. Is there any possibility that you update the module with a new free/open-source intelligence feed provider, please?

**Comment by tamer-fpga** [comment]
Ok Solution may be done through Kaspersky  >>   https://support.kaspersky.com/datafeeds/general/15908
I am still validating it.

**Comment by v-mchatla** [comment]
Hi @tamer-fpga -
Please find the different Threat Intelligence feed options available for Microsoft Sentinel below.
https://learn.microsoft.com/en-us/azure/sentinel/threat-intelligence-integration#taxii-threat-intelligence-feeds
Thanks

**Comment by v-mchatla** [comment]
> Ok Solution may be done through Kaspersky >> https://support.kaspersky.com/datafeeds/general/15908 I am still validating it.

sorry missed this comment. Yes this is also one of the feed option available.
Thanks

**Comment by tamer-fpga** [comment]
For Kaspersky feeds, they do not want to give me the token so I can’t configure it. I will look at MS link you provided However if anyone can provide fir the token, I would like to get it at my email.

**Comment by v-vdixit** [comment]
Hi @tamer-fpga are you still facing this issue?

**Comment by tamer-fpga** [comment]
The issue has been resolved by this comment above 
————
https://github.com/Azure/Azure-Sentinel/issues/7460#issuecomment-1453289548
