### ISSUE TITLE
 Location Info Column is missing. Please check map settings. in UserMap.json

### ISSUE THREAD

**Issue by agressini** [Azure/Azure-Sentinel#747]
**Describe the bug**
Hi, recently i've deployed the UserMap.json in Sentinel but the Map View did not work here is a screenshoot:

![image](https://user-images.githubusercontent.com/36573756/84504558-854f7080-ac92-11ea-8cd2-16ffc61213bd.png)

**To Reproduce**
 follow the article in  https://techcommunity.microsoft.com/t5/azure-sentinel/how-to-use-azure-sentinel-to-follow-a-users-travel-and-map-their/ba-p/981716

**Expected behavior**
I guess that the workbook shoud work with the steps deciberd above

**Desktop (please complete the following information):**
 - Microsoft Azure - Sentinel

**Additional context**
I have found a workaround for this by editing the map and set the following values:

- Minimum Region Size

- Maximum Region Size

- Default Region Size
![image](https://user-images.githubusercontent.com/36573756/84505178-a95f8180-ac93-11ea-9097-2dc96866d845.png)

**Comment by shainw** [comment]
@CliveW-MSFT - can you have a look at this?

**Comment by CliveW-MSFT** [comment]
@shainw and @agressini  it looks like you can just press APPLY to add these new controls in.  That's the simple fix or do what you did, you should go to the first Map anyway as its linked to the UK, so unless you are based in Reading, UK you have to make an edit / apply.  
However I will look to revise this workbook, to make setting the base location a parameter and other tweaks to take advantages of recent changes.

**Comment by bobsyourmom** [comment]
I actually had to type in the values and then press apply.
It's like they're ghosted in there as suggested values but you have to type them in and then it works.

**Comment by CliveW-MSFT** [comment]
Hello.  I'm starting to update this workbook, is there anything you'd like me to add or think about?

**Comment by agressini** [comment]
Hello everyone, nothing else to add.

**Comment by CliveW-MSFT** [comment]
Fixed, new version published
