### ISSUE TITLE
Logic App 

### ISSUE THREAD

**Issue by Adilhasan5** [Azure/Azure-Sentinel#7486]
I am seeing following error in logic apps:
"Failed to run playbook - no incident found with the properties you provided" Error 404. Any idea why it might be happening and what is the potential solutions to it?

Thanks!

**Comment by v-amolpatil** [comment]
Hi @Adilhasan5, Could you please provide more details like which playbook and screenshot if available will help for us to identify the issue.

**Comment by Adilhasan5** [comment]
Here is the screenshot
<img width="299" alt="screenshot MS" src="https://user-images.githubusercontent.com/126819393/222787219-75317eac-217a-4dbd-b09b-33c54ff623f0.png">

**Comment by Adilhasan5** [comment]
![screenshot MS](https://user-images.githubusercontent.com/126819393/222787841-c35a19b8-10c4-4899-a3f7-fbcc77a6d234.png)
Here is the screenshot

**Comment by Adilhasan5** [comment]
I am using MS Sentinel Alert as a the trigger. Please let me know if you need anything else

**Comment by v-amolpatil** [comment]
Could you please give the name of the logic app/playbook name?

**Comment by v-rbajaj** [comment]
@Adilhasan5, can you please provide some update?
