### ISSUE TITLE
Duplicated detections for AAD user changed from Guest to Member UserType

### ISSUE THREAD

**Issue by ep3p** [Azure/Azure-Sentinel#7492]
**Is your feature request related to a problem? Please describe.**
There are two detections for basically the same purpose. This might confuse clients.

https://github.com/Azure/Azure-Sentinel/blob/master/Detections/AuditLogs/GuestsChangedUserTypetoMember.yaml
https://github.com/Azure/Azure-Sentinel/blob/master/Detections/AuditLogs/UserStatechangedfromGuesttoMember.yaml

**Describe the solution you'd like**
Maybe the repository should only use one of the detections.

If this is not a problem for Microsoft, just close this issue.

**Comment by v-mchatla** [comment]
Hi @ep3p,
Thanks for flagging this. We will discuss with the team and take it forward.
Thanks

**Comment by v-vdixit** [comment]
Hi @ep3p thanks for flagging this, we have discussed with the team and will keep only one of these detections, we will be closing this case as this will be resolved.
