### ISSUE TITLE
Rename User Agent field

### ISSUE THREAD

**Issue by cgiampoulakis** [Azure/Azure-Sentinel#7527]
https://github.com/Azure/Azure-Sentinel/blob/156b3e8bb2abdcc554f0cf7df205c93aa3e8fb8f/Parsers/ASimWebSession/Parsers/vimWebSessionPaloAltoCEF.yaml#L183

Hi,

Palo Alto has the capability of logging the user agent string. It would be helpful if we align the connector field to the ASIM model field:
HttpUserAgent             = RequestClientApplication

Regards,
Christos.

**Comment by oshezaf** [comment]
Thanks @cgiampoulakis . I have updated the parser accordingly in the GitHub version. The build-in version will be updated in the next scheduled deployment.
