### ISSUE TITLE
Domain Admin Group is actually Domain AdminS

### ISSUE THREAD

**Issue by dbona75** [Azure/Azure-Sentinel#7529]
**Describe the bug**

If you manipulate Doamin Admins (Add / remove) the query reports null

**To Reproduce**

Add/remove a domain admins , wait some time (1 hour at least) and run the query

**Expected behavior**

the change is logged

**Additional context**

**The solution : please rename "Domain Admin" in "Domain Admins" in the code**
****

**Comment by v-amolpatil** [comment]
@dbona75 Could you please let us know for which file this is for?

**Comment by dbona75** [comment]
Hello,

no file it's the code of the query having a problem on the group name
Azure-Sentinel/Active Directory Sensitive Group Modifications.yaml at master · Azure/Azure-Sentinel · GitHub<https://github.com/Azure/Azure-Sentinel/blob/master/Hunting%20Queries/Microsoft%20365%20Defender/Credential%20Access/Active%20Directory%20Sensitive%20Group%20Modifications.yaml>



Take care of yourself.

Daniele Bona
Senior Cloud Solution Architect - Engineering
Global Technology Team Security
Planned leave : 4–5 Jan 2023

Microsoft respects your privacy. Review our online Privacy Statement<http://go.microsoft.com/fwlink/?LinkId=248681>.

[cid:cece4aff-e743-43be-80ba-568bbf6fdedc]



________________________________
Da: v-amolpatil ***@***.***>
Inviato: venerdì 10 marzo 2023 05:53
A: Azure/Azure-Sentinel ***@***.***>
Cc: Daniele Bona ***@***.***>; Mention ***@***.***>
Oggetto: Re: [Azure/Azure-Sentinel] Domain Admin Group is actually Domain AdminS (Issue #7529)


@dbona75<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fdbona75&data=05%7C01%7Cdaniele.bona%40microsoft.com%7Ce23ad00b21b04ad5838108db2123542c%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638140207867098911%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=UBLJi4un4U2jg3iiK%2Frh1m7sm3%2FSfwZzs09Oy6t%2FN90%3D&reserved=0> Could you please let us know for which file this is for?

**Comment by v-amolpatil** [comment]
Closing this issue as changes for this issue are now in master branch. Feel free to reopen if you need any assistance.
