### ISSUE TITLE
MDO Power BI Dashboard readme requires license information

### ISSUE THREAD

**Issue by MikeBakerSAV** [Azure/Azure-Sentinel#7539]
THE MDO Power BI Dashboard readme does not include license requirements
do you require MDO P2 or equivalent to report via PBI??

https://github.com/Azure/Azure-Sentinel/tree/master/Tools/MDO%20Power%20BI%20Dashboard

bad request 400 is returned...

**To Reproduce**
following instructions of readme..
Web.Contents failed to get contents from 'https://api.security.microsoft.com/api/advancedhunting/?key=EmailEvents%20%7Cwhere%20Timestamp%20%3E%20ago(30d)%7C%20where%20isnotempty(ThreatNames)%20%7C%20summarize%20count()%20by%20ThreatNames,%20bin(Timestamp,%201d)%20%7C%20sort%20by%20count_' (400): Bad Request

**Comment by v-amolpatil** [comment]
@MikeBakerSAV a new change is now merged in master on the license information. Please have a look. Closing this issue and readme file is now updated. Feel free to reopen the issue if you need any assistance.
