### ISSUE TITLE
Logicapp AbuseIPDB-BlacklistIpToThreatIntelligence failes 

### ISSUE THREAD

**Issue by atech-soc** [Azure/Azure-Sentinel#7544]
**Describe the bug**
my logic app "AbuseIPDB-BlacklistIpToThreatIntelligence" from contenct hub in sentinel is being failed at point it should be injecting data to TI in setinel

**Expected behavior**
successfully insert the TI data to sentinel 

**Screenshots**
![image](https://user-images.githubusercontent.com/93925456/224663812-a2118bb9-dd63-4b2e-8ee9-b39bf8b2acd8.png)
![image](https://user-images.githubusercontent.com/93925456/224664043-bfc05c9c-1d86-41f8-89b9-959c69457a36.png)

**Comment by atech-soc** [comment]
Hello, 

Can anyone help me with this?

thanks,
Snehal

**Comment by v-amolpatil** [comment]
Hi @atech-soc, We will update you in few days. Thanks!

**Comment by samryanturner** [comment]
Seeing the same issue here too!

**Comment by atech-soc** [comment]
Hi @v-amolpatil, I hope you are well. did you get a chance to check this issue?

**Comment by v-vdixit** [comment]
Hi @atech-soc Can you please check the following points once and confirm for us:

1) Got to AbuseIPDB solution from content hub then go to playbook AbuseIPDB-BlacklistIpToThreatIntelligence
2) Select the API connections tab
![image](https://github.com/Azure/Azure-Sentinel/assets/115772287/b3de921b-514d-44c6-8f38-b390820928c1)

3) Select abuseipdb-AbuseIPDB-BlacklistIpToThreatIntelligence connection and go to Edit API Connection and ensure the API key parameter has your required key and save the changes
![image](https://github.com/Azure/Azure-Sentinel/assets/115772287/031da3de-9611-4e9e-9807-8a135f26eed3)

4) Again back on API connections tab select the ThreatIntelligence-connection-AbuseIPDB-BlacklistIpToThreatIntelligence connection and in the Edit API tab ensure that you have Authorized the usage of the API save the changes and run again.

If you still face the same issue please let us know, we will discuss further with the team, thanks!

**Comment by dustypaulson** [comment]
@atech-soc Open the designer and open the Select statement and change the value of targetProeduct from Microsoft Sentinel to Azure Sentinel. 

![image](https://github.com/Azure/Azure-Sentinel/assets/26881778/4f880b99-8409-4274-aae5-e4717aeb59cb)

This will get the Submit multiple TI indicators to give you a status of 200 and be successful. However, I do not see the data in the ThreatIntelligenceIndicator table in Log Analytics. @v-vdixit any thoughts on the API returning an incorrect status or possibly missing some mandatory values?

![image](https://github.com/Azure/Azure-Sentinel/assets/26881778/26929b7a-1ec6-4fe1-90d1-e94e1a6a0f94)
![image](https://github.com/Azure/Azure-Sentinel/assets/26881778/d37be051-7085-4b82-9125-b8f1dc48afaa)
![image](https://github.com/Azure/Azure-Sentinel/assets/26881778/b2f96e59-f2db-4303-b3a2-5a4f6c9bb6cf)

**Comment by v-vdixit** [comment]
Hi @atech-soc Since we have not received a response in the last 5 days, we are closing your issue #7544 as per our standard operating procedures. If you still need support for this issue, feel free to re-open at any time. Thank you for your co-operation.
