### ISSUE TITLE
ActionFailed. An action failed. No dependent actions succeeded. For logic app Get-GitHubAuditEntry( Ingest GitHub AuditLog and API Data)

### ISSUE THREAD

**Issue by AbhiramVijayan** [Azure/Azure-Sentinel#759]
### ActionFailed. An action failed. No dependent actions succeeded. For logic app Get-**GitHubAuditEntry**( I[ngest GitHub AuditLog and API Data](https://github.com/Azure/Azure-Sentinel/tree/master/DataConnectors/GitHub))

After triggering the logic app " Get-GitHubAuditEntry" getting an error like this "
_"InvalidTemplate. Unable to process template language expressions for action 'Condition_3' at line '1' and column '3448': 'The template language function 'length' expects its parameter to be an array or a string. The provided value is of type 'Null'. Please see https://aka.ms/logicexpressions#length for usage details.'._" for condition 3 of the logic app. The other 2 logic apps were successfully triggered.

Output Body of 'HTTP' in the "Until"
{
"errors": [
{
"message": "A query attribute must be specified and must be a string."
}
]
}
![screencapture-portal-azure-2020-06-18-09_44_02](https://user-images.githubusercontent.com/23203675/84989225-f98d8680-b160-11ea-9beb-b2ba332fe7f2.png)

![FireShot Capture 010 - Logic Apps Designer - Microsoft Azure - portal azure com](https://user-images.githubusercontent.com/23203675/84989238-fdb9a400-b160-11ea-8895-915a57c694b5.png)
![Screenshot from 2020-06-18 09-47-08](https://user-images.githubusercontent.com/23203675/84989229-fb574a00-b160-11ea-9949-8b92444fb35e.png)
![Screenshot from 2020-06-18 09-47-57](https://user-images.githubusercontent.com/23203675/84989242-feead100-b160-11ea-8477-65268cb146e7.png)

**Comment by dicolanl** [comment]
@AbhiramVijayan  could you share a screenshot of the output from the Parse JSON 2?

**Comment by AbhiramVijayan** [comment]
![image](https://user-images.githubusercontent.com/23203675/85095780-087f4200-b210-11ea-8a6d-5e798ed3c745.png)

**Comment by dicolanl** [comment]
@AbhiramVijayan Could you try adding a row in condition 3.
make it an OR condition, click add row.  Enter @body('Parse_JSON_2')?['data']?['organization']?['auditLog']?['edges'] is equal to @null
should look like this
![image](https://user-images.githubusercontent.com/25964057/88843597-3f912d80-d196-11ea-83ae-5c204816a7c1.png)


Then re-reun.  it should fix it.  once you confirm ill update the arm template

**Comment by AbhiramVijayan** [comment]
**@dicolanl**  Getting same error after adding the OR condition 

![image](https://user-images.githubusercontent.com/23203675/89327685-ea7b7d00-d6a9-11ea-816e-af227f202e50.png)


Error
![image](https://user-images.githubusercontent.com/23203675/89327439-8d7fc700-d6a9-11ea-830c-61e6facdc3e3.png)

![image](https://user-images.githubusercontent.com/23203675/89327598-ca4bbe00-d6a9-11ea-9129-1e9c22fc7434.png)

**Comment by dicolanl** [comment]
I just noticed the problem.
![image](https://user-images.githubusercontent.com/25964057/89338024-c8094580-d650-11ea-9897-1f498bd34587.png)
this http call has no body.  the body should be the variable auditQuery.

I tested on mine and it did it too.  I added a delay step (wait 1 min). before the HTTP step now it has the body = auditquery.  Could you try the same?
![image](https://user-images.githubusercontent.com/25964057/89338121-f555f380-d650-11ea-93ad-2bfb5262a985.png)

**Comment by AbhiramVijayan** [comment]
@dicolanl  I think the issue is now solved, I don't have a GitHub organization account, so I can't move forward

![image](https://user-images.githubusercontent.com/23203675/89492445-36741200-d7cf-11ea-8862-cd34c6005cdf.png)



**Parse JSON 2 Input**
{
  "data": {
    "organization": null
  },
  "errors": [
    {
      "type": "PLAN_NOT_SUPPORTED",
      "path": [
        "organization",
        "auditLog"
      ],
      "locations": [
        {
          "line": 1,
          "column": 52
        }
      ],
      "message": "Organization billing plan does not support access to auditLog information."
    }
  ]
}


![image](https://user-images.githubusercontent.com/23203675/89492322-f876ee00-d7ce-11ea-8a9f-112c8928625e.png)

**Comment by Raj4IBM** [comment]
Hi Team im getting similar type of issue in Logic app getting "An action failed. No dependent actions succeeded "  and Bad request in Http
