### ISSUE TITLE
Infoblox parser (Solution & ASIM) typo

### ISSUE THREAD

**Issue by twi252** [Azure/Azure-Sentinel#7611]
Missing ':' after SrcPortNumber both in Infoblox NIOS solution parser & related built-in ASIM parsers.

**To Reproduce**
1. Ingest Infoblox data
2. The following KQL returns no data in the DnsQuery field
3. Infoblox | summarize count() by DnsQuery

**Expected behavior**
Results in the DnsQuery field from client DNS lookups.

**Additional context**
Created the following PR for the solution https://github.com/Azure/Azure-Sentinel/pull/7610 but the same problem exists in the built-in Infoblox parsers (_Im_Dns_InfobloxNIOSVxx & _Asim_Dns_InfobloxNIOSVxx) also preventing correct results there as well.

**Comment by oshezaf** [comment]
hi @twi252 : my sample data does not have a colon between the port number and the protocol. Actually I believe your fix does not work with our sample events. We would need you to provide samples data to test against to improve the parser. 

Tagging @vakohl

**Comment by twi252** [comment]
No problem that's fair, here are some raw query logs (from Syslog) as i see them.

22-Mar-2023 08:59:34.790 client 1.1.1.1#50164: UDP: query: 2.2.2.2.in-addr.arpa IN PTR response: NOERROR +A 3.3.3.3.in-addr.arpa. 3600 IN PTR myhost.mydomain.local.

22-Mar-2023 08:59:34.791 client 1.1.1.1#51443: UDP: query: myhost.mydomain.local IN A response: NOERROR +A thehost.mydomain.local. 3600 IN A 4.4.4.4

22-Mar-2023 08:59:34.804 client 1.1.1.1#50499: UDP: query: ahost.mydomain.local IN AAAA response: NOERROR +A

Perhaps it's ever so slightly changed based on the version of Infoblox, but i'm not certain the version of this one (not in my control) unfortunately.

**Comment by twi252** [comment]
This is not concrete, but i saw a similar issue posted over at ArcSight.

Guessing this might have changed around v8.x

https://community.microfocus.com/cyberres/arcsight/f/arcsight-discussions/352069/infoblox-unparsed-events

Might have to tweak the parsers to cater for both cases. I can verify that i got a correct parse on my Infoblox DNS query logs with that change in the PR for the solution (not tested the change on the ASIM parsers), the rest of the fields seem to line up ok after the change.

Hope it helps.

**Comment by twi252** [comment]
> hi @twi252 : my sample data does not have a colon between the port number and the protocol. Actually I believe your fix does not work with our sample events. We would need you to provide samples data to test against to improve the parser.
> 
> Tagging @vakohl

Thanks Ofer. See the thread in PR https://github.com/Azure/Azure-Sentinel/pull/7610 for more info.

**Comment by vakohl** [comment]
The fix related to this issue has been applied. Please refer to the PRs for the same:
https://github.com/Azure/Azure-Sentinel/pull/7949
https://github.com/Azure/Azure-Sentinel/pull/7939
