### ISSUE TITLE
Add connector for Google Alert Centre Alerts

### ISSUE THREAD

**Issue by beachfires** [Azure/Azure-Sentinel#7618]
**Is your feature request related to a problem? Please describe.**
Sentinel has a connector for Google Reports for Sentinel but it doesn't contain any Security Alerts from Google Alert Centre. We're missing extremely value security alerts.

**Describe the solution you'd like**
A new connector which ingests alerts from Google Alert Centre.

**Describe alternatives you've considered**
There are no alternatives than having an integration facilitate this with the use of the Google API.

**Additional context**
Datadog have an integration for Google Alert Centre here: https://docs.datadoghq.com/integrations/google_workspace_alert_center/

**Comment by v-dvedak** [comment]
Thank you for submitting an Issue to the Azure Sentinel GitHub repo! You should expect an initial response to your Issue from the team within 5 business days. Note that this response may be delayed during holiday periods. For urgent, production-affecting issues please raise a support ticket via the Azure Portal.
