### ISSUE TITLE
If the Salesforce Service Cloud data connector supports Salesforce Sales Cloud.

### ISSUE THREAD

**Issue by winnie008** [Azure/Azure-Sentinel#7621]
Hi Team,

This is regarding whether the Salesforce Service Cloud data connector supports Salesforce Sales Cloud.

We are testing the Salesforce Cloud integration and just wondering if we could use the Salesforce Service Cloud to ingest the Salesforce Sales Cloud logs. If not, are there any further plans to add a connector to ingest the Salesforce Sales Cloud logs?

Thanks for your help ahead.

**Comment by winnie008** [comment]
Hi Team, may I know if there is any update regarding this issue?

**Comment by v-vdixit** [comment]
Hi @winnie008, we are discussing this with the team, will update you shortly, thanks!

**Comment by winnie008** [comment]
Hi Team, may I know if there is a way or a plan to ingest Salesforce Sales Cloud logs via Sentinel data connectors?

**Comment by v-dvedak** [comment]
We have noted your request and identified this as an enhancement. We are closing this issue as per our standard operating procedure, but we will continue to track this request internally. If you still need support for this issue, feel free to re-open at any time. Thank you for your feedback and engagement. Your feedback is valuable, and we encourage you to continue providing it.
