### ISSUE TITLE
Turn on/off defender products within the M365D connector

### ISSUE THREAD

**Issue by idnahacks** [Azure/Azure-Sentinel#7687]
Purview/DLP incidents are handled by a different team to the SOC. When using the M365D connector the SOC get these alerts in their queue.

I would like to be able to use the functionality of the M365D connector (bidirectional sync, grouping etc etc) but be able to turn off certain Defender products. 

Using the individual defender connectors works around the issue but loses the added benefits that the M365D connector brings.

**Comment by v-rbajaj** [comment]
It is possible to customize the alerts that are sent to the SOC queue from the M365D connector by configuring the alert policies within the Microsoft 365 Defender portal.

To turn off certain Defender products, you can modify the alert policies to exclude those products from triggering alerts. Here are the steps to do this:

1. Navigate to the Microsoft 365 Defender portal and go to the "Settings" page.
2. Click on "Alert policies" to view the list of existing policies.
3. Find the policy that is associated with the M365D connector and click on it to open its settings.
4. In the "General" tab, you will see a list of Defender products that are included in the policy. Uncheck the boxes next to the products that you want to exclude from the policy.
5. Save your changes.

By modifying the alert policy, you can ensure that the SOC team only receives alerts from the Defender products that are relevant to them, while still taking advantage of the functionality of the M365D connector.

**Comment by idnahacks** [comment]
Thanks, however we do not wish to turn off the alerts altogether. There is a separate team that handle alerts from the purview product and they will still need to process these.

I would imagine it's a reasonably common use case for separate teams managing purview and "cyber" incidents.

**Comment by idnahacks** [comment]
Won't those alerts still sync to Sentinel in this case?

For clarity, we don't wish the purview team to only receive email alerts. The alerts should remain in defender, we just want to be able to choose not to sync those alerts to Sentinel.

**Comment by v-rbajaj** [comment]
Hi @idnahacks, 
This is a known feature request which is tracked by the product team and the respective team is already working on it. So we are closing this issue https://github.com/Azure/Azure-Sentinel/issues/7687 based on our standard procedure.

**Comment by Jamiegithub7** [comment]
What happened with this?
