### ISSUE TITLE
Authentication Methods Changed for Privileged Account rule is poorly named

### ISSUE THREAD

**Issue by DeanGross** [Azure/Azure-Sentinel#7705]
**Describe the bug**
The analytic rule template title implies that it will be looking for changes to the auth methods, which are described on [Manage authentication methods](https://learn.microsoft.com/en-us/azure/active-directory/authentication/concept-authentication-methods-manage), but in fact it is looking for the following 

let security_info_actions = dynamic(["User registered security info", "User changed default security info", "User deleted security info", "Admin updated security info", "User reviewed security info", "Admin deleted security info", "Admin registered security info"]);

My research indicates that changes to the Authentication Method will be logged in the "Admin registered security info" activity type, which is only one of actions. Renaming this to something broader would seem to be appropriate. 

Also, I only "Viewed" my security info, and a High Severity alert got created which does not seem appropriate when nothing got changed.

**To Reproduce**
1. view data in the Authentication methods page of Azure AD
2. review azure ad audit logs
3. review sentinel incidents

**Expected behavior**
The title should describe all of the various changes that will generate an alert. 
Viewing data should not generate a high severity alert

**Screenshots**

**Additional context**

**Comment by v-vdixit** [comment]
Hi @DeanGross thanks for flagging this, we are discussing with the team, will update you shortly.

**Comment by bharp28** [comment]
I am also seeing frequent high severity alerts for "Authentication Methods Changed for Privileged Account". The user action was "User successfully reviewed security info".

**Comment by v-vdixit** [comment]
Hi @DeanGross, @bharp28 we have raised this issue with the authors of the detection, the rule will be updated soon, thanks!

**Comment by v-vdixit** [comment]
@DeanGross Gentle Reminder: We are waiting for your response on this issue. If you still need to keep this issue active, please respond on it in the next 2 days. If we don't receive response, we will be closing this issue as per our standard procedures, thanks!

**Comment by v-vdixit** [comment]
Since we have not received a response in the last 5 days, we are closing your issue as per our standard operating procedures. If you still need support for this issue, feel free to re-open at any time. Thank you for your co-operation.
