### ISSUE TITLE
Wrong Identifier used on template: AaDUserId instead of AadUserId

### ISSUE THREAD

**Issue by garis** [Azure/Azure-Sentinel#7712]
When deploying the rule “Suspicious Resource deployment” from the Azure Activity Content Hub solution in Sentinel the following error shows up after confirming the deployment:

![image](https://user-images.githubusercontent.com/13544227/229068316-0c05ee9b-863f-4168-bd1b-702c8a88f8b0.png)

Failed to save analytics rule
Failed to save analytics rule 'Suspicious Resource deployment'. Invalid data model. [: Invalid identifier 'AaDUserId' for type 'Account' encountered. Valid identifiers are: [Name, NTDomain, DnsDomain, UPNSuffix, Sid, AadTenantId, AadUserId, PUID, IsDomainJoined, DisplayName, ObjectGuid, CloudAppAccountId, IsAnonymized, FullName]]

The issue is caused by the template referencing the wrong Identifier AaDUserId instead of AadUserId (lowercase d).
Based on [this commit](https://github.com/Azure/Azure-Sentinel/commit/b9aa0efc41bab152078acd0c7ebda554b6d93f21) other rule might be affected.

**Comment by v-vdixit** [comment]
Hi @garis thanks for flagging this, we have made the changes you requested, will be updating them in the package soon, thanks!

**Comment by v-vdixit** [comment]
Hi @garis we have fixed the issue and the rule can be created successfully now 
![image](https://user-images.githubusercontent.com/115772287/229434562-5ee9c056-4716-464c-adb8-6f4e6a6c630a.png)
Please check the latest package of solution and feel free to reopen the issue if you have any further questions, thanks!
