### ISSUE TITLE
ASIM Roadmap

### ISSUE THREAD

**Issue by pazgoyal** [Azure/Azure-Sentinel#7747]
Hey, can anyone help me with ASIM roadmap. Which ASIM Schemas are on the roadmap to be developed?

**Comment by oshezaf** [comment]
Hi @pazgoyal : we can't provide roadmap information through GitHub (or in public in general). We deliver roadmap information to our private community members. You can find more information on this program [here](https://techcommunity.microsoft.com/t5/security-compliance-and-identity/the-new-microsoft-security-customer-connection-program-ccp/ba-p/3733595)
