### ISSUE TITLE
In Use label is unreadable in dark mode

### ISSUE THREAD

**Issue by anfisher1967** [Azure/Azure-Sentinel#7749]
In the Rule Template section of analytics, the in use label is unreadable in dark mode. 
![inuse](https://user-images.githubusercontent.com/33937240/229831655-98cb9ad8-49ea-4504-83f4-e26a4fa25600.jpg)

**Comment by v-vdixit** [comment]
Hi @anfisher1967 Gentle Reminder: We are waiting for your response on this issue. If you still need to keep this issue active, please respond on it in the next 2 days. If we don't receive response, we will close this issue as per our standard procedures, thanks.

**Comment by v-vdixit** [comment]
Hi @anfisher1967 since we have not received a response in the last 5 days, we are closing your issue #7749, as per our standard operating procedures. If you still need support for this issue, feel free to re-open at any time. Thank you for your co-operation.
