### ISSUE TITLE
Daily cap issue

### ISSUE THREAD

**Issue by shipothana** [Azure/Azure-Sentinel#7799]
Hi Team.

We have a daily cap of 100 GP, so if we use 59 GB of that, will Microsoft charge us for the remaining 40 GB or not?

Thanks,
Siva Pothana

**Comment by v-vdixit** [comment]
Hi @shipothana as per my understanding of your question, I would like to inform you that you will not be charged for the remaining 41 GB. The daily cap is the maximum amount of data that you can use per day without incurring additional charges. As long as you stay within the daily cap, you will not be charged for any extra usage, if there is something else you would like to know please update here, thanks!

**Comment by shipothana** [comment]
Thanks for your response
