### ISSUE TITLE
Revoke-AADSignInSessions playbook stuck with error on Authorization_RequestDenied

### ISSUE THREAD

**Issue by KrishhnaM** [Azure/Azure-Sentinel#783]
The revokesigninsession using graph API fails with below error
//
{
  "error": {
    "code": "Authorization_RequestDenied",
    "message": "Access to invalidate refresh tokens operation is denied.",
    "innerError": {
      "date": "2020-06-24T09:42:07",
      "request-id": "712c3e1a-54c0-4d8f-9da3-7e2728121914"
    }
  }
}
//
the permission to managed identity and graph api is given as described in MS docs- [https://docs.microsoft.com/en-us/graph/api/user-revokesigninsessions?view=graph-rest-1.0&tabs=http](url) 
//
the HTTP request to graph API is 
https://graph.microsoft.com/v1.0/users/adelev@m365domain.onmicrosoft.com/revokeSignInSessions

**Comment by dicolanl** [comment]
@KrishhnaM 
which permission did you grant in AAD Apps? Delegated or Application?  it should be delegated.


Permission type | Permissions (from least to most privileged)
-- | --
Delegated (work or school account) | User.ReadWrite, Directory.ReadWrite.All, Directory.AccessAsUser.All
Delegated (personal Microsoft account) | Not supported.
Application | Directory.ReadWrite.All, Directory.AccessAsUser.All

**Comment by dicolanl** [comment]
No response closing

**Comment by wang3620** [comment]
I have the same issue. I made an http post call and it returned the following
{
    "error": {
        "code": "Authorization_RequestDenied",
        "message": "Access to invalidate refresh tokens operation is denied.",
        "innerError": {
            "date": "2021-08-11T05:43:22",
            "request-id": "bc8326bc-7354-44c0-8818-caaeb281948a",
            "client-request-id": "bc8326bc-7354-44c0-8818-caaeb281948a"
        }
    }
}

I have already granted my application with delegated permissions. No sure what's going wrong.

![Screen Shot 2021-08-10 at 10 51 38 PM](https://user-images.githubusercontent.com/22897208/128976576-9993e39c-67bf-4a96-bbb1-d7d89ea7868e.png)
@dicolanl

**Comment by dicolanl** [comment]
the playbook uses Managed identity, not application.  did you grant the MI the correct permissions per https://github.com/Azure/Azure-Sentinel/tree/master/Playbooks/Revoke-AADSignInSessions#prerequisites
