### ISSUE TITLE
Query could not be parsed for Authentication Normalization rules

### ISSUE THREAD

**Issue by Quirin02** [Azure/Azure-Sentinel#7836]
Hello, I am trying to create two analytic rules from the templates "User login from different countries within 3 hours (Uses Authentication Normalization)" and "Brute force attack against user credentials (Uses Authentication Normalization)" for my Sentinel Workspace. 

This worked fine a few months ago but now I get the error message in the logic tab of the rule when going through the process of creating it "Query could not be parsed at ',' on line [449,2]." for both of them. I have not changed anything in the rule template and I have successfully deployed all ASIM parsers to the resource group that my workspace is in.

Is this a bug, or can I do something to fix it?

**Comment by oshezaf** [comment]
Hi @Quirin02 : I was not able to replicate by deploying ASIM parsers on a clean workspace and deploying the rule. I suggest you open a support case which enable the support engineer to gather the details and work with you on your workspace if needed.

**Comment by oshezaf** [comment]
It seems that you did not deploy correctly. If you just try to run imAuthentication in the log screen in this workspace, does it work? can you see the imAuthentication functions in the function list in the log screen?

**Comment by oshezaf** [comment]
Hi @Quirin02 : pretty hard to debug over GitHub and I do suggest opening a support ticket. The one thing I have seen before is deploying to the wrong workspace. Sounds trivial, but we all do such mistakes.
