### ISSUE TITLE
I am getting users with Days uptime how is this possible?

### ISSUE THREAD

**Issue by mannycarz** [Azure/Azure-Sentinel#7838]
**Describe the bug**
https://github.com/Azure/Azure-Sentinel/tree/master/Hunting%20Queries/Microsoft%20365%20Defender/General%20queries/Device%20uptime%20calculation.yaml

when running this I get some users who have days uptime not just hours. How is this possible? Also I have about 10 users who are fully enrolled in Azure autopilot nothing different and they are using their computers but they do not show up in this report. All others do. 

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by v-rbajaj** [comment]
Hi @mannycarz ,
Regarding the first question, it is possible for some users to have days of uptime if their devices have been running continuously for that long. The query you are running calculates the uptime of devices in hours, but it is possible for some devices to have been running for multiple days.

Regarding the second question, it is possible that the users who are fully enrolled in Azure Autopilot are not showing up in the report because they have not been active for the time period specified in the query. The query you are running calculates the uptime of devices based on the last time they were seen by Microsoft Defender for Endpoint. If the users have not been active during that time period, they will not show up in the report.

**Comment by mannycarz** [comment]
Thanks for your answers even though this is not possible. One of the users not showing up is an admin and handles a lot of our database work. He is heavily on his computer . The user activity reports shows this with his device but not on your uptime device. Can we look in to this further?

**Comment by mannycarz** [comment]
also when I run your query now I am getting 000000 no time stamps for everyone . THe query is broken I believe. 
// This query calculates device uptime based on periodic DeviceInfo which is recorded every 15 minutes regardless of device's network connectivity and uploaded once device gets online. If its interval is over 16 minutes, we can consider device is turned off.Calculated uptime may include up to 30 minutes gap. Devices may be turned on up to 15 minutes earlier than the "timestamp", and may be turned off up to 15 minutes later than the "LastTimestamp".  When the single independent DeviceInfo without any sequential DeviceInfo within 16 minutes before or after is recorded, "DurationAtLeast" will be displayed as "00.00:00:00".
// This query was updated from https://github.com/Azure/Azure-Sentinel/tree/master/Hunting%20Queries/Microsoft%20365%20Defender/General%20queries/Device%20uptime%20calculation.yaml
DeviceInfo 
| order by DeviceId, Timestamp desc
| extend FinalSignal = (prev(DeviceId,1) != DeviceId) or (prev(LoggedOnUsers,1) != LoggedOnUsers) or (prev(Timestamp,1,now(1d)) - Timestamp > 16m)
| extend StartSignal = (next(DeviceId,1) != DeviceId) or (next(LoggedOnUsers,1) != LoggedOnUsers) or (Timestamp - next(Timestamp,1,0) > 16m)
| where FinalSignal or StartSignal
| extend LastTimestamp=iff(FinalSignal,Timestamp,prev(Timestamp,1))
| where StartSignal
| extend ParsedFields=parse_json(LoggedOnUsers)[0]
| extend DurationAtLeast= format_timespan(LastTimestamp-Timestamp,'dd.hh:mm:ss')
| project Timestamp,LastTimestamp,DurationAtLeast,DeviceName,DomainName=ParsedFields.DomainName,UserName=ParsedFields.UserName

**Comment by v-rbajaj** [comment]
Hi @mannycarz, we are checking with the team internally, we will provide you an update in sometime.

**Comment by v-rbajaj** [comment]
Hi @mannycarz, can you please provide us with Sample data so that we can test the query?

**Comment by v-rbajaj** [comment]
Gentle Reminder: We are awaiting for your response on this issue. If you still need to keep this issue active please respond on it in the next 2 days.  If we don't receive response,  we will be close this issue.

**Comment by v-rbajaj** [comment]
Since we have not received a response in the last 5 days, we are closing your issue https://github.com/Azure/Azure-Sentinel/issues/7838 as per our standard operating procedures. If you still need support for this issue, feel free to re-open at any time. Thank you for your co-operation.
