### ISSUE TITLE
Require a deploy button or ARM template/script for Azure Gov for O365 Management Activity API Log Ingestion

### ISSUE THREAD

**Issue by Instantazn** [Azure/Azure-Sentinel#7852]
**Is your feature request related to a problem? Please describe.**
Yes, the article here: https://github.com/Azure/Azure-Sentinel/tree/master/DataConnectors/O365%20Data only has a solution built out for Azure commercial and not AzureGov.

**Describe the solution you'd like**
I would like to see a Deploy button for AzureGov or proper files modified specifically for AzureGov to deploy there.

**Describe alternatives you've considered**
I have considered modifying the code, but I am unsure if it will break or work as expected. It would be better to have an official solution given by Microsoft for this.

**Additional context**

**Comment by v-rbajaj** [comment]
Hi @Instantazn, we have raised a PR https://github.com/Azure/Azure-Sentinel/pull/7908 for this issue.
Please let us know in case you have any further questions.

**Comment by v-rbajaj** [comment]
Hi @Instantazn, the PR is merged. Please let us know in case you have any questions?

**Comment by v-rbajaj** [comment]
Hi all, we are closing this issue.

**Comment by Instantazn** [comment]
Hi @v-rbajaj, I have seen the new update which includes the button for Azure Gov now. I'll give this solution a try soon, but feel free to close this out. Thank you so much for getting this done so fast! I was very impressed with the timing on this as it was an important item for me!
