### ISSUE TITLE
Cisco Meraki ASIM network session parser issue

### ISSUE THREAD

**Issue by cgiampoulakis** [Azure/Azure-Sentinel#7863]
https://github.com/Azure/Azure-Sentinel/blob/206f1ab3247fc29f2a135279ba8b1788b495d1d9/Parsers/ASimNetworkSession/Parsers/ASimNetworkSessionCiscoMeraki.yaml#L27

Hi, I notice that the table CiscoMerakiNativePoller_CL is not used anymore. Instead the table meraki_CL or the alias CiscoMeraki could be used:
![image](https://user-images.githubusercontent.com/104133928/233066691-f5c0c185-9d82-46eb-bd67-edf0b719d53f.png)

Also, the condition https://github.com/Azure/Azure-Sentinel/blob/206f1ab3247fc29f2a135279ba8b1788b495d1d9/Parsers/ASimNetworkSession/Parsers/ASimNetworkSessionCiscoMeraki.yaml#L29 should only filter the IDS events. Maybe the flows could be added and change the field to the correct one from the new table (LogType).

**Comment by devikamehra** [comment]
@cgiampoulakis Thanks for reaching out. This ASIM parser is due for deprecation and there is no ASIM support for Syslog based data in case of Meraki today.

Please let me know if you have anything else that needs clarification.

**Comment by krabelize** [comment]
I have slightly edited this Meraki parser in order to solve this: https://github.com/krabelize/Cisco-Meraki-Sentinel-SIEM/blob/main/Meraki_CL. Feel free to merge this with official MS supported parser
