### ISSUE TITLE
Is there any way to deploy an data connector in MS Defender portal?

### ISSUE THREAD

**Issue by BSpatel183** [Azure/Azure-Sentinel#7864]
I want to create an indicators in defender from my client's application using [API](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/post-ti-indicator). Just want to know if I can publish my application on defender portal, just the way we can publish a data connector and other services in sentinel portal.

**Comment by samikroy** [comment]
@BSpatel183 - You have to register the application in Azure AD with the specified permission if you only want to ingest IOCs to Defender and build an azure function or logic app to publish to Defender.

**Comment by samikroy** [comment]
> @samikroy Thank you for your response.
> 
> * **I am also planning to create an azure function app, but my question is how we can publish that function app on defender?**
> 
> (Just for example for sentinel integrations we are creating solution and need to raise PR to Azure sentinel git repo. Such a way it there any steps for publishing it into defender)
> 
> * **After getting published where we can find that on defender portal?**

@BSpatel183 - As a consumer of Defender, we will are limited to build and publish this into our Azure Subscription which will not be visible in Defender but, it will be as follows 

1. Create an app registration in Azure AD (in the same tenant as defender is deployed)
2. Write an azure function in azure function in one of the subscription attached the same active directory 
3. Use the App ID & secret to connect & ingest TI feeds to Defender. 

We can then manage the app in azure ad & the function is azure subscription

**Comment by BSpatel183** [comment]
@samikroy Got you point, thanks!

**Comment by samikroy** [comment]
@v-vdixit  - This seems ready for closure.
