### ISSUE TITLE
Device uptime is not working anymore it reports 000000 for time stamps for all users

### ISSUE THREAD

**Issue by mannycarz** [Azure/Azure-Sentinel#7867]
https://github.com/microsoft/Microsoft-365-Defender-Hunting-Queries/blob/d6da8647e41b6862278f50d7227501039e37140d/General%20queries/Device%20uptime%20calculation.md

YOUR SAMPLE BELOW AND THEN AFTER THAT IS OUR SCREENSHOT WHICH SHOWS 000000 FOR TIME . IT USED TO WORK UNTIL YESTERDAY

![image](https://user-images.githubusercontent.com/131030634/233112624-28a1dc98-7659-471b-9e77-cd09a87471bd.png)

**Comment by v-vdixit** [comment]
Hi @mannycarz Gentle Reminder: We are waiting for your response on this issue. If you still need to keep this issue active, please respond on it in the next 2 days. If we don't receive a response, we will have to close this issue as per our standard procedures. Thanks!
