### ISSUE TITLE
NOBELIUM - Domain, Hash and IP IOCs - May 2022 should be fixed or removed from repo

### ISSUE THREAD

**Issue by best-geek** [Azure/Azure-Sentinel#7885]
**Describe the bug**
The rule Sentinel Rule [NOBELIUM - Domain, Hash and IP IOCs - May 2021](https://github.com/Azure/Azure-Sentinel/blob/c6dce9c3aa4d4b4d02423ac4eb5a6b677a39e432/Solutions/Legacy%20IOC%20based%20Threat%20Protection/Analytic%20Rules/NOBELIUM_IOCsMay2021.yaml) references an external watchlist of CSVs which, when requested, returns a 404. 

This blocks execution of of the rule on a customer's Sentinel instance with the following error from the SentinelHealth table:

```
"StoragePathNotFound","Description":"The query referred to a storage path that was not found.
```

The reference for the unavailable CSV can be seen on line 98:
```
  [@"https://raw.githubusercontent.com/microsoft/mstic/master/Indicators/May21-NOBELIUM/May21NOBELIUMIoCs.csv"] with (format="csv", ignoreFirstRecord=True);

```

**To Reproduce**
1. Attempt to deploy *NOBELIUM - Domain, Hash and IP IOCs - May 2021* as an analytic rule to Sentinel
2. The validation wizard will fail because it cannot contact the external CSV referenced at line 98. 

**Expected behavior**
The rule wizard should complete without error. The rule should execute on it's schedule without populating errors in the SentinelHealth table. 

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Edge
 - Version: Version 112.0.1722.48 (Official build) (64-bit)

**Additional context**
Rule should be rectified to include an updated CSV location or removed from this repo.

**Comment by v-rbajaj** [comment]
Since we have pushed the change in this https://github.com/Azure/Azure-Sentinel/pull/7901,  I hope this resolves the issue. 
Please provide the confirmation.

**Comment by v-rbajaj** [comment]
Hi @best-geek, Gentle Reminder: We are awaiting for your response on this issue. If you still need to keep this issue active please respond on it in the next 2 days . If we don't receive response, we will be close this issue.

**Comment by v-rbajaj** [comment]
Since we have not received a response in the last 5 days, we are closing your issue https://github.com/Azure/Azure-Sentinel/issues/7885 as per our standard operating procedures. If you still need support for this issue, feel free to re-open at any time. Thank you for your co-operation.
