### ISSUE TITLE
Enrich-SentinelIncident-MDATPTVM

### ISSUE THREAD

**Issue by noapocalypse** [Azure/Azure-Sentinel#7887]
Enrich-SentinelIncident-MDATPTVM

I believe the field names have changed for the Alert - Get Incident task.

Which means on running the playbook it attempts to query a path that looks something like the below

"/Cases///7a441234-b23c-4d88-e123-f123g123hi2j/"

And subsequently errors out with a 404

**Comment by noapocalypse** [comment]
Looking through the playbook in more detail it's doing a number of things that have been replaced with easier methods.

Such as calling the old V2 Sentinel Incident Comment tasks, referring to none existent variables and using an old schema.

I'd recommend the whole playbook needs a rebuild. https://github.com/Azure/Azure-Sentinel/pull/7906 I've created a pull request with a version I believe resolves the issues.

@v-vdixit @v-rbajaj Feel free to check it out and see if it helps.

**Comment by v-rbajaj** [comment]
Hi @noapocalypse, Thanks for flagging this. Will take a look at the PR and let you know!

**Comment by v-vdixit** [comment]
Hi @noapocalypse we are reviewing the PR, thanks!

**Comment by v-vdixit** [comment]
Hi @noapocalypse the PR is under review by the team, will update changes in PR, thanks!

**Comment by v-vdixit** [comment]
Hi @noapocalypse we will check the code in your PR and raise a new PR with updates, thanks!

**Comment by v-vdixit** [comment]
Hi @noapocalypse we are checking with the concerned team, will update you shortly, thanks!

**Comment by v-rbajaj** [comment]
Internal team is working on this and checking further.

**Comment by v-vdixit** [comment]
We are waiting to hear back from concerned team, thanks!

**Comment by v-vdixit** [comment]
We are still waiting to hear back from the concerned team, thanks!

**Comment by v-rbajaj** [comment]
Hi @noapocalypse, you will receive a final update on this issue by 25th July, 2023.

**Comment by v-rbajaj** [comment]
Since the closed PR has many bugs, that can't be pushed, new PR for this playbook will be raised soon.

**Comment by v-rbajaj** [comment]
We are working and having a discussion internally on this

**Comment by v-rbajaj** [comment]
We are working on this and having a discussion internally on this

**Comment by ajkallur** [comment]
@manishkumar1991 @v-rbajaj  the playbook can be released. Since, this is being published as an individual Sentinel Playbook and not being included part of the MDTI-Sentinel Content hub Solution.

**Comment by v-rbajaj** [comment]
We are having an internal discussion on this issue.

**Comment by v-rbajaj** [comment]
Waiting for update from the respective team.

**Comment by v-rbajaj** [comment]
Hi all, we have raised a backlog item for this playbook and will discuss and update according to the discussions there.
