### ISSUE TITLE
Unable to Monitor the Azure Honeytokens via Sentinel

### ISSUE THREAD

**Issue by grsandeep** [Azure/Azure-Sentinel#7897]
Unable to Monitor the Azure Honeytokens via Sentinel

When clicked on "Add Monitoring in the SOC" from the SOCHManagement we are seeing an error.

When went into deep and see the error is with-in the logicApp "HoneyTokensAdd2WLKV" and the error is innerError": "Workspace id doesn't exist"

I checked and updated the correct workspace ID in the API Connection, but still failing. Can someone suggest ?

**Comment by v-vdixit** [comment]
Hi @grsandeep we have two more similar issues related to this solution and we are actively working with the solution owners to troubleshoot and resolve the issues, thanks!

**Comment by v-vdixit** [comment]
Hi @grsandeep we are working with solution owners on this, will update you once we hear back from them, thanks!

**Comment by v-vdixit** [comment]
Hi @grsandeep we are still waiting to hear back from the solution owners, thanks!

**Comment by v-vdixit** [comment]
Hi @grsandeep thanks for your patience please ensure you have admin access to install and use this solution and refer to this documentation - [Honey Tokens Solution](https://github.com/Azure/Azure-Sentinel/blob/master/Solutions/HoneyTokens/README.md) to troubleshoot from your end, we are working on with the team will update you shortly, thanks!

**Comment by v-vdixit** [comment]
Gentle Reminder: We are waiting for your response on this issue. If you still need to keep this issue active, please respond on it in the next 2 days. If we don't receive response, we will be closing this issue as per our standard procedures, thanks!

**Comment by v-vdixit** [comment]
Gentle Reminder: We are waiting for your response on this issue. If you still need to keep this issue active, please respond on it in the next 2 days. If we don't receive response, we will be closing this issue as per our standard procedures, thanks!

**Comment by v-vdixit** [comment]
Since we have not received a response in the last 5 days, we are closing your issue as per our standard operating procedures. If you still need support for this issue, feel free to re-open at any time. Thank you for your co-operation
