### ISSUE TITLE
How to Get M365 Audit log for eDiscovery activities like create content search or view search via sentinel log query

### ISSUE THREAD

**Issue by angerfirecn** [Azure/Azure-Sentinel#7919]
**Is your feature request related to a problem? Please describe.**
Yes, We need use SIME to Close the incident for M365 audit log with  M365 activities like eDiscovery "create content search"  or "view search", not only alert from M365  activity alert for email notice. 

**Describe the solution you'd like**
Via Sentinel log query to get the M365 activities like  eDiscovery "create content search"  or "view search" ... and make Analytics rule to create incident to close the internal risk.

**Describe alternatives you've considered**
M365 Defender for Office to create the custom alert for eDiscovery "create content search"  or "view search" ..., and sync the alert from MDO to sentinel. but just "eDiscovery search started or exported" one activities now

**Additional context**

**Comment by angerfirecn** [comment]
any update?

**Comment by v-vdixit** [comment]
Hi @angerfirecn we have tagged this as an enhancement and our team is working on adding the analytic rule you have requested for in "Expected Solution", thanks!

**Comment by angerfirecn** [comment]
Great！ Hope Public preview ASAP

**Comment by v-vdixit** [comment]
Hi we are still discussing this with team, will update you shortly, thanks!

**Comment by v-vdixit** [comment]
Hi @angerfirecn can you please provide confirmation that these events are not created by

**Comment by v-vdixit** [comment]
Since we have not received a response in the last 5 days, we are closing your issue as per our standard operating procedures. If you still need support for this issue, feel free to re-open at any time. Thank you for your co-operation.

**Comment by linko7527** [comment]
hello. i m interess by to knmw how i can creat an alert hen a new e discovery case is created. do u have a solution? thnax

**Comment by cyberman6877** [comment]
Can we please reopen this, we do not have an answer and I am stuck on the same issue, how can we Get M365 Audit log for eDiscovery activities like create content search or view search via sentinel log query

**Comment by pensivepaddle** [comment]
@cyberman6877 
> Can we please reopen this, we do not have an answer and I am stuck on the same issue, how can we Get M365 Audit log for eDiscovery activities like create content search or view search via sentinel log query

@linko7527 
> hello. i m interess by to knmw how i can creat an alert hen a new e discovery case is created. do u have a solution? thnax

It should be available through the `CloudAppEvents` table. An extensive list of all relevant `ActionTypes` to look for may be found in the docs [here](https://learn.microsoft.com/en-us/purview/ediscovery-search-for-activities-in-the-audit-log).
