### ISSUE TITLE
SIGNL4 2.0.2 image not accepted

### ISSUE THREAD

**Issue by rons4** [Azure/Azure-Sentinel#7929]
**Describe the bug**
There is a new SIGNL4 package:
https://github.com/Azure/Azure-Sentinel/blob/master/Solutions/SIGNL4/Package/2.0.2.zip
Thanks for that.
If I upload it, the approval process fails:
![image](https://user-images.githubusercontent.com/43244104/234629056-1ef183d4-2cd9-434e-8db7-8b912ec9c189.png)

It seems the image did not change. Not sure what the problem might be.

**To Reproduce**
1. Upload the above package
2. Start the approval process and click "go live"
3. I get the above error

**Expected behavior**
The approval process should succeed.

**Screenshots**
See above.

**Desktop (please complete the following information):**
N/A

**Smartphone (please complete the following information):**
N/A

**Additional context**
N/A

**Comment by v-prasadboke** [comment]
Hello @rons4 looking into this
