### ISSUE TITLE
Three bugs in AzurePortalSigninfromanotherAzureTenant.yaml

### ISSUE THREAD

**Issue by esschotenw** [Azure/Azure-Sentinel#7948]
The latest update for the analytic rule "Azure Portal sign in from another Azure Tenant" contains three bugs that will prevent us from updating the rule.  

The first bug: On lines 26 and 27 the line "with(format='multijson')" exists 2 times. The solution is to remove "with(format='multijson')" from line 27 as I did locally.
The second bug: the function "ipv6_is_in_any_range" is not available for Log Analytics but for Azure Data Explorer. No solution found, I've commented these out.
The third bug: The error in "Alert Description Format" in the section "Alert details" is "Too many column names. You can define up to 3 column names". The solution is to delete the latest sentence with a column "with the User Agent of {{UserAgent}}."

I did the bugfixes locally and the validation passed

**Comment by v-vdixit** [comment]
Hi @esschotenw Thanks for flagging this, we have raised a PR - #7967 for resolving the first and third bug and for second bug that you have reported regarding the ipv6_is_in_any_range() function, we tried running the below test query in workspace for the given function
let LocalNetworks=dynamic([
    "a5e:f127:8a9d:146d:e102:b5d3:c755:f6cd/112",
    "0:0:0:0:0:ffff:c0a8:ac/60"
]);
let IPs=datatable(IP:string) [
    "a5e:f127:8a9d:146d:e102:b5d3:c755:abcd",
    "a5e:f127:8a9d:146d:e102:b5d3:c755:abce",
    "a5e:f127:8a9d:146d:e102:b5d3:c755:abcf",
    "a5e:f127:8a9d:146d:e102:b5d3:c756:abd1",
];
IPs
| extend IsLocal=ipv6_is_in_any_range(IP, LocalNetworks)

We observed that the results returned after running this query are as expected so the workspace is accepting this function as required, if there is anything else we can assist you with please let us know, thanks!

**Comment by esschotenw** [comment]
> 

Hi @v-vdixit, Thank you!
I've tested your query on our workspaces and it's working properly as you said. So, the second one is no bug!
But it's still weird that Logs, where we put the KQL, marks this function with a red line and error text: "The name 'ipv6_is_in_any_range' does not refer to any know functions.
