### ISSUE TITLE
ASIM/deploy tools do not deploy the 2nd required empty unifying parser for NetworkSession

### ISSUE THREAD

**Issue by deggis** [Azure/Azure-Sentinel#7975]
**Describe the bug**

[ASIM/deploy/EmptyCustomUnifyingParsers](https://github.com/Azure/Azure-Sentinel/blob/master/ASIM/deploy/EmptyCustomUnifyingParsers/NetworkSessionDeploymentCustomUnifyingParsers.json) deploys only `NetworkSessionCustom`, while the built-in function also requires `NetworkSessionSolutions`.

[ASimFullDeployment](https://github.com/Azure/Azure-Sentinel/blob/master/ASIM/ASimFullDeployment.json) does not seem to bring those either.

**To Reproduce**
1. Go to https://github.com/Azure/Azure-Sentinel/tree/master/ASIM
3. Follow the steps to "This template deploy all ASIM parsers".
4. Observe that one workspace function for NetworkSession schema was created
5. See error when you try to use built-in functions

Current definition of _ASim_NetworkSession from Azure portal:
```
union isfuzzy=true
_ASim_NetworkSessionBuiltIn(pack= pack),
ASim_NetworkSessionSolutions(pack= pack),    <-- missing?
ASim_NetworkSessionCustom(pack= pack)
```

Current definition of _Im_NetworkSession from Azure portal:
```
union isfuzzy=true
_Im_NetworkSessionBuiltIn(...args),
Im_NetworkSessionSolutions(...args),    <-- missing?
Im_NetworkSessionCustom(...args)
```

**Expected behavior**
I would expect that after deploying all ASIM parsers or parsers for a specific schema that I could use the built-in functions `_ASim_NetworkSession` or `_Im_NetworkSession` without errors.

**Comment by oshezaf** [comment]
This behavior is intentional. Im_NetworkSessionSolutions is intended for future use and should not be populated now. Using union isfuzzy=true ensures that the query works even if this parser is missing.

**Comment by deggis** [comment]
> This behavior is intentional. Im_NetworkSessionSolutions is intended for future use and should not be populated now. Using union isfuzzy=true ensures that the query works even if this parser is missing.

Oh, right! Thanks for the explanation!
