### ISSUE TITLE
Analytics rules for SysdigSecure_CL with Tactics and techniques: T1609 & T0807 configures prevents host entity mapping from populating

### ISSUE THREAD

**Issue by eric-mark** [Azure/Azure-Sentinel#7984]
**Describe the bug**
We are ingesting SysDig logs to Azure Sentinel to a SysdigSecure_CL table.  If we create an analytic rules and map the mitre attack framework to T1609 & T0807, our host entity mapping no longer populates for our alerts.  If we remove the alert mapping for T1609 & T0807, the host entity mapping populates again.

**To Reproduce**

1. Ingest Sysdigs logs to Log Analytic Workspace with Azure Sentinel

3. Create an analytic rule with tactics and techniques.:
- T1609 - Container Administration Command
- T0807 - Command-Line Interface

4. Security: High

6. Create Rule Query (we can open a msft support case to provide you the exact query if you wish)

7. Configure the entity mappings for
- Host = labels_host_hostName_S
- Account = content_fields_user_name_s

8. Configure the custom details (we can provide via msft support case if you are interested)

9. Query scheduling:
- Run every 1 hour, lookup data from last 1 day

10. Create incident from alert trigger:
- Enabled

11. Alert grouping:
- Enabled

12. Limit the group of alerts created within time frame
- 1 day

13. Group matching by host, and other vars (we can expose more information via msft support case)

**Expected behavior**
Host entity mapping enrich our alert with or without the mitre attack framework tags.

**Screenshots**

![image](https://user-images.githubusercontent.com/45639241/236551824-0eb72342-ec34-44e3-9c61-e8f69806cebe.png)

![image](https://user-images.githubusercontent.com/45639241/236552435-35a59ca0-293a-4634-a83d-e2d64c43a4b4.png)

**Additional context**

This problem seems to be specific to the Execution tags for:
- T1609 - Container Administration Command
- T0807 - Command-Line Interface

**Comment by v-vdixit** [comment]
Hi @eric-mark could you please provide us with some sample data for SysdigSecure_CL table to work on this issue, thanks!

**Comment by eric-mark** [comment]
Hi @v-vdixit,

We have opened a msft support Case 2305080010003362 to either securely transfer sample data from our table or to provide you direct access.

**Comment by v-vdixit** [comment]
Hi @eric-mark please provide update on this.

**Comment by eric-mark** [comment]
@v-vdixit -- this is the message we received from msft support:

"Ive already located an internal issue on this that looks similar to what you are describing, and I'll see if we get a solution to help with this issue you are seeing.

I'm looking forward to partnering with you on a timely and helpful solution."

RayAnn Long
Support Engineer | Cloud & Infrastructure Solutions | Azure Security, Identity, & Management


Has the support team reached out to you to provide you access to our sentinel logs?  If not, I could raise this with our tam to get the support case linked over.

**Comment by v-vdixit** [comment]
Hi @eric-mark I have not yet received any update from support team, thanks!

**Comment by v-vdixit** [comment]
Gentle Reminder: We are waiting for your response on this issue. If you still need to keep this issue active, please respond on it in the next 2 days. If we don't receive response, we will be closing this issue as per our standard procedures, thanks!

**Comment by eric-mark** [comment]
@v-vdixit -- did msft support team get in contact with you?  We have raised this with our account manager for to get support team connected with you.

The last message we received from support was:

"Just want to check back on this – we did finally get an update that this should be remediated now.
Can you please confirm? 
 
RayAnn Long
Support Engineer"

And currently, one of our soc analyst is testing out if this has been fixed or not.

**Comment by v-vdixit** [comment]
Hi @eric-mark I have not heard anything from support team yet, if there is any update on this please let me know, thanks!

**Comment by v-vdixit** [comment]
Since we have not received a response in the last 5 days, we are closing your issue as per our standard operating procedures. If you still need support for this issue, feel free to re-open at any time. Thank you for your co-operation.
