### ISSUE TITLE
Bug in FirstAppOrServicePrincipalCredential.yaml

### ISSUE THREAD

**Issue by selmas** [Azure/Azure-Sentinel#7989]
The current version of the detection rule FirstAppOrServicePrincipalCredential.yaml contains the field "TenantId" in the second to last line (project-reorder statement). However, this field is not available which prevented us from updating the rule.

I fixed the bug locally by removing the field "TenanteId" and the validation passed.

**Comment by v-vdixit** [comment]
Hi @selmas Gentle Reminder: We are waiting for your response on this issue. If you still need to keep this issue active, please respond on it in the next 2 days. If we don't receive response, we will be closing this issue as per our standard procedures, thanks!

**Comment by v-vdixit** [comment]
Hi @selmas Since we have not received a response in the last 5 days, we are closing your issue #7989 as per our standard operating procedures. If you still need support for this issue, feel free to re-open at any time. Thank you for your co-operation

**Comment by selmas** [comment]
Sorry for the late reply. Issue was local and is now resolved. Thanks for your support!
