### ISSUE TITLE
fwdingDestination value for Multiple users email forwarded to same destination sometimes returns True

### ISSUE THREAD

**Issue by Lokaalin** [Azure/Azure-Sentinel#801]
The analytics rule Multiple users email forwarded to same destination sometimes has the value True for fwdingDestination instead of a proper email address. We've seen this in cases where someone is sending an email on behalf of someone else

The UserID mentions the exchange account + on behalf of + exchange account. 

Ports | **fwdingDestination** | EventCount | timestamp
["18599","49095"] | **TRUE** | 2 | 2020-06-22T15:15:36Z
["18599","49095"] | **TRUE** | 2 | 2020-06-22T15:15:36Z

**Expected behavior**
The value should contain the address the emails are being forwarded to or the query not count the result if nothing is being forwarded.

**Comment by Lokaalin** [comment]
Looking at the query it parses fwdingDestination from Parameters:

| extend parsed = parse_json(Parameters)
| extend parameterName = parsed[1].Name, fwdingDestination = tostring(parsed[1].Value)

The order in OfficeActivity - Parameters doesnt seem to be consistent, for the query to work it needs to contain

0 | {"Name":"Identity","Value"
1 | {"Name":"ForwardingSmtpAddress"
2 | {"Name":"DeliverToMailboxAndForward","Value"

In the problematic records Identity is last in the list.

**Comment by shainw** [comment]
@Lokaalin - thanks for the feedback, we are looking into this and will get back to you by next week with how we may be able to address this.

**Comment by shainw** [comment]
Submitted a PR for the fix - #818 - Please check it out and see if this works for you.

**Comment by Lokaalin** [comment]
I don't have access to the same logs anymore but it should work.

**Comment by shainw** [comment]
@Lokaalin - Thanks the PR #818 has been committed to master.
