### ISSUE TITLE
AbuseIPDB Logic App has incorrect targetProduct

### ISSUE THREAD

**Issue by dustypaulson** [Azure/Azure-Sentinel#8011]
**Describe the bug**
In the select statement of the logic app AbuseIPDB-BlacklistIpToThreatIntelligence the select statement for targetProduct has the value as Microsoft Sentinel but the api only allows for Azure Sentinel.

**To Reproduce**
1. Deploy AbuseIPDB solution from content hub
2. Set permissions for managed identity
3. Run runbook AbuseIPDB-BlacklistIpToThreatIntelligence
4. Observe failure after runtime (see print screen: Error Message Screenshot before being fixed)

**Expected behavior**
Data gets added to the ThreatIntelleginceIndicator datatype in log analytics but returns an error

**Screenshots**
Broken Select Statement
![image](https://github.com/Azure/Azure-Sentinel/assets/26881778/0a52c851-2dc2-4d54-b0b5-cd25cfe8d118)

Fixed Screen Shot
![image](https://github.com/Azure/Azure-Sentinel/assets/26881778/5dd58eef-66c8-4cca-8865-926375a14c2f)

Error Message Screenshot before being fixed
![image](https://github.com/Azure/Azure-Sentinel/assets/26881778/d312d7ad-b14a-4f4b-bef6-9b7db8b33564)

**Comment by v-vdixit** [comment]
Hi @dustypaulson Can you please check the following points once and confirm for us:
1) Got to AbuseIPDB solution from content hub then go to playbook AbuseIPDB-BlacklistIpToThreatIntelligence
2) Select the API connections tab 
![image](https://github.com/Azure/Azure-Sentinel/assets/115772287/263d5f52-07de-43e4-a1b8-c2ebff45b559)
3) Select abuseipdb-AbuseIPDB-BlacklistIpToThreatIntelligence connection and go to Edit API Connection and ensure the API key parameter has your required key and save the changes
![image](https://github.com/Azure/Azure-Sentinel/assets/115772287/dd56482d-3ff0-48b3-b75f-f03f37151ca2)
4) Again back on API connections tab select the ThreatIntelligence-connection-AbuseIPDB-BlacklistIpToThreatIntelligence connection and in the Edit API tab ensure that you have Authorized the usage of the API save the changes and run again.

If you still face the same issues please let us know, we would discuss further with the team, thanks!

**Comment by dustypaulson** [comment]
> Hi @dustypaulson Can you please check the following points once and confirm for us:
> 
> 1. Got to AbuseIPDB solution from content hub then go to playbook AbuseIPDB-BlacklistIpToThreatIntelligence
> 2. Select the API connections tab
>    ![image](https://user-images.githubusercontent.com/115772287/237361081-263d5f52-07de-43e4-a1b8-c2ebff45b559.png)
> 3. Select abuseipdb-AbuseIPDB-BlacklistIpToThreatIntelligence connection and go to Edit API Connection and ensure the API key parameter has your required key and save the changes
>    ![image](https://user-images.githubusercontent.com/115772287/237361639-dd56482d-3ff0-48b3-b75f-f03f37151ca2.png)
> 4. Again back on API connections tab select the ThreatIntelligence-connection-AbuseIPDB-BlacklistIpToThreatIntelligence connection and in the Edit API tab ensure that you have Authorized the usage of the API save the changes and run again.
> 
> If you still face the same issues please let us know, we will discuss further with the team, thanks!

Hello! There was no issue with AbuseIP Blacklist action gathering the data from their API. The issue was with the action submit multiple ti indications. The targetProduct for the TI indications which is a static string in the select statement needs the product name of **Azure Sentinel** not **Microsoft Sentinel**. I have already resolved the issue in my environment. Just wanted to let you know the app itself in the content hub has incorrect information. 

If you look at the print screens above that is the actual fix for the app. 

Have a great day!

**Comment by v-vdixit** [comment]
Thanks for flagging this, @dustypaulson, we appreciate your feedback and will discuss and apply it, as per your comment, I am closing this issue as resolved, if you still face this issue, feel free to open again this, thanks.

**Comment by dustypaulson** [comment]
> Thanks for flagging this, @dustypaulson, we appreciate your feedback and will discuss and apply it, as per your comment, I am closing this issue as resolved, if you still face this issue, feel free to open again this, thanks.

Hello @v-vdixit ! I missed one piece to the solution for this. In Microsoft Sentinel the data connector Threat Intelligence Platforms (Preview) needs to be connected otherwise the logic app will run correctly but no data is added to the Threat Intelligence feed. Just wanted to let you know!

**Comment by v-vdixit** [comment]
Sure, thanks for this update, we will convey this to the team.
