### ISSUE TITLE
UserAssignedPrivilegedRole.yaml will return empty target if PIM was done against service principal

### ISSUE THREAD

**Issue by best-geek** [Azure/Azure-Sentinel#8014]
**Describe the bug**
KQL issue with query in detection. 

The Azure AD detection for [UserAssignedPrivilegedRole](https://github.com/Azure/Azure-Sentinel/blob/c6dce9c3aa4d4b4d02423ac4eb5a6b677a39e432/Solutions/Azure%20Active%20Directory/Analytic%20Rules/UserAssignedPrivilegedRole.yaml) will return an empty value in the 'Target' column, if PIM was activated against a Service Principal. 

This is because the Target field is populated by an KQL `extend` of 'TargetResources.userPrincipalName'. If the PIM target is a Service Principal then there is no UPN available in the logs.

**Resolution**
The fix can be applied by adding the following line below the initial extend on line 38, capturing the DisplayName instead, if the TargetResource was a Service Principal:
```
| extend Target = tostring(TargetResources.userPrincipalName) 
| extend Target = iff(TargetResources.type == "ServicePrincipal", tostring(TargetResources.displayName), Target)
``` 

**To Reproduce**
1. Deploy detection to Sentinel environment with Azure AD Logs
2. Create a Service Principal (creating an Enterprise Azure AD application should suffice)
3. In Azure AD activate a PIM role against a Service Principal (ie, Exchange Administrator)
4. Wait for the Sentinel detection to fire
5. See that the `Target` column is empty. 

**Expected behavior**
See fix above which correctly identifies the target when it's a Service Principal 

**Additional context**
Issue with the KQL query and fix supplied.

**Comment by v-vdixit** [comment]
Hi @best-geek thanks for flagging this, we are checking on this will update you shortly, thanks!

**Comment by v-vdixit** [comment]
Hi @best-geek we are working on updating the changes, will publish the updated solution shortly, thanks!

**Comment by v-vdixit** [comment]
Hi @best-geek we are working on this solution packaging with latest updates in our packaging tool, the changes will be updated shortly, thanks!

**Comment by v-vdixit** [comment]
Hi @best-geek we are working on this solution packaging with latest updates in our packaging tool, the changes will be updated shortly, thanks!

**Comment by best-geek** [comment]
Awesome - thank you :)

**Comment by v-vdixit** [comment]
Hi @best-geek we will be raising the PR with updated package by Wednesday, 19th July 2023, thanks!

**Comment by v-vdixit** [comment]
Hi @best-geek we are working on another query issue in same solution package, will be raising a PR post updating that query in this package, thanks for your patience, we will be raising PR till Friday, 21st July 2023
