### ISSUE TITLE
Imperva WAF Cloud connector bug

### ISSUE THREAD

**Issue by tokesr** [Azure/Azure-Sentinel#8017]
**Describe the bug**
Seems like there is a bug or defficiency at least in the Imperva Cloud WAF solution data connector:
https://github.com/Azure/Azure-Sentinel/blob/master/Solutions/ImpervaCloudWAF/Data%20Connectors/ImpervaWAFCloudSentinelConnector/__init__.py

I think the decrypt_and_unpack_file does not do any type of decryption.
Also the code has an issue that can throw an error while it could have been easily handled.

1: Events_data used before assignment - throws an error
```
file_encryption_flag = file_header.find("key:")
if file_encryption_flag == -1:
    events_data = zlib.decompressobj().decompress(file_data).decode("utf-8")
if events_data is not None:
   #some code
```

Here inthe code above you can see that the 'if events_data is not None' will throw an error if file_encryption_flag is not equal to -1.
Possible the second 'if' here should be an elif type branch like: "elif events_data is not None" or a nested "else: if events_data is not None".

2: No decryption is being done.
Seemingly there is no decryption is done in the code at least I could not identify the code in this function that does decryption. The function name 'decrypt_and_unpack_file' indicates there should be some decryption done as well'.
Also there is a variable regarding decryption that is not being used in the code:
```
logs_encryption_private_key = ""
```
Seems like the code is not finished and it does not support decryption right now. Is this correct?

**To Reproduce**
1. Open the code and review it
2. Potentially one can deploy the code, enable encryption in Imperva WAF and check the error messages. I assume the events_data is referred before assignment error is created due to encryption, so when the 'if file_encryption == -1' is not true!

**Expected behavior**
Not to throw error message.
Work with encrypted data in Imperva.

**Comment by tokesr** [comment]
hey folks, do we have any update regarding this case?

**Comment by v-vdixit** [comment]
Hi @tokesr thanks for flagging this, we are discussing with the team, will update you soon.

**Comment by v-vdixit** [comment]
Hi @tokesr we are testing the changes made in code will update shortly, thanks!

**Comment by v-vdixit** [comment]
Hi @tokesr currently this connector does not support encryption, can you please connect with Imperva team to get this included in the connector functionality, thanks!

**Comment by v-vdixit** [comment]
Gentle Reminder: We are waiting for your response on this issue. If you still need to keep this issue active, please respond on it in the next 2 days. If we don't receive response, we will be closing this issue as per our standard procedures, thanks!

**Comment by v-vdixit** [comment]
Since we have not received a response in the last 5 days, we are closing your issue as per our standard operating procedures. If you still need support for this issue, feel free to re-open at any time. Thank you for your co-operation
