### ISSUE TITLE
CrowdStrike Solution using inconsistent capitalization breaking case-sensitive KQL.

### ISSUE THREAD

**Issue by cs-shadowbq** [Azure/Azure-Sentinel#8028]
**Describe the bug**
CrowdStrike Solution using inconsistent capitalization breaking case-sensitive KQL.

**To Reproduce**
Throughout multiple files the solution uses inconsistent capitalization of CrowdStrike.

Opening the solution and looking at the query you will find the red_underlined errors of KQL stating that the package does not exist. 

**Expected behavior**
CrowdStrike should be capital 'C' and 'S' for its propername. This is not spaces, Camel cased, nor is it underscored. 

**Screenshots**
If applicable, add screenshots to help explain your problem

![Bug1 - Screenshot 2023-04-28 at 3 56 30 PM](https://github.com/Azure/Azure-Sentinel/assets/77163928/e36ce5a3-c2a6-4eb9-a787-5669246ab185)

**Comment by cs-shadowbq** [comment]
As an example the provider should be changed 
```
from "providers": ["Crowdstrike"],
to "providers": ["CrowdStrike"],
```
The files should be renamed as well.

**Comment by v-vdixit** [comment]
Hi @cs-shadowbq we have fixed the issue in the parser that we were using in rules and queries in our latest package, for other content we are working on analyzing the impact it would have on end users, we will make the changes based on the impact they might create, please let us know if we can assist you with anything else, thanks!
