### ISSUE TITLE
Tools/AzureDataExplorer/Migrate-LA-to-ADX.ps1 does not select all relevant tables

### ISSUE THREAD

**Issue by andrePKI** [Azure/Azure-Sentinel#8039]
**Describe the bug**
Line 669 `$QueryAllTables = 'search *| distinct $table| sort by $table asc nulls last'` does not return all tables. For instance empty tables are not returned, nor are some tables (?) that are not real tables (I am not sure how to phrase this)
Besides that, in the log analytics workspace many more tables are present (see the Tables tab on the workspace itself *). So I guess a REST API call against `https://api.loganalytics.io` or something similar could be better.

*): in fact there are many more tables in the workspace, even the Tables blade does not show them all.

**To Reproduce**
1. Run the script
2. Count tables in ADX
3. Count tables in Sentinel or Log Analytics workspace Logs blade
4. Count tables in the Log Analytics workspace Tables blade
5. use REST api call, run this code
``
$metadata=Invoke-AzRestMethod -Path "https://api.loganalytics.io/v1/subscriptions/<subs Id>/resourcegroups/<resource group name>/providers/microsoft.operationalinsights/workspaces/<workspace name>/metadata?api-version=2017-10-01" -method POST
$tabs= $tables.Content | Convertfrom-Json
$tabs.value.count
``
6. Find that the result of 2. is much less than 3. and 4. en that the result of 5. is even bigger

**Expected behavior**
I would expect that the script creates _all_ tables that are present in the workspace (or at least the ones that hold data). This is the number of tables in the Logs blade of Sentinel as a minimum.

**Screenshots**
![image](https://github.com/Azure/Azure-Sentinel/assets/23510294/02e9d527-e7cf-4871-bf48-5336b204c4c3)
As an example `ADXIngestionBatching` table is missing from the query results.

![image](https://github.com/Azure/Azure-Sentinel/assets/23510294/c82bfe85-74e7-496d-857a-a2d586d01965)
This shows 115 tables

![image](https://github.com/Azure/Azure-Sentinel/assets/23510294/e365084b-32d7-4a4d-a0df-9084ef323a7c)
and here 508 tables.

**Desktop (please complete the following information):**
N/A

**Smartphone (please complete the following information):**
N/A

**Additional context**
N/A

**Comment by v-vdixit** [comment]
Hi @sreedharande can you please have a look at this feature request, thanks!

**Comment by sreedharande** [comment]
@andrePKI - Thanks, can you please raise PR with this change

**Comment by v-vdixit** [comment]
Gentle Reminder: We are waiting for your response on this issue. If you still need to keep this issue active, please respond on it in the next 2 days. If we don't receive response, we will be closing this issue as per our standard procedures, thanks!

**Comment by andrePKI** [comment]
This issue may be closed. I will and create a pull request

**Comment by v-rbajaj** [comment]
Thanks @andrePKI for the confirmation. We are closing this issue.
