### ISSUE TITLE
Describe mapping logic used in Cisco ASA/FTD via AMA connector

### ISSUE THREAD

**Issue by DonadoJuan** [Azure/Azure-Sentinel#8080]
**Is your feature request related to a problem? Please describe.**
As of now `Connector Cisco ASA/FTD via AMA [docs](https://learn.microsoft.com/en-us/azure/sentinel/data-connectors/cisco-asa-ftd-via-ama) do not describe the mapping logic used to transform Cisco ASA logs and map them into CommonSecurityLog table.

**Describe the solution you'd like**
It would be nice to describe what specific fields from CommonSecurityLog table are being used to store values from Cisco ASA logs. In that way we can create KQL queries for this vendor without the need to use sample data.

**Comment by prtanej** [comment]
Hi @DonadoJuan - Thank you for the feedback. This page has been taken down as we work on more aspects of this connector via a Private Preview. It will be re-introduced at a later time.

I will be closing this issue, but I would encourage you to continue leveraging this channel (GitHub issues) to share your feedback to help identifying improvement opportunities.
