### ISSUE TITLE
Array handling in SignInAnomaly 

### ISSUE THREAD

**Issue by hzjace3d** [Azure/Azure-Sentinel#8081]
**Is your feature request related to a problem? Please describe.**
Azure/Azure-Sentinel/tree/master/Detections/Anomalies/SignInAnomaly.yaml: line 37 does not handle arrays (although it might be unique to my environment)

**Describe the solution you'd like**
Reference the proper array element (usually 0, but it requires further analysis) -  "| extend PasswordResult = tostring(parse_json(AuthenticationDetails)[0].authenticationStepResultDetail)" or solve it with mv-expand - if the rest of the array contains relevant information(I think not). 
I'm open to further suggestions too, what do you think?

**Comment by v-vdixit** [comment]
Hi @hzjace3d we are discussing with the concerned team, will update you once we receive update from them, thanks!

**Comment by v-vdixit** [comment]
Hi @hzjace3d we are waiting to hear back from the concerned team, will update you once we hear back from them, thanks!

**Comment by v-vdixit** [comment]
Hi @hzjace3d the team has suggested to use on the below line, please check if your requirements are met by adding this
_**| extend PasswordResult = tostring(parse_json(AuthenticationDetails)[0].authenticationStepResultDetail)**_
Thanks.

**Comment by v-vdixit** [comment]
Gentle Reminder: We are waiting for your response on this issue. If you still need to keep this issue active, please respond on it in the next 2 days. If we don't receive response, we will be closing this issue as per our standard procedures, thanks!

**Comment by v-vdixit** [comment]
Since we have not received a response in the last 5 days, we are closing your issue as per our standard operating procedures. If you still need support for this issue, feel free to re-open at any time. Thank you for your co-operation.
