### ISSUE TITLE
Potential beaconing activity (ASIM Network Session schema) does not filter 169.254.0.0/16

### ISSUE THREAD

**Issue by rweirtbg** [Azure/Azure-Sentinel#8105]
**Describe the bug**
[Potential beaconing activity (ASIM Network Session schema)] (https://github.com/Azure/Azure-Sentinel/blob/a6593c2bb08c6cb6fbcaabdd961c83ef9f9b89b1/Solutions/Network%20Session%20Essentials/Analytic%20Rules/PossibleBeaconingActivity.yaml) does not filter out self-assigned IPs (169.254.0.0/16).

**To Reproduce**
Trigger a beaconing alert with a destination of 169.254.0.0/16

**Expected behavior**
We should not see alerts for traffic destined for 169.254.0.0/16 since that IP space is not routable.

**Comment by v-rbajaj** [comment]
Hi @devikamehra, can you please look into this issue?

**Comment by devikamehra** [comment]
@rweirtbg Thank you for the suggestion. We will accommodate this change in future releases. But for now, you can modify the current query to fix these false positives.

**Comment by devikamehra** [comment]
Let us know if you need any further assistance otherwise we can close this by adding the suggestion as a workitem in our backlog.

**Comment by azurekid** [comment]
The Analytics rule mentioned above is using the statement on line 7 `| where not(ipv4_is_private(DstIpAddr))` to avoid alerts of private address ranges. This is a build-in function as described in this article: https://learn.microsoft.com/en-us/azure/data-explorer/kusto/query/ipv4-is-privatefunction

Based on the documentation the function is working as expected as the CIDR 169.254.0.0/16 is not part of this function just like the 127.0.0.0/24 range.

@oshezaf @devikamehra I can add the exclusion of private ranges by adding a `let PrivateRanges` statement including the ranges that are not picked up by the previous function.

Let me know if I need to create a PR for this.

**Comment by v-vdixit** [comment]
Thanks for the update @azurekid

**Comment by v-vdixit** [comment]
> The Analytics rule mentioned above is using the statement on line 7 `| where not(ipv4_is_private(DstIpAddr))` to avoid alerts of private address ranges. This is a build-in function as described in this article: https://learn.microsoft.com/en-us/azure/data-explorer/kusto/query/ipv4-is-privatefunction
> 
> Based on the documentation the function is working as expected as the CIDR 169.254.0.0/16 is not part of this function just like the 127.0.0.0/24 range.
> 
> @oshezaf @devikamehra I can add the exclusion of private ranges by adding a `let PrivateRanges` statement including the ranges that are not picked up by the previous function.
> 
> Let me know if I need to create a PR for this.

Hi @azurekid thanks for the details you have provided please raise a PR for this and mention this issue in it, we will get it reviewed by the team, thanks!

**Comment by v-vdixit** [comment]
Hi @rweirtbg we are waiting for @azurekid to raise PR, thanks!

**Comment by v-vdixit** [comment]
Hi @azurekid we are waiting for update from you on this, thanks!

**Comment by azurekid** [comment]
Hi I am currently on a holiday in Croatie with very limited internet coverage on the campsite.
Will update once I will have access

**Comment by v-vdixit** [comment]
Thanks for the update @azurekid please update us here once you have raised PR

**Comment by v-rbajaj** [comment]
Hi @azurekid, please let us know once you have raised the PR.

**Comment by v-rbajaj** [comment]
Hi @azurekid, did you get a chance to a raise a PR?

**Comment by v-rbajaj** [comment]
Hi @azurekid, Did you raise a PR? Please provide some response that would be really appreciated..

**Comment by azurekid** [comment]
Hi,

Sorry, Data is really horrible here. 
Got a 150 kbs connection 🙈 have created the code locally, buy not able to test due to connection limitations

**Comment by azurekid** [comment]
Hi, I have created a PR #8690 for issue #8105

On line six I have added the following to define local ranges:

```kql
let LocalNetworks=dynamic(["169.254.0.0/16","127.0.0.0/8"]);
```
On line nine the results are filtered based on the LocalNetworks:

```kql
| where not (ipv4_is_in_any_range(DstIpAddr, LocalNetworks))
```

Also did some code alignment, fixed a typo in the description, and added 2 private ranges

**Comment by v-rbajaj** [comment]
Hi @rweirtbg, thanks for raising the PR. We will soon review it and provide you an update.

**Comment by azurekid** [comment]
> Hi @rweirtbg, thanks for raising the PR. We will soon review it and provide you an update. 
> 

LoL, I made the PR, not @rweirtbg 😉

**Comment by v-rbajaj** [comment]
> > Hi @rweirtbg, thanks for raising the PR. We will soon review it and provide you an update.
> 
> LoL, I made the PR, not @rweirtbg 😉

Really sorry on that, thanks for raising the PR @azurekid, we are reviewing the PR and we will soon get back to you.

**Comment by v-rbajaj** [comment]
Hi all, we are still reviewing the PR, we will get back to you once there is an update.

**Comment by v-rbajaj** [comment]
Hi all, we are still reviewing the PR, we will get back to you once there is an update.

**Comment by vakohl** [comment]
@v-rbajaj @azurekid PR is approved.
