### ISSUE TITLE
Add ability to choose or exclude activities to ingest

### ISSUE THREAD

**Issue by beachfires** [Azure/Azure-Sentinel#8115]
Hardcoding activities which are onboarded creates a situation where we are struck ingesting logs which we do not want, and is causing necessary costs. It would be simple to add the ability to define which activities to exclude from the default list using an environment variable.

https://github.com/Azure/Azure-Sentinel/blob/63d0796e36e87bc93f9c3e24fe2a7c97a9d54a22/Solutions/GoogleWorkspaceReports/Data%20Connectors/GWorkspaceReportsAPISentinelConnector/__init__.py#L32

**Comment by v-vdixit** [comment]
Hi @beachfires we are reviewing the PR, will provide an update soon, thanks!

**Comment by v-vdixit** [comment]
Hi @beachfires we have merged the PR will publish the latest changes for this shortly, thanks!
