### ISSUE TITLE
" Microsoft Defender for Office 365" alerts issues

### ISSUE THREAD

**Issue by shipothana** [Azure/Azure-Sentinel#8126]
Hi,

Sentinel incidents are not redirecting to Microsoft Defender for Office 365; what is the issue here?
 
May I know what I need to do to troubleshoot?

**Comment by v-vdixit** [comment]
Hi @shipothana To troubleshoot the issue of Sentinel incidents not redirecting to Microsoft Defender for Office 365, you can try the following steps:

1) Verify that the Microsoft 365 Defender data connector is enabled to collect incidents and alerts - [connector link](https://github.com/MicrosoftDocs/azure-docs/blob/main/articles/sentinel/connect-microsoft-365-defender.md).

2) Check that the Microsoft 365 Defender incidents appear in the Microsoft Sentinel incidents queue with the product name [Microsoft 365 Defender](https://github.com/MicrosoftDocs/azure-docs/blob/main/articles/sentinel/microsoft-365-defender-sentinel-integration.md).

3) Ensure that the connectors for all the integrated components and services (Defender for Endpoint, Defender for Identity, Defender for Office 365, Defender for Cloud Apps, and Azure Active Directory Identity Protection) are automatically connected in the background if they weren't already.
4) If any component licenses were purchased after Microsoft 365 Defender was connected, the alerts and incidents from the new product will still flow to Microsoft Sentinel with no additional configuration or charge.

**Comment by v-vdixit** [comment]
Gentle Reminder: We are waiting for your response on this issue. If you still need to keep this issue active, please respond on it in the next 2 days. If we don't receive response, we will be closing this issue as per our standard procedures, thanks!
