### ISSUE TITLE
DNS Solution - Watch lists are missing in version 2.0.2

### ISSUE THREAD

**Issue by maniaX1** [Azure/Azure-Sentinel#8148]
**Describe the bug**
When you deploy new version of DNS Essentials from Content Hub you don't get Watchlists installed:
DNS_Solution_Domain_IOCs
DNS_Solution_Monitoring_Configuration

Since they are not available then hunting queries will not work.

**To Reproduce**

**Expected behavior**

**Screenshots**
![image](https://github.com/Azure/Azure-Sentinel/assets/33328622/b3df4f92-7299-4147-b3eb-e3881a02c996)
![image](https://github.com/Azure/Azure-Sentinel/assets/33328622/33ae44b2-3192-4840-a5d4-c287c24a74a1)

**Comment by vakohl** [comment]
@maniaX1 are you referring to this hunting query? 'Detect DNS request to known Domain IOCs (ASIM DNS Solution)'
Known domain IOCs related Hunting Query and Analytics rule were removed from the solution in the recent release. These rules along with watchlist are no longer part of this solution.

**Comment by maniaX1** [comment]
@vakohl Hello, yes I am refering to exactly this hunting query. I missed that it is not supported anymore and strange is that even I updated DNS Essentials solution hunting query stayed in Sentinel. Anyway good to know and thank you!

**Comment by v-vdixit** [comment]
Thanks, @maniaX1, we will be closing this issue as resolved.

**Comment by maniaX1** [comment]
Thank you!
