### ISSUE TITLE
Data of type O365 was dropped as the maximum columns is reached

### ISSUE THREAD

**Issue by alexandrupnt** [Azure/Azure-Sentinel#8155]
Describe the problem that is being experienced with the alert rule.

Answer: Operation table, has thousands of entries with the FAILED error below

Data of type O365 was dropped: The number of custom fields 501 is above the limit of 500 fields per data type. See https://aka.ms/AA593as to find instructions for removing unnecessary custom fields for this type.

Documentation used: https://github.com/Azure/Azure-Sentinel/tree/master/DataConnectors/O365%20Data

The solution is supposed to take into consideration the column Limite

limitation of Service:

![image](https://github.com/Azure/Azure-Sentinel/assets/104505093/c364fd0c-5eaa-489e-aacf-deffb8bcfc68)
https://learn.microsoft.com/en-us/azure/azure-monitor/service-limits

**Comment by alexandrupnt** [comment]
Hello team, do we have any updates on this topic ?

**Comment by v-rbajaj** [comment]
Hi @alexandrupnt, we are checking with the team internally, we will provide an update soon.

**Comment by v-vdixit** [comment]
Hi @alexandrupnt we have understood the issue you are facing, we tried checking the documentation link you have attached and it's not working, can you please check this link - https://aka.ms/AA593as once please, thanks!

**Comment by alexandrupnt** [comment]
not possible, this link - https://aka.ms/AA593as is from the error message and in deed is not working

**Comment by alexandrupnt** [comment]
Hello, do we have any updates here ?

**Comment by v-rbajaj** [comment]
Hi @alexandrupnt, sorry for the delay in response. We have checked with the team internally.
You can delete some custom records from the custom table which are not necessary and try to keep the count below 500 to get it working. 
I am attaching the steps to delete the custom columns from the custom table below. I hope this helps. 
[Steps To Delete Columns From Custom Table - Draft.docx](https://github.com/Azure/Azure-Sentinel/files/11915819/Steps.To.Delete.Columns.From.Custom.Table.-.Draft.docx)

**Comment by v-rbajaj** [comment]
Hi @alexandrupnt, Gentle Reminder: We are awaiting for your response on this issue. If you still need to keep this issue active please respond on it in the next 2 days . If we don't receive response, we will be close this issue.

**Comment by alexandrupnt** [comment]
Hi @v-rbajaj, thank you for your reply. You can close the case. We will delete some record in the custom table
