### ISSUE TITLE
TAXII Connector not importing data

### ISSUE THREAD

**Issue by clarked-msft** [Azure/Azure-Sentinel#8164]
**Describe the bug**
The TAXII connector does not import threat indicators from my TAXII server.

**To Reproduce**
1. Setup OpenCTI taxii server
2. Add IPv4 indicator
3. Configured TAXII connector to OpenCTI TAXII endpoint
4. Verify no threat indicators imorted to Sentinel

**Expected behavior**
Threat indicators returned in configured TAXII collection are imported into Sentinel.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Edge
 - Version: latest

**Additional context**
I'm able to see that the calls from sentinel to my TAXII server are successful and have the expected payload size, but I do not have any insight into why indicators don't show up in Sentinel, or which indicators should should up in Sentinel.  I configured Sentinel to import all indicators.

**Comment by v-vdixit** [comment]
Hi @clarked-msft, we have discussed with the concerned team about this, please open an ICM to Sentinel US/Threat Intelligence and their on-call will work on it, thanks.
