### ISSUE TITLE
Cannot deploy 'NRT Authentication Methods Changed for VIP Users' Analytic Rule

### ISSUE THREAD

**Issue by rweirtbg** [Azure/Azure-Sentinel#8187]
**Describe the bug**
'NRT Authentication Methods Changed for VIP Users' cannot be deployed.

https://github.com/Azure/Azure-Sentinel/blob/master/Solutions/Azure%20Active%20Directory/Analytic%20Rules/NRT_AuthenticationMethodsChangedforVIPUsers.yaml

**To Reproduce**
1. Go to add new rule. Select 
2. See error `'distinct' operator: Failed to resolve scalar expression named '["User Principal Name"]'.` on the Rule Logic Page

**Expected behavior**
We should see no error.

<img width="1489" alt="Screenshot 2023-06-02 at 4 15 07 AM" src="https://github.com/Azure/Azure-Sentinel/assets/111534841/9412f49c-0398-4c99-a35a-984d3784641f">

**Comment by v-rbajaj** [comment]
Hi @rweirtbg, We were able to deploy the query as this is part of Azure Active Directory solution. Can you please re try from your end? Also please make sure that the sample data is there in your workspace. 
![image](https://github.com/Azure/Azure-Sentinel/assets/120547590/eb9a411d-c570-4466-9cd7-de19b22ec3c5)

**Comment by v-rbajaj** [comment]
Hi @rweirtbg, Gentle Reminder: We are awaiting for your response on this issue. If you still need to keep this issue active please respond on it in the next 2 days. If we don't receive response, we will be close this issue.

**Comment by v-rbajaj** [comment]
Hi @rweirtbg, Since we have not received a response in the last 5 days, we are closing https://github.com/Azure/Azure-Sentinel/issues/8187 your issue as per our standard operating procedures. If you still need support for this issue, feel free to re-open at any time. Thank you for your co-operation.

**Comment by rweirtbg** [comment]
Hi @v-rbajaj ,

Here's the screenshot.

![Screenshot 2023-06-15 at 1 51 24 AM](https://github.com/Azure/Azure-Sentinel/assets/111534841/cae11306-ac34-4d7c-86e0-f34b69baf9e4)

**Comment by esfateev** [comment]
I've got same error with this analytical rule. Please fix it.

**Comment by esfateev** [comment]
> Hi @rweirtbg, We were able to deploy the query as this is part of Azure Active Directory solution. Can you please re try from your end? Also please make sure that the sample data is there in your workspace. ![image](https://user-images.githubusercontent.com/120547590/243565296-eb9a411d-c570-4466-9cd7-de19b22ec3c5.png)

Is it possible to reopen issue? I've tested this rule on two differente tenants, same error.
