### ISSUE TITLE
Cannot deploy "A client made a web request to a potentially harmful file (ASIM Web Session schema)"

### ISSUE THREAD

**Issue by rweirtbg** [Azure/Azure-Sentinel#8189]
**Describe the bug**
Cannot deploy "A client made a web request to a potentially harmful file (ASIM Web Session schema)"

**To Reproduce**
1. Deploy Rule.
2. See error on Rule Logic tab: `Request is invalid and cannot be processed: Syntax error: SYN0001: I could not parse that, sorry. [line:position=0:0].` 

**Expected behavior**
No Error

**Screenshots**
<img width="1486" alt="Screenshot 2023-06-02 at 4 51 40 AM" src="https://github.com/Azure/Azure-Sentinel/assets/111534841/329eee16-1972-453b-ab5b-f899631c7ff7">

**Comment by oshezaf** [comment]
@vakohl : can you have a look?

**Comment by vakohl** [comment]
acknowledged.

**Comment by v-vdixit** [comment]
Hi @rweirtbg the PR is under review by team, changes will be published once the PR is merged, thanks!

**Comment by v-vdixit** [comment]
Hi @rweirtbg the PR is under review by team, changes will be published once the PR is merged, thanks!

**Comment by v-vdixit** [comment]
Hi @rweirtbg the PR has been merged, closing this as completed, thanks!
