### ISSUE TITLE
Bug in Azure Sentinel Query: Incorrect Usage of "contains_cs" Operator

### ISSUE THREAD

**Issue by serpaldom** [Azure/Azure-Sentinel#8190]
**Description:**
I would like to report a bug in the GitHub repository of Microsoft Azure Sentinel. The bug is related to the incorrect usage of the "contains_cs" operator in a specific query. The query can be found in the file "MalformedUserAgents.yaml" in the following location: https://github.com/Azure/Azure-Sentinel/blob/master/Detections/MultipleDataSources/MalformedUserAgents.yaml

**Issue:**
In the query provided in the file, the "contains_cs" operator is not being used correctly. Instead, the operator "containscs" is being used, which is not the correct syntax according to the current documentation available at https://learn.microsoft.com/en-us/azure/data-explorer/kusto/query/contains-cs-operator.

Query Snippet:
```   // Likely artefact of hardcoding
  | where UserAgent startswith "User" or UserAgent startswith '\"'
  // Incorrect casing
  or (UserAgent startswith "Mozilla" and not(UserAgent containscs "Mozilla"))
  // Incorrect casing
  or UserAgent containscs  "(Compatible;"
  // Missing MSIE version
  or UserAgent matches regex @"MSIE\s?;"
  // Incorrect spacing around MSIE version
  or UserAgent matches regex  @"MSIE(?:\d|.{1,5}?\d\s;)"
  | extend timestamp = StartTime, IPCustomEntity = SourceIP, AccountCustomEntity = Account
``` 

**Solution:**
The correct operator to be used is "contains_cs" which is designed for case-sensitive substring search within a string. To address the bug, the instances of "containscs" should be replaced with "contains_cs" in the query.

Additionally, in terms of query efficiency, there are areas where optimization can be considered. For example, the condition or (UserAgent startswith "Mozilla" and not(UserAgent containscs "Mozilla")) can be simplified to or (UserAgent !startswith_cs "Mozilla"), removing the unnecessary "containscs" operator.

I hope this report is helpful in addressing the bug. If you have any further questions or need additional information, please let me know.

**Comment by v-vdixit** [comment]
Hi @serpaldom thanks for flagging this, we will raise a PR with the changes that you have suggested shortly.
