### ISSUE TITLE
Celirium -  TAXii Sever

### ISSUE THREAD

**Issue by DeanHaycox** [Azure/Azure-Sentinel#8205]
Just to let you know, the Celirium - TAXii is not accepting new requests to this feed anymore. 

Would you have an alternative for this , to move forward with this part of the project?

thank you

**Comment by v-vdixit** [comment]
Hi @DeanHaycox can you please provide screenshots for the error so we can troubleshoot the error better, thanks!

**Comment by DeanHaycox** [comment]
Hi,

thanks for the reply back. This is the document I'm following.
https://github.com/Azure/Azure-Sentinel/blob/master/Solutions/Training/Azure-Sentinel-Training-Lab/Modules/Module-3-Analytics-Rules.md
Module 2

Here is the link that is in that module for the threat intelligence.
https://www.celerium.com/pickupstix

thank you
Dean

**Comment by v-vdixit** [comment]
Hi @DeanHaycox thanks for updating us, for this issue you can get in touch with the Celirium team to stay updated on the status of their feed and receive notifications when they start accepting new requests again. Once they resume operations, you can proceed with integrating their feed into your project and continue working towards your objectives. Please let us know if there is anything we can help you with. Thanks!

**Comment by v-rbajaj** [comment]
Hi @DeanHaycox, Gentle Reminder: We are awaiting for your response on this issue. If you still need to keep this issue active please respond on it in the next 2 days . If we don't receive response, we will be close this issue.

**Comment by v-rbajaj** [comment]
Hi @DeanHaycox, Since we have not received a response in the last 5 days, we are closing your issue https://github.com/Azure/Azure-Sentinel/issues/8205 as per our standard operating procedures. If you still need support for this issue, feel free to re-open at any time. Thank you for your co-operation.
