### ISSUE TITLE
imAuthSigninsMultipleCountries should exclude nonInteractive logons ?

### ISSUE THREAD

**Issue by SunChero** [Azure/Azure-Sentinel#8207]
Hi Guys,

this rule generate a lot of noise with noninteractive logon requests being made from microsoft /public  apps and not  the client's specific apps or client tenant bound identities.
is it possible to exclude the nonInteractive logon events coming from microsoft public apps Ids   such as Bing, Cortana ...etc

Thank you

**Comment by devikamehra** [comment]
@SunChero Thank you for raising the issue. I understand your concern here and would take the appropriate action.

@v-amolpatil Can you please raise a PR to modify this query to exclude EventSubType == "NonInteractive". The issue will arise for any NonInteractive login source and not just AAD.

**Comment by v-vdixit** [comment]
Hi @SunChero we are working with the concerned team will update you once we hear back from them, thanks!

**Comment by v-rbajaj** [comment]
Hi @SunChero, we are working on this with the respective team and will soon get back to you.

**Comment by v-vdixit** [comment]
Hi @SunChero we are still waiting to hear back from the concerned team, will update you shortly, thanks!

**Comment by v-vdixit** [comment]
Hi @SunChero we are waiting for update from concerned team, thanks!

**Comment by v-vdixit** [comment]
Hi @SunChero we are still waiting for update from concerned team, will update you once we hear back from them, thanks!

**Comment by v-vdixit** [comment]
Hi @SunChero we are waiting for update from concerned team, thanks!

**Comment by v-rbajaj** [comment]
Waiting for update from concerned team.

**Comment by v-rbajaj** [comment]
Hi @SunChero, we are waiting for update from concerned team, we will get back to you once there is an update.

**Comment by v-rbajaj** [comment]
Hi @SunChero, we will get back to you once there is an update.

**Comment by v-rbajaj** [comment]
Hi @SunChero, we will get back to you once there is an update.

**Comment by v-rbajaj** [comment]
Hi @SunChero, we will get back to you once there is an update.

**Comment by vakohl** [comment]
@SunChero thankyou for your suggestion. Before looking more into this just wanted to be sure that you're referring to this rule: https://github.com/Azure/Azure-Sentinel/blob/master/Detections/ASimAuthentication/imAuthSigninsMultipleCountries.yaml

Would it be possible for you to share few sample logs for the following scenario you shared?
we see alerts firing when an application like cortana or bing try to authenticate to another microsoft App such as windows search or notifications.

I'll check for possibility of your following suggestions:
-  whitelisting Microsoft own IPs from triggering the alerts
- ignore the alert if the requesting and resource App Ids are Microsofts first-party Apps (a list of these apps can be found from https://learn.microsoft.com/en-us/troubleshoot/azure/active-directory/verify-first-party-apps-sign-in#application-ids-of-commonly-used-microsoft-applications)

**Comment by v-rbajaj** [comment]
Hi @SunChero, 
Gentle Reminder: We are awaiting for your response on this issue. If you still need to keep this issue active please respond on it in the next 2 days. If we don't receive response, we will be close this issue.

**Comment by v-rbajaj** [comment]
Hi @SunChero, Since we have not received a response in the last 5 days, we are closing your issue #8207 as per our standard operating procedures. If you still need support for this issue, feel free to re-open at any time. Thank you for your co-operation.
