### ISSUE TITLE
Some Anomalies RuleName values should be coherent between them

### ISSUE THREAD

**Issue by ep3p** [Azure/Azure-Sentinel#8211]
**Is your feature request related to a problem?**

There are 2 Anomalies rules called "UEBA Anomalous Failed Sign-in" & "UEBA Anomalous Sign In".

**Describe the solution you'd like**

I think these two rules should be called similar, they both should use "Sign-in" or "Sign In", but not distinct values in each one.

![image](https://github.com/Azure/Azure-Sentinel/assets/2527990/23517142-2655-4c08-807f-c139c95eb2d9)

**Comment by v-vdixit** [comment]
Hi @ep3p Thank you for bringing the issue to our attention. After reviewing the two anomalies you mentioned, 'UEBA Anomalous Sign In' and 'UEBA Anomalous Failed Sign-in,' we have determined that while these anomalies may have similarities in terms of authentication and user behavior, they are intended to address distinct threat scenarios.
The 'UEBA Anomalous Sign In' anomaly focuses on detecting adversaries who may be attempting to steal credentials or gain persistence through credential access techniques or social engineering. It specifically looks for anomalies in valid account activities.
On the other hand, the 'UEBA Anomalous Failed Sign-in' anomaly is aimed at identifying adversaries who have no prior knowledge of legitimate credentials and may be attempting to gain unauthorized access through password guessing or brute-forcing. It focuses on detecting failed login attempts.
We hope this clarifies the purpose and intent of these two anomalies, if you are looking for something else then please let us know, thanks!

**Comment by ep3p** [comment]
@v-vdixit I am looking at something else, please what I want to mean is that one rule uses the term "Sign-in", and the other uses the term "Sign In", one has a "-" character, the other not. I think these terms should be coherent, both rules should write the same word.

**Comment by ep3p** [comment]
If they were really intended to be written with different versions of ”signin", please just close this issue, but both rules are looking at authentication events.

**Comment by ep3p** [comment]
Thank you very much @v-vdixit, as long as this is noticed this issue can be closed.

**Comment by v-vdixit** [comment]
@ep3p thanks for confirming, closing this now.
