### ISSUE TITLE
Checkpoint Networksession parser product name

### ISSUE THREAD

**Issue by cgiamp** [Azure/Azure-Sentinel#8214]
Hi all,

How about adding something more descriptive into product on Checkpoint parser:
https://github.com/Azure/Azure-Sentinel/blob/81cc5c26df0cf317b876d11fb2ea74c4f24a7ba5/Parsers/ASimNetworkSession/Parsers/ASimNetworkSessionCheckPointFirewall.yaml#L201
maybe something like "VPN-1 & FireWall-1" or "Checkpoint Firewall" just to avoid any misconceptions.

**Comment by oshezaf** [comment]
@v-amolpatil : ASIM tickets and issues should be assigned to Devika going forward.

**Comment by devikamehra** [comment]
@cgiamp Thank you so much for raising this issue.
EventVendor is set to "Checkpoint" and EventProduct is set to "Firewall". This unique pair will identify the logs perfectly.

Please let me know if you have any more concerns.
