### ISSUE TITLE
Juniper SRX parser "eating" first IP digit

### ISSUE THREAD

**Issue by TiboJFR** [Azure/Azure-Sentinel#8253]
**Describe the bug**
When I use the Juniper SRX parsers here : https://github.com/Azure/Azure-Sentinel/blob/master/Solutions/Juniper%20SRX/Parsers/JuniperSRX.txt with the first sample provided I get SrcIpAddress = 72.20.22.237 instead of 172.20.22.237

**To Reproduce**
In Sentinel logs tab I used Juniper SRX parser code on this simulated entry : 

```
let Sysl = datatable(SyslogMessage:string, EventTime:int, HostName:string,ProcessName:string,ProcessID:int)
[
   "RT_FLOW session created 172.20.22.237/161->134.207.87.33/162 0x0 None 155.117.69.171/52344->134.207.87.33/162 0x0 source rule source-nat-rule N/A N/A 17 trust_to_Untrust_Internet trust untrust 25620 N/A(N/A) reth4.0 UNKNOWN UNKNOWN UNKNOWN", 1685525912, "JuniperSRX_FW4", "RT_FLOW", 1111
];
```

Then I get SrcIpAddr 72.20.22.237 instead of SrcIpAddr 172.20.22.237

The regular expression line 88 : 
`| extend Parser = extract_all(@"^([\w\s\-]+)(\s\d|\:)\s?([\d\.]+)\/(\d+)\-\>([\d\.]+)\/(\d+)\s(\w+)?\s?([\w\-]+)\s([\d\.]+)\/(\d+)\-\>([\d\.]+)\/(\d+)\s([\S\s]+)",dynamic([1,2,3,4,5,6,7,8,9,10,11,12,13]), Message)` is failing.

I tried this one instead and it seems to work (though I don't have any full testing dataset) : `| extend Parser = extract_all(@"^([\w\s\-]+)\s([\d\.]+)\/(\d+)\-\>([\d\.]+)\/(\d+)\s(\w+)?\s?([\w\-]+)\s([\d\.]+)\/(\d+)\-\>([\d\.]+)\/(\d+)\s([\S\s]+)",dynamic([1,2,3,4,5,6,7,8,9,10,11,12,13]), Message)`

**Screenshots**
![image](https://github.com/Azure/Azure-Sentinel/assets/119405686/38633664-c68f-4a0c-b02e-814b0f76ebe9)

**Comment by kavishbakshi1** [comment]
We are looking into the issue and one of our developers will start working on it soon.

**Comment by v-mchatla** [comment]
Hi @TiboJFR
Thanks for flagging this, I will be working on it today and will keep you posted.
Thanks

**Comment by v-mchatla** [comment]
Hi @@TiboJFR
We have fixed the issue and raised a [PR](https://github.com/Azure/Azure-Sentinel/pull/8357). Will merge the changes and make it live by 27th April.
Thanks

**Comment by TiboJFR** [comment]
[heart]         Thibaud Johannet reacted to your message:
________________________________

**Comment by v-mchatla** [comment]
Hi @TiboJFR 
We have pushed the solution to live. Please let me know if you need any further assistance on this.
Thanks

**Comment by v-vdixit** [comment]
> Hi @TiboJFR We have pushed the solution to live. Please let me know if you need any further assistance on this. Thanks

Closing this, thanks!
