### ISSUE TITLE
ThreatIntelligenceTaxii source info

### ISSUE THREAD

**Issue by clarked-msft** [Azure/Azure-Sentinel#8273]
**Is your feature request related to a problem? Please describe.**
Request for information.
Solutions/Threat Intelligence/Data Connectors/template_ThreatIntelligenceTaxii.JSON
Is the Threat Intelligence Taxii data connector open source?  I would like to use it with additional authentication options.

**Describe the solution you'd like**
Access to the threat intelligence taxii data connector source code if possible, with instructions on how to deploy from source...

**Describe alternatives you've considered**
Using the OpenCTI playbook is an option, but less desirable.

**Additional context**

**Comment by v-vdixit** [comment]
Hi @clarked-msft You can find the details of ThreatIntelligenceTaxii - [TAXII connector Configurations](https://docs.microsoft.com/azure/sentinel/import-threat-intelligence#adding-threat-indicators-to-azure-sentinel-with-the-threat-intelligence---taxii-data-connector), I hope this answers your question, if you are looking for something else, please let us know, thanks!

**Comment by clarked-msft** [comment]
Hello.  Thanks for the documentation, but this is not what I'm looking for.  Is that TAXII connector open source?  I can't find it in the repository.  I have a requirement to use client certificate authentication from Sentinel to our TAXII server and it doesn't seem possible with the current connector.  Thanks!

**Comment by v-vdixit** [comment]
Hi @clarked-msft here is the link to Taxii connector in repo - [template_ThreatIntelligenceTaxii](https://github.com/Azure/Azure-Sentinel/blob/master/Solutions/Threat%20Intelligence/Data%20Connectors/template_ThreatIntelligenceTaxii.JSON), please check and confirm if this is what you are looking for, thanks!

**Comment by v-vdixit** [comment]
Gentle Reminder: We are waiting for your response on this issue. If you still need to keep this issue active, please respond on it in the next 2 days. If we don't receive response, we will be closing this issue as per our standard procedures, thanks!

**Comment by clarked-msft** [comment]
I'm looking for source code.  Seems it is closed source?  Thanks

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by v-vdixit** [comment]
The source code we have available for the connector in our repository is attached above and for other details please check the documentation for taxii connector [here](https://learn.microsoft.com/en-us/azure/sentinel/connect-threat-intelligence-taxii), thanks!

**Comment by v-vdixit** [comment]
Gentle Reminder: We are waiting for your response on this issue. If you still need to keep this issue active, please respond on it in the next 2 days. If we don't receive response, we will be closing this issue as per our standard procedures, thanks!

**Comment by clarked-msft** [comment]
That looks to be just some template to deploy the connector.  I will pursue other options.  Thanks.
