### ISSUE TITLE
ESET Protect CEF ingested logs parser

### ISSUE THREAD

**Issue by Rapsoulis** [Azure/Azure-Sentinel#8276]
**Is your feature request related to a problem? Please describe.**
Not a problem but potential improvement.
The current [ESET Protect parser](https://github.com/Azure/Azure-Sentinel/blob/master/Solutions/ESETPROTECT/Parsers/ESETPROTECT.txt) only checks for log that have been ingested via syslog. Is there a plan to create a CEF parser that would check in the CommonSecurityLog table?

**Describe the solution you'd like**
Creation of a new parser for CEF ingested logs by ESET Protect. Same applies for the 2 available [Analytics Rules](https://github.com/Azure/Azure-Sentinel/tree/master/Solutions/ESETPROTECT/Analytic%20Rules).

**Describe alternatives you've considered**
Existing flow setup is still a viable option. 

**Additional context**
Related CEF formatting of logs forwarded by ESET Protect:
https://help.eset.com/protect_admin/10.0/en-US/events_exported_to_cef_format.html

**Comment by v-vdixit** [comment]
Hi @Rapsoulis we are working on your request, will update you shortly, thanks!

**Comment by v-vdixit** [comment]
Hi @Rapsoulis we have reached out to the concerned team with your feature request, will update you once we hear back from them, thanks!

**Comment by v-vdixit** [comment]
Hi @Rapsoulis we are waiting to hear back from the concerned team, will update you once we hear back from them, thanks!

**Comment by v-vdixit** [comment]
Hi @Rapsoulis we have updated the solution owners about this issue, will update you once we hear back from them, thanks!

**Comment by Rapsoulis** [comment]
Hi @v-vdixit looking forward for further updates. Thank you for looking into this topic.

**Comment by v-vdixit** [comment]
Hi @Rapsoulis we are waiting for update from solution owners on this, thanks!

**Comment by v-vdixit** [comment]
Hi @Rapsoulis we are still waiting for update from solution owners, thanks!

**Comment by v-vdixit** [comment]
Hi @Rapsoulis we are waiting for update from solution owners on this, thanks!

**Comment by v-rbajaj** [comment]
Hi @Rapsoulis, waiting for update from concerned team.

**Comment by v-rbajaj** [comment]
Hi @Rapsoulis, waiting for update from concerned team.

**Comment by v-rbajaj** [comment]
Hi @Rapsoulis, we have informed the concerned team, we will get back to you once there is an update.

**Comment by v-rbajaj** [comment]
Hi @Rapsoulis, Thanks for your suggestion. We've informed the respective team for this enhancement also you can raise a ticket with support team - https://techcenter.eset.nl/en/ for further updates.
