### ISSUE TITLE
Unsual behaviour when managing RBAC in Sentinel as MSSP via Azure Lighthouse

### ISSUE THREAD

**Issue by DonadoJuan** [Azure/Azure-Sentinel#8286]
**Describe the bug**
When mananing a Sentinel instance from a different tenant via Azure lightouse, the Microsft Secutity Insight (Microsoft application) of the client's tenant seems to merged with the MSSP tenant's Microsoft Security insights. This generates a "Mirror" efect where if we add playbook permissions to the MSSP's sentinel over a specific resource group, then that same permission will be automatically added to the client's sentinel too. Also, if we were to remove this permission from the client's sentinel, this would cause the same permission to be removed from the MSSP's sentinel. 

**To Reproduce**
1. Stablish an Azure Lighthouse offer emited by MSSP tenant over Client tenant's resource group/subscription.
2. Create a Sentinel instance in MSSP tenant.
3. Create a Sentinel instance in Client tenant.
4. In MSSP's sentinel instance. Go to Settings -> Playbook permisions -> Configure permissions.
5. In browse tab select any resource group belonging to MSSP tenant and apply permissions to it. 
6. In Client's sentinel instance. Go to Settings -> Playbook permisions -> Configure permissions -> Current Permissions. You will notice permission from step 5 was also automatically added to the Client's sentinel instance.

**Expected behavior**
MSSP and Client security insights should be independant from each other. Adding playbook permisions to a MSSP sentinel should not affect other sentinel instances belonging to other tenants.

**Comment by v-vdixit** [comment]
Hi @DonadoJuan we are waiting for update from concerned team, will update you shortly on this, thanks!

**Comment by v-vdixit** [comment]
Hi @DonadoJuan can you please provide some screenshots highlighting the issue you are facing, thanks!

**Comment by v-vdixit** [comment]
Gentle Reminder: We are waiting for your response on this issue. If you still need to keep this issue active, please respond on it in the next 2 days. If we don't receive response, we will be closing this issue as per our standard procedures, thanks!

**Comment by v-vdixit** [comment]
Since we have not received a response in the last 5 days, we are closing your issue as per our standard operating procedures. If you still need support for this issue, feel free to re-open at any time. Thank you for your co-operation
