### ISSUE TITLE
ApiKey (without encryption) ingested into storage account table

### ISSUE THREAD

**Issue by navintkr** [Azure/Azure-Sentinel#8287]
On [AzureFunctionOktaSSO/run.ps1 ](https://github.com/Azure/Azure-Sentinel/blob/master/Solutions/Okta%20Single%20Sign-On/Data%20Connectors/Okta%20Single%20Sign-On/AzureFunctionOktaSSO_V2/AzureFunctionOktaSSO/run.ps1#L84) we noticed that **rowkey values ingested with Api Key** when there is update to the table. Also, we can't have encryption at the storage account level and so **ApiKey** will be exposed as the plan text to everyone who has the access to store account which is a security threat.

**Comment by v-rbajaj** [comment]
Hi @navintkr, thanks for flagging this, we will soon get back to you.

**Comment by v-vdixit** [comment]
Hi @navintkr we are discussing with the concerned team, will update you shortly, thanks!

**Comment by v-vdixit** [comment]
Hi @navintkr can you please check if using ConvertFrom-SecureString -SecureString <variable> works as a solution for you, so that we can add this as a part of script, thanks!

**Comment by v-vdixit** [comment]
Gentle Reminder: We are waiting for your response on this issue. If you still need to keep this issue active, please respond on it in the next 2 days. If we don't receive response, we will be closing this issue as per our standard procedures, thanks!

**Comment by v-vdixit** [comment]
Since we have not received a response in the last 5 days, we are closing your issue as per our standard operating procedures. If you still need support for this issue, feel free to re-open at any time. Thank you for your co-operation
