### ISSUE TITLE
ConfigAwsConnector.ps1 throws errors and then quits after 3 retries.

### ISSUE THREAD

**Issue by bobsyourmom** [Azure/Azure-Sentinel#8293]
**Describe the bug**
Location of script(s):
https://github.com/Azure/Azure-Sentinel/tree/master/DataConnectors/AWS-S3
When running this script from powershell (on Windows 11, fully patched), the following errors are consistently seen, before the script quits:
.\ConfigAwsConnector.ps1
Starting ConfigAwsConnector at: 06/16/2023 21:13:33
  Log created: C:\users\bob\aws\Logs\AwsS3-06162113.csv

To begin you will choose the AWS logs to configure.

Please enter the AWS log type to configure (VPC, CloudTrail, GuardDuty, CustomLog): CloudTrail

Checking AWS CLI configuration...

This script creates an Assume Role with minimal permissions to grant Azure Sentinel access to your logs in a designated S3 bucket & SQS of your choice, enable CloudTrail Logs, S3 bucket, SQS Queue, and S3 notifications.

  Notes:
  * You can find more information about the script in https://github.com/Azure/Azure-Sentinel/blob/master/DataConnectors/AWS-S3/README.md
  * If a resource name(like: S3, Sqs, Kms) already exists, the script will use the available one and not create a new resource

Assume role definition

Please enter role name. If you have already configured an assume role for Azure Sentinel, use the same role name: Sentinel
  Using role name: Sentinel
ConvertFrom-Json : Invalid JSON primitive: ROLE.
At C:\users\bob\aws\ConfigCloudTrailDataConnector.ps1:244 char:30
+ $roleArn = ($roleArnObject | ConvertFrom-Json ).Role.Arn
+                              ~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [ConvertFrom-Json], ArgumentException
    + FullyQualifiedErrorId : System.ArgumentException,Microsoft.PowerShell.Commands.ConvertFromJsonCommand

Write-Log : Cannot bind argument to parameter 'Message' because it is null.
At C:\users\bob\aws\ConfigCloudTrailDataConnector.ps1:245 char:20
+ Write-Log -Message $roleArn -LogFileName $LogFileName -Severity Verbo ...
+                    ~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Write-Log], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationErrorNullNotAllowed,Write-Log

**To Reproduce**
Follow the instructions as presented here:
https://github.com/Azure/Azure-Sentinel/tree/master/DataConnectors/AWS-S3

See error as shown above.

**Expected behavior**
no errors should be shown during the execution of the powershell script.

**Screenshots**
n/a

**Desktop (please complete the following information):**
 - OS: windows 11, fully patched.
 - Latest version of powershell and the AWS cli.

**Comment by v-vdixit** [comment]
Hi @bobsyourmom thanks for flagging this we will discuss with the team and update you shortly.

**Comment by bobsyourmom** [comment]
it also doesn't work on GovCloud but I'm very sure you guys aren't supporting that yet.

**Comment by v-rbajaj** [comment]
Hi @bobsyourmom, we are trying to connect to respective team, as soon as we get an update will let you know.

**Comment by v-rbajaj** [comment]
Hi @bobsyourmom, For easier investigation i need the customer logs file as well.
![MicrosoftTeams-image (3)](https://github.com/Azure/Azure-Sentinel/assets/120547590/635c6ae2-bf26-4eb1-9f6e-ef0d2e9e5f06)
In the logs file we would able to see all the commands results, and it will help us to understand if the bug is on our side or in AWS CLI response.

In addition to this, would like to verify that the rule name (Sentinel), really exists in your AWS account.

**Comment by v-vdixit** [comment]
Gentle Reminder: We are waiting for your response on this issue. If you still need to keep this issue active, please respond on it in the next 2 days. If we don't receive response, we will be closing this issue as per our standard procedures, thanks!

**Comment by v-vdixit** [comment]
Since we have not received a response in the last 5 days, we are closing your issue as per our standard operating procedures. If you still need support for this issue, feel free to re-open at any time. Thank you for your co-operation

**Comment by ezaspy** [comment]
I am experiencing this error too. 
I follow the steps from 
https://learn.icrosoft.

under *Automatic Setup* and upon running of ./ConfigAwsConnector.ps1 an error returns:
`Cannot bind argument to parameter 'Message' because it is null
Please execute again 'aws configure' and verify that AWS configuration is correct.`

**Comment by czglow** [comment]
Check the requirements of the powershell scripts.  They require Powershell v7+.

Now check the version of powershell you are running. type "$PSVersionTable.PSVersion" without the quotes
- If it shows v5 or something similar then you don't have the RIGHT version of powershell running.  The v7 Powershell installer, install along side the existing v5. 

Do not use ISE, instead, look in your start menu for Powershell 7.  Run that command window and with that go to the directory where the scripts where downloaded to.  Run the configaws script and all should be ok.
