### ISSUE TITLE
Threat Intelligence ingestion thorugh SecurityGraph trimmed error

### ISSUE THREAD

**Issue by exente** [Azure/Azure-Sentinel#8297]
Hello,

We have connected Anomali as Threat Intelligence feed through the TI connector, once we did this we are getting this error all the time

The following fields' values tags of type THREAT_INTELLIGENCE_INDICATOR_DATA have been trimmed to the max allowed size, 32766 bytes. Please adjust your input accordingly

Can it be fixed somehow?

**Comment by v-rbajaj** [comment]
Hi @exente, Thanks for flagging this, we are checking with the team internally and will provide an update on this soon.

**Comment by v-rbajaj** [comment]
Hi @exente, The error message you are seeing indicates that the values of the "tags" field of type THREAT_INTELLIGENCE_INDICATOR_DATA have been trimmed to the maximum allowed size of 32766 bytes. You will need to adjust your input according to this document 
https://github.com/MicrosoftDocs/azure-docs/blob/main/articles/sentinel/includes/sentinel-limits-threat-intelligence.md

**Comment by exente** [comment]
Hi @v-rbajaj thank you for the answer, how and where I can change this value then?

**Comment by v-rbajaj** [comment]
Hi @exente,
Here are a few suggestions to address this problem:

1. Reduce the length of the tags: Review the tags associated with the threat intelligence indicators and check if there are any lengthy or unnecessary values. Shorten or remove any tags that are not essential or exceed the maximum allowed size.
2. Prioritize important tags: If you have a large number of tags, prioritize the most relevant or critical ones and remove any less significant tags. This will help reduce the overall size of the tags field.
3. Use shorter tag values: Consider using shorter names or abbreviations for your tags without sacrificing clarity. This can help reduce the overall size of the tags field.
4. Split long tags into multiple fields: If you have lengthy tags that are essential, consider splitting them into multiple fields or using additional fields to store the information. This way, you can distribute the content across multiple fields and avoid exceeding the size limit for a single field.
5. Consult Anomali documentation or support: Refer to the Anomali documentation or reach out to their support team for specific guidance on working with the TI connector and managing the size limitations of the fields. They may have additional recommendations or insights tailored to their system.

By implementing these suggestions, you should be able to adjust your input and resolve the issue of the "tags" field exceeding the maximum allowed size.
