### ISSUE TITLE
Possible Beaconing Activity is using too many resources, generates too many events and associates too many entities.

### ISSUE THREAD

**Issue by rweirtbg** [Azure/Azure-Sentinel#8312]
**Describe the bug**

When we see this alert get triggered, the event data contains excessive amounts unrelated log data that needs to be filtered and triggers the "Your query is consuming excessive resources." in the Events view and generates matches to 100+ entities even though the title only contains one destination IP address.

https://github.com/Azure/Azure-Sentinel/blob/master/Solutions/Network%20Session%20Essentials/Analytic%20Rules/PossibleBeaconingActivity.yaml

**To Reproduce**
1. Go to alert generated by incident.
2. View excessive number of entities
3. Click on Events
4. See "Your query is consuming excessive resources."

**Expected behavior**
We should only see two entities for this alert.

**Screenshots**
<img width="479" alt="Screenshot 2023-06-20 at 9 01 12 AM" src="https://github.com/Azure/Azure-Sentinel/assets/111534841/93ab2af2-616b-4d31-af56-f2cf51cdd47d">

<img width="105" alt="Screenshot 2023-06-20 at 9 05 02 AM" src="https://github.com/Azure/Azure-Sentinel/assets/111534841/759bdda7-bdeb-47ff-bd36-ccba9546f854">

**Comment by v-vdixit** [comment]
Hi @rweirtbg thanks for flagging this, we are working on this with concerned team, will update you once we receive update from them, thanks!

**Comment by v-vdixit** [comment]
Hi @rweirtbg can you please add some screenshots of the error for our reference, thanks!

**Comment by rweirtbg** [comment]
Hi @v-vdixit I'm not sure what you are asking for exactly? The screenshot attached to the original post is from the query results. I can't share any of the results themselves here since they are customer proprietary.

**Comment by v-vdixit** [comment]
Hi @rweirtbg we are looking for screenshots of the error that you are facing, so that we can work on resolving that, thanks!

**Comment by v-vdixit** [comment]
Gentle Reminder: We are waiting for your response on this issue. If you still need to keep this issue active, please respond on it in the next 2 days. If we don't receive response, we will be closing this issue as per our standard procedures, thanks!

**Comment by v-vdixit** [comment]
Since we have not received a response in the last 5 days, we are closing your issue as per our standard operating procedures. If you still need support for this issue, feel free to re-open at any time. Thank you for your co-operation.

**Comment by rweirtbg** [comment]
HI @v-vdixit,

I'm at a bit of a loss here. The error that we are receiving is that this query is consuming too many resources and that screenshot is in the original post. I can't share any of the results here since they contain client proprietary data.

**Comment by v-vdixit** [comment]
Hi @rweirtbg We are not looking for the results we are looking for the error message you are getting, thanks!

**Comment by rweirtbg** [comment]
@v-vdixit "Your query is consuming too many resources" is the error message.
