### ISSUE TITLE
Oracle Cloud Infrastructure - Nonetype Error in Function

### ISSUE THREAD

**Issue by DavidT8777** [Azure/Azure-Sentinel#8313]
**Describe the bug**
Getting the following error messages. The function was working but now no data has been received since 6/15/23 (37 Success, 1949 Error as of 6/20/23 @ 11:35am)

2023-06-20 15:35:00.815
Result: Failure Exception: TypeError: argument of type 'NoneType' is not iterable Stack: File "/azure-functions-host/workers/python/3.8/LINUX/X64/azure_functions_worker/dispatcher.py", line 406, in _handle__invocation_request call_result = await self._loop.run_in_executor( File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run result = self.fn(*self.args, **self.kwargs) File "/azure-functions-host/workers/python/3.8/LINUX/X64/azure_functions_worker/dispatcher.py", line 648, in _run_sync_func return ExtensionManager.get_sync_invocation_wrapper(context, File "/azure-functions-host/workers/python/3.8/LINUX/X64/azure_functions_worker/extension.py", line 215, in _raw_invocation_wrapper result = function(**args) File "/home/site/wwwroot/AzureFunctionOCILogs/main.py", line 51, in main process_events(stream_client, StreamOcid, cursor, sentinel_connector, start_ts) File "/home/site/wwwroot/AzureFunctionOCILogs/main.py", line 124, in process_events if "headers" in event["data"]["request"]:
Error
2023-06-20 15:35:00.815
Executed 'Functions.AzureFunctionOCILogs' (Failed, Id=99e722d5-5672-4dce-88d9-be2c97cc547a, Duration=804ms)
Error
2023-06-20 15:35:00.826
Result: Failure Exception: TypeError: argument of type 'NoneType' is not iterable Stack: File "/azure-functions-host/workers/python/3.8/LINUX/X64/azure_functions_worker/dispatcher.py", line 406, in _handle__invocation_request call_result = await self._loop.run_in_executor( File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run result = self.fn(*self.args, **self.kwargs) File "/azure-functions-host/workers/python/3.8/LINUX/X64/azure_functions_worker/dispatcher.py", line 648, in _run_sync_func return ExtensionManager.get_sync_invocation_wrapper(context, File "/azure-functions-host/workers/python/3.8/LINUX/X64/azure_functions_worker/extension.py", line 215, in _raw_invocation_wrapper result = function(**args) File "/home/site/wwwroot/AzureFunctionOCILogs/main.py", line 51, in main process_events(stream_client, StreamOcid, cursor, sentinel_connector, start_ts) File "/home/site/wwwroot/AzureFunctionOCILogs/main.py", line 124, in process_events if "headers" in event["data"]["request"]:

**To Reproduce**
1. Go to Microsoft Sentinel
2. Select the Sentinel workspace
3. Select Content hub
4. Search Oracle Cloud Infrastructure
5. Deploy the solution as directed 

**Expected behavior**
Function deployed successfully and OCI logs were being pulled into the Azure workspace. However, the last log entry was on 6/15/23 and the function is now showing a NoneType error. No data is being retrieved at this point. Reviewing the stream in OCI (Oracle Government Cloud) shows that data is there.

**Screenshots**
![image](https://github.com/Azure/Azure-Sentinel/assets/137198855/dd1898f9-f546-47f0-b0e4-2e1daba2252b)
![image](https://github.com/Azure/Azure-Sentinel/assets/137198855/34c1f6db-b4b4-41db-b59d-9464a1769c5f)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Microsoft Edge
 - Version 114.0.1823.51 (Official build) (64-bit)

**Additional context**

**Comment by v-vdixit** [comment]
Hi @DavidT8777 thanks for flagging this, we already have an IcM for this and the team is working on it will update you shortly.

**Comment by v-vdixit** [comment]
Hi @DavidT8777 As per the lastest conversation, customer is not able to see the logs getting ingested as it exceeded the column limit of 500. When we request them to delete unnecessary columns from the custom table, the deleted columns are getting added to the Azure Columns.
Created IcM with Log Analytics team for this issue.
Thanks

**Comment by v-vdixit** [comment]
Hi @DavidT8777 this issue has been transferred to Log Analytics team, thanks!

**Comment by DavidT8777** [comment]
Hello,

I'm wondering if there's been any movement on the IcM with the Log Analytics team? We have no visibility on the issue since the ticket was transferred and closed.  I've updated the solution to the latest version but still get the same error.  Would it be possible to get the IcM number so that our team at Microsoft can research?  Thanks!
