### ISSUE TITLE
ARM template/script for Azure Gov for O365 Management Activity API Log Ingestion Deployment failing.

### ISSUE THREAD

**Issue by sreddy3219** [Azure/Azure-Sentinel#8314]
**Describe the bug**
ARM template/script for Azure Gov for O365 Management Activity API Log Ingestion Deployment failing.
The remote name could not be resolved: 'o365datasax3whmwgn4lvhg.file.core.windows.net

**To Reproduce**
1. Go to https://github.com/Azure/Azure-Sentinel/tree/master/DataConnectors/O365%20Data
2. Click on Azure GOV function App deployment button
3. Enter Details and Scroll Down and create
4. The remote name could not be resolved: 'o365datasax3whmwgn4lvhg.file.core.windows.net

**Expected behavior**
Deployment Successful

**Comment by v-rbajaj** [comment]
@sreddy3219, Thanks for flagging this, we will soon provide an update on this.

**Comment by v-rbajaj** [comment]
Hi @sreddy3219, we tried deploying the template on commercial portal, it did deploy successfully. 
Can you please share the screenshot of the error message you are receving?

**Comment by v-rbajaj** [comment]
Hi @sreddy3219, Gentle Reminder: We are awaiting for your response on this issue. If you still need to keep this issue active please respond on it in the next 2 days . If we don't receive response by given date we will be close this issue.

**Comment by sreddy3219** [comment]
Hi,

We tested in commercial too. It worked without any errors.  The issue we are facing is in Azure Gov Portal. I don’t have screenshot as we were asked to remove it from our environment due to compliance issues.
However, I have tested the Azure GOV template multiple times. I have faced same error as described below.
Please see the details below:

Describe the bug
ARM template/script for Azure Gov for O365 Management Activity API Log Ingestion Deployment failing.
The remote name could not be resolved: 'o365datasax3whmwgn4lvhg.file.core.windows.net
To Reproduce
Steps to reproduce the behavior:

  1.  Go to https://github.com/Azure/Azure-Sentinel/tree/master/DataConnectors/O365%20Data
  2.  Click on Azure GOV function App deployment button
  3.  Enter Details and Scroll Down and create
  4.  Error ” The remote name could not be resolved: 'o365datasax3whmwgn4lvhg.file.core.windows.net”
Thanks,
Swetha Reddy

**Comment by v-vdixit** [comment]
Hi @sreddy3219 we will check on the issue with Gov portal thanks for the update.

**Comment by v-vdixit** [comment]
Hi @sreddy3219 the error message "The remote name could not be resolved: 'o365datasax3whmwgn4lvhg.file.core.windows.net'" indicates that the DNS resolution failed. This could be due to a network issue or a misconfiguration in the ARM template, please check if the storage account is accessible and properly configured, please refer to the following documentation to troubleshoot the error, [Troubleshooting Guide](https://github.com/MicrosoftDocs/azure-docs/blob/main/articles/azure-resource-manager/troubleshooting/quickstart-troubleshoot-arm-deployment.md) and [Common Errors](https://github.com/MicrosoftDocs/azure-docs/blob/main/articles/azure-resource-manager/troubleshooting/common-deployment-errors.md)

**Comment by v-rbajaj** [comment]
Gentle Reminder: We are awaiting for your response on this issue. If you still need to keep this issue active please respond on it in the next 2 days. If we don't receive response by given date we will be close this issue.

**Comment by sreddy3219** [comment]
Hi,

This issue is still active. We are trying to replicate it.

Thanks,
Swetha Reddy

**Comment by v-vdixit** [comment]
Hi @sreddy3219 we are waiting for your update, thanks!

**Comment by v-rbajaj** [comment]
Hi @sreddy3219, waiting for the update.

**Comment by v-rbajaj** [comment]
Since we have not received a response in the last 5 days, we are closing your issue https://github.com/Azure/Azure-Sentinel/issues/8314. If you still need support for this issue, feel free to re-open at any time. Thank you for your co-operation.
