### ISSUE TITLE
'Multiple users email forwarded to same destination' alert has incomplete info, confusing users

### ISSUE THREAD

**Issue by randomstability** [Azure/Azure-Sentinel#8316]
**Describe the issue**
The '**Multiple users email forwarded to same destination**' (Office_MailForwarding.yaml) rule does not include the impacted mailbox, and hence the alert appears to insinuate that admin mailboxes are being modified to forward mail to another mailbox.  The "altered mailbox(es)" are _required_ information for this alert.

**To Reproduce**
1. Use the rule from [Multiple users email forwarded to same destination](https://github.com/Azure/Azure-Sentinel/blob/master/Solutions/Microsoft%20365/Analytic%20Rules/Office_MailForwarding.yaml)
2. Trigger the rule by having an O365 email admin modify 2 mailboxes to forward to the same email destination.
3. In the triggered alert, notice you have no way of knowing which 2 mailboxes were modified, and that it is implied that the admin mailboxes are (incorrectly) the ones altered.  Nowhere in the alert are the altered mailboxes mentioned, and the user is forced to try and locate the raw events to find the altered mailboxes.

**Desired Solution**
The rule should present all the relevant data to ensure users are not confused by the information presented.  It should include the 'Identity' parameter that is present in the source events and which appears to represent the "altered mailbox".  If 'Identity' is not assured to be the proper value, then it is at least correct sometimes (all the time for us?). 

Right now, the alert is the equivalent of 'a virus was found on a server", which is very unuseful.

**Additional context**
Perhaps there are better fields/lookups to determine the impacted mailbox, but I'm just a very simple infosec guy,  not an Exchange Admin.  Hopefully, either MS or the community knows best how to include the _required_ information.

**Comment by v-rbajaj** [comment]
Hi @randomstability, thanks for flagging this. We are looking into this internally and will soon provide an update.

**Comment by v-vdixit** [comment]
Hi @randomstability we are working with the concerned team on this, will update you as soon as we hear back from them, thanks!

**Comment by v-vdixit** [comment]
Hi @randomstability we are working on this solution packaging with latest updates in our packaging tool, the changes will be updated shortly, thanks!

**Comment by v-vdixit** [comment]
Hi @randomstability we are working on this solution packaging with latest updates in our packaging tool, the changes will be updated shortly, thanks!

**Comment by v-vdixit** [comment]
Hi @randomstability we have packaged this solution with latest updates in our packaging tool, will raise the PR by Tuesday, 18th July 2023, thanks!

**Comment by v-vdixit** [comment]
Hi @randomstability we encountered some issue with the updated package while testing we are working on fixing them, will update by 21st July 2023, thanks!

**Comment by v-vdixit** [comment]
Hi @randomstability we are working on resolving the issue in analytic rule will update you by Monday, 24th July 2023, thanks!

**Comment by v-vdixit** [comment]
Hi @randomstability we are still working on resolving the issue in analytic rule will update you by Wednesday, 26th July 2023, thanks!

**Comment by v-rbajaj** [comment]
Hi @randomstability, checking internally on this issue.

**Comment by v-rbajaj** [comment]
Hi @randomstability, checking internally on this issue.

**Comment by v-rbajaj** [comment]
Hi @randomstability, we will get back to you once there is an update.

**Comment by v-rbajaj** [comment]
Hi @randomstability, we will get back to you once there is an update.
