### ISSUE TITLE
Sentinel Hunting NoRegisteredProviderFound

### ISSUE THREAD

**Issue by jeffrywu28** [Azure/Azure-Sentinel#8319]
**Describe the bug**
can't access on hunting sentinel. even though from log analytics and microsoft sentinel and the resource group all are from UK South.

**To Reproduce**
1. Go to Microsoft Sentinel at Threat Management Group
2. Click on Hunting
3. Create Hunt
4. Then at actions i click add queries to hunt
5. See error 

**Expected behavior**
it should be accessible and usable because IAM access at the Resource group / Subscription level is already the owner or Microsoft Sentinel Contributor.

**Screenshots**
![image](https://github.com/Azure/Azure-Sentinel/assets/47622164/672ac6c3-f3e2-46c9-8bcc-e724067fb4d9)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version Latest

**Additional context**
Log Analytics Region : uksouth
Microsoft Sentinel Workspaces : uksouth
Still Showing error like this :
{"code":"NoRegisteredProviderFound","message":"No registered resource provider found for location 'uksouth' and API version '2023-04-01' for type 'contenttemplates'. The supported api-versions are '2022-11-01-preview, 2022-12-01-preview, 2023-02-01-preview, 2023-03-01-preview, 2023-04-01-preview, 2023-05-01-preview, 2023-06-01-preview'. The supported locations are 'westeurope, northeurope, francecentral, uksouth, ukwest, francesouth, switzerlandnorth, switzerlandwest, norwayeast, norwaywest, germanywestcentral, swedencentral, '."}

**Comment by v-vdixit** [comment]
Hi @jeffrywu28 we have tested at our end and we can successfully add the queries to hunt, please ensure that the resource you are using or the query you are trying to add has the correct api-version that is expected ("2022-11-01-preview", "2023-05-01-preview" etc.), thanks!

**Comment by v-vdixit** [comment]
Gentle Reminder: We are waiting for your response on this issue. If you still need to keep this issue active, please respond on it in the next 2 days. If we don't receive response, we will be closing this issue as per our standard procedures, thanks!

**Comment by v-vdixit** [comment]
Since we have not received a response in the last 5 days, we are closing your issue as per our standard operating procedures. If you still need support for this issue, feel free to re-open at any time. Thank you for your co-operation.
