### ISSUE TITLE
User login from different countries within 3 hours (Uses Authentication Normalization) should include the countries that trigger this alert in the events details.

### ISSUE THREAD

**Issue by rweirtbg** [Azure/Azure-Sentinel#8329]
User login from different countries within 3 hours (Uses Authentication Normalization) should include the countries that trigger this alert in the events details.

https://github.com/Azure/Azure-Sentinel/blob/master/Detections/ASimAuthentication/imAuthSigninsMultipleCountries.yaml

**Describe the solution you'd like**

Change the following :

Current:
```
query: |
  let timeframe = ago(3h);
  let threshold = 2;
  imAuthentication
  | where TimeGenerated > timeframe
  | where EventType=='Logon' and EventResult=='Success'
  | where isnotempty(SrcGeoCountry)
  | summarize StartTime = min(TimeGenerated), EndTime = max(TimeGenerated), Vendors=make_set(EventVendor), Products=make_set(EventProduct)
    , NumOfCountries = dcount(SrcGeoCountry)
    by TargetUserId, TargetUsername, TargetUserType
  | where NumOfCountries >= threshold
  | extend timestamp = StartTime, AccountCustomEntity = TargetUsername
```

Proposed:

Add: `Countries =  make_set(SrcGeoCountry)`

Inline:
```
query: |
let timeframe = ago(3h);
let threshold = 2;
imAuthentication
| where TimeGenerated > timeframe
| where EventType == 'Logon' and EventResult == 'Success'
| where isnotempty(SrcGeoCountry)
| summarize
    StartTime = min(TimeGenerated),
    EndTime = max(TimeGenerated),
    Vendors=make_set(EventVendor),
    Products=make_set(EventProduct),
    NumOfCountries = dcount(SrcGeoCountry),
    Countries =  make_set(SrcGeoCountry)
    by TargetUserId, TargetUsername, TargetUserType
| where NumOfCountries >= threshold
| extend timestamp = StartTime, AccountCustomEntity = TargetUsername
```

**Comment by v-rbajaj** [comment]
Hi @azurekid, thanks for raising the PR for this, team is reviewing the PR.

**Comment by v-vdixit** [comment]
Hi @rweirtbg the related PR is under review, the changes will be updated once PR is merged, thanks!

**Comment by v-vdixit** [comment]
Hi @rweirtbg  the related PR is under review, the changes will be updated once PR is merged, thanks!

**Comment by v-rbajaj** [comment]
Thanks @azurekid for keeping us updated.

**Comment by v-vdixit** [comment]
Hi @rweirtbg the related PR is still under review, the changes will be updated once PR is merged, thanks!

**Comment by azurekid** [comment]
> @azurekid can we get this alert fine tuned to only alert on unique users within 7days range. 

Sure, I can work on that 👍
