### ISSUE TITLE
Retrieve process tree by KQL query

### ISSUE THREAD

**Issue by gilb77** [Azure/Azure-Sentinel#8331]
I would like to request a new feature in KQL that allows users to get a process tree based on the process leaf details we provide from the  DeviceProcessEvents table. 

Currently, we have access to individual process events with detail of his parents, but it would be extremely valuable to receive a full tree of the processes with the hierarchy of the ancestors processes that create the leaf process according to the relationships between parent and child processes.

For example: 
we have the following process three creation: 

process A(742) -> process B(693) ->    process C (533) ->   process D(848)
          

We have the detail of process D with PID 848 that was Initiated by process C with PID 535, when I request from the table DeviceProcessEvents detail about process D i will receive only detail about the direct parent C and i can't conclude from these details who the other ancestors of the this process, in this example process A and process B.  

A new query that returns the full tree path from process A to process D  according to input process D will help to investigate the process events more easily by one query.

**Comment by v-rbajaj** [comment]
Hi @gilb77, thanks for flagging this issue. We are looking into it and will get back to you soon on this.

**Comment by v-vdixit** [comment]
Hi @gilb77 we have reached out to the concerned team with your feature request, will update you once we hear back from them, thanks!

**Comment by v-vdixit** [comment]
Hi @gilb77 we are waiting to hear back from the concerned team, will update you once we hear back from them, thanks!

**Comment by v-vdixit** [comment]
HI @gilb77 we are still waiting to hear back from the concerned team, thanks!

**Comment by v-vdixit** [comment]
Hi @gilb77 we are waiting to hear back from the concerned team, will update you once we hear back from them, thanks!

**Comment by v-vdixit** [comment]
HI @gilb77  we are still waiting to hear back from the concerned team, thanks!

**Comment by v-vdixit** [comment]
Hi @gilb77 we are waiting to hear back from concerned team, thanks!

**Comment by v-vdixit** [comment]
HI @gilb77 we are still waiting to hear back from the concerned team, thanks!

**Comment by v-sudkharat** [comment]
Hi @gilb77, we are still waiting to hear back from concern team. Thanks!

**Comment by v-sudkharat** [comment]
Hi @gilb77, we have taken a note of this enhancement and will be tracking it internally. Thus, closing this issue for now.
