### ISSUE TITLE
Duo Security Connector - Error 400 (invalid request parameters (maxtime))

### ISSUE THREAD

**Issue by technaholic** [Azure/Azure-Sentinel#8341]
**Describe the bug**
After setting up the Duo Security Connector, the function app errors out when running with the following :
```
Exception while executing function
 /Functions.AzureFunctionCiscoDuo ---> Microsoft.Azure.WebJobs.Script.Workers.Rpc.RpcException 
 /Result
 /Failure Exception
 /RuntimeError
 /Received 400 Invalid request parameters (maxtime) 

 /  
 '/azure-functions-host/workers/python/3.8/LINUX/X64/azure_functions_worker/dispatcher.py', line 479, in _handle__invocation_request     call_result = await self._loop.run_in_executor(   
 '/usr/local/lib/python3.8/concurrent/futures/thread.py', line 57, in run     result = self.fn(*self.args, **self.kwargs)   
 '/azure-functions-host/workers/python/3.8/LINUX/X64/azure_functions_worker/dispatcher.py', line 752, in _run_sync_func     return ExtensionManager.get_sync_invocation_wrapper(context,   
 '/azure-functions-host/workers/python/3.8/LINUX/X64/azure_functions_worker/extension.py', line 215, in _raw_invocation_wrapper     result = function(**args)   
 '/home/site/wwwroot/AzureFunctionCiscoDuo/main.py', line 55, in main     process_trust_monitor_events(admin_api, state_manager=state_manager, sentinel=sentinel)   
 '/home/site/wwwroot/AzureFunctionCiscoDuo/main.py', line 101, in process_trust_monitor_events     for event in admin_api.get_trust_monitor_events_iterator(mintime=mintime, maxtime=maxtime)
 /  
 '/home/site/wwwroot/.python_packages/lib/site-packages/duo_client/client.py', line 441, in json_cursor_api_call     (response, metadata) = self.parse_json_response_and_metadata(   
 '/home/site/wwwroot/.python_packages/lib/site-packages/duo_client/client.py', line 476, in parse_json_response_and_metadata     raise_error('Received %s %s (%s)' % (   
 '/home/site/wwwroot/.python_packages/lib/site-packages/duo_client/client.py', line 468, in raise_error     raise error    
```

In the function monitor, after clicking on an error invocation, the following is shown :
`Making trust_monitor logs request: mintime=1687357200000, maxtime=1687357203600000`

Comparing those parameter values to what Duo Admin API is wanting (they want 13 digit unix time stamps), I believe the error is that the maxtime is being calculated incorrectly as it is 16 digits long while the mintime is 13.

**To Reproduce**
1 : Install and setup Duo Connector in Sentinel
2 : Ensure its running
3 : Navigate into Duo Function App to the Monitor item and look at any invocation errors

**Expected behavior**
We expect to get Duo logs into Sentinel successfully

**Comment by technaholic** [comment]
You’re welcome and thanks!
Let me know how I can help!
-Paul

**Comment by v-vdixit** [comment]
Hi @technaholic we are working on updates in function app code, will update you by the end of this week, thanks!

**Comment by technaholic** [comment]
Awesome!  Thanks!

**Comment by v-vdixit** [comment]
Hi @technaholic can you please use this https://github.com/Azure/Azure-Sentinel/raw/v-sukharat/testingissueciscoduo/Solutions/CiscoDuoSecurity/Data%20Connectors/CiscoDuoSecurity_func.zip link in WEBSITE_RUN_FROM_PACKAGE and check if the error is resolved, thanks!

**Comment by technaholic** [comment]
Nevermind.  I think I found it in the function app.  Give me a few and I'll
let you know

**Comment by technaholic** [comment]
Looks like it works now!  We are getting logs in with no errors!
Thanks!
Once you commit this what would I need to do to go back to normal and make
sure we don't have any special setup?

**Comment by v-vdixit** [comment]
Hi @technaholic I hope the change that we made in file is working for you, once we make it live you have to simply deploy the function app, no special setup required, thanks!
