### ISSUE TITLE
"VirusInfo" field not parsed in O365 connector, OfficeActivity table for FileMalwareDetected events

### ISSUE THREAD

**Issue by girlbossceo** [Azure/Azure-Sentinel#8355]
Hi Azure Sentinel team, we have noticed in a couple Azure Sentinel environments that a specific field called "VirusInfo" does not appear to be parsed in your Office 365 connector for `FileMalwareDetected` events in the `OfficeActivity` table.

For context, [Microsoft 365 Defender customers can enable Safe Attachments](https://learn.microsoft.com/en-us/microsoft-365/security/office-365-security/safe-attachments-for-spo-odfb-teams-configure?view=o365-worldwide) and enable Office ATP to alert on potential malware stored in OneDrive, Sharepoint, Teams chats, etc. The event in this is `FileMalwareDetected`. The logs are JSON formatted and contain fields such as the object ID (usually the full Sharepoint link to the malicious file), client IP, user agent (also usually the malware scanner agent like `MS Scanner ATP`), file name, etc. One of those fields is the signature that the malware engine detected which is in a field called `VirusInfo`, just like a typical anti-virus engine would tell you the signature it detected.

Take the following KQL query for example:

```
OfficeActivity // table
| where Operation == "FileMalwareDetected"
```

Upon a FileMalwareDetected event ([list of all audit log activities](https://learn.microsoft.com/en-us/microsoft-365/compliance/audit-log-activities?view=o365-worldwide)) in the OfficeActivity table, we see various fields parsed out that are same/similar in other SIEMs like QRadar and Splunk, however we do not see `VirusInfo` which is parsed out like normal in these other SIEMs in this table. E.g. `"VirusInfo": "DOS/EICAR_Test_File"`

There also does not appear to be any form of raw JSON payload that we could extract the field from, so the fields that we are given from the connector are what we have even though `VirusInfo` definitely exists.

[Microsoft Corporation is the maintainer of the Office 365 connector](https://learn.microsoft.com/en-us/azure/sentinel/data-connectors/office-365) so we are reaching out to see if this is a bug or a parsing issue with your connector here.

**Comment by v-rbajaj** [comment]
Hi @girlbossceo, thanks for flagging this, we are looking into it and will provide an update soon.

**Comment by v-vdixit** [comment]
Hi @girlbossceo can you provide us an instance of query you ran in Logs and where you cannot find 'VirusInfo' included in results, as expected, this will help us better in understanding root cause of error, thanks!

**Comment by girlbossceo** [comment]
@v-vdixit Viewing all the fields with:

```
OfficeActivity // table
| where Operation == "FileMalwareDetected"
```

Should show you

**Comment by v-vdixit** [comment]
Hi @girlbossceo thanks for the update, we are checking on the details, will update you by end of next week.

**Comment by v-vdixit** [comment]
Hi @girlbossceo we are working on this error and will go through the documentation, in order to come up with an appropriate resolution we would conduct proper research as this will take some time, we will be able to provide you an update by Friday, 21st July 2023, thanks for your patience and understanding.

**Comment by v-vdixit** [comment]
Hi @girlbossceo we are still looking into this issue, will update by 21st July 2023, thanks!

**Comment by v-vdixit** [comment]
Hi @girlbossceo we have reached out to the concerned team for the issue, we will update you once we hear back from them, thanks!

**Comment by v-vdixit** [comment]
Hi @girlbossceo we are investigating into this, will update you by Thursday 26th July 2023, thanks!

**Comment by v-amolpatil** [comment]
Hi @girlbossceo we are still investigating into this, will update you by 28th July 2023, thanks!

**Comment by v-muuppugund** [comment]
Hi @girlbossceo we are still investigating into this, will update you by 02Aug 2023, thanks!

**Comment by v-muuppugund** [comment]
Hi @girlbossceo, we are still investigating into this, we need some time to work on this issue, will share an update once we started on it,Thanks.
