### ISSUE TITLE
Successful logon from IP and failure from a different IP - missing code line

### ISSUE THREAD

**Issue by bittib010** [Azure/Azure-Sentinel#8362]
**Describe the bug**
The rule name as title states are very noisy in my portal. It seems to be triggering on failed ip and success ip where they actually are the same as well. This is not what the rule is described to do. I therefore added a simple line to avoid this: 
```
| where SuccessIPAddress != FailedIPAddress
```

Complete rule: 
```
let logonDiff = 10m;
let aadFunc = (tableName:string){
table(tableName)
| where ResultType == "0"
| where AppDisplayName !in ("Office 365 Exchange Online", "Skype for Business Online") // To remove false-positives, add more Apps to this array
| project SuccessLogonTime = TimeGenerated, UserPrincipalName, SuccessIPAddress = IPAddress, AppDisplayName, SuccessIPBlock = strcat(split(IPAddress, ".")[0], ".", split(IPAddress, ".")[1]), Type
| join kind= inner (
    table(tableName)
    | where ResultType !in ("0", "50140")
    | where ResultDescription !~ "Other"
    | where AppDisplayName !in ("Office 365 Exchange Online", "Skype for Business Online") // To remove false-positives, add more Apps to this array
    | project FailedLogonTime = TimeGenerated, UserPrincipalName, FailedIPAddress = IPAddress, AppDisplayName, ResultType, ResultDescription, Type
) on UserPrincipalName, AppDisplayName
| where SuccessLogonTime < FailedLogonTime and FailedLogonTime - SuccessLogonTime <= logonDiff and FailedIPAddress !startswith SuccessIPBlock
| summarize FailedLogonTime = max(FailedLogonTime), SuccessLogonTime = max(SuccessLogonTime) by UserPrincipalName, SuccessIPAddress, AppDisplayName, FailedIPAddress, ResultType, ResultDescription, Type
| extend timestamp = SuccessLogonTime
};
let aadSignin = aadFunc("SigninLogs");
let aadNonInt = aadFunc("AADNonInteractiveUserSignInLogs");
union isfuzzy=true aadSignin, aadNonInt
| extend Name = tostring(split(UserPrincipalName,'@',0)[0]), UPNSuffix = tostring(split(UserPrincipalName,'@',1)[0])
| where SuccessIPAddress != FailedIPAddress
```

**Expected behavior**
Should avoid triggering on incidents where the failure and the successfull login are from the same IP, rather when a successfull trigger happens and is followed by a failed IP within 10 minutes on the same app.

**Comment by best-geek** [comment]
Hi @bittib010, 

Was this IPV6 by any chance? We have seen this with IPV6 because `SuccessIPBlock ` relies on a string split, using a period as a delimiter. IPV6 addresses obviously don't have this and are separated by colons instead. 

Other than your method excluding if it's an exact match, you can also introduce the same logic by chunking the first part of the IPV6 address into your choice. I have gone for the first few prefixes of an IPv6 address by doing the following:

Take the `SuccessIPBlock` out of the project statement and put it in an extend. This is done right at the top of the function. 

```
table(tableName) 
| where ResultType == "0" 
| where AppDisplayName !in ("Office 365 Exchange Online", "Skype for Business Online")
| extend  SuccessIPBlock = strcat(split(IPAddress, ".")[0], ".", split(IPAddress, ".")[1])
| extend SuccessIPBlock = iff(IPAddress contains ":", strcat(split(IPAddress, ":")[0], ":", split(IPAddress, ":")[1] , ":", split(IPAddress, ":")[2], ":", split(IPAddress, ":")[3]), SuccessIPBlock) // take first 4 blocks of IPV6
| project SuccessLogonTime = TimeGenerated, UserPrincipalName, SuccessIPAddress = IPAddress, AppDisplayName, Type, SuccessIPBlock
```

**Comment by bittib010** [comment]
It seems like IPv6 is the reason behind it, yes. In combination this seem to work, in theory at least. I also adjusted the ```project``` in your snippet to fit the rest of the code and then ran it. It ran for more than 7 minutes before i gave up. I havent dug too deep into why this would not work. Any idea?

Do we have to look at ip blocks? The only thing we are looking for is difference in failed and success ip, right?

**Comment by v-vdixit** [comment]
Hi @bittib010 and @best-geek thanks for highlighting these issues, we are working with the team on tracing error cause will update you shortly.

**Comment by v-vdixit** [comment]
Hi @bittib010 Hi we have received a suggestion that we should compare first two parts of IPv6 also and not the entire IP, can you please check and confirm if that works as a resolution for you, thanks!

**Comment by best-geek** [comment]
Hi @bittib010 , for security reasons, I would suggest comparing the first e sections of an IPv6 at minimum as this will be the site prefix. More information can be found [here](https://docs.oracle.com/cd/E18752_01/html/816-4554/ipv6-overview-10.html)

**Comment by v-vdixit** [comment]
Hi @best-geek  thanks for your updates. @bittib010 can you please confirm if this comparison resolves your issue, thanks!

**Comment by bittib010** [comment]
Yes, in combination with the last line of code in my first message i got the most accurate data response. I also flet the query ran pretty slow. Im not sure how to proceed further. Any suggestions?

**Comment by v-vdixit** [comment]
Hi @bittib010 the query is running without any delay at our end, could you check once with latest version of solution and confirm, thanks!

**Comment by v-vdixit** [comment]
Gentle Reminder: We are waiting for your response on this issue. If you still need to keep this issue active, please respond on it in the next 2 days. If we don't receive response, we will be closing this issue as per our standard procedures, thanks!

**Comment by v-vdixit** [comment]
Since we have not received a response in the last 5 days, we are closing your issue as per our standard operating procedures. If you still need support for this issue, feel free to re-open at any time. Thank you for your co-operation

**Comment by bittib010** [comment]
I've been on vacation - sorry for the late reply! This looks good! Good job, and thanks!

**Comment by best-geek** [comment]
Hi @v-vdixit , it looks like you got a reply on this issue. Could you confirm if there's still an intention to resolve this issue? We were hoping that this could be fixed by MS pushing a template so it can be updated in a scalable across a customer base and new deployments do not have this issue.

**Comment by best-geek** [comment]
Hi @v-vdixit , 

Is there any way to re-open this issue? I had initially replied before it was closed that the fix looks good. We still haven't seen this pushed to the template. 

Thanks!
