### ISSUE TITLE
Possible AiTM Phishing Attempt Against Azure AD - column failing

### ISSUE THREAD

**Issue by bittib010** [Azure/Azure-Sentinel#8367]
**Describe the bug**
[This rule](https://github.com/Azure/Azure-Sentinel/blob/82c0cb41306eb5e72d3fdad89fa948e28470575a/Solutions/SecurityThreatEssentialSolution/Analytic%20Rules/PossibleAiTMPhishingAttemptAgainstAAD.yaml) has a fault project-reorder column that does not resolve: Dst. 

Not sure if "Dvc" is the aimed for column to use, or if there has been some backend changes that makes this rule trigger.

**Comment by v-vdixit** [comment]
Hi @bittib010 we are working on resolution, will publish the updated changes shortly, thanks!

**Comment by v-vdixit** [comment]
Hi @bittib010 we are working on this solution packaging with latest updates in our packaging tool, the changes will be updated shortly, thanks!

**Comment by v-vdixit** [comment]
Hi @bittib010 we are working on this solution packaging with latest updates in our packaging tool, the changes will be updated shortly, thanks!
