### ISSUE TITLE
DNS workbook not working when the DnsEvents table gets large.

### ISSUE THREAD

**Issue by holi1-ops** [Azure/Azure-Sentinel#8376]
**Describe the bug**
When IP address is set to All, all the sub tabs would show error “couldn’t connect to server” even if we filter time range to a few hours. 
 
![image](https://github.com/Azure/Azure-Sentinel/assets/62872235/b5a64b88-c886-4f91-aa95-005de2a5eec4)

**To Reproduce**
1. Go to 'Sentinel Workbooks'
2. Click on 'DNS'
3. Select "All" (should be default) for the "IpAddress" filter with a relatively large DnsEvents table in the workspace

**Expected behavior**
We should be able to see the charts showing up in the sub panels

**Screenshots**
From the captured browser trace we can see the server returned payload too large –
![image](https://github.com/Azure/Azure-Sentinel/assets/62872235/30ab6524-99db-4d0b-a624-b7ec99c1ea86)
And we can see an incredibly huge query(about 1,690,000 characters) being sent in the post body. 
![image](https://github.com/Azure/Azure-Sentinel/assets/62872235/f71622a4-9708-49e6-ae1d-6dc1a931a350)

The IP Address filter gets it’s value sets by below query –
DnsEvents
| extend IpAddresses = iif(IPAddresses=="","empty" ,IPAddresses)
| summarize by IpAddresses
| sort by IpAddresses desc

And in the sub tabs, below query are being used –
DnsEvents
| extend IPAddresses = iif(IPAddresses=="", "empty", IPAddresses)
**| where "*" in ({IpAddresses}) or IPAddresses in ({IpAddresses})**
| summarize Events= count() by bin_at(TimeGenerated, 1h, now()), SubType

When “All” is selected, the **bold line** would inject all the IP addresses from the DnsEvents table into the query body and make the query unacceptable large.

**Comment by v-rbajaj** [comment]
Hi @holi1-ops, can you please specify the name of the workbook or maybe link that workbook here, this will help us understand which specific workbook you are facing this issue. Thanks

**Comment by holi1-ops** [comment]
> Hi @holi1-ops, can you please specify the name of the workbook or maybe link that workbook here, this will help us understand which specific workbook you are facing this issue. Thanks

This is the link to the workbook https://github.com/Azure/Azure-Sentinel/blob/master/Workbooks/Dns.json

**Comment by v-rbajaj** [comment]
Hi @holi1-ops, we have made some modifications to the query please try this attached template and let us know if that solves the issue. 

Just change the format to .json from .txt (I couldn't attach .json so I changed it to .txt) in case you plan import or do something with it
[DNS.txt](https://github.com/Azure/Azure-Sentinel/files/11955768/DNS.txt)

**Comment by holi1-ops** [comment]
> Hi @holi1-ops, we have made some modifications to the query please try this attached template and let us know if that solves the issue.
> 
> Just change the format to .json from .txt (I couldn't attach .json so I changed it to .txt) in case you plan import or do something with it [DNS.txt](https://github.com/Azure/Azure-Sentinel/files/11955768/DNS.txt)

By reviewing the change made, it seems only difference made was to change how the IpAddresses parameter was defined. But it's still being saved as an string array. 
When DnsEvents table is huge and has significant number of unique IP addresses, the resulting IpAddresses string in the query could still become very long. 
The problem should be in the "in" operation used in the clause, and we might consider to store the IP address in a separate table or data structure. 
| where "*" in ({IpAddresses}) or IPAddresses in ({IpAddresses})

From usage perspective, why would we want to filter for some IP addresses from DNS logs? We don't even know what those IP address stands for.

**Comment by v-rbajaj** [comment]
Hi @holi1-ops, PFA updated workbook with some more changes. 
[DNS.txt](https://github.com/Azure/Azure-Sentinel/files/11965608/DNS.txt)

**Comment by v-vdixit** [comment]
Hi @holi1-ops we are waiting for your update, thanks!

**Comment by v-vdixit** [comment]
Gentle Reminder: We are waiting for your response on this issue. If you still need to keep this issue active, please respond on it in the next 2 days. If we don't receive response, we will be closing this issue as per our standard procedures, thanks!

**Comment by v-rbajaj** [comment]
Since we have not received a response in the last 5 days, we are closing your issue https://github.com/Azure/Azure-Sentinel/issues/8376 as per our standard operating procedures. If you still need support for this issue, feel free to re-open at any time. Thank you for your co-operation.
