### ISSUE TITLE
[FileName typo] IPentity_SigninLogs.yaml 

### ISSUE THREAD

**Issue by FormindMPO** [Azure/Azure-Sentinel#8381]
**Describe the bug**
File [IPentity_SigninLogs.yaml](https://github.com/Azure/Azure-Sentinel/blob/master/Solutions/Threat%20Intelligence/Analytic%20Rules/IPentity_SigninLogs.yaml) under `Solutions/Threat Intelligence/Analytic Rules/` as a typography in filename.

**To Reproduce**
IP`e`ntity_SigninLogs.yaml -> IP`E`ntity_SigninLogs.yaml (Capital E)

**Expected behavior**
filename : *IP**E**ntity_SigninLogs.yaml* (Capital E)

**Screenshots**
/

**Desktop (please complete the following information):**
/

**Smartphone (please complete the following information):**
/

**Additional context**
/

**Comment by v-rbajaj** [comment]
Hi @FormindMPO, thanks for flagging this issue, we are looking into it and will get back to you soon.
