### ISSUE TITLE
Exception thrown while ingesting Atlassian JIRA Audit logs using the connector

### ISSUE THREAD

**Issue by MKaleem92** [Azure/Azure-Sentinel#8385]
I am trying to connect the Atlassian  JIRA Data Connectors with Sentinel. However, the connector is failing to connect even though deployment is successful. I have found the following error from the exceptions table for the JIRA function app which is deployed with the data connector:

Result: Failure Exception: TypeError: '>' not supported between instances of 'NoneType' and 'int' Stack: File "/azure-functions-host/workers/python/3.8/LINUX/X64/azure_functions_worker/dispatcher.py", line 406, in _handle__invocation_request call_result = await self._loop.run_in_executor( File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run result = self.fn(*self.args, **self.kwargs) File "/azure-functions-host/workers/python/3.8/LINUX/X64/azure_functions_worker/dispatcher.py", line 648, in _run_sync_func return ExtensionManager.get_sync_invocation_wrapper(context, File "/azure-functions-host/workers/python/3.8/LINUX/X64/azure_functions_worker/extension.py", line 215, in _raw_invocation_wrapper result = function(**args) File "/home/site/wwwroot/JiraAuditAPISentinelConnector/__init__.py", line 129, in main get_result(generate_date()) File "/home/site/wwwroot/JiraAuditAPISentinelConnector/__init__.py", line 85, in get_result if element_count > 0:

**Comment by v-vdixit** [comment]
Hi @MKaleem92 we have already updated the function app for this connector to fix this exception, please ensure you are using the latest zip file for Website run from package - [JiraAuditAPISentinelConnector](https://github.com/Azure/Azure-Sentinel/blob/master/Solutions/AtlassianJiraAudit/Data%20Connectors/JiraAuditAPISentinelConn.zip), please let us know if you are facing any other issue, thanks!

**Comment by v-vdixit** [comment]
Gentle Reminder: We are waiting for your response on this issue. If you still need to keep this issue active, please respond on it in the next 2 days. If we don't receive response, we will be closing this issue as per our standard procedures, thanks!

**Comment by MKaleem92** [comment]
This issue is now fixed. Host name was incorrect. Thanks.
