### ISSUE TITLE
Wrong logic in Analytics rule "Suspicious Login from deleted guest account"

### ISSUE THREAD

**Issue by Aeven-elnr** [Azure/Azure-Sentinel#8386]
**Describe the bug**
The analytics rule "Suspicious Login from deleted guest account" looks for successful logons after an account has been deleted. However, the logic in the query will trigger when the timestamp of the delete event is "bigger" than the timestamp of the login event. 

**To Reproduce**
1. Go to Sentinel> Analytics
2. Search for "Suspicious Login from deleted guest account"
3. Scroll down to query.
4. See error on line 21 `| where Delete_TimeGenerated > SigninLogs_TimeGenerated`

**Expected behavior**
`| where Delete_TimeGenerated < SigninLogs_TimeGenerated`

**Screenshots**
Example from actual alert thrown. Delete event happened after successful login event. Delete time was at 6/27/2023 whereas login was at 6/25/2023.
![image](https://github.com/Azure/Azure-Sentinel/assets/138006751/650a002c-db62-4352-8321-c1b02c123612)

**Desktop (please complete the following information):**
N/A

**Smartphone (please complete the following information):**
N/A

**Additional context**
We have currently just updated the alert in our own environment.

**Comment by v-vdixit** [comment]
Hi @Aeven-elnr  in this query we are trying to get that just before deletion of the account, was there any successful sign-ins and what were the associated activities, and since sign-ins are not possible from deleted accounts, deleted account signin timestamp can never be smaller than signin timestamp. I hope this resolves your issue, thanks!

**Comment by Aeven-elnr** [comment]
Hello @v-vdixit , thank you for the quick answer! A login before an account is deleted is in itself not suspicious. Can you elaborate as to what suspicious activity this alert is attempting to detect? Is it that someone logs on within a day of the account being deleted? If so, why is this suspicious?

**Comment by v-vdixit** [comment]
> Hello @v-vdixit, so the alert is triggered when the deleted account, has logged in (before deletion) and created 2 new user accounts? Can you help me understand where in the query, this lookup is done? I only see that is looks for "Delete user" operation and then looks for signinlogs for this account.

Hi @Aeven-elnr this is just an instance of use case of this query, basic working of this query suggests that it is looking for suspicious activity from any of the accounts right before they were deleted.

**Comment by Aeven-elnr** [comment]
Hey @v-vdixit, thanks for the clarification. I have changed the alert back to what it was before.

**Comment by tarun2400** [comment]
Hello, 

I came across a similar issue with this alert. As mentioned above, I believe the KQL logic is correct however, the title of the alert is misleading. I would suggest something like External Guest User Deleted After Recent Login
