### ISSUE TITLE
Unusual-Mass-Downgrade-AIP-Label simulation does not work

### ISSUE THREAD

**Issue by mrbrutka** [Azure/Azure-Sentinel#8395]
**Describe the bug**
I understand that the code has been maintained few years ago, but this is the single simulation which I am interested.  

**To Reproduce**
The script has ran successfully several times: 

![image](https://github.com/Azure/Azure-Sentinel/assets/96731072/df99ccf8-41a4-4e47-a166-84d7a0c2c6d9)

waited 24hours both times

**Expected behavior**
As per documentation a table should be created. 
https://github.com/Azure/Azure-Sentinel/tree/master/Tools/Simulators/Anomalies/Unusual-Mass-Downgrade-AIP-Label

![image](https://github.com/Azure/Azure-Sentinel/assets/96731072/10c8029d-2f88-4020-a2c7-0705c8b696ac)

**Screenshots**
The Anomaly is turned on: 

![image](https://github.com/Azure/Azure-Sentinel/assets/96731072/ce0e3023-cad1-4164-b73e-1aa444bf28d4)

Please explain me if I am doing something wrong or I should just to skip this simulator as it is EOL?

Thanks in advance,

Balys

**Comment by v-rbajaj** [comment]
@mrbrutka, Thanks for flagging this, we will check on this and provide an update soon here.

**Comment by v-rbajaj** [comment]
Hi @mrbrutka, AIP integration to Log Analytics has been sunset and does no longer stream data to the InformationProtectionLogs_CL table. 
AIP logs can be found in the MicrosoftPurviewInformationProtection standard table, which collects the audit logs from the compliance center using the Office Management API.  

I hope this answers your question.

**Comment by v-rbajaj** [comment]
Hi @mrbrutka, Gentle Reminder: We are awaiting for your response on this issue. If you still need to keep this issue active please respond on it in the next 2 days . If we don't receive response, we will be close this issue.

**Comment by Rishik999** [comment]
Hi @mrbrutka, thanks for sharing this information, we will get back to you

**Comment by v-rbajaj** [comment]
Hi @mrbrutka, thanks for sharing this information, we will get back to you

**Comment by v-rbajaj** [comment]
Hi @mrbrutka, we have reached out to the concerned team, waiting for response from them.

**Comment by v-vdixit** [comment]
Hi @mrbrutka we are still waiting to hear back from the concerned team, thanks!

**Comment by v-rbajaj** [comment]
Hi @mrbrutka,
We can only refer to the table. 
This is a standard table which will be presented in the list shown in the screenshot attached when there is data landing in the table. All tables can be listed below by marking the “Show tables with no data” toggle to be enabled (screenshot below)
![download](https://github.com/Azure/Azure-Sentinel/assets/120547590/f8d16b1c-2829-4352-aafb-c6d44a4eea72)

All data that had been streaming to the previous CL table – still exist there, dependent on the retention time for the customer.   

I hope this answer your question

**Comment by v-rbajaj** [comment]
Since we have not received a response in the last 5 days, we are closing your issue https://github.com/Azure/Azure-Sentinel/issues/8395 as per our standard operating procedures. If you still need support for this issue, feel free to re-open at any time. Thank you for your co-operation.
