### ISSUE TITLE
Wrong logic in the analytic rule: Sign-in attempts by IP via disabled accounts

### ISSUE THREAD

**Issue by OmarEfat** [Azure/Azure-Sentinel#8409]
**Describe the bug**
This rule produces false positive. If the user tried to log in to a disabled account that has been subsequently reactivated and then tries to log in again, the rule will be still triggered without considering that they are both the same account.

**To Reproduce**
This is the rule -  [SigninAttemptsByIPviaDisabledAccounts.yaml](https://github.com/Azure/Azure-Sentinel/blob/master/Solutions/Azure%20Active%20Directory/Analytic%20Rules/SigninAttemptsByIPviaDisabledAccounts.yaml)

**Expected behavior**
If the user tries to log in to a disabled account and that account got reactivated, a subsequent attempt by the same user should not trigger the rule.

**Comment by v-rbajaj** [comment]
Hi @OmarEfat, Thanks for flagging this, we will look into this and will back to you on this.

**Comment by v-vdixit** [comment]
Hi @OmarEfat we have reached out to the concerned team with your feature request, will update you once we hear back from them, thanks!

**Comment by v-vdixit** [comment]
@OmarEfat We are still waiting to hear back from the concerned team, thanks!

**Comment by v-vdixit** [comment]
Hi @OmarEfat we haven't heard back from the concerned team yet, will update you once they respond, thanks!

**Comment by v-vdixit** [comment]
Hi @OmarEfat we have got suggestion from team that as this issue does not occur very often, we need confirmation from query author before making this change, we will update you once we get confirmation from the query author, thanks!

**Comment by v-vdixit** [comment]
Hi @OmarEfat we are still waiting to hear back from the query author, thanks!

**Comment by v-vdixit** [comment]
Hi @OmarEfat we are still waiting to hear back from the query author, thanks!

**Comment by v-sudkharat** [comment]
Hi @OmarEfat we are still waiting to hear back from the query author, thanks!

**Comment by v-sudkharat** [comment]
Hi @OmarEfat, we are still waiting to hear back from the query author, thanks!

**Comment by v-sudkharat** [comment]
Hi @OmarEfat, we are still waiting to hear back from the query author, thanks!

**Comment by v-sudkharat** [comment]
Hi @OmarEfat, we are still waiting to hear back from the query author, thanks!

**Comment by v-sudkharat** [comment]
Hello @OmarEfat, we receive update from query author with modification in "analytic rule". We are working on this and will provide next update by 09-08-2023. Thanks!

**Comment by v-sudkharat** [comment]
Hi @OmarEfat, the query author's PR has been merged into the master. We are working on adding changes into the solution, and we'll let you know when it goes live. Thanks!
