### ISSUE TITLE
ARM template/script for Sentinel Solution Deployment failing

### ISSUE THREAD

**Issue by ling-tx** [Azure/Azure-Sentinel#8478]
**Describe the bug**
Can't deploy playbooks successfully

**To Reproduce**
1. Go to 'https://github.com/Azure/Azure-Sentinel/blob/master/Tools/Create-Azure-Sentinel-Solution/V3/'
2. run command './createSolutionV3.ps1'
3. After the tool generates `mainTemplate.json`, validate `mainTemplate.json` by deploying the template in portal.

**Expected behavior**
It should request me to input some necessary parameter of playbooks and deploy 2 playbooks on Microsoft Sentinel

**Screenshots**
If I use `https://github.com/Azure/Azure-Sentinel/blob/master/Tools/Create-Azure-Sentinel-Solution/createSolution.ps1`, the `mainTemplate.json` is like below, there are some parameters of playbooks
![Screenshot 2023-06-27 at 10 19 25 AM](https://github.com/Azure/Azure-Sentinel/assets/77289312/528062b3-26c0-41b5-a27e-038942d43428)
But if I use `https://github.com/Azure/Azure-Sentinel/blob/master/Tools/Create-Azure-Sentinel-Solution/V3/createSolutionV3.ps1`, the `mainTemplate.json` is like below
![Screenshot 2023-06-27 at 10 20 34 AM](https://github.com/Azure/Azure-Sentinel/assets/77289312/83a91290-b474-4a09-a77f-942e36ece38d)
I am using the same json files of playbook but v1/v3 tools generate totally different solutions

**Comment by v-vdixit** [comment]
Hi @ling-tx thanks for raising PR, we will review this and update you, thanks!

**Comment by v-vdixit** [comment]
Hi @ling-tx we are reviewing the PR once the PR is merged the changes will be published, thanks

**Comment by v-vdixit** [comment]
Hi @ling-tx we are still reviewing the PR once the PR is merged the changes will be published, thanks

**Comment by v-amolpatil** [comment]
As per comment in PR 8328 by v-prasadboke. A call has been scheduled to discuss on pending things.

**Comment by v-rbajaj** [comment]
Hi @ling-tx, we are still reviewing the PR, will let you know once there is an update.

**Comment by v-rbajaj** [comment]
Hi @ling-tx, we are still reviewing the PR, will let you know once there is an update.

**Comment by v-rbajaj** [comment]
We are reviewing the PR, will let you know once there is an update.

**Comment by v-rbajaj** [comment]
Gentle Reminder: We are awaiting for your response on this issue. If you still need to keep this issue active please respond on it in the next 2 days . If we don't receive response, we will be close this issue.

**Comment by v-rbajaj** [comment]
Hi @ling-tx, please respond on the PR which is under review. 
Feel free to re open this issue, if you have further question.
