### ISSUE TITLE
Cloudflare HTTP Logs - Function App failing to process http log file 

### ISSUE THREAD

**Issue by paulo-lana** [Azure/Azure-Sentinel#8490]
Cloudflare Connector
https://github.com/Azure/Azure-Sentinel/tree/master/Solutions/Cloudflare

**Describe the bug**
Occasional exported log file from Cloudflare to Azure Storage Account is not processed by the Function App and ingested on Sentinel, causing ingestion delay until the file is manually deleted.

The deleted from Storage Account log file is readable and presents no clear difference from other files that were ingested normally.

![AzureFunctionCloudflare - Error](https://github.com/Azure/Azure-Sentinel/assets/92587429/e16c8d38-2eaa-476b-bc9e-fec787f06e89)

**To Reproduce**
We haven't yet been able to reproduce the issue. We were not able to identify what information on the log file is responsible for breaking the ingestion function. 

**Expected behavior**
The Function App being able to process and ingest all Cloudflare http log files that arrive on the Storage Account.

**Additional context**
Function App error, that persists until the corrupted log file is deleted.

> Result: Failure Exception: HttpResponseError: Download stream interrupted. Stack: File "/azure-functions-host/workers/python/3.8/LINUX/X64/azure_functions_worker/dispatcher.py", line 475, in _handle__invocation_request call_result = await self._run_async_func( File "/azure-functions-host/workers/python/3.8/LINUX/X64/azure_functions_worker/dispatcher.py", line 758, in _run_async_func return await ExtensionManager.get_async_invocation_wrapper( File "/azure-functions-host/workers/python/3.8/LINUX/X64/azure_functions_worker/extension.py", line 147, in get_async_invocation_wrapper result = await function(**args) File "/home/site/wwwroot/AzureFunctionCloudflare/main.py", line 63, in main await asyncio.gather(*cors) File "/home/site/wwwroot/AzureFunctionCloudflare/main.py", line 111, in process_blob async for chunk in blob_cor.chunks(): File "/home/site/wwwroot/.python_packages/lib/site-packages/azure/storage/blob/aio/_download_async.py", line 151, in __anext__ self._current_content = await self._iter_downloader.yield_chunk(chunk) File "/home/site/wwwroot/.python_packages/lib/site-packages/azure/storage/blob/aio/_download_async.py", line 62, in yield_chunk return await self._download_chunk(chunk_start, chunk_end - 1) File "/home/site/wwwroot/.python_packages/lib/site-packages/azure/storage/blob/aio/_download_async.py", line 105, in _download_chunk chunk_data = await process_content(response, offset[0], offset[1], self.encryption_options) File "/home/site/wwwroot/.python_packages/lib/site-packages/azure/storage/blob/aio/_download_async.py", line 27, in process_content raise HttpResponseError(message="Download stream interrupted.", response=data.response, error=error)

Have any other customers experienced this scenario?

**Comment by paulo-lana** [comment]
> Hi @paulo-lana thanks for flagging this we are working on this, will update you shortly.

thank you @v-vdixit, let me know in case you need further information regarding this issue.

**Comment by v-vdixit** [comment]
Hi @paulo-lana have you run this function app at your end, if yes please share the execution logs file with us, thanks!

**Comment by v-vdixit** [comment]
Hi @paulo-lana the information and error you are getting after running the function app are execution logs, they will help us in tracing the error cause step by step, please add either screenshot or a zip file with execution logs, thanks!

**Comment by v-vdixit** [comment]
Since we have not received a response in the last 5 days, we are closing your issue as per our standard operating procedures. If you still need support for this issue, feel free to re-open at any time. Thank you for your co-operation
