### ISSUE TITLE
Role needed to install Sentinel Training Lab?  

### ISSUE THREAD

**Issue by mathurin68** [Azure/Azure-Sentinel#8491]
I have Contributor permissions in a subscription in our tenant, it let me install the resource group, the resource group LA, and then Sentinel. 

However, when I try to install the Microsoft Sentinel training lab it all seems to work except the 'ingestEvents' piece fails with 
'This request is not authorized to perform this operation.'  
![image](https://github.com/Azure/Azure-Sentinel/assets/5932961/a92519f1-928a-4503-ab02-6967efeaecd7)

Trying to connect 'Azure Activity' gave me a similar error and wouldn't let me complete it. 

I'm working toward the SC-200 and just trying to learn so hopefully someone can give me a clue what I'm doing wrong. 

Thanks!

**Comment by v-rbajaj** [comment]
Hi @mathurin68,
It seems like you have Contributor permissions in a subscription in your tenant, and you were able to install the resource group, the resource group LA, and then Sentinel. However, when you tried to install the Microsoft Sentinel training lab, the 'ingestEvents' piece failed with 'This request is not authorized to perform this operation.(https://github.com/MicrosoftDocs/azure-docs/blob/main/articles/lab-services/includes/lab-services-troubleshoot-not-authorized.md).

This error message indicates that you do not have the necessary permissions to perform the operation. You may need to assign the Lab Creator role at the resource group level to prevent this behavior (https://github.com/MicrosoftDocs/azure-docs/blob/main/articles/lab-services/includes/lab-services-troubleshoot-not-authorized.md).

Additionally, when you tried to connect 'Azure Activity', you received a similar error and were unable to complete it. It is possible that you do not have the necessary permissions to perform this operation as well.

To learn more about roles and permissions in Microsoft Sentinel, you can refer to the documentation on the topic (https://github.com/MicrosoftDocs/azure-docs/blob/main/articles/sentinel/roles.md).

I hope this helps! Let me know if you have any other questions.

**Comment by mathurin68** [comment]
Thanks @v-rbajaj for the answer... is that in labs.azure.com ? I'm not sure the instructions say I just need permissions to create a RG which I have and I did.
