### ISSUE TITLE
Dynatrace data connectors paging not working as expected

### ISSUE THREAD

**Issue by keyoke** [Azure/Azure-Sentinel#8504]
**Describe the bug**
Dynatrace solution data connector paging does not seem to be working. Only the first page of events is ingested. 

**To Reproduce**
1. Connect Dynatrace Runtime Vulnerabilities connector to a Dynatrace tenant with more than 10 reported vulnerabilities.
2. Wait till data ingested
3. query data and confirm only 10 events were ingested.

**Expected behavior**
Page correctly and ingest all available events returned by rest API

** More details **
Current polling config

![image](https://github.com/Azure/Azure-Sentinel/assets/183547/835995f8-3d7c-4474-bdb6-1337f83d0c93)

initial rest request looks like this

> api/v2/securityProblems?fields=+riskAssessment&pageSize=10&from=now-5m&to=now

but must look like this for second page

> api/v2/securityProblems?nextPageKey=vu8XQiDj3q0SIU59....

currently testing this polling config

<img width="630" alt="image" src="https://github.com/Azure/Azure-Sentinel/assets/183547/75db5cc2-b74c-4e43-a35a-c6a430d281b0">

this is the raw rest response from same rest endpoint

![image](https://github.com/Azure/Azure-Sentinel/assets/183547/58c94d99-9fb4-4320-8314-382833f83bf4)

LAWS only has 11 items since connected

<img width="1025" alt="image" src="https://github.com/Azure/Azure-Sentinel/assets/183547/ffa57802-edee-4b8a-9f26-1c2e81a0ad1e">

**Comment by v-rbajaj** [comment]
Hi @keyoke, thanks for flagging this, we will soon get back to you on this.

**Comment by v-sudkharat** [comment]
Hello @keyoke, as this is the partner solution, we have connected with solution owners, we will update you once we hear back from them. Thanks.

**Comment by keyoke** [comment]
Hi @v-sudkharat, I built this partner solution at Dynatrace, what I would need to know the correct paging config as the documentation for the codeless connector paging configuration is a little confusing and its hard to find any information for it.
Thanks

**Comment by v-sudkharat** [comment]
@keyoke Could you please refer this link for more information of paging configuration. Link to paging configuration [here](https://learn.microsoft.com/en-us/azure/sentinel/create-codeless-connector?tabs=deploy-via-arm-template%2Cconnect-via-the-azure-portal#configure-your-connectors-polling-settings). Adding image for your reference:
![image](https://github.com/Azure/Azure-Sentinel/assets/132428394/8992a814-32c0-4322-b015-1f58eb63b541)

**Comment by keyoke** [comment]
> @keyoke Could you please refer this link for more information of paging configuration. Link to paging configuration [here](https://learn.microsoft.com/en-us/azure/sentinel/create-codeless-connector?tabs=deploy-via-arm-template%2Cconnect-via-the-azure-portal#configure-your-connectors-polling-settings). Adding image for your reference:
> 
> ![image](https://github.com/Azure/Azure-Sentinel/assets/132428394/8992a814-32c0-4322-b015-1f58eb63b541)
> 
> 

Thanks I have read the documentation and as mentioned above its not clear and does not work as expected would require clear explanation. Many thanks

**Comment by v-sudkharat** [comment]
@keyoke For more information on this, I assist you to contact Dynatrace support. Dynatrace offers support for this solution.

**Comment by keyoke** [comment]
Ok, I discovered another issue with the polling config, pagingType was incorrectly set to "PageToken", its odd that when deploying this connector no error is raised for the non-existent paging type? As far as I could see this meant that paging was ignored completely. I have set the pagingType to "NextPageToken" and now I see the following when connecting the Data Connector to a data source, my initial assumption was correct that its using an invalid URL when requesting subsequent pages of data.

<img width="630" alt="image" src="https://github.com/Azure/Azure-Sentinel/assets/183547/989773f2-a53a-4fdd-aa18-a38548dd1bb8">

Here we can see the json response served by the rest endpoint
`{
    "error": {
        "code": 400,
        "message": "Constraints violated.",
        "constraintViolations": [
            {
                "path": "fields",
                "message": "must not be used in combination with nextPageKey query parameter.",
                "parameterLocation": "QUERY",
                "location": null
            },
            {
                "path": "from",
                "message": "must not be used in combination with nextPageKey query parameter.",
                "parameterLocation": "QUERY",
                "location": null
            },
            {
                "path": "to",
                "message": "must not be used in combination with nextPageKey query parameter.",
                "parameterLocation": "QUERY",
                "location": null
            },
            {
                "path": "pageSize",
                "message": "must not be used in combination with nextPageKey query parameter.",
                "parameterLocation": "QUERY",
                "location": null
            }
        ]
    }
}`

**My question to the Microsoft team is how can I configure the sentinel data connector to only include the _nextPageToken_ in subsequent http requests?**

**Comment by v-rbajaj** [comment]
Hi @keyoke, we are connecting with our internal team and once we get any information on this, we will update you.

**Comment by v-sudkharat** [comment]
Hello @keyoke, as per discussion with our internal team. Please remove "pageSize" parameter, as default value for "pageSize" is 100. Regarding pagingType we are following with team.

**Comment by keyoke** [comment]
> Hello @keyoke, as per discussion with our internal team. Please remove "pageSize" parameter, as default value for "pageSize" is 100. Regarding pagingType we are following with team.

Hello, this does not help as the dynatrace api has max page size of 10 for this endpoint, if I set it to a 100 paging still wouldn't work anyway due to incorrect URL querystring.
Thanks

**Comment by v-sudkharat** [comment]
Hey @keyoke, we are following up with team and once we get response, we will connect with you. Thanks

**Comment by v-sudkharat** [comment]
Hi @keyoke, we are still waiting to hear back from concern team. Thanks

**Comment by v-sudkharat** [comment]
Hi @keyoke, since still you are facing the paging issue, we recommend moving to the new CCP API. It is currently in private preview, but we plan to move to public soon and deprecate the old API. Attached is the new API documentation and if needed we will be happy to assist you in building the connector.
[DataConnectorDefinition API.pdf](https://github.com/Azure/Azure-Sentinel/files/12171993/DataConnectorDefinition.API.pdf)
[DataConnector API.pdf](https://github.com/Azure/Azure-Sentinel/files/12171994/DataConnector.API.pdf)
[Create a codeless connector for Microsoft Sentinel.pdf](https://github.com/Azure/Azure-Sentinel/files/12171995/Create.a.codeless.connector.for.Microsoft.Sentinel.pdf)

**Comment by v-sudkharat** [comment]
Hi @keyoke, we have reached out to the concerned team, will update you once we hear back from them, thanks!

**Comment by v-sudkharat** [comment]
Hello @keyoke, please refer this API link which has more details for a reference: - `https://www.dynatrace.com/support/help/dynatrace-api/environment-api/events-v2/get-events ` 
Please let us know if this helps.

**Comment by keyoke** [comment]
> Hello @keyoke, please refer this API link which has more details for a reference: - `https://www.dynatrace.com/support/help/dynatrace-api/environment-api/events-v2/get-events ` 
> 
> Please let us know if this helps.
> 
> 

No it doesn't help  not sure you understand the problem?
Thanks

**Comment by v-sudkharat** [comment]
Hi @keyoke, are you facing issue while retrieving next page data using "nextPageKey" property? Could you please share the API URL that you are using. Thanks!

**Comment by keyoke** [comment]
> Hi @keyoke, are you facing issue while retrieving next page data using "nextPageKey" property? Could you please share the API URL that you are using. Thanks!

initial rest request from the codeless connector looks like this

api/v2/securityProblems?fields=+riskAssessment&pageSize=10&from=now-5m&to=now

When second page is retrieved it must look like this 

api/v2/securityProblems?nextPageKey=vu8XQiDj3q0SIU59....

But it does not as the codeless connector uses invalid request which looks like this

**Comment by v-sudkharat** [comment]
Hello @keyoke, as per communication with concern team, they are going to evaluate and have a fix by end of this month. Thanks!

**Comment by keyoke** [comment]
> Hello @keyoke, as per communication with concern team, they are going to evaluate and have a fix by end of this month. We will let you know once we will have any updates. Thanks! 

Ok many thanks!

**Comment by keyoke** [comment]
hello @v-sudkharat any news about the fix? thanks

**Comment by v-sudkharat** [comment]
Hi @keyoke, we are waiting for the response from concern team about the fix, we will update you once we hear back from them. Thank you for your cooperation.

**Comment by v-sudkharat** [comment]
Hello @keyoke, we received update from concern team, please expect an update by 14-09-2023. Thanks

**Comment by v-sudkharat** [comment]
Hello @keyoke, we received the response from concern team, The fix is now deployed. Please use below paging config for your use case: 
![image](https://github.com/Azure/Azure-Sentinel/assets/132428394/0703b75d-2643-459c-93c1-c82c7f5642ce)

please let us know if you are facing any issues. Thanks

**Comment by v-sudkharat** [comment]
Hi @keyoke, hope you are doing well. Just wanted to check if you got a chance to look at the above comment. Thanks!

**Comment by keyoke** [comment]
> Hi @keyoke, hope you are doing well. Just wanted to check if you got a chance to look at the above comment. Thanks!

I have made the required changes [here](https://github.com/keyoke/Azure-Sentinel/tree/users/gaemslie/8504) and tested but it does not seem to work, has this change been rolled out to all regions?

`az sentinel data-connector list --resource-group test --workspace-name testsentinel`
![image](https://github.com/Azure/Azure-Sentinel/assets/183547/6e45bb34-7fa7-464f-bf1d-db296c169423)

**Comment by keyoke** [comment]
> Hi @keyoke, hope you are doing well. Just wanted to check if you got a chance to look at the above comment. Thanks!

Hi @v-sudkharat , it does not seem to be working  I made the changes to the connector json, I can see these changes reflected in the generated mainTemplate.json on packaging but the paging behaves exactly as before.

![image](https://github.com/Azure/Azure-Sentinel/assets/183547/94c536bc-471f-4f0a-9b2c-c22a4a51fc85)

if I run following to check what is deployed by this template the new json property is missing
` az sentinel data-connector list --resource-group test --workspace-name testsentinel`

![image](https://github.com/Azure/Azure-Sentinel/assets/183547/c7f604d2-1db3-4d41-bb2b-b9a1e7ed8156)

**Comment by v-sudkharat** [comment]
Hi @keyoke, we are checking this issue and also connecting with the concern team, expect an update by 20 Sep.

**Comment by keyoke** [comment]
hello @v-sudkharat any news?

**Comment by v-sudkharat** [comment]
Hello @keyoke, our concern team is working on fixing this issue. Once we receive an update, we will let you know. Thanks!

**Comment by v-sudkharat** [comment]
Hi @keyoke, could you please share your mail id with us? so, the concern team reach out to you to get the information they require. Thanks!

**Comment by v-sudkharat** [comment]
@keyoke, we receive an update from concern team, from logs they can see that they are processing successfully. could you please let us know if you are still facing issue? so, we can share the Information with team. Thanks!

**Comment by keyoke** [comment]
> Hi @keyoke, we are checking this issue and also connecting with the concern team, expect an update by 20 Sep. Thanks

Hello it's been some time and have not received any feedback

**Comment by keyoke** [comment]
> @keyoke, we receive an update from concern team, from logs they can see that they are processing successfully. could you please let us know if you are still facing issue? so, we can share the Information with team. Thanks!

Hello @v-sudkharat  I see what the issue is the nextpagekey for some reason includes encoded quotes(%22) when you request the next page, only the value should be provided not a quoted string.

![image](https://github.com/Azure/Azure-Sentinel/assets/183547/832d0786-6f9d-490b-ae47-639c0beece3f)

this is the raw json response 

![image](https://github.com/Azure/Azure-Sentinel/assets/183547/716668f3-6d3e-452b-bf66-9590c84a44b1)

**Comment by v-sudkharat** [comment]
Hi @keyoke, thanks for sharing the information, could you please share your mail id with us? so, the concern team can reach out to you to get the information they require. Thanks!

**Comment by keyoke** [comment]
> Hi @keyoke, thanks for sharing the information, could you please share your mail id with us? so, the concern team can reach out to you to get the information they require. Thanks!

Sure Gareth.Emslie{at}dynatrace.com

**Comment by v-sudkharat** [comment]
@keyoke, thanks!

**Comment by keyoke** [comment]
@v-sudkharat have tested fix applied by MS team, all seems to work. changes applied in link PR

**Comment by v-sudkharat** [comment]
Hi @keyoke, based on last email conversion, just want to know should we start to review the PR? if no, please can you Draft the PR. 

Thanks!

**Comment by keyoke** [comment]
@v-sudkharat yes please review PR at your earliest its now working again as expected

**Comment by v-sudkharat** [comment]
Hi @keyoke, thank you for your response, we will review your PR (https://github.com/Azure/Azure-Sentinel/pull/9148) and we will share updates on PR comment chat. Thanks!
