### ISSUE TITLE
Send-IngestionCostAnomalyAlert Quantity Type Issue 

### ISSUE THREAD

**Issue by ZLT-ops** [Azure/Azure-Sentinel#8518]
**Describe the bug**
The bug is that the number that is reference in the playbook is in GB and on the Usage table is in MB

**To Reproduce**
Search the Usage table 
`
Usage
| where IsBillable == "true"
| distinct QuantityUnit
`
**Expected behavior**
Either change the readme file to say that you will need to write in MB or change the query.

**Comment by ZLT-ops** [comment]
Example for the default query with the fix
`
let UpperThreshold = 3;
Usage
| where IsBillable == "true"
| where Quantity > (10*1024)
| make-series Qty=sum(Quantity) on TimeGenerated from ago(30d) to now() step 1d by DataType
| extend (anomalies, score, baseline) = series_decompose_anomalies(Qty, 1.5, 7, 'linefit', 1, 'ctukey', 0.01)
| where anomalies[-1] == 1 or anomalies[-1] == -1
| extend Score = score[-1]
| where Score >= 3
| extend PercentageQtyIncrease = ((round(todouble(Qty[-1]),0)-round(todouble(baseline[-1]),1))/round(todouble(Qty[-1]),0) * 100)
| project DataType,ExpectedQty=round(todouble(baseline[-1]),0), ActualQty=round(todouble(Qty[-1]),0),round(PercentageQtyIncrease,0) 
| order by round(todouble(PercentageQtyIncrease),0) desc
| where PercentageQtyIncrease > 25
`

**Comment by v-vdixit** [comment]
Hi @ZLT-ops thanks for flagging this we will discuss with the team and update you by Monday, 17th July 2023

**Comment by v-vdixit** [comment]
Hi @ZLT-ops we have connected with the concerned team, will update the playbook with changes and raise PR shortly, thanks!
