### ISSUE TITLE
AWS Security Hub Connector invalid ELF header error

### ISSUE THREAD

**Issue by Pathward-MikeM** [Azure/Azure-Sentinel#8527]
**Describe the bug**
AWS Security Hub function app has an error "invalid ELF header". Copy of error here:

Result: Failure Exception: ImportError: /home/site/wwwroot/.python_packages/lib/site-packages/cryptography/hazmat/bindings/_rust.abi3.so: invalid ELF header. Troubleshooting Guide: https://aka.ms/functions-modulenotfound Stack: File "/azure-functions-host/workers/python/3.8/LINUX/X64/azure_functions_worker/dispatcher.py", line 314, in _handle__function_load_request func = loader.load_function( File "/azure-functions-host/workers/python/3.8/LINUX/X64/azure_functions_worker/utils/wrappers.py", line 42, in call raise extend_exception_message(e, message) File "/azure-functions-host/workers/python/3.8/LINUX/X64/azure_functions_worker/utils/wrappers.py", line 40, in call return func(*args, **kwargs) File "/azure-functions-host/workers/python/3.8/LINUX/X64/azure_functions_worker/loader.py", line 85, in load_function mod = importlib.import_module(fullmodname) File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module return _bootstrap._gcd_import(name[level:], package, level) File "<frozen importlib._bootstrap>", line 1014, in _gcd_import File "<frozen (... etc etc)

**To Reproduce**
This is a read only app that is ran from a vendor managed package. We have made no custom changes on our end. To replicate, simply deploy the function app and wait for the error to populate.

**Expected behavior**
No ELF header error, expected behavior is ingestion of AWS Security Hub findings into Sentinel.

**Screenshots**
![image](https://github.com/Azure/Azure-Sentinel/assets/139395548/765a5434-150c-4735-a082-b74bc3c2321c)

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser: N/A
 - Version: 3.20.0.0

**Comment by v-rbajaj** [comment]
Hi @Pathward-MikeM, thanks for flagging this, we will look into this and provide an update soon.

**Comment by v-rbajaj** [comment]
Hi @Pathward-MikeM, can you please change the runtime version to 4 and restart the function app then check the invocation logs?
![image](https://github.com/Azure/Azure-Sentinel/assets/120547590/8319d897-3de8-430a-b181-3362d3ac85bf)

**Comment by v-rbajaj** [comment]
Hi @Pathward-MikeM, we are checking on this with the team and once will receive an update will let you know

**Comment by v-rbajaj** [comment]
Hi @Pathward-MikeM, we are still checking on this with the team internally and once will receive an update will let you know

**Comment by v-rbajaj** [comment]
Hi @Pathward-MikeM,
The error message "invalid ELF header" is related to a module import error in the Azure Function app. The error message indicates that the module "cryptography" is not loading properly The error message suggests that the issue is with the "rust" module, which is a dependency of the "cryptography" module. 

Please follow this document for help on troubleshooting.
https://github.com/MicrosoftDocs/azure-docs/blob/main/articles/azure-functions/recover-python-functions.md.

**Comment by Pathward-MikeM** [comment]
Hi @v-rbajaj, this is function app runs from a package file. We do not make changes to the package file as that would prevent future updates - this is Azure best practice. Your recommended path to remediation would involve disabling the run from package setting, thereby preventing future updates. Please correct me if I am wrong here? Thanks!

**Comment by v-rbajaj** [comment]
Hi @Pathward-MikeM, we will get back to you on this.

**Comment by v-rbajaj** [comment]
Hi @Pathward-MikeM, we are looking into the query asked here, we will get back to you once there is an update.

**Comment by v-rbajaj** [comment]
Hi @Pathward-MikeM, we are looking into the query asked here, we will get back to you once there is an update.

**Comment by v-rbajaj** [comment]
Hi @Pathward-MikeM, we are trying to reproduce this issue.

**Comment by v-rbajaj** [comment]
Thanks for your patience @Pathward-MikeM, we are able to reproduce the issue, we are figuring out the fix. 

Just wanted to know, have you read the readme file and did the configuration as per the readme file?

**Comment by v-rbajaj** [comment]
Hi @Pathward-MikeM, can you please look into the above comment?

**Comment by Pathward-MikeM** [comment]
Hi yes I have done all the configuration steps as part of the readme and configuration. Thanks

**Comment by v-rbajaj** [comment]
Hi @Pathward-MikeM, I'll get back to you on this in some time.

**Comment by v-rbajaj** [comment]
Hi @Pathward-MikeM, we are reaching out to the concerned team, we will get to back.

**Comment by v-rbajaj** [comment]
Hi @Pathward-MikeM, we have reached out to concerned team, sorry for the delay.

**Comment by v-rbajaj** [comment]
Hi @Pathward-MikeM, sorry for the delay, we are reaching out to concerned team for this issue.

**Comment by v-rbajaj** [comment]
Hi @Pathward-MikeM, sorry for the delay, we are reaching out to concerned team for this issue, will update you by 17 Oct 2023.

**Comment by rcscoggin** [comment]
Any updates on this issue, it is after 10/17.

**Comment by v-rbajaj** [comment]
Hi @rcscoggin, sorry for the delay, please give us more time to investigate till 31 Oct 2023.

**Comment by v-rbajaj** [comment]
Hi @Pathward-MikeM , sorry for the delay, please give us more time to investigate till 03 Nov 2023.

**Comment by v-rbajaj** [comment]
Hi @Pathward-MikeM , sorry for the delay, please give us more time to investigate till 07 Nov 2023.

**Comment by v-rbajaj** [comment]
Hi @Pathward-MikeM , sorry for the delay, please give us more time to investigate till 08 Nov 2023.

**Comment by v-rbajaj** [comment]
Hi @Pathward-MikeM , we are still investigating on this issue,  please give us more time to investigate till 10 Nov 2023.

**Comment by v-rbajaj** [comment]
Hi @Pathward-MikeM, Our current challenge centers around identifying a specific missing module in our Function App that is causing this issue which we feel that is the ideal fix. Despite our successful reproduction of the issue via function app deployment on Azure, we still not able to figure out the module, we need to perform local testing, it's noteworthy that other users haven't reported this issue yet.

**Comment by v-muuppugund** [comment]
Hi @Pathward-MikeM ,noticed the issue related to packages while debugging the code and working on it, will update you by 20Nov23

**Comment by rcscoggin** [comment]
That's great news, thanks, Murali.
________________________________

**Comment by v-muuppugund** [comment]
Hi @Pathward-MikeM , fixed few dependency issues as there are version compatible issues, so it's taking time to address those issues, will get back to you updates by 23Nov23.Thanks.

**Comment by v-muuppugund** [comment]
Hi @Pathward-MikeM ,I have fixed locally fixed the packages issues and deployed from VS code,Please find below screen shot for reference with incremented python version i.e.3.9,having packaging issues,once done,will share the package for testing

![image](https://github.com/Azure/Azure-Sentinel/assets/139563098/26122e68-e6f7-491f-8f73-d19be170895f)

**Comment by Pathward-MikeM** [comment]
Hi @v-muuppugund any update?

**Comment by v-muuppugund** [comment]
Hi @Pathward-MikeM ,Apologies for late response,as blocked with high priority issue, unable to focus on this issue,will get back to with an update by 13Dec2023.

**Comment by v-muuppugund** [comment]
> Hi @Pathward-MikeM ,Apologies for late response,as blocked with high priority issue, unable to focus on this issue,will get back to you with an update by 13Dec2023.
Hi @Pathward-MikeM ,Till yesterday working on the high priority issue,will focus on this asap and share updates

**Comment by Pathward-MikeM** [comment]
Hi team, any update?

**Comment by v-muuppugund** [comment]
Hi @Pathward-MikeM ,Working on this one,will share updates by eod

**Comment by v-muuppugund** [comment]
Hi @Pathward-MikeM ,Please use the package url  i.e. https://github.com/Azure/Azure-Sentinel/raw/users/v-muuppugund/AWSchanges/DataConnectors/AWS-SecurityHubFindings/AzFunAWSSecurityHubIngestion.zip  point this url to WEBSITE_RUN_FROM_PACKAGE in existing function app settings and restart the function app,please let me know if you have any issues,will connect over teams meeting.

**Comment by Pathward-MikeM** [comment]
Hi @v-muuppugund, good morning! I unfortuntaly am still receiving an error. Screenshot is attached.
![image](https://github.com/Azure/Azure-Sentinel/assets/139395548/b79e50c5-dbc0-4b60-ad80-93f8c3a01dba)

**Comment by v-muuppugund** [comment]
Hi @Pathward-MikeM ,Apologies for the delayed response,for me i am not getting issues as i don't have valid account credentials to check this issue,Could you please share email id and conveninet time slots for trouble shooting this issue via teams meeting

**Comment by Pathward-MikeM** [comment]
Hi, can you drop your email and I will send you an email with availability? Thank you!

**Comment by v-muuppugund** [comment]
Hi @Pathward-MikeM ,Apologies for the delayed response, don't see email id from profile,could you please share couple of time slots to (v-muuppugund@microsoft.com) for teams meeting,Thanks

**Comment by v-sudkharat** [comment]
Hi @Pathward-MikeM, Could you please confirm have you sent your slot time on above mentioned mail id? Thanks!

**Comment by Pathward-MikeM** [comment]
Hi all, yes I have sent an email to begin scheduling a call. Thanks!

**Comment by v-muuppugund** [comment]
Hi @Pathward-MikeM ,Blocked time for the issue troubleshooting, please let me know if this time isn't convenient.

**Comment by v-muuppugund** [comment]
Hi @Pathward-MikeM ,As discussed over call today ,I am trying the set up in my environment and will update you

**Comment by v-muuppugund** [comment]
Hi @Pathward-MikeM ,As discussed on last Thursday call i,e. 28Dec2023, the initial error is fixed with the package and the error now getting while token generation and we have environment and i am working on using that replcating the same issue at my end if required will let you know.

**Comment by v-muuppugund** [comment]
Hi @Pathward-MikeM ,I have enabled security  hub in our environment and role ,debugging it,Will update you and trying to replciate the issue at my end

![image](https://github.com/Azure/Azure-Sentinel/assets/139563098/8d162607-cf2b-4f85-9239-4979a3221391)
![image](https://github.com/Azure/Azure-Sentinel/assets/139563098/9c990a16-2c00-414f-9fb7-e64fc936e80e)

**Comment by v-muuppugund** [comment]
Hi @Pathward-MikeM ,still working on fixes in the environment created,will update you,once fix is completed ,will block your calendar.

**Comment by v-muuppugund** [comment]
Hi @Pathward-MikeM ,Still need some time to complete debugging,will share an update this and will block your calendar for the same.

**Comment by v-muuppugund** [comment]
Hi @Pathward-MikeM ,Fixed the issues while generating token,please find below screen shot for reference,please share convenient time slot for teams meeting
![image](https://github.com/Azure/Azure-Sentinel/assets/139563098/7e9945e6-3947-433a-a878-8481430b06c1)

**Comment by v-muuppugund** [comment]
Hi @Pathward-MikeM ,Tomorrow call has been scheduled for redeploying entire solution earlier call fixed aws permissions and azure function configuration issues.

**Comment by CyberHunter7** [comment]
Hi @v-muuppugund we have been waiting for a fix for this issue for a couple of months now. We see it's marked as resolved, we have deployed to Azure once again but the original message error still there. Could you please confirm if the **_AzFunAWSSecurityHubIngestion.zip_** is now updated on (Azure-Sentinel/DataConnectors/AWS-SecurityHubFindings) to reflect the last updates ? If yes could we schedule a call in order to look into this matter. Thank you.

**Comment by v-muuppugund** [comment]
> Hi @v-muuppugund we have been waiting for a fix for this issue for a couple of months now. We see it's marked as resolved, we have deployed to Azure once again but the original message error still there. Could you please confirm if the **_AzFunAWSSecurityHubIngestion.zip_** is now updated on (Azure-Sentinel/DataConnectors/AWS-SecurityHubFindings) to reflect the last updates ? If yes could we schedule a call in order to look into this matter. Thank you.

Will be raising PR ,will update you

**Comment by v-muuppugund** [comment]
> > Hi @v-muuppugund we have been waiting for a fix for this issue for a couple of months now. We see it's marked as resolved, we have deployed to Azure once again but the original message error still there. Could you please confirm if the **_AzFunAWSSecurityHubIngestion.zip_** is now updated on (Azure-Sentinel/DataConnectors/AWS-SecurityHubFindings) to reflect the last updates ? If yes could we schedule a call in order to look into this matter. Thank you.
> 
> Will be raising PR ,will update you

@CyberHunter7  rasied pr for it https://github.com/Azure/Azure-Sentinel/pull/9910

**Comment by CyberHunter7** [comment]
> > > Hi @v-muuppugund we have been waiting for a fix for this issue for a couple of months now. We see it's marked as resolved, we have deployed to Azure once again but the original message error still there. Could you please confirm if the **_AzFunAWSSecurityHubIngestion.zip_** is now updated on (Azure-Sentinel/DataConnectors/AWS-SecurityHubFindings) to reflect the last updates ? If yes could we schedule a call in order to look into this matter. Thank you.
> > 
> > 
> > Will be raising PR ,will update you
> 
> @CyberHunter7 raised pr for it #9910
Hi @v-muuppugund Any news ?

**Comment by v-muuppugund** [comment]
> > > > > Hi @v-muuppugund we have been waiting for a fix for this issue for a couple of months now. We see it's marked as resolved, we have deployed to Azure once again but the original message error still there. Could you please confirm if the **_AzFunAWSSecurityHubIngestion.zip_** is now updated on (Azure-Sentinel/DataConnectors/AWS-SecurityHubFindings) to reflect the last updates ? If yes could we schedule a call in order to look into this matter. Thank you.
> > > > 
> > > > 
> > > > Will be raising PR ,will update you
> > > 
> > > 
> > > @CyberHunter7 raised pr for it #9910
> > > Hi @v-muuppugund Any news ?
> 
> Hi @CyberHunter7 , Working on PR push as team has asked me to check another issue i.e. dependency bot version compatibility issue for this connector ,so i am occupied with other items, didn't get chance to check it, will be checking that also and pushing it.

Hi @CyberHunter7 ,I have completed the package computability for cryptography version upgrade by dependency bot and PR is under review,will update you once completed.

**Comment by CyberHunter7** [comment]
> > > > > > Hi @v-muuppugund we have been waiting for a fix for this issue for a couple of months now. We see it's marked as resolved, we have deployed to Azure once again but the original message error still there. Could you please confirm if the **_AzFunAWSSecurityHubIngestion.zip_** is now updated on (Azure-Sentinel/DataConnectors/AWS-SecurityHubFindings) to reflect the last updates ? If yes could we schedule a call in order to look into this matter. Thank you.
> > > > > 
> > > > > 
> > > > > Will be raising PR ,will update you
> > > > 
> > > > 
> > > > @CyberHunter7 raised pr for it #9910
> > > > Hi @v-muuppugund Any news ?
> > 
> > 
> > Hi @CyberHunter7 , Working on PR push as team has asked me to check another issue i.e. dependency bot version compatibility issue for this connector ,so i am occupied with other items, didn't get chance to check it, will be checking that also and pushing it.
> 
> Hi @CyberHunter7 ,I have completed the package compatability for cryptography version upgrade by dependency bot and PR is under review as team asked me to check on the another item for the same connector,will update you once completed.

Hi @v-muuppugund Thank you for your support. It's working now.

**Comment by CyberHunter7** [comment]
Hi @Pathward-MikeM since you opened this issue, just checking if you noticed that events related to Macie and GuardDuty, even if it's showing in Security Hub (in the aws console or aws cli output), it does not appear on Azure Log Analytics side ? What's visible in Azure log analytics side are only events related to security standards.

**Comment by Pathward-MikeM** [comment]
Yes, I have experienced issues with the connector since update. @CyberHunter7 have you found any workarounds?
