### ISSUE TITLE
Manually run ./IngestCSV.ps1 fails too... 

### ISSUE THREAD

**Issue by mathurin68** [Azure/Azure-Sentinel#8548]
I have Contributor permissions in a subscription in our tenant, it let me install the resource group, the resource group LA, and then Sentinel.

However, when I try to install the Microsoft Sentinel training lab it all seems to work except the 'ingestEvents' piece fails with
'This request is not authorized to perform this operation.'
![image](https://github.com/Azure/Azure-Sentinel/assets/5932961/6e927fbb-2bd5-4e6c-810b-853e470295b5)

So I'm trying to run the 'IngestCSV.ps1' script manually as suggested in this this issue - 
https://github.com/Azure/Azure-Sentinel/issues/4725

I uploaded it to Azure Cloud Storage
![image](https://github.com/Azure/Azure-Sentinel/assets/5932961/c1a6dee4-f69f-4527-a63a-e0ac3f46a2fd)

and executed it with ./IngestCSV.ps1
it asks for the workspace id and key...
it seems to finish without error but still no data in Sentinel :(
 
![image](https://github.com/Azure/Azure-Sentinel/assets/5932961/e97a61a2-d1d3-4a99-8aef-057062a26221)

I'd be grateful for any suggestions thanks!!

**Comment by v-rbajaj** [comment]
Hi @mathurin68, thanks for flagging this, we will provide an update in sometime.

**Comment by javiersoriano** [comment]
@mathurin68 can you send the entire output of the script? How are you checking if the data is ingested?

I have tried in my environment and it works without issues

**Comment by mathurin68** [comment]
Hey @javiersoriano! 

Understanding I'm just learning, and have no idea what I'm doing. 

I ran the script in the Azure cloud shell and that was the output of the script.  It looks like all the tables are there except for the 
SecurityAlert, SecurityIncident tables? 

I'm not sure... I'm gonna run it in my personal subscription at home tonight.

**Comment by javiersoriano** [comment]
@mathurin68 when you run it, check if there's data in the SecurityEvent_CL table

**Comment by mathurin68** [comment]
Seem to be there - 
![image](https://github.com/Azure/Azure-Sentinel/assets/5932961/2852a823-5fc5-4197-8a78-4f0d56da19d6)

**Comment by javiersoriano** [comment]
then the script is working as expected

**Comment by v-vdixit** [comment]
Hi @mathurin68 since we have received update that script is working as expected we are closing this issue, feel free to reopen if you are still facing this issue, thanks!
