### ISSUE TITLE
ASIM Parser for AuditEventMicrosoftWindowsEvents Issue with 1102

### ISSUE THREAD

**Issue by briandelmsft** [Azure/Azure-Sentinel#8565]
**Describe the bug**
The ASIM Parser AuditEventMicrosoftWindowsEvents incorrectly categorizes some 1102 events as a *Delete Logs* operation.
As 1102 events are not exclusive to event log clears, this creates a false positive detection if you are working off the ASIM parser

AD FS servers will log an 1102 to the security log that are not log clears

Another example of such an 1102 can be found here which is in the Application log: https://social.technet.microsoft.com/Forums/en-US/7061c9d8-a03c-4195-9e20-e8d94eaee453/microsoftfilteringfipfs which is also not a log clear

**To Reproduce**
Generate any 1102 event that is not a security log clear and the parser will indicate that logs were deleted.

**Expected behavior**
Only actual security audit/log clear 1102 should trigger a log clear event with the parser

**Comment by v-rbajaj** [comment]
Hi @briandelmsft, thanks for flagging this, we will get back to you once we receive an update from the internal team.

**Comment by v-rbajaj** [comment]
Hi @briandelmsft, we have reached out to concerned team for this issue, we will get back to you once we receive an update.

**Comment by v-rbajaj** [comment]
Hi @briandelmsft, we have reached out to concerned team for this issue, we will get back to you once we receive an update.

**Comment by v-rbajaj** [comment]
Hi @briandelmsft, we have reached out to concerned team for this issue, we will get back to you once we receive an update.

**Comment by v-rbajaj** [comment]
Hi @briandelmsft, once we receive a response from concerned team, we will let you know

**Comment by v-rbajaj** [comment]
Hi @briandelmsft, once we receive a response from concerned team, we will let you know

**Comment by v-rbajaj** [comment]
Hi @briandelmsft, once we receive a response from concerned team, we will let you know

**Comment by v-rbajaj** [comment]
Hi @briandelmsft, once we receive a response from concerned team, we will let you know

**Comment by v-rbajaj** [comment]
Hi @briandelmsft, once we receive a response from concerned team, we will let you know

**Comment by vakohl** [comment]
@briandelmsft Thanks for raising this issue. I'll be looking into this request. Are you still facing this issue or have applied any workaround for this? If possible, please help sharing the ADFS or 'other' log sample that causing false positive.

**Comment by briandelmsft** [comment]
@vakohl Yes I am still facing the issue.  I have not applied a workaround though a simple KQL tweak to the parsers should do it.

Really we need a more granular filter on the 1102 event to only capture log clear, and not exclude the 'other' events as there could be many 1102 from other products.  As I originally indicated, I've already found 2 cases.

Keep in mind, this issues applies to the SecurityEvent, Event and WindowsEvent tables but my examples below only show the SecurityEvent data

Here is an event that triggers a lot clear... but it isn't.  I know the activity says log clear, but that seems to be something log analytics/Sentinel is doing on ingestion as it is not and the source event does not contain any reference to log clear:
![image](https://github.com/Azure/Azure-Sentinel/assets/68655382/d9d75fe0-c1ee-4993-80b2-fc36b2581964)

here's the source event before ingestion copied from event viewer:
```
Log Name:      Security
Source:        AD FS Auditing
Date:          9/28/2023 12:55:14 PM
Event ID:      1102
Task Category: (3)
Level:         Information
Keywords:      Classic,Audit Success
User:          XXXXX\xxxxxxxxx$
Computer:      ADFS01.xxxx.xx
Description:
The Federation Service authorized a request to one of the REST endpoints. 

Additional Data 

Activity ID: 163ff081-41d9-4cdc-2b19-0080010000f0 

Request Details: 
    Client IP: 192.168.xx.xx 
    Requested URI: https://xxx.xxxxxxxx.xxx:443/adfs/Proxy/GetConfiguration?api-version=2 

Additional details: 
The client was authenticated using the client certificate with thumbprint '4BC8E9A4623BF4A60AD4329763D07ABA3CAA2368' and subject 'CN=ADFS ProxyTrust - XXXXXXXXX'.
Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="AD FS Auditing" />
    <EventID Qualifiers="0">1102</EventID>
    <Level>0</Level>
    <Task>3</Task>
    <Keywords>0x80a0000000000000</Keywords>
    <TimeCreated SystemTime="2023-09-28T16:55:14.556141400Z" />
    <EventRecordID>86381748</EventRecordID>
    <Channel>Security</Channel>
    <Computer>ADFS01.xxxxxx.xxx</Computer>
    <Security UserID="S-1-5-21-0000000-100000000000-24000001-1107" />
  </System>
  <EventData>
    <Data>163ff081-41d9-4cdc-2b19-0080010000f0</Data>
    <Data>192.168.xx.xx</Data>
    <Data>https://xx.xxxxxxxx.xxx:443/adfs/Proxy/GetConfiguration?api-version=2</Data>
    <Data>The client was authenticated using the client certificate with thumbprint '4BC8E9A4623BF4A60AD4329763D07ABA3CAA2368' and subject 'CN=ADFS ProxyTrust - XXXXXXXX'.</Data>
  </EventData>
</Event>
```

here is an actual log clear:
![image](https://github.com/Azure/Azure-Sentinel/assets/68655382/1db38494-029a-4231-85ee-66194094c854)

**Comment by vakohl** [comment]
thanks for sharing @briandelmsft , I'll be looking into this.

**Comment by briandelmsft** [comment]
@vakohl Any update on this? This makes this parser unusable as a number of systems, particularly AD FS log 1102 events that are not event log clears

**Comment by vakohl** [comment]
Hi @briandelmsft , apologies for delay on this, I'll try to prioritize this case.

**Comment by vakohl** [comment]
@briandelmsft 
The information you shared is useful. Even I see multiple EventType for 1102. Also, your observation regarding Sentinel tagging those events as Log cleared is correct. Also, I noticed that, since actual 'audit log clear' has different Eventdata field format, hence fields like ActorUsername, ActorUserId, ActorSessionId won't be getting parsed and would be coming as null currently with 1102, can you please confirm if these are coming as null in your case to? We might need to fix this parsing issue as well.

I'll keep you posted for further progress on this issue.

**Comment by vakohl** [comment]
@briandelmsft can you please confirm, with EventID:1102 logs the fields ActorUsername, ActorUserId, ActorSessionId are not getting parsed.

**Comment by briandelmsft** [comment]
@vakohl they are getting parsed for me when it is a legitimate event log clear.  That is true for both when found in SecurityEvent and WindowsEvent tables.  In looking for this I've located another bug, the imAuditEvent unifying parser doesn't call the right stub parsers and therefore drops all of the invoked parameters, for example `imAuditEvent(starttime=ago(14d))` does not return the last 14 days of data.  I will open another issue for this.

**Comment by briandelmsft** [comment]
just logged the additional bug as #9474

**Comment by v-sudkharat** [comment]
Hi @briandelmsft, Noted. Thanks!

**Comment by vakohl** [comment]
> @vakohl they are getting parsed for me when it is a legitimate event log clear. That is true for both when found in SecurityEvent and WindowsEvent tables. In looking for this I've located another bug, the imAuditEvent unifying parser doesn't call the right stub parsers and therefore drops all of the invoked parameters, for example `imAuditEvent(starttime=ago(14d))` does not return the last 14 days of data. I will open another issue for this.

@briandelmsft I doubt that  ActorUsername, ActorUserId, ActorSessionId will get parsed with 1102 with SecurityEvent table, they should be coming null. Can you please help sharing the 'EventData' field value for legitimate event log clear.

**Comment by vakohl** [comment]
> just logged the additional bug as #9474

@briandelmsft 
thanks for reporting this issue. This require union parser to be updated, will get this fixed in separate PR. For now, please use the built-in AuditEvent functions instead of workspace deployed ones. e.g.

_Im_AuditEvent(starttime=ago(14d))
| summarize max(TimeGenerated), min(TimeGenerated)

**Comment by briandelmsft** [comment]
> @briandelmsft I doubt that ActorUsername, ActorUserId, ActorSessionId will get parsed with 1102 with SecurityEvent table, they should be coming null. Can you please help sharing the 'EventData' field value for legitimate event log clear?

here's EventData from a legitimate clear from the SecurityEvent table:
```
<UserData xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <LogFileCleared xmlns="http://manifests.microsoft.com/win/2004/08/windows/eventlog">
    <SubjectUserSid>S-1-5-21-111111111-1111111111-1111111111-11111</SubjectUserSid>
    <SubjectUserName>username</SubjectUserName>
    <SubjectDomainName>DOMAIN</SubjectDomainName>
    <SubjectLogonId>0x1fc296c</SubjectLogonId>
    <ClientProcessId>8412</ClientProcessId>
    <ClientProcessStartKey>82753643152935667</ClientProcessStartKey>
  </LogFileCleared>
</UserData>
```

The specific event does parse out those 3 fields: ActorUsername, ActorUserId, ActorSessionId with the correct data
