### ISSUE TITLE
Mistakes in selection in the analytic rule: Credential added after admin consented to Application

### ISSUE THREAD

**Issue by lukas-holas** [Azure/Azure-Sentinel#8571]
**Describe the bug**
The time comparison in the last where clause is wrong. We need the query to detect situations when credentials have been added after the consent, not before. Omitting the clause completely seems as a good idea to me, as both situations need investigation.

I also suggest selecting a situation where the two actions have been done by different users or apps as stated in the description of the analytic rule. That would be something like:
| where Consent_InitiatingUserOrApp != Credential_InitiatingUserOrApp

**Comment by v-vdixit** [comment]
Hi @lukas-holas thanks for flagging this we will discuss this with the team and update you by Monday, 24th July 2023, thanks!

**Comment by v-vdixit** [comment]
Hi @lukas-holas we are investigating into this issue, will provide you update by 26th July 2023, thanks!

**Comment by v-amolpatil** [comment]
Hi @lukas-holas we are still investigating into this issue, will provide you update by 28th July 2023, thanks!

**Comment by v-rbajaj** [comment]
Hi @lukas-holas, thanks for suggesting these changes. 
We have investigated about the time comparison and we have fixed it in the raised PR#8739. 

Right now we aren't looking to update the analytical rule with Consent_InitiatingUserOrApp != Credential_InitiatingUserOrApp.
