### ISSUE TITLE
Checkpoint Data connector 

### ISSUE THREAD

**Issue by joe161314** [Azure/Azure-Sentinel#8598]
**Describe the bug**
Checkpoint dta connector no longer showing available int he content hub or repository 

**To Reproduce**
1. Go to 'Content hub'
2. Search 'Checkpoint'
3. See error

**Expected behavior**
previously the checkpoint connector was available and being used

**Comment by v-sudkharat** [comment]
Hi @joe161314, we are checking on this, will update shortly, thanks!

**Comment by v-sudkharat** [comment]
Hello @joe161314, We are not able to repro the issue. Could you please try to reinstall the solution and check it again?
FYI, Below is the screenshot after installation at our end:
![image](https://github.com/Azure/Azure-Sentinel/assets/132428394/59805e3c-9dbb-4bed-8916-1dae48a8e32a)

**Comment by v-sudkharat** [comment]
Hello @joe161314, as we discussed previously, please open the "Playbook" and you can see configuration after clicking the "checkpoint-add-host-to-group". Thanks! 
Sharing the screenshot for reference -
![MicrosoftTeams-image (2)](https://github.com/Azure/Azure-Sentinel/assets/132428394/161bfbe5-3cf3-40de-8396-7d43207e6907)

**Comment by v-sudkharat** [comment]
Hi @joe161314, could you please let us know if the previous comment is work and whether we should close this issue.?

**Comment by v-sudkharat** [comment]
Hello @joe161314, closing this issue, if you still need support for this issue, feel free to re-open at any time. Thank you for your co-operation.
