### ISSUE TITLE
ImpervaCloudWAF "last_file_point" function bug

### ISSUE THREAD

**Issue by A773ycat** [Azure/Azure-Sentinel#8602]
The "last_file_point" function fails if the file name of the last log file processed is not found in the current "logs.index" file retrieved from the location referred to by the application setting "ImpervaLogServerURI".  

**To Reproduce**
Use of prior versions of the connector that were unable to parse log files or stop the function app until the file name of the last log file processed is no longer included in the "logs.index" file retrieved from the URI defined by the "ImpervaLogServerURI" application setting then restart the function app.  Log files will no longer be processed and ongoing use of the Data Connector only results in wasting processing cycles, small amounts of bandwidth, and electricity.  

**Expected behavior**
If the file name assigned to the variable, "past_file" is not found in the current "logs.index", all available log files should be processed with the "past_file" variable being set to the name of the subsequent files available as each is processed.    

**Screenshots**
N/A

**Desktop (please complete the following information):**
N/A

**Smartphone (please complete the following information):**
N/A

**Additional context**
Recommended fix:
Within the file, "__init__.py", in the "last_file_point" function, change the line "if past_file is not None:" to "if past_file is not None and self.files_array.index(past_file):" If the file name of the last log file processed is no longer included in the "logs.index" file, this will allow the code to continue to the next "else:" section instead of ending in error.

**Comment by v-rbajaj** [comment]
Hi @A773ycat, thanks for flagging this issue, we will soon get back to you on this.

**Comment by v-rbajaj** [comment]
Hi @A773ycat, can you please share the screenshot of the error message you are receiving?

**Comment by A773ycat** [comment]
Before changing the line "if past_file is not None:" to "if past_file is not None and self.files_array.index(past_file):" in the "last_file_point" function, the error observed appeared as shown in the following screen excerpt:

![ImpervaCloudWAFFunctionAppError](https://github.com/Azure/Azure-Sentinel/assets/138087399/16dbf0cf-57a2-436c-86e4-6360556c0695)

**Comment by v-rbajaj** [comment]
We are looking this and we will get back to you soon.

**Comment by v-rbajaj** [comment]
We are getting in touch with concerned team, we will get back to you.

**Comment by v-rbajaj** [comment]
We are in touch with concerned team, we will get back to you once we receive an update.

**Comment by v-rbajaj** [comment]
Hi @A773ycat, can you please update WEBSITE_RUN_FROM_PACKAGE with this URL in the function app 
![image](https://github.com/Azure/Azure-Sentinel/assets/120547590/31f6d8e2-927c-4deb-b4d4-d958403e71c9)

https://github.com/Azure/Azure-Sentinel/raw/v-mchatla/ImpervaCloudWAF-8602IssueFix/Solutions/ImpervaCloudWAF/Data%20Connectors/ImpervaWAFCloudSentinelConn.zip

If this fixes the issue then we will merge the changes to master. Please let us know

**Comment by A773ycat** [comment]
Hello,

I appreciate the attention to the matter.  It will take me a couple of days to fit the work into the current task load.  I will report back once the updated package has been evaluated.

**Comment by v-rbajaj** [comment]
Thanks @A773ycat, let us know once you update the package.

**Comment by v-rbajaj** [comment]
Hi @A773ycat, please let us know if the provided update was helpful.

**Comment by A773ycat** [comment]
Hello v-rbajaj,

Testing with the provided update was successful.  Within the Function App, assigning the configuration setting "WEBSITE_RUN_FROM_PACKAGE" with https://github.com/Azure/Azure-Sentinel/raw/v-mchatla/ImpervaCloudWAF-8602IssueFix/Solutions/ImpervaCloudWAF/Data Connectors/ImpervaWAFCloudSentinelConn.zip<https://github.com/Azure/Azure-Sentinel/raw/v-mchatla/ImpervaCloudWAF-8602IssueFix/Solutions/ImpervaCloudWAF/Data%20Connectors/ImpervaWAFCloudSentinelConn.zip>, saving the change, then restarting the Function App (may not have been needed as the "save" action may have done this but just to be sure...) showed the log files being processed properly and the content available in the table (~10-15 minute lag for the data to appear presumably due to the 10 minute processing cycle).



Thank you

**Comment by v-rbajaj** [comment]
> Hello v-rbajaj, Testing with the provided update was successful. Within the Function App, assigning the configuration setting "WEBSITE_RUN_FROM_PACKAGE" with"https://github.com/Azure/Azure-Sentinel/raw/v-mchatla/ImpervaCloudWAF-8602IssueFix/Solutions/ImpervaCloudWAF/Data%20Connectors/ImpervaWAFCloudSentinelConn.zip", saving the change, then restarting the Function App (may not have been needed as the "save" action may have done this but just to be sure...) showed the log files being processed properly and the content available in the table (~10-15 minute lag for the data to appear presumably due to the 10 minute processing cycle). Thank You

Thanks for letting us know. We will push these changes on master and closing this issue.
