### ISSUE TITLE
SecurityIncident report 

### ISSUE THREAD

**Issue by shipothana** [Azure/Azure-Sentinel#8612]
Hi,

We have 90-day retention in the Sentinel incident table, but by any chance we'll get 180-day data, so we need an incident report.

Thanks,
Siva Pathana

**Comment by v-sudkharat** [comment]
Hello @shipothana, thanks for flagging this, we will soon get back to you on this.

**Comment by v-sudkharat** [comment]
Hi @shipothana, yes you can have a 180-day retention period in the Sentinel incident table. However, you'll need to adjust the retention settings in your Azure Sentinel workspace.
Please refer this document for more information: `https://learn.microsoft.com/en-us/azure/azure-monitor/logs/data-retention-archive?tabs=portal-1%2Cportal-2#set-retention-and-archive-policy-by-table`

**Comment by v-sudkharat** [comment]
Hi @shipothana, based on previous comment as a solution for the question we are closing this issue. Feel free to reopen this issue if you need any further assistance. Thanks!
