### ISSUE TITLE
Device Uptime Calculation does not return accurate results

### ISSUE THREAD

**Issue by wlrss** [Azure/Azure-Sentinel#8621]
**Describe the bug**
When running the built-in Device Uptime Calculation defender advanced hunting kql query, the results come back with no accurate entries in the 'DurationAtLeast' field. From what I understand, there will be some entries that show as 00:00:00, but when I run the query all of the entries show as 00:00:00. There are a couple of entries that are more than 00.00:00:00 but they are never longer than 00.00:15:00, which I know that the devices in my inventory are up for longer than that. 

**To Reproduce**
1. Go to security.microsoft.com.
2. Go to the Advanced Hunting page.
3. Click on the 'Queries' tab on the hunting side bar.
4. Click on the 'General' queries drop down.
5. Add the 'Device uptime calculation' query to the editor.
6. Run the query.
8. Scroll down and see the results.
9. See error in the 'DurationAtLeast' field of the entries

**Expected behavior**
I expected to see some entries that have 00.00:00:00 as devices are sometimes going to be down, but I would also expect to see some entries that are more than 00.00:15:00 as the devices are usually up more than that.
**Screenshots**
![image](https://github.com/Azure/Azure-Sentinel/assets/116840413/a0d3c592-e34d-48e7-afbd-25cd2698ed1a)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Edge
 - Version 114.0.1823.86

**Additional context**

**Comment by v-sudkharat** [comment]
Hello @wlrss thanks for flagging this, we will soon get back to you on this.

**Comment by v-sudkharat** [comment]
Hi @wlrss, please can you tell us in which solution or hunting queries you are facing issue?

**Comment by v-sudkharat** [comment]
Hi @wlrss, hope you are doing well. Just wanted to check if you got a chance to look at the feedback shared. Please feel free to reach out to us for any queries or support. Thanks!

**Comment by v-sudkharat** [comment]
Hi @wlrss, Gentle Reminder: We are waiting for your response on this issue. If you still need to keep this issue active, please respond on it in the next 2 days. If we don't receive response by 10-08-2023 date, we will be close this issue. Thanks!

**Comment by v-sudkharat** [comment]
Hi @wlrss, since we have not received a response in the last 5 days, we are closing your issue https://github.com/Azure/Azure-Sentinel/issues/8621 as per our standard operating procedures. If you still need support for this issue, feel free to re-open at any time. Thank you for your co-operation.

**Comment by wlrss** [comment]
Hello v-sudkharat,

Apologies for the radio silence from me I forgot I had submitted this issue. 
As for your question :

> Hi @wlrss, please can you tell us in which solution or hunting queries you are facing issue?

I am facing this issue with the 'Device uptime calculation' advanced hunting query in Microsoft Defender portal.

**Comment by wlrss** [comment]
@v-sudkharat I cannot see where I can re-open this issue. Apologies for directly tagging you.

**Comment by v-sudkharat** [comment]
Hi @wlrss, could you please reopen the issue? Thanks!
