### ISSUE TITLE
Workbooks/M365SecurityPosture Issues with M365 Secure score tables

### ISSUE THREAD

**Issue by david-singh-dtsl** [Azure/Azure-Sentinel#8644]
I think the table name has changed from "M365SecureScore_CL", all the Microsoft 365 secure score action in the workbook are not working. Thanks

**Comment by v-sudkharat** [comment]
Hi @david-singh-dtsl, thanks for flagging this issue, we will soon get back to you on this.

**Comment by v-sudkharat** [comment]
Hi @david-singh-dtsl, please can you add the screenshot for the failing query in workbook and mention table name it has been changed.

**Comment by david-singh-dtsl** [comment]
Hi

Attached is the error. It is having issues with the ‘M365SecureScore_CL’ table. I am not sure about what should the new table. Essentially my goal is finding information about 365 Secure Score via the workbook.

Cheers,
David Singh

**Comment by v-sudkharat** [comment]
Hi @david-singh-dtsl, you need to have ‘M365SecureScore_CL’ table in your workspace to get the information about 365 Secure Score via the workbook. It will be better if you add screenshot for error you get. Thanks!

**Comment by v-sudkharat** [comment]
Hi @david-singh-dtsl, Gentle Reminder: We are waiting for your response on this issue. If you still need to keep this issue active, please respond on it in the next 2 days. If we don't receive response by 09-08-2023 date, we will be close this issue. Thanks!

**Comment by v-sudkharat** [comment]
Hi @david-singh-dtsl, since we have not received a response in the last 5 days, we are closing your issue as per our standard operating procedures. If you still need support for this issue, feel free to re-open at any time. Thank you for your co-operation.
