### ISSUE TITLE
Fortinet SOAR CustomConnectorName unclear how to fill it.

### ISSUE THREAD

**Issue by jeffrywu28** [Azure/Azure-Sentinel#8657]
**Describe the bug**
I try to deploy Fortinet SOAR Playbook to block IP. but the parameter in content hub is not clear how I to input? I'm not a fortune teller. How do I connect to the custom connector that I have installed the app function on? is there a clearer step than this documentation? because the steps are less detailed and incomplete. but we cannot doing the next step because bad documentation.

I following all of this :
Function app must deploy before deploying consloidated template
Fortinet end point should be known. [Fortinet Console](https://%7Bhttps//fndn.fortinet.net/index.php?/category/1-fortianswers/%7D)
Generate an API key ([learn how](https://www.insoftservices.uk/fortigate-rest-api-token-authentication)).
Create the key vaults and capture secret identifier
Create the managed identity and capture name [Create user assigned manage identity](https://docs.microsoft.com/azure/active-directory/managed-identities-azure-resources/how-to-manage-ua-identity-portal)

**To Reproduce**
1. Go to 'Content Hub'
2. Click on 'Fortinet Forti'
3. Scroll down to 'IP Block'
4. Fill the Parameter
5. There are several explanations on how to get the parameters that are not documented

**Expected behavior**
step by step documentation with explanation clearly. how to connect and setup the soar?

**Screenshots**
![WhatsApp Image 2023-07-28 at 15 13 48](https://github.com/Azure/Azure-Sentinel/assets/47622164/fc1b0d70-6de6-4269-b117-4e606d9a30b5)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser Chrome/Mozilla

**Additional context**
Please give me the guide

**Comment by v-sudkharat** [comment]
Hi @jeffrywu28, thanks for flagging this issue. We will look into this and will back to you on this.

**Comment by v-sudkharat** [comment]
Hello @jeffrywu28, thank you for reaching out to us. Please open the "Playbook" and you can see configuration after clicking the "Fortinet-FortiGate-ResponseOnBlockIP". Once you successfully deploy the custom connector which is highlighted in below screenshot, then create playbook.
Sharing the screenshot for reference: -
![image](https://github.com/Azure/Azure-Sentinel/assets/132428394/1bf0a139-867b-4743-93af-e3c82b7d0b5c)
