### ISSUE TITLE
Playbook to Learn Alert for Defender for IoT

### ISSUE THREAD

**Issue by guarismo** [Azure/Azure-Sentinel#8662]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
There are a couple of playbooks under /[Solutions](https://github.com/Azure/Azure-Sentinel/tree/master/Solutions)/[IoTOTThreatMonitoringwithDefenderforIoT](https://github.com/Azure/Azure-Sentinel/tree/master/Solutions/IoTOTThreatMonitoringwithDefenderforIoT )/[Playbooks](https://github.com/Azure/Azure-Sentinel/tree/master/Solutions/IoTOTThreatMonitoringwithDefenderforIoT/Playbooks/ )
that are able to change the Status of alerts to Close, we would like one to Learn, and if successful close from Sentinel.

**Describe alternatives you've considered**
Manually doing it on the Sensor or on Defender for IoT.

**Additional context**
Because pushing Learn on Defender for IoT or the sensor doesn't register automatically on the Sentinel Incident, we would like to be able to select the all the alerts in an Incident or do it by Alert in the incident so it automatically documents what was made (Learned) and how.

It would be useful to at least know the API call to Defender for IoT (NOT the Sensor API) to use, like the one to change the Status, we can't find the documentation for this.

```
POST hxxps://management.azure.com/subscriptions/.../providers/Microsoft.IoTSecurity/locations/.../alerts/<AlertID>

{
  "properties": {
          "status": <NEW STATUS>
    }
}
```

**Comment by v-sudkharat** [comment]
Hello @guarismo, thanks for flagging this, we will soon get back to you on this.

**Comment by v-sudkharat** [comment]
Hi @guarismo, we are looking into this issue, and we will provide next update on 04-08-2023 thanks.

**Comment by v-sudkharat** [comment]
Hello @guarismo, could you please refer the Microsoft document for more information: -`https://learn.microsoft.com/en-us/rest/api/azure/`, If you require any further assistance, feel free to connect with [Azure Support](https://azure.microsoft.com/en-in/support/). Thanks!

**Comment by guarismo** [comment]
> Hello @guarismo, could you please refer the Microsoft document for more information: -`https://learn.microsoft.com/en-us/rest/api/azure/`, If you require any further assistance, feel free to connect with [Azure Support](https://azure.microsoft.com/en-in/support/). Thanks!

I cannot find any API calls for Microsoft.IoTSecurity in that link you provided that;s why I opened this ticket, it seems Microsoft is keeping it hidden or a secret.
Very bad service that after a week you just provide the first link every developer already checked. Seems like lazy work or no internal communication between your teams.

**Comment by v-sudkharat** [comment]
Hi @guarismo, the above documentation shared by us is related to Azure API documentation and issue is related to Azure API, so we mentioned about azure support team, as you are looking for specific azure Api call, could you please share the details of API call, (Ex. Type of call- GET, PUT, POST etc. API URL, body. parameters). If needed, we will have a call and discussed for clarification. Thanks!

**Comment by guarismo** [comment]
> Hi @guarismo, the above documentation shared by us is related to Azure API documentation and issue is related to Azure API, so we mentioned about azure support team, as you are looking for specific azure Api call, could you please share the details of API call, (Ex. Type of call- GET, PUT, POST etc. API URL, body. parameters). If needed, we will have a call and discussed for clarification. Thanks!

wow, seems you didn't even read my post

**Comment by v-sudkharat** [comment]
Hello @guarismo, we are connecting with our concerned team for this issue, once we get any information on this, we will update you. Thanks!

**Comment by v-sudkharat** [comment]
Hi @guarismo, hope you are doing well. We have received an update from our concern team that they are in parallel discussion with you and sent the relevant information about the APIs. So, please let us know if that helps. Thanks!

**Comment by guarismo** [comment]
Thank you!

**Comment by v-sudkharat** [comment]
Hi @guarismo, closing this issue. If you still need support for this issue, feel free to re-open at any time. Thank you for your co-operation.
