### ISSUE TITLE
Zero Trust TIC 3.0 workbook typo

### ISSUE THREAD

**Issue by DeanGross** [Azure/Azure-Sentinel#8720]
**Describe the bug**
When Lighthouse is selected, there are several typos in the field titles "managee" should be "managed"

**To Reproduce**

- view the workbook
- check the Lighthouse option

**Expected behavior**

words should be spelled correctly. 

**Screenshots**
<img width="326" alt="image" src="https://github.com/Azure/Azure-Sentinel/assets/4058555/a7905e4a-0f45-4d89-ae5a-fb824bc9577e">

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by v-sudkharat** [comment]
Hi @DeanGross, thanks for flagging this, we will soon get back to you on this. Thanks!

**Comment by v-sudkharat** [comment]
Hi @DeanGross, we already have the column (ManagedByTenantName & ManagedByTenantId ), so (ManageeTenantName, ManageeTenantId) are different from this and values are also different.  
Sharing screenshot for reference: -
![image](https://github.com/Azure/Azure-Sentinel/assets/132428394/669257a6-1286-4831-899c-7d50df9c5ab0)

**Comment by v-sudkharat** [comment]
Hi @DeanGross, As refer to above screenshot, "ManagedByTenantName" and "ManagedByTenantId" refer to the tenant that manages the resource. The "ManageeTenantName" and "ManageeTenantId" refer to the tenant that the resource belongs to. 
So, closing this issue, as this not a solution issue, if you still need support for this issue, feel free to re-open at any time. Thank you for your co-operation.
