### ISSUE TITLE
Results pane collapses whitespaces

### ISSUE THREAD

**Issue by rkxff** [Azure/Azure-Sentinel#8733]
**Describe the bug**

Sentinel's HTML/CSS does not specify how browsers should handle whitespace, and the default is to collapse consecutive whitespace characters.

This can pose a problem when running queries as it is unclear whether or not a returned element contains a single whitespace character or multiple consecutive whitespace characters.

The same issue applies to Defender Advanced Hunting.

**To Reproduce**

```kql
let testtable = datatable(column1:string)
[
   "single space",
   "double  space",
   "triple   space",
];
testtable
```

Returns:
![image](https://github.com/Azure/Azure-Sentinel/assets/141643752/cc8089d1-d996-49a3-b6ad-ae60580b06bf)

**Expected behavior**

Sequential whitespace characters should be preserved, ie by applying white-space-collapse:preserve to the result elements 

![image](https://github.com/Azure/Azure-Sentinel/assets/141643752/cdc9889c-169f-49df-970e-e4d9e7b67b95)

**Comment by v-sudkharat** [comment]
Hello @rkxff, thanks for flagging this issue, we are working on this, will update you shortly, thanks!

**Comment by v-muuppugund** [comment]
@rkxff  Could you please share the error details with screen shots from sentinel portal,so we can continue on this issue,Thanks

**Comment by v-muuppugund** [comment]
@rkxff  Could you please share the error details with screen shots from sentinel portal,so we can look in to this issue,Thanks

**Comment by v-muuppugund** [comment]
@rkxff Gentle reminder, Could you please share the error details with screen shots from sentinel portal, so we can look in to this issue, Thanks
