### ISSUE TITLE
Bug Report - AUTO DISABLED Sentinel Analytic Rules

### ISSUE THREAD

**Issue by 0ccupi3R** [Azure/Azure-Sentinel#8735]
**Describe the bug**
I received an "AUTO DISABLED" alert for SentinelOne in Azure Sentinel. To address this, I removed the existing SentinelOne workspace function. However, I've noticed a curious behavior – despite having deleted the function, it seems that parsing is still occurring, leading to confusion.

Apart from this, after deleting the new function got created automatically with different KQL statements. 

Function I have deleted starts like below (without `view()`): 

```
SentinelOne_CL
| extend 
    EventVendor="SentinelOne",
    EventProduct="SentinelOne",
```

New Function that auto-load in Sentinel is : 

```
let SentinelOne_view  = view () { 
    SentinelOne_CL
    | extend 
                EventVendor="SentinelOne",
                EventProduct="SentinelOne",
```

**To Reproduce**

- Receive an "AUTO DISABLED" alert for SentinelOne in Azure Sentinel.
- Delete the existing SentinelOne workspace function.
- Observe that parsing still takes place even after the function has been deleted.

**Similar Issue**
#8673 

**Screenshots**
Before Parser Deleted:
<img width="1268" alt="image" src="https://github.com/Azure/Azure-Sentinel/assets/47894266/a3ef615a-afb2-42c9-8b49-ff58546303fa">

Please check how did the new parser added automatically.

**Comment by v-rbajaj** [comment]
Hi @0ccupi3R, Thanks for flagging this, we are looking into this, we will get back to you soon.

**Comment by v-rbajaj** [comment]
Hi @0ccupi3R, 
The new parser function has the view in the code so it got updated after you deleted the old one. 
You can check the parser code here - https://github.com/Azure/Azure-Sentinel/blob/master/Solutions/SentinelOne/Parsers/SentinelOne.txt

Apart from that, you are correct, since it got migrated to content hub, it created copies of it.

**Comment by 0ccupi3R** [comment]
Thanks a lot @v-rbajaj for the confirmation.

**Comment by v-rbajaj** [comment]
Hi @0ccupi3R, Thanks, I hope we answered all your questions, if you have any further questions related to this, please let us know.
