### ISSUE TITLE
Increase character limit for Azure Sentinel incident comments

### ISSUE THREAD

**Issue by alexverboon** [Azure/Azure-Sentinel#874]
**Is your feature request related to a problem? Please describe.**
The Playbook *Enrich-SentinelIncident-MDATPTVM* will fail when a device has many vulnerabilities because the result of the identified CVEs that is stored into a variable and then saved to the Azure Sentinel incident comment exceeds 10000 characters. 

https://github.com/Azure/Azure-Sentinel/tree/master/Playbooks/Enrich-SentinelIncident-MDATPTVM

**Describe the solution you'd like**
Instead of having to write a workaround and save multiple comments, the best option would be to increase the comment message size from 1000 to 5000 *OR* allow for adding an attachment to the incident

I have also filed this suggestion here: https://feedback.azure.com/forums/920458-azure-sentinel/suggestions/40941286-increase-comment-character-limit

**Describe alternatives you've considered**
Split the variable into multiple chunks and add multiple comments, but that's not really a nice option. 

**Additional context**

**Comment by dicolanl** [comment]
@alexverboon ill share with the team for future.
