### ISSUE TITLE
Sentinel Github DataConnector Required Permissions

### ISSUE THREAD

**Issue by aka0** [Azure/Azure-Sentinel#8767]
**Describe the bug**
The documentation isn't clear on what Github Enterprise Cloud permissions are needed for the PAT. Can you please clarify on the exact permissions needed for the connector to work?

**To Reproduce**
I granted the PAT with `admin:org` as per Github (ref #1) documentation and executed the query found in the PowerShell code

https://github.com/Azure/Azure-Sentinel/blob/bc1b032cdfb1d349ee9dea1d1b33a43ad0f1c23b/DataConnectors/GithubFunction/AzureFunctionGitHub/GitHubTimerTrigger/run.ps1#L245

Updated the `orgName` with my orgName, executed the query but received

```
{
  "errors": [
    {
      "type": "INSUFFICIENT_SCOPES",
      "locations": [
        {
          "line": 1,
          "column": 340
        }
      ],
      "message": "Your token has not been granted the required scopes to execute this query. The 'email' field requires one of the following scopes: ['user:email', 'read:user'], but your token has only been granted the: ['admin:org'] scopes. Please modify your token's scopes at: https://github.com/settings/tokens."
    }
  ]
}

```

Added additional scopes `user:email` and `read:user` as per the error message but the request was still denied

```
{
  "data": {
    "organization": null
  },
  "errors": [
    {
      "type": "FORBIDDEN",
      "path": [
        "organization",
        "auditLog"
      ],
      "locations": [
        {
          "line": 1,
          "column": 51
        }
      ],
      "message": "myserviceaccount does not have permission to retrieve auditLog information."
    }
  ]
}
```

**Expected behavior**
1. The above query should return Github audit events in order for the connector to function

**Reference**
1. https://github.blog/2019-06-21-the-github-enterprise-audit-log-api-for-graphql-beginners/

**Comment by v-sudkharat** [comment]
Hi @aka0, thanks for flagging this, we will soon get back to you on this.

**Comment by v-sudkharat** [comment]
Hi @aka0, Gentle Reminder: We are waiting for your response on this issue. If you still need to keep this issue active, please respond on it in the next 2 days. If we don't receive response by 23-08-2023 date, we will be close this issue. Thanks!

**Comment by aka0** [comment]
Hi @v-sudkharat ,

To clarify I am testing against enterprise cloud.

I get the following error message if I only assign `admin:org` scope to the token and execute the query found on line 245 in the connector code:

```
{
  "errors": [
    {
      "type": "INSUFFICIENT_SCOPES",
      "locations": [
        {
          "line": 1,
          "column": 306
        }
      ],
      "message": "Your token has not been granted the required scopes to execute this query. The 'email' field requires one of the following scopes: ['user:email', 'read:user'], but your token has only been granted the: ['admin:org'] scopes. Please modify your token's scopes at: https://github.com/settings/tokens."
    }
  ]
}
```

If I then add `user:email` and `read:user` to the scope then I get the error message found in my first post.

**Comment by v-sudkharat** [comment]
Hi @aka0, as asked before can you please check if you are the owner for the organization? and let us know. Thanks!

**Comment by aka0** [comment]
Update token to owner. Issue resolved.
