### ISSUE TITLE
Content Hub Data Connector Symantec Endpoint Protection - Parser is not working as expected for "Agent Behavior Log"

### ISSUE THREAD

**Issue by v-miketang** [Azure/Azure-Sentinel#8769]
**Describe the bug**

After installing the Symantec Endpoint Protection data connector from the content hub, the Syslog is connected and ingested to the workspace. However, after the parser filtering the logs into the SymantecEndpointPortection table, for log type "Agent Behavior Event", the values from RAW syslog message are not correctly mapped into the corresponding columns.

**To Reproduce**
For example, we have the RAW syslog message from the Syslog table as below:

![image](https://github.com/Azure/Azure-Sentinel/assets/96047595/d26c5185-798e-449a-af35-9e473cad6059)

The value of Action Type is mapped into the Domain Name column in the SymantecEndpointPortection table:

![image](https://github.com/Azure/Azure-Sentinel/assets/96047595/7ea5112e-0adf-4324-ae04-15aa0a2398f9)

After checking the parser, it might relate to the below section of the parser:

| extend AgentBehaviorLogsParser2 = iif(SyslogMessage has_all ("User Name:","Domain Name:", "Action Type:"),extract_all(@"([^,]+)?\,([^,]+)?\,User Name:\s([^,]+)?\,Domain Name:\s([^,]+)?\,Action Type:\s([^,]+)?\,File size \(bytes\):\s(\d+)?\,Device ID:\s([^,]+)?",dynamic([1,2,3,4,5,6,7,8]),AgentBehaviorLogsSubstring)[0], dynamic(""))
| extend LogType = iif(isempty(LogType) and isnotempty(AgentBehaviorLogsParser) and isnotempty(AgentBehaviorLogsParser2),"Agent Behavior Logs",LogType)

**Expected behavior**
We would like to see the columns of SymantecEndpointPortection table showing the correct values. If the column does not have a value, just leave it as blank instead of an incorrect value.

**Comment by v-sudkharat** [comment]
Hi @v-miketang, thanks for flagging this, we will soon get back to you on this. Thanks!

**Comment by v-rbajaj** [comment]
We are investigating on this issue, we will soon get back to you.

**Comment by v-miketang** [comment]
Hi @v-sudkharat @v-rbajaj May I get an update on the issue? Thanks

**Comment by v-rbajaj** [comment]
Hi @v-miketang, we have made change to the parser and still testing is in progress.

You can have look at the raised PR here - https://github.com/Azure/Azure-Sentinel/pull/8596

**Comment by v-miketang** [comment]
@v-rbajaj May I know if the testing is finished, and the updates is available in production? If not, do we have an ETA so far?

**Comment by v-rbajaj** [comment]
Hi @v-miketang, testing is still in progress, you can expect an update by 10 September, 2023.

**Comment by v-rbajaj** [comment]
Hi @v-miketang, testing is still in progress, you can expect an update by 11 September, 2023.

**Comment by v-rbajaj** [comment]
Hi @v-miketang, sorry the testing is still in progress and with provide an update by 20 Sep 2023.

**Comment by v-miketang** [comment]
Hi @v-rbajaj, thanks for the update and look forward to the update next week.

**Comment by v-rbajaj** [comment]
Hi @v-miketang, we wanted to inform you that we got confused between Symantec Endpoint Protection and Symantec Proxy. 
The above PR which was shared with you is for Symantec Proxy, sincere apologies for the confusion. 

For this parser, can you export all the RAW syslog message in an excel and share it here?

**Comment by v-miketang** [comment]
@v-rbajaj I have already shared the logs required in an email with you this Monday, please confirm if you have received it or not. Thanks.

**Comment by v-rbajaj** [comment]
Hi @v-miketang,

Requesting you to update the parser with this parser ([v-mchatla/SymantecEndpointProtection-Parser-Fix](https://github.com/Azure/Azure-Sentinel/tree/v-mchatla/SymantecEndpointProtection-Parser-Fix)) and see whether results are populating correctly or not
We have fixed the issue which you had raised, we hope to unblock the user.

Once we get the confirmation we will raise the PR and merge it to master.

**Comment by v-rbajaj** [comment]
Hi @v-miketang, please provide some update on this issue?

**Comment by v-rbajaj** [comment]
Hi @v-miketang, Gentle Reminder: We are awaiting for your response on this issue. If you still need to keep this issue active please respond on it in the next 2 days. If we don't receive response, we will be close this issue.

**Comment by v-rbajaj** [comment]
Since we have not received a response in the last 5 days, we are closing your issue #8769 as per our standard operating procedures. If you still need support for this issue, feel free to re-open at any time. Thank you for your co-operation
