### ISSUE TITLE
Unable to connect Meraki API connector

### ISSUE THREAD

**Issue by philfy20** [Azure/Azure-Sentinel#8777]
**Describe the bug**
I am unable to connect to the Meraki REST API data connector is looks like the Meraki API is not providing the expected data (schema) and is failing

**To Reproduce**
1. Install solution https://github.com/Azure/Azure-Sentinel/tree/master/Solutions/CiscoMeraki/Data%20Connectors/CiscoMerakiNativePollerConnector
2.  Connector to connector providing organisation ID and AP KEY
3. Click connect
4. Then get error message
Failed to create Connector resource of kind Log Analytics Table, error: User provided schema is invalid, due to - HttpClient: Response status code does not indicate success - 400 (Bad Request), for request - cms/apiv2/workspaces/............................/tables/CiscoMerakiNativePoller_CL/validate?intent=PUT, due to reason - [Table validation failed with following 5 errors: MSG 1015: Invalid value provided for data type: Double, in column DstGeoLatitude
;MSG 1015: Invalid value provided for data type: Double, in column DstGeoLongitude
;MSG 1015: Invalid value provided for data type: Double, in column SrcGeoLatitude
;MSG 1015: Invalid value provided for data type: Double, in column SrcGeoLongitude
;MSG 1041: Additional Fields Column  Type should be of dynamic Data Type]. Operation Id: '654bb77f82c0b4dd69ab715013b9c00a'
**Expected behavior**
Connector should connect and ingest alerts from meraki

**Additional context**
Hitting the API directly the API does not provide details on latitude and longitude as per examples from Meraki - https://developer.cisco.com/meraki/api-latest/get-organization-appliance-security-events/

**Comment by v-sudkharat** [comment]
Hi @philfy20, thanks for flagging this, we will soon get back to you on this. Thanks!

**Comment by v-sudkharat** [comment]
Hi @philfy20, we are looking into this issue, and we will provide next update on 22-08-2023.  Thanks!

**Comment by v-sudkharat** [comment]
Hello @philfy20, we are connecting with our concerned team for this issue, once we get any information on this, we will update you. Thanks!

**Comment by philfy20** [comment]
@v-sudkharat connector can now connect which is good. Just waiting on a Meraki device to create a new alert to confirm end to end connector is working. Will update once this is done. Thanks

**Comment by v-sudkharat** [comment]
Hi @philfy20, please let us know once you done. Thanks!

**Comment by philfy20** [comment]
@v-sudkharat can confirm this has fixed the issue. Data connector can connect and ingest the alerts. Thanks

**Comment by v-sudkharat** [comment]
Hi @philfy20, thanks for confirmation we will raise a PR with modification in data connector file. Closing this issue. If you still need support for this issue, feel free to re-open it any time. Thank you for your co-operation.

**Comment by v-sudkharat** [comment]
Hi @philfy20, we are going to upgrade the solution with the changes; it is now in private preview. Please monitor the channel for further updates. Thanks
