### ISSUE TITLE
Office 365 Connector showing connected but no tenant are associated with it.

### ISSUE THREAD

**Issue by SentinelRohit** [Azure/Azure-Sentinel#878]
Hello Team,

I recently created the trial tenant and connected Office 365 Connector with Sentinel but there no data ingestion is happening and also do not see any tenant are associated with the Connector. 

Please let me know, if there is anyway can disconnect the connector and reconnect it.
![O365 Connector](https://user-images.githubusercontent.com/67151892/87950778-5c0dd580-cac5-11ea-83b3-c0ce6f49cda8.JPG)

**Comment by sarah-yo** [comment]
This should be raised as a support ticket in the Azure portal if this is still an issue, as it is not related to the content of analytics rules, workbooks, playbooks or hunting queries. Thanks!
