### ISSUE TITLE
Cisco Umbrella Connector missing updated Firewall Logs folder name

### ISSUE THREAD

**Issue by wtcdwclark** [Azure/Azure-Sentinel#8788]
Discovered the Cisco Umbrella Connector was not pulling in my Cisco_Umbrella_cloudfirewall_CL logs:
<img width="294" alt="image" src="https://github.com/Azure/Azure-Sentinel/assets/101876321/17831942-55a2-4d0d-b200-2d75e9358c74">

Looking at the code, it is looking for a folder named "cloudfirewalllogs" or "cdfwlogs":
<img width="443" alt="image" src="https://github.com/Azure/Azure-Sentinel/assets/101876321/6dafee8a-5467-4754-bc85-52c730c8d862">

When browsing my S3 bucket, the folder is now called "firewalllogs":
<img width="303" alt="image" src="https://github.com/Azure/Azure-Sentinel/assets/101876321/9d2b6228-3027-4760-a3aa-6eabf60bc776">

According to the Cisco Umbrealla log documentation, they are now stored in "firewalllogs": https://docs.umbrella.com/umbrella-user-guide/docs/log-format-and-versioning
<img width="455" alt="image" src="https://github.com/Azure/Azure-Sentinel/assets/101876321/a9836306-facb-444e-b398-32cae6b4b347">

I believe the code should be updated to include the new firewall log folder name.

**Comment by v-sudkharat** [comment]
Hi @wtcdwclark, thanks for flagging this, we will soon get back to you on this. Thanks!

**Comment by v-rbajaj** [comment]
We are investigating on this issue, we will soon get back to you.

**Comment by wtcdwclark** [comment]
@v-sudkharat or @v-rbajaj  Is there any update on this?

**Comment by v-rbajaj** [comment]
Hi @wtcdwclark, PR will be raised by 17 Sep 2023.

**Comment by v-rbajaj** [comment]
Hi @wtcdwclark, sorry for the delay, we have raised this PR #9077 for this issue. We are currently testing the DC, once that is done we will let you know.

**Comment by wtcdwclark** [comment]
Any update on this?


Daryl W. Clark
Senior Vice President and Chief Technology Officer
The Washington Trust Company
2 Crosswind Road, Westerly, RI 02891
401-348-1438
***@***.***
washtrust.com
​*******
​Confidential: The information contained in this e-mail message, including any attached documents or files, may contain information that is confidential or proprietary. Dissemination, distribution or copying of this e-mail or the information contained herein by anyone other than the intended recipient(s), or an employee or agent responsible for delivering the message to the intended recipient(s), is unauthorized and prohibited. If you are not the intended recipient(s), or an employee or agent responsible for delivering the message to the intended recipient(s), please notify the sender by reply e-mail and delete this message.

**Comment by v-rbajaj** [comment]
Hi @wtcdwclark, testing is still progress..

**Comment by v-rbajaj** [comment]
Hi @wtcdwclark, sorry for delay, testing of the parser is still progress, we get back to by 10 Oct 2023

**Comment by v-rbajaj** [comment]
Hi @wtcdwclark, sorry for delay, testing of the parser is still progress, we get back to by 20 Oct 2023

**Comment by v-rbajaj** [comment]
Hi @wtcdwclark, sorry for delay, testing of the parser is still progress, we get back to by 31 Oct 2023

**Comment by v-rbajaj** [comment]
Hi @wtcdwclark, sorry for delay, testing of the parser is still progress, we get back to by 03 Nov 2023

**Comment by v-rbajaj** [comment]
Hi @wtcdwclark, sorry for delay, testing of the parser is still progress, we get back to by 08 Nov 2023

**Comment by v-rbajaj** [comment]
Hi @wtcdwclark, testing is still in progress,  will get back to you by 10 Nov 2023

**Comment by v-rbajaj** [comment]
Hi @wtcdwclark, testing is still in progress, will get back to you by 16 Nov 2023

**Comment by v-muuppugund** [comment]
Hi @wtcdwclark PR(https://github.com/Azure/Azure-Sentinel/pull/9077)  review is in progress and will get back to you by 20Nov23

**Comment by v-rbajaj** [comment]
Hi @wtcdwclark, 
Could you please update the WEBSITE_RUN_FROM_PACKAGE with the following URL in the function app:
![image](https://github.com/Azure/Azure-Sentinel/assets/120547590/8ed483df-874c-4c6a-9a4e-a502f64174d5)

URL: https://github.com/Azure/Azure-Sentinel/raw/4440d968a5b550fd94badfbc3dc30c60d3448f30/Solutions/CiscoUmbrella/Data%20Connectors/CiscoUmbrellaConn.zip

After updating, kindly restart the Function App and check if the issue persists. If this resolves the issue, we can proceed to merge the changes to the master branch.

**Comment by v-muuppugund** [comment]
Hi @wtcdwclark Could you please check confirm after performing the above steps

**Comment by wtcdwclark** [comment]
Sorry I was out since the last update, I will test today


Daryl W. Clark
Senior Vice President and Chief Technology Officer
The Washington Trust Company
2 Crosswind Road, Westerly, RI 02891
401-348-1438
***@***.***
washtrust.com
​*******
​Confidential: The information contained in this e-mail message, including any attached documents or files, may contain information that is confidential or proprietary. Dissemination, distribution or copying of this e-mail or the information contained herein by anyone other than the intended recipient(s), or an employee or agent responsible for delivering the message to the intended recipient(s), is unauthorized and prohibited. If you are not the intended recipient(s), or an employee or agent responsible for delivering the message to the intended recipient(s), please notify the sender by reply e-mail and delete this message.

**Comment by wtcdwclark** [comment]
This does NOT appear to be working. There is not data in the logs its pulling in.

***@***.***


Daryl W. Clark
Senior Vice President and Chief Technology Officer
The Washington Trust Company
2 Crosswind Road, Westerly, RI 02891
401-348-1438
***@***.***
washtrust.com
​*******
​Confidential: The information contained in this e-mail message, including any attached documents or files, may contain information that is confidential or proprietary. Dissemination, distribution or copying of this e-mail or the information contained herein by anyone other than the intended recipient(s), or an employee or agent responsible for delivering the message to the intended recipient(s), is unauthorized and prohibited. If you are not the intended recipient(s), or an employee or agent responsible for delivering the message to the intended recipient(s), please notify the sender by reply e-mail and delete this message.

**Comment by v-muuppugund** [comment]
Hi @wtcdwclark ,Will revalidate the steps and get back to you with an update,Thanks.

**Comment by v-rbajaj** [comment]
Hi @wtcdwclark, thanks for confirming, need to check and get back to you by 28 Nov 2023.

**Comment by v-rbajaj** [comment]
Hi @wtcdwclark, we are investigating on this and will get back to you by 28 Nov 2023.

**Comment by v-rbajaj** [comment]
Hi @wtcdwclark, we are still investigating on this and will get back to you by 04 Dec 2023

**Comment by v-rbajaj** [comment]
Hi @wtcdwclark, we are still investigating on this and will get back to you by 07 Dec 2023

**Comment by v-rbajaj** [comment]
Hi @wtcdwclark,
We have made some more minor changes. 
Could you please update the WEBSITE_RUN_FROM_PACKAGE with the following URL in the function app, just like last time?

URL: 
https://github.com/Azure/Azure-Sentinel/raw/49ed35a71dae54e3173eb0d6edeaf9f18c53caab/Solutions/CiscoUmbrella/Data%20Connectors/CiscoUmbrellaConn.zip

After updating, kindly restart the Function App and check if the issue persists. If this resolves the issue, we can proceed to merge the changes to the master branch.

**Comment by wtcdwclark** [comment]
That appears to be working:

***@***.***


Daryl W. Clark
Senior Vice President and Chief Technology Officer
The Washington Trust Company
2 Crosswind Road, Westerly, RI 02891
401-348-1438
***@***.***
washtrust.com
​*******
​Confidential: The information contained in this e-mail message, including any attached documents or files, may contain information that is confidential or proprietary. Dissemination, distribution or copying of this e-mail or the information contained herein by anyone other than the intended recipient(s), or an employee or agent responsible for delivering the message to the intended recipient(s), is unauthorized and prohibited. If you are not the intended recipient(s), or an employee or agent responsible for delivering the message to the intended recipient(s), please notify the sender by reply e-mail and delete this message.

**Comment by v-muuppugund** [comment]
@wtcdwclark Thanks for confirmation ,we are closing the issue, If you still need support for this issue, feel free to re-open at any time. Thank you for your co-operation

**Comment by wtcdwclark** [comment]
What should I set the run from URL back to?

Get Outlook for iOS<https://aka.ms/o0ukef>

Daryl W. Clark
Senior Vice President and Chief Technology Officer
The Washington Trust Company
2 Crosswind Road, Westerly, RI 02891
401-348-1438
***@***.***
washtrust.com
​*******
​Confidential: The information contained in this e-mail message, including any attached documents or files, may contain information that is confidential or proprietary. Dissemination, distribution or copying of this e-mail or the information contained herein by anyone other than the intended recipient(s), or an employee or agent responsible for delivering the message to the intended recipient(s), is unauthorized and prohibited. If you are not the intended recipient(s), or an employee or agent responsible for delivering the message to the intended recipient(s), please notify the sender by reply e-mail and delete this message.
________________________________
