### ISSUE TITLE
Restore previous Watchlist "view".

### ISSUE THREAD

**Issue by ep3p** [Azure/Azure-Sentinel#8799]
**Is your feature request related to a problem? Please describe.**
It seems the watchlist view (after pressing "Edit watchlist items") has been changed.
- It is missing the name of the watchlist field.
- White space takes more space.
- High number of columns are not properly distributed.

![image](https://github.com/Azure/Azure-Sentinel/assets/2527990/f82df7bd-3707-4856-93ed-8b3349fb6dc1)

**Describe the solution you'd like**
The previous state of the watchlist views was better, I don't feel any upgrade has been added. Please, could it be restored?

Old:

![image](https://github.com/Azure/Azure-Sentinel/assets/2527990/3f253191-8ae6-447b-bfd8-b00b62655ebf)

New:

![image](https://github.com/Azure/Azure-Sentinel/assets/2527990/b2770e52-c916-4987-b668-23a76bbad47a)

**Comment by v-rbajaj** [comment]
Hi @ep3p, 
Thanks for flagging this, we tried checking a random watchlist, we could see the name of the watchlist after clicking on "edit watchlist items", the columns were distributed well enough, if they are not we could adjust them as well. Please take a look at the below screenshot.
![image](https://github.com/Azure/Azure-Sentinel/assets/120547590/8230b04f-4b92-4bb6-b06f-b0ca3abc686a)

**Comment by ep3p** [comment]
Sorry @v-rbajaj , I had spent a few days with the other version, and I thought it was really a change (I use a workspace in Preview), I had tried different computers and browsers and I had the same experience in all of them.

Today I tried to replicate it after your comment, and now I see the old UI, all of the problems have disappeared, I am really sorry.

Please, you could consider this issue solved from my side.

**Comment by v-rbajaj** [comment]
Hi @ep3p, no worries, glad it helped, thanks for confirmation. We are closing this issue based on this confirmation, feel free to reopen if you need further assistance.
