### ISSUE TITLE
Entity incident timeline displays time logged not time occurred

### ISSUE THREAD

**Issue by idnahacks** [Azure/Azure-Sentinel#8818]
When viewing an entities alert timeline the time displayed is the TimeGenerated value, which is when Sentinel recieved the alert, and not the time that the activity happened. This is very misleading when investigating the order of events.
This does not happen when looking at the same timeline in the Investigation Graph where the Activity StartTime is displayed.

**To Reproduce**
1. Browse to an incident and click "View Full Details"
2. Click on Entities and select an entity
3. If using the "New Experience" In the flight out pane, select timeline
4. If using the old experience see the timeline in the new window
5. See that the displayed time is not necessarily when the activity occurred but the time that Sentinel received that event

**Expected behavior**
The timeline should follow the time the events occurred. From the above steps if you click "Investigate" and move to the Investigation graph the timeline is displayed correctly.

**Screenshots**
Timeline from entities page (see the start time of the alert highlighted compared to the time displayed in the timeline):
![entities-timeline](https://github.com/Azure/Azure-Sentinel/assets/12153311/9f773f50-7d29-4c91-8291-3c1d680dfbc7)
Timeline for the same incident in the Investigation Graph. (See the alert that matches the above screenshot's start time):
![inverstigationgraph-timeline](https://github.com/Azure/Azure-Sentinel/assets/12153311/9af6b7d0-75d9-46e0-9f8d-f4c18fc4c303)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Edge
 - Version 115.0.1901.183

**Comment by v-rbajaj** [comment]
Hi @idnahacks, thanks for flagging this issue, we are looking into it and will get back to you.

**Comment by v-rbajaj** [comment]
Hi @idnahacks, we are reaching out to the concerned team we will get back to you once there an update.

**Comment by v-rbajaj** [comment]
We are reaching out to the concerned team on this and we will get back to you.

**Comment by v-rbajaj** [comment]
We are reaching out to the concerned team on this, will get back to you by update.

**Comment by v-rbajaj** [comment]
Hi @idnahacks, we have informed about this request to the concerned team.
For now we are closing this issue, please feel free to re open in case you have further questions.
