### ISSUE TITLE
Cisco Umbrella Admin Audit Logs

### ISSUE THREAD

**Issue by wtcdwclark** [Azure/Azure-Sentinel#8821]
I would like to request that the Cisco Umbrella Connector also pull in the Admin Audit Logs (https://docs.umbrella.com/umbrella-user-guide/docs/log-format-and-versioning#audit)

The path according to the document is: auditlogs/<year>-<month>-<day>/<year>-<month>-<day>-<hour>-<minute>.csv.gz

We would like to have a consolidated place for all of our audit logs, including those from 3rd parties. It would also allow us to build centralized alerting policies in Sentinel and Log Analytics to trigger when certain events occur in that solution.

**Comment by v-rbajaj** [comment]
Thanks for flagging this, we will provide you an update on this.

**Comment by v-rbajaj** [comment]
We are reaching out to the concerned team for this enhancement, and we provide an update soon on it.

**Comment by v-rbajaj** [comment]
Hi @wtcdwclark, Sorry for delay in response, we will get back to you on 22 Sep 2023

**Comment by v-rbajaj** [comment]
Hi @wtcdwclark, we have informed the respective team about this request and we have created the backlog item, and we will work on it based on our priority. Right now, there is no ETA associated with it.

Please feel free to re open this issue in case you have further questions

**Comment by twistedbow1** [comment]
@v-rbajaj Wondering if there's any update on it? Thank you.
