### ISSUE TITLE
Get-GeoFromIpAndTagIncident won't tag multiple IPs, fails on subsequent tags

### ISSUE THREAD

**Issue by richlilly2004** [Azure/Azure-Sentinel#883]
When executing the playbook on an incident with multiple IPs, it parses the IPs just fine and labels the first one, but subsequent labels fail with the following example:

{
  "error": {
    "code": "Conflict",
    "message": "Newer version of resource '193f0487-f0fc-4edc-a7b6-1796944dc97a' exists. Data was not saved"
  },
  "debugInfo": "clientRequestId: 0fc69fa4-c2a4-4d90-b8fd-ec29b7d71823"
}

I'm guessing this is because it's trying to write subsequent tags to Tag1. Can we easily increment IP2 to write to tag2?

**Comment by dicolanl** [comment]
@richlilly2004 good catch... taking this with the connector team.

**Comment by dicolanl** [comment]
@richlilly2004 #924 PR was just submitted. We changed the concurrency to 1 for the loop.  could you try the new template?

**Comment by richlilly2004** [comment]
> @richlilly2004 #924 PR was just submitted. We changed the concurrency to 1 for the loop. could you try the new template?

Looks good now
