### ISSUE TITLE
Support gov tenants for microsoft-sentinel-log-analytics-logstash-output-plugin.

### ISSUE THREAD

**Issue by csidiro** [Azure/Azure-Sentinel#8861]
**Describe the bug**
Currently the login URL for AAD is hardcoded here https://github.com/Azure/Azure-Sentinel/blob/master/DataConnectors/microsoft-sentinel-log-analytics-logstash-output-plugin/lib/logstash/sentinel_la/logAnalyticsAadTokenProvider.rb#L13 taking into account only the commercial tenant. 

**To Reproduce**
1. Configure a gov tenant.
2. You will get authentication error since it will try to connect to commercial aad.

**Comment by v-sudkharat** [comment]
Hi @csidiro, thanks for flagging this, we will soon get back to you on this. Thanks!

**Comment by v-sudkharat** [comment]
Hello @csidiro, we are connecting with our concerned team for this issue, once we get any information on this, we will update you. Thanks!

**Comment by v-sudkharat** [comment]
Hi @csidiro, we are connected with data connector concerned team for this issue, they will look into this. once we get any information, we will update you. Thanks!

**Comment by v-sudkharat** [comment]
Hi @csidiro, we received the update from concern team, the AAD endpoint is indeed hardcoded for the commercial cloud; plugin is currently in public preview and is slated to be globally available in the next few months. Below are few of the questions we would like to know - 
1. Which cloud service you are using and are you sentinel client? 
2. can you share the expected data volume which you are planning to send using the plugin? 
Thanks!

**Comment by v-sudkharat** [comment]
Hello @csidiro, Gentle Reminder: We are waiting for your response on this issue. If you still need to keep this issue active, please respond on it in the next 2 days. If we don't receive response by 20-08-2023 date, we will be close this issue. Thanks!

**Comment by csidiro** [comment]
Hi @v-sudkharat 
1. Yes we are a sentinel client.
2. Data volume is ~10gb/month.

**Comment by v-sudkharat** [comment]
Hello @csidiro, Thanks for sharing details with us, the concerned team is working on this issue, once we get any further information, we will update you.

**Comment by v-sudkharat** [comment]
Hi @csidiro, as per response from concern team the AAD endpoint is indeed hardcoded for the commercial cloud and plugin is currently in public preview and is slated to be globally available in the next few months.
Currently there is no plan on including national clouds to public preview phase of the plugin.
So, closing this issue. If you still need support for this issue, feel free to re-open it any time. Thank you for your co-operation.
