### ISSUE TITLE
Microsoft Exchange Security - Exchange On-Premises - Microsoft Exchange Logs and Events - Step 2 Option 1 connector is configured for firewall logs instead of Event logs

### ISSUE THREAD

**Issue by GThomas-ent** [Azure/Azure-Sentinel#8872]
**Describe the bug**
After installing the Microsoft Exchange Security for Exchange On-Premises solution, there is an issue with Option 1 in the "Microsoft Exchange Logs and Events" data connector.  
The [Option 1] MS Exchange Management Log collection in Step 2 sets up a Windows Firewall data connector instead of Windows Events.

**To Reproduce**
Install the "Microsoft Exchange Security for Exchange On-Premises" solution from Content Hub.
After installation, open the Data Connector "Microsoft Exchange Logs and Events"
Expand "2. Deploy log injestion following choosed options"
Expand "[Option 1] MS Exchange Management Log collection"
Expand "Data Collection Rules - When Azure Monitor Agent is used"
Click "+Create data collection rule"
Click the "Collect" tab.  
Here, you are prompted to "Check the box next to the profile that you want to collect Windows Firewall logs from. Multiple profiles can be selected".

**Expected behavior**
The "Collect" tab should instead reference Windows Event Logs and thus have the ability to complete the step "1. 
![datacollectionrule-firewall](https://github.com/Azure/Azure-Sentinel/assets/94411210/d0078ee8-12ad-4c55-ac23-eac5b94dd157)
Choose 'Custom' type and Enter 'MS Exchange Management' as expression and Add it"
**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser Edge
 - Version 115.0.1901.203 (Official build) (64-bit)

**Additional context**
I have contributor rights in the subscription that Sentinel is configured in

**Comment by v-sudkharat** [comment]
Hi @GThomas-ent, thanks for flagging this issue, we will soon get back to you on this. Thanks!

**Comment by v-sudkharat** [comment]
Hi @GThomas-ent, to collect the Windows Events Logs from the option 1 you have to navigate to step 2 in the same option and click on the dropdown of "Data Collection Rules - When the legacy Azure Log Analytics Agent is used". You can see the steps to collect the Windows Event Logs. 
![image](https://github.com/Azure/Azure-Sentinel/assets/132428394/0cb51a80-1595-48c0-99e9-b322e437cc3d)
I hope this answer your question. 
If you have any more questions or need further assistance, feel free to reach out to us. Thanks!

**Comment by v-sudkharat** [comment]
Hi @GThomas-ent, Gentle Reminder: We are waiting for your response on this issue. If you still need to keep this issue active, please respond on it in the next 2 days. If we don't receive response by 06-09-2023 date, we will be close this issue. Thanks!

**Comment by v-sudkharat** [comment]
Hi @GThomas-ent, since we have not received a response in the last 5 days, we are closing your issue as per our standard operating procedures. If you still need support for this issue, feel free to re-open at any time. Thank you for your co-operation.
