### ISSUE TITLE
Dynatrace analytic rules not showing as conditions in automation rule

### ISSUE THREAD

**Issue by BSteiner9** [Azure/Azure-Sentinel#8881]
**Describe the bug**
Analytic rule (Conditions : If Analytic rule name contains 'Dynatrace Application Security - Attack detection') not showing when creating an automation rule, we can see the Analytic rule in templates though.

**To Reproduce**
1. Go to Sentinel
2. Go to Automation
3. New automation rule
4. Analytics rule does not show in available list of conditions

**Expected behavior**
Expected to see analytics rule as a condition in the automation rule wizard 

**Screenshots**
![analytic rule not showing](https://github.com/Azure/Azure-Sentinel/assets/143106680/9955fcdd-1e3f-4519-9c84-78c82a08a39c)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome
 - Version 116.0.5845.110

**Smartphone (please complete the following information):**
N/A

**Additional context**
We're following the instructions for this playbook, step 3 is where we get stuck:
https://github.com/Azure/Azure-Sentinel/tree/master/Solutions/Dynatrace/Playbooks/Ingest-DynatraceSentinelSecurityAlerts

**Comment by v-sudkharat** [comment]
Hi @BSteiner9, thanks for flagging this issue, we will soon get back to you on this. Thanks!

**Comment by v-sudkharat** [comment]
Hi @BSteiner9, thanks for flagging this issue, we will soon get back to you on this. Thanks!

**Comment by v-sudkharat** [comment]
Hi @BSteiner9, the rule does not show when creating as conditions in automation rule because the analytical rule was not created in the "Content Hub". Please install "Dynatrace Software Intelligence Platform" solution from "Content Hub" and create the "Dynatrace Application Security - Attack detection" analytic rule. 
![image](https://github.com/Azure/Azure-Sentinel/assets/132428394/020206db-4b3e-4e67-b4a8-bb41805f034c)
Once above rule is successfully created it will show in Automation rule.
Let us know if above step's are working for you. 
Thanks!

**Comment by v-sudkharat** [comment]
Hi @BSteiner9, Gentle Reminder: We are waiting for your response on this issue. If you still need to keep this issue active, please respond on it in the next 2 days. If we don't receive response by 06-09-2023 date, we will be close this issue. Thanks!

**Comment by v-sudkharat** [comment]
Hi @BSteiner9, since we have not received a response in the last 5 days, we are closing your issue as per our standard operating procedures. If you still need support for this issue, feel free to re-open at any time. Thank you for your co-operation.

**Comment by BSteiner9** [comment]
Hey @v-sudkharat , thanks for your help! My apologies for the delay on responding.. we're running into an issue when creating the Analytics rule saying that  'Dynatraceattacks_cl data source is missing' - do we have to create something else? Wasn't sure where to find/create a data source or should it import it through the connector?

**Comment by v-sudkharat** [comment]
Hello @BSteiner9, the 'Dynatraceattacks_cl data source is missing', issue occurs when the table is not created into the Workspace. please can you check once the data connector is created, and status of connector is showing as "Connected". 

If Data connector is not created, sharing steps for configure the Data Connector: 
Step 1:   Go to "Dynatrace Software Intelligence Platform" solution and click on the data connector to configure. 
![image](https://github.com/Azure/Azure-Sentinel/assets/132428394/a4677f6a-582c-4113-9422-fb4d89b9d5a3)

Step 2: while configure the connector go through the Pre-requisites and configure it. Once the data connector status show "Connected" the table will be created into the workspace. 
 
![image](https://github.com/Azure/Azure-Sentinel/assets/132428394/ea509ef5-d81d-46be-9663-d88ee13d95e3)

Thanks!

**Comment by v-sudkharat** [comment]
Hi @BSteiner9, this data connector issue needs to be further investigation. could you please create a support case for this issue? so, support team can connect with you to get more details that are needed about the problem and assist you in fixing it. Thanks!
