### ISSUE TITLE
Continuation of issue 8362 [Successful logon from IP and failure from a different IP ]

### ISSUE THREAD

**Issue by best-geek** [Azure/Azure-Sentinel#8882]
**Describe the bug**
Successful login from IP and failure from different IP is currently broken. It will still alert if the IPs are the same when they are IPV6 because this rule does not account for IPV6 address parsing. 

The issue was discussed with a potential fix in [Issue 8362](https://github.com/Azure/Azure-Sentinel/issues/8362) but this was closed before a fix was pushed via a PR. @v-vdixit also helped with creating the fix. 

**Expected Behaviour**
Should avoid triggering on incidents where the failure and the successful login are from the same IP, rather when a successful trigger happens and is followed by a failed IP within 10 minutes on the same app.

**Comment by v-rbajaj** [comment]
Hi @best-geek, will check on this and will get back to you.

**Comment by v-rbajaj** [comment]
Hi @best-geek, I just wanted to confirm that this is the fix you were trying to get pushed on master right?
```
let logonDiff = 10m;
let aadFunc = (tableName:string){
table(tableName)
| where ResultType == "0"
| where AppDisplayName !in ("Office 365 Exchange Online", "Skype for Business Online") // To remove false-positives, add more Apps to this array
| project SuccessLogonTime = TimeGenerated, UserPrincipalName, SuccessIPAddress = IPAddress, AppDisplayName, SuccessIPBlock = strcat(split(IPAddress, ".")[0], ".", split(IPAddress, ".")[1]), Type
| join kind= inner (
    table(tableName)
    | where ResultType !in ("0", "50140")
    | where ResultDescription !~ "Other"
    | where AppDisplayName !in ("Office 365 Exchange Online", "Skype for Business Online") // To remove false-positives, add more Apps to this array
    | project FailedLogonTime = TimeGenerated, UserPrincipalName, FailedIPAddress = IPAddress, AppDisplayName, ResultType, ResultDescription, Type
) on UserPrincipalName, AppDisplayName
| where SuccessLogonTime < FailedLogonTime and FailedLogonTime - SuccessLogonTime <= logonDiff and FailedIPAddress !startswith SuccessIPBlock
| summarize FailedLogonTime = max(FailedLogonTime), SuccessLogonTime = max(SuccessLogonTime) by UserPrincipalName, SuccessIPAddress, AppDisplayName, FailedIPAddress, ResultType, ResultDescription, Type
| extend timestamp = SuccessLogonTime
};
let aadSignin = aadFunc("SigninLogs");
let aadNonInt = aadFunc("AADNonInteractiveUserSignInLogs");
union isfuzzy=true aadSignin, aadNonInt
| extend Name = tostring(split(UserPrincipalName,'@',0)[0]), UPNSuffix = tostring(split(UserPrincipalName,'@',1)[0])
| where SuccessIPAddress != FailedIPAddress
```

**Comment by v-rbajaj** [comment]
Hi @best-geek, would really appreciate your response on this. Waiting for confirmation.

**Comment by best-geek** [comment]
Hi @v-rbajaj , yes, that will resolve the initial issue :)

**Comment by v-rbajaj** [comment]
Hi @best-geek, thanks for confirmation, we are currently testing the rule, will raise a PR by 14 Aug 2023.

**Comment by v-rbajaj** [comment]
Hi @best-geek, we need to confirm the fix and so after it is verified, will raise a PR . Sorry for delay in response.

**Comment by best-geek** [comment]
@v-rbajaj  no problem! :)

**Comment by v-rbajaj** [comment]
Hi @best-geek, the query has been updated 4 days ago based on other users feedback, can you please check if that solves the issue?
https://github.com/Azure/Azure-Sentinel/blob/master/Solutions/Azure%20Active%20Directory/Analytic%20Rules/SuccessThenFail_DiffIP_SameUserandApp.yaml

**Comment by v-rbajaj** [comment]
Hi @best-geek, would appreciate your response. Thanks.

**Comment by v-rbajaj** [comment]
Hi @best-geek, 
Gentle Reminder: We are awaiting for your response on this issue. If you still need to keep this issue active please respond on it in the next 2 days . If we don't receive response, we will be close this issue.

**Comment by best-geek** [comment]
Hi @v-rbajaj! Apologies. Yes, this fixes my issue. Happy for this one to be closed off.

**Comment by best-geek** [comment]
Resolved by updating yaml rule file with altered KQL that can parse IPv6
