### ISSUE TITLE
UserMap workbook not working properly

### ISSUE THREAD

**Issue by fbinotto** [Azure/Azure-Sentinel#889]
**Describe the bug**
I get the following error when running this workbook.

Location Info Column is missing. Please check map settings.

**To Reproduce**
1. Just load the workbook
2. Select the workspace and a timerange

**Expected behavior**
Map populated with signin locations.

**Screenshots**
![image](https://user-images.githubusercontent.com/17077662/88138699-854b7480-cc31-11ea-8bcd-8d222de1b998.png)

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Windows 10
 - Browser [e.g. chrome, safari] Chrome
 - Version [e.g. 22] 84

**Smartphone (please complete the following information):**

**Additional context**

**Comment by CliveW-MSFT** [comment]
Hello.  I'm starting to update this workbook, is there anything you'd like me to add or think about?
