### ISSUE TITLE
Palo Alto Workbooks Error / no results showing with correct configs and data logs

### ISSUE THREAD

**Issue by johnB007** [Azure/Azure-Sentinel#8893]
@devikamehra 
**Describe the bug**
**To Reproduce**
1. Go to - Microsoft Sentinel, activate Palo Alto Data Network Firewall Connector, deploy Palo Alto Workbooks (Palo Alto Overview/Network Threat) in content hub and follow all directions.
2. Click on Workbooks and then (1) Palo Alto Overview and open.
3. Scroll down to Web Filter, Top 5 allowed URLs, and everything below it. All say "query returned no results". All products that require data/graphs in this workbook have been verified on network. ( 2nd Workbook), Palo Alto Network Threat, Entire workbook  has  "query returned no results" except Top correlation events section at bottom
4. See error: "query returned no results" with attached screenshots

**Expected behavior**
Both workbooks show all graphics, data, etc in each section as all products have licenses and confirmed in logs and setup correctly per connectors.

**Screenshots**
See attacched

**Desktop (please complete the following information):**
 - OS: WIN 11 , 22H2
 - Browser  Edge
 - Version 118.0.2060.0

**Smartphone (please complete the following information):**
 - Device: NA
 - OS: NA
 - Browser NA
 - Version NA

**Additional context**

Several other customer environments to include Microsoft demo environment, reproduces the exact same exact behavior and result with no graphics or data in both workbooks. 

![msedge_wL6Jb2CAwM](https://github.com/Azure/Azure-Sentinel/assets/49559203/47ba57bb-71a9-4b8a-89fe-faadb60f1284)
![msedge_QypoUNUyHM](https://github.com/Azure/Azure-Sentinel/assets/49559203/e4598a13-d6c9-4f11-a98d-a4c48f4126e6)
![msedge_j4aKj1xm2x](https://github.com/Azure/Azure-Sentinel/assets/49559203/816e2a48-22a6-4923-b9f3-14b7fccc4001)
![msedge_ENt0QEQnBI](https://github.com/Azure/Azure-Sentinel/assets/49559203/ac4fb0e7-83b4-407f-94da-c49e0c655551)

**Comment by v-sudkharat** [comment]
Hi @johnB007, thanks for flagging this issue, we will soon get back to you on this. Thanks!

**Comment by v-sudkharat** [comment]
1. Hi @johnB007, please run the below query in your workspace and share the results to check for the Activity, DeviceEventClassID, DeviceAction details.

2. As the query for web filter is on activity as **threat**  that must be the reason the data is not rendering, please check for the activity type for your data by below query, thanks.
```
CommonSecurityLog
| where DeviceProduct has 'PAN-OS'
| where DeviceVendor =~ 'Palo Alto Networks'
| distinct Activity, DeviceEventClassID, DeviceAction
```

**Comment by johnB007** [comment]
@v-sudkharat - I ran the query and it doesn't have threat for activity type but wildfire is active with the license and showing in wildfire GUI.  Some data is shown in the workbooks but a majority is not. Not sure why Threat would populate in "some places" in workbook, with some graphics/data but not the rest. If you have an explanation or if the workbook needs updating, it would be most helpful.  Thanks.
![msedge_yKqtYJBYkF](https://github.com/Azure/Azure-Sentinel/assets/49559203/c44827fe-c7a9-4bc2-85d9-6cbabc94faf5)
![msedge_mLFwQsfyCi](https://github.com/Azure/Azure-Sentinel/assets/49559203/725e21f2-1c0e-4806-8fa7-945ace2d12d0)
![msedge_Djfs2cbqHt](https://github.com/Azure/Azure-Sentinel/assets/49559203/4c8ce610-7661-4a9a-943b-0d47f3bbb589)

**Comment by v-sudkharat** [comment]
Hello @johnB007, we are checking this issue, and we will get back to you. Thanks.

**Comment by johnB007** [comment]
Further inspection, break / inspect on logs isnt formatted thus no wildfire alerts/logs
