### ISSUE TITLE
Missing requiredDataConnectors in analytic rules

### ISSUE THREAD

**Issue by Kaloszer** [Azure/Azure-Sentinel#8905]
**Describe the bug**
Analytic rules contain the requiredDataConnectors property - which should reflect required connectors and tables used for queries. However, some of them do not contain everything required for them. 

Eg. 
https://github.com/Azure/Azure-Sentinel/blob/master/Detections/MultipleDataSources/RunCommandUEBABreach.yaml

Requires BehaviorAnalytics table to be available which is part of UEBA, no BehaviorAnalytics in requiredDataConnectors

Eg. where this is used in the query and it exists in the aforementioned field
https://github.com/Azure/Azure-Sentinel/blob/master/Solutions/Azure%20Active%20Directory/Analytic%20Rules/SuccessThenFail_DiffIP_SameUserandApp.yaml

**To Reproduce**

Try to deploy `RunCommandUEBABreach.yaml` with BehaviorAnalytics table missing

**Expected behavior**

Every required data source to run a query should be available in the rule definition. If it is not `required` for the query to execute it should not be there.

**Additional context**
This can be used to validate whether an analytic rule would be successful in deploying to an environment or would fail due to a missing table.

**Comment by Kaloszer** [comment]
Added what I found initially into #8908. But I suppose that if I found a few there's more that have a similar issue.

**Comment by v-sudkharat** [comment]
Hi @Kaloszer, thanks for flagging this issue, we will soon get back to you on this. Thanks!
