### ISSUE TITLE
OneLogin Parser - OneLogin

### ISSUE THREAD

**Issue by katerobson08** [Azure/Azure-Sentinel#8912]
**Describe the bug**
I have been trying to use the parser for OneLogin but get an error as there seems to be 7 fields missing form the table(OneLogin_CL).
The fields are:
app_name_s
              app_id_d
              role_name_s
              role_id_d
              user_attributes_username_s
              user_attributes_department_s
              user_attributes_title_s

**To Reproduce**
1. Install OneLogin Parser
2. Go to **Sentinel -> Logs**
3. Run the parser OneLogin
4. Error "project-rename: Failed to resolve column reference 'app_name_s'"

**Expected behavior**
To produce parsed table

**Screenshots**
![image](https://github.com/Azure/Azure-Sentinel/assets/98545637/b6ca5b80-a528-44b9-a406-866a365070c9)

Fields removed:
![image](https://github.com/Azure/Azure-Sentinel/assets/98545637/9f41fdf3-ce5f-403a-ad8b-a3fd88fcc65a)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Edge
 - Version Version 116.0.1938.62

**Smartphone (please complete the following information):**

**Additional context**

**Comment by v-sudkharat** [comment]
Hi @katerobson08, thanks for flagging this issue, we will soon get back to you on this. Thanks!

**Comment by v-sudkharat** [comment]
Hi @katerobson08, can you please share the table schema with us, so we check the failed column in parser. Thanks
Sharing the query to get the schema: 
```
OneLogin_CL
| getschema  
```

**Comment by v-sudkharat** [comment]
Hello @katerobson08, hope you are doing well. Can you please share the table schema, so we check the failed column in parser. 
Sharing the steps to get the schema. 
1. Go to your workspace and click Logs. 
2. Run the below mentioned query in Logs 
![image](https://github.com/Azure/Azure-Sentinel/assets/132428394/209f854a-c3a7-4988-9491-83abb8c40409)

Thanks!

**Comment by v-sudkharat** [comment]
Hi @katerobson08, Gentle Reminder: We are waiting for your response on this issue. If you still need to keep this issue active, please respond on it in the next 2 days. If we don't receive response by 12-09-2023 date, we will be close this issue. Thanks!

**Comment by katerobson08** [comment]
So sorry, I missed your email.  Here is the schema you require.

[cid:051a6eeb-d9d4-4954-ae0c-f60d26fcd787]




Kate

__
Kate Robson
Senior Security Engineer (Connectors)
+447984320764
***@***.***
 
Quorum Cyber Security Limited
​Registered Office: First Floor Suite (West Wing), Verdant, 2 Redheughs Rigg, South Gyle, Edinburgh, EH12 9DQ
​Registered Number: SC510322. Registered in Scotland
________________________________
From: v-sudkharat ***@***.***>
Sent: Tuesday, September 12, 2023 9:10 AM
To: Azure/Azure-Sentinel ***@***.***>
Cc: Kate Robson ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] - Re: [Azure/Azure-Sentinel] OneLogin Parser - OneLogin (Issue #8912)

Caution: This email originated from outside of the organisation. Do not click links or open attachments unless you recognise the sender and know the content is safe.


Hi @katerobson08<https://github.com/katerobson08>, Gentle Reminder: We are waiting for your response on this issue. If you still need to keep this issue active, please respond on it in the next 2 days. If we don't receive response by 12-09-2023 date, we will be close this issue. Thanks!

**Comment by v-sudkharat** [comment]
Hi @katerobson08, we are unable to see the schema which you shared, please can you share the schema by referring above comment. Thanks!

**Comment by v-sudkharat** [comment]
@katerobson08, we are waiting for your response. Thanks!

**Comment by v-sudkharat** [comment]
Hello @katerobson08, Gentle Reminder: We are still waiting for your response on this issue. If you still need to keep this issue active, please respond on it in the next 2 days. If we don't receive response by 20-09-2023 date, we will be close this issue. Thanks!

**Comment by v-sudkharat** [comment]
Hello @katerobson08, since we have not received a response in the last 5 days, we are closing your issue #8912 as per our standard operating procedures. If you still need support for this issue, feel free to re-open at any time. Thank you for your co-operation.

**Comment by katerobson08** [comment]
So sorry, I think I replied to the wrong email address.  Here is the schema you require.

[cid:feb1454c-4278-4d75-9315-1f67d82fe24f]




Kate

__
Kate Robson
Senior Security Engineer (Connectors)
+447984320764
***@***.***
 
Quorum Cyber Security Limited
​Registered Office: First Floor Suite (West Wing), Verdant, 2 Redheughs Rigg, South Gyle, Edinburgh, EH12 9DQ
​Registered Number: SC510322. Registered in Scotland
________________________________
From: v-sudkharat ***@***.***>
Sent: Tuesday, September 12, 2023 12:23 PM
To: Azure/Azure-Sentinel ***@***.***>
Cc: Kate Robson ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] - Re: [Azure/Azure-Sentinel] OneLogin Parser - OneLogin (Issue #8912)

Caution: This email originated from outside of the organisation. Do not click links or open attachments unless you recognise the sender and know the content is safe.


Hi @katerobson08<https://github.com/katerobson08>, we are unable to see the schema which you shared, please can you share the schema by referring above comment. Thanks!

**Comment by katerobson08** [comment]
Sorry, hopefully you can see this.

![image](https://github.com/Azure/Azure-Sentinel/assets/98545637/2c83c500-5c68-43e8-a701-2e28b7a58405)






Kate
