### ISSUE TITLE
Netskope Function uploads to Netskope_CL but workbook does not refer to the table

### ISSUE THREAD

**Issue by anthonysomerset** [Azure/Azure-Sentinel#8938]
**Describe the bug**
Netskope Data Connector ingests to the Netskope_CL table, however the provided workbook is expecting data to exist in the following tables:

Netskope_Events_CL
Netskope_Alerts_CL
Netskope_WebTX_CL

as a result the workbook does not work

**To Reproduce**
1. Deploy Netskope connector from content hub and deploy all the neccesary resources
2. Allow data to be ingested
3. attempt to view workbook

**Expected behavior**
Workbook should work, either by updating it to refer to correct tables or update the connector function and/or parser to support the new tables

**Screenshots**

**Desktop (please complete the following information):**
 - OS: MacOS Ventura
 - Browser: Chrome
 - Version 116.0.5845.110 (Official Build) (arm64)

**Additional context**
Guessing that something is out of sync between the connector/parser and the workbook

**Comment by v-sudkharat** [comment]
Hi @anthonysomerset, thanks for flagging this issue, we will soon get back to you on this. Thanks!

**Comment by v-rbajaj** [comment]
Hi @anthonysomerset, we have reached out to concerned team for this issue, we will get back once there is an update.

**Comment by v-rbajaj** [comment]
Hi @anthonysomerset, we have reached out to concerned team for this issue, we will get back once there is an update.

**Comment by v-rbajaj** [comment]
Hi @anthonysomerset, we have reached out to concerned team for this issue, we will get back once there is an update.

**Comment by v-rbajaj** [comment]
Hi @anthonysomerset, we have reached out to concerned team for this issue, we will get back once there is an update.

**Comment by v-rbajaj** [comment]
Hi @anthonysomerset, we have reached out to concerned team for this issue, we will get back to you by 11 Oct 2023.

**Comment by rahul0216** [comment]
Hello @anthonysomerset, thank you for raising the issue.
This solution has been developed and maintained by Netskope. 

Netskope uses Log Shipper to push logs to Microsoft Sentinel. In Log Shipper user have option to provide table name but they suggest default names like Netskope_Events_CL, Netskope_Alerts_CL, Netskope_WebTX_CL etc, so that provided workbook and playbook can function properly.
You can read the details [here](https://docs.netskope.com/en/netskope-help/integrations-439794/netskope-cloud-exchange/log-shipper-module/configure-3rd-party-log-shipper-plugins/microsoft-azure-sentinel-plugin-for-log-shipper/).

Looks like workbook is not yet updated to support Azure Functions app based connector ingested data.

**Comment by anthonysomerset** [comment]
so i don't have Log Shipper at all

I am going off the original instructions in Sentinel and this Repo - this suggests that the instructions are wrong or incomplete or out of date. This should be rectified depending on what the correct situation is

**Comment by anthonysomerset** [comment]
from what i can tell, log shipper/cloud exchange is NEW functionality relative to the azure function based solution

I think the right way forward is to deprecate the azure function approach in favour of linking to the Netskope documentation for Cloud Exchange/Log Shipper  and the documentation updated to reflect that

**Comment by rahul0216** [comment]
Hi @anthonysomerset, hopefully you are unblocked.    
Yes, looks like instructions are out of date which is causing the confusion. We will reach out to Netskope support to look into it.

In the meantime, if you are a Netskope customer, you can reach out to them as well for clarification and latest instructions.

**Comment by rahul0216** [comment]
Hi @elforb, I see you are original committer of [Netskope Solution](https://github.com/Azure/Azure-Sentinel/commits/master/Solutions/Netskope). Can you please have a look @anthonysomerset concerns?

**Comment by v-rbajaj** [comment]
Hi @elforb, can you please look into the above comment?

**Comment by v-rbajaj** [comment]
Hi @elforb, can you please look into the above comment, would really appreciate your response here.

**Comment by v-rbajaj** [comment]
Hi @anthonysomerset, thanks for raising this concern here. But since this solution is partner supported you would need to raise a ticket in Netskope support queue. Please raise this concern with them here - https://www.netskope.com/services#support
