### ISSUE TITLE
Incorrect name in two EmptyCustomUnifyingParsers json files

### ISSUE THREAD

**Issue by sarathynature** [Azure/Azure-Sentinel#8939]
**Describe the bug**
Instead of providing this name ASim_AuditEventCustom, wrong name(ASim_DnsCustom) has been updated in below 1st link.
Instead of providing this name Im_AuditEventCustom, wrong name(Im_DnsCustom) has been updated in below 2nd link.

https://github.com/Azure/Azure-Sentinel/blob/master/ASIM/deploy/EmptyCustomUnifyingParsers/ASim_AuditEventCustom.json

https://github.com/Azure/Azure-Sentinel/blob/master/ASIM/deploy/EmptyCustomUnifyingParsers/Im_AuditEventCustom.json

**To Reproduce**
You can see code directly in the above two links

**Expected behavior**
The "name" should be replaced by "function alias" name in resources section.

**Comment by v-sudkharat** [comment]
Hi @sarathynature, thanks for flagging this issue, we will soon get back to you on this. Thanks!

**Comment by vakohl** [comment]
@sarathynature thankyou for sharing this issue. PR has been raised, soon this would be corrected. Thankyou for your contribution
https://github.com/Azure/Azure-Sentinel/pull/8978

**Comment by v-sudkharat** [comment]
Hello @sarathynature, PR has been Merged with the corrections. Closing this issue. If you still need support for this issue, feel free to re-open it any time. Thank you for your co-operation.
