### ISSUE TITLE
Qualys connector not parsing login correctly

### ISSUE THREAD

**Issue by iukea1** [Azure/Azure-Sentinel#894]
Hello,

Currently having an issue with the Qualys connector where it is coming back with an HTTP bad login response. I verified that my login credentials are correct and able to hit the API by hand using postman and I am able to get a successful response.

When running the Qualys function deployed out with the ARM template  I get the following error shown below 
![image](https://user-images.githubusercontent.com/35882815/88250901-ada59400-cc6e-11ea-83f6-ef8392a2fdef.png)

[](https://github.com/Azure/Azure-Sentinel/tree/master/DataConnectors/Qualys%20VM)

**Comment by chicduong** [comment]
@iukea1 does the password to the Qualys account password have special characters? a back slash/forward slash perhaps?

**Comment by iukea1** [comment]
@chicduong it has a + in it.

Do you think that is what is causing this issue?

**Comment by chicduong** [comment]
It very well could be, we've had a customer where it was the case. If you change the password to just numbers and letters does it resolve it?

**Comment by chicduong** [comment]
@iukea1 It very well could be, we've had a customer where it was the case. If you change the password to just numbers and letters does it resolve it?

**Comment by chicduong** [comment]
@iukea1 you can modify the password in the Function App -> Configuration blade, so you don't have to redeploy the Function App

**Comment by iukea1** [comment]
> @iukea1 you can modify the password in the Function App -> Configuration blade, so you don't have to redeploy the Function App

So in Qualys your password must have a special character and one uppercase character.

I reset the password just to be on the safe side and change the special char from a +  to a !  to see if that would help or change anything. 

Sadly it was not a success 


My URL settings are as follows. 
- Is this the correct layout and format for the URL? 
https://qualysapi.qg3.apps.qualys.com/api/2.0/fo/asset/host/vm/detection/?action=list&vm_processed_after=
![image](https://user-images.githubusercontent.com/35882815/88443403-d4cea380-cddd-11ea-9afc-66d3256992b4.png)

**Comment by chicduong** [comment]
@iukea1 yes that URI is correct. Are you getting a successful response from Postman with the same header information? 

Also, do you have any IP restrictions configured in Qualys?

**Comment by iukea1** [comment]
I figured out the issue :D

Ohhhhhhh azure how you are not like AWS.... 

Now I have a new issue. It is not syncing back the old vulnerability data and it is looking like that is because the functions pulls from last date and time  from when the function last ran.

So  (function last ran here ) pull from here to current time.

**Comment by chicduong** [comment]
@iukea1 glad you were able to resolve it. Is it something that could be prevented within the Function? or was it something what was overlooked?

Could you elaborate a little further on the new issue? Where would the last ran time need to be in that situation?

**Comment by preetikr** [comment]
Closing this thread owing to inactivity for the past month.

**Comment by Mindstate08** [comment]
bump.

Having this exact issue! @iukea1 what was the solution here? It sounds like the problem is within the Azure function...?

**Comment by Ascampbe** [comment]
Hey @iukea1  Can you let me know what your solution was with the Qualys connector?
