### ISSUE TITLE
Bug: Isolate endpoint - MDE - Not running when it's triggered

### ISSUE THREAD

**Issue by costaluisc** [Azure/Azure-Sentinel#8941]
**Describe the bug**
When using the "Isolate endpoint - MDE" playbook template, the playbook is not always executed. When it's triggered manually from the incidente page it runs, but when its triggered from automation rule it does not.
**To Reproduce**
1. Use the "Isolate endpoint - MDE" playbook template to create a playbook
2. Setup all the appropriate permissions for the logic app to isolate a device and write comments to the incident
3. Create an Automation rule with Trigger: "When incident is created" and choose the newly created playbook
4. Trigger an incident in MDE, wait until it streams to Sentinel.
5. Notice that the playbook fails on action "Isolate machine" with error "Missing application roles. API required roles: Machine.Isolate, application roles: ."
6. Now go back to the Incident --> Actions --> Run playbook and choose the same playbook that was triggered automatically
7. Notice that it now succeeded to run the logic app.

**Expected behavior**
The playbook must be able to run with triggered by automation rule

**Screenshots**
![image](https://github.com/Azure/Azure-Sentinel/assets/97606048/5e846f53-6938-4320-8c91-bd38d2941a2c)
![image](https://github.com/Azure/Azure-Sentinel/assets/97606048/7a159297-a6ac-4ee5-bc47-5eb46e41e70f)
![image](https://github.com/Azure/Azure-Sentinel/assets/97606048/20cff792-2875-4700-8faa-011ba10b8ce9)

**Additional context**
M365 E5 License

**Comment by v-sudkharat** [comment]
Hi @costaluisc, thanks for flagging this issue, we will soon get back to you on this. Thanks!

**Comment by costaluisc** [comment]
Your welcome @v-sudkharat.
If you need more information please let me know

**Comment by v-rbajaj** [comment]
Hi @costaluisc, sure, will get back to you if we need any more details.

**Comment by rahul0216** [comment]
Hi @costaluisc, can you please check if you have installed two instances of playbook in different resource groups? 
In my testing, Playbook is executing fine both ways?

**Comment by v-rbajaj** [comment]
Hi @costaluisc, Gentle Reminder: We are awaiting for your response on this issue. If you still need to keep this issue active please respond on it in the next 2 days . If we don't receive response, we will be close this issue.

**Comment by v-rbajaj** [comment]
Hi @costaluisc, Since we have not received a response in the last 5 days, we are closing your issue #8941 as per our standard operating procedures. If you still need support for this issue, feel free to re-open at any time. Thank you for your co-operation

**Comment by costaluisc** [comment]
> Hi @costaluisc, can you please check if you have installed two instances of playbook in different resource groups? In my testing, Playbook is executing fine both ways?

Sorry for the delay. No I only have the playbook deployed in that resource group.
After some time messing with the playbook it started working again.
Thanks for the help
