### ISSUE TITLE
Broken Entity Mapping in Azure Active Directory rule template

### ISSUE THREAD

**Issue by goosvorbook** [Azure/Azure-Sentinel#8946]
**Describe the bug**
One of the "Azure Active Directory" Analytic rules from the Content hub have a mismatch on their entity mapping.

Rule:
"Successful logon from IP and failure from a different IP"
Does not actually contain name and UPNSuffix

**To Reproduce**
1. Install Analytic Rule
2. Open the entity mapping
3. Check if the value actually exists

**Expected behavior**
Full entity mapping with the correct fields, e.g. Name and UPNSuffix, this requires a rewrite of the KQL to actually contain the Name and UPNSuffix

**Screenshots**
![image](https://github.com/Azure/Azure-Sentinel/assets/23636293/68896110-5651-43ec-bc09-9c8b6f84f84e)

**Comment by v-sudkharat** [comment]
Hi @goosvorbook, thanks for flagging this issue, we will soon get back to you on this. Thanks!

**Comment by v-sudkharat** [comment]
Hi @goosvorbook, we are looking into this issue, please can you add below shared KQL query while create an analytic rule and let us know if it works for you.

`| extend Name = tostring(split(UserPrincipalName,'@',0)[0]), UPNSuffix = tostring(split(UserPrincipalName,'@',1)[0])  `

Sharing the steps and screenshot for reference.
1. While create analytic rule click on Set rule logic
![image](https://github.com/Azure/Azure-Sentinel/assets/132428394/56fc3db1-d4b4-4cbd-96f2-e00cd3cbedaf)

2. Add the above query after- `union isfuzzy=true aadSignin, aadNonInt`.
![image](https://github.com/Azure/Azure-Sentinel/assets/132428394/90279838-b9a9-45f8-bd94-33490a4d60a6)

3. Select the "Name" and "UPNSuffix" in the dropdown and processed further to create rule.  

Thanks.

**Comment by goosvorbook** [comment]
Yes that will work

**Comment by v-sudkharat** [comment]
Hello @goosvorbook, please can you let us know the above shared steps are work for you? Thanks

**Comment by goosvorbook** [comment]
yes they did

**Comment by v-sudkharat** [comment]
@goosvorbook, Thanks for sharing the update, we will raise the PR with the changes. can we close this issue? please let us know if you need any further assistance. Thanks
