### ISSUE TITLE
Different Alert Descriptions from MDI and Sentinel

### ISSUE THREAD

**Issue by jeffrywu28** [Azure/Azure-Sentinel#8965]
**Describe the bug**
There is a significant difference number descriptions when you are see M365 Portal Alert and Sentinel Alert.

**To Reproduce**
1. Go to m365 Defender portal
2. Click on Alert > filter the alert named "Suspicious Brute-force attack (LDAP)" alert from MDI > Click for details
3. Scroll down to Descriptions
4. Then Go to sentinel portal 
5. Click on Alert > choose the same alert. "Suspicious Brute-force attack (LDAP)"
7. See the really different number

**Expected behavior**
Same Number from m365 Portal and sentinel.

**Screenshots**
![image](https://github.com/Azure/Azure-Sentinel/assets/47622164/c815afa5-778d-4362-8742-e4f0627139b8)
![image](https://github.com/Azure/Azure-Sentinel/assets/47622164/2b632c1b-0a8b-4d83-9a0c-83b9b1d7ee91)

**Additional context**
It's such a huge different right? but why?

**Comment by v-sudkharat** [comment]
Hi @jeffrywu28, thanks for flagging this issue, we will soon get back to you on this. Thanks!

**Comment by jeffrywu28** [comment]
> Hi @jeffrywu28, thanks for flagging this issue, we will soon get back to you on this. Thanks!

Any updates?

**Comment by v-sudkharat** [comment]
Hello @jeffrywu28, we are connecting with our concerned team for this issue, once we get any information on this, we will update you. Thanks!

**Comment by v-sudkharat** [comment]
Hello @jeffrywu28, Apologies for the inconvenience and delay. This issue needs to be further investigation. could you please create a support case for this issue? so, support team can connect with you to get more details that are needed about the problem and assist you in fixing it.
Please confirm us once you raise a support case so that we can close this issue from GitHub.
Thanks!

**Comment by v-sudkharat** [comment]
Hello @jeffrywu28, could you please let us know if you have raised a support case and got assistance for this issue? so we can close this issue from GitHub.

**Comment by v-sudkharat** [comment]
Hi @jeffrywu28, Gentle Reminder: We are waiting for your response on this issue. If you still need to keep this issue active, please respond to it in the next 2 days. If we don't receive a response by 28-09-2023 date, we will be closing this issue. 		
Thanks!

**Comment by v-sudkharat** [comment]
Hi @jeffrywu28, since we have not received a response in the last 5 days, we are closing your issue #8965 as per our standard operating procedures. If you still need support for this issue, feel free to re-open at any time. Thank you for your co-operation.
