### ISSUE TITLE
Not all ExchangeAdmin audit logs are being collected, like New-InboxRule

### ISSUE THREAD

**Issue by bstmor** [Azure/Azure-Sentinel#8970]
**Describe the bug**
With _Microsoft 365 (formerly, Office 365)_ data connector, ExchangeAdmin audit logs are being collected from O365 to Sentinel, including logs with the "Operation" field set to "New-InboxRule" or "Set-InboxRule". 
However, when using _O365 Data_ [https://github.com/Azure/Azure-Sentinel/tree/aea89e0c15f28a209046e61c56c5ce7b18eca6b5/DataConnectors/O365%20Data](url) to collect O365 ExchangeAdmin audit logs from a different tenant as the tenant where Sentinel is located, logs with "Operation" set to "New-InboxRule" or "Set-InboxRule" are not collected. Even if other Exchange admin audit logs are collected.

**Steps to reproduce the behavior**:
1. 2 tenants, 1 with Sentinel, 1 with O365 environment
2. Deploy O365 Data to collect ExchangeAdmin audit logs from the tenant with O365 and send those logs to Sentinel
3. ExchangeAdmin audit logs are being received but no logs where field "Operation" has the value "New-InboxRule" or "Set-InboxRule"

**Expected behavior:**
Receiving "New-InboxRule" or "Set-InboxRule" logs
![image](https://github.com/Azure/Azure-Sentinel/assets/144374859/36516121-294e-4cc8-a929-6937bd64afdc)

**Comment by v-sudkharat** [comment]
Hi @bstmor, thanks for flagging this issue, we will soon get back to you on this. Thanks!

**Comment by v-rbajaj** [comment]
Hi @bstmor, Please check these troubleshooting steps 

Check Permissions: Ensure that the account you are using to collect logs from the different tenant has the necessary permissions to access and collect ExchangeAdmin audit logs. You typically need Global Administrator or Security Administrator privileges in the source tenant. Double-check the permissions of the account and verify that it has the necessary roles assigned.

Audit Logging Enabled: Confirm that audit logging is enabled in the source tenant for the specific activities you want to collect logs for (i.e., "New-InboxRule" and "Set-InboxRule"). Audit logging settings can be managed in the Security & Compliance Center.

Audit Log Retention: Ensure that the audit logs you are trying to collect have not exceeded their retention period. Audit logs are retained for a certain duration, and you may not be able to collect logs that have already been purged.

Advanced Audit Settings: In some cases, the specific activities you want to collect may not be included in the default auditing settings. You might need to enable advanced auditing settings for those activities. Go to the Security & Compliance Center and check if advanced auditing is enabled for "New-InboxRule" and "Set-InboxRule."

Connector Configuration: Double-check the configuration of the O365 Data connector in Azure Sentinel. Ensure that you have correctly specified the source tenant's details, including the application ID, client secret, and other relevant settings. Make sure that the connector is set up to collect ExchangeAdmin audit logs.

Data Connector Logs: Review the logs and diagnostics provided by the O365 Data connector in Azure Sentinel. These logs can often provide detailed information about any errors or issues that are preventing the collection of specific logs.

Network and Firewall Considerations: Check for any network or firewall issues that might be blocking the data collection process. Ensure that the necessary ports and protocols are open for communication between the source tenant and Azure Sentinel.

Update Connector: Make sure you are using the latest version of the O365 Data connector. Sometimes, updating the connector to the latest version can resolve known issues and improve compatibility.

**Comment by v-rbajaj** [comment]
Gentle Reminder: We are awaiting for your response on this issue. If you still need to keep this issue active please respond on it in the next 2 days. If we don't receive response, we will be close this issue.

**Comment by bstmor** [comment]
Hi,

Thank you for the reply.


Check Permissions: _I will double check on that but I think it is OK._

Audit Logging Enabled: Audit log is enable indeed. We can see these"New-InboxRule" logs on the source tenant. 

Audit Log Retention: They are new logs everyday, so I should be able to collect them.

Advanced Audit Settings: As we can see those logs on the source tenant, I think the configuration is OK, _I will double check._

Connector Configuration: The connector is correctly configured as I can received ExchangeAdmin audit logs

Data Connector Logs: _Could you tell me where I can access theses logs ?_

Network and Firewall Considerations: The firewalls are correctly configured as I can received ExchangeAdmin audit logs

Update Connector: I'm using the last version

Regards,

**Comment by v-rbajaj** [comment]
Hi @bstmor,

Accessing the logs for a Data Connector in Azure Sentinel depends on the specific connector you are using. Here are the general steps to access Data Connector logs:

Azure Sentinel Portal: To access logs for most Data Connectors, you can start by logging into the Azure Sentinel portal:

Go to the Azure portal (https://portal.azure.com/).
Navigate to your Azure Sentinel workspace.
Data Connector Configuration: In the Azure Sentinel workspace, you'll find a section for Data connectors. Select the Data Connector you want to review logs for. Click on the specific Data Connector configuration you are interested in.

Logs and Diagnostics: Within the Data Connector configuration page, there should be an option or tab for "Logs" or "Diagnostics." This is where you can access logs related to the connector's activities.

Log Types: Depending on the connector, you may have access to different types of logs, including status logs, ingestion logs, and error logs. These logs can provide information about the connector's performance and any issues encountered during data collection.

Filter and Search: You can typically filter and search these logs to find specific information or errors related to the Data Connector's activities.

Export or Download Logs: In some cases, you may have the option to export or download logs for further analysis or troubleshooting.

**Comment by v-rbajaj** [comment]
Gentle Reminder: We are awaiting for your response on this issue. If you still need to keep this issue active please respond on it in the next 2 days . If we don't receive response, we will be close this issue.

**Comment by v-rbajaj** [comment]
Since we have not received a response in the last 5 days, we are closing your issue #8970 as per our standard operating procedures. If you still need support for this issue, feel free to re-open at any time. Thank you for your co-operation

**Comment by yokhaldi** [comment]
Hi @v-rbajaj, i have another customer who met the same problem. They have multiple tenants and they need to collect Office 365 logs from x tenants to centralized tenant where Sentinel is enabled. They cannot use the Office 365 connector in Sentinel as it will collect only from the current tenant where this connector is enabled, so the only solution is to pass through the custom function https://github.com/Azure/Azure-Sentinel/tree/master/DataConnectors/O365%20Data but they cannot see these tow operations in Sentinel « New-InboxRule » et « Set-InboxRule ». As it's critical, can you please support ? thanks

**Comment by bstmor** [comment]
Hi [v-rbajaj](https://github.com/v-rbajaj),
Is it possible to re-open this issue please ?

Regards,
