### ISSUE TITLE
KV reference in Linux (Python) Function Apps

### ISSUE THREAD

**Issue by DiaAyyad** [Azure/Azure-Sentinel#8979]
**Describe the bug**
When I deploy a Funtion App Linux based using (Python) (in my case Box connector) I noticed I can't retrieve the secrets from KV although I have managed Identity enabled and using the right secret

**To Reproduce**
1. Function App Linux Based (Python based Function)
2. on the overview page open the function 
3. check monitor page
4. See error "json file couldn't be reached"

**Expected behavior**
1. Used sam format that woked with another Function App (Windows based) and still couldn't retrieve the secret.
2. Tested plain text creds in the configuration page and then the function app starts working.
3. This should work when I reference to a secret in KV

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [Linux]
 - Function App
 - Python

**Additional context**

**Comment by v-sudkharat** [comment]
Hi @DiaAyyad, thanks for flagging this issue, we will soon get back to you on this. Thanks!

**Comment by v-sudkharat** [comment]
Hello @DiaAyyad, just want to know when you deploy a Function App, have you entered the correct "config file content" which is highlighted in below screenshot.

![image](https://github.com/Azure/Azure-Sentinel/assets/132428394/a84ed59a-74fc-4912-8a77-c9e04be26155)
please let us know if you enter filed correctly and still facing same issue. 

Thanks!

**Comment by DiaAyyad** [comment]
Hi @v-sudkharat,
Yes I have used the correct values, this should be Json format which conatins (ClienID, ClientSecret, Public and Private Keys, and enterpriseID)

**Comment by v-sudkharat** [comment]
Hi @DiaAyyad, thanks for your response, we are working this issue, and we will provide an update by 21 Sep 2023. Thanks

**Comment by v-sudkharat** [comment]
Hello @DiaAyyad, as per the first step mentioned on the connector page, have you configured the "setup JWT authentication and obtain JSON file with credentials"? 
If yes,
After generating the "json file," past full contain of "Json file" without any modification in - "Box Config JSON" filed and redeploy the function app.  
Sharing screenshot for reference: -
![image](https://github.com/Azure/Azure-Sentinel/assets/132428394/8fdddb5a-2cc9-481f-9dfc-14869d114cf8)

Thanks!

**Comment by DiaAyyad** [comment]
Hi @v-sudkharat,
The JSON looks like this, 

{
  "boxAppSettings": {
    "clientID": "abc...123",
    "clientSecret": "def...234",
    "appAuth": {
      "publicKeyID": "abcd1234",
      "privateKey": "-----BEGIN ENCRYPTED PRIVATE KEY-----\n....\n-----END ENCRYPTED PRIVATE KEY-----\n",
      "passphrase": "ghi...345"
    }
  },
  "enterpriseID": "1234567"
}

**Comment by v-sudkharat** [comment]
Hi @DiaAyyad, yes please past full contain of that "Json file" without any modification in - "Box Config JSON" and try to deploy the function.
Please let us know once you done. 
Thanks!

**Comment by DiaAyyad** [comment]
Hi @v-sudkharat,
that will make the connector works as expected, but again the secrets will be visibile in the config page, which is not desired 
Thanks

**Comment by v-sudkharat** [comment]
Hi @DiaAyyad,
none of the value will be visible in function app configuration, unless and until you have that function app required access. 
Sharing screenshot for reference -
![image](https://github.com/Azure/Azure-Sentinel/assets/132428394/10a88235-c150-4b06-9a56-a5538b73046b)

Thanks!

**Comment by DiaAyyad** [comment]
Thanks @v-sudkharat,
the question was about when click show values you will see the actual value of secrets (we usually reference the Keyvault for secrets) by using Secret Identifier from KV, example

![image](https://github.com/Azure/Azure-Sentinel/assets/73919947/0b19d56f-3664-4815-a1df-0a473a886131)

**Comment by v-sudkharat** [comment]
Hi @DiaAyyad, that values will visible because those are in configuration for running function app and can be manage the accessibility of function app. 
The image show like workspace key is taken from keyvault, expected value for workspace key is shared key OR workspace key.

Thanks!

**Comment by v-sudkharat** [comment]
Hi @DiaAyyad, we are waiting for your response. Thanks!

**Comment by v-sudkharat** [comment]
Hi @DiaAyyad, Gentle Reminder: We are waiting for your response on this issue. If you still need to keep this issue active, please respond to it in the next 2 days. If we don't receive a response by 03-09-2023 date, we will be closing this issue. 		
Thanks!

**Comment by DiaAyyad** [comment]
Hi @v-sudkharat,
Apologies for the late response, just want to confirm if you have tried storing the json file in your KV and use key Identifier in the config file?
otherwise, you can please go a head and close the ticket 

thanks,

**Comment by v-sudkharat** [comment]
Hi @DiaAyyad, No. 
Thank you for your confirmation. closing this issue. If you still need support for this issue, feel free to re-open it any time. Thank you for your co-operation.
