### ISSUE TITLE
TAXII Feed from Microsoft tutorial error

### ISSUE THREAD

**Issue by jeffrywu28** [Azure/Azure-Sentinel#8988]
**Describe the bug**
Why always error when get the TAXII feed from ms learn
**To Reproduce**
1. Go to TAXII Connector
2. Fill this

Friendly name (for server): PickupSTIX-AbuseIPDB-blacklist
API root URL: 
https://test.pickupstix.io/taxii2/api2/
Collection ID: system.AbuseIPDB_blacklist
Username: guest
Password: guest
Import indicators: "All available"
Polling frequency: Once an hour

**Expected behavior**
Not Error.

**Screenshots**
![image](https://github.com/Azure/Azure-Sentinel/assets/47622164/3fa5b26e-ed23-48c5-a23b-e8cc3d5967f1)

**Comment by v-rbajaj** [comment]
Hi @jeffrywu28, thanks for flagging this issue, we will get back to you soon.

**Comment by jeffrywu28** [comment]
@v-rbajaj any updates?

**Comment by v-rbajaj** [comment]
Hi @jeffrywu28, we have reached out to concerned team, waiting for update from them.

**Comment by v-rbajaj** [comment]
Hi @jeffrywu28, 
You would need to find a working TAXII server, and they may need to add MS Sentinel TAXII client IP Address to the allowlist of the server. Please follow this guide: https://learn.microsoft.com/en-us/azure/sentinel/connect-threat-intelligence-taxii

**Comment by v-rbajaj** [comment]
Hi @jeffrywu28, Since we have not received a response in the last 5 days, we are closing your issue
#8988 as per our standard operating procedures. If you still need support for this issue, feel free to re-open at any time. Thank you for your co-operation.
