### ISSUE TITLE
Content Hub Solution has not correct version (KQL)

### ISSUE THREAD

**Issue by TJ1512** [Azure/Azure-Sentinel#8993]
**Describe the bug**
When installing the Content Hub Solution "KQL Training" the Solution is not installing the correct version of the workbook "Intro to KQL". My guess is that it is installing an outdated version like this one [here](https://github.com/Azure/Azure-Sentinel/blob/master/Workbooks/IntrotoKQL.json) instead of the current properly working Workbook from [here](https://github.com/Azure/Azure-Sentinel/blob/master/Solutions/KQL%20Training/Workbooks/IntrotoKQL.json). 

**To Reproduce**
1. Go to 'Content Hub'
2. Click on 'Install KQL Training Solution'
3. Open Workbook "Intro to KQL"
4. See a wrong output of the json when opening the "json" within the first parameters. And also the Selection for Section is not working properly because here it seems like the query is faulty and the json output is not correct.

**Expected behaviour**
- Installation of the correct workbook version (there is no update available either)

The settings should look like -> Parameter field style: multiline and text editor language: json instead of the values as in the following picture
![Screenshot 2023-09-12 at 15 41 36](https://github.com/Azure/Azure-Sentinel/assets/87079406/63b07d44-2570-45fc-b574-c6421c06d0d6)

And for the "Select Section" it should be like: 
![Screenshot 2023-09-12 at 15 56 33](https://github.com/Azure/Azure-Sentinel/assets/87079406/009b02d1-a46e-42b4-9115-67a2b8c34c47)

instead of 
![Screenshot 2023-09-12 at 15 41 59](https://github.com/Azure/Azure-Sentinel/assets/87079406/5c329241-a2bb-452d-b22c-3d4107ffeb1d)

so it is possible to choose the Section:
![Screenshot 2023-09-12 at 15 54 35](https://github.com/Azure/Azure-Sentinel/assets/87079406/badf08b3-a978-4617-a436-e7cf63a4cb4f)

**Desktop (please complete the following information):**
 - OS: MacOS Ventura 13.5.2
 - Browser: Safari v16.6

**Comment by v-sudkharat** [comment]
Hi @TJ1512, thanks for flagging this issue, we will soon get back to you on this. Thanks!

**Comment by v-rbajaj** [comment]
Hi @TJ1512, 
Wanted to confirm on few things
Are you trying to have Parameter field style: multiline as default ?
And can you please let us know what are you trying to achieve here, so that we can guide you accordingly?

**Comment by TJ1512** [comment]
Hi @v-rbajaj, so first: Yes, I think it is supposed to be multiple line by default if we look [here](https://github.com/Azure/Azure-Sentinel/blob/master/Solutions/KQL%20Training/Workbooks/IntrotoKQL.json). I would also expect that this is the version we should get from the download of the solution via content hub. So that is why I think something is not working properly when downloading the Solution via the content hub. 

When the Solution is downloaded, the workbook shows that it is set to standard and not multiline (see picture), furthermore the Query for getting the Data of the json (see picture) is also not correct. It should be "print tab = todynamic({json:value})" and not "datatable(tab:string)["{json:escapejson}"]" which it is when downloading the solution. 

So for me it looks like the solution is still using an deprecated version like the one [here](https://github.com/Azure/Azure-Sentinel/blob/master/Workbooks/IntrotoKQL.json) instead of the correct version which is working when I download it manually from [here](https://github.com/Azure/Azure-Sentinel/blob/master/Solutions/KQL%20Training/Workbooks/IntrotoKQL.json). 

I hope that made things a bit more clear.

**Comment by v-rbajaj** [comment]
Hi @TJ1512, thanks for the details, will get back to you.

**Comment by v-rbajaj** [comment]
Hi @TJ1512, we are still investigating on this issue, sorry for delay.

**Comment by v-rbajaj** [comment]
Hi @TJ1512, we are still investigating on this issue, sorry for delay will update you by 17 Oct 2023

**Comment by v-sudkharat** [comment]
> Hi @v-rbajaj, so first: Yes, I think it is supposed to be multiple line by default if we look [here](https://github.com/Azure/Azure-Sentinel/blob/master/Solutions/KQL%20Training/Workbooks/IntrotoKQL.json). I would also expect that this is the version we should get from the download of the solution via content hub. So that is why I think something is not working properly when downloading the Solution via the content hub.
> 
> When the Solution is downloaded, the workbook shows that it is set to standard and not multiline (see picture), furthermore the Query for getting the Data of the json (see picture) is also not correct. It should be "print tab = todynamic({json:value})" and not "datatable(tab:string)["{json:escapejson}"]" which it is when downloading the solution.
> 
> So for me it looks like the solution is still using an deprecated version like the one [here](https://github.com/Azure/Azure-Sentinel/blob/master/Workbooks/IntrotoKQL.json) instead of the correct version which is working when I download it manually from [here](https://github.com/Azure/Azure-Sentinel/blob/master/Solutions/KQL%20Training/Workbooks/IntrotoKQL.json).
> 
> I hope that made things a bit more clear.

Hello @TJ1512, We apologies for the delay and appreciate you giving us the information. 
We modified the Solution template by adding the correct workbook ([link](https://github.com/Azure/Azure-Sentinel/blob/master/Solutions/KQL%20Training/Workbooks/IntrotoKQL.json)) version. 
Could you please Custom Deploy the below shared MainTemplate in your workspace and check it working fine for you. 

Sharing the custom deployment steps documentation- https://learn.microsoft.com/en-us/azure/azure-resource-manager/templates/quickstart-create-templates-use-the-portal

MainTemplate Zip - [mainTemplate.zip](https://github.com/Azure/Azure-Sentinel/files/13215855/mainTemplate.zip)

Kindly notify us if this issue persists. 

Thanks!

**Comment by TJ1512** [comment]
Hi @v-sudkharat, seems like it is working now when downloading and setting the solution up from the content hub, but when I want to install the provided MainTemplate.json it does not work properly, it gives me the following error and I don't really get it:
{
  "code": "InvalidTemplate",
  "message": "Deployment template validation failed: 'The template resource '/Microsoft.SecurityInsights/-wb-d53f4nb6olnp2' for type 'Microsoft.OperationalInsights/workspaces/providers/contentTemplates' at line '77' and column '87' has incorrect segment lengths. A nested resource type must have identical number of segments as its resource name. A root resource type must have segment length one greater than its resource name. Please see https://aka.ms/arm-syntax-resources for usage details.'."
}

**Comment by v-sudkharat** [comment]
Hi @TJ1512, thank you for your response, Could you please redeploy the MainTemplate.json by below steps. 

- Go to Custom Deployment

![image](https://github.com/Azure/Azure-Sentinel/assets/132428394/8d8b3370-f72f-459c-9184-61bbed0037b7)

-Add the Workspace details in template- 
 
![image](https://github.com/Azure/Azure-Sentinel/assets/132428394/82e4f704-cb93-4a25-b712-915a001392a7)

-Click Create

![image](https://github.com/Azure/Azure-Sentinel/assets/132428394/ddcab49e-c3eb-476e-82de-3ae5435352f2)

- Check the Deployment 

![image](https://github.com/Azure/Azure-Sentinel/assets/132428394/2d632490-063a-4fe5-af46-9264345467c1)


Once above steps done, check workbook in solution and let us know it works or not. So, we can raise the PR with those changes.

Thanks!

**Comment by TJ1512** [comment]
Thanks for the instruction, this time it worked. Workbook is working properly now.

**Comment by v-sudkharat** [comment]
@TJ1512, thanks for confirmation. Can we close this issue?

**Comment by TJ1512** [comment]
@v-sudkharat, yes, thank you for the support 👍

**Comment by v-sudkharat** [comment]
@TJ1512, Ok. Thank you!
