### ISSUE TITLE
Imperva WAF Cloud Connector - Function breaks when last saved file is missing in current array

### ISSUE THREAD

**Issue by giorebil** [Azure/Azure-Sentinel#9023]
Hi,
the handling of the last saved file in the function last_file_point (line 79) is improper.
https://github.com/Azure/Azure-Sentinel/blob/master/Solutions/ImpervaCloudWAF/Data%20Connectors/ImpervaWAFCloudSentinelConnector/__init__.py

![image](https://github.com/Azure/Azure-Sentinel/assets/22745890/2798d987-f28e-4ca7-a434-034685886f85)

In the function, the script expects the last saved log file (e.g., "6277_271.log") to always be present in the current array retrieved from an API call. If this specific log file is missing from the array, the function encounters an error.
![image](https://github.com/Azure/Azure-Sentinel/assets/22745890/c30cb073-9382-4554-abfb-9104d9742618)

I would edit line 84 as follow:
`if past_file is not None and past_file in self.files_array:`
If the previously stored file point is absent from the current log array, the script will continue execution and update its last file point to the most recent log in the array.

**Comment by v-rbajaj** [comment]
Hi @giorebil, we are still investigating on this issue we will get back to you by 13 Oct 2023.

**Comment by v-rbajaj** [comment]
Hi @giorebil, we are still investigating on this issue we will get back to you by  18 Oct 2023

**Comment by v-rbajaj** [comment]
Hi @giorebil, we are still investigating on this issue we will get back to you by 14 Nov 2023

**Comment by v-rbajaj** [comment]
Hi @giorebil, can you please update WEBSITE_RUN_FROM_PACKAGE with this URL in the function app
![image](https://github.com/Azure/Azure-Sentinel/assets/120547590/011724b8-6577-48e3-9585-4bba1dcc4418)

https://github.com/Azure/Azure-Sentinel/raw/v-mchatla/ImpervaCloudWAF-8602IssueFix/Solutions/ImpervaCloudWAF/Data%20Connectors/ImpervaWAFCloudSentinelConn.zip

Then do restart the Function App and check if you are still facing the issue .

If this fixes the issue then we will merge the changes to master.

**Comment by v-muuppugund** [comment]
Hi @giorebil  Could you please follow the above steps mentioned and let us know if any issues

**Comment by giorebil** [comment]
Hi, the provided solution is working. 

Thanks and best regards,
Giovanni

**Comment by v-muuppugund** [comment]
Hi @giorebil ,Thanks for confirmation, we will continue next steps for pushing those changes.

**Comment by v-rbajaj** [comment]
Hi @giorebil, Thanks for the confirmation, we will raise the PR and push the changes to master.
