### ISSUE TITLE
Reset-AADPassword Prerequisites is wrong.

### ISSUE THREAD

**Issue by ankkp** [Azure/Azure-Sentinel#9035]
**Describe the bug**
I was testing Reset-AADPassword playbook and followed the [permission steps](https://github.com/Azure/Azure-Sentinel/tree/master/Solutions/Azure%20Active%20Directory/Playbooks/Reset-AADUserPassword#prerequisites). But I still get error for https-reset password step.

{
  "error": {
    "code": "Authorization_RequestDenied",
    "message": "Insufficient privileges to complete the operation.",
    "innerError": {

**To Reproduce**
follow link above

**Expected behavior**
playbook should run sucessfully.

**Screenshots**
![image](https://github.com/Azure/Azure-Sentinel/assets/108366779/2478ab5e-a450-4c6a-bf75-69f64ddfd098)

**Desktop (please complete the following information):**
NA

**Smartphone (please complete the following information):**
NA

**Additional context**
I think MI needs more permission.

Example:
`$MIGuid = "<Enter your managed identity guid here>"
$MI = Get-AzureADServicePrincipal -ObjectId $MIGuid
$GraphAppId = "00000003-0000-0000-c000-000000000000"
$PermissionName = "User.ReadWrite.All" 
$GraphServicePrincipal = Get-AzureADServicePrincipal -Filter "appId eq '$GraphAppId'"
$AppRole = $GraphServicePrincipal.AppRoles | Where-Object {$_.Value -eq $PermissionName -and $_.AllowedMemberTypes -contains "Application"}
New-AzureAdServiceAppRoleAssignment -ObjectId $MI.ObjectId -PrincipalId $MI.ObjectId `
-ResourceId $GraphServicePrincipal.ObjectId -Id $AppRole.Id`

**Comment by ankkp** [comment]
@rahul0216 

If you could look at this or get the right person to review it.

Thank you

**Comment by rahul0216** [comment]
Thanks @ankkp for reporting this. @v-rbajaj and @v-sudkharat will look into the issue.

**Comment by v-rbajaj** [comment]
Hi @ankkp, we are investigating this issue but most probably looking at the error message, it looks like there aren't sufficient privileges to run this playbook for you and hence you are getting authorization error.

**Comment by ankkp** [comment]
hello @v-rbajaj  Please resolve it I missed part MI needing GA permission for admin accounts.

**Comment by ankkp** [comment]
hello @v-rbajaj  Please resolve it I missed part MI needing GA permission for admin accounts.
