### ISSUE TITLE
    Azure-Sentinel/DataConnectors  /microsoft-sentinel-log-analytics-logstash-output-plugin/

### ISSUE THREAD

**Issue by alexandrupnt** [Azure/Azure-Sentinel#9036]
On the description of this Connector - [Azure-Sentinel](https://github.com/Azure/Azure-Sentinel/tree/master)/[DataConnectors](https://github.com/Azure/Azure-Sentinel/tree/master/DataConnectors)/microsoft-sentinel-log-analytics-logstash-output-plugin/ 

there is a reference to the installation requirements:

Logstash 8 Between 8.0 and 8.8.1

BUT the LINKS points to the latest version which is 8.10.1
https://github.com/Azure/Azure-Sentinel/tree/master/DataConnectors/microsoft-sentinel-log-analytics-logstash-output-plugin#1-install-the-plugin

Is the latest version supported ?
If this is supported, then we should update the requirements

**Comment by v-sudkharat** [comment]
Hi @alexandrupnt, thanks for flagging this issue, we will soon get back to you on this. Thanks!

**Comment by v-sudkharat** [comment]
Hello @alexandrupnt, we check the click point of link, the link redirect to the latest version of the plugin, to use the document mentioned plugin version you have to click on "Other Version" tab. 

Sharing steps and screenshot for reference: - 
1. Click on the "Other Version Option." - 
![image](https://github.com/Azure/Azure-Sentinel/assets/132428394/3a062cf0-3bf3-4728-bbea-4a3a5bf72f81)

2. Select the Microsoft Sentinel's Logstash output plugin supports version which mentioned in GitHub document - 

![image](https://github.com/Azure/Azure-Sentinel/assets/132428394/1dfe15c9-5b55-44de-891c-79c75a32f363)
![image](https://github.com/Azure/Azure-Sentinel/assets/132428394/7034a3a3-4bde-4217-a592-5ab87daaf2a7)

I hope this helps you. so, closing this issue. If you still need support for this issue, feel free to re-open it any time. Thank you for your co-operation.
