### ISSUE TITLE
Tabs (\t) in detection files raises PyYaml errors

### ISSUE THREAD

**Issue by d3vzer0** [Azure/Azure-Sentinel#9045]
**Describe the bug**
Some of the Yaml files contain tabs which will raise an error when parsed using PyYaml.

**To Reproduce**
1. Clone the Azure-Sentinel repository
2. Open and load the files listed in the PR with PyYaml

**Expected behavior**
No errors to appear

**Errors**
```
Detections/MultipleDataSources/Unauthorized_user_access_across_AWS_and_Azure.yaml while scanning for the next token
found character '\t' that cannot start any token
  in "<unicode string>", line 28, column 10:
      - T1212
             ^
Solutions/SpyCloud Enterprise Protection/Analytic Rules/SpyCloudEnterpriseProtectionMalwareRule.yaml while scanning for the next token
found character '\t' that cannot start any token
  in "<unicode string>", line 38, column 24:
      - entityType: Account
                           ^
Solutions/SpyCloud Enterprise Protection/Analytic Rules/SpyCloudEnterpriseProtectionBreachRule.yaml while scanning for the next token
found character '\t' that cannot start any token
  in "<unicode string>", line 36, column 24:
      - entityType: Account
```

**Desktop (please complete the following information):**
 - OS: Mac
 - Software: Python 3.11.5
 - Software: Pyyaml 6.0.1

**Additional context**
I opened a pull request with the files in scope of this issue here: https://github.com/Azure/Azure-Sentinel/pull/9044

**Comment by v-rbajaj** [comment]
Hi @d3vzer0, thanks for flagging this, we are looking into this and we will get back to you once there is an update.

**Comment by d3vzer0** [comment]
Hi @v-rbajaj this issue has been solved since my pull request (https://github.com/Azure/Azure-Sentinel/pull/9044) has been merged already. Thanks!
