### ISSUE TITLE
OneLogin Parser for Connector - OneLogin

### ISSUE THREAD

**Issue by katerobson08** [Azure/Azure-Sentinel#9060]
*Describe the bug
I have been trying to use the parser for OneLogin but get an error as there seems to be 7 fields missing form the table(OneLogin_CL).
The fields are:
app_name_s
app_id_d
role_name_s
role_id_d
user_attributes_username_s
user_attributes_department_s
user_attributes_title_s

To Reproduce

Install OneLogin Parser
Go to Sentinel -> Logs
Run the parser OneLogin
Error "project-rename: Failed to resolve column reference 'app_name_s'"
Expected behavior
To produce parsed table

Screenshots
![image](https://github.com/Azure/Azure-Sentinel/assets/98545637/38b7101d-9cab-4b4f-aeac-5a41f069b4d8)

![image](https://github.com/Azure/Azure-Sentinel/assets/98545637/1034c60e-8612-4352-a46a-69e49ea1062f)

Schema:

![image](https://github.com/Azure/Azure-Sentinel/assets/98545637/662806b5-6801-4df4-90ee-14223409fce7)

Desktop (please complete the following information):

OS: Windows
Browser Edge
Version Version 116.0.1938.62
Smartphone (please complete the following information):

Additional context

**Comment by v-sudkharat** [comment]
Hi @katerobson08, thank you for sharing the schema with us. please can you run the below parser query in same workspace and let us know it works for you or if the issue still persists. 
[OneLoginParser.txt](https://github.com/Azure/Azure-Sentinel/files/12697727/OneLoginParser.txt)

Thanks!

**Comment by katerobson08** [comment]
Morning @v-sudkharat, 

I have run the above example and that works fine for me!

Kate

**Comment by v-sudkharat** [comment]
Hi @katerobson08, 
Thank you for sharing feedback with us. We raised the PR with those changes, the changes will reflect in an upcoming version of the solution.
Thanks!
