### ISSUE TITLE
TI map IP entity to Network Session Events

### ISSUE THREAD

**Issue by davidalonsod** [Azure/Azure-Sentinel#9063]
When you try to configure the analytic rule that you can see in the subject there is an issue in Set Rule Logic and the error is "Validation failed. Required information is missing or not valid. This is the query in Sentinel.

let dt_lookBack = 1h;
let ioc_lookBack = 14d;
let IP_TI = materialize (
  ThreatIntelligenceIndicator
  | where TimeGenerated >= ago(ioc_lookBack) and ExpirationDateTime > now()
  | summarize LatestIndicatorTime = arg_max(TimeGenerated, *) by IndicatorId
  | where Active == true
  | extend TI_ipEntity = coalesce(NetworkIP, NetworkDestinationIP, NetworkSourceIP,EmailSourceIpAddress,"NO_IP")
  | where TI_ipEntity != "NO_IP"
);
IP_TI
  // using innerunique to keep perf fast and result set low, we only need one match to indicate potential malicious activity that needs to be investigated
| join kind=innerunique 
(
  _Im_NetworkSession (starttime=ago(dt_lookBack))
  | where isnotempty(SrcIpAddr)
  | summarize imNWS_mintime=min(TimeGenerated), imNWS_maxtime=max(TimeGenerated) by SrcIpAddr, DstIpAddr, Dvc, EventProduct, EventVendor  
  | lookup (IP_TI | project TI_ipEntity, Active) on $left.SrcIpAddr == $right.TI_ipEntity
  | project-rename SrcMatch = Active
  | lookup (IP_TI | project TI_ipEntity, Active) on $left.DstIpAddr == $right.TI_ipEntity
  | project-rename DstMatch = Active
  | where SrcMatch or DstMatch
  | extend 
      IoCIP = iff(SrcMatch, SrcIpAddr, DstIpAddr),
      IoCDirection = iff(SrcMatch, "Source", "Destination")
)on $left.TI_ipEntity == $right.IoCIP
| where imNWS_mintime < ExpirationDateTime
| project imNWS_mintime, imNWS_maxtime, Description, ActivityGroupNames, IndicatorId, ThreatType, ExpirationDateTime, ConfidenceScore, SrcIpAddr, DstIpAddr, IoCDirection, IoCIP, Dvc, EventVendor, EventProduct

If you run the query this is the error " Some aspects of the query had errors so the results are not complete
If the issue persists, please open a support ticket. Request id: 41ade80a-1700-4b6e-bc3f-9834791447ad"

**Comment by davidalonsod** [comment]
Just to provide more information the issue happen when you try to update the rule. I can see review an update and it failed

**Comment by davidalonsod** [comment]
I have just realise thast the issue was because my customer didn't wait time to evalute the query. Once the query is evaluated it works

**Comment by v-sudkharat** [comment]
Hello @davidalonsod, Thanks for closing this issue. If you still need support for this issue, feel free to re-open it any time. Thank you for your co-operation.
