### ISSUE TITLE
GithubFunction connector not using the correct api endpoint

### ISSUE THREAD

**Issue by aka0** [Azure/Azure-Sentinel#9078]
API endpoint `https://api.github.com/repos/$orgName/$repoName/traffic/clones` referenced in the GithubFunction connector only provides a "total number of clones and breakdown per day or week for the last 14 days" and does not produce actual Git clone events (who cloned repo from where).

Link to code:
https://github.com/Azure/Azure-Sentinel/blob/f832c108f037f0980525f9e379070a14bf79624a/DataConnectors/GithubFunction/AzureFunctionGitHub/GitHubTimerTrigger/run.ps1#L356

Vendor doc reference: [traffic/clones](https://docs.github.com/en/rest/metrics/traffic?apiVersion=2022-11-28#get-repository-clones)

Correct API endpoint should be: https://docs.github.com/en/enterprise-cloud@latest/admin/monitoring-activity-in-your-enterprise/reviewing-audit-logs-for-your-enterprise/audit-log-events-for-your-enterprise#git

**Comment by v-rbajaj** [comment]
Hi @aka0, we are investigating on this issue and we will get back to you once there is an update.

**Comment by v-rbajaj** [comment]
Hi @aka0, we are reaching out to concerned team on this issue, you will get an update by 13 Oct 2023.

**Comment by v-rbajaj** [comment]
Hi @aka0, sorry for the delay, we are reaching out to concerned team on this issue, you will get an update by 07 Nov 2023

**Comment by v-rbajaj** [comment]
Hi @aka0, can you please let us to know which API exactly you are expecting to hit for getting the actual git clone events?
Moreover, the description of the data connector says that it is expected to gather Audit, Repo and vulnerability logs only. 
![image](https://github.com/Azure/Azure-Sentinel/assets/120547590/ee144773-c5d2-4f74-8ae0-e785c2154616)

**Comment by v-rbajaj** [comment]
Hi @aka0, Gentle Reminder: We are awaiting for your response on this issue. If you still need to keep this issue active please respond on it in the next 2 days . If we don't receive response, we will be close this issue.

**Comment by v-rbajaj** [comment]
Hi @aka0, Since we have not received a response in the last 5 days, we are closing your issue
#9078 as per our standard operating procedures. If you still need support for this issue, feel free to re-open at any time. Thank you for your co-operation.
