### ISSUE TITLE
MFA Rejected by user is not firing alerts

### ISSUE THREAD

**Issue by seeavosh** [Azure/Azure-Sentinel#9092]
**Describe the bug**
There are two rules that will look into MFA details 
MFA Rejected by User
Explicit MFA Deny

A recent MFA fraud report that we received from Azure AD clearly shows it worked but none of the rules were fired. I looked into the logs and I cannot see any values such as the following 

MFA denied; user declined the authentication
MFA denied; Phone App Reported Fraud

It all shows: MFA denied; duplicate authentication attempt

**To Reproduce**
1. Reject MFA 
2. Go to Log analytic 
3. Run the query 
SigninLogs
| where ResultType == 500121
| extend additionalDetails_ = tostring(Status.additionalDetails)
| extend UserPrincipalName = tolower(UserPrincipalName)

4. look for any of the value in additionalDetails_

**Expected behavior**
additionalDetails_ must provide any of the following 
MFA denied; user declined the authentication
MFA denied; Phone App Reported Fraud

**Comment by v-sudkharat** [comment]
Hi @seeavosh, thanks for flagging this issue, we will soon get back to you on this. Thanks!

**Comment by v-sudkharat** [comment]
Hi @seeavosh, could you please run the below query, and share `additionalDetails_` column contain with us? 
```
let riskScoreCutoff = 0; //Adjust this based on volume of results
  SigninLogs
  | where ResultType == 500121
  | extend additionalDetails_ = tostring(Status.additionalDetails)
  | extend UserPrincipalName = tolower(UserPrincipalName)
  //| where additionalDetails_ =~ "MFA denied; user declined the authentication" or additionalDetails_ has "fraud"
  | distinct additionalDetails_
```
Reference to the query, we have to adjust the `riskScoreCutoff ` based in volume of result. 

Thanks!

**Comment by seeavosh** [comment]
Hi @v-sudkharat 

The result for the time we got the MFA reject 
![image](https://github.com/Azure/Azure-Sentinel/assets/24514382/558ca832-47be-48a7-9630-d86b90e6f9b4)

**Comment by v-sudkharat** [comment]
Hi @seeavosh, thanks for sharing column schema with us. As reference to previous [comment](https://github.com/Azure/Azure-Sentinel/issues/9092#issuecomment-1739144121), the query is looking for `SigninLogs` and alert will fire when the query condition is meet/satisfied. 
We can see in your shared column schema, the `MFA denied; user declined the authentication` ,` MFA denied; Phone App Reported Fraud` is not present in that `additionalDetails_` column. 
If you want to alter the trigger, you can make change in where condition. please refer below query as example: - 

```
let riskScoreCutoff = 1; //Adjust this based on volume of results
  SigninLogs
  | where ResultType == 500121
  | extend additionalDetails_ = tostring(Status.additionalDetails)
  | extend UserPrincipalName = tolower(UserPrincipalName)
  | where additionalDetails_ =~ "MFA denied; user declined the authentication" or additionalDetails_ has "MFA denied; Phone App Reported Fraud"
```
we hope this helps. 
Thanks!

**Comment by v-sudkharat** [comment]
Hi @seeavosh, we are waiting for you response on above comment. Thanks!

**Comment by v-sudkharat** [comment]
Hi @seeavosh, Gentle Reminder: We are waiting for your response on this issue. If you still need to keep this issue active, please respond to it in the next 2 days. If we don't receive a response by 06-10-2023 date, we will be closing this issue. 		
Thanks!

**Comment by v-sudkharat** [comment]
Hi @seeavosh, since we have not received a response in the last 5 days, we are closing your issue #9092 as per our standard operating procedures. If you still need support for this issue, feel free to re-open at any time. Thank you for your co-operation.
