### ISSUE TITLE
Fortinet connector using AMA

### ISSUE THREAD

**Issue by Notorious-AFK** [Azure/Azure-Sentinel#9102]
**Is your feature request related to a problem? Please describe.**
The current Fortinet connector deployment script uses OMS agent and is being deprecated.

**Describe the solution you'd like**
A similar easy to deploy connector using the AMA agent.

**Describe alternatives you've considered**
Other options like using logstash is possible, but a lot harder than just running a line of code in a Linux terminal like the Fortinet connector does.

**Additional context**
.

**Comment by v-rbajaj** [comment]
Hi @Notorious-AFK, can you please provide the exact solution name also the connector name as well for confirmation?

**Comment by v-rbajaj** [comment]
Hi @Notorious-AFK, please provide some update on this issue.

**Comment by Notorious-AFK** [comment]
Hi, sorry for the delay.

Connector name is «Fortinet».
Content source is: «Fortinet FortiGate Next-Generation Firewall connector
for Microsoft Sentinel»

Content source version: «1.0.0»

**Comment by v-rbajaj** [comment]
Hi @Notorious-AFK, thanks for providing the details.

**Comment by manishkumar1991** [comment]
@Notorious-AFK , Creating the AMA data connector for Fortinet FortiGate Next-Generation Firewall is already in our pipeline,

ETA will be end of this year.

**Comment by v-rbajaj** [comment]
Hi @Notorious-AFK, as per above confirmation, we are currently bringing this issue to closure. Feel free to ask any further questions!
