### ISSUE TITLE
Calls to GET entities return 404, but after 2-5 minutes return a value

### ISSUE THREAD

**Issue by jgbvnt** [Azure/Azure-Sentinel#9105]
**Describe the bug**
When we try to get an entity from the related items of incident, we receive a 404 NOT_FOUND.  A retry after a few minutes will sometimes return the entity, but not always.
We're using this api: 
https://docs.microsoft.com/en-us/rest/api/securityinsights/preview/entities/get
https://learn.microsoft.com/en-us/rest/api/securityinsights/preview/entities/get?tabs=HTTP#get-a-security-alert-entity.

**To Reproduce**
1. Get authentication token from Microsoft Login
2. Call the incident relations endpoint to get related entities
3. Call the entity endpoint with each returned entity name
4. receive 404
5. wait 2 minutes and retry - entity endpoint returns the entity

**Expected behavior**
When the call for entity is successful, it can return within a couple of seconds.  We would like it to consistently return in a couple of seconds or less

**Screenshots**
N/A

**Desktop (please complete the following information):**
N/A

**Smartphone (please complete the following information):**
N/A

**Additional context**
The endpoint works correctly about 90% of the time

**Comment by v-rbajaj** [comment]
Hi @jgbvnt, can please let us know how is it related to Sentinel?

**Comment by jgbvnt** [comment]
@v-rbajaj i may have posted this to the incorrect location.  was thinking that the team also was involved with the REST API

**Comment by v-rbajaj** [comment]
Hi @jgbvnt, this isn't related to  Sentinel. You can contact Microsoft support for this request and they can take it further. 

https://ms.portal.azure.com/#view/Microsoft_Azure_Support/HelpAndSupportBlade/~/overview

I hope this helps. 
Feel free to re open this issue in case you have further questions.
