### ISSUE TITLE
Microsoft 365 Defender data connector delay

### ISSUE THREAD

**Issue by reedijkbart** [Azure/Azure-Sentinel#9111]
**Is your feature request related to a problem? Please describe.**
It can take up to 10 minutes for Microsoft 365 Defender incidents to appear in Microsoft Sentinel, when using the Microsoft 365 Defender data connector. 

This is a problem: automation rules will run much later than they should, any integration with Microsoft Sentinel and 3rth party products will have this delay as well (ITSM tooling for example).

**Describe the solution you'd like**
Much less delay in the creation of Microsoft Sentinel incidents based on incidents from Microsoft 365 Defender.

**Describe alternatives you've considered**
I don't see an alternative, because the only way to synchronize incidents between Micosoft 365 Defender and Microsoft Sentinel is by using the Microsoft 365 Defender data connector.
As a workaround, building different integrations especially for Microsoft 365 Defender, is an option. But this is not ideal.

**Additional context**
.

**Comment by v-sudkharat** [comment]
Hi @reedijkbart  thanks for flagging this issue, we will soon get back to you on this. Thanks!

**Comment by v-sudkharat** [comment]
Hi @reedijkbart, yes, In Microsoft documentation its mentioned that, it can take up to 10 minutes from the time an incident is generated in Microsoft 365 Defender to the time it appears in Microsoft Sentinel.  please refer the below link and screenshot for more information. 

link-` https://learn.microsoft.com/en-us/azure/sentinel/microsoft-365-defender-sentinel-integration`

![image](https://github.com/Azure/Azure-Sentinel/assets/132428394/f2c8d02d-c0d2-45b0-911a-77c58335d697)

so, closing this issue. If you still need support for this issue, feel free to re-open it any time. Thank you for your co-operation.

**Comment by reedijkbart** [comment]
@v-sudkharat thank you for your answer.

Is it possible to improve this? 10 minutes is a very long time, especially for potential P1 incidents.

**Comment by v-sudkharat** [comment]
Hi @reedijkbart, thank you for your feedback, as this is an enhancement in connector, we shared this issue with data collection team. Thanks!
