### ISSUE TITLE
Feature Request: NISTSP80053workbook - Missing Controls

### ISSUE THREAD

**Issue by brandonconn03** [Azure/Azure-Sentinel#9113]
**Is your feature request related to a problem? Please describe.**
The NIST SP 800-53 R4 workbook solution appears to be 'missing' controls that my company is required to report on a regular basis. It would be extremely helpful to have more controls mapped.

**Describe the solution you'd like**
Include additional control families: 
AC | ACCESS CONTROL (AU-21-25)
AT | AWARENESS AND TRAINING (ALL)
AU | AUDIT AND ACCOUNTABILITY (AU-13-16)
CA | ASSESSMENT, AUTHORIZATION, AND MONITORING (CA-1,4-6,8-9)
CM | CONFIGURATION MANAGEMENT (CM-1,12-14)
CP | CONTINGENCY PLANNING (CP-1-5, 10-13)
IA | IDENTIFICATION AND AUTHENTICATION (IA-1,3, 6-12)
IR | INCIDENT RESPONSE (IR-1-2,7-10)
MA | MAINTENANCE (MA-1-7)
MP | MEDIA PROTECTION (MP-1,8)
RA | RISK ASSESSMENT (RA-1,6-10)
SA | SYSTEM AND   SERVICES ACQUISITION (SA-1-23)
SC | SYSTEM AND COMMUNICATIONS PROTECTION (SC-1-3,9-10,14-16,19,20,22,24,25,27,29-51)
SI | SYSTEM AND INFORMATION INTEGRITY (SI-1,6,9-11,13-23)
SR | RISK ASSESSMENT (SR-1-12)

**Describe alternatives you've considered**
I've attempted to use the Regulatory Compliance solution in Defender for Cloud but it does not seem to fulfill my desired needs.

**Additional context**
If this is captured somewhere else or being evaluated please let me know. Thanks,

**Comment by v-sudkharat** [comment]
Hi @brandonconn03, thanks for flagging this issue, we will soon get back to you on this. Thanks!

**Comment by v-rbajaj** [comment]
Hi @brandonconn03, we have reached out to concerned team, we will get back to you once there is an update.

**Comment by v-rbajaj** [comment]
Hi @brandonconn03, thanks for suggesting these changes, we have created the backlog item for this feature request, and we will work on it based on our priority. There is no ETA associated with it. 

Feel free to re open this issue in case you have further questions.
