### ISSUE TITLE
NRT Creation of expensive computes in Azure seems to not honor 'tokens' dynamic list

### ISSUE THREAD

**Issue by tohov** [Azure/Azure-Sentinel#9119]
**Describe the bug**
I tested this rule by first creating a VM with the size Standard_D48s_v5. Then after some while I checked that the operation was visible in the Activity Log. Ran the query but it returned no results. Not sure where it goes wrong. I know that I can see the activity in the results if I comment out the `//| where vmSize has_any (tokens)`

**To Reproduce**
Steps to reproduce the behaviour:
1. Create new resource group
2. Create VM that has size Standard_D48s_v5 in the same rg
3. Wait for the activity log to reflect the operations
4. Run the analytics query in Azure Monitor Logs in the rg context
5. No results

**Expected behaviour**
I would assume that the query spots the creation of the instance as the vmSize has '48' in the name 

**Screenshots**
Query run as-is
![image](https://github.com/Azure/Azure-Sentinel/assets/38506856/a9c5f985-ae80-4a2a-8265-8e033d2d92c5)

Query run without `| where vmSize has_any (tokens)`
![image](https://github.com/Azure/Azure-Sentinel/assets/38506856/6348193c-9cc1-4355-9356-d4ee5fd3276a)

**Comment by v-sudkharat** [comment]
Hi @tohov, thanks for flagging this issue, we will soon get back to you on this. Thanks!

**Comment by v-sudkharat** [comment]
Hi @tohov, could you please run the below query in same resource group and let us know it works for you or if the issue still persists. 
  ```
let tokens = dynamic(["416","208","192","128","120","96","80","72","64","48","44","40","g5","gs5","g4","gs4","nc12","nc24","nv24","D48s"]);
  let operationList = dynamic(["microsoft.compute/virtualmachines/write", "microsoft.resources/deployments/write"]);
  AzureActivity
  | where OperationNameValue in~ (operationList)
  | where ActivityStatusValue startswith "Accept"
  | where Properties has 'vmSize'
  | extend parsed_property= parse_json(tostring((parse_json(Properties).responseBody))).properties
  | extend vmSize = tostring((parsed_property.hardwareProfile).vmSize)
  | where vmSize has_any (tokens)
  | extend ComputerName = tostring((parsed_property.osProfile).computerName)
  | project TimeGenerated, OperationNameValue, ActivityStatusValue, Caller, CallerIpAddress, ComputerName, vmSize
  | extend Name = tostring(split(Caller,'@',0)[0]), UPNSuffix = tostring(split(Caller,'@',1)[0])
```
Thanks!

**Comment by tohov** [comment]
@v-sudkharat Hello, I see that you added a token "D48s". This actually works now in my tests with the Standard D48s v5 virtual machine. But I'm not interested in this particular machine, but I was just testing how the analytics rule works and wondering why I did not receive an incident based on this rule. So I guess, all the tokens (the first twelve maybe or those in just double digits) won't work for some reason. Is there a character limit to a string search? Like minimum three characters?

I'd like to deploy the rule but it won't help if the query in whole does not work

**Comment by v-sudkharat** [comment]
Hi @toho, we are investigating this issue, we will provide you an update by 12-10-2023. Thanks!

**Comment by v-sudkharat** [comment]
Hi @tohov, we are reached out to the concerned team for this issue, once we receive an update on this, we will update you. Thanks!

**Comment by v-sudkharat** [comment]
Hi @tohov, hope you are doing well. we make some modification in the query, could you please run the below query and let us know it works fine for you. so, it would be very helpful for us to proceed further. Thanks!

```
  let tokens = dynamic(["416","208","192","128","120","96","80","72","64","48","44","40","g5","gs5","g4","gs4","nc12","nc24","nv24"]);
  let operationList = dynamic(["microsoft.compute/virtualmachines/write", "microsoft.resources/deployments/write"]);
  AzureActivity
  | where OperationNameValue in~ (operationList)
  | where ActivityStatusValue startswith "Accept"
  | where Properties has 'vmSize'
  | extend parsed_property= parse_json(tostring((parse_json(Properties).responseBody))).properties
  | extend vmSize = tostring((parsed_property.hardwareProfile).vmSize)
  | mv-apply token=tokens to typeof(string) on (where vmSize contains token)
  | extend ComputerName = tostring((parsed_property.osProfile).computerName)
  | project TimeGenerated, OperationNameValue, ActivityStatusValue, Caller, CallerIpAddress, ComputerName, vmSize
  | extend Name = tostring(split(Caller,'@',0)[0]), UPNSuffix = tostring(split(Caller,'@',1)[0])
```

**Comment by v-sudkharat** [comment]
Hi @tohov, we are waiting for your response on above comment. Thanks!

**Comment by v-sudkharat** [comment]
Hi @tohov, could you please have a look at above comments and share feedback with us? so, we can share update with our concern team and proceed further. Thanks!

**Comment by tohov** [comment]
Hi @v-sudkharat, I will have time to test this tomorrow Thursday 26th. I will get back to you with results then!

**Comment by v-sudkharat** [comment]
@tohov, ok, Thank you.

**Comment by tohov** [comment]
@v-sudkharat Hello, I've tested this with the D48s VM because my subscription vCPU quota is only 50 and don't want to increase it because of the testing. But this time the detection worked like a charm. Noticed that the analytic rule does not by default raise the host entity to the incident which I think it should do. I can edit the rule though, but maybe something to consider also that the information about the VM in question should be added as entity to the incident by default.

Thank you for solving this!

**Comment by v-sudkharat** [comment]
Hi @tohov, We appreciate your confirmation about the rule, we will raise a PR with this modification. So, the updates will be visible in the next version of the solution. 
Closing this issue now. If you still need support for this issue, feel free to re-open it any time. Thank you for your co-operation.
