### ISSUE TITLE
Analytic rule description link is broken

### ISSUE THREAD

**Issue by applefacts** [Azure/Azure-Sentinel#9129]
https://github.com/Azure/Azure-Sentinel/blob/a6593c2bb08c6cb6fbcaabdd961c83ef9f9b89b1/Solutions/Network%20Session%20Essentials/Analytic%20Rules/PossibleBeaconingActivity.yaml

This rule identifies beaconing patterns from Network traffic logs based on recurrent frequency patterns. Such potential outbound beaconing pattern to untrusted public networks should be investigated for any malware callbacks or data exfiltration attempts as discussed in this [Blog](http://www.austintaylor.io/detect/beaconing/intrusion/detection/system/command/control/flare/elastic/stack/2017/06/10/detect-beaconing-with-flare-elasticsearch-and-intrusion-detection-systems/).\<br><br>
This analytic rule uses [ASIM](https://aka.ms/AboutASIM) and supports any built-in or custom source that supports the ASIM NetworkSession schema'

The blog doesn't exist anymore.

**Additional context**

**Comment by azurekid** [comment]
Validated link and added a PR: #9136

**Comment by v-rbajaj** [comment]
Hi @azurekid, thanks for confirming, we will review the PR and will update you.
