### ISSUE TITLE
Github Connector: keyvault-GitHubPlaybooks API connection error

### ISSUE THREAD

**Issue by qcmatt** [Azure/Azure-Sentinel#913]
**Describe the bug**
While authorising the API connection for "keyvault-GitHubPlaybooks" I get the following error when saving the update.

```
Failed to edit API connection 'keyvault-GitHubPlaybooks'.
```

I'm not sure if it's related, but this error appears in the activity log 

```

{"Code":"BadRequest","Message":"Input parameters are invalid. See details for more information. Details:Invalid code or connection..","Target":null,"Details":[{"Message":"Input parameters are invalid. See details for more information. Details:Invalid code or connection.."},{"Code":"BadRequest"},{"ErrorEntity":{"ExtendedCode":"14022","MessageTemplate":"Input parameters are invalid. See details for more information. Details:{0}.","Parameters":["Invalid code or connection."],"Code":"BadRequest","Message":"Input parameters are invalid. See details for more information. Details:Invalid code or connection.."}}],"Innererror":null}
```

**To Reproduce**
Followed the steps outlined in the [Azure Sentinel/Github](https://github.com/Azure/Azure-Sentinel/tree/master/DataConnectors/GitHub) documentation. Steps 8 and 9 are where the error occurs.

**Expected behavior**
I expected the changes to the API connection to be saved without error.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: macOS 
 - Browser Brave 84 and Firefox 78

**Comment by dicolanl** [comment]
@qcmatt  could you open a support ticket?  the api connection is part of logic apps.  Authorize has worked with testing and other customers using this which makes me think its environment specific or just a bug in azure.

**Comment by qcmatt** [comment]
Will do @dicolanl
