### ISSUE TITLE
Amazon Web Services S3 (Preview) connector for CloudTrail discard eventTime, uses incorrect TimeGenerated

### ISSUE THREAD

**Issue by fischaz** [Azure/Azure-Sentinel#9145]
**Describe the bug**

If the CloudTrail logs are stuck in the SQS queue for an extended period of time (because the Sentinel Connector is having issue, is being disconnected, is having a hard time to keep up), Then the CloudTrail events stored in Sentinel will have:
* the CloudTrail eventTime field will be discarded and lost.
* The Sentinel TimeGenerated field will be populated with the timestamp when sentinel **eventually** ingested the event, not when it was issued by CloudTrail.

This is a security issue as we want to be able to correlate timestamps between sources accurately and events being stuck in transit should not affect that information.

**To Reproduce**
1. Configure the CloudTrail / S3 bucket / SQS Queue and Sentinel Connector.
2. Ensure the SQS Has a long retention of messages (around 4 days)
3. Ensure Connector is operational (messages are ingested, Queue is generally empty)
4. Disable the Sentinel connector (in Sentinel)
5. Wait 4 days (the queue will fill up with historical messages)
6. Enable the Sentinel connector
7. Wait for the Queue to be processed.
8. Search for Sentinel for the older messages (sort by TimeGenerated asc)
9. Compare Sentinel event with the same event in AWS CloudTrail Lookup Event (You can use the RequestId to select the unique event).

**Expected behavior**

The Field TimeIngested of the selected event should match the time when the event was issued by CloudTrail (4 days ago, matching the eventTime field in CloudTrail).

**Screenshots**

Sentinel Search:
<img width="412" alt="image" src="https://github.com/Azure/Azure-Sentinel/assets/37970138/1f9ca0ab-d73a-413c-be4e-a936d83ea829">

Sub-set of the event:
<img width="364" alt="image" src="https://github.com/Azure/Azure-Sentinel/assets/37970138/f1cd9cdd-f496-4314-a0cb-1e59bd5ca6a5">

Search in AWS of the Same Event:
<img width="379" alt="image" src="https://github.com/Azure/Azure-Sentinel/assets/37970138/07041c70-b433-4e75-81fe-4844d11f3f78">

Result event found:
<img width="1079" alt="image" src="https://github.com/Azure/Azure-Sentinel/assets/37970138/c4a9232f-f744-4ea9-8dcf-6fba7383a1e1">

NOTE that all times are in UTC (both in Sentinel and AWS).

**Desktop (please complete the following information):**
N/a

**Smartphone (please complete the following information):**
N/A

**Additional context**

**Comment by fischaz** [comment]
As additional info, 

I know there is another timestamp field in sentinel called `SessionCreationDate`. This field is mapped from the AWS Cloudtrail field `useridentity.sessioncontext.attributes.creationdate` and match perfectly between AWS and Sentinel.

**Comment by v-sudkharat** [comment]
Hi @fischaz, could you please run below queries in same workspace and share result with us? we just want to check the mismatch values for those tables. 
1st- 
```
AWSCloudTrail
| where AwsRequestId_ == 'your AwsRequestId_'
| order  by  TimeGenerated asc 
| limit 10
| project TimeGenerated, SessionCreationDate
```
2nd- 
```
AWSCloudTrail
| order  by  TimeGenerated asc 
| project TimeGenerated, SessionCreationDate
```
we also check this issue, and we can see that the value for column TimeGenerated(UTC) and SessionCreationData are contain correct values. 
Sharing the screenshot for reference -
![image](https://github.com/Azure/Azure-Sentinel/assets/132428394/f21941ef-2808-4c6b-857e-f73c0e3dba59)

Thanks!

**Comment by v-sudkharat** [comment]
Hi @fischaz, hope you are doing well. We are waiting for your response on above comment. Thanks!

**Comment by v-sudkharat** [comment]
Hi @fischaz, Gentle Reminder: We are waiting for your response on this issue. If you still need to keep this issue active, please respond to it in the next 2 days. If we don't receive a response by 18-10-2023 date, we will be closing this issue. 		
Thanks!

**Comment by v-sudkharat** [comment]
Hi @fischaz, since we have not received a response in the last 5 days, we are closing your issue #9145 as per our standard operating procedures. If you still need support for this issue, feel free to re-open at any time. Thank you for your co-operation.

**Comment by fischaz** [comment]
Hello, 

I was on leave until now. but being back, I found a new entries mismatching:

```
AWSCloudTrail
| where AwsRequestId_ == '4a1664e2-bd98-4811-b0c3-5736d49af078'
| where SessionCreationDate < (TimeGenerated - 24h)
| order  by  TimeGenerated desc 
| limit 10
| project SessionCreationDate, TimeGenerated, AwsRequestId_

```

<img width="559" alt="image" src="https://github.com/Azure/Azure-Sentinel/assets/37970138/4b91a930-1117-4862-8426-195b900ef9d2">


Actual cloutrail entry:
```
SELECT
    useridentity.sessioncontext.attributes.creationdate,
    eventtime,
    requestid
FROM "athena-cloudtrail-database"."cloudtrail_table"
WHERE 1=1
AND year = '2023'
AND month = '11'
AND requestid = '4a1664e2-bd98-4811-b0c3-5736d49af078'
limit 1
```

<img width="804" alt="image" src="https://github.com/Azure/Azure-Sentinel/assets/37970138/9b05b92a-3ba4-4fda-8d03-271a5ad62350">

As you can see:
| | Sentinel | CloudTrail |
|--|---------|------------|
| TimeGenerated/eventtime | 11/1/2023, 10:43:08.811 PM | 2023-10-27T23:30:47Z |
| SessionCreationDate | 10/27/2023, 4:46:06.000 PM | 2023-10-27T16:46:06Z |

SessionCreationDate  is matching (expected, there was never any problem there). But TimeGenerated is 3 days later than the actual eventtime reported by Cloudtrail for that particular requestID.

**Comment by fischaz** [comment]
Hi @v-sudkharat , although I am unable to reopen the issue #9145 with my permissions.

**Comment by v-muuppugund** [comment]
@fischaz ,Thanks for flagging the above issues ,we will do analysis and get back to you by 20Nov23

**Comment by v-sudkharat** [comment]
Hi @fischaz, we are investigating this issue by do analysis of the SQS queue and AWS Cloud trail for Timestamp delay. we will share update with you by 23-11-2023. 
Thanks!

**Comment by v-sudkharat** [comment]
Hi @fischaz, hope you are doing well. Just want to clarify that if the Sentinel connector is disconnected and the logs are stuck in the SQS queue for a period of time, when you reconnect the connector, the logs that you receive should have the correct Timestamp value, except only for that particular request ID?

**Comment by fischaz** [comment]
Hi @v-sudkharat , 

That's not quite right. If I do disconnect SQS for a period of time (the elements in the queue grow) and after a few days, reconnect it, then **ALL** sentinel events (while the connector is processing the backlog of the queue) would be incorrect and the field TimeGenerated (in sentinel) would reflect the time where the event was eventually ingested by sentinel.

Not the time the event was generated by CloudTrail (eventtime field in CloudTrail). In this scenario, That would be around 4 days (if the time the queue was disconnected was 4 days). 

NOTE That as the queue gets process, that "time difference" would gradually reduce and once the connector has caught up, the time lag would be negligible so it's important to look at the "OLDER" events of the queue (not way for the queue to be empty and then at the current events).

Finally, My last example here is a tad special, but is here to prove the point. In this example, SQS was actually empty and Sentinel was connected. BUT AWS which delivers CloudTrail asynchronously and eventually (their eventual consistency) actually delivered that particular event (event time = 2023-10-27) the S3 object actually written to the bucket on 2023-11-01 (so really the event was really late to be delivered in S3). 

Now we can argue indeed if the primary timestamp field in sentinel should be the time the event was received by Sentinel or the event was generated by Cloudtrail (and there are pros/cons for either side), but I don't believe there is any discussion about dropping that cloudtrail eventtime field entirely (it's the source of truth when the API call was made and I need that info somewhere in sentinel).

**Comment by v-sudkharat** [comment]
Hi @fischaz, Thank you for your clarification. We are currently investigating this issue and will get back to you by 30-11-2023. Meanwhile, could you please share your mail ID with us? This will allow us to connect via a call if necessary. 

Thanks!

**Comment by v-sudkharat** [comment]
Hi @fischaz, we are reaching out to the concerned team for this issue, once we receive an update on this, we will update you. 

Thanks!

**Comment by v-sudkharat** [comment]
Hi @fischaz, Could you please share your mail id with us? so, our concern team connect with you for further details. Thanks!

**Comment by fischaz** [comment]
Hi @v-sudkharat , sadly, I feel reticent in providing private information in a public place. if you can share yours, I'll send you an email to continue the discussion via email.

**Comment by v-sudkharat** [comment]
Hi @fischaz, sure please share you mail id with us on - v-sudkharat@microsoft.com. Thanks!

**Comment by v-sudkharat** [comment]
Hi @fischaz, Gentle Reminder: We are waiting for your response on this issue. If you still need to keep this issue active, please respond to it in the next 2 days. If we don't receive a response by 19-12-2023 date, we will be closing this issue. 		
Thanks!

**Comment by fischaz** [comment]
I'm checking if we can share that information internally, I've passed it on to my manager.
regards.

**Comment by v-sudkharat** [comment]
Hi @fischaz, thanks for sharing update with us. Thanks!

**Comment by fischaz** [comment]
I will be closing this issue. 

Basically, per the 2 examples above, there is a feature in Sentinel that if the Logs ingested have a TimeGenerated older than two days old, then the Time will be reset to the ingestion time. 

This matches the 2 examples where:
* the SQS queue was disabled for 4 days, so around have of the events in that Queue would have the time reseted.
* The second example picked specifically a AWS Event which was delivered to the S3 object 3 days after it happened.

For reference this is documented in https://learn.microsoft.com/en-us/azure/azure-monitor/logs/data-ingestion-time

**Comment by v-sudkharat** [comment]
Hi @fischaz, Thank you for closing this issue. If you still need support for this issue, feel free to re-open it any time. Thank you for your co-operation.

**Comment by dwrusse** [comment]
@fischaz Thanks for reporting this and digging into it, I am also noticing the same issue with the legacy connector and I was just hoping you could clarify where in the linked documentation you see this behavior mentioned?  I went through it myself and could not see the bit about using the ingestion time if the delay is longer than 2 days?
