### ISSUE TITLE
UserMap Workbook not identifying Location Details

### ISSUE THREAD

**Issue by jross1012** [Azure/Azure-Sentinel#915]
**Describe the bug**
Customer reported and demoed that using the "UserMap" workbook is not able to show data on the two map graphics that the workbook contains. In the Workbook's Map Settings the latitude and longitude fields are not translating into data points on the map. To get the maps showing data points I had to rename the final variables for latitude and longitude and re run the query, which then yielded the results:
1st Map: Variables are {lat & lon} changed to {latitude & longitude}
2nd Map: Variables are {latitude_ & longitude_} changed to {latitude & longitude}

**To Reproduce**
1. Go to 'UserMap' workbook
2. View malicious events map and user sign in maps
3. Observe error that says "Location Details missing"

**Expected behavior**
The variables defined in the workbook and listed in the map settings should load latitude and longitude data points on the two maps

**Additional context**
Two customers have expressed that they had the issue and the renaming of the variables fixed both

**Comment by CliveW-MSFT** [comment]
Acknowledged, a new version, that fixes this is almost done, as well as a full update and extra views. I'm just testing and adding to the help content.

**Comment by jross1012** [comment]
Thanks Clive!

**Comment by CliveW-MSFT** [comment]
Fixes and new features / and a general update have been added to: https://github.com/Azure/Azure-Sentinel/pull/980

**Comment by sarah-yo** [comment]
Closing as updates have been added
