### ISSUE TITLE
Zoom web-hook Sentinel connector does not pass Zoom validation

### ISSUE THREAD

**Issue by aka0** [Azure/Azure-Sentinel#9163]
**Describe the bug**
On Oct 23, 2022, Zoom requires web-hook destination in order receive web-hook events. As such, newly deployed Zoom connector would not be able to receive events. 

**To Reproduce**
1. Select ‘Develop’ in the top right-hand corner and click ‘Build App’.
2. Select ‘Webhook Only’ as your app type.
3. Give your app a name.
4. Fill out the required Basic Information and click continue.
5. Under the Feature Tab enable the ‘Event Subscriptions’ toggle and click ‘Add new event subscription’.
6. Set a subscription name and in the Event notification endpoint URL enter your Function App URL.
7. Click Validate

Validation will fail

**Expected behavior**
Validation passes

**Screenshots**

![image](https://github.com/Azure/Azure-Sentinel/assets/941108/ffda4674-c00e-47dd-adcb-93d50d4f6d1a)

**Additional context**
1. https://devsupport.zoom.us/hc/en-us/articles/360060332591-How-to-add-Webhooks-to-an-app
2. https://developers.zoom.us/docs/api/rest/webhook-reference/#validate-your-webhook-endpoint

**Comment by v-sudkharat** [comment]
Hi @aka0, thanks for flagging this issue, we will soon get back to you on this. Thanks!

**Comment by v-muuppugund** [comment]
Hi @aka0 ,Could you please confirm whether we are using zoom reports solution in sentnel?

**Comment by aka0** [comment]
> Hi @aka0 ,Could you please confirm whether we are using zoom reports solution in sentnel?

No. I was trying to use Zoom data connector (web-hook).

See: https://github.com/Azure/Azure-Sentinel/blob/master/DataConnectors/Zoom/ZoomLogs/run.ps1

ZoomReport solution also does not work because Zoom has deprecated JWT authentication in June 2023.

Ref: https://developers.zoom.us/blog/jwt-deprecation-guide/

**Comment by v-muuppugund** [comment]
HI 

> > Hi @aka0 ,Could you please confirm whether we are using zoom reports solution in sentnel?
> 
> No. I was trying to use Zoom data connector (web-hook).
> 
> See: https://github.com/Azure/Azure-Sentinel/blob/master/DataConnectors/Zoom/ZoomLogs/run.ps1
> 
> ZoomReport solution also does not work because Zoom has deprecated JWT authentication in June 2023.
> 
> Ref: https://developers.zoom.us/blog/jwt-deprecation-guide/

@aka0 Working on the https://github.com/Azure/Azure-Sentinel/blob/master/DataConnectors/Zoom/ZoomLogs/run.ps1 issue, will update you

ZoomReport solution also does not work because Zoom has deprecated JWT authentication in June 2023. its development done and we are working to production it, soon you will get the production version.

**Comment by v-muuppugund** [comment]
> HI
> 
> > > Hi @aka0 ,Could you please confirm whether we are using zoom reports solution in sentnel?
> > 
> > 
> > No. I was trying to use Zoom data connector (web-hook).
> > See: https://github.com/Azure/Azure-Sentinel/blob/master/DataConnectors/Zoom/ZoomLogs/run.ps1
> > ZoomReport solution also does not work because Zoom has deprecated JWT authentication in June 2023.
> > Ref: https://developers.zoom.us/blog/jwt-deprecation-guide/
> 
> @aka0 Working on the https://github.com/Azure/Azure-Sentinel/blob/master/DataConnectors/Zoom/ZoomLogs/run.ps1 issue, will update you
> 
> ZoomReport solution also does not work because Zoom has deprecated JWT authentication in June 2023. its development done and we are working to production it, soon you will get the production version.

Hi @aka0 ,still working on the validation issue at zoom side and next update is 13/10/2023

**Comment by aka0** [comment]
Hi @v-muuppugund ,

I added validation to the Zoom webhook connector. See PR: https://github.com/Azure/Azure-Sentinel/pull/9201

**Comment by v-muuppugund** [comment]
> Hi @v-muuppugund ,
> 
> I added validation to the Zoom webhook connector. See PR: #9201

Hi @aka0 , ok, just want to update, actually gone through the changes/code of zoom logs at https://developers.zoom.us/docs/api/rest/webhook-reference/#validate-your-webhook-endpoint ,thought of changing the code in couple of days ,as working on other priority items,Thanks

**Comment by v-muuppugund** [comment]
Hi @aka0 ,got update reg PR comments resolution and team is working on testing it and may require some testing screen shots.

**Comment by v-muuppugund** [comment]
> Hi @aka0 ,got update reg PR comments resolution and team is working on testing it and may require some testing screen shots.

Hi @aka0 ,reviewed the PR again,please resolve the comments and let us share convenient time for meeting for the same for any queries

**Comment by v-muuppugund** [comment]
Hi @aka0 ,As discussed in today's call reviewed the PR and resolved few comments and will be working on the below changes
1.New version package
2.Short link creation
3.Pointing package with new target
4.Arm template updates
5.Schedule call with you on monday i.e 06Nov23

**Comment by v-muuppugund** [comment]
Hi @aka0 ,As discussed,scheduled call for this pr on tuesday i.e. 11/7/23

**Comment by v-muuppugund** [comment]
Made changes in PR, reviewed,tested with author,so closing the issue
