### ISSUE TITLE
Microsoft Exchange Security - Exchange On-Premises - Microsoft Exchange Logs and Events - Step 2 Option 1 connector is configured for firewall logs instead of Event logs #8872

### ISSUE THREAD

**Issue by javbux** [Azure/Azure-Sentinel#9171]
**Describe the bug**
This issue reported under #8872 still exists

**To Reproduce**
Perfectly described in #8872 

**Expected behavior**
#8872 

**Screenshots**
#8872 

**Desktop (please complete the following information):**
#8872 

**Additional context**
The original issue is around creating the DCR  which means we are using Azure Monitor Agent

The comments from v-sudkharat are incorrect as this is based on the MMA.

Can this be re-looked at please as I have this issue and a few more in relation to the 
**Microsoft Exchange Logs and Events** data connector

**Comment by v-sudkharat** [comment]
Hi @javbux, Thanks for flagging this issue, we will investigate this issue and get back to you with some updates by 11-10-2023. Thanks!

**Comment by v-sudkharat** [comment]
Hi @javbux, could you please explain the exact issue you are facing with detail explanation and if possible, please provide the screenshots. Thanks!

**Comment by javbux** [comment]
Hi @v-sudkharat, the issue is exactly as reported in #8872 
the screenshots and issue are in #8872 thats why I have not repeated.

**Comment by v-sudkharat** [comment]
Hi @javbux, thank you for response, we are investigating this issue, and we will share you update by 18-10-2023. Thanks!

**Comment by v-sudkharat** [comment]
Hi @javbux, we are reached out to the concerned team for this issue, once we receive an update on this, we will update you. Thanks!

**Comment by v-sudkharat** [comment]
Hi @javbux, we connected the respective data connector team for this issue, they are working on this issue, but there is no ETA. 
Meanwhile, you can refer below document and steps to configure the DCR (Azure Monitor Agent) for pull the windows logs. 
**https://learn.microsoft.com/en-us/azure/azure-monitor/agents/data-collection-rule-azure-monitor-agent?tabs=portal**

1. Create DCR:
![image](https://github.com/Azure/Azure-Sentinel/assets/132428394/1e7bf040-0756-4753-84bc-d7e74c25fb40)

2. Add your resources: 
![image](https://github.com/Azure/Azure-Sentinel/assets/132428394/03ee5cad-2ceb-4a98-8ca5-87dec68db6ba)

3. Select Data Source Type to Windows Events Logs
![image](https://github.com/Azure/Azure-Sentinel/assets/132428394/4f3acc84-8d74-49a9-91f1-e8d8f3b5fed4)

4. Select the event logs
![image](https://github.com/Azure/Azure-Sentinel/assets/132428394/f2ae36fc-54f4-4c38-99d5-98ccd3409ad8)

5. Add data source 
![image](https://github.com/Azure/Azure-Sentinel/assets/132428394/18958e29-1a4a-4878-8772-d6997b4675eb)
![image](https://github.com/Azure/Azure-Sentinel/assets/132428394/72fb9ef8-c8ca-4e5e-b6ba-ef004d0d1b2b)

6. Create the rule.
![image](https://github.com/Azure/Azure-Sentinel/assets/132428394/79d70b2d-be55-4a08-89f5-08175a5b9684)

We hope these steps help you. Thanks!

**Comment by v-sudkharat** [comment]
Hi @javbux, hope you are doing well, could you please have a look at above comment? and share feedback with us. Thanks!

**Comment by v-sudkharat** [comment]
Hi @javbux, Gentle Reminder: We are waiting for your response on this issue. If you still need to keep this issue active, please respond to it in the next 2 days. If we don't receive a response by 01-11-2023 date, we will be closing this issue. 		
Thanks!

**Comment by javbux** [comment]
Hi @v-sudkharat 
Apologies I have been on leave, let me try this week and get back to you.

**Comment by v-sudkharat** [comment]
Hi @javbux, Thank you for your response. Please check and share the feedback with us. 
Thanks!

**Comment by javbux** [comment]
Hi @v-sudkharat, thanks for your guide.
On review I am already collecting the application and system logs with a DCR.

What I would like is the **MSExchange Management** logs which would be collected via the data connector which doesn't work currently

https://github.com/nlepagnez/ESI-PublicContent/blob/main/README.md#option-1---exchange-admin-audits

![image](https://github.com/Azure/Azure-Sentinel/assets/147181330/a06ec754-1899-4902-87f6-299f82e420f5)

Do you have the necessary steps that would need to be performed so it is collected and entered into the right table?

**Comment by v-sudkharat** [comment]
Hi @javbux, Thank you for sharing response with us. We are reaching out to the data connector concerned team for this issue, once we receive an update on this, we will update you by 09-11-2023. Thanks!
