### ISSUE TITLE
Microsoft Exchange Logs and Events - Data Connector

### ISSUE THREAD

**Issue by javbux** [Azure/Azure-Sentinel#9172]
**Describe the bug**

I have a couple of issues with the Microsoft Exchange Logs and Events - data connector
What is the best way to get a screen share to go through them or should I log with Microsoft and not here?

Issues

- Using a template to deploy a DCR does not work as my Log Analytics is not in the same RG as my DCR or DCE
(I believe that's the issue).

- Another DCR does not do what the instructions suggest should happen.

- Following the manual steps of creating a DCR/DCE puts data in table that the connector is not using

**To Reproduce**
From the Content Hub I have installed the **Microsoft Exchange Security for Exchange On-Premises** solution
which gives me two data connectors

          For the **Microsoft Exchange Logs and Events** - Data Connector
          On the Instructions Page, Under Configuration
          Step 2. Deploy log ingestion following choose options
          [Option 1] MS Exchange Management Log collection
          The Data Collection Rule is wrong and does not work to populate the Event table - have reported this #9171 

[Option 5] IIS logs of Exchange Servers
Option 1 - Azure Resource Manager (ARM) Template
Use this method for automated deployment of the DCE and DCR.

A. Create DCE (If not already created for Exchange Servers)
Click the Deploy to Azure button below.

When I click the button, I end up on Microsoft Bing. The URL in the address bar shows this
https://www.bing.com/?ref=aka&shorturl=sentinel-ESI-DCEExchangeServers

          [Option 5] IIS logs of Exchange Servers
          Select how to stream IIS logs of Exchange Servers
          Option 2 - Manual Deployment of Azure Automation
          Use the following step-by-step instructions to deploy manually a Data Collection Rule.
          
          A. Create DCE (If not already created for Exchange Servers)
          B. Create DCR, Type IIS log
    
          If I follow the above steps and create my DCR manually, the IIS logs appear in the W3CIISLog
          For the connector I believe you want them in the Microsoft-W3CIISLog table
    
    
**Expected behaviour**
I would expect the Deploy to Azure template to work

1. where I have my Log Analytics in one Resource Group, my Data Collection Rule in another resource group and My Data Collection Endpoint in another.
2. be taken to the right location, not Bing

I would expect where I follow the instructions to create DCR/DCE manually, that the data will end up in the right table.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser : Edge
 - Version : 117

**Additional context**
I'm new here, is this the right place to be reporting these issues?

**Comment by v-sudkharat** [comment]
Hi @javbux, Thanks for flagging this issue, we will investigate this issue and get back to you with some updates by 12-10-2023.  Thanks!

**Comment by v-sudkharat** [comment]
Hi @javbux, this issue needs to be further investigation. could you please create a support case for this issue? so, support team can connect with you to get more details that are needed about the problem and assist you in fixing it.
Please confirm us once you raise a support case so that we can close this issue from GitHub.

Thanks!

**Comment by javbux** [comment]
Thank you @v-sudkharat, this is now logged.
Support request ID: 	2310130050004078

**Comment by v-sudkharat** [comment]
Hi @javbux, Thanks for confirmation, closing this issue. If you still need support for this issue, feel free to re-open it any time. Thank you for your co-operation.
