### ISSUE TITLE
Duplicate alert rule template guid (id)

### ISSUE THREAD

**Issue by bittib010** [Azure/Azure-Sentinel#9174]
**Describe the bug**
Two rules has the same ID (alert rule template guid).

These: 
Detections/LAQueryLogs/UserSearchingForVlPUserActivity.yaml
Playbooks/Update-CVE-lPs-WatchListwithGreyNoise/NetworkSearchingForGreyNoiselPbyCVEActivity.yaml

**To Reproduce**
Look at ID: f7f4a77e-f68f-4b56-9aaf-a0c9d87d7a8e

**Expected behavior**
Made it tricky to automate community rules with script as this would cause a collision in terraform. Expected these to be unique and so does Terraform.
**Screenshots**
![image](https://github.com/Azure/Azure-Sentinel/assets/77796831/a55ec55f-e6bb-4e3f-ad5f-fadf78fd68ef)

**Comment by v-rbajaj** [comment]
Hi @bittib010, thanks for suggesting this, really appreciate this. We have raised this PR #https://github.com/Azure/Azure-Sentinel/pull/9210
