### ISSUE TITLE
AzureFunctionVMwareCarbonBlack using depreciated notification API throwing internal server errors

### ISSUE THREAD

**Issue by CyberNinja97** [Azure/Azure-Sentinel#9175]
**Describe the bug**
The Function App ([run.ps1](https://github.com/Azure/Azure-Sentinel/blob/master/Solutions/VMware%20Carbon%20Black%20Cloud/Data%20Connectors/AzureFunctionVMwareCarbonBlack/run.ps1)) calls the wrong VMware Carbon Black Cloud REST API integrationServices/v3/notifications. 

https://github.com/Azure/Azure-Sentinel/blob/41a237b42b0b8c374ed52cc59f314a94b629f50a/Solutions/VMware%20Carbon%20Black%20Cloud/Data%20Connectors/AzureFunctionVMwareCarbonBlack/run.ps1#L297

This one has been depreciated, as per the carbon black [documentation](https://developer.carbonblack.com/reference/carbon-black-cloud/cb-defense/latest/rest-api/). As a result, internal server errors (500) are thrown when the function app tries to retrieve alerts from carbon black.

The documentation also lists a [migration guide.](https://developer.carbonblack.com/reference/carbon-black-cloud/guides/api-migration/notification-migration)

The following two errors can be retrieved from the function app's logging (same timestamps):
1. ERROR: Response status does not indicate success: 500 (Internal Server Error)
2. INFORMATION: Notifications API status failed. Please check.

**To Reproduce**

To Reproduce:
1. Deploy the carbon black connector
3. Ingest carbon black alerts using the SIEM API

**Expected behavior**
Expected behavior is successful ingestion of the notifications/alerts into sentinel.

**Screenshots**

**Desktop (please complete the following information):**
N/A

**Smartphone (please complete the following information):**
N/A

**Additional context**

**Comment by v-muuppugund** [comment]
Hi @CyberNinja97 , thanks for flagging this issue, we will soon get back to you on this. Thanks!

**Comment by v-muuppugund** [comment]
Hi @CyberNinja97  Completed the initial analysis on this issue and working on changes to be made and next update is 19/10/23

**Comment by v-muuppugund** [comment]
Hi @CyberNinja97  Completed the changes as mentioned in the VM carbon black cloud for the new api as existing one deprecated  and working on locally testing ,expected ETA is 23Oct23 for the next update

**Comment by v-muuppugund** [comment]
Hi @CyberNinja97  ,while local testing new endpoint observed few issues and working on issues fixes , expected ETA is 27Oct23 for the next update.

**Comment by v-muuppugund** [comment]
Hi @CyberNinja97 ,I have made changes locally but want to test with other changes, before that i had a query has the error i am getting is 403 forbidden with test account, Could you please tell convenient time for testing and clarifying the queries in teams meeting,please share email id,so will block some time.

**Comment by v-muuppugund** [comment]
> Hi @CyberNinja97 ,I have made changes locally but want to test with other changes done for VM ware carbon black cloud, before that i had a query has the error i am getting is 403 forbidden with test account/trial accounts for v3/notifications api and also v7 api through post man, Could you please tell convenient time for testing and clarifying the queries for the errors/other queries for payload of carbon black, will modify accordingly in v7api post teams meeting & get back to you, please share email id, so will block some time.

Hi @CyberNinja97 , Gentle Reminder: We are waiting for your response on this issue. If you still need to keep this issue active, please respond to it in the next 2 days. Thanks

**Comment by woosters** [comment]
Hello, sorry for the late reply. You can reach me at 97CyberNinja@gmail.com.

Please send me an email detailing the exact steps you need me to take in order to validate / troubleshoot.

**Comment by CyberNinja97** [comment]
Hello, sorry for the late reply. You can reach me at 97CyberNinja@gmail.com

Please send detailed information regarding the steps needed to be taken to troubleshoot / validate.

**Comment by CyberNinja97** [comment]
I accidentally closed this on mobile. Reopening.

**Comment by CyberNinja97** [comment]
I accidentally closed this on mobile. Reopening.

**Comment by v-muuppugund** [comment]
> Hello, sorry for the late reply. You can reach me at [97CyberNinja@gmail.com](mailto:97CyberNinja@gmail.com)
> 
> Please send detailed information regarding the steps needed to be taken to troubleshoot / validate.

Hi @CyberNinja97 ,Will share details and need some information reg V7api our test account is having issues i.e. 403 forbidden issue and other queries related to payload,so will be scheduling the call for the discussing the same,Could you please share convenient time for the same for teams meeting,Thanks

**Comment by v-muuppugund** [comment]
> > Hello, sorry for the late reply. You can reach me at [97CyberNinja@gmail.com](mailto:97CyberNinja@gmail.com)
> > Please send detailed information regarding the steps needed to be taken to troubleshoot / validate.
> 
> Hi @CyberNinja97 ,Will share details but before that need some information reg V7api our test account is having issues i.e. 403 forbidden issue and other queries related to payload as we don't have access to VM ware,so will be scheduling the call for the discussing the same,Could you please share convenient time for the same for teams meeting,Thanks

Hi @CyberNinja97  Could you please share convenient time for discussion on above queries,will schedule teams meeting

**Comment by CyberNinja97** [comment]
I can do Thursday and/or Friday 10.00-11.00 and 13.00-14.00 CET.

**Comment by Ajay250496** [comment]
Hi @v-muuppugund,

I also have this issue and am looking for a resolution. Any chance you can share the code that you're working on?

**Comment by v-muuppugund** [comment]
> I can do Thursday and/or Friday 10.00-11.00 and 13.00-14.00 CET.

Sure, Will schedule the meeting, post the meeting, will work on tweaks, share the steps with you for testing it, Thanks

**Comment by v-muuppugund** [comment]
> Hi @v-muuppugund,
> 
> I also have this issue and am looking for a resolution. Any chance you can share the code that you're working on?

Hi @Ajay250496 ,We are still working on the payload and testing it ,once done,you all will get it,Thanks

**Comment by v-muuppugund** [comment]
> 97CyberNinja@gmail.com
@CyberNinja97 
Scheduled meeting tomorrow evening 5:30pm 06:30pm IST,please join the meeting

**Comment by CyberNinja97** [comment]
@v-muuppugund noted, will be there.

**Comment by v-muuppugund** [comment]
Hi @CyberNinja97 ,Thanks for joining the call for checking and verifying the payload,please find below items done on the call
1. In VM ware carbon black created the alert ,verified the payload and its using different version v1,
2. Tried calling V7 api by modifying the pay load with V7,but unable to call to due to user is unable to authenticate issue

meanwhile could you please raise a ticket at vm carbon cloud on this issue,Thanks,will connect with other user also.

**Comment by v-muuppugund** [comment]
Hi @CyberNinja97 ,Any update on the last call issue and update from VM carbon black team on ticket

**Comment by v-muuppugund** [comment]
Hi @CyberNinja97 ,Could you please update on the v7 api issue and update from VM carbon black team on ticket, Thanks.

**Comment by v-muuppugund** [comment]
Hi @CyberNinja97 ,Could you please update on the v7 api issue and update from VM carbon black team on ticket, Thanks.

**Comment by CyberNinja97** [comment]
Hello, unfortunately I have no clear update on the case. It's taking support a while, apparently. Will provide update when I have one. Hopefully soon.

**Comment by v-muuppugund** [comment]
Hi @CyberNinja97 ,Sure, will be waiting for your updates, Thanks

**Comment by v-muuppugund** [comment]
Hi @CyberNinja97 , Could you please post updates if you have any on VMware carbon black ticket,Thanks

**Comment by v-muuppugund** [comment]
Hi @CyberNinja97 ,Gentle reminder, Could you please post updates if you have any on VMware carbon black ticket, Thanks

**Comment by v-muuppugund** [comment]
Hi @CyberNinja97 ,Since we have not received a response in the last 5 days, we are closing your issue (https://github.com/Azure/Azure-Sentinel/issues/9175) as per our standard operating procedures. If you still need support for 	this issue, feel free to re-open at any time. Thank you for your co-operation!
