### ISSUE TITLE
Java implementation to call Data Connector API

### ISSUE THREAD

**Issue by kailasandhale** [Azure/Azure-Sentinel#918]
I am using the data collector APIs to push data to sentinel. I see few implementations given at https://docs.microsoft.com/en-us/azure/azure-monitor/platform/data-collector-api#sample-requests , which are mainly in Power Shell, Python and C#. I tried doing same with Java, but this is failing with error code 403. I tried replicating everything from the given examples, still no success. Could you please provide java implementation for the same

**Comment by dicolanl** [comment]
Hi @kailasandhale 
Please go to the page referenced above and share this feedback for the Log A team.
![image](https://user-images.githubusercontent.com/25964057/88933522-60a85b80-d234-11ea-9367-e19cc628a23f.png)
