### ISSUE TITLE
microsoft-sentinel-log-analytics-logstash-output-plugin fatal crash on logstash 8.10.2 

### ISSUE THREAD

**Issue by MprBol** [Azure/Azure-Sentinel#9180]
**Describe the bug**
Encountering a `SyntaxError` with the message "_1 is reserved for numbered parameter" when attempting to use the `microsoft-sentinel-log-analytics-logstash-output-plugin` on Logstash version 8.10.2.

**To Reproduce**
1. Install Logstash version 8.10.2.
2. Configure the `microsoft-sentinel-log-analytics-logstash-output-plugin` as per the documentation.
(eg 
```
  microsoft-sentinel-log-analytics-logstash-output-plugin {
        create_sample_file => true
        sample_file_path => "test" #for example: "c:\\temp" (for windows) or "/var/log" for Linux.
  }
```
4. Start Logstash.
5. Observe the error in the logs.

**Expected behavior**
The plugin should load without any syntax errors and send data to Azure Sentinel.

**Screenshots**

```
 39.19 /usr/share/logstash/vendor/bundle/jruby/3.1.0/gems/microsoft-sentinel-log-analytics-logstash-output-plugin-1.1.0/lib/logstash/sentinel_la/logsSender.rb:4: warning: parentheses after method name is interpreted as an argument list, not a decomposed argument
39.21 /usr/share/logstash/vendor/bundle/jruby/3.1.0/gems/microsoft-sentinel-log-analytics-logstash-output-plugin-1.1.0/lib/logstash/sentinel_la/logStashEventsBatcher.rb:3: warning: parentheses after method name is interpreted as an argument list, not a decomposed argument
39.30 [2023-10-09T12:07:05,391][FATAL][logstash.runner          ] The given configuration is invalid. Reason: Unable to configure plugins: (SyntaxError) /usr/share/logstash/vendor/bundle/jruby/3.1.0/gems/mime-types-2.6.2/lib/mime/types/logger.rb:26: _1 is reserved for numbered parameter
39.30       def initialize(_1, _2 = nil, _3 = nil)
39.30
39.32 [2023-10-09T12:07:05,395][FATAL][org.logstash.Logstash    ] Logstash stopped processing because of an error: (SystemExit) exit
39.32 org.jruby.exceptions.SystemExit: (SystemExit) exit
39.32 	at org.jruby.RubyKernel.exit(org/jruby/RubyKernel.java:795) ~[jruby.jar:?]
39.32 	at org.jruby.RubyKernel.exit(org/jruby/RubyKernel.java:758) ~[jruby.jar:?]
39.32 	at usr.share.logstash.lib.bootstrap.environment.<main>(/usr/share/logstash/lib/bootstrap/environment.rb:90) ~[?:?]
------
failed to solve: process "/bin/sh -c logstash --config.test_and_exit" did not complete successfully: exit code: 1
```

**Desktop (please complete the following information):**
 - Version: Logstash 8.10.2

**Additional information**

Im using logstash in docker;; base image  docker.elastic.co/logstash/logstash:8.10.2

**Comment by MprBol** [comment]
I also get a similar error for the older version, `microsoft-logstash-output-azure-loganalytics`. I understand that's no longer supported. However we would very much appreciate a fix for that version too if possible.

**Comment by v-sudkharat** [comment]
Hi @MprBol, the` logstash 8.10.2 version` is enhancement, the Microsoft Sentinel's Logstash output plugin supports the following versions- 
![image](https://github.com/Azure/Azure-Sentinel/assets/132428394/fafb9c4c-f29a-4989-a43a-288a08b37f39)

please refer the below documentation for reference-
`https://github.com/Azure/Azure-Sentinel/tree/master/DataConnectors/microsoft-sentinel-log-analytics-logstash-output-plugin#1-install-the-plugin `

so, closing this issue. If you still need support for this issue, feel free to re-open it any time. Thank you for your co-operation.

**Comment by pa-jberanek** [comment]
Just discovered this issue on our own logstash instances, and I find the below notification of closure to be very unimpressive indeed. Are people just meant to not update logstash (including any security updates) and wait until you get around to making the plugin work with current versions of logstash!?
