### ISSUE TITLE
Cloudflare Function App fails when encountering log files larger than 2MB

### ISSUE THREAD

**Issue by aaronbeuhring** [Azure/Azure-Sentinel#9183]
**Describe the bug**
If log files that are larger than 2MB are pushed into the Azure Storage Container used by the Function App to pick up logs it will fail to process the logs and leave them. Eventually, when the number of log files greater than 2MB exceeds the number set for MAX_CONCURRENT_PROCESSING_FILES the function app will keep trying to process those 20 but won't ingest any new logs. 

There is a variable in the function app code called MAX_CHUNK_SIZE_MB which is set by default to 2MB. This number should probably be higher and also this variable should be made available as a configurable property in the [Function App properties](https://github.com/Azure/Azure-Sentinel/blob/master/Solutions/Cloudflare/Data%20Connectors/azuredeploy_Cloudflare_API_FunctionApp.json). Manually adding and entry for that variable and setting it to a higher number allowed the function app to process larger log files.

**To Reproduce**
1. Receive 20 + log files from cloudflare log push that are larger than 2MB 
2. watch it fail to process any new log files.

**Expected behavior**
Log files are expected and should be processed

**Comment by v-sudkharat** [comment]
Hi @aaronbeuhring, Thanks for flagging this issue, we will investigate this issue and get back to you with some updates by 13-10-2023. Thanks!

**Comment by v-sudkharat** [comment]
Hi @aaronbeuhring, could you please share the invocation logs with us? it would be helpful for us. Thanks!

**Comment by v-sudkharat** [comment]
Hi @aaronbeuhring, hope you are doing well. Could you please have a look at above comment?  Thanks!

**Comment by aaronbeuhring** [comment]
Attached is an invocation log. The file 20231013/20231013T205217Z_20231013T205316Z_c2fb5f45.log.gz is over 5MB in size which exceeds the current setting I have for MAX_CHUNK_SIZE so it fails and retries each invocation. According to cloudflare there is no way to limit the size of log files that are sent via log push so it seems like there should not be a limit on chunk size and instead the function app should be able to handle log files of any size.

[invocationlog.csv](https://github.com/Azure/Azure-Sentinel/files/13033534/invocationlog.csv)

**Comment by v-sudkharat** [comment]
Hi @aaronbeuhring, thanks for sharing the log file with us. We will investigate this issue and get back to you with updates by - 25-10-2023. Thanks!

**Comment by v-sudkharat** [comment]
Hi @aaronbeuhring, we trust this message finds you well. We checked the solution contains; this solution is supported with Cloudflare.
We kindly request you to raise an issue with Cloudflare's support team and let us know, so we can close this issue from GitHub. 
Sharing the Cloudflare mailID and link - 
Mail Id - "support@cloudflare.com"
Link -      "https://support.cloudflare.com"

Thanks!

**Comment by v-sudkharat** [comment]
Hi @aaronbeuhring, could you please have a look at above comment. Thanks!

**Comment by aaronbeuhring** [comment]
I've opened a ticket with cloudflare that has made no progress. This code
is in your repo so I believe this is the right place for the bug to be
logged. You should coordinate with whoever is responsible for the code in
your repo to resolve it or else what is the point of having it in your repo?

**Comment by v-sudkharat** [comment]
Hi @aaronbeuhring, thank you for sharing response with us. Actually, the `CloudFlare` solution which is in our GitHub repo is partner supported and this is supported by `CloudFlare` team, so we cannot make any changes in solution. 
You can connect with them via a below mail and links- 
Mail Id - "[support@cloudflare.com](mailto:support@cloudflare.com)"
Link - "https://support.cloudflare.com/"
 So, closing this issue. If you still need support for this issue, feel free to re-open it any time. Thank you for your co-operation.

**Comment by aaronbeuhring** [comment]
You should be working with your partners then to resolve the issue. MS
advertises that it has working partner integrations and positions itself as
providing these. This is a terrible customer experience.

**Comment by Goutham051101** [comment]
@jimbobsyouruncle  I am facing similar issue , Do you found any solution./
