### ISSUE TITLE
ExternalData to Reference API Data

### ISSUE THREAD

**Issue by panovattack** [Azure/Azure-Sentinel#919]
Can the external data feature be changed to permit API calls to REST end points which return data in the appropriate format?  (csv, json, etc.)  This would be like the fileprofile function in MTP.

**Comment by ashwin-patil** [comment]
Hi @panovattack,

Per the documentation of externaldata, it works with persistent storage mechanisms (e.g. Azure blob, ADL, ADLS Gen 2etc.). It invokes Azure blob API underneath and works with regular (non-Azure storage) web resources (e.g. raw.github.com) , but not all web resources/REST endpoints are supported.

For REST endpoints, i would suggest to use logic app HTTP triggers which supports directly making HTTP request to REST endpoint , capture the output (csv, json) , parse and do other stuff. 

Example blog on similar use-case in case you have not already seen
- https://techcommunity.microsoft.com/t5/azure-sentinel/sending-rest-api-data-to-azure-sentinel/ba-p/558896

Alternatively you can also post this as an idea in Azure feedbacks and define your use-cases which will be reviewed by LA product team. 
- https://feedback.azure.com/forums/267889-azure-monitor-log-analytics

**Comment by ashwin-patil** [comment]
I will close this issue based on the above comments and no follow-up action needed.
