### ISSUE TITLE
Netskope Data Connector Issue

### ISSUE THREAD

**Issue by Shubham-Lale-Work** [Azure/Azure-Sentinel#9196]
Hello, I'm raising an issue with the Netskope Data Connector (Azure Function) we configured for one of our client .

On the "Solutions/Netskope/Data Connectors/Netskope/AzureFunctionNetskope/run.ps1" repo . looking into for history its stated as function app code is changed from v1 API to v2 API.

At the time of deployment it was configured using V1 API requirements, but after change to v2 API the function app doesn't seem to work properly.

Also, Api token required from Netskope for configuration does it has to be V1 based or V2 based. Can someone help me with the issue on priority?

**Comment by v-rbajaj** [comment]
Hi @Shubham-Lale-Work, thanks for flagging this, we acknowledge your concern and we will get back to you by 18 Oct 2023

**Comment by v-rbajaj** [comment]
Hi @Shubham-Lale-Work, would really appreciate if you could provide us some screenshots of the error messages and logs where ever possible to understand the issue completely.

**Comment by v-rbajaj** [comment]
Hi @Shubham-Lale-Work, can you please provide some update here?

**Comment by v-rbajaj** [comment]
Hi @Shubham-Lale-Work, We are awaiting for your response on this issue. If you still need to keep this issue active please respond on it in the next 2 days. If we don't receive response, we will be close this issue.

**Comment by v-rbajaj** [comment]
Hi @Shubham-Lale-Work, Since we have not received a response in the last 5 days, we are closing your issue
[#](https://github.com/Azure/Azure-Sentinel/issues/9196) as per our standard operating procedures. If you still need support for this issue, feel free to re-open at any time. Thank you for your co-operation.
