### ISSUE TITLE
Okta_FailedLoginsFromUnknownOrInvalidUser: Tested but no results

### ISSUE THREAD

**Issue by jross1012** [Azure/Azure-Sentinel#921]
**Describe the bug**
Customer attempted to test the analytic rule but received no results via incidents or query results. Customer triggered 51 failed logins from an account that does not exist, but this did not trigger the analytic rule. Running the query shows "No Results"

Looking at the Okta workbook, running a query to display top 10 users with a failed login in Okta_CL reveals the non-existant account with 51 failed logins.

Shouldn't this test account have been caught by the analytic template? Additionally doing a search of all the "outcome_reasons_s" does not include any "UNKNOWN_USER" value, rather it includes: FailedLogin, AccountLockout, etc.

**To Reproduce**
1. Go to sign in page and try to login with a nonexistant account
2. Attempt to sign in 50+ times
3. View query results from: FailedLoginsFromUnknownOrInvalidUser
4. No Results

**Expected behavior**
Signing in with nonexistant test username should have triggered the alert

![MicrosoftTeams-image (1) (1)](https://user-images.githubusercontent.com/49956478/89055162-d123ab00-d30e-11ea-913c-b8a85811b1ee.png)
![MicrosoftTeams-image (2) (1)](https://user-images.githubusercontent.com/49956478/89055164-d1bc4180-d30e-11ea-9b2f-ba20283ce09d.png)

**Comment by jross1012** [comment]
Customer attempted to test the 'Potential Password Spray Attack' Analytic Rule as well with no success. Customer locked out 4 accounts with 5 password attempts within the same minute and received no analytic rule results. Customer attempted to find results by running the analytic query in the workspace but this yielded no results.
![OktaAnalyticPasswordSprayLogic](https://user-images.githubusercontent.com/49956478/89055010-8f930000-d30e-11ea-8ec7-6094f9d0fe7f.png)
![OktaWorkbook](https://user-images.githubusercontent.com/49956478/89055013-902b9680-d30e-11ea-8688-e4fdf946298f.png)

**Comment by chicduong** [comment]
hey, @jross1012, I authored this rules, here to help.

Can you run the search:
Okta_CL
| where actor_alternateId_s in ("user1@kloveair1.com","user2@kloveair2.com")
| summarize count() by eventType_s, outcome_reason_s

**Comment by jross1012** [comment]
User1 and User 2 replaced with the actual users that tested
![Snag_19ab33e7](https://user-images.githubusercontent.com/49956478/89320299-2aa11800-d636-11ea-9f90-62e29b4b2139.png)

**Comment by chicduong** [comment]
@jross1012 are those users valid user accounts?

**Comment by jross1012** [comment]
Yes the two accounts are the same accounts referenced in the previous screen clippings: jfink and jtabujara
![Snag_1a8bcdf3](https://user-images.githubusercontent.com/49956478/89342983-6fd64180-d658-11ea-8d35-6efc825dde71.png)

**Comment by jross1012** [comment]
@chicduong should the password spraying analytic rule be detecting outcome_reason_s = INVALID_CREDENTIALS as noted in the screenshot?

**Comment by chicduong** [comment]
@jross1012 ah ok there may be a few different threads here that are causing some confusion.

- Potential Password Spray Attack - it seems like this Analytics is incorrectly titled, this rule should be Account Lockouts. Could they run the test to trigger an account lockout based on their lockout settings?

- FailedLoginsFromUnknownOrInvalidUser - Can we run the query I mentioned above for these test users to see what the outcome_reason_s is?

**Comment by jross1012** [comment]
@chicduong queries have been run, please see results below:
![ValidUser](https://user-images.githubusercontent.com/49956478/89436332-f2174200-d6fa-11ea-8be0-759218a0fb03.png)
![TestingOktaRule](https://user-images.githubusercontent.com/49956478/89436341-f4799c00-d6fa-11ea-9f7d-bb87bbaa50ce.png)

**Comment by chicduong** [comment]
@jross1012 are these test attempts logging onto the Okta console?

**Comment by jross1012** [comment]
yes

**Comment by sarah-yo** [comment]
Fix is available for this
