### ISSUE TITLE
Broken links in jira sync project

### ISSUE THREAD

**Issue by stf-nl** [Azure/Azure-Sentinel#9214]
**Describe the bug**
in Solutions/AtlassianJiraAudit/Playbooks/Sync-Incidents there are links to images and files which are broken.

can you please fix them and restore the missing images.

#https://github.com/Azure/Azure-Sentinel/tree/f5a16365151b11a66db24d860a3a159c561014af/Solutions/AtlassianJiraAudit/Playbooks/Sync-Incidents

#5670

**Comment by v-rbajaj** [comment]
Thanks for flagging this issue, we acknowledge your concern and will get back to you by 17 Oct 2023

**Comment by v-rbajaj** [comment]
Hi @stf-nl, sorry for delay, we are still investigating on this and we will get back to by 27 Oct 2023.

**Comment by v-rbajaj** [comment]
Hi @stf-nl, we have raised #9331 to fix this issue.
