### ISSUE TITLE
Update rules in GUI shows wrong error message

### ISSUE THREAD

**Issue by bittib010** [Azure/Azure-Sentinel#9215]
**Describe the bug**
We are using Terraform for our rules and constantly updating the community rules with a script, keeping us up to date almost every day. This leads us to stay ahead of Sentinel some times making sentinel tell us to update the rule even when we are ahead. We've had customers complaining about us telling us to update the rule set and so on. Is it possible to change Sentinels lookup to avoid looking at rules that are newer than what Sentinel has already stated as the newest?

**To Reproduce**
Deploy a rule with terraform that is newer than the current one listed in sentinel as the newest. Here is an example of such a rule: https://raw.githubusercontent.com/Azure/Azure-Sentinel/f5a16365151b11a66db24d860a3a159c561014af/Solutions/Azure%20Active%20Directory/Analytic%20Rules/AuthenticationMethodsChangedforPrivilegedAccount.yaml

Current version is 1.0.8 but Sentinel says it is 1.0.7. Which makes me according to sentinel "out of date".

**Screenshots**
![image](https://github.com/Azure/Azure-Sentinel/assets/77796831/c3c88e96-89d1-49c6-8be3-73b28159032e)

![image](https://github.com/Azure/Azure-Sentinel/assets/77796831/8d2b06c9-7cc5-4ece-abe6-f0d6bcee40a5)

**Comment by v-sudkharat** [comment]
Hi @bittib010, Thanks for flagging this issue, we will investigate this issue and get back to you with some updates by 20-10-2023. Thanks!

**Comment by v-sudkharat** [comment]
Hi @bittib010, we have recently updated the solution, so to get the latest analytic rule version you have to update the solution from Content Hub.
Thanks!

**Comment by bittib010** [comment]
Thank you! But for those using other solution that do the update quicker there will always be an error. Is there a possibility to add or change the check to see if the rule is behind, rather than not equal to?

**Comment by v-sudkharat** [comment]
Hi @bittib010, there will be an update option (Icon) available to the solution, if there is any modification or update in content of the solution. Thanks!

**Comment by v-sudkharat** [comment]
Hi @bittib010, hope you are doing well. Could you please have a look at above comment and share response with us. Thanks!

**Comment by bittib010** [comment]
At the moment, I can't find any components that are out-of-date, which suggests two possibilities: either the update was successful, or everything is already aligned in a way that masks any existing errors. If the issue reappears, I'll either update this existing ticket or create a new one.

To provide more context on the issue I encountered: When I deploy rules that are actually more up-to-date than the solutions themselves, I still get a warning message indicating that the rule needs an update. In my experience, updates from your end typically lag a few days behind updates to the Git repository containing the rule. As a result, even when I update a rule directly from Git using Terraform and am ahead of the Sentinel solutions, Sentinel still prompts me to update, which is misleading.

**Comment by bittib010** [comment]
Sorry for misunderstanding you. The updates button are now located in the Solution it belongs to, could not find them in "analytics" blade anymore. But the error persists. Look at the image:
![image](https://github.com/Azure/Azure-Sentinel/assets/77796831/d0d66307-fec8-4b00-b8d9-9cbffcf78f9e)

So this accounts for alot of rule, and as far as my logic sense goes, there is a functionality that checks your current rule as an equal version. If it is not equal it is "out of date". It should rather be taken into account "if not equal and less than" then update, if it is ahead of the solution we shouldnt get the notification. Wouldnt you agree?

**Comment by v-sudkharat** [comment]
Hi @bittib010, thanks you for your response. Actually, the solution updates are available in `ContentHub` itself. We are sharing screenshots and document which help you to update the Analytic rule or Solution in Content Hub. 
1. Go to ContentHub and check for updates.
![image](https://github.com/Azure/Azure-Sentinel/assets/132428394/16ab8586-45fe-401d-be77-e2ae3b5a8a04)

2. You can filer the Solution updates by using Status Filter. (Add filter - Status - Update Available) 
![image](https://github.com/Azure/Azure-Sentinel/assets/132428394/dfd50703-ff09-408e-9310-01c662b83f0a)

3. Select the solution click on Actions and check on Update 
![image](https://github.com/Azure/Azure-Sentinel/assets/132428394/7206d920-5ff0-4acb-bd2a-860a131e69b0)

Once update is done, it will update the Solution to Latest version. 

Sharing the Document for reference-  **https://learn.microsoft.com/en-us/azure/sentinel/sentinel-solutions-deploy**

Please let us know this information helps you. So, we can close this issue from GitHub. Thanks!

**Comment by bittib010** [comment]
Thank you for providing that. Updating the rules are not the issue. We have a solution based on powershell for that. We only would like the icon of a necesary update to be removed if our rule is ahead of the  contenthun version. We deploy everything via terraform for all our customers. Some of which has been tuned to fit. Doing so for every customer is too much work when we can simply do it using pipelines.

**Comment by v-sudkharat** [comment]
Hi @bittib010, this issue needs to be further investigation from support team. Could you please create a support case for this issue? so, support team can connect with you to get more details that are needed about the problem and assist you in fixing it. Thanks!

**Comment by bittib010** [comment]
Yup. Ill try that. Thanks!

**Comment by v-sudkharat** [comment]
Hi @bittib010, Thanks for sharing the response. 
so, closing this issue from GitHub. If you still need support for this issue, feel free to re-open it any time. Thank you for your co-operation.
