### ISSUE TITLE
Defender for Identity Timestamp values do not match in Sentinel and Microsoft 365 Defender

### ISSUE THREAD

**Issue by ep3p** [Azure/Azure-Sentinel#9216]
**Describe the bug**
Timestamp column values for Defender for Identity do not match in Sentinel and in Microsoft 365 Defender

**To Reproduce**
1. Have a Sentinel workspace receiving events in Defender for Identity tables (e.g. IdentityQueryEvents or IdentityLogonEvents)
2. Go to Logs tab in Sentinel.
3. Take one event from IdentityQueryEvents or IdentityLogonEvents tables with:
```
union IdentityQueryEvents, IdentityLogonEvents
| summarize take_any(TimeGenerated, Timestamp, ReportId) by Type
```
4. Search for the same ReportId in Advanced Hunting in Microsoft 365 Defender with:
```
union IdentityQueryEvents, IdentityLogonEvents
| search "<found 1st ReportId in step 3>" or "<found 2nd ReportId in step 3>"
```
5. Observe Timestamp values might not match.

**Expected behavior**
Please, could Timestamp column have the same values in Sentinel and in Microsoft 365 Defender?

**Additional context**
Microsoft 365 Defender has an advantage over Sentinel for these events. Sentinel does not have the real value where an event might have happened.

The following 4 events where generated consecutively, a logon and a LDAP query are generated from one single action, and in Microsoft 365 Defender the Timestamp values show clearly this (the ```LDAP query``` is "generated" **1 second after** the ```LogonSuccess```). 

![image](https://github.com/Azure/Azure-Sentinel/assets/2527990/ad6bb06b-452b-4591-aa67-abc9ec7c9cf9)

BUT in Sentinel the Timestamp column does not have the same values. The order of the events is not kept. Thus, in Microsoft 365 Defender I can create a query that could match easily logon and LDAP query events, but in Sentinel I can't create it.

![image](https://github.com/Azure/Azure-Sentinel/assets/2527990/64e5c687-7237-4613-b20a-1ec5552c4f1a)

I would like Sentinel to show the real values from Defender for Identity, to be able to develop better detections rules, please.

**Comment by v-sudkharat** [comment]
Hi @ep3p, Thanks for flagging this issue, we will investigate this issue and get back to you with some updates by 20-10-2023. Thanks!

**Comment by v-sudkharat** [comment]
Hi @ep3p, just want to know, you are using the below (MicrosoftThreatProtection) data connector or any other standalone one?  
![image](https://github.com/Azure/Azure-Sentinel/assets/132428394/d29a0b86-1fe3-4c7b-bcaf-118808a161a6)

Please let us know which data connector you are using. Thanks!

**Comment by ep3p** [comment]
@v-sudkharat I believe that is the only connector to be able to receive Defender for Identity tables.

Yes, we are using that connector.

![image](https://github.com/Azure/Azure-Sentinel/assets/2527990/c515e33b-3891-4c0e-af1f-f4bca4f0aadc)

**Comment by v-sudkharat** [comment]
Hi @ep3p, Thanks for clarify. We are reaching out to data connector team. Once we receive an update from the team, we will update you. Thanks!

**Comment by v-sudkharat** [comment]
Hi @ep3p, we received the response from concern team, the Timestamp is populated by the “Timestamp” field as it appears in the data sent by M365D API. Could you please create a support case for this issue? so, team can investigate this issue and if required they can connect with you to get more details that are needed about the issue and assist you. 
Please let us know once you raise a Support Case, so we can close this issue from GitHub. Thanks!

**Comment by ep3p** [comment]
I have opened a support case, Support request number: 2310260050003360

You may close this issue, thank you very much for helping us.

**Comment by v-sudkharat** [comment]
Hi @ep3p, Thanks for confirmation, closing this issue. If you still need support for this issue, feel free to re-open it any time. Thank you for your co-operation.
