### ISSUE TITLE
Forcepoint CSG Solution

### ISSUE THREAD

**Issue by javbux** [Azure/Azure-Sentinel#9219]
**Describe the bug**
This recently changed from Preview and I had to re-set up but this time I could use AMA on the Syslog server I built.
When you install the solution you get two Data Connectors

[Deprecated] Forcepoint CSG via Legacy Agent
[Recommended] Forcepoint CSG via AMA

I followed the Configuration Steps on the connector page for **[Recommended] Forcepoint CSG via AMA**

First Bug I have is that the connected data connector lit up green is **[Deprecated] Forcepoint CSG via Legacy Agent**
and not [Recommended] Forcepoint CSG via AMA

Second Bug is the configuration guide no longer works and I get a page 404 not found

Third Bug is around how much data is being pulled down from Forcepoint Cloud; it appears to only get a certain amount of files every 10 minutes.

**To Reproduce**
When you install the solution you get two data connectors

[Deprecated] Forcepoint CSG via Legacy Agent
[Recommended] Forcepoint CSG via AMA

Try and follow the Configuration Guide and under Step B. Implementation options
Both Docker Implementation and Traditional Implementation take you to https://forcepoint.github.io/docs/csg_and_sentinel
with a message 

404
Page not found :(

The requested page could not be found.

**Expected behavior**

**Screenshots**
![image](https://github.com/Azure/Azure-Sentinel/assets/147181330/f91b9046-da99-4c5e-ad09-9c4c2a965beb)
![image](https://github.com/Azure/Azure-Sentinel/assets/147181330/aae3c722-722d-4f91-94fd-a2f177984c51)
![image](https://github.com/Azure/Azure-Sentinel/assets/147181330/956f084a-82d9-4fc1-ae0a-ede5d773f097)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Edge
 - Version 117

**Additional context**
I also logged this with Forcepoint who after trying to assist, suggested I log with the Community

**Comment by v-sudkharat** [comment]
Hi @javbux, Thanks for flagging this issue, we will investigate this issue and get back to you with some updates by 19-10-2023. Thanks!

**Comment by v-sudkharat** [comment]
Hi @javbux, thanks for sharing the bug description with us. 
For 1st bug - Could you please check and let us know in your workspace the `CollectorHostName` column is present? Use below query to get the schema. if No then `[Recommended] Forcepoint CSG via AMA` connector is not configured. And about the `[Deprecated] Forcepoint CSG via Legacy Agent` show as green because the workspace having the old data.
```
CommonSecurityLog
| getschema 
```
2nd bug - We're following up with the Forcepoint team on the configuration guide; if you have a support contract with them, you can get in touch with them while we're still working.

3rd bug - please check the data available in syslog table at your workspace, that data is sync to the `CommonSecurityLog` in same workspace. 

Thanks!

**Comment by javbux** [comment]
Hello @v-sudkharat, thanks for getting back to me.

Bug 1:
I do have the CollectorHostName column, screenshot below
![image](https://github.com/Azure/Azure-Sentinel/assets/147181330/e421900f-b7e2-41e4-97ba-d38894fa1ceb)

If I work off that being required, I can see from the data I have coming from AMA that CollectorHostName is not one of them
These are the fields being populated for Forcepoint CSG in CommonSecurityLog

TimeGenerated [UTC]
DeviceVendor
DeviceProduct
DeviceVersion
DeviceEventClassID
Activity
LogSeverity
DeviceAction
ApplicationProtocol
DestinationIP
FileType
FileName
RequestURL
RequestClientApplication
RequestMethod
SourceIP
SourceUserID
DeviceCustomString1
DeviceCustomString1Label
DeviceCustomString2

Bug 2:
This has been logged with Forcepoint who advised it should be looked at by the community here as they are not responsible for the Sentinel content.

Bug 3:
Is there anyone from the community who wrote the code who could explain the behaviour and how much data is being pulled back?  the data is being collected, but I dont know what determines how much and what is picked up every 10 minutes.

**Comment by v-sudkharat** [comment]
Hi @javbux, Thanks for your response. We are reaching out to the concerned team for connector configuration steps, once we receive an update on this, we will update you by 07-11-2023. Thanks!

**Comment by v-sudkharat** [comment]
Hi @javbux, hope you are doing well. We are still waiting for response from concerned team for the connector configuration steps, once we receive an update on this, we will update you. Thanks!

**Comment by javbux** [comment]
thanks @v-sudkharat 

Can you confirm that the concerned team are working on all 3 bugs I reported?
It hasn't been right since Mid Sept, how long do they need and how does Microsoft "encourage" a speedier resolution?
It seems that with anything from the Content Hub - support is slow.

**Comment by v-sudkharat** [comment]
Hi @javbux, Apologies for the delay in response. We will check the bug you've raised with our concerned team and will share an update with you.
Thanks!

**Comment by v-sudkharat** [comment]
Hi @javbux. I hope this message finds you well. Our team has been continuously followed up with the Forcepoint team, to address the issue and we are grateful for your patience and understanding. 
Please check on below your reported bug's - 

1st bug - As you mentioned the `CommonSecurityLog `table schema having `CollectorHostName `column. So, could you please check the `CollectorHostName  `column having data into it? if it is having the data the then `[Recommended] Forcepoint CSG via AMA `connector is get configured. 
But only column schema is there and not consisting of any data then the `[Deprecated] Forcepoint CSG via Legacy Agent` will get configured. 
It would be great if you share screenshots.  

2nd bug - We are able to access the configuration steps link. so, could you please check on the below link and try again - 
link -`https://frcpnt.com/csg-sentinel`

![image](https://github.com/Azure/Azure-Sentinel/assets/132428394/74c20daa-9f6f-42fd-9f8d-21c60ba54e70)

3rd bug - We are checking with the concern team on this. But FYI. As per the connector instruction page, it may take about 20 minutes until the connection streams data to your workspace. 
![image](https://github.com/Azure/Azure-Sentinel/assets/132428394/ed8a91fa-b1d9-452e-b12a-3ba67f6a7634)


Thanks!

**Comment by v-sudkharat** [comment]
Hi @javbux, Yes right, Based on the below connector **connectivityCriterias** query, the column called **sent_by_ama**, which will contain the value from the **CollectorHostName** column if it exists, Otherwise, it will be an empty string. So, **CollectorHostName** column should have the data to configure the AMA connector. 
![image](https://github.com/Azure/Azure-Sentinel/assets/132428394/e36e35fb-5d96-4537-97cf-fd010025b0b5)

Regarding the GitHub repo script. We will check on this and get back to you by 17-01-2024.

Thanks!

**Comment by v-sudkharat** [comment]
Hi @javbux, We have checked the details of GitHub repo script, which you highlighted. The Repo/Script is own by Forcepoint team, and we are not authorized to do any modification on it. 
We are kindly requesting you could you please raise issue with them in below shared repo link. so the Forcepoint team will can look into it. 
https://github.com/Forcepoint/fp-bd-csg-azure-sentinel/releases/tag/v1.0
Thanks!

**Comment by v-sudkharat** [comment]
Hi @javbux, This solution and the GitHub repository mentioned above are maintained by Forcepoint. Therefore, we are not authorized to make any modifications to it. As per our procedure, we cannot keep this issue open, so we are closing it on our GitHub. If you still require support for this issue, please feel free to reopen it at any time. Thank you for your cooperation.

**Comment by Gabrielpbs** [comment]
Hello, @javbux ! 

Were you able to resolve the connector issue via Forcepoint AMA? I'm also having the same problem.

I install the connector, the AMA agent on Linux and the connector still does not receive the data.

**Comment by Gabrielpbs** [comment]
Hello, @javbux ! 

Were you able to resolve the connector issue via Forcepoint AMA? I'm also having the same problem.

I install the connector, the AMA agent on Linux and the connector still does not receive the data.

**Comment by Gabrielpbs** [comment]
Hello, javbux! 

Were you able to resolve the connector issue via Forcepoint AMA? I'm also having the same problem.

I install the connector, the AMA agent on Linux and the connector still does not receive the data.

**Comment by javbux** [comment]
Hi @Gabrielpbs 

So I have the forcepointcloud logs coming in using AMA and populating the CommonSecurityLog but only the
[Deprecated] Forcepoint CSG via Legacy Agent - data connector shows connected still.
The other does not, just as I reported here.

The GitHub repo maintained by Forcepoint has had no updates for three years and no one came back to me, so I have just accepted it.

**Comment by Gabrielpbs** [comment]
Thank you very much for your feedback, JavBux!

Did you uninstall the Legacy agent and just install AMA?

**Comment by javbux** [comment]
In my case I started with a new ubuntu vm and installed the AMA agent, but had to amend the install command to use Python3

sudo wget -O Forwarder_AMA_installer.py https://raw.githubusercontent.com/Azure/Azure-Sentinel/master/DataConnectors/Syslog/Forwarder_AMA_installer.py&&sudo python3 Forwarder_AMA_installer.py
