### ISSUE TITLE
Function Fortinet-GetEntityDetails

### ISSUE THREAD

**Issue by kausd1** [Azure/Azure-Sentinel#9237]
**Describe the bug**
Request to look at the function app code. I have been seeing customers facing issue with it. On multiple occasions customers have fixed the code on their own. Mostly they are seeing error 500.

Also using postman, the rest api call works well. So not a network issue.
No Certificate issue.
An example where code changes were made by customer to fix the problem.
#4015 
https://github.com/Azure/Azure-Sentinel/issues/4015

**Screenshots**

![image](https://github.com/Azure/Azure-Sentinel/assets/117085560/89e2fc07-2f52-4fb7-943a-924fff372fbe)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by v-muuppugund** [comment]
Hi  @kausd1 , Thanks for flagging this issue, we will investigate this issue and get back to you with some updates by 23/10/2023. Thanks!

**Comment by v-muuppugund** [comment]
Hi @kausd1  , I tried to replicate the issue  but unable to replicate it, Could you please share exact play book details or path of it and error details,when on onwards its occuring/its frequest etc..

**Comment by kausd1** [comment]
@v-muuppugund Are we saying that the function code is working as expected in your test environment ?

**Comment by v-muuppugund** [comment]
@kausd1 As discussed over call,got the additional details about the issue,so will replicate the issue based on the details provided and get back to if require any details by 30Oct23

**Comment by v-muuppugund** [comment]
Hi @kausd1,I have below queries after going through email chain for the issue analysis
1.Is the FortinetFunction app worked any time in customer environment?
2.Is there any private n/w b/w the services?

Want to discuss in detail on this trying to reach over teams

**Comment by kausd1** [comment]
1.Is the FortinetFunction app worked any time in customer environment?
Never Worked

2.Is there any private n/w b/w the services?
No private network but can you expand on what exactly we mean by Private Network.
In the email forwarded using postman the api was able to make the call.

**Comment by v-muuppugund** [comment]
> > 1.Is the FortinetFunction app worked any time in customer environment? Never Worked
> > 2.Is there any private n/w b/w the services? No private network but can you expand on what exactly we mean by Private Network. In the email forwarded using postman the api was able to make the call.
> 
> Its in any virtual network communicating with on prem resources /services using PTS VPN/STS VPN/Express route or using azure private link i.e. https://azure.microsoft.com/en-in/products/private-link

Hi @kausd1 , Gentle Reminder: We are waiting for your response on this issue. Could you please let me know the details on the issue

**Comment by v-muuppugund** [comment]
Hi @kausd1 , As discussed over call, Code seems 5n and unable to replicate the issue, please let us know if we need to reinvestigate again the issue, you can reopen it any time.
