### ISSUE TITLE
Insider Risk_Sensitive Data Access Outside Organizational Geo-location analytic rule references obsolete table

### ISSUE THREAD

**Issue by Torch02** [Azure/Azure-Sentinel#9244]
**Describe the bug**
The analytic rule "Insider Risk_Sensitive Data Access Outside Organizational Geo-location" references the legacy InformationProtectionLogs_CL table instead of the new MicrosoftPurviewInformationProtection table.

File: https://github.com/Azure/Azure-Sentinel/blob/master/Solutions/MicrosoftPurviewInsiderRiskManagement/Analytic%20Rules/InsiderRiskSensitiveDataAccessOutsideOrgGeo.yaml

**To Reproduce**
1. Go to the Sentinel Content Hub
2. Install the Microsoft Purview Insider Risk Management content
3. Click on the "Insider Risk_Sensitive Data Access Outside Organizational Geo-location" analytic rule to create it (b81ed294-28cf-48c3-bac8-ac60dcef293b)
4. If this Sentinel instance hasn't ever ingested "Azure Information Protection" logs to the InformationProtectionLogs_CL table, the "Set rule logic" tab will fail to resolve multiplescalar expersions in the query and the validation will fail on the "Review + create" tab.

**Expected behavior**
I would expect this rule template (or a new rule template) to reference the MicrosoftPurviewInformationProtection table.

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
N/A

**Additional context**
Some of the corrections are easy. Replacing:
- "InformationProtectionLogs_CL" with "MicrosoftPurviewInformationProtection", and
- "LabelName_s" with "LabelName"

will fix those parts of the query. I'm not sure what the proper mapping of "Activity_s" is to in the new table schema.

**Comment by v-rbajaj** [comment]
Hi @Torch02, thanks for flagging this, we are looking into it and will get back to you by 26 Oct 2023

**Comment by v-muuppugund** [comment]
@Torch02 , I have done analysis and having below queries
1.Microsoft purview insider risk management data connector mainly on security alert and the analytic rule  i.e. InformationProtectionLogs_CL is referered the azure active directory also verified and its not part of it,so need to do further investigation on this,but we insider Risk_Sensitive Data Access Outside Organizational Geo-location?
2.https://learn.microsoft.com/en-us/azure/azure-monitor/reference/tables/microsoftpurviewinformationprotection
 But Microsoft pureview [Microsoft Purview](https://www.microsoft.com/security/business/microsoft-purview) offers a single pane of glass to view and manage your entire data estate from one place. As a unified solution, Microsoft Purview empowers you to easily create a holistic, up-to-date map of your data landscape with automated data discovery, sensitive data classification, and end-to-end data lineage,so my question we need to check  why we need to use that table instead need to use azure active directory table for locating geo location issues

Please find below screen shot Microsoft pureview protection
![image](https://github.com/Azure/Azure-Sentinel/assets/139563098/d7e01d18-d865-4e77-9a0c-0f7d274f1904)

Please find below screen shot of Microsoft pureview insider risk management and its used for other logs
![image](https://github.com/Azure/Azure-Sentinel/assets/139563098/9cb3cf5e-d61c-4c2d-a0cc-044d81633f52)

If needed, We can have a call to discuss further on this queries, please share your email id and convenient time

**Comment by v-muuppugund** [comment]
> @Torch02 , I have done analysis and having below queries 1.Microsoft purview insider risk management data connector mainly on security alert and the analytic rule i.e. InformationProtectionLogs_CL is referered the azure active directory also verified and its not part of it,so need to do further investigation on this,but we need insider Risk_Sensitive Data Access Outside Organizational Geo-location? 2.https://learn.microsoft.com/en-us/azure/azure-monitor/reference/tables/microsoftpurviewinformationprotection But Microsoft pureview [Microsoft Purview](https://www.microsoft.com/security/business/microsoft-purview) offers a single pane of glass to view and manage your entire data estate from one place. As a unified solution, Microsoft Purview empowers you to easily create a holistic, up-to-date map of your data landscape with automated data discovery, sensitive data classification, and end-to-end data lineage,so my question we need to check why we need to use that table instead need to use azure active directory table for locating geo location issues
> 
> Please find below screen shot Microsoft pureview protection ![image](https://user-images.githubusercontent.com/139563098/278982049-d7e01d18-d865-4e77-9a0c-0f7d274f1904.png)
> 
> Please find below screen shot of Microsoft pureview insider risk management and its used for other logs ![image](https://user-images.githubusercontent.com/139563098/278982893-9cb3cf5e-d61c-4c2d-a0cc-044d81633f52.png)
> 
> If needed, We can have a call to discuss further on this queries, please share your email id and convenient time

Hi @Torch02 , Gentle Reminder: We are waiting for your response on this issue. Could you please share the query details on the issue.

**Comment by Torch02** [comment]
I came across this bug as part of installing the Content package for Purview Insider Risk Management (which we are already using). This analytic rule is part of that package.

The description in the template states "Azure Information Protection Logs (InformationProtectionLogs_CL)". The Azure Information Protection connector no longer exists and thus the InformationProtectionLogs_CL table does not exist for any new Sentinel instances.

The details in the original post's "Additional context" covers 2 of the 3 replacements that need to happen. The 3rd is the replacement/mapping for the Activity_s column. I would guess the correct mapping is LabelAction, or maybe RuleActions, but it is not clear.

Since the "Azure Information Protection" connector has been deprecated, any details about the InformationProtectionLogs_CL table schema is unavailable.

These are all Microsoft 1st party tools & integrations, so I would expect MSFT to know how these new versions map.

**Comment by v-muuppugund** [comment]
> I came across this bug as part of installing the Content package for Purview Insider Risk Management (which we are already using). This analytic rule is part of that package.
> 
> The description in the template states "Azure Information Protection Logs (InformationProtectionLogs_CL)". The Azure Information Protection connector no longer exists and thus the InformationProtectionLogs_CL table does not exist for any new Sentinel instances.
> 
> The details in the original post's "Additional context" covers 2 of the 3 replacements that need to happen. The 3rd is the replacement/mapping for the Activity_s column. I would guess the correct mapping is LabelAction, or maybe RuleActions, but it is not clear.
> 
> Since the "Azure Information Protection" connector has been deprecated, any details about the InformationProtectionLogs_CL table schema is unavailable.
> 
> These are all Microsoft 1st party tools & integrations, so I would expect MSFT to know how these new versions map.

Sure, Will Cross verify the details mentioned above and get back to you

**Comment by v-muuppugund** [comment]
@Torch02 ,I have made changes in my branch i.e. https://github.com/Azure/Azure-Sentinel/tree/users/v-muuppugundu/AnalayticalRuleupdates unable to test it locally as don't have access, Could you please tell me convenient time and email id,so will schedule the meeting ,test it, once testing done, will raise the PR for analytic rule

**Comment by Torch02** [comment]
Sure, that version of the rule "compiles" just fine, but is the activity not important to the analytic?

**Comment by v-muuppugund** [comment]
> Sure, that version of the rule "compiles" just fine, but is the activity column not important to the analytic?

Hi @Torch02 ,Its also needed but still didn't figure out exact replacement,I don't have data to check ,so want to connect in call,so will find the replacement,Could you please tell me the convenient time

**Comment by v-muuppugund** [comment]
Hi @Torch02 ,Gentle reminder, Its also needed but still didn't figure out exact replacement, I don't have data to check, so want to connect in call, so will find the replacement, Could you please tell me the convenient time.

**Comment by Torch02** [comment]
I don't have access to an environment that has the InformationProtectionLogs_CL table populated

**Comment by v-muuppugund** [comment]
@Torch02 ,Need some environment for getting the exact mappings,so we can verify it and add the missing fields

**Comment by v-muuppugund** [comment]
@Torch02  Could you please update on the above request to check the details in environment,if needed,we can have teams meeting and troubleshoot this issue,Thanks.

**Comment by Torch02** [comment]
There is nothing for me to check in my environment. I do not have the legacy InformationProtectionLogs_CL table in my environment. 

I'm expecting Microsoft as the vendor of these solutions (previously Azure Information Protection, currently Microsoft Purview) to be able to translate their old data schema to their new data schema.

**Comment by v-muuppugund** [comment]
Hi @Torch02 ,I am working on internally for finding the data for the Activity_s column ,will get back to you with an update by 17Nov23

**Comment by v-muuppugund** [comment]
Hi @Torch02 ,I have tried to check the data in our log analytic work spaces, didn't find data,Could you please verify from your end any sample data that will use ful for identifying the column replacement.

**Comment by Torch02** [comment]
I do not have any logs in this table.

**Comment by v-muuppugund** [comment]
Hi @Torch02,Will check internally, how we can get this sample data and will update you, Thanks.

**Comment by v-muuppugund** [comment]
Hi @Torch02 ,Unable to find the data from our internal work spaces and sample data also don't have, checking internally for the data ,so we can map the pending Activity_s column with new table, will update you, Thanks

**Comment by v-muuppugund** [comment]
Hi @Torch02 , Still figuring out the column activity_s to new table as we don't have data for old table in workspaces, Thanks.

**Comment by v-sudkharat** [comment]
Hi @Torch02, could you please check below steps at your environment and let us know the result -

1st - Run below query at same LAW and check in table schema you are getting "Activity_s" or "Activity" column. 
```
MicrosoftPurviewInformationProtection
| getschema 
```

2nd. In schema "Activity_s" or "Activity" is not showing, could you please test below query and check whether you are got the expected result- 


```
MicrosoftPurviewInformationProtection
  | extend UserPrincipalName = UserId
  | where LabelName <> ""
  | join kind=inner (SigninLogs) on UserPrincipalName
  | extend City = tostring(LocationDetails.city)
  // | where City <> "New York" // Configure Location Details within Organizational Requirements
  | extend State = tostring(LocationDetails.state)
  // | where State <> "Texas" // Configure Location Details within Organizational Requirements
  | extend Country_Region = tostring(LocationDetails.countryOrRegion)
  // | where Country_Region <> "US" // Configure Location Details within Organizational Requirements
  // | lookup kind=inner _GetWatchlist('<Your Watchlist Name>') on $left.UserPrincipalName == $right.SearchKey
  | summarize count() by UserPrincipalName, LabelName, City, State, Country_Region, TimeGenerated
  | sort by count_ desc
  | extend AccountCustomEntity = UserPrincipalName
```
Based on  MicrosoftPurviewInformationProtection schema there is no   "Activity_s" column present - https://learn.microsoft.com/en-us/azure/azure-monitor/reference/tables/MicrosoftPurviewInformationProtection

Thanks!

**Comment by Torch02** [comment]
1. The MicrosoftPurviewInformationProtection schema does not have an activity column. That is the whole problem here., as identified when the issue was opened 7 weeks ago.
2. Yes, that query executes just fine, as stated a month ago. The original rule that relied on the InformationProtectionLogs_CL had the activity_s column important enough to be in the result set and a distinguishing part of the summary. Does Microsoft think that is no longer required/no longer important for the efficacy of this analytic rules?

**Comment by v-sudkharat** [comment]
Hi @Torch02, thank you for your response. After checking in the "`InformationProtectionLogs_CL`" table we don't see the `Activity_s` is mapped to any column with` MicrosoftPurviewInformationProtection`.  so, please remove the `Activity_s` from the query. 
Please refer below PR in which we have removed the `Activity_s` and done the other changes. 
PR- https://github.com/Azure/Azure-Sentinel/pull/9173/files#diff-19b4dd868aa5dddaf0f6eebbc374ff65ba43eeeb8613afdd4b18cb47fa049b49

Thanks!

**Comment by v-sudkharat** [comment]
Hi @Torch02, Gentle Reminder: We are waiting for your response on this issue- #9244. If you still need to keep this issue active, please respond to it in the next 2 days. If we don't receive a response by 13-12-2023 date, we will be closing this issue. 		
Thanks!

**Comment by Torch02** [comment]
I guess there's nothing left other than to note the product regression and press forward.

**Comment by v-sudkharat** [comment]
@Torch02, thanks for the response. 
so, closing this issue. If you still need support for this issue, feel free to re-open it any time. Thank you for your co-operation.
