### ISSUE TITLE
DOD Zero Trust Workbook

### ISSUE THREAD

**Issue by DeanGross** [Azure/Azure-Sentinel#9248]
**Describe the bug**
On the Data page, I selected 4.6 DLP and the Security incidents table shows events for multiple password reset by user which has nothing to do with Data Loss

**To Reproduce**
1. Go to 'DoD Zero Trust Strategy Workbook in Sentinel'
2. Click on 'Data Page'
3. Select '4.6 DLP'
4. Scroll down to example visual representation section

**Expected behavior**
Security incidents to be associated with data loss should be shown

**Screenshots**
<img width="498" alt="image" src="https://github.com/Azure/Azure-Sentinel/assets/4058555/48ebcc79-4cc1-42a3-8825-2718617f9c70">

**Comment by v-rbajaj** [comment]
Hi @DeanGross, thanks for flagging this issue, we will get back to you by 27 Oct 2023

**Comment by v-muuppugund** [comment]
@DeanGross noticed the user is trying to reset the password at multiple instances,so as per zero trust proactive security incident has been rasied,Could you please let me know if you have any further queries on this.

**Comment by v-muuppugund** [comment]
Hi @DeanGross ,Since we have not received a response in the last 5 days, we are closing your issue (https://github.com/Azure/Azure-Sentinel/issues/9248) as per our standard operating procedures. If you still need support for 	this issue, feel free to re-open at any time. Thank you for your co-operation.

**Comment by DeanGross** [comment]
sorry, i missed this, but I think you misunderstood my comment. This type of security incident should not be in the DLP category, since it has nothing to do with data loss

**Comment by v-muuppugund** [comment]
> sorry, i missed this, but I think you misunderstood my comment. This type of security incident should not be in the DLP category, since it has nothing to do with data loss

Hi @DeanGross ,Got you,will analyse and update on this issue by 10Nov23

**Comment by v-muuppugund** [comment]
Hi @DeanGross ,I have done analysis and raised the PR(https://github.com/Azure/Azure-Sentinel/pull/9368) for it but need your help in testing it,Will share the json file , Please follow the below steps and confirm the issue
1.Go to work space and click on ADD work book
![image](https://github.com/Azure/Azure-Sentinel/assets/139563098/185f9910-6022-42e8-9103-6ea35ccce74e)
2.Click on Edit
![image](https://github.com/Azure/Azure-Sentinel/assets/139563098/30f526be-9d9a-4597-b43d-66de5bc45981)
3.Click on Advance Editor
![image](https://github.com/Azure/Azure-Sentinel/assets/139563098/5bd381a7-8ba2-4104-8e0f-b560b0be649f)
4.Download the attachment and copy the json,then click apply
![image](https://github.com/Azure/Azure-Sentinel/assets/139563098/9706b304-6b4f-4c56-b89f-55b9cbf33d95)
5.Click on Apply
![image](https://github.com/Azure/Azure-Sentinel/assets/139563098/5c4e9ba1-74bc-4e29-a3f0-4a94bcce3f0a)
6.Click on Data and 4.6 DLP 
![image](https://github.com/Azure/Azure-Sentinel/assets/139563098/c66f1f09-ae83-4189-ab36-ac81e98ff2a0)

Please check incidents are displaying under Password Reset Category

**Comment by v-muuppugund** [comment]
Hi @DeanGross ,Could you please provide an update on above steps performed for the issue resolution.

**Comment by v-muuppugund** [comment]
Hi @DeanGross , Gentle Reminder: We are waiting for your response on this issue. If you still need to keep this issue active, please respond to it in the next 2 days i.e. 23Nov23. If we don't receive response by the given date, we will close this issue.

**Comment by v-muuppugund** [comment]
Hi @DeanGross ,Since we have not received a response in the last 5 days, we are closing your issue (https://github.com/Azure/Azure-Sentinel/issues/9248) as per our standard operating procedures. If you still need support for 	this issue, feel free to re-open at any time. Thank you for your co-operation!
