### ISSUE TITLE
Microsoft Sentinel Solution for Dynamics 365 CE Apps (Preview) - D365 - New Office user agent detected - template error

### ISSUE THREAD

**Issue by Kaloszer** [Azure/Azure-Sentinel#9249]
**Describe the bug**
Cannot create an Analytic Rule from template

![image](https://github.com/Azure/Azure-Sentinel/assets/62133917/00312c74-ee24-436a-bbfe-a584203b0853)

**To Reproduce**
1. Install https://azuremarketplace.microsoft.com/en-us/marketplace/apps/sentinel4dynamics365.sentinel4dynamics365?tab=Overview
2. Sentinel Workspace > Analytic > Rule Templates > select 'D365 - New Office user agent detected'
3. Create rule

**Expected behavior**
Can create analytic rule from template

**Additional context**
Tried on dev subscription with no connector attached and in prod with Dynamics 365 connector attached, same result. Rule template id seems not to be available within github - I think it's `094b3c0a-1f63-42f7-9535-c8c7b7198328`

**Comment by v-muuppugund** [comment]
Hi @Kaloszer , Thanks for flagging this issue, we will investigate this issue and get back to you with some updates by 27Oct23. Thanks!

**Comment by v-muuppugund** [comment]
Hi @Kaloszer ,After analysis,able to replicate the same issue  working on investigating cause of the issue by 03Nov23

**Comment by v-muuppugund** [comment]
Hi @Kaloszer , we are reaching out to the concerned team for this issue, once we receive 	an update on this, we will update you by 07Nov23. Thanks!

**Comment by v-muuppugund** [comment]
Hi @Kaloszer ,Our team has fixed the issue and waiting for deployment formalities to be completed. we will update you by 10Nov23. Thanks!

**Comment by v-muuppugund** [comment]
Hi @Kaloszer ,Our team has fixed the issue and waiting for deployment formalities to be completed. we will update you 14Nov2023. Thanks!

**Comment by v-muuppugund** [comment]
Hi @Kaloszer ,Our team has fixed the issue and waiting for deployment formalities to be completed. we will update you by 17Nov2023. Thanks!

**Comment by v-muuppugund** [comment]
Hi @Kaloszer,We are still waiting for deployment formalities to be completed, will update you once done.

**Comment by v-sudkharat** [comment]
Hi @Kaloszer, the deployment has been done. we reproduce this issue and now able to create the analytic rule. 

Sharing screenshot reference -   
![image](https://github.com/Azure/Azure-Sentinel/assets/132428394/9e3f4563-11f5-46a2-aee3-846f70462ea8)

![image](https://github.com/Azure/Azure-Sentinel/assets/132428394/2cafb7c4-7f00-4a10-b39c-b9a10801ab6b)

Please Update the solution if you are using previous versions. 
As of now, we are closing this issue. If you still need support for this issue, feel free to re-open it any time. Thank you for your co-operation.
