### ISSUE TITLE
Automation rule REST API endpoint no longer returns all Automation Rules on GET list action

### ISSUE THREAD

**Issue by Kaloszer** [Azure/Azure-Sentinel#9252]
**Describe the bug**

Portal:
![image](https://github.com/Azure/Azure-Sentinel/assets/62133917/2cb02162-17ab-4bd6-86ea-de478d986f69)

Rest API return count:
![image](https://github.com/Azure/Azure-Sentinel/assets/62133917/a25c0bb6-d72c-4104-8a9f-26b2c391d13a)

**To Reproduce**

1. Have in excess of 50 automation rules on a workspace
2. Execute REST API call against REST API endpoint
3. End up short on the amount of Automation Rules
4. REST API endpoint does not return nextLink/ or anything that would imply another page is ready to be parsed.

``` pwsh
$SubscriptionId = 'subid'
$ResourceGroupName = 'rg'
$WorkspaceName = 'wk'
$apiVersion = '2023-09-01-preview'

    $headers = New-Object "System.Collections.Generic.Dictionary[[String],[String]]"
    $headers.Add("Authorization", "Bearer $((Get-AzAccessToken).token)")
    $headers.Add("Content-Type", "application/json")
    try
    {
        $uri = "https://management.azure.com/subscriptions/$($SubscriptionId)/resourceGroups/$($ResourceGroupName)/providers/Microsoft.OperationalInsights/workspaces/$($WorkspaceName)/providers/Microsoft.SecurityInsights/automationRules?api-version=$($apiVersion)"
        Write-Verbose -Verbose $uri
        $automationRules = Invoke-RestMethod $uri -Method 'GET' -Headers $headers
    }
    catch
    {
        throw $_
    }

```

**Expected behavior**
All Automation Rules are returned

**Additional context**

Tried various API versions, same result:
- 2021-09-01-preview
- 2023-09-01-preview
- 2023-02-01 (returns 46)

This has been ongoing since about the beggining of the month, hard to pinpoint the moment, but we have noticed that as we depend on this endpoint for current environment state - and by not returning all entries we found that we re-deploy some automation rules that are not listed within that endpoint - this is causing issues on production.

**Comment by v-muuppugund** [comment]
Hi @Kaloszer , Thanks for flagging this issue, we will investigate this issue and get back to you with some updates by 27Oct23. Thanks!

**Comment by Kaloszer** [comment]
I have also now limited the Automation Rules under 50 (down to 47) and I still get less than the amount of Automation Rules (40)

**Comment by v-muuppugund** [comment]
Hi @Kaloszer ,we will analyze and get back you about the above query

**Comment by v-muuppugund** [comment]
Hi @Kaloszer ,Could you please confirm automation rules api is working on the remaining  below scenarios,so need to replicate the same scenario checking on it and will get back to you by 03Nov23
1.<50 automation rules

Could you please give more details on the below query in detail
b) Or when Automation Rules have >2 occurence of the same order (all Automation rules that had 3 orders of the same count would not show up in the results, was similar only for 'some' of those that had 2 orders of the same count)

**Comment by Kaloszer** [comment]
Hey @v-muuppugund, unfortunately I'm unable to replicate this behaviour on dev.

1) I don't have 50 Automation rules to deploy atm on dev
2) I couldn't replicate this behaviour whilst having 10 automation rules with 3 order 1 and 2 order 2s'

So I'm still not sure what might've caused the aforementioned behaviour on the other environment :(

By order I mean this field in automation rules:

![image](https://github.com/Azure/Azure-Sentinel/assets/62133917/4f702d0a-36f2-4fcc-808f-db1318b8192c)

![image](https://github.com/Azure/Azure-Sentinel/assets/62133917/89b86f76-0887-411a-9726-419c9a94e171)

**Comment by v-muuppugund** [comment]
> Hey @v-muuppugund, unfortunately I'm unable to replicate this behaviour on dev.
> 
> 1. I don't have 50 Automation rules to deploy atm on dev
> 2. I couldn't replicate this behaviour whilst having 10 automation rules with 3 order 1 and 2 order 2s'
> 
> So I'm still not sure what might've caused the aforementioned behaviour on the other environment :(
> 
> By order I mean this field in automation rules:
> 
> ![image](https://user-images.githubusercontent.com/62133917/278966935-4f702d0a-36f2-4fcc-808f-db1318b8192c.png)
> 
> ![image](https://user-images.githubusercontent.com/62133917/278967106-89b86f76-0887-411a-9726-419c9a94e171.png)

Hi @Kaloszer ,As unable to replicate the issue, Please let us know if any information required on this issue

**Comment by v-muuppugund** [comment]
Hi @Kaloszer ,Since we have not received a response in the last 5 days, we are closing your issue (https://github.com/Azure/Azure-Sentinel/issues/9252) as per our standard operating procedures. If you still need support for this issue, feel free to re-open at any time. Thank you for your co-operation.
