### ISSUE TITLE
Mimecast API integration is creating new log analytic workspace..

### ISSUE THREAD

**Issue by AkshayPadekar** [Azure/Azure-Sentinel#9256]
Hi,

I have tried Azure deploy function app code for Mimecast SEG and Microsoft sentinel integration. I have an existing sentinel in my tenant where i want to deploy Mimecast SEG Data connector through the function app. During this process, I tried to deploy azuredeploy_MimecastSEG_AzureFunctionApp.json through custom deployment but it is creating a new log analytic workspace in my tenant. I tried to put my existing workspace key and ID code, but it is not accepting it. can you please guide me on how can i deploy this connector in my existing Log analytic workspace?

**Comment by v-muuppugund** [comment]
Hi @AkshayPadekar , Thanks for flagging this issue, we will investigate this issue and get back 	to you with some updates by 27Oct23. Thanks!

**Comment by v-muuppugund** [comment]
Hi @AkshayPadekar ,I tried to deploy mimecast seg api through custom deployment  https://github.com/Azure/Azure-Sentinel/blob/master/Solutions/MimecastSEG/Data%20Connectors/azuredeploy_MimecastSEG_AzureFunctionApp.json,please find below screen shot for reference
![image](https://github.com/Azure/Azure-Sentinel/assets/139563098/ad9fe23c-2643-49dd-a3ac-172ebf49d453)

we are using key vault parameters for log analytics work space key and id,please find below screen shot for reference
![image](https://github.com/Azure/Azure-Sentinel/assets/139563098/dcbc07f7-ff83-48e3-8839-b477c8593649)


Please try to redeploy using the same template and let me know if any issues

**Comment by AkshayPadekar** [comment]
Yes, you are right. In the code, we can see it is taking the value from the Key vault but while deploying through custom deployment we are getting options to fill the required details as you have shared in a snap but not asking for the workspace details. and if I create a new key vault and save these details there while deploying it again creates a new key vault.

Could you please guide me on how can I use my existing workspace key and ID while deploying it using a custom template?

**Comment by v-muuppugund** [comment]
@AkshayPadekar  The following are the two options for achieving it

1. Use existing key vault updating the existing secrets in key vault with log-analytics-workspace-id,log-analytics-workspace-key values,then restart function app
2. Change the ARM template input parameters for collecting log analytic work space id and key

Please let me know if have any questions on it

**Comment by v-sudkharat** [comment]
Hi @AkshayPadekar, hope you are doing well. Could you please have a look at above comment? and share response with us. Thanks!

**Comment by v-muuppugund** [comment]
Hi @AkshayPadekar , Since we have not received a response in the last 5 days, we are closing your issue (https://github.com/Azure/Azure-Sentinel/issues/9256) as per our standard operating procedures. If you still need support for this issue, feel free to re-open at any time. Thank you for your co-operation!
