### ISSUE TITLE
OktaSSO function app deployment failure since new repo update

### ISSUE THREAD

**Issue by philfy20** [Azure/Azure-Sentinel#9264]
**Describe the bug**
Since the new update 2 weeks ago to the repo it seems to have to broke the function app. While the function app deploys it does not deploy the actual function code to polls the API and push the data to Sentinel.

Issue is URL link to package goes points to a broken URL

 {
              "name": "WEBSITE_RUN_FROM_PACKAGE",
              "value": "https://aka.ms/sentineloktaazurefunctioncodev2-solution"
            }

**To Reproduce**
1. Deploy Okta Solution to Sentinel
2. Go to Sentinel / Data connectors and then the okta data connector
3. deploy the function app attached to the okta data connector.
4. Go to function app and under functions you will see no functions are deployed

**Expected behavior**
Function app is deployed with functions.

**Additional context**

**Comment by sgregorioTC** [comment]
Also experiencing this issue. Broke our Okta Logging.... 

Looks like the aka.ms short url needs to be updated to point to the new location

**Comment by biers04** [comment]
++ This has broken our Okta logging

**Comment by biers04** [comment]
aka ms should point to
https://github.com/Azure/Azure-Sentinel/blob/master/Solutions/Okta%20Single%20Sign-On/Data%20Connectors/OktaSingleSign-On/AzureFunctionOktaSSO_V2/AzureFunctionOktaSSO.zip?raw=true

currently points to (spaces in Okta Single Sign-On)

https://github.com/Azure/Azure-Sentinel/blob/master/Solutions/Okta%20Single%20Sign-On/Data%20Connectors/Okta%20Single%20Sign-On/AzureFunctionOktaSSO_V2/AzureFunctionOktaSSO.zip?raw=true

**Comment by philfy20** [comment]
Further update as a hotfix I am manually updating the deployment code to the correct URL which seems to fix it. However hoping someone can do a proper fix with a code update.

Also if the function app was already deployed before the bug you can update application settings and the URI value to the correct URL and do a restart which also fixes it

**Comment by v-muuppugund** [comment]
@philfy20 ,Will work on the above issues analysis ,will get back to you on 01Nov23

**Comment by v-muuppugund** [comment]
@philfy20 We have analysed the master path i.e. https://github.com/Azure/Azure-Sentinel/raw/master/Solutions/Okta%20Single%20Sign-On/Data%20Connectors/OktaSingleSign-On/AzureFunctionOktaSSO_V2/AzureFunctionOktaSSO.zip

Short link path: https://github.com/Azure/Azure-Sentinel/blob/master/Solutions/Okta%20Single%20Sign-On/Data%20Connectors/OktaSingleSign-On/AzureFunctionOktaSSO_V2/AzureFunctionOktaSSO.zip?raw=true

Both are same,Please verify and let us know if any issue

**Comment by philfy20** [comment]
the short link which was flagged "https://aka.ms/sentineloktaazurefunctioncodev2-solution" is now resolving to the correct URL. Previously "https://aka.ms/sentineloktaazurefunctioncodev2-solution" would point to a URL that did not exist. As this is now resolved this can be closed. thanks
