### ISSUE TITLE
Sentinel Symantec Endpoint Protection data connector - Paser not working. 

### ISSUE THREAD

**Issue by v-miketang** [Azure/Azure-Sentinel#9271]
**Describe the bug**
Reference: https://github.com/Azure/Azure-Sentinel/issues/8769

**To Reproduce**
After updating the parser, the customer reported that results are not parsing any column of the Syslog.

https://github.com/Azure/Azure-Sentinel/commit/e38b6d16bd96c0f023a0369974ead0f6ec2e176e

**Comment by v-rbajaj** [comment]
Hi @v-miketang, thanks for flagging this issue. We will get back to you by 31 Oct 2023.

**Comment by v-rbajaj** [comment]
Hi @v-miketang, sorry for the delay, we will get back to you by 03 Nov 2023.

**Comment by v-rbajaj** [comment]
Hi @v-miketang, we have a mail communication on going for this issue. Analysis have been shared there. Waiting for your confirmation with customer.

**Comment by v-rbajaj** [comment]
We had a call with the customer on this issue. Although the provided issue has been fixed we need to rewrite the entire syslog message.

**Comment by v-muuppugund** [comment]
We are waiting for a call with customer for troubleshooting the issue

**Comment by v-muuppugund** [comment]
We are still waiting for a call with customer for troubleshooting the issue

**Comment by v-rbajaj** [comment]
Hi @v-miketang, since we have provided you the updated parser and since it working now. I am closing this issue. 

We will push the changes to master soon.
