### ISSUE TITLE
Solutions/Watchlists Utilities/Playbooks/Watchlist-ChangeIncidentSeverityandTitleIFUserVIP is not working as intended

### ISSUE THREAD

**Issue by tohov** [Azure/Azure-Sentinel#9274]
**Describe the bug**
Playbook (Watchlist-ChangeIncidentSeverityandTitleIFUserVIP) in "Watchlists Utilities" does not work as intended. I've tested this playbook with automation rule that triggers from an analytics rule "Guest accounts added in AAD Groups other than the ones specified", but I'm quite sure any analytics rule will suffice.

What happens is that if my account is used to add guest user to a non-allowed AAD group (allowed groups are set in the watchlist), it will raise an incident. Great! In that incident there are two account entities: mine (as the actor of the operation) and the guest user's account (as the target of the operation). Once I will trigger an automation rule that has this playbook it successfully executes.

The erroneous behaviour happens because my account has been used to create the VIP User watchlist. This means that in the body of the watchlist JSON there is not only VIP users but also my account name in the `properties.createdBy` and `properties.updatedBy`. As the playbook operates the for each loop it first suffixes the target account correctly to the incident title but will overwrite the correct title addition with my account name in the next for each loop. This is mistake as I'm not a VIP user in the watchlist.

As a side note, also the Sentinel actions after the condition evaluation should be updated to newer actions (mainly 'Update incident' action)

**To Reproduce**
1. Create an AAD group "Guest users" and copy object id. Create another groups "Members only".
2. Create an watchlist with schema that includes AAD group object id and display name. Make object id SearchKey. Make alias as "AAD-Guest-User-Groups"
3. Add the "Guest users" AAD group object id and display name to the newly created watchlist.
4. Install Azure Active Directory solution that has the "Guest accounts added in AAD Groups other than the ones specified" analytics rule
5. Edit the rule to get the AAD group object IDs from watchlist instead of hardcoded values in query (only the first row of query is changed a bit)
```
// OBJECT ID of AAD Groups can be found by navigating to Azure Active Directory then from menu on the left, select Groups and from the list shown of AAD Groups, the Second Column shows the ObjectID of each
let GroupIDs = _GetWatchlist('AAD-Guest-User-Groups');
AuditLogs
| where OperationName in ('Add member to group', 'Add owner to group')
| extend InitiatedByActionUserInformation = iff(isnotempty(InitiatedBy.user.userPrincipalName), InitiatedBy.user.userPrincipalName, InitiatedBy.app.displayName)
| extend InitiatedByIPAdress = InitiatedBy.user.ipAddress 
// Uncomment the following line to filter events where the inviting user was a guest user
//| where InitiatedBy has_any ("CUSTOM DOMAIN NAME#", "#EXT#")
| mv-apply TargetResource = TargetResources on 
  (
      where TargetResource.type =~ "User"
      | extend InvitedUser = trim(@'"',tostring(TargetResource.userPrincipalName)),
               Properties = TargetResource.modifiedProperties
  )
| mv-apply Property = Properties on 
  (
      where Property.displayName =~ "Group.DisplayName"
      | extend AADGroup = trim('"',tostring(Property.newValue))
  )
| where InvitedUser has_any ("CUSTOM DOMAIN NAME#", "#EXT#")
| mv-apply Property = Properties on
   (
     where Property.displayName =~ "Group.ObjectID"
     | extend AADGroupId = trim('"',tostring(Property.newValue))
   )
| where AADGroupId !in (GroupIDs)
| extend Name = tostring(split(InitiatedByActionUserInformation,'@',0)[0]), UPNSuffix = tostring(split(InitiatedByActionUserInformation,'@',1)[0])
```
6. Save the rule
7. Create an automation rule that will trigger from incident creation and only from this analytics rule
8. Add the playbook in question into the automation rule as an action and save the automation rule
9. Invite a guest user and add guest as member to "Members only" group. Use same account that was used to create the watchlist.
10. Wait for activity log to appear and analytics rule to run and automation rule to trigger and eventually run the playbook
11. You should have an incident that has severity 'High' and which has either your account name suffixed instead of the target user (may depend of the for each loop order)

**Expected behavior**
I expect the playbook workflow to properly parse the watchlist JSON and only compare incident account entities in for each loop against watchlist `body.properties.watchListItems.properties.itemsKeyValue` which contains "User Principal Name" value that can be used to check with Account Name using 'contains'. Checking against the whole watchlist body will result in unwanted situation.

**Screenshots**
Condition evaluation inside the for each loop returns 'true' for both accounts even if the other account is not a VIP user.
<img width="602" alt="image" src="https://github.com/Azure/Azure-Sentinel/assets/38506856/96d7b685-21d6-4880-acf7-5ca14e3dc0c1">

**Comment by v-muuppugund** [comment]
Hi @tohov , we are reaching out to the concerned team for this issue, once we receive an update on this, we will update you by 02Nov23. Thanks!

**Comment by tohov** [comment]
Hello @v-muuppugund I'd like to add that the Sentinel Actions like 'Change incident severity' and 'Change incident title (V2)' should also be updated to match the current 'Update incident (preview)'

**Comment by tohov** [comment]
Here's a picture of the watchlist body json. It does contain other user principal name information (red arrows) other then the VIP users (green arrow) which is why this error has been able to manifest itself.

![image](https://github.com/Azure/Azure-Sentinel/assets/38506856/f11af3ea-ed94-4016-8542-7d7e6f2c7c19)

**Comment by v-muuppugund** [comment]
> Here's a picture of the watchlist body json. It does contain other user principal name information (red arrows) other then the VIP users (green arrow) which is why this error has been able to manifest itself. Hence searching UPNs from json body is not enough.
> 
> ![image](https://user-images.githubusercontent.com/38506856/279063311-f11af3ea-ed94-4016-8542-7d7e6f2c7c19.png)

Hi @tohov ,Thanks for your above queries, will do analysis and get back to you by 02Nov23

**Comment by v-muuppugund** [comment]
Hi @tohov ,I am unable to replicate the above issue,Could you please share your email and convenient time for discussing the issue in detail

**Comment by v-sudkharat** [comment]
Hi @tohov, Hope you are doing well. Could you please take a look at the above comment? and share details with us. Thanks!

**Comment by v-muuppugund** [comment]
Hi @tohov , Gentle Reminder: We are waiting for your response on this issue. If you 	still need to keep this issue active, please respond to it in the next 2 days. If we don't 		receive response by the given date i.e. 10Nov23, we will close this issue.

**Comment by tohov** [comment]
@v-muuppugund Hi I will check your comments and get back to you tomorrow on Eastern European office time.

**Comment by tohov** [comment]
@v-muuppugund 👉🏼 tommi.hovi@cloud2.fi

**Comment by v-muuppugund** [comment]
Hi @tohov ,Could you please share convenient time for teams meeting for further trouble shooting the issue.

**Comment by v-muuppugund** [comment]
Hi @tohov ,Could you please share convenient time for teams meeting for further trouble shooting the issue.

**Comment by tohov** [comment]
@v-muuppugund
Mon 20th 9.00-12.00 EET
Tue 21st 10.30-13.00 EET
Wed 22nd 9.30-14.00 EET

**Comment by v-muuppugund** [comment]
Hi @tohov ,Thanks for sharing time slot,will schedule the meeting during the time slots,Thanks

**Comment by v-muuppugund** [comment]
Hi @tohov ,Thanks for joining the call today,will be working on logical changes and get back to you with an update.

**Comment by v-muuppugund** [comment]
Hi @tohov ,Apologies for the delayed response, Will be scheduling this meeting for the changes, please let me know if this time is not convenient.

**Comment by v-muuppugund** [comment]
Hi @tohov ,As discussed, scheduled call with customer for issue troubleshooting on 09/01/2024

**Comment by v-muuppugund** [comment]
Hi @tohov ,As discussed on 09/01/24 , have fixed few logic app issues and Scheduled call for today i.e. 12/01/24 as per your availability but unable to make this call for further troubleshooting, please let me know ,when we can schedule this call.

**Comment by v-muuppugund** [comment]
Hi @tohov ,Gentle reminder,Please let me know when we can connect on this issue troubleshooting,Thanks.

**Comment by v-muuppugund** [comment]
Hi @tohov ,Since we have not received a response in the last 5 days, we are closing your issue (https://github.com/Azure/Azure-Sentinel/issues/9274) as per our standard operating procedures. If you still need support for 	this issue, feel free to re-open at any time. Thank you for your co-operation

**Comment by v-muuppugund** [comment]
Hi @tohov , As discussed over teams meeting the issue has been resolved after code changes done over to logic app for this scenario based issue,will be Rasing PR for this fix,will update you.

**Comment by v-sudkharat** [comment]
Hey @tohov, The raised PR has been merged into master. Thanks!
