### ISSUE TITLE
Github Desktop link broken in README

### ISSUE THREAD

**Issue by niranjan-kurhade** [Azure/Azure-Sentinel#9307]
**Describe the bug**
The GitHub Desktop link in README.md is broken.

**To Reproduce**
1. Go to README.md
2. Scroll down to General Steps https://github.com/Azure/Azure-Sentinel#general-steps
3. Click on GitHub Desktop

**Expected behavior**
It should redirect to the correct link.

**Screenshots**
![image](https://github.com/Azure/Azure-Sentinel/assets/97905637/6ab9224f-8045-4ede-9253-d1faef7dbaab)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by v-sudkharat** [comment]
Hi @niranjan-kurhade, Thanks for flagging this issue and we appreciate your willingness to contribute. Unfortunately, we cannot add you as assignees.  
We investigated this issue, and we will fix it by 02-11-2023. 
Thanks!

**Comment by niranjan-kurhade** [comment]
> Hi @niranjan-kurhade, Thanks for flagging this issue and we appreciate your willingness to contribute. Unfortunately, we cannot add you as assignees.  
> We investigated this issue, and we will fix it by 02-11-2023. 
> Thanks!

Okay

**Comment by v-sudkharat** [comment]
Hi @niranjan-kurhade, Our PR has been raised, and changes will take effect after it is merged.  Thanks!
