### ISSUE TITLE
AAD Data Connector Not Showing

### ISSUE THREAD

**Issue by jacktarian** [Azure/Azure-Sentinel#9312]
As per https://github.com/Azure/Azure-Sentinel/blob/master/Solutions/Azure%20Active%20Directory/ReleaseNotes.md it looks like the Data Connector was added back in. 

However, I can only see version 3.0.5 within the content hub across multiple sentinel instances which does not include the Data Connector for Azure AD which in turn does not allow new sentinel deployments to connect to Azure AD.

Can this be advised

**Comment by KostaS10** [comment]
Confirming I also don't see the connector in the solution even though the description says there is one

**Comment by jacktarian** [comment]
Thanks Kosta - just re-checked and seems there was an update in the content hub available for AAD to 3.0.6 which now shows the connector and is showing in Data Connectors under Entra ID now.

**Comment by v-sudkharat** [comment]
Hi @jacktarian, Thanks for reporting the issue. We have updated the solution with new version of - 3.0.6.  You can update the solution for reflect the new changes. 
![image](https://github.com/Azure/Azure-Sentinel/assets/132428394/168b9580-5828-49a6-8757-3ebf9e88d9db)

Closing this issue as of now. If you still need support for this issue, feel free to re-open it any time. Thank you for your co-operation.
