### ISSUE TITLE
Documentation update for Sentinel Palo Alto Data Connector 

### ISSUE THREAD

**Issue by chris-bristow-maersk** [Azure/Azure-Sentinel#9337]
Hi 
Is it possible to update this page https://github.com/Azure/Azure-Sentinel/tree/master/Solutions/PaloAlto-PAN-OS/Data%20Connectors
to include more details.

I don't think its clear enough how the PA firewalls are configured to correctly send CEF events, the last line just talks about 7 CEF fields, but the guidelines could be clearer.

For example I found this page which shows exactly the format required for the events to be sent in the proper format:
https://www.ibm.com/docs/no/dsm?topic=panps-configuring-palo-alto-networks-firewall-send-arcsight-cef-formatted-syslog-events

thanks

**Comment by v-sudkharat** [comment]
Hi @chris-bristow-maersk, Thanks for flagging this issue, we will investigate this issue and get back to you with some updates by 07-11-2023. Thanks!

**Comment by v-sudkharat** [comment]
Hi @chris-bristow-maersk, hope you are doing well. In the data connector page, you will get the CEF configuration link which redirects to the `Common Event Format (CEF) Configuration Guides`, and it have the detailed information about configuration. please download the document from official PA documentation site.  
![image](https://github.com/Azure/Azure-Sentinel/assets/132428394/aabbd1c4-f37e-4866-b7f5-682cd3f1ec70)

Hope we have answered your questions. Thanks!
