### ISSUE TITLE
Azure-Sentinel/Solutions/SquidProxy/Parsers /SquidProxy.txt parser issue`

### ISSUE THREAD

**Issue by nmohammed94** [Azure/Azure-Sentinel#9347]
**Describe the bug**
The parser doesn't work unless you specify the parsing kind. As below on line 26:
| parse **kind=regex** RawData with * " " EpochTimeExtended " " Duration " " SrcIpAddr " " ResultStatusCode " " Bytes " " HttpRequestMethod " " Url " " Username " " PeerStatusHost " " ContentType

**Comment by v-sudkharat** [comment]
Hi @nmohammed94, Thanks for flagging this issue, we will investigate this issue and get back to you with some updates by 10-11-2023 . Thanks!

**Comment by v-sudkharat** [comment]
Hi @nmohammed94, we have tested the parser in below scenarios: 

1. Without using the `kind=regex` in parser query - The parser works successfully without any failure. 
![image](https://github.com/Azure/Azure-Sentinel/assets/132428394/a7902377-b0af-4689-869c-2ac5e8742455)

2. Using `kind=regex` in parser query 
![image](https://github.com/Azure/Azure-Sentinel/assets/132428394/52857225-efd8-4f07-ab4e-77a4b85eb078)

In above both the scenarios the Parser works successfully without any failures and with the same results. 

if you use the parse command without specifying the kind parameter, which defaults to Relaxed and it is simple and fast in non-complex data.  
In other hand, if your input string is too complex and not handled by the Relaxed then the `kind=regex` is useful, but it is slower. 

below is the screenshot of both query execution time - 
For 1st one - 
![image](https://github.com/Azure/Azure-Sentinel/assets/132428394/24b016bd-33f2-4d13-a6e7-b0a981035ef9)

for 2nd one - 
![image](https://github.com/Azure/Azure-Sentinel/assets/132428394/d9e12ecb-0e8d-4583-ae90-e8c758ec3467)

Hope this helps you. Thanks!

**Comment by nmohammed94** [comment]
@v-sudkharat, thank you for looking into this. 

I have been testing this with one of my customers, and without specifying the kind as regex, the parsing would always fail. I am not sure what was happening there. Thank you anyway for looking into this.
