### ISSUE TITLE
GitHub repository On Boarding - Azure sentinel

### ISSUE THREAD

**Issue by Milanthumar** [Azure/Azure-Sentinel#937]
I have followed steps and deployed template in azure with correct inputs. After deploying at step 7 i was getting error to save keyvault-GitHubPlaybooks.
https://techcommunity.microsoft.com/t5/azure-sentinel/protecting-your-github-assets-with-azure-sentinel/ba-p/1457721

I tried exactly all commands but getting below error in keyvault playbook, can you please suggest how to correct it:

Error: Failed to edit API connection.
Failed to edit API connection 'keyvault-GitHubPlaybooks'.

**To Reproduce**
Steps to reproduce the behavior: Steps are given in URL.

**Expected behavior**

**Screenshots**

![1](https://user-images.githubusercontent.com/68587784/89279510-bff8d800-d647-11ea-93ff-442368ceb2e7.JPG)
![2](https://user-images.githubusercontent.com/68587784/89279513-c0916e80-d647-11ea-8a68-f53525ee0a76.JPG)
![3](https://user-images.githubusercontent.com/68587784/89279516-c12a0500-d647-11ea-8b4d-1cd45b508b60.JPG)

**Comment by dicolanl** [comment]
Just tested.  Got the same error.  Looks like something is missing from the arm template that specifies tenant and keyvault name. 

Here is the workaround.
Deploy per the blog.
Edit API Connection for Keyvault, click signin.
![image](https://user-images.githubusercontent.com/25964057/89301875-fec66800-d61e-11ea-92ab-2d02c016f88c.png)

Click Save. this will fail but the sign in worked.
![image](https://user-images.githubusercontent.com/25964057/89301937-10a80b00-d61f-11ea-8d0f-6ae16ae59268.png)

go to either plabook.  you can see the orange triangle indicator.
![image](https://user-images.githubusercontent.com/25964057/89301976-1aca0980-d61f-11ea-8d72-6091f49a3b31.png)

Click that step.  click the ! under invalid column header.
![image](https://user-images.githubusercontent.com/25964057/89302026-30d7ca00-d61f-11ea-82fe-847ca693207f.png)

Select your tenant and enter the keyvault name, click sign in
![image](https://user-images.githubusercontent.com/25964057/89302055-3cc38c00-d61f-11ea-8aef-f399a387297e.png)

it should enumerate personalaccesstoken key name.
![image](https://user-images.githubusercontent.com/25964057/89302126-51078900-d61f-11ea-9858-1da1f4b78c43.png)


playbook will run fine now.

I will investigate how to add these properties to the arm template.
