### ISSUE TITLE
Query Style Guide wiki needs to be updated to include character limit of 255 in description

### ISSUE THREAD

**Issue by jischell-msft** [Azure/Azure-Sentinel#9385]
@v-atulyadav 
- The Query Style Guide (https://github.com/Azure/Azure-Sentinel/wiki/Query-Style-Guide#description) description section does not reference the 255 character limit either.

_Originally posted by @jischell-msft in https://github.com/Azure/Azure-Sentinel/issues/9323#issuecomment-1799254777_

**Comment by v-sudkharat** [comment]
Hi @jischell-msft, Thanks for flagging this issue, we will investigate this issue and get back to you with some updates by 17/11/2023.  Thanks!

**Comment by v-sudkharat** [comment]
Hi @jischell-msft, we are working on updating the "Query Style" Guide, and we will raise the PR once the document update is done. Thanks!

**Comment by jischell-msft** [comment]
@v-sudkharat where is this branch/ work being perfomed?

**Comment by v-sudkharat** [comment]
Hi @jischell-msft, hope you are doing well. We have updated the "Query Style" Guide, at below path. - 
https://github.com/Azure/Azure-Sentinel/wiki/Query-Style-Guide#description

Could you please check it and let us know that can we close this issue? Thanks!

**Comment by jischell-msft** [comment]
@v-sudkharat, feedback:
- placement should be third (3rd) in listing, before `should attempt to be a max of 5 sentences`, since this is a requirement
- change from `'Description' for 'Hunting Query' should NOT exceed more than 255 characters.` to `Do **NOT** exceed 255 characters.`

**Comment by jischell-msft** [comment]
@v-sudkharat thank you for adjusting placement, appears phrasing did not get updated.
Current: `'Description' for 'Hunting Query' should **NOT** exceed 255 characters.`
Should be: `Do **NOT** exceed 255 characters.`

**Comment by v-sudkharat** [comment]
Hi @jischell-msft, thanks for suggestions, we are using "should not" because it is expressing a recommendation and it appropriately placed after the - 'Description' for 'Hunting Query' 
So, closing this issue. If you still need support for this issue, feel free to re-open it any time. Thank you for your co-operation.

**Comment by jischell-msft** [comment]
@v-sudkharat the use of 'Description' in the body of text is unnecessary, because this is within the 'Description' section of the guide. The 'Hunting Query' in the body of text is misleading, as this 255 character limit will be effective for detection queries as well.
