### ISSUE TITLE
 Unable to Authorize GitHubPlaybooks (keyvault) API Connection- Protecting your GitHub assets with Azure Sentinel

### ISSUE THREAD

**Issue by AbhiramVijayan** [Azure/Azure-Sentinel#939]
Getting an error while trying to edit the keyvault API connection. ([Ingest GitHub AuditLog and API Data](https://github.com/Azure/Azure-Sentinel/tree/master/DataConnectors/GitHub))

(step 7,8,9 in [document](https://github.com/Azure/Azure-Sentinel/tree/master/DataConnectors/GitHub) )

1) Go to the keyvault - GitHubPlaybooks connection resource.
2) Click Edit API Connection.
3) Click Authorize. Sign in as the user which was provided in the parameters. Click Save.

Getting an error at step 3 
**"Failed to edit API connection.
Failed to edit API connection 'keyvault-GitHubPlaybooks'."**

![image](https://user-images.githubusercontent.com/23203675/89300467-e50c3b80-d685-11ea-83e8-3e4547448773.png)

![image](https://user-images.githubusercontent.com/23203675/89300150-66170300-d685-11ea-9227-08f354d30d50.png)

![image](https://user-images.githubusercontent.com/23203675/89300259-8c3ca300-d685-11ea-85df-41b9b7afdaf0.png)

**Comment by dicolanl** [comment]
please follow #937  same issue
