### ISSUE TITLE
Please reopen issue  #9145

### ISSUE THREAD

**Issue by fischaz** [Azure/Azure-Sentinel#9408]
**Describe the bug**

Hi team, 

Sadly, it seems that notifications have not worked. Could someone review and re-open #9145  as I've provided new information.

Regards,
Johan.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by v-muuppugund** [comment]
Hi @fischaz , Thanks for flagging this issue, we have reopened the issue(https://github.com/Azure/Azure-Sentinel/issues/9145),so closing the issue
