### ISSUE TITLE
 Cisco ASA's Syslog Parser Not Parsing all the Events.

### ISSUE THREAD

**Issue by v-jackzou** [Azure/Azure-Sentinel#9418]
**Is your feature request related to a problem? Please describe.**
For the current Cisco ASA parser, the parser is not parsing all the Cisco ASA event and Feilds.

For example, for the event 716039

716039
Error Message %ASA-6-716039: Authentication: rejected, group = name user = user , Session Type: %s

Explanation Before a WebVPN session starts, the user must be authenticated successfully by a local or remote server (for example, RADIUS or TACACS+). In this case, the user credentials (username and password) either did not match, or the user does not have permission to start a WebVPN session. The username is hidden when invalid or unknown, but appears when valid or the no logging hide username command has been configured.

%s—The session type, which can be either WebVPN or admin
Recommended Action Verify the user credentials on the local or remote server and that WebVPN is configured for the user.

The parser is not parsing the field above for example the user and the IP. 

Just wish to confirm the coverage of the parser and if there are any further plans to update the parser to improve the coverage

**Comment by v-muuppugund** [comment]
Hi @v-jackzou  , Thanks for flagging this issue, we will investigate this issue and get back to you with some updates by 22Nov23. Thanks!

**Comment by v-muuppugund** [comment]
Hi @v-jackzou ,Could you please share more details,I have checked cisco ASA solution in content hub ,but doesn't have parser

**Comment by v-jackzou** [comment]
Hi @v-muuppugund 

Thanks again for the attention on this, to be more specific, customer needs an ASIM parser for the ASA logs as the current ASA logs ingestion is based on the common Security logs but some of the attributes in the source ASA logs cannot be fit into the Common Security logs table schema.  

For example 
LOCAL5.CRIT: Aug 22 14:37:02 XPNQFW93 : %ASA-2-302014: Teardown TCP connection 135002160 for XPNQ_TRANSIT:170.114.52.6/443 to XPNQ_SQUID_PROXY_PROD:10.71.189.12/60838 duration 0:06:40 bytes 8357 TCP FINs from XPNQ_TRANSIT 

in the common security table schema, there is no place for the address above.
https://learn.microsoft.com/en-us/azure/azure-monitor/reference/tables/commonsecuritylog

therefore we may need to have a parser to address this issue

**Comment by v-jackzou** [comment]
Hi team 

Any updates regarding this issue?

**Comment by v-sudkharat** [comment]
Hi @v-jackzou, sorry for inconvenience. We are investigating this issue, and we will get back to you by - 07-12-2023. Thanks!

**Comment by vakohl** [comment]
@v-jackzou 
Please find details of Events currently supported by this Parser here: https://github.com/Azure/Azure-Sentinel/blob/master/Parsers/ASimAuthentication/Parsers/ASimAuthenticationCiscoASA.yaml

Regarding the event=> 716039, the Message field that we built this parser on had this format => %ASA-6-716039: Group <DefaultADMINGroup> User <*****> IP <192.168.1.5> Authentication: rejected, Session Type: Admin.
The parser will parse User and IP, if the Message field matches above format.

If in your case, parser is unable to parse those field, this could be because of some different format coming in your logs. Can you please help sharing few sample logs from your environment for event: 716039.

**Comment by v-sudkharat** [comment]
Hi @v-jackzou, We are waiting for your response on above comment. Thanks!

**Comment by v-jackzou** [comment]
HI @v-sudkharat @vakohl  thank again for checking on this, the customer has provided the logs, I will share with you offline

**Comment by v-sudkharat** [comment]
Thanks @v-jackzou.

**Comment by v-jackzou** [comment]
HI team, I have provided the information required @v-sudkharat any updates?

**Comment by v-sudkharat** [comment]
Hi @v-jackzou, We have shared the information provided by you with the respective team. They are checking on this issue and will share an update with you. Thanks!

**Comment by vakohl** [comment]
@v-jackzou the parser seems to be parsing fine the log type you shared. Can you please check with customer how they are running this parser?

**Comment by v-sudkharat** [comment]
Hi @v-jackzou, I see recent mail trail response on this issue, just want a confirmation from your end, Could you please let know can we close this issue? 

Thanks!

**Comment by v-sudkharat** [comment]
Hey @v-jackzou, Thank you for sharing your issue closer confirmation on team's chat. So we are closing this issue. If you still need support for this issue, feel free to re-open it any time. Thank you for your co-operation.

**Comment by vakohl** [comment]
Notes: Customer was not using the ASIM parser. Customer was querying CommonSecurityLog table instead was ASIM function. Connected with customer over call and suggested to use ASIM function for parsing.
