### ISSUE TITLE
Defender for Cloud Data Connector doc conflict on requirement for sub-level plans

### ISSUE THREAD

**Issue by deggis** [Azure/Azure-Sentinel#9426]
**Describe the bug**
Documentation for Defender for Cloud Data connector has conflicting statements and does not cover subscriptions with only per-resource enabled Defender for Cloud plans.

**To Reproduce**
1. Go to see documentation for Defender for Cloud data connector:
  - https://github.com/Azure/Azure-Sentinel/blob/master/Solutions/Microsoft%20Defender%20for%20Cloud/Data%20Connectors/AzureSecurityCenter.JSON#L58
  - https://github.com/Azure/Azure-Sentinel/blob/master/Solutions/Microsoft%20Defender%20for%20Cloud/Data%20Connectors/AzureSecurityCenter.JSON#L69

There seems to be inconsistency between the lines 58 and 69:
- "standard tier is no longer required. The connector is available for all deployments of Microsoft Defender for Cloud" 
- "The connector can be enabled only on subscriptions that have at least one Microsoft Defender plan enabled in Microsoft Defender for Cloud"

**Expected behavior**

- "standard tier is no longer required" this comment seems obsolete and seems to refer to an era where there as a single pricing tier for Defender for Cloud.
- "standard tier is no longer required" vs "that have at least one Microsoft Defender plan enabled in Microsoft Defender for Cloud" which one is it?

If this text stays, "that have at least one Microsoft Defender plan enabled in Microsoft Defender for Cloud", I would expect the documentation to updated to cover subscriptions that don't have per sub plans, but only per resource enablements (like Defender for Storage) for some resources.

**Comment by v-muuppugund** [comment]
Hi  @deggis , Thanks for flagging this issue, we will investigate this issue and get back to you with some updates by 24Nov23. Thanks!

**Comment by v-muuppugund** [comment]
Hi @deggis ,I am working on changes and will get back to you with updates by 29Nov23.

**Comment by v-muuppugund** [comment]
Hi @deggis ,Apologies for the delayed response, Standard tier one has been removed ,but as per the connector cofiguration we need to select subscriptions where Microsoft defender plans are enabled, Please let me know if its 5n,I am proceeding with the changes and will have an internal review.

**Comment by v-muuppugund** [comment]
Hi @deggis ,Gentle Reminder, Please let me know if you have issues on above mentioned changes, otherwise will proceed with changes, Thanks.

**Comment by deggis** [comment]
At least the removal of "standard tier is no longer required." looks good to me.

**Comment by v-muuppugund** [comment]
@deggis ,sure,already done it,working on internal review of PR (https://github.com/Azure/Azure-Sentinel/issues/9426)

**Comment by v-muuppugund** [comment]
@deggis ,Will update you once PR completed,Thanks.

**Comment by v-muuppugund** [comment]
Hi @deggis ,Pushing the PR as we have the process for 1p connector and will keep you updated once pr is completed

**Comment by v-sudkharat** [comment]
Hey @deggis, PR has been merged, and the new changes will get reflect in upcoming solution version. Thanks!
