### ISSUE TITLE
Meraki Azure Deploy Button Broken

### ISSUE THREAD

**Issue by JustinGrote** [Azure/Azure-Sentinel#9429]
```https://github.com/Azure/Azure-Sentinel/tree/master/Solutions/CiscoMeraki```

```There was an error downloading the template from URI 'https://raw.githubusercontent.com/Azure/Azure-Sentinel/master/Playbooks/CiscoMeraki/ConsolidatedTemplate.json'. Ensure that the template is publicly accessible and that the publisher has enabled CORS policy on the endpoint. To deploy this template, download the template manually and paste the contents in the 'Build your own template in the editor' option below. ```

**Comment by JustinGrote** [comment]
Looks like `Playbooks` needs to be renamed to `Solutions`

**Comment by v-muuppugund** [comment]
Hi @JustinGrote , Thanks for flagging this issue, we will investigate this issue and get back to you with some updates by 24Nov23. Thanks!

**Comment by philfy20** [comment]
Just manually deploy the connector via this - https://github.com/Azure/Azure-Sentinel/issues/8777#issuecomment-1691339361 looks like a few things are broken but this is working fine

**Comment by JustinGrote** [comment]
@philfy20  I mean, I did that, but probably good to fix the repo so others don't have the same problem, right?

**Comment by v-muuppugund** [comment]
@philfy20 ,Will check on above issues and get back to you, Thanks.

**Comment by v-muuppugund** [comment]
Hi @JustinGrote ,Could you please point to exact play book in meraki, Thanks.

**Comment by JustinGrote** [comment]
> Hi @JustinGrote ,Could you please point to exact play book in meraki, Thanks.

It's literally the deploy button on the README page I linked above.

**Comment by v-sudkharat** [comment]
@JustinGrote, Noted. Thanks!
