### ISSUE TITLE
Issue in Dashboard file (Azure_Ad_Signin.json) and Weird behavior in MFAdetail dynamic dictionnary

### ISSUE THREAD

**Issue by digitalarche** [Azure/Azure-Sentinel#943]
**Describe the bug**

In this dashboard the 'Trust Type' Area:
Line 841 and Line 900 for the title. 

the 'MFA authentication details' Area:
Line 929 and Line 988 for the title. 

It'is the same Query!

 ["value": "\nSigninLogs| summarize count() by tostring( DeviceDetail.trustType)"]

But, we'll have to use MfaDetail (Dynamic Field be careful) and inside the Json the recommanded field would be 'authMethod'

SO, the solution would be  ["value": "\nSigninLogs| summarize count() by tostring(MfaDetail.authMethod)"]

**Additional Issues**

On the other hand I noticed that there was a weird behavior because we have a certain number of 'Authentication Type'

Inside this field 'MfaDetail.authMethod' you have: 

Text message
Mobile app verification code
Mobile app notification
Phone call (Authentication phone)
Phone call (Office phone)

But when you do this on a very consistent AAD (it's my case) the first result is an empty field. 
And let me explain it is either totally an empty field without the brakets (therefore not a dictionary) or it's a dictionary but also empty (with brakets). 

This is the vast majority of results especially when you run this KQL query in your LogAnalytics (connected):

SigninLogs
| summarize count () by tostring (MfaDetail)

**Comment by LuzmariaChile** [comment]
Can you please take me out of this GitHub repo?

Thanks

Luz Maria Pasini

**Comment by digitalarche** [comment]
Hi, 

A lot of commits by week and mostly by month I don't know if it's a error but someone delete the Dashboard Folder ?
There are 28 days.  https://github.com/Azure/Azure-Sentinel/commit/196809f2c8898cff048d6fd4a35109c9dda91cdf

I think there are a idea behind this action, peharps leave workbooks make the dashboards ?? 
But I'm not sure that we have all the twinking with Workbook and especialy we loose some ideas, queries adhoc, and collectiv memories. Iwould have prefered really a archived inside a archive folder -- until really waiting to erase it ! My 2Cents. 

Thanks.

**Comment by v-laanjana** [comment]
@digitalarche are you still facing same issue?

**Comment by v-amolpatil** [comment]
Since we have not received a response in the last 5 days, we are closing your issue #943 as per our standard operating procedures. If you still need support for this issue, feel free to re-open at any time. Thank you for your co-operation.
