### ISSUE TITLE
M365Defender-VulnerabilityManagement Deployment Template Validation Failed

### ISSUE THREAD

**Issue by conor-campbell-23** [Azure/Azure-Sentinel#9450]
**Describe the bug**
When deploying the connector from the Github, validation fails, connector here - https://github.com/Azure/Azure-Sentinel/tree/master/DataConnectors/M365Defender-VulnerabilityManagement)

Error message -
 "Deployment template validation failed: 'The template resource 'rbacAssignmentLaw' at line '2241' and column '5' is not valid: The language expression property array index '2' is out of bounds.. Please see https://aka.ms/arm-functions for usage details.'. (Code: InvalidTemplate)"

**To Reproduce**
1. Go to https://github.com/Azure/Azure-Sentinel/tree/master/DataConnectors/M365Defender-VulnerabilityManagement)
2. Scroll down to Non-Network Restricted Deployment
3. Select Deploy to Azure

**Expected behavior**
Deployment of azure resources to send vulnerability information from Defender to Sentinel

**Screenshots**
Attached
![error1](https://github.com/Azure/Azure-Sentinel/assets/139169636/91c4075a-17f1-479a-9fc4-c24654bfd634)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome and Edge both

**Comment by v-muuppugund** [comment]
Hi @conor-campbell-23 , Thanks for flagging this issue, we will investigate this issue and get back to you with some updates by 28Nov23. Thanks!

**Comment by v-sudkharat** [comment]
Hi @conor-campbell-23, Sorry for delay in response. 
While custom deployment of ARM template, could you please fill details for `Log Analytics Workspace Resource Id` with below format- 

`/subscriptions/Your Subscription Id /resourceGroups/YourResourceGroupName/providers/Microsoft.OperationalInsights/workspaces/YourWorkspaceName`


![image](https://github.com/Azure/Azure-Sentinel/assets/132428394/e6fa4ce4-f66c-4798-9297-4e66bea7ad2c)

Once you filled required details click on review and create. Please let us know if issue is still persist. 

Thanks!

**Comment by conor-campbell-23** [comment]
hey folks, we got this deployed, not sure if maybe it was a permissions issue but it is working ok now.

**Comment by v-sudkharat** [comment]
Hi @conor-campbell-23, thanks for your confirmation.
