### ISSUE TITLE
Unable to save DoD Zero Trust Strategy Sentinel Workbook on some US regions

### ISSUE THREAD

**Issue by mstracyli** [Azure/Azure-Sentinel#9455]
**Describe the bug**

Need assistance to fix or understand why it is not possible to save the DoD Zero Trust Strategy Workbook on some US regions.
(Same issue happened to other workbooks as well)

Internal ICM 433560567 created but since it is standalone content PG suggested to create a Github issue.

**To Reproduce**
<html>
<body>

1. Go to Microsoft Sentinel2. Select a Workspace3. Click on the Content Hub blade4. Search for DoD Zero Trust Strategy Workbook5. Click on Save6. Choose East US
--

</body>
</html>

Trying save the DoD Zero Trust Strategy Workbook on some US regions (specifically East US), the portal is returning the following error:
![image](https://github.com/Azure/Azure-Sentinel/assets/95902734/2070b640-a0f0-4051-9132-5a24e9437a5b)

![image](https://github.com/Azure/Azure-Sentinel/assets/95902734/3295173f-0965-4155-a705-862b03b35da7)

If we try to save the Workbook on another region, like Canada Central or other US regions, there is no issues.

I understand there could be some default limit of 2MB on all the regions (include workbook content and its meta data, but
Why it's allowing us to save the workbook in some regions but not all.

If the limitation is by design, please review the design as it is blocking user create the workbook in some regions.

**Expected behavior**
Expect to be able to save the workbook in all regions.

**Screenshots**
Attached as above.

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by v-muuppugund** [comment]
Hi @mstracyli , Thanks for flagging this issue, we will investigate this issue and get back 	to you with some updates by 28Nov23. Thanks!

**Comment by blauwers** [comment]
The 2 MB limit is for the template plus Azure internal metadata. The 'East US' region appears to attach a greater amount of Azure metadata causing this template to fail to deploy in the region. Since the amount of Azure metadata is not defined by the end-user and is dependent on the region it leads to unpredictable outcomes.

This is a bug in Azure. Templates should have a 2 MB limit (if a limit is really needed) without any of the Azure metadata attached so that results are consistent.

**Comment by v-sudkharat** [comment]
@blauwers, thanks for information. we will check on this. and let you by - 29 Nov 2023.

**Comment by v-muuppugund** [comment]
Hi @blauwers ,Could you please share HAR logs from the browser for this issue troubleshooting

**Comment by v-muuppugund** [comment]
Hi @blauwers ,Gentle Reminder, Could you please share HAR logs from the browser for this issue troubleshooting

**Comment by mstracyli** [comment]
Hi @v-muuppugund , thank you for checking the issue. Sorry for the late response as I just came back from vacation. The issue is 100% reproducible by users and our internal teams so you can reproduce in your environment as well. If you need a HAR, I can share with you offline the HAR in my environment.

**Comment by v-muuppugund** [comment]
Hi @mstracyli ,I am trying to reach you over teams on this issue,Please find the screen shot as i am able to save it in my work space for reference

![image](https://github.com/Azure/Azure-Sentinel/assets/139563098/c9f76226-b8a8-4cbb-8406-f93497709bae)

**Comment by blauwers** [comment]
@v-muuppugund did you save it to the "East US" region?

**Comment by v-muuppugund** [comment]
> @v-muuppugund did you save it to the "East US" region?

Yes its in East US 
![image](https://github.com/Azure/Azure-Sentinel/assets/139563098/d8049bc0-cc59-4bfb-a137-2cdd5bd5df5d)

**Comment by mstracyli** [comment]
Hi @v-muuppugund , I just shared you the HAR in Teams. I am still 100% able to reproduce the issue. From your screenshot, I understand the Sentinel workspace is in East US, when you save the workbook, could you double check if the workbook is saved in East US as well?
![image](https://github.com/Azure/Azure-Sentinel/assets/95902734/18baed5e-e8d7-4aa9-afb8-e6035a220643)

**Comment by v-sudkharat** [comment]
Hi @mstracyli, will check and get back to you by - 29-12-2023. Thanks!

**Comment by v-muuppugund** [comment]
Hi @blauwers ,I am troubleshooting it, will get back to with an update.

**Comment by mstracyli** [comment]
Hi @v-muuppugund , kindly allow me for a follow-up if you have any update on the issue. Thank you!

**Comment by v-muuppugund** [comment]
Hi @mstracyli ,Still working on it, Will get back to you with an update.

**Comment by v-muuppugund** [comment]
Hi @mstracyli / @blauwers ,noticed from the code its self we are sending the message i.e.  errorCode: 413,
        message: "The workbook length is too large." and trying to replicating the scenario locally so can address the issue

**Comment by ran-ten21** [comment]
I have taken over this - please keep me up to date. Can we get this fixed soon?

**Comment by ran-ten21** [comment]
@v-muuppugund  - like are you expecting us to tell the customer to adjust something? how can we resolve this issue?

**Comment by ran-ten21** [comment]
@v-sudkharat - can I please get an update?

**Comment by v-muuppugund** [comment]
Hi @ran-ten21 / @blauwers / @mstracyli  there is a work book limitation of 2mb ,i thought of checking through code while debugging and fixing it but taking time as am facing issues for permanent fix,could you please ask customer to 1. adjust the size less than 2mb, 2.tried to save in another region other East Us and West Us,mean while will check on permanent fix.

**Comment by ran-ten21** [comment]
response from customer:
The workbook is smaller than the advertised 2 mb. It’s the Azure metadata that is added to the transaction that is putting it over the limit. It does not do this in most other regions, this is a region-specific problem. The region where we happen to run Sentinel.

I already have this Microsoft solution deployed as it’s not a problem for us to modify the code. I don’t believe many other customers will happily make edits to a Microsoft supplied solution to make it work on your platform.

That said, I don’t specifically like the thought of having to keep up with this as updates are released.

I see this as an Azure problem, not a workbook or Sentinel problem. Deployments should behave consistently and have predictable outcomes.

Right now, the limit for the workbooks is 2 mb minus some unpredictable amount of metadata that is outside of the customer control. That is bad IT / devops.

**Comment by v-muuppugund** [comment]
Hi @ran-ten21 ,Apologies for the delayed response,got it,Could you please let me know if any thing needed from my side,so we can proceed further,just want to update from my side,faced machine issues didn't get chance to complete the analysis from my side.

**Comment by v-muuppugund** [comment]
Hi @blauwers / @ran-ten21 ,We have modified the attached [DoDZeroTrustWorkbook 1.json](https://github.com/Azure/Azure-Sentinel/files/14873817/DoDZeroTrustWorkbook.1.json) workbook template and let us know if any issues.

Please follow below steps to save workbook manually.
 
1. Navigate to Sentinel --> Workbook blade --> Click on Add workbook.

![image](https://github.com/Azure/Azure-Sentinel/assets/139563098/0acc282d-ee54-46d4-916d-5b449c481f7b)

 
 
2. Click on Edit and the advanced edit (</>)
 
 
![image](https://github.com/Azure/Azure-Sentinel/assets/139563098/fbd6f74f-42f3-4a89-8753-ff1b0ab4a585)

![image](https://github.com/Azure/Azure-Sentinel/assets/139563098/bde4b71e-05d6-426d-8bb4-fc74fbcf8c27)


 
3. Paste the workbook content --> click Apply on right hand top corner and then click on done editing.
4.Click save on top banner and you can save the workbook by adding Subscription, resource group and other details.
 
![image](https://github.com/Azure/Azure-Sentinel/assets/139563098/df64bdb7-9dd1-481e-9fad-e60f3fed23f2)

 
 
The workbook will be saved.
 
Note- To load the content of specific tab you will get notification to load remote content, click yes to load the content.
![image](https://github.com/Azure/Azure-Sentinel/assets/139563098/6e02f9a0-a633-440d-9b1b-b9ee9c790327)

**Comment by v-muuppugund** [comment]
> Hi @blauwers / @ran-ten21 ,Gentle Reminder,Could you please perform the above steps and let us know if any issues.

**Comment by v-muuppugund** [comment]
Hi @blauwers / @ran-ten21 Since we have not received a response in the last 5 days, we are closing your issue (https://github.com/Azure/Azure-Sentinel/issues/9455) as per our standard operating procedures. If you still need support for 	this issue, feel free to re-open at any time. Thank you for your co-operation!
