### ISSUE TITLE
Microsoft Entra ID - Analytics rules - SigninLogs table: incorrect detection logic

### ISSUE THREAD

**Issue by J3roen** [Azure/Azure-Sentinel#9463]
**Is your feature request related to a problem? Please describe.**
The SigninLog table has multiple records for 1 login activity, which can be grouped by either Id or OriginalRequestId.
None of the current detection rules for suspicious login attempts take this into account, leading to excessive false positive hits on most of these rules.

**Describe the solution you'd like**
Improve detection rules based on the SigninLog table to include the summarize command
_| summarize arg_max(TimeGenerated, *) by Id_ 
before performing any detection logic. This will ensure that the rule only considers the final result of the login attempts, and not the intermediate steps

**Comment by v-muuppugund** [comment]
Hi @J3roen , Thanks for flagging this issue, we will investigate this issue and get back to you with some updates by 28Nov23. Thanks!

**Comment by v-muuppugund** [comment]
Hi @J3roen ,Could you please share more details about the ask or issue you are facing

**Comment by v-muuppugund** [comment]
Hi @J3roen ,Gentle reminder,Could you please share more details about the ask or issue you are facing.

**Comment by v-muuppugund** [comment]
Hi @J3roen ,Since we have not received a response in the last 5 days, we are closing your issue (https://github.com/Azure/Azure-Sentinel/issues/9463) as per our standard operating procedures. If you still need support for 	this issue, feel free to re-open at any time. Thank you for your co-operation!
