### ISSUE TITLE
ASIM: imAuditEvent Parsers does not pass parameters to stub parsers

### ISSUE THREAD

**Issue by briandelmsft** [Azure/Azure-Sentinel#9474]
**Describe the bug**
When calling the imAuditEvent parser, it does not pass the parser parameters to the sub parsers.

In fact it calls the incorrect stub parsers that don't even support the parameters, it calls the ASim* stub parsers, when it should be calling the vim* stub parsers and passing the parameters

As a result, a query such as `imAuditEvent(starttime=ago(14d))` will not pass the 14d filter, and the data returned will only be for the time range your query is otherwise set to in the search window

**To Reproduce**
Run the query
```
imAuditEvent(starttime=ago(14d))
| summarize min(TimeGenerated), max(TimeGenerated)
```
While the oldest data should be approximately 14 days old, the min returned timestamp will be in the last 24 hours by default

If you run the less efficient query
```
imAuditEvent()
| where TimeGenerated > ago(14d)
| summarize min(TimeGenerated), max(TimeGenerated)
```
you will get data from the 14 day window

**Expected behavior**
The parser should honor the parameters that are passed

**Comment by vakohl** [comment]
Thanks for reporting this @briandelmsft 
PR has been raised to fix this - https://github.com/Azure/Azure-Sentinel/pull/10116
In the meantime, you can use in-built _Im_AuditEvent function

**Comment by v-sudkharat** [comment]
Hi @briandelmsft, The PR has been merged with the fix, so closing this issue. If you still need support for this issue, feel free to re-open it any time. Thank you for your co-operation.
