### ISSUE TITLE
Cannot use join KQL for Analytics Rules 

### ISSUE THREAD

**Issue by jeffrywu28** [Azure/Azure-Sentinel#9484]
**Describe the bug**
why i cannot use detection rules that correlated with ThreatIntelIndicator join table ?

**To Reproduce**
1. Go to Analytics Rules
2. Create analytics rules
3. use the query :

_Im_NetworkSession
| where ipv4_is_private(SrcIpAddr) == False
| where SrcIpAddr !in ("127.0.0.1", "::1")
| summarize
    AttemptedPortsCount = dcount(DstPortNumber), 
    AttemptedPorts = make_set(DstPortNumber), 
    ReportedBy = make_set(strcat(EventVendor, "/", EventProduct)), 
    LastTimeGenerated = max(TimeGenerated)
    by SrcIpAddr
| where AttemptedPortsCount > PortScanThreshold
| join kind=inner (
    ThreatIntelligenceIndicator
    | summarize ThreatTypes = make_set(ThreatType) by NetworkSourceIP  // Aggregate ThreatTypes for each NetworkSourceIP
    )
    on $left.SrcIpAddr == $right.NetworkSourceIP
| project
    SrcIpAddr,
    LastTimeGenerated,
    AttemptedPortsCount,
    AttemptedPorts,
    ReportedBy,
    ThreatTypes

**Expected behavior**
It's running and showing the test result clearly

**Screenshots**
<img width="1041" alt="image" src="https://github.com/Azure/Azure-Sentinel/assets/47622164/9ffbf685-c639-470f-af95-c01c13235e8a">

**Comment by v-sudkharat** [comment]
Hi @jeffrywu28, just want to know, have you declaired the `"let PortScanThreshold = 50;"` in the query? 
We have run your provided query in our workspace we are got below result. - 
![image](https://github.com/Azure/Azure-Sentinel/assets/132428394/18b1dccd-4841-412e-bac4-2514a0855015)

If we declare the `"let PortScanThreshold = 50;"` in query and re-run it, then query executed successfully and start getting the result -

![image](https://github.com/Azure/Azure-Sentinel/assets/132428394/42f7d9c0-2f94-4cc7-8529-07571ebf01ca)
 
 FYI. we have defined the `"let PortScanThreshold = 50;"` as 50 at the beginning of the query. This means that the query will only consider source IP addresses (SrcIpAddr) that have attempted to connect to more than 50 different ports (AttemptedPortsCount > PortScanThreshold).
 
Could you please check with `"let PortScanThreshold = 50;"` and let us know if your issue still persists. 
Thanks!

**Comment by v-sudkharat** [comment]
Hi @jeffrywu28, Gentle Reminder: We are waiting for your response on this issue. If you still need to keep this issue active, please respond to it in the next 2 days. If we don't receive a response by 08-12-2023 date, we will be closing this issue. 		
Thanks!
