### ISSUE TITLE
Get-AzSentinelAlertRule doesn't show Techniques mapped in the rules.

### ISSUE THREAD

**Issue by ovcrash** [Azure/Azure-Sentinel#9491]
**Describe the bug**

**To Reproduce**
Use Get-AzSentinelAlertRule to get a rule or all rules and it will only output the Tactics but not the Techniques.
When we go into the GUI, we can clearly see the Tactics and Techniques.

**Expected behavior**
We should see the Tactics and Techniques that are mapped on the rule.

**Screenshots**
n/a

**Desktop (please complete the following information):**
Script     3.1.1                 Az.SecurityInsights

**Smartphone (please complete the following information):**
n/a

**Additional context**
In this documentation:
[https://learn.microsoft.com/en-us/rest/api/securityinsights/alert-rules/list?view=rest-securityinsights-2023-10-01-preview&tabs=HTTP](url)
They do show in the Responses section, that there is a Techniques field in the Sample Response section.

**Comment by v-sudkharat** [comment]
Hi @ovcrash, Thanks for flagging this issue, we will investigate this issue and get back to you with some updates by 04-12-2023. Thanks!
