### ISSUE TITLE
Cisco Duo Function App failure - Timer fired.

### ISSUE THREAD

**Issue by technaholic** [Azure/Azure-Sentinel#9502]
**Describe the bug**
Our Cisco Duo Function App is failing with :
Timeout value of 00:10:00 exceeded by function 'Functions.AzureFunctionCiscoDuo' (Id: 'bd62380e-bf7b-4890-b87a-462a1a5782ca'). Initiating cancellation.
We have set "MAX_SYNC_WINDOW_PER_RUN_MINUTES" to 120 after that fix was implemented, but it still times out.
From looking at the monitor logs it seems to be only grabbing logs from July 10th around 3:52pm and forward and then starts right back at that same spot again each time it runs.

**To Reproduce**
1. Run Function app.
2. It fails

**Expected behavior**
We expect all of our Duo logs to be ingested into Sentinel.  Note that we have almost 40,000 users in Cisco Duo with 50,000 to 75,000 authentications every 24 hours.

**Screenshots**
![image](https://github.com/Azure/Azure-Sentinel/assets/4130041/b5049b70-2ded-4315-b5cd-65ea12ddaa06)
![image](https://github.com/Azure/Azure-Sentinel/assets/4130041/29d93fbf-5217-4ae9-b3ff-6fe843721c76)
![image](https://github.com/Azure/Azure-Sentinel/assets/4130041/538bf4d9-60bc-4f17-a5fc-a0ae0f932350)
![image](https://github.com/Azure/Azure-Sentinel/assets/4130041/a37ab304-342c-4737-9343-b5b502c2a7be)

**Desktop (please complete the following information):**
 - OS: MacOS 14 and Windows 11/10
 - Browser : Chrome / Safari / Firefox / Edge
 - Version : latest of all

**Smartphone (please complete the following information):**
N/A

**Additional context**
N/A

**Comment by technaholic** [comment]
Thanks for the update

**Comment by v-muuppugund** [comment]
Hi @technaholic ,I have done the analysis and need few more details before proceeding with the changes  as need to have data points What is the daily volume of data for the following log types and every run what is the volume we are trying to ingesting from cisco due,,What is the total volume of logs ingesting daily,

1. trust_monitor
2. authentication
3. administrator
4. telephony
5. offline_enrollment

based on the data points and future volume for this log types ,so will proceed and do the design changes, Could you please share couple of time slots and email ,will have a teams meeting for this issue.

**Comment by technaholic** [comment]
Murali,
     So, before I left work for the holidays I checked the code that we
have against what is in GitHub and noticed that it was about 100 lines
short and so was obvious that it wasn't the right code.  I believe this is
because from the first issue I opened up last July we were provided a fix
and were running that and it didn't auto update to the latest version when
you all pushed a new version out.  I have since fixed that and it is about
50% successful now.  You can close this ticket as the issue we are getting
now is a BrokenPipeError which is different from it timing out.  I'm gonna
take a deeper look into it after the start of the year and might open a new
issue up.

Thanks and Happy Holidays!
-paul

**Comment by v-muuppugund** [comment]
@technaholic Thanks for confirmation for closure, If you still need support for his issue, feel free to re-open at any time.
