### ISSUE TITLE
Function Parameters default values not deployed with Parsers during solution deployment "Microsoft Exchange Security - Exchange Online"

### ISSUE THREAD

**Issue by nlepagnez** [Azure/Azure-Sentinel#9520]
**Describe the bug**
When the solutions "Microsoft Exchange Security - Exchange Online" or "Microsoft Exchange Security - Exchange On-Premises" are deployed, the parsers inside the solutions are deployed but without the default value of the parameters

**To Reproduce**
1. Go to 'Content Hub'
2. Deploy the solution "Microsoft Exchange Security - Exchange Online"
3. Go to 'Logs'
4. Search the parser 'ExchangeConfiguration' in 'Workspace Functions'
5. Check the parameters of the parser
6. Default value of parameters have to be visible

**Expected behavior**
Default value of parameters have to be visible. Values configured in the Solution : 
"functionParameters": "SpecificSectionList:string = \"\", SpecificConfigurationDate:string = \"lastdate\", Target:string = \"On-Premises\", SpecificConfigurationEnv:string = \"All\"",

**Screenshots**
Actual : 
![image](https://github.com/Azure/Azure-Sentinel/assets/2814429/f85f345b-b8c5-4532-86dc-11df00b44475)

Desired : 
![image](https://github.com/Azure/Azure-Sentinel/assets/2814429/aeaafc8e-472a-412b-bf8e-a07682affab5)

Configured in the template : 
![image](https://github.com/Azure/Azure-Sentinel/assets/2814429/a41b8879-73ee-457c-a796-a4c84b22391f)

**Comment by nlepagnez** [comment]
Notes that "Manual deployment" of the package using https://aka.ms/AzureSentinelPrP as indicated here for testing (https://github.com/Azure/Azure-Sentinel/blob/master/Tools/Create-Azure-Sentinel-Solution/V2/README.md) deploys correctly the "default values" of the parameters for solution "Microsoft Exchange Security - Exchange On-Premises".

Perhaps linked to an error in the "Online" package : https://github.com/Azure/Azure-Sentinel/pull/9522

**Comment by v-sudkharat** [comment]
Hi @nlepagnez, Thanks for flagging this issue, we will investigate this issue and get back to you with some updates by 08-12-2023. Thanks!
