### ISSUE TITLE
Azure Monitor HTTP Data Collector API has been deprecated

### ISSUE THREAD

**Issue by miloszpiglas** [Azure/Azure-Sentinel#9529]
**Describe the bug**
According to [Azure documentation](https://learn.microsoft.com/en-us/azure/azure-monitor/logs/data-collector-api?tabs=powershell) The Azure Monitor HTTP Data Collector API has been deprecated and will no longer be functional as of 9/14/2026. However it is advertised in this repository and in Azure documentation as go-to solution for Sentinel connectors. After 2026-09-14 connectors using shutdown API might stop working

**Expected behavior**
Logs ingestion API should be used in mentioned in this repository instead deprecated Data Collector API.

**Comment by v-sudkharat** [comment]
Hi @miloszpiglas, Thanks for flagging this issue, we will investigate this issue and get back to you with some updates by 08-12-2023. Thanks!

**Comment by v-muuppugund** [comment]
Hi @miloszpiglas ,We are still working on this issue analysis and will get back to you with an updates by 13/11/2023

**Comment by v-muuppugund** [comment]
Hi @miloszpiglas ,We can use DCR as another option i.e. Logs ingestion api (https://learn.microsoft.com/en-us/azure/azure-monitor/logs/logs-ingestion-api-overview),Please let me know if need more details

**Comment by v-muuppugund** [comment]
Hi @miloszpiglas ,Gentle Reminder, We can use DCR as another option i.e. Logs ingestion api (https://learn.microsoft.com/en-us/azure/azure-monitor/logs/logs-ingestion-api-overview), Please let me know if need more details

**Comment by v-muuppugund** [comment]
@miloszpiglas , Since we have not received a response in the last 5 days, we are closing your issue (https://github.com/Azure/Azure-Sentinel/issues/9529) as per our standard operating procedures. If you still need support for this issue, feel free to re-open at any time. Thank you for your co-operation!
