### ISSUE TITLE
MimecastSEG Azure Function timeouts after 30 minutes

### ISSUE THREAD

**Issue by plutusrt** [Azure/Azure-Sentinel#9543]
**Describe the bug**
The function keeps getting events from Mimecast, and timeouts after 30 minutes

**Expected behavior**
Sending the messages after X messages 
**Screenshots**
<img width="1124" alt="image" src="https://github.com/Azure/Azure-Sentinel/assets/147429520/4ec2b0e2-1cbf-41a2-9b65-9dd3dc376fe3">

**Additional context**
Was able go fix it by adding a counter of 100(example) changes are bolded and change the function timer to every one minutes after the old one finishes

**counter = 0**

    try:
        while has_more_logs:
            model = GetSIEMLogsRequest(file_format, next_token)
            response = request_helper.send_post_request(model.payload, MimecastEndpoints.get_siem_logs)
            response_helper.check_response_codes(response, MimecastEndpoints.get_siem_logs)
            success_response = response_helper.parse_siem_success_response(response, file_format)
            has_more_logs, next_token = response_helper.get_siem_next_token(response)
            parsed_logs.extend(siem_parser.parse(logs=success_response))
            **if counter > 100:
                has_more_logs = False
            else:
                counter+=1**

**Comment by v-sudkharat** [comment]
Hi @plutusrt, Thanks for flagging this issue, we will investigate this issue and get back to you with some updates by 12-12-2023 Thanks!

**Comment by v-sudkharat** [comment]
Hi @plutusrt, hope you are doing well. This solution's is a supported with Mimecast, we kindly request you to raise an issue ticket with Mimecast's support team.
Sharing the Mimecast mail ID and support link -
Mail Id - "[support@mimecast.com](mailto:support@mimecast.com)"
Link - "https://community.mimecast.com/s/contactsupport"
Closing this issue from github. If you still need support for this issue, feel free to re-open it any time. Thank you for your co-operation.
