### ISSUE TITLE
Deploy ASIM to Azure Fails

### ISSUE THREAD

**Issue by Wallace4444** [Azure/Azure-Sentinel#9546]
**Describe the bug**
When deploying ASIM to Azure from https://github.com/Azure/Azure-Sentinel/tree/master/ASIM, the deployment fails.

A number of parsers fail with:

The resource write operation failed to complete successfully, because it reached terminal provisioning state 'Failed'. (Code: ResourceDeploymentFailure)

At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-deployment-operations for usage details. (Code: DeploymentFailed), {

  "error": {

    "code": "NewerDataExists",

    "message": "Failed to modify resource '/subscriptions/<subid>/resourceGroups/<resourcegroup>providers/Microsoft.OperationalInsights/workspaces/<workspace>', newer data exists. If you are using eTag please use the latest one and try again in a few minutes. Operation Id: '64498f4aba872aea66c58ac8b611b83c'"

  }

} (Code: Conflict)

Have tested on a brand new Sentinel workspace and it fails with same error.

**To Reproduce**
1. Go to '(https://github.com/Azure/Azure-Sentinel/tree/master/ASIM)'
2. Click on 'Deploy to Azure'
3. Fill in details and deploy

**Expected behavior**
ASIM Parsers deployed successfully.

**Screenshots**
![image](https://github.com/Azure/Azure-Sentinel/assets/44393444/33b1b787-2018-4f45-8839-0cc0e4cc3379)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser Edge / Firefox

**Comment by vakohl** [comment]
hi @Wallace4444 we are aware of this issue and we're looking into its fix. For now, can you please try installing the schema you need individually. If you get error with individual schemas as well, please retry 2-3 times. This issue is more related to Log Analytics than Sentinel, we are working with concerned teams to get this resolved soon. Thankyou

**Comment by v-sudkharat** [comment]
Hi @Wallace4444, hope you are doing well. As this issue has already been reported in the following GitHub issue: - https://github.com/Azure/Azure-Sentinel/issues/8623 and is presently under investigation, we recommend monitoring the issue for updates. Consequently, we are closing this issue for the time being. Feel free to comment on #8623 if there is anything you would like to share more.
Thank you for your co-operation.
