### ISSUE TITLE
Crowdstrike analytics and workbooks do not work due to incorrect use of capitalisation referencing function CrowdstrikeFalconEventStream

### ISSUE THREAD

**Issue by MikeBakerSAV** [Azure/Azure-Sentinel#9551]
**Describe the bug**
Sentinel connections and workbooks for crowdstrike do not work due to incoherent use of Case when referencing "CrowdstrikeFalconEventStream" or "CrowdStrikeFalconEventStream"   - note issue with "strike v Strike"

previously reported in #8028 

**To Reproduce**
Function (lower case s)- https://github.com/Azure/Azure-Sentinel/blob/master/Solutions/CrowdStrike%20Falcon%20Endpoint%20Protection/Parsers/CrowdstrikeFalconEventStream.yaml

https://github.com/Azure/Azure-Sentinel/blob/master/Solutions/CrowdStrike%20Falcon%20Endpoint%20Protection/Workbooks/CrowdStrikeFalconEndpointProtection.json  line 120

**Expected behavior**
use of correct and consistent CASE

**Comment by v-sudkharat** [comment]
Hi @MikeBakerSAV, Thanks for flagging this issue, we will investigate this issue and get back to you with some updates by 12-12-2023. Thanks!

**Comment by v-sudkharat** [comment]
Hi @MikeBakerSAV, we are working on modification, meanwhile could you please follow the below steps and check is modified function is working for you.  
1. go to LAW and search for `CrowdstrikeFalconEventStream` in functions -
![image](https://github.com/Azure/Azure-Sentinel/assets/132428394/5e0422ca-3912-4420-91be-74c924643d1a)
 
2. Click on Load function code- 
![image](https://github.com/Azure/Azure-Sentinel/assets/132428394/7a29c31a-0a0a-43e0-9587-c1abfdaaf2df)

3. then click on save as a function and save the function with name - `CrowdStrikeFalconEventStream`
![image](https://github.com/Azure/Azure-Sentinel/assets/132428394/d9440d47-c886-41d0-888e-6e68e62fb999)
![image](https://github.com/Azure/Azure-Sentinel/assets/132428394/ae6a8ead-4931-409a-953b-507d5a7ebe87)

Once faction is saved, check your sentinel connection for which you are facing issue. 
Thanks!

**Comment by v-sudkharat** [comment]
Hi @MikeBakerSAV, We are waiting for your response on above comment. Thanks!

**Comment by v-sudkharat** [comment]
Hi @MikeBakerSAV, Gentle Reminder: We are waiting for your response on this issue. If you still need to keep this issue active, please respond to it in the next 2 days. If we don't receive a response by 20-12-2023 date, we will be closing this issue. 		
Thanks!

**Comment by MikeBakerSAV** [comment]
this seems to have resolved the problems for the workbook - we will check the other advanced modules for CS enrichment and see if there are other issues.

**Comment by v-sudkharat** [comment]
Hi @MikeBakerSAV, sure. Please check and let us know. Thanks!

**Comment by v-sudkharat** [comment]
Hi @MikeBakerSAV, I hope you are doing well. just want to check have you check on your advance environment? 
Thanks!

**Comment by MikeBakerSAV** [comment]
this appears to be working through our smoketests.  i think you can close issue

**Comment by v-sudkharat** [comment]
Hi @MikeBakerSAV, thank you for your confirmation. Closing this issue. If you still need support for this issue, feel free to re-open it any time. Thank you for your co-operation.
