### ISSUE TITLE
Functionality broken for GWorkspaceReportsAPISentinelConnector following code update

### ISSUE THREAD

**Issue by Shammack** [Azure/Azure-Sentinel#9563]
**Describe the bug**
A reference before assignment error for the local variable 'next_page_token' is now triggering on our GoogleWorkspace Function App.

**Full Error**
Exception while executing function: Functions.GWorkspaceReportsAPISentinelConnector Result: Failure
Exception: UnboundLocalError: local variable 'next_page_token' referenced before assignment
Stack:   File "/azure-functions-host/workers/python/3.8/LINUX/X64/azure_functions_worker/dispatcher.py", line 406, in _handle__invocation_request
    call_result = await self._loop.run_in_executor(
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/azure-functions-host/workers/python/3.8/LINUX/X64/azure_functions_worker/dispatcher.py", line 648, in _run_sync_func
    return ExtensionManager.get_sync_invocation_wrapper(context,
  File "/azure-functions-host/workers/python/3.8/LINUX/X64/azure_functions_worker/extension.py", line 215, in _raw_invocation_wrapper
    result = function(**args)
  File "/home/site/wwwroot/GWorkspaceReportsAPISentinelConnector/__init__.py", line 342, in main
    result_obj, next_page_token = get_result(line,latest_timestamp,end_time)
  File "/home/site/wwwroot/GWorkspaceReportsAPISentinelConnector/__init__.py", line 162, in get_result
    return result_activities, next_page_token

**Screenshots**
![image](https://github.com/Azure/Azure-Sentinel/assets/14854818/1c0dfe5a-9b40-4f6f-b844-45bdd539c9d4)

**Azure Function App:**
 - Runtime version: 4.27.5.5
 - Operating System: Linux

**Comment by v-sudkharat** [comment]
Hi @Shammack, Thanks for flagging this issue, we will investigate this issue and get back to you with some updates by 20-12-2023. Thanks!

**Comment by v-muuppugund** [comment]
Hi @Shammack, Could you please share exceptions from app insights and also the invocation logs details logs in text or csv format, need some details about when on wards this function app stopped, and it worked earlier or not with all the configurations in place, if needed we can have a team's meeting, please share convenient time slots and email id, Thanks.

**Comment by v-sudkharat** [comment]
Hi @Shammack, Could you please have a look at above comment. Thanks!

**Comment by v-muuppugund** [comment]
Hi @Shammack ,gentle reminder, Could you please share exceptions from app insights and also the invocation logs details logs i.e. traces from app insights in text or csv format, need some details about when on wards this function app stopped, and it worked earlier or not with all the configurations in place, if needed we can have a team's meeting, please share convenient time slots and email id,will take it forward on this issue, Thanks.

**Comment by v-muuppugund** [comment]
Hi @Shammack ,Since we have not received a response in the last 5 days, we are closing your issue (https://github.com/Azure/Azure-Sentinel/issues/9563  )as per our standard operating procedures. If you still need support for 	his issue, feel free to re-open at any time. Thank you for your co-operation!
