### ISSUE TITLE
Suspicious AAD Joined Device Update {{OldDeviceName}} renamed to {{NewDeviceName}} and {{UpdatedPropertiesCount}} properties changed

### ISSUE THREAD

**Issue by Kharn9201** [Azure/Azure-Sentinel#9569]
**Describe the bug**
I have an analytic rule in my Senitnel Enviroment with the following name "Suspicious AAD Joined Device Update {{OldDeviceName}} renamed to {{NewDeviceName}} and {{UpdatedPropertiesCount}} properties changed" - The above name is what I expect to see in Sentinel however when this alert triggers the alert shows in the incident tab as "Suspicious AAD Joined Device Update {{NewDeviceName}} renamed to {{OldDeviceName}} and {{UpdatedPropertiesCount}} " having the names the wrong way around, in itself not a big deal but can cause a level of confuison.

**To Reproduce**
Run this analytic rule and check the output in the Incident tab.

**Expected behavior**
To receive the alert as it the name is written e.g " "Suspicious AAD Joined Device Update {{OldDeviceName}} renamed to {{NewDeviceName}} and {{UpdatedPropertiesCount}} properties changed"

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome

**Additional context**

Not sure if this is limited to my instance or wider instance, additionally I am aware I can swap the OldDeviceName and NewDeviceName variable in the alert logic itself to display differently, I am just wondering if there is a deeper issue maybe in the alert logic itself?

**Comment by v-sudkharat** [comment]
Hi @Kharn9201, Thanks for flagging this issue, we will investigate this issue and get back to you with some updates by 18-12-2023. Thanks!

**Comment by v-muuppugund** [comment]
Hi @Kharn9201 ,Could you please share more details about the issue you're facing with Problem statement and screen shot with issue details as I am unable to get the query and am going through the below analytic rule,Thanks.
(https://github.com/Azure/Azure-Sentinel/blob/bdeb8adf97c39a6ec87267410a91bb72976748a7/Solutions/Microsoft%20Entra%20ID/Analytic%20Rules/SuspiciousAADJoinedDeviceUpdate.yaml#L2)

**Comment by v-muuppugund** [comment]
Hi @Kharn9201 ,Gentle Reminder, ,Could you please share more details about the issue you're facing with Problem statement and screen shot with issue details as I am unable to get the query and am going through the below analytic rule,Thanks.
(

[Azure-Sentinel/Solutions/Microsoft Entra ID/Analytic Rules/SuspiciousAADJoinedDeviceUpdate.yaml](https://github.com/Azure/Azure-Sentinel/blob/bdeb8adf97c39a6ec87267410a91bb72976748a7/Solutions/Microsoft%20Entra%20ID/Analytic%20Rules/SuspiciousAADJoinedDeviceUpdate.yaml#L2)

Line 2 in [bdeb8ad](https://github.com/Azure/Azure-Sentinel/commit/bdeb8adf97c39a6ec87267410a91bb72976748a7)

 name: Suspicious Entra ID Joined Device Update 
)
