### ISSUE TITLE
AzureFunctionOktaSSO does not handle pagination of results

### ISSUE THREAD

**Issue by aka0** [Azure/Azure-Sentinel#957]
**Describe the bug**
AzureFunctionOktaSSO does not handle pagination of results. OKTA events would be missed for users with a large number of OKTA events. 

**To Reproduce**
1. Deploy AzureFunctionOktaSSO 
2. Change `time` to a larger interval 
3. Examine the header
4. If `Link` header contains `next` then there are more results
```
"link": "<https://example.okta.com/api/v1/logs?since=2020-08-11T12%3A24%3A09.4654876Z&limit=1000&sortOrder=ASCENDING>; rel=\"self\",<https://example.okta.com/api/v1/logs?since=2020-08-11T12%3A24%3A09.4654876Z&limit=1000&sortOrder=ASCENDING&after=1597148709086_1>; rel=\"next\""
```

**Expected behavior**
AzureFunctionOktaSSO should follow `next` link to upload all results to the Log Analytics workspace. 

**Screenshots**
N/A

**Additional context**
- https://developer.okta.com/docs/reference/api/system-log/#next-link-response-header

**Comment by preetikr** [comment]
Fixed and deployed.
