### ISSUE TITLE
Function app not working 

### ISSUE THREAD

**Issue by wolyslager** [Azure/Azure-Sentinel#9571]
**Describe the bug**
Azure function seeing Module not found when deployed via ARM template. When I deploy this via vs-code there is no error. The requirements.txt file is exactly the same in both deployments. cc @v-sudkharat 
```
Result: Failure Exception: ModuleNotFoundError: No module named 'azure.durable_functions'. Please check the requirements.txt file for the missing module. For more info, please refer the troubleshooting guide: https://aka.ms/functions-modulenotfound Stack: File "/azure-functions-host/workers/python/3.8/LINUX/X64/azure_functions_worker/dispatcher.py", line 387, in _handle__function_load_request func = loader.load_function( File "/azure-functions-host/workers/python/3.8/LINUX/X64/azure_functions_worker/utils/wrappers.py", line 48, in call raise extend_exception_message(e, message) File "/azure-functions-host/workers/python/3.8/LINUX/X64/azure_functions_worker/utils/wrappers.py", line 44, in call return func(*args, **kwargs) File "/azure-functions-host/workers/python/3.8/LINUX/X64/azure_functions_worker/loader.py", line 194, in load_function mod = importlib.import_module(fullmodname) File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module return _bootstrap._gcd_import(name[level:], package, level) File "/home/site/wwwroot/SentinelTimerTrigger/__init__.py", line 11, in <module> import azure.durable_functions as df
```

**To Reproduce**

**Expected behavior**
Expect the function app to succeed

**Screenshots**
Requirements.txt file from the ARM deployment function 
<img width="979" alt="image" src="https://github.com/Azure/Azure-Sentinel/assets/29632564/9a2f56a2-ebb4-455c-b8dc-80253ba51111">

error from the invocation details
<img width="1012" alt="image" src="https://github.com/Azure/Azure-Sentinel/assets/29632564/1f14a209-fbad-4cfa-8703-e3e619dc7ae1">

requirements.txt file from the vs-code deployed app 
<img width="962" alt="image" src="https://github.com/Azure/Azure-Sentinel/assets/29632564/0627da9a-446e-4890-b735-4e444708d694">

success from the invocation details

<img width="1102" alt="image" src="https://github.com/Azure/Azure-Sentinel/assets/29632564/ce84c5f3-61e5-4288-8d0b-f8195c949840">

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by v-sudkharat** [comment]
Hi @wolyslager, we have added comment here - https://github.com/Azure/Azure-Sentinel/pull/9572 . 

Thanks!

**Comment by v-sudkharat** [comment]
Hi @wolyslager, we have merged the linked PR for this issue. so, closing this issue. If you still need support for this issue, feel free to re-open it any time. Thank you for your co-operation.
