### ISSUE TITLE
Error when creating and deploying a single HoneyToken to the Keyvault

### ISSUE THREAD

**Issue by plim2282** [Azure/Azure-Sentinel#9577]
I am using the HoneyTokens solution for the Keyvaults and I created the secret in the keyvault. I am at the step where I need to add monitoring in the SOC and I keep getting this error:

{"error":{"code":"NoResponse","message":"The server did not receive a response from an upstream server.

**Comment by plim2282** [comment]
This issue seems to be the same as this:

https://github.com/Azure/Azure-Sentinel/issues/7731

Unfortunately, the solution was not posted in the thread.

**Comment by v-sudkharat** [comment]
Hi @plim2282, Thanks for flagging this issue, we will investigate this issue and get back to you with some updates by 15-12-2023. Thanks!

**Comment by v-muuppugund** [comment]
Hi @plim2282 , Could you please check the in Logic apps HoneyTokensAdd2WLKV is properly configured with service connection
if needed we can have a call for further troubleshooting ,Please share email and convenient slots will have a teams meeting

**Comment by plim2282** [comment]
I have time for a call on weekdays 10am to 5pm eastern time. My email is plim2282@gmail.com

**Comment by v-muuppugund** [comment]
@plim2282 ,Will schedule a call for this issue based on time slots suggested and let you know, Thanks.

**Comment by v-muuppugund** [comment]
Hi @plim2282  Blocked time for tomorrow, please join the meeting.

**Comment by plim2282** [comment]
Great thank you @v-muuppugund

**Comment by v-muuppugund** [comment]
@plim2282 ,as disucssed over teams call,configured the logic app with appropriate params,please let me know if any issues.

**Comment by plim2282** [comment]
@v-muuppugund After our call, I noticed that the api connector disappeared in the logic app

**Comment by v-muuppugund** [comment]
> @v-muuppugund After our call, I noticed that the api connector disappeared in the logic app

@plim2282 ,as we are unable to create new connection in logic due to permissions, told will get back and the remaining logic app configurations are done, we are having connection need to updated, Please let me know if any issues, we can connect on the same teams meeting.

**Comment by v-muuppugund** [comment]
Hi @plim2282 we are closing your issue (https://github.com/Azure/Azure-Sentinel/issues/9577) as resolution provided. If you still need support for this issue, feel free to re-open at any time. Thank you for your co-operation!

**Comment by plim2282** [comment]
@v-muuppugund Can we reopen this ticket? Still having issues creating the connection on the logic app.

**Comment by v-muuppugund** [comment]
Sure @plim2282 ,tried to reach over teams,please suggest time,we can connect,Thanks

**Comment by v-muuppugund** [comment]
Hi @plim2282 we are closing your issue (https://github.com/Azure/Azure-Sentinel/issues/9577) as resolution provided. If you still need support for this issue, feel free to re-open at any time. Thank you for your co-operation!

![image](https://github.com/Azure/Azure-Sentinel/assets/139563098/8d163918-6dca-45ce-9c02-eda844d800db)

**Comment by Lxcyfxr** [comment]
Hello, im currently trying to implement this solution. What was the fix for this Issue now, bacause there are many Issues to this topic but no resolve?
