### ISSUE TITLE
Issue in Cisco Meraki - Block IP Address Playbook

### ISSUE THREAD

**Issue by mlaraibkhan** [Azure/Azure-Sentinel#9578]
**Describe the bug**
I am using the playbook present in the "Solutions/CiscoMeraki/Playbooks/Block-IP-Address", this playbook creates a new rule for every new IP Address. A new rule will be created with the **same rule description** again and again which is completely unnecessary.

The playbook also lacks ability to give your own existing Rule Name in a variable.

Another problem is that it's creating an outbound rule and not inbound. Can we also add this ability to alter rule traffic direction to inbound if need be?

**Expected behaviour**
Append the IP Addresses in the same rule. 

![image](https://github.com/Azure/Azure-Sentinel/assets/24682607/087fc56a-c0dc-4a4d-a884-40fa8e6947c9)

**Comment by v-sudkharat** [comment]
Hi @mlaraibkhan, Thanks for flagging this issue, we will investigate this issue and get back to you with some updates by 18-12-2023. Thanks!

**Comment by v-muuppugund** [comment]
Hi @mlaraibkhan ,I have gone through the play book we are giving the comment in the code and this being passed to put call for cisco Meraki api for updating the fire wall rule i.e. Blocked by play book, second part is in cisco Meraki i.e. In Routed mode, all inbound connections are denied except for ICMP traffic to the appliance, by default. If you want to allow additional inbound traffic, you will need to create a new port forwarding rule or NAT policy and explicitly allow connections based on protocols, ports, or remote IP addresses.

Outbound connections are allowed by default. we may need to add a default deny rule for compliance and increased security.so we are doing the same, please find below articles for reference,
(https://documentation.meraki.com/MX/Firewall_and_Traffic_Shaping/MX_Firewall_Settings)
(https://documentation.meraki.com/General_Administration/Cross-Platform_Content/Layer_3_and_7_Firewall_Processing_Order)

Please let me know if you have any questions on it

**Comment by v-muuppugund** [comment]
Hi @mlaraibkhan ,Gentle reminder,I have gone through the play book we are giving the comment in the code and this being passed to put call for cisco Meraki api for updating the fire wall rule i.e. Blocked by play book, second part is in cisco Meraki i.e. In Routed mode, all inbound connections are denied except for ICMP traffic to the appliance, by default. If you want to allow additional inbound traffic, you will need to create a new port forwarding rule or NAT policy and explicitly allow connections based on protocols, ports, or remote IP addresses.

Outbound connections are allowed by default. we may need to add a default deny rule for compliance and increased security.so we are doing the same, please find below articles for reference,
(https://documentation.meraki.com/MX/Firewall_and_Traffic_Shaping/MX_Firewall_Settings)
(https://documentation.meraki.com/General_Administration/Cross-Platform_Content/Layer_3_and_7_Firewall_Processing_Order)

Please let me know if you have any questions on it

**Comment by v-sudkharat** [comment]
Hi @mlaraibkhan, since we have not received a response in the last 5 days, we are closing your issue- #9579 as per our standard operating procedures. If you still need support for this issue, feel free to re-open at any time. Thank you for your co-operation.
