### ISSUE TITLE
Mimecast Azure function connectors Error 413

### ISSUE THREAD

**Issue by aalhanbali** [Azure/Azure-Sentinel#9584]
**Describe the bug**
I have configured the 4 connectors based on the guide "https://community.mimecast.com/s/article/api-integrations-microsoft-sentinel-integration?_gl=1*14zyeru*_ga*MTIwMzA3NzY5Ny4xNjg3MTgzMjUx*_ga_2RRJFGC554*MTcwMTkzNzQ0Ni4zOS4xLjE3MDE5Mzk2ODEuMzEuMC4w#consolidating_azure_workspaces" but the function app keeps on failing. I keep on checking the Log stream and monitor and I find the below errors:

[Error]   Azure Monitor Collector response code: 413
[Error]   Failed to send Audit logs to Azure Sentinel.

I have recreated the application from Mimecast with no luck. Any idea?

**Screenshots**
![image](https://github.com/Azure/Azure-Sentinel/assets/120581247/5d9000d3-3dd1-4b56-aee6-0f684f39e252)

**Comment by v-sudkharat** [comment]
Hi @aalhanbali, thank you for flagging this issue. This solution's is a supported with Mimecast, we kindly request you to raise an issue ticket with Mimecast's support team.
Sharing the Mimecast mail ID and support link -
Mail Id - "[support@mimecast.com](mailto:support@mimecast.com)"
Link - "https://community.mimecast.com/s/contactsupport"
So, closing this issue. If you still need support for this issue, feel free to re-open it any time. Thank you for your co-operation.
