### ISSUE TITLE
Deployment Error - FortiNet Custom Connector

### ISSUE THREAD

**Issue by swiftsolves-msft** [Azure/Azure-Sentinel#9590]
**Describe the bug**
Fortinet Custom Connector for Playbooks will not deploy results in a swagger API error.

**To Reproduce**
1. Go to Content Hub Solution, install FortiNet FW Solution, got to Automation, and Playbooks (Templates) click on instructions and click on link to deploy Fortinet Custom Connector, deploy in custom deployment UI, deployment starts and swagger error

**Expected behavior**
Custom Connector for Playbooks link should deploy without Swagger error

**Screenshots**
"{"code":"BadRequest","message":"{\"Code\":\"BadRequest\",\"Message\":\"Invalid Api definition object. Please specify a valid Swagger 2.0 Url and valid list of ServiceUrls.\",\"Target\":null,\"Details\":[{\"Message\":\"Invalid Api definition object. Please specify a valid Swagger 2.0 Url and valid list of ServiceUrls.\"},{\"Code\":\"BadRequest\"},{\"ErrorEntity\":{\"ExtendedCode\":\"14012\",\"MessageTemplate\":\"Invalid Api definition object. Please specify a valid Swagger 2.0 Url and valid list of ServiceUrls.\",\"Parameters\":[],\"Code\":\"BadRequest\",\"Message\":\"Invalid Api definition object. Please specify a valid Swagger 2.0 Url and valid list of ServiceUrls.\"}}],\"Innererror\":null}"}"
![image](https://github.com/Azure/Azure-Sentinel/assets/30509195/9d154269-e861-427e-b40e-3fd1f0e69c38)

**Comment by v-sudkharat** [comment]
Hi @swiftsolves-msft, Thanks for flagging this issue, we will investigate this issue and get back to you with some updates by 19-12-2023. Thanks!

**Comment by v-sudkharat** [comment]
Hi @swiftsolves-msft, just want to check, have your **Fortiweb URL** compliance with the below mentioned Prerequisites- 
Link- https://github.com/Azure/Azure-Sentinel/tree/master/Solutions/Fortinet%20FortiWeb%20Cloud%20WAF-as-a-Service%20connector%20for%20Microsoft%20Sentinel/Playbooks/FortiWebCustomConnector

If yes, could you please try to redeploy the custom connector without adding the prefix with https:// or http:// etc. 

![image](https://github.com/Azure/Azure-Sentinel/assets/132428394/a905e5eb-db3e-4a26-8e14-fb3004200a55)

Please let us know if your issue still persists. Thanks!

**Comment by v-sudkharat** [comment]
Hi @swiftsolves-msft, we are waiting for your response on above comment. Thanks!

**Comment by v-sudkharat** [comment]
Hi @swiftsolves-msft, Gentle Reminder: We are waiting for your response on this issue. If you still need to keep this issue active, please respond to it in the next 2 days. If we don't receive a response by 26-12-2023 date, we will be closing this issue. 		
Thanks!

**Comment by v-sudkharat** [comment]
Hi @swiftsolves-msft, since we have not received a response in the last 5 days, we are closing your issue- #9590 as per our standard operating procedures. If you still need support for this issue, feel free to re-open at any time. Thank you for your co-operation.
