### ISSUE TITLE
Unable to deploy github ARM template with conflict error

### ISSUE THREAD

**Issue by Milanthumar** [Azure/Azure-Sentinel#960]
**Describe the bug**
A clear and concise description of what the bug is. : Earlier when i was deploying ARM template i was getting 8 resources (1 Storage account, 1 key vault, 3 playbook, 3 logic app) in total, now using same template but not able to deploy completely and getting conflict error.

**To Reproduce**
1. Go to '...': https://github.com/Azure/Azure-Sentinel/tree/master/DataConnectors/GitHub
2. Click on '....' Deploy to Azure
4. See error : 

**Expected behavior**
A clear and concise description of what you expected to happen. : Same errors after deleting resources and deploying from beggining

**Screenshots**
![image](https://user-images.githubusercontent.com/68587784/90009667-c9fd8500-dc9e-11ea-9576-023022ae333f.png)

**Desktop (please complete the following information):**
 - Browser [e.g. chrome, safari] : Chrome

**Smartphone (please complete the following information):**

**Additional context**

**Comment by dicolanl** [comment]
@Milanthumar 
The deployment uses resource group and subscription to create a random string.  when you delete log a and key vault they are soft deletes.  so the names are still reserved and you can not redeploy using the same name.

Could you create a new resource group and deploy clean there?

**Comment by Milanthumar** [comment]
@dicolanl

Thanks for suggestion it worked after deleting resource group and creating new with different name.

Regards,
Milan Thumar
