### ISSUE TITLE
Cloudflare data connector broke

### ISSUE THREAD

**Issue by philfy20** [Azure/Azure-Sentinel#9601]
cloudflare data connector is broken no longer showing the function in the function app. Have tried a clean deployment and get this error 

'The template parameter 'MaxRunTime' is not found. Please see https://aka.ms/arm-syntax-parameters for usage details.'",

Issue has affected 4 our customers currently using this data connector. Please resolve believe issue is from recent commits 2 weeks ago

**Comment by masterchrister** [comment]
Experiencing the same issue in my end.

**Comment by ingest0x** [comment]
Our Data Connector has also broken - function no longer present within the function app - this is causing us a huge problem.

**Comment by tiagoasousa** [comment]
this PR seems to be at fault https://github.com/Azure/Azure-Sentinel/pull/9518 @v-atulyadav can this be reverted?

**Comment by flatech25** [comment]
Experiencing the same issue ! 

Unable to process template language expressions for resource '/subscriptions/xxxxxxxxxxxxxxxxxxx/resourceGroups/Sentinel_Resource_Group/providers/Microsoft.Web/sites/cloudflareqd2sxr4b4bgr2/config/appsettings' at line '154' and column '17'. 'The template parameter 'MaxRunTime' is not found. Please see https://aka.ms/arm-syntax-parameters for usage details.' (Code: InvalidTemplate)

**Comment by boodoesgh** [comment]
I also have this issue.

**Comment by nathanreevesac3** [comment]
Also present.

**Comment by v-sudkharat** [comment]
Hi @philfy20, Thanks for flagging this issue, we will investigate this issue and get back to you with some updates by 20-12-2023. Thanks!

**Comment by ingest0x** [comment]
FYI I have raised a Severity B support case via the Azure Portal support feature.

**Comment by v-sudkharat** [comment]
@ingest0x, noted. thanks!

**Comment by scottmckenzie** [comment]
Just discovered that we were affected by this change also. You can roll back to the previous version by updating the WEBSITE_RUN_FROM_PACKAGE app setting to https://raw.githubusercontent.com/Azure/Azure-Sentinel/f159b501922a9d396af6047c40fd93095a3f9778/Solutions/Cloudflare/Data%20Connectors/CloudflareConn.zip

**Comment by v-muuppugund** [comment]
@scottmckenzie ,We are analyzing the issue and will get back to you with an update

**Comment by ingest0x** [comment]
thanks @scottmckenzie ! I'll try give that a go today

**Comment by v-sudkharat** [comment]
Hi @scottmckenzie, sharing update with you, we are working on revert the recent changes. Thanks!

**Comment by philfy20** [comment]
any update on the fix?

**Comment by v-sudkharat** [comment]
Hi @philfy20, we are checking this issue with respective author, meanwhile just want to know have you raised the support case ticket with Cloudflare team? 

Thanks!

**Comment by masterchrister** [comment]
> Hi @philfy20, we are checking this issue with respective author, meanwhile just want to know have you raised the support case ticket with Cloudflare team?
> 
> Thanks!

ref support case with Cloudflare "This is owned by Azure, so there is limited action we can take on our side".

**Comment by v-sudkharat** [comment]
@masterchrister, noted thanks!

**Comment by elvischau** [comment]
looks like there is an extra layer of folder inside the package https://aka.ms/sentinel-CloudflareDataConnector-functionapp, that cause the original issue where the connector disappearing from the function app

for the deployment issue, i was able to work around it by adding this piece code into the ARM template between line 10 and 11

        "MaxRunTime": {
            "defaultValue": "10",
            "type": "String"
        },
        "MaximumStorageBlobSize": {
            "defaultValue": "2",
            "type": "String"
        },
        
but that still doesn't resolve the connector disappearing issue

**Comment by v-sudkharat** [comment]
Hi @philfy20, 
We are checking this issue with respective PR author, meanwhile, Could you please follow the below steps and check whether your issue get resolved. 

1, Deploy the below Azure deployment file using Custom Deployment- 
[azuredeploy_Cloudflare_API_FunctionApp.json](https://github.com/Azure/Azure-Sentinel/files/13768948/azuredeploy_Cloudflare_API_FunctionApp.json)

![image](https://github.com/Azure/Azure-Sentinel/assets/132428394/b359c51e-9add-467c-b3ba-218349e48c39)

2. Once deployment get successful check the function app in your workspace or resource group - 

![image](https://github.com/Azure/Azure-Sentinel/assets/132428394/1419b151-5686-4a80-b8d3-9ada6227dcb7)

3. Then go to Configuration option and chick on the edit option of WEBSITE_RUN_FROM_PACKAGE and replace the existing Value with below shared one -

https://github.com/Azure/Azure-Sentinel/raw/v-mchatla/Cloudflare/Solutions/Cloudflare/Data%20Connectors/CloudflareConn.zip

![image](https://github.com/Azure/Azure-Sentinel/assets/132428394/e3ddedcd-1b8c-4ad2-bbde-49313fb0d58d)

![image](https://github.com/Azure/Azure-Sentinel/assets/132428394/88778a7b-8bca-49b8-8215-a3304ea6119a)
![image](https://github.com/Azure/Azure-Sentinel/assets/132428394/216e0d04-6d68-4999-9463-cf17589d0593)

4. Once it gets updated save the changes and restart the function app - 
![image](https://github.com/Azure/Azure-Sentinel/assets/132428394/af66015d-1fe8-4b23-b343-976f5afdb738)
![image](https://github.com/Azure/Azure-Sentinel/assets/132428394/6c98eb3b-e371-4f19-9f14-905a2b1dee66)

Please let us know once your issue gets resolved. 
Thanks!

**Comment by v-sudkharat** [comment]
Hi @philfy20, Could you please have a look on above comment and let us know if your issue get resolved. Thanks!

**Comment by philfy20** [comment]
Updating value  WEBSITE_RUN_FROM_PACKAGE to -
https://github.com/Azure/Azure-Sentinel/raw/v-mchatla/Cloudflare/Solutions/Cloudflare/Data%20Connectors/CloudflareConn.zip works.

Also seems like updating to https://raw.githubusercontent.com/Azure/Azure-Sentinel/f159b501922a9d396af6047c40fd93095a3f9778/Solutions/Cloudflare/Data%20Connectors/CloudflareConn.zip works.

Thanks

**Comment by v-sudkharat** [comment]
@philfy20, Thank you for your confirmation. So, closing this issue. If you still need support for this issue, feel free to re-open it any time. Thank you for your co-operation.

**Comment by egallis31** [comment]
This still appears to be an issue when utilizing WEBSITE_RUN_FROM_PACKAGE as https://aka.ms/sentinel-CloudflareDataConnector-functionapp

When deploying today, the function was "found" but never loaded into the runtime to execute
![image](https://github.com/Azure/Azure-Sentinel/assets/18443524/c9573ee6-a655-4951-8701-3a563b333d92)


The rolled-back release work for WEBSITE_RUN_FROM_PACKAGE as https://raw.githubusercontent.com/Azure/Azure-Sentinel/f159b501922a9d396af6047c40fd93095a3f9778/Solutions/Cloudflare/Data%20Connectors/CloudflareConn.zip

**Comment by beachfires** [comment]
When will the Sentinel connector store version of this be fixed?

**Comment by pir8g33k** [comment]
Any update on CF connector with sentinel, the deployment via sentinel portal still having issue, looking forward to fixed this

**Comment by v-sudkharat** [comment]
Hi @pir8g33k, Apologies for the inconvenience. We are following up with the PR author who made the fix, but as of now, we have not received any response from them. We kindly request you to raise an issue ticket with Cloudflare's support team by sending an email to [support@cloudflare.com](mailto:support@cloudflare.com) or by visiting their support page at https://support.cloudflare.com/.

**Comment by o-l-a-v** [comment]
@v-sudkharat Cloudflare has already said this is not on them, but on Azure?

* https://github.com/Azure/Azure-Sentinel/issues/9601#issuecomment-1864502365

**Comment by v-sudkharat** [comment]
Hi @o-l-a-v, thank you for sharing this update with us. We have shared this information with our team, and they are working on it. Please expect an ETA by 11 Jan 2024.

Thanks!

**Comment by v-sudkharat** [comment]
Hi @o-l-a-v, @pir8g33k, @beachfires, thanks for being connected with us. The fix has been merged and it get reflected into Cloudflare Solution. 

Thanks!

**Comment by pir8g33k** [comment]
> Hi @o-l-a-v, @pir8g33k, @beachfires, thanks for being connected with us. The fix has been merged and it get reflected into Cloudflare Solution.
> 
> Thanks!

Ok Great thanks for the update and looking forward, i was able to redeploy with the solution you provided above, it would be great if the new fixes applied on sentinel portal deployment file

**Comment by beachfires** [comment]
We have not seen the new release yet within Azure Sentinel Content Hub. When will you be releasing it?
