### ISSUE TITLE
Need to automate Azure AD data ingestion towards Azure sentinel

### ISSUE THREAD

**Issue by Milanthumar** [Azure/Azure-Sentinel#961]
**Is your feature request related to a problem? Please describe.**
I can use commands manually and it runs and able to ingest data into sentinel workspace but unable to automate with any option.

**Describe the solution you'd like**
Would like to have some ARM template where i can give certain details and deploy to work as desired.

**Describe alternatives you've considered**
Other solution / option to create logic app / function would be helpful.

**Additional context**
Reference commands:
$MyCredential = Get-Credential
$TenantID = '<TenentID>'
Connect-AzureAD -TenantId $TenantID -Credential $MyCredential
$UserCollected = Get-AzureADUser -All $True
$TotalCount = $UserCollected.count
$customerId = '<WorkspaceID>'
$sharedKey = '<Workspace Key>'
$logType = 'AD_USER_DATA'
For($number = 0; $number -le $TotalCount; $number+=20)
{
$TopNumber = $number+20
$TimeStampfield = Get-date
$JSONUserFormat = ConvertTo-Json $UserCollected[$number..$TopNumber] -Compress -ErrorAction Stop
Send-OMSAPIIngestionFile -customerId $customerId -sharedKey $sharedKey -body $JsonUserFormat -logType $logType -TimeStampField $Timestampfield -Verbose
}

Reference URL: https://techcommunity.microsoft.com/t5/azure-sentinel/enriching-azure-sentinel-with-azure-ad-information/ba-p/1288805

**Comment by ThijsLecomte** [comment]
I think a Logic App is the best solution here to automate this.

Some pointers:
- Use the Graph API to retrieve all user data -  https://docs.microsoft.com/en-us/graph/api/user-list?view=graph-rest-1.0&tabs=http
- Use an app registration with application permissions for this
- Use the integrated Log Analytics step to send data to Log Analytics
- Create an ARM template from your Logic App. Check the details here - https://github.com/Azure/Azure-Sentinel/tree/master/Playbooks

Let me know what else I can do to help!

**Comment by dicolanl** [comment]
@chboeh will look into this.  Likely will be an azure function.

**Comment by MIILLAANN** [comment]
Hi All,

It can be considered as a feature request. we need to automate this activity as it's not formal way of on boarding Enrichment of AD info to sentinel using run manual command.
I Appreciate suggestion but unable to run function with listed commands.

**Comment by trillex** [comment]
Is this still in the pipeline? 

I was pushing projects around to see if I could get to this, but if it is coming as a feature, I might as well wait.

**Comment by sarah-yo** [comment]
Feature available as per above
