### ISSUE TITLE
GoogleWorkspaceReports Data Connector - API start time error

### ISSUE THREAD

**Issue by s-khan14** [Azure/Azure-Sentinel#9617]
**Description**
The recent update to GoogleWorkspaceReport Data Connector has caused function app to fail. The python script uses a start_time and end_time to fetch logs for GoogleWorkspaceAPI. Start_date is based on past_time, that depends on Function App's state. _The function app state is returning unexpected date on first run_.

**To Reproduce**
1. Deploy functionApp for GoogleWorkspaceReports Data Connector from Microsoft Sentinel.
2. After function deployment, open functionApp.
3. Click on function Name **GWorkspaceReportsAPISentinelConnector** 
4. Click **Run/Test**
5. View Error in Monitor tab.
6. Unexpected: The start date can be 1-2 years in the past.

**Expected behavior**
If Function App state returns a date more that 24h in the past, use the default start_time parameter (which is 1 day as of now).

**Error Message**
Something wrong while getting the results. Exception error text: <HttpError 400 when requesting hxxps://admin.googleapis.com/admin/reports/v1/activity/users/all/applications/user_accounts?maxResults=1000&startTime=2022-11-21T20%3A00%3A00.000Z&endTime=2022-11-21T20%3A15%3A00.000000Z&alt=json returned "Invalid request: Start time and end time should be within last 180 days. Start time should be less than end time.". Details: "[{'message': 'Invalid request: Start time and end time should be within last 180 days. Start time should be less than end time.', 'domain': 'global', 'reason': 'invalid'}]">

**Additional context**
* **Location of FunctionApp code**: [Solutions/GoogleWorkspaceReports/Data Connectors/GWorkspaceReportsAPISentinelConnector/__init__.py](https://github.com/Azure/Azure-Sentinel/blob/master/Solutions/GoogleWorkspaceReports/Data%20Connectors/GWorkspaceReportsAPISentinelConnector/__init__.py)
* Currently the Function App uses StateManager to get the past_time: Line 121 on __init__.py
* Suggestion: If the date returned by StateManager is more than 24h, use default start_time and at the end of execution, set the time_stamp using state, which will be used for next run. line 124

**Comment by v-muuppugund** [comment]
Hi @s-khan14 , Thanks for flagging this issue, we will investigate this issue and get back to you with some updates by 19Dec2023. Thanks!

**Comment by v-muuppugund** [comment]
Hi @s-khan14 ,The start time and end time both are same ,so there is an issue,please check the followiing the statemarkerfile share in azure containers
Please follow the steps below
1.Browse to function app application settings and go to storage accounts->Please go to the storage accounts-->Containers->FileShare-->Click on -->funcstatemarkershare->Browse-->Click on ... at the end->Select Edit,Please find below screen shot for reference

![image](https://github.com/Azure/Azure-Sentinel/assets/139563098/455e0d9d-8574-44e8-92c3-008da421b7e9)

2.Please check the delays configured in function app settings as the end time is based on that as there are no default delays configured
![image](https://github.com/Azure/Azure-Sentinel/assets/139563098/593c6c77-a4ed-4df3-b7c5-0cb24efb1a0b)

Please let me know if you have any isuses,if can have a call and do further troubleshooting

**Comment by s-khan14** [comment]
This is the content of **funcstatemarkershare**.

`{"access_transparency": "2023-03-31T10:20:00.000Z", "admin": "2023-12-07T15:34:33.317Z", "calendar": "2023-12-07T10:49:45.310Z", "chat": "2023-12-06T12:20:24.605Z", "drive": "2023-12-06T18:37:39.076Z", "gcp": "2023-03-31T10:20:00.000Z", "gplus": "2023-03-31T10:20:00.000Z", "groups": "2023-12-07T13:33:19.547Z", "groups_enterprise": "2023-12-07T13:33:18.874Z", "jamboard": "2023-03-31T10:20:00.000Z", "login": "2023-12-07T10:58:48.470Z", "meet": "2023-12-07T16:39:50.821Z", "mobile": "2023-03-31T10:20:00.000Z", "rules": "2023-03-31T10:20:00.000Z", "saml": "2023-03-31T10:20:00.000Z", "token": "2023-12-07T16:51:59.220Z", "user_accounts": "2023-12-19T17:10:00.000Z", "context_aware_access": "2023-03-31T10:20:00.000Z", "chrome": "2023-12-07T14:53:47.593Z", "data_studio": "2023-03-31T10:20:00.000Z"}`

Still the function is grabbing timestamps other than this. 

**Suggestion**
Add a check statement to validate timestamps grabbed from state manager. if timestamp do not align or are more than 1d (or normal period) in the past, replace them with default look_back value.

**Why**:

1. In case of current situation, where **statemanager** is returning dates from 2022.
2. What if function didn't run for a long time. The timestamps in state will be expired/not valid for google API.

Note: I was able to solve the problem by doing a manual deployment via VS code - Not from ARM template

**Comment by v-muuppugund** [comment]
Hi @s-khan14 , Sorry to hear this issue, got the issue, but want to have more details, so can proceed with changes,

Want to have these data points based on that will do the changes,Could you please share couple of time slots and email id,so will block the calendar.

**Comment by v-muuppugund** [comment]
@s-khan14  Gentle Reminder,got the issue, but want to have more details, so can proceed with changes,
Want to have these data points based on that will do the changes, Could you please share couple of time slots and email id, so will block the calendar.

**Comment by s-khan14** [comment]
> @s-khan14 Gentle Reminder,got the issue, but want to have more details, so can proceed with changes, Want to have these data points based on that will do the changes, Could you please share couple of time slots and email id, so will block the calendar.

Hi @v-muuppugund, sorry for the delayed response. you can contact me at [this email](mailto:maced73@yahoo.com) and then we can arrange a meeting from there.

**Comment by v-muuppugund** [comment]
Hi @s-khan14 ,I waited for some time in the call today,as you are unable to join will work on changes and share package,please let me know if you have any concern

**Comment by s-khan14** [comment]
Did you add the right email address to the invite? I never got the teams invite. Checked both spam and inbox.

**Comment by v-muuppugund** [comment]
Yes @s-khan14 , I am unable to open this email and asked my collogue to open it and got the email as i.e. [maced73@yahoo.com] (mailto:maced73@yahoo.com), Could you please drop an email to (v-muuppugund@microsoft.com) .

**Comment by v-muuppugund** [comment]
Hi @s-khan14 ,Gentle Reminder,, I am unable to open this email and asked my collogue to open it and got the email as i.e. [[maced73@yahoo.com](mailto:maced73@yahoo.com)] (mailto:maced73@yahoo.com), Could you please drop an email to ([v-muuppugund@microsoft.com](mailto:v-muuppugund@microsoft.com)) .

**Comment by v-muuppugund** [comment]
Hi @s-khan14 , Gentle Reminder,, I am unable to open this email and asked my collogue to open it and got the email as i.e. [[maced73@yahoo.com](mailto:maced73@yahoo.com)] (mailto:maced73@yahoo.com), Could you please drop an email to ([v-muuppugund@microsoft.com](mailto:v-muuppugund@microsoft.com)) .
