### ISSUE TITLE
Checking wrong list in query

### ISSUE THREAD

**Issue by bittib010** [Azure/Azure-Sentinel#9630]
**Describe the bug**
The Scheduled rule with GUID 957cb240-f45d-4491-9ba5-93430a3c08be stores the IP as ClientIPOnly, but looks at a nested list [0][0]. At our place, this is constantly wrong, and should only be:

![image](https://github.com/Azure/Azure-Sentinel/assets/77796831/e43ae9da-ee22-4951-88b9-e7ef4385d7b7)

Hopefully this will help others as well - I could not find any entries in our logs where this value actually works. We use this column in a title override, but keep getting blank on the IP.

**Comment by v-muuppugund** [comment]
Hi @bittib010 , Thanks for flagging this issue, we will investigate this issue and get back to you with some updates by 25Dec2023. Thanks!

**Comment by v-sudkharat** [comment]
Hi @bittib010, team is still checking on this issue and get back you by - 29-12-2023. Thanks!

**Comment by v-muuppugund** [comment]
Hi @bittib010 ,Could you please share more details on this issue,which solution and what wrong query?

**Comment by bittib010** [comment]
Here is the query: https://github.com/Azure/Azure-Sentinel/blob/e99fa2b06eacbbe3e5865f77b8626ba20919e269/Solutions/Microsoft%20365/Analytic%20Rules/RareOfficeOperations.yaml#L4

And looking at the query, like my original post here, showing the query and where it is looking into nested lists, in our dataset we never get a nested list, and therefore by looking at something that does not exist, we get an empty value:
![image](https://github.com/Azure/Azure-Sentinel/assets/77796831/71c06747-4127-4cb4-93a5-3c67cc44f1a4)

Therefore we would like to see if changing it to (end of line 4):

```
  OfficeActivity
  | where Operation in~ ( "Add-MailboxPermission", "Add-MailboxFolderPermission", "Set-Mailbox", "New-ManagementRoleAssignment", "New-InboxRule", "Set-InboxRule", "Set-TransportRule")
  and not(UserId has_any ('NT AUTHORITY\\SYSTEM (Microsoft.Exchange.ServiceHost)', 'NT AUTHORITY\\SYSTEM (w3wp)', 'devilfish-applicationaccount') and Operation in~ ( "Add-MailboxPermission", "Set-Mailbox"))
  | extend ClientIPOnly = tostring(extract_all(@'\[?(::ffff:)?(?P<IPAddress>(\d+\.\d+\.\d+\.\d+)|[^\]]+)\]?', dynamic(["IPAddress"]), ClientIP)[0])
  | extend AccountName = tostring(split(UserId, "@")[0]), AccountUPNSuffix = tostring(split(UserId, "@")[1])
```

**Comment by v-muuppugund** [comment]
Hi @bittib010 ,I am able to replicate the issue and have only 3 records in our work space,Please find below screen shot for reference
![image](https://github.com/Azure/Azure-Sentinel/assets/139563098/4bfe4b1e-78ab-4d07-b501-0d2ff9f080f8)

Could you please share sample data in CSV format to (v-muuppugund@microsoft.com),so will be modify the analytic rule and update you

**Comment by v-muuppugund** [comment]
Hi @bittib010 ,Gentle Reminder,,I am able to replicate the issue and have only 3 records in our work space,Please find below screen shot for reference
![image](https://github.com/Azure/Azure-Sentinel/assets/139563098/37f6be46-247f-4fd5-84c6-17b7af9fd984)

Could you please share sample data in CSV format to ([v-muuppugund@microsoft.com](mailto:v-muuppugund@microsoft.com)),so will be modify the analytic rule and update you

**Comment by bittib010** [comment]
I'm sorry, im not able to do so in a while. I hoped you would get the same output as we did, but that shows only that there are differences in the data outputting. I'm currently unavailable to produce any dummy data for the next two weeks as I'm logged off main computer.

**Comment by v-muuppugund** [comment]
Hi @bittib010 , Working on the changes ,will be raising PR for the same.

**Comment by v-sudkharat** [comment]
Hi @bittib010, Team is still working on changes, and will raise a PR once it gets completed. Thanks!

**Comment by v-muuppugund** [comment]
Hi @bittib010 , Apologies for the delayed response, its a 1p connector, made the changes tested it, need to push it as don't have permissions as the connector is not reflecting Will update you.

**Comment by v-muuppugund** [comment]
Hi @bittib010 ,just want update,as its 1p connector,we are discussing internally process to push it and will update you once had an update

**Comment by v-muuppugund** [comment]
Hi @bittib010 ,we have defined the process internally and will be working on the PR,will update you once PR is pushed

**Comment by v-muuppugund** [comment]
Hi @bittib010 ,PR has merged,so we are closing the issue.
