### ISSUE TITLE
Inconsistent CSV Export Log Analytics Workspaces

### ISSUE THREAD

**Issue by jeffrywu28** [Azure/Azure-Sentinel#9634]
**Describe the bug**
When I Export the SecurityEvent result, i got bad result that i must to doing manual cleansing. i want the .csv data is consistent. that was really bad and takes so many times especially my data is BIG. thankyou!

**To Reproduce**
1. Go to Sentinel
2. Click on Log Analytics Query
3. Query the SecurityEvents then Export all column

**Expected behavior**
A consistent .csv value

**Screenshots**
<img width="904" alt="image" src="https://github.com/Azure/Azure-Sentinel/assets/47622164/8fb6d751-4580-4ab2-b197-54a047962842">

**Comment by v-muuppugund** [comment]
Hi @jeffrywu28 ,Thanks for flagging this issue, we will investigate this issue and get back 	to you with some updates by 25Dec2023. Thanks!

**Comment by v-sudkharat** [comment]
Hi @jeffrywu28, team is still checking on this issue, once analysis is done will share update with you. Thanks!

**Comment by v-sudkharat** [comment]
Hi @jeffrywu28, Hope you are doing well. We have checked this issue; This issue needs to be further investigation by our support team so could you please create a support case for this issue so the support team can connect with you to get more details that are needed about the problem and assist you in fixing it.
As of now we are closing this issue from GitHub. If you still need support for this issue, feel free to re-open it any time. Thank you for your co-operation.
