### ISSUE TITLE
 Function App Execution Error: Parsing Issue with Azure Sentinel Template

### ISSUE THREAD

**Issue by cryanskl** [Azure/Azure-Sentinel#9636]
**Describe the bug**
One of our clients has created a function app using this template (https://github.com/Azure/Azure-Sentinel/tree/master/Solutions/Fortinet%20FortiGate%20Next-Generation%20Firewall%20connector%20for%20Microsoft%20Sentinel/Playbooks/FortinetFortigateFunctionApp).

The customer is using this project to configure a playbook in Sentinel for automating the Function app. However, when the client executes it, they encounter the same error as the previous issue (https://github.com/Azure/Azure-Sentinel/issues/2874): "Unexpected character encountered while parsing value: <. Path '', line 0, position 0."

**To Reproduce**
You could take the same action in 'To Reproduce' section in https://github.com/Azure/Azure-Sentinel/issues/2874.

**Expected behavior**
Function could execute successfully and the logic app can complete.

**Screenshots**
![image](https://github.com/Azure/Azure-Sentinel/assets/34471145/cb315086-b4a4-46fb-a0a6-6110b80bbdd9)
![image](https://github.com/Azure/Azure-Sentinel/assets/34471145/1c6025dd-fcdc-43ff-8c70-6ba6288d6ab4)

**Additional context**
1.We have used two templates, but the function app runtime version created by both templates is 3.20. However, version 3.20 has not been supported by Azure since December last year, so I would like to know if you have any new templates similar to 'https://github.com/Azure/Azure-Sentinel/tree/master/Solutions/Fortinet%20FortiGate%20Next-Generation%20Firewall%20connector%20for%20Microsoft%20Sentinel/Playbooks/FortinetFortigateFunctionApp'.
2.Our coding capabilities are limited, so we cannot rewrite as mentioned by scottbrien01 in the previous issue. Could you please help us modify the relevant code in the github template or kindly guide us how to change it?

Thanks in advance!

**Comment by cryanskl** [comment]
Hi team, Merry Christmas! May I kindly inquire if there are any updates? Looking forward to hearing from you at your earliest convenience.

**Comment by v-sudkharat** [comment]
Hi @cryanskl, Merry Christmas!, team still checking on this issue, and will share an update you by - 29-12-2023. Thanks!

**Comment by cryanskl** [comment]
Hi @v-sudkharat, thank you for your prompt response! Looking forward to hearing from you at your earliest convenience.

**Comment by v-muuppugund** [comment]
Hi @cryanskl ,I tried check the existing ARM template and its not behaving expected,Please find below screen shot for reference
![image](https://github.com/Azure/Azure-Sentinel/assets/139563098/8e109a90-6128-49ad-a812-1eb5b4cea804)
![image](https://github.com/Azure/Azure-Sentinel/assets/139563098/b09d90d3-eca1-4bb6-889d-c6421439982d)


Could you please share your requirement in detail, want to pass the Authorization with Bearer token?

**Comment by v-muuppugund** [comment]
Hi @cryanskl ,Gentle reminder,Could you please share your requirement in detail, want to pass the Authorization with Bearer token?,so will proceed with the changes.

**Comment by v-muuppugund** [comment]
Hi @cryanskl ,Since we have not received a response in the last 5 days, we are closing your issue (https://github.com/Azure/Azure-Sentinel/issues/9636) as per our standard operating procedures. If you still need support for 	this issue, feel free to re-open at any time. Thank you for your co-operation!
