### ISSUE TITLE
It is not possible to deploy Reset-AADUserPassword

### ISSUE THREAD

**Issue by wesleyfrancof** [Azure/Azure-Sentinel#9643]
It is not possible to deploy, 

1. Go to 'https://github.com/Azure/Azure-Sentinel/tree/master/Solutions/Microsoft%20Entra%20ID/Playbooks/Reset-AADUserPassword'
2. Click on Deploy to azure

When the deploy button was created the Playbook path was: 
Solutions/Azure Active Directory/Playbooks/Reset-AADUserPassword/incident-trigger/azuredeploy.json

and now it is:
Solutions/Microsoft Enter ID/Playbooks/Reset-AADUserPassword/incident-trigger/azuredeploy.json

**Comment by v-muuppugund** [comment]
Hi @wesleyfrancof , Thanks for flagging this issue, we will investigate this issue and get back to you with some updates by 25Dec2023. Thanks!

**Comment by v-sudkharat** [comment]
Hi @wesleyfrancof, we are working on the correction in file path. Meanwhile could you please try to deploy that playbook using solution installation. 
![image](https://github.com/Azure/Azure-Sentinel/assets/132428394/7f53142e-840e-4ceb-ad77-f7833cc2f9c9)

Thanks!

**Comment by v-sudkharat** [comment]
Hi @wesleyfrancof, We have raised the PR with changes, the changes get reflected, once PR is merge. Thanks!
