### ISSUE TITLE
PP Inventory data connector broken

### ISSUE THREAD

**Issue by philfy20** [Azure/Azure-Sentinel#9657]
The function app related to data connector https://github.com/Azure/Azure-Sentinel/tree/master/DataConnectors/PPInventory has broke. Issue started since the last commit https://github.com/Azure/Azure-Sentinel/commit/0d1e6b67d5a4a84de1417355dc352724d496acb7

The function app now shows no functions in the app. 

I have tried to update WEBSITE_RUN_FROM_PACKAGE to an older version https://raw.githubusercontent.com/Azure/Azure-Sentinel/68e6252d29cd74ec2ce323131ae29d05a2f420ed/DataConnectors/PPInventory/ppinventoryfunction.zip however issue still occurring.

**Comment by v-muuppugund** [comment]
Hi @philfy20 , Thanks for flagging this issue, we will investigate this issue and get back to you with some updates by 27Dec2023. Thanks!

**Comment by v-muuppugund** [comment]
Hi @philfy20 ,Able to replicate the issue, Still need some time for local debugging and checking the package,will update you.

**Comment by v-muuppugund** [comment]
Hi @philfy20 ,In the earlier analysis i have just pointed the web site run from a package to a different function app,but requires different configurations,so the commit mentioned in the issue description is part of arm template changes and is it a fresh deployment?

**Comment by philfy20** [comment]
This issue I am having is with an existing function app that has been running fine for a few months until the last commit https://github.com/Azure/Azure-Sentinel/commit/0d1e6b67d5a4a84de1417355dc352724d496acb7

**Comment by v-muuppugund** [comment]
Hi @philfy20 ,we are reaching out to the concerned team for this issue, once we receive an update on this, we will update you by 12Jan2024 . Thanks!

**Comment by v-muuppugund** [comment]
Hi @philfy20 ,Could you please check the PP inventory function app  under configuration settings pointing the **"WEBSITE_RUN_FROM_PACKAGE"** value as **"https://aka.ms/sentinel-ppinventory-functionapp"**,if its pointing,please point this url and restart the function,please let us know if any issues.

**Comment by philfy20** [comment]
@v-muuppugund I have updated as per your request
<img width="895" alt="image" src="https://github.com/Azure/Azure-Sentinel/assets/91515482/a1b3f9f1-79c2-4a4b-9afc-574e05039960">
However still no function showing
<img width="969" alt="image" src="https://github.com/Azure/Azure-Sentinel/assets/91515482/1a767d75-902d-4b0e-8b8b-d317929d819c">

**Comment by v-sudkharat** [comment]
Hi @philfy20, thanks for your response on this. As per response from our concern team, the function app you are deploying using standalone GitHub repo path is already a part of a solution which is -` Microsoft Power Platform`, and team has place that function app source code in repo as alternative. 
So, to address your issue we are sharing below steps, please try to deploy function app using below steps and let us know if your issue gets resolved.  

1st - Please deploy the function app using below deployment link and fill your correct details on it -  
Link - https://aka.ms/sentinel-ppinventory-azuredeploy

Once it gets successfully deployed, you will get the function app in overview tab: -
![image](https://github.com/Azure/Azure-Sentinel/assets/132428394/843b8d95-a39f-4246-bd85-d64921e8dc9c)

2nd - Using `Microsoft Power Platform` solution. You have to install this solution from Content Hub and deploy the below highlighted function app from there: - 

![image](https://github.com/Azure/Azure-Sentinel/assets/132428394/0627a25f-9a60-4166-8e13-396eef931003)


Kindly let us know your valuable feedback on this.
Thanks!

**Comment by v-muuppugund** [comment]
Hi @philfy20 ,Gentle reminder, Could you please check on the above steps and let us know if any issues.

**Comment by philfy20** [comment]
@v-muuppugund wasn't as straight forward as we though but its now working. Had to delete all the resources and permissions related to this function app and the function app itself to start from scratch. After a fresh deployment and following the above the function app is working again. thanks,

**Comment by v-muuppugund** [comment]
@philfy20 ,we are closing your issue as issue has been resolved (https://github.com/Azure/Azure-Sentinel/issues/9657) as per our standard operating procedures. If you still need support for 	this issue, feel free to re-open at any time. Thank you for your co-operation!
