### ISSUE TITLE
How to integrate Azure sentinel with Servicenow for incident creation

### ISSUE THREAD

**Issue by ushahn** [Azure/Azure-Sentinel#968]
How can we automate incident creation in service now if there are any new alerts triggered in Azure sentinel

**Comment by dicolanl** [comment]
Hi @ushahn 

@Yaniv-Shasha  created a playbook https://github.com/Azure/Azure-Sentinel/tree/master/Playbooks/Open-SNOW-Ticket that opens a SNOW ticket.  you just need to set the analytic rule to trigger this playbook.
