### ISSUE TITLE
Tenable.io Vulnerability Management log trimming issue

### ISSUE THREAD

**Issue by Andy298** [Azure/Azure-Sentinel#9705]
We've connected the Tenable.io Vulnerability Management (using Azure Function) data connector, however we're seeing the following attached LAW operational error on a daily basis.

**_The following fields' values output of type Tenable_IO_Vuln_CL have been trimmed to the max allowed size, 32766 bytes. Please adjust your input accordingly. (1)_**

![image](https://github.com/Azure/Azure-Sentinel/assets/26548347/c06a9942-e40d-4ea4-8f21-01bbf3c29e43)

**Comment by v-sudkharat** [comment]
Hi @Andy298, Thanks for flagging this issue, we will investigate this issue and get back to you with some updates by 09-01-2024 Thanks!

**Comment by v-sudkharat** [comment]
Hi @Andy298, there can be more amount of data on your selected time range. so could you please select it for 24 hr and check whether you are getting same warning message on it - 

![image](https://github.com/Azure/Azure-Sentinel/assets/132428394/ee7b4f78-d3f8-4745-9968-bb8819e066c1)

Thanks!

**Comment by Andy298** [comment]
@v-sudkharat hi there. Nope, still the same message sorry.

![image](https://github.com/Azure/Azure-Sentinel/assets/26548347/c8d10f5f-a2aa-4c33-b593-e5af29a92daf)

**Comment by v-sudkharat** [comment]
@Andy298, thanks for your response. we will check on it and get back to you by - 12-01-2024. 
Thanks!

**Comment by v-sudkharat** [comment]
Hi @Andy298, I hope you are doing well. This issue requires further investigation, so we have checked the solution and found that, this solution is supported by Tenable, which is partner-supported. As of now, we are not authorized. We kindly request that you raise a support ticket with the Tenable support team.
Sharing the Tenable support link -
https://www.tenable.com/support/technical-support
so, closing this issue from GitHub. If you still need support for this issue, feel free to re-open it any time. Thank you for your co-operation.
