### ISSUE TITLE
Github Security workbook - 'where' operator: Failed to resolve scalar expression named 'commit_oid_s'

### ISSUE THREAD

**Issue by kborowiec-mag** [Azure/Azure-Sentinel#9710]
**Describe the bug**
"Advanced Security Overvivew" tab returns following status:

![image](https://github.com/Azure/Azure-Sentinel/assets/116068264/ef7a82d0-0089-40c8-bf34-fc7b878b5460)

Other tab like "Dependabot Alerts" returns result correctly

**To Reproduce**
1. [Configure Github Webhook Connector](https://github.com/Azure/Azure-Sentinel/tree/master/Solutions/GitHub/Data%20Connectors/GithubWebhook)
2. Wait until GHAS data are propagated to githubscanaudit_CL
3. Go to Sentinel "Github Security" workbook

**Expected behavior**
Workbook generates proper reports

**Screenshots**
![image](https://github.com/Azure/Azure-Sentinel/assets/116068264/ef7a82d0-0089-40c8-bf34-fc7b878b5460)

**Comment by kborowiec-mag** [comment]
I have enabled CodeQL Analysis and found that "Code Scanning Alerts" also returns errors:

![image](https://github.com/Azure/Azure-Sentinel/assets/116068264/251d77b3-553b-49c1-b295-2e3ea8294cfa)

but "Secret Scanning Alerts" and "Dependabot Alerts" tabs are working fine.

**Comment by v-sudkharat** [comment]
Hi @kborowiec-mag, Thanks for flagging this issue, we will investigate this issue and get back to you with some updates by 08-01-2024. Thanks!

**Comment by kborowiec-mag** [comment]
After enabling CodeQL Analysis and running a code scan - "commit_oid_s" appeared in githubscanaudit_CL and problem disappeared. 

Looks like having CodeQL enabled is crucial to have "Advanced Security Overview" tab working.

**Comment by v-sudkharat** [comment]
Hi @kborowiec-mag, thank you for closing this issue. if you still need support for this issue, feel free to re-open it any time. Thank you for your co-operation.
