### ISSUE TITLE
Cloudflare (Preview) (using Azure Functions)

### ISSUE THREAD

**Issue by javbux** [Azure/Azure-Sentinel#9711]
**Describe the bug**
The function app is no longer working.

LogPush from Cloudflare is still working and populating my storage account.
The Cloudflare Function app is failing to take these logs and ingest into Log Analytics

Looking back through FunctionAppLogs it appears to have stopped working on 12th December sometime after 11:15 UK time

**To Reproduce**
n/a

**Expected behavior**
Cloudflare Function app should be taking files from storage account and uploading into Log Analytics

**Screenshots**
Screenshot showing the function being found on the 11th Dec
![image](https://github.com/Azure/Azure-Sentinel/assets/147181330/22c6578b-5fb2-40f3-bb24-92b6c1425e7d)

Screenshot showing no functions found on the 12th Dec
![image](https://github.com/Azure/Azure-Sentinel/assets/147181330/0cf363b1-de8a-42f7-a42e-285e7d46bbc0)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Edge
 - Version: 120

**Smartphone (please complete the following information):**
n/a

**Additional context**
When I look at the function App blade, it doesn't have any functions associated with it anymore, which is probably the issue

**Comment by v-sudkharat** [comment]
Hi @javbux , Thanks for flagging this issue, we will investigate this issue and get back to you with some updates by 08-01-2024. Thanks!

**Comment by v-sudkharat** [comment]
Hi @javbux, We have checked this solution, this solution is supported with Cloudflare, we kindly request you to raise an issue ticket with Cloudflare's support team.
Sharing the Cloudflare mail ID and link -
Mail Id - "[support@cloudflare.com](mailto:support@cloudflare.com)"
Link - "https://support.cloudflare.com/"
Additionally, to unblock you from this issue we are sharing below steps from our end - 
so, Could you please follow the below steps and check whether your issue get resolved. 

1, Deploy the below Azure deployment file using Custom Deployment- 
[azuredeploy_Cloudflare_API_FunctionApp.json](https://github.com/Azure/Azure-Sentinel/files/13768948/azuredeploy_Cloudflare_API_FunctionApp.json)

![image](https://github.com/Azure/Azure-Sentinel/assets/132428394/b359c51e-9add-467c-b3ba-218349e48c39)

2. Once deployment get successful check the function app in your workspace or resource group - 

![image](https://github.com/Azure/Azure-Sentinel/assets/132428394/1419b151-5686-4a80-b8d3-9ada6227dcb7)

3. Then go to Configuration option and chick on the edit option of WEBSITE_RUN_FROM_PACKAGE and replace the existing Value with below shared one -

https://github.com/Azure/Azure-Sentinel/raw/v-mchatla/Cloudflare/Solutions/Cloudflare/Data%20Connectors/CloudflareConn.zip

![image](https://github.com/Azure/Azure-Sentinel/assets/132428394/e3ddedcd-1b8c-4ad2-bbde-49313fb0d58d)

![image](https://github.com/Azure/Azure-Sentinel/assets/132428394/88778a7b-8bca-49b8-8215-a3304ea6119a)
![image](https://github.com/Azure/Azure-Sentinel/assets/132428394/216e0d04-6d68-4999-9463-cf17589d0593)

4. Once it gets updated save the changes and restart the function app - 
![image](https://github.com/Azure/Azure-Sentinel/assets/132428394/af66015d-1fe8-4b23-b343-976f5afdb738)
![image](https://github.com/Azure/Azure-Sentinel/assets/132428394/6c98eb3b-e371-4f19-9f14-905a2b1dee66)

So, Closing this issue from GitHub. If you still need support for this issue, feel free to re-open it any time. Thank you for your co-operation.
Thanks!

**Comment by javbux** [comment]
Thank you @v-sudkharat that URL for WEBSITE_RUN_FROM_PACKAGE has addressed my issue.
I didn't think to check back through Closed calls as for me it was an Open Issue
