### ISSUE TITLE
Cloudflare (Preview) (using Azure Functions) - ARM template

### ISSUE THREAD

**Issue by javbux** [Azure/Azure-Sentinel#9712]
**Describe the bug**
ARM template is failing to run for this data connector
After completing all necessary fields and proceed to review and create...

The deployment partially runs successfully but fails stating template parameter  _MaxRunTime_ is not found.
After further troubleshooting, I found _MaximumStorageBlobSize_ paramater is also missing.

NOTE: Once I modified the template and added these missing parameters and re-ran the deployment it was successful

**To Reproduce**
1. Visit ContentHub, search for Cloudflare and install
2. Once installed, choose **Manage**
3. Look for **Cloudflare (Preview) (using Azure Functions)** and click on **"1 item"**
4. Under Step 2, Option 1, click on the **Deploy to Azure** button
5. Fill in the project details and Instance details as required, then choose **Next**
6. Validation passes, and now click on **Create** button
7. Should see deployment partially running successfully, then fail, citing MaxRunTime as the issue

**Expected behavior**
I have previously run this so know it used to work and it does work if I add in the missing parameters.
It should complete successfully, creating a Function App, a storage account, Application Insight, App Service plan, Smart detector alert rule

**Screenshots**
![image](https://github.com/Azure/Azure-Sentinel/assets/147181330/150c21cb-9a46-4be7-9ef0-dd98425e84c7)

**Desktop (please complete the following information):**
 - OS: Window
 - Browser: Edge
 - Version: 120

**Smartphone (please complete the following information):**
n/a

**Additional context**
I only found this out as I removed the Solution to troubleshoot another issue with Cloudflare Function app I have also reported under 
#9711

**Comment by v-sudkharat** [comment]
Hi @javbux, Thanks for flagging this issue, we will investigate this issue and get back to you with some updates by 08-01-2024. Thanks!

**Comment by v-sudkharat** [comment]
Hi @javbux, Please follow the step's which we provided in below comment - 
https://github.com/Azure/Azure-Sentinel/issues/9711#issuecomment-1878315365
Closing this issue from GitHub. If you still need support for this issue, feel free to re-open it any time. Thank you for your co-operation.
