### ISSUE TITLE
Intro to KQL

### ISSUE THREAD

**Issue by janmigs1** [Azure/Azure-Sentinel#9728]
Need help with using the Intro to KQL workbook. Please guide me where to start.

![image](https://github.com/Azure/Azure-Sentinel/assets/96889496/52d57471-edca-4c65-a420-3f3288770188)

**Comment by v-muuppugund** [comment]
Hi @janmigs1 ,Could you please share more details,which work book you are looking for ? in which solution ,Please share more details,so will proceed further on this issue.

**Comment by v-sudkharat** [comment]
Hii @janmigs1, We happy to assist you on this issue. Please follow below steps and let us know once you get the option's in Selection Tab. 
1. Download the below shared workbook json template - 
[IntrotoKQL.json](https://github.com/Azure/Azure-Sentinel/files/13887025/IntrotoKQL.json)

2. Click on Advance edit option in workbook, which highlighted in below screenshot -
![image](https://github.com/Azure/Azure-Sentinel/assets/132428394/d72fb516-d1cf-43ca-9905-7fd89b2d21a7)
 
3. Now copy the content which you downloaded from step 1. and past over there. Once you past it click on apply - 
![image](https://github.com/Azure/Azure-Sentinel/assets/132428394/e9971e9d-ed82-4a07-bd7f-75bc7ce490d4)

4. Now click on Done editing Option - 
![image](https://github.com/Azure/Azure-Sentinel/assets/132428394/c42be189-6885-4eea-b733-617ff9b01ffc)

5. It take few seconds to load the content, once it gets done Go to Overview tab and you are ready to select from Sections- 
![image](https://github.com/Azure/Azure-Sentinel/assets/132428394/e35f7bb2-d945-4815-a092-3e6da4945157)

I hope above steps will help you. 

Thanks!

**Comment by v-sudkharat** [comment]
Hi @janmigs1, Gentle Reminder: We are waiting for your response on this issue. If you still need to keep this issue active, please respond to it in the next 2 days. If we don't receive a response by 16-01-2024 date, we will be closing this issue. 		
Thanks!

**Comment by v-sudkharat** [comment]
Hi @janmigs1, since we have not received a response in the last 5 days, we are closing your issue #9728 as per our standard operating procedures. If you still need support for this issue, feel free to re-open at any time. Thank you for your co-operation.

**Comment by DeanGross144** [comment]
Thanks, these instructions fixed this problem for me
