### ISSUE TITLE
Issue with parser for CISCO ISE in Sentinel

### ISSUE THREAD

**Issue by v-nguyentruong** [Azure/Azure-Sentinel#9746]
**Describe the bug**
Parsing issue with Cisco ISE data source
Using the parser from the Cisco Identity Service Engine data connector page in Sentinel provide and still got wrong information in the logs.
I found out that the parser will apply for these logs:
Syslog
    | where ProcessName has_any  ("CSCO", "CISE")
There are many logs with different structures of SyslogMessage which causes the parser to not be able to function properly.
When applied this line in parser for the above results, there will be an eventid with a date (Ex 1: 2024-01-05) and an eventid with a string (Ex 2: NetworkDeviceGroups...).
| parse SyslogMessage with * " " * " " * " " EventId " " EventSeverity " " EventCategory " " RestOfMessage

**To Reproduce**
1. Go to Sentinel portal > Data Connectors > Cisco Identity Service Engine
2. Click on "Follow these steps"
3. Copy the function code then paste into Logs then Save as function.
4. See wrong information in CiscoISEEvent table.

**Expected behavior**
Correct data from Syslog parse into the correct field in CiscoISEEvent table.

**Screenshots**

**Comment by v-sudkharat** [comment]
Hi @v-nguyentruong, Thanks for flagging this issue, we will investigate this issue and get back to you with some updates by 15-01-2024. Thanks!

**Comment by v-sudkharat** [comment]
Hi @v-nguyentruong, Could you please check with below shared parser file. 
[CiscoISEParser_Updated3.txt](https://github.com/Azure/Azure-Sentinel/files/13918064/CiscoISEParser_Updated3.txt)

**Sharing the steps to configure it -** 
1. Go to Log Analytics workspace and select your workspace.
2. Click on Logs.
In the Schema and Filter Pane, select Functions tab and enter Parser name (e.g. CiscoISE) in the search box, function list would be filtered.
4. Hover over the function name and click on Load the function code link in the flyout.
5. This would load the definition of the parser in the new query window. Copy and paste the content of the function in a notepad and save it.

Please let us know if it works or you need any assistance on it. 
Thanks!

**Comment by v-sudkharat** [comment]
Hi @v-nguyentruong, we are waiting for your response on above comment. Thanks!

**Comment by v-nguyentruong** [comment]
Hi @Sudarshan Kharat (Tata Consultancy Services ***@***.***>

Thanks for your response.

I'm still checking this parser on customer environment. I'm still waiting for the customer to send a reply. I will update you if I get any response.


Best Regards,


Nelson Truong

Support Engineer

Azure - Security

Working Hours: 3:00 PM - 12:00 AM (UTC+7, Monday to Friday)

Need help outside of my working hours?

Locate an engineer: ***@***.******@***.***>

Manager: Olivia Li/ ***@***.***

[image]

________________________________

**Comment by v-sudkharat** [comment]
Hi @v-nguyentruong, Please let us know once you get update from customer on this. Thanks!

**Comment by v-sudkharat** [comment]
Hi @v-nguyentruong, Any update from customer on this? Thanks!

**Comment by v-sudkharat** [comment]
Hi @v-nguyentruong, thanks for sharing update with us, please let us know, once you get more update from customer on this. 
Thanks!

**Comment by v-nguyentruong** [comment]
Hi @Sudarshan Kharat (Tata Consultancy Services ***@***.***>

Hope you doing well

Just got a response from customer. Everything is working fine except there is no timestamp this time (No TimeGenerated column). Can you check the parser again?
Here is the screenshots from customer:
[cid:7389d18d-085f-46d0-a6f5-0c2bc3d9738c]

Thanks for your response.

I'm still checking this parser on customer environment. I'm still waiting for the customer to send a reply. I will update you if I get any response.


Best Regards,

 

Nelson Truong

Support Engineer

Azure - Security

Working Hours: 3:00 PM - 12:00 AM (UTC+7, Monday to Friday)

Need help outside of my working hours?

Locate an engineer: ***@***.******@***.***>

Manager: Olivia Li/ ***@***.***

[image]

________________________________

**Comment by v-sudkharat** [comment]
Hi @v-nguyentruong, your shared screenshot is not visible for me, could you please reshare it. Thanks!

**Comment by v-nguyentruong** [comment]
Hi @Sudarshan Kharat (Tata Consultancy Services ***@***.***>

Here is the screenshot:
[cid:accc5ade-4b7a-41a1-ba4e-116e5b4ce74e]


Best Regards,

 

Nelson Truong

Support Engineer

Azure - Security

Working Hours: 3:00 PM - 12:00 AM (UTC+7, Monday to Friday)

Need help outside of my working hours?

Locate an engineer: ***@***.******@***.***>

Manager: Olivia Li/ ***@***.***

[image]

________________________________

**Comment by v-sudkharat** [comment]
Hi @v-nguyentruong, still not visible, Could you please sent it on below mail id - v-sudkharat@microsoft.com
![image](https://github.com/Azure/Azure-Sentinel/assets/132428394/432b654d-4515-47a0-8b69-031f87fd7722)

Thanks!

**Comment by v-nguyentruong** [comment]
Hi @Sudarshan Kharat (Tata Consultancy Services ***@***.***>

I just sent the screenshot to your email. Can you check it if it is visible?


Best Regards,

 

Nelson Truong

Support Engineer

Azure - Security

Working Hours: 3:00 PM - 12:00 AM (UTC+7, Monday to Friday)

Need help outside of my working hours?

Locate an engineer: ***@***.******@***.***>

Manager: Olivia Li/ ***@***.***

[image]

________________________________

**Comment by v-sudkharat** [comment]
Hi @v-nguyentruoy - ng, yes, it's visible now. We will check on it and get back to you by 07-01-2024. Thanks!

**Comment by v-sudkharat** [comment]
Hi @v-nguyentruong, could you please ask customer to expand the one of the raw and check for the TimeGenerated Column. 
![image](https://github.com/Azure/Azure-Sentinel/assets/132428394/9c136c2d-7bb9-45f3-9d54-39c58111d444)
Thanks!

**Comment by v-nguyentruong** [comment]
Hi @Sudarshan Kharat (Tata Consultancy Services ***@***.***>

I checked from our end and the raw doesn't have any TimeGenerated Column. Here is the screenshots:
[cid:b433c2c1-5e48-48aa-b347-ad1832b63c49]
[cid:9bfa16f6-dd57-4612-8a11-34ebf2e23f7e]



Best Regards,

 

Nelson Truong

Support Engineer

Azure - Security

Working Hours: 3:00 PM - 12:00 AM (UTC+7, Monday to Friday)

Need help outside of my working hours?

Locate an engineer: ***@***.******@***.***>

Manager: Olivia Li/ ***@***.***

[image]

________________________________

**Comment by v-sudkharat** [comment]
Hi @v-nguyentruong, have you checked with updated parser? - https://github.com/Azure/Azure-Sentinel/files/14122744/CiscoISEParser_Updated1.txt

**Comment by v-nguyentruong** [comment]
Thanks for the update parser file. I just checked and seem like it will work. Let's me check this with customers. I will response if I have any update from them.

**Comment by v-sudkharat** [comment]
@v-nguyentruong, Sure. Please share update with us once it done. Thanks!

**Comment by v-sudkharat** [comment]
@v-nguyentruong, thanks for update. We will check on this and get back to you by - 08-02-2024. Thanks!

**Comment by v-sudkharat** [comment]
Hi @v-nguyentruong, We have updated the parser and tested in our workspace with available data. Could you please check it in customer environment and let us know still TimeGenerated column is not visible. Thanks! 
Updated Paser File - [CiscoParser.txt](https://github.com/Azure/Azure-Sentinel/files/14163264/CiscoParser.txt)

![image](https://github.com/Azure/Azure-Sentinel/assets/132428394/929cedbe-c019-48f0-9388-16c28522ff75)

**Comment by v-nguyentruong** [comment]
Thanks for the update parser file. Let's me check this with customers. I will response if I have any update from them.

**Comment by v-sudkharat** [comment]
Hi @v-nguyentruong, Any update from customer? Thanks!

**Comment by v-sudkharat** [comment]
@v-nguyentruong, noted, please let us know once you any update on this. Thanks!

**Comment by v-sudkharat** [comment]
@v-nguyentruong, Noted. Thanks!

**Comment by v-nguyentruong** [comment]
Nelson Truong (WICLOUD CORPORATION) ***@***.***) has sent you a protected message.
                                          Read the message            Learn about messages protected by Microsoft Purview Message Encryption.        
    
    
    
        
            This is a secure message from Microsoft. The contents of this email message and any attachments are intended solely for the addressee(s) on this message and will contain confidential and/or privileged information. It is strictly prohibited to share any part of this message with any third party.           Privacy Statement        
    
    
        
              Learn More on email encryption.             Microsoft Corporation, One Microsoft Way, Redmond, WA 98052

**Comment by v-nguyentruong** [comment]
Hi @Sudarshan Kharat (Tata Consultancy Services Limi)

Just got a reply from the customer. The parser working fine now but the customer wants to request if it is possible to parse the computer name separately from the line AcsSessionID=Computer/Number/Number.
Example screenshot:
[cid:2fba9cbb-53fd-4e51-a57e-850c9b9b5dbb]
Request add 1 more column name: "Computer" contain the Computer name in the AcsSessionID field.

Please, let me know if you can do this for the customer.


Best Regards,

 

Nelson Truong

Support Engineer

Azure - Security

Working Hours: 3:00 PM - 12:00 AM (UTC+7, Monday to Friday)

Need help outside of my working hours?

Locate an engineer: ***@***.******@***.***>

Manager: Olivia Li/ ***@***.***

[image]

________________________________

**Comment by v-sudkharat** [comment]
Hi @v-nguyentruong, Thanks for the update. The feature request from the customer we need to check with the respective team.  Meanwhile, we have checked for extract the `ComputerName` from the column `AcsSessionID` and extracted into new `Computers `column. Due to limitation for sample data, we have tested the below parser with the different sample data. So, could you please check with the customer and let us know the feedback. 
Parser File - [Cisco.txt](https://github.com/Azure/Azure-Sentinel/files/14266719/Cisco.txt)

Thanks!

**Comment by v-sudkharat** [comment]
@v-nguyentruong, Thanks!

**Comment by sandeep5234** [comment]
Hi, We are facing exactly same issue, I have tried above both updated parsers but they both give me different output. One of them definitely gave time generated column . See below image.
<img width="491" alt="image" src="https://github.com/Azure/Azure-Sentinel/assets/41977495/74bf6f64-63a4-43b1-958a-7e1b58bf870c">

**Comment by v-sudkharat** [comment]
Hi @sandeep5234. Have you checked with this one - Paser File - [CiscoParser.txt](https://github.com/Azure/Azure-Sentinel/files/14163264/CiscoParser.txt)

**Comment by v-sudkharat** [comment]
Hi @v-nguyentruong, Any update from customer. Thanks!

**Comment by sandeep5234** [comment]
@v-sudkharat I have just tried and below is the result
<img width="443" alt="image" src="https://github.com/Azure/Azure-Sentinel/assets/41977495/0e3a0929-3f82-437e-8deb-00a2fd149d09">
seems same issue to me

**Comment by v-nguyentruong** [comment]
Hi @v-sudkharat. I'm still waiting for cx response.

**Comment by v-sudkharat** [comment]
@v-nguyentruong, Ok. Thanks!

**Comment by v-sudkharat** [comment]
Hi @v-nguyentruong, Could you please request cx to share the sample data with us, so we can modify the query accordingly. Thanks!

**Comment by v-nguyentruong** [comment]
Hi @v-sudkharat . Sure, I'll let you know if I got the sample data from cx.

**Comment by v-sudkharat** [comment]
Hi @sandeep5234, we have received the data from customer. thank you for your response.

**Comment by v-sudkharat** [comment]
Hi @v-nguyentruong, We have make those modification as per customer requirement in Parser and added the new column as `Computers`. 
Sharing the screenshot for reference - 
![image](https://github.com/Azure/Azure-Sentinel/assets/132428394/a7673deb-b9c7-4d4b-a00d-e6667f258efe)

Could you please share the latest updated parser with the customer and let us know the feedback with us. 
Updated Parser File - [Cisco.txt](https://github.com/Azure/Azure-Sentinel/files/14417087/Cisco.txt)

Thanks!

**Comment by v-nguyentruong** [comment]
Hi @v-sudkharat . Thanks for the update parser, I'll let you know if I get update from cx.

**Comment by v-sudkharat** [comment]
@v-nguyentruong, Ok

**Comment by v-nguyentruong** [comment]
Nelson Truong (WICLOUD CORPORATION) ***@***.***) has sent you a protected message.
                                          Read the message            Learn about messages protected by Microsoft Purview Message Encryption.        
    
    
    
        
            This is a secure message from Microsoft. The contents of this email message and any attachments are intended solely for the addressee(s) on this message and will contain confidential and/or privileged information. It is strictly prohibited to share any part of this message with any third party.           Privacy Statement        
    
    
        
              Learn More on email encryption.             Microsoft Corporation, One Microsoft Way, Redmond, WA 98052

**Comment by sandeep5234** [comment]
@v-sudkharat I have just tested the new updated parser and results are below
<img width="496" alt="image" src="https://github.com/Azure/Azure-Sentinel/assets/41977495/3baf138b-5b4f-4c6c-8f46-ae7514dc29e4">

seems same issue for me.

**Comment by v-nguyentruong** [comment]
Hi @Sudarshan Kharat (Tata Consultancy Services ***@***.***>

Just got a response from cx. There is Computer column now and it has computer name in it. However, some stay blank. Screenshot below.

[cid:a84575ce-00e2-4da5-9dfb-2a81e544143f]


Best Regards,

 

Nelson Truong

Support Engineer

Azure - Security

Working Hours: 3:00 PM - 12:00 AM (UTC+7, Monday to Friday)

Need help outside of my working hours?

Locate an engineer: ***@***.******@***.***>

Manager: Olivia Li/ ***@***.***

[image]

________________________________

**Comment by v-sudkharat** [comment]
@v-nguyentruong, checking on Parser. 
Hey @sandeep5234, Could you please more explain your issue or if it is different, could you please raise a new issue so our team can check on that. Thanks!

**Comment by sandeep5234** [comment]
@v-sudkharat We have Cisco ISE network device from where we collect logs in Syslog format, the Cisco ISE parser available as part of the Cisco ISE package in Azure sentinel repository doesn't parse the data to correct columns.  This is my issue in short.

**Comment by v-sudkharat** [comment]
Hi @v-nguyentruong, We have updated the parser, and it successfully showing the expected result in cx shared CISCO ISE sample data. Please check with cx - [Cisco.txt](https://github.com/Azure/Azure-Sentinel/files/14435235/Cisco.txt) 
If he still having the issue, then we required the cx syslog data to check on it. 


Thanks!

**Comment by v-sudkharat** [comment]
Hii @sandeep5234, Could you please raise a new GitHub issue and shared details over there with adding the sample data. So our team check on your case and update you. Thanks!

**Comment by sandeep5234** [comment]
@v-sudkharat   I have created new issue

This is the one. 
#10070

**Comment by v-sudkharat** [comment]
Hi @v-nguyentruong, Waiting for your response on above comment. Thanks!

**Comment by v-nguyentruong** [comment]
Hi @v-sudkharat . Cx deployed the new parser, and it was working fine. However, they want to monitor the parser for few more days to check if new issue arises. I'll let you know if there is new update from them.

**Comment by v-sudkharat** [comment]
Hi @v-nguyentruong, Any update from cx? Thanks!

**Comment by v-nguyentruong** [comment]
Hi @v-sudkharat . The parser working fine now. Thanks for your help.

**Comment by v-nguyentruong** [comment]
Hi @v-sudkharat . The parser working fine now. Thanks for your help.

**Comment by v-sudkharat** [comment]
@v-nguyentruong, Always welcome.
