### ISSUE TITLE
Create-Snapshot Playbook will operates on unrelated entities 

### ISSUE THREAD

**Issue by NVolcz** [Azure/Azure-Sentinel#978]
**Describe the bug**
The [Create-Snapshot](https://github.com/Azure/Azure-Sentinel/blob/master/Playbooks/Create-AzureSnapshot/Create-Snapshot.json) will fetch unrelated alerts due to incorrect fetching of alert details.

The current flow currently looks like this:
1. When a response to an Azure Sentinel alert is triggered
2. Alert - Get incident
3. Parse JSON
4. [Get Full Alert Details](https://github.com/Azure/Azure-Sentinel/blob/master/Playbooks/Create-AzureSnapshot/Create-Snapshot.json#L764-L788). This step uses the ExtendedProperties.Query in order to fetch the alerts that triggered the Sentinel incident.
5. Parse Query Result
6. For each alert in Result
6.a. Get Azure VM
6.b. Parse VM data
6.c. Create Snapshot
6.d. Add comment to Sentinel incident

The Get Full Alert Details is not restricted to the same context that triggered the Sentinel Alert and will therefor include a lot more alerts.

**To Reproduce**
1. Create a Scheduled query rule that run every hour, with a threshold of "greater than 0" and with the following query:
```
SecurityAlert
```
2. Run Create-Snapshot Playbook on an triggered incident.
3. Compare the number of alerts handled by the Playbook and the number of alerts that triggered the Sentinel Alert.

**Expected behavior**
The playbook should only apply for the machines in the incident.

**Screenshots**
![alert-full-details](https://user-images.githubusercontent.com/1667690/90502172-b72afa80-e14d-11ea-98e1-4eeb4b85984b.PNG)

**Comment by shainw** [comment]
@ThijsLecomte - Can you have a look at this?  Thanks, Shain

**Comment by ThijsLecomte** [comment]
Hi @NVolcz 

Let me start off by saying I am not a Microsoft employee, I am a community member who created this.

The playbook uses the ResourceId to identify the correct machine. As the SecurityAlert table doesn't have this, this is bound to fail.

However, I am more than happy to look into a solution for your use case. What exactly are you trying to achieve?

**Comment by NVolcz** [comment]
The bug report is that this playbook is not safe to use in many environments.
There is no general safe way to get the triggering alerts by using the `ExtendedProperties.Query`. I have solved this in a similar scenario by replacing `SecurityAlert ` with (pseudo code) `SecurityAlert | TimeGenerated >ExtendedProperties.StartTime && TimeGenerated < ExtendedProperties.EndTime` but this does only work in simple cases.

**Comment by ThijsLecomte** [comment]
@NVolcz I agree that there is no optimal way to retrieve the ResourceId for the VM.
I have updated the query which now queries for the last 15 minutes instead of 1 hour and also added a warning in the ReadMe.

What do you think?

**Comment by NVolcz** [comment]
I guess it is up to the maintainers to decide what is good enough. The risk is limited since the action performed is not destructive. It feels like this is a problem that should be solvable by using the incident Entities but I haven't found any useful documentation for this. Maybe @shainw knows?

We could improve the [time limit](https://github.com/Azure/Azure-Sentinel/pull/1071/files#diff-b9762d190573d720bcc434d55f2d1a99R772) by using the `Query Start Time UTC` and `Query End Time UTC` in `ExtendedProperties` (have not tested the code):
```
"body": " @{body('Parse_JSON')?['ExtendedProperties']?['Query']}| where TimeGenerated >= @{body('Parse_JSON')?['ExtendedProperties']?['Query Start Time UTC']} and TimeGenerated <= @{body('Parse_JSON')?['ExtendedProperties']?['Query End Time UTC']} ",
```
We could also add an additional check to ensure that the returned number of alerts equals to `Seach Query Result Overall Count`.

**Comment by ThijsLecomte** [comment]
@NVolcz  I just made it change which ensures the Playbook only operators on the entities of the alert. So in order to use this Playbook, the Host Custom Entity should be used.

I think this can be closed now @dicolanl ?

**Comment by NVolcz** [comment]
Thanks for making the change. I would consider the playbook safe in the current form. Some reflections I have made from this issue are that it would be easier to retrieve the alerts if:
- the Azure monitor `timerange` parameter worked. `"timerange": "Last hour"` currently does nothing.
- or if Sentinel somehow included the IDs for the alerts. Maybe something like how Azure monitor includes alerts.
