### ISSUE TITLE
New Mimecast (3.0.1) Function App based data connectors change Workspace default log retention to 30 days (typically 90 days) causing all tables retention to be changed/reduced

### ISSUE THREAD

**Issue by PCNZ** [Azure/Azure-Sentinel#9780]
**Describe the bug**
After deploying any of the new Mimecast data connectors (Mimecast Audit Logs, Mimecast Cloud Gateway MTA, Mimecast Cloud Gateway Targeted Threat Protection or Mimecast Cloud Gateway Threat Intel Regional Feed) the default log retention of the Workspace specified during deployment of the function app is set to 30 days. The deployment overwrites the existing retention setting of the workspace, which is typically 90 days.
It should not be changing the retention of the workspace at all.
The result is that all tables which are using the default retention period, have logs retention significantly reduced.

**To Reproduce**
1. Check the log retention on your existing Sentinel Workspace (typically 90 days)
2. Install one of the Mimecast contents from the Content Hub ((Mimecast Audit Logs, Mimecast Cloud Gateway MTA, Mimecast Cloud Gateway Targeted Threat Protection or Mimecast Cloud Gateway Threat Intel Regional Feed)
3. Open Data Connectors and the new Mimecast data connector
4. Select "Deploy to Azure" to deploy the function app.
5. In the Custom deployment page select a Sentinel workspace which has a retention period other than 30 days
6. Deploy the function app (doesn't require valid Mimecast details at this point as change to workspace retention happens regardless)
7. Check the log retention on your existing Sentinel Workspace, observe it has changed to 30 days.

**Expected behavior**
Sentinel Workspace Default Log Retentions are not changed when a data connector is deployed.

**Screenshots**
Function app deployment setting retention to 30 days.
![image](https://github.com/Azure/Azure-Sentinel/assets/68888744/642bf0c0-5c0a-4864-9a03-3ffa13a7563c)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser Edge
 - Version 120.0.2210.133 (Official build) (64-bit)

**Additional context**
Anyone who has deployed this data connector should check and reset their default log retentions to avoid unexpected data loss.
Please add code checks to all Sentinel pull requests, to prevent future data connectors being deployed which exhibit this behaviour.

**Comment by v-muuppugund** [comment]
Hi  @PCNZ , Thanks for flagging this issue, we will investigate this issue and get back to you with some updates by 23Jan2024. Thanks!

**Comment by v-sudkharat** [comment]
Hi @PCNZ, thanks for reporting this bug with us. We have checked the solution, the Mimecast solution is partner supported with the Mimecast Team, and as of now we are not authorized to make those modification in function app. but i can see you have raised the PR-(#9781) with those changes, we really appreciate your contribution on this. 

We will check this issue with our team and get back to you by some updates. Thanks!

**Comment by PCNZ** [comment]
> Hi @PCNZ, thanks for reporting this bug with us. We have checked the solution, the Mimecast solution is partner supported with the Mimecast Team, and as of now we are not authorized to make those modification in function app. but i can see you have raised the PR-(#9781) with those changes, we really appreciate your contribution on this.
> 
> We will check this issue with our team and get back to you by some updates. Thanks!

Thanks, I have also emailed the Mimecast support email address listed in the solution (support@mimecast.com) but it responds saying that it is no longer used/monitored.

**Comment by v-sudkharat** [comment]
Hi @PCNZ, thank you for response. Could you please check with below shared link and raise case with Mimecast. So Mimecast team will can check on this issue and made those modification's. 
Sharing the Mimecast support link -
Link - "https://community.mimecast.com/s/contactsupport" 
We are closing this issue from GitHub. If you still need support for this issue, feel free to re-open it any time. Thank you for your co-operation.

**Comment by PCNZ** [comment]
> Hi @PCNZ, thank you for response. Could you please check with below shared link and raise case with Mimecast. So Mimecast team will can check on this issue and made those modification's. Sharing the Mimecast support link - Link - "https://community.mimecast.com/s/contactsupport" We are closing this issue from GitHub. If you still need support for this issue, feel free to re-open it any time. Thank you for your co-operation.

Seems you need to be a customer and have a registered domain with Mimecast to be able to access that support, which I don't have.

**Comment by PCNZ** [comment]
I don't seem to have access to re-open this, can you please leave it open until it is resolved. To let users know the bug still exists and give them the opportunity to work around it.

**Comment by v-sudkharat** [comment]
Hi @PCNZ, Apologies for the delay in response. Unfortunately, we cannot keep this partner-supported solution open. As mentioned above, we are not authorized to do so. Therefore, we kindly request the customer to open a case with Mimecast so that they can make the required changes.

Thanks!

**Comment by PCNZ** [comment]
@nipun-crestdatasystem
@SmitR01
Sorry to ping you directly, but you involved with the development of this still?

**Comment by nipun-crestdatasystem** [comment]
@PCNZ yes we are in discussion with Mimecast on this.

**Comment by PCNZ** [comment]
This has been fixed now.
https://github.com/Azure/Azure-Sentinel/commit/d306787ec2b5c5d861769632ea84bc74683f595b
