### ISSUE TITLE
Dynatrace solution deployment wizard shows duplicated text on the Data Collectors pane

### ISSUE THREAD

**Issue by keyoke** [Azure/Azure-Sentinel#9787]
**Describe the bug**
The text "This Solution installs the data connector for Dynatrace. You can get Dynatrace custom log data in your Microsoft Sentinel workspace. After installing the solution, configure and enable this data connector by following guidance in Manage solution view." on the data connectors page is repeated multiple times

**To Reproduce**
deploy the solution from marketplace

**Expected behavior**
text should not be duplicated

**Screenshots**
duplicated text

![image](https://github.com/Azure/Azure-Sentinel/assets/183547/cbf37f7c-8e9a-43fe-8ee1-c95d7ff8cf37)

playbook templates not listed

<img width="951" alt="image" src="https://github.com/Azure/Azure-Sentinel/assets/183547/dc4037cc-5765-43fa-b6ed-d2deb1534238">

**Comment by keyoke** [comment]
working on this [here](https://github.com/keyoke/Azure-Sentinel/tree/users/gaemslie/9787)

**Comment by v-sudkharat** [comment]
Hi @keyoke, Thanks for flagging this issue, we can see you have already raised a PR with the correction's. Our team will review that PR and if required will share the comment over there. Thanks! 
![image](https://github.com/Azure/Azure-Sentinel/assets/132428394/b04ebc14-fa5a-40cd-ab22-ae1c1ef4d9c0)

**Comment by v-sudkharat** [comment]
Hi @keyoke, Could you please check the comment on this PR - https://github.com/Azure/Azure-Sentinel/pull/9788 . Thanks!

**Comment by keyoke** [comment]
> Hi @keyoke, Could you please check the comment on this PR - #9788 . Thanks!

responded on the PR

**Comment by v-sudkharat** [comment]
Hi @keyoke, I can see you have made correction in Create Ui file for connector instructions - 
![image](https://github.com/Azure/Azure-Sentinel/assets/132428394/ca75b161-ce8b-4913-85ef-6caa0402b053)

So, can we close this issue as changes has been done. Thanks!

**Comment by v-sudkharat** [comment]
Hi @keyoke, waiting for your response on above comment. Thanks!

**Comment by v-sudkharat** [comment]
Hi @keyoke, Gentle Reminder: We are waiting for your response on this issue. If you still need to keep this issue active, please respond to it in the next 2 days. If we don't receive a response by 08-03-2024 date, we will be closing this issue. 		
Thanks!

**Comment by v-sudkharat** [comment]
Hi @keyoke, since we have not received a response in the last 5 days, we are closing your issue as per our standard operating procedures. If you still need support for this issue, feel free to re-open at any time. Thank you for your co-operation.
