### ISSUE TITLE
Entity mapping details missing in the Analytic Rule template

### ISSUE THREAD

**Issue by v-rubkumari** [Azure/Azure-Sentinel#9790]
Case :2312130050002666

2312130050002666 .docx](https://github.com/Azure/Azure-Sentinel/files/13988384/ICM.Draft.for.case.2312130050002666.docx)

Customer has reported bug for the some inbuilt analytic rule template which when they updated from content Hub showing error as empty Entity mapping empty
•	Analytic rule "AD account with Don't Expire Password". 
•	Current template version: 1.1.3.
•	New template version with errors: 1.2.1.
•	Error:
 
•	Analytic rule "Account created from non-approved sources". 
•	Current template version: 1.1.0.
•	New template version with errors: 1.1.1.
•	Error:
 
•	
•	Analytic rule "Midnight Blizzard - suspicious rundll32.exe execution of vbscript". 
•	Current template version: 1.1.3.
•	New template version with errors: 1.1.5.
•	Error:
 
•	
•	Analytic rule "User account enabled and disabled within 10 min". 
•	Current template version: 1.1.3.
•	New template version with errors: 1.2.1.
•	Error:
 
I have checked that particular analytic rule template and downloaded this standalone template from content HUB  it showing missing identifier in entity mapping, however if I am adding the identifier manually the error is gone.

**Comment by v-sudkharat** [comment]
Hi @v-rubkumari, Thanks for flagging this issue, we will investigate this issue and get back to you with some updates by 25-01-2024 . Thanks!

**Comment by shainw** [comment]
@v-rubkumari and @v-sudkharat 

#9803 submitted to fix this.  Please note that "User account enabled and disabled within 10 min" was already previously fixed and you should see version 1.2.2 via a commit on Dec 22nd - https://github.com/Azure/Azure-Sentinel/commits/master/Detections/SecurityEvent/UserAccountEnabledDisabled_10m.yaml

**Comment by v-sudkharat** [comment]
Hi @v-rubkumari, I hope you are doing well. Our concern team has raised the PR-#9803 with the modifications, and it also get merged. So could you please have a look into it and let us know if your issue gets resolved. 

Thanks!

**Comment by v-rubkumari** [comment]
@v-sudkharat Hello ,

Thank you for promptly looking into this, I am looking into this.

**Comment by v-sudkharat** [comment]
@v-rubkumari, Thanks!

**Comment by v-sudkharat** [comment]
Hi @v-rubkumari, As per discussion, closing this issue. If you still need support for this issue, feel free to re-open it any time. Thank you for your co-operation.
