### ISSUE TITLE
Broken Links Found in AnalyticRules/Descriptions

### ISSUE THREAD

**Issue by vmonge** [Azure/Azure-Sentinel#9813]
Inconsistency description: 
 
Broken link found in ARs' description : 

1. Non Domain Controller Active Directory Replication
2. Wazuh - Large Number of Web errors from an IP

**To Reproduce**
### 1) 
https://github.com/MSSAPSCA1/Azure_Sentinel/blob/main/Default_AZ_Sentinel_Rule_Templates/Non_Domain_Controller_Active_Directory_Replication_AZ_Sentinel_Analytics_Rules.json

Broken Link in Row # 18
                "description": "This query detects potential attempts by non-computer accounts (non domain controllers) to retrieve/synchronize an active directory object leveraging directory replication services (DRS).\nA Domain Controller (computer account) would usually be performing these actions in a domain environment. Another detection rule can be created to cover domain controllers accounts doing at rare times.\nA domain user with privileged permissions to use directory replication services is rare. Ref: **https://threathunterplaybook.com/notebooks/windows/06_credential_access/WIN-180815210510.html**",

returning 404 
![image](https://github.com/Azure/Azure-Sentinel/assets/28789477/6e5dff22-204f-4681-8cd4-7579e29715a7)

### 2) 
https://github.com/MSSAPSCA1/Azure_Sentinel/blob/main/Default_AZ_Sentinel_Rule_Templates/(5)%20S-Z_Azure_Sentinel_Scheduled_Analytics_Rules.json

Broken Link in Row # 18
  https://github.com/wazuh/wazuh-documentation/blob/master/source/azure/monitoring%20activity.rst
![image](https://github.com/Azure/Azure-Sentinel/assets/28789477/d0de6295-1972-49ac-bff3-b33fe79c60cd)

**Expected behavior**
Return 200 

**Screenshots**

Observations: 
Not sure if these are all the broken links.

**Comment by v-sudkharat** [comment]
Hi @vmonge, Thanks for flagging this issue, we will investigate this issue and get back to you with some updates by 30-01-2024. Thanks!

**Comment by v-sudkharat** [comment]
Hi @vmonge, we are checking with the respective team for broken link correction. In the meantime, we are providing a link that may redirect correctly, which we have investigated to help resolve your issue.
For 1st rule - 
Old - https://github.com/MSSAPSCA1/Azure_Sentinel/blob/main/Default_AZ_Sentinel_Rule_Templates/Non_Domain_Controller_Active_Directory_Replication_AZ_Sentinel_Analytics_Rules.json

New - https://threathunterplaybook.com/library/windows/active_directory_replication.html

2nd - 
Old - 
https://github.com/wazuh/wazuh-documentation/blob/master/source/azure/monitoring%20activity.rst

New - 
https://github.com/wazuh/wazuh-documentation/blob/985d7cd2d024be45e5a920c871596e1cb64add87/source/azure/monitoring%20activity.rst

Thanks!

**Comment by v-sudkharat** [comment]
Hi @vmonge, we are waiting for your response on above comment. Thanks!

**Comment by v-sudkharat** [comment]
Hi @vmonge, we have checked your shared links, currently we are not authorized to make any changes in that repo. So we kindly request you please raise issue in below mentioned repo. 
https://github.com/MSSAPSCA1/Azure_Sentinel/tree/main
Closing this issue. If you still need support for this issue, feel free to re-open it any time. Thank you for your co-operation.
