### ISSUE TITLE
Solution - Microsoft Defender Threat Intelligence missing 4 playbooks

### ISSUE THREAD

**Issue by MikeP1375** [Azure/Azure-Sentinel#9829]
**Describe the bug**
The content hub solution "Microsoft Defender Threat Intelligence" only has 4 playbooks but GitHub solution itself reports 8 playbooks.

**To Reproduce**
1. Go to Content Hub.
2. Install content solution 'Deploy the content hub solution "Microsoft Defender Threat Intelligence" and you will get 4 playbooks.'
3. Go to automation -> Playbook templates.
4. Filter for 'MDTI'.
5. Output is 'MDT-Automated-Triage', 'MDTI-Intel-Reputation', 'MDTI-Base', 'MDTI-Data-WebComponents'.

**Expected behavior**
Output should have the following playbooks
- MDT-Automated-Triage
- MDTI-Intel-Reputation
- MDTI-Base
- MDTI-Data-WebComponents
- MDTI-Data-Cookies
- MDTI-PassiveDns
- MDTI-PassiveDnsReverse
- MDTI-Trackers

See Playbook folder in GitHub - https://github.com/Azure/Azure-Sentinel/tree/master/Solutions/Microsoft%20Defender%20Threat%20Intelligence/Playbooks

**Screenshots**
![image](https://github.com/Azure/Azure-Sentinel/assets/157804428/4d4e2bdb-29cd-4b8d-bcb5-07452c8d2002)

![image](https://github.com/Azure/Azure-Sentinel/assets/157804428/988f7849-49d2-4674-99b0-cd605070b855)

**Comment by v-sudkharat** [comment]
Hi @MikeP1375, Thanks for flagging this issue, we will investigate this issue and get back to you with some updates by 01-02-2024. Thanks!

**Comment by v-sudkharat** [comment]
Hi @MikeP1375, I hope you are doing well. We have created a pull request by including those playbooks in the solution. The changes will be reflected in the upcoming version of the solution.

Thanks!
