### ISSUE TITLE
Workbook - WorkBook Usage Report missing fields for analytic rules due to using old preview API

### ISSUE THREAD

**Issue by MikeP1375** [Azure/Azure-Sentinel#9830]
**Describe the bug**
The workbook 'Workbook usage report' is using the 2202-06-01-preview api which does not include fields like Description, Severity for the display of analytic rules. The latest API version is 2023-11-01 which includes the fields.

https://learn.microsoft.com/en-us/rest/api/securityinsights/alert-rules/list?view=rest-securityinsights-2023-11-01&tabs=HTTP#code-try-0

Note - Workbook allows for the export of analytic rules.

**To Reproduce**
1. Go to Sentinel.
2. Install the workbook 'workbook usage report' from the content hub.
3. Navigate to workbooks, and open 'workbook usage report'.
4. Select Sentinel workspace.
5. Select Regular Checks (D/W/M).
6. Select Weekly for Group: Regular Checks.
7. Select Rules.
8. Scroll down to '3a. Active Rules via Rest API'. 
9. See fields Description, Severity are not displayed.

**Expected behavior**
Display fields Description, Severity. Updating the API version to 2023-11-01 would allow the additional information to be displayed.

**Screenshots**
![image](https://github.com/Azure/Azure-Sentinel/assets/157804428/06ebc802-306b-48f5-bdbb-de6d3fbe6a36)

![image](https://github.com/Azure/Azure-Sentinel/assets/157804428/8c1e977d-f996-4012-a72e-b4c3766adc3c)

**Comment by v-muuppugund** [comment]
Hi  @MikeP1375 , Thanks for flagging this issue, we will investigate this issue and get back to you with some updates by 02/02/2024. Thanks!

**Comment by v-muuppugund** [comment]
Hi @MikeP1375 ,need some more time for applying those missing fields,working on it,will update you

**Comment by v-muuppugund** [comment]
Hi @MikeP1375 ,I have modified the api call and added the fields in KQL query,Please find below screen shot for reference,will be raising the PR for the same,
![image](https://github.com/Azure/Azure-Sentinel/assets/139563098/95d60859-c995-4111-af6f-246ef6d7c9e9)

**Comment by v-muuppugund** [comment]
> Hi @MikeP1375 ,I have modified the api call and added the fields in KQL query,Please find below screen shot for reference,will be raising the PR for the same, ![image](https://private-user-images.githubusercontent.com/139563098/303901708-95d60859-c995-4111-af6f-246ef6d7c9e9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIxNDI5NTYsIm5iZiI6MTcxMjE0MjY1NiwicGF0aCI6Ii8xMzk1NjMwOTgvMzAzOTAxNzA4LTk1ZDYwODU5LWM5OTUtNDExMS1hZjZmLTI0NmVmNmQ3YzllOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQwM1QxMTEwNTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xMzliMTk1YWFlMmM0NWNjNjM4ZDMyNTA4ZjdkNzVmOTNlNDcyMDlhMGEyMzg5MTMzYjE0YjFmYjA0NTg1NGRhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.FUf-1WG_cDRy3bOzzyVsOCeyaiehEWBjkmH3l217_Kg)

Hi @MikeP1375 ,Apologies for delayed response, Raised the PR,once merged,will close the issue
