### ISSUE TITLE
PPInventory not sending data to Sentinel

### ISSUE THREAD

**Issue by philfy20** [Azure/Azure-Sentinel#9832]
Data connector PPInventory - https://github.com/Azure/Azure-Sentinel/tree/master/DataConnectors/PPInventory is not sending data to Sentinel after processing the blob. See below logs from the function app, function app is not showing any errors even though data has not been sent to Sentinel

<img width="1234" alt="image" src="https://github.com/Azure/Azure-Sentinel/assets/91515482/aaa3d9bf-76ad-4be4-bd13-064332698573">

Looking at the logs, the function app run successfully the first time but since then the above issue has happened and no logs have come through

<img width="1147" alt="image" src="https://github.com/Azure/Azure-Sentinel/assets/91515482/d6a575f9-3dc2-435f-9df0-f7c36385700f">

**Comment by v-muuppugund** [comment]
Hi @philfy20 ,, Thanks for flagging this issue, we will investigate this issue and get back to you with some updates by 02/02/2024. Thanks!

**Comment by v-muuppugund** [comment]
Hi @philfy20 ,Apologies for the delayed response, Could you please share more details with from application insights traces/excpetions and also from when onwards its stopped ingesting the data.

**Comment by philfy20** [comment]
Hi @v-muuppugund, I am unable to to do further trouble as the same issue that was raised a few ago has returned - https://github.com/Azure/Azure-Sentinel/issues/9657.

The issue is the function in the function app disappears. Have restarted the function and same issue

<img width="1435" alt="image" src="https://github.com/Azure/Azure-Sentinel/assets/91515482/d9e4cc54-235d-45ee-b14c-3210b267e8da">

I really dont want to have deleting all the resources and redeploying ever few weeks when this happens

**Comment by v-muuppugund** [comment]
> Hi @v-muuppugund, I am unable to to do further trouble as the same issue that was raised a few ago has returned - #9657.
> 
> The issue is the function in the function app disappears. Have restarted the function and same issue
> 
> <img alt="image" width="1435" src="https://private-user-images.githubusercontent.com/91515482/303166341-d9e4cc54-235d-45ee-b14c-3210b267e8da.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDczODA1MzEsIm5iZiI6MTcwNzM4MDIzMSwicGF0aCI6Ii85MTUxNTQ4Mi8zMDMxNjYzNDEtZDllNGNjNTQtMjM1ZC00NWVlLWIxNGMtMzIxMGIyNjdlOGRhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjA4VDA4MTcxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU2MDYwYjAxOWUxNWYxZjRkMDZmYjg2NTg0MWVlZTIyNTRkNmEwMGRjMmIyYjcxNjY3YmM5OTZkZWNhOTMyNWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ksLV5nP_45KgXyk0OYOgizXSSJs_tw_ZcJTrQHq2cxw">
> I really dont want to have deleting all the resources and redeploying ever few weeks when this happens

got it,we need to check why this occurring frequently,Could you please share convenient time for a teams meeting to v-(muuppugund@microsoft.com),so have queries on this issue.

**Comment by v-muuppugund** [comment]
Hi @philfy20 ,Gentle reminder,we need to check why this occurring frequently,Could you please share convenient time for a teams meeting to ([v-muuppugund@microsoft.com](mailto:v-muuppugund@microsoft.com)),so have queries on this issue.

**Comment by philfy20** [comment]
@v-muuppugund have pinged you MS teams waiting for response

**Comment by v-muuppugund** [comment]
@philfy20 ,As discussed yesterday over teams call, Please redeploy the solution and let me know if you have any issues ,meanwhile will cross check with our team as don't access to environment.

**Comment by v-muuppugund** [comment]
@philfy20 ,Could you please check and let us know if the issue resolved or not after redeployment, meanwhile will have a meeting with concern team with detail discussion on this issue for permanent solution

**Comment by v-muuppugund** [comment]
@philfy20 ,Could you please share convenient time for teams meeting on this issue to v-muuppugund@microsoft.com

**Comment by v-muuppugund** [comment]
@philfy20 ,Gentle reminder, trying to reach over teams,Could you please share convenient time for teams meeting on this issue to [v-muuppugund@microsoft.com](mailto:v-muuppugund@microsoft.com)

**Comment by v-sudkharat** [comment]
Hi @philfy20, since we have not received a response in the last 5 days, we are closing your issue #9832 as per our standard operating procedures. If you still need support for this issue, feel free to re-open at any time. Thank you for your co-operation.
