### ISSUE TITLE
Errors in AWS s3 script

### ISSUE THREAD

**Issue by ShachafGoldstein** [Azure/Azure-Sentinel#9867]
https://github.com/Azure/Azure-Sentinel/blob/a089a4e0d5195c6c8b7ffcc0d8b2b8dd2a85bd02/DataConnectors/AWS-S3/Utils/AwsResourceCreator.ps1#L146

seems like this should be `-eq`, in general the scripts do not run on powershell core on macOS.

**Comment by v-sudkharat** [comment]
Hi @ShachafGoldstein, Thanks for flagging this issue, we will investigate this issue and get back to you with some updates by 06-01-2024. Thanks!

**Comment by v-muuppugund** [comment]
Hi @ShachafGoldstein ,I am unable to create new resources in the AWS environment i.e. s3 bucket due to limitations and working on it,will update you.

**Comment by v-muuppugund** [comment]
Hi @ShachafGoldstein ,created AWS environment using personal account and working on replicating the issue,will update you
![image](https://github.com/Azure/Azure-Sentinel/assets/139563098/ccf20b8b-1508-4b4b-a82d-cf79506f5e5f)

**Comment by v-muuppugund** [comment]
Hi @ShachafGoldstein ,Working on my created aws environment and need some more time for replicating the issue and will update you.

**Comment by v-muuppugund** [comment]
Hi @ShachafGoldstein ,Working on replicating the issue,will update you

**Comment by v-muuppugund** [comment]
Hi @ShachafGoldstein ,I am unable to replicate the issue,I have tried couple of days having a mac os VM, but unable to proceed further,Could you please share couple of time slots for a teams meeting to v-muuppugund@microsoft.com

**Comment by v-muuppugund** [comment]
Hi @ShachafGoldstein ,Blocked your calendar tomorrow for further trouble shooting,please join the meeting,

**Comment by ShachafGoldstein** [comment]
Seems to be solved now.
