### ISSUE TITLE
Query: Entra ID Local Device Join Information and Transport Key Registry Keys Access

### ISSUE THREAD

**Issue by rogfleming** [Azure/Azure-Sentinel#9874]
**Describe the bug**
Query fails to run as a Sentinel Hunting Query or a Sentinel Analytics. The query does work in Log Analytics Workspace

**To Reproduce**
1. Go to  'Sentinel click on Analytics
2. Click on 'create schedle alert'
3. Scroll down to 'add query to query section
4. Server Error, view query results works fine, but cannot save alert rule

**Expected behavior**
Rule should save, query should function

**Screenshots**

The server encountered a temporary error and could not complete your request.

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Windows 10
 - Browser [e.g. chrome, safari] Edge

**Smartphone (please complete the following information):**

**Additional context**
Azure Gov Environment

**Comment by v-muuppugund** [comment]
Hi @rogfleming ,Could you please share more details  with screen shot,Which solution,Which query you are facing the issue?

**Comment by v-sudkharat** [comment]
Hi @rogfleming, Gentle Reminder: We are waiting for your response on this issue. If you still need to keep this issue active, please respond to it in the next 2 days. If we don't receive a response by 13-02-2023 date, we will be closing this issue. 		
Thanks!

**Comment by v-muuppugund** [comment]
ince we have not received a response in the last 5 days, we are closing your issue (https://github.com/Azure/Azure-Sentinel/issues/9874) as per our standard operating procedures. If you still need support for this issue, feel free to re-open at any time. Thank you for your co-operation!
