### ISSUE TITLE
Content failed to deploy

### ISSUE THREAD

**Issue by ProGHAzure** [Azure/Azure-Sentinel#9876]
Hi All,

Content wont deploy? fork is fully updated but fails everytime!
  
Validating inputs
Module Az latest installed from hostedAgentFolder
Initializing Az Module
"C:\Program Files\PowerShell\7\pwsh.exe" -NoLogo -NoProfile -NonInteractive -Command Test-Path (Join-Path C:\Modules az_*)
"C:\Program Files\PowerShell\7\pwsh.exe" -NoLogo -NoProfile -NonInteractive -Command $env:PSModulePath
C:\Users\runneradmin\Documents\PowerShell\Modules;C:\Program Files\PowerShell\Modules;c:\program files\powershell\7\Modules;C:\\Modules\azurerm_2.1.0;C:\\Modules\azure_2.1.0;C:\Users\packer\Documents\WindowsPowerShell\Modules;C:\Program Files\WindowsPowerShell\Modules;C:\Windows\system32\WindowsPowerShell\v1.0\Modules;C:\Program Files\Microsoft SQL Server\130\Tools\PowerShell\Modules\
"C:\Program Files\PowerShell\7\pwsh.exe" -NoLogo -NoProfile -NonInteractive -Command "try ***
            $ErrorActionPreference = \"Stop\"
            $WarningPreference = \"SilentlyContinue\"
            $output = @***
            $data = Get-Module -Name Az -ListAvailable | Sort-Object Version -Descending | Select-Object -First 1
            $output['AzVersion'] = $data.Version.ToString()
            $output['Success'] = \"true\"
        ***
        catch ***
            $output['Error'] = $_.exception.Message
        ***
        return ConvertTo-Json $output"
True
***
  "Success": "true",
  "AzVersion": "9.3.0"
***
"C:\Program Files\PowerShell\7\pwsh.exe" -NoLogo -NoProfile -NonInteractive -Command $env:PSModulePath
C:\Modules;C:\Users\runneradmin\Documents\PowerShell\Modules;C:\Program Files\PowerShell\Modules;c:\program files\powershell\7\Modules;C:\\Modules\azurerm_2.1.0;C:\\Modules\azure_2.1.0;C:\Users\packer\Documents\WindowsPowerShell\Modules;C:\Program Files\WindowsPowerShell\Modules;C:\Windows\system32\WindowsPowerShell\v1.0\Modules;C:\Program Files\Microsoft SQL Server\130\Tools\PowerShell\Modules\
Initializing Az Module Complete
Running Az PowerShell Script
"C:\Program Files\PowerShell\7\pwsh.exe" -NoLogo -NoProfile -NonInteractive -Command D:\a\_temp\[27](https://github.com/ProGHAzure/Sentinel/actions/runs/7728473583/job/21069333760#step:11:28)2d0[29](https://github.com/ProGHAzure/Sentinel/actions/runs/7728473583/job/21069333760#step:11:30)2-948b-4c40-9e9c-5c37af507fb8.ps1
[Info] load the deployment configuration from [D:\a\Sentinel\Sentinel\sentinel-deployment.config]
Starting Deployment for Files in path: D:\a\Sentinel\Sentinel
[Info] Try to deploy D:\a\Sentinel\Sentinel\.script\SolutionValidations\ValidDomainsVerticals.json
Error:  Failed to check valid resource type.
Warning:  Skipping deployment for D:\a\Sentinel\Sentinel\.script\SolutionValidations\ValidDomainsVerticals.json. The file contains resources for content that was not selected for deployment. Please add content type to connection if you want this file to be deployed.
[Info] Try to deploy D:\a\Sentinel\Sentinel\.script\tests\dataConnectorValidatorTest\testFiles\Agari\invalidAzureFunctionConnectorPermissions.json
Error:  Failed to check valid resource type.
Warning:  Skipping deployment for D:\a\Sentinel\Sentinel\.script\tests\dataConnectorValidatorTest\testFiles\Agari\invalidAzureFunctionConnectorPermissions.json. The file contains resources for content that was not selected for deployment. Please add content type to connection if you want this file to be deployed.
[Info] Try to deploy D:\a\Sentinel\Sentinel\.script\tests\dataConnectorValidatorTest\testFiles\Agari\validAzureFunctionConnectorPermissions.json
Error:  Failed to check valid resource type.
Warning:  Skipping deployment for D:\a\Sentinel\Sentinel\.script\tests\dataConnectorValidatorTest\testFiles\Agari\validAzureFunctionConnectorPermissions.json. The file contains resources for content that was not selected for deployment. Please add content type to connection if you want this file to be deployed.
[Info] Try to deploy D:\a\Sentinel\Sentinel\.script\tests\dataConnectorValidatorTest\testFiles\Agari\validAzureFunctionDataConnector.json
Error:  Failed to check valid resource type.
Warning:  Skipping deployment for D:\a\Sentinel\Sentinel\.script\tests\dataConnectorValidatorTest\testFiles\Agari\validAzureFunctionDataConnector.json. The file contains resources for content that was not selected for deployment. Please add content type to connection if you want this file to be deployed.
[Info] Try to deploy D:\a\Sentinel\Sentinel\.script\tests\dataConnectorValidatorTest\testFiles\Templates\Connector_REST_API_template.json
Error:  Failed to check valid resource type.
Warning:  Skipping deployment for D:\a\Sentinel\Sentinel\.script\tests\dataConnectorValidatorTest\testFiles\Templates\Connector_REST_API_template.json. The file contains resources for content that was not selected for deployment. Please add content type to connection if you want this file to be deployed.
[Info] Try to deploy D:\a\Sentinel\Sentinel\.script\tests\dataConnectorValidatorTest\testFiles\invalidAzureDiagnosticsDataConnector.json
Error:  Failed to check valid resource type.
Warning:  Skipping deployment for D:\a\Sentinel\Sentinel\.script\tests\dataConnectorValidatorTest\testFiles\invalidAzureDiagnosticsDataConnector.json. The file contains resources for content that was not selected for deployment. Please add content type to connection if you want this file to be deployed.
[Info] Try to deploy D:\a\Sentinel\Sentinel\.script\tests\dataConnectorValidatorTest\testFiles\invalidAzureFunctionConnectorPermissions.json
Error:  Failed to check valid resource type.
Warning:  Skipping deployment for D:\a\Sentinel\Sentinel\.script\tests\dataConnectorValidatorTest\testFiles\invalidAzureFunctionConnectorPermissions.json. The file contains resources for content that was not selected for deployment. Please add content type to connection if you want this file to be deployed.
[Info] Try to deploy D:\a\Sentinel\Sentinel\.script\tests\dataConnectorValidatorTest\testFiles\invalidCEFConnectorPermissions.json
Error:  Failed to check valid resource type.
Warning:  Skipping deployment for D:\a\Sentinel\Sentinel\.script\tests\dataConnectorValidatorTest\testFiles\invalidCEFConnectorPermissions.json. The file contains resources for content that was not selected for deployment. Please add content type to connection if you want this file to be deployed.
[Info] Try to deploy D:\a\Sentinel\Sentinel\.script\tests\dataConnectorValidatorTest\testFiles\invalidSyslogConnectorPermissions.json
Error:  Failed to check valid resource type.
Warning:  Skipping deployment for D:\a\Sentinel\Sentinel\.script\tests\dataConnectorValidatorTest\testFiles\invalidSyslogConnectorPermissions.json. The file contains resources for content that was not selected for deployment. Please add content type to connection if you want this file to be deployed.
[Info] Try to deploy D:\a\Sentinel\Sentinel\.script\tests\dataConnectorValidatorTest\testFiles\missingAdditionalRequirementBanner.json
Error:  Failed to check valid resource type.
Warning:  Skipping deployment for D:\a\Sentinel\Sentinel\.script\tests\dataConnectorValidatorTest\testFiles\missingAdditionalRequirementBanner.json. The file contains resources for content that was not selected for deployment. Please add content type to connection if you want this file to be deployed.
[Info] Try to deploy D:\a\Sentinel\Sentinel\.script\tests\dataConnectorValidatorTest\testFiles\missingIdAndConnectivityCriteria.json
Error:  Failed to check valid resource type.
Warning:  Skipping deployment for D:\a\Sentinel\Sentinel\.script\tests\dataConnectorValidatorTest\testFiles\missingIdAndConnectivityCriteria.json. The file contains resources for content that was not selected for deployment. Please add content type to connection if you want this file to be deployed.
[Info] Try to deploy D:\a\Sentinel\Sentinel\.script\tests\dataConnectorValidatorTest\testFiles\missingPublisherProperty.json
Error:  Failed to check valid resource type.
Warning:  Skipping deployment for D:\a\Sentinel\Sentinel\.script\tests\dataConnectorValidatorTest\testFiles\missingPublisherProperty.json. The file contains resources for content that was not selected for deployment. Please add content type to connection if you want this file to be deployed.
[Info] Try to deploy D:\a\Sentinel\Sentinel\.script\tests\dataConnectorValidatorTest\testFiles\spaceIn DataConnector FileName.json
Error:  Failed to check valid resource type.
Warning:  Skipping deployment for D:\a\Sentinel\Sentinel\.script\tests\dataConnectorValidatorTest\testFiles\spaceIn DataConnector FileName.json. The file contains resources for content that was not selected for deployment. Please add content type to connection if you want this file to be deployed.
[Info] Try to deploy D:\a\Sentinel\Sentinel\.script\tests\dataConnectorValidatorTest\testFiles\spaceInDataConnectorDataType.json
Error:  Failed to check valid resource type.
Warning:  Skipping deployment for D:\a\Sentinel\Sentinel\.script\tests\dataConnectorValidatorTest\testFiles\spaceInDataConnectorDataType.json. The file contains resources for content that was not selected for deployment. Please add content type to connection if you want this file to be deployed.
[Info] Try to deploy D:\a\Sentinel\Sentinel\.script\tests\dataConnectorValidatorTest\testFiles\spaceInDataConnectorId.json
Error:  Failed to check valid resource type.
Warning:  Skipping deployment for D:\a\Sentinel\Sentinel\.script\tests\dataConnectorValidatorTest\testFiles\spaceInDataConnectorId.json. The file contains resources for content that was not selected for deployment. Please add content type to connection if you want this file to be deployed.
[Info] Try to deploy D:\a\Sentinel\Sentinel\.script\tests\dataConnectorValidatorTest\testFiles\validAzureDiagnosticsDataConnector.json
Error:  Failed to check valid resource type.
Warning:  Skipping deployment for D:\a\Sentinel\Sentinel\.script\tests\dataConnectorValidatorTest\testFiles\validAzureDiagnosticsDataConnector.json. The file contains resources for content that was not selected for deployment. Please add content type to connection if you want this file to be deployed.
[Info] Try to deploy D:\a\Sentinel\Sentinel\.script\tests\dataConnectorValidatorTest\testFiles\validCEFConnectorPermissions.json
Error:  Failed to check valid resource type.
Warning:  Skipping deployment for D:\a\Sentinel\Sentinel\.script\tests\dataConnectorValidatorTest\testFiles\validCEFConnectorPermissions.json. The file contains resources for content that was not selected for deployment. Please add content type to connection if you want this file to be deployed.
[Info] Try to deploy D:\a\Sentinel\Sentinel\.script\tests\dataConnectorValidatorTest\testFiles\validCEFDataConnector.json
Error:  Failed to check valid resource type.
Warning:  Skipping deployment for D:\a\Sentinel\Sentinel\.script\tests\dataConnectorValidatorTest\testFiles\validCEFDataConnector.json. The file contains resources for content that was not selected for deployment. Please add content type to connection if you want this file to be deployed.
[Info] Try to deploy D:\a\Sentinel\Sentinel\.script\tests\dataConnectorValidatorTest\testFiles\validRestApiDataConnector.json
Error:  Failed to check valid resource type.
Warning:  Skipping deployment for D:\a\Sentinel\Sentinel\.script\tests\dataConnectorValidatorTest\testFiles\validRestApiDataConnector.json. The file contains resources for content that was not selected for deployment. Please add content type to connection if you want this file to be deployed.
[Info] Try to deploy D:\a\Sentinel\Sentinel\.script\tests\dataConnectorValidatorTest\testFiles\validSyslogConnectorDataSourcesPermissions.json
Error:  Failed to check valid resource type.
Warning:  Skipping deployment for D:\a\Sentinel\Sentinel\.script\tests\dataConnectorValidatorTest\testFiles\validSyslogConnectorDataSourcesPermissions.json. The file contains resources for content that was not selected for deployment. Please add content type to connection if you want this file to be deployed.
[Info] Try to deploy D:\a\Sentinel\Sentinel\.script\tests\dataConnectorValidatorTest\testFiles\validSyslogConnectorPermissions.json
Error:  Failed to check valid resource type.
Warning:  Skipping deployment for D:\a\Sentinel\Sentinel\.script\tests\dataConnectorValidatorTest\testFiles\validSyslogConnectorPermissions.json. The file contains resources for content that was not selected for deployment. Please add content type to connection if you want this file to be deployed.
[Info] Try to deploy D:\a\Sentinel\Sentinel\.script\tests\dataConnectorValidatorTest\testFiles\validSyslogDataConnector.json
Error:  Failed to check valid resource type.
Warning:  Skipping deployment for D:\a\Sentinel\Sentinel\.script\tests\dataConnectorValidatorTest\testFiles\validSyslogDataConnector.json. The file contains resources for content that was not selected for deployment. Please add content type to connection if you want this file to be deployed.
[Info] Try to deploy D:\a\Sentinel\Sentinel\.script\tests\detectionTemplateSchemaValidation\SkipConnectorIdsValidationsTemplates.json
Error:  Failed to check valid resource type.
Warning:  Skipping deployment for D:\a\Sentinel\Sentinel\.script\tests\detectionTemplateSchemaValidation\SkipConnectorIdsValidationsTemplates.json. The file contains resources for content that was not selected for deployment. Please add content type to connection if you want this file to be deployed.
[Info] Try to deploy D:\a\Sentinel\Sentinel\.script\tests\detectionTemplateSchemaValidation\SkipStrcutreValidationsTemplates.json
Error:  Failed to check valid resource type.
Warning:  Skipping deployment for D:\a\Sentinel\Sentinel\.script\tests\detectionTemplateSchemaValidation\SkipStrcutreValidationsTemplates.json. The file contains resources for content that was not selected for deployment. Please add content type to connection if you want this file to be deployed.
[Info] Try to deploy D:\a\Sentinel\Sentinel\.script\tests\detectionTemplateSchemaValidation\ValidConnectorIds.json
Error:  Failed to check valid resource type.
Warning:  Skipping deployment for D:\a\Sentinel\Sentinel\.script\tests\detectionTemplateSchemaValidation\ValidConnectorIds.json. The file contains resources for content that was not selected for deployment. Please add content type to connection if you want this file to be deployed.
[Info] Try to deploy D:\a\Sentinel\Sentinel\.script\tests\idChangeValidatorTest\SkipIdValidationsTemplates.json
Error:  Failed to check valid resource type.
Warning:  Skipping deployment for D:\a\Sentinel\Sentinel\.script\tests\idChangeValidatorTest\SkipIdValidationsTemplates.json. The file contains resources for content that was not selected for deployment. Please add content type to connection if you want this file to be deployed.
[Info] Try to deploy D:\a\Sentinel\Sentinel\.script\tests\jsonFileValidatorTest\invalidFile.json
ConvertFrom-Json: D:\a\Sentinel\Sentinel\.github\workflows\azure-sentinel-deploy-cc788f67-63ce-42ee-b8[31](https://github.com/ProGHAzure/Sentinel/actions/runs/7728473583/job/21069333760#step:11:32)-1afb617ba[38](https://github.com/ProGHAzure/Sentinel/actions/runs/7728473583/job/21069333760#step:11:39)0.ps1:[48](https://github.com/ProGHAzure/Sentinel/actions/runs/7728473583/job/21069333760#step:11:49)9
Line |
 489 |  …   $templateObject = Get-Content $path | Out-String | ConvertFrom-Json
     |                                                         ~~~~~~~~~~~~~~~~
     | Conversion from JSON failed with error: Unterminated string. Expected delimiter: ". Path 'testInvalidYamlFile',
     | line 5, position 0.
Error: Error: The process 'C:\Program Files\PowerShell\7\pwsh.exe' failed with exit code 1

**Comment by v-sudkharat** [comment]
Hi @ProGHAzure, Thanks for flagging this issue, could you please share more details with us link in which solution or content you are getting issue. Thanks!

**Comment by ProGHAzure** [comment]
Hi, 

Thanks alot, this is the Azure\Sentinel forked to our repository, linked into Sentinel. it fails deployment every time, this is the out of the box fork from the master branch of Azure\Sentinel public

Error code is:

| Conversion from JSON failed with error: Unterminated string. Expected delimiter: ". Path 'testInvalidYamlFile',
| line 5, position 0.
Error: Error: The process 'C:\Program Files\PowerShell\7\pwsh.exe' failed with exit code 1

**Comment by v-sudkharat** [comment]
@ProGHAzure, thank you for response, we will check on this and get back to you by - 06-02-2024. In addition, could you please share your mail id with us, so if required we can connect with you via a call. Thanks!

**Comment by ProGHAzure** [comment]
![image](https://github.com/Azure/Azure-Sentinel/assets/156699025/37389546-327a-4096-9a2b-76b44476ac44)

It already has this in the yamlFileVAlidatortest/invalidFile.yaml

Thanks

**Comment by v-sudkharat** [comment]
@ProGHAzure, Correct, as per the error message - | Conversion from JSON failed with error: Unterminated string. Expected delimiter: ". Path `'testInvalidYamlFile', `
you can add close double quotes by adding `"` in the` testInvalidYamlFile: "validFile ` and update it. 

Old file is having -` testInvalidYamlFile: "validFile `

Update with -        ` testInvalidYamlFile: "validFile" `

And then check the deployment. Please let us know if you still get deployment failure after update that file. 

Thanks!

**Comment by ProGHAzure** [comment]
If i try to edit the file and add "valid file" and commit it fails deployment and reverts with the same message.

What i dont understand is this is just the Azure\Sentinel synced from the master repository with no changes?

![image](https://github.com/Azure/Azure-Sentinel/assets/156699025/dcec3728-caa8-4b4d-9bea-9f9e92f5d4f2)

**Comment by v-sudkharat** [comment]
Hi @ProGHAzure, We have just go through you deployment file, and based on that we have requested to add "" in above mentioned file. 
We have revisited your repo to check that issue but it not available for us - 
![image](https://github.com/Azure/Azure-Sentinel/assets/132428394/03971ec2-5cf1-471f-b72e-93fb93482be1)

Thanks!

**Comment by ProGHAzure** [comment]
Ok I have just invited you thanks. 

It looks like the invalidtestfile.yaml has the "" added now but the deployment still fails


![image](https://github.com/Azure/Azure-Sentinel/assets/156699025/7634c79e-3f49-4bac-9b19-350cffcb63e9)

**Comment by v-sudkharat** [comment]
Hi @ProGHAzure, Thank you for providing repo access. We have made modification in the below file by adding "" in your repo and re-run the job. Currently job is in running stage, please let us know once it done. 
![image](https://github.com/Azure/Azure-Sentinel/assets/132428394/ab4d455f-2fc0-498b-8880-2368f7496fb8)

Thanks!

**Comment by v-sudkharat** [comment]
@ProGHAzure, we have updated another below file, based on the Job-error message- 
![image](https://github.com/Azure/Azure-Sentinel/assets/132428394/27ae38fc-229f-4ee0-b418-6fc9a9aab2f6)

**Comment by ProGHAzure** [comment]
@v-sudkharat , all sync jobs are failing. all I have done was sync the Azure-Sentinel repo I have made no changes or updates to any of the code wo why is this happening? 

![image](https://github.com/Azure/Azure-Sentinel/assets/156699025/949de791-cd7d-4a36-95f0-6c0e39f13aa2)

**Comment by v-sudkharat** [comment]
Hi @ProGHAzure, We have go through your sync Azure-Sentinel Repo and check the deployment file - .github/workflows/azure-sentinel-deploy-4fb7a97e-a915-4de7-92a4-b41a5343e482.ps1 which run the deployment. But when this script executes into the pipeline it will check the standalone yaml file content and deploy it. As of now we have resolve the 2 errors - 1. Expected delimiter: ". Path 'testInvalidYamlFile', and 2. "empty string" error for crowdstrick playbook which is highlighted in this screenshot-https://github.com/Azure/Azure-Sentinel/issues/9876#issuecomment-1926847022
Currently the recent deployment get failed due to it try to deploy the Sample data file which you can see in deployment workflow line no- 8987. 
![image](https://github.com/Azure/Azure-Sentinel/assets/132428394/c3179d07-af58-4a34-873e-1b025a651e5d)

So, could you please let us know is the Sample data folder deployment required or it can be skip? If you skip that folder the script will move to next ARM template deployment files which like in below screenshot - 
![image](https://github.com/Azure/Azure-Sentinel/assets/132428394/bf10c87b-07a5-4d23-aa31-16a2cd9dcdb5)

Thanks!

**Comment by ProGHAzure** [comment]
ah yes please skip it, I dont need that thanks!

**Comment by v-sudkharat** [comment]
Hi @ProGHAzure, We have modified the workflow file to skip the Sample data folder- 
![image](https://github.com/Azure/Azure-Sentinel/assets/132428394/a4ab1ea2-31a3-4439-9896-b3253a0442a1)

just want to check, only Sample data folder you want to skip, and other content want to deploy?

**Comment by ProGHAzure** [comment]
I want to sync in general - playbooks, analytics & automation rules.  sample data can be skipped.

Thanks

**Comment by v-sudkharat** [comment]
@ProGHAzure, can you please update your script/workflow file accordingly. Currently it run in entire repo which also contains the undeployable yaml file. Ex. in sample data folder, due to that the deployment get failure every different steps. 
If you check on below screenshot, the playbook get successfully deployment - 
![image](https://github.com/Azure/Azure-Sentinel/assets/132428394/78ee98d9-f5c7-4d3a-8d2b-91027ceef693)

but it gets failure other unwanted contains- 
![image](https://github.com/Azure/Azure-Sentinel/assets/132428394/adab2a4a-eccc-4b9e-9226-50ff7a153a57)

Thanks!

**Comment by v-muuppugund** [comment]
Hi @ProGHAzure ,Can we have a teams meeting ,could you please share couple of time slots to (v-muuppugund@microsoft.com) as having queries,

**Comment by ProGHAzure** [comment]
Yes thank you I will email you now. thanks

**Comment by v-sudkharat** [comment]
Hi @ProGHAzure, We still working on it, and will update you over GitHub or Chat. Thanks!

**Comment by ProGHAzure** [comment]
Great thank you.

Ian Rawlinson
Information Security Analyst
TimeZone UTC+0


***@***.***<http://www.prodirectsport.com/>
PRO:DIRECT SPORT LTD
Torre House, Shaldon Road,
Newton Abbot, Devon TQ12 4PQ

This e-mail message may contain confidential or legally privileged information and is intended only for the use of the intended recipient(s). Any unauthorized disclosure, dissemination, distribution, copying or the taking of any action in reliance on the information herein is prohibited. E-mails are not secure and cannot be guaranteed to be error free as they can be intercepted, amended, or contain viruses. Anyone who communicates with us by e-mail is deemed to have accepted these risks. Pro:Direct Sport is not responsible for errors or omissions in this message and denies any responsibility for any damage arising from the use of e-mail. Any opinion and other statement contained in this message and any attachment are solely those of the author and do not necessarily represent those of the company.

**Comment by ProGHAzure** [comment]
Hi Sudkharart,

Yes indeed please send a teams call over , afternoon gmt is better between 14:00-5pm ideally.

Thanks

Sent from Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by v-sudkharat** [comment]
Hi @ProGHAzure, we have reach out to our concerned team for this issue, once we receive an update on this from our team, we will update you. 

Thanks!

**Comment by v-sudkharat** [comment]
Hi @ProGHAzure, We have received the update from our concern team, For the deployment the content requires in the ARM template format into the repo, and the Sentinel repo which you have fork is having different formats. 
Sharing the doc for your reference- 
MS doc - https://learn.microsoft.com/en-us/azure/sentinel/ci-cd-custom-deploy?tabs=github
Sample repo - https://github.com/SentinelCICD/RepositoriesSampleContent

Thanks!

**Comment by v-sudkharat** [comment]
Hey @ProGHAzure, Any questions/concern on above comment. If nothing from your end, please let us know, so we can close this issue from GitHub. Thanks!

**Comment by ProGHAzure** [comment]
Yes please  close, I understand how I can sync what I need now.

Thank you for all your assistance.

Ian Rawlinson
Information Security Analyst
TimeZone UTC+0


***@***.***<http://www.prodirectsport.com/>
PRO:DIRECT SPORT LTD
Torre House, Shaldon Road,
Newton Abbot, Devon TQ12 4PQ

This e-mail message may contain confidential or legally privileged information and is intended only for the use of the intended recipient(s). Any unauthorized disclosure, dissemination, distribution, copying or the taking of any action in reliance on the information herein is prohibited. E-mails are not secure and cannot be guaranteed to be error free as they can be intercepted, amended, or contain viruses. Anyone who communicates with us by e-mail is deemed to have accepted these risks. Pro:Direct Sport is not responsible for errors or omissions in this message and denies any responsibility for any damage arising from the use of e-mail. Any opinion and other statement contained in this message and any attachment are solely those of the author and do not necessarily represent those of the company.

**Comment by v-sudkharat** [comment]
@ProGHAzure, Thanks for the confirmation. Closing this issue. If you still need support for this issue, feel free to re-open it any time. Thank you for your co-operation.
