### ISSUE TITLE
AzureActivity still cannot connected to Sentinel

### ISSUE THREAD

**Issue by jeffrywu28** [Azure/Azure-Sentinel#9881]
**Describe the bug**
I follow this tutorial https://github.com/Azure/Azure-Sentinel/blob/master/Solutions/Training/Azure-Sentinel-Training-Lab/Modules/Module-2-Data-Connectors.md#exercise-1-enable-the-azure-activity-connector or i follow the official tutorial below : 
 Launch the Azure Policy Assignment wizard and follow the steps.​

        In the Basics tab, click the button with the three dots under Scope to select your resources assignment scope.
        In the Parameters tab, choose your Microsoft Sentinel workspace from the Log Analytics workspace drop-down list, and leave marked as "True" all the log and metric types you want to ingest.
        To apply the policy on your existing resources, select the Remediation tab and mark the Create a remediation task checkbox.

but it's still cannot connected to Sentinel.

**To Reproduce**
1. Go to 'microsoft sentinel'
2. Click on 'connector'
3. Scroll down to 'azure activity'
4. go to the tutorial : https://github.com/Azure/Azure-Sentinel/blob/master/Solutions/Training/Azure-Sentinel-Training-Lab/Modules/Module-2-Data-Connectors.md#exercise-1-enable-the-azure-activity-connector
5. Follow the tutorial
6. See error

**Expected behavior**
Connected AzureActivity Connector

**Screenshots**
<img width="1434" alt="image" src="https://github.com/Azure/Azure-Sentinel/assets/47622164/8c8d0947-0680-4acd-919b-7a933cb6c7a6">

**Desktop (please complete the following information):**
 - Browser Chrome

**Comment by v-sudkharat** [comment]
Hi @jeffrywu28, Thanks for flagging this issue, we will investigate this issue and get back to you with some updates by 07-02-2024. Thanks!

**Comment by jeffrywu28** [comment]
Hi @v-sudkharat, can i get the info faster? i need it monday

**Comment by v-sudkharat** [comment]
Hi @jeffrywu28, Sure, could you please share the screenshot of what error you get while connecting the connector. In above your shared screenshot the error message not visible. Thanks!

**Comment by v-muuppugund** [comment]
Hi @jeffrywu28 ,Can we connect over teams to understand the error with more details, Could you please share over an email your convenient time, to (v-muuppugund@microsoft.com)

**Comment by v-muuppugund** [comment]
Hi @jeffrywu28 ,Gentle reminder, Can we connect over teams meeting to understand the error with more details, Could you please share over an email your convenient time, to ([v-muuppugund@microsoft.com](mailto:v-muuppugund@microsoft.com))

**Comment by v-muuppugund** [comment]
Hi @jeffrywu28 .Since we have not received a response in the last 5 days, we are closing your issue (https://github.com/Azure/Azure-Sentinel/issues/9881) as per our standard operating procedures. If you still need support for this issue, feel free to re-open at any time. Thank you for your co-operation!
