### ISSUE TITLE
New Mimecast (3.0.1) Function App based data connectors changes Workspace Usage billing from a commitment tier to PAYG significantly increasing costs

### ISSUE THREAD

**Issue by PCNZ** [Azure/Azure-Sentinel#9884]
**Describe the bug**
After deploying any of the new Mimecast data connectors (Mimecast Audit Logs, Mimecast Cloud Gateway MTA, Mimecast Cloud Gateway Targeted Threat Protection or Mimecast Cloud Gateway Threat Intel Regional Feed) the billing tier of the Workspace specified during deployment of the function app is set to PAYG. The deployment overwrites the existing billing tier, where customers have high log volumes and specified a commitment tier this results in a significant increase in costs as commitment tier discounts are removed.
It should not be changing the retention of the workspace at all.
The result is that all tables which are using the default retention period, have logs retention significantly reduced.

This is caused by the "pergb2018" setting in this arm template. This should be removed.
[Azure-Sentinel/Solutions/MimecastAudit/Data Connectors/azuredeploy_MimecastAudit_AzureFunctionApp.json at master · Azure/Azure-Sentinel (github.com)](https://github.com/Azure/Azure-Sentinel/blob/master/Solutions/MimecastAudit/Data%20Connectors/azuredeploy_MimecastAudit_AzureFunctionApp.json)

**To Reproduce**

1. Check/set the log retention on your existing Sentinel Workspace to a commitment tier such as 100GB
2. Install one of the Mimecast contents from the Content Hub ((Mimecast Audit Logs, Mimecast Cloud Gateway MTA, Mimecast Cloud Gateway Targeted Threat Protection or Mimecast Cloud Gateway Threat Intel Regional Feed)
3. Open Data Connectors and the new Mimecast data connector
4. Select "Deploy to Azure" to deploy the function app.
5. In the Custom deployment page select a Sentinel workspace which has a commitment tier such as 100GB
6. Deploy the function app (doesn't require valid Mimecast details at this point as change to workspace commitment tier happens regardless)
7. Check the log commitment tier of your existing Sentinel Workspace, observe it has changed to 30 days.

**Expected behavior**
Sentinel Workspace commitment tier is not changed when a data connector is deployed.

**Screenshots**
Commitment tiers before and after deploying Mimecast function app.
![image](https://github.com/Azure/Azure-Sentinel/assets/68888744/c6dfae1a-6070-4672-88ab-93f20de9d946)

**Desktop (please complete the following information):**
- OS: Windows 11
- Browser Edge
- Version 120.0.2210.133 (Official build) (64-bit)

**Additional context**
Anyone who has deployed this data connector should check and reset their commitment tier to avoid unexpected cost increases.
Please add code checks to all Sentinel pull requests, to prevent future data connectors being deployed which exhibit this behaviour.

**Comment by v-sudkharat** [comment]
Hi @PCNZ, Thanks for flagging this issue, we will investigate this issue and get back to you with some updates by 07-02-2024. Thanks!

**Comment by PCNZ** [comment]
This has been fixed now.
https://github.com/Azure/Azure-Sentinel/commit/d306787ec2b5c5d861769632ea84bc74683f595b
