### ISSUE TITLE
Unwanted Log Analytics Workspace Settings

### ISSUE THREAD

**Issue by JAK-Insight** [Azure/Azure-Sentinel#9891]
It appears that the data connector for all Mimecast deployments is causing an issue where some settings are being set for the log analytics workspace - referenced in the line below but here is a code snippet:

      "apiVersion": "2015-03-20",
      "name": "[variables('workspaceName')]",
      "location": "[parameters('location')]",
      "type": "Microsoft.OperationalInsights/workspaces",
      "properties": {
        "sku": {
          "name": "pergb2018"
        },
        "retentionInDays": 30,
        "features": {
          "legacy": 0,
          "searchVersion": 1,
          "enableLogAccessUsingOnlyResourcePermissions": true
        },
        "publicNetworkAccessForIngestion": "Enabled",
        "publicNetworkAccessForQuery": "Enabled"
      }
    },

This appears to be setting the SKU (which can only be done once every 31 days, and has major financial ramifications should a customer be on a commitment tier getting reset back to pergb2018).  It also seems to be setting some other settings like network access, retention, etc.

https://github.com/Azure/Azure-Sentinel/blob/5498e9af255b4fd442fd0a0d60c48ea6398dbfa3/Solutions/MimecastAudit/Data%20Connectors/azuredeploy_MimecastAudit_AzureFunctionApp.json#L228

**Comment by v-sudkharat** [comment]
Hi @JAK-Insight, We have reviewed the issue and found that the Mimecast solution is partner-supported. Therefore, we are not authorized to make any modifications to it. We kindly request that you raise a support case with Mimecast so they can investigate your case further. Additionally, In workspace you have the option to manually change your tier and get unblock from this issue.
![image](https://github.com/Azure/Azure-Sentinel/assets/132428394/311014c7-5b6c-4a9d-9682-c0320e5e241a)

Closing this issue from GitHub. If you still need support for this issue, feel free to re-open it any time. Thank you for your co-operation.

**Comment by PCNZ** [comment]
@nickshanks347 see also my issue raised for the same
https://github.com/Azure/Azure-Sentinel/issues/9884

Also related
https://github.com/Azure/Azure-Sentinel/issues/9780

**Comment by PCNZ** [comment]
This has been fixed now
https://github.com/Azure/Azure-Sentinel/commit/d306787ec2b5c5d861769632ea84bc74683f595b
