### ISSUE TITLE
Data Connector Exchange Security Insights On-Premise Collector

### ISSUE THREAD

**Issue by NickNicolaou2129** [Azure/Azure-Sentinel#9894]
**Describe the bug**
The data connector "Exchange Security Insights On-Premise Collector" is not collecting any data after installing the collection script, adding the permissions, and setting up a schedule.

**To Reproduce**
1. Go to the data connector page in Sentinel and follow all of the steps.
2. Install the collection script as instructed.
3. Ensure the account has the correct permissions and setup the schedule.

**Schedule is setup**
![image](https://github.com/Azure/Azure-Sentinel/assets/31247621/cd37f511-6eb7-4769-bf50-78635ef26b31)

Script runs successfully
![image](https://github.com/Azure/Azure-Sentinel/assets/31247621/502966d7-e68d-4ea9-b759-2e1929e325a6)

Account has correct permissions:
![image](https://github.com/Azure/Azure-Sentinel/assets/31247621/87902a04-ec0f-472b-bec1-b1f6cdb2cb00)

Exchange Configuration Function has errors:
![image](https://github.com/Azure/Azure-Sentinel/assets/31247621/6eda411d-bd14-4e91-a804-53a3c9ce7dc1)

Exchange Environment List has errors:
![image](https://github.com/Azure/Azure-Sentinel/assets/31247621/3347b412-3ffe-4af1-a79d-10936a53337d)

**Expected behavior**
I expect to see the logs arrive in Azure Sentinel when I search the table name ESIExchangeConfig_CL

**Comment by v-sudkharat** [comment]
Hi @NickNicolaou2129, Thanks for flagging this issue, we will investigate this issue and get back to you with some updates by 12-02-2024. Thanks!

**Comment by v-sudkharat** [comment]
Hi @NickNicolaou2129, Could you please share mail address with us So if required, we connect with you via call and check on issue. Thanks!

**Comment by NickNicolaou2129** [comment]
Email sent to you

**Comment by v-sudkharat** [comment]
@NickNicolaou2129, Thanks!

**Comment by v-muuppugund** [comment]
Hi @NickNicolaou2129 ,Scheduled call with you on 14Feb24,please join the meeting for further trouble shooting.

**Comment by v-muuppugund** [comment]
Hi @NickNicolaou2129 ,As discussed on friday,need more details with logs,could you please share it,if needed we can have a call over  teams with Exchanges server team

**Comment by NickNicolaou2129** [comment]
Hi @v-muuppugund, I sent this to your email last Friday. I will send it again

**Comment by v-muuppugund** [comment]
Hi @NickNicolaou2129 ,The logs shared earlier are the table logs and yesterday in teams call shared the server logs and have trouble shooting session today with server team.

**Comment by v-muuppugund** [comment]
HI @NickNicolaou2129 ,as discussed on last call,scripts and shared the logs ,scripts are executing 5n now,please let me know if any issues.

**Comment by v-sudkharat** [comment]
Hi @NickNicolaou2129, Could you please check on the above comment and let us know if your issue get resolve. Thanks!

**Comment by NickNicolaou2129** [comment]
Resolved
