### ISSUE TITLE
Qualys VM connector - Does not Pull Knowledgebase data, which includes vulnerability details and other attributes like CVE IDs 

### ISSUE THREAD

**Issue by psmaan1** [Azure/Azure-Sentinel#992]
**Is your feature request related to a problem? Please describe.**
The host detections current connector pulls does not have KB data associated with Qualys vulnerability (QID). Qualys indexes all the vulnerabilities as QID and then maintain a separate knowledgebase to have details about the vulnerability e.g. CVE mapping, CVSS score etc.
These details are important ( infact manadory) to put more context around detected vulnerability and prioritize vulnerability remediation.

**Describe the solution you'd like**
There can be a separate script pulling KB data (preferally once every 24 hours), and pushing it into a separate table in Sentinel workspace. KQL can be used to combine information from both tables for generating reports/alerts later.

The logic remain almost same, you just need to point it to a differnent endpoint. Pagination might be required, currently there are 55K+ vulnerabilties in Qualys KB. 

**Describe alternatives you've considered**

**Additional context**

**Comment by preetikr** [comment]
Thanks,  @psmaan1 for the detailed feature request. This would be a scope for a new Qualys KB data connector. We'll add this to our backlog.

**Comment by sarah-yo** [comment]
Added to backlog
