### ISSUE TITLE
Data Connector not picking up log events

### ISSUE THREAD

**Issue by wolyslager** [Azure/Azure-Sentinel#9923]
Need help diagnosing an issue with a Data Connector. I have Solution / Function App [here](https://github.com/Azure/Azure-Sentinel/tree/master/Solutions/AbnormalSecurity) that polls 2 API endpoints every 5 minutes to query for logs. One log type, which occurs very frequently, shows up fine in the Data Connector. The other log type, which is much less frequent, appears as "disconnected" in the Data Connector. Keep in mind that even when I can confirm 100% that the "infrequent" log occurred, it does not populate in the Data Connector page. Strangely, when I modify the WEBSITE_RUN_FROM_PACKAGE to use [this](https://github.com/Azure/Azure-Sentinel/compare/master...wolyslager:Azure-Sentinel:hardcode-dates) PR (which literally only hardcodes the dates for the query params in the API request), then the second log type starts populating just fine. The dates are hardcoded to a time range when the second log type occurred, so the only difference in behavior that I can see is that the frequency of occurrence of the logs is impacting whether or not the tables in Sentinel get populated. Is there any feature in Azure Sentinel that would be causing this? Is there some reason why a (custom) log that is infrequently sent to the Data Connector would not be populated in the log tables?
<img width="465" alt="image" src="https://github.com/Azure/Azure-Sentinel/assets/29632564/7504d931-e75b-484e-a2dd-d166e4bf756a">

cc:  @v-sudkharat  since you were reviewer in the pull requests for this function app :)

**Comment by v-sudkharat** [comment]
Hi @wolyslager, Thanks for flagging this issue, we will investigate this issue and get back to you with some updates by 15-02-2024. Thanks!

**Comment by v-sudkharat** [comment]
Hi @wolyslager, Just want to check few points with you for troubleshoot this issue - 
1. As per your mentioned issue description what I have understand, In the deployed function app you are able to receive the logs for ABNORMAL_THREAT_MESSAGES_CL and ABNORMAL_CASES_CL. But when you check it into data connector page, the connector shows connected only for the ABNORMAL_THREAT_MESSAGES_CL logs and not for the other one? 
2. Ans to your this question - Is there some reason why a (custom) log that is infrequently sent to the Data Connector would not be populated in the log tables? 
    - It may be due to the retention policy, If the infrequent logs are older than the retention period, they will be automatically deleted and will not be visible in the log tables. So, the infrequent logs not older than the retention period. 
    - You need to check the logs when you have received into the LAW. According to the below connectivity criteria query, it will show as connected only the query condition get matched - 
    
![image](https://github.com/Azure/Azure-Sentinel/assets/132428394/4507f48f-50d8-4565-9299-e4fcee5b0581)

Please let us know your feedback on this. Thanks!

**Comment by v-sudkharat** [comment]
Hi @wolyslager, we are waiting for your response on above comment. Thanks!

**Comment by v-sudkharat** [comment]
Hi @wolyslager , Gentle Reminder: We are waiting for your response on this issue. If you still need to keep this issue active, please respond to it in the next 2 days. If we don't receive a response by 20-02-2023 date, we will be closing this issue. 		
Thanks!
