### ISSUE TITLE
Netscape4.8 version is faulting at line 27

### ISSUE THREAD

**Issue by Conduit83-Q** [Azure/Azure-Sentinel#9937]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by v-sudkharat** [comment]
Hi @Conduit83-Q, Thanks for flagging this issue, could you please share more details about the issue, like which solution or content you are facing the issue. Thanks!

**Comment by v-sudkharat** [comment]
Hi @Conduit83-Q, we have checked this solution connector, this solution is supported with Netskope, and we are not authorized to make modification into it. We kindly request you to raise an issue ticket with Netskope support team. 
Sharing the Netskope mail ID and link -
  Link - "https://www.netskope.com/services#support"
Closing this issue from GitHub. If you still need support for this issue, feel free to re-open it any time. Thank you for your co-operation.

**Comment by Conduit83-Q** [comment]
Issue resolved []()
