### ISSUE TITLE
Netskope Connector for Microsoft Sentinel

### ISSUE THREAD

**Issue by eduardmu** [Azure/Azure-Sentinel#9945]
Hello team, has anyone had problems using the sentinel connector for integration with netskope?
I get errors in Azure Function from different tenants when I try to ingest the alerts or audits to sentinel.. this error I receive: 

Exiting from do while loop for logType : audit because of error message as : + Error in method invocation because [System.Management.Automation.PSCustomObject] does not contain a method called 'GetEnumerator

**Comment by v-sudkharat** [comment]
Hi @eduardmu, Thanks for flagging this issue, could you please share more details about this issue? Thanks!

**Comment by eduardmu** [comment]
thanks you ! for you response v-sudkharat
![image](https://github.com/Azure/Azure-Sentinel/assets/98397092/261e25d3-7901-47c8-9d58-7d364d075953)

**Comment by v-sudkharat** [comment]
Hi @eduardmu, we have checked this connector and its solution, this Netskope solution is a partner supported, and we are not authorized to make modification into it. We kindly request you to raise an issue ticket with Netskope support team. So, they can check on it and if required they will make modification into it. 
Sharing the Netskope support link -
Link - "https://www.netskope.com/services#support"

Additionally, we are sharing few points which may help to get unblocked from this issue- 
1. Open the Function App and click on the Environment variables.
2. Then click on the apikey and uri and check it for the correct value has been added - 
![image](https://github.com/Azure/Azure-Sentinel/assets/132428394/4f894016-1435-4fd0-81a1-aa096d9c9790)
3. Once all the values get correctly entered, restart the function app and check the LAW for log ingestion. 

Closing this issue from GitHub. If you still need support for this issue, feel free to re-open it any time. Thank you for your co-operation.
