### ISSUE TITLE
Exchange online connector parser function's parameters are not loading correctly

### ISSUE THREAD

**Issue by kiranIngram08** [Azure/Azure-Sentinel#9948]
<img width="639" alt="Capture" src="https://github.com/Azure/Azure-Sentinel/assets/159431814/04fdd02d-eddc-49df-8b3e-c2b7d7f3c812">

**Comment by v-muuppugund** [comment]
Hi @kiranIngram08 , Thanks for flagging this issue, we will investigate this issue and get back 	to you with some updates by 19Feb24. Thanks!

**Comment by v-muuppugund** [comment]
Hi @kiranIngram08 ,Working on data ingestion and analyzing the date, once done,  will update you.

**Comment by v-muuppugund** [comment]
Hi @kiranIngram08 ,Completed the data analysis and noticed members are missing in raw data ,working on further analysis with data and parser will update you.

**Comment by v-muuppugund** [comment]
Hi @kiranIngram08 ,The following is the status to parser
1.Initial analysis completed
2.Data ingestion completed
3.Changes done for parsing data
4.Working on testing will update you

**Comment by v-muuppugund** [comment]
Hi @kiranIngram08 , The following is the status

Still need some time for testing the parser,will update you once done.

**Comment by v-muuppugund** [comment]
Hi @kiranIngram08 ,As discussed over teams, I have made changes to parser with data shared ingested in to work space and will be sharing the details over an email as confirm over teams chat closing the issue,

Please find below screen shot for reference
![image](https://github.com/Azure/Azure-Sentinel/assets/139563098/14aca6b7-2c74-4f39-8c5e-f1e24a3aa5be)
