### ISSUE TITLE
Ensure all logs from PANW are included in Sentinel dashboard

### ISSUE THREAD

**Issue by arshvishen123** [Azure/Azure-Sentinel#9958]
**Describe the bug**
Logs from Cortex Data Lake are not showing up in the Sentinel dashboard. Palo Alto Networks/Microsoft mutual customer uses the CDL / Sentinel workbook integration for graphs, charts, etc. The queries are only pulling data from firewalls that are forwarding directly to Sentinel as opposed to logs from CDL (which receives logs from FWs and forwards them to Sentinel). 

In that workbook, the logic “where DeviceProduct has ‘PAN-OS’” is used to leverage logs from PANW firewalls. However, it seems that logs coming from CDL have a different DeviceProduct value: ‘LF.” As a result, logs from CDL are not showing up in the workbook.

**To Reproduce**
1. Navigate to Sentinel dashboard (GitHub Repo: https://github.com/Azure/Azure-Sentinel/tree/master/Solutions/PaloAlto-PAN-OS)
2. See that the charts do not pull CDL data 

**Expected behavior**
The data visualized should be from both CDL and firewall data.

**Comment by v-sudkharat** [comment]
Hi @arshvishen123, Thanks for flagging this issue, we will investigate this issue and get back to you with some updates by 20-02-2024. Thanks!

**Comment by v-muuppugund** [comment]
Hi @arshvishen123 Could you please share more details with detailed replication steps ,if needed will have teams meeting on this issue

**Comment by arshvishen123** [comment]
+Pralay Roy ***@***.***>

Hi Pralay, can you please work with this Murali (a representative from
Microsoft) on the Sentinel issue?

Arsh

**Comment by v-muuppugund** [comment]
Hi @arshvishen123 / Pralay,Could you please share convenient time slots for teams meeting to v-muuppugund@microsoft.com,so we can do further trouble shooting on this issue

**Comment by v-sudkharat** [comment]
Hi @arshvishen123, Could you please check on above comment. Thanks!

**Comment by arshvishen123** [comment]
Pralay and Manoj, can you please work with the MSFT team here. This ticket
has been open for a while now.



On Thu, Feb 29, 2024 at 12:34 AM v-sudkharat ***@***.***>
wrote:

> Hi @arshvishen123
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_arshvishen123&d=DwMCaQ&c=V9IgWpI5PvzTw83UyHGVSoW3Uc1MFWe5J8PTfkrzVSo&r=TaMK1c37nC6elB3AYiepetqiFSs_nnrSAGs42zjzreg&m=5HFPGk6nJiKHjaWQRTQbVytyc9kCH-N0GFJtiC4_K6HbLZkH1Wr82MBuXIbq0vPn&s=98qkv-qMDmaUnNrhYOA4q6hXcCoa_dxGttw7cyqf_Nw&e=>,
> Could you please check on above comment. Thanks!
>
> —
> Reply to this email directly, view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_Azure_Azure-2DSentinel_issues_9958-23issuecomment-2D1970653243&d=DwMCaQ&c=V9IgWpI5PvzTw83UyHGVSoW3Uc1MFWe5J8PTfkrzVSo&r=TaMK1c37nC6elB3AYiepetqiFSs_nnrSAGs42zjzreg&m=5HFPGk6nJiKHjaWQRTQbVytyc9kCH-N0GFJtiC4_K6HbLZkH1Wr82MBuXIbq0vPn&s=T5kUFtPkNE8KJ4nJ1aCTSz3IYG2HQxBX_C9vzqUEEbY&e=>,
> or unsubscribe
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_BGFJSBMNLUZN2K5DARM7JFLYV3TZPAVCNFSM6AAAAABDJKOQHKVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMYTSNZQGY2TGMRUGM&d=DwMCaQ&c=V9IgWpI5PvzTw83UyHGVSoW3Uc1MFWe5J8PTfkrzVSo&r=TaMK1c37nC6elB3AYiepetqiFSs_nnrSAGs42zjzreg&m=5HFPGk6nJiKHjaWQRTQbVytyc9kCH-N0GFJtiC4_K6HbLZkH1Wr82MBuXIbq0vPn&s=pFUKRoc-TfPtlzGJOMLLoymrutZ4lZw-T4_fbP14eNY&e=>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>
-- 

Arsh

**Comment by arshvishen123** [comment]
Hi Rajiv,

Please schedule a call on Monday IST to fix this issue.




Thanks & Regards
Pralat

**Comment by arshvishen123** [comment]
Sounds good.

Microsoft Team, could we connect March 11th Monday at 9:30 AM IST / 11 PM
EST? I can send a Zoom invite.

Thanks,

Rajiv Kandiah |  Systems Engineer

Palo Alto Networks  |  Canada

Mobile: 647.891.0506  | *www.paloaltonetworks.com
<https://www.paloaltonetworks.com/>*

<https://www.paloaltonetworks.com/>
<https://www.linkedin.com/company/palo-alto-networks>
<https://www.facebook.com/PaloAltoNetworks/>
<https://twitter.com/PaloAltoNtwks>

The content of this message is the proprietary and confidential property of
Palo Alto Networks, and should be treated as such. If you are not the
intended recipient and have received this message in error, please delete
this message from your computer system and notify me immediately by e-mail.
Any unauthorized use or distribution of the content of this message is
prohibited.

<https://register.paloaltonetworks.com/igniteontourtoronto>

**Comment by arshvishen123** [comment]
+Michael Ong ***@***.***>

Arsh

**Comment by arshvishen123** [comment]
Hi team, was this closed?

Arsh

**Comment by v-sudkharat** [comment]
Hey @arshvishen123, Any update for us? Please let us know if anything required for our side. Thanks!

**Comment by v-muuppugund** [comment]
> Hey @arshvishen123, Any update for us? Please let us know if anything required for our side. Thanks!
Hi @arshvishen123 ,Apologies for delay,PR has been raised ,will update you once pushed

**Comment by v-muuppugund** [comment]
Hi @arshvishen123 , we are closing your issue (https://github.com/Azure/Azure-Sentinel/issues/9958) as PR is raised ,as per our standard operating procedures. If you still need support for this issue, feel free to re-open at any time. Thank you for your co-operation!
