### ISSUE TITLE
Transformation DCR Not Working

### ISSUE THREAD

**Issue by t0neex** [Azure/Azure-Sentinel#9982]
**Describe the bug**
I'm having issue with ingest-time transformation. The below notification appear at the top of Tables page of Log Analytics Workspace. I realized the transformations are not working (e.g Syslog table transformation for CEF messages)
There is not removed transformation DCR but I deleted my current transformation DCR and re-create with different name and created transformations for Syslog and LAQuery tables for a workaround. But it's not working and this notification still there.
**To Reproduce**

**Expected behavior**

**Screenshots**
![image](https://github.com/Azure/Azure-Sentinel/assets/100233276/9adce818-bc0b-477c-b550-bb3f337dd165)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by v-sudkharat** [comment]
Hi @t0neex, Thanks for flagging this issue, we will investigate this issue and get back to you with some updates by 27-02-2023 . Thanks!

**Comment by v-muuppugund** [comment]
Hi @t0neex ,Could you please share more details with replication steps of the issue in detail with screen shots

**Comment by v-sudkharat** [comment]
Hi @t0neex, waiting for your response, on above comment. Thanks!

**Comment by v-sudkharat** [comment]
Hi @t0neex, Gentle Reminder: We are waiting for your response on this issue. If you still need to keep this issue active, please respond to it in the next 2 days. If we don't receive a response by 22-08-2023 date, we will be closing this issue. 		
Thanks!

**Comment by v-sudkharat** [comment]
Hi @t0neex, since we have not received a response in the last 5 days, we are closing your issue #9982 as per our standard operating procedures. If you still need support for this issue, feel free to re-open at any time. Thank you for your co-operation.
