### ISSUE TITLE
Anomaly found in Network Session Traffic Analytics Rule Generating Blank Incidents

### ISSUE THREAD

**Issue by NickNicolaou2129** [Azure/Azure-Sentinel#9983]
**Describe the bug**

**To Reproduce**
When running the "Anomaly found in Network Session Traffic" it does not load any query results, this is because we have so much data coming in that it cannot read it all back. Even if I set the lookback to 1 second, it still does not load any data:
![image](https://github.com/Azure/Azure-Sentinel/assets/31247621/587a982a-4e99-4e9c-a8c7-c1a9ceeca65a)

This results in incidents being created that are empty because the query cannot load the data:
![image](https://github.com/Azure/Azure-Sentinel/assets/31247621/04fd53aa-e3ad-4e8e-9430-306f0061601f)

**Expected behavior**
We expect to see the incident information appear when it is generated.

**Comment by v-sudkharat** [comment]
Hi @NickNicolaou2129, Thanks for flagging this issue, we will investigate this issue and get back to you with some updates by 26-02-2024. Thanks!

**Comment by v-sudkharat** [comment]
Hi @NickNicolaou2129, Could you please run below shared query once and check for the result - [query.txt](https://github.com/Azure/Azure-Sentinel/files/14402557/query.txt)
If query not showing any result, then please check the data availability into the table - `NetworkCustomAnalytics_protocol_CL`

Thanks!

**Comment by v-sudkharat** [comment]
Hi @NickNicolaou2129, We are waiting for your response from on above comment. Thanks!

**Comment by NickNicolaou2129** [comment]
Hi @v-sudkharat NetworkCustomAnalytics_protocol_CL does not refer to a know table:
![image](https://github.com/Azure/Azure-Sentinel/assets/31247621/88d76060-b2d7-40a4-a1a5-f2950bdf78ff)

**Comment by NickNicolaou2129** [comment]
Hi,

Yes it is company, otherwise the incident would not trigger in the first place.

Many thanks,
Nicholas

**Comment by v-sudkharat** [comment]
@NickNicolaou2129, will check on it and if required will schedule a call for it. Thanks!

**Comment by v-sudkharat** [comment]
Hi @NickNicolaou2129, Can we have a call? We need few more details about the incident. Thanks!

**Comment by v-sudkharat** [comment]
Hi @NickNicolaou2129, Hope you're doing good. As you have raised the support case for this same issue, our team is working on your ticket. So could you please let us know can we close this issue from GitHub? as other team is checking on this. Thanks!

**Comment by NickNicolaou2129** [comment]
Hi, I would like to keep this GitHub ticket. I have just sent you the documents you requested from me in yesterdays call. Let me know if you have any further news, thanks!

**Comment by v-sudkharat** [comment]
Hey @NickNicolaou2129, Our support team still working on this issue and will communicate with you for required details. Thanks!

**Comment by v-muuppugund** [comment]
Hi @NickNicolaou2129 ,As the ICM is raised for this issue and so this is duplicate issue and Please let me any work needs to be done will reopen it and closing as per process and will discuss in detail in tomorrow call

**Comment by NickNicolaou2129** [comment]
Yes, there is too much data in that table for the query to process, causing it to generate blank incidents.

Try running the analytics rule in the logs section, gradually changing it to optimise the query. You can check the CPU in the query details section after it finishes running.

**Comment by fkh090** [comment]
The Same Problem here. Did anyone find the Solution?

**Comment by Dalbrink** [comment]
Hi,

old bug but still present. If the scheduled rule has to create an Incident the Incident is not enriched properly and a error message is written in Sentinel Health:

<img width="1474" height="110" alt="Image" src="https://github.com/user-attachments/assets/b527a2ff-5821-455a-8a82-6d836bb3a4d3" />
