### ISSUE TITLE
M365 analytic rule "malicious inbox rule" yields no data in parameters column AND operation "New-InboxRule" does not work

### ISSUE THREAD

**Issue by jackluz84** [Azure/Azure-Sentinel#9988]
When testing the built in analytic rule from the M365 sentinel connector, I have determined I'm getting unexpected behavior:

1. where Operation =~ "New-InboxRule" does not work.  the operation column is now apparently "UpdateInboxRules"
2. Parameters column has no data

**To Reproduce**
1. Mimic a malicious inbox rule by creating a rule that will move email from a sender into deleted items
2. query OfficeActivity table
3. observe operation=New-InboxRule does not work and observe Parameters does not contain data.

**Expected behavior**
I expect the built in query to project data in Parameters column

let Keywords = dynamic(["helpdesk", " alert", " suspicious", "fake", "malicious", "phishing", "spam", "do not click", "do not open", "hijacked", "Fatal"]);
OfficeActivity
| where OfficeWorkload =~ "Exchange" 
| where Operation =~ "New-InboxRule" and (ResultStatus =~ "True" or ResultStatus =~ "Succeeded")
| where Parameters has "Deleted Items" or Parameters has "Junk Email"  or Parameters has "DeleteMessage"
| extend Events=todynamic(Parameters)
| parse Events  with * "SubjectContainsWords" SubjectContainsWords '}'*
| parse Events  with * "BodyContainsWords" BodyContainsWords '}'*
| parse Events  with * "SubjectOrBodyContainsWords" SubjectOrBodyContainsWords '}'*
| where SubjectContainsWords has_any (Keywords)
 or BodyContainsWords has_any (Keywords)
 or SubjectOrBodyContainsWords has_any (Keywords)
| extend ClientIPAddress = case( ClientIP has ".", tostring(split(ClientIP,":")[0]), ClientIP has "[", tostring(trim_start(@'[[]',tostring(split(ClientIP,"]")[0]))), ClientIP )
| extend Keyword = iff(isnotempty(SubjectContainsWords), SubjectContainsWords, (iff(isnotempty(BodyContainsWords),BodyContainsWords,SubjectOrBodyContainsWords )))
| extend RuleDetail = case(OfficeObjectId contains '/' , tostring(split(OfficeObjectId, '/')[-1]) , tostring(split(OfficeObjectId, '\\')[-1]))
| summarize count(), StartTimeUtc = min(TimeGenerated), EndTimeUtc = max(TimeGenerated) by  Operation, UserId, ClientIPAddress, ResultStatus, Keyword, OriginatingServer, OfficeObjectId, RuleDetail
| extend AccountName = tostring(split(UserId, "@")[0]), AccountUPNSuffix = tostring(split(UserId, "@")[1])

**Screenshots**
![image](https://github.com/Azure/Azure-Sentinel/assets/147873075/8a466a84-9c55-4292-a637-447f3a7964d9)

OTHER USEFUL INFO:
OfficeActivity

| where isnotempty(Parameters)

This captured several operations of "Set-ConditionalAccessPolicy" from some other irrelevant activity from earlier in the day

**Comment by v-sudkharat** [comment]
Hi @jackluz84, Thanks for flagging this issue, we will investigate this issue and get back to you with some updates by 23-02-2024. Thanks!

**Comment by jackluz84** [comment]
Thank you for the update, I look forward to hearing back!

**Comment by v-sudkharat** [comment]
Hi @jackluz84, We have checked this issue from our end. As per your above-mentioned issue description we have checked the Columns "Operations" and "Parameter" in our workspace, and we can see this column contains certain values into it. Sharing the screenshot for reference -
![image](https://github.com/Azure/Azure-Sentinel/assets/132428394/7545a239-f684-43e9-b54a-b6315860f60f)

Coud you please run the below query and check whether in OfficeActivity table is having the data "New-InboxRule" in Operation column and satisfying the condition for it - (ResultStatus =~ "True" or ResultStatus =~ "Succeeded").

You can run the below query to validate the data - 
```
 let Keywords = dynamic(["helpdesk", " alert", " suspicious", "fake", "malicious", "phishing", "spam", "do not click", "do not open", "hijacked", "Fatal"]);
 OfficeActivity
 | where OfficeWorkload =~ "Exchange" 
 | where Operation =~ "New-InboxRule" and (ResultStatus =~ "True" or ResultStatus =~ "Succeeded")
 | project Operation, Parameters, ResultStatus 
```
And also set the Time Range as per your data availability- 
![image](https://github.com/Azure/Azure-Sentinel/assets/132428394/c778ed50-3e98-4b3a-a770-fa08d6e6e6dd)

IF both the columns not showing the expected data, then please verify the operations are executed correctly in the Inbox mail rule.
Please let us know if this helps you. Thanks!

**Comment by jackluz84** [comment]
What I am trying to say is...This analytic rule is looking for "New-InboxRule" operations. This is not working because:
1. See screenshot below. When I create an Inbox Rule in my outlook client, the correlated OfficeActivity output of that operation is showing as "UpdateInboxRules" and NOT "New-InboxRule"
![image](https://github.com/Azure/Azure-Sentinel/assets/147873075/5cbb6741-6c85-4c16-a3c8-35dc1b045325)

2. The operation UupdateInboxRules does not have any parameters to look for useful information. This analytic rule's key functionality relies on the parameters column as well. I am observing there are no parameters returning in the UpdateInboxRules as you can see in the screenshot as well.

3. As I was writing this response, I wanted to provide as much data as I could and see if I observe different behavior using outlook on the web, and Indeed I do! See screenshot below. If i create the rule on outlook on the web we see the New-InboxRule operation. When performing on the Windows outlook client, it will do the UpdateInboxRules operation. Interesting. Well I guess false alarm then? Sorry for wasting your time.

![image](https://github.com/Azure/Azure-Sentinel/assets/147873075/4b2b6d49-45c0-40e8-8e9f-027bba4664a2)

**Comment by v-sudkharat** [comment]
Hi @jackluz84, we really appreciate your observation which you have shared with us. we will forward this with our respective team so they can check on this and enhance this analytic rule. 
So, could you please let us know anything we can help you? if not, can we close this issue. Thanks!

**Comment by jackluz84** [comment]
You may close out the issue, thank you.

**Comment by v-sudkharat** [comment]
Hi @urajat, Thank you for your confirmation. Closing this issue. If you still need support for this issue, feel free to re-open it any time. Thank you for your co-operation.
