### ISSUE TITLE
Exchange Security Insights Online Parser Does not Pick Up All Data

### ISSUE THREAD

**Issue by NickNicolaou2129** [Azure/Azure-Sentinel#9994]
**Describe the bug**
Hi, the parse for the Exchange Security Insights Online connector misses out valuable fields

**To Reproduce**
1. Go to LAW and open Logs
2. Search the table ESIExchangeOnlineConfig_CL
3. View the logs in RawData column, we see that the logs within here are not parsed:
ESIExchangeOnlineConfig_CL

Example:
{"RoleGroup":"TenantAdmins_af308","Identity":"VALUE","DisplayName":"Surname Name (VALUE)","RecipientType":"UserMailbox","WhenCreated":"\/Date(1591385292000)\/","WhenChanged":"\/Date(1708331006000)\/"}

I have already sent an export that you can analyse the raw data from to parse what is not already parsed. 

**Expected behavior**
All data in the RAW data column should be correctly parsed and presented as a column in the log results.

**Comment by v-muuppugund** [comment]
Hi @NickNicolaou2129 , Thanks for flagging this issue, we will investigate this issue and get back to you with some updates by 27Feb2024. Thanks!

**Comment by v-muuppugund** [comment]
Hi @NickNicolaou2129 ,Working on  data ingestion ,will post frequent update over teams the status and will update you

**Comment by v-muuppugund** [comment]
Hi @NickNicolaou2129 ,The following is the status

- Completed initial analysis
- Data ingestion completed
- Working on changes
- Once done will post updates

**Comment by v-muuppugund** [comment]
Hi @NickNicolaou2129 ,The following is the status,will update you

- Completed the changes
- Working on testing

**Comment by NickNicolaou2129** [comment]
Hi @v-muuppugund , any news?

**Comment by v-muuppugund** [comment]
Hi @NickNicolaou2129 ,Still need some more time for testing,will post updates by next week

**Comment by v-muuppugund** [comment]
Hi @NickNicolaou2129 ,Will be sharing parser today eod ,we can have a call for the discussion

**Comment by v-muuppugund** [comment]
> Hi @NickNicolaou2129 ,Will be sharing parser today eod ,we can have a call for the discussion

Hi @NickNicolaou2129 ,Shared the parser over an email and let me know if you have any issues.

**Comment by v-muuppugund** [comment]
Hi @NickNicolaou2129 ,As discussed yesterday,,working on PR for these changes,will update you

**Comment by v-muuppugund** [comment]
Hi @NickNicolaou2129, we have raised the PR with the enhancements. The changes will be reflected once the PR is merged.
PR link -
https://github.com/Azure/Azure-Sentinel/issues/10020

Thank you for your cooperation.
